discourse/discourse

.git-blame-ignore-revs
=> Hide imports commit from blame

app/controllers/bootstrap_controller.rb
This allows 3rd party clients (such as Ember CLI) to run plugins and
their tests.
=> FEATURE: Add plugin js / plugin test js to bootstrap.json

app/assets/javascripts/discourse/app/controllers/preferences/users.js, app/assets/javascripts/discourse/tests/acceptance/preferences-test.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js, config/site_settings.yml
based on the current user trust level and the appropriate site setting.
Follow-up to 0ec62358
=> FIX: show/hide ignored users preferences

.git-blame-ignore-revs
=> DEV: Hide 'DEV: Sort imports alphabetically (#11382)' from blame

app/assets/javascripts/discourse/app/components/topic-timer-info.js, app/jobs/regular/toggle_topic_closed.rb, app/models/topic.rb, app/models/topic_timer.rb, app/services/topic_status_updater.rb, config/locales/client.en.yml, lib/post_creator.rb, spec/components/post_creator_spec.rb
New TopicTimer to silently close topic - similar to whisper. It will be used by the `discourse-solved` plugin
Meta: https://meta.discourse.org/t/allow-auto-close-for-solved-to-do-so-silently/169300
=> FEATURE: silently close topic

app/controllers/users/omniauth_callbacks_controller.rb
It also removes the unused `provider` variable and stops Discourse from redirecting to /login after a login.
=> DEV: Make it easier to customize omniauth login complete handler in plugins

app/assets/javascripts/discourse/app/controllers/review-index.js, app/assets/javascripts/discourse/app/routes/review-index.js, app/assets/javascripts/discourse/app/templates/review-index.hbs, app/controllers/reviewables_controller.rb, app/models/reviewable.rb, config/locales/client.en.yml, spec/models/reviewable_spec.rb
New reviewable filter to only display reviewables handled by a specific user.
=> FEATURE: Reviewed by filter.

Gemfile.lock
Update Gemfile.lock to pull in onebox changes
=> DEV: update onebox gem

app/models/emoji.rb, spec/components/pretty_text_spec.rb
https://emojipedia.org/slightly-smiling-face/
https://emojipedia.org/smiling-face/
=> FIX: do not replace smiling_face by slight_smile

app/assets/javascripts/discourse/app/templates/components/topic-list.hbs
Similar to before-topic-list-body plugin outlet that can be found above.
=> FEATURE: Add after-topic-list-body plugin-outlet

plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/03-colors.hbs, plugins/styleguide/assets/stylesheets/colors.scss
=> DEV: Add header colors to styleguide

app/assets/stylesheets/desktop/login.scss
=> UX: Fix invite checkbox width issue

app/assets/stylesheets/common/admin/users.scss
=> UX: makes sk components full width on users admin page

app/assets/javascripts/discourse/app/templates/full-page-search.hbs, app/assets/stylesheets/common/base/search.scss
This reverts commit a19a3adf9e7688c7b0dd9691a0c1fbf851dd5cd3.
Need to look into failing tests.
=> Revert "DEV: no need to iterate through each tag for rendering"

app/assets/javascripts/select-kit/addon/components/topic-notifications-options.js
=> DEV: Remove duplicate (and deprecated) SK option

app/models/watched_word.rb
This is useful for more complex regex watched words
https://meta.discourse.org/t/166249
=> FEATURE: Increase maximum watched word length from 50 to 100 chars

app/assets/javascripts/discourse/app/components/composer-body.js
=> FIX: Prevent usage of `composer-action-undefined` CSS class

config/locales/client.en.yml
=> FIX: Missing translation

app/models/user.rb, app/services/user_merger.rb
=> FIX: Prevent error when primary email is missing

app/assets/javascripts/admin/addon/models/admin-user.js, app/controllers/admin/users_controller.rb, app/jobs/regular/merge_user.rb, app/services/user_merger.rb, config/locales/client.en.yml, config/locales/server.en.yml, spec/requests/admin/users_controller_spec.rb
Currently, the admin page is timing out while merging the users with lots of posts.
=> PERF: run user merging task in a background job.

app/assets/stylesheets/common/components/footer-nav.scss
Otherwise it is hidden below the footer nav.
=> DEV: Fix position of filtered replies notice on DiscourseHub

app/models/theme_field.rb, app/models/topic.rb, lib/topic_query.rb
This is a follow up to comment under this PR https://github.com/discourse/discourse/pull/11441
Sam suggested using sql_fragment instead of sanitize_sql_array
=> FIX: use sql_fragment instead of sanitize_sql_array

app/assets/javascripts/discourse/app/components/group-post.js, app/assets/javascripts/discourse/app/templates/group-activity-posts.hbs, app/models/group.rb, app/serializers/group_post_serializer.rb, spec/requests/groups_controller_spec.rb
Now they are included, with the correct color applied.
=> FIX: Posts with Staff Colors were excluded from the group activity

app/controllers/admin/users_controller.rb, spec/requests/admin/users_controller_spec.rb
=> FEATURE: Allow IP anonymization via admin user controller API

app/assets/javascripts/discourse/app/models/post-stream.js
=> DEV: Trigger events when filtering replies

app/assets/javascripts/discourse/app/models/post-stream.js, app/assets/javascripts/discourse/app/widgets/post-gap.js, app/assets/javascripts/discourse/app/widgets/post-stream.js, app/assets/javascripts/discourse/app/widgets/post.js, app/assets/javascripts/discourse/tests/unit/models/post-stream-test.js
And passes postID to "filter-replies" event for better consistency.
=> DEV: More events for filtered replies

app/models/watched_word.rb
- Have doubled the size of the Watched Words Per Action Limit to accommodate additional watched words
- Hate speech should never be tolerated and 1000 watched words does not allow for enough coverage
- Can you point me to Resource for how to: _All pull requests should have tests (rspec in Ruby, qunit in Javascript)_
Offensive/Profane Word List
Description: A list of 1,300+ English terms that could be found offensive. The list contains some words that many people won't find offensive, but it's a good start for anybody wanting to block offensive or profane terms on their Site.
File Size: 11Kb
Tags: Bad words, offensive words, profane words, profanity.
https://www.cs.cmu.edu/~biglou/resources/
https://www.cs.cmu.edu/~biglou/resources/bad-words.txt
=> FIX: increase max words per watched word to 2000

Gemfile.lock, spec/support/sidekiq_helpers.rb
I had to update our sidekiq helper too because the latest release has a higher precision in ruby.
=> Upgrade oj gem

lib/search.rb
This commit allows discourse-assign plugin to show assigned users on search result topic list.
Accompanying plugin PR: https://github.com/discourse/discourse-assign/pull/123
=> FEATURE: allow plugins to preload custom data on search

app/assets/javascripts/discourse/app/components/site-header.js, app/assets/javascripts/discourse/app/mixins/rerender-on-do-not-disturb-change.js
=> DEV: Move rerender on 'do not disturb' change to mixin

app/assets/javascripts/discourse/tests/unit/lib/sanitizer-test.js, app/assets/javascripts/pretty-text/addon/allow-lister.js, app/assets/javascripts/pretty-text/addon/sanitizer.js
=> FIX: Ensure video tags with autoplay are muted

app/models/optimized_image.rb, config/site_settings.yml
=> FEATURE: Adds support for the WEBP image format

app/models/global_setting.rb, config/discourse_defaults.conf, config/initializers/400-deprecations.rb, lib/discourse.rb, spec/models/global_setting_spec.rb
Introduce Redis `replica` config and deprecate `slave`
=> FIX: use Redis replica host and port

lib/discourse_tagging.rb, spec/components/discourse_tagging_spec.rb
=> FIX: Disallow zero-width and other non-printing characters in tags

app/assets/javascripts/discourse/app/templates/group/manage/tags.hbs
=> DEV: Add "before-manage-group-tags" plugin outlet

config/locales/server.en.yml
simplify copy slightly for new post / topic advice panel
=> simplify copy slightly for new post / topic panel

Gemfile.lock
- do not show title only oneboxes
=> Bump onebox gem to 2.2.0

Gemfile.lock
- allow oneboxes with title and image
=> Bump onebox gem to 2.2.1

config/locales/server.en.yml
add some detail to the TL2 congratulatory PM
=> enhance TL2 congratulations PM

lib/discourse_plugin_registry.rb
=> DEV: Deprecate SCSS variable overrides in plugins

Gemfile, Gemfile.lock, config/initializers/006-mini_profiler.rb
Included support for flamegraphs using speedscope!
=> DEV: update rack-mini-profiler

Gemfile.lock
see: https://github.com/discourse/discourse/commit/39ba1ae2b52fbb4ec03df390a4516e2b2414c315
=> DEV: add support for macOS in bundler

plugins/discourse-local-dates/assets/javascripts/lib/local-date-builder.js.es6, plugins/discourse-local-dates/test/javascripts/lib/local-date-builder-test.js.es6
=> FIX: ensures recurring works when setting a start date in future

app/assets/javascripts/discourse/app/templates/mobile/components/mobile-nav.hbs, app/assets/stylesheets/mobile/discourse.scss, app/assets/stylesheets/mobile/user.scss
=> UX: text overflow user-{primary,secondary}-navigation

app/assets/javascripts/discourse/app/lib/formatter.js, app/assets/javascripts/discourse/app/widgets/do-not-disturb.js, app/assets/javascripts/discourse/app/widgets/quick-access-notifications.js, app/assets/javascripts/discourse/app/widgets/quick-access-panel.js, app/assets/javascripts/discourse/app/widgets/quick-access-profile.js, app/assets/javascripts/discourse/tests/acceptance/do-not-disturb-test.js, app/assets/javascripts/discourse/tests/unit/lib/formatter-test.js, app/assets/stylesheets/common/base/discourse.scss, lib/svg_sprite/svg_sprite.rb
=> UX: Move do not disturb to profile panel

app/assets/javascripts/discourse/app/lib/autocomplete.js
=> DEV: uses popper for autocomplete

config/locales/server.en.yml, spec/requests/email_controller_spec.rb
very minor copyedit of help text for unsubscribing
=> Update server.en.yml -- minor copyedit

config/locales/server.en.yml
.. as it is no longer applicable for the most part
=> remove anon download attachment warning

docs/INSTALL.md
This matches what we are using in the bundled image
=> Update minimum required software versions

app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js, app/assets/javascripts/discourse/tests/acceptance/category-new-test.js, app/assets/javascripts/discourse/tests/fixtures/category-fixtures.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js
See https://meta.discourse.org/t/url-doesnt-update-when-creating-a-new-category/173307
=> UX: transition to edit URL when adding a category

app/assets/javascripts/select-kit/addon/components/multi-select.js, app/assets/javascripts/select-kit/addon/components/multi-select/multi-select-filter.js, app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-filter.js, app/assets/javascripts/select-kit/addon/mixins/utils.js, app/assets/javascripts/select-kit/addon/templates/components/select-kit/select-kit-filter.hbs
https://user-images.githubusercontent.com/339945/103760015-cfc08200-5014-11eb-984f-ab8ed781e971.mp4
=> UX: allows to copy/paste a list of | separated values in sk

plugins/discourse-local-dates/assets/javascripts/lib/date-with-zone-helper.js.es6, plugins/discourse-local-dates/assets/javascripts/lib/local-date-builder.js.es6, plugins/discourse-local-dates/test/javascripts/lib/date-with-zone-helper-test.js.es6, plugins/discourse-local-dates/test/javascripts/lib/local-date-builder-test.js.es6
=> FIX: recurring was not working for some cases (eg: hours and unit > 1)

app/models/user.rb, spec/models/user_spec.rb
=> FEATURE: Use the site's small logo as the system user's avatar.

app/controllers/posts_controller.rb, config/locales/server.en.yml, lib/guardian/post_guardian.rb, spec/components/guardian_spec.rb, spec/requests/posts_controller_spec.rb
https://meta.discourse.org/t/restoring-deleted-messages/173647/6?u=techapj
=> FEATURE: allow disabling self-deletions of posts

spec/integrity/i18n_spec.rb
Those fail on the buggy i18n release (1.8.6) and pass on 1.8.5, 1.8.7 (the revert release), and with the second stab at thread safety on the current master (https://github.com/ruby-i18n/i18n/commit/63a79cb929770629e20f0645676065025c599662)
=> DEV: Add i18n fallback specs

app/assets/javascripts/discourse/app/templates/groups/index.hbs
Adding this for an Enterprise customer's theme
=> FEATURE: Add before-groups-index-container outlet

app/assets/javascripts/discourse/app/lib/link-hashtags.js, app/assets/javascripts/discourse/tests/acceptance/hashtags-test.js, app/models/category.rb, db/migrate/20201117212328_set_category_slug_to_lower.rb, lib/slug.rb, spec/components/concern/category_hashtag_spec.rb, spec/models/category_spec.rb
Administrators could specify category slug with upper case characters.
=> FIX: Make category slugs lowercase

script/import_scripts/vanilla_body_parser.rb, script/import_scripts/vanilla_mysql.rb, spec/script/import_scripts/vanilla_body_parser_spec.rb
- import groups and group users
- import uploads/attachments
- improved code tag parsing
- improved text formatting
- mark topics as solved
=> Improve Vanilla import script.

app/controllers/admin/groups_controller.rb, config/locales/client.en.yml, spec/requests/admin/groups_controller_spec.rb
We include the group "name" and "granted_trust_level" attributes.
=> FEATURE: Log when a group is deleted.

app/assets/javascripts/discourse-shims.js, app/assets/javascripts/discourse/app/index.html, app/assets/javascripts/discourse/app/initializers/keyboard-shortcuts.js, app/assets/javascripts/discourse/config/environment.js, app/assets/javascripts/discourse/config/optional-features.json, app/assets/javascripts/discourse/config/targets.js
These changes should all be safe to live in master even if they're not
being used yet.
=> Sync up master with Ember CLI branch where possible

app/assets/javascripts/discourse/app/templates/components/reviewable-topic-link.hbs
=> FIX: Render topic fancy title in review queue

script/import_scripts/base.rb, script/import_scripts/base/lookup_container.rb, script/import_scripts/phpbb3/database/database.rb, script/import_scripts/phpbb3/database/database_3_0.rb, script/import_scripts/phpbb3/importer.rb, script/import_scripts/phpbb3/importers/bookmark_importer.rb, script/import_scripts/phpbb3/importers/category_importer.rb, script/import_scripts/phpbb3/importers/importer_factory.rb, script/import_scripts/phpbb3/importers/message_importer.rb, script/import_scripts/phpbb3/importers/permalink_importer.rb, script/import_scripts/phpbb3/importers/poll_importer.rb, script/import_scripts/phpbb3/importers/post_importer.rb, script/import_scripts/phpbb3/importers/user_importer.rb, script/import_scripts/phpbb3/settings.yml, script/import_scripts/phpbb3/support/bbcode/markdown_node.rb, script/import_scripts/phpbb3/support/bbcode/xml_to_markdown.rb, script/import_scripts/phpbb3/support/settings.rb, script/import_scripts/phpbb3/support/smiley_processor.rb, script/import_scripts/phpbb3/support/text_processor.rb, spec/script/import_scripts/phpbb3/support/bbcode/xml_to_markdown_spec.rb
Support for phpBB 3.2.x, attachments, better smileys, etc.
=> Improvements to phpBB3 import script

app/assets/stylesheets/common/base/menu-panel.scss
=> UX: Ellipsis hamburger menu link text when overflowing

app/assets/javascripts/admin/addon/templates/customize-themes-show.hbs, app/controllers/admin/themes_controller.rb, spec/requests/admin/themes_controller_spec.rb
=> Prevent users from converting the default theme to a component

app/assets/javascripts/discourse/app/pre-initializers/inject-discourse-objects.js
=> FIX: TopicTrackingState was initialized after Site

spec/script/import_scripts/vanilla_body_parser_spec.rb
in reference to: https://github.com/discourse/discourse/commit/bd7cbcd8f8dbff84efab67bef196a05f41c9feda
=> DEV: add specs for Vanilla import script improvements

app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js, app/assets/javascripts/pretty-text/engines/discourse-markdown/typographer-arrows.js
=> FEATURE: Replace single dash arrows when the typographer is enabled.

app/assets/javascripts/discourse/app/templates/preferences/interface.hbs, app/assets/javascripts/discourse/tests/integration/components/select-kit/single-select-test.js, app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js, app/assets/javascripts/select-kit/addon/components/selected-name.js, app/assets/javascripts/select-kit/addon/templates/components/selected-name.hbs
=> DEV: adds support for lang attribute in select-kit

lib/tasks/uploads.rake
=> DEV: Add a note to S3 migration task

app/assets/stylesheets/common/base/tagging.scss, app/assets/stylesheets/common/select-kit/mini-tag-chooser.scss, app/assets/stylesheets/common/select-kit/select-kit.scss, app/assets/stylesheets/common/select-kit/tag-chooser.scss
=> UX: Use uniform style for tag counts

app/services/badge_granter.rb, spec/services/badge_granter_spec.rb
=> FIX: Check for user presence before granting badge

app/assets/javascripts/discourse/app/templates/modal/feature-topic.hbs, app/assets/javascripts/discourse/app/templates/tags/index.hbs, app/assets/javascripts/discourse/ember-cli-build.js, app/assets/javascripts/discourse/package.json, app/assets/javascripts/discourse/public/assets/scripts/discourse-boot.js, app/assets/javascripts/discourse/testem.js
We are getting closer to parity now. These changes should not affect
master but help keep things in sync.
=> Sync up master and Ember CLI branches again

app/assets/javascripts/discourse/app/templates/components/google-search.hbs, app/assets/javascripts/discourse/app/templates/full-page-search.hbs, app/assets/javascripts/discourse/app/widgets/search-menu-controls.js, config/locales/client.en.yml
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search#search_form_labels_and_accessibility
=> A11Y: Add aria-labels to search inputs and search button

app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js, app/assets/javascripts/discourse/app/pre-initializers/inject-discourse-objects.js, app/assets/javascripts/discourse/tests/unit/services/current-user-test.js
This is a regression from recent Ember-CLI merging stuff.
=> FIX: currentUser was missing `appEvents`

app/assets/javascripts/admin/addon/controllers/admin-user-index.js, app/assets/javascripts/admin/addon/controllers/modals/admin-delete-user-posts-progress.js, app/assets/javascripts/admin/addon/controllers/modals/admin-merge-users-progress.js, app/assets/javascripts/admin/addon/models/admin-user.js, app/assets/javascripts/admin/addon/models/backup.js, app/assets/javascripts/admin/addon/routes/admin-backups-index.js, app/assets/javascripts/admin/addon/routes/admin-backups.js, app/assets/javascripts/admin/addon/templates/modal/admin-delete-user-posts-progress.hbs, app/assets/javascripts/admin/addon/templates/modal/admin-merge-users-progress.hbs, app/assets/stylesheets/common/base/modal.scss, config/locales/client.en.yml
Fix for `admin-user.js` and `backup.js` models.
=> FIX: remove rendering UX from ember models

lib/post_revisor.rb
This can be used to add to the message notifying the client about the
update.
=> DEV: Add DiscourseEvent before post changes are published

config/locales/names.yml
Absolutely no need for "language" prefix…
=> FIX: Polish lang label

app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-body.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-filter.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js, app/assets/javascripts/select-kit/addon/components/select-kit/single-select-header.js, app/assets/javascripts/select-kit/addon/templates/components/selected-name.hbs
https://www.w3.org/TR/wai-aria-practices-1.1/#wai-aria-roles-states-and-properties-6
=> DEV: implements combobox roles for select-kit

app/assets/javascripts/discourse/app/templates/components/invite-link-panel.hbs
=> FIX: Allow max_redemptions_limit to be 1

app/assets/javascripts/discourse/tests/fixtures/about.js, app/assets/javascripts/discourse/tests/fixtures/user-fixtures.js, app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/dropdown-select-box-test.js, app/assets/javascripts/discourse/tests/test_helper.js, app/assets/javascripts/locales/en_GB.js.erb, app/assets/javascripts/locales/en_US.js.erb, app/assets/javascripts/wizard/test/test_helper.js, app/models/locale_site_setting.rb, config/locales/client.en.yml, config/locales/client.en_GB.yml, config/locales/names.yml, config/locales/server.en.yml, config/locales/server.en_GB.yml, config/site_settings.yml, db/migrate/20210120125607_rename_english_locale.rb, lib/js_locale_helper.rb, lib/site_settings/defaults_provider.rb, spec/components/freedom_patches/translate_accelerator_spec.rb, spec/components/js_locale_helper_spec.rb, spec/components/site_setting_extension_spec.rb, spec/lib/i18n/fallback_locale_list_spec.rb, spec/lib/search_spec.rb, spec/mailers/user_notifications_spec.rb, spec/models/locale_site_setting_spec.rb, spec/multisite/site_settings_spec.rb, spec/requests/extra_locales_controller_spec.rb, spec/services/badge_granter_spec.rb
* "English" gets renamed into "English (US)"
* "English (UK)" replaces "English"
@discourse-translator-bot keep_translations_and_approvals
=> FEATURE: Add English (UK) as locale

app/models/imap_sync_log.rb, app/models/incoming_email.rb, app/models/post.rb, lib/demon/email_sync.rb, lib/imap/sync.rb, spec/jobs/cleanup_imap_sync_log_spec.rb
Improvements to make console access to IncomingEmail more pleasant, and stopping certain IMAP logs from landing in the DB because they just create too much noise,
=> DEV: IMAP debugging improvements

README.md
=> It's 2021 🥳

app/models/incoming_email.rb, db/migrate/20210121001720_change_incoming_email_created_at_null.rb, lib/email/receiver.rb, spec/fabricators/incoming_email_fabricator.rb
Follow up to https://review.discourse.org/t/dev-add-created-via-column-to-incomingemail-pr-11751/18366/6
=> FIX: Change default for IncomingEmail#created_via to 0 (unknown) and make NOT NULL

lib/version.rb
=> Version bump to v2.7.0.beta2

app/assets/javascripts/discourse/app/components/share-popup.js
=> FIX: Share popup is positioned incorrectly in RTL locales

app/assets/javascripts/discourse-common/addon/config/environment.js, app/assets/javascripts/discourse-common/addon/lib/debounce.js, app/assets/javascripts/discourse/app/app.js, app/assets/javascripts/discourse/app/initializers/inject-objects.js, app/assets/javascripts/discourse/app/pre-initializers/map-routes.js, app/assets/javascripts/discourse/app/templates/components/edit-category-general.hbs, app/assets/javascripts/discourse/tests/acceptance/category-edit-test.js, app/assets/javascripts/discourse/tests/acceptance/composer-test.js, app/assets/javascripts/discourse/tests/acceptance/create-account-user-fields-test.js, app/assets/javascripts/discourse/tests/acceptance/enforce-second-factor-test.js, app/assets/javascripts/discourse/tests/acceptance/group-test.js, app/assets/javascripts/discourse/tests/acceptance/invite-show-user-fields-test.js, app/assets/javascripts/discourse/tests/acceptance/plugin-keyboard-shortcut-test.js, app/assets/javascripts/discourse/tests/acceptance/preferences-test.js, app/assets/javascripts/discourse/tests/acceptance/raw-plugin-outlet-test.js, app/assets/javascripts/discourse/tests/acceptance/search-full-test.js, app/assets/javascripts/discourse/tests/acceptance/sign-in-test.js, app/assets/javascripts/discourse/tests/acceptance/tag-groups-test.js, app/assets/javascripts/discourse/tests/acceptance/tags-test.js, app/assets/javascripts/discourse/tests/acceptance/topic-discovery-test.js, app/assets/javascripts/discourse/tests/acceptance/topic-test.js, app/assets/javascripts/discourse/tests/acceptance/user-card-test.js, app/assets/javascripts/discourse/tests/acceptance/user-test.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js, app/assets/javascripts/discourse/tests/unit/controllers/bookmark-test.js, app/assets/javascripts/discourse/tests/unit/localization-test.js, app/assets/javascripts/handlebars-shim.js
This is mostly changes to acceptance tests to allow them to run in both
versions of Ember.
=> DEV: Sync up more Ember CLI features

app/assets/javascripts/select-kit/addon/templates/components/selected-name.hbs
This should have the role button, because clicking on it will trigger an action (either reopening the combobox or removing the item)
=> A11Y: Update selected name role to button

app/assets/javascripts/discourse/app/templates/full-page-search.hbs, app/assets/stylesheets/common/base/search.scss
=> A11y: makes advanced search and html heading

app/assets/javascripts/discourse/app/templates/components/search-advanced-options.hbs, app/assets/stylesheets/common/base/discourse.scss
=> A11Y: improves search-in-options filter accessibility

app/assets/javascripts/admin/addon/components/dashboard-new-features.js, app/assets/javascripts/admin/addon/controllers/admin-dashboard.js, app/assets/javascripts/admin/addon/models/admin-dashboard.js, app/assets/javascripts/admin/addon/templates/components/dashboard-new-feature-item.hbs, app/assets/javascripts/admin/addon/templates/components/dashboard-new-features.hbs, app/assets/javascripts/admin/addon/templates/dashboard.hbs, app/assets/javascripts/discourse/tests/acceptance/dashboard-test.js, app/assets/javascripts/discourse/tests/fixtures/dashboard-new-features.js, app/assets/stylesheets/common/admin/dashboard.scss, app/controllers/admin/dashboard_controller.rb, config/locales/client.en.yml, config/routes.rb, config/site_settings.yml, lib/discourse_updates.rb, spec/components/discourse_updates_spec.rb, spec/requests/admin/dashboard_controller_spec.rb
=> FEATURE: Add new features section in admin dashboard

app/assets/javascripts/admin/addon/controllers/admin-user-index.js
https://meta.discourse.org/t/cancelling-sso-record-deletion-deletes-record/176964
=> FIX: Check the confirmation result before deleting SSO record

app/assets/javascripts/discourse/app/components/bookmark-local-date.js, app/assets/javascripts/discourse/app/components/topic-list-item.js, app/assets/javascripts/discourse/app/controllers/bookmark.js, app/assets/javascripts/discourse/app/controllers/topic.js, app/assets/javascripts/discourse/app/models/post.js, app/assets/javascripts/discourse/app/models/topic.js, app/assets/javascripts/discourse/app/templates/components/bookmark-local-date.hbs, app/assets/javascripts/discourse/app/templates/modal/bookmark.hbs, plugins/discourse-narrative-bot/assets/javascripts/initializers/new-user-narrative.js.es6
Fix for `bookmark.js` model. Most logic was moved to `topic` controller
=> FIX: remove rendering UX from bookmark model

app/services/user_anonymizer.rb, spec/services/user_anonymizer_spec.rb
=> FIX: Destroy associated user api keys when making a user anonymous.

app/assets/javascripts/admin/addon/templates/badges-show.hbs
=> FIX: "Customize text" link was broken on badges admin page

lib/discourse_updates.rb, spec/components/discourse_updates_spec.rb
Followup to 4f01ca87e30c4b7d63a71267e4a572eea786c152
=> FIX: Support version in new feature payload

db/post_migrate/20210125100452_migrate_search_data_after_default_locale_rename.rb
This will hopefully prevent any potential deadlocks on large tables.
=> PERF: batch expensive post-migration

config/nginx.sample.conf
These headers are useful for debugging and performance analysis
=> FEATURE: Add extra response headers to nginx log format

spec/requests/api/schemas/json/tag_group_create_response.json, spec/requests/api/schemas/json/upload_create_request.json, spec/requests/api/schemas/json/upload_create_response.json, spec/requests/api/tags_spec.rb, spec/requests/api/uploads_spec.rb, spec/swagger_helper.rb
- Create helper wrapper method `load_spec_schema(name)`
- A minor change to tag_group_create response schema
- Document the uploads endpoint
=> DEV: More API Doc improvements

plugins/styleguide/assets/javascripts/discourse/components/styleguide-example.js.es6, plugins/styleguide/assets/javascripts/discourse/components/styleguide-icons.js.es6, plugins/styleguide/assets/javascripts/discourse/lib/dummy-data.js.es6, plugins/styleguide/assets/javascripts/discourse/templates/components/styleguide-example.hbs, plugins/styleguide/assets/javascripts/discourse/templates/components/styleguide-icons.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/dropdowns.hbs, plugins/styleguide/assets/stylesheets/styleguide.scss
Includes:
* FIX: Don't override computed properties
* FIX: Prevent a set-after-destroy error
* FIX: Get rid of select-kit deprecations
* FIX: Replace removed admin-group-selector
* FIX: Provide onChange action to fix warnings
* FIX: Remove an element with an invalid id
* DEV: Remove topic-notifications-button from dropdowns
It has its own styleguide section under "Molecules".
* UX: Styleguide tweaks
* DEV: Make the dropdowns useable
=> DEV: Styleguide fixes

lefthook.yml, package.json, yarn.lock
For now only attempts to use it in pre-commit hook
=> DEV: experiments parallel prettier

.github/workflows/ci.yml
=> DEV: Add png packages to GitHub CI

app/assets/stylesheets/common/base/topic-post.scss
=> ensure topic footer buttons match heights

app/assets/javascripts/discourse/app/widgets/button.js, app/assets/javascripts/discourse/app/widgets/post-edits-indicator.js, app/assets/javascripts/discourse/tests/integration/widgets/button-test.js
Follow-up to 6f13d2b03912165e2d9d5830a2ef6f73b535f3f4
=> FIX: Translated button title didn't work

lib/version.rb
=> Version bump to v2.7.0.beta3

app/controllers/application_controller.rb, app/controllers/highlight_js_controller.rb, app/controllers/static_controller.rb, app/controllers/stylesheets_controller.rb, app/controllers/svg_sprite_controller.rb, app/controllers/theme_javascripts_controller.rb, app/controllers/uploads_controller.rb, app/controllers/user_avatars_controller.rb, config/initializers/008-rack-cors.rb, lib/discourse.rb, lib/middleware/enforce_hostname.rb, spec/requests/application_controller_spec.rb, spec/requests/static_controller_spec.rb
Currently, it creates a CORS error while accessing those static files. Also, this commit blocks dynamic routes in all CDN requests.
=> DEV: apply allow origin response header for CDN requests.

app/assets/javascripts/discourse/app/components/topic-list-item.js, app/assets/javascripts/discourse/app/controllers/reorder-categories.js, app/assets/javascripts/discourse/app/helpers/raw.js, app/assets/javascripts/discourse/app/initializers/copy-codeblocks.js, app/assets/javascripts/discourse/app/initializers/jquery-plugins.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/mixins/buffered-content.js, app/assets/javascripts/discourse/app/mixins/mobile-scroll-direction.js, app/assets/javascripts/discourse/app/mixins/scrolling.js, app/assets/javascripts/discourse/app/mixins/username-validation.js, app/assets/javascripts/discourse/app/services/app-events.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js, app/assets/javascripts/discourse/tests/unit/controllers/create-account-test.js
They should all be backwards compatible. This is all to help merge our
branches.
=> Quite a few Ember-CLI / Upgrade related changes

spec/requests/api/schemas/json/admin_user_list_response.json, spec/requests/api/schemas/json/admin_user_response.json, spec/requests/api/schemas/json/success_ok_response.json, spec/requests/api/schemas/json/user_actions_response.json, spec/requests/api/schemas/json/user_delete_request.json, spec/requests/api/schemas/json/user_delete_response.json, spec/requests/api/schemas/json/user_refresh_gravatar_response.json, spec/requests/api/schemas/json/user_update_avatar_request.json, spec/requests/api/schemas/json/user_update_email_request.json, spec/requests/api/schemas/json/users_public_list_response.json, spec/requests/api/shared/shared_examples.rb, spec/requests/api/users_spec.rb
- document user endpoints, allow for empty request/response bodies
- document more user endpoints, improve debugging output if no details are specified
- document some more user endpoints
=> document user endpoints

app/jobs/scheduled/check_new_features.rb
=> FEATURE: Add daily job to check for new features

app/assets/javascripts/discourse/app/templates/modal/change-owner.hbs
=> UX: Add autofocus to the change ownership modal

Gemfile.lock
It seems like 1.4.1 was yanked.
=> DEV: Update msgpack to 1.4.2.

lib/email_cook.rb
Follow-up to 3c678df942b9322bfda5eb47d428b1c692ac0bf4
=> PERF: Avoid lookbehinds when replacing links in imported emails

plugins/discourse-narrative-bot/assets/stylesheets/discourse-narrative-bot.scss, plugins/discourse-narrative-bot/plugin.rb
=> UX: Remove border from certificate due to iframe

app/controllers/session_controller.rb, spec/requests/session_controller_spec.rb
This adds an additional layer of security.
=> SECURITY: Rate limit MFA by login if possible

app/models/admin_dashboard_data.rb, config/locales/server.en.yml
`update_mail_receiver`-related code was removed in 269ec70ba8d5997c7b6a49f97cafc774e4dcf9d2 and `deprecated_api_usage`-related code was removed in d04ba4b3b2e4c750d3f4bd32a2263cd6e405eb69.
=> DEV: Remove `update_mail_receiver` and `deprecated_api_usage`

app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-body.js, app/assets/stylesheets/common/base/_topic-list.scss, app/assets/stylesheets/common/base/discourse.scss, app/assets/stylesheets/common/base/header.scss, app/assets/stylesheets/common/base/menu-panel.scss, app/assets/stylesheets/common/components/buttons.scss, app/assets/stylesheets/common/components/date-input.scss, app/assets/stylesheets/common/components/date-time-input.scss, app/assets/stylesheets/common/d-editor.scss, app/assets/stylesheets/common/foundation/mixins.scss, app/assets/stylesheets/common/foundation/variables.scss, app/assets/stylesheets/common/select-kit/combo-box.scss, app/assets/stylesheets/common/select-kit/multi-select.scss, app/assets/stylesheets/common/select-kit/single-select.scss
Before / After screenshots
**Safari macOS**
**Firefox macOS**
**Chrome macOS**
Note also that this uses the theme's colors (vs. the browser's defaults previously):
=> UX: Uniformize styles for focus states

lib/backup_restore.rb, spec/requests/api/backups_spec.rb, spec/requests/api/groups_spec.rb, spec/requests/api/schemas/json/backups_create_request.json, spec/requests/api/schemas/json/backups_list_response.json, spec/requests/api/schemas/json/group_add_members_request.json, spec/requests/api/schemas/json/group_add_members_response.json, spec/requests/api/schemas/json/group_members_response.json, spec/requests/api/schemas/json/group_remove_members_request.json, spec/requests/api/schemas/json/group_remove_members_response.json, spec/requests/api/schemas/json/group_response.json, spec/requests/api/schemas/json/groups_list_response.json, spec/requests/api/schemas/json/search_request.json, spec/requests/api/schemas/json/search_response.json, spec/requests/api/schemas/json/user_password_change_request.json, spec/requests/api/schemas/json/user_password_reset_request.json, spec/requests/api/schemas/json/user_password_reset_response.json, spec/requests/api/search_spec.rb, spec/requests/api/users_spec.rb
- DEV: Documented several group endpoints
- documented some more endpoints
- document more api endpoints
- Document backup endpoints
=> document api endpoints

app/assets/javascripts/discourse/app/controllers/static.js, app/assets/javascripts/discourse/app/templates/static.hbs, app/assets/stylesheets/common/base/faqs.scss
follow-up to f1d5d2b
Before:
After:
=> fix button alignment on log-in required page

app/assets/stylesheets/common/components/user-stream.scss
relevant discussion here: https://meta.discourse.org/t/margin-issue-on-users-page/178308
=> remove unneeded margin from user stream

app/assets/javascripts/select-kit/addon/components/email-group-user-chooser-filter.js
Follow up to https://github.com/discourse/discourse/commit/db7b7eed9df1713a39cd6bde304cae077ce4c19c.
=> DEV: Use @action decorator

app/assets/javascripts/discourse/app/controllers/topic-bulk-actions.js, config/locales/client.en.yml
UX: update label for "Remove Tags" action
=> UX: add a confirmation modal to "Remove All Tags" action

app/assets/stylesheets/common/base/compose.scss, app/assets/stylesheets/desktop/topic-post.scss
=> UX: Adjust focus styles for topic post menu, composer cancel button

app/assets/javascripts/discourse/app/templates/modal/bulk-notification-level.hbs, app/assets/stylesheets/common/base/modal.scss, config/locales/client.en.yml
=> UX: Fix & clarify bulk notification change modal

app/assets/javascripts/discourse/app/controllers/composer.js, app/assets/stylesheets/common/base/modal.scss
Follow-up to f1d5d2b
Before:
After:
=> UX: Fix reply where modal layout

app/assets/javascripts/discourse/app/widgets/post-menu.js
=> EXTENSION: Allow Widgets to extend post-controls

app/assets/stylesheets/common/base/_topic-list.scss, app/assets/stylesheets/desktop/topic-list.scss
Fixes this issue, follow-up to 615a091
=> Move category dropdown changes to desktop only

app/controllers/session_controller.rb, spec/requests/session_controller_spec.rb
Followup to 821bb1e8cb72bee56cf5c2a878043112cc7ea2fd
=> FIX: Correct server error for starting SSO login, and add spec

app/assets/javascripts/service-worker.js.erb
=> FEATURE: Handle user agent push subscription change events

spec/requests/api/schemas/json/admin_user_list_response.json, spec/requests/api/schemas/json/backups_list_response.json, spec/swagger_helper.rb
- DEV: Escape backslashes in curl example
- FIX: uniqItems should be uniqueItems
=> api docs example

app/assets/javascripts/discourse/app/controllers/tag-show.js, app/assets/javascripts/discourse/app/models/topic-tracking-state.js, app/assets/javascripts/discourse/app/models/topic.js, app/assets/javascripts/discourse/app/templates/tags/show.hbs, app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js, app/controllers/topics_controller.rb, app/models/topic_tracking_state.rb, app/services/dismiss_topics.rb, spec/requests/topics_controller_spec.rb, spec/services/dismiss_topics_spec.rb
Follow up of https://github.com/discourse/discourse/pull/11927
Using the same mechanism to disable new topics in a tag.
=> FEATURE: Ability to dismiss new topics in a specific tag

spec/requests/api/categories_spec.rb, spec/requests/api/schemas/json/category_create_request.json, spec/requests/api/schemas/json/category_create_response.json, spec/requests/api/schemas/json/category_list_response.json, spec/requests/api/schemas/json/category_topics_response.json, spec/requests/api/schemas/json/category_update_response.json
Updated the category api docs to follow the new validation format.
=> DEV: Update category api docs

lib/backup_restore/backup_file_handler.rb, lib/backup_restore/factory.rb, lib/backup_restore/restorer.rb, spec/lib/backup_restore/backup_file_handler_spec.rb, spec/requests/api/backups_spec.rb
=> Fix issues in backup restore

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
=> A11Y: sets html lang using current locale and not default

lib/tasks/emails.rake
=> tasks/emails.rake: catch exception and puts message

lib/tasks/plugin.rake
Based on https://github.com/discourse/docker_manager/pull/94
=> DEV: Support for `main` branches in plugin:update

.github/workflows/ci.yml, lib/tasks/qunit.rake, lib/tasks/smoke_test.rake
Most likely a leftover from the npm days.
=> DEV: `--dev` option does nothing in yarn

app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show.js, app/assets/javascripts/admin/addon/templates/customize-themes-show.hbs
=> UX: Remove Convert option for system themes

app/assets/stylesheets/desktop/login.scss
This commit adjusts the height of the left side of the login modal, and changes the scroll gradient positioning.
=> FIX: Login UI Fixes

app/assets/javascripts/discourse/public/assets/scripts/discourse-boot.js
=> DEV: Live reload styles in Ember CLI

app/assets/stylesheets/common/components/buttons.scss, app/assets/stylesheets/desktop/login.scss, config/locales/client.en.yml
This commit adjusts the scroll gradient on the login modal, changes `email / username` to `Email / Username` and adjusts the color of social button icons on hover in the login modal.
=> UI: Adjust gradient, icon hover, capitalizations

app/assets/javascripts/discourse/app/controllers/create-account.js
=> UX: Hide external login column when account creation in progress

app/assets/javascripts/discourse/app/lib/autocomplete.js, app/assets/stylesheets/common/base/compose.scss
=> UX: Adjust focus styles for autocomplete input

app/assets/stylesheets/common/base/login.scss
This commit adds more specificity to the social buttons styling.
=> UI: Specify social button styling

app/jobs/scheduled/check_new_features.rb, lib/discourse_updates.rb, spec/multisite/jobs_spec.rb
=> DEV: Avoid rate limits for new feature checks on multisite

config/nginx.sample.conf
We need to allow origin header to force CORS in CDN requests.
=> DEV: add allow origin header to public javascript files.

app/assets/javascripts/admin/addon/templates/components/site-settings/tag-list.hbs
=> FIX: Allow all tags in site/theme settings, ignore tag group restrictions

app/assets/javascripts/admin/addon/templates/plugins-index.hbs, app/assets/stylesheets/common/admin/plugins.scss, app/serializers/admin_plugin_serializer.rb
=> UX: show plugin descriptions on admin plugins page

plugins/poll/assets/javascripts/widgets/discourse-poll.js.es6
=> DEV: Add poll:voted event

app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-body.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-filter.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-header.js, app/assets/javascripts/select-kit/addon/templates/components/email-group-user-chooser-header.hbs, app/assets/javascripts/select-kit/addon/templates/components/multi-select.hbs, app/assets/javascripts/select-kit/addon/templates/components/multi-select/multi-select-header.hbs, app/assets/javascripts/select-kit/addon/templates/components/single-select.hbs
=> A11Y: makes aria-owns an ID and not a data attribute

app/assets/javascripts/discourse/app/components/d-navigation-item.js, app/assets/javascripts/discourse/app/templates/components/d-navigation-item.hbs, app/assets/javascripts/discourse/app/templates/user/activity.hbs
=> A11Y: adds support for aria-current through d-navigation-item

lib/backup_restore/restorer.rb
=> FIX: Restoring backup via UI was broken

app/views/layouts/publish.html.erb
=> FIX: adds google tracking to page publishing

app/assets/javascripts/service-worker.js.erb
=> DEV: debug: false for service workers to stop log spam via workbox

spec/models/topic_spec.rb
=> DEV: Fix topic timer flaky spec for inheriting from category

app/assets/javascripts/discourse/app/widgets/post-menu.js, app/assets/stylesheets/desktop/topic-post.scss
=> DEV: flexify post-controls and stop relying on clearfix

app/controllers/groups_controller.rb, app/models/invite.rb, lib/guardian.rb, spec/models/invite_spec.rb, spec/requests/groups_controller_spec.rb
=> DEV: Replace deprecated sso site settings with discourse_connect

config/nginx.sample.conf
It's required when we enable cors mod in the service worker.
=> DEV: add CORS header for all files served from public folder.

app/services/dismiss_topics.rb
Quick fix after https://github.com/discourse/discourse/pull/12103
=> FIX: remove unnecessary OR from dismiss service

app/controllers/admin/users_controller.rb, app/controllers/session_controller.rb, app/models/discourse_single_sign_on.rb, lib/single_sign_on.rb, spec/models/discourse_single_sign_on_spec.rb, spec/requests/admin/users_controller_spec.rb, spec/requests/session_controller_spec.rb, spec/support/integration_helpers.rb
=> SECURITY: Attach DiscourseConnect (SSO) nonce to current session

Gemfile, Gemfile.lock, lib/email/receiver.rb, spec/components/email/receiver_spec.rb, spec/components/imap/imap_helper.rb, spec/fixtures/emails/encoded_filename.eml
This is a draft until mail 2.8 is released. I created it just to create awareness about future update.
Version 2.8 brings some changes to how address fields are handled and
this commits updates that and should also include a fix which handles
encoded attachment filenames.
=> DEV: Update mail

lib/version.rb
=> Version bump to v2.7.0.beta4

app/assets/stylesheets/desktop/login.scss
This PR adds padding to the top and bottom of the form on the create account modal.
=> UX: Adjust padding on create account modal

app/models/reviewable_user.rb, spec/models/reviewable_user_spec.rb
=> FIX: Don't require a rejection reason if the user is a spammer.

app/assets/stylesheets/common/admin/dashboard.scss, lib/discourse_updates.rb, spec/components/discourse_updates_spec.rb
Also fixes an alignment issue in the grid.
=> FIX: Sort admin dashboard new updates by latest

app/assets/javascripts/discourse/app/templates/components/edit-category-general.hbs, app/assets/javascripts/discourse/app/templates/components/edit-category-images.hbs, app/assets/javascripts/discourse/app/templates/components/edit-category-settings.hbs, app/assets/javascripts/discourse/app/templates/components/edit-category-tags.hbs
=> DEV: add classes to sections in category settings

app/assets/javascripts/discourse/app/widgets/header.js, app/assets/javascripts/discourse/app/widgets/post.js
=> A11Y: ensures avatar image in site header has alt attribute

app/assets/javascripts/discourse/app/templates/preferences/interface.hbs
=> A11Y: makes other and color, fieldset/legend elements

app/models/user.rb, app/models/user_email.rb, spec/models/user_spec.rb
- Only apply the change after `save` is called on the record
- Automatically remove matching secondary emails
=> DEV: Improve User#email= behavior

app/assets/javascripts/select-kit/addon/components/multi-select.js, app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/stylesheets/common/select-kit/multi-select.scss
=> A11Y: deselect focused choice when using enter in multi-select

app/assets/javascripts/discourse/app/templates/group.hbs, app/assets/stylesheets/common/base/group.scss, app/assets/stylesheets/desktop/group.scss, app/assets/stylesheets/mobile/group.scss
=> UX: Tweak `group` layout to fix button alignment

app/assets/stylesheets/wizard.scss, config/locales/server.en.yml, lib/wizard/builder.rb, spec/components/wizard/step_updater_spec.rb
=> UX: Remove emoji step in wizard

app/assets/javascripts/discourse/app/templates/discovery/categories.hbs
=> DEV: add plugin outlets above and below discovery-categories

spec/requests/api/schemas/json/user_suspend_request.json, spec/requests/api/schemas/json/user_suspend_response.json, spec/requests/api/users_spec.rb
Wrote an api docs rspec test for documenting the user suspend api
endpoint.
=> DEV: Document the user suspend api endpoint

app/assets/stylesheets/common/admin/dashboard.scss, app/assets/stylesheets/mobile/dashboard.scss
- Fixes an alignment issue when emojis have varying widths
- Adjusts mobile alignment
=> UX: Styling adjustments for admin new features

app/assets/javascripts/discourse/app/components/badge-card.js
=> FIX: Ensure badge description is updated when routing without loading state

app/assets/javascripts/discourse/app/controllers/preferences/interface.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-interface-test.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js
Fixes failures in user-preferences-interface-test on Ember CLI.
=> DEV: Fix Settings/Interface UI breaking on Ember CLI

config/nginx.sample.conf
This reverts commit d628c65af06d4e809fde5e3825e065173517e5a1 and adding CORS header in two more places individually.
=> DEV: add CORS header for all nginx rules of public folder files.

app/assets/stylesheets/common/base/login.scss
=> FIX: login modal max-width wasn't specific enough

app/controllers/metadata_controller.rb
Used in the new install prompt
https://twitter.com/alexey_rodionov/status/1349612958754762753
=> FEATURE: Add site description for the webmanifest

app/assets/stylesheets/desktop/login.scss, app/assets/stylesheets/mobile/login.scss
=> UX: Some fixes for the 2FA step on login 

app/assets/javascripts/discourse/public/assets/scripts/discourse-boot.js, app/controllers/bootstrap_controller.rb, spec/requests/bootstrap_controller_spec.rb
This also supports plugins with custom HTML.
=> FIX: When using Ember CLI theme Javascript/HTML was not being inserted

lib/freedom_patches/raw_handlebars.rb
Without this patch, we'd be using the `__DISCOURSE_RAW_TEMPLATES` global which is
incompatible with Ember CLI.
=> FIX: Use `addRawTemplates` even when compiling `.hbr` files

app/assets/javascripts/discourse/app/components/group-card-contents.js, app/assets/javascripts/discourse/app/templates/components/group-card-contents.hbs
CTRL + click on user avatar did not open user page.
=> FIX: Add href to user avatar in group cards

app/assets/javascripts/discourse/app/components/site-header.js, app/assets/javascripts/discourse/app/widgets/button.js, app/assets/javascripts/discourse/app/widgets/quick-access-panel.js, app/assets/javascripts/discourse/app/widgets/user-menu.js, app/assets/stylesheets/common/base/menu-panel.scss
Reverts discourse/discourse#12241
=> Revert "A11Y: Switch tabs using the keyboard"

app/assets/javascripts/discourse/app/components/relative-time-picker.js, app/assets/javascripts/discourse/app/controllers/edit-topic-timer.js, app/assets/javascripts/discourse/tests/integration/components/relative-time-picker-test.js, config/locales/client.en.yml
Add a new year interval option to relative time picker, and also fix some rounding issues (Math.floor is not ideal because it gets rid of half days etc.)
Also adding some component tests here for relative-time-picker.
=> FEATURE: Add year to relative time picker

app/assets/javascripts/discourse/app/controllers/preferences/account.js, app/assets/javascripts/discourse/app/controllers/preferences/security.js, app/assets/javascripts/discourse/app/routes/app-route-map.js, app/assets/javascripts/discourse/app/routes/preferences-security.js, app/assets/javascripts/discourse/app/templates/preferences.hbs, app/assets/javascripts/discourse/app/templates/preferences/account.hbs, app/assets/javascripts/discourse/app/templates/preferences/security.hbs, app/assets/javascripts/discourse/tests/acceptance/preferences-test.js, config/locales/client.en.yml, config/routes.rb
=> FEATURE: Move security related user preferences to different tab

config/locales/client.en.yml
I made some adjustments to the invite system copy, to reflect the mockups at https://meta.discourse.org/t/improve-invite-system/173756 - the goal is to try to reduce the number of words and make it as simple as possible, similar to discord.
=> copy changes to new invite system

app/assets/javascripts/discourse/app/controllers/create-account.js, app/assets/javascripts/discourse/app/controllers/login.js, app/assets/javascripts/discourse/app/lib/waving-hand-url.js
Allows for resuse in other controllers and components.
=> DEV: DRY up wavingHandUrl code.

app/controllers/metadata_controller.rb, config/locales/server.en.yml, config/site_settings.yml
=> FEATURE: Add opt-in screenshots to the web app manifest

Gemfile, Gemfile.lock
This contains 3 security fixes that do not impact us, see:
https://discuss.rubyonrails.org/c/security-announcements/9
=> DEV: Update Rails to latest patch level

docs/code-of-conduct.md
The code of conduct is from the Contributor Covenant. Latest version is 2.0. See https://www.contributor-covenant.org
=> Update Code of Conduct to v2.0

config/locales/client.en.yml
as per: https://meta.discourse.org/t/this-site-was-just-updated-popups-are-annoying/181125?u=tobiaseigen
=> clarify copy "this site was just updated" popup

app/models/draft_sequence.rb
This was causing RecordNotUnique exceptions
=> FIX: Race condition in draft sequence updates

app/assets/javascripts/discourse/app/templates/tags/index.hbs
=> DEV: add new plugin outlet to tags template

app/assets/javascripts/discourse/app/controllers/invites-show.js
Follow-up to ce04db861033c906830fd07ae98b3d0cb375c753
=> FIX: Incorrect parameter when using omniauth providers on invites page.

app/assets/javascripts/admin/addon/templates/watched-words-action.hbs, app/assets/stylesheets/common/admin/staff_logs.scss
=> UX: Remove duplicate title from watched words page

lib/tasks/db.rake
Added a new task to test if indexes are coherent with a blank database
This allows us to detect for cases where somehow indexes are out of sync
=> DEV: add db:validate_indexes task

app/assets/javascripts/admin/addon/controllers/admin-watched-words-action.js, config/locales/client.en.yml
=> FIX: Add translation string for confirmation

app/models/user.rb, spec/models/user_spec.rb
It was validated twice, once by validates_associated and once by
has_many.
=> FIX: Validate user email only once

app/assets/javascripts/discourse/app/components/bulk-select-all.js, app/assets/javascripts/discourse/app/controllers/topic-bulk-actions.js, app/assets/javascripts/discourse/app/controllers/user-private-messages.js, app/assets/javascripts/discourse/app/templates/user/messages.hbs, app/assets/stylesheets/desktop/topic-list.scss, config/locales/client.en.yml
=> FEATURE: Implement bulk operations for PMs

app/assets/javascripts/discourse-common/addon/resolver.js, app/assets/javascripts/discourse/app/models/topic.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js, app/assets/javascripts/discourse/tests/integration/components/topic-list-test.js
If you were unlucky and tested a mobile raw template before a desktop
raw template, it would keep using the mobile one resulting in failures.
=> FIX: Flaky JS tests

app/assets/stylesheets/common.scss, app/assets/stylesheets/desktop.scss, app/assets/stylesheets/embed.scss, app/assets/stylesheets/mobile.scss, app/assets/stylesheets/wizard.scss, lib/stylesheet/compiler.rb, lib/stylesheet/importer.rb, spec/components/stylesheet/importer_spec.rb
=> DEV: Refactor font and category background importers

app/assets/javascripts/discourse/app/templates/invites/show.hbs, app/assets/stylesheets/common/base/user.scss
- Adds * on required fields (consistent with required fields elsewhere,
including custom user fields in the invite form, where applicable)
- adds `for` attributes
=> UX: Consistent labels in invite form

lib/version.rb
=> Version bump to v2.7.0.beta5

config/locales/client.en.yml
=> add bell emoji for better unread education

db/migrate/20210311022303_drop_show_filter_by_tag_site_setting.rb
Follow-up to 83519e7f3ac4fe2e06d1fc521b1f7535ed2a86f6
=> DEV: Drop `show_filter_by_tag` site settings.

app/controllers/invites_controller.rb, app/models/invite.rb, app/serializers/invite_serializer.rb, spec/requests/api/invites_spec.rb
=> DEV: Update API documentation for invites

app/assets/javascripts/discourse/app/index.html, app/assets/javascripts/discourse/lib/bootstrap-json/index.js, app/assets/javascripts/discourse/public/assets/scripts/discourse-boot.js, app/assets/javascripts/discourse/tests/index.html
=> A couple important Ember CLI fixes

app/assets/javascripts/discourse/app/templates/modal/create-invite.hbs
=> DEV: add classes to invite modal fields so they can be targeted

lib/post_action_creator.rb
I plan on using this in a plugin :smiley:
=> FEATURE: New DiscourseEvent trigger for likes

lib/stylesheet/common.rb, lib/stylesheet/compiler.rb, lib/stylesheet/importer.rb, spec/components/plugin/instance_spec.rb, spec/components/stylesheet/compiler_spec.rb, spec/fixtures/plugins/scss_plugin/assets/stylesheets/colors.scss, spec/fixtures/plugins/scss_plugin/assets/stylesheets/common/_variables.scss, spec/fixtures/plugins/scss_plugin/assets/stylesheets/common/common.scss, spec/fixtures/plugins/scss_plugin/assets/stylesheets/common/subfolder/other.scss, spec/fixtures/plugins/scss_plugin/plugin.rb, spec/models/theme_field_spec.rb
=> DEV: Refactor plugin SCSS compilation

spec/models/user_spec.rb
=> DEV: Remove stray debug logging

spec/requests/reviewables_controller_spec.rb
=> DEV: Remove debug print statement

lib/stylesheet/watcher.rb
This switches the dev environment stylesheet watcher to launch only one listener for all watchable paths instead of launching a listener per path (where the paths include core + each plugin stylesheet folder). 
Also limits the watcher to css/scss file changes, previously it was watching all files and only triggering a change notice on css/scss files.
=> DEV: Use fewer threads when watching for SCSS changes

app/assets/javascripts/discourse/app/templates/topic.hbs
Adding this to avoid template overrides for a customer
=> DEV: Add above-timeline plugin outlet

app/controllers/metadata_controller.rb
=> FIX: Move PWA App shortcut for bookmarks to new path

lib/topic_retriever.rb
=> FEATURE: Fallback to system users when creating new TopicEmbed

app/assets/javascripts/discourse/app/index.html, app/assets/javascripts/discourse/public/assets/scripts/start-app.js
This is to help with potential CSP issues.
=> REFACTOR: Use a `<script src>` tag to start the app

app/assets/javascripts/discourse/app/models/invite.js, app/assets/javascripts/discourse/app/templates/user-invited-show.hbs, app/assets/stylesheets/mobile/user.scss, config/locales/client.en.yml
=> UX: Show Topic column in invites pending tab

app/assets/javascripts/discourse/app/templates/preferences-username.hbs
=> A11Y: links change_username input to its label

app/assets/javascripts/discourse/app/templates/preferences/interface.hbs
=> A11Y: associates lists with labels on interface page

spec/requests/topics_controller_spec.rb
=> DEV: Speed up topics_controller_spec.rb

app/assets/javascripts/discourse/app/templates/components/topic-footer-buttons.hbs, app/assets/stylesheets/common/base/topic-post.scss, app/assets/stylesheets/desktop/topic-post.scss, app/assets/stylesheets/mobile/topic-post.scss
This fixes some alignment and spacing issues, especially in some more verbose languages. 
**Before**:
**After**: 
**Before**: 
**After**:
=> UX: Improve topic footer alignment and layout

app/assets/javascripts/discourse/app/widgets/quick-access-notifications.js, app/assets/stylesheets/common/base/menu-panel.scss, app/assets/stylesheets/common/components/buttons.scss
=> A11Y: improves avatar menu focus/active states

.eslintignore, .prettierignore, app/assets/javascripts/browser-update.js
This caused issues in IE11 with compatibility mode.
=> FIX: browser-update should work with old browsers

plugins/discourse-narrative-bot/plugin.rb
Follow-up to 50f8782def77735c9dc3e13b68b3c8af7ab6ac6b.
=> FIX: Do not fail if Postgres is not available

app/assets/javascripts/discourse/app/index.html, app/assets/javascripts/discourse/ember-cli-build.js, app/assets/javascripts/discourse/lib/bootstrap-json/index.js, app/assets/javascripts/discourse/lib/discourse-scss.js, app/assets/javascripts/discourse/lib/pretty-text-engine.js, app/assets/javascripts/discourse/lib/translation-plugin.js, app/assets/javascripts/discourse/package.json, app/assets/javascripts/discourse/testem.js, app/assets/javascripts/discourse/tests/acceptance/flag-post-test.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js, app/assets/javascripts/discourse/tests/helpers/fixture-pretender.js, app/assets/javascripts/discourse/tests/index.html, app/assets/javascripts/discourse/tests/integration/components/highlighted-code-test.js, app/assets/javascripts/yarn.lock, app/assets/stylesheets/testem.scss
These commits allow us to run `ember test` and `ember test --server` in our Ember CLI branch.
See commits for individual stepping stones to the full support.
=> Support for Testem in Ember CLI

app/assets/javascripts/admin/addon/components/admin-wrapper.js
Also removes some jQuery
Relevant discussion: https://meta.discourse.org/t/ignore-theme-for-admin-backend-or-add-classname-to-html/183877
=> FEATURE: Add `admin-area` class to HTML tag

app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
=> DOC: document addShortcut click option

app/assets/javascripts/discourse/app/components/site-header.js
=> FIX: a never created listener was removed

config/locales/client.zh_TW.yml
Accidentally removed in b7556fca80b743345e8e5dd96e644fb8bf09e6bc
=> FIX: Restore client.zh_TW.yml

app/assets/javascripts/discourse/app/templates/modal/login.hbs, app/assets/stylesheets/common/base/login.scss
=> FIX: ensures invisible link is not interfering with UI/tab order

lib/email/styles.rb
=> FIX: Improvements to email styles

app/assets/javascripts/discourse/app/controllers/create-account.js, app/assets/javascripts/discourse/app/mixins/username-validation.js, app/assets/javascripts/discourse/app/models/user.js, app/assets/javascripts/discourse/app/templates/modal/create-account.hbs, app/assets/javascripts/discourse/tests/helpers/create-pretender.js, app/controllers/users_controller.rb, config/locales/client.en.yml, config/routes.rb, spec/requests/users_controller_spec.rb
=> FEATURE: Check email availability in signup form

app/assets/javascripts/discourse/app/components/slow-mode-info.js, app/assets/javascripts/discourse/tests/integration/components/slow-mode-info-test.js
=> FIX: Anons should see the Topic slow mode notice.

app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js, app/assets/javascripts/pretty-text/engines/discourse-markdown/custom-typographer-replacements.js
=> FEATURE: Add a typographer rule to replace (pa) with ¶.

app/controllers/embed_controller.rb, config/locales/server.en.yml, config/site_settings.yml, lib/content_security_policy/default.rb, spec/lib/content_security_policy_spec.rb, spec/requests/embed_controller_spec.rb
=> FEATURE: Add CSP frame-ancestors support

app/assets/javascripts/discourse/app/controllers/topic-bulk-actions.js
Meta bug report: https://meta.discourse.org/t/bulk-archive-of-group-pms-doesnt-work/183972
=> FIX: bulk "archive" and "move to inbox" for group messages was broken

app/controllers/users_controller.rb, spec/requests/users_controller_spec.rb
Using UserEmail for validation is not sufficient because it checks the
emails of staged users too.
=> FIX: Perform better email validation

Gemfile.lock, db/migrate/20210315173137_set_disable_mailing_list_mode.rb, lib/mini_sql_multisite_connection.rb, spec/lib/mini_sql_multisite_connection_spec.rb
- DEV: upgrade mini_sql
- implement multisite friendly prepared statements
- FIX: if mailing list mode was disabled, keep it disabled
=> correct mailing list migration

app/models/topic_list.rb, spec/models/topic_list_spec.rb
https://meta.discourse.org/t/complex-url-for-creating-new-topics-results-in-server-side-error/184067/4?u=techapj
=> FIX: new-topic route with sub-category and tags were broken

spec/requests/posts_controller_spec.rb
=> DEV: Change flakey posts controller spec

app/assets/javascripts/discourse/tests/acceptance/composer-test.js
=> DEV: Skip composer duplicate link test

app/assets/javascripts/discourse/app/components/invite-panel.js, app/assets/javascripts/discourse/app/templates/components/invite-panel.hbs, app/assets/stylesheets/common/components/share-and-invite-modal.scss
Meta topic: https://meta.discourse.org/t/pasting-email-in-share-a-thread-box-stopped-working/180919?u=osama.
=> FIX: Allow pasting invitees in invite modal

app/assets/javascripts/discourse/app/components/topic-timer-info.js
This PR improves the code structure of the topic-timer-info component while retaining all the functionality and making it extensible for theme/plugin devs.
=> IMPR: improved topic timer component's code structure

app/assets/stylesheets/common/base/emoji.scss
=> UX: Emoji popup layout adjustments

app/assets/javascripts/discourse/app/templates/modal/create-invite.hbs, app/assets/javascripts/discourse/tests/acceptance/create-invite-modal-test.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js
=> DEV: Add tests for create-invite modal

app/services/post_alerter.rb
=> FIX: Prevent UniqueViolation exceptions when syncing group mentions

spec/rails_helper.rb
It makes SimpleCov work with turbo_rspec and uses the default Rails
configuration (with some changes) to groups files by their type
(models, controllers, etc).
Our current code coverage is ~81%.
=> DEV: Better SimpleCov configuration

app/assets/javascripts/discourse/app/templates/components/emoji-picker.hbs, app/assets/stylesheets/common/base/emoji.scss
Followup to https://github.com/discourse/discourse/pull/12533
Thanks for the testing @CvX!
=> UX: Fix tab list alignment in emoji popup

Gemfile.lock
=> DEV: bundle update onebox

app/assets/javascripts/discourse/app/templates/topic.hbs
In a theme, I need to access this action.
=> DEV: Pass editFirstPost action to plugin outlet in topic.hbs

app/assets/javascripts/discourse/app/components/topic-list.js, app/assets/javascripts/discourse/app/raw-views/topic-list-header-column.js, app/assets/javascripts/discourse/app/templates/topic-list-header-column.hbr, app/assets/stylesheets/common/base/discourse.scss
* Make sortable `th` keyboard accessible with `tabindex`
* Allow sortable `th` to be triggered by space/enter
* Add `scope`, `aria-role`, `aria-sort`, `aria-pressed` to sortable `th`
=> A11Y: make th keyboard accessible + aria attribs

config/locales/client.en.yml
The original copy I proposed was too scary, so here's a simplified educational message.
=> Change to no_messages_body copy

config/locales/client.en.yml
=> added basePath

config/locales/client.en.yml
=> added %{base_url} to about link

app/assets/javascripts/discourse/app/lib/intercept-click.js
=> DEV: removes jquery usage from intercept-click

app/assets/stylesheets/desktop/user.scss
=> FIX: Remove overflow on user controls to fix select-kit

app/assets/javascripts/discourse/app/raw-views/list/posts-count-column.js, app/assets/javascripts/discourse/app/templates/list/posts-count-column.hbr, app/assets/stylesheets/common/base/_topic-list.scss
=> A11Y: makes replies count a button and not a link

app/assets/javascripts/discourse/app/models/category-list.js, app/assets/javascripts/discourse/app/models/topic-list.js, app/assets/javascripts/discourse/app/routes/discovery-categories.js, app/assets/javascripts/discourse/app/routes/tag-show.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js
=> FIX: New Topic button regression in tag page

app/assets/javascripts/discourse/app/components/user-avatar-flair.js, app/assets/javascripts/discourse/app/lib/avatar-flair.js, app/assets/javascripts/discourse/app/lib/transform-post.js, app/assets/javascripts/discourse/app/templates/components/groups-form-profile-fields.hbs, app/assets/javascripts/discourse/app/templates/components/latest-topic-list-item.hbs, app/assets/javascripts/discourse/app/templates/components/user-card-contents.hbs, app/assets/javascripts/discourse/app/templates/components/user-info.hbs, app/assets/javascripts/discourse/app/templates/components/user-profile-avatar.hbs, app/assets/javascripts/discourse/app/widgets/post.js, app/assets/javascripts/discourse/app/widgets/topic-map.js, app/assets/javascripts/discourse/tests/integration/components/user-avatar-flair-test.js, app/controllers/groups_controller.rb, app/serializers/category_and_topic_lists_serializer.rb, app/serializers/concerns/user_primary_group_mixin.rb, app/serializers/poster_serializer.rb, app/serializers/site_serializer.rb, app/serializers/topic_post_count_serializer.rb, app/serializers/topic_poster_serializer.rb, lib/user_lookup.rb, spec/requests/groups_controller_spec.rb
https://meta.discourse.org/t/avatar-flair-image-for-automatic-groups-staff-moderators-admin/98618/12
=> FEATURE: Allow setting avatar flair for automatic groups

app/assets/javascripts/discourse/app/templates/composer.hbs
=> DEV: Add a new plugin outlet to composer bottom for mobile buttons

script/import_scripts/higher_logic.rb
Wrote up a new script to import from Higher Logic. Nothing too crazy going on here. Two major things about this script:
1. It requires you to convert a Microsoft SQL file to a format MySQL can read.
2. Higher Logic stores posts (at least in the case of the import I ran) with the email thread shown in the post body. The script does its best to truncate this out, but the logic may need to be improved on future imports. For the import I ran, it worked just fine as is. 🤷‍♂️
=> DEV: Add Higher Logic import script

Gemfile.lock
=> DEV: Bump discourse_dev to 0.0.7

lib/oneboxer.rb, spec/components/oneboxer_spec.rb
=> DEV: stub youtube embed requests

lib/version.rb
=> Version bump to v2.7.0.beta6

config/locales/client.en.yml
=> tweaks to invite error messages

config/locales/client.en.yml
=> FIX: behaviour -> behavior spelling in default US translation

app/assets/javascripts/select-kit/addon/components/tag-drop.js, app/assets/javascripts/select-kit/addon/components/tag-drop/more-tags-collection.js, app/assets/javascripts/select-kit/addon/templates/components/tag-drop/more-tags-collection.hbs, app/assets/stylesheets/common/select-kit/tag-drop.scss, app/models/tag.rb, config/locales/client.en.yml
=> UX: shows a hint when there are more tags than displayed

app/models/group.rb, app/models/web_hook_event_type.rb, app/serializers/web_hook_group_user_serializer.rb, config/initializers/012-web_hook_events.rb, config/locales/client.en.yml, db/fixtures/007_web_hook_event_types.rb, spec/fabricators/web_hook_fabricator.rb, spec/models/web_hook_spec.rb
Whenever a group is added or removed from a group a webhook event will get triggered if it's active.
=> FEATURE: trigger webhook when a user added/removed in a group.

app/assets/javascripts/discourse/app/templates/about.hbs, app/models/about.rb, app/views/about/index.html.erb, config/locales/client.en.yml
Context of this change: https://meta.discourse.org/t/how-to-get-the-dau-and-mau-data-separately/186021
=> FEATURE: adds last day to about page stats

app/assets/stylesheets/common/base/onebox.scss
https://github.com/discourse/onebox/pull/466
=> UI: adds styling for new github PR body details/summary

Gemfile.lock
=> DEV: uses onebox 2.2.12

app/mailers/user_notifications.rb, app/models/reviewable_queued_post.rb, app/services/notification_emailer.rb, config/locales/server.en.yml, spec/mailers/user_notifications_spec.rb, spec/services/notification_emailer_spec.rb
We now send an email when a queued post is approved, and we create a notification.
=> FEATURE: Send an email notification when a post is approved.

plugins/poll/assets/javascripts/controllers/poll-ui-builder.js.es6, plugins/poll/assets/javascripts/discourse/templates/modal/poll-ui-builder.hbs, plugins/poll/assets/stylesheets/common/poll-ui-builder.scss, plugins/poll/assets/stylesheets/desktop/poll-ui-builder.scss, plugins/poll/assets/stylesheets/mobile/poll-ui-builder.scss, plugins/poll/config/locales/client.en.yml, plugins/poll/plugin.rb, plugins/poll/test/javascripts/acceptance/poll-builder-enabled-test.js.es6, plugins/poll/test/javascripts/controllers/poll-ui-builder-test.js.es6
=> UX: Improve poll builder UI

app/controllers/admin/users_controller.rb
As suggested by eviltrout in
https://github.com/discourse/discourse/pull/12666
=> DEV: user suspension use .present?

app/assets/javascripts/discourse/yarn.lock
=> Update `caniuse-lite` to the latest version

app/assets/javascripts/discourse/app/helpers/raw.js
Since cd24eff5d98e74db4afe0257e4d9de1ad2556c5d, theme modules are now prefixed with the theme id. Therefore themes which defined raw-view classes will be broken
This commit updates the `raw` helper to use the resolver for looking up the view class. This automatically takes care of trying theme/plugin paths in addition to core paths.
=> FIX: Allow raw-view classes to be resolved from themes/plugins

config/locales/server.en.yml, lib/theme_store/git_importer.rb, lib/version.rb
=> SECURITY: Improve theme git import

lib/version.rb
=> Version bump to v2.7.0.beta7

app/models/global_setting.rb, config/database.yml
=> FEATURE: allow setting postgres connection variables via environment

app/assets/javascripts/discourse/ember-cli-build.js
=> FIX: `ember build` was not adding digests to additional bundles

app/assets/javascripts/discourse/app/routes/unknown.js, app/assets/javascripts/discourse/tests/acceptance/unknown-test.js
=> FIX: handle permalinks with query parameters

Gemfile.lock, app/assets/javascripts/discourse/app/initializers/onebox-decorators.js, app/assets/stylesheets/common/base/onebox.scss
=> UX: moves from summary/details to a button to expand github body

app/assets/javascripts/discourse/app/controllers/composer.js, app/assets/javascripts/discourse/app/controllers/edit-slow-mode.js, config/locales/client.en.yml, config/locales/server.en.yml
=> FEATURE: Tweak slow mode messages and intervals

app/assets/javascripts/discourse/app/templates/modal/create-invite.hbs, app/assets/javascripts/discourse/tests/acceptance/create-invite-modal-test.js, app/assets/stylesheets/common/base/modal.scss, app/assets/stylesheets/desktop/modal.scss
Reduce the width of the modal to make it consistent with other modals
and use the full width for inputs with a button on the right side.
Before:
After:
=> UX: Minor styling improvements to invites

app/assets/javascripts/discourse/app/controllers/edit-slow-mode.js, config/locales/client.en.yml
=> FEATURE: In slow mode dialog make "Enabled Until" mandatory

lib/backup_restore/database_restorer.rb, spec/lib/backup_restore/database_restorer_spec.rb
Follow-up to 0ec5fd5262647633399e856b0fba93735f6d6c11
=> FIX: Update database_restorer to avoid shell use

app/assets/javascripts/discourse/app/lib/screen-track.js, app/assets/javascripts/discourse/app/pre-initializers/inject-discourse-objects.js
This event can be used by analytics plugins.
=> DEV: Add app event "topic:timings-sent"

app/assets/javascripts/select-kit/addon/components/composer-actions.js
=> FEATURE: Show the slow mode indicator in composer

app/assets/stylesheets/mobile/modal.scss
=> UX: Mobile styling for discard draft modal buttons

app/assets/stylesheets/mobile/modal.scss
=> DEV: Fix linting

app/assets/javascripts/discourse/app/templates/components/categories-boxes.hbs
=> FEATURE: Add plugin outlet for category-box-below-each-category

script/import_scripts/vbulletin.rb
The regular vBulletin importer does not import attachments which haven't been referenced inside the post. vBulletin supports this way of attaching and will just show the attachments at the end of the post. After our migration we lost roughly 25% of attachments due to this. I developed this fix which i successfully ran on our production env.
Fixed things:
- Will import all unreferenced attachments
- Allows resuming und will not append attachments twice
- Add codepath that will speedup resuming before falling back to upload deduplication for the remaining attachments
FYI: The vBulletin 5 importer seems to be not affected. I opted not to fully reuse the vB5 code, but to fix the old code as simple as possible. (During research i found someone working a vB5 bulk importer: …
=> FIX: vBulletin importer should import unreferenced attachments

app/assets/javascripts/discourse/app/templates/components/categories-boxes-with-topics.hbs, app/assets/javascripts/discourse/app/templates/components/categories-boxes.hbs, app/assets/stylesheets/common/base/category-list.scss
=> FEATURE: Topic count in category boxes

config/locales/server.en.yml
=> added "in kB" to email total attachment limit

app/assets/javascripts/discourse/app/templates/components/signup-cta.hbs, app/assets/stylesheets/common/base/topic-post.scss, app/assets/stylesheets/desktop/topic-post.scss, app/assets/stylesheets/mobile/topic-post.scss, config/locales/client.en.yml
=> UX: Update signup cta styles

config/locales/client.en.yml
=> COPYEDIT: remove one unnecessary word from upload dialog

app/models/theme.rb, spec/models/theme_spec.rb
=> FIX: Use CDN urls for theme uploads

app/assets/stylesheets/desktop/topic-list.scss
=> UX: Wider drop down for top page select kit

app/assets/stylesheets/desktop/components/user-card.scss, app/assets/stylesheets/mobile/components/user-card.scss
=> UX: improve user card control layout for long text

app/assets/stylesheets/desktop/latest-topic-list.scss, app/assets/stylesheets/desktop/topic-list.scss
=> FIX: Revert color of post-map

config/locales/server.en.yml
Let's JITeach users about trust levels if/when they hit the daily ❤️ limit.
=> COPY: Add a JIT when user hits likes rate limit

app/assets/javascripts/admin/addon/models/report.js, app/assets/javascripts/admin/addon/templates/components/admin-report-table-header.hbs, app/assets/stylesheets/mobile/admin_report_table.scss
@jjaffeux  To test it out locally, do try it with this PR https://github.com/discourse/discourse-reactions/pull/73
=> UX: adds emoji in the table-title of admin-report-table

app/assets/javascripts/discourse/app/components/d-editor.js
=> DEV: Fix flaky Ember test

app/assets/javascripts/discourse/app/templates/components/date-input.hbs, app/assets/javascripts/discourse/app/templates/components/date-time-input.hbs, app/assets/stylesheets/common/base/modal.scss, plugins/poll/assets/javascripts/controllers/poll-ui-builder.js.es6, plugins/poll/assets/javascripts/discourse/templates/modal/poll-ui-builder.hbs, plugins/poll/config/locales/client.en.yml
This pull requests bring several improvements to polls plugin, the more important being better poll validation.
=> Improve validation for polls and improve builder

app/assets/javascripts/discourse/app/components/group-post.js, app/assets/javascripts/discourse/app/components/user-card-contents.js, app/serializers/group_post_user_serializer.rb
Add primary group CSS class target in group post list, and in usercards.
=> Add primary group classes

app/assets/javascripts/discourse/app/components/group-membership-button.js
=> DEV: Add group join/leave events

app/assets/javascripts/discourse/lib/bootstrap-json/index.js
=> FIX: Forward all the HTTP headers through when we bootstrap Ember CLI

plugins/discourse-local-dates/assets/stylesheets/common/discourse-local-dates.scss
=> UX: correctly shows outline around focused input time

app/assets/stylesheets/common/base/_topic-list.scss, app/assets/stylesheets/desktop/topic-list.scss, app/assets/stylesheets/mobile/topic-list.scss
The alignment here needed some maintenance; I also improved spacing and increased the font size on mobile to better match the desktop style. 
Before:
After:
=> UX: Improve alignment and spacing of category headers

app/assets/javascripts/admin/addon/components/admin-user-field-item.js, app/assets/javascripts/admin/addon/templates/components/admin-user-field-item.hbs, app/assets/javascripts/discourse/app/widgets/search-menu-results.js, app/assets/stylesheets/common/base/search-menu.scss, app/controllers/admin/user_fields_controller.rb, app/models/user.rb, app/models/user_custom_field.rb, app/models/user_field.rb, app/serializers/search_result_user_serializer.rb, app/serializers/user_field_serializer.rb, app/services/search_indexer.rb, config/locales/client.en.yml, db/migrate/20210420015635_add_searchable_to_user_fields.rb, lib/search.rb, spec/lib/search_spec.rb, spec/services/search_indexer_spec.rb
When the admin creates a new custom field they can specify if that field should be searchable or not.
That setting is taken into consideration for quick search results.
=> FEATURE: the ability to search users by custom fields

spec/requests/tag_groups_controller_spec.rb
This PR should stop this test case from failing randomly.
=> DEV: Improve tag groups test

lib/guardian/post_guardian.rb, lib/guardian/topic_guardian.rb, lib/post_merger.rb, spec/components/post_merger_spec.rb
=> FEATURE: TL4 & category mods can merge posts

lib/theme_store/git_importer.rb
Followup to 0a6fab564f7533d87f02272c3febf622b27dd366
=> FIX: Remove whitespace from theme git versions

lib/content_security_policy/default.rb
=> FIX: Ember CLI Live Reload was not supported by the CSP

app/assets/javascripts/discourse/lib/bootstrap-json/index.js
=> FIX: Recent regression meant we were proxying qunit when we shouldn't

app/models/user_summary.rb, app/serializers/user_summary_serializer.rb
=> FEATURE: include avatar flair on the avatars listed in a user summary’s “Most…” sections

app/assets/javascripts/discourse/app/components/discovery-topics-list.js, app/assets/javascripts/discourse/app/mixins/bulk-topic-selection.js, app/assets/javascripts/discourse/app/models/topic-tracking-state.js, app/assets/javascripts/discourse/tests/helpers/site-settings.js, app/assets/javascripts/discourse/tests/unit/models/nav-item-test.js, app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js, app/controllers/topics_controller.rb, app/models/topic_tracking_state.rb, app/serializers/current_user_serializer.rb, lib/topic_query.rb
This reverts commit 45df579db05a133eaeb55693827a1ec7c2690b43.
This was causing huge browser freezes and crashes.
=> Revert "DEV: Improving topic tracking state code (#12555)"

app/assets/stylesheets/common/select-kit/toolbar-popup-menu-options.scss
=> UI: ensures toolbar gear button has identic color and height

app/controllers/embed_controller.rb, app/views/embed/topics.html.erb, spec/requests/embed_controller_spec.rb
=> FEATURE: Small improvements to the topic list embed

lib/version.rb
=> Version bump to v2.7.0.beta8

app/assets/javascripts/discourse/app/components/discourse-root.js, app/assets/javascripts/discourse/app/templates/application.hbs
We can use this for grids and footers and such, rather than having to
rely on `#main > div` selectors.
=> DEV: Add top level `<div>`

app/assets/javascripts/discourse/lib/bootstrap-json/index.js
I think this was a find-and-replace error 😄
=> DEV: Fix `BAD CSRF` errors for admin POST requests when on Ember CLI

app/assets/javascripts/discourse/app/initializers/live-development.js
This updates the preview_theme_id preservation logic to use more recent, robust, browser APIs. It also adds support for preserving the `?pp=async-flamegraph` parameter which is proposed in https://github.com/MiniProfiler/rack-mini-profiler/pull/494
=> DEV: Update pushState and replaceState development patches

config/unicorn.conf.rb, lib/discourse.rb
This commit makes a few changes to improve boot time in development environments. It will have no effect on production boot times.
- Skip the SchemaCache warmup. In development mode, the SchemaCache is refreshed every time there is a code change, so warmup is of limited use.
- Skip warming up PrettyText. This adds ~2s to each web worker's boot time. The vast majority of requests do not use PrettyText, so it is more efficient to defer its warmup until it's needed
- Skip the intentional 1 second pause during Unicorn worker forking. The comment (which also exists in Unicorn's documentation) suggests this works around a Unix signal handling bug, but I haven't been able to locate any more information. Skipping it in dev will significantly speed up boot. If we start to see issues, we can revert …
=> DEV: Improve `bin/unicorn` boot time in development environment

lib/guardian/post_guardian.rb
=> FIX: topic might be nil at this stage

app/assets/stylesheets/common/foundation/mixins.scss, spec/components/stylesheet/compiler_spec.rb
=> DEV: Support referencing public images in plugins in SCSS

README.md
=> DOC: adds a link to teams.discourse.com

app/assets/javascripts/discourse/app/components/latest-topic-list-item.js
For consistency, and because I need them for a customer theme.
=> FEATURE: Add more class names to latest-topic-list-item

config/locales/client.en.yml
=> UX: update copy on the notifications empty panel

app/assets/javascripts/admin/addon/templates/components/watched-word-form.hbs, app/assets/stylesheets/common/admin/staff_logs.scss, config/locales/client.en.yml
=> UX: Admin watched words UI tweaks

spec/rails_helper.rb
=> DEV: removes unused set_env

spec/support/helpers.rb
=> DEV: remove unused Helpers::StubbedJob

app/assets/javascripts/pretty-text/engines/discourse-markdown/watched-words-replace.js
@ZogStriP I was too quick with the Merge button on the other PR.
=> DEV: tiny refactor in watched words

app/assets/javascripts/discourse/lib/bootstrap-json/index.js
=> Add Mini Profiler support to Ember CLI

app/assets/stylesheets/common/base/_topic-list.scss, app/assets/stylesheets/mobile/topic-list.scss
=> UX: Improve category controls on smallest devices

app/assets/javascripts/discourse/lib/bootstrap-json/index.js
In development using ember cli we were missing timings for the first req
=> DEV: show profiler badge for first request

app/assets/javascripts/discourse/app/templates/tags/show.hbs
=> DEV: Fix tags/show template lint errors

spec/lib/upload_creator_spec.rb
I think this test was duplicated on accident. We test for the
exact thing a few lines up.
=> DEV: Remove duplicate test

lib/plugin/instance.rb, lib/topic_view.rb, spec/components/topic_view_spec.rb, spec/requests/topics_controller_spec.rb
Allow plugins to extend TopicView to filter posts
=> FEATURE: ability to register custom filters for posts

lib/version.rb
=> Version bump to v2.7.0.beta9

app/assets/javascripts/discourse/app/components/d-editor.js
=> DEV: Fix flaky d-editor test

app/models/category.rb
=> DEV: Extract out compound conditional

bin/ember-cli
Was previously rejecting all args.
Fix logic to properly filter args
=> FIX: properly filter ember-cli args

app/assets/javascripts/vendor.js, lib/tasks/javascript.rake, package.json, vendor/assets/javascripts/intersection-observer.js, yarn.lock
=> Revert "DEV: Drop old IE11 intersection-observer references" (#13017)

app/controllers/application_controller.rb, config/locales/server.en.yml
This will allow to correctly catch it client side and display a correct error.
=> DEV: rescues site setting missing exception

app/views/qunit/theme.html.erb
=> DEV: Minor changes to `/theme-qunit` landing page

package.json, vendor/assets/javascripts/handlebars.js, vendor/assets/javascripts/handlebars.runtime.js, yarn.lock
Release notes: https://github.com/handlebars-lang/handlebars.js/blob/master/release-notes.md#v477---february-15th-2021
=> Update handlebars from 4.7.6 to 4.7.7

app/assets/stylesheets/publish.scss, plugins/discourse-presence/assets/stylesheets/presence.scss
=> DEV: Remove SCSS color vars fallbacks

app/assets/javascripts/admin/package.json, app/assets/javascripts/discourse-common/package.json, app/assets/javascripts/discourse-hbr/package.json, app/assets/javascripts/discourse-widget-hbs/package.json, app/assets/javascripts/pretty-text/package.json, app/assets/javascripts/select-kit/package.json, app/assets/javascripts/truth-helpers/package.json, app/assets/javascripts/yarn.lock
…to match the version used in the app.
=> DEV: Update ember-cli across all in-repo addons

lib/version.rb
=> Version bump to v2.8.0.beta1

config/locales/server.en.yml, config/site_settings.yml, lib/edit_rate_limiter.rb, spec/components/post_revisor_spec.rb
=> FEATURE: Increase daily edit limits proportionally to trust level

lib/stylesheet/manager.rb, spec/components/stylesheet/manager_spec.rb
Previously, we only precompiled the CSS for parent themes but not for
the child themes. As a result, the CSS for child themes were being
compiled during the first request which made the respond time high for
that request.
=> PERF: Precompile child theme stylesheets.

app/assets/javascripts/discourse/app/components/category-title-link.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/lib/register-topic-footer-button.js, app/assets/javascripts/discourse/app/models/user.js, app/mailers/rejection_mailer.rb, app/models/topic.rb, config/initializers/200-first_middlewares.rb, lib/auth/authenticator.rb, lib/auth/managed_authenticator.rb, lib/tasks/emails.rake
Split per https://github.com/discourse/discourse/pull/12779#issuecomment-845553581
=> Spelling comments

app/assets/javascripts/admin/addon/components/admin-watched-word.js, app/assets/javascripts/admin/addon/controllers/modals/admin-watched-word-test.js, app/assets/javascripts/admin/addon/templates/components/admin-watched-word.hbs, app/assets/javascripts/admin/addon/templates/components/watched-word-form.hbs, app/assets/javascripts/admin/addon/templates/modal/admin-watched-word-test.hbs, app/assets/javascripts/admin/addon/templates/watched-words-action.hbs, app/assets/javascripts/discourse/tests/acceptance/admin-watched-words-test.js, app/assets/javascripts/discourse/tests/fixtures/watched-words-fixtures.js, app/assets/stylesheets/common/admin/staff_logs.scss, app/serializers/watched_word_serializer.rb, config/locales/client.en.yml
The modal used to show only the matches, without the replacement or list of tags.
=> FEATURE: Support tag and replace in watched words in test modal

app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/widgets/topic-map.js
Allow plugins to add custom css classes to topic participants
=> DEV: add plugin hook to add topic participant classes

config/locales/server.en.yml
=> minor refinements to the Universal Rules

app/assets/javascripts/discourse/app/models/post.js, config/locales/client.en.yml, lib/post_destroyer.rb, plugins/discourse-narrative-bot/spec/discourse_narrative_bot/advanced_user_narrative_spec.rb, spec/components/post_destroyer_spec.rb
based on feedback from Matt Haughey, we don't need to use so many words when describing a deleted topic or post.
=> simplify post and topic deletion language

app/assets/javascripts/discourse/app/index.html, app/assets/stylesheets/common/foundation/base.scss, app/views/layouts/application.html.erb
Looks like a vestige of Ember 1.x?
=> DEV: Remove unused `offscreen-content`

app/assets/javascripts/admin/package.json, app/assets/javascripts/discourse/package.json, app/assets/javascripts/yarn.lock
=> DEV: Add peer dependencies

app/assets/javascripts/discourse/app/components/d-modal-body.js, app/assets/javascripts/discourse/app/components/d-modal.js
=> FIX: Better focus support for modals

app/assets/javascripts/discourse/app/widgets/post.js
=> A11Y: Add heading role for post titles.

app/helpers/application_helper.rb, config/nginx.sample.conf, config/routes.rb, lib/tasks/assets.rake
=> FEATURE: Normalize the service worker route

app/assets/javascripts/discourse/app/widgets/header.js, app/assets/stylesheets/common/base/discourse.scss, config/locales/client.en.yml
=> UX: Users can postpone discobot's tutorial.

app/assets/javascripts/select-kit/addon/components/categories-admin-dropdown.js
=> UX: change categories page dropdown to a wrench

app/models/theme.rb, app/models/theme_field.rb
=> DEV: Define theme test modules under a `/test` subdirectory

app/assets/javascripts/discourse/app/components/footer-nav.js
Body class added on load to ensure fixed elements are positioned correctly when styled relative to bottom of viewport in mobile app.
=> FIX: add body class and remove jQuery usage in footer-nav component

app/assets/javascripts/discourse/app/widgets/header.js
=> UX: Add auto focus to hamburger and user menu dropdowns

app/assets/javascripts/discourse/app/widgets/header.js
=> FIX: We can't use `?.` yet

script/import_scripts/flarum_import.rb
PR to push basic Flarum Import script to main
https://meta.discourse.org/t/flarum-to-discourse-migration-script/191510
=> DEV: Add Flarum to Discourse Import Script

app/models/watched_word.rb, app/services/word_watcher.rb, config/locales/client.en.yml, config/locales/server.en.yml, lib/new_post_manager.rb, spec/requests/posts_controller_spec.rb
This is a new type of watched word, meant as a replacement to `auto_silence_first_post_regex`. It replaces PR #12585 too with a more simple implementation.
=> FEATURE: Silence watched word

app/assets/javascripts/admin/addon/components/watched-word-form.js, app/assets/javascripts/admin/addon/controllers/admin-watched-words-action.js, app/assets/javascripts/admin/addon/controllers/admin-watched-words.js, app/assets/javascripts/admin/addon/models/watched-word.js, app/assets/javascripts/admin/addon/routes/admin-watched-words-action.js, app/assets/javascripts/admin/addon/routes/admin-watched-words.js, app/assets/javascripts/admin/addon/templates/watched-words-action.hbs, app/assets/javascripts/admin/addon/templates/watched-words.hbs, app/assets/javascripts/pretty-text/engines/discourse-markdown/censored.js, app/assets/javascripts/pretty-text/engines/discourse-markdown/watched-words-replace.js, app/serializers/watched_word_list_serializer.rb
Watched words with the recent changes became a bit more complex than it needs to be. In this PR I removed a lot of dead or duplicated code.
=> DEV: Simplify watched word code

plugins/discourse-narrative-bot/plugin.rb, plugins/discourse-narrative-bot/spec/discourse_narrative_bot/advanced_user_narrative_spec.rb
Includes a small refactor/fix, because `return` isn't allowed in blocks.
=> FIX: TL2 promotion message from discobot didn't use user locale

app/assets/javascripts/discourse/app/widgets/widget-dropdown.js, app/assets/javascripts/discourse/tests/integration/widgets/widget-dropdown-test.js
The widget should accept the disabled option.
In that case, CSS class "disabled".
In addition, after click dropdown will not be shown.
=> FEATURE: extend widget-dropdown to accept disabled option

config/locales/server.en.yml
=> DEV: Add deprecation notice to site setting description

app/assets/javascripts/discourse/app/components/badge-card.js, app/assets/javascripts/discourse/app/controllers/user-badges.js, app/assets/javascripts/discourse/app/models/user-badge.js, app/assets/javascripts/discourse/app/templates/components/badge-card.hbs, app/assets/javascripts/discourse/app/templates/user/badges.hbs, app/assets/javascripts/discourse/tests/helpers/create-pretender.js, app/assets/javascripts/discourse/tests/unit/models/user-badge-test.js, app/assets/stylesheets/common/base/user-badges.scss, app/assets/stylesheets/desktop/user.scss, app/controllers/user_badges_controller.rb, app/models/user_badge.rb, app/serializers/detailed_user_badge_serializer.rb, config/locales/client.en.yml, config/routes.rb, db/migrate/20210218144656_add_is_favorite_to_user_badge.rb, lib/svg_sprite/svg_sprite.rb, spec/requests/user_badges_controller_spec.rb
=> FEATURE: lets users favorite 2 badges to show on user-card

app/models/group.rb, spec/models/group_spec.rb
=> DEV: calls user_added_to_group on group/TL enforcement

spec/models/user_spec.rb
Follow-up to 624edac3bbf96a36c20daaf2318d9caece540408
=> DEV: Fix spec

app/assets/javascripts/discourse-shims.js, app/assets/javascripts/discourse/app/controllers/reorder-categories.js, app/assets/javascripts/discourse/app/mixins/buffered-content.js, vendor/assets/javascripts/buffered-proxy.js
This version matches the one we have in discourse/package.json.
Fixes an issue with saving topic name form w/o any changes.
=> FIX: Update non-Ember CLI ember-buffered-proxy

app/assets/javascripts/discourse/app/components/bookmark.js
=> FIX: translation issue on the bookmark modal

lib/svg_sprite/svg_sprite.rb
Follow-up to 0700e9382d551e4948b493e1219f3119e52bcae4
=> DEV: Fix incorrect optimization in SvgSprite take 2.

spec/models/report_spec.rb
Fabrication does not guarantee the ordering of records in anyway.
=> DEV: Remove unused comments from tests.

app/assets/javascripts/discourse/app/routes/edit-category.js, app/assets/javascripts/discourse/tests/acceptance/category-edit-test.js, app/assets/javascripts/discourse/tests/fixtures/category-fixtures.js, app/serializers/category_serializer.rb, spec/serializers/category_serializer_spec.rb
=> SECURITY: Do not allow unauthorized access to category edit UI

lib/tasks/docker.rake, lib/tasks/qunit.rake, script/docker_test.rb, spec/models/optimized_image_spec.rb, spec/requests/user_avatars_controller_spec.rb
The second attempt at #10041 now that all our plugins use GitHub Actions CI instead.
=> DEV: Remove the remaining Travis code

app/models/topic_tracking_state.rb
This allows us to do DISTINCT on the topic_id to remove
duplicates (e.g. in extensions to the report SQL), and
also introduces an additional_join_sql string to allow
extensions to JOIN additional tables.
=> FIX: Change order of topic_tracking_state SELECT SQL

app/models/theme.rb, lib/distributed_cache.rb, lib/site_icon_manager.rb, lib/stylesheet/manager.rb, lib/svg_sprite/svg_sprite.rb
Setting a key/value pair in DistributedCache involves waiting on the
write to Redis to finish. In most cases, we don't need to wait on the
setting of the cache to finish. We just need to take our return value
and move on.
=> PERF: Defer setting of distributed cache in performance critical paths.

app/models/watched_word.rb, spec/models/watched_word_spec.rb
=> DEV: Add test for link watched words

app/assets/javascripts/discourse/app/widgets/search-menu-controls.js, app/assets/stylesheets/common/base/header.scss, app/assets/stylesheets/common/base/menu-panel.scss, app/assets/stylesheets/common/base/search-menu.scss, app/assets/stylesheets/common/base/search.scss
* Matching the topic list font-size and colors
* Adding highlight color to search terms
* More consistent spacing between elements (the options button, search box alignment with left of text, etc)
* removing an old clearfix
Before:
After:
=> UX: Update search panel styles, add highlight, consistency

config/discourse_defaults.conf, lib/auth/default_current_user_provider.rb, spec/components/auth/default_current_user_provider_spec.rb, spec/integration/rate_limiting_spec.rb
=> FEATURE: Add global admin api key rate limiter

app/models/theme.rb, app/serializers/application_serializer.rb, lib/distributed_cache.rb, lib/site_icon_manager.rb, lib/stylesheet/manager.rb, lib/svg_sprite/svg_sprite.rb
See follow up commit for rational.
Follow-up to 8cfe203383367cc7a3cf31b3c3960b7b7aac92ef
=> PERF: Defer setting of distributed cache in more spots. 

app/models/post_action_type.rb, app/serializers/application_serializer.rb, spec/models/post_action_type_spec.rb
The bug was introduced in dc10bdee3dd23ae8d2acb4729c119e4b0b3f4853
=> FIX: Clear post action types application serializer fragment cache.

app/models/category.rb
See follow up commit for rational.
Follow-up to 8cfe203
=> PERF: Defer setting of distributed cache in category.

config/locales/client.en.yml
=> UX: Copy edit

plugins/poll/assets/stylesheets/common/poll.scss
Fixes a regression in 33cb1b7.
=> FIX: Size of emoji in poll options

app/assets/stylesheets/common/base/header.scss
=> UX: Improve tag truncation in scrolled header

spec/models/trust_level_setting_spec.rb
=> DEV: Fix another cause of the same flaky spec

lib/version.rb
=> Version bump to v2.8.0.beta2

app/assets/javascripts/discourse/app/templates/components/tag-info.hbs, config/locales/client.en.yml
=> UX: add a hint that tags can be included in tag groups on ungrouped tags

app/assets/javascripts/discourse/app/controllers/users.js, app/assets/javascripts/discourse/app/routes/users.js, app/assets/javascripts/discourse/app/templates/mobile/users.hbs, app/assets/javascripts/discourse/app/templates/users.hbs, app/assets/stylesheets/common/base/directory.scss, app/assets/stylesheets/mobile/directory.scss, config/locales/client.en.yml
Thanks this this commit, we already support filtering users by group https://github.com/discourse/discourse/commit/3cd4c82c49e6abdb140bb8900f6c61fb8c5cda7f
=> FEATURE: Add group filter to user directory

bin/ember-cli
Followup to https://github.com/discourse/discourse/pull/13336
=> DEV: bin/ember-cli standalone by default

app/assets/javascripts/discourse/app/models/post.js, app/assets/javascripts/discourse/app/widgets/post.js, app/assets/javascripts/discourse/ember-cli-build.js, app/assets/javascripts/discourse/tests/helpers/widget-test.js, app/assets/javascripts/discourse/tests/integration/components/slow-mode-info-test.js, plugins/discourse-details/test/javascripts/acceptance/details-button-test.js.es6, plugins/discourse-details/test/javascripts/lib/details-cooked-test.js.es6, plugins/discourse-local-dates/test/javascripts/acceptance/local-dates-composer-test.js.es6, plugins/discourse-local-dates/test/javascripts/lib/date-with-zone-helper-test.js.es6, plugins/discourse-local-dates/test/javascripts/lib/local-date-builder-test.js.es6, plugins/poll/assets/javascripts/controllers/poll-ui-builder.js.es6, plugins/poll/test/javascripts/acceptance/poll-breakdown-test.js.es6, plugins/poll/test/javascripts/acceptance/poll-builder-disabled-test.js.es6, plugins/poll/test/javascripts/acceptance/poll-builder-enabled-test.js.es6, plugins/poll/test/javascripts/acceptance/poll-in-reply-history-test.js.es6, plugins/poll/test/javascripts/acceptance/poll-pie-chart-test.js.es6, plugins/poll/test/javascripts/acceptance/poll-quote-test.js.es6, plugins/poll/test/javascripts/acceptance/polls-bar-chart-test-desktop.js.es6, plugins/poll/test/javascripts/acceptance/polls-bar-chart-test-mobile.js.es6, plugins/poll/test/javascripts/controllers/poll-ui-builder-test.js.es6, plugins/poll/test/javascripts/helpers/display-poll-builder-button.js.es6, plugins/poll/test/javascripts/widgets/discourse-poll-option-test.js.es6, plugins/poll/test/javascripts/widgets/discourse-poll-standard-results-test.js.es6, plugins/poll/test/javascripts/widgets/discourse-poll-test.js.es6
=> FIX: Lots of plugin tests were using old, non-Ember compatible CLI APIs

app/controllers/bootstrap_controller.rb, spec/requests/bootstrap_controller_spec.rb
=> FIX: can't bootstrap with ember-cli when login_required is enabled

app/helpers/application_helper.rb
https://meta.discourse.org/t/missing-open-graph-og-type/177360?u=falco
=> FEATURE: Add type=website OpenGraph meta tag

app/assets/javascripts/discourse-common/addon/lib/get-url.js, app/assets/javascripts/discourse/app/lib/click-track.js, app/assets/javascripts/discourse/tests/unit/lib/click-track-test.js
=> FIX: Some absolute links were causing full page reloads

config/locales/server.en.yml
Was there ever a contact form? 🤔
=> UX: Remove reference to contact form in setting

app/assets/javascripts/admin/addon/routes/admin-search-logs-term.js, app/assets/javascripts/discourse/app/controllers/full-page-search.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/lib/search.js, app/assets/javascripts/discourse/app/routes/full-page-search.js, app/assets/javascripts/discourse/app/widgets/search-menu.js, app/assets/javascripts/discourse/tests/unit/lib/search-test.js, app/serializers/search_post_serializer.rb
=> DEV: Add plugin API to extend search results

lib/file_store/to_s3_migration.rb
Uploading lots of small files can be made significantly faster by parallelizing the `s3.put_object` calls. In testing, an UPLOAD_CONCURRENCY of 10 made a large restore 10x faster. An UPLOAD_CONCURRENCY of 20 made the same restore 18x faster.
This commit is careful to parallelize as little as possible, to reduce the chance of concurrency issues. In the worker threads, no database transactions are performed. All modification of shared objects is controlled with a mutex.
Unfortunately we do not have any existing tests for the `ToS3Migration` class. This change has been tested with a large site backup (120k uploads totalling 45GB)
=> FEATURE: Upload to s3 in parallel to speed up backup restores

app/models/category.rb, app/models/category_tag.rb, app/models/category_tag_group.rb, app/models/site.rb, app/serializers/site_serializer.rb, lib/guardian/category_guardian.rb, spec/serializers/site_serializer_spec.rb
This reverts commit 7dc0f88acd7cef0f4cc5944ef634f8ecc4886a27.
=> Revert "PERF: Cache categories in Site model."

app/assets/javascripts/admin/addon/routes/admin-reports-show.js
=> FIX: prevents mode to be forced to un-existing mode

lib/tasks/smoke_test.rake, test/run-qunit.js
The purpose of this is to allow us to catch regressions for a feature we've built recently that allows theme tests to run in production. We recently had a regression that we didn't notice for days, so to prevent that from happening again we'll use this in our internal CI pipelines.
=> DEV: Add optional theme test step to the `smoke:test` rake task

db/migrate/20210617183010_add_automatic_column_directory_columns.rb
=> FIX: Broken DB issue following a reverted migration

db/migrate/20210617202227_change_automatic_on_directory_columns_to_bool.rb
=> FIX: Drop and recreate  column properly for directory_columns

app/assets/javascripts/admin/addon/templates/components/site-settings/tag-list.hbs
=> DEV: removes maximum limit on tag list site setting

app/models/api_key_scope.rb, config/locales/client.en.yml, spec/requests/admin/api_controller_spec.rb
=> FEATURE: An API key scope for editing posts.

plugins/poll/assets/javascripts/widgets/discourse-poll.js.es6, plugins/poll/test/javascripts/acceptance/poll-results-test.js.es6
This pull request fixes two bugs that would either show too few or too many users.
=> FIX: Do not display twice a user who changed vote

app/assets/stylesheets/common/topic-timeline.scss
=> UX: Fix mobile progress bar button alignment

app/assets/stylesheets/common/base/modal.scss
=> UX: Fix jump-to-post layout on mobile

app/models/category.rb, app/models/category_tag.rb, app/models/category_tag_group.rb, app/models/site.rb, app/serializers/site_serializer.rb, lib/guardian/category_guardian.rb, spec/models/site_spec.rb, spec/serializers/site_serializer_spec.rb
Follow-up to aa4f0aee67d6f9802856ab4abb5a7560359854b6.
Fixed the security problem in the previous attempt.
=> PERF: Cache categories in Site model take 2.

spec/components/topic_view_spec.rb, spec/requests/groups_controller_spec.rb
stub_const was introduced in https://github.com/discourse/discourse/commit/6fe78cd542194576b0a02ff52cb9dbaa79bba82d
=> DEV: Replace const munging in specs with stub_const helper

lib/stylesheet/manager.rb, spec/components/stylesheet/manager_spec.rb
Follow-up to 8e3691d5370bb95d99fe750f46287763721fcc9c
=> FIX: Color scheme stylesheet not loaded when no default theme is set.

lib/stylesheet/manager.rb, spec/components/stylesheet/manager_spec.rb
Follow-up to 8e3691d5370bb95d99fe750f46287763721fcc9c
=> FIX: Multiple links being generated for non-theme targets.

lib/stylesheet/watcher.rb
Follow-up to 8e3691d5370bb95d99fe750f46287763721fcc9c
=> DEV: Fix broken stylesheet watcher.

app/assets/javascripts/discourse/tests/acceptance/keyboard-shortcuts-test.js
Also add extra logging for test failures
=> DEV: Try fix flaky dismiss keyboard specs

app/assets/javascripts/admin/addon/models/report.js
=> FIX: ensures average is applied on last incomplete segment

app/assets/javascripts/discourse/app/routes/users.js
=> FIX: Absolute path for directory-columns.json

.byebug_history, app/controllers/directory_items_controller.rb, spec/requests/directory_items_controller_spec.rb
=> FIX: Load more users URL respect group param

app/controllers/directory_items_controller.rb, app/serializers/directory_item_serializer.rb
=> PERF: Remove n+1 in user directory

app/jobs/scheduled/clean_up_uploads.rb, app/models/upload.rb, lib/shrink_uploaded_image.rb, script/downsize_uploads.rb, spec/lib/shrink_uploaded_image_spec.rb, spec/models/upload_spec.rb
* Only shrink images that are used in Posts and no other models
* Don't save the upload if the size is the same
=> DEV: Improve `script/downsize_uploads.rb`

app/models/site.rb, app/serializers/site_category_serializer.rb, lib/guardian/category_guardian.rb, spec/models/site_spec.rb
Follow-up to 0e4b8c5318569ef7e7a111563709699e3b9ce219
=> FIX: Missing category edit icon.

app/assets/javascripts/admin/addon/components/admin-watched-word.js, app/assets/javascripts/admin/addon/templates/components/admin-watched-word.hbs, app/assets/javascripts/discourse/tests/acceptance/admin-watched-words-test.js, app/assets/stylesheets/common/admin/staff_logs.scss
=> FIX: only delete the word/phrase when the 'x' icon is clicked

app/assets/javascripts/discourse/app/components/directory-table.js, app/assets/javascripts/discourse/app/templates/components/directory-table.hbs, app/assets/stylesheets/common/base/directory.scss
Horizontal scroll on top will show up if the bottom of the table is below the viewport. The idea for this came from https://stackoverflow.com/questions/3934271/horizontal-scrollbar-on-top-and-bottom-of-table
=> UX: Horizontal scroll bar on top of user directory (when needed)

app/assets/javascripts/discourse/app/controllers/topic.js, app/assets/javascripts/discourse/tests/unit/models/topic-test.js
The error was:
```
↪ Unit | Model | topic::recover [✔]
↪ Unit | Utility | emoji::emojiUnescape [✔]
↪ Unit | Utility | pretty-text::quoting a quote [✔]
↪ Unit | Utility | click-track::routes to internal urlsUnhandled request in test environment: /forum/t/1234/recover (PUT)
Error: Unhandled request in test environment: /forum/t/1234/recover (PUT)
at Pretender.server.unhandledRequest (discourse/tests/setup-tests:173:15)
at Pretender.handleRequest (pretender:400:14)
at FakeRequest.send (pretender:169:21)
at Object.send (jquery:10100:10)
at Function.ajax (jquery:9683:15)
at performAjax (discourse/app/lib/ajax:174:19)
at eval (discourse/app/lib/ajax:183:11)
at invokeCallback (ember:63104:17)
at publish (ember:63087:9)
at eval (ember:57463:16)
[✘]
```
Included:
* DEV: Don't duplicate a function
=> DEV: Fix a leaky test

spec/lib/search_spec.rb
More precise expectations for search spec
=> FIX: flaky search-spec

app/assets/javascripts/admin/addon/models/user-field.js, app/assets/javascripts/discourse/app/templates/components/user-fields/multiselect.hbs, config/locales/client.en.yml
Ability to register new user custom field by plugins.
=> FEATURE: add multiselect user custom field

app/assets/javascripts/admin/addon/components/admin-report.js
Testing this is tricky because it's wrapped in a `try/catch`.
=> FIX: Some admin reports (notably backups) were not showing up

app/assets/javascripts/admin/addon/components/admin-report.js
=> FIX: ensures we don't apply charts options to other modes

app/controllers/admin/watched_words_controller.rb, app/models/user_history.rb, app/models/watched_word.rb, app/services/staff_action_logger.rb, config/locales/client.en.yml, spec/requests/admin/watched_words_controller_spec.rb, spec/services/staff_action_logger_spec.rb
=> FEATURE: add staff action logs for watched words

app/assets/javascripts/discourse/app/controllers/preferences/profile.js, app/assets/javascripts/discourse/tests/unit/controllers/preferences-profile-test.js
Multiselect data can be saved but when all options are removed then data are not cleared
Ajax function is removing an empty array from request data. In that case, we should change `[]` to `null`.
We need that empty values to properly empty data.
=> FIX: problem when [] custom field is send

lib/guardian/post_guardian.rb, spec/components/guardian_spec.rb, spec/components/post_merger_spec.rb
=> FIX: TL4 users cannot delete others posts

app/assets/javascripts/discourse/app/initializers/live-development.js, app/assets/javascripts/discourse/app/lib/theme-selector.js, config/initializers/014-track-setting-changes.rb, lib/stylesheet/compiler.rb, lib/stylesheet/manager.rb, lib/stylesheet/manager/builder.rb, lib/stylesheet/watcher.rb, lib/tasks/assets.rake, spec/components/stylesheet/importer_spec.rb, spec/components/stylesheet/manager_spec.rb
These changes caused several issues with color schemes and fonts, reverting for now.
=> DEV: Revert stylesheet refactors

script/discourse
=> FIX: typo in discourse

lib/stylesheet/manager.rb, spec/components/stylesheet/manager_spec.rb
This fix was reverted in 128fdf9 but
fix is still relevant.
=> FIX: Child themes being precompiled multiple times take 2.

app/assets/javascripts/discourse/tests/acceptance/keyboard-shortcuts-test.js
Page was not scrolled to top so buttons were not in
viewport, so they were being hidden.
await scrollTo() helper does not seem to work, so using
jquery instead
For whatever reason normal js scrollTop = 0 doesn't work
either...
=> DEV: Try fix keyboard shortcut acceptance tests

spec/serializers/topic_view_serializer_spec.rb
This is just a hunch, but this is quite a complex test.
I think that there is some timing issue where the jobs
enqueued for generating the thumbnails via the serializer
thumbnails method and they aren't generated in time before
we do the json[:thumbnails] check. Split the tests up
into two, with one checking the right jobs are enqueued
and another with Jobs.run_immediately! that checks that
json[:thumbnails] is correct.
=> DEV: Try fix flaky topic view serializer spec

app/assets/javascripts/discourse/app/components/composer-editor.js, app/assets/javascripts/discourse/app/lib/uploads.js, app/assets/javascripts/discourse/app/templates/components/composer-editor.hbs, app/assets/javascripts/discourse/tests/acceptance/composer-attachment-test.js, app/assets/javascripts/discourse/tests/unit/lib/uploads-test.js
=> FEATURE: pass supported file extensions to the system file picker

lib/topic_query.rb, script/import_scripts/base/lookup_container.rb, spec/helpers/application_helper_spec.rb, spec/models/topic_link_spec.rb
=> DEV: Prefer .pluck_first over .pluck.first

config/locales/client.en.yml
=> FIX: update locale keys for watched word logs

app/assets/javascripts/discourse/lib/bootstrap-json/index.js, app/controllers/bootstrap_controller.rb
It's rendered in Rails in:
https://github.com/discourse/discourse/blob/ebcc70a5bafba06b48449136eb6dd4a1db16254c/app/views/layouts/_head.html.erb#L9-L9
=> DEV: Add theme-color meta to bootstrap

Gemfile.lock, config/initializers/100-logster.rb
See also https://github.com/discourse/logster/commit/dc351fd00f283db212696c940ef3a456efc42ccb
=> DEV: Bump Logster and use full hostnames

app/assets/stylesheets/common/base/topic-post.scss
Follow-up to 37b8ce79c99f4e8dd1c5aee0d3dd8cfe1ef4249b
=> UX: Remove top border on small action after last visit line.

plugins/poll/plugin.rb, plugins/poll/spec/controllers/polls_controller_spec.rb
The endpoint validates the existence of the poll and if the current user can see it. It
will facilitate using a poll programmatically, especially if we'd like to create an external poll through a theme component.
=> DEV: An endpoint to check if the current user voted in a poll.

app/assets/javascripts/discourse/app/widgets/topic-post-visited-line.js, app/assets/stylesheets/common/base/topic-post.scss, app/assets/stylesheets/desktop/topic-post.scss, app/assets/stylesheets/mobile/topic-post.scss
Remove the calculation of width and instead switch to small action class
that automatically sets the width based on the screen size.
=> UX: Layout issues with topic last visit line.

spec/requests/omniauth_callbacks_controller_spec.rb
This cookie has not been used for a number of years, and has no effect. This commit removes it from the specs. (diff is almost entirely whitespace)
=> DEV: Remove `fsl` cookie from specs

lib/tasks/uploads.rake
This commit logs an error and moves to next upload when saving a single
upload record fails when running `uploads:fix_missing_s3` task.
=> FIX: do not stop `fix_missing_s3` task if saving an upload failed

lib/tasks/uploads.rake
ref: https://github.com/discourse/discourse/commit/935aadbfddc6ece3742163e9d878a75617292e64
=> FIX: `fix_missing_s3` task fails on failed upload (take 2)

app/assets/stylesheets/common/select-kit/flair-row.scss
=> FIX: Do not wrap flair title

config/locales/client.en.yml, config/locales/server.en.yml
=> FIX: Various translation string fixes

lib/tasks/emails.rake
meta/t/185109
Additionally, print an extra warning if the `disable_emails` site setting is set.
Example output:
```
$ bin/rake 'emails:test[]'
Testing sending to  using localhost:1025, username: with  auth.
SMTP server connection successful.
Sending to . . . 
Mail was not sent.
Reason: message.to is blank
The `disable_emails` site setting is currently set to non-staff.
Consider changing it to 'no' before performing any further troubleshooting.
```
and
```
Sending to michael@example.com. . . 
Mail accepted by SMTP server.
Message-ID: dfaf1c88-aab6-474b-b50c-8c500afb6291@localhost
If you do not receive the message, check your SPAM folder
[...]
```
=> DEV: Report message-id, skip reason in rake email:test

app/assets/stylesheets/common/base/alert.scss
=> UX: Fix z-index for new topic alert

app/assets/javascripts/discourse/app/routes/badges-index.js, app/assets/javascripts/discourse/app/routes/badges-show.js
…so we don't end up at a random point on the page after a transition.
=> FIX: Scroll to top on badge pages

app/controllers/categories_controller.rb
There is no existing hook to do _something_ when a category is saved. I want this for a plugin, where I want to create/remove an associated record when a custom field is enabled/disabled.
=> DEV: DiscourseEvent for category updated

spec/requests/api/schemas/json/admin_user_response.json
=> FIX: admin_user_response schema

script/db_timestamps_mover.rb
Some tables have constraints on columns with a date which can cause problems when moving timestamps. By now I think it's enough to just ignore them.
=> DEV: ignore some tables when updating timestamps using db_timestamps_mover

app/assets/javascripts/discourse/app/routes/application.js
=> DEV: App event when modal is closed

app/assets/javascripts/discourse/app/controllers/badges/show.js
Converted `actions` hash to `@action` and added:
```
if (!this.canLoadMore) {
return;
}
```
=> FIX: Don't try to load badges if there none left

app/assets/javascripts/discourse/app/templates/badges/show.hbs, app/assets/stylesheets/common/base/user.scss, app/assets/stylesheets/mobile/user.scss
Otherwise there's a button hugging the the viewport frame.
=> UX: Make sure there's always a margin on badges page

app/assets/javascripts/discourse/app/templates/user/badges.hbs, app/assets/javascripts/discourse/tests/acceptance/user-anonymous-test.js, app/assets/stylesheets/desktop/user.scss
No more special CSS just for this path.
=> FIX: `user/badges` grid fix

Gemfile.lock
Using `literate_randomizer` to generate random paragraph text.
=> DEV: Bump `discourse_dev_assets` to 0.0.3.

lib/discourse_dev/post.rb, lib/discourse_dev/record.rb, lib/discourse_dev/topic.rb
=> DEV: return populated data at the end of the method.

lib/onebox/engine/youtube_onebox.rb, plugins/lazy-yt/assets/javascripts/initializers/lazyYT.js, plugins/lazy-yt/assets/javascripts/lib/lazyYT.js, plugins/lazy-yt/plugin.rb, spec/lib/onebox/engine/youtube_onebox_spec.rb
=> SECURITY: Sanitize YouTube Onebox data

plugins/lazy-yt/assets/javascripts/initializers/lazyYT.js, plugins/lazy-yt/assets/javascripts/lib/lazyYT.js, plugins/lazy-yt/plugin.rb
=> SECURITY: Sanitize YouTube Onebox data (stable)

lib/version.rb
=> Version bump to v2.8.0.beta3

app/assets/javascripts/discourse/app/templates/user/summary.hbs
Fixes a regression introduced in #13719
=> FIX: User's "Top badges" grid

app/assets/javascripts/discourse/app/components/groups-form-profile-fields.js
`debounce` (and `throttle` etc.) don't work as expected if they receive a different function reference (which is what happens when passing an anonymous function) each time they're called. This PR makes the debounced function a component property and passes it to `debounce` so it's correctly debounced.
=> FIX: Debounce group name validation correctly

app/models/api_key_scope.rb, config/locales/client.en.yml
=> FEATURE: Add 'users.list' API scope

app/assets/javascripts/discourse/app/initializers/live-development.js
We have had reports of tabs freezing in Firefox and reporting an error on this line. I haven't been able to reproduce the browser error, but I suspect the `forEach` loop is at the heart of the issue, so I have replaced it with a (hopefully) safer call.
=> DEV: Refactor stylesheet live-reloading

app/assets/stylesheets/common/components/user-card.scss
=> FIX: Alignment of user badges in user card

app/assets/javascripts/admin/addon/components/themes-list.js, app/assets/javascripts/admin/addon/templates/components/themes-list.hbs, app/assets/javascripts/discourse/tests/integration/components/themes-list-test.js, app/assets/stylesheets/common/admin/customize.scss, config/locales/client.en.yml
This PR adds a search box to the themes/components list to allow admins to quickly find a theme/component with a specific name. 
Screenshot:
=> FEATURE: Add filter box to the themes/components list

spec/fixtures/onebox/githubfolder.response, spec/lib/onebox/engine/github_folder_onebox_spec.rb
=> DEV: fix test (missed a reference to master)

app/models/notification.rb, spec/models/notification_spec.rb
=> DEV: Add chat_mention notification type

lefthook.yml
=> DEV: uses main branch in lefthooks

script/version_bump.rb
=> DEV: uses main instead of master in version_bump script

app/assets/javascripts/discourse/app/models/user.js
That'll be consistent with recent changes in https://github.com/discourse/discourse/pull/13776.
=> FIX: Consider 100 years suspension as permanent (instead of 500-years suspension)

config/locales/server.en.yml
=> Fixed a typo in the 'same_site_cookies' site setting description

app/assets/javascripts/discourse/app/widgets/post.js
This is a follow-up fix to aa6daea
=> check if currentUser exists

lib/topic_query.rb, spec/components/topic_query_spec.rb, spec/requests/list_controller_spec.rb
Fixes a possible SQL injection vector.
=> SECURITY: Validate period param for top topic routes

lib/version.rb
=> Version bump to v2.8.0.beta4

app/assets/javascripts/pretty-text/engines/discourse-markdown/mentions.js
=> DEV: Export pretty text function for plugin use

lib/plugin/instance.rb
=> DEV: update doc as parameters would raise

app/assets/javascripts/discourse/app/templates/components/d-navigation.hbs
=> DEV: Add new after-create-topic-button plugin outlet

app/assets/javascripts/discourse/tests/acceptance/admin-badges-show-test.js, app/assets/javascripts/discourse/tests/fixtures/badges-fixture.js
=> DEV: prevents badges tests to log 404

config/locales/names.yml, spec/models/locale_site_setting_spec.rb
Discussion at https://meta.discourse.org/t/198066
=> use more appropriate labels for chinese UI option

app/jobs/regular/post_update_topic_tracking_state.rb, lib/post_jobs_enqueuer.rb
Same intend as b1f32f2f5717c4f55b902485794e62b8cecd8522.
=> DEV: Move private message topic tracking state publish into sidekiq.

app/controllers/users/associate_accounts_controller.rb
These do not accurately describe the methods. They were likely copy/pasted from another controller.
=> DEV: Remove incorrect method descriptions

app/assets/javascripts/discourse/lib/bootstrap-json/index.js, app/controllers/bootstrap_controller.rb, spec/requests/bootstrap_controller_spec.rb
=> FIX: allows authentication data to be present in bootstrap

app/assets/javascripts/discourse/app/lib/intercept-click.js
=> FIX: Typo in intercept-click

spec/requests/api/schemas/json/user_anonymize_response.json, spec/requests/api/users_spec.rb
Adding the anonymize user endpoint to the api docs.
See: https://meta.discourse.org/t/158704/7
=> DEV: Document anonymize user api endpoint

app/assets/javascripts/discourse/app/lib/plugin-api.js
Follow-up to  91456ad2cbbf767f71aedffb6b556617df64342f
=> DEV: Bump client side plugin-api version.

app/controllers/users_controller.rb, app/models/user_field_option.rb, spec/fabricators/user_field_option_fabricator.rb.rb, spec/requests/users_controller_spec.rb
This PR is to address this issue from meta: https://meta.discourse.org/t/validation-of-dropdown-custom-user-fields/198132
=> FIX: Validate value of custom user fields (dropdowns and multiple selects)

plugins/poll/assets/stylesheets/common/poll.scss, plugins/poll/assets/stylesheets/desktop/poll.scss
This PR will fix the misaligned poll buttons.
=> FIX: Adjust poll buttons

spec/requests/api/badges_spec.rb, spec/requests/api/schemas/json/badge_create_request.json, spec/requests/api/schemas/json/badge_create_response.json, spec/requests/api/schemas/json/badge_list_response.json, spec/requests/api/schemas/json/badge_update_request.json, spec/requests/api/schemas/json/badge_update_response.json, spec/requests/api/schemas/json/user_badges_response.json, spec/requests/api/user_badges_spec.rb
Adding some api documentation for the badge routes.
=> DEV: Document some of the badge api endpoints

app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/widgets/post-menu.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
=> DEV: resets post menu extra buttons between tests

app/assets/javascripts/discourse/app/mixins/card-contents-base.js
Send user-card:show event when card is opened. 
Other parts may listen, for example, for analytic purpose.
=> FEATURE: send user-card:show event

app/assets/javascripts/discourse/app/controllers/user-private-messages.js, app/assets/javascripts/discourse/app/controllers/user-topics-list.js, app/assets/javascripts/discourse/app/models/topic.js, app/assets/javascripts/discourse/app/routes/build-private-messages-group-route.js, app/assets/javascripts/discourse/app/routes/build-private-messages-route.js, app/assets/javascripts/discourse/app/routes/user-private-messages-group-archive.js, app/assets/javascripts/discourse/app/routes/user-private-messages-group-new.js, app/assets/javascripts/discourse/app/routes/user-private-messages-group-unread.js, app/assets/javascripts/discourse/app/routes/user-private-messages-group.js, app/assets/javascripts/discourse/app/routes/user-private-messages-index.js, app/assets/javascripts/discourse/app/routes/user-private-messages-new.js, app/assets/javascripts/discourse/app/routes/user-private-messages-personal-archive.js, app/assets/javascripts/discourse/app/routes/user-private-messages-personal-new.js, app/assets/javascripts/discourse/app/routes/user-private-messages-personal-sent.js, app/assets/javascripts/discourse/app/routes/user-private-messages-personal-unread.js, app/assets/javascripts/discourse/app/routes/user-private-messages-personal.js, app/assets/javascripts/discourse/app/routes/user-private-messages-sent.js, app/assets/javascripts/discourse/app/routes/user-private-messages-unread.js, app/assets/javascripts/discourse/app/templates/components/basic-topic-list.hbs, app/assets/javascripts/discourse/app/templates/user-topics-list.hbs, app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js, app/controllers/topics_controller.rb, config/routes.rb, lib/topic_query.rb, lib/topic_query/private_message_lists.rb, lib/topics_bulk_action.rb, spec/components/topics_bulk_action_spec.rb, spec/lib/topic_query/private_message_lists_spec.rb, spec/requests/topics_controller_spec.rb
=> FEATURE: Dismiss new and unread for PM inboxes.

app/controllers/topics_controller.rb, spec/requests/topics_controller_spec.rb
Follow-up to 2c046cc670161e3b9f998edcc7500d18bcfd8f9a
=> FIX: Remove limit on dismissing unread and new messages.

lib/onebox/engine/simplecast_onebox.rb
https://meta.discourse.org/t/onebox-regression-simplecast-com/187911/
=> FIX: update oEmbed URL for simplecast onebox

lib/onebox/engine/simplecast_onebox.rb
https://meta.discourse.org/t/onebox-regression-simplecast-com/187911
=> FIX: update iframe url for simplecast onebox

app/assets/javascripts/discourse/app/lib/plugin-api.js
The API is well described in the comments.
=> DEV: New Plugin API method for delegating an app event

app/models/group.rb, spec/components/user_lookup_spec.rb, spec/models/group_spec.rb, spec/requests/groups_controller_spec.rb
follow up to https://github.com/discourse/discourse/commit/fe3e18f9814d94cf5ca19891262b9376861ce3d0
=> FIX: do not show flair bg color if flair is not visible

app/assets/javascripts/admin/addon/components/permalink-form.js, app/assets/javascripts/admin/addon/components/screened-ip-address-form.js, app/assets/javascripts/admin/addon/components/value-list.js, app/assets/javascripts/admin/addon/components/watched-word-form.js, app/assets/javascripts/admin/addon/mixins/setting-component.js, app/assets/javascripts/discourse/app/components/choose-topic.js, app/assets/javascripts/discourse/app/components/create-account.js, app/assets/javascripts/discourse/app/components/login-modal.js, app/assets/javascripts/discourse/app/components/share-popup.js, app/assets/javascripts/discourse/app/controllers/flag.js, app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js, app/assets/javascripts/discourse/app/mixins/card-contents-base.js, app/assets/javascripts/discourse/tests/acceptance/composer-test.js, app/assets/javascripts/discourse/tests/acceptance/flag-post-test.js, app/assets/javascripts/discourse/tests/acceptance/group-manage-membership-test.js, app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/mini-tag-chooser-test.js, app/assets/javascripts/discourse/tests/integration/components/value-list-test.js, app/assets/javascripts/discourse/tests/test_starter.js, app/assets/javascripts/select-kit/addon/components/mini-tag-chooser.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-filter.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-header.js, app/assets/javascripts/wizard/components/invite-list.js, app/assets/javascripts/wizard/components/wizard-step.js, plugins/poll/assets/javascripts/widgets/discourse-poll.js.es6
Makes the code a bit more readable. Inspired by https://github.com/emberjs/ember.js/pull/19185
=> DEV: Use `key` over the deprecated `keyCode`

spec/rails_helper.rb
This reverts commit 52035dc665f84174caedf275f6b6282e0f80d220.
This broke the specs in jenkins...
=> Revert "DEV: Move rate limiter disable to after :each for tests (#13986)

spec/requests/uploads_controller_spec.rb
Was missing RateLimiter.clear_all!, leading to 403 errors.
=> DEV: Fix uploads controller flaky presigned put spec

app/assets/stylesheets/common/components/navs.scss
- active setting should now correctly show an arrow which was previously floating in the middle of nowhere
- uses a correct color for border separation, previously the border was present but invisible as similar to the background
- slighty tweak padding
- makes arrow computation based on a variable
=> UI: fixes sidebar settings border and active styles

app/models/group.rb, app/serializers/site_serializer.rb, lib/user_lookup.rb, spec/components/user_lookup_spec.rb, spec/models/group_spec.rb, spec/requests/groups_controller_spec.rb
This reverts commit fe3e18f9814d94cf5ca19891262b9376861ce3d0 and 0d8fd9ace60ad676af0cfb58d65191821a77e8a9
=> REVERT "FIX: do not show private group flair on user avatars"

app/assets/javascripts/discourse/app/components/d-button.js
=> DEV: stop propagation of events on button click

config/locales/client.en.yml, config/site_settings.yml, lib/discourse.rb, lib/topic_query.rb, spec/components/topic_query_spec.rb
This view is the same as _Latest_ except it hides the topics you have fully read. Based on this plugin of @davidtaylorhq https://meta.discourse.org/t/simple-unread-list-plugin-discourse-simple-unread/70013.
=> FEATURE: add Unseen view

app/assets/stylesheets/common/components/footer-nav.scss
I want to use the variable in a plugin, and currently cannot. This simply adds the css variable and uses it to set the scss var.
=> DEV: Define --footer-nav-height css var

script/import_scripts/vanilla_mysql.rb
We're parsing the post raw based on the record format now.
=> DEV: minor improvements in the vanilla import script.

app/assets/stylesheets/desktop/user.scss
=> FIX: Button alignment on messages

app/assets/javascripts/discourse/app/models/topic-tracking-state.js, config/locales/client.en.yml
This adds this banner to the Unseen view:
=> FEATURE: Show the incoming topics banner on the Unseen view

app/jobs/regular/emit_web_hook_event.rb
Previously, webhooks has 60 seconds default timeout of Excon and were added in the 'default' queue.
=> DEV: decrease webhook timeout and move to 'low' priority queue.

spec/requests/api/groups_spec.rb, spec/requests/api/topics_spec.rb
- Remove duplicate paths
- Remove query param listed in the path
=> DEV: Fix some openapi spec issues

app/assets/stylesheets/common/base/share_link.scss
=> UX: Add margin to share input

lib/middleware/request_tracker.rb, spec/components/middleware/request_tracker_spec.rb
Allow admins to configure exceptions to our Rails rate limiter.
Configuration happens in the environment variables, and work with both
IPs and CIDR blocks.
Example:
```
env:
DISCOURSE_MAX_REQS_PER_IP_EXCEPTIONS: >-
14.15.16.32/27
216.148.1.2
```
=> FEATURE: Rate limit exceptions via ENV

app/assets/javascripts/discourse/app/widgets/search-menu-controls.js
- uses keyDown for Enter event
- input for other keys and pasting
=> FIX: allows paste from context menu to work

app/models/topic_embed.rb, spec/models/topic_embed_spec.rb
This will be used in the rss pooling plugin to address the feature
request at https://meta.discourse.org/t/-/200644?u=falco
=> DEV: Allow passing a category parameter when importing a topic

lib/topic_query/private_message_lists.rb, spec/lib/topic_query/private_message_lists_spec.rb
This bug was causing unread PMs for groups to appear inaccurate.
=> FIX: Unread group PMs should use `GroupUser#first_unread_pm_at`.

lib/tasks/site.rake
Uploads can be reused between site settings. This change allows the same
upload to be exported only once and then the same file is reused. The
same applies to import.
=> FIX: Make site tasks work with duplicated uploads

app/assets/javascripts/discourse/app/widgets/search-menu-results.js, app/assets/javascripts/discourse/app/widgets/search-menu.js, app/assets/javascripts/discourse/tests/acceptance/search-test.js, app/assets/stylesheets/common/base/search-menu.scss
Followup to https://github.com/discourse/discourse/commit/438a7629561397830fa9622f517ecec46e003e82
=> FIX: Include tags in quick search suggestions

app/assets/javascripts/discourse/app/templates/user/messages.hbs
There is no CSS class for `noGlyph`.
=> DEV: Remove invalid class.

app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js, app/assets/stylesheets/common/select-kit/select-kit.scss
=> FIX: sk3 wizard regressions

app/assets/javascripts/discourse/app/components/choose-topic.js
This also fixes an incorrect usage of `debounce`.
Meta topic: https://meta.discourse.org/t/odd-search-behaviour-when-moving-messages-as-a-staff-member/201261?u=osama.
=> FIX: Discard old search results if search term changes when moving posts to a different topic

app/assets/javascripts/discourse/app/components/composer-messages.js, app/assets/javascripts/discourse/app/templates/components/composer-messages.hbs, app/assets/javascripts/discourse/app/templates/composer/get-a-room.hbs, app/assets/stylesheets/desktop/compose.scss, config/locales/server.en.yml, lib/composer_messages_finder.rb, spec/components/composer_messages_finder_spec.rb
This updates the text to be less patronizing, makes the text larger, updates the styling a bit, and adds a button that converts the current reply to a PM.
=> UX: Update "get a room" composer message

app/controllers/users_controller.rb, spec/requests/users_controller_spec.rb
Negative values generated invalid SQL queries.
=> FIX: Do not allow negative values for LIMIT

config/locales/server.en.yml
=> minor wording fix for get a room message

app/services/external_upload_manager.rb
See also 58e9fffe4cd0156284257c64306a6af0133367e0
=> DEV: Do not delete failed uploads from S3 in debug mode

app/assets/stylesheets/common/select-kit/dropdown-select-box.scss, app/assets/stylesheets/common/select-kit/period-chooser.scss, app/assets/stylesheets/common/select-kit/user-notifications-dropdown.scss, app/assets/stylesheets/mobile/user.scss
This fixes the alignment issues outlined here: https://meta.discourse.org/t/few-minor-issue-with-dropdowns/201993
=> UX: Select-kit update alignment fixes

app/assets/javascripts/discourse/app/mixins/card-contents-base.js
=> DEV: cards were leaking mousedown event listener

lib/version.rb
=> Version bump to v2.8.0.beta5

Gemfile.lock
We appear to be having memory issues with oj leading to stuck proccesses
see: https://github.com/ohler55/oj/pull/695#issuecomment-911012672
not certain this will fix the issue, but worth a shot
=> FIX: downgrade oj

Gemfile, Gemfile.lock
Follow-up to 0183d51070d33abc66c8681b43a5ce7571333b13
=> DEV: Pin oj gem to 3.13.2.

app/assets/javascripts/discourse/app/lib/plugin-api.js, plugins/discourse-details/assets/javascripts/initializers/apply-details.js.es6, plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js.es6, plugins/discourse-narrative-bot/assets/javascripts/initializers/new-user-narrative.js.es6, plugins/poll/assets/javascripts/initializers/add-poll-ui-builder.js.es6, plugins/poll/assets/javascripts/initializers/extend-for-poll.js.es6
This fixes the issue by creating a key for each modification and
checking to see if it's been applied to the class before.
=> FIX: In test mode, initializers were modifying classes over and over

app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js, app/assets/javascripts/discourse/app/mixins/upload.js, app/assets/javascripts/discourse/app/mixins/uppy-upload.js
=> DEV: prevents uppy to act on destroyed object

.github/workflows/ember.yml
=> DEV: re-enable ember-cli tests on CI

app/models/private_message_topic_tracking_state.rb
This change helps the planner to use the
index_topics_on_timestamps_private index on topics.
Follow-up to f66007ec83b62169b5c41016eecd40c72f27028f
=> PERF: Improve query perf when fetching unread for PM topic tracking state.

app/assets/javascripts/select-kit/addon/components/select-kit.js
=> DEV: simplify logic when selecting an undefined value

app/assets/javascripts/select-kit/addon/components/select-kit/single-select-header.js
=> DEV: prevents focus event bubbling

lib/tasks/db.rake
=> FIX: Don't attempt to migrate concurrently with other migrations

app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-body.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-filter.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-header.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js, app/assets/javascripts/select-kit/addon/templates/components/topic-notifications-button.hbs
=> DEV: toggle sk on click

app/assets/javascripts/discourse/app/templates/mobile/discovery/categories.hbs
=> REFACTOR: Remove unneeded mobile `hbs` file

app/models/bookmark.rb
This was removed a long time ago and ignored in
8dc3543134170e73d3bd504a5a3923e869b03691
=> DEV: Stop ignoring bookmarks.delete_when_reminder_sent

app/assets/javascripts/discourse/app/initializers/page-tracking.js, app/assets/javascripts/discourse/app/lib/clean-dom.js
See https://meta.discourse.org/t/-/202482/5
No tests because we don't enable mini-profiler in test env and it is not something worth testing imo.
=> DEV: Don't transition miniprofiler on first page load.

plugins/poll/assets/stylesheets/desktop/poll.scss
=> UX: adjust poll button spacing

app/jobs/scheduled/clean_up_uploads.rb
=> DEV: Do not clean up chat message uploads

app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/lib/user-search.js, app/assets/javascripts/select-kit/addon/components/user-chooser.js, app/controllers/users_controller.rb, app/models/group.rb, lib/discourse_plugin_registry.rb, lib/plugin/instance.rb, spec/models/group_spec.rb, spec/requests/users_controller_spec.rb
Follow up of https://github.com/discourse/discourse/pull/14216
Allow plugins to register custom filter with block
=> FIX: better filter for groups search

.github/workflows/tests.yml
=> DEV: Use discourse image redis in CI

app/assets/stylesheets/common/base/onebox.scss, lib/onebox/engine/google_photos_onebox.rb, lib/onebox/engine/reddit_media_onebox.rb
=> FIX: Correct the play icon position

config/site_settings.yml
=> markdown_linkify_tlds: Added onion in default

lib/tasks/db.rake
=> DEV: Add rake task to check that the DB can be accessed

Gemfile.lock, config/application.rb, config/discourse_defaults.conf
=> FEATURE: Make the multisite config path configurable

app/assets/javascripts/discourse/app/widgets/topic-timeline.js
This reverts commit b246a63a5922321eb63d28a191a0cde3f1152f21.
=> Revert "FIX: Give the topic timeline unique keys for state"

.github/workflows/ember.yml
=> DEV: Mark Ember CLI action as experimental

.github/workflows/ember.yml
Gotta have gems before running ruby code 😛 
See failure e.g. here: https://github.com/discourse/discourse/runs/3581746429?check_suite_focus=true
=> DEV: Fix the cron ember workflow

app/assets/javascripts/admin/addon/templates/site-settings.hbs, app/assets/javascripts/admin/addon/templates/watched-words.hbs, app/assets/stylesheets/common/admin/admin_base.scss, app/assets/stylesheets/common/admin/customize.scss
Before
After
Also removes some unused styles.
=> UX: Fix alignment for admin controls on mobile

app/controllers/topics_controller.rb, lib/topic_query/private_message_lists.rb
This reverts commit ddb458343dc39a7a8c99467dcd809b444514fe2c.
=> Revert "PERF: Improve query performance all inbox private messages. (#14304)"

app/jobs/scheduled/clean_up_uploads.rb, app/models/upload.rb, db/migrate/20210914152002_update_value_on_theme_setting_for_upload_type.rb, lib/theme_settings_manager.rb, spec/components/theme_settings_manager_spec.rb, spec/jobs/clean_up_uploads_spec.rb, spec/models/theme_spec.rb
when we use URL instead it creates the problem while changing the CDN hostname.
=> DEV: use upload id to save in theme setting instead of URL.

db/fixtures/010_uploads.rb
=> DEV: update comments on unused Uploads. -4 is now considered reserved.

app/assets/javascripts/discourse/app/components/quote-button.js
The algorithm will now do the following:
- split selection to retain only first line
- removes possible "* "
- check for first inclusion
- fallback to first row if nothing found
=> UX: improves fast edit fallback handling

app/assets/stylesheets/common/base/login.scss, app/assets/stylesheets/desktop/login.scss
=> UX: Prevent invite form fields from resizing

app/assets/javascripts/discourse/app/lib/uppy-checksum-plugin.js, app/assets/javascripts/discourse/app/lib/uppy-media-optimization-plugin.js, app/assets/javascripts/discourse/app/lib/uppy-plugin-base.js, app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js, app/assets/javascripts/discourse/app/mixins/extendable-uploader.js, app/assets/javascripts/discourse/app/mixins/uppy-upload.js, app/assets/javascripts/discourse/tests/unit/lib/uppy-checksum-plugin-test.js
This reverts commit 36bd6e8c3bccbcdb79cc96934475025b46e4c9b7.
ember/debug .debug errors when called in prod :(
=> Revert "DEV: Improve uppy plugin base and large file handling (#14383)"

app/assets/javascripts/select-kit/addon/components/topic-notifications-button.js
=> DEV: observes used properties in reason text

app/assets/javascripts/admin/addon/templates/badges-award.hbs, app/assets/javascripts/admin/addon/templates/badges-show.hbs, app/assets/javascripts/admin/addon/templates/user-badges.hbs, app/assets/javascripts/admin/addon/templates/web-hooks-show.hbs, app/assets/stylesheets/common/admin/admin_base.scss, app/assets/stylesheets/common/admin/api.scss, app/assets/stylesheets/common/admin/badges.scss, app/assets/stylesheets/common/admin/customize.scss, app/assets/stylesheets/desktop/discourse.scss, app/assets/stylesheets/desktop/group.scss, app/assets/stylesheets/desktop/user.scss, app/assets/stylesheets/mobile/admin_customize.scss, app/assets/stylesheets/mobile/user.scss
Should have no visual effect, this removes some local styles and replaces them with more global declarations. Also removes some styles that are no longer used.
=> DEV: Clean up some styles

spec/lib/topic_query/private_message_lists_spec.rb
This is in response to the security incident published in
https://github.com/discourse/discourse/security/advisories/GHSA-vm3x-w6jm-j9vv.
The security incident highlighted a gap in our test suite so we're
adding more test cases to ensure that personal and group messages do not
leak between users in the future.
=> DEV: Improve tests coverage when listing private messages.

app/assets/javascripts/discourse/tests/setup-tests.js
This PR updates the `qunit_skip_core`, `qunit_skip_plugins` and `qunit_single_plugin` to be compatible with the Ember CLI `/tests` route. The public `addModuleExcludeMatcher` API is used for Ember CLI. The legacy `require()` solution is also maintained for the `/qunit` route. 
This PR also amends the QUnit toolbar UI to hide unused options, and adds these new plugin-related parameters. These toolbar changes are compatible with both `/tests` and `/qunit`.
See commit messages for more information (to be rebased and merged)
=> Add qunit filter parameters to Ember CLI `/tests` route, and add UI

config/locales/server.en.yml, config/site_settings.yml
=> FEATURE: enables fast edit by default

plugins/discourse-local-dates/assets/javascripts/discourse/components/discourse-local-dates-create-form.js.es6, plugins/discourse-local-dates/assets/javascripts/discourse/templates/modal/discourse-local-dates-create-modal.hbs, plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js.es6
=> DEV: Add toolbar button when chat in installed

app/assets/javascripts/discourse/app/routes/discovery-categories.js
This topic describes the issue in further detail. https://meta.discourse.org/t/see-new-or-updated-topics/204206/7
=> FIX: make update banner always clickable on the categories view

app/assets/javascripts/discourse/app/templates/components/latest-topic-list-item.hbs, app/assets/javascripts/discourse/app/templates/components/parent-category-row.hbs, app/assets/javascripts/discourse/app/templates/discovery.hbs
need these for a customer theme
=> DEV: Adding plugin outlets to avoid overrides

app/assets/javascripts/discourse/app/templates/tags/show.hbs
more plugin outlets for a customer theme (these should be consistent with `discovery.hbs` anyway)
=> DEV: Tag topic list needs discovery outlets

app/assets/javascripts/admin/addon/mixins/setting-component.js, app/assets/javascripts/discourse/app/lib/utilities.js
- drops jquery usage
- extract spit function
- uses @action
- removes get usage where possible
- uses helpers
- minor changes
=> REFACTOR: setting component mixin

app/assets/javascripts/admin/addon/controllers/admin-api-keys-new.js, app/assets/javascripts/admin/addon/routes/admin-api-keys-new.js, app/assets/javascripts/admin/addon/templates/api-keys-new.hbs
- moves loading scopes to controller
- avoids declaring array
- simplify code
=> REFACTOR: minor changes to api-keys-new

app/assets/stylesheets/mobile/search.scss
=> UX: Adjust mobile spacing for full page search

app/assets/javascripts/discourse/tests/setup-tests.js
We were using multiple methods to check which environment we're running in. This commit switches us to use the isLegacyEmber helper consistently. This should be a no-op, but makes the code much easier to read
=> DEV: Use isLegacyEmber helper in setup-tests

app/assets/javascripts/discourse/testem.js
DEV: Increase chrome JS memory limit in CI
=> DEV: Increase chrome JS memory limit in CI

plugins/styleguide/assets/javascripts/discourse/components/styleguide-icons.js.es6
=> DEV: Sort styleguide icons alphabetically and fix render on refresh

app/assets/javascripts/discourse/app/lib/plugin-api.js
=> FIX: incorrect interpolation was limiting to 1 dispatch / component

app/assets/javascripts/discourse/app/controllers/user-private-messages.js, app/assets/javascripts/discourse/app/templates/user/messages.hbs, app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js
Follow-up to 9d5da2b383765becb824a8f3ff3665abc8e527fa
=> UX: PM inboxes being expanded incorrectly when viewing tags.

app/assets/javascripts/discourse/app/models/post-stream.js
Follow-up to fc1fd1b41689694b3916dc4e10605eb9b8bb89b7
Not sure how I can test a scrolling stream here.
=> FIX: Error loading suggested topics for anon users.

app/assets/javascripts/discourse/app/templates/components/categories-topic-list.hbs
Adding this for a customer theme
=> DEV: add plugin outlet to categories page topic list table header

app/assets/javascripts/discourse/app/controllers/full-page-search.js, config/locales/client.en.yml
See https://meta.discourse.org/t/new-search-mentions-tags-when-tags-arent-supported/205024/4
=> UX: Fix label in search when tagging is disabled

app/assets/javascripts/discourse/app/components/d-editor.js, app/assets/javascripts/discourse/tests/acceptance/composer-onebox-test.js, app/assets/javascripts/discourse/tests/acceptance/hashtags-test.js
=> DEV: observe all elements to prevent any missed mutation

app/assets/javascripts/discourse/app/index.html, app/assets/javascripts/discourse/lib/bootstrap-json/index.js
The admin payload should only be loaded if the user is staff.
=> FIX: Ember CLI was always loading the admin payload in dev mode

app/assets/javascripts/discourse/app/models/topic-list.js, app/assets/javascripts/discourse/app/routes/discovery-categories.js
I don't know if JS engines were able to optimize-away those gigantic arrays but in any case that's a definite anti-pattern.
=> DEV: Use Set instead of array-as-an-object

config/locales/server.en.yml
=> UX: Global notice no longer accepts HTML.

app/assets/javascripts/discourse/app/controllers/topic.js, app/assets/javascripts/discourse/app/models/topic.js
=> DEV: adds a topic level bookmark toggle

lib/plugin/metadata.rb
Add LTI plugin to the Official list
The test is omitted, I just added a plugin to the list.
=> Add LTI plugin

spec/components/pbkdf2_spec.rb
Fixes failing tests in CI, where this spec file was first in a batch.
=> DEV: Load rails_helper in pbkdf2_spec

app/assets/javascripts/discourse/app/templates/composer.hbs, app/assets/stylesheets/desktop/compose.scss
=> UX: better accommodate PM composer with tags

Gemfile
This reverts commit 2818ebd19fc101faba6e28ca09c6d762034dc760.
=> Revert "DEV: Avoid duplication of gems in gemfile."

app/assets/stylesheets/common/components/badges.scss, app/assets/stylesheets/common/select-kit/category-drop.scss
=> UX: Fix bar-style category dropdown
