discourse/discourse

- app/jobs/regular/export_csv_file.rb
https://meta.discourse.org/t/wrong-number-of-fields-in-csv-export-of-users/203191
> FIX: insert commas even when field value is null

- app/assets/javascripts/discourse/app/components/avatar-uploader.js
Simple change, no further caveats for this one.
> FEATURE: Move avatar uploader to uppy

- app/assets/javascripts/discourse/app/widgets/post-menu.js
- app/assets/javascripts/discourse/tests/integration/widgets/post-test.js
- app/assets/stylesheets/desktop/topic-post.scss
> REFACTOR: Use CSS animations for likes

- app/assets/javascripts/admin/addon/templates/permalinks.hbs
- app/assets/stylesheets/common/admin/customize.scss
> UX: Layout fixes for admin permalinks page

- app/assets/javascripts/discourse/app/lib/transform-post.js
- app/assets/javascripts/discourse/app/widgets/post-small-action.js
- app/models/user_action.rb
- app/serializers/post_serializer.rb
- app/serializers/user_action_serializer.rb
- app/views/topics/show.html.erb
- lib/topic_view.rb
Optionally add href to small action.
It can be used by discourse-assign to link to correct post from translation
Related PR: https://github.com/discourse/discourse-assign/pull/232
> FEATURE: small action post accepts href

- app/assets/javascripts/admin/addon/components/tags-uploader.js
> FEATURE: Use uppy for tags uploader

- docs/INSTALL-cloud.md
While working through the cloud installation README, I figured it would be useful to the reader to have steps numbered.
> UX: Number steps in cloud installation README

- app/assets/javascripts/discourse/app/widgets/post-menu.js
- app/assets/stylesheets/common/base/topic-post.scss
- app/assets/stylesheets/desktop/topic-post.scss
Regressed in https://github.com/discourse/discourse/commit/89a2cec7bef2321a4f633f900b2b240dd91113ce
> FIX: Restore animation for like action on mobile

- app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js
- app/assets/javascripts/pretty-text/engines/discourse-markdown/anchor.js
> FIX: Generate valid heading ids

- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
Fixes `qunit/no-commented-tests`
> DEV: Skip a test instead of commenting it out

- Gemfile.lock
This reverts commit f7529ec43b813ed4e229cdc6c5fbd3f9bd6aa8b5.
> Revert "Build(deps): Bump hashie from 4.1.0 to 5.0.0"

- app/assets/javascripts/admin/addon/controllers/admin-api-keys-index.js
- app/assets/javascripts/admin/addon/templates/api-keys-index.hbs
- app/controllers/admin/api_controller.rb
- spec/requests/admin/api_controller_spec.rb
> FEATURE: Add pagination to API keys page

- app/assets/stylesheets/common/base/magnific-popup.scss
> "A11Y: Add prefers reduced motion"

- app/models/discourse_single_sign_on.rb
- spec/models/discourse_single_sign_on_spec.rb
> DEV: Update DiscourseConnect nonce errors to be more descriptive

- yarn.lock
Follow up to 47075c0d12d1ea1106734a2de4034f3565cfdad9
> DEV: Update yarn.lock

- plugins/discourse-local-dates/assets/javascripts/discourse/components/discourse-local-dates-create-form.js.es6
See https://github.com/discourse/eslint-config-discourse/commit/4f7aba06c03fdd22bb26669aeb8ed4af3127c409
> DEV: Update discourse-local-dates for eslint shorthand rule

- lib/tasks/posts.rake
- lib/tasks/redis.rake
- lib/tasks/s3.rake
- lib/tasks/topics.rake
`return` isn't allowed in a block context. A followup to #14865
> FIX: `LocalJumpError` in rake tasks

- lib/tasks/db.rake
This reverts commit 337ef60303bbc20619004fc6e5daa284eb59383c.
> Revert "DEV: increase lock timeout for multisite migration (#14831)"

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/discourse/tests/test-helper.js
- app/assets/javascripts/yarn.lock
This allows us to partition and load balance tests, if we like.
> Add support for Ember Exam

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/discourse/tests/test-helper.js
- app/assets/javascripts/yarn.lock
This reverts commit d1dec23a937683f92b2401c375046430d4f474ec.
It was causing issues with internal builds. (/t/56168)
> Revert "Add support for Ember Exam"

- app/assets/javascripts/discourse/app/controllers/topic.js
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/app/models/composer.js
- app/assets/javascripts/discourse/app/templates/composer.hbs
- app/assets/javascripts/discourse/tests/integration/components/time-input-test.js
- app/assets/javascripts/discourse/tests/unit/models/category-test.js
- app/assets/javascripts/select-kit/addon/components/category-chooser.js
- app/assets/javascripts/select-kit/addon/components/dropdown-select-box.js
- app/assets/javascripts/select-kit/addon/components/mini-tag-chooser.js
- app/assets/javascripts/select-kit/addon/components/multi-select.js
- app/assets/javascripts/select-kit/addon/components/select-kit.js
- app/assets/javascripts/select-kit/addon/templates/components/multi-select.hbs
- config/locales/client.en.yml
Also fixes a bug where select-kit was not updating noneItem in multi-selects.
> FIX: ensures minimum tags logic is correct and shared

- app/models/group.rb
> DEV: Remove deprecated method

- app/assets/javascripts/discourse/app/components/composer-editor.js
- app/assets/javascripts/discourse/app/components/d-editor.js
- app/assets/javascripts/discourse/app/lib/link-hashtags.js
> DEV: reduces jquery usage in composer-editor

- app/assets/javascripts/discourse/testem.js
```
Error: illegal value for flag --max_semi_space_size
```
> DEV: Fix Chrome flags

- app/assets/javascripts/discourse/testem.js
> DEV: Increase Chrome memory limit

- app/assets/javascripts/discourse/app/components/date-input.js
> DEV: Fix a `computed-property.override` warning

- app/assets/javascripts/discourse/app/lib/eyeline.js
- app/assets/javascripts/discourse/app/mixins/load-more.js
Use `Evented` from `@ember/object/evented` instead.
> DEV: Don't create AppEvents instance in Eyeline

- app/assets/javascripts/discourse/tests/acceptance/category-edit-security-test.js
- app/assets/javascripts/discourse/tests/acceptance/emoji-picker-test.js
- app/assets/javascripts/discourse/tests/acceptance/tags-test.js
- app/assets/javascripts/discourse/tests/unit/models/post-stream-test.js
Just a couple of invalid assertions.
> DEV: Fix `qunit/assert-args`

- app/assets/javascripts/discourse/app/components/bookmark.js
- app/assets/javascripts/discourse/app/components/d-editor.js
- app/assets/javascripts/discourse/app/components/reviewable-item.js
- app/assets/javascripts/discourse/app/controllers/user-private-messages.js
- app/assets/javascripts/discourse/app/lib/uppy-checksum-plugin.js
- app/assets/javascripts/discourse/app/lib/uppy-media-optimization-plugin.js
- app/assets/javascripts/discourse/app/mixins/card-contents-base.js
- app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
- app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
- app/assets/javascripts/discourse/app/models/private-message-topic-tracking-state.js
- app/assets/javascripts/discourse/app/models/topic-tracking-state.js
- app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/unit/lib/uppy-media-optimization-plugin-test.js
Fixes some cases where event listeners weren't correctly removed. Also fixes a dependency tracking bug in user-private-messages.
> DEV: Use `@bind` instead of repeated `.bind(this)`

- app/assets/javascripts/discourse/app/pre-initializers/sniff-capabilities.js
Drop jQuery, remove unused caps (`canPasteImages` and `highRes`), enable `canVibrate` for Firefox (per the old comment), and other minor changes.
> DEV: Clean up `sniff-capabilities`

- lib/version.rb
> Version bump to v2.8.0.beta8

- app/assets/javascripts/discourse/app/initializers/sticky-avatars.js
- app/assets/javascripts/discourse/app/lib/sticky-avatars.js
- app/assets/javascripts/discourse/tests/acceptance/sticky-avatars-test.js
- app/assets/stylesheets/desktop/topic-post.scss
This PR takes the small component we had for sticky avatars and adds it into our core code base.
A small refactor has been made to have a `StickyAvatars` dedicated class.
To see it in action:
https://user-images.githubusercontent.com/5648/139278562-fbfe3377-e30f-45b0-a32d-7ffb18f97fbf.mp4
> FEATURE: Move sticky avatars into core

- app/assets/javascripts/discourse/app/lib/theme-selector.js
> DEV: removes unnecessary jquery selector

- app/assets/javascripts/admin/addon/components/admin-report-stacked-chart.js
> DEV: drops jquery usage in stacked chart

- app/assets/javascripts/admin/addon/components/staff-actions.js
- app/assets/javascripts/admin/addon/templates/components/staff-actions.hbs
> DEV: drops jquery/simplify code/removes leaked event

- app/assets/javascripts/discourse/app/components/composer-body.js
- app/assets/javascripts/discourse/app/components/composer-editor.js
- app/assets/javascripts/discourse/app/components/d-editor.js
- app/assets/javascripts/discourse/app/lib/autocomplete.js
- app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
- app/assets/javascripts/discourse/testem.js
Removes more than 60 jquery function leaks in one `Acceptance: Composer` run.
> DEV: reduces jquery usage and memory leaks in composer

- app/assets/javascripts/discourse/app/templates/list/visited-line.hbr
> FIX: adds missing class for last visit separator

- app/assets/javascripts/discourse/app/components/html-with-links.js
> DEV: removes jquery usage from html-with-links

- app/assets/javascripts/discourse/app/components/links-redirect.js
> DEV: removes jquery usage from links-redirect

- app/assets/javascripts/discourse/app/components/discourse-topic.js
> DEV: removes jquery usage from discourse-topic

- app/assets/javascripts/discourse/app/initializers/sticky-avatars.js
- app/assets/javascripts/discourse/app/lib/sticky-avatars.js
> DEV: sticky avatar was retained during tests

- lib/s3_cors_rulesets.rb
It adds unnecessary noise when running the test suite.
> DEV: Skip logging in test environment

- app/assets/javascripts/discourse/app/components/d-editor.js
- app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
> DEV: Export add emoji logic in textarea manipulation mixin

- app/assets/javascripts/discourse/app/templates/components/bookmark-list.hbs
- app/assets/javascripts/discourse/app/templates/user-topics-list.hbs
- app/assets/stylesheets/common/components/bookmark-list.scss
This commit adds needed changes to the bookmarked topic lists.
> REFACTOR: Continued topic-list tweaks

- app/assets/javascripts/discourse/app/models/site.js
- app/assets/javascripts/discourse/tests/unit/models/site-test.js
Fixes the issue where categories over two levels deep were missing.
> FIX: Include all categories in sortedCategories

- lib/tasks/emoji.rake
Search aliases are retrieved from https://github.com/jjaffeux/emoji-db/commit/ec9cdb6d04de48dae04f6b2f4c4db595f8a3fae6.
> UX: add more search aliases for emojis.

- app/assets/javascripts/discourse/app/controllers/login.js
> FIX: clear previous errors on second factor form display

- app/assets/javascripts/discourse/app/controllers/preferences/profile.js
- app/assets/javascripts/discourse/tests/unit/controllers/preferences-profile-test.js
in `preferences/profile` controller
> DEV: Fix a `userFields` computed property override

- app/assets/javascripts/discourse/app/widgets/post.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
The widget's state did not reflect the state of the controller.
> FIX: Incorrect title and chevron when filtering by post number.

- app/assets/javascripts/discourse/app/templates/components/categories-and-latest-topics.hbs
- app/assets/javascripts/discourse/app/templates/components/categories-and-top-topics.hbs
> DEV: add plugin-outlet for extra categories column

- config/site_settings.yml
Admins don't need to be changing these.
> DEV: Hide message bus site settings

- app/assets/stylesheets/common/base/_topic-list.scss
- app/assets/stylesheets/desktop/topic-list.scss
> FIX: Topic list separator fix

- app/assets/javascripts/discourse/app/controllers/share-topic.js
- app/assets/javascripts/discourse/app/templates/modal/share-topic.hbs
- app/assets/javascripts/discourse/tests/acceptance/share-topic-test.js
- app/assets/stylesheets/common/base/share_link.scss
- config/locales/client.en.yml
> UX: Move share topic warning to modal flash alert

- app/assets/javascripts/discourse/app/initializers/post-decorations.js
- app/assets/javascripts/discourse/app/lib/text-direction.js
> DEV: Remove JQuery from discourse/lib/text-direction

- app/models/user_stat.rb
The inefficiency here is that we were previously fetching all the
records from `TopicAllowedUser` before filtering against a limited subset of
users based on `User#last_seen_at`.
> PERF: Reduce records queried in UserStat.update_first_unread_pm.

- app/assets/javascripts/discourse/app/components/d-navigation.js
- app/assets/javascripts/discourse/app/components/user-stream.js
- app/assets/javascripts/discourse/tests/acceptance/user-drafts-stream-test.js
- app/assets/javascripts/discourse/tests/fixtures/user-fixtures.js
> FIX: Remove 'Open Draft' label after topic draft deleted

- spec/models/user_stat_spec.rb
The users all shared the same `User#last_seen_at` column so depending on
how the database returned the records, the user that we're interested in
may be excluded from the update query.
Follow-up to 8226ab1099ebdb05403ba27c25921e25e269c031
> DEV: Fix flaky specs due to 8226ab1099ebdb05403ba27c25921e25e269c031.

- lib/tasks/themes.rake
> FIX: Do not fail-stop if theme update fails

- lib/topic_view.rb
- spec/components/topic_view_spec.rb
Not exposing this as a plugin API yet as we're testing it out with a
plugin.
> DEV: Allow default scope to be configurable per topic.

- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
* DEV: Fix ember-cli proxy compat with node < 16
* DEV: Fix uploading via ember-cli
* DEV: Fix proxying /logs & other CSP-enabled pages
> DEV: Fix ember-cli proxy issues

- app/assets/javascripts/discourse/app/controllers/history.js
- app/assets/javascripts/discourse/app/templates/modal/history.hbs
- app/assets/javascripts/discourse/tests/acceptance/post-history-test.js
> FEATURE: Highlight changed tags in post revisions

- lib/tasks/themes.rake
This applies only when a single site exists. If a theme update fails
when there are multiple sites, then it will continue updating the
remaining themes.
> DEV: Fail stop if theme update fails

- app/assets/javascripts/discourse/app/lib/autocomplete.js
This is a workaround for an annoying bug that crashes the browser when an autocomplete suggestion is selected on Android if the virtual keyboard is Gboard. It's specific to Gboard because it sometimes sends `keydown` and `keyup` events twice for a single key press, more details can be found here: https://meta.discourse.org/t/emoji-selector-crashes-the-message-editor-in-android-chrome/187009/24?u=osama.
> FIX: Don't crash the browser when tapping autocomplete suggestions on Android/Gboard

- app/assets/javascripts/admin/addon/components/dashboard-new-features.js
- app/assets/javascripts/discourse/app/controllers/create-account.js
- app/assets/javascripts/discourse/app/mixins/username-validation.js
One of these (create-account.js:363) fixes a broken test on the legacy ember env.
> DEV: Fix set-after-destroy issues

- app/jobs/scheduled/clean_up_email_tokens.rb
> FIX: Delete unconfirmed AND expired email tokens only

- .github/workflows/ember.yml
- .github/workflows/linting.yml
- .github/workflows/tests.yml
> DEV: Cancel in-progress test runs on PRs

- app/assets/javascripts/discourse/app/widgets/hooks.js
For widget event handlers, we register a single listener on the `<body>`, and then notify the relavent widget (if any) when the event fires.
`touchstart` and `touchmove` events are particularly performance sensitive because they block scrolling on mobile. Therefore we want to avoid registering global non-passive listeners for these events.
This commit updates the WidgetTouchStartHook and WidgetDragHook implementations to automatically register listeners on the specific widget DOM elements when required.
This commit removes the last global scroll-blocking event handler from Discourse core. That means that mobile scrolling is now completely decoupled from our JS app. Even if the JS app is completely blocked (e.g. during rendering), scrolling will now continue to work. This should make …
> PERF: Update widget hooks to avoid global scroll-blocking events

- app/assets/javascripts/discourse/tests/integration/components/select-kit/multi-select-test.js
- app/assets/javascripts/select-kit/addon/components/select-kit.js
> UX: closes multi-select on selection when maximum=1

- app/assets/javascripts/discourse/tests/acceptance/bookmarks-test.js
- app/assets/javascripts/discourse/tests/acceptance/fast-edit-test.js
- app/assets/javascripts/discourse/tests/acceptance/flag-post-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
- app/assets/javascripts/discourse/tests/unit/models/user-badge-test.js
The leak was introduced in #11722 and a test was added that relied on it in #14563
This PR fixes the leak (bookmarks-test), fixes the test that relied on it (fast-edit-test), and replaces some ad-hoc code with `cloneJSON` helper (other files)
> DEV: Fix a test leak

- app/assets/javascripts/discourse/app/services/presence.js
- app/assets/javascripts/discourse/tests/unit/services/presence-test.js
> DEV: Automatically leave PresenceChannels when in the background 

- app/assets/stylesheets/mobile/compose.scss
> UX: Tweak mobile composer styling

- app/assets/stylesheets/mobile/compose.scss
> FIX: Broken css in #15141

- lib/version.rb
> Version bump to v2.8.0.beta9

- .byebug_history
- app/assets/javascripts/discourse/app/lib/uploads.js
- app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
- app/jobs/scheduled/clean_up_uploads.rb
> DEV: Changes to support chat uploads

- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
That code is not transpiled, so it doesn't work on older node versions.
> DEV: Don't use `?.` in bootstrap-json

- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
Before:
After:
Much more useful!
> DEV: Print full stack trace on ember-cli bootstrap error

- app/assets/stylesheets/common/components/navs.scss
- app/assets/stylesheets/desktop/group.scss
- plugins/styleguide/assets/javascripts/discourse/lib/dummy-data.js
- plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/navigation-bar.hbs
Same as #15145 (that commit got reverted in https://github.com/discourse/discourse/pull/15150 due to issues in an internal plugin that have now been resolved).
> UX: Fix alignment in group navigation bar

- lib/plugin/metadata.rb
> DEV: Update discourse-plugin-linkedin-auth to discourse-linkedin-auth

- spec/components/post_action_creator_spec.rb
- spec/models/post_action_spec.rb
- spec/models/topic_spec.rb
- spec/requests/groups_controller_spec.rb
- spec/requests/users_controller_spec.rb
- spec/services/user_destroyer_spec.rb
- spec/services/user_merger_spec.rb
> PERF: Shave off some test-suite time

- app/assets/javascripts/discourse/app/initializers/badging.js
That regressed in #7714, over two years ago. :P
> FIX: PWA badges were not updating

- app/services/notifications/consolidate_notifications.rb
- spec/services/post_alerter_spec.rb
In the future, it would be better to have a consolidated_at timestamp instead of updating created_at.
> FIX: Updating a consolidated notification should bump it to the top.

- app/assets/stylesheets/common/select-kit/flair-row.scss
> UX: Fix flair dropdown styling in user account

- app/models/email_token.rb
- db/migrate/20211206160211_create_index_on_email_tokens_token_hash.rb
> PERF: Add index on email_tokens.token_hash

- app/assets/javascripts/discourse/app/templates/components/tag-info.hbs
- app/assets/javascripts/discourse/tests/acceptance/tags-test.js
Broken with PR https://github.com/discourse/discourse/pull/15149
> FIX: edit tag test

- spec/components/pretty_text_spec.rb
- spec/requests/users_controller_spec.rb
> PERF: Speed up tests

- spec/requests/omniauth_callbacks_controller_spec.rb
> DEV: dry up omni_auth_callback_controller_spec

- app/assets/javascripts/discourse/app/services/presence.js
This allows consumers to vary the parameters on a per-channel basis. e.g. if you wanted a channel to consider someone 'away' after 10 minutes, and another channel to consider someone 'away' after 1 minute, that is now possible.
> DEV: Allow PresenceChannel to specify custom activity thresholds

- app/assets/javascripts/discourse/app/pre-initializers/sniff-capabilities.js
> DEV: Sniff isPwa for capabilities

- lib/email/message_id_service.rb
- spec/lib/message_id_service_spec.rb
> FIX: Ensure MessageIdService can handle hostname changes and multisite

- app/assets/javascripts/select-kit/addon/components/select-kit.js
> UX: scroll row to top of container in select-kit

- app/models/user_stat.rb
- spec/models/draft_spec.rb
> FIX: Select correct topic draft for user

- app/assets/javascripts/discourse/app/lib/utilities.js
Meta topic: https://meta.discourse.org/t/discourse-with-a-screen-reader/178105/87?u=osama.
> A11Y: Move focus to highlighted post when visiting a topic

- spec/components/file_store/s3_store_spec.rb
- spec/models/optimized_image_spec.rb
> FIX: make tests work with higher starting upload id

- app/assets/javascripts/discourse/app/widgets/post.js
- app/assets/stylesheets/common/base/topic-post.scss
This was added 6 years ago in d1e85bdd8b7752a33ef840c8af48fefa54281ec3
and I can't see how this is useful for any customizations at all.
> DEV: Remove unnecessary element.

- app/assets/javascripts/discourse/app/components/choose-topic.js
- app/assets/javascripts/discourse/app/components/topic-status.js
- app/assets/javascripts/discourse/app/templates/components/choose-topic.hbs
- prevents category to be clickable to make clicking topics easier
- drops jQuery
- uses @action
- uses ? operator where possible
- drops un-needed next/schedule usage
> DEV: minor choose topic refactoring

- app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
allows plugin event hook for keyboard:move-selection.
> Add keyboard move selection event

- app/assets/javascripts/discourse/app/components/discovery-categories.js
> DEV: drops jquery usage from discovery-categories

- app/assets/javascripts/admin/addon/controllers/admin-plugins.js
- app/assets/javascripts/admin/addon/controllers/admin-site-settings.js
- app/assets/javascripts/admin/addon/templates/plugins.hbs
- drops jQuery usage
- removes apparently useless clearfix
- uses @action
- drops unused clearFilter function in admin-plugins
> DEV: refactors admin-plugins/admin-site-settings

- app/assets/javascripts/discourse/app/components/d-section.js
> DEV: fixes test as bodyClass is sometimes "foo bar"

- app/assets/javascripts/admin/addon/controllers/admin-watched-words.js
> DEV: removes jquery usage from admin-watched-words

- app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
> FIX: only consider it handled by composer when a composer

- lib/plugin/metadata.rb
Adding Apple plugin to the official plugins list, no test needed.
> Add Apple plugin

- lib/plugin/metadata.rb
> DEV: Add SAML to official plugin list

- spec/requests/topics_controller_spec.rb
> PERF: Prefabricate more of topics_controller_spec.rb

- lib/plugin/metadata.rb
> DEV: Add discourse-vk-auth to official plugins list

- app/assets/javascripts/discourse/app/components/popup-input-tip.js
> DEV: Prefers reads helper over alias

- app/assets/javascripts/discourse/app/components/topic-list-item.js
Meta topic: https://meta.discourse.org/t/discourse-with-a-screen-reader/178105/88?u=osama.
> A11Y: Focus last viewed topic in topic lists

- app/assets/javascripts/discourse/app/controllers/jump-to-post.js
- replaces alias by reads
- drops jquery usage
- autofocus should already be done; so remove custom code
- uses @action
> DEV: minor refactoring of jump-to-post

- app/services/post_alerter.rb
- spec/services/post_alerter_spec.rb
When a member set a group PM notification level to Normal, we didn't notify them if someone quoted or replied to one of their posts.
> FIX: Notify group members when someone quotes or replies to their post.

- app/assets/javascripts/discourse/app/components/bookmark-list.js
- app/assets/javascripts/discourse/app/controllers/user-activity-bookmarks.js
- app/assets/javascripts/discourse/app/routes/user-activity-bookmarks.js
Clicking on a bookmark and then back will preserve the scrolling
position.
> FEATURE: Save scroll position on bookmarks page

- app/assets/javascripts/discourse/app/components/topic-navigation-popup.js
- app/assets/javascripts/discourse/app/templates/components/topic-navigation-popup.hbs
- app/assets/javascripts/discourse/app/templates/topic.hbs
- app/assets/stylesheets/common/base/topic.scss
Adds a plugin outlet that can be used to insert a popup over topic timeline.
> FEATURE: Add topic-navigation plugin outlet and popup component

- app/assets/javascripts/discourse/app/templates/components/edit-category-settings.hbs
- app/assets/javascripts/discourse/app/templates/components/edit-category-tags.hbs
- app/assets/javascripts/discourse/app/templates/components/relative-time-picker.hbs
> DEV: Cleanup `for` attributes in category edit screens

- spec/components/post_creator_spec.rb
- spec/components/post_destroyer_spec.rb
- spec/components/post_revisor_spec.rb
- spec/models/notification_spec.rb
- spec/models/post_spec.rb
- spec/models/topic_spec.rb
- spec/models/user_action_spec.rb
- spec/models/user_spec.rb
- spec/requests/admin/users_controller_spec.rb
- spec/requests/post_actions_controller_spec.rb
- spec/services/post_alerter_spec.rb
- spec/services/user_merger_spec.rb
> PERF: Speed up the tests by pre-fabricating more things

- app/assets/javascripts/discourse/app/lib/category-tag-search.js
- app/assets/javascripts/discourse/tests/acceptance/tags-test.js
- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/tag-drop-test.js
- app/assets/javascripts/select-kit/addon/components/mini-tag-chooser.js
- app/assets/javascripts/select-kit/addon/components/tag-chooser.js
> FIX: uses new format for search tag endpoint to prevent issues

- spec/requests/static_controller_spec.rb
Fixes flakyness introduced in #15324
> DEV: Make i18n spec ignore these test-only settings

- spec/requests/users_controller_spec.rb
> PERF: Prefabricate more parts of users_controller_spec

- app/assets/javascripts/polyfills.js
The polyfill was scrolling much slower than browser that actually support the feature. See: https://github.com/iamdustan/smoothscroll/issues/13
This commit is based on https://github.com/dss886/smoothscroll/commit/1baba758a7451680a1d82f32f976fb9e18ab0fbf
> DEV: Tweak smooth-scroll polyfill speed

- app/assets/javascripts/discourse/app/components/site-header.js
I somehow changed the sign before committing #15221 🤦
> FIX: Incorrect header offset calculation

- app/assets/javascripts/discourse-common/addon/lib/dom-from-string.js
- app/assets/javascripts/discourse/tests/unit/lib/dom-from-string-test.js
- app/assets/javascripts/discourse/tests/unit/lib/formatter-test.js
- app/assets/javascripts/discourse/tests/unit/lib/link-mentions-test.js
- app/assets/javascripts/pretty-text/addon/oneboxer.js
> DEV: creates domFromString utility function

- app/assets/javascripts/discourse/app/widgets/post-small-action.js
- app/assets/javascripts/discourse/tests/integration/widgets/post-small-action-test.js
> DEV: supports actionClick for small actions

- app/assets/javascripts/discourse/app/initializers/onebox-decorators.js
> DEV: allows to import decorateGithubOneboxBody

- app/assets/javascripts/discourse/app/components/emoji-picker.js
- app/assets/javascripts/discourse/app/templates/components/emoji-picker.hbs
> UX: correctly handles escape on emoji picker

- app/assets/javascripts/discourse/app/widgets/post-small-action.js
- app/assets/javascripts/discourse/tests/integration/widgets/post-small-action-test.js
This will allow to have more complex behaviors in post-small-actions, while keeping most of the behavior consistent.
> DEV: implements actionDecriptionWidget

- spec/components/guardian_spec.rb
- spec/components/topic_query_spec.rb
- spec/jobs/export_user_archive_spec.rb
- spec/models/group_user_spec.rb
- spec/models/topic_spec.rb
- spec/models/user_spec.rb
- spec/requests/list_controller_spec.rb
> PERF: Make tests faster by prefabricating more things

- spec/requests/topics_controller_spec.rb
See: https://github.com/discourse/discourse/runs/4589134998?check_suite_focus=true
> DEV: Fix a flaky test

- app/assets/javascripts/discourse/app/templates/components/choose-topic.hbs
The list of topics is not wrapped in a div currently so you can't put a max height on it. I would like to in the chat plugin :)
> DEV: Add div around choose-topic results

- app/assets/javascripts/discourse/app/components/choose-topic.js
> DEV: Add callback when search is empties in choose-topic

- lib/version.rb
> Version bump to v2.8.0.beta10

- spec/requests/topics_controller_spec.rb
> DEV: Avoid shadowing variables in topics_controller_spec

- app/controllers/static_controller.rb
- spec/requests/static_controller_spec.rb
> FIX: SiteSetting.title was being polluted in StaticController

- app/assets/javascripts/discourse/app/services/emoji-store.js
> DEV: correctly notify property changes of emoji store

- spec/requests/topics_controller_spec.rb
> DEV: Re-organize TopicsController#reset_new tests

- config/locales/server.en.yml
> Improve translation in pending reviewables reminder.

- app/assets/javascripts/discourse/app/routes/new-message.js
- app/assets/javascripts/discourse/tests/acceptance/new-message-test.js
https://meta.discourse.org/t/possible-to-compose-pre-filled-multi-user-private-message-via-url/78020
> FEATURE: allow sending message via a link to multiple users

- app/assets/javascripts/discourse/app/controllers/composer.js
- app/assets/javascripts/discourse/app/models/composer.js
> DEV: Add `composer-open` class to body element when compsoer is open

- app/assets/javascripts/discourse/app/templates/invites/show.hbs
- app/assets/stylesheets/common/base/login.scss
- app/assets/stylesheets/desktop/login.scss
- app/assets/stylesheets/mobile/login.scss
Desktop (light mode):
Desktop (dark mode):
Mobile:
> UX: improved invite accept page layout

- config/initializers/100-logster.rb
> Update logster ignore patterns

- app/assets/javascripts/discourse/app/components/emoji-picker.js
- app/assets/javascripts/discourse/app/templates/components/emoji-picker.hbs
Some details in https://review.discourse.org/t/dev-fix-linting-issue-with-emoji-keydown-event-15352/28596/6?u=pmusaraj 
cc @davidtaylorhq @jjaffeux
> DEV: revert linting workaround for emoji picker `keydown` action

- spec/requests/topics_controller_spec.rb
> PERF: Turn common test prefixes into contexts in topics_controller_spec

- app/assets/javascripts/discourse/app/app.js
> DEV: Remove JQuery usage from app.js

- config/locales/client.en.yml
as discussed: https://dev.discourse.org/t/improve-copy-on-send-me-email-when-user-pref/58401/3?u=tobiaseigen
> improved copy on "send me email when.." user pref

- lib/email/receiver.rb
> DEV: Add email bounce DiscourseEvent for plugins

- app/assets/javascripts/pretty-text/addon/engines/discourse-markdown-it.js
- app/assets/javascripts/pretty-text/addon/pretty-text.js
The code had no effect on how the markdown-it is being configured.
> DEV: Removing unused lines of code.

- app/assets/javascripts/discourse/tests/unit/lib/i18n-test.js
- app/assets/javascripts/locales/i18n.js
…for easier debugging of i18n issues.
> DEV: Add count to missing translation strings

- app/assets/javascripts/discourse/app/pre-initializers/theme-errors-handler.js
> DEV: Correct method name in theme-errors-handler pre-initializer

- spec/requests/topics_controller_spec.rb
It's very much possible for there to be a topic with id 999.
> DEV: Fix a flaky spec

- app/models/badge.rb
- app/models/category.rb
- app/models/directory_column.rb
- app/models/email_token.rb
- app/models/embeddable_host.rb
- app/models/invite.rb
- app/models/post.rb
- app/models/topic.rb
- app/models/topic_timer.rb
- app/models/topic_user.rb
- app/models/upload.rb
- app/models/user_api_key.rb
- app/models/user_stat.rb
This reverts commit 9f5c8644d060b462395135bf7ea2a48f831e129d.
Have to revert because the ignored columns have not been dropped.
> Revert "DEV: Remove stale ignored_columns from models."

- app/assets/javascripts/discourse/app/widgets/post-small-action.js
- app/serializers/post_serializer.rb
- config/locales/client.en.yml
- spec/serializers/post_serializer_spec.rb
The wording "made this topic public" made confusion in login required forums.
> UX: change text of public_topic action code in login required sites.

- app/assets/javascripts/discourse/app/templates/invites/show.hbs
There's no general way to target an invite page with CSS, this adds the `invite-page` class to body tag.
> DEV: add invite-page class

- app/controllers/invites_controller.rb
- lib/auth/default_current_user_provider.rb
- spec/requests/invites_controller_spec.rb
> SECURITY: Do not sign in unapproved users

- app/assets/stylesheets/common/base/login.scss
- app/assets/stylesheets/desktop/login.scss
improves some spacing, alignment, and flexibility for long content
Before:
After:
> UX: adjust invite and related form spacing

- app/assets/javascripts/discourse/app/components/d-button.js
- app/assets/javascripts/discourse/tests/integration/components/d-button-test.js
> DEV: using Enter on a focused button should trigger action

- app/assets/stylesheets/common/base/onebox.scss
> FIX: attempts to compensate for first line spacing with pre-line

- lib/version.rb
> Version bump to v2.8.0.beta11

- app/assets/stylesheets/common/base/onebox.scss
- lib/onebox/templates/twitterstatus.mustache
> FIX: limits pre-line impact to tweet text

- app/assets/javascripts/discourse/app/components/quote-button.js
- app/assets/stylesheets/common/base/topic-post.scss
https://user-images.githubusercontent.com/6270921/149589375-5ee14846-3463-462e-856a-81fc7e7bb461.mp4
> UX: Animate the movement of the quote button on selection change

- app/assets/javascripts/discourse/tests/acceptance/bookmarks-test.js
- app/assets/javascripts/discourse/tests/acceptance/click-track-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-test.js
- app/assets/javascripts/discourse/tests/acceptance/fast-edit-test.js
- app/assets/javascripts/discourse/tests/acceptance/jump-to-test.js
- app/assets/javascripts/discourse/tests/acceptance/post-history-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-quote-button-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/assets/javascripts/discourse/tests/acceptance/unknown-test.js
At Sam's request, these are causing a lot of build
problems right now.
> DEV: Skip failing flaky tests for now

- app/assets/javascripts/discourse/tests/unit/models/topic-test.js
> DEV: Fix a computed override in tests

- app/assets/javascripts/discourse/app/lib/autocomplete.js
- app/assets/javascripts/discourse/tests/acceptance/composer-editor-mentions-test.js
* Adds test to document the behavior we were seeing.
> FIX: Autocomplete incorrectly replacing text if used mid sentence.

- app/assets/javascripts/discourse/app/components/quote-button.js
Some safari-specific logic was inadvertently removed during the refactoring in b2d45c59. This commit restores it. The logic requires some state, so the getRangeBoundaryRect helper has to be moved back into the Component class. The functional change in this commit is the three lines enclosed by `if (this.capabilities.isSafari) {`.
> FIX: Quick-quote on Safari

- app/assets/javascripts/discourse/app/controllers/create-invite.js
- app/assets/javascripts/discourse/app/templates/modal/create-invite.hbs
- app/controllers/invites_controller.rb
- app/models/concerns/has_sanitizable_fields.rb
- app/models/invite.rb
- lib/validators/email_validator.rb
- spec/models/invite_spec.rb
Context: https://meta.discourse.org/t/html-tags-are-explicit-after-latest-update/214220
> FIX: Mark invites flash messages as HTML safe.

- app/assets/javascripts/discourse/app/templates/mobile/list/topic-list-item.hbr
Testing this is kidding complicated ATM (especially mobile template with hbr) , this is a component we should definitely aim to test very extensively when we move away from hbr templates.
> FIX: correctly access last poster username

- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
This creates a helper function with all the cleanup tasks we need to do
after tests, then makes sure to call it after tests that previously
weren't.
This fixes a lot of flakey tests.
> DEV: A bunch of tests (like controller) weren't cleaning up

- app/assets/javascripts/pretty-text/engines/discourse-markdown/newline.js
Backport https://github.com/markdown-it/markdown-it/commit/ffc49ab46b5b751cd2be0aabb146f2ef84986101
> FIX: possible ReDOS in markdown newline rule

- app/models/concerns/has_custom_fields.rb
This commit makes a more specific N1NotPreLoadedError from
StandardError to raise when a custom field is loaded before
being preloaded, so it is easier to test that this does
not happen from plugins. Also adds the name of the class
trying to load the custom field to the error message.
> DEV: Add more info to N1 custom field error

- app/assets/javascripts/discourse/app/lib/uploads.js
- app/assets/javascripts/discourse/tests/integration/components/avatar-uploader-test.js
Follow up to 64b089072a9ec29c8534819da31a916a98d15e47.
> DEV: Add test for avatar-uploader

- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
> DEV: use query() instead of queryAll() in tests

- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
Follow-up to https://github.com/discourse/discourse/commit/a742952c8d26f9a1cd3ff1a27722cf37a4d4847f.
> DEV: Update fixture to fix tests

- .github/workflows/tests.yml
- app/assets/javascripts/discourse/tests/test-boot-ember-cli.js
In browser this uses the `seed` config, in ember exam it adds `--random`
as a parameter.
> DEV: Run Ember CLI tests in random order

- app/assets/javascripts/discourse/tests/acceptance/user-activity-read-test.js
The path should be `/topics/bulk` not `topics/bulk` (leading slash.)
> FIX: This was causing a flaky test in Ember CLI

- app/assets/javascripts/discourse/app/lib/plugin-api.js
> DEV: Fix typo in comment.

- lib/version.rb
> Version bump to v2.9.0.beta1

- app/assets/javascripts/discourse/app/components/d-editor.js
> DEV: remove an unused function in d-editor

- config/locales/server.en.yml
> I18N: Improve copy on blocked words error messages

- app/assets/javascripts/discourse-common/addon/lib/get-url.js
- app/assets/javascripts/discourse/tests/acceptance/bookmarks-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-edit-conflict-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/setup-tests.js
Many of the tests work now that other, general fixes have been made.
I've deleted some that seem to have lost functionality.
> DEV: Clean up skipped tests

- app/assets/javascripts/discourse/app/components/quote-button.js
> PERF: prevents any fast edit work if you can't edit

- app/assets/javascripts/discourse/app/components/quote-button.js
- app/assets/javascripts/discourse/app/lib/utilities.js
> PERF: attempts to resort to compute markdown in less cases

- app/assets/stylesheets/common/software-update-prompt.scss
Also fixes icon size and position
> UX: Add hover style to refresh-page dismiss button

- app/assets/stylesheets/common/admin/customize.scss
> UX: Slightly tweak /admin/customize/themes CSS

- app/assets/stylesheets/common/base/compose.scss
- app/assets/stylesheets/mobile/compose.scss
> FIX: Composer fields on small desktop sizes

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/yarn.lock
This makes a small improvement to 'cold cache' ember-cli build times, and a large improvement to 'warm cache' build times
(As discussed in https://github.com/discourse/discourse/pull/15494#pullrequestreview-848498059)
> PERF: Update ember-auto-import

- app/assets/javascripts/discourse/app/templates/user.hbs
> DEV: new plugin outlet on user page

- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/mixins/bulk-topic-selection.js
- app/assets/javascripts/discourse/app/templates/components/topic-list.hbs
- app/assets/javascripts/discourse/tests/acceptance/topic-bulk-actions-test.js
An admin/moderator feature, it lets users press Shift to select a range of topics when bulk selecting is enabled. 
Screencast: 
https://user-images.githubusercontent.com/368961/150657400-d2b2517b-7f52-4bdd-9143-907c6cf8a0ff.mp4
> FEATURE: support Shift + click selecting bulk topics

- plugins/discourse-narrative-bot/config/locales/server.en.yml
Adding quotes to the existing quotes used by Discobot.  There do not seem to be any further tests needed for this.
> Increase geographical diversity of quotes

- app/helpers/qunit_helper.rb
This regressed in f4c6a6185517a7d8a17c3faefb7e2e8cc67c44a8
> DEV: Load all vendor files for theme-qunit under prod ember-cli

- config/routes.rb
- lib/admin_constraint.rb
This reverts commit 492226a9737fc6c8d672383316569b7d2c523a55.
> Revert "DEV: Add context in `AdminConstraint` (#15838)"

- app/assets/javascripts/discourse/app/initializers/inject-objects.js
> DEV: Add Ember-CLI backwards compatibility for Discourse.Site

- app/models/post.rb
- app/models/reviewable_flagged_post.rb
> DEV: Convert `:send_system_message` arguments to strings

- lib/onebox/engine/wistia_onebox.rb
> FIX: Explicitly set `allowfullscreen` on Wistia Oneboxes

- lib/onebox/engine/wistia_onebox.rb
- spec/lib/onebox/engine/wistia_onebox_spec.rb
Follow-up to 4ef56b0ca4d997e5d0b331c488c83b7f574721df
> DEV: Add tests for wistia onebox.

- lib/freedom_patches/cose_rsapkcs1.rb
- lib/webauthn.rb
- spec/lib/webauthn/security_key_authentication_service_spec.rb
These algorithms are not implemented by cose-ruby, but used in the web
authentication API.
> FEATURE: RS512, RS384 and RS256 COSE algorithms

- app/assets/javascripts/discourse/app/components/quote-button.js
- app/assets/javascripts/discourse/app/lib/quote.js
- app/assets/javascripts/discourse/app/lib/transform-post.js
- app/assets/javascripts/discourse/app/models/composer.js
- app/assets/javascripts/discourse/app/widgets/post.js
- app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-quote-button-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/serializers/post_serializer.rb
This reverts commit 5a93ce421da4e52b9d649cf609cd7d79d21a1683.
> Revert "DEV: Prioritize full name when setting active (#15820)"

- spec/requests/api/posts_spec.rb
- spec/requests/api/schemas/json/post_replies_response.json
- spec/requests/api/schemas/json/user_update_username_request.json
- spec/requests/api/users_spec.rb
Added api docs for:
- update username
- get post replies
> DEV: Update api docs to update username and to get post replies

- app/assets/javascripts/discourse-common/addon/lib/deprecated.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
This reverts commit a4ff69bd99e5ca00ee8c26cf0e9bbabc3c36e23b.
Follow-up to 8e5b945b0ffd8ab5f5156ae52e460cef0136a551
> Revert "DEV: Prefix deprecation notices and api warnings with theme name/id"

- app/services/user_stat_count_updater.rb
We already have existing tests but there is little to no value in testing the entire string.
> DEV: Fix small typo.

- lib/plugin/metadata.rb
> UX: Add whos-online to official plugin list

- script/import_scripts/phpbb3/settings.yml
> FIX: Default settings for phpBB3 import were broken

- lib/version.rb
> Version bump to v2.9.0.beta2

- app/assets/javascripts/discourse-common/addon/lib/deprecated.js
- app/assets/javascripts/discourse/app/app.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/lib/source-identifier.js
- app/assets/javascripts/discourse/app/pre-initializers/theme-errors-handler.js
- app/assets/stylesheets/common/base/discourse.scss
- app/models/theme.rb
- app/models/theme_field.rb
- config/locales/client.en.yml
- spec/models/theme_field_spec.rb
Repeat of #15886, with one additional commit to fix use of deprecated() in the pretty-text environment
> DEV: Theme error/deprecation improvements

- lib/tasks/assets.rake
The `assets:precompile` rake task loads the full Ruby app, which can consume around 500mb of RAM by itself. Using `exec` to run `ember build` allows us to free up the Ruby memory and make more space for `ember build`
> PERF: Terminate `rake` process during `ember build`

- app/helpers/application_helper.rb
Followup to a01b1dd648aa11058c2e8b191b11e56a33f20a83
> FIX: Update application_helper logic now that Ember CLI is default

- script/bulk_import/base.rb
- script/import_scripts/base.rb
The cakeday plugin doesn't use the year.
> DEV: Don't import year of birth

- app/assets/javascripts/discourse/app/widgets/post.js
- app/assets/javascripts/discourse/app/widgets/poster-name.js
- app/assets/stylesheets/common/foundation/helpers.scss
Make name / avatar non-clickable for anon users
> DEV: Make user card non-clickable for anon users:

- app/assets/javascripts/discourse/app/templates/components/date-picker.hbs
> UX: Use autocomplete="off" for date-picker

- app/assets/javascripts/discourse-common/addon/lib/icon-library.js
- app/models/notification.rb
- app/services/post_alerter.rb
- spec/requests/api/schemas/json/site_response.json
This is needed for the notification sent when quoting
chat messages inside a post.
> DEV: Add chat_quoted notification type

- Gemfile.lock
This includes significant upstream performance improvements. For details, see https://github.com/discourse/message_bus/commit/984009119ef3c3fb08053a75a7850b2210dee2b5
> PERF: Bump message_bus to 4.1

- config/locales/client.en.yml
> UX: Add 'update' to theme error message

- app/controllers/session_controller.rb
- app/controllers/users_controller.rb
- app/jobs/regular/bulk_invite.rb
- app/jobs/regular/group_smtp_email.rb
- app/models/email_change_request.rb
- app/models/user.rb
- lib/email.rb
- lib/validators/email_address_validator.rb
- lib/validators/email_setting_validator.rb
- lib/validators/email_validator.rb
- lib/validators/reply_by_email_address_validator.rb
- script/bulk_import/base.rb
- script/import_scripts/base.rb
- script/import_scripts/drupal.rb
- script/import_scripts/vbulletin.rb
- spec/components/validators/email_address_validator_spec.rb
- spec/components/validators/email_validator_spec.rb
- DEV: pull email address validation out to a new EmailAddressValidator
- FIX: ReplyByEmailAddressValidator should leverage EmailAddressValidator
> emailaddrvalidator

- app/assets/javascripts/discourse/app/controllers/topic-bulk-actions.js
- app/assets/javascripts/discourse/tests/acceptance/topic-bulk-actions-test.js
- app/controllers/topics_controller.rb
- app/models/post_timing.rb
- config/locales/client.en.yml
- lib/topics_bulk_action.rb
- spec/lib/topics_bulk_action_spec.rb
- spec/models/post_timing_spec.rb
It is enabled only if defer is enabled in user options too and if the
button shows up in the topic's footer.
> FEATURE: Rename Reset Read bulk action to Defer

- app/models/web_hook_event_type.rb
- config/initializers/012-web_hook_events.rb
- config/locales/client.en.yml
- db/fixtures/007_web_hook_event_types.rb
- spec/fabricators/web_hook_fabricator.rb
- spec/models/web_hook_spec.rb
> FEATURE: adds the user_promoted event to webhooks

- spec/requests/users_controller_spec.rb
> DEV: Freeze time in time-sensitive specs

- app/assets/javascripts/discourse/app/components/d-editor.js
- app/assets/javascripts/discourse/app/components/emoji-picker.js
- app/assets/javascripts/discourse/app/templates/components/d-editor.hbs
- app/assets/javascripts/discourse/app/templates/components/emoji-picker.hbs
…has regressed at some point:
After:
> FIX: Setting emoji filter from initial autocomplete

- app/assets/javascripts/discourse/app/templates/modal/fullscreen-code.hbs
> FIX: Minor indentation fix for fullscreen code

- app/assets/javascripts/discourse/app/lib/source-identifier.js
> DEV: Correctly detect plugin JS with `.br.js` extension

- lib/discourse_ip_info.rb
- spec/requests/admin/users_controller_spec.rb
These changes can be used by plugins to locate the user more precisely.
> FEATURE: Return geoname IDs from MaxMindDb

- lib/post_action_destroyer.rb
- spec/lib/post_action_destroyer_spec.rb
> FIX: correctly notifies subscribers with post_action_destroyer

- app/assets/javascripts/discourse/app/mixins/scroll-top.js
> DEV: drops jquery for scroll-top mixin

- app/assets/javascripts/discourse-common/addon/utils/handle-descriptor.js
- app/assets/javascripts/discourse/tests/unit/utils/decorators-test.js
(also fixes `writeable` -> `writable` typo)
> DEV: Allow `@discourseComputed` in native classes

- app/models/api_key_scope.rb
- config/locales/client.en.yml
This change adds a new api scope for updating topics.
See: https://meta.discourse.org/t/219805
> DEV: Add api scoping for updating topics.

- app/assets/javascripts/discourse/app/models/category-list.js
- app/assets/javascripts/discourse/app/templates/components/subcategories-with-featured-topics.hbs
- app/assets/javascripts/discourse/tests/acceptance/categories-test.js
- app/assets/stylesheets/common/base/category-list.scss
- app/controllers/categories_controller.rb
- app/models/category_list.rb
- app/models/category_page_style.rb
- config/locales/client.en.yml
- spec/requests/categories_controller_spec.rb
This categories view is designed for sites which make heavy use of subcategories, and use top-level categories mainly for grouping
> FEATURE: Introduce 'Subcategories with featured topics' view

- app/assets/javascripts/discourse/app/lib/lightbox.js
- app/assets/javascripts/discourse/tests/acceptance/lightbox-test.js
- app/assets/stylesheets/common/base/magnific-popup.scss
- config/locales/client.en.yml
- lib/svg_sprite/svg_sprite.rb
Adds a link to the original image next to the download link. It can be
used to view full resolution image in the browser.
> FEATURE: Add link to original image in lightbox

- app/controllers/posts_controller.rb
- spec/requests/posts_controller_spec.rb
> FIX: Make reply-ids public by fixing a typo

- app/assets/javascripts/discourse/app/controllers/discovery/categories.js
- app/assets/javascripts/discourse/app/templates/components/subcategories-with-featured-topics.hbs
- app/assets/javascripts/discourse/app/templates/mobile/components/subcategories-with-featured-topics.hbs
- app/assets/stylesheets/common/base/category-list.scss
> FEATURE: Add mobile support for subcategories-with-featured-topics

- docs/SECURITY.md
Add note regarding low quality reports being received via email.
> DEV: Update security policy

- app/models/api_key_scope.rb
In the API keys page where admins can create API keys with restricted scopes, each scope shows a list of URLs that it allows. But currently, this list of allowed URLs shows incomplete URLs for scopes that are added by plugins. For example, the allowed URL for the "run queries" scope of the data-explorer plugin is currently:
But the correct URL for this scope is `/admin/plugins/explorer/queries/:id/run`. The first 3 segments of the path are the mount path of the plugin's engine and it's missing because the routes set of the engine doesn't include the mount path. So this PR gets the mount path and prepends it to the URL.
It's not possible to write tests for this change because plugins are not loaded in the test environment by default when core's tests suite is running.
> FIX: Include engine mount path for API scopes added by plugins

- lib/retrieve_title.rb
> FIX: return nil when RetrieveTitle.crawl fails

- app/assets/javascripts/discourse/testem.js
- lib/tasks/docker.rake
> DEV: Use Ember CLI for docker.rake CI testing

- app/jobs/regular/pull_hotlinked_images.rb
> DEV: Log more when verbose_upload_logging is enabled

- README.md
> DEV: Update copyright year in README.

- lib/tasks/assets.rake
> FIX: Skip ember-cli build memory optimisation for multiple rake tasks

- app/assets/javascripts/admin/addon/controllers/admin-users-list-show.js
> FIX: remove racing requests for admin users

- app/models/notification.rb
- config/site_settings.yml
> DEV: Reserve usernames for chat and sunset `chat_group_mention`

- lib/final_destination.rb
The parameter is not used and it did not work properly anyway because sometimes `@uri` is used instead, which may be different.
> DEV: Remove unused uri parameter

- .github/workflows/tests.yml
We have 3 branches which we care about, main, beta and stable.
However, each of this branch has different compatibilties with plugins
and we want to respect that.
> DEV: Pull compatible version for plugins in Github test workflow.

- app/assets/javascripts/discourse/app/components/d-section.js
When using the loading-slider, the component instance is re-used across different pages and so the didInsertElement/willDestroyElement hooks are not fired during page transitions. Instead, we can lean on `didReceiveAttrs`.
Similar fix to 87b98e2862
Note that the `scrollTop` feature is still problematic under the loading slider. That will need to be addressed in a future commit.
> DEV: Refactor d-section to function correctly with loading-slider

- app/assets/javascripts/discourse/tests/helpers/component-test.js
> DEV: Add missing service injections

- lib/chrome_installed_checker.rb
- lib/tasks/qunit.rake
- lib/tasks/smoke_test.rake
> DEV: Add chromium to ChromeInstalledChecker

- app/assets/javascripts/discourse/app/lib/utilities.js
In certain cases (like chat quoting) we need to be able
to call the API with an async AJAX call before copying
the results to the clipboard. The only way to reliably
do this is by handing off the AJAX promise to a ClipboardItem.
This commit introduces a new clipboardCopyAsync function
to handle this, which will stand alongside the existing
clipboardCopy function which can be used when no AJAX
request is necessary.
Note: It's not possible to test this, the clipboard API throws
an error in our testing environments.
> DEV: Add clipboardCopyAsync API to utilities

- app/assets/javascripts/admin-plugins.js.erb
- app/assets/javascripts/admin.js
- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
- app/assets/javascripts/discourse/testem.js
- app/assets/javascripts/discourse/tests/index.html
- app/views/qunit/theme.html.erb
- config/application.rb
Why no tests: this PR is all about getting tests to run - We don't have a test harness to test the existence of a test harness :)
> FIX: When using Ember CLI, plugin admin code was not being loaded in tests

- app/assets/javascripts/discourse/app/mixins/card-contents-base.js
> DEV: appEvent to close user card

- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/stylesheets/common/base/_topic-list.scss
This reverts commit 5d77f485cbcdb7e5f6b1e82c88d06c58f2b5d22e.
There are some edge cases that we need to handle better. Reverting this
commit because we're going to do a beta release later today.
> Revert "A11Y: Focus last viewed topic in topic lists (#16240)"

- lib/version.rb
> Version bump to v2.9.0.beta3

- app/assets/javascripts/discourse/app/components/topic-entrance.js
- app/assets/javascripts/discourse/app/templates/components/topic-entrance.hbs
- app/assets/javascripts/discourse/app/templates/list/posts-count-column.hbr
- app/assets/javascripts/discourse/app/templates/list/topic-list-item.hbr
- app/assets/javascripts/discourse/app/templates/topic-list-header.hbr
- app/assets/javascripts/discourse/tests/acceptance/topic-entrance-test.js
- config/locales/client.en.yml
There are multiple changes in this PR and they're all for improving accessibility of topics list. Each commit improves one thing and it's explained in the commit message/description.
> A11Y: Various topic list accessibility improvements

- app/serializers/reviewable_score_serializer.rb
We have a new API introduced [here](https://github.com/discourse/discourse/pull/14553).
> DEV: Remove old link building code.

- spec/requests/session_controller_spec.rb
Since we give a 200 response for login errors, we should be checking
whether the error key exists in each case or not.
Some tests were broken, because they weren't checking.
> DEV: Make tests more resilient

- app/assets/javascripts/discourse/app/controllers/ignore-duration.js
- app/assets/javascripts/discourse/app/controllers/user.js
- app/assets/javascripts/discourse/app/templates/modal/ignore-duration.hbs
- app/assets/javascripts/discourse/tests/acceptance/user-test.js
- app/controllers/users_controller.rb
- config/locales/server.en.yml
- spec/requests/users_controller_spec.rb
> FIX: Bug setting notification level to muted/ignored on user page

- app/assets/javascripts/browser-detect.js
- app/assets/javascripts/polyfills.js
> DEV: Add polyfill for `String.prototype.replaceAll`

- app/assets/javascripts/discourse/app/templates/components/user-card-contents.hbs
- app/assets/stylesheets/mobile/components/user-card.scss
This PR adds a new button outlet to the user card next to current `message` button
> DEV: Add additional outlet to user-card next to `message` button

- app/assets/javascripts/discourse/app/templates/components/user-card-contents.hbs
- app/assets/javascripts/discourse/app/templates/user.hbs
Couple of new plugin outlets to avoid template overrides in a customer theme
> DEV: New plugin outlets for user and user-card

- app/assets/javascripts/discourse/app/controllers/share-topic.js
- app/assets/javascripts/discourse/tests/acceptance/share-topic-test.js
Since 3fd7b31a2aa79dabcc34625c10877fcf737d5855 some tests
were failing with this error:
> Error: Unhandled request in test environment: /c/feature/find_by_slug.json
> (GET) at http://localhost:7357/assets/test-helpers.js
This commit fixes the issue by adding the missing pretender. Also
noticed while fixing this that the parameter for the translation
was incorrect -- it was `group` instead of `groupNames`, so that
is fixed here too, along with moving the onShow functions into
@afterRender decorated private functions. There is no need for the
appevent listeners.
> DEV: Fix failing share topic tests

- app/services/user_destroyer.rb
This is much more memory-efficient when there are 1000s of rows
> PERF: Update UserDestroyer to fetch histories and actions in batch

- app/assets/javascripts/discourse/app/templates/user/badges.hbs
- app/assets/javascripts/discourse/app/templates/user/summary.hbs
Adding these for a customer theme
> DEV: add plugin outlets for user badges

- app/models/group.rb
- app/serializers/category_serializer.rb
- spec/serializers/category_serializer_spec.rb
> Backport beta

- app/models/group.rb
- app/serializers/category_serializer.rb
- spec/serializers/category_serializer_spec.rb
> Backport stable

- app/assets/javascripts/discourse/app/templates/user/summary.hbs
Need some more data for a customer theme!
> DEV: pass user to user-summary outlets

- app/assets/javascripts/discourse/testem.js
- Repeat failure output at end (similar to rspec)
- When running in GitHub actions, set a workflow error message
> DEV: Improve `ember test` (testem) output

- app/assets/stylesheets/common/base/code_highlighting.scss
This reverts commit 11abb50cf7b78886d6181628d78a52097e0355c6.
Styling change is still under discussion
> Revert "UX: Inline code block edit (#16394)"

- app/assets/javascripts/browser-update.js
- app/assets/stylesheets/common/base/crawler_layout.scss
- app/views/layouts/_noscript_footer.html.erb
- app/views/layouts/_noscript_header.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/crawler.html.erb
See commit messages. To be rebased-and-merged.
> Various crawler view improvements

- app/assets/javascripts/discourse/app/controllers/share-topic.js
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/tests/acceptance/share-topic-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/controllers/categories_controller.rb
- app/serializers/category_serializer.rb
- config/routes.rb
- spec/requests/categories_controller_spec.rb
- spec/serializers/category_serializer_spec.rb
> Beta backport

- app/assets/javascripts/discourse/app/mixins/uppy-upload.js
These calls were missed in ac672cfcc6726b9309904857dd246f5ee54b20a8
> DEV: Minor in-progress-uploads refactor

- app/models/tag_group.rb
> FIX: Ensure category_required_tag_groups are destroyed with tag_groups

- app/assets/javascripts/admin/addon/templates/user-index.hbs
It's hard to target these with CSS at the moment
> add classes to danger buttons on user admin page

- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/tests/acceptance/category-edit-test.js
> FIX: Ensure allowed_tags and allowed_tag_groups can be removed

- app/models/screened_ip_address.rb
- app/services/staff_action_logger.rb
- spec/models/screened_ip_address_spec.rb
- spec/services/staff_action_logger_spec.rb
> FEATURE: Make IPv4 and IPv6 roll up more granular

- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/templates/mobile/list/topic-list-item.hbr
- app/assets/stylesheets/mobile/topic-list.scss
This was working initially... but seems to have some problems? Not sure at a glance. 
Reverts:
0e88cffaf4ba6e079c94955e3fe076ab3fede377
0ff66b3b74e586ccdfd0a3b3e469889e58b9c290
> Revert: UX: Make full topic row clickable on mobile (#16440)

- app/assets/javascripts/discourse/app/components/scrolling-post-stream.js
- app/assets/javascripts/discourse/app/components/site-header.js
> Backport iOS 12 fixes to stable

- lib/email/styles.rb
Update dark mode styles for: 
- secure media borders
- code blocks
- quote blocks
> FIX: update dark mode email styles

- config/locales/server.en.yml
As suggested by https://meta.discourse.org/t/223311
> UX: Add more detail to remove full quote site setting description

- README.md
> DEV: Update browser policy to include iOS 12

- spec/models/web_hook_spec.rb
> DEV: Add test for web hooks and topic tags changes

- app/assets/javascripts/discourse/app/templates/user/summary.hbs
> DEV: adds an above-user-summary-stats outlet

- app/assets/javascripts/discourse/tests/acceptance/topic-edit-timer-test.js
Add a test for checking that the notice is not displayed if a value for the topic timer is not set.
> DEV: Add test for topic timer notice

- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/mini-tag-chooser-test.js
- app/assets/javascripts/select-kit/addon/components/mini-tag-chooser.js
- app/controllers/tags_controller.rb
- config/locales/client.en.yml
- lib/discourse_tagging.rb
- spec/requests/tags_controller_spec.rb
> FEATURE: Show prompt for required tag groups

- lib/tasks/qunit.rake
`system()` provides `chdir:` option for that.
> DEV: Don't use `Dir.chdir()`

- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
They're already cleared after each test.
> DEV: Don't clean outlet and html caches twice

- app/assets/javascripts/discourse/app/lib/load-script.js
> DEV: Clean up `loadScript()`

- app/assets/javascripts/discourse/app/mixins/add-archetype-class.js
> REFACTOR: add-archetype-class mixin

- app/assets/javascripts/discourse/tests/acceptance/search-full-test.js
It was incorrectly put inside the pretender block.
> DEV: Fix test hook placement

- app/assets/javascripts/discourse/app/initializers/live-development.js
- app/models/theme_field.rb
- drop jquery
- replaces setTimeout by later
- removes dead code which is not even working today
> REFACTOR: live-development.js

- app/assets/stylesheets/common/base/topic-admin-menu.scss
* Increase the space between icons and labels
* Increase the menu width
Before / After
> UX: Tweak topic-admin-menu alignment/size

- .github/workflows/licenses.yml
- .gitignore
- .licensed.yml
- .licensee.json
Supersedes https://github.com/discourse/discourse/pull/13590 cc @kemitchell
> DEV: Audit dependency licenses

- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/templates/mobile/list/topic-list-item.hbr
- app/assets/stylesheets/mobile/topic-list.scss
I had previously attempted this in f2468f1093fc8a865730523a5af8bb869077ea9c (now reverted), but needed to make sure `.main-link` was included as well.
> UX: Larger clickable area for mobile topic list

- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/javascripts/discourse/app/controllers/preferences/interface.js
- app/assets/javascripts/discourse/app/models/user.js
- app/assets/javascripts/discourse/app/templates/application.hbs
- app/assets/javascripts/discourse/app/templates/preferences/interface.hbs
- app/models/user_option.rb
- app/serializers/current_user_serializer.rb
- app/serializers/user_option_serializer.rb
- app/services/user_updater.rb
- config/locales/client.en.yml
- config/site_settings.yml
- db/migrate/20220428025825_add_enable_experimental_sidebar_to_user_options.rb
- spec/requests/users_controller_spec.rb
* hidden siteSetting to enable experimental sidebar
* user preference to enable experimental sidebar
* `experimental_sidebar_enabled` attribute for current user
* Empty glimmer component for Sidebar
> DEV: Setup experimental sidebar skeleton

- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/javascripts/discourse/app/templates/application.hbs
This reverts commit 98c49acad5fbacee543505313998e4f05d0b35c7.
> Revert "DEV: Setup experimental sidebar skeleton (#16575)"

- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
> DEV: Add support for GH Codespaces to ember proxy

- .github/workflows/ember_with_plugins.yml
- .github/workflows/licenses.yml
- .github/workflows/linting.yml
- .github/workflows/tests.yml
> DEV: Minor workflow updates

- script/import_scripts/base.rb
- script/import_scripts/mbox/importer.rb
- script/import_scripts/mbox/settings.yml
- script/import_scripts/mbox/support/database.rb
- script/import_scripts/mbox/support/indexer.rb
- script/import_scripts/mbox/support/settings.rb
Some small mbox importer improvements
> mbox importer improvements

- .devcontainer/devcontainer.json
> DEV: Allow Codespaces host when in Codespaces

- app/assets/javascripts/admin/addon/controllers/admin-customize-robots-txt.js
- app/assets/javascripts/admin/addon/templates/customize-robots-txt.hbs
> DEV: Fix typo in customize-robots-txt

- README.md
> UX: Add a brief accessibility summary to the README

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update ember-try to 2.0.0

- lib/backup_restore.rb
c1db9687 introduced an postgres enum type. Our database restore logic did not handle custom types correctly, and would therefore raise a 'type already exists' error when restoring any backup.
This commit adds restore handling for enums, mirroring the similar logic for tables and views.
---
(This code is not tested by rspec, but it is tested by a regular internal job at CDCK, which correctly picked up on this issue)
> FIX: Handle enum types during database restore

- app/assets/javascripts/discourse/ember-cli-build.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- config/dev_defaults.yml
- config/initializers/100-logster.rb
- lib/tasks/db.rake
> DEV: Fix typos and outdated comments

- app/assets/javascripts/discourse/app/templates/components/categories-boxes.hbs
- app/assets/javascripts/discourse/app/templates/discovery.hbs
Need these for a customer theme
> DEV: add new plugin outlets

- bin/rails
- config/initializers/006-mini_profiler.rb
- spec/rails_helper.rb
> DEV: Compatibility with TruffleRuby

- app/models/bookmark.rb
- app/models/topic_timer.rb
- app/models/upload.rb
Bookmark columns deleted in b22450c7a8d378b32291743ca602cbc477dea106
TopicTimer columns deleted in d098f51ad3a3649d34717fa6567489998709ba6c
Upload columns deleted in ef90575b918467e0417c5b5d72c22f12a8550b43
> DEV: Remove ignored columns

- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/javascripts/discourse/app/controllers/application.js
- app/assets/javascripts/discourse/app/routes/application.js
- app/assets/javascripts/discourse/app/templates/application.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar.hbs
- app/assets/javascripts/discourse/app/widgets/header-contents.js
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/app/widgets/sidebar-toggle.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-test.js
- app/assets/stylesheets/common/base/_index.scss
- app/assets/stylesheets/common/base/header.scss
- app/assets/stylesheets/common/base/sidebar.scss
- app/assets/stylesheets/desktop/discourse.scss
First approved in https://github.com/discourse/discourse/pull/16590 but was reverted as styling on an internal plugin broke.
> DEV: First desktop design interface pass at experimental sidebar take 2.

- app/assets/javascripts/admin/addon/templates/user-index.hbs
Context: https://deprecations.emberjs.com/v3.x/#toc_ember-glimmer-with-syntax
> DEV: Remove last instance of {{with}} helper

- config/initializers/100-sidekiq.rb
- lib/sidekiq_logster_reporter.rb
This fits more naturally in its own file.
> DEV: Move SidekiqLogsterReporter out of initializer

- app/assets/javascripts/discourse/app/components/sidebar/section-link-to.js
- app/assets/javascripts/discourse/app/components/sidebar/section.js
- app/assets/javascripts/discourse/app/components/sidebar/topics-section.js
- app/assets/javascripts/discourse/app/controllers/discovery-sortable.js
- app/assets/javascripts/discourse/app/templates/components/sidebar.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/section-link.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/section.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/topics-section.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-topics-section-test.js
- app/assets/stylesheets/common/base/sidebar.scss
- config/locales/client.en.yml
* Implements everything, tracked and bookmarked links
* Implements unread/new count for everything link
> DEV: First pass at side topics section

- app/models/user_action.rb
> DEV: Expose user action types where the user was the instigator

- app/assets/javascripts/discourse/app/controllers/bookmark.js
- app/assets/stylesheets/common/components/bookmark-modal.scss
- config/locales/client.en.yml
- lib/bookmark_query.rb
- spec/lib/bookmark_query_spec.rb
* Make the modal for bookmarks display more consistently
* Make sure bookmark query can handle empty results for certain
bookmarkable queries
> DEV: Minor bookmark tweaks for polymorphism

- app/assets/javascripts/discourse/app/components/sidebar/topics-section.js
- app/assets/javascripts/discourse/app/templates/components/sidebar/section-link.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/section.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/topics-section.hbs
- config/locales/client.en.yml
* Also small refactor to reduce magical generation of translation string
key when using `Section` and `SectionLink` components.
> DEV: Add missing titles on sidebar buttons.

- app/assets/javascripts/admin/addon/controllers/admin.js
- app/assets/javascripts/discourse/app/components/reviewable-item.js
Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions
> DEV: Remove string prototype extensions

- app/controllers/application_controller.rb
- app/views/exceptions/read_only.html.erb
> FIX: Make read only errors respect the request format

- app/controllers/session_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- spec/requests/omniauth_callbacks_controller_spec.rb
> FIX: Prevent all kinds of login in readonly mode

- app/assets/javascripts/discourse/app/controllers/review-index.js
- app/assets/javascripts/discourse/app/models/reviewable.js
Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions
> DEV: Remove 'underscore' string prototype extensions

- app/controllers/session_controller.rb
> DEV: Add helper method for repeated sso logging pattern

- app/controllers/session_controller.rb
> DEV: Let's deny access to sso endpoints when disabled consistently

- Gemfile
- Gemfile.lock
This reverts commit 0d30c19b7e1034c39e9eba01d8ac11570815e15f.
Pending resolution of https://github.com/mikel/mail/issues/1489
> Revert "DEV: Drop our `mail` gem fork (#16622)"

- config/initializers/new_framework_defaults_7_0.rb
> DEV: Enable Rails 7 cache format version

- app/helpers/application_helper.rb
- app/views/topics/show.html.erb
This change is required for adding crawler view in Q&A plugin. I also updated the method to allow adding tests in plugin.
Accompanying PR in Q&A plugin: https://github.com/discourse/discourse-question-answer/pull/64
> FEATURE: allow locals to be passed in server_plugin_outlet

- app/helpers/application_helper.rb
DEV: enable plugin tests for server_plugin_outlet
> FIX: pass empty hash for view locals by default

- app/assets/javascripts/discourse/app/templates/components/topic-list-item.hbs
- app/assets/javascripts/discourse/app/templates/components/topic-list.hbs
Moving things around for better placement
> FIX: Refactor placement of plugin outlet & index use

- app/controllers/admin/site_settings_controller.rb
> REFACTOR: Remove duplicate code in `SiteSettingsController`

- lib/tasks/db.rake
This feature only was only demuxing stdout, not stderr. That means that stdout and stderr output appears out-of-order, and makes debugging migrations very confusing.
In future we may want to add stderr support to the demuxing. But right now, the concurrency variable is hard-coded to 1. Therefore the easiest fix is to bypass the demuxing.
> DEV: Only demux migration stdout if running concurrently

- app/assets/javascripts/discourse/app/components/sidebar/topics-section.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/lib/sidebar/custom-topics-section-links.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/base-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/bookmarked-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/everything-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/tracked-section-link.js
- app/assets/javascripts/discourse/app/templates/components/sidebar/section-link.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/topics-section.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-topics-section-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
> DEV: Plugin API for plugins to add links to sidebar topics section

- db/migrate/20220512011522_backfill_polymorphic_bookmarks_and_make_default.rb
Otherwise the migration can fail
> FIX: Delete extraneous topic bookmarks

- app/assets/stylesheets/common/base/onebox.scss
- lib/onebox/engine/youtube_onebox.rb
> UX: Make YouTube playlist onebox full width to match video onebox

- app/assets/javascripts/discourse/app/models/post.js
Previously, errors would only be displayed in the developer console.
> UX: Show message if rebake fails

- lib/system_message.rb
See https://github.com/discourse/discourse-local-site-contacts/pull/1
> DEV: Add event for plugins to customize system messages

- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/lib/to-markdown.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/unit/lib/to-markdown-test.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
To be used in https://github.com/discourse/discourse-spoiler-alert/pull/85
> DEV: Add to-markdown plugin api

- app/assets/javascripts/discourse/app/controllers/group-index.js
> DEV: Remove jquery from group list

- app/assets/javascripts/admin/addon/components/themes-list-item.js
> DEV: Remove jquery from themes list

- app/assets/javascripts/discourse/app/components/sidebar/topics-section.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/base-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/everything-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/topics-section/tracked-section-link.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-topics-section-test.js
> DEV: Display new/unread count for tracked link in sidebar

- app/assets/javascripts/discourse/app/components/generated-invite-link.js
> DEV: Remove jquery from invite-panel

- app/assets/javascripts/discourse/app/services/presence.js
> DEV: under specific conditions (like tests) presenceState can be null

- app/assets/javascripts/wizard/components/styling-preview.js
- app/assets/javascripts/wizard/components/wizard-field-dropdown.js
- app/assets/javascripts/wizard/components/wizard-step.js
- app/assets/javascripts/wizard/models/wizard.js
- app/assets/javascripts/wizard/templates/components/styling-preview.hbs
- app/assets/javascripts/wizard/templates/components/wizard-field.hbs
- app/assets/javascripts/wizard/templates/components/wizard-step.hbs
> FIX: Don't throw errors on wizard dropdowns

- app/assets/javascripts/discourse/app/routes/tag-show.js
- app/assets/javascripts/discourse/tests/acceptance/tags-test.js
> FIX: ensures composer is not pre-filled with none/all tags

- app/serializers/wizard_field_serializer.rb
- spec/serializers/wizard_serializer_spec.rb
> DEV: Add choices only to dropdown wizard fields

- app/assets/javascripts/discourse/app/components/watch-read.js
- app/assets/javascripts/discourse/app/lib/is-element-in-viewport.js
> DEV: De-jQuerify is-element-in-viewport

- app/assets/javascripts/discourse/app/components/watch-read.js
> DEV: De-jQuerify marking FAQ as read

- lib/topic_query.rb
- spec/lib/topic_query_spec.rb
Follow-up to 7ae647d092ff13bea0a93bf7fdfa13cc898cd6f6
> FIX: Missing tracked sub category topics from tracked topic list

- spec/models/user_spec.rb
Making sure to test this new scope.
Follow up to: 27d7b0c6de73cb0cd2bd5137b5a58c151bd83289
as well as: 3941bad0751fc2e59576d77bef531b0088571104
> DEV: Add spec for not_staged user scope

- app/assets/javascripts/discourse/app/components/tap-tile.js
- app/assets/javascripts/discourse/app/templates/modal/do-not-disturb.hbs
- app/assets/javascripts/discourse/tests/acceptance/do-not-disturb-test.js
> A11Y: Add keyboard support for do-not-disturb modal

- app/assets/javascripts/discourse-common/addon/utils/escape-regexp.js
- app/assets/javascripts/discourse/app/components/quote-button.js
- app/assets/javascripts/discourse/app/initializers/url-redirects.js
- app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
This was re-implemented in a number of places - it makes more sense as a utility function.
> DEV: Add `escapeRegExp` util

- app/assets/javascripts/discourse/app/components/sidebar/tags-section.js
- app/assets/javascripts/discourse/app/lib/sidebar/tags-section/tag-section-link.js
- app/assets/javascripts/discourse/app/templates/components/sidebar.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/tags-section.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-tags-section-test.js
- config/locales/client.en.yml
Counts for the section links will be added in a follow up commit.
> FEATURE: First pass tags section for experimental sidebar. 

- app/assets/javascripts/discourse/app/initializers/subscribe-user-notifications.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-topics-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-status-test.js
- app/models/user.rb
- app/models/user_stat.rb
- spec/lib/post_creator_spec.rb
- spec/models/draft_spec.rb
- spec/requests/user_status_controller_spec.rb
- spec/services/user_notification_schedule_processor_spec.rb
Introduces an interface to publish user updates on the server side and
helps to reduce the growing number of subscriptions on the client side.
> DEV: Centralize user updates to a single MessageBus channel.

- app/assets/javascripts/discourse/app/components/sidebar/tags-section.js
- app/assets/javascripts/discourse/app/lib/sidebar/tags-section/tag-section-link.js
- app/assets/javascripts/discourse/app/templates/components/sidebar/tags-section.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-tags-section-test.js
- app/models/topic_tracking_state.rb
- app/serializers/topic_tracking_state_serializer.rb
- spec/models/topic_tracking_state_spec.rb
- spec/serializers/topic_tracking_state_serializer_spec.rb
This allows us to accurately count the unread/new in Sidebar for each
tag.
> FEATURE: Add new/unread counts to tags section links exp sidebar

- app/controllers/application_controller.rb
- spec/requests/application_controller_spec.rb
Do not expose banner data in login_required sites
> SECURITY: banner-info

- lib/version.rb
> Version bump to v2.8.4

- lib/version.rb
> Version bump to v2.9.0.beta5

- lib/onebox/json_ld.rb
- spec/lib/onebox/json_ld_spec.rb
> FIX: Handle sites with more than 1 JSON-LD element

- app/assets/javascripts/discourse/app/services/presence.js
- app/assets/javascripts/discourse/tests/unit/services/presence-test.js
e.g.
```
presenceChannel = this.presence.getChannel('/blah');
presenceChannel.subscribe();
presenceChannel.on('change', (channel) => console.log(channel.users));
```
This commit also does some refactoring to remove the use of an unnecessary EmberObject and dynamic `defineProperty` call
> DEV: Emit a 'change' event when PresenceChannel info changes

- app/assets/javascripts/discourse/app/components/create-account.js
- app/assets/javascripts/discourse/tests/acceptance/create-account-user-fields-test.js
Context: https://github.com/discourse/discourse/pull/16983#discussion_r894721403
> DEV: @bind create-account actions

- app/assets/javascripts/discourse/app/components/sidebar/messages-section.js
- app/assets/javascripts/discourse/app/lib/page-tracker.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/group-message-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/personal-message-section-link.js
- app/assets/javascripts/discourse/app/templates/components/sidebar.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/messages-section.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/section-link.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-messages-section-test.js
- app/assets/stylesheets/common/base/sidebar.scss
- config/locales/client.en.yml
> FEATURE: Add messages section links to experimental sidebar.

- app/views/topics/show.html.erb
Relevant PR in Q&A plugin: https://github.com/discourse/discourse-question-answer/pull/82
> PERF: remove server plugin outlet for post

- lib/js_locale_helper.rb
> FIX: Extra-locale merging didn't account for fallbacks

- db/migrate/20220330160747_copy_site_settings_uploads_to_upload_references.rb
> FIX: Skip invalid values in site setting upload references migration

- app/assets/javascripts/discourse/app/templates/discovery.hbs
- app/assets/javascripts/discourse/app/templates/tag/show.hbs
> DEV: Add `before-list-area` plugin outlet

- app/assets/javascripts/discourse/app/components/sidebar/messages-section.js
- app/assets/javascripts/discourse/app/templates/components/sidebar/messages-section.hbs
Avoid duplicating composer logic in multiple places.
> DEV: Rely on route action to open composer.

- app/assets/javascripts/discourse/app/components/sidebar/messages-section.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/group-message-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/message-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/personal-message-section-link.js
- app/assets/javascripts/discourse/app/models/topic.js
- app/assets/javascripts/discourse/app/templates/components/sidebar/messages-section.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-messages-section-test.js
> FEATURE: Expand messages filter links when viewing private messages.

- app/assets/javascripts/admin/addon/components/admin-report-table-cell.js
- app/assets/javascripts/admin/addon/models/report.js
- app/assets/javascripts/admin/addon/templates/components/admin-report-table-cell.hbs
- app/assets/javascripts/admin/addon/templates/components/admin-report-table.hbs
- app/assets/javascripts/discourse/tests/integration/components/select-kit/host-list-test.js
- app/assets/javascripts/discourse/tests/unit/models/report-test.js
- app/assets/javascripts/select-kit/addon/components/multi-select/format-selected-content.js
- app/assets/javascripts/select-kit/addon/templates/components/multi-select/format-selected-content.hbs
- app/assets/stylesheets/common/select-kit/multi-select.scss
- app/assets/stylesheets/mobile/compose.scss
- plugins/discourse-local-dates/assets/javascripts/discourse/components/discourse-local-dates-create-form.js
- plugins/discourse-local-dates/assets/javascripts/discourse/templates/components/discourse-local-dates-create-form.hbs
- plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js
- plugins/discourse-local-dates/assets/javascripts/lib/local-date-builder.js
- plugins/discourse-local-dates/test/javascripts/lib/local-date-builder-test.js
(nothing in all-the* relies on these)
> DEV: Fix typos "formated" -> "formatted"

- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
- app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js
- app/assets/javascripts/discourse/tests/integration/components/watched-word-uploader-test.js
> DEV: Remove `isLegacyEmber` from tests

- lib/version.rb
> Version bump to v2.8.5

- app/assets/javascripts/discourse-common/addon/config/environment.js
- app/assets/javascripts/yarn.lock
> DEV: add deprecation notice to `isLegacyEmber`

- app/assets/javascripts/discourse-common/addon/lib/debounce.js
- app/assets/javascripts/discourse/app/initializers/inject-objects.js
- app/assets/javascripts/discourse/app/lib/d-popover.js
- app/assets/javascripts/discourse/app/pre-initializers/map-routes.js
- app/assets/javascripts/discourse/app/services/presence.js
- app/assets/javascripts/discourse/tests/setup-tests.js
> DEV: Remove `isLegacyEmber`

- app/assets/javascripts/discourse/app/components/sidebar/messages-section.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/group-message-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/message-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/messages-section/personal-message-section-link.js
- app/assets/javascripts/discourse/app/models/private-message-topic-tracking-state.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-messages-section-test.js
- config/locales/client.en.yml
> FEATURE: New/unread messages count in experimental sidebar

- app/assets/javascripts/discourse/app/helpers/category-badge.js
- app/assets/javascripts/discourse/tests/integration/components/category-badge-test.js
> DEV: allows category-badge helper to display a link

- app/assets/javascripts/discourse/app/app.js
- app/views/common/_discourse_splash.html.erb
> FIX: Reverts #17225 & #17223

- app/assets/javascripts/yarn.lock
Fixes concurrent addon build lockups.
> DEV: Update broccoli-babel-transpiler

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `@glimmer/tracking`

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `js-yaml`

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/wizard/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `ember-cli-terser`

- spec/requests/invites_controller_spec.rb
> FIX: Fix bulk_invite flaky tests

- config/locales/client.en.yml
> UX: Change copy for user-selector placeholder

- app/assets/stylesheets/common/base/d-popover.scss
> UX: update color on arrow tippy box

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `jsdom`

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `qunit-dom`

- config/site_settings.yml
> FIX: max value for SiteSetting.delete_removed_posts_after

- app/assets/javascripts/discourse/app/templates/components/reviewable-queued-post.hbs
- app/assets/javascripts/discourse/app/templates/topic.hbs
- app/assets/javascripts/discourse/tests/integration/components/cook-text-test.js
> DEV: Convert `{{cook-text}}` to angle-brackets

- app/assets/javascripts/discourse/config/deprecation-workflow.js
- app/assets/javascripts/discourse/config/environment.js
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
Right now there are no deprecations so we don't have anything to manage.
> DEV: Set up ember-cli-deprecation-workflow

- app/assets/javascripts/discourse-common/addon/lib/get-url.js
> DEV: De-jQuerify `get-url`

- app/assets/javascripts/discourse/tests/unit/controllers/create-account-test.js
> DEV: Fix a flaky submodule/auth test

- app/assets/javascripts/discourse/tests/acceptance/search-full-test.js
- app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/category-chooser-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/category-drop-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/combo-box-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/dropdown-select-box-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/notifications-button-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/single-select-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/topic-notifications-options-test.js
> DEV: Remove most jQ from select-kit test helpers

- lib/auth/default_current_user_provider.rb
- lib/route_matcher.rb
- spec/components/auth/default_current_user_provider_spec.rb
> Backport fixes to stable branch

- config/site_settings.yml
- spec/requests/application_controller_spec.rb
We now want the splash screen to be enabled by default.
Internal topic /t/65378/83
> UX: Makes splash screen setting enabled by default

- app/assets/stylesheets/common/base/topic-post.scss
Hover effect isn't specific enough
Everything else lights up on hover, except reply
https://user-images.githubusercontent.com/101828855/177172342-25a5b8d7-8bea-49d1-9287-ee6c4e05cf07.mov
> UX: missing specificity

- app/assets/stylesheets/common/select-kit/category-chooser.scss
> UX: remove hardcoded colour value

- app/assets/javascripts/admin/addon/components/ace-editor.js
- app/assets/javascripts/admin/addon/controllers/admin-api-keys.js
- app/assets/javascripts/discourse-common/addon/lib/legacy-resolver.js
- app/assets/javascripts/discourse-common/addon/resolver.js
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse/app/app.js
- app/assets/javascripts/discourse/app/pre-initializers/dynamic-route-builders.js
- app/assets/javascripts/discourse/tests/helpers/create-store.js
- app/assets/javascripts/discourse/tests/unit/ember/resolver-test.js
- app/assets/javascripts/yarn.lock
(Rebase of #17189 on latest main)
> DEV: Modernize Ember Resolver

- app/assets/stylesheets/common/select-kit/select-kit.scss
> UX: switch highlight/select colours in select-kit

- app/assets/javascripts/discourse/app/controllers/application.js
- app/assets/stylesheets/common/base/discourse.scss
- app/assets/stylesheets/common/base/sidebar.scss
- app/assets/stylesheets/desktop/discourse.scss
This removes some of the jankiness from the CSS transitions on desktop. 
Also
* Removed extra animation class
* Moved some reused values into variables 
* Improved mobile toggle alignment
> UX: improve experimental sidebar transitions

- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
- app/assets/javascripts/discourse/tests/acceptance/unknown-test.js
> DEV: Reduce test noise

- .github/workflows/linting.yml
- lib/tasks/docker.rake
The performance improvement is fairly small, but I don't see any downside to this. If GitHub actions running performance/cores improve in future, this will mean we immediately see the benefit.
> DEV: Run prettier and rubocop in parallel for CI

- app/assets/javascripts/discourse/tests/helpers/component-test.js
- app/assets/javascripts/discourse/tests/integration/components/bookmark-icon-test.js
- app/assets/javascripts/discourse/tests/integration/components/d-navigation-test.js
- app/assets/javascripts/discourse/tests/integration/components/site-header-test.js
> DEV: Allow hooks.beforeEach usage w/ component tests

- app/assets/javascripts/discourse/lib/discourse-scss.js
> DEV: Make sass deprecations quieter during test build

- app/assets/javascripts/discourse/app/routes/tag-show.js
> DEV: Don't use the deprecated route

- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
- app/assets/javascripts/discourse/tests/acceptance/unknown-test.js
- app/assets/javascripts/discourse/tests/unit/services/presence-test.js
…and improve silencing added in #17362
> DEV: Silence one more test

- app/assets/javascripts/admin/addon/components/secret-value-list.js
- app/assets/javascripts/admin/addon/components/simple-list.js
- app/assets/javascripts/admin/addon/components/value-list.js
- app/assets/javascripts/admin/addon/templates/components/secret-value-list.hbs
- app/assets/javascripts/admin/addon/templates/components/simple-list.hbs
- app/assets/javascripts/admin/addon/templates/components/value-list.hbs
- app/assets/javascripts/discourse/tests/integration/components/secret-value-list-test.js
- app/assets/javascripts/discourse/tests/integration/components/simple-list-test.js
- app/assets/javascripts/discourse/tests/integration/components/value-list-test.js
> FIX: Inputs using focusout regressed in #17345

- app/assets/javascripts/discourse/app/components/discourse-root.js
As a result discourse-root will be tag-less
> DEV: glimmerify discourse-root

- app/assets/javascripts/discourse/app/components/discourse-root.js
This reverts commit 27408c7e14b11ca234ec57e59fa1f575295fb79f.
> Revert "DEV: glimmerify discourse-root (#17390)"

- spec/lib/theme_javascript_compiler_spec.rb
Previously the spec was hardcoded to expect a certain compiled result. The precise result will change as we update to more recent Ember versions.
Instead, we can compile via the special theme compiler, and then compile our expected result via the normal compiler. If they match, then things are working as intended. This technique should be safe across template-compiler upgrades.
> DEV: Future-proof ThemeJavascriptCompiler spec

- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `qunit`

- app/assets/javascripts/discourse/tests/unit/services/screen-track-test.js
Fixes failures like:
```
Unhandled request in test environment: /forum/topics/timings (POST)
```
> DEV: Fix test leakage/flakes

- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
- app/assets/javascripts/discourse/tests/acceptance/lightbox-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/assets/javascripts/discourse/tests/unit/lib/text-direction-test.js
- plugins/discourse-presence/test/javascripts/acceptance/discourse-presence-test.js
> DEV: Avoid triggering 404 errors in tests

- app/assets/stylesheets/test_helper.scss
- app/assets/stylesheets/vendor/qunit.css
This reverts commit cf85ccca7d6a3db09a3ae11874489816717d3dfb.
> Revert "DEV: Don't vendor old qunit css (#17410)"

- app/models/user.rb
- app/models/user_profile.rb
- spec/models/user_profile_spec.rb
- spec/models/user_spec.rb
Currently we only apply watched words of the `Block` type to custom user fields and user profile fields.
This patch enables all rules to be applied such as `Censor` or `Replace`.
> FIX: Apply all watched words rules to user fields

- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
This fixes i18n related tests in dev env
> DEV: Don't forward `test-i18n.js` requests

- spec/requests/invites_controller_spec.rb
> FIX: update flaky bulk invite spec

- app/assets/javascripts/discourse/app/components/sidebar/section.js
- app/assets/stylesheets/common/base/sidebar.scss
This fixes some toggle icon shift on mobile and improves alignment at some breakpoints.
I also brought back the caret hover and added some transitions.
> UX: Fix exp sidebar toggle alignment, add hovers

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/wizard/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `ember-cli-handlebars`

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/wizard/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `ember-resolver`

- app/assets/javascripts/discourse/app/initializers/mobile.js
- app/assets/javascripts/discourse/tests/helpers/component-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
> FIX: Set resolver options on the legacy resolver

- app/assets/javascripts/discourse/tests/setup-tests.js
> DEV: Simplify test setup

- app/assets/javascripts/discourse/tests/test-helpers-rails.js
> DEV: Remove an unused js helpers file

- app/assets/javascripts/discourse/tests/integration/components/select-kit/email-group-user-chooser-test.js
> DEV: prevents prop override and simplifies test

- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
> DEV: Remove old pretender paths

- Gemfile
- Gemfile.lock
- config/application.rb
https://discuss.rubyonrails.org/t/81017
> SECURITY: Bump Rails to 7.0.3.1

- Gemfile
- Gemfile.lock
- config/application.rb
> SECURITY: Bump Rails to 6.1.6.1 (stable)

- app/assets/javascripts/discourse/app/components/composer-body.js
- app/assets/javascripts/discourse/app/lib/safari-hacks.js
> DEV: De-jQuerify safari-hacks

- lib/version.rb
> Version bump to v2.9.0.beta7

- lib/version.rb
> Version bump to v2.8.6

- app/assets/stylesheets/desktop/topic-post.scss
reported here: https://meta.discourse.org/t/sticky-avatars-not-too-sticky/232359
> FIX: adjust topic avatar height to fix stickiness

- app/assets/javascripts/discourse/app/components/emoji-picker.js
- app/assets/javascripts/discourse/app/components/software-update-prompt.js
- app/assets/javascripts/discourse/app/controllers/about.js
- app/assets/javascripts/discourse/app/controllers/preferences/sidebar.js
- app/assets/javascripts/discourse/app/controllers/second-factor-auth.js
- app/assets/javascripts/discourse/app/lib/lock-on.js
- app/assets/javascripts/discourse/app/lib/media-optimization-utils.js
- app/assets/javascripts/discourse/app/lib/text.js
- app/assets/javascripts/discourse/app/lib/url.js
- app/assets/javascripts/discourse/app/lib/utilities.js
- app/assets/javascripts/discourse/app/mixins/mobile-scroll-direction.js
- app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
- app/assets/javascripts/discourse/app/mixins/uppy-upload.js
- app/assets/javascripts/discourse/app/models/post-stream.js
- app/assets/javascripts/discourse/app/models/private-message-topic-tracking-state.js
- app/assets/javascripts/discourse/app/routes/preferences-sidebar.js
- app/assets/javascripts/discourse/app/templates/about.hbs
- app/assets/javascripts/discourse/app/templates/components/emoji-picker.hbs
- app/assets/javascripts/discourse/app/templates/preferences/sidebar.hbs
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-mobile-test.js
- app/assets/stylesheets/vendor/normalize-ext.scss
- spec/requests/users_controller_spec.rb
> DEV: Fix various typos

- app/assets/javascripts/discourse/app/components/d-modal-body.js
- app/assets/javascripts/discourse/app/components/featured-topic.js
- app/assets/javascripts/discourse/app/components/topic-list.js
- app/assets/javascripts/discourse/app/mixins/card-contents-base.js
- app/assets/javascripts/discourse/app/widgets/home-logo.js
- app/assets/javascripts/discourse/app/widgets/link.js
- app/assets/javascripts/discourse/app/widgets/topic-admin-menu.js
- plugins/poll/assets/javascripts/widgets/discourse-poll.js
> DEV: Use native `element.closest()`

- app/assets/javascripts/admin/addon/components/screened-ip-address-form.js
- app/assets/javascripts/admin/addon/components/watched-word-form.js
- app/assets/javascripts/admin/addon/templates/components/screened-ip-address-form.hbs
- app/assets/javascripts/admin/addon/templates/components/watched-word-form.hbs
> DEV: Fix submit-on-enter and de-jQ two components

- app/models/user.rb
- app/serializers/current_user_serializer.rb
This feature flag is temporary so we're omitting tests here. 
Extracted from https://github.com/discourse/discourse/pull/17379
> DEV: Add per-user feature flag for the new notifications menu

- app/assets/javascripts/discourse/app/controllers/account-created-index.js
- app/assets/javascripts/discourse/app/templates/account-created/index.hbs
- app/assets/javascripts/discourse/tests/acceptance/account-created-test.js
- app/assets/stylesheets/common/base/activation.scss
- app/assets/stylesheets/common/base/login.scss
UX: minor styling updates to accept invite pages
Before:
After:
> UX: better account-created page

- app/models/user.rb
- spec/models/user_spec.rb
Fix user creation when there are `multiselect` type user fields present.
> FIX: bug with multiselect user field validation

- config/application.rb
- spec/models/post_revision_spec.rb
Followup to bb287c6c74aed9c9ccd36f6270c219f806bb84f3
> FIX: Allow Time objects to be deserialized in PostRevision (stable)

- app/assets/javascripts/discourse/tests/acceptance/topic-list-tracker-test.js
Follow-up to 0525455ef69f4482b0f7b1610c5ccade40f88dd7
> DEV: Fix state leak in QUnit acceptance tests

- app/assets/javascripts/admin/addon/templates/users-list.hbs
> UX: remove .btn-default from admin btn

- app/assets/stylesheets/mobile/_index.scss
- app/assets/stylesheets/mobile/sidebar.scss
Just some minor font-size and padding bumps
> UX: increase text size for mobile exp sidebar

- app/assets/javascripts/discourse/app/helpers/concat-class.js
- app/assets/javascripts/discourse/tests/integration/helpers/concat-class-test.js
Usage:
```
<button class={{concat-class "foo" this.bar (if true "baz")}} />
```
> DEV: introduces {{concat-class}} helper

- app/assets/javascripts/discourse/tests/setup-tests.js
🤞 maybe this will cover the remaining out-of-viewport flakes
> DEV: Also reset horizontal scroll after each test

- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
Forgot to save this file when doing #17474 😅
> DEV: One more de-jQueryfied test

- app/assets/javascripts/discourse/tests/acceptance/preferences-test.js
> DEV: Don't await for updateCurrentUser

- app/assets/javascripts/discourse/tests/acceptance/admin-site-settings-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-editor-mentions-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-hyperlink-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-image-preview-test.js
- app/assets/javascripts/discourse/tests/acceptance/create-account-user-fields-test.js
- app/assets/javascripts/discourse/tests/acceptance/do-not-disturb-test.js
- app/assets/javascripts/discourse/tests/acceptance/emoji-test.js
- app/assets/javascripts/discourse/tests/acceptance/fast-edit-test.js
- app/assets/javascripts/discourse/tests/acceptance/keyboard-shortcuts-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal-test.js
- app/assets/javascripts/discourse/tests/acceptance/search-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-entrance-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-quote-button-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/assets/javascripts/discourse/tests/acceptance/users-test.js
- app/assets/javascripts/discourse/tests/integration/components/d-button-test.js
- app/assets/javascripts/discourse/tests/integration/components/d-popover-test.js
- app/assets/javascripts/discourse/tests/integration/components/flat-button-test.js
- app/assets/javascripts/discourse/tests/integration/components/simple-list-test.js
> DEV: Use key names in triggerKeyEvent

- app/assets/javascripts/discourse/tests/acceptance/plugin-keyboard-shortcut-test.js
> DEV: Remove unnecessary `visit()` calls

- app/assets/javascripts/discourse-common/addon/lib/legacy-resolver.js
- app/assets/javascripts/discourse-common/addon/lib/raw-handlebars-helpers.js
- app/assets/javascripts/discourse/app/components/d-editor.js
- app/assets/javascripts/discourse/app/components/share-panel.js
- app/assets/javascripts/discourse/app/controllers/grant-badge.js
- app/assets/javascripts/discourse/app/lib/cookie.js
- app/assets/javascripts/discourse/app/lib/discourse-location.js
- app/assets/javascripts/discourse/app/lib/intercept-click.js
- app/assets/javascripts/discourse/app/lib/url.js
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/app/models/nav-item.js
- app/assets/javascripts/pretty-text/addon/emoji.js
- app/assets/javascripts/pretty-text/addon/sanitizer.js
- app/assets/javascripts/pretty-text/engines/discourse-markdown/quotes.js
- lib/javascripts/widget-hbs-compiler.js
- public/javascripts/embed.js
> DEV: Extensively use `startsWith()`

- app/assets/javascripts/discourse/tests/unit/services/emoji-store-test.js
> DEV: Move emoji-store test to the correct dir

- app/assets/javascripts/discourse/app/services/screen-track.js
> DEV: Run screen-track `run` in a runloop, drop jQ

- app/assets/javascripts/discourse/app/components/sidebar/section.js
- app/assets/javascripts/discourse/app/templates/components/sidebar.hbs
Custom sections `willDestroy` function has to be passed to SidebarSection component  to call when component is removed.
> FIX: pass custom section willDestroy

- app/assets/stylesheets/common/base/sidebar.scss
Follow-up to 0d72a8c458216698f55aaee54b8ffbe4d7750ce9
> FIX: Restrict sidebar specific select kit CSS to sidebar

- app/assets/javascripts/discourse/app/templates/components/sidebar/messages-section.hbs
This icon is missing currently
> UX: plus icon for sidebar messages section header

- app/assets/javascripts/admin/addon/mixins/setting-object.js
- app/assets/javascripts/select-kit/addon/components/categories-admin-dropdown.js
- app/assets/javascripts/select-kit/addon/components/category-row.js
- app/assets/javascripts/select-kit/addon/components/category-selector.js
- app/assets/javascripts/select-kit/addon/components/user-notifications-dropdown.js
> DEV: Fix typos and other spell-checker warnings

- app/assets/javascripts/admin/addon/mixins/setting-object.js
- app/assets/javascripts/discourse-common/addon/lib/icon-library.js
- app/assets/javascripts/discourse/app/components/color-picker-choice.js
- app/assets/javascripts/discourse/app/lib/uploads.js
- app/assets/javascripts/discourse/app/models/topic-list.js
- app/assets/javascripts/discourse/app/models/topic.js
- app/assets/javascripts/discourse/app/models/user-action.js
- app/assets/javascripts/discourse/app/routes/discovery-categories.js
- app/assets/javascripts/discourse/app/widgets/post-cooked.js
- app/assets/javascripts/select-kit/addon/components/mini-tag-chooser/selected-collection.js
> DEV: Use `includes()` instead of `indexOf() >= 0`

- app/assets/javascripts/discourse/app/components/site-header.js
- app/assets/javascripts/discourse/app/components/user-menu-wrapper.js
- app/assets/javascripts/discourse/app/components/user-menu/items-list-empty-state.hbs
- app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs
- app/assets/javascripts/discourse/app/components/user-menu/items-list.js
- app/assets/javascripts/discourse/app/components/user-menu/menu.hbs
- app/assets/javascripts/discourse/app/components/user-menu/menu.js
- app/assets/javascripts/discourse/app/components/user-menu/notification-item.hbs
- app/assets/javascripts/discourse/app/components/user-menu/notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/notifications-list-empty-state.hbs
- app/assets/javascripts/discourse/app/components/user-menu/notifications-list-empty-state.js
- app/assets/javascripts/discourse/app/components/user-menu/notifications-list.js
- app/assets/javascripts/discourse/app/initializers/subscribe-user-notifications.js
- app/assets/javascripts/discourse/app/models/notification.js
- app/assets/javascripts/discourse/app/templates/components/user-menu-wrapper.hbs
- app/assets/javascripts/discourse/app/widgets/component-connector.js
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/tests/integration/components/site-header-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/menu-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/notification-item-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/notifications-list-test.js
- app/assets/stylesheets/common/base/menu-panel.scss
- app/assets/stylesheets/desktop/menu-panel.scss
- app/assets/stylesheets/mobile/menu-panel.scss
- config/locales/client.en.yml
- lib/svg_sprite.rb
Extracted from https://github.com/discourse/discourse/pull/17379.
> DEV: Introduce a basic version of the new notifications menu behind a feature flag

- app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs
- app/assets/javascripts/discourse/app/components/user-menu/menu.hbs
> FIX: Correctly invoke dynamic components by name

- plugins/poll/test/javascripts/widgets/discourse-poll-test.js
> DEV: Fix pretender in poll tests

- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
> DEV: Fix pretender leaking request handlers

- app/assets/javascripts/discourse/app/lib/key-value-store.js
- app/assets/javascripts/discourse/tests/unit/lib/key-value-store-test.js
> DEV: Use a separate KVS namespace for tests

- app/models/badge.rb
- app/models/user_badge.rb
- app/services/badge_granter.rb
- spec/models/badge_spec.rb
- spec/models/user_badge_spec.rb
- spec/services/badge_granter_spec.rb
- spec/support/discourse_event_helper.rb
Follow-up to 02ce9b8a621ef917044e138ac4289ea3e228cc1e
> DEV: Refactor user_badge_granted DiscourseEvent logic

- app/assets/javascripts/discourse/app/components/user-menu/bookmark-reminder-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/custom-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/granted-badge-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/group-mentioned-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/group-message-summary-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/invitee-accepted-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/liked-consolidated-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/liked-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/membership-request-accepted-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/membership-request-consolidated-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/moved-post-notification-item.js
- app/assets/javascripts/discourse/app/components/user-menu/watching-first-post-notification-item.js
- app/assets/javascripts/discourse/app/models/notification.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/bookmark-reminder-notification-item-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/granted-badge-notification-item-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/group-mentioned-notification-item-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/group-message-summary-notification-item-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/liked-consolidated-notification-item-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/liked-notification-item-test.js
- config/locales/client.en.yml
Extracted from https://github.com/discourse/discourse/pull/17379.
> DEV: Add implementations for various notification types for the new menu

- app/assets/stylesheets/common/base/sidebar-section.scss
- app/assets/stylesheets/common/base/sidebar.scss
- app/assets/stylesheets/desktop/sidebar-section.scss
> UX: Only hide section header icons when sidebar is pinned on Desktop

- app/assets/stylesheets/common/base/menu-panel.scss
> UX: Set width on hamburger menu drop down to prevent overflow

- app/assets/stylesheets/common/base/sidebar-section-link.scss
> UX: Properly size emoji in sidebar section link text

- app/assets/javascripts/discourse/app/components/sidebar/community-section.js
- app/assets/javascripts/discourse/app/lib/sidebar/community-section/groups-section-link.js
- app/assets/javascripts/discourse/app/lib/sidebar/community-section/users-section-link.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-community-section-test.js
- config/locales/client.en.yml
> FEATURE: Add users and groups links to community section in sidebar

- app/assets/stylesheets/common/base/onebox.scss
> UX: Prevent jitter in some onebox images

- config/locales/client.en.yml
Before:
After
Internal topic
/t/-/70417
> UX: Updates sign up CTA copy

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/wizard/package.json
- app/assets/javascripts/yarn.lock
> DEV: Update `@embroider/test-setup`

- app/assets/javascripts/discourse/tests/acceptance/notifications-test.js
- app/assets/javascripts/discourse/tests/acceptance/review-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-categories-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-community-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-messages-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-tags-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-discovery-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-discovery-tracked-test.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-status-test.js
- app/assets/javascripts/discourse/tests/helpers/presence-pretender.js
- app/assets/javascripts/discourse/tests/integration/components/software-update-prompt-test.js
- app/assets/javascripts/discourse/tests/unit/models/private-message-topic-tracking-state-test.js
- app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js
- app/assets/javascripts/discourse/tests/unit/services/presence-test.js
- plugins/poll/test/javascripts/acceptance/poll-results-test.js
- spec/lib/pretty_text_spec.rb
> DEV: Always `await` for `publishToMessageBus`

- app/assets/javascripts/discourse/tests/acceptance/dismiss-notification-modal-test.js
- app/assets/javascripts/discourse/tests/acceptance/second-factor-auth-test.js
- app/assets/javascripts/discourse/tests/integration/components/admin-report-test.js
- app/assets/javascripts/discourse/tests/integration/components/avatar-uploader-test.js
- app/assets/javascripts/discourse/tests/integration/components/badge-title-test.js
- app/assets/javascripts/discourse/tests/integration/components/cook-text-test.js
- app/assets/javascripts/discourse/tests/integration/components/invite-panel-test.js
- app/assets/javascripts/discourse/tests/integration/components/site-header-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/notifications-list-test.js
- app/assets/javascripts/discourse/tests/unit/controllers/topic-test.js
- app/assets/javascripts/discourse/tests/unit/lib/link-mentions-test.js
- app/assets/javascripts/discourse/tests/unit/models/post-stream-test.js
- app/assets/javascripts/discourse/tests/unit/models/private-message-topic-tracking-state-test.js
- plugins/poll/test/javascripts/widgets/discourse-poll-test.js
> DEV: Consistently use `response` helper

- app/assets/javascripts/discourse/tests/acceptance/notifications-test.js
> DEV: Remove yet another jQ use in tests

- spec/lib/final_destination_spec.rb
> DEV: Fix `FinalDestination` specs

- script/import_scripts/mybb.rb
Wrote this for a client that ended up not having budget :-(
I've not seen any tests for import scripts!
> FEATURE: my_bb supports avatars

- lib/discourse_dev/user.rb
discourse-chat's auto-join users rely on these values, so it's handy for the populate task to set them.
> DEV: Populate first and last seen at timestamps.

- app/assets/stylesheets/common/base/header.scss
at the moment it transitions on some route changes and page refresh
> UX: only transition header on sidebar toggle

- spec/lib/final_destination_spec.rb
> DEV: Fix a flaky FinalDestination spec

- spec/lib/final_destination_spec.rb
> DEV: Fix flaky `FinalDestination` specs

- app/assets/javascripts/discourse/app/templates/composer.hbs
> UX: copy change

- lib/version.rb
> Version bump to v2.8.7

- app/assets/javascripts/discourse/app/components/sidebar/community-section.js
- app/assets/javascripts/discourse/app/components/sidebar/more-section-links.js
- app/assets/javascripts/discourse/app/templates/components/sidebar/community-section.hbs
- app/assets/javascripts/discourse/app/templates/components/sidebar/more-section-links.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-community-section-test.js
- app/assets/stylesheets/common/base/_index.scss
- app/assets/stylesheets/common/base/sidebar-more-section-links.scss
- app/assets/stylesheets/common/base/sidebar-section-link.scss
- config/locales/client.en.yml
Additional links are hidden by default and can be accessed via the
"more..." link.
> UX: Reduce number of links displayed in Community by default

- .github/workflows/licenses.yml
Workaround for https://github.com/github/licensed/issues/521
> DEV: Workaround for licensed gem incompatibility with latest Bundler

- app/assets/stylesheets/common/base/sidebar-more-section-links.scss
- app/assets/stylesheets/desktop/sidebar-section.scss
- app/assets/stylesheets/mobile/sidebar.scss
This shows some hidden buttons that were hidden on touch devices (due to hover), and improves some focus styles.
> UX: sidebar focus styles, remove hover for touch

- app/assets/javascripts/discourse/app/models/topic-tracking-state.js
- app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js
* Use `Set` instead of `Array` for `this.newIncoming`
* Remove `isUnseen()`
* Use array spread instead of `Array.from()`
* Don't use `@on()`
* Fix typos
* Make sure `this.incomingCount` is always a Number
> DEV: Minor topic-tracking-state refactor

- app/assets/javascripts/discourse/app/controllers/discovery-sortable.js
- lib/topic_query.rb
> FIX: Ensure all public topic-query options can be used via Ember

- app/assets/javascripts/discourse/app/controllers/user-activity-bookmarks.js
- app/assets/javascripts/discourse/app/routes/user-activity-bookmarks.js
Follow-up to 6bb77d30553a346c22bc9efb52a977ce7ae0c33a
> UX: Only set user bookmarks loading state when loading

- app/assets/javascripts/discourse/app/controllers/invites-show.js
- app/assets/javascripts/discourse/app/templates/invites/show.hbs
- app/assets/stylesheets/common/base/login.scss
We include this when an anonymous user signs up, so it should also be here!
> UX: Add the TOS disclaimer to the invite signup

- app/assets/stylesheets/common/base/activation.scss
- app/views/users/activate_account.html.erb
- app/views/users/perform_account_activation.html.erb
> UX: updated account activation page design

- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/stylesheets/common/base/sidebar.scss
Ability to scroll to specific section in sidebar. Sometimes a sidebar might be too short, and we have to add height to the last element.
NOTE: code related to screen resolutions and scroll is a bit difficult to test
Related PR: https://github.com/discourse/discourse-chat/pull/1101
Demo:
https://user-images.githubusercontent.com/72780/181670236-a8109bbf-e158-4243-8296-4654cbfed079.mov
> DEV: Ability to scroll sidebar to specific element

- app/assets/javascripts/discourse/app/initializers/clean-dom-on-route-change.js
> DEV: dom clean should be cancelled on aborted transition

- app/assets/javascripts/discourse/app/templates/components/sidebar/more-section-links.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-community-section-test.js
- config/locales/client.en.yml
> UX: Remove count from more section links

- app/assets/javascripts/discourse/tests/acceptance/wizard-test.js
- app/assets/javascripts/wizard/addon/components/wizard-step.js
- app/assets/javascripts/wizard/addon/controllers/wizard-step.js
- app/assets/javascripts/wizard/addon/test-helpers/wizard-pretender.js
Follow up to cfd0a04965fc058012b02d40da05384f61f951a7
> DEV: add test for wizard last step and some minor optimizations

- lib/plugin/metadata.rb
https://meta.discourse.org/t/discourse-chat-plugin/230881/11
> DEV: Add discourse-chat to official plugins

- app/assets/javascripts/discourse/app/components/user-menu/likes-notifications-list.js
- app/assets/javascripts/discourse/app/components/user-menu/mentions-notifications-list.js
- app/assets/javascripts/discourse/app/components/user-menu/notifications-list.js
- app/assets/javascripts/discourse/app/components/user-menu/replies-notifications-list.js
- app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
- app/assets/javascripts/discourse/tests/fixtures/notification-fixtures.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/notifications-list-test.js
- app/controllers/notifications_controller.rb
- app/models/notification.rb
- spec/requests/notifications_controller_spec.rb
Extracted from https://github.com/discourse/discourse/pull/17379.
Depends on https://github.com/discourse/discourse/pull/17718.
> DEV: Wire up the dimiss button in the new notifications menu

- spec/lib/second_factor/auth_manager_spec.rb
- spec/models/site_spec.rb
- spec/models/user_spec.rb
- spec/services/post_bookmarkable_spec.rb
- spec/services/topic_bookmarkable_spec.rb
> DEV: Guardians aren't active record objects, so shouldn't use fab!

- app/assets/stylesheets/common/base/sidebar-section-link.scss
> UX: fix channel lock icon position and background

- app/assets/stylesheets/wizard.scss
- app/views/finish_installation/register.html.erb
This page was missed in the wizard redesign, updating styles to match.
Before: 
After:
> UX: update register admin wizard page styles

- app/assets/javascripts/admin/jsconfig.json
- app/assets/javascripts/discourse-widget-hbs/jsconfig.json
- app/assets/javascripts/discourse/jsconfig.json
- app/assets/javascripts/pretty-text/jsconfig.json
- app/assets/javascripts/select-kit/jsconfig.json
- app/assets/javascripts/wizard/jsconfig.json
- jsconfig.base.json
This allows VSCode to find references.
> DEV: Add jsconfig

- app/assets/javascripts/discourse/app/routes/build-topic-route.js
> DEV: Asyncify `findTopicList()`

- app/assets/javascripts/discourse/app/lib/notification-item.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
> DEV: Fix a function name typo

- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
> DEV: Clear extra header buttons

- app/models/theme.rb
- config/initializers/assets.rb
This will trigger recompilation of theme/plugin assets following 7f9c2c0b
> DEV: Bump asset compiler versions

- app/assets/javascripts/discourse/app/components/welcome-topic-banner.js
- app/assets/javascripts/discourse/app/controllers/discovery/topics.js
- app/assets/javascripts/discourse/app/templates/components/welcome-topic-banner.hbs
- app/assets/javascripts/discourse/app/templates/discovery/topics.hbs
- app/assets/javascripts/discourse/tests/acceptance/welcome-topic-banner-test.js
- app/assets/stylesheets/desktop/topic-list.scss
- app/models/site.rb
- app/models/user.rb
- app/serializers/site_serializer.rb
- config/locales/client.en.yml
- config/site_settings.yml
- lib/wizard.rb
- spec/models/site_spec.rb
- spec/requests/api/schemas/json/site_response.json
- spec/serializers/site_serializer_spec.rb
> FEATURE: add welcome topic cta banner

- app/assets/javascripts/discourse/app/components/bootstrap_mode_notice.js
- app/assets/javascripts/discourse/app/components/global-notice.js
- app/assets/javascripts/discourse/app/controllers/application.js
- app/assets/javascripts/discourse/app/templates/application.hbs
- app/assets/javascripts/discourse/app/templates/components/bootstrap-mode-notice.hbs
- app/assets/javascripts/discourse/tests/acceptance/bootstrap-mode-notice-test.js
- app/assets/stylesheets/desktop/_index.scss
- app/assets/stylesheets/desktop/alert.scss
- app/assets/stylesheets/mobile/alert.scss
- config/locales/client.en.yml
- spec/models/translation_override_spec.rb
> FEATURE: update bootstrap mode notice to add invite and wizard links

- app/assets/javascripts/discourse/app/components/user-menu/menu.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/lib/user-menu/tab.js
- app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
Port from https://github.com/discourse/discourse/pull/17815
> DEV: Add `registerUserMenuTab` plugin API

- app/models/invite.rb
- spec/models/invite_spec.rb
> SECURITY: Limit email invitations to topic

- lib/version.rb
> Version bump to v2.9.0.beta9

- lib/version.rb
> Version bump to 2.8.8

- app/assets/stylesheets/common/base/menu-panel.scss
Very minor, but feels a lot better
> minor padding update for revamped user-menu

- app/models/theme.rb
Compiled themes often include upload URLs which will need to be re-calculated
> DEV: Invalidate theme cache when S3 configuration changes

- app/assets/javascripts/discourse/app/controllers/preferences/interface.js
- app/assets/javascripts/discourse/tests/acceptance/user-preferences-interface-test.js
> FIX: don't preview color scheme if it's not current user's profile.

- lib/distributed_mutex.rb
Polling every 0.001s can cause extreme load on the redis instance, especially in scenarios where multiple app instances are waiting on the same lock. This commit introduces an exponential backoff starting from 0.001s and reaching a maximum interval of 1s.
> PERF: Add exponential backoff for DistributedMutex

- app/assets/javascripts/discourse/app/lib/key-value-store.js
…to something more easily recognizable and less collision-prone
> DEV: Change test localStorage prefix

- app/assets/javascripts/discourse/app/components/time-shortcut-picker.js
> DEV: Prefer kvs over raw localStorage

- app/assets/javascripts/wizard/addon/components/wizard-field.js
- app/assets/javascripts/wizard/addon/templates/components/wizard-field-checkbox.hbs
- app/serializers/wizard_field_serializer.rb
- lib/wizard/field.rb
- spec/lib/wizard/wizard_step_spec.rb
This commit allows a wizard field to be disabled.
> FEATURE: allow wizard checkbox field to be disabled

- app/assets/stylesheets/common/base/sidebar-section-link.scss
> UX: Reduce font-size of sidebar section link suffix icon

- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/stylesheets/common/base/sidebar.scss
Reverts discourse/discourse#17727
> Revert "DEV: Ability to scroll sidebar to specific element"

- app/assets/javascripts/discourse/lib/bootstrap-json/index.js
> DEV: Allow safe_mode and preview_theme_id to work via ember-cli proxy

- app/assets/stylesheets/vendor/pikaday.scss
- plugins/discourse-local-dates/assets/stylesheets/common/discourse-local-dates.scss
Affects date dropdowns, prev/next month arrows and day grid.
> A11Y: Add clearer focus states for date picker elements

- app/assets/javascripts/discourse/tests/acceptance/tags-test.js
> DEV: Remove commented-out code

- app/assets/javascripts/discourse/tests/acceptance/admin-watched-words-test.js
Fixes flaky tests. Also, a typo.
cc: @Flink, @s3lase
> DEV: Await for async helpers

- app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-test.js
Also removes _clearSnapshots calls, as those are already being reset in testCleanup
> DEV: Use afterEach instead of try/finally

- app/assets/javascripts/discourse/app/templates/components/composer-toggles.hbs
- app/assets/stylesheets/common/base/compose.scss
> A11Y: Accessible full-screen and minimize composer buttons

- app/assets/javascripts/discourse/app/models/user.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-categories-section-test.js
> UX: Sort categories alphabetically in Sidebar

- app/assets/javascripts/discourse/app/models/user.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-tags-section-test.js
> UX: Sort tags alphabetically in sidebar

- app/assets/javascripts/discourse/app/components/bootstrap_mode_notice.js
- app/assets/javascripts/discourse/app/templates/components/bootstrap-mode-notice.hbs
- app/assets/javascripts/discourse/tests/acceptance/bootstrap-mode-notice-test.js
https://user-images.githubusercontent.com/5732281/185048711-2b232215-f92e-4359-b639-c65375108cd8.mov
> FEATURE: open create invite modal from the bootstrap notice banner

- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/javascripts/discourse/app/components/sidebar/anonymous-sections.hbs
- app/assets/javascripts/discourse/app/components/sidebar/anonymous-sections.js
- app/assets/javascripts/discourse/app/components/sidebar/footer.js
- app/assets/javascripts/discourse/app/controllers/application.js
- app/assets/javascripts/discourse/app/templates/components/sidebar.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-user-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-test.js
Setup the stage for the sidebar which will be shown to anonymous users.
> DEV: Display Sidebar template for anonymous user

- app/assets/javascripts/discourse/tests/integration/components/site-header-test.js
Extracted from https://github.com/discourse/discourse/pull/17379.
> DEV: Add test for arrow keys navigation in the experimental user menu

- .eslintrc
- app/assets/javascripts/discourse/app/services/presence.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/unit/services/presence-test.js
Should take care of yet another category of flaky tests
> DEV: Await for all async MessageBus callbacks

- lib/backup_restore/backuper.rb
This also adds an optional `ticket` parameter to `Backuper` which allows identifying the backup in `backup_complete` and `backup_failed` events. Both events contain the logs as payload and moving some methods around ensures that all errors are included in the logs.
> FEATURE: Trigger `backup_failed` event on backup failure

- app/assets/javascripts/discourse/app/components/composer-body.js
- app/assets/javascripts/discourse/app/controllers/composer.js
Context: [t72195](https://dev.discourse.org/t/-/72195)
> FIX: set --composer-height when the composer is in collapsed state

- app/controllers/categories_controller.rb
- app/models/category_list.rb
- spec/requests/categories_controller_spec.rb
> DEV: Filter topics by tag for categories

- app/assets/javascripts/discourse/app/controllers/composer.js
> DEV: Clean up `loadDraft()`

- jsconfig.base.json
> DEV: Add more excludes to jsconfig

- app/assets/javascripts/discourse/app/controllers/composer.js
- app/assets/javascripts/discourse/app/controllers/discard-draft.js
…and fix cases where we were breaking the promise/async chain (by not awaiting or not returning promises)
> DEV: Asyncify most of Composer controller

- config/locales/client.en.yml
> UX: fix typo in a blank page copy

- app/assets/javascripts/discourse/app/components/sidebar/section-header.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js
- app/assets/stylesheets/common/base/sidebar-section.scss
Buttons can be focused and action triggered via the enter key compared
to a span.
> DEV: Use button for sidebar section header

- lib/tasks/revisions.rake
See https://meta.discourse.org/t/232885 for context. This rake task enumerates problematic records and prints out a sample of each failure.
> DEV: Introduce debugging rake task for PostRevision issues

- app/assets/javascripts/discourse/app/templates/composer.hbs
> DEV: Add after-title-and-category plugin outlet

- app/assets/javascripts/discourse/app/templates/components/bread-crumbs.hbs
> DEV: Add values to bread-crumbs-right plugin outlet

- spec/lib/oneboxer_spec.rb
Added in #17519. Was causing spec failures.
> DEV: Fix busted twitter onebox spec

- app/assets/stylesheets/common/base/modal.scss
And make the buttons actually full width, and use css vars.
> UX: Correctly center the reply-where modal

- app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-test.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/menu-item-test.js
- app/assets/javascripts/discourse/tests/unit/controllers/topic-test.js
- app/assets/javascripts/discourse/tests/unit/lib/preload-store-test.js
- app/assets/javascripts/discourse/tests/unit/lib/uppy-media-optimization-plugin-test.js
- app/assets/javascripts/discourse/tests/unit/models/post-stream-test.js
> DEV: Use async and sinon.resolves instead of rsvp

- app/assets/stylesheets/common/base/rtl.scss
- app/assets/stylesheets/common/foundation/mixins.scss
It's been a while since IE8 days
> DEV: Remove `progid:DXImageTransform`

- app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
> DEV: Rework two composer actions tests

- app/assets/javascripts/discourse/tests/acceptance/composer-test.js
- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
> DEV: Simplify "Editing a post stages new content" test

- app/assets/javascripts/discourse/app/lib/key-value-store.js
- app/assets/javascripts/discourse/tests/unit/lib/key-value-store-test.js
Usage:
```
this.keyValueStore.removeKeys((key, value) => key === ...);
```
> DEV: implements `removeKeys(predicate)` in keyValueStore

- lib/oneboxer.rb
- lib/twitter_api.rb
> DEV: Clean up twitter onebox code

- app/assets/javascripts/discourse-common/addon/utils/handle-descriptor.js
- app/assets/javascripts/discourse/tests/unit/utils/decorators-test.js
> FIX: Track native class deps in discourseComputed

- app/assets/javascripts/discourse/app/components/topic-title.js
- app/assets/javascripts/discourse/app/lib/sidebar/custom-community-section-links.js
- app/assets/javascripts/discourse/app/lib/sidebar/custom-sections.js
- app/assets/javascripts/discourse/app/lib/user-menu/tab.js
- app/assets/javascripts/discourse/app/lib/user-presence.js
- app/assets/javascripts/discourse/app/widgets/post-menu.js
> DEV: Correctly clear global exported variables

- app/assets/javascripts/discourse/app/controllers/application.js
- app/assets/javascripts/discourse/app/templates/application.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-test.js
- app/assets/javascripts/discourse/tests/acceptance/wizard-test.js
- app/assets/stylesheets/wizard.scss
> UX: do not show site header on wizard pages

- lib/retrieve_title.rb
improves comment about caught exception to match
implementation
> DEV: improve comment

- app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-user-tags-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-user-test.js
> DEV: De-jQ sidebar tests

- app/assets/javascripts/discourse/app/components/topic-list.js
> DEV: Remove JQuery from `components/topic-list.js`

- app/assets/javascripts/discourse/tests/acceptance/plugin-outlet-multi-template-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/unit/lib/link-lookup-test.js
> DEV: Keep global state reset in a single place

- config/routes.rb
Additional tests are omitted as this is a small typo fix for an existing feature.
> Fix constraints typo in routes config

- lib/plugin/metadata.rb
> DEV: Add salesforce plugin to official list of plugins

- app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
> DEV: Remove JQuery from `lib/keyboard-shortcuts.js`

- app/assets/javascripts/discourse/app/components/sidebar.hbs
- app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.hbs
- app/assets/javascripts/discourse/app/components/sidebar/user/sections.hbs
- app/assets/stylesheets/common/base/sidebar-footer.scss
- app/assets/stylesheets/common/base/sidebar.scss
- app/assets/stylesheets/desktop/discourse.scss
This reverts the scrollbar changes in 3068df4ceaea48adc62ab915294e5787c02694c4 and removes an extra scroll wrapper
> UX: revert sidebar scrollbar repositioning

- app/assets/stylesheets/common/base/sidebar-section.scss
> remove margin from sidebar sections

- app/assets/stylesheets/common/base/sidebar-section-link.scss
- app/assets/stylesheets/common/base/sidebar-section.scss
Unifying some duplicate styles, and improving the sizing and hover/focus states of these header buttons:
> improve sidebar header sub-hovers

- app/assets/javascripts/discourse/app/components/sidebar.hbs
- app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.hbs
- app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.js
- app/assets/javascripts/discourse/app/components/sidebar/sections.hbs
- app/assets/javascripts/discourse/app/components/sidebar/sections.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-user-test.js
We were incorrectly trying to render the sidebar sections for a logged
in user.
> FIX: Sidebar hamburger panel dropdown not working for anonymous

- app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.hbs
- app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.js
- app/assets/javascripts/discourse/tests/acceptance/user-status-test.js
- app/assets/stylesheets/common/base/menu-panel.scss
> FEATURE: add the set user status button to the new user menu

- app/assets/javascripts/discourse/app/components/user-menu/bookmarks-list.js
- app/assets/javascripts/discourse/app/components/user-menu/items-list.js
- app/assets/javascripts/discourse/app/components/user-menu/messages-list.js
- app/assets/javascripts/discourse/app/components/user-menu/notifications-list.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/models/bookmark.js
- app/assets/javascripts/discourse/app/models/notification.js
- app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
- app/assets/javascripts/discourse/tests/fixtures/notification-fixtures.js
See https://github.com/discourse/discourse/pull/18081 for more details.
> DEV: Apply model transformer API on more models

- app/assets/javascripts/admin/addon/controllers/admin-site-text-index.js
- app/assets/javascripts/admin/addon/templates/site-text-index.hbs
- config/locales/client.en.yml
> UX: Remove confusing fallback locale warning

- Gemfile.lock
- lib/discourse_redis.rb
- spec/lib/discourse_redis_spec.rb
This reverts commit 0b5a0fd857a56e19834d52c9b5e2927c60f68771.
Pending release of Sidekiq 6.5.6 so that we don't get depreciation
warnings
> Revert "DEV: Upgrade Redis to 4.8"

- app/assets/stylesheets/wizard.scss
- app/views/finish_installation/index.html.erb
- config/locales/server.en.yml
Fixes the issue described here: https://meta.discourse.org/t/discourse-get-started-screen-is-too-big/237232
> UX: fix styles for the wizard congrats step

- app/assets/javascripts/discourse/app/templates/components/bread-crumbs.hbs
> DEV: update breadcrumbs outlet values

- app/assets/javascripts/wizard/addon/templates/components/wizard-field-checkbox.hbs
> DEV: plugin outlet for wizard checkboxes

- app/assets/stylesheets/mobile/menu-panel.scss
- app/assets/stylesheets/mobile/sidebar.scss
Font size was first increased in 9909d001c5c4c74bd4f25015001530c7be5796b7 but regressed in
7a05a9d4110cd3ad8c085750b9e2eb6590aeb75e
> UX: Increase sidebar fontsize on mobile

- app/assets/javascripts/discourse/app/templates/user-selector-autocomplete.hbr
- app/assets/javascripts/discourse/tests/acceptance/composer-editor-mentions-test.js
- app/assets/stylesheets/common/base/compose.scss
> FEATURE: show user status description on the mention popup

- .github/dependabot.yml
In preparation for npm addition
> DEV: Reformat dependabot config whitespace

- spec/lib/ember_cli_spec.rb
Followup to 6570fed175e61328341d1a7c0d8a7a7077b496ab
> DEV: Add test for EmberCli#ember_version

- .github/dependabot.yml
> DEV: Enable dependabot for frontend deps

- app/assets/javascripts/discourse/app/initializers/banner.js
- app/assets/javascripts/discourse/app/initializers/logout.js
- app/assets/javascripts/discourse/app/initializers/read-only.js
> DEV: message bus is always present

- app/assets/javascripts/discourse/app/widgets/render-glimmer.js
- app/assets/javascripts/discourse/tests/integration/components/widgets/render-glimmer-test.js
> DEV: Improve testing and documentation of RenderGlimmer actions

- app/assets/javascripts/admin/addon/controllers/admin-badges/show.js
- app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
- app/assets/javascripts/discourse/app/models/badge.js
- app/assets/javascripts/discourse/tests/acceptance/admin-badges-show-test.js
> Admin-badges fixes

- app/assets/javascripts/discourse/tests/fixtures/topic.js
It can be useful to have a topic with some predefined tags
> DEV: Add tags to a topic fixture

- .github/dependabot.yml
1. Restore the original time for npm updates
2. Increase the PR limit
> DEV: Update dependabot config

- package.json
- vendor/assets/javascripts/moment-locale/sr-cyrl.js
- vendor/assets/javascripts/moment-locale/sr.js
- vendor/assets/javascripts/moment.js
- yarn.lock
> DEV: Update moment.js

- app/assets/javascripts/discourse/tests/acceptance/preferences-test.js
> DEV: Add another missing `await`

- app/assets/javascripts/discourse/app/components/basic-topic-list.js
- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/initializers/banner.js
- app/assets/javascripts/discourse/app/initializers/logout.js
- app/assets/javascripts/discourse/app/initializers/read-only.js
- app/assets/javascripts/discourse/app/initializers/subscribe-user-notifications.js
- app/assets/javascripts/discourse/app/initializers/welcome-topic-banner.js
- app/assets/javascripts/discourse/app/lib/desktop-notifications.js
- app/assets/javascripts/discourse/app/models/user.js
- app/assets/javascripts/discourse/app/services/pm-topic-tracking-state.js
- app/assets/javascripts/discourse/app/services/presence.js
- plugins/discourse-narrative-bot/assets/javascripts/initializers/new-user-narrative.js
- plugins/poll/assets/javascripts/initializers/extend-for-poll.js
Various small changes made while debugging MessageBus-related tests.
> DEV: Minor code cleanup

- app/assets/javascripts/discourse/app/controllers/preferences/account.js
- app/assets/javascripts/discourse/tests/acceptance/user-preferences-account-test.js
- app/assets/javascripts/discourse/tests/fixtures/user-fixtures.js
Replaces bootbox and adds a test.
> DEV: Refactor self-delete dialog

- app/views/layouts/_noscript_header.html.erb
Related to https://meta.discourse.org/t/remove-duplicate-h1-from-topic-other-pages-to-improve-seo-rankings-for-topic-pages/238577
> DEV: remove H1 from crawler view header

- app/assets/javascripts/discourse/app/components/sidebar/user/categories-section.hbs
- app/assets/javascripts/discourse/app/components/sidebar/user/tags-section.hbs
- app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-user-tags-section-test.js
- config/locales/client.en.yml
> UX: sidebar more link for categories & tags

- app/assets/javascripts/discourse/app/controllers/composer.js
- app/assets/javascripts/discourse/app/initializers/logout.js
- app/assets/javascripts/discourse/app/models/composer.js
- app/assets/javascripts/discourse/tests/acceptance/composer-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-test.js
- app/assets/stylesheets/common/base/dialog.scss
- app/assets/stylesheets/common/base/modal.scss
> DEV: Refactor composer and logout dialogs

- app/assets/javascripts/discourse/app/widgets/header-contents.js
- app/assets/stylesheets/common/base/header.scss
- app/assets/stylesheets/desktop/discourse.scss
0ef68f52d88148246854f7b44c37aa582de6ce44 is causing a few issues that I can't repro, so reverting until it can get figured out...
> Revert: header sidebar change 0ef68f5

- app/assets/stylesheets/desktop/topic-list.scss
> UX: Get rid of active cursor on dead link

- app/assets/stylesheets/mobile/menu-panel.scss
> UX: Remove height CSS preventing sidebar touch scrolling on mobile

- app/assets/javascripts/discourse/app/pre-initializers/theme-errors-handler.js
> DEV: Log theme error names and messages

- app/assets/javascripts/discourse/tests/addons/truth-helpers/integration/helpers/includes-test.js
- app/assets/javascripts/truth-helpers/addon/helpers/includes.js
Usage :
```
{{#if (includes fooArray foo)}}
```
```
{{#if (includes fooString foo)}}
```
> DEV: adds includes helper to templates

- app/assets/stylesheets/common/base/compose.scss
- app/assets/stylesheets/common/base/discourse.scss
- app/assets/stylesheets/common/base/lightbox.scss
- app/assets/stylesheets/common/base/onebox.scss
- app/assets/stylesheets/common/base/rtl.scss
- app/assets/stylesheets/common/base/search-menu.scss
- app/assets/stylesheets/common/components/buttons.scss
- app/assets/stylesheets/common/components/conditional-loading-section.scss
- app/assets/stylesheets/common/components/user-card.scss
- app/assets/stylesheets/common/foundation/mixins.scss
- app/assets/stylesheets/common/select-kit/category-chooser.scss
- app/assets/stylesheets/common/select-kit/category-row.scss
- app/assets/stylesheets/common/topic-timeline.scss
- app/assets/stylesheets/desktop/modal.scss
- app/assets/stylesheets/desktop/topic-post.scss
- app/assets/stylesheets/mobile/header.scss
> DEV: Remove obsolete CSS prefixes

- config/locales/client.en.yml
> Improve Safari 13 deprecation copy

- spec/requests/api/posts_spec.rb
> DEV: Add `before` parameter to `/posts.json` API docs

- app/assets/javascripts/discourse/app/templates/list/topic-list-item.hbr
> DEV: Add two new plugin outlets in topic list

- app/assets/javascripts/discourse/app/widgets/post-cooked.js
- app/assets/javascripts/discourse/tests/integration/components/widgets/post-cooked-test.js
- app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js
> SECURITY: Handle incomplete quote bbcode (beta)

- .github/workflows/tests.yml
> DEV: Update github workflow for 8-core workers

- db/migrate/20220920044310_enforce_user_profile_max_limits.rb
> DEV: Only lock rows that need to change in migration

- app/assets/javascripts/discourse/app/controllers/user.js
- app/assets/javascripts/discourse/app/templates/user.hbs
Followup to b066955838b0107b34b9ea7bce073632c73eeedc
> FIX: Hide experimental user navigation changes when disabled

- lib/tasks/posts.rake
Follow up to commit 9db8f00b3dd6f2881adf1b786e29426889225e7a.
> FIX: Query correct model in posts:inline_uploads

- app/assets/javascripts/discourse/app/widgets/topic-timeline.js
- app/assets/stylesheets/common/topic-timeline.scss
This reverts commit b98cd73aced2c15bef5f6346fb3ddd498e16cd45.
These are sticking around for some people after a click, so this will need more work.
> Revert "FEATURE: add tooltips to timeline start/end dates (#18294)"

- .github/workflows/tests.yml
- Gemfile
- Gemfile.lock
- bin/start_selenium_server
- bin/system_rspec
- lib/chrome_installed_checker.rb
- spec/rails_helper.rb
Some proposed changes for #16311. See commit messages for details.
> Rails system tests experiment proposals

- app/assets/javascripts/discourse/app/widgets/post-cooked.js
> DEV: De-jQ post-cooked

- app/assets/javascripts/discourse/app/components/global-notice.js
- config/locales/client.en.yml
> DEV: Differentiate staff-writes-only banner

- app/models/category_featured_topic.rb
In the past, CategoryFeaturedTopic.feature_topics raised an exception sometimes because it tried to create multiple CategoryFeaturedTopic records for the same topic.
> FIX: Make sure featured category topics are unique

- app/assets/javascripts/discourse/app/templates/components/time-shortcut-picker.hbs
> A11Y: Associate label with input in bookmark modal

- app/assets/stylesheets/common/base/login.scss
This reverts commit c975fa3b29ccc460d94a00b3427e25ea0fcf10b4.
CSS changes here break CI
> Revert "init (#18387)"

- app/assets/javascripts/discourse/app/controllers/composer.js
Follow up to https://github.com/discourse/discourse/commit/250c0bccbd5ca3fe34f5e0e0b94113dbb87c3cd3
> FIX: some composer messages were broken

- app/assets/stylesheets/common/base/sidebar.scss
Follow-up to f1cbc23f1ecbfff3bd4c6c1c1dfde057184122ba
> DEV: Revert change in background-color of sidebar

- app/assets/stylesheets/common/base/sidebar-section.scss
Follow-up to f1cbc23f1ecbfff3bd4c6c1c1dfde057184122ba
> UX: Correct padding and height for sidebar section message

- app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/review-section-link.js
I don't think a test is worth it here long term so just adding a screenshot for reviewer:
> UX: Add flag icon for review section link in sidebar

- app/controllers/admin/themes_controller.rb
- config/routes.rb
- spec/requests/admin/themes_controller_spec.rb
> SECURITY: moderator shouldn't be able to import a theme via API

- lib/compression/engine.rb
- lib/compression/gzip.rb
- lib/compression/pipeline.rb
- lib/compression/strategy.rb
- lib/compression/tar.rb
- lib/compression/zip.rb
- lib/theme_store/zip_importer.rb
- spec/lib/compression/engine_spec.rb
- spec/lib/theme_store/zip_exporter_spec.rb
> SECURITY: Prevent arbitrary file write when decompressing files

- lib/compression/engine.rb
- lib/compression/gzip.rb
- lib/compression/pipeline.rb
- lib/compression/strategy.rb
- lib/compression/tar.rb
- lib/compression/zip.rb
- lib/theme_store/zip_importer.rb
- spec/components/theme_store/zip_exporter_spec.rb
- spec/lib/compression/engine_spec.rb
> SECURITY: Prevent arbitrary file write when decompressing files (stable)

- app/controllers/admin/themes_controller.rb
- config/routes.rb
- spec/requests/admin/themes_controller_spec.rb
> SECURITY: moderator shouldn't be able to import a theme via API (beta)

- app/controllers/admin/themes_controller.rb
- config/routes.rb
- spec/requests/admin/themes_controller_spec.rb
> SECURITY: moderator shouldn't be able to import a theme via API (stable)

- lib/compression/engine.rb
- lib/compression/gzip.rb
- lib/compression/pipeline.rb
- lib/compression/strategy.rb
- lib/compression/tar.rb
- lib/compression/zip.rb
- lib/theme_store/zip_importer.rb
- spec/lib/compression/engine_spec.rb
- spec/lib/theme_store/zip_exporter_spec.rb
> SECURITY: Prevent arbitrary file write when decompressing files (beta)

- lib/version.rb
> Version bump to v2.8.9
