app/assets/stylesheets/desktop/topic-list.scss
=> UX: move dismiss button on the bottom to the right of the footer message

app/models/invite.rb, config/locales/server.en.yml, spec/models/invite_spec.rb
=> FIX: Add better and more strict invite validators

app/assets/javascripts/discourse/app/routes/application.js
=> FIX: Allow logout for admins in staff-writes-only-mode

app/controllers/session_controller.rb, app/controllers/users_controller.rb, spec/requests/session_controller_spec.rb
=> FIX: Allow email login for admins in staff-writes-only-mode

app/assets/javascripts/discourse/app/templates/topic-list-header.hbr
=> DEV: Add new plugin outlet in topic list header

app/assets/javascripts/discourse/app/components/user-nav.hbs, app/assets/javascripts/discourse/app/templates/user.hbs
Now that we have chat, the comment icon is no longer ideal
Internal Ref: /t/67780/55
=> UX: Change notifications nav icon in user page to bell

app/assets/javascripts/discourse/app/components/user-nav/messages-groups-dropdown.js, app/assets/javascripts/discourse/app/components/user-nav/messages-nav.hbs, app/assets/javascripts/discourse/app/components/user-nav/messages-nav.js, app/assets/javascripts/discourse/app/controllers/user-private-messages.js, app/assets/javascripts/discourse/app/templates/user/messages.hbs, app/assets/stylesheets/desktop/new-user.scss, app/assets/stylesheets/mobile/new-user.scss, config/locales/client.en.yml
No tests are written for now as we're still in a highly iterative stage
=> DEV: Convert messages user page nav to experimental redesign

app/assets/javascripts/discourse/app/controllers/application.js, app/assets/javascripts/discourse/app/routes/second-factor-auth.js, app/assets/javascripts/discourse/tests/acceptance/second-factor-auth-test.js, app/assets/javascripts/wizard/addon/routes/wizard.js
=> UX: Hide sidebar on 2FA route

app/assets/javascripts/discourse/app/templates/user/notifications.hbs
No tests as the changes are experimental and unconfirmed
Internal Ref: /t/67780/58
=> DEV: Experimental changes to user page notifications nav

app/assets/javascripts/discourse/tests/unit/routes/review-index-test.js
Related: https://github.com/discourse/discourse/pull/18395
=> DEV: Add tests for review-index route

app/assets/javascripts/discourse/app/components/user-nav.hbs, app/assets/javascripts/discourse/app/components/user-nav/messages-nav.hbs, app/assets/javascripts/discourse/app/templates/user/activity.hbs, app/assets/javascripts/discourse/app/templates/user/notifications.hbs
As usual, design is still in flux so no tests for now.
Internal Ref: /t/67780/59
=> DEV: Convert experimental user page activity nav to horizontal nav

app/assets/javascripts/discourse/app/lib/sidebar/user/messages-section/message-section-link.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-messages-section-test.js
Follow-up to c0037dc0f06f08bd050aedc8aad97d1f05b322ab
=> DEV: Fix message section link filters displaying icons

app/models/reviewable.rb, spec/models/reviewable_spec.rb
=> DEV: Delete reviewable associations when deleting them

app/assets/javascripts/discourse/app/templates/mobile/list/topic-list-item.hbr
=> FEATURE: new outlet topic-list-main-link-bottom added to mobile

app/assets/javascripts/discourse/app/components/user-nav.hbs, app/assets/javascripts/discourse/app/components/user-nav/messages-nav.hbs, app/assets/javascripts/discourse/app/controllers/user.js, app/assets/javascripts/discourse/app/templates/preferences.hbs, app/assets/javascripts/discourse/app/templates/user-invited.hbs, app/assets/javascripts/discourse/app/templates/user.hbs, app/assets/javascripts/discourse/app/templates/user/activity.hbs, app/assets/javascripts/discourse/app/templates/user/notifications.hbs, app/assets/stylesheets/common/base/new-user.scss, app/assets/stylesheets/desktop/new-user.scss, app/assets/stylesheets/mobile/new-user.scss
No tests and this redesign is still highly highly experimental
=> DEV: Try out double nav for new experimental user page nav

app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, lib/stylesheet/manager.rb, spec/helpers/application_helper_spec.rb, spec/lib/stylesheet/manager_spec.rb, spec/requests/application_controller_spec.rb
This reverts commit 2d1dbc6f9616ce18807d87c8700c41ee73daa450.
We need to increase nginx proxy buffer to land this.
=> Revert "FEATURE: Preload resources via link header (#18475)"

app/assets/javascripts/discourse/app/templates/components/bread-crumbs.hbs
=> DEV: Fix `bread-crumbs-right` `currentCategory` argument

app/assets/javascripts/discourse/app/mixins/user-fields-validation.js, app/assets/javascripts/discourse/app/templates/components/user-fields/text.hbs, app/assets/javascripts/discourse/app/templates/modal/create-account.hbs, app/assets/javascripts/discourse/tests/acceptance/create-account-user-fields-test.js, config/locales/client.en.yml
=> FIX: Show error if field is same as password

spec/lib/pretty_text/helpers_spec.rb, spec/requests/hashtags_controller_spec.rb
Adding a couple of small specs to code around hashtags for tags and categories since I will be working in this area soon and these were not covered.
=> DEV: Add specs for hashtags related code

plugins/poll/assets/javascripts/controllers/poll-ui-builder.js, plugins/poll/assets/javascripts/discourse/templates/modal/poll-ui-builder.hbs, plugins/poll/test/javascripts/acceptance/poll-builder-enabled-test.js
Followup to 03b7b7d1bc7c978c280e441a610a5ef5c049c60c
=> FIX: Ensure poll type toggle buttons function correctly

app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/discourse_defaults.conf, lib/stylesheet/manager.rb, spec/helpers/application_helper_spec.rb, spec/lib/stylesheet/manager_spec.rb, spec/requests/application_controller_spec.rb
This reverts commit 95a57f7e0c7e78ecac14760ae4751e0ae2e8ea0d.
Can be landed after #18530  **and** a beta bump + forced rebuild lands
=> Revert "Revert "FEATURE: Preload resources via link header (#18475)" (#18511)"

app/assets/stylesheets/common/foundation/colors.scss, spec/models/report_spec.rb
=> UX: danger colour update

app/assets/javascripts/discourse/app/controllers/auth-token.js
=> A11Y: Trap focus on auth security modal

app/assets/javascripts/discourse/app/models/topic.js, app/assets/javascripts/discourse/app/routes/topic-from-params.js, app/assets/javascripts/discourse/app/routes/topic.js, app/assets/javascripts/discourse/app/templates/topic.hbs
See https://github.com/discourse/discourse/pull/14838#issuecomment-1271935405 for details about `controllerReady` logic.
Co-authored-by: David Taylor <david@taylorhq.com>
=> DEV: Asyncify loadTopicView

app/assets/javascripts/admin/addon/templates/users-list-show.hbs, app/assets/javascripts/discourse/app/components/table-header-toggle.js, app/assets/javascripts/discourse/app/templates/components/table-header-toggle.hbs, config/locales/client.en.yml
While navigating the table, indicate what the button does and if the user pressed it or not. Also, don't lose focus after reordering elements.
=> A11Y: Signal the toggle header can reorder table elements.

config/locales/client.en.yml
Fixed a typo and added more guidance on info the welcome topic should contain.
=> updated copy for Create your Welcome Topic CTA

app/assets/javascripts/discourse/app/widgets/post-menu.js, config/locales/client.en.yml
Includes the post number and poster's username for screen readers.
=> A11Y: Add more information to the "reply to" button label.

lib/topic_query.rb, spec/requests/list_controller_spec.rb
This reverts commit 49abcf965bfc9fc8728a3919dbd820c5bf59617a.
=> Revert "FEATURE: Hide Privacy Policy and TOS topics (#18533)"

app/assets/javascripts/discourse/app/templates/components/d-navigation.hbs
=> UX: Change button to grey

app/assets/javascripts/discourse/app/templates/components/d-navigation.hbs
Reverts discourse/discourse#18635
=> Revert "UX: Change button to grey"

app/assets/javascripts/discourse/app/components/d-navigation.js, app/assets/javascripts/discourse/app/templates/components/bootstrap-mode-notice.hbs, app/assets/javascripts/discourse/app/templates/components/d-navigation.hbs, app/assets/javascripts/discourse/tests/acceptance/bootstrap-mode-notice-test.js
Reverts discourse/discourse#18626
=> Revert "UX: Simplify bootstrap mode visuals"

app/assets/javascripts/discourse-js-processor.js, app/models/theme.rb, app/models/theme_field.rb, config/locales/server.en.yml, lib/discourse_js_processor.rb, lib/theme_javascript_compiler.rb, spec/lib/theme_javascript_compiler_spec.rb, spec/models/theme_field_spec.rb
=> DEV: Introduce support for template colocation in themes

app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
If one were to modify nested objects in `Site.current()` those changes would be carried over subsequent tests.
=> DEV: Prevent potential site state leaks in tests

app/models/theme.rb
This should have been included in c185043590f931c7185ccbec33eb0bd2d77d764d
=> DEV: Bump theme compiler version for connector fix

app/assets/javascripts/discourse-common/addon/config/environment.js, app/assets/javascripts/discourse-common/addon/lib/legacy-resolver.js, app/assets/javascripts/discourse-common/addon/resolver.js, app/assets/javascripts/discourse/app/components/d-tooltip.js, app/assets/javascripts/discourse/app/components/reviewable-item.js, app/assets/javascripts/discourse/app/initializers/ember-events.js, app/assets/javascripts/discourse/app/initializers/ember-link-component-extension.js, app/assets/javascripts/discourse/app/lib/click-track.js, app/assets/javascripts/discourse/app/lib/formatter.js, app/assets/javascripts/discourse/app/lib/lightbox.js, app/assets/javascripts/discourse/app/lib/link-hashtags.js, app/assets/javascripts/discourse/app/lib/link-mentions.js, app/assets/javascripts/discourse/app/lib/plugin-connectors.js, app/assets/javascripts/discourse/app/pre-initializers/theme-errors-handler.js, app/assets/javascripts/discourse/tests/acceptance/custom-html-template-test.js, app/assets/javascripts/discourse/tests/acceptance/modal-test.js, app/assets/javascripts/discourse/tests/acceptance/plugin-outlet-connector-class-test.js, app/assets/javascripts/discourse/tests/acceptance/plugin-outlet-decorator-test.js, app/assets/javascripts/discourse/tests/acceptance/plugin-outlet-multi-template-test.js, app/assets/javascripts/discourse/tests/acceptance/plugin-outlet-single-template-test.js, app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js, app/assets/javascripts/discourse/tests/setup-tests.js, app/assets/javascripts/discourse/tests/test-boot-ember-cli.js, app/assets/javascripts/discourse/tests/unit/ember/resolver-test.js
=> DEV: Remove all use of Ember/jQuery globals in core

app/assets/javascripts/discourse/lib/bootstrap-json/index.js, app/assets/javascripts/discourse/public/assets/scripts/discourse-test-load-dynamic-js.js, app/assets/javascripts/discourse/testem.js, app/assets/javascripts/discourse/tests/index.html, app/controllers/bootstrap_controller.rb, config/routes.rb, plugins/poll/test/javascripts/widgets/discourse-poll-test.js
=> DEV: Load plugin CSS in tests

config/locales/client.en.yml
=> UX: correct capitalization

app/models/site.rb, lib/topic_query_params.rb, spec/requests/list_controller_spec.rb
For non-admins this change will hide the welcome topic if it hasn't been
edited yet.
=> FEATURE: Hide welcome topic if it hasn't been edited

lib/theme_javascript_compiler.rb, spec/lib/theme_javascript_compiler_spec.rb
=> DEV: Apply theme template transforms to colocated components

app/assets/javascripts/discourse/app/templates/preferences/profile.hbs
=> A11Y: Add `for` attributes for location, website in profile

app/assets/javascripts/discourse/app/templates/components/user-stream-item.hbs
=> A11Y: Add title to drafts remove icon button

app/assets/javascripts/discourse/app/components/sidebar/footer.hbs
Using this to add a theme toggle
=> DEV: add plugin outlet to sidebar footer

.template-lintrc.js
=> DEV: Enable `no-args-paths` and `no-attrs-in-components` lint rules

docs/ADMIN-QUICK-START-GUIDE.md
=> Fix: minor typo

app/assets/stylesheets/common/base/compose.scss
A follow-up to c421dc0b2894ed2cae407b1727fff92603a7e90b
=> UX: Fix user status display in autocomplete

spec/requests/api/groups_spec.rb, spec/requests/api/schemas/json/group_create_request.json
Documenting more params that are available to the create group api
endpoint.
=> DEV: Document create group api params

app/models/discourse_connect.rb, spec/models/discourse_connect_spec.rb
Discourse Connect can be used to manage group memberships of users by including a `add_groups`, `remove_groups` or `groups` attribute in the Discourse Connect payload. However, additions/deletions of users from groups aren't logged to the groups logs (available at `/g/<group>/manage/logs`) which can cause confusions to admins they try to figure out when/how users were added or removed from a group. This PR makes Discourse Connect add entries to the groups logs when it makes changes to users' group memberships.
=> FIX: Log user addition/deletion from groups when they're changed via DiscourseConnect

lib/html_to_markdown.rb
=> DEV: remove deprecation warnings related to Nokogiri

app/assets/javascripts/discourse/app/lib/plugin-api.js
=> DEV: Update docs for composerBeforeSave

app/assets/javascripts/discourse/app/controllers/preferences/account.js, app/assets/javascripts/discourse/app/controllers/user-status.js
See [this discussion](https://github.com/discourse/discourse/pull/18532#discussion_r993610151).
=> DEV: make possible to pass both async and sync callbacks to the user status modal

lib/tasks/docker.rake
=> DEV: Parallelize core JS tests in docker.rake

config/locales/client.en.yml
=> UX: Fix grammar typo in trust_level_unlocked_tip

app/assets/javascripts/discourse/app/components/sidebar/user/categories-section.hbs, app/assets/javascripts/discourse/app/components/sidebar/user/categories-section.js, app/assets/javascripts/discourse/app/components/sidebar/user/tags-section.hbs, app/assets/javascripts/discourse/app/components/sidebar/user/tags-section.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-tags-section-test.js, config/locales/client.en.yml
=> UX: Switch no categories/tags configured text in sidebar to a link

app/models/theme.rb, lib/theme_javascript_compiler.rb
=> DEV: Do not remove `debugger` statements from theme JS

app/assets/javascripts/discourse/app/controllers/invites-show.js, app/assets/javascripts/discourse/app/templates/invites/show.hbs, app/controllers/invites_controller.rb, app/controllers/session_controller.rb, app/models/email_token.rb, app/models/invite.rb, app/models/invite_redeemer.rb, config/locales/client.en.yml, config/locales/server.en.yml, db/post_migrate/20221026035440_security_log_out_invite_redemption_invited_users.rb, spec/models/invite_redeemer_spec.rb, spec/models/invite_spec.rb, spec/requests/invites_controller_spec.rb
See https://github.com/discourse/discourse/security/advisories/GHSA-x8w7-rwmr-w278
=> SECURITY: Fix invite link email validation

app/assets/javascripts/discourse/app/controllers/invites-show.js, app/assets/javascripts/discourse/app/templates/invites/show.hbs, app/assets/javascripts/discourse/tests/acceptance/invite-accept-test.js, app/controllers/invites_controller.rb, app/controllers/session_controller.rb, app/models/email_token.rb, app/models/invite.rb, app/models/invite_redeemer.rb, config/locales/client.en.yml, config/locales/server.en.yml, db/post_migrate/20221026035440_security_log_out_invite_redemption_invited_users.rb, spec/models/invite_redeemer_spec.rb, spec/models/invite_spec.rb, spec/requests/invites_controller_spec.rb
See https://github.com/discourse/discourse/security/advisories/GHSA-x8w7-rwmr-w278
=> SECURITY: Fix invite link validation (stable)

lib/version.rb
=> Stable version bump to v2.8.10

app/assets/javascripts/yarn.lock
1. Add `"testem": "latest"` to package.json
2. `yarn`
3. `npx yarn-deduplicate`
4. Remove the line from package.json
5. `yarn`
=> DEV: Force `testem` upgrade

spec/jobs/jobs_base_spec.rb, spec/jobs/jobs_spec.rb, spec/lib/discourse_plugin_registry_spec.rb, spec/lib/file_store/s3_store_spec.rb, spec/lib/onebox/json_ld_spec.rb, spec/lib/s3_helper_spec.rb, spec/lib/site_settings/yaml_loader_spec.rb, spec/lib/theme_store/git_importer_spec.rb, spec/models/report_spec.rb, spec/models/reviewable_user_spec.rb, spec/multisite/s3_store_spec.rb, spec/requests/admin/backups_controller_spec.rb, spec/requests/reviewables_controller_spec.rb, spec/services/user_merger_spec.rb
It now supports strict keyword argument matching by default.
=> DEV: Fix mocha deprecations

spec/integration/github_omniauth_spec.rb
=> DEV: Add integration specs for Github login

.github/labeler.yml, .github/workflows/labeler.yml
This will automatically apply the "chat" label to any PR which includes changes to `plugins/chat/**/*`
https://github.com/actions/labeler
=> DEV: Automatically label chat PRs

.github/labeler.yml
Followup to 449f7d5ed5b32adf281e96a4d36ff3084f320817
=> DEV: Fix `labeler.yml` glob configuration

app/assets/javascripts/discourse/app/components/sidebar/user/sections.hbs, app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-section-link.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js, plugins/chat/assets/javascripts/discourse/initializers/chat-sidebar.js, plugins/chat/assets/stylesheets/sidebar-extensions.scss, plugins/chat/test/javascripts/acceptance/core-sidebar-test.js
=> UX: Muted style for entire chat section link when muted

config/locales/client.en.yml
=> removed some extraneous question marks

plugins/chat/app/jobs/regular/chat_notify_mentioned.rb, plugins/chat/spec/jobs/regular/chat_notify_mentioned_spec.rb
https://github.com/discourse/discourse/blob/main/plugins/chat/assets/javascripts/discourse/initializers/chat-user-menu.js#L87
=> FIX: the notification data on the client expects an identifier

app/assets/javascripts/discourse/app/components/user-menu/messages-list.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/pinned-options-test.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/topic-notifications-button-test.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/topic-notifications-options-test.js, app/assets/javascripts/discourse/tests/integration/components/topic-list-item-test.js, app/assets/javascripts/discourse/tests/integration/components/topic-list-test.js, app/assets/javascripts/discourse/tests/integration/components/user-menu/messages-list-test.js, app/assets/javascripts/discourse/tests/integration/components/widgets/post-stream-test.js, app/assets/javascripts/discourse/tests/integration/components/widgets/topic-admin-menu-test.js, app/assets/javascripts/discourse/tests/unit/controllers/topic-test.js, app/assets/javascripts/discourse/tests/unit/models/topic-details-test.js, app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js
=> DEV: Use `store.createRecord` for Topic models

app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/tests/unit/lib/plugin-api-test.js
`modifyClassStatic` left as an exercise for the reader 😜
=> DEV: Make `modifyClass` native class-aware, add tests

app/controllers/admin/themes_controller.rb, spec/requests/admin/themes_controller_spec.rb
Otherwise the errors don't get caught.
=> FIX: Theme import error handling needs to happen inside the hijack block

lib/theme_store/git_importer.rb
This should fix fetching from gitlab.
=> FIX: When cloning themes via HTTP, try the original URI too

.streerc
Chat plugin had this file, we can add it safely
without adding changes to CI so we can still run
syntax_tree on chat code manually.
=> DEV: Add .streerc file

app/assets/javascripts/discourse/app/components/user-nav/notifications-nav.hbs
=> FIX: restore mention tab for experimental user nav

lib/tasks/themes.rake
=> DEV: Add rake task to install a theme from an archive

config/locales/client.en.yml, plugins/poll/config/locales/server.en.yml
=> Fix spelling

lib/tasks/s3.rake
- Ensure it works with prefixed S3 buckets
- Perform a sanity check that all current assets are present on S3 before starting deletion
- Remove the lifecycle rule configuration and delete expired assets immediately. This task should be run post-deploy anyway, so adding a 10-day window is not required
=> Fix and improve `s3:expire_missing_assets` task

app/assets/javascripts/discourse/tests/unit/lib/text-test.js
Follow up to ac7bf98ad10e529b02a9cddce4367ecb9428b5e1
=> DEV: Fix text util test

app/views/qunit/theme.html.erb
Follow up to ac7bf98ad10e529b02a9cddce4367ecb9428b5e1
=> DEV: Load JS site settings in theme qunit HTML

config/initializers/assets.rb, spec/requests/qunit_controller_spec.rb
Follow up to 59da6c6ea22865e0be3dce18b3243cf423a76f22
=> DEV: Add test-site-settings to asset pipeline

app/assets/javascripts/discourse/tests/integration/components/widgets/post-stream-test.js, app/assets/javascripts/discourse/tests/unit/lib/link-lookup-test.js, app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js, app/assets/javascripts/discourse/tests/unit/models/composer-test.js, app/assets/javascripts/discourse/tests/unit/models/pending-post-test.js, app/assets/javascripts/discourse/tests/unit/models/post-test.js
=> DEV: Use store to create Post records in tests

app/models/bookmark.rb, app/models/concerns/has_custom_fields.rb, app/models/site_setting.rb, db/post_migrate/20221108032233_drop_old_bookmark_columns_v2.rb, lib/guardian/tag_guardian.rb, spec/support/uploads_helpers.rb
* Drop old bookmark columns to follow up b22450c7a8d378b32291743ca602cbc477dea106
* Change some group site setting checks to use the _map helper
* Remove old secure_media helper stub for chat
* Change attr_accessor to attr_reader for preloaded_custom_fields to follow up 70af45055ae24dc7eb1a20678a52ed3ec69421c3
=> DEV: TODO followups

plugins/chat/assets/javascripts/discourse/routes/chat.js, plugins/chat/spec/system/navigation_spec.rb, plugins/chat/spec/system/page_objects/sidebar/sidebar.rb, plugins/chat/test/javascripts/acceptance/core-sidebar-test.js
=> FIX: handles starting draft dm from sidebar

plugins/chat/assets/javascripts/discourse/templates/components/chat-channel-settings-view.hbs
=> FIX: uses i18n for saved text

plugins/chat/db/post_migrate/20221104054957_backfill_channel_slugs.rb
Follow up c6764d8c74634c3928c8dadf36f8786487e80ba5
=> DEV: Fix broken slug migration

app/assets/javascripts/admin/addon/controllers/admin-permalinks.js, app/assets/javascripts/admin/addon/templates/components/permalink-form.hbs, app/assets/javascripts/admin/addon/templates/permalinks.hbs, app/assets/javascripts/discourse/tests/acceptance/admin-permalink-test.js, config/locales/client.en.yml
This PR fixes some minor usability issues with permalinks, namely:
- the search bar should not disappear after a search with no results
- the "no results" message should not appear when no permalinks are present
=> FIX: Permalinks issues

app/models/post.rb, lib/shrink_uploaded_image.rb, spec/lib/shrink_uploaded_image_spec.rb
…has regressed in 991b62b6f123e9df63f443bba411eee4f3c3066a / #16594
=> FIX: Shrinking images where smaller image upload exists

app/views/users/password_reset.html.erb
=> UX: better password reset error page

spec/system/page_objects/pages/category.rb
=> DEV: Add category page object for plugin tests

app/assets/stylesheets/common/base/sidebar-section-link.scss
=> UX: more contrast for sidebar counts

spec/integration/discord_omniauth_spec.rb, spec/integration/facebook_omniauth_spec.rb, spec/integration/twitter_omniauth_spec.rb
=> DEV: Add integration specs for Discord, Facebook and Twitter logins

app/assets/javascripts/admin/addon/templates/plugins-index.hbs, plugins/chat/assets/stylesheets/common/core-extensions.scss, plugins/chat/config/locales/client.en.yml, plugins/chat/config/settings.yml
=> UX: adds chat section in settings and hide it in plugins

lib/theme_store/git_importer.rb, spec/components/theme_store/git_importer_spec.rb
Fixes:
* An issue where the git url gets updated when it shouldn't,
* Fetching from gitlab,
=> FIX: Update GitImporter to match main

spec/requests/api/schemas/json/category_create_request.json
Updating the API Docs for creating a category. Added several more params
that are available to this endpoint, like `parent_category_id` and
`permissions`. There are many more parameters to add, but this is a good
step in the right direction.
=> DEV: Document some more parms for the cat create api docs

lib/theme_store/git_importer.rb, spec/lib/theme_store/git_importer_spec.rb
=> DEV: Reinstate --single-branch when cloning themes

plugins/chat/assets/javascripts/discourse/components/chat-emoji-picker.js, plugins/chat/assets/javascripts/discourse/templates/components/chat-emoji-picker.hbs
=> UX: improves arrow support in chat emoji picker

app/assets/javascripts/discourse/tests/test-boot-ember-cli.js
=> DEV: Make the `setupTests` a regular import

spec/requests/theme_javascripts_controller_spec.rb
It was failing in the local env
=> DEV: Fix a theme_js spec

app/assets/javascripts/discourse/app/components/site-header.js, app/assets/javascripts/discourse/app/widgets/header.js, app/assets/javascripts/discourse/tests/acceptance/user-tips-test.js, app/assets/javascripts/discourse/tests/integration/components/site-header-test.js, app/assets/stylesheets/common/base/discourse.scss, app/assets/stylesheets/mobile/ring.scss, config/locales/client.en.yml
This was replaced by the new "first notification" user tip.
=> DEV: Remove old "first notification" tutorial

app/assets/javascripts/discourse/app/lib/public-js-versions.js, package.json, public/javascripts/pikaday/1.8.2/pikaday.js, yarn.lock
=> DEV: Bump pikaday

app/assets/javascripts/discourse/app/widgets/search-menu-results.js, config/locales/client.en.yml
=> Add search tip for `@me` shortcut

package.json, yarn.lock
=> DEV: Bump `@mixer/parallel-prettier`

app/assets/javascripts/discourse/app/templates/user/summary.hbs
=> DEV: Added plugin outlet below user summary stats

app/assets/javascripts/discourse/app/templates/email-login.hbs, app/assets/stylesheets/common/base/login.scss, app/assets/stylesheets/desktop/login.scss, app/assets/stylesheets/mobile/login.scss, app/controllers/session_controller.rb, config/locales/server.en.yml, spec/requests/session_controller_spec.rb
=> UX: better email login pages

plugins/chat/assets/javascripts/discourse/components/chat-browse-view.js, plugins/chat/config/locales/server.en.yml, plugins/chat/config/settings.yml, plugins/chat/test/javascripts/acceptance/chat-browse-test.js
=> FEATURE: Stop hiding “allow archiving channels” setting

app/assets/javascripts/discourse/app/components/bulk-select-all.js, app/assets/javascripts/discourse/app/components/composer-save-button.hbs, app/assets/javascripts/discourse/app/components/composer-save-button.js, app/assets/javascripts/discourse/app/components/d-button.js, app/assets/javascripts/discourse/app/components/glimmer-component-with-deprecated-parent-view.js, app/assets/javascripts/discourse/app/components/login-reply-button.js, app/assets/javascripts/discourse/app/templates/components/d-button.hbs, app/assets/javascripts/discourse/tests/integration/components/d-button-test.js
Still a handful of failing tests.
=> Convert DButton to a Glimmer Component

.github/workflows/tests.yml, lib/s3_helper.rb, lib/tasks/s3.rake, spec/components/s3_helper_spec.rb
(to be rebased and merged - see individual commits)
=> Backport `s3:expire_missing_assets` fixes to stable

package.json, yarn.lock
=> DEV: Bump chrome-remote-interface

package.json, yarn.lock
=> DEV: Bump chrome-launcher

app/assets/javascripts/discourse/app/components/topic-list.js, app/assets/javascripts/discourse/app/controllers/topic-bulk-actions.js, app/assets/javascripts/discourse/app/mixins/bulk-topic-selection.js, app/assets/javascripts/discourse/tests/acceptance/topic-bulk-actions-test.js
- Also allows tl4 to perform batch tagging
---
Long term this needs to be rewritten to account for "bulk action" permission
given from the server.
=> FIX: allow tl4 to bulk select

app/assets/javascripts/discourse/tests/acceptance/preferences-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-security-test.js
Mixing multiple acceptance tests in a single file makes the acceptance
tests much harder to find.
=> DEV: Split tests for user preferences security page into individual file

app/assets/javascripts/discourse/tests/acceptance/preferences-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-second-factor-backup-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-second-factor-test.js
This helps to make it easier to identify the test file for the
particular route.
=> DEV: Move 2FA preferences tests into individual files

app/assets/javascripts/discourse/ember-cli-build.js, app/assets/javascripts/discourse/package.json, app/assets/javascripts/discourse/tests/acceptance/preferences-test.js
=> DEV: Move the recently added dev-deps to deps

lib/s3_inventory.rb
The UPDATE statement could lock the `uploads` table for a very long time when the `verification_status` of lots of uploads changed. Splitting up and simplifying the UPDATE solves that problem.
Also, this change ensures that only the needed data from the inventory gets inserted into the `TEMP TABLE`. For example, there's no need to have records for optimized images in that table when the `uploads` table gets updated.
=> PERF: Speed up S3 inventory updates

app/assets/javascripts/discourse/tests/acceptance/preferences-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-account-test.js
Makes it easier to associate the route with the tests
=> DEV: Centralise more user preferences tests into individual files

app/assets/javascripts/discourse/app/controllers/composer.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/tests/acceptance/composer-test.js, docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md, lib/post_creator.rb, lib/post_revisor.rb, spec/lib/post_creator_spec.rb, spec/lib/post_revisor_spec.rb
This will be used by plugins to handle the client side of their custom post validations without having to overwrite the whole composer save action as it was done in other plugins.
=> FEATURE: API to customize server side composer errors handling in the client side

app/assets/javascripts/discourse/app/initializers/user-tips.js, app/assets/javascripts/discourse/app/models/user.js, app/assets/javascripts/discourse/tests/unit/models/user-test.js, app/services/user_updater.rb, spec/services/user_updater_spec.rb
=> FEATURE: Sync user tips status between client

spec/models/topic_tracking_state_spec.rb
MessageBus sends message only when post number is equal to topic `highest_post_number`
https://github.com/discourse/discourse/blob/main/app/models/topic_tracking_state.rb#L534
Hard-coded value may be a cause for flaky spec.
=> DEV: Avoid hard-coded values in topic tracking state spec

plugins/chat/assets/javascripts/discourse/components/chat-browse-view.js, plugins/chat/assets/javascripts/discourse/templates/components/chat-browse-view.hbs
No test as I don't think it's worth the complexity of a test.
=> UX: ensures browse view input is focused on page load

app/models/tag.rb, lib/discourse_tagging.rb, spec/lib/discourse_tagging_spec.rb
=> FIX: When filtering tags, take into account the groups users are in

config/locales/server.en.yml, config/site_settings.yml, lib/composer_messages_finder.rb
=> UX: Update "education.dominating_topic" and raise default percentage

app/assets/javascripts/discourse/app/components/create-account.js, app/assets/javascripts/discourse/app/templates/components/user-fields/text.hbs, app/assets/javascripts/discourse/app/templates/invites/show.hbs, app/assets/javascripts/discourse/app/templates/modal/create-account.hbs, app/assets/javascripts/discourse/app/templates/password-reset.hbs, app/assets/stylesheets/common/base/login.scss, config/locales/client.en.yml, package.json
This PR adds a login button to the bottom of the admin invite page. This is for users who are wanting to visit the site via the invite link but already have an account. 
I also show the header again, but hide the buttons for an easier way for the user to navigate to the forum's home page.
=> UX: Style adjustments & addition of login button on admin invite page

plugins/chat/db/migrate/20221122070108_save_chat_allowed_groups_site_setting.rb
Follow-up to 0c1e5a76ee0c11c1484d621c6260ff54fa0af63e
=> DEV: Fix chat_allowed_groups migration

plugins/chat/config/locales/server.en.yml, plugins/chat/lib/extensions/user_notifications_extension.rb, plugins/chat/spec/mailers/user_notifications_spec.rb
=> DEV: Make summary subject logic more explicit

plugins/chat/assets/javascripts/discourse/controllers/chat.js, plugins/chat/assets/javascripts/discourse/templates/chat.hbs, plugins/chat/spec/system/sidebars_spec.rb
=> FIX: ensures chat sidebar is present when core sidebar is disabled

plugins/chat/assets/javascripts/discourse/templates/preferences/chat.hbs
=> DEV: removes select-kit deprecation

app/controllers/notifications_controller.rb, spec/requests/notifications_controller_spec.rb
Filter notifications the user cannot see anymore
via guardian.can_see_topic_ids
=> SECURITY: Hide notifications for inaccessible topics

plugins/chat/assets/javascripts/discourse/services/chat-audio-manager.js
=> FIX: prevents audio from playing when appended

script/import_scripts/elgg.rb
I wanted to praise discourse team to make such a beautiful code base and environment to work this import script.
It was a while since I didn't code ruby, and with this folder, it was really easy to get things done, thanks a lot!
I hope this script will help somebody else!
=> Adds elgg import script.

script/import_scripts/xenforo.rb
Added features:
- migrate view count for topics
- create permalinks for categories and topics
- import private messages
- import likes
- import avatars
Fixes:
- frozen string literal error
- import all attachments instead of embedded ones
- fix list regexes
- make expressions non-greedy
=> Xenforo importer improvements

plugins/chat/assets/stylesheets/common/common.scss
=> FIX: ensures date/time don't linebreak

Gemfile, script/bulk_import/base.rb, script/bulk_import/vbulletin.rb, script/import_scripts/vbulletin.rb
Small fixes after a vBulletin v4.2.4 migration
=> Fixes for vBulletin bulk importer

plugins/chat/assets/stylesheets/common/chat-index.scss, plugins/chat/assets/stylesheets/common/common.scss
=> UX: chat index UX fixes

plugins/chat/test/javascripts/acceptance/chat-composer-test.js, plugins/chat/test/javascripts/acceptance/composer-hashtag-autocomplete-test.js
=> DEV: skip breaking tests

app/assets/javascripts/discourse/app/templates/components/edit-category-settings.hbs, config/locales/client.en.yml
=> UX: Add instructions for multiple category emails

plugins/chat/assets/stylesheets/common/common.scss
=> FIX: do not apply hover state to non capable devices

app/models/application_request.rb, app/models/concerns/reports/consolidated_api_requests.rb, app/models/report.rb, config/locales/server.en.yml, lib/middleware/request_tracker.rb, spec/integration/request_tracker_spec.rb, spec/lib/middleware/request_tracker_spec.rb, spec/models/report_spec.rb
There are statistics for regular page views already, but none for API and user API requests.
=> FEATURE: Track API and user API requests

app/mailers/user_notifications.rb, spec/mailers/user_notifications_spec.rb
=> SECURITY: Filter tags in user notifications for visibility

app/mailers/user_notifications.rb, app/models/tag.rb, lib/discourse_tagging.rb, spec/components/discourse_tagging_spec.rb, spec/mailers/user_notifications_spec.rb
=> SECURITY: Filter tags in user notifications for visibility (stable)

lib/version.rb
=> Version bump to v2.8.13

lib/post_destroyer.rb, spec/models/reviewable_flagged_post_spec.rb
=> FIX: Don't notify of post deletion when agreeing with automatic flags.

app/assets/javascripts/admin/addon/controllers/admin-web-hooks-show-events.js, app/assets/javascripts/admin/addon/controllers/modals/admin-merge-users-progress.js, app/assets/javascripts/admin/addon/routes/admin-backups-index.js, app/assets/javascripts/admin/addon/routes/admin-backups.js, app/assets/javascripts/discourse/app/components/basic-topic-list.js, app/assets/javascripts/discourse/app/components/software-update-prompt.js, app/assets/javascripts/discourse/app/components/topic-list-item.js, app/assets/javascripts/discourse/app/controllers/topic.js, app/assets/javascripts/discourse/app/initializers/banner.js, app/assets/javascripts/discourse/app/initializers/live-development.js, app/assets/javascripts/discourse/app/initializers/logout.js, app/assets/javascripts/discourse/app/initializers/read-only.js, app/assets/javascripts/discourse/app/initializers/welcome-topic-banner.js, app/assets/javascripts/discourse/app/models/topic-tracking-state.js, app/assets/javascripts/discourse/app/pre-initializers/inject-discourse-objects.js, app/assets/javascripts/discourse/app/routes/review-index.js, app/assets/javascripts/discourse/app/routes/user.js, app/assets/javascripts/discourse/app/services/logs-notice.js, app/assets/javascripts/discourse/app/services/pm-topic-tracking-state.js, plugins/discourse-narrative-bot/assets/javascripts/initializers/new-user-narrative.js, plugins/poll/assets/javascripts/initializers/extend-for-poll.js
1. "What goes up must come down" – if you subscribe to message bus, make sure you also unsubscribe
2. And when you do unsubscribe - remove only your subscription, not **all** subscriptions on given channel
=> DEV: Clean up all message bus subscriptions

app/assets/javascripts/admin/addon/controllers/admin-web-hooks-show-events.js, app/assets/javascripts/admin/addon/controllers/modals/admin-merge-users-progress.js, app/assets/javascripts/admin/addon/routes/admin-backups-index.js, app/assets/javascripts/admin/addon/routes/admin-backups.js, app/assets/javascripts/discourse/app/components/basic-topic-list.js, app/assets/javascripts/discourse/app/components/software-update-prompt.js, app/assets/javascripts/discourse/app/components/topic-list-item.js, app/assets/javascripts/discourse/app/controllers/topic.js, app/assets/javascripts/discourse/app/initializers/banner.js, app/assets/javascripts/discourse/app/initializers/live-development.js, app/assets/javascripts/discourse/app/initializers/logout.js, app/assets/javascripts/discourse/app/initializers/read-only.js, app/assets/javascripts/discourse/app/initializers/welcome-topic-banner.js, app/assets/javascripts/discourse/app/models/topic-tracking-state.js, app/assets/javascripts/discourse/app/pre-initializers/inject-discourse-objects.js, app/assets/javascripts/discourse/app/routes/review-index.js, app/assets/javascripts/discourse/app/routes/user.js, app/assets/javascripts/discourse/app/services/logs-notice.js, app/assets/javascripts/discourse/app/services/pm-topic-tracking-state.js, plugins/discourse-narrative-bot/assets/javascripts/initializers/new-user-narrative.js, plugins/poll/assets/javascripts/initializers/extend-for-poll.js
This reverts commit b0839ccf27217d9a2be6866a6ac7e824d5104474.
=> Revert "DEV: Clean up all message bus subscriptions (#18675)"

app/controllers/email_controller.rb, app/views/email/unsubscribe.html.erb, config/locales/server.en.yml, spec/requests/email_controller_spec.rb
=> FIX: Validate unsubscribe key has an associated user

app/models/theme.rb, app/models/theme_field.rb
=> DEV: Add link rel preload to theme-javascripts

config/locales/server.en.yml, lib/guardian/topic_guardian.rb, lib/topic_creator.rb, spec/lib/guardian/topic_guardian_spec.rb, spec/lib/topic_creator_spec.rb, spec/requests/posts_controller_spec.rb
=> SECURITY: Restrict unlisted topic creation

plugins/chat/assets/stylesheets/common/chat-channel-title.scss, plugins/chat/assets/stylesheets/common/chat-drawer.scss, plugins/chat/assets/stylesheets/common/chat-index.scss, plugins/chat/assets/stylesheets/common/common.scss, plugins/chat/assets/stylesheets/desktop/chat-channel-title.scss, plugins/chat/assets/stylesheets/desktop/chat-index-drawer.scss, plugins/chat/assets/stylesheets/desktop/chat-index-full-page.scss, plugins/chat/assets/stylesheets/desktop/desktop.scss, plugins/chat/assets/stylesheets/mobile/chat-index.scss, plugins/chat/assets/stylesheets/mobile/mobile.scss, plugins/chat/plugin.rb
Before refactor:
After refactor:
If you don't see any differences between the images, that's the point, but y'know, protocol to show a before/after ;)
=> UX: chat index refactor

plugins/chat/assets/javascripts/discourse/components/chat-message.js, plugins/chat/test/javascripts/acceptance/chat-test.js
=> UX: removes silence from chat message actions

app/assets/javascripts/discourse/app/controllers/user-private-messages.js
I'm working on the controller in another PR and would like to separate this refactor out into its own commit.
=> DEV: Port `user-private-messages` controller to native class

config/locales/client.en.yml
=> UX: add target to start discussion link

plugins/chat/assets/javascripts/discourse/components/chat-channel-metadata.js, plugins/chat/assets/javascripts/discourse/services/chat.js, plugins/chat/test/javascripts/components/chat-channel-metadata-test.js, plugins/chat/test/javascripts/unit/services/chat-test.js
=> FIX: ensures chat channel metadata date is updated

app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs, app/assets/javascripts/discourse/app/components/topic-timeline/container.js
=> DEV: htmlSafe timeline topic title

app/models/topic.rb, spec/models/topic_spec.rb
Previously we would trigger the event before the `Topic#deleted_at`
column has been updated making it hard for plugins to correctly work
with the model when its new state has not been persisted in the
database.
=> DEV: Correct order of triggering topic trashed and recovered event

plugins/chat/assets/javascripts/discourse/services/chat-audio-manager.js
=> FIX: uses CDN when available for chat mp3 sounds

config/locales/server.en.yml
=> DEV: Update inappropriate flag text

app/assets/javascripts/discourse/app/models/post-stream.js, app/assets/javascripts/discourse/app/widgets/post-cooked.js
Repro for the bug:
1. Add a post with a mention of a user
2. Post another post below
3. Delete the first post with a mention
4. Reload the page and try to attempt to view hidden reply
=> FIX: error when opening a previously deleted post

app/models/topic.rb, spec/models/topic_spec.rb
When finding the candidates for `Topic.similar_to`, we will now ignore
topics in categories where `Category#search_priority` has been set to
ignore and also topics in categories which the user has specifically
muted.
Internal Ref: /t/87132
=> UX: Exclude search ignored and user muted categories in similarity search

app/assets/javascripts/discourse-plugins/colocated-template-compiler.js, app/assets/javascripts/discourse-plugins/index.js, lib/theme_javascript_compiler.rb, spec/lib/theme_javascript_compiler_spec.rb
=> DEV: Support colocation under `/admin` namespace in themes/plugins

spec/system/hashtag_autocomplete_spec.rb
These are timing out and I don't have time to check why right now, skipping so the build doesn't keep failing.
=> DEV: Skip hashtag system specs for now

config/locales/server.en.yml
Followup to de080723b5c70b1828977f6dc34aad38f51a48c8
=> FIX: Add translation for setting

app/assets/javascripts/admin/addon/templates/customize-themes-show.hbs, spec/system/admin_customize_themes_spec.rb
Follow-up to 63119144ff481b1a18b69c0d638ece1b03c54766
=> DEV: Add system test for updating color scheme of a theme

app/assets/javascripts/admin/addon/routes/admin-web-hooks-show.js
In the meantime, before #19360 lands.
=> FIX: Admin webhook regression in 321b14d

app/assets/javascripts/admin/addon/components/admin-penalty-similar-users.js, app/assets/javascripts/admin/addon/controllers/modals/admin-silence-user.js, app/assets/javascripts/admin/addon/controllers/modals/admin-suspend-user.js, app/assets/javascripts/admin/addon/templates/components/admin-penalty-similar-users.hbs, app/assets/javascripts/admin/addon/templates/modal/admin-silence-user.hbs, app/assets/javascripts/admin/addon/templates/modal/admin-suspend-user.hbs, app/assets/stylesheets/common/admin/admin_base.scss, app/assets/stylesheets/common/admin/penalty.scss, app/controllers/admin/users_controller.rb, app/serializers/admin_detailed_user_serializer.rb, app/serializers/similar_admin_user_serializer.rb, config/locales/client.en.yml, spec/requests/admin/users_controller_spec.rb
Moderators will be notified if other users with the same IP address exist before penalizing a user.
=> FEATURE: Show similar users when penalizing a user

app/assets/stylesheets/wizard.scss
=> FIX: Remove negative margin on wizard preview

.github/workflows/tests.yml, spec/system/hashtag_autocomplete_spec.rb
=> DEV: Re-enable hashtag system specs

spec/rails_helper.rb
Will make your test run in an emulated iPhone 12 Pro view. It means you can now use `click(delay: 0.5)` to emulate some long press or that `mobile_view=1` will be set automatically.
Usage:
```
it "works", mobile: true do
visit("/")
end
```
Note: `window-size=390,950` is different than native iPhone 12 Pro size, but due to minimum browser size and the automated browser alert at the top of the view, this was the best size I could find.
=> DEV: adds native support for mobile in system tests

app/assets/javascripts/discourse/app/components/suggested-topics.js, app/assets/javascripts/discourse/app/helpers/category-link.js, app/assets/javascripts/discourse/app/routes/discovery-categories.js, app/assets/javascripts/discourse/app/routes/discovery.js, app/assets/javascripts/discourse/tests/unit/lib/category-badge-test.js
And in helpers, use `helperContext().site`
=> DEV: Prefer `site` injection over import

app/assets/javascripts/discourse/app/mixins/uppy-s3-multipart.js
=> FIX: Multipart uppy upload regression in 80e422c

app/assets/stylesheets/wizard.scss, config/locales/server.en.yml, lib/wizard/builder.rb, lib/wizard/step_updater.rb, spec/lib/wizard/step_updater_spec.rb, spec/lib/wizard/wizard_builder_spec.rb
- Fix css alignment
- Add Enable Chat Toggle
- Add Enable Sidebar Toggle
=> FEATURE: Add chat and sidebar toggles to the setup wizard

db/post_migrate/20221212234948_drop_topic_allowed_users_backup_nov_2022.rb
Follow up a414520742da8dc9dc976d4fb7b72dbd445813bb
=> DEV: Delete tmp table from migration for invites

plugins/chat/assets/javascripts/discourse/components/chat-live-pane.js
c.f. 7d7551adfcee90f61297d261742338b8bfe72255
=> DEV: Fix resolvedTimezone deprecation in chat-live-pane

app/assets/stylesheets/common/base/_topic-list.scss
\*in Dora's voice\* Can YOU spot the missing ellipsis?
=> FIX: GitHub onebox ellipsis styling regressed in 9d03f20

config/locales/client.en.yml
@discourse-translator-bot keep_translations_and_approvals
=> REFACTOR: Update Message Format strings to make them easier to read on Crowdin

app/controllers/static_controller.rb, app/controllers/user_avatars_controller.rb, app/models/theme.rb, spec/integrity/i18n_spec.rb, spec/models/reviewable_score_spec.rb, spec/requests/user_avatars_controller_spec.rb
=> DEV: Compatibility with Ruby 3.2

plugins/chat/app/models/chat_message.rb, plugins/chat/spec/components/chat_message_updater_spec.rb
There is no need to duplicate check chat messages when they are being
edited but not having their message text changed. This was leading to
a validation error when adding/removing an upload but not changing the
message text.
=> FIX: Do not duplicate check when editing chat message to remove uploads

app/assets/stylesheets/common/foundation/variables.scss
Simple lighter box shadow variable added
=> UX: add new boxshadow variation

plugins/lazy-yt/config/locales/server.en.yml, plugins/lazy-yt/config/settings.yml, plugins/lazy-yt/plugin.rb
=> DEV: Add hidden option to disable the lazy-yt plugin

spec/lib/distributed_mutex_spec.rb
otherwise they take a looong time
=> DEV: Fake sleeping in distributed mutex tests

app/assets/javascripts/discourse-common/addon/lib/icon-library.js, plugins/styleguide/assets/javascripts/discourse/components/styleguide-icons.js, plugins/styleguide/assets/stylesheets/styleguide.scss
=> FIX: Add REPLACEMENTS icons to styleguide

app/assets/javascripts/discourse/app/components/uppy-image-uploader.js, app/assets/javascripts/discourse/app/templates/components/uppy-image-uploader.hbs
=> UX: Add tooltip why file upload is disabled

spec/rails_helper.rb, spec/support/system_helpers.rb, spec/system/page_objects/components/base.rb, spec/system/page_objects/components/composer.rb, spec/system/page_objects/components/topic_list.rb
For use in https://github.com/discourse/discourse-post-voting/pull/132
=> DEV: Add helpers for system testing in plugins

app/assets/javascripts/discourse/app/widgets/post-small-action.js, app/assets/javascripts/discourse/tests/integration/components/widgets/post-small-action-test.js
Follow-up to f77660b047f77809e86de0d1f22e546e36f3ce6c
=> DEV: Add missing test case

app/models/notification.rb, spec/requests/api/schemas/json/site_response.json
Add information about discourse-follow notification types to Core
https://github.com/discourse/discourse-follow/blob/main/plugin.rb#L32
=> FIX: discourse-follow notification types

plugins/chat/assets/stylesheets/common/common.scss
=> FIX: box-sizing for avatars

spec/models/group_spec.rb
since plugins can have fixtures
=> FIX: Don't assume a clean slate in tests

spec/services/hashtag_autocomplete_service_spec.rb
Not sure why this is flaky, either way it doesn't really add anything so removing it.
=> DEV: Remove flaky hashtag test

.licensed.yml, Gemfile, Gemfile.lock, plugins/chat/spec/requests/chat_controller_spec.rb
fixes chat specs with ruby 3.1
=> DEV: Ruby 3.1 compat

spec/fabricators/user_fabricator.rb
=> DEV: Remove fabrication hack

plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js, plugins/chat/spec/system/list_channels/mobile_spec.rb, plugins/chat/spec/system/list_channels/no_sidebar_spec.rb, plugins/chat/spec/system/list_channels/sidebar_spec.rb
=> FIX: correctly sorts public channels

.github/workflows/licenses.yml, .github/workflows/linting.yml, .github/workflows/tests.yml
Followup to 7eb9482ba94f5eac0dc89ad5f5ed6cf4eab92727
=> DEV: Correct private-fork -> private-mirror

plugins/chat/assets/javascripts/discourse/connectors/user-preferences-nav/preferences-chat-link.hbs, plugins/chat/assets/javascripts/discourse/routes/preferences-chat.js, plugins/chat/spec/system/user_chat_preferences_spec.rb
=> FIX: allows an admin to access users preferences

lib/plugin/instance.rb
=> DEV: Pass kwargs to defined method

plugins/chat/assets/javascripts/discourse/components/chat-live-pane.js, plugins/chat/assets/javascripts/discourse/models/user-chat-channel-membership.js, plugins/chat/assets/javascripts/discourse/services/chat-subscriptions-manager.js, plugins/chat/spec/system/chat_channel_spec.rb, plugins/chat/spec/system/create_channel_spec.rb, plugins/chat/spec/system/edited_message_spec.rb, plugins/chat/spec/system/message_notifications_mobile_spec.rb, plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb, plugins/chat/spec/system/replying_indicator_spec.rb, plugins/chat/spec/system/unfollow_dm_channel_spec.rb
This commit also adds a system to correctly track this case.
=> FIX: corrects a regression with last_read_message_id

plugins/chat/assets/javascripts/discourse/services/chat-message-visibility-observer.js, plugins/chat/assets/javascripts/discourse/services/chat-subscriptions-manager.js, plugins/chat/assets/javascripts/discourse/services/chat.js
=> FIX: triggers update last read when message is not staged

plugins/chat/assets/javascripts/discourse/initializers/chat-audio.js
I couldn't figure a sane way to test this, I'm open to suggestions.
=> FIX: prevents playing chat sound when in DnD

plugins/chat/assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js, plugins/chat/spec/system/channel_members_page_spec.rb, plugins/chat/spec/system/channel_selector_modal_spec.rb, plugins/chat/spec/system/edited_message_spec.rb, plugins/chat/spec/system/message_notifications_mobile_spec.rb, plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb, plugins/chat/spec/system/replying_indicator_spec.rb, plugins/chat/spec/system/unfollow_dm_channel_spec.rb, plugins/chat/spec/system/user_menu_notifications/sidebar_spec.rb
=> FIX: re-enables using_session tests

app/assets/stylesheets/wizard.scss, config/locales/server.en.yml
* Tell us about your community -> About your site
* Community logo -> Site logo
* When there are no logos uploaded, stack the logo fields instead of side by side
* Tweaks on medium sized screen
=> UX: Setup wizard copy changes and vertically stack logo fields

plugins/chat/spec/system/page_objects/chat/chat_channel.rb
=> DEV: more reliable send message helper

.github/workflows/licenses.yml, .licensed.yml
1. Add `cgi` (ruby terms)
2. Move `strscan`, ~~`ruby2_keywords`, and `openssl`~~ to "reviewed" section (update: two of those are postponed, need to debug stuff in our docker image)
3. Sort
=> DEV: Update bundler `licensed` config

package.json
=> DEV: Move `eslint-config-discourse` to `devDependencies`

plugins/chat/assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
=> FIX: at this point in time component can be destroyed

Gemfile.lock
=> DEV: Update bundler to 2.4.1

plugins/chat/spec/system/archive_channel_spec.rb, plugins/chat/spec/system/channel_members_page_spec.rb, plugins/chat/spec/system/jit_messages_spec.rb, plugins/chat/spec/system/message_notifications_mobile_spec.rb, plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb, plugins/chat/spec/system/user_menu_notifications/sidebar_spec.rb, plugins/chat/spec/system/user_status/sidebar_spec.rb
=> DEV: attempts to move all Jobs.run_immediately! at top

app/serializers/site_serializer.rb, spec/serializers/site_serializer_spec.rb
Refactor whispers_allowed_groups_names to avoid small N+1
=> DEV: Refactor whispers_allowed_groups_names

plugins/chat/spec/system/jit_messages_spec.rb
=> DEV: slightly increase wait to avoid flakey tests

app/controllers/users_controller.rb, spec/requests/users_controller_spec.rb
Co-authored-by: Penar Musaraj <pmusaraj@gmail.com>
=> SECURITY: Don't expose user post counts to users who can't see the topic

app/assets/javascripts/discourse/app/lib/render-tag.js
=> SECURITY: escape quotes in tag description when rendering

lib/validators/stripped_length_validator.rb, spec/requests/posts_controller_spec.rb
=> SECURITY: Check the length of raw post body

app/models/user_email.rb, spec/requests/users_controller_spec.rb, spec/requests/users_email_controller_spec.rb
=> SECURITY: Delete email tokens when a user's email is changed or deleted

app/assets/javascripts/admin/addon/models/email-preview.js, config/routes.rb, spec/requests/admin/email_controller_spec.rb
=> SECURITY: Convert send_digest to a post request

.github/workflows/tests.yml
=> DEV: Use ruby-2.7 for stable branch CI

app/assets/javascripts/discourse/app/routes/user-activity-pending.js
=> SECURITY: Sanitize PendingPost titles before rendering to prevent XSS

lib/version.rb
=> Version bump to v2.8.14

script/import_scripts/xenforo.rb
=> DEV: Fix syntax/formatting in xenforo import script

lib/middleware/request_tracker.rb, spec/lib/middleware/request_tracker_spec.rb
=> DEV: Include message-bus request type in HTTP request data

app/assets/stylesheets/common/admin/emails.scss
=> UX: improve readability for admin email modal

app/jobs/scheduled/check_out_of_date_themes.rb, lib/discourse.rb
=> FIX: Continue if checking themes if updating one fails

.editorconfig
=> DEV: Update .editorconfig to match new hbs rules

app/models/topic_tracking_state.rb, spec/models/topic_tracking_state_spec.rb
When a topic belongs to category that is read restricted but permission
has not been granted to any groups, publishing ceratin topic tracking state
updates for the topic will result in the `MessageBus::InvalidMessageTarget` error being raised
because we're passing `nil` to `group_ids` which is not support by
MessageBus.
This commit ensures that for said category above, we will publish the
updates to the admin groups.
=> FIX: Error when publishing TopicTrackingState updates for certain topics

lib/version.rb
=> Version bump to v3.1.0.beta1

plugins/chat/app/controllers/incoming_chat_webhooks_controller.rb
I inspected the JSON payload from OpsGenie and added a
note to show what it can look like.
=> DEV: Remove old TODO for chat webhooks

config/application.rb
=> Bump minimum Ruby version to 3.1

app/models/top_topic.rb
=> FIX: Prevent concurrent updates to top_topics

.github/workflows/tests.yml
Does this makes sense for you @CvX ?
=> DEV: Key bundler CI cache on Ruby version

app/assets/javascripts/select-kit/addon/templates/components/email-group-user-chooser-row.hbs
=> UX: fix alignment issues with autocomplete

app/controllers/webhooks_controller.rb, config/locales/server.en.yml, config/site_settings.yml, spec/requests/webhooks_controller_spec.rb
=> FEATURE: Verify email webhook signatures

app/assets/stylesheets/common/base/onebox.scss, app/assets/stylesheets/common/base/tagging.scss
Followup to 1ce9582a6c3d85201d8a3eec26a2a9c3be887311
=> UX: Refactor alignment of tag icon in Discourse onebox

app/assets/stylesheets/common/base/search-menu.scss
=> UX: Add margin to search keyword

app/assets/stylesheets/common/base/compose.scss
=> UX: Remove left margin

app/assets/javascripts/admin/addon/templates/modal/admin-penalize-user.hbs, app/assets/stylesheets/common/admin/penalty.scss
=> UX: Set penalty history to sticky

app/assets/stylesheets/common/base/compose.scss
=> FIX: Fix margin on mini-tag-chooser

Gemfile, Gemfile.lock
=> SECURITY: Bump Rails to v7.0.4.1

app/models/api_key_scope.rb, config/locales/client.en.yml, spec/requests/admin/api_controller_spec.rb
Adds an api scope for the POST /invite endpoint.
=> FEATURE: Add api scope for create invite endpoint

app/models/api_key_scope.rb, config/locales/client.en.yml
See: https://meta.discourse.org/t/request-separate-api-granular-api-scope-for-suspend-user/249928/5
=> FEATURE: Add api scope for suspending users

app/assets/javascripts/discourse/tests/acceptance/composer-test.js, app/controllers/uploads_controller.rb, plugins/chat/spec/system/navigating_to_message_spec.rb, plugins/chat/spec/system/shortcuts/chat_composer_spec.rb, plugins/chat/spec/system/shortcuts/sidebar_spec.rb
=> DEV: Fix random typos

plugins/lazy-yt/plugin.rb
=> FIX: lazy_yt_enabled doesn't affect the engine

lib/mobile_detection.rb
=> SECURITY: Prevent ReDoS in user agent parsing

app/controllers/tags_controller.rb, spec/requests/tags_controller_spec.rb
=> SECURITY: only show restricted tag lists to authorized users

db/post_migrate/20230105153520_trigger_post_rebake_local_onebox_xss.rb, lib/oneboxer.rb, spec/lib/oneboxer_spec.rb
=> SECURITY: Prevent XSS in local oneboxes

lib/version.rb
=> Version bump to v3.1.0.beta2

lib/version.rb
=> Version bump to v3.0.1

app/assets/javascripts/discourse/app/lib/user-search.js, app/assets/javascripts/discourse/tests/unit/lib/user-search-test.js
=> FIX: Use specified limit option in user search

config/locales/client.en.yml
=> UX: Add staff action log text for permanently_delete_post_revisions

app/models/optimized_image.rb
=> DEV: Include upload_id on image optimization errors to have more context

app/models/optimized_image.rb
=> DEV: Fix ruby syntax tree linting error

plugins/discourse-narrative-bot/config/locales/server.en.yml
As reported on https://meta.discourse.org/t/253028, the linked site includes
language which we do not support.
=> FIX: remove link to site with inappropriate content

app/models/topic.rb, spec/lib/email/receiver_spec.rb, spec/models/topic_spec.rb
This reverts commit 88a972c61b0dec3ffe48bb7a37daeac74fa16ec6.
It's actually used in some plugins.
=> Revert "DEV: Delete dead Topic#incoming_email_addresses code (#19970)"

app/models/user_status.rb, spec/requests/user_status_controller_spec.rb
=> FIX: Limit user status to 100 characters

app/assets/stylesheets/common/select-kit/select-kit.scss
This reverts commit 853439104438d3f45377c636a251627f35e75222.
=> Revert "Select-kit > use new color vars"

app/assets/javascripts/discourse/app/templates/components/user-status-picker.hbs, app/models/user_status.rb, db/migrate/20230127173249_truncate_user_status_to_100_characters.rb, spec/requests/user_status_controller_spec.rb, spec/requests/users_controller_spec.rb
Follow up to commit b6f75e231cb49455908c980e0549290828c2162f.
=> FIX: Truncate existing user status to 100 chars

app/assets/javascripts/discourse/app/mixins/card-contents-base.js, app/assets/stylesheets/common/components/user-card.scss, app/assets/stylesheets/desktop/components/user-card.scss, app/assets/stylesheets/mobile/components/user-card.scss
Behavior should be very similar but the code is simplified and it should fix various bugs where the card was showing out of screen even if we had available space.
=> DEV: uses popperjs for positioning user and group card

spec/requests/user_status_controller_spec.rb
This test appears to be flaky. This assertion should help us track down the reason.
=> DEV: Update user-status test to assert message-bus channels

spec/requests/tags_controller_spec.rb
=> DEV: skip spec failing on CI

spec/system/page_objects/pages/search.rb, spec/system/search_spec.rb
=> DEV: attempts to fix flakey spec

app/assets/javascripts/discourse/tests/unit/services/presence-test.js
=> DEV: Convert presence service tests to actual unit tests

config/site_settings.yml, lib/search.rb, spec/lib/search_spec.rb
This site setting is mostly experimental at this point.
=> DEV: Add hidden site setting to configure search ranking weights

script/import_scripts/base/generic_database.rb, script/import_scripts/yammer.rb
Supersedes https://github.com/discourse/discourse/pull/17651
The original PR was already reviewed by me (it's good enough), so this should be rather easy to review. :wink: 
Rebased, fixed conflicts and formatted with stree
=> DEV: Add import script for Yammer

plugins/chat/assets/javascripts/discourse/components/chat-header-icon.hbs, plugins/chat/assets/javascripts/discourse/components/chat-header-icon.js
=> UX: brings back URL on chat icon when in full page

spec/system/search_spec.rb
=> DEV: skip failing spec

app/assets/stylesheets/desktop/discourse.scss
Globally fixing stacked controls in horizontal-forms
=> UX: flex horizontal form controls

config/locales/server.en.yml, config/site_settings.yml, lib/validators/search_ranking_weights_validator.rb, spec/lib/validators/search_ranking_weights_validator_spec.rb
Follow-up to 6934edd97cfdc855d5882e85415b33f573db120c
=> DEV: Add validator for search_ranking_weights site setting

config/locales/server.en.yml
=> FIX: Update flag URL in auto silence PM to moderators

app/assets/javascripts/discourse/app/controllers/full-page-search.js, app/assets/javascripts/discourse/app/templates/full-page-search.hbs, app/assets/stylesheets/common/base/search.scss, app/controllers/search_controller.rb, config/site_settings.yml, db/migrate/20230104054425_rename_rate_limit_search_anon.rb, db/post_migrate/20230104054426_delete_old_rate_limit_search_anon.rb, spec/requests/search_controller_spec.rb, spec/system/page_objects/pages/search.rb, spec/system/search_spec.rb
=> FEATURE: rate limit anon searches per second

app/assets/javascripts/discourse/app/templates/components/badge-card.hbs
Customer requested plugin outlet addition
=> DEV: add plugin outlet to badge-card

spec/requests/search_controller_spec.rb
No easy repro locally for me, but ran the change here a few times in CI, and got all green. Let's give it a shot.
=> DEV: Fix flakey search spec

plugins/chat/spec/requests/chat_controller_spec.rb
=> DEV: fixes failing spec

app/controllers/admin/backups_controller.rb
Follow-up to 008b700a3f24fdbb0feb9897321b61a3deabe0e2
=> FIX: Redirecting to download backup from S3 could fail

app/models/concerns/trashable.rb, spec/lib/trashable_spec.rb
=> DEV: Added .only_deleted scope in the Trashable module

plugins/chat/assets/stylesheets/common/chat-message.scss
=> FIX: changed classname for YT images

spec/system/admin_customize_form_templates_spec.rb
Assigning myself to a TODO I added previously for easier tracking.
=> DEV: Assign TODO to `@keegan`

app/assets/javascripts/discourse/app/components/user-status-message.js, app/assets/javascripts/discourse/app/controllers/preferences/interface.js, app/assets/javascripts/discourse/app/models/user.js, app/assets/javascripts/discourse/tests/acceptance/mobile-topic-bulk-actions-test.js, app/assets/javascripts/discourse/tests/acceptance/user-card-test.js, app/assets/javascripts/discourse/tests/acceptance/user-status-test.js, app/assets/javascripts/discourse/tests/fixtures/user-fixtures.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/topic-notifications-button-test.js
=> DEV: Resolve user_option deprecations

app/assets/javascripts/discourse/app/templates/preferences-second-factor.hbs, app/assets/stylesheets/desktop/discourse.scss
=> UX: add flex alignment for form actions

plugins/chat/app/services/update_user_last_read.rb, plugins/chat/spec/services/update_user_last_read_spec.rb
We’re now using `contract` as the first step and validations for mandatory parameters have been added.
To simplify specs a bit, we only assert the service contract is run as expected without testing each validation case. We’re now testing the contract itself in isolation.
=> DEV: Refactor `UpdateUserLastRead` a little

app/assets/javascripts/admin/addon/components/version-checks.hbs
=> DEV: Add a plugin outlet for admin upgrade-header

app/assets/javascripts/discourse/app/initializers/colocated-template-overrides.js, app/assets/javascripts/discourse/tests/integration/template-override-test.js
Long-term, we may aim to remove the ability to have mobile-specific component templates. But for now, this commit will allow us to colocate a component's template, while keeping the mobile-specific-override functionality for core, plugins and themes.
=> DEV: Support mobile-specific template overrides of colocated components

plugins/chat/assets/javascripts/discourse/components/chat-message-actions-desktop.hbs, plugins/chat/assets/javascripts/discourse/components/chat-message-actions-desktop.js, plugins/chat/assets/javascripts/discourse/components/chat-message-actions-mobile.hbs, plugins/chat/assets/javascripts/discourse/components/chat-message-actions-mobile.js
These are fairly small components, so we can change to using
glimmer without too much trouble.
=> DEV: Glimmerize ChatMessageActionsDesktop/Mobile components

app/assets/stylesheets/common/base/discourse.scss, app/assets/stylesheets/common/components/footer-nav.scss, plugins/chat/assets/stylesheets/common/common.scss, plugins/chat/assets/stylesheets/mobile/mobile.scss
This code also removes duplicated code in chat which doesn’t seem necessary anymore.
=> FIX: correctly account for ipad footer nav height

plugins/chat/assets/javascripts/discourse/components/chat-message-info.hbs, plugins/chat/assets/javascripts/discourse/components/chat-message-info.js, plugins/chat/test/javascripts/components/chat-message-info-test.js
This commit also refactors `chat-message-info` to use glimmer.
=> DEV: adds is-new-user and primary group class

app/assets/stylesheets/common/base/menu-panel.scss, plugins/chat/assets/stylesheets/common/direct-message-creator.scss, plugins/chat/assets/stylesheets/mobile/chat-index.scss
Adding ellipsis at various places where the userstatus is shown.
=> UX: userstatus limit handling in UI

plugins/chat/assets/javascripts/discourse/components/chat-channel-members-view.hbs, plugins/chat/assets/javascripts/discourse/components/chat-user-info.hbs, plugins/chat/assets/javascripts/discourse/components/chat-user-info.js, plugins/chat/assets/stylesheets/common/chat-channel-info.scss, plugins/chat/test/javascripts/components/chat-user-info-test.js
Clicking outside the avatar or the username does nothing now, so I removed the hover effect.
<div align="center">
<h3>Before / After</h3>
</div>
=> FIX: Chat member user card rendered out of view

app/assets/javascripts/admin/addon/controllers/admin-plugins.js, app/assets/javascripts/admin/addon/templates/plugins.hbs, app/assets/javascripts/discourse/tests/acceptance/admin-plugins-test.js, app/assets/stylesheets/common/admin/admin_base.scss, app/assets/stylesheets/common/components/horizontal-overflow-nav.scss, config/locales/client.en.yml
This eliminates another legacy sidebar nav and moves it to the new horizontal overflow nav component. 
Before:
After:
=> UX: move vertical admin plugin nav to horizontal overflow nav

plugins/chat/assets/stylesheets/common/chat-index.scss
=> UX: contains overscroll in channels list

.licensed.yml
=> DEV: Add `digest` to licensed's default gems list

plugins/chat/assets/javascripts/discourse/components/chat-composer.js
=> FIX: Wrong interpolation key

plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/02-buttons.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/05-input-fields.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/date-time-inputs.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/dropdowns.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/char-counter.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/empty-state.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/footer-message.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/navigation-bar.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/rich-tooltip.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/signup-cta.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/topic-list-item.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/topic-notifications.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/molecules/topic-timer-info.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/organisms/03-topic-footer-buttons.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/organisms/04-topic-list.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/organisms/basic-topic-list.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/organisms/categories-list.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/organisms/modal.hbs, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/organisms/suggested-topics.hbs
=> DEV: Update styleguide example titles to use angle-bracket naming

plugins/chat/assets/stylesheets/common/chat-skeleton.scss
=> UX: apply animation on content only

app/assets/stylesheets/common/admin/admin_base.scss, app/assets/stylesheets/common/admin/admin_report.scss, app/assets/stylesheets/common/admin/customize.scss, app/assets/stylesheets/common/admin/settings.scss, app/assets/stylesheets/common/base/alert.scss, app/assets/stylesheets/common/base/compose.scss, app/assets/stylesheets/common/base/directory.scss, app/assets/stylesheets/common/base/header.scss, app/assets/stylesheets/common/base/history.scss, app/assets/stylesheets/common/base/menu-panel.scss, app/assets/stylesheets/common/base/modal.scss, app/assets/stylesheets/common/base/new-user.scss, app/assets/stylesheets/common/base/onebox.scss, app/assets/stylesheets/common/base/popup-menu.scss, app/assets/stylesheets/common/base/search-menu.scss, app/assets/stylesheets/common/base/topic-post.scss, app/assets/stylesheets/common/base/topic.scss, app/assets/stylesheets/common/components/tap-tile.scss, app/assets/stylesheets/common/components/user-stream-item.scss, app/assets/stylesheets/desktop/compose.scss, app/assets/stylesheets/desktop/topic.scss, app/assets/stylesheets/embed.scss, app/assets/stylesheets/mobile/topic-post.scss, app/models/color_scheme.rb, plugins/chat/assets/stylesheets/common/chat-message.scss, plugins/styleguide/assets/javascripts/discourse/templates/styleguide/atoms/03-colors.hbs, plugins/styleguide/assets/stylesheets/colors.scss
1. Replace the old highlight var use cases with the new variables in 3 big components:
* popup menu
* autocomplete
* menu panel
\+ in several smaller occurances
2. Update the sol light theme with a better contrasting variable
=> UX: highlight vars updates

app/assets/stylesheets/common/base/menu-panel.scss
Followup to c82094cd9dbd6160a2e611e6dde915ce4695b32f
=> UX: Restore wider search dropdown width

app/models/post.rb, db/migrate/20230202204937_add_index_to_posts_where_not_deleted_or_empty.rb
=> PERF: Add index to speed up ReindexSearch job

app/models/api_key_scope.rb, config/locales/client.en.yml, spec/requests/admin/api_controller_spec.rb
Added two new api scopes for managing and administering groups.
See https://meta.discourse.org/t/249710
=> FEATURE: Add API scopes for group endpoints

app/models/api_key_scope.rb, config/locales/client.en.yml, spec/requests/admin/api_controller_spec.rb
Adds api scopes for
- deleting a topic
- deleting a post
- listing tags
=> FEATURE: Adding some more api scopes

app/assets/javascripts/admin/addon/components/ace-editor.js, app/assets/javascripts/admin/addon/components/email-styles-editor.hbs, app/assets/javascripts/admin/addon/components/email-styles-editor.js
The save action clashed with the save component argument
Followup to a433b30650d125e6685fb13f679f613003f246aa
=> FIX: Correct issues in admin email-styles-editor

app/assets/javascripts/admin/addon/routes/admin-backups.js, app/assets/javascripts/discourse/app/controllers/login.js, app/assets/javascripts/discourse/app/routes/application.js, app/assets/javascripts/discourse/app/routes/discovery-categories.js, app/assets/javascripts/discourse/app/routes/topic.js
=> DEV: Clean up `showModal()` calls

app/assets/javascripts/discourse/app/pre-initializers/dynamic-route-builders.js, app/assets/javascripts/discourse/config/deprecation-workflow.js
=> DEV: Resolve and unsilence ember string prototype deprecation

app/assets/javascripts/discourse/app/components/d-modal.js
=> DEV: Clean up `d-modal`

plugins/chat/app/services/base.rb, plugins/chat/spec/lib/service_runner_spec.rb
=> DEV: Make the `model` step compatible with collections

Gemfile.lock, lib/email/receiver.rb, lib/topic_query.rb, script/import_scripts/phpbb3/importers/poll_importer.rb
=> DEV: Update syntax_tree to 6.0.1

app/assets/javascripts/admin/package.json, app/assets/javascripts/dialog-holder/package.json, app/assets/javascripts/discourse-common/package.json, app/assets/javascripts/discourse-hbr/package.json, app/assets/javascripts/discourse-js-processor.js, app/assets/javascripts/discourse-plugins/package.json, app/assets/javascripts/discourse-widget-hbs/package.json, app/assets/javascripts/discourse/package.json, app/assets/javascripts/pretty-text/package.json, app/assets/javascripts/select-kit/package.json, app/assets/javascripts/truth-helpers/package.json, app/assets/javascripts/wizard/package.json, app/assets/javascripts/yarn.lock, lib/discourse_js_processor.rb, spec/lib/discourse_js_processor_spec.rb
=> DEV: Update ember-cli-htmlbars to 6.2.0

app/models/api_key_scope.rb
Adding an api scope for `/c/{slug}/{id}.json`. Without this you had to
append `/l/latest` to the url in order for it to work with existing
scopes.
=> FEATURE: Add API scope for listing topics in a category

db/fixtures/006_badges.rb, db/migrate/20230227050147_update_badge_icons.rb, plugins/discourse-narrative-bot/db/fixtures/002_badges.rb, plugins/discourse-narrative-bot/db/migrate/20230227050146_update_narrative_badge_icons.rb
Update icons from font awesome for badge icons.
Before / After
Related: https://meta.discourse.org/t/badges-on-meta/256289
=> UX: Update badge icons

app/assets/javascripts/admin/addon/templates/users-list-show.hbs
=> Add a plugin outlet `admin-users-list-show-before`

app/jobs/regular/notify_reviewable.rb, lib/distributed_mutex.rb
Forcing distributed muted to raise when a notify reviewable job is running
leads to excessive errors in the logs under many conditions.
The new pattern
1. Optimises the counting of reviewables so it is a lot faster
2. Holds the distributed lock for 2 minutes (max)
The downside is the job queue can get blocked up when tons of notify
reviewables are running at the same time. However this should be very
rare in the real world, as we only notify when stuff is flagged which
is fairly infrequent.
This also give a fair bit more time for the notifications which may be
a little slow on large sites with tons of mods.
=> DEV: reduce amount of errors logged when notifying on flags

app/assets/javascripts/discourse/app/models/composer.js, app/assets/javascripts/discourse/tests/unit/models/composer-test.js
=> FIX: Don't set `categoryId` on PM drafts

plugins/chat/assets/javascripts/discourse/connectors/user-preferences-nav/user-nav__preferences-chat.hbs
This adds an icon and span tag to match the core nav, and updates the connector name to match the core class names 
Before:
=> UX: update user chat preference link for new nav

plugins/chat/assets/stylesheets/common/chat-message-separator.scss
=> UX: makes last visit stand out less

plugins/chat/app/services/chat_publisher.rb
=> DEV: removes dead code

plugins/chat/assets/stylesheets/common/chat-message.scss
Remove the opacity in a staged chat message
=> UX: remove visual chat msg staging effect

plugins/chat/assets/javascripts/discourse/components/chat-live-pane.js
On fast networks it could end up in infinite loop until all messages had been loaded.
=> PERF: reduce height of the load more past message area

plugins/chat/assets/javascripts/discourse/components/chat-composer-uploads.js, plugins/chat/assets/javascripts/discourse/components/chat-live-pane.js, plugins/chat/assets/javascripts/discourse/components/chat-message-in-reply-to-indicator.js, plugins/chat/assets/javascripts/discourse/components/chat-message.hbs, plugins/chat/assets/javascripts/discourse/components/full-page-chat.hbs, plugins/chat/assets/javascripts/discourse/routes/chat-channel.js, plugins/chat/assets/javascripts/discourse/templates/chat-channel-near-message.hbs, plugins/chat/assets/javascripts/discourse/templates/chat-channel.hbs, plugins/chat/spec/system/single_thread_spec.rb, plugins/chat/spec/system/transcript_spec.rb
=> PERF: various perf improvements of chat-live-pane

plugins/chat/spec/models/chat_message_spec.rb
Followup to a252022117350829dabd80c463cb8c8984da6548
=> DEV: Fix another chat bookmark spec

plugins/chat/assets/stylesheets/common/chat-message-separator.scss
=> FIX: broken sticky date on firefox

app/assets/javascripts/discourse/app/components/composer-editor.js, app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js, app/models/post.rb, spec/models/post_spec.rb
FEATURE: Generate thumbnail images for uploaded videos
Topics in Discourse have a topic thumbnail feature which allows themes
to show a preview image before viewing the actual Topic.
This PR allows for the ability to generate a thumbnail image from an
uploaded video that can be use for the topic preview.
=> Generate thumbnail images for video uploads

app/assets/javascripts/discourse/app/controllers/avatar-selector.js, app/assets/javascripts/discourse/app/templates/modal/avatar-selector.hbs
=> DEV: Resolve avatar-selector `computed-property.override` deprecation

plugins/chat/assets/javascripts/discourse/components/chat-live-pane.js, plugins/chat/assets/javascripts/discourse/models/chat-message.js, plugins/chat/spec/system/edited_message_spec.rb
=> FIX: ensures edited message is correctly re-decorated

app/assets/javascripts/discourse/app/controllers/exception.js
=> DEV: Resolve `d-button-action-string` deprecation in `exception.hbs`

app/assets/javascripts/discourse/app/controllers/avatar-selector.js
Followup to 4f9afabf877b06c434dc84286fbebd0434a6efc3
https://meta.discourse.org/t/257731
=> FIX: Avatar upload error

app/jobs/regular/user_email.rb, spec/jobs/user_email_spec.rb
=> DEV: Refactor `Jobs::UserEmail` a little

config/locales/server.en.yml
Safe-mode only applies to client-side customizations - let's make that clearer
=> UX: Improve safe-mode copy

app/models/theme.rb, app/models/theme_field.rb, app/models/theme_svg_sprite.rb, db/migrate/20230224193734_create_theme_svg_sprite.rb, db/post_migrate/20230224225129_backfill_svg_sprites.rb, lib/svg_sprite.rb, lib/tasks/svg_sprites.rake, spec/lib/svg_sprite/svg_sprite_spec.rb, spec/models/theme_field_spec.rb, spec/models/theme_svg_sprite_spec.rb
Let's avoid fetching sprites from the CDN during page rendering.
=> DEV: Store theme sprites in the DB

app/assets/javascripts/admin/addon/controllers/modals/admin-add-upload.js, app/assets/javascripts/admin/addon/controllers/modals/admin-badge-preview.js, app/assets/javascripts/admin/addon/controllers/modals/admin-color-scheme-select-base.js, app/assets/javascripts/admin/addon/controllers/modals/admin-delete-posts-confirmation.js, app/assets/javascripts/admin/addon/controllers/modals/admin-delete-user-posts-progress.js, app/assets/javascripts/admin/addon/controllers/modals/admin-edit-badge-groupings.js, app/assets/javascripts/admin/addon/controllers/modals/admin-incoming-email.js, app/assets/javascripts/admin/addon/controllers/modals/admin-install-theme.js, app/assets/javascripts/admin/addon/controllers/modals/admin-merge-users-confirmation.js, app/assets/javascripts/admin/addon/controllers/modals/admin-merge-users-progress.js, app/assets/javascripts/admin/addon/controllers/modals/admin-merge-users-prompt.js, app/assets/javascripts/admin/addon/controllers/modals/admin-penalize-user.js, app/assets/javascripts/admin/addon/controllers/modals/admin-reseed.js, app/assets/javascripts/admin/addon/controllers/modals/admin-staff-action-log-details.js, app/assets/javascripts/admin/addon/controllers/modals/admin-start-backup.js, app/assets/javascripts/admin/addon/controllers/modals/admin-theme-change.js, app/assets/javascripts/admin/addon/controllers/modals/admin-uploaded-image-list.js, app/assets/javascripts/admin/addon/controllers/modals/admin-watched-word-test.js, app/assets/javascripts/admin/addon/controllers/modals/site-setting-default-categories.js
This commit was generated using the ember-native-class-codemod along with a handful of manual updates
=> DEV: Update admin modal controllers to native class syntax

app/controllers/admin/backups_controller.rb, lib/backup_restore/backuper.rb, spec/lib/backup_restore/backuper_spec.rb, spec/requests/admin/backups_controller_spec.rb
=> SECURITY: Rate limit the creation of backups

plugins/chat/spec/mailers/user_notifications_spec.rb
A follow-up to https://github.com/discourse/discourse/pull/20677.
=> DEV: add test cases for email notifications about channel-wide mentions

app/assets/javascripts/discourse/app/components/choose-topic.hbs, app/assets/javascripts/discourse/app/components/composer-action-title.js, app/assets/javascripts/discourse/app/helpers/replace-emoji.js, app/assets/javascripts/discourse/app/templates/modal/insert-hyperlink.hbs, app/assets/javascripts/discourse/app/templates/review-topics.hbs, app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js, app/assets/javascripts/discourse/tests/fixtures/topic.js, app/assets/javascripts/discourse/tests/integration/helpers/replace-emoji-test.js, app/assets/javascripts/select-kit/addon/templates/components/topic-row.hbs, lib/cooked_processor_mixin.rb, lib/final_destination/fast_image.rb, lib/final_destination/ssrf_detector.rb, lib/freedom_patches/web_push_request.rb, plugins/chat/app/models/chat_message.rb, plugins/chat/assets/javascripts/discourse/components/chat-channel-about-view.hbs, plugins/chat/assets/javascripts/discourse/components/chat-channel-card.hbs, plugins/chat/assets/javascripts/discourse/components/chat-channel-title.hbs, plugins/chat/spec/models/chat_message_spec.rb, plugins/chat/spec/system/chat_channel_spec.rb, spec/lib/final_destination/fast_image_spec.rb, spec/lib/final_destination/ssrf_detector_spec.rb, spec/lib/freedom_patches/web_push_spec.rb, spec/services/search_indexer_spec.rb
- SECURITY: Fix XSS in full name composer reply
- SECURITY: Monkey-patch web-push gem to use safer HTTP client
- SECURITY: SSRF protection bypass with IPv4-mapped IPv6 addresses
- SECURITY: XSS on chat excerpts
- FIX: Escaped mentions in chat excerpts
- SECURITY: Add FinalDestination::FastImage that's SSRF safe
=> SECURITY: Multiple commits for Version bump 3.1.0.beta3

Gemfile, Gemfile.lock, app/assets/javascripts/discourse/app/components/composer-action-title.js, app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js, app/assets/javascripts/discourse/tests/fixtures/topic.js, lib/cooked_processor_mixin.rb, lib/final_destination/fast_image.rb, lib/final_destination/ssrf_detector.rb, lib/freedom_patches/web_push_request.rb, spec/lib/final_destination/fast_image_spec.rb, spec/lib/final_destination/ssrf_detector_spec.rb, spec/lib/freedom_patches/web_push_spec.rb, spec/services/search_indexer_spec.rb
Bringing several security commits that are already in main to stable.
=> Security stable bump

app/models/application_request.rb
Using `create_or_find_by!`, followed by `update_all!` requires two or three queries (two when the row doesn't already exist, three when it does). Instead, we can use postgres's native `INSERT ... ON CONFLICT ... DO UPDATE SET` feature to do the logic in a single atomic call.
=> PERF: Use native postgres upsert for ApplicationRequest

app/assets/javascripts/admin/addon/models/admin-dashboard.js, app/assets/javascripts/admin/addon/models/admin-user.js, app/assets/javascripts/admin/addon/models/api-key.js, app/assets/javascripts/admin/addon/models/backup-status.js, app/assets/javascripts/admin/addon/models/backup.js, app/assets/javascripts/admin/addon/models/color-scheme-color.js, app/assets/javascripts/admin/addon/models/color-scheme.js, app/assets/javascripts/admin/addon/models/email-log.js, app/assets/javascripts/admin/addon/models/email-preview.js, app/assets/javascripts/admin/addon/models/email-settings.js, app/assets/javascripts/admin/addon/models/email-style.js, app/assets/javascripts/admin/addon/models/email-template.js, app/assets/javascripts/admin/addon/models/flag-type.js, app/assets/javascripts/admin/addon/models/form-template.js, app/assets/javascripts/admin/addon/models/incoming-email.js, app/assets/javascripts/admin/addon/models/permalink.js, app/assets/javascripts/admin/addon/models/report.js, app/assets/javascripts/admin/addon/models/screened-email.js, app/assets/javascripts/admin/addon/models/screened-ip-address.js, app/assets/javascripts/admin/addon/models/screened-url.js, app/assets/javascripts/admin/addon/models/site-setting.js, app/assets/javascripts/admin/addon/models/site-text.js, app/assets/javascripts/admin/addon/models/staff-action-log.js, app/assets/javascripts/admin/addon/models/theme-settings.js, app/assets/javascripts/admin/addon/models/theme.js, app/assets/javascripts/admin/addon/models/tl3-requirements.js, app/assets/javascripts/admin/addon/models/user-field.js, app/assets/javascripts/admin/addon/models/version-check.js, app/assets/javascripts/admin/addon/models/watched-word.js, app/assets/javascripts/admin/addon/models/web-hook.js
This commit was generated using the ember-native-class-codemod along with a handful of manual updates
=> DEV: Update admin models to native class syntax

plugins/chat/spec/requests/core_ext/bookmarks_controller_spec.rb
=> DEV: fixes a flakey spec

lib/tasks/docker.rake
=> FIX: An ember build is required to run the system tests

app/assets/javascripts/admin/addon/models/incoming-email.js
Followup to 64557c407611783506db7172be81ed5d63aa2172
=> FIX: Error for admin-panel incoming email logs

app/assets/javascripts/discourse/app/lib/user-tips.js, app/assets/stylesheets/common/base/user-tips.scss
=> FIX: Do not show user tips over composer

app/assets/stylesheets/common/base/sidebar.scss
Followup to https://github.com/discourse/discourse/commit/54eaae43267a14abb9b63c41be02081df38d52e8
=> DEV: fixes linting

app/assets/javascripts/discourse/app/components/sidebar/section.hbs, app/assets/javascripts/discourse/app/components/sidebar/user/custom-sections.hbs, app/assets/javascripts/discourse/app/components/sidebar/user/custom-sections.js, app/assets/javascripts/discourse/app/components/sidebar/user/section-link.js, app/assets/javascripts/discourse/app/components/sidebar/user/section.js, app/assets/javascripts/discourse/app/controllers/sidebar-section-form.js, app/assets/javascripts/discourse/app/modifiers/draggable.js, app/assets/stylesheets/common/base/_index.scss, app/assets/stylesheets/common/base/sidebar-custom-section.scss, app/assets/stylesheets/common/base/sidebar.scss, app/controllers/sidebar_sections_controller.rb, app/models/sidebar_section.rb, app/models/sidebar_section_link.rb, app/serializers/sidebar_section_serializer.rb, config/routes.rb, db/migrate/20230307051200_add_position_to_sidebar_section_links.rb, spec/requests/sidebar_sections_controller_spec.rb, spec/system/custom_sidebar_sections_spec.rb
Drag and drop to reorder custom sidebar sections
https://user-images.githubusercontent.com/72780/224182541-b4f5bb73-cd75-4992-b6d3-c1612bcec583.mov
=> FEATURE: ability to reorder links in custom sidebar sections

app/assets/javascripts/admin/addon/models/admin-user.js, app/controllers/admin/users_controller.rb, app/models/user_history.rb, app/services/staff_action_logger.rb, config/routes.rb, spec/requests/admin/users_controller_spec.rb
DEV: rename the route `/admin/users/:id/reset_bounce_score` to use dashes instead of underscores
=> FEATURE: log manual bounce reset

app/services/user_anonymizer.rb, lib/guardian/user_guardian.rb, spec/lib/guardian_spec.rb
=> FIX: Do not allow anonymous users to be anonymized

lib/tasks/hashtags.rake, spec/tasks/hashtags_spec.rb
=> DEV: Capture output in hashtags spec

app/assets/javascripts/discourse-common/addon/config/environment.js, app/assets/javascripts/discourse/app/components/sidebar/user/section-link.js, app/assets/stylesheets/common/base/sidebar-custom-section.scss
Reorder should start after 300ms.
In addition, pointer events should be blocked to not open link after reorder is finished.
Finally, ensure that it is a left click
https://user-images.githubusercontent.com/72780/227079203-4cc6b91e-58ae-4f95-801c-7b5a29bd1b92.mov
=> FIX: delay custom section reorder

app/assets/javascripts/discourse/app/components/sidebar/section.hbs, app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-categories-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-community-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-tags-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-community-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-messages-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-tags-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-sidebar-test.js, plugins/chat/spec/system/list_channels/sidebar_spec.rb, plugins/chat/spec/system/page_objects/sidebar/sidebar.rb, spec/system/custom_sidebar_sections_spec.rb, spec/system/page_objects/components/sidebar.rb
Data attributes are less restrictive than the class attribute.
=> DEV: Switch to data attributes to represent sidebar section name

app/assets/javascripts/discourse-common/addon/config/environment.js, app/assets/javascripts/discourse/app/components/sidebar/user/section-link.js, app/assets/stylesheets/common/base/sidebar-custom-section.scss
This reverts commit 4fe79ccc790118aa78b01aade53f9f6cb3431d8b as this was breaking system specs probably due to ` || environment === "test"`
=> Revert "FIX: delay custom section reorder (#20781)"

app/controllers/admin/themes_controller.rb, lib/url_helper.rb, spec/lib/url_helper_spec.rb, spec/requests/admin/themes_controller_spec.rb
=> SECURITY: Limit URL length for theme remote

app/controllers/admin/themes_controller.rb, lib/url_helper.rb, spec/lib/url_helper_spec.rb, spec/requests/admin/themes_controller_spec.rb
=> SECURITY: Limit URL length for theme remote (stable)

app/models/category_list.rb, spec/models/category_list_spec.rb
=> DEV: More specific API to including extra associations in CategoryList

.github/workflows/tests.yml
... to see if it's always the same test causing timeouts
=> DEV: Show which system tests are being executed in CI

lib/topic_query.rb
This commit breaks down the code in `TopicQuery#default_results` into
smaller private methods to improve readability.
=> DEV: Refactor `TopicQuery#default_results` to improve readability

app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.hbs, app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.js, app/assets/javascripts/discourse/app/controllers/application.js, app/assets/javascripts/discourse/app/templates/application.hbs, app/assets/javascripts/discourse/app/widgets/header-bootstrap-mode.js, app/assets/javascripts/discourse/app/widgets/header-contents.js, app/assets/javascripts/discourse/tests/acceptance/bootstrap-mode-notice-test.js, app/assets/stylesheets/common/base/header.scss, app/jobs/regular/enable_bootstrap_mode.rb, app/jobs/scheduled/disable_bootstrap_mode.rb, config/locales/client.en.yml, config/site_settings.yml, docs/ADMIN-QUICK-START-GUIDE.md
=> FEATURE: Move bootstrap mode indicator to header

spec/system/composer/review_media_unless_trust_level_spec.rb
=> DEV: Disable test to see if this is what's causing ci failures

app/controllers/application_controller.rb
=> DEV: Make banner cache work like other caches

lib/topics_filter.rb, spec/lib/topics_filter_spec.rb
Follow-up to dd88fdeabcdf21ee1b27a4bac2f914de490d51b5
=> DEV: Fix `TopcisFilter#filter_tags` not working for a single tag

plugins/chat/spec/system/channel_selector_modal_spec.rb, plugins/chat/spec/system/shortcuts/chat_composer_spec.rb
=> DEV: Fix a constant redefinition warning

app/models/developer.rb
=> DEV: make developer cache work like other caches

lib/content_security_policy/extension.rb
=> DEV: Make csp cache work like other caches

app/models/color_scheme.rb
=> DEV: Make hex cache work like other caches

app/models/category.rb
=> DEV: Make category subcategory_ids cache work like other caches

app/models/category.rb
=> DEV: Make category topic_ids cache work like other caches

app/models/group.rb, spec/models/group_spec.rb
We currently have the method `bulk_add`, but there was no `bulk_remove` method for a group. This implements it :)
=> FEATURE: ability to bulk_remove users from a group

app/assets/stylesheets/common/base/sidebar-custom-section.scss, app/assets/stylesheets/common/base/sidebar.scss
https://github.com/discourse/discourse/blob/7dcaaec90cca3bd8fd5cbe521813d918ea471aaf/app/assets/stylesheets/common/foundation/mixins.scss#L122
=> FIX: use unselectable mixin in sidebar drag and drop

app/assets/javascripts/discourse/app/controllers/full-page-search.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/templates/full-page-search.hbs
This change adds an experimental API tagged as "Do not use", only intended to conduct a PoC to test semantic search in the AI plugin.
=> FEATURE: Experimental API for custom full-page search types.

app/assets/javascripts/discourse/app/components/reviewable-item.hbs, app/assets/stylesheets/common/base/reviewables.scss
Added context question for flagged messages + added fallback badge colour
=> UX: reviewq flagging

app/serializers/search_post_serializer.rb
=> DEV: Get headline excerpt config from GroupedSearchResult in serializer.

app/assets/javascripts/discourse/app/components/composer-messages.js
=> DEV: Fix a use-after-destroy issue

app/assets/javascripts/discourse/app/components/reviewable-item.hbs, app/assets/javascripts/discourse/tests/fixtures/session-fixtures.js, app/assets/stylesheets/common/base/reviewables.scss
Plugin related code should not be polluting core's code base.
=> DEV: Nuke plugin related code from core

app/assets/stylesheets/common/components/topic-query-filter.scss
=> UX: Make input on `/filter` route full width

app/assets/javascripts/discourse/app/components/user-status-message.hbs, app/assets/javascripts/discourse/tests/integration/components/user-status-message-test.js
This will now allow:
```
<UserStatusMessage @status={{@message.user.status}} @class="foo" />
```
=> DEV: allows <UserStatusMessage /> to accept custom css class

app/controllers/sidebar_sections_controller.rb, app/models/sidebar_section.rb, app/models/sidebar_section_link.rb, db/migrate/20230404064728_system_user_for_public_sections.rb, spec/models/sidebar_section_link_spec.rb, spec/models/sidebar_section_spec.rb, spec/requests/sidebar_sections_controller_spec.rb
Before, public sidebar sections were belonging to admin. However, a better choice is system user.
=> FIX: public sidebar sections belong to system user

bin/yarn-app
=> DEV: Add yarn-app shim to run yarn using the app modules

app/assets/javascripts/admin/addon/controllers/admin-user-index.js
=> FIX: Show better default error when failing to delete all user posts

app/assets/javascripts/discourse/app/controllers/edit-user-directory-columns.js
=> FIX: Handle errors when we show the edit user directory columns modal

app/assets/javascripts/admin/addon/controllers/admin-user-index.js, app/assets/javascripts/discourse/app/lib/ajax-error.js
Follow-up-to: 6bbf8324008871068ddf46a80567a3887bb984be
=> DEV: Allow HTML errors whenever a popup is generated

app/assets/javascripts/discourse/app/controllers/activation-edit.js, app/assets/javascripts/discourse/app/controllers/do-not-disturb.js, app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js, app/assets/javascripts/discourse/app/controllers/forgot-password.js, app/assets/javascripts/discourse/app/controllers/grant-badge.js, app/assets/javascripts/discourse/app/controllers/group-add-members.js, app/assets/javascripts/discourse/app/controllers/login.js, app/assets/javascripts/discourse/app/controllers/move-to-topic.js, app/assets/javascripts/discourse/app/lib/ajax-error.js, plugins/chat/assets/javascripts/discourse/controllers/chat-channel-edit-name-slug.js
=> DEV: Rely on helpers for ajax error handling to reduce repetition

plugins/chat/assets/javascripts/discourse/components/chat-composer.hbs, plugins/chat/assets/javascripts/discourse/components/chat-composer.js, plugins/chat/assets/javascripts/discourse/components/chat-live-pane.hbs, plugins/chat/assets/javascripts/discourse/components/chat-thread.hbs, plugins/chat/spec/system/chat_composer_spec.rb
=> FIX: cancel editing should clear the composer

app/assets/javascripts/admin/addon/components/form-template/row-item.js, app/assets/javascripts/discourse/app/components/json-editor.js, app/assets/javascripts/discourse/app/components/quote-button.js, app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js
(and fix a typo, and remove an unnecessary `this.element` check)
=> DEV: Remove unneeded optional chaining operators

app/assets/javascripts/discourse/app/templates/modal/second-factor-backup-edit.hbs, app/assets/javascripts/discourse/app/templates/preferences-email.hbs, app/assets/javascripts/discourse/app/templates/preferences-second-factor.hbs, app/assets/stylesheets/common/base/new-user.scss
These pages could use some more love, but this gets them into a more sane place for now. 
Before:
After:
=> UX: fix solo preference page layout

plugins/chat/assets/stylesheets/common/base-common.scss
=> DEV: Add `overflow-x: hidden` to chat message containers

app/assets/javascripts/discourse/app/widgets/embedded-post.js
=> FIX: Add RenderGlimmer support for embedded posts

config/application.rb, docs/SECURITY.md
Existing passwords will continue to work. Hashes will be regenerates on a user's next login.
Requires https://github.com/discourse/discourse/pull/20980
=> FEATURE: Increase pbkdf2 iterations to 600k

app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/widgets/toggle-topic-summary.js
=> DEV: Experimental JS plugin API for topic summary HTML

app/assets/javascripts/discourse/app/components/sidebar/section-link.hbs, app/assets/javascripts/discourse/app/components/sidebar/section-link.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-categories-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-community-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-tags-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-community-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-messages-section-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-tags-section-test.js, app/assets/javascripts/discourse/tests/integration/components/sidebar/section-link-test.js, app/assets/stylesheets/common/base/sidebar-section-link.scss, plugins/chat/spec/system/navigation_spec.rb, plugins/chat/spec/system/sidebar_navigation_menu_spec.rb, spec/system/custom_sidebar_sections_spec.rb, spec/system/page_objects/components/sidebar.rb, spec/system/page_objects/components/sidebar_header_dropdown.rb
Data attribute is less restrictive than relying on the class attribute
=> DEV: Switch sidebar section link identifier to data attribute

plugins/chat/spec/system/chat_composer_spec.rb
https://github.com/discourse/discourse/actions/runs/4675927190/jobs/8281605117
=> DEV: Skip flaky test on actions

app/jobs/regular/update_username.rb
2e78045a fixed the anonymization job so that it correctly updated self-mentions, which are not logged in the post_actions table. The solution was to scan the entire `posts` table with an `raw ILIKE` query. On sites with many posts, this can take a very long time.
This commit updates the job to take a two-pass approach:
First, we update posts based on the post_actions table. This is much more efficient than a full table scan, and takes care of all 'non-self' mentions.
Then, we make a second pass using the `raw ILIKE` approach. Since we already took care of most posts, we can scope this down to self-mentions only. By filtering the query to a specific posts.user_id, it is significantly more performant than a full table scan.
=> PERF: Avoid full `posts` table scans during anonymisation

plugins/chat/spec/requests/chat/api/chatables_controller_spec.rb
=> DEV: skip flakey chatables controller spec

lib/topics_filter.rb, spec/lib/topics_filter_spec.rb
This commit adds support for the `posters-min:<count>` and
`posters-max:<count>` filters for the topics filtering query language.
`posters-min:1` will filter for topics with at least a one poster while
`posters-max:3` will filter for topics with a maximum of 3 posters.
If the filter has an invalid value, i.e string that cannot be converted
into an integer, the filter will be ignored.
If either of each filter is specify multiple times, only the last
occurence of each filter will be taken into consideration.
=> DEV: Support `posters-(min|max):<count>`  on `/filter` route

app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.hbs, app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/widgets/quick-access-profile.js, app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
=> DEV: Plugin API addQuickAccessProfileItem adds to revamped user menu

app/assets/javascripts/discourse/app/lib/plugin-api.js
- Print warning when it affects user/currentUser
- Improve description and link to Meta topic
=> DEV: Improve modifyClass warning message

app/assets/javascripts/discourse/ember-cli-build.js, app/assets/javascripts/discourse/package.json, app/assets/javascripts/package.json, app/assets/javascripts/patches/virtual-dom+2.1.1.patch, app/assets/javascripts/yarn.lock
Replaces: https://github.com/discourse/discourse/pull/21006, which was an alternative to https://github.com/discourse/discourse/pull/20903
Requires: https://github.com/discourse/discourse/pull/20904
See other PRs for context / reasoning / etc.
=> Virtual dom take 3

app/assets/javascripts/discourse/app/templates/composer.hbs
=> DEV: Add class to composer-open plugin outlet container

config/locales/server.en.yml
=> bootstrap mode change can take 24 hours

app/assets/javascripts/discourse/tests/unit/lib/build-quote-test.js, app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js
They are not related to pretty-text.
=> DEV: Extract build-quote tests

lib/discourse.rb, lib/plugin/instance.rb, plugins/chat/plugin.rb, plugins/poll/plugin.rb, spec/lib/plugin/instance_spec.rb
=> DEV: Improve add_to_serializer include_* options

app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js
On some mobile and possibly other browsers, the automatic video thumbnail generation would create blank or all white images.
This commit addresses several different issues that was preventing image generation from working correctly on mobile.
=> FIX: Blank video thumbnails

app/assets/javascripts/discourse/app/components/user-avatar-flair.js, app/assets/javascripts/discourse/app/lib/transform-post.js, app/assets/javascripts/discourse/app/widgets/post.js, app/assets/javascripts/discourse/app/widgets/topic-map.js, app/assets/javascripts/discourse/tests/integration/components/user-avatar-flair-test.js, app/assets/javascripts/discourse/tests/integration/components/widgets/topic-participant-test.js, app/serializers/post_serializer.rb, app/serializers/topic_post_count_serializer.rb, spec/requests/api/posts_spec.rb, spec/requests/api/schemas/json/admin_user_response.json, spec/requests/api/schemas/json/post_replies_response.json, spec/requests/api/schemas/json/post_show_response.json, spec/requests/api/schemas/json/post_update_response.json, spec/requests/api/schemas/json/topic_create_response.json, spec/requests/api/schemas/json/topic_show_response.json, spec/serializers/web_hook_post_serializer_spec.rb
=> FIX: Show auto-group flair according to user preferences

app/assets/javascripts/confirm-new-email/confirm-new-email.js
To security key errors when confirming new email.
=> DEV: Add error message styling

lib/composer_messages_finder.rb, spec/lib/composer_messages_finder_spec.rb
=> FIX: Safely return from missing post on `check_dont_feed_the_trolls`

.github/workflows/tests.yml
=> DEV: increase plugin system tests timeout

.github/workflows/tests.yml, plugins/chat/spec/system/archive_channel_spec.rb, plugins/chat/spec/system/chat_composer_spec.rb, plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb, spec/system/emojis/emoji_deny_list_spec.rb
=> DEV: Enable parallel system specs in GitHub actions CI

spec/system/emojis/emoji_deny_list_spec.rb
=> DEV: skips flakey spec

plugins/chat/assets/javascripts/discourse/routes/chat-channel-thread.js, plugins/chat/assets/javascripts/discourse/routes/chat-channel.js, plugins/chat/spec/system/page_objects/chat/chat_side_panel.rb, plugins/chat/spec/system/page_objects/chat/chat_thread.rb, plugins/chat/spec/system/single_thread_spec.rb
Followup to https://github.com/discourse/discourse/commit/a1b35601fcd209d83471e269e23b7c4f9a42465a
=> FIX: ensures thread is cleared when closing it

app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js, config/site_settings.yml
Creating a way to disable the auto generation of video thumbnails.
=> DEV: Create a site setting for video thumbnails

lib/topics_filter.rb, spec/lib/topics_filter_spec.rb
This commit adds support for the following date filters:
1. `activity-before:<YYYY-MM-DD>` which filters for topics that have been bumped at or before given date
2. `activity-after:<YYYY-MM-DD>` which filters for topics that have been bumped at or after given date
3. `created-before:<YYYY-MM-DD>` which filters for topics that have been created at or before given date
4. `created-after:<YYYY-MM-DD>` which filters for topics that have been created at or after given date
5. `latest-post-before:<YYYY-MM-DD>` which filters for topics with the
latest post posted at or before given date
6. `latest-post-after:<YYYY-MM-DD>` which filters for topics with the
latest post posted at or after given date
If the filter has an invalid value, i.e string that cannot be converted
into a proper date in the …
=> DEV: Support filtering by date columns on /filter route

app/models/group.rb, spec/models/group_spec.rb
=> DEV: set limits for text fields on groups

app/models/badge.rb, spec/models/badge_spec.rb
=> DEV: Set limits for text fields in badges

app/models/theme.rb
=> PERF: Remove unnecessary queries from Theme#set_field

plugins/discourse-lazy-videos/assets/javascripts/discourse/components/lazy-iframe.js, plugins/discourse-lazy-videos/assets/javascripts/discourse/components/lazy-video.hbs, plugins/discourse-lazy-videos/assets/javascripts/lib/lazy-video-attributes.js, plugins/discourse-lazy-videos/lib/lazy-videos/lazy_youtube.rb, plugins/discourse-lazy-videos/test/javascripts/components/lazy-video-test.js
=> FIX: allows youtube embeds to respect the `t` param

app/assets/stylesheets/common/base/onebox.scss, lib/onebox/templates/discourse_user_onebox.mustache, lib/oneboxer.rb
=> UX: Fix user onebox layout

lib/tasks/themes.rake
=> DEV: Wrap remote theme update in transaction

app/assets/javascripts/discourse/app/components/user-menu/menu.js, app/assets/javascripts/discourse/app/components/user-menu/notifications-list.js, app/assets/javascripts/discourse/app/lib/user-menu/notification-item.js
No tests needed here, just firing appEvents that themes can consume for whatever purposes they may consume them for :)
=> DEV: Fire appEvents for user menu events (opening/clicking)

lib/tasks/docker.rake
=> DEV: Add 20m timeout to system tests

lib/search.rb, spec/lib/search_spec.rb
This new modifier can be used by plugins to modify search ordering.
Specifically plugins such as discourse_solved can amend search ordering
so solved topics bump to the top.
Also correct edge case where low and high sort priority categories did not
order correctly when it came to closed/archived
=> FEATURE: search_rank_sort_priorities modifier

.github/workflows/linting.yml, .github/workflows/tests.yml
This will help us to catch missing lockfile changes before they are merged into `main`
=> DEV: Use `--frozen-lockfile` in GitHub CI

lib/tasks/docker.rake
=> DEV: Increase docker.rake system test timeout time to match CI

app/models/reviewable.rb, spec/models/reviewable_spec.rb
=> DEV: Set limits for text fields in reviewables

lib/discourse_plugin_registry.rb
Clearing modifiers during a plugin spec run will affect all future specs. Instead, this commit introduces a more surgical `.unregister_modifier` API which plugins can use if they need to add/remove a modifier during a specific spec.
=> DEV: Prevent clearing plugin modifiers during plugin spec runs

app/models/concerns/reports/consolidated_api_requests.rb, app/models/concerns/reports/consolidated_page_views.rb, app/models/concerns/reports/trust_level_growth.rb, app/models/report.rb, spec/models/report_spec.rb
Related to https://github.com/discourse/discourse/pull/21362
=> UX: Use fixed colors for admin stacked chart reports

app/assets/javascripts/discourse/app/routes/discourse.js
I've made sure there are no usages in plugins.
=> DEV: drop a deprecated function

app/assets/javascripts/discourse/tests/acceptance/category-edit-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-categories-test.js, app/assets/javascripts/discourse/tests/acceptance/user-preferences-tracking-test.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/mini-tag-chooser-test.js, app/assets/javascripts/select-kit/addon/components/multi-select.js, app/assets/javascripts/select-kit/addon/components/select-kit.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-body.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-header.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js
This reverts commit 1b2a1c94d46d27e8e95dd24faa71ad18b8a17349. Noticed some issues in Safari macOS that need to be addressed.
=> Revert "A11Y: select kit close on focus out (#21274)"

app/assets/javascripts/discourse/tests/acceptance/composer-editor-mentions-test.js, app/assets/javascripts/discourse/tests/acceptance/hashtag-autocomplete-test.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
=> DEV: extract emulateAutocomplete test helper

app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs
Using this for a component that adds a button here:
=> DEV: add panel-body-bottom outlet to user menu

app/assets/javascripts/discourse/app/components/sidebar/more-section-links.hbs, app/assets/javascripts/discourse/app/components/sidebar/more-section-links.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-user-community-section-test.js, app/assets/stylesheets/common/base/sidebar-more-section-links.scss
Change mechanism handling `more` button for sidebar. 
Before it was using HTML details tag. 
To make tests more reliable, we are switching to use ember runloop.
=> FIX: flaky sidebar-user-community-section-test

spec/models/group_spec.rb
Related: https://github.com/discourse/discourse/commit/608bde734b0154290bb15542a08579a2765f3304
=> FIX: Update test limit for email domain

app/assets/javascripts/discourse/app/models/rest.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js, plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js, plugins/chat/test/javascripts/components/chat-composer-uploads-test.js
=> DEV: Correct the app-events service injections

config/locales/server.en.yml, config/site_settings.yml, db/migrate/20230505113906_hide_user_tips_for_existing_users.rb, spec/requests/api/schemas/json/site_response.json, spec/serializers/site_serializer_spec.rb, spec/support/system_helpers.rb
=> FEATURE: Enable user tips by default

app/assets/javascripts/select-kit/addon/components/multi-select.hbs, app/assets/javascripts/select-kit/addon/components/single-select.hbs, app/assets/stylesheets/common/select-kit/select-kit.scss
Curious to see if this feels smoother. 
Before/after screen recordings: 
https://user-images.githubusercontent.com/368961/236371685-1efb78c3-7ae7-4c74-a5c8-b2d41b86b5e1.mp4
https://user-images.githubusercontent.com/368961/236371691-34320a4e-f927-4489-aaeb-96bd72b91d28.mp4
=> UX: loading slider for select-kit filter

plugins/chat/spec/system/channel_members_page_spec.rb
Allows more time for the members to be appended in tests
=> DEV: more resilient spec

.github/workflows/tests.yml
We're testing out BuildJet which can provide cheaper runners. /t/98456
=> DEV: Use BuildJet for some test jobs

app/controllers/admin/site_settings_controller.rb, app/controllers/application_controller.rb, lib/discourse.rb, lib/plugin/instance.rb, lib/site_setting_extension.rb, plugins/poll/plugin.rb, spec/requests/admin/site_settings_controller_spec.rb
=> DEV: Add configurable? helper to Plugin::Instance 

app/controllers/admin/site_settings_controller.rb, app/controllers/application_controller.rb, lib/discourse.rb, lib/plugin/instance.rb, lib/site_setting_extension.rb, plugins/poll/plugin.rb, spec/requests/admin/site_settings_controller_spec.rb
This reverts commit 3073e5cfb0721b3b8009963c5fc7f61d414db317.
=> Revert "DEV: Add configurable? helper to Plugin::Instance  (#20767)"

spec/lib/stylesheet/manager_spec.rb
Should fix "stack too deep" issues in CI
=> DEV: Stub stderr instead of manual change

app/assets/javascripts/discourse/app/lib/plugin-api.js
The example doesn't work as-is, this fixes it
=> FIX: addNavigationBarItem api example

app/models/api_key.rb, spec/models/api_key_spec.rb
=> DEV: Set a limit for ApiKey#description

plugins/chat/assets/stylesheets/common/chat-thread-list-item.scss, plugins/chat/assets/stylesheets/common/chat-thread-list.scss, plugins/chat/spec/system/thread_list/full_page_spec.rb
- hide setting button on thread when it's disabled
- small changes in colour and spacing
=> UX thread list

plugins/chat/spec/system/navigating_to_message_spec.rb
This reverts commit 64971e5972488d089f80df8b40fd4646cd5485ba.
=> Revert "DEV: attempts to fix flakey spec (#21547)"

app/models/badge_grouping.rb, spec/models/badge_grouping_spec.rb
=> DEV: Set limits for text fields on BadgeGrouping

app/assets/javascripts/discourse/app/components/d-modal-body.hbs, app/assets/javascripts/discourse/app/components/d-modal-body.js, app/assets/javascripts/discourse/app/components/d-modal.hbs, app/assets/javascripts/discourse/app/components/d-modal.js, app/assets/javascripts/discourse/app/controllers/forgot-password.js, app/assets/javascripts/discourse/app/controllers/login.js, app/assets/javascripts/discourse/app/lib/show-modal.js, app/assets/javascripts/discourse/app/templates/modal/history.hbs, app/assets/javascripts/discourse/app/templates/modal/raw-email.hbs, app/assets/javascripts/discourse/tests/acceptance/login-with-email-test.js, app/assets/stylesheets/common/base/history.scss, app/assets/stylesheets/common/base/modal.scss
(see individual commit messages)
=> Modernise d-modal and d-modal-body components

config/locales/server.en.yml
=> remove "powered by discourse.org" from seeded welcome topic

app/assets/javascripts/discourse/app/components/user-menu/menu.js
=> DEV: Use `@cached` decorator in `user-menu/menu`

app/assets/javascripts/discourse/app/components/user-card-contents.hbs, app/assets/javascripts/discourse/app/components/user-card-contents.js, app/assets/javascripts/discourse/tests/acceptance/user-card-test.js, app/assets/stylesheets/common/components/user-card.scss, app/controllers/users_controller.rb, app/serializers/inactive_user_serializer.rb, config/locales/client.en.yml, spec/requests/users_controller_spec.rb
=> FEATURE: Show user cards for inactive users

lib/svg_sprite.rb, plugins/chat/assets/javascripts/discourse/components/chat-drawer/header/thread-list-button.hbs, plugins/chat/assets/javascripts/discourse/components/chat-full-page-header.hbs, vendor/assets/svg-icons/discourse-additional.svg
=> FIX: Add new chat threads icon and move thread list button to right

app/assets/javascripts/discourse/tests/unit/services/store-test.js
* Use native getters
* Use `assert.true`/`assert.false`
* Improve some assertions
=> DEV: Clean up store-test

app/assets/javascripts/discourse/tests/acceptance/category-edit-test.js, app/assets/javascripts/discourse/tests/acceptance/select-kit-accessibility-test.js, app/assets/javascripts/discourse/tests/integration/components/select-kit/single-select-test.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-body.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-filter.js, app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.js
Same as #214500 but fixes an issue with mobile navigation in some cases.
=> A11Y: Improve select-kit accessibility (take 2)

plugins/chat/assets/stylesheets/mixins/chat-scrollbar.scss
=> FIX: show scrollbars under firefox in chat

plugins/chat/assets/stylesheets/common/chat-composer.scss, plugins/chat/assets/stylesheets/common/chat-height-mixin.scss, plugins/chat/assets/stylesheets/common/chat-threads-list.scss
=> FIX: allows notch to have composer bg color

bin/turbo_rspec, lib/turbo_tests/progress_formatter.rb, lib/turbo_tests/runner.rb
=> DEV: add `--seed` to turbo_rspec, tweak CI output

app/assets/javascripts/discourse/app/services/composer.js
=> DEV: Option to always hide warning in the coposer

app/assets/javascripts/discourse/app/components/sidebar/common/custom-section.hbs, app/assets/javascripts/discourse/app/components/sidebar/section.hbs, app/assets/javascripts/discourse/app/lib/sidebar/community-section.js, app/assets/stylesheets/desktop/menu-panel.scss, app/assets/stylesheets/mobile/menu-panel.scss
=> UX: Improve display of short site description in header dropdown

plugins/styleguide/assets/javascripts/discourse/components/toggle-color-mode.hbs, plugins/styleguide/assets/javascripts/discourse/components/toggle-color-mode.js
=> DEV: Improve manual color scheme toggle in styleguide

plugins/chat/assets/stylesheets/common/chat-composer-dropdown.scss, plugins/chat/assets/stylesheets/common/chat-composer.scss
* prevent hover on disabled state
* more contrast between focus and not focus for send button
=> UX: General chat composer tweaks

app/assets/stylesheets/common/base/static-login.scss
=> UX: Tweak logo size to make sure it's not too small on small screen

app/assets/javascripts/discourse/app/templates/modal/share-topic.hbs
=> DEV: add plugin outlet to share sources

config/site_settings.yml, lib/search.rb
We have someone asking to be able to control this, but I don't think anyone needs to see the setting in the UI, so the setting is hidden.
=> DEV: Add site setting to control search page size

app/assets/javascripts/discourse/ember-cli-build.js
=> DEV: Resolve a sinon/webpack warning

app/jobs/scheduled/clean_up_inactive_users.rb, spec/jobs/clean_up_inactive_users_spec.rb
=> FIX: consider users with trashed topics/posts for inactive cleanup

app/assets/stylesheets/common/components/buttons.scss, app/assets/stylesheets/common/foundation/mixins.scss
Looking into changing the active button styling. This primarily makes the active state slightly darker than the hover state. To do this I made a couple changes to how we color the background on the active state button.
This also fixes an issue where the active state was not rendering unless you moved your cursor while holding down your click away from the button.
=> Button research

plugins/chat/assets/javascripts/discourse/components/chat-thread.js
We don't have proper pagination yet so this
should help us in the interim.
=> DEV: Bump thread page size to 100

plugins/chat/app/controllers/chat/chat_controller.rb
I upped this to 100 in dad6b618071b1644a7f9cb68e9f746cdfde1c042
but didn't update the controller. This controller is going away
quite soon so not really worth adding tests etc. to this.
=> FIX: Page size check for thread messages

plugins/chat/spec/requests/chat_controller_spec.rb
Followup 3fed1abf2f2a5553139d9c284702705dfba4ce4e
=> DEV: Fix chat pagination spec

plugins/chat/assets/javascripts/discourse/components/chat-message.hbs, plugins/chat/spec/system/chat_channel_spec.rb, plugins/chat/spec/system/deleted_message_spec.rb, plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb, plugins/chat/spec/system/page_objects/chat/chat.rb, plugins/chat/spec/system/page_objects/chat/chat_channel.rb, plugins/chat/spec/system/page_objects/chat/chat_thread.rb, plugins/chat/spec/system/page_objects/chat/components/message.rb, plugins/chat/spec/system/page_objects/chat/components/messages.rb
This should also make `message_notifications_with_sidebar_spec.rb` more resilient as we are now checking for `is-persisted` class instead of checking for the absence of `is-staged`.
=> DEV: implements initial messages component

app/assets/javascripts/discourse/app/lib/uploads.js, app/assets/javascripts/discourse/tests/unit/lib/uploads-test.js, app/models/optimized_image.rb, config/nginx.sample.conf, config/site_settings.yml, lib/file_helper.rb, lib/upload_creator.rb
Depends on https://github.com/sdsykes/fastimage/pull/141
=> FEATURE: Add support for AVIF images

app/assets/javascripts/discourse/app/templates/about.hbs, app/views/static/show.html.erb, config/initializers/014-track-setting-changes.rb, config/site_settings.yml, lib/seed_data/topics.rb, lib/tasks/annotate.rake, spec/initializers/track_setting_changes_spec.rb, spec/lib/seed_data/topics_spec.rb
Legal topics, such as the Terms of Service and Privacy Policy topics
do not make sense if the entity creating the community is not a company.
=> FEATURE: Create legal topics for set company name

app/controllers/sidebar_sections_controller.rb, spec/requests/sidebar_sections_controller_spec.rb
1. '#reorder' specs where serializing objects when it is not needed.
2. Add tests for anon user to `#reorder` specs
=> DEV: Minor improvements to SidebarSectionsController spec

app/assets/javascripts/discourse/app/components/bookmark-list.hbs, app/assets/javascripts/discourse/app/components/d-toggle-switch.hbs, app/assets/javascripts/discourse/app/components/user-card-contents.hbs, app/assets/javascripts/discourse/app/templates/user/summary.hbs
=> DEV: Clean up template-lint disable/enable lines

plugins/chat/app/serializers/chat/message_serializer.rb
This would generate a 500 as we would call id on a nil object.
=> FIX: removes destroyed mentioned used

plugins/chat/assets/javascripts/discourse/components/styleguide/chat-thread-list-item.hbs, plugins/chat/assets/javascripts/discourse/components/styleguide/chat-thread-list-item.js, plugins/chat/assets/javascripts/discourse/components/styleguide/organisms/chat.hbs, plugins/chat/assets/javascripts/discourse/lib/fabricators.js, plugins/chat/assets/javascripts/discourse/models/chat-thread-preview.js
=> DEV: introduces Chat::Thread::ListItem in styleguide

plugins/chat/assets/javascripts/discourse/components/chat-channel.js, plugins/chat/assets/javascripts/discourse/components/chat-drawer.js
=> FIX: uses DiscourseURL.routeTo for drawer transitions

plugins/chat/assets/stylesheets/common/chat-composer-button.scss
- ensures buttons are aligned to the bottom
- makes the emoji icon tertiary as initially intended
- correctly sets the icon scale of the sending button
=> UI:  blue emoji icon when input is focused

app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/widgets/search-menu-results.js, app/assets/javascripts/discourse/app/widgets/search-menu.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
=> DEV: Plugin outlets / extension points in search-menu

plugins/chat/spec/system/chat_message_onebox_spec.rb, plugins/chat/spec/system/edited_message_spec.rb, plugins/chat/spec/system/message_errors_spec.rb, plugins/chat/spec/system/page_objects/chat/chat_channel.rb, plugins/chat/spec/system/page_objects/chat/chat_thread.rb, plugins/chat/spec/system/transcript_spec.rb
Just remove the assertions for now as they are a constant source of
tests flakiness.
=> DEV: Partially revert d1924c7328b6823167f2d713030b98d0176f20cf

app/assets/javascripts/discourse/app/lib/sidebar/community-section.js, spec/system/custom_sidebar_sections_spec.rb, spec/system/page_objects/components/sidebar.rb, spec/system/page_objects/modals/sidebar_section_form.rb
Because of typo, icon could not be changed.
=> FIX: change Community icons

app/assets/javascripts/discourse/app/lib/autocomplete.js
Meta topic: https://meta.discourse.org/t/mention-suggestion-list-box-in-the-rtl-website-in-wrong-place/266763?u=osama.
Our autocomplete box doesn't currently take into account the user's locale and places itself off-screen when using an RTL locale. This PR changes the placement logic for the autocomplete box when an RTL locale is used to make sure that:
1. the autocomplete box's right side is near and to the left of the caret 
2. the autocomplete box doesn't go outside the composer's left side
Before:
After:
=> FIX: Ensure mention autocomplete box doesn't go off-screen in RTL locales

app/models/api_key_scope.rb, config/locales/client.en.yml, spec/requests/admin/api_controller_spec.rb
Adds api scopes for
- `/posts.json`
- `/posts.rss`
- `/private-posts.json`
- `/private-posts.rss`
=> FEATURE: Add API Scope for latest posts

app/assets/javascripts/discourse/app/components/offline-indicator.hbs, app/assets/javascripts/discourse/app/components/offline-indicator.js, app/assets/javascripts/discourse/app/initializers/message-bus.js, app/assets/javascripts/discourse/app/services/app-state.js, app/assets/javascripts/discourse/app/services/message-bus-connectivity.js, app/assets/javascripts/discourse/app/templates/application.hbs, app/assets/stylesheets/common/components/_index.scss, app/assets/stylesheets/common/components/offline-indicator.scss, config/locales/client.en.yml, config/locales/server.en.yml, config/site_settings.yml, spec/system/network_disconnected_spec.rb
=> FEATURE: Offline indicator

app/assets/stylesheets/common/components/user-card.scss
=> DEV: Fix a sass warning

lib/plugin/metadata.rb
https://github.com/discourse/discourse-zoom
=> DEV: Add zoom plugin to official list of plugins

config/locales/server.en.yml
Previous copy was unclear if setting the site setting to 0 would disable the feature or disable the rate limit.
=> UX: Improve /print rate limit description

app/assets/javascripts/discourse/app/controllers/discovery/topics.js, app/assets/javascripts/discourse/app/controllers/dismiss-new.js, app/assets/javascripts/discourse/app/controllers/tag-show.js, app/assets/javascripts/discourse/app/mixins/dismiss-topics.js, app/assets/javascripts/discourse/app/models/topic.js, app/assets/javascripts/discourse/app/templates/modal/dismiss-new.hbs, app/controllers/topics_controller.rb, config/locales/client.en.yml, spec/requests/topics_controller_spec.rb, spec/system/dismiss_topics_spec.rb, spec/system/page_objects/modals/dismiss_new.rb
Display modal for combined new and unread view. 
Demo:
=> FEATURE: new dismiss button for combined new and unread view

app/views/static/login.html.erb
Accompanying PR: https://github.com/discourse/discourse-trendy-login/pull/5
=> DEV: add class for static login description section

plugins/chat/test/javascripts/acceptance/user-status-on-mentions-test.js
=> DEV: disable flaky specs

app/controllers/webhooks_controller.rb, config/routes.rb, spec/requests/webhooks_controller_spec.rb
This is a continuation of https://github.com/discourse/discourse/pull/19374.
=> FEATURE: Add Mailpace webhook

app/models/theme.rb
=> FIX: json_schemer no longer allows nil keys

spec/initializers/track_setting_changes_spec.rb
=> DEV: Fix welcome topic test

app/assets/stylesheets/common/base/_topic-list.scss
=> UX: list group label indicator should match existing design

app/assets/javascripts/discourse/app/lib/lock-on.js
This reverts commit ad0a8cccc8c4360ca4423b952702fe2f0bc8bf46.
=> Revert "FIX: attempts to exit lock-on early (#21949)"

spec/models/theme_field_spec.rb
=> DEV: Fix interactions between tests via plugin svg sprite cache

app/assets/stylesheets/common/base/d-image-grid.scss
Ensures video and placeholder elements have vertical spacing in the grid.
=> UX: Spacing fix for grid items

app/assets/javascripts/discourse/app/mixins/uppy-s3-multipart.js
When we get to really big files, it's better to not have thousands
of small chunks, since we don't have a resume functionality if the
upload fails. Better to try upload less chunks even if those chunks
are bigger.
For example, with this change a 20GB file would go from 4000 chunks
of the default 5mb to 1000 chunks of the new 20mb size. Still a lot,
but perhaps more manageable.
This is somewhat experimental -- if we still don't see improvements
we can always change back.
=> FEATURE: Dynamic chunk size with uppy

app/assets/javascripts/discourse/package.json, app/assets/javascripts/yarn.lock
=> DEV: Bump workbox packages from 4.3.1 to 7.0.0

spec/system/topic_page_spec.rb
=> DEV: Increase topic_page_spec wait time

app/assets/stylesheets/common/base/d-popover.scss, app/assets/stylesheets/common/base/user-tips.scss
=> UX: Make user tips more obvious

app/assets/stylesheets/common/base/lightbox.scss
=> UX: remove rounded border on hover lightbox

app/models/topic_embed.rb, spec/models/topic_embed_spec.rb
This prevents duplicate topics from being created when using embed_urls
that only differ on query params.
=> SECURITY: Use canonical url for topic embeddings

app/assets/stylesheets/common/base/magnific-popup.scss
=> UX: force long filenames to wrap in lightbox

plugins/chat/app/services/chat/lookup_channel_threads.rb
=> PERF: fixes multiple N+1 while loading threads

docs/INSTALL-email.md
"SMTP and SEND API Settings" link under Mailjet.
=> Fix broken link

app/assets/javascripts/discourse/app/templates/list/participant-groups.hbr, app/assets/stylesheets/common/base/_topic-list.scss
=> UX: stack group inbox label horizontally

.github/workflows/tests.yml
This should help us to catch the most catastrophic cases where plugins fail to auto-reload
=> DEV: Introduce Zeitwerk reloading check in CI

app/assets/javascripts/discourse/app/components/d-navigation-item.hbs, app/assets/javascripts/discourse/app/components/d-navigation-item.js, app/assets/javascripts/discourse/app/components/user-nav.hbs, app/assets/javascripts/discourse/app/templates/preferences.hbs, app/assets/javascripts/discourse/app/templates/user-private-messages-group.hbs, app/assets/javascripts/discourse/app/templates/user-private-messages-user.hbs, app/assets/javascripts/discourse/app/templates/user/activity.hbs, app/assets/javascripts/discourse/app/templates/user/notifications.hbs
=> DEV: Convert d-navigation-item to glimmer

app/assets/javascripts/discourse/app/models/user.js, app/assets/javascripts/discourse/app/routes/app-route-map.js, app/assets/javascripts/discourse/app/routes/new-category.js, app/assets/javascripts/discourse/app/routes/preferences-email.js, app/assets/javascripts/discourse/app/routes/preferences-second-factor.js, app/assets/javascripts/discourse/app/templates/preferences-second-factor.hbs, config/routes.rb
=> DEV: Remove renderTemplate from 2fa preferences, email preferences, and new-category

app/services/post_alerter.rb
=> DEV: Add plugin modifier to expand group mentions in post_alerter

app/assets/javascripts/discourse/tests/acceptance/glimmer-search-test.js
=> DEV: Cleanup glimmer search menu tests

Gemfile.lock, app/assets/javascripts/discourse/package.json, app/assets/javascripts/yarn.lock
- Revert "Build(deps): Bump message-bus-client from 4.3.2 to 4.3.3 in /app/assets/javascripts (#22194)"
- Revert "Build(deps): Bump message_bus from 4.3.2 to 4.3.3 (#22188)"
=> revert message bus

app/services/post_alerter.rb
=> DEV: Add plugin modifier for notification_data manipulation

spec/services/post_alerter_spec.rb
=> DEV: Add spec for notification data modifier

app/controllers/sidebar_sections_controller.rb
=> FIX: Force ordering to make things more consistent and fix flaky test

app/assets/javascripts/discourse/app/templates/application.hbs
Adding a couple plugin outlets for a theme, as well as one for https://meta.discourse.org/t/a-plugin-outlet-for-the-footer-that-keeps-the-sidebar-at-full-height/269384
=> DEV: add before/after/below main-outlet outlets

spec/lib/auth/default_current_user_provider_spec.rb
Why is this change required?
Prevents the test from leaking state in Redis and ends up causing other
tests to become flaky.
Without this change, the following command was failing consistently:
```
bundle exec rspec --order random:12828 spec/import_export/category_exporter_spec.rb spec/initializers/web_hook_events_spec.rb spec/integration/auto_reject_reviewable_users_spec.rb spec/integration/content_security_policy_spec.rb spec/integration/email_outbound_spec.rb spec/integration/flags_spec.rb spec/integration/secure_uploads_spec.rb spec/jobs/admin_problems_spec.rb spec/jobs/check_new_features_spec.rb spec/jobs/clean_up_user_export_topics_spec.rb spec/jobs/create_recent_post_search_indexes_spec.rb spec/jobs/enqueue_suspect_users_spec.rb spec/jobs/export_csv_file_spec.rb …
```
=> DEV: Use `use_redis_snapshotting` in rate limiting test

app/assets/stylesheets/common/base/user.scss
=> UX: fix user preference `saved!` position

package.json, yarn.lock
=> DEV: Update moment-timezone

app/assets/javascripts/package.json, app/assets/javascripts/yarn.lock
…to close automated upgrade warnings. the api didn't have any breaking changes between 1.x and 2.x
=> DEV: Force update of unset-value

spec/lib/summarization/base_spec.rb, spec/services/topic_summarization_spec.rb, spec/system/topic_summarization_spec.rb
=> DEV: Fix lint and flaky summarization spec

app/assets/javascripts/admin/addon/components/theme-translation.js
Reported here: https://meta.discourse.org/t/translation-fields-not-working/269749
=> FIX: nest theme translation data so it saves properly 

Gemfile, Gemfile.lock
https://discuss.rubyonrails.org/t/cve-2023-28362-possible-xss-via-user-supplied-values-to/83132
=> upgrade Rails to 7.0.5.1

lib/middleware/discourse_public_exceptions.rb
Follow up to 4d3999de1026c7c6ede40bff1d9e394b94dccc2b
=> DEV: Fix failing spec after Rails upgrade to 7.0.5.1

plugins/chat/assets/javascripts/discourse/components/chat-channel.js, plugins/chat/assets/javascripts/discourse/components/chat-thread.js, plugins/chat/assets/javascripts/discourse/services/chat-api.js, plugins/chat/assets/javascripts/discourse/services/chat-channel-pane-subscriptions-manager.js, plugins/chat/assets/javascripts/discourse/services/chat-pane-base-subscriptions-manager.js
These are all well-known things we need to deal with
(e.g. scrolling and granular read in thread panel) or just
unnecessary to keep around.
=> DEV: Get rid of old chat TODOs

app/assets/javascripts/discourse/tests/acceptance/user-preferences-profile-test.js, app/assets/javascripts/discourse/tests/acceptance/user-profile-summary-test.js, app/assets/javascripts/discourse/tests/helpers/create-pretender.js
Prevent state leakage and update `/tags` to match the server
=> DEV: Fix default pretenders

app/assets/stylesheets/common/components/form-template-field.scss
> Note: This PR is part of the `experimental_form_templates` feature
=> UX: Make template fields fill the container width

spec/system/composer/preview_spec.rb, spec/system/page_objects/components/composer.rb
(both fail with the updated diffhtml)
=> DEV: Add diffhtml composer preview specs

app/assets/javascripts/discourse/app/models/user.js
=> DEV: Remove unused `User` methods

.eslintrc, app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js
=> DEV: Remove unused `testSelectKitModule`

app/assets/javascripts/discourse/app/lib/d-tooltip.js
=> DEV: Update `hasTouchCapabilities` in `d-tooltip.js`

plugins/chat/test/javascripts/acceptance/user-status-on-mentions-test.js
=> DEV: Skip flaky chat mention status test

plugins/chat/test/javascripts/acceptance/user-status-on-mentions-test.js
=> DEV: Skip flaky chat deleted message mention status flake

plugins/chat/test/javascripts/acceptance/user-status-on-mentions-test.js
=> DEV: Skip remaining flaky mention status tests

plugins/chat/test/javascripts/acceptance/user-status-on-mentions-test.js
=> DEV: Skip all chat user status tests

app/assets/javascripts/discourse/tests/acceptance/post-inline-mentions-test.js
=> DEV: Skip flaky post-inline-mention test

plugins/chat/assets/javascripts/discourse/components/chat-thread.js, plugins/chat/assets/javascripts/discourse/components/chat/selection-manager.hbs, plugins/chat/assets/javascripts/discourse/components/chat/selection-manager.js, plugins/chat/assets/javascripts/discourse/components/chat/thread/header.js, plugins/chat/spec/system/transcript_spec.rb
Fixes various flaky specs for chat. See commits for more detail.
=> DEV: Fix or remove flaky chat specs

app/assets/javascripts/discourse/app/components/d-modal.hbs, app/assets/javascripts/discourse/tests/integration/components/d-modal-test.js
=> DEV: Add `@bodyClass` argument to `<DModal>` component

app/assets/javascripts/discourse/app/components/d-modal.hbs, app/assets/javascripts/discourse/app/components/d-modal.js
=> DEV: Error if invalid `@flashType` passed to modal

plugins/chat/app/services/chat/search_chatable.rb, plugins/chat/spec/system/new_message_spec.rb
=> FIX: do not filter on category name

app/assets/javascripts/discourse/app/components/scrolling-post-stream.js, config/site_settings.yml
Followup to d51baa3bb3b08c5a7df6c22593d0162be6543147
=> FEATURE: Enable loading slider by default

app/assets/stylesheets/common/base/modal.scss
Co-authored-by: Kris <kris.aubuchon@discourse.org>
=> UX: Improve position of modal close button

plugins/chat/spec/services/auto_remove/handle_user_removed_from_group_spec.rb
We have no guarantees on the last record here, it's easier and more stable to check all created records.
=> DEV: more resilient auto remove spec

app/assets/javascripts/discourse/app/components/modal/dismiss-new.hbs, app/assets/javascripts/discourse/app/components/modal/dismiss-new.js, app/assets/javascripts/discourse/app/mixins/dismiss-topics.js, spec/system/dismiss_topics_spec.rb, spec/system/page_objects/components/topic_list.rb, spec/system/page_objects/modals/dismiss_new.rb
Regressed in 8b80132f8868500571ec1c80bb3e02f1873dbac2 due to a lack of
tests.
=> FIX: Can't dismiss new topics for experimental new new view

plugins/chat/assets/javascripts/discourse/services/chat.js
Sadly this function is one of the very hard to test codepaths of the app. We could in the future attempt to extract the content of the function to unit-test it.
=> FIX: typo in property name

plugins/chat/assets/javascripts/discourse/components/chat/admin/export-messages.hbs, plugins/chat/assets/javascripts/discourse/components/chat/admin/export-messages.js
=> DEV: makes <Chat::Admin::ExportMessage /> use glimmer

plugins/chat/assets/javascripts/discourse/components/chat/message-creator/user-selection.hbs
=> UX: do not show presence in message creator selection

app/assets/javascripts/discourse/app/components/d-modal.hbs, app/assets/javascripts/discourse/app/components/d-modal.js, app/assets/javascripts/discourse/tests/integration/components/d-modal-test.js, plugins/styleguide/assets/javascripts/discourse/components/sections/organisms/modal.hbs, plugins/styleguide/assets/javascripts/discourse/components/sections/organisms/modal.js
=> DEV: Support rendering `<DModal>` as a `<form>` element

plugins/chat/assets/stylesheets/common/chat-channel-card.scss
=> UX: lower border radius for channel cards

app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.hbs, app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.js, app/assets/javascripts/discourse/app/components/d-tooltip.js, app/assets/javascripts/discourse/app/components/suggested-topics.hbs, app/assets/javascripts/discourse/app/components/user-tip.hbs, app/assets/javascripts/discourse/app/components/user-tip.js, app/assets/javascripts/discourse/app/lib/user-tips.js, app/assets/javascripts/discourse/app/models/user.js, app/assets/javascripts/discourse/tests/acceptance/user-tips-test.js, app/assets/stylesheets/common/base/header.scss, app/assets/stylesheets/common/base/user-tips.scss, app/models/user.rb, config/locales/client.en.yml, config/locales/server.en.yml, spec/requests/api/schemas/json/site_response.json
https://github.com/discourse/discourse/assets/23153890/83e5ecfe-e5e4-46b5-8d87-a55584499e78
=> FEATURE: Show tooltip for bootstrap mode

app/assets/javascripts/discourse/app/components/composer-messages.js, app/assets/javascripts/discourse/tests/acceptance/composer-messages-test.js
What does this commit do?
This commit introduces two changes:
1. As a follow up review comment to
cc463c3e9bed468defe5399ee4fa16216ed96264, we remove the top level
recipientNames cache in composer message to be a property of the
`ComposerMessage` component instead. Across components, we're more
likely to get a cache miss than a hit since we're caching the entire
recipient array so we can just drop it. If we really need this
optimisation, we should probably use a map and cache the information for
each user instead. However, the request is fairly cheap so we avoid that
optimisation for now.
2. This commit adds a debounce to `_typeReply` as well since we were not
debouncing and the method was being called each time we received the
event.
=> DEV: Improve composer-messages implementation for PMs

app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.hbs, app/assets/javascripts/discourse/app/components/user-tip.js, app/assets/javascripts/discourse/app/lib/user-tips.js, app/assets/javascripts/discourse/app/models/user.js, app/assets/javascripts/discourse/tests/unit/models/user-test.js, app/assets/stylesheets/common/base/user-tips.scss, config/locales/client.en.yml
- Add an icon to the bootstrap user tip to draw attention
- Remove the second "don't show user tip" button from every user tip
=> UX: Improve user tips

app/controllers/sidebar_sections_controller.rb, app/models/sidebar_section.rb, config/site_settings.yml, spec/requests/sidebar_sections_controller_spec.rb
Custom sidebar section can have maximum of 50 links
=> SECURITY: limit amount of links in custom sidebar section

plugins/chat/app/controllers/chat/api/channel_threads_controller.rb, plugins/chat/app/models/chat/threads_view.rb, plugins/chat/app/serializers/chat/thread_list_serializer.rb, plugins/chat/app/services/chat/lookup_channel_threads.rb, plugins/chat/assets/javascripts/discourse/components/chat-browse-view.hbs, plugins/chat/assets/javascripts/discourse/components/chat-browse-view.js, plugins/chat/assets/javascripts/discourse/components/chat-channel-members-view.hbs, plugins/chat/assets/javascripts/discourse/components/chat-channel-members-view.js, plugins/chat/assets/javascripts/discourse/components/chat-channel.js, plugins/chat/assets/javascripts/discourse/components/chat/thread-list.hbs, plugins/chat/assets/javascripts/discourse/components/chat/thread-list.js, plugins/chat/assets/javascripts/discourse/components/chat/thread-list/item.hbs, plugins/chat/assets/javascripts/discourse/lib/chat-threads-manager.js, plugins/chat/assets/javascripts/discourse/lib/collection.js, plugins/chat/assets/javascripts/discourse/models/chat-channel.js, plugins/chat/assets/javascripts/discourse/services/chat-api.js, plugins/chat/assets/javascripts/discourse/services/chat-tracking-state-manager.js, plugins/chat/spec/services/chat/lookup_channel_threads_spec.rb, plugins/chat/spec/system/page_objects/chat/components/thread_list.rb
=> WIP: threads list pagination

app/assets/javascripts/discourse/app/widgets/summary-box.js
=> FIX: Display the whole summary when it consists of multiple <p> tags.

app/assets/stylesheets/common/base/sidebar.scss
=> UX: fix icon warning position in sidebar modal

plugins/chat/assets/stylesheets/common/chat-drawer.scss
=> FIX: s/--border-radius-large/--d-border-radius-large/

app/assets/javascripts/discourse/app/widgets/summary-box.js, app/assets/javascripts/discourse/app/widgets/toggle-topic-summary.js, config/locales/client.en.yml
=> FEATURE: Let users collapse the topic inline summary

app/assets/javascripts/discourse/app/widgets/admin-problems-notification-item.js
=> FIX: add the required widget for admin-problems notification item

docs/INSTALL-email.md
Added requisite SMTP parameters to be retrieved from the Mailjet Account page
=> DEV: Include details for Mailjet SMTP configs

plugins/chat/assets/javascripts/discourse/components/chat/modal/move-message-to-channel.js
=> FIX: Close modal after moving message to channel

lib/plugin/metadata.rb
=> Add discourse-ai plugin

app/assets/stylesheets/common/components/keyboard_shortcuts.scss
Firefox needed some prodding to be full width when possible.
=> UX: firefox fix for shorthand modal width

app/assets/javascripts/discourse/app/widgets/summary-box.js, app/assets/javascripts/discourse/app/widgets/toggle-topic-summary.js, app/controllers/topics_controller.rb, config/locales/client.en.yml
=> UX: Point that topic summaries are generated by an AI

config/locales/server.en.yml
Follow-up to b7196888876306011a8b1bd4ac944aed851615b3
=> DEV: Update copy for legacy navigation menu warning

.github/workflows/tests.yml, spec/rails_helper.rb
Port of 77b4e42f61bcbd616126dcf5b92480ff83fa00ab from `main` branch.
=> FIX: specify chrome version (#22681)

app/assets/javascripts/discourse/app/components/modal/topic-bulk-actions.hbs, app/assets/javascripts/discourse/app/components/modal/topic-bulk-actions.js, app/assets/javascripts/discourse/app/components/topic-list.js, app/assets/javascripts/discourse/app/controllers/full-page-search.js, app/assets/javascripts/discourse/app/lib/plugin-api.js, app/assets/javascripts/discourse/app/routes/application.js, app/assets/javascripts/discourse/app/services/modal.js, app/assets/javascripts/discourse/tests/acceptance/mobile-topic-bulk-actions-test.js, app/assets/javascripts/discourse/tests/acceptance/search-full-test.js, app/assets/javascripts/discourse/tests/acceptance/topic-bulk-actions-test.js, app/assets/javascripts/discourse/tests/acceptance/user-activity-read-test.js, app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
=> DEV: Migrate topic-bulk-actions to the new modal API

app/assets/javascripts/discourse/app/widgets/summary-box.js
=> UX: Show the info icon outside the tooltip

app/assets/javascripts/discourse/app/widgets/summary-box.js, spec/system/topic_summarization_spec.rb
=> DEV: disambiguate system spec find to prevent flakyness

app/assets/javascripts/discourse/app/templates/badges/show.hbs
See: https://github.com/discourse/discourse/pull/22385
=> DEV: Remove the last/only use of inline-date helper

app/assets/javascripts/discourse/app/components/sidebar.hbs, app/assets/javascripts/discourse/app/components/sidebar.js, app/assets/javascripts/discourse/app/components/sidebar/switch-panel-buttons.hbs, app/assets/javascripts/discourse/app/components/sidebar/switch-panel-buttons.js, app/assets/javascripts/discourse/app/lib/sidebar/custom-sections.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js, config/locales/server.en.yml, config/site_settings.yml
SiteSetting which allows to position switch panels buttons at the top or the bottom of the Sidebar.
=> FEATURE: ability to position switch panel buttons

app/assets/javascripts/admin/addon/controllers/admin-customize-colors-show.js, app/assets/javascripts/admin/addon/controllers/admin-customize-colors.js, app/assets/javascripts/admin/addon/controllers/admin-customize-themes-edit.js, app/assets/javascripts/admin/addon/controllers/admin-dashboard-general.js, app/assets/javascripts/admin/addon/controllers/admin-dashboard.js
72edb727 updated these to point to the router service, but the method name also needed to be changed from replaceRoute -> replaceWith
=> FIX: Correct router service call from some admin controllers

app/assets/javascripts/discourse/app/lib/hashtag-types/category.js, app/assets/javascripts/discourse/tests/acceptance/css-generator-test.js, plugins/chat/test/javascripts/acceptance/hashtag-css-generator-test.js
https://meta.discourse.org/t/hashtag-bullet-for-subcategories-has-colours-reversed/272578
=> UX: category hashtag colors order fix

app/assets/javascripts/discourse/app/services/network-connectivity.js
=> FIX: Looping attempt to reconnect in network connectivity service

app/assets/javascripts/discourse/app/widgets/header.js, app/assets/stylesheets/common/base/header.scss, app/assets/stylesheets/mobile/_index.scss, app/assets/stylesheets/mobile/ring.scss
=> UX: Remove ring from avatar for a new user

app/assets/javascripts/discourse/tests/acceptance/d-lightbox-test.js, app/assets/javascripts/discourse/tests/acceptance/sidebar-narrow-desktop-test.js
=> DEV: Use `waitFor` instead of `waitUntil`

config/locales/client.en.yml
This PR removes unnecessary ellipsis in the "Summarizing using AI" description.
**Before**
**After**
=> FIX: Remove unnecessary ellipsis

.template-lintrc.js, app/assets/javascripts/discourse/app/components/modal/history/topic-footer.hbs, app/assets/javascripts/discourse/app/templates/preferences.hbs, plugins/chat/assets/javascripts/discourse/components/chat-emoji-picker.hbs
=> DEV: Fix no-negated-condition linting issues

app/assets/javascripts/discourse/tests/acceptance/topic-test.js, app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js, app/assets/javascripts/discourse/tests/integration/components/input-size-test.js
=> DEV: Enable some of the skipped Firefox tests

Gemfile.lock, lib/tasks/emoji.rake, spec/support/dom_matcher.rb
=> DEV: Update minitest to 5.19.0

plugins/chat/db/migrate/20230721025249_remove_experimental_site_setting_for_threads.rb
=> DEV: Remove experimental setting row for chat threads

app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js, app/assets/javascripts/discourse/tests/acceptance/keyboard-shortcuts-test.js
This has been broken for a long time (since 04a63cfaaa)
=> FIX: Share topic shortcut (shift+s)

app/assets/javascripts/admin/addon/controllers/admin-site-settings.js, app/assets/javascripts/admin/addon/templates/site-settings.hbs, app/assets/javascripts/discourse/tests/acceptance/admin-site-settings-test.js
=> FIX: Toggling overridden settings broke in #21572

app/assets/javascripts/discourse/tests/integration/components/admin-theme-settings-editor-test.js
=> FIX: fix flaky test from settings editor PR

app/assets/javascripts/discourse/tests/integration/components/admin-theme-settings-editor-test.js
See
https://github.com/discourse/discourse/actions/runs/5683868303/job/15405355263
and https://github.com/discourse/discourse/actions/runs/5684998320/job/15408941916
=> DEV: Skip flaky QUnit tests

app/assets/stylesheets/common/base/user-tips.scss
=> FIX: Tweak right arrow position; set other arrow placements to default

app/assets/stylesheets/common/select-kit/multi-select.scss
Input font size was too small.
=> UX: More tweaks to compact tag picker

plugins/chat/lib/chat/messages_exporter.rb
See https://github.com/discourse/discourse/pull/22854#discussion_r1277542736.
=> DEV: a better way of picking of the earliest date

lib/excerpt_parser.rb
Follow up to: a8c504aee43f2b5589fe6fe3af14012983c393e6
See: https://github.com/discourse/discourse/pull/22829#discussion_r1277747036
=> DEV: Update code comment wording

plugins/chat/config/locales/client.en.yml, plugins/chat/config/locales/server.en.yml
=> FIX: Chat translation minor issues

app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs, app/assets/javascripts/discourse/app/components/badge-card.hbs, config/locales/client.en.yml, plugins/discourse-narrative-bot/config/locales/server.en.yml
=> I18n fixes

app/assets/stylesheets/common/base/topic-post.scss
This reverts commit 507551ea7322f2b868f96ca5871a16ff4e59edb4.
=> Revert "UX: fix alignment extra buttons in post controls"

app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.hbs, app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.js, app/assets/javascripts/discourse/app/components/user-tip.js, app/assets/javascripts/discourse/app/lib/user-tips.js, app/assets/stylesheets/common/base/user-tips.scss, config/locales/client.en.yml
=> UX: Move Admin Guide link to URL

script/import_scripts/lithium.rb
=> DEV: Remove redundant case in import script

app/assets/stylesheets/common/components/d-lightbox.scss
=> UX: fix long image titles in experimental lightbox

app/models/global_setting.rb, config/database.yml, config/discourse_defaults.conf
It doesn't actually do anything.
=> DEV: Remove db_timeout setting

app/assets/javascripts/discourse/app/components/more-topics.js
=> FIX: Default to the first list if the preferred one is empty

app/assets/javascripts/admin/addon/components/modal/delete-user-posts-progress.hbs, app/assets/javascripts/admin/addon/components/modal/delete-user-posts-progress.js, app/assets/javascripts/admin/addon/controllers/admin-user-index.js, app/assets/javascripts/admin/addon/controllers/modals/admin-delete-user-posts-progress.js, app/assets/javascripts/admin/addon/templates/modal/admin-delete-user-posts-progress.hbs, app/assets/javascripts/discourse/app/services/modal.js
https://github.com/discourse/discourse/assets/50783505/414ffcc5-06e9-470f-b160-83b4c12bbb96
=> DEV: Convert `delete-user-posts-progress` modal to component-based API

app/assets/javascripts/discourse/app/modifiers/auto-focus.js, app/assets/javascripts/truth-helpers/addon/helpers/add.js, plugins/poll/assets/javascripts/discourse/components/modal/poll-ui-builder.hbs, plugins/poll/assets/javascripts/discourse/components/modal/poll-ui-builder.js, plugins/poll/assets/stylesheets/common/poll-ui-builder.scss, plugins/poll/assets/stylesheets/desktop/poll-ui-builder.scss
1. recent css regression related to modal upgrade
2. autofocus and on-enter regressions
3. array related linting issue (reliance on Ember's firstObject/lastObject)
=> FIX: Poll builder UI issues

app/assets/javascripts/discourse/app/controllers/topic.js, app/assets/javascripts/discourse/app/services/composer.js, plugins/discourse-local-dates/assets/javascripts/discourse/components/discourse-local-dates-create-form.js
This was forgotten during the work in 22991bba44ffae62d72bdb833787f73f17a8f6bf
=> DEV: Update composer service to inherit from Service, not Controller

spec/requests/api/users_spec.rb
=> DEV: Document additional parameters for admin users list API

.template-lintrc.js, app/assets/javascripts/admin/addon/components/modal/merge-users-prompt.hbs, app/assets/javascripts/admin/addon/controllers/admin-user-fields.js, app/assets/javascripts/admin/addon/templates/user-fields.hbs, app/assets/javascripts/discourse/app/components/emoji-picker.hbs, app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.hbs, plugins/chat/assets/javascripts/discourse/components/chat-channel-title.hbs, plugins/chat/assets/javascripts/discourse/components/chat-emoji-picker.hbs, plugins/styleguide/assets/javascripts/discourse/components/sections/atoms/05-input-fields.hbs, plugins/styleguide/assets/javascripts/discourse/components/sections/atoms/dropdowns.hbs
and remove more linting exemptions
=> DEV: Fix array-related linting issues in templates

plugins/checklist/assets/javascripts/discourse/initializers/checklist.js, plugins/checklist/config/locales/server.en.yml, plugins/checklist/test/javascripts/lib/checklist-test.js
=> DEV: Use async/await in checklist

app/assets/javascripts/discourse/app/controllers/navigation/filter.js, app/assets/javascripts/discourse/app/templates/navigation/filter.hbs
Temporary outlet for navigation filter for /filter page. In addition, copy button and reset button were added to core.
https://github.com/discourse/discourse/assets/72780/454f2bf0-2501-4b69-b33c-8b53bda0c6de
=> DEV: experimental outlet for navigation filter

app/assets/javascripts/discourse/app/app.js, app/assets/javascripts/discourse/app/initializers/dynamic-route-builders.js, app/assets/javascripts/discourse/app/initializers/inject-discourse-objects.js, app/assets/javascripts/discourse/app/routes/build-category-route.js
=> Updates to build-category-route

app/assets/javascripts/discourse/app/components/d-modal.hbs, plugins/poll/assets/javascripts/discourse/components/modal/poll-breakdown.hbs, plugins/poll/assets/javascripts/discourse/components/poll-breakdown-chart.js, plugins/poll/assets/javascripts/discourse/components/poll-breakdown-option.js, plugins/poll/assets/stylesheets/common/poll-breakdown.scss
Some related to the modal api change, some due to chart.js updates
=> FIX: Poll breakdown regressions (stable)

app/assets/javascripts/discourse/app/components/more-topics.hbs, app/assets/javascripts/discourse/app/components/more-topics.js, app/assets/javascripts/discourse/app/components/suggested-topics.hbs, app/assets/javascripts/discourse/app/components/suggested-topics.js, app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js, app/assets/stylesheets/common/base/topic.scss, app/assets/stylesheets/desktop/topic.scss
=> FIX: Display browse more message as long as there are suggested topics

app/assets/javascripts/discourse/app/components/d-button.gjs, app/assets/javascripts/discourse/app/components/form-template-field/upload.js, app/assets/javascripts/discourse/app/components/modal/bookmark.js, app/assets/javascripts/discourse/app/components/modal/second-factor-backup-edit.js, app/assets/javascripts/discourse/app/components/search-menu.js, app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.js, package.json, plugins/chat/assets/javascripts/discourse/initializers/chat-sidebar.js, yarn.lock
see https://github.com/discourse/eslint-config-discourse/pull/39
=> DEV: Introduce decorator-position lint rule

app/assets/javascripts/discourse/app/initializers/dynamic-route-builders.js, app/assets/javascripts/discourse/app/routes/build-topic-route.js
(to be rebased-and-merged)
Will be easiest to review with whitespace changes hidden: https://github.com/discourse/discourse/pull/22980/files?diff=split&w=1)
=> Refactor build-topic-route

app/assets/javascripts/discourse/app/components/mount-widget.hbs, app/assets/javascripts/discourse/app/widgets/render-glimmer.js, app/assets/javascripts/discourse/tests/integration/components/widgets/render-glimmer-test.js
=> DEV: Introduce dynamic wrapper attributes in RenderGlimmer

plugins/chat/lib/chat/review_queue.rb, plugins/chat/spec/lib/chat/review_queue_spec.rb
=> FIX: Don't create a reviewable when sending PM to user in chat

app/assets/javascripts/discourse/app/routes/discovery-categories.js, app/assets/javascripts/discourse/app/routes/discovery-filter.js, app/assets/javascripts/discourse/app/routes/discovery.js
=> DEV: Convert discovery routes to native class syntax

app/assets/javascripts/discourse/app/controllers/full-page-search.js, app/assets/javascripts/discourse/tests/acceptance/search-mobile-test.js, app/controllers/search_controller.rb, spec/requests/search_controller_spec.rb
Reported in https://meta.discourse.org/t/-/222735
=> FIX: Search by tag context was broken

spec/system/page_objects/modals/login.rb
=> DEV: Added page object for the login modal

spec/system/page_objects/components/select_kit.rb
=> DEV: Added visible/hidden methods on the SelectKit page component

spec/rails_helper.rb
Followup to edb276b9a95845e81c9b799cb66c72103115c003
True spec failures now show the proper error:
```ruby
it "does a thing" do
visit("/latest")
expect(page).to have_css("body.nonexistant-class")
```
But if the spec would've passed, then the timeout error is surfaced:
```ruby
it "does a thing" do
visit("/latest")
page.has_css?("body.nonexistant-class")
```
=> DEV: Only reveal capybara finder timeouts if the spec otherwise passes

plugins/chat/assets/stylesheets/common/chat-composer-button.scss, plugins/chat/assets/stylesheets/common/chat-composer-dropdown.scss
* animation for open/close toggle
* slightly scaling on hover for toggle and emoji btn
=> UX: micro animations chat input

app/assets/javascripts/discourse/app/templates/topic.hbs
=> DEV: Add plugin outlet after TopicNavigation
