discourse/discourse

- app/assets/javascripts/discourse/app/lib/logout.js
- app/assets/javascripts/discourse/tests/acceptance/user-test.js
> DEV: Don't stub `logout` function

- spec/requests/api/schemas/json/user_update_request.json
These parameters are not allowed for user update.
> DEV: Fix user update api docs

- app/models/group.rb
- app/models/user.rb
- lib/external_upload_helpers.rb
- lib/guardian.rb
- lib/onebox/engine/allowlisted_generic_onebox.rb
- lib/pretty_text.rb
- lib/quote_comparer.rb
- lib/tasks/typepad.thor
- script/import_scripts/socialcast/create_title.rb
- spec/lib/quote_comparer_spec.rb
> DEV: Correct `Style/RedundantReturn` rubocop issues

- app/assets/stylesheets/common/components/sidebar/edit-navigation-menu/tags-modal.scss
> UX: align tags to top in modal

- plugins/chat/assets/stylesheets/common/chat-composer-button.scss
- plugins/chat/assets/stylesheets/common/chat-composer-dropdown.scss
> UX: add transition

- lib/plugin/metadata.rb
https://github.com/discourse/discourse-jira
> DEV: Add jira plugin to official list of plugins

- .github/workflows/linting.yml
- lib/tasks/backfill.thor
- lib/tasks/populate.thor
- lib/tasks/typepad.thor
> DEV: Format .thor files

- plugins/chat/assets/javascripts/discourse/components/styleguide/chat-modal-thread-settings.js
> FIX: chat styleguide modal import

- spec/system/page_objects/components/composer.rb
> DEV: Added the category chooser into the composer page object

- spec/system/network_disconnected_spec.rb
> DEV: Skip flaky network disconnected spec

- spec/models/username_validator_spec.rb
> DEV: Make sure max_username_length is within MAX_USERNAME_LENGTH_RANGE

- app/assets/javascripts/discourse/app/components/more-topics.hbs
- app/assets/javascripts/discourse/app/components/more-topics.js
- app/assets/javascripts/discourse/app/components/related-messages.hbs
- app/assets/javascripts/discourse/app/components/related-messages.js
- app/assets/javascripts/discourse/app/components/suggested-topics.hbs
- app/assets/javascripts/discourse/app/components/suggested-topics.js
- app/assets/javascripts/discourse/app/templates/topic.hbs
- app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js
- app/assets/stylesheets/common/base/topic.scss
- app/assets/stylesheets/common/components/_index.scss
- app/assets/stylesheets/common/components/more-topics.scss
- app/assets/stylesheets/desktop/topic-post.scss
- app/assets/stylesheets/desktop/topic.scss
- app/assets/stylesheets/mobile/components/_index.scss
- app/assets/stylesheets/mobile/components/more-topics.scss
- app/assets/stylesheets/mobile/topic-post.scss
> UX: Use pill design on both mobile and desktop

- app/assets/javascripts/discourse/app/components/related-messages.js
> FIX: Inject currentUser service for related-messages

- app/assets/stylesheets/common/base/header.scss
This PR removes the rounded corners on the bootstrap mode button to align with standard Discourse
> UX: remove boostrap mode button rounded corners

- plugins/chat/assets/stylesheets/common/chat-composer-dropdown.scss
Changed animation speed + range a bit to look better
> UX: improved animation

- app/models/category.rb
- app/models/developer.rb
- app/models/theme.rb
> DEV: Make every DistributedCache lazily instantiated

- spec/system/page_objects/components/composer.rb
> DEV: Add close method to composer component

- plugins/chat/assets/javascripts/discourse/modifiers/chat/resizable-node.js
> FIX: Resize-modifier event listener cleanup

- app/assets/javascripts/discourse-common/addon/utils/decorators.js
- app/assets/javascripts/discourse/app/components/d-popover.js
- app/assets/javascripts/discourse/app/components/date-input.js
- app/assets/javascripts/discourse/app/components/date-time-input-range.js
- app/assets/javascripts/discourse/app/controllers/review-settings.js
- app/assets/javascripts/discourse/app/helpers/raw.js
- app/assets/javascripts/discourse/app/lib/cookie.js
- app/assets/javascripts/discourse/app/lib/highlight-html.js
- app/assets/javascripts/discourse/app/models/topic-list.js
- app/assets/javascripts/discourse/app/routes/build-topic-route.js
- app/assets/javascripts/discourse/app/routes/tag-show.js
- app/assets/javascripts/discourse/app/routes/topic.js
- app/assets/javascripts/discourse/app/services/screen-track.js
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/tests/acceptance/admin-site-settings-test.js
- app/assets/javascripts/discourse/tests/helpers/presence-pretender.js
- app/assets/javascripts/discourse/tests/unit/lib/i18n-test.js
- app/assets/javascripts/select-kit/addon/components/email-group-user-chooser.js
- plugins/poll/assets/javascripts/discourse/widgets/discourse-poll.js
Same behavior, more consistent and concise code.
> DEV: Use object spread instead of `Object.assign({}, …)`

- app/assets/javascripts/discourse/app/components/modal/user-status.hbs
- app/assets/javascripts/discourse/app/components/modal/user-status.js
- app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.js
- app/assets/javascripts/discourse/app/controllers/preferences/account.js
- app/assets/stylesheets/common/modal/user-status.scss
> DEV: converts user-status modal to component

- app/models/user_search.rb
- lib/search.rb
> DEV: Add plugin modifier locations for user search locations

- app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.js
- app/assets/javascripts/discourse/app/components/search-menu/search-term.js
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/stylesheets/common/base/search-menu.scss
There was a few outstanding items that needed cleaning up.
https://github.com/discourse/discourse/assets/50783505/e92e4d6f-f42c-4357-8f13-8fa9f1024ade
_getting to zero search characters would automatically clear the search context_
https://github.com/discourse/discourse/assets/50783505/fd805dfd-576d-4e32-b6b5-5b93c25a5782
> DEV: Finalize glimmer search menu

- plugins/chat/assets/javascripts/discourse/chat-route-map.js
- plugins/chat/assets/javascripts/discourse/routes/chat-channel-decorator.js
- plugins/chat/lib/chat/user_notifications_extension.rb
- plugins/chat/plugin.rb
Removes code which had TODOs to be removed in past releases.
> DEV: removes deprecated code

- lib/tasks/assets.rake
- lib/tasks/maxminddb.rake
> DEV: Extract maxmind refresh logic to its own task

- README.md
- https://blog.discourse.org/2023/08/discourse-3-1-is-here/
- t/109311
> DEV: update readme.md for Discourse 3.1

- spec/system/page_objects/pages/topic.rb
Adding a method for replying via the topic footer buttons, for a plugin.
> DEV: Add method for page object

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
> FIX: Add site name to sitelinks structured data

- app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
- app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
- app/assets/javascripts/discourse/tests/integration/components/select-kit/mini-tag-chooser-test.js
- config/locales/client.en.yml
- config/locales/server.en.yml
Also adds a note for translators for the `type_to_filter` string.
> DEV: Use ellipsis instead of three dots

- lib/plugin/metadata.rb
Part of making these plugins official.
Dependent on: https://github.com/discourse/.github/pull/114
> DEV: add geoblocking and tag-by-group plugins

- app/assets/javascripts/discourse/tests/unit/lib/plugin-api-test.js
> DEV: Add missing `pluginId` to a `modifyClass` test

- app/assets/javascripts/discourse/app/controllers/user-topics-list.js
> DEV: Update user-topics-list to native class syntax

- app/assets/javascripts/admin/addon/components/modal/badge-preview.hbs
- app/assets/javascripts/admin/addon/components/modal/badge-preview.js
- app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
- app/assets/javascripts/discourse/tests/acceptance/admin-badges-show-test.js
- app/assets/javascripts/discourse/tests/fixtures/badges-fixture.js
> FIX: Badge preview not displaying grant count

- plugins/chat/assets/stylesheets/common/chat-composer-button.scss
- plugins/chat/assets/stylesheets/common/chat-composer-separator.scss
This reverts commit 3bcbb2444ac7bfddc2d6ef40d6d6d48a6af6c79f.
> Revert "UX: chat composer (#23267)"

- app/assets/stylesheets/common/base/search-menu.scss
Remove overflow hidden, which is causing issues on windows
> FIX: Update search-menu.scss

- app/assets/javascripts/discourse/app/components/summary-box.js
> FIX: Typo in summary URL

- app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
- app/assets/javascripts/discourse/app/lib/utilities.js
- app/assets/javascripts/discourse/app/widgets/post-small-action.js
- app/assets/javascripts/discourse/app/widgets/post.js
- app/assets/stylesheets/common/base/topic-post.scss
- app/assets/stylesheets/common/components/keyboard_shortcuts.scss
This reverts commit 9b3fc8081a62c6cdcfa28a9f0a9a28fea13889df. Will rework it shortly, this commit had some unwanted side effects.
> Revert "A11Y: Improve setting focus to post"

- app/assets/javascripts/discourse/app/components/modal/move-to-topic.js
> Update move to topic modal cvx

- app/assets/javascripts/discourse/app/components/bulk-select-toggle.hbs
- app/assets/javascripts/discourse/app/components/d-navigation.hbs
- app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
- app/assets/javascripts/discourse/app/templates/invites/show.hbs
- app/assets/javascripts/discourse/app/templates/user/messages.hbs
- plugins/chat/assets/javascripts/discourse/components/chat-drawer/header/full-page-button.hbs
> DEV: Remove redundant braces

- app/assets/javascripts/discourse/app/instance-initializers/auth-complete.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/tests/acceptance/auth-complete-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
> FEATURE: Plugin API to skip auth-complete logic

- app/assets/javascripts/discourse/app/templates/modal/create-account.hbs
- app/assets/javascripts/discourse/app/templates/modal/login.hbs
> DEV: add plugin outlets to create/login

- app/assets/javascripts/discourse/app/templates/mobile/modal/login.hbs
Forgot we had a separate mobile template for this! follow-up to 6b37544
> DEV: add plugin outlet to mobile login

- app/assets/javascripts/admin/addon/components/modal/start-backup.hbs
- app/assets/javascripts/admin/addon/components/modal/start-backup.js
- app/assets/stylesheets/common/admin/backups.scss
- config/locales/client.en.yml
Also, this PR will introduce a new checkbox in the modal window to manage whether the uploads should be included in the backup or not.
> UX: display warning message when uploads are not included in backup.

- spec/fixtures/emails/email_to_group_email_username_auto_generated.eml
For use with discourse-automation feature
> DEV: Add email fixture

- app/assets/javascripts/discourse/app/templates/user/messages.hbs
This allows for adding a custom button in a customer theme.
> DEV: new `user-messages-control-bottom` outlet

- spec/system/theme_qunit_spec.rb
This was intended to be included as part of c7dce90f43ec15f93b95e719d3fafca50e40edb1
> DEV: Introduce theme-qunit system spec

- app/assets/javascripts/discourse-plugins/index.js
- app/assets/javascripts/discourse/config/deprecation-workflow.js
- app/assets/javascripts/js-processor.js
- app/assets/javascripts/patches/ember-this-fallback+0.3.1.patch
- spec/lib/theme_javascript_compiler_spec.rb
- spec/models/theme_field_spec.rb
> DEV: Enable ember-this-fallback in themes

- app/assets/javascripts/package.json
- app/assets/javascripts/patches/babel-plugin-debug-macros+0.3.4.patch
- app/assets/javascripts/yarn.lock
> DEV: Move from babel-plugin-debug-macros fork to in-repo patch

- app/assets/javascripts/discourse/app/components/modal/login/local-login-form.js
Introduced in bb2d1f8703ab63f5eb504d37f926670583ca8288
> FIX: An incorrect import

- app/assets/javascripts/admin/addon/components/theme-upload-add.js
> DEV: Allow `uploadUrl` to be set dynamically on `theme-upload-add` modal

- app/assets/javascripts/discourse/app/components/topic-list-item.js
backport of https://github.com/discourse/discourse/commit/b8d6c9bd45d771162d20b073cbb5ec2ff89f37d8
> Fix: navigate to topic stable

- app/assets/javascripts/discourse/app/models/user.js
A follow up to f73d8346c25a65d8543986aef25cfce70190d693
> DEV: Use a standard service injection

- plugins/chat/assets/stylesheets/common/chat-message-creator.scss
Juicing Discourse, one superfluous micro-animation at the time
> UX:  popping animation for adding users

- app/assets/javascripts/admin/addon/components/modal/install-theme.js
> DEV: Update `install-theme` modal extension points

- lib/tasks/docker.rake
Broke in ef73d208323a43467fdd3367be0f413c965a398b
> DEV: Fix broken conditional in `docker:test` Rake task

- app/models/user.rb
- lib/guardian.rb
- lib/guardian/category_guardian.rb
> DEV: Remove unused topic_create_allowed_category_ids

- app/assets/javascripts/discourse/app/components/search-menu/results/assistant.hbs
- app/assets/javascripts/discourse/app/components/search-menu/results/initial-options.hbs
- app/assets/javascripts/discourse/tests/acceptance/glimmer-search-test.js
> FIX: Render 'In topic context' search results at the correct time

- app/assets/javascripts/discourse/tests/integration/helpers/category-badge-test.js
- app/assets/javascripts/discourse/tests/integration/helpers/d-icon-test.js
- app/assets/javascripts/discourse/tests/integration/helpers/html-safe-test.js
> DEV: Move helper tests to the correct directory

- spec/system/scroll_manager_service_spec.rb
> DEV: Remove unused pageobject from scroll_manager_service_spec

- app/assets/javascripts/discourse/app/components/uppy-image-uploader.js
- app/assets/javascripts/discourse/app/routes/user-private-messages-user-new.js
- app/assets/javascripts/discourse/app/routes/user-private-messages-user-unread.js
- app/assets/javascripts/discourse/tests/unit/lib/deprecated-test.js
- app/assets/javascripts/discourse/tests/unit/lib/ember-action-modifer-test.js
- app/assets/javascripts/discourse/tests/unit/lib/ember-events-test.js
> DEV: Use `import x` rather than `import { default as x }`

- app/assets/javascripts/discourse/app/components/invite-link-panel.js
> DEV: Remove unused files

- app/assets/javascripts/admin/addon/components/modal/install-theme.hbs
> FIX: Double footer in install-theme modal

- app/assets/javascripts/discourse/tests/acceptance/modal-service-test.gjs
- app/assets/javascripts/discourse/tests/integration/components/d-modal-test.gjs
> DEV: Update d-modal tests to gjs

- app/assets/javascripts/discourse/tests/integration/components/widgets/home-logo-test.gjs
> DEV: Convert home-logo-test to gjs

- lib/tasks/docker.rake
> DEV: Run core system tests by default in docker test image

- spec/system/emojis/emoji_deny_list_spec.rb
- spec/system/new_topic_list_spec.rb
cc: @OsamaSayegh (new_topic_list_spec.rb), @dbattersby (emoji_deny_list_spec.rb)
> DEV: Skip flaky specs

- lib/tasks/release_note.rake
> DEV: Add link to PR when generating release notes

- plugins/chat/assets/javascripts/discourse/components/chat-upload.hbs
> FIX: chat layout shift when loading videos

- app/assets/javascripts/discourse/app/instance-initializers/animated-images-pause-on-click.js
- app/assets/javascripts/discourse/app/instance-initializers/codeblock-buttons.js
- app/assets/javascripts/discourse/app/instance-initializers/hashtag-post-decorations.js
- app/assets/javascripts/discourse/app/instance-initializers/image-aspect-ratio.js
- app/assets/javascripts/discourse/app/instance-initializers/onebox-decorators.js
- app/assets/javascripts/discourse/app/instance-initializers/post-decorations.js
- app/assets/javascripts/discourse/app/lib/lazy-load-images.js
- app/assets/javascripts/discourse/app/widgets/decorator-helper.js
- app/assets/javascripts/discourse/tests/acceptance/topic-post-decorate-cooked-test.js
- plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
- plugins/checklist/assets/javascripts/discourse/initializers/checklist.js
- plugins/discourse-lazy-videos/assets/javascripts/initializers/lazy-videos.js
- plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js
- plugins/poll/assets/javascripts/discourse/initializers/extend-for-poll.js
These are no longer required per https://github.com/discourse/discourse/pull/23543
> DEV: Remove decorateCookedElement id parameters

- app/assets/javascripts/discourse/app/instance-initializers/animated-images-pause-on-click.js
This was causing issues on chat which is not properly supporting this for now.
> FIX: scope animated-images-pause to topic-post

- app/models/theme.rb
This should have been included in f6326d0
> DEV: Bump theme compiler version for max svg sprite size change

- app/assets/javascripts/discourse/app/components/search-menu.hbs
- app/assets/javascripts/discourse/app/components/search-menu.js
- app/assets/javascripts/discourse/app/components/search-menu/menu-panel-contents.hbs
- app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.js
- app/assets/javascripts/discourse/app/components/search-menu/results/initial-options.js
- app/assets/javascripts/discourse/app/services/search.js
- app/assets/javascripts/discourse/app/widgets/header.js
> DEV: Move relevant glimmer search menu logic to service

- app/assets/javascripts/discourse/app/components/invite-panel.js
share-and-invite modal doesn't seem to use it anymore
> DEV: Remove unused `userInvitedShow` logic

- app/assets/javascripts/discourse/app/services/emoji-store.js
> DEV: Convert emoji-store into a native class

- app/assets/javascripts/discourse/app/components/global-notice.js
> DEV: Convert global-notice to a native class

- plugins/chat/assets/javascripts/discourse/components/chat-channel-row.gjs
- plugins/chat/assets/stylesheets/common/chat-channel-row.scss
- plugins/chat/assets/stylesheets/mobile/chat-channel-row.scss
> UI: tweaks remove channel animation

- app/assets/javascripts/discourse/app/components/modal/tag-upload.hbs
- app/assets/javascripts/discourse/app/controllers/tags-index.js
- app/assets/javascripts/discourse/app/services/modal.js
- app/assets/javascripts/discourse/app/templates/modal/tag-upload.hbs
> DEV: Convert tag-upload to the new modal API

- plugins/chat/assets/stylesheets/common/chat-channel-row.scss
- plugins/chat/assets/stylesheets/mobile/chat-index.scss
Fixing misalignment of unread notifications and timestamp
> UX: chat-channel-row alignment

- app/assets/javascripts/discourse/app/loader-shims.js
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn.lock
This will allow us to use `<template>` for route templates. For more details, see the README at https://github.com/discourse/ember-route-template
> DEV: Install ember-route-template

- app/models/post.rb
- spec/models/post_spec.rb
This commit adds support for filtering posts reports by multiple categories.
> FEATURE: allow filtering posts report by multiple categories

- plugins/chat/assets/javascripts/discourse/components/chat-channel.js
- plugins/chat/assets/javascripts/discourse/components/chat-composer.js
- plugins/chat/assets/javascripts/discourse/components/chat-message-actions-mobile.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-message.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-thread.js
- plugins/chat/assets/javascripts/discourse/components/chat/selection-manager.js
- plugins/chat/assets/javascripts/discourse/components/styleguide/chat-message.js
- plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
- plugins/chat/assets/javascripts/discourse/models/chat-channel.js
- plugins/chat/assets/javascripts/discourse/models/chat-message.js
- plugins/chat/assets/javascripts/discourse/models/chat-thread.js
- plugins/chat/assets/javascripts/discourse/services/chat-tracking-state-manager.js
- plugins/chat/test/javascripts/unit/lib/chat-emoji-reaction-store-test.js
- plugins/chat/test/javascripts/unit/services/chat-channel-info-route-origin-manager-test.js
- plugins/chat/test/javascripts/unit/services/chat-drafts-manager-test.js
- plugins/chat/test/javascripts/unit/services/chat-drawer-size-test.js
- plugins/chat/test/javascripts/unit/services/chat-emoji-picker-manager-test.js
- plugins/chat/test/javascripts/unit/services/chat-state-manager-test.js
- plugins/chat/test/javascripts/unit/utility/plugin-api-test.js
See 8958b4f76af85ddc89c8a3b6434dcfbd4274d569 for motivation
> DEV: Modernize chat getOwner usage

- app/assets/javascripts/discourse/ember-cli-build.js
> DEV: Enable Embroider build by default

- app/assets/javascripts/discourse/app/components/modal/request-group-membership-form.hbs
- app/assets/javascripts/discourse/app/components/modal/request-group-membership-form.js
- app/assets/javascripts/discourse/tests/integration/components/request-group-membership-form-test.gjs
> FIX: A regression in RequestGroupMembershipForm

- app/assets/javascripts/discourse/app/initializers/dynamic-route-builders.js
- app/assets/javascripts/discourse/app/routes/tag-show.js
- app/assets/javascripts/discourse/app/routes/tags-intersection.js
> DEV: Update tag-show route to native class syntax

- .github/dependabot.yml
> DEV: Group embroider updates in dependabot

- app/assets/javascripts/patches/content-tag+1.1.1.patch
> DEV: Update content-tag patch following version bump

- app/assets/javascripts/discourse/tests/integration/components/composer-editor-test.gjs
> DEV: Convert composer-editor tests to gjs

- app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
- app/assets/javascripts/float-kit/addon/components/d-menu.gjs
> FIX: ensures close arg from d-menu/:content works

- lib/discourse_js_processor.rb
(i.e. non-production, non-test, non-development environments :P like `RAILS_ENV="profile"`)
> DEV: Build theme transpiler in custom envs

- app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/tags-modal.hbs
> UX: Center loading spinner for editing nav menu tags modal

- app/assets/javascripts/discourse/app/services/capabilities.js
This is cleaner to read/write than manually building a POJO
> DEV: Refactor capabilities into native class syntax

- app/assets/javascripts/discourse/app/templates/user/bookmarks.hbs
> DEV: Add body class for user activity bookmarks

- app/assets/javascripts/discourse/app/lib/raw-render-glimmer.js
> DEV: Don't attempt to render to empty element in RawRenderGlimmer

- app/assets/javascripts/discourse/app/models/user.js
- app/assets/javascripts/discourse/app/services/app-events.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/unit/models/composer-test.js
> DEV: Do not manually create app-events on models

- app/assets/javascripts/discourse/app/components/modal/user-status.hbs
- app/assets/javascripts/discourse/app/components/modal/user-status.js
> DEV: Convert user-status modal to a glimmer component

- app/assets/javascripts/discourse/app/lib/webauthn.js
- config/locales/client.en.yml
- lib/discourse_webauthn/authentication_service.rb
- spec/lib/discourse_webauthn/authentication_service_spec.rb
Our inline instructions were out of sync with [the source ](https://w3c.github.io/webauthn/#sctn-verifying-assertion). 
This also adds a `userHandle` check for first factor verification, though first factor is not yet fully implemented.
Followup to #23586
> DEV: Update webauthn authentication flow documentation

- app/assets/javascripts/discourse/app/components/user-menu/items-list.js
- app/assets/javascripts/discourse/app/controllers/preferences/interface.js
- app/assets/javascripts/discourse/app/models/topic-list.js
- app/assets/javascripts/discourse/app/routes/discovery-categories.js
- app/assets/javascripts/discourse/app/services/presence.js
- app/assets/javascripts/discourse/app/widgets/home-logo.js
- app/assets/javascripts/discourse/tests/integration/components/widgets/home-logo-test.gjs
> DEV: Use Session service rather than singleton

- plugins/chat/assets/stylesheets/common/chat-thread-list-item.scss
- plugins/chat/assets/stylesheets/mobile/chat-threads-list.scss
> UX: flat design for thread list

- app/assets/javascripts/admin/addon/components/themes-list-item.hbs
- app/assets/javascripts/admin/addon/components/themes-list.hbs
- app/assets/javascripts/admin/addon/components/themes-list.js
- app/assets/javascripts/discourse/app/components/modal/delete-themes-confirm.hbs
- app/assets/javascripts/discourse/app/components/modal/delete-themes-confirm.js
- app/assets/stylesheets/common/admin/customize.scss
- app/controllers/admin/themes_controller.rb
- config/locales/client.en.yml
- config/routes.rb
- spec/requests/admin/themes_controller_spec.rb
- spec/system/admin_customize_themes_spec.rb
- spec/system/page_objects/modals/delete_themes_confirm.rb
- spec/system/page_objects/pages/admin_customize_themes.rb
Ability to select multiple inactive themes or components and delete them all together.
https://github.com/discourse/discourse/assets/72780/c8cb727d-433f-43af-aa83-6d059c41f576
> FEATURE: delete multiple inactive themes/components

- app/assets/javascripts/patches/content-tag+1.1.2.patch
> DEV: Update the content-tag patch

- app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
- app/assets/javascripts/discourse/app/mixins/uppy-upload.js
> FIX: Fetch csrf token if needed before uploading

- app/assets/javascripts/discourse/app/components/bookmark-list.hbs
- config/locales/client.en.yml
> DEV: Wrap bookmark-list table header in plugin outlet

- app/assets/javascripts/discourse/app/instance-initializers/component-templates.js
> DEV: Add link to gjs template override error

- app/assets/javascripts/discourse/app/components/search-menu/results/types.js
> FIX: Prevent browser refresh when clicking search menu result

- app/assets/javascripts/discourse/app/lib/plugin-api.js
> DEV: Add note about wrapper element to `renderInOutlet` API

- app/assets/stylesheets/common/base/onebox.scss
> FIX: Chat layout shift with GitHub onebox

- app/assets/javascripts/discourse/app/components/conditional-loading-spinner.gjs
> DEV: Add a plugin outlet for conditional-loading-spinner

- app/assets/javascripts/discourse/app/instance-initializers/video-placeholder.js
Have the click target be the entire placeholder instead of just the play
button.
> DEV: Change video placeholder click target

- plugins/chat/spec/system/reply_to_message/smoke_spec.rb
We now create threads on reply so the refresh check is not really necessary as there's nothing special about it anymore. We don't refresh every pages in other tests to check they still work.
Hopefully these changes will prevent few flakeys too.
> DEV: simplify reply to message smoke spec

- spec/system/dismissing_new_spec.rb
- spec/system/page_objects/pages/discovery.rb
> DEV: Add system specs for dismiss new on tag routes

- .github/workflows/tests.yml
Followup to 3f8a85ed49d80b3ff8ce538cd0599f7129571cfc
> DEV: Write execution file for test failures

- plugins/chat/assets/stylesheets/common/chat-message-creator.scss
* removed the border-radius in line with the general style
* small improvement to user-count positioning
> UX: CMD-K style fix

- app/assets/javascripts/admin/addon/templates/email-preview-digest.hbs
- app/assets/javascripts/discourse/tests/acceptance/admin-email-preview-test.js
- app/controllers/posts_controller.rb
- app/controllers/users_controller.rb
- app/models/topic.rb
- config/discourse_defaults.conf
- config/initializers/102-truncate-logs.rb
- lib/discourse_plugin_registry.rb
- lib/guardian/user_guardian.rb
- lib/plugin/instance.rb
- lib/post_creator.rb
- lib/topic_creator.rb
- lib/truncate_logs_formatter.rb
- plugins/chat/app/services/chat/publisher.rb
- plugins/chat/spec/services/chat/publisher_spec.rb
- plugins/poll/lib/poll.rb
- plugins/poll/spec/integration/poll_endpoints_spec.rb
- spec/lib/post_creator_spec.rb
- spec/lib/topic_creator_spec.rb
- spec/lib/truncate_logs_formatter_spec.rb
- spec/models/topic_spec.rb
- spec/requests/posts_controller_spec.rb
- spec/requests/users_controller_spec.rb
> Security fixes for main

- app/assets/javascripts/admin/addon/templates/email-preview-digest.hbs
- app/assets/javascripts/discourse/tests/acceptance/admin-email-preview-test.js
- app/controllers/posts_controller.rb
- app/controllers/users_controller.rb
- app/models/topic.rb
- config/discourse_defaults.conf
- config/initializers/102-truncate-logs.rb
- lib/discourse_plugin_registry.rb
- lib/guardian/user_guardian.rb
- lib/plugin/instance.rb
- lib/post_creator.rb
- lib/topic_creator.rb
- lib/truncate_logs_formatter.rb
- plugins/chat/app/services/chat/publisher.rb
- plugins/chat/spec/services/chat/publisher_spec.rb
- plugins/poll/lib/poll.rb
- plugins/poll/spec/integration/poll_endpoints_spec.rb
- spec/lib/post_creator_spec.rb
- spec/lib/topic_creator_spec.rb
- spec/lib/truncate_logs_formatter_spec.rb
- spec/models/topic_spec.rb
- spec/requests/posts_controller_spec.rb
- spec/requests/users_controller_spec.rb
> Security fixes for stable

- app/assets/stylesheets/common/base/onebox.scss
Also adds a small effect on hover.
https://github.com/discourse/discourse/assets/368961/ea961118-8b51-498c-96a2-42761e23b7d4
> UX: Fix icon color for video placeholder

- app/assets/javascripts/discourse/app/helpers/category-link.js
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/select-kit/addon/components/category-chooser.js
- app/assets/javascripts/select-kit/addon/components/category-drop.js
- app/assets/javascripts/select-kit/addon/components/category-selector.js
- app/assets/stylesheets/common/select-kit/category-selector.scss
- app/controllers/categories_controller.rb
- config/locales/client.en.yml
- config/routes.rb
- config/site_settings.yml
- spec/requests/categories_controller_spec.rb
This makes it work better on sites with many categories.
> FEATURE: Use async search for category dropdown components

- app/assets/javascripts/dialog-holder/addon/services/dialog.js
- app/assets/javascripts/discourse/app/services/logs-notice.js
- app/assets/javascripts/discourse/app/services/pm-topic-tracking-state.js
- app/assets/javascripts/discourse/app/services/store.js
> DEV: Convert remaining core services to native class syntax

- app/assets/stylesheets/common/admin/customize.scss
> UX: improve handling of long theme names in admin

- .github/dependabot.yml
> DEV: Group `@types/*` updates

- lib/tasks/assets.rake
- spec/tasks/assets_precompile_spec.rb
> DEV: Remove the transpilation message

- lib/tasks/themes.rake
> DEV: Precompile the transpiler before `themes:update`

- spec/lib/email/sender_spec.rb
> DEV: Flaky fixes for Email::Sender spec

- app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js
> DEV: Fix `ember/prefer-ember-test-helpers`

- app/assets/javascripts/discourse/tests/acceptance/user-preferences-second-factor-backup-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-preferences-second-factor-test.js
> DEV: Fix `ember/require-valid-css-selector-in-test-helpers`

- app/assets/javascripts/discourse/app/components/user-status-picker.js
- app/assets/javascripts/discourse/app/services/composer.js
> DEV: Fix `ember/no-incorrect-calls-with-inline-anonymous-functions`

- app/assets/javascripts/discourse/tests/acceptance/search-test.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-narrow-desktop-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- app/assets/javascripts/discourse/tests/integration/components/d-lightbox-test.js
> DEV: Fix `ember/no-settled-after-test-helper`

- app/assets/javascripts/admin/addon/components/ace-editor.js
- app/assets/javascripts/admin/addon/components/admin-graph.js
- app/assets/javascripts/admin/addon/components/modal/install-theme.js
- app/assets/javascripts/admin/addon/components/modal/merge-users-progress.js
- app/assets/javascripts/discourse/app/components/d-modal-body.js
- app/assets/javascripts/discourse/app/components/discourse-banner.js
- app/assets/javascripts/discourse/app/components/mobile-nav.js
- app/assets/javascripts/discourse/app/components/modal/bookmark.js
- app/assets/javascripts/discourse/app/components/mount-widget.js
- app/assets/javascripts/discourse/app/components/pending-post.js
- app/assets/javascripts/discourse/app/components/scrolling-post-stream.js
- app/assets/javascripts/discourse/app/components/sidebar.js
- app/assets/javascripts/discourse/app/components/sidebar/more-section-links.js
- app/assets/javascripts/discourse/app/components/sidebar/section-link.js
- app/assets/javascripts/discourse/app/components/sidebar/section.js
- app/assets/javascripts/discourse/app/components/sidebar/user/messages-section.js
- app/assets/javascripts/discourse/app/components/sidebar/user/tags-section.js
- app/assets/javascripts/discourse/app/components/site-header.js
- app/assets/javascripts/discourse/app/components/table-header-toggle.js
- app/assets/javascripts/discourse/app/components/topic-entrance.js
- app/assets/javascripts/discourse/app/components/topic-timeline/container.js
- app/assets/javascripts/discourse/app/components/user-status-picker.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/tests/acceptance/topic-post-decorate-cooked-test.js
- app/assets/javascripts/discourse/tests/integration/components/widgets/render-glimmer-test.js
- app/assets/javascripts/discourse/tests/integration/helpers/raw-test.gjs
and `ember/no-ember-super-in-es-classes`
> DEV: Fix `ember/require-super-in-lifecycle-hooks`

- app/controllers/application_controller.rb
- lib/xml_cleaner.rb
- spec/requests/topics_controller_spec.rb
See https://meta.discourse.org/t/rss-subscription-broken-by-post-content/282415?u=falco
> FIX: Remove invalid chars from feed XMLs

- app/models/topic_list.rb
> DEV: Fix lazy_load_categories for uncategorized topic lists

- plugins/chat/spec/system/channel_members_page_spec.rb
- plugins/chat/spec/system/navigation_spec.rb
> DEV: skips two flakey specs

- lib/tasks/assets.rake
Quote mark inadvertently got removed somehow.
> FIX: missing quote

- plugins/chat/assets/javascripts/discourse/initializers/chat-plugin-decorators.js
Spoiler-alert plugin is now part of core
> FIX: Update path for spoiler-alert plugin

- app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.hbs
- app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.js
- app/assets/javascripts/discourse/app/routes/application.js
- app/assets/javascripts/discourse/app/templates/application.hbs
> DEV: Move `toggleAnonymous` out of app route

- app/assets/javascripts/discourse/app/components/user-field.gjs
- app/assets/javascripts/discourse/app/components/user-field.hbs
> DEV: Convert `user-field` to gjs

- plugins/styleguide/assets/javascripts/discourse/components/sections/atoms/00-typography.gjs
> DEV: Update styleguide to use real i18n helper implementation

- plugins/chat/assets/stylesheets/common/chat-onebox.scss
- plugins/chat/assets/stylesheets/common/chat-transcript.scss
- plugins/chat/config/locales/server.en.yml
- plugins/chat/lib/chat/engine.rb
- plugins/chat/lib/chat/onebox_handler.rb
- plugins/chat/lib/onebox/templates/discourse_chat_channel.mustache
- plugins/chat/lib/onebox/templates/discourse_chat_message.mustache
- plugins/chat/lib/onebox/templates/discourse_chat_thread.mustache
- plugins/chat/spec/lib/chat/onebox_handler_spec.rb
> FEATURE: Add onebox support for chat threads

- app/assets/javascripts/discourse/app/components/post-text-selection.gjs
- app/assets/stylesheets/common/base/topic-post.scss
This changes allows for a faster and smoother experience. It's also less noise while selecting text, and is already how mobile is working.
> UX: improve quote/edit bar's rendering

- app/assets/javascripts/discourse/app/components/discovery/topics.hbs
- app/assets/javascripts/discourse/app/components/discovery/topics.js
- app/assets/javascripts/discourse/app/controllers/discovery/list.js
- app/assets/javascripts/discourse/app/routes/build-category-route.js
- app/assets/javascripts/discourse/app/routes/build-topic-route.js
- app/assets/javascripts/discourse/app/routes/tag-show.js
- app/assets/javascripts/discourse/app/services/discovery.js
- app/assets/javascripts/discourse/app/templates/discovery/list.hbs
> (discovery-named-outlets) Move all route -> controller data to `model`

- app/assets/javascripts/discourse/app/components/emoji-picker.hbs
- app/assets/javascripts/discourse/app/templates/preferences/interface.hbs
- app/assets/javascripts/discourse/app/templates/user-invited-show.hbs
- app/assets/javascripts/select-kit/addon/components/notifications-filter/notifications-filter-header.js
Noticed these needed adjustment after working on theme, these are some outliers I had to manually accommodate for because they weren't covered or had `btn-default` instead of `btn-flat`
> UX: adjust various button classes

- app/assets/javascripts/discourse/app/routes/build-category-route.js
- app/assets/javascripts/discourse/app/routes/build-topic-route.js
- app/assets/javascripts/discourse/app/routes/tag-show.js
> (discovery-named-outlets) Use explicit service injections

- app/assets/javascripts/discourse/app/components/login-buttons.js
- app/assets/javascripts/discourse/app/components/modal/login.hbs
- app/assets/javascripts/discourse/app/components/modal/login.js
- app/assets/javascripts/discourse/tests/acceptance/create-account-test.js
> FIX: `autotracking.mutation-after-consumption`

- plugins/chat/lib/onebox/templates/discourse_chat_message.mustache
- plugins/chat/spec/lib/chat/onebox_handler_spec.rb
> FiX: Update date url for thread oneboxes

- app/assets/stylesheets/common/d-editor.scss
Followup to https://github.com/discourse/discourse/commit/e2d9117378ead0dbfcc6533d7cf6a7bf8a14d033
> UX: update composer border colour

- app/assets/javascripts/discourse/app/components/modal/create-account.js
- app/assets/javascripts/discourse/tests/acceptance/create-account-test.js
Regressed in 351cbab1a8568c06e138cf5d31fa66552c3ef352
> FIX: Full name validation regression

- spec/system/create_account_spec.rb
> DEV: Add a basic account creation system spec

- app/assets/stylesheets/qunit-custom.scss
1. Prevent a white background flash
2. Dark-mode support for two more inputs
> DEV: QUnit CSS tweaks

- app/assets/javascripts/admin/addon/templates/customize-themes-show.hbs
> DEV: Add a couple PluginOutlets to admin theme show

- app/controllers/admin/watched_words_controller.rb
- app/models/admin_dashboard_data.rb
- app/models/watched_word.rb
- app/serializers/site_serializer.rb
- app/serializers/watched_word_list_serializer.rb
- app/services/word_watcher.rb
- lib/new_post_manager.rb
- lib/pretty_text.rb
- lib/validators/censored_words_validator.rb
- spec/lib/validators/censored_words_validator_spec.rb
- spec/requests/admin/watched_words_controller_spec.rb
- spec/services/word_watcher_spec.rb
- Ignore only invalid words, not all words if one of them is invalid
- The naming scheme for methods was inconsistent
- Optimize regular expressions
> DEV: Refactor watched words

- lib/backup_restore.rb
> FIX: Correctly handle materialized views during db restore

- app/assets/javascripts/discourse/app/components/modal/create-account.js
> DEV: Resolve `observes` deprecation in create-account

- spec/lib/site_setting_extension_spec.rb
> DEV: Skip flaky site-setting deprecation spec

- spec/lib/js_locale_helper_spec.rb
> DEV: Update js_locale_helper_spec following 76b75fae

- app/assets/javascripts/discourse/app/lib/webauthn.js
In some browsers, 2FA login was failing with a "request is already pending" error. This only concerns instances with `experimental_passkeys` enabled and users on Chrome. Users would see this error (with a valid key): 
This was due to the fact that the webauthn API only supports one auth attempt at a time, so the security key call needs to abort the passkey's conditional UI request before starting.
I am not sure we can test this. We have system specs that simulate webauthn credentials and they didn't catch this.
> FIX: Broken login with security key when passkeys enabled

- spec/lib/site_setting_extension_spec.rb
Followup to baeac8f105cff8bbe70db67789bc96883cb185bc
> DEV: Re-enable site setting deprecation specs

- spec/models/group_spec.rb
Since the test description expects an event, let's assert it
```
it "triggers an event when a user is added to an automatic group" do
```
> DEV: Add an assertion for event triggered

- app/assets/javascripts/discourse/app/components/discovery/topics.js
- app/assets/javascripts/discourse/app/components/topic-list-item.js
Followup to 82d6d691eec9e97c88d67182bcbc583461e3e0dc
> FIX: Expand globally pinned topics correctly

- plugins/chat/app/services/chat/create_message.rb
- plugins/chat/assets/javascripts/discourse/models/chat-message.js
- plugins/chat/spec/integration/thread_replies_count_cache_accuracy_spec.rb
- plugins/chat/spec/models/chat/message_spec.rb
- plugins/chat/spec/plugin_helper.rb
- plugins/chat/spec/requests/chat/api/channel_threads_controller_spec.rb
- plugins/chat/spec/system/chat_channel_spec.rb
- plugins/chat/spec/system/deleted_message_spec.rb
- plugins/chat/spec/system/message_thread_indicator_spec.rb
- plugins/chat/spec/system/page_objects/chat/components/message.rb
- plugins/chat/spec/system/reply_to_message/full_page_spec.rb
- plugins/chat/spec/system/thread_list/full_page_spec.rb
- plugins/chat/spec/system/thread_preview_spec.rb
> DEV: improves reliability of delete/restore/update specs

- plugins/chat/plugin.rb
> DEV: Metadata update for plugin.rb

- config/locales/server.en.yml
Followup to b90b7ac7055202276cb66ceff27ae3f61d6cce00
> DEV: Add keywords for shared_drafts_allowed_groups

- app/assets/javascripts/discourse/app/components/user-stream.js
Followup to 545e92039c7e7f45e72274773ea39e7d2df94ded
This commit fixes an issue where hashtags on user activity stream
items past page 1 did not get decorated. This is because of a bug
in the user stream component, where it was trying to get stream
items to decorate after the AJAX call but before they had been
rendered by Ember. This can be fixed by wrapping this decoration
logic in later() to run on the next runloop.
> FIX: Fix hashtag decoration on later pages of user activity stream

- app/assets/stylesheets/common/base/reviewables.scss
> FIX: Adjust wrapping & width of reviewable values

- app/assets/stylesheets/common/base/topic-post.scss
> UX: adjust bulk selection position to avoid edits

- app/assets/javascripts/select-kit/addon/components/category-selector.js
- app/assets/javascripts/select-kit/addon/components/tag-chooser.js
These were broken following 8250609, this gets them working again
> FIX: update tag-chooser & category-selector action

- spec/system/editing_sidebar_categories_navigation_spec.rb
> DEV: Skip flaky sidebar mobile spec

- lib/validators/integer_setting_validator.rb
- spec/lib/validators/integer_setting_validator_spec.rb
Format big numbers validation to easy to read format like 1,000,000
> UX: Format number for site setting validation message

- app/assets/javascripts/discourse/app/components/discovery/navigation.js
Fixes the reorder-categories modal.
(tests to follow)
> FIX: Add a missing service injection

- plugins/chat/assets/javascripts/discourse/components/chat/modal/new-message.gjs
- plugins/chat/assets/stylesheets/common/chat-modal-new-message.scss
> FIX: Hide chat message header with new argument

- app/assets/javascripts/wizard/addon/components/wizard-field-checkbox.hbs
> DEV: allows to wrap wizard checkbox with outlet

- app/assets/javascripts/discourse/app/components/login-buttons.js
- app/assets/javascripts/discourse/app/components/modal/login.js
- app/assets/javascripts/discourse/app/controllers/preferences/security.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-test.js
- app/assets/javascripts/discourse/tests/acceptance/user-preferences-security-test.js
- app/controllers/session_controller.rb
- app/controllers/users_controller.rb
- app/serializers/user_serializer.rb
- config/site_settings.yml
- db/migrate/20231111201253_rename_experimental_passkeys_site_setting.rb
- spec/requests/session_controller_spec.rb
- spec/requests/users_controller_spec.rb
- spec/serializers/user_serializer_spec.rb
- spec/system/user_page/user_preferences_security_spec.rb
> DEV: Rename `experimental_passkeys` to `enable_passkeys`

- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/channel.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/list.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/members-selector.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/search.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/user.gjs
- plugins/chat/assets/stylesheets/common/chat-message-creator.scss
- plugins/chat/spec/system/chat_message_creator_spec.rb
> UX: do not show new-group-chat when filtering

- app/assets/javascripts/discourse/app/components/discovery/layout.hbs
- app/assets/javascripts/discourse/app/components/discovery/navigation.hbs
- app/assets/javascripts/discourse/app/components/discovery/topics.hbs
- app/assets/javascripts/discourse/app/templates/discovery/categories.hbs
- app/assets/javascripts/discourse/app/templates/discovery/filter.hbs
- app/assets/javascripts/discourse/app/templates/discovery/list.hbs
> DEV: Introduce discovery-list-area wrapper outlet

- plugins/chat/assets/javascripts/discourse/components/chat-channel-settings.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-full-page-header.gjs
> UX: shows editing title only on settings page

- plugins/chat/assets/stylesheets/common/chat-message.scss
This uses the mixin, which helps make the styles consistent (padding was a little off previously)
> UX: use mention mixin for chat mentions

- plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js
> UX: shorter copy link confirmation

- app/assets/stylesheets/common/modal/modal-overrides.scss
Fix wrong scope for cmd-k position to the top
> UX: fix cmd-k position

- app/assets/javascripts/discourse/app/components/card-container.hbs
The intent is to be able to completely override the user card (and all its event handlers) in some customization.
> DEV: user-card-content-container plugin outlet

- script/bulk_import/discourse_merger.rb
This script still could use some work (or be replaced by something else entirely), but in the meantime, these are all the fixes I applied to make it work for the last couple of merges I've worked on.
> DEV: Adding polls, solutions, upload references and other improvements to the Discourse merger script

- config/locales/server.en.yml
> UX: Expand enforce_second_factor setting description

- config/locales/client.en.yml
> FIX: Add desktop notification translation for watching_category_or_tag

- lib/tasks/docker.rake
Followup to 9449a0e0eda7aa49f13dc0eb181fb28dc8e63939
> DEV: Silence successful db:migrate output in docker.rake

- plugins/discourse-local-dates/spec/system/post_small_action_spec.rb
- spec/system/post_small_action_spec.rb
> DEV: Remove unnecessary fab! blocks

- app/models/concerns/has_custom_fields.rb
> DEV: Don't define methods in an included block

- app/jobs/scheduled/clean_up_uploads.rb
- app/models/reviewable_queued_post.rb
- spec/fabricators/reviewable_fabricator.rb
- spec/jobs/clean_up_uploads_spec.rb
Followup to 9db8f00b3dd6f2881adf1b786e29426889225e7a, we
don't need this dead code any more. Also made some minor
improvements and comments.
> DEV: Housekeeping for CleanUpUploads job

- app/assets/javascripts/discourse/app/components/modal/create-account.hbs
- app/assets/stylesheets/common/modal/login-modal.scss
- app/assets/stylesheets/mobile/login-modal.scss
Fixes for https://meta.discourse.org/t/login-signup-modal-issue/286046
> UX: Fixes login/create modal

- app/assets/javascripts/discourse/app/lib/homepage-router-overrides.js
- app/assets/javascripts/discourse/app/routes/discovery-index.js
- app/assets/javascripts/discourse/tests/acceptance/homepage-test.js
Followup to https://github.com/discourse/discourse/pull/24373
> FIX: Navigating to home via route name

- app/assets/javascripts/discourse/app/modifiers/auto-focus.js
> DEV: Add selectText option to auto-focus modifier

- app/assets/javascripts/discourse/app/components/topic-entrance.js
- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/routes/build-category-route.js
- app/assets/javascripts/discourse/app/routes/build-topic-route.js
- app/assets/javascripts/discourse/app/routes/discourse.js
- app/assets/javascripts/discourse/app/routes/tag-show.js
- app/assets/javascripts/discourse/app/routes/user-activity-bookmarks.js
- app/assets/javascripts/discourse/app/services/history-store.js
- app/assets/javascripts/discourse/app/services/route-scroll-manager.js
> Introduce history-store service and fix poppedState logic

- db/post_migrate/20231120190818_trigger_post_rebake_category_style_quotes.rb
Posts with quotes need to be rebaked to apply the new category badge
style css.
See: https://meta.discourse.org/t/285705
> DEV: Rebake posts w/ quotes to update category badge style

- spec/requests/omniauth_callbacks_controller_spec.rb
Followup to 5c38e55dc9047c121d7727352e994041d26ce95
> DEV: Properly cleanup auth providers in test

- app/assets/javascripts/discourse/app/models/category.js
> PERF: Cache results of Category.asyncSearch

- app/assets/stylesheets/common/modal/login-modal.scss
This is a small fix that broke due to modal refactoring.
> FIX: Fix custom login input label animations

- spec/system/admin_dashboard_new_features_spec.rb
> DEV: Remove unnecessary fab! block

- lib/tasks/docker.rake
We support a `USE_TURBO` environment variable which tells the
`docker:test` rake task to run rspec tests in parallel. However, this
currently does not apply to system tests.
This commit runs system specs for both core and plugins using
`./bin/turbo_rspec` when the `USE_TURBO` environment is present. Note
that when running system specs, we will only spawn X number of test
processes where X is half the number of available CPU cores. This is
done because we have to leave CPU resources for the chrome processes
that will be created.
1. No tests here are these changes are practically impossible to test with CI. However, we will know fairly quickly if this broke stuff as the `docker:test` Rake task is an integral part of our CI process.
> FIX: `docker:test` Rake task did not run system tests in parallel

- plugins/styleguide/assets/javascripts/discourse/templates/styleguide/index.hbs
Non-translated text – mainly for internal use
> UX: add BEM documentation to styleguide

- app/models/concerns/has_custom_fields.rb
- spec/lib/concern/has_custom_fields_spec.rb
> DEV: Allow setting different custom field length limits by key

- lib/tasks/plugin.rake
Similar to d0117ff6e32c371822a08a4453f6b0de73c42a0e, `plugins:update_all` spends most of its time waiting
on the network. On my local machine, this takes up to 2 mins when I have
all the official plugins installed. On a 32 cores machine, the total
time is cut down to 4 seconds.
1. Move the logic in the `plugin:update` Rake task into a method.
2. Updates the `plugin:update` and `plugin:update_all` to rely on the
new method.
3. Wraps the method call to update a plugin in `plugin:update_all` in a
`Concurrent::Promise`
This change also adds the `--quiet` option to the `git pull` option
since the `git pull` output is just noise for 99% of the time.
> PERF: Switch `plugins:update_all` to git pull concurrently

- app/assets/javascripts/discourse/app/models/nav-item.js
- app/assets/javascripts/discourse/app/services/store.js
These are handled lazily by our implicit-injections shim
> DEV: Remove unneeded RestModel injections

- app/assets/javascripts/discourse/tests/setup-tests.js
> DEV: Don't reload looping tests when cancelling

- app/assets/javascripts/discourse/app/instance-initializers/admin-sidebar.js
- plugins/chat/test/javascripts/components/chat-channel-test.js
- plugins/chat/test/javascripts/components/chat-notices-test.js
> DEV: Consistently use kebab-case in service lookups

- app/assets/javascripts/discourse/tests/acceptance/glimmer-search-test.js
- script/import_scripts/friendsmegplus.rb
(and the same typo in another file)
> FIX: A typo bug in an import script

- app/assets/javascripts/discourse/config/deprecation-workflow.js
Extracted from https://github.com/discourse/discourse/pull/21720
> DEV: Prepare deprecation-workflow for Ember upgrade

- .github/workflows/ember-version-enforcement.yml
Checking out the raw PR branch was only needed for the dependabot-helper workflow, but then I copy/pasted it here 🤦‍♂️
Followup to 16b6e869320a6d289b9c7eb8346cbcfd44217dfd
> DEV: Run ember enforcement on merge-result ref

- app/assets/javascripts/admin/addon/components/site-settings/integer.hbs
- app/assets/javascripts/admin/addon/components/themes-list.hbs
> DEV: Fix `no-unnecessary-curly-parens` lint rule

- app/assets/javascripts/discourse-markdown-it/src/engine.js
- app/assets/javascripts/discourse/app/controllers/full-page-search.js
- app/assets/javascripts/discourse/app/services/store.js
- app/assets/javascripts/pretty-text/addon/emoji.js
- plugins/chat/assets/javascripts/lib/discourse-markdown/chat-transcript.js
> DEV: Fix `no-extra-boolean-cast` lint

- plugins/chat/assets/javascripts/discourse/components/channels-list.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-browse-view.js
- plugins/chat/assets/javascripts/discourse/components/chat-channel-message-emoji-picker.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-vh.js
- plugins/chat/assets/javascripts/discourse/components/chat/modal/create-channel.js
- plugins/chat/assets/javascripts/discourse/services/chat-audio-manager.js
> DEV: Fix `super` calls in native chat classes

- plugins/chat/test/javascripts/components/chat-composer-uploads-test.js
> DEV: Remove unnecessary `await settled()`

- app/assets/javascripts/admin/addon/components/admin-theme-editor.js
- app/assets/javascripts/admin/addon/components/email-styles-editor.js
- app/assets/javascripts/admin/addon/components/embedding-setting.js
- app/assets/javascripts/admin/addon/components/site-settings/bool.js
- app/assets/javascripts/admin/addon/components/webhook-event-chooser.js
- app/assets/javascripts/admin/addon/models/api-key.js
- app/assets/javascripts/discourse/app/models/topic.js
- app/assets/javascripts/discourse/app/services/composer.js
- plugins/chat/assets/javascripts/discourse/models/chat-message.js
> DEV: Fix "no-setter-return" lint

- app/assets/javascripts/bootstrap-json/index.js
> DEV: Fix "no-unsafe-finally" lint

- plugins/spoiler-alert/assets/javascripts/lib/discourse-markdown/spoiler-alert.js
> DEV: Fix "no-empty" lint

- app/assets/javascripts/discourse/tests/acceptance/topic-timeline-test.js
- app/assets/javascripts/discourse/tests/helpers/site-settings.js
> DEV: Fix "no-dupe-keys" lint

- app/assets/javascripts/discourse/tests/acceptance/click-track-test.js
- app/assets/javascripts/discourse/tests/unit/lib/click-track-test.js
> DEV: Update click-track tests

- app/assets/javascripts/discourse/tests/setup-tests.js
https://github.com/discourse/discourse/assets/50783505/c6db8c35-1473-4ccd-aca2-bfb71af9e73e
> DEV: Make `theme-qunit` discoverable from `/tests`

- plugins/chat/spec/lib/chat/channel_archive_service_spec.rb
- plugins/chat/spec/lib/chat/transcript_service_spec.rb
> DEV: Skip flaky chat transcript specs

- app/assets/javascripts/discourse/app/components/search-menu.hbs
This PR adds a plugin outlet to place a button after & outside of the search input.
> FEATURE: Add search menu outlet

- app/assets/javascripts/discourse/app/components/search-menu.hbs
follow-up to 12902c1, FYI @jordanvidrine seems like prettier wasn't run on this one
> FIX: lint unlinted file

- app/assets/javascripts/discourse/app/components/search-menu.hbs
> DEV: Update `search-menu-before-term-input` outlet args

- app/assets/stylesheets/common/base/discourse.scss
follow-up to 6d624c6, used the completely wrong variable name here 😅
> FIX: use correct color for inputs

- app/assets/javascripts/discourse/app/components/search-menu.hbs
> DEV: Remove unused search plugin-outlets

- app/assets/javascripts/admin/addon/components/admin-plugins-list.gjs
- app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
- app/assets/javascripts/discourse/app/components/glimmer-component-with-deprecated-parent-view.js
- app/assets/javascripts/discourse/app/components/passkey-login-button.gjs
- app/assets/javascripts/discourse/tests/integration/component-templates-test.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-composer-message-details.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-drawer/header/close-button.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-emoji-avatar.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-message-separator-new.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-side-panel-resizer.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/composer/button.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/composer/separator.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/form/row.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/list-action.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message-creator/member.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message/avatar.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/message/error.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/scroll-to-bottom-arrow.gjs
- plugins/chat/assets/javascripts/discourse/components/styleguide/organisms/chat.gjs
- plugins/styleguide/assets/javascripts/discourse/components/dummy-component.gjs
- plugins/styleguide/assets/javascripts/discourse/components/styleguide/component.js
- plugins/styleguide/assets/javascripts/discourse/components/styleguide/controls.js
- plugins/styleguide/assets/javascripts/discourse/components/styleguide/controls/toggle.js
> DEV: Fix "ember/no-empty-glimmer-component-classes" lint

- app/assets/javascripts/admin/addon/mixins/period-computation.js
- app/assets/javascripts/discourse-widget-hbs/lib/widget-hbs-compiler.js
- app/assets/javascripts/discourse/app/components/composer-action-title.js
- app/assets/javascripts/discourse/app/components/sidebar/section-link-prefix.js
- app/assets/javascripts/discourse/app/instance-initializers/component-templates.js
- app/assets/javascripts/discourse/app/lib/homepage-router-overrides.js
- app/assets/javascripts/discourse/app/models/category-list.js
- app/assets/javascripts/discourse/app/services/media-optimization-worker.js
- app/assets/javascripts/discourse/tests/acceptance/topic-post-decorate-cooked-test.js
A grab bag of smaller issues (constructor-super, no-fallthrough, ember/no-private-routing-service, no-unreachable, no-async-promise-executor)
> DEV: Fix or disable various lint rules

- app/assets/javascripts/discourse/app/components/search-menu/results/blurb.hbs
> DEV: Add missing html-safe on search result blurb

- app/models/concerns/has_custom_fields.rb
- lib/plugin/instance.rb
> DEV: Allow setting max_length for field types using the plugin API

- .github/workflows/stale-pr-closer.yml
> DEV: Update stale-pr-closer configuration

- app/assets/javascripts/discourse/app/components/menu-panel.hbs
- app/assets/javascripts/discourse/app/components/site-header.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
> DEV: Add `forceDropdownForMenuPanels` to plugin api

- plugins/chat/assets/javascripts/discourse/routes/chat-channel.js
> DEV: Resolve transitionTo deprecation in chat-channel route

- app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/modal.hbs
- app/assets/stylesheets/common/base/modal.scss
- app/assets/stylesheets/common/components/sidebar/edit-navigation-menu/modal.scss
Fixing top spacing 
and narrow width
> UX: fix sidebar modal

- app/assets/javascripts/discourse/app/routes/tag-show.js
- app/assets/javascripts/discourse/tests/acceptance/tags-test.js
https://meta.discourse.org/t/286130/4
> FIX: Ensure 'untagged' document title is set correctly

- spec/lib/cooked_post_processor_spec.rb
> DEV: remove duplicate spec

- spec/system/editing_sidebar_tags_navigation_spec.rb
> DEV: skip failing spec due to modal refactoring

- spec/requests/session_controller_spec.rb
"prevents login by admins" should test with an admin.
> DEV: Fix readonly admin login spec

- app/assets/javascripts/discourse/app/components/search-menu.hbs
> DEV: Add `search-menu-before-advanced-search` plugin outlet

- config/locales/client.en.yml
This PR adds more explicit title text to the select text menu options.
> UX: Add select text menu labels

- app/assets/javascripts/admin/addon/templates/dashboard_reports.hbs
- app/assets/stylesheets/common/base/alert.scss
- config/locales/client.en.yml
> UX: Add a link from admin reports page to meta a topic

- .github/workflows/tests.yml
> DEV: Add ember-5 to test matrix for core/chat system specs

- app/models/about.rb
- app/models/email_style.rb
- app/models/report.rb
- app/models/search_log.rb
- app/models/tag_group.rb
- app/models/topic_list.rb
- app/models/trust_level3_requirements.rb
- app/serializers/user_post_bookmark_serializer.rb
- lib/has_errors.rb
- lib/import_export/base_exporter.rb
- plugins/chat/app/serializers/chat/user_message_bookmark_serializer.rb
- plugins/chat/spec/system/page_objects/chat/components/messages.rb
- plugins/chat/spec/system/page_objects/chat/components/thread_list.rb
- plugins/chat/spec/system/page_objects/sidebar/sidebar.rb
- spec/support/fake_logger.rb
- spec/system/page_objects/modals/sidebar_edit_categories.rb
> DEV: Fix Lint/DuplicateMethods

- app/assets/javascripts/discourse/app/components/user-menu/bookmarks-list.js
- app/assets/javascripts/discourse/app/components/user-menu/icon-avatar.gjs
- app/assets/javascripts/discourse/app/components/user-menu/menu-item.hbs
- app/assets/javascripts/discourse/app/components/user-menu/menu-item.js
- app/assets/javascripts/discourse/app/components/user-menu/menu.hbs
- app/assets/javascripts/discourse/app/components/user-menu/menu.js
- app/assets/javascripts/discourse/app/components/user-menu/messages-list.js
- app/assets/javascripts/discourse/app/components/user-menu/notification-avatar.gjs
- app/assets/javascripts/discourse/app/lib/user-menu/base-item.js
- app/assets/javascripts/discourse/app/lib/user-menu/bookmark-item.js
- app/assets/javascripts/discourse/app/lib/user-menu/message-item.js
- app/assets/javascripts/discourse/app/lib/user-menu/notification-item.js
- app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
- app/assets/javascripts/discourse/tests/fixtures/notification-fixtures.js
- app/assets/javascripts/discourse/tests/fixtures/user-menu.js
- app/assets/javascripts/discourse/tests/integration/components/user-menu/menu-item-test.js
- app/assets/stylesheets/common/base/menu-panel.scss
- app/controllers/notifications_controller.rb
- app/controllers/users_controller.rb
- app/models/notification.rb
- app/serializers/notification_serializer.rb
- app/serializers/site_serializer.rb
- config/locales/server.en.yml
- config/site_settings.yml
- spec/models/notification_spec.rb
- spec/requests/notifications_controller_spec.rb
- spec/requests/users_controller_spec.rb
> FEATURE: Site setting to display user avatars in user menu

- app/models/concerns/has_custom_fields.rb
> FIX: Validate each value in an array custom field separately

- app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
- app/assets/javascripts/discourse/app/lib/utilities.js
- app/assets/javascripts/discourse/app/widgets/post-small-action.js
- app/assets/javascripts/discourse/app/widgets/post.js
- app/assets/javascripts/discourse/tests/acceptance/topic-test.js
- app/assets/stylesheets/common/base/topic-post.scss
- app/assets/stylesheets/common/components/keyboard_shortcuts.scss
This reverts commit 9dce1592dc30e3c196a92b908b7ffb09f7e73908.
The change is having some adverse effects.
> Revert "A11Y: fix setting focus to a post (#23367)"

- app/assets/javascripts/discourse/app/components/modal/login.hbs
- app/assets/javascripts/discourse/app/components/modal/login.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-test.js
- config/locales/client.en.yml
Admins will be instructed to login via /u/admin-login to change their site settings.
> UX: if no login options are configured, show a message

- Gemfile.lock
…after 28956a54159f2f3f78b5704442f04bda7329fb44 merge
> DEV: Update Gemfile.lock

- spec/rails_helper.rb
> DEV: Increase per-spec timeout to 45s

- plugins/chat/assets/javascripts/discourse/components/chat-message-thread-indicator.gjs
- plugins/chat/assets/javascripts/discourse/components/thread-title/index.gjs
- plugins/chat/assets/javascripts/discourse/components/user-threads/index.gjs
- plugins/chat/assets/stylesheets/common/chat-thread-title.scss
- plugins/chat/spec/system/page_objects/chat/user_threads.rb
- plugins/chat/spec/system/page_objects/chat_drawer/chat_drawer.rb
> UX: allow users to click thread title to open it

- plugins/chat/assets/stylesheets/common/chat-message.scss
- plugins/chat/config/locales/client.en.yml
- plugins/chat/test/javascripts/unit/lib/get-reaction-text-test.js
> UI: ensures emojis are correctly aligned in reactions

- app/assets/javascripts/discourse/app/components/groups-form-interaction-fields.hbs
(and correct some html whitespace)
> DEV: Remove incorrect "for" attributes

- app/assets/stylesheets/common/base/personal-message.scss
- app/assets/stylesheets/common/base/topic-post.scss
Two regressions fixed here, one introduced in 6dc5fe0c83829a4fca549f0903669bf48f42d74a and the other introduced a few months ago.
> UX: Fix highlighting regressions

- plugins/chat/spec/lib/chat/transcript_service_spec.rb
Revert https://github.com/discourse/discourse/pull/24778
> DEV: Skip chat transcript spec

- app/assets/stylesheets/common/base/code_highlighting.scss
> Cleanup HLJS styling

- app/assets/stylesheets/common/base/menu-panel.scss
> UX: Adjust notification items when avatar is shown

- .github/labeler.yml
- .github/workflows/labeler.yml
> DEV: Update actions/labeler to v5

- spec/requests/admin/web_hooks_controller_spec.rb
> FIX: Remove duplicate spec example

- plugins/chat/assets/stylesheets/common/chat-navbar.scss
> FIX: ensures border and shadow of header is visible

- lib/tasks/assets.rake
See https://meta.discourse.org/t/upgrade-from-3-2-0-beta3-dev-to-3-2-0-beta3-failed-due-to-out-of-memory/286643/14?u=falco
Co-authored-by: David Taylor <david@taylorhq.com>
> PERF: Update node_options during ember build for low end servers

- app/assets/javascripts/discourse/app/components/user-menu/icon-avatar.gjs
- app/assets/stylesheets/common/base/menu-panel.scss
> UX: Improve layout of avatar+icon notifications

- Gemfile.lock
- app/assets/stylesheets/common/base/menu-panel.scss
> UX: Align icon with username in menu panel

- lib/turbo_tests/base_formatter.rb
- lib/turbo_tests/json_example.rb
- spec/rails_helper.rb
> DEV: Summarize JS deprecations at end of system spec run

- app/models/concerns/has_custom_fields.rb
> DEV: Concerns can use class_methods

- Gemfile.lock
- app/assets/javascripts/discourse/app/controllers/user-notifications.gjs
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/routes/user-notifications.js
- app/assets/javascripts/discourse/app/templates/user/notifications-index.hbs
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
- spec/system/page_objects/pages/user.rb
- spec/system/page_objects/pages/user_notifications.rb
- spec/system/user_page/user_notifications_spec.rb
This allows blocking infinite scrolling until a condition is met, and changing notification limit
> DEV: Plugin-api methods for user-notifications route customizations

- app/assets/javascripts/discourse/app/components/date-picker.js
> DEV: Make DatePicker placeholder customizable

- .github/workflows/tests.yml
Accidentally removed in c9cf3f5a520162da2f679397af21b7edfc68d376
> DEV: Restore chat system spec job in GitHub CI

- app/assets/stylesheets/common/base/topic-post.scss
- app/assets/stylesheets/common/components/more-topics.scss
This reverts commit 368f4ef24df588a742994265046a16336e0ee70d.
> REVERT: "UX: fix overlap obstructed anon topic reply (#24921)"

- .github/workflows/tests.yml
This regressed in b2c27a8c6089c1c919ae6aff18483418bff7a5b9
> DEV: Fix path for flaky test report when uploading artifact

- app/assets/javascripts/discourse/app/components/modal/fullscreen-table.hbs
- app/assets/stylesheets/common/base/topic-post.scss
> UX: fullscreen modal > add missing modifier + sticky header

- .github/workflows/tests.yml
> DEV: Update actions/upload-artifact to v4

- app/assets/javascripts/admin/addon/components/modal/reseed.js
- app/assets/javascripts/discourse/app/components/modal/change-owner.js
Super minor, without tracking, these error messages weren't being shown.
> FIX: Modal flash tracking

- plugins/chat/spec/system/navigation_spec.rb
- plugins/chat/spec/system/thread_tracking/drawer_spec.rb
> DEV: skip two flakey specs

- app/assets/javascripts/discourse/app/lib/notification-types/admin-problems.js
- config/locales/client.en.yml
* Icon was a gift and not exclamation-triangle...these admin problems
are not usually a gift :P
* Added missing title translation
> FIX: Admin problem notification minor issues

- Gemfile
- Gemfile.lock
> DEV: Update rbtrace to 0.5.1

- plugins/chat/assets/stylesheets/common/chat-navbar.scss
This reverts commit b8a36dd870b3a80594f4442f9482e1f75f2d74a8.
Commit is breaking the build
> Revert "UX: typo (#24971)"

- spec/rails_helper.rb
Previously, we were attaching any server exception to the RSpec
example's `Exception#cause` by doing `example.exception.cause =
RspecErrorTracker.last_exception`. However, this is problematic because
it relies on RSpec internal implementation details where RSpec will
print out the exception's cause. The other problem is that when RSpec
prints out the exception cause, it only includes a single line of
backtrace which isn't very helpful sometimes.
While this change of tracking the last exception works OK for request
specs, it doesn't not work for system specs where multiple requests can
be triggered in an example potentially leading to multiple exceptions.
Knowing all the exceptions which happened when running the example is important
for us when it comes to debugging …
> DEV: Report all exceptions in RSpec example failure lines

- app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.hbs
- app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.js
- app/assets/javascripts/discourse/app/components/search-menu/results/initial-options.hbs
- app/assets/javascripts/discourse/app/components/search-menu/results/random-quick-tip.js
- app/assets/javascripts/discourse/app/components/search-menu/results/recent-searches.hbs
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/tests/acceptance/glimmer-search-test.js
- app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
> DEV: PluginApi function to customize search menu assistant item behavior

- spec/rails_helper.rb
When running system tests with all official plugins installed, we have
encountered instances where the system tests will hang. When dumping the
backtraces of the threads, we can see that the main thread running the
tests is stuck in a deadlock with the puma thread while serving a
request.
The deadlock happens when the main thread acquires the `ActiveSupport::Concurrency::LoadInterlockAwareMonitor`
lock first in `ActiveRecord::ConnectionAdapters::AbstractAdapter` before acquring another `Monitor` lock in
`ActiveRecord::ModelSchema`. In the Puma thread, it acquires the
`Monitor` lock in `ActiveRecord::ModelSchema` first before acquring the
`ActiveSupport::Concurrency::LoadInterlockAwareMonitor` lock.
To workaround this problem, we will preload all model schema cache
before running system …
> DEV: Preload all models schema cache before running system tests

- app/views/topics/show.html.erb
Needed by https://github.com/discourse/discourse-ai/pull/386
> FEATURE: Topic crawler view bottom plugin outlet

- script/import_scripts/fusionforge.rb
This is an import script for the forum/development platform https://www.fusionforge.org/projects/fusionforge imports users, forums and posts including attachments
> FEATURE: Import Script for Fusionforge

- script/import_scripts/fusionforge.rb
> DEV: Apply code format to import script

- app/assets/javascripts/select-kit/addon/components/form-template-chooser.js
A system test which was testing our ability to add a form template to a
category was flaky. This turned out to be a client side bug where the
`FormTemplateChooser` dropdown may not display any dropdown options if
the ajax request to fetch the categories form template has not been
completed when the dropdown is opened.
What does this change do?
Make use of select-kit's `triggerSearch` function to fetch the records
which will properly rerender the dropdown options.
> FIX: Adding form template to category dropdown can some times be empty

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/common/post-action-feedback.scss
- app/assets/stylesheets/common/post-action-menu.scss
- app/assets/stylesheets/desktop/_index.scss
- app/assets/stylesheets/desktop/post-action-feedback.scss
- app/assets/stylesheets/mobile/_index.scss
- app/assets/stylesheets/mobile/post-action-feedback.scss
(to test try using discourse-ai which displays feedback on mobile)
> FIX: allow styling of feedback on mobile

- Gemfile
- Gemfile.lock
See https://github.com/rails/rails/releases/tag/v7.0.8
> DEV: Update Rails to 7.0.8

- Gemfile.lock
- app/assets/stylesheets/mobile/login-modal.scss
This PR fixes styles being applied to custom user dropdown fields.
**Before**
**After**
> FIX: Drop down fix

- app/views/topics/show.html.erb
https://meta.discourse.org/t/discussion-forum-schema-improvements/287347/22
> FEATURE: include username link in the microdata schema

- app/assets/javascripts/admin/addon/components/themes-list-item.js
- app/assets/javascripts/admin/addon/components/themes-list.hbs
- app/assets/javascripts/admin/addon/components/themes-list.js
- app/assets/javascripts/discourse/tests/acceptance/themes-test.js
- app/assets/javascripts/discourse/tests/integration/components/themes-list-test.js
- app/assets/stylesheets/common/admin/customize.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
Allow filtering themes or components to find Active/Enabled Inactive/Disabled or Updates Available in the admin panel.
In addition, original filter was renamed to search and some BEM CSS cleaning was done. 
Demo
https://github.com/discourse/discourse/assets/72780/f6f04ae8-8031-41e2-9a60-99105ddd67fc
Mobile screenshot
> FEATURE: filter themes and components

- app/assets/javascripts/admin/addon/components/themes-list.js
- app/assets/javascripts/discourse/tests/integration/components/themes-list-test.js
- config/locales/client.en.yml
In this PR we introduced the enabled/disabled components filter.
https://github.com/discourse/discourse/pull/25105
However, components are slightly more complicated and can be used/unused/enabled/disabled.
https://github.com/discourse/discourse/assets/72780/85859c75-b67a-4d4a-b768-d840eeaf0d12
> FEATURE: used, unused,  enabled, disabled component filter

- script/install_minio_binaries.rb
Reverts discourse/discourse#25137
> Revert "DEV: Skip MinioRunner until min.io renews their cert"

- app/models/topic_embed.rb
- db/migrate/20240104155715_add_embed_content_cache_to_topic_embed.rb
- spec/models/topic_embed_spec.rb
This will be useful for features that rely on the semantic content of topics, like the many AI features
> FEATURE: Cache embed contents in the database

- app/models/concerns/has_custom_fields.rb
- lib/plugin/instance.rb
- spec/lib/concern/has_custom_fields_spec.rb
> Backport custom field changes

- app/assets/javascripts/bootstrap-json/index.js
- app/assets/javascripts/bootstrap-json/package.json
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn-ember3.lock
- app/assets/javascripts/yarn-ember5.lock
Parsing html, modifying it, and then serializing had some negative side-effects (namely, it was losing html entity escaping in some cases)
> DEV: Use html-rewriter-wasm/lol_html instead of JSDOM

- app/assets/javascripts/discourse/app/app.js
> FIX: Remove all noscript elements, not just the first one

- lib/version.rb
Reverts discourse/discourse#25168
> Revert "DEV: Version bumps for main: v3.2.0.beta4, v3.2.0.beta5-dev"

- app/assets/javascripts/discourse/app/components/user-menu/notifications-list.js
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
- spec/system/page_objects/components/user_menu.rb
- spec/system/viewing_user_menu_spec.rb
This is pretty self explanatory.. New limit setting for notifications in the user menu!
> DEV: Add setUserMenuNotificationsLimit plugin-api method

- app/services/topic_summarization.rb
- spec/fabricators/topic_embed_fabricator.rb
- spec/services/topic_summarization_spec.rb
- spec/support/dummy_custom_summarization.rb
> FEATURE: Prefer topic_embed's cached content when summarizing

- app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs
> DEV: Pass `showDismiss` to panel-body-bottom outlet

- spec/requests/api/schemas/json/post_replies_response.json
- spec/requests/api/schemas/json/post_show_response.json
- spec/requests/api/schemas/json/post_update_response.json
- spec/requests/api/schemas/json/topic_create_response.json
- spec/requests/api/schemas/json/topic_show_response.json
- spec/requests/api/topics_spec.rb
- Fix score missing type and wrong type issue
- https://github.com/discourse/discourse/pull/21028#discussion_r1162526721 the missing type issue is actually reviewed but not resolved and merged.
> https://meta.discourse.org/t/contribute-to-the-discourse-api-docs/56693
> Fix OpenAPI doc issue

- app/assets/javascripts/deprecation-silencer/index.js
> DEV: Unsilence link-to deprecation for ember-cli build

- app/assets/javascripts/bootstrap-json/index.js
Regressed in fe10a3feab0f8dbf0476812c0987ad198f0b14cf
Fixes /theme-qunit
> FIX: Correctly rewrite script/link tags in the proxy

- app/assets/javascripts/admin/package.json
- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse-hbr/package.json
- app/assets/javascripts/discourse-widget-hbs/package.json
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/float-kit/package.json
- app/assets/javascripts/package-ember3.json
- app/assets/javascripts/package-ember5.json
- app/assets/javascripts/pretty-text/package.json
- app/assets/javascripts/select-kit/package.json
- app/assets/javascripts/theme-transpiler/package.json
- app/assets/javascripts/truth-helpers/package.json
- app/assets/javascripts/yarn-ember3.lock
- app/assets/javascripts/yarn-ember5.lock
> DEV: Use ember 5 in package.json files by default

- lib/topic_upload_security_manager.rb
Posts may have multiple uploads/upload references.
> FIX: Don't use joins to filter

- app/assets/javascripts/bootstrap-json/index.js
> DEV: Use correct vendor file when using ember-cli proxy in prod mode

- app/assets/javascripts/discourse/app/components/modal/create-account.hbs
> A11Y: Add `describedby` associations in create account modal

- app/assets/javascripts/discourse/app/components/composer-container.hbs
> A11Y: Add role="button" to composer cancel button

- app/assets/javascripts/discourse/app/components/modal/keyboard-shortcuts-help.hbs
> A11Y: Allow keyboard users to scroll help modal

- app/assets/stylesheets/common/base/compose.scss
This might be causing performance issues in Firefox? so let's try without it
> DEV: remove `:has` selector from composer

- plugins/chat/assets/javascripts/discourse/components/chat/navbar/back-button.gjs
> UX: change chat back button to btn-transparent

- lib/email/renderer.rb
- spec/lib/email/renderer_spec.rb
> DEV: Add apply_modifier in Email::Renderer for html modifications

- app/assets/javascripts/admin/addon/mixins/period-computation.js
https://meta.discourse.org/t/-/291354
> FIX: use getter and setter for computed properties

- lib/middleware/request_tracker.rb
- spec/lib/middleware/request_tracker_spec.rb
> FIX: Update global rate limiter keys/messages to clarify user vs ip

- plugins/chat/assets/stylesheets/mobile/chat-footer.scss
> FIX: correctly support safe-area-inset-bottom in footer

- config/locales/server.en.yml
- config/site_settings.yml
> DEV: Add site setting for Discourse Discover

- app/models/topic_hot_score.rb
- config/site_settings.yml
- lib/topic_query.rb
- spec/lib/topic_query_spec.rb
- spec/models/topic_hot_scores_spec.rb
- Decrease gravity, we come in too hot prioritizing too many new topics
- Remove all muted topics / categories and tags from the hot list
- Punish topics with zero likes in algorithm
> FEATURE: improvements to hot algorithm

- config/locales/server.en.yml
> DEV: Add link to Discover page

- lib/tasks/import.rake
Rake files share methods with all other rake files and there is already a `rebake_posts` method in another rake file.
> FIX: Rake task executed wrong method

- config/locales/server.en.yml
- lib/onebox/engine/github_blob_onebox.rb
- lib/onebox/engine/github_commit_onebox.rb
- lib/onebox/engine/github_gist_onebox.rb
- lib/onebox/engine/github_issue_onebox.rb
- lib/onebox/engine/github_pull_request_onebox.rb
- lib/onebox/engine/gitlab_blob_onebox.rb
- lib/onebox/mixins/git_blob_onebox.rb
- lib/onebox/templates/githubblob.mustache
- lib/onebox/templates/githubcommit.mustache
- lib/onebox/templates/githubgist.mustache
- lib/onebox/templates/githubissue.mustache
- lib/onebox/templates/githubpullrequest.mustache
- lib/onebox/templates/gitlabblob.mustache
> FIX: Localize text in github oneboxes

- plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs
- plugins/chat/assets/javascripts/discourse/modifiers/chat/scrollable-list.js
- plugins/chat/assets/javascripts/discourse/services/chat-channel-scroll-positions.js
- plugins/chat/spec/system/chat_channel_spec.rb
Note this is only saved on each tab session.
> FEATURE: save/retrieve scroll position in chat channel

- plugins/chat/assets/javascripts/discourse/routes/chat-channel-threads.js
No test as this is a very specific edge case, already hard to repro manually.
> FIX: ensures active message is cleared on threads opening

- app/assets/javascripts/discourse/app/services/user-tips.js
1. TrackedSet instead of TrackedMap of `true`s
2. Use Set#has for early exit
3. Use the site service instead of Site import
> DEV: Clean up user-tips service

- app/assets/javascripts/discourse/app/components/activation-email-form.gjs
- app/assets/javascripts/discourse/app/components/activation-email-form.hbs
- app/assets/javascripts/discourse/app/components/activation-email-form.js
- app/assets/javascripts/discourse/app/components/modal/activation-edit.js
- app/assets/javascripts/discourse/app/controllers/account-created-edit-email.js
- app/assets/javascripts/discourse/app/templates/account-created/edit-email.hbs
- app/assets/javascripts/discourse/tests/acceptance/account-created-test.js
- app/assets/javascripts/discourse/tests/acceptance/sign-in-test.js
> DEV: Convert activation-email-form to gjs

- app/services/push_notification_pusher.rb
- spec/services/push_notification_pusher_spec.rb
> DEV: Trigger DiscourseEvent on push notification send

- spec/rails_helper.rb
We have been seeing specs time out on GitHub CI but the problem is that
we are unable to debug those timeouts due to a lack of information. This
change seeks to print out the backtraces of all threads right before a
spec times out on CI.
What does this change do?
1. Starts a thread on CI which will wait for a spec to start running.
1. Once a spec starts running, the thread will sleep for
`PER_SPEC_TIMEOUT_SECONDS -1` seconds.
1. After sleeping, the thread checks if the spec is still running and
prints out the backtraces of all threads if it is. Otherwise, the
thread does nothing and runs the next loop.
1. At the end of each spec run, we ensure that the thread is in a
waiting state for the next spec run to start.
Note that there is no need for us to teardown or cleanup the …
> DEV: Print out backtraces of all threads when spec times out on CI

- plugins/discourse-narrative-bot/lib/discourse_narrative_bot/advanced_user_narrative.rb
- plugins/discourse-narrative-bot/spec/discourse_narrative_bot/advanced_user_narrative_spec.rb
- plugins/poll/assets/javascripts/discourse/initializers/add-poll-ui-builder.js
- plugins/poll/config/locales/server.en.yml
- plugins/poll/config/settings.yml
- plugins/poll/db/post_migrate/20240122015626_fill_poll_create_allowed_groups_based_on_deprecated_setting.rb
- plugins/poll/lib/post_validator.rb
- plugins/poll/plugin.rb
- plugins/poll/spec/controllers/polls_controller_spec.rb
- plugins/poll/spec/controllers/posts_controller_spec.rb
- plugins/poll/spec/lib/new_post_manager_spec.rb
- plugins/poll/spec/lib/poll_spec.rb
- plugins/poll/spec/models/poll_spec.rb
- plugins/poll/test/javascripts/acceptance/poll-builder-disabled-test.js
- plugins/poll/test/javascripts/acceptance/poll-builder-enabled-test.js
- plugins/styleguide/app/controllers/styleguide/styleguide_controller.rb
- plugins/styleguide/config/locales/server.en.yml
- plugins/styleguide/config/settings.yml
- plugins/styleguide/db/post_migrate/20240122015630_fill_styleguide_admin_only_groups.rb
- plugins/styleguide/spec/integration/access_spec.rb
- DEV: Change poll_minimum_trust_level_to_create to group based setting
- DEV: Move styleguide_admin_only to group based setting
> DEV: Move core plugin TL -> group settings

- app/assets/javascripts/discourse/app/components/discourse-topic.js
- app/assets/javascripts/discourse/app/components/links-redirect.js
- app/assets/javascripts/discourse/app/components/user-stream.js
- app/assets/javascripts/discourse/app/lib/click-track.js
This commit adds appevent trigger for click tracking so that they can be intercepted.
> FEATURE: trigger app event for click tracking

- app/assets/javascripts/discourse/tests/acceptance/create-account-from-login-test.js
- app/assets/javascripts/discourse/tests/acceptance/create-account-test.js
- app/assets/javascripts/discourse/tests/acceptance/forgot-password-test.js
- app/assets/javascripts/discourse/tests/acceptance/groups-index-test.js
- app/assets/javascripts/discourse/tests/acceptance/login-redirect-test.js
- app/assets/javascripts/discourse/tests/acceptance/login-required-test.js
- app/assets/javascripts/discourse/tests/acceptance/mobile-sign-in-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-and-hide-email-address-taken-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-and-no-social-logins-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-disabled-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-test.js
- app/assets/javascripts/discourse/tests/acceptance/new-message-test.js
- app/assets/javascripts/discourse/tests/acceptance/new-topic-test.js
- app/assets/javascripts/discourse/tests/acceptance/sign-in-test.js
- app/assets/javascripts/discourse/tests/acceptance/static-test.js
- app/serializers/web_hook_user_serializer.rb
- config/site_settings.yml
- spec/requests/api/schemas/json/user_get_response.json
- spec/serializers/user_serializer_spec.rb
Was announced in November, we've rolled it out to most of our hosting and now we're ready to make it enabled by default. 
More context: https://meta.discourse.org/t/passwordless-login-using-passkeys/285589
> FEATURE: Enable passkeys by default

- app/assets/javascripts/discourse/app/routes/application.js
…so "site" and "currentUser" (and sort all of them)
> DEV: Add missing service injections to app route

- app/assets/javascripts/discourse/app/lib/url.js
- plugins/checklist/assets/javascripts/discourse/initializers/checklist.js
- plugins/discourse-lazy-videos/assets/javascripts/initializers/lazy-videos.js
- plugins/footnote/assets/javascripts/initializers/inline-footnotes.js
- plugins/poll/assets/javascripts/discourse/initializers/extend-for-poll.js
- plugins/spoiler-alert/assets/javascripts/initializers/spoiler-alert.js
> DEV: Use `service:` lookups instead of `:main`

- app/assets/javascripts/discourse/app/templates/user/notifications-index.hbs
> DEV: Add PluginOutlet wrapping user notifications EmptyState

- app/assets/javascripts/discourse/app/controllers/application.js
- app/assets/javascripts/discourse/app/instance-initializers/narrow-desktop.js
- app/assets/javascripts/discourse/app/lib/lock-on.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-narrow-desktop-test.js
No need to fire up those query parsing engines :P
> DEV: Use `document.body` directly

- app/assets/javascripts/discourse/app/components/site-header.js
- app/assets/javascripts/discourse/app/instance-initializers/narrow-desktop.js
We already assume it's there in many other places
> DEV: Don't check for ResizeObserver existence

- app/assets/stylesheets/desktop/topic-list.scss
Accidentally added this css that didn't need to be added as part of this
commit: 0dcdc66f58d0037487db3adaddbe07afa3c1f783
> FIX: Remove css that should not have been added

- app/assets/javascripts/discourse/app/routes/group-index.js
- app/assets/javascripts/discourse/tests/acceptance/create-invite-modal-test.js
> FIX: Auto-populate group field in invite modal on group route

- app/assets/javascripts/bootstrap-json/index.js
Specifying alternatives to `dist/` is useful when running multiple servers locally (e.g. for performance testing)
> DEV: Fix alternative output directories in ember-cli proxy

- app/assets/javascripts/discourse/app/templates/user/notifications-index.hbs
- app/assets/javascripts/discourse/app/templates/user/summary.hbs
A few little changes for customizing discourse via themes :)
> DEV: user notifications PluginOutlet & summary class names

- app/assets/javascripts/discourse/tests/acceptance/create-account-from-login-test.js
- app/assets/javascripts/discourse/tests/acceptance/forgot-password-test.js
- app/assets/javascripts/discourse/tests/acceptance/groups-index-test.js
- app/assets/javascripts/discourse/tests/acceptance/login-redirect-test.js
- app/assets/javascripts/discourse/tests/acceptance/login-required-test.js
- app/assets/javascripts/discourse/tests/acceptance/mobile-sign-in-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-and-hide-email-address-taken-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-and-no-social-logins-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-disabled-test.js
- app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-test.js
- app/assets/javascripts/discourse/tests/acceptance/new-message-test.js
- app/assets/javascripts/discourse/tests/acceptance/new-topic-test.js
- app/assets/javascripts/discourse/tests/acceptance/sign-in-test.js
- app/assets/javascripts/discourse/tests/acceptance/static-test.js
- app/assets/javascripts/discourse/tests/helpers/create-pretender.js
Also simplifies plugin/theme tests, they no longer need to add similar pretenders.
> DEV: Add general pretender for passkey challenge

- app/assets/javascripts/discourse/app/templates/user/summary.hbs
> DEV: Wrap user summary category rows in plugin outlet

- app/assets/javascripts/admin/addon/components/site-settings/integer.hbs
- app/assets/stylesheets/common/base/discourse.scss
Regressed in f2e1363f6727ef837e957911f258ac436e09708e
> FIX: Site-setting integer input type

- app/assets/javascripts/admin/addon/components/site-settings/integer.hbs
- app/assets/stylesheets/common/base/discourse.scss
Regressed in f2e1363f6727ef837e957911f258ac436e09708e
> FIX: Site-setting integer input type (stable)

- Gemfile.lock
> DEV: Update platforms for Gemfile

- app/assets/stylesheets/common/foundation/colors.scss
- app/models/color_scheme.rb
Implementation after an unchallenged design experiment
https://meta.discourse.org/t/selected-list-item-background-colour/292487
> UX: Update selected colour var

- config/locales/server.en.yml
- lib/seed_data/topics.rb
- spec/lib/seed_data/topics_spec.rb
Broken in https://github.com/discourse/discourse/pull/25253
> FIX: missing translation of guidelines_topic.body

- config/locales/server.en.yml
- lib/seed_data/topics.rb
https://review.discourse.org/t/71308/4
> FIX: use feedback_category placeholder in i18n string

- app/models/topic_hot_score.rb
- spec/models/topic_hot_scores_spec.rb
1. Serial likers will just like a bunch of posts on the same topic, this will
heavily inflate hot score. To avoid artificial "heat" generated by one user only count
the first like on the topic within the recent_cutoff range per topic
2. When looking at recent topics prefer "unique likers", defer to total likes on
older topics cause we do not have an easy count for unique likers
3. Stop taking 1 off like_count, it is not needed - platforms like reddit
allow you to like own post so they need to remove it.
> DEV: adjustments to hot algorithm

- app/assets/javascripts/patches/content-tag+2.0.0.patch
- app/assets/javascripts/theme-transpiler/package.json
- app/assets/javascripts/yarn-ember3.lock
- app/assets/javascripts/yarn-ember5.lock
> DEV: Update content-tag to 2.0.0

- spec/system/email_change_spec.rb
> DEV: Clean up authenticator in email_change_spec

- README.md
> DEV: Replace Twitter screenshot with X screenshot

- app/assets/javascripts/discourse/app/components/discovery/topics.hbs
- app/assets/javascripts/discourse/app/components/discovery/topics.js
- app/assets/javascripts/discourse/app/components/topic-list.js
- app/models/topic_hot_score.rb
- spec/models/topic_hot_scores_spec.rb
1. Don't show visited line for hot filter, it is in random order
2. Don't count likes on non regular posts (eg: whispers / small actions)
3. Don't count participants in non regular posts
> FEATURE: improvements to hot feature

- lib/plugin/instance.rb
Followup to 1757a688c4749968db8e27623b975fc57519b97a
> FIX: Plugin image assets in production

- config/site_settings.yml
- db/migrate/20240112073149_fill_tag_topic_allowed_groups_based_on_deprecated_settings.rb
- db/migrate/20240201170412_fix_tag_topic_allowed_groups_setting.rb
- Update the existing migration to include staff and admin
- Update default values
- Added migration to include staff and admin cases
> DEV: Update min trust level to tag topics migration to groups

- config/site_settings.yml
- db/migrate/20231107055903_migrate_min_trust_level_for_here_mention_to_group.rb
- db/migrate/20240202204030_fix_here_mention_allowed_groups_setting.rb
- Created a new migration for here_mention
- Updated existing migration for here_mention
- Updated site settings for here_mention, create_tag, and
send_email_messages
> DEV: Correct some tl to group site setting changes

- app/assets/javascripts/admin/addon/components/site-settings/category-list.gjs
> DEV: Convert site-settings/category-list to glimmer component

- app/assets/javascripts/discourse/app/lib/user-menu/base-item.js
- app/assets/javascripts/discourse/tests/acceptance/notifications-test.js
- app/assets/javascripts/discourse/tests/fixtures/notification-fixtures.js
> FIX: Clicking a notification was triggering an error

- app/assets/javascripts/discourse/app/templates/composer/similar-topics.hbs
- app/assets/stylesheets/desktop/compose.scss
Regressed in https://github.com/discourse/discourse/pull/25545
> FIX: Similar topics relying on widget search menu

- app/assets/javascripts/service-worker.js.erb
Followup to c4559ae5751fce09b6d43f71887a310f7ba2670d
> DEV: Remove service-worker fetch handler entirely when cache disabled

- lib/hijack.rb
- lib/scheduler/defer.rb
- lib/work_queue.rb
- spec/lib/scheduler/defer_spec.rb
- spec/lib/work_queue_spec.rb
> PERF: Don't allow a single user to monopolize the defer queue

- app/assets/javascripts/admin/addon/components/site-settings/category-list.gjs
- app/assets/javascripts/discourse/app/models/category.js
Otherwise, if you pass in strings, strange things happen.
> DEV: Coalesce category ids to numbers

- app/assets/javascripts/discourse/app/models/category.js
> FIX: Add id to warn

- app/assets/javascripts/service-worker.js.erb
> FIX: Service worker push notifications when cache disabled

- app/assets/javascripts/discourse/app/models/post.js
- app/assets/javascripts/discourse/app/models/topic.js
This commit was created with a combination of the ember-native-class-codemod and manual cleanup
> DEV: Update `topic` and `post` models to native class syntax

- app/models/incoming_links_report.rb
- spec/models/incoming_links_report_spec.rb
See https://meta.discourse.org/t/reports-top-traffic-sources-topics-stat-issue/179850
> FIX: Respect date range in top traffic sources report

- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/app/models/group.js
> DEV: Resolve decorator import deprecations

- config/database.yml
Follow-up to 96ae5c395f6cf8bc256e2bbe8ebee88e4f6c9fb6
> DEV: Fix checkout time not properly enabled on CI

- app/assets/javascripts/discourse/app/models/nav-item.js
This commit was created with a combination of the ember-native-class-codemod and manual cleanup
> DEV: Update nav-item model to native class syntax

- app/assets/javascripts/discourse/app/models/user-stream.js
This commit was created with a combination of the ember-native-class-codemod and manual cleanup
> DEV: Convert UserStream model to native class syntax

- app/assets/javascripts/admin/addon/components/site-settings/category-list.gjs
> DEV: Clarify site-setting category-list concurrency protection

- plugins/chat/lib/chat/channel_fetcher.rb
- plugins/chat/spec/services/hashtag_autocomplete_service_spec.rb
> FIX: Look up all channel hashtags

- plugins/chat/spec/lib/chat/channel_hashtag_data_source_spec.rb
Follow up to commit 1403217ca4bbc4daba91a188d1b2757ed56d0a2d.
> DEV: Fix test

- app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.js
> DEV: Only autocomplete search result when suggestion keyword present

- app/assets/javascripts/discourse/app/components/discovery/topics.hbs
- app/assets/javascripts/discourse/app/components/discovery/topics.js
- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/models/topic-list.js
- app/assets/javascripts/discourse/app/models/topic-tracking-state.js
- app/assets/stylesheets/desktop/topic-list.scss
- app/assets/stylesheets/mobile/topic-list.scss
> UX: Add loading indicator when loading 'new or updated topics'

- lib/discourse_webauthn.rb
- spec/lib/concern/second_factor_manager_spec.rb
- spec/lib/discourse_webauthn/authentication_service_spec.rb
- spec/lib/discourse_webauthn/discourse_webauthn_spec.rb
- spec/lib/discourse_webauthn/registration_service_spec.rb
- spec/requests/session_controller_spec.rb
- spec/requests/users_controller_spec.rb
Stable backport of https://github.com/discourse/discourse/pull/25651
> FIX: Webauthn origin was incorrect for subfolder setups (stable)

- app/assets/javascripts/discourse/app/components/discovery/navigation.hbs
> FIX: Do not add `"tag-"` class to pages with no tag filter

- docs/INSTALL-cloud.md
This PR updates the outdated screenshots to match what users should see after the install.
> UX: Update INSTALL-cloud.md screenshots and copy when landed on the forum homepage

- app/assets/javascripts/discourse-markdown-it/src/engine.js
- app/assets/javascripts/discourse/app/instance-initializers/video-placeholder.js
- app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
- app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js
- app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js
- app/assets/stylesheets/common/base/onebox.scss
- app/models/post.rb
- lib/pretty_text.rb
- spec/system/composer_uploads_spec.rb
This change will allow auto generated video thumbnails to be used
instead of the black video thumbnail that overlays videos.
Follow up to: 2443446e62bff9dd8a0493d10e5359a5e946a84e
> FEATURE: Auto generate and display video preview image

- Gemfile.lock
- config/initializers/100-logster.rb
- config/locales/server.en.yml
Configure the backlink to the site from Logster.
Related PR https://github.com/discourse/logster/pull/220
> FEATURE: backlink to the site from Logster

- Gemfile.lock
> DEV: bump Logster version to 2.17.1

- app/models/topic_hot_score.rb
- lib/topic_query.rb
- spec/lib/topic_query_spec.rb
pinned topics should be pinned even on hot lists so it can be used as a
home page
> FEATURE: apply pinning to hot topic lists

- plugins/chat/assets/stylesheets/common/chat-channel-card.scss
> UX: better card alignment

- config/discourse_defaults.conf
- spec/requests/static_controller_spec.rb
Followup to c4559ae5751fce09b6d43f71887a310f7ba2670d
> DEV: Disable service worker caching by default

- plugins/chat/assets/javascripts/discourse/components/chat/modal/create-channel.js
> FIX: Correct category name for auto_join_users_info in chat

- app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.gjs
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
- app/controllers/categories_controller.rb
- app/jobs/base.rb
- app/models/category.rb
- app/services/search_indexer.rb
- spec/models/category_spec.rb
- spec/requests/categories_controller_spec.rb
- spec/system/editing_sidebar_categories_navigation_spec.rb
> DEV: Async category search for sidebar modal

- app/assets/stylesheets/common/base/onebox.scss
A followup to 62e36145c550eebc7541d0346d25133b2c37053c
> UX: Fix the video spinner css

- app/assets/javascripts/discourse-common/package.json
- app/assets/javascripts/discourse/package.json
- app/assets/javascripts/yarn-ember3.lock
- app/assets/javascripts/yarn-ember5.lock
This reverts commit ec63f2b876eca4f8acea9eb6015a0c3acbf35eeb.
Broke the build
> Revert "Build(deps): Bump @uppy/drop-target from 2.0.1 to 2.0.4 in /app/assets/javascripts (#25772)"

- app/assets/stylesheets/common/base/modal.scss
- app/assets/stylesheets/mobile/login-modal.scss
* Prevent modal-close button from moving when there is no modal title (which shouldn't be the case though)
* Remove touch class wrapper
> UX: Modal mobile fixes

- app/controllers/categories_controller.rb
> FIX: Make /categories/search order deterministic

- app/serializers/application_serializer.rb
- lib/distributed_cache.rb
- lib/stylesheet/manager.rb
> DEV: Reduce duplication with DistributedMutex#clear_regex

- app/assets/javascripts/discourse/public/assets/scripts/discourse-test-trigger-ember-cli-boot.js
- app/assets/javascripts/discourse/tests/index.html
> DEV: Remove a duplicated file

- app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
- app/assets/javascripts/select-kit/addon/components/bulk-select-topics-dropdown.js
- config/locales/client.en.yml
This change updates the experimental bulk-select-dropdown (that is
currently feature-flagged) with more buttons.
> DEV: Add more bulk-select-dropdown options

- plugins/chat/assets/stylesheets/mobile/chat-composer.scss
> UX: chat composer >  fix typing indicator and top padding (mobile)

- plugins/chat/assets/stylesheets/mobile/chat-composer.scss
> UX: Chat > send btn alignment + hardcoded value fix

- app/assets/javascripts/discourse/app/components/sidebar/switch-panel-buttons.js
> FIX: do not raise error on transition aborted

- app/assets/javascripts/discourse/app/components/composer-container.hbs
- app/assets/javascripts/discourse/app/components/composer-toggles.hbs
- app/assets/javascripts/discourse/app/components/composer-toggles.js
- app/assets/javascripts/discourse/tests/acceptance/composer-uncategorized-test.js
- app/assets/stylesheets/common/base/compose.scss
- app/assets/stylesheets/desktop/compose.scss
This reverts commit 13eabff7399811695071956a6f5eeb8246bd673f due to issues when testing on both iOS and Android. See https://meta.discourse.org/t/expand-composer-button-on-mobile/296469
> Revert "UX: allow fullscreen composer on mobile (#25787)"

- app/assets/javascripts/admin/addon/components/modal/install-theme.hbs
- config/locales/client.en.yml
This commit adds a loading spinner when installing a theme as sometimes
installing a theme can take quite a bit of time this way we have some
indication that things are still working as the theme is being
installed.
> DEV: Add loading spinner to install theme modal

- app/assets/javascripts/discourse/package.json
- yarn.lock
> DEV: Remove ember-router-service-refresh-polyfill

- lib/tasks/smoke_test.rake
- package.json
- test/smoke-test.mjs
- yarn.lock
> DEV: Update chrome-launcher from 0.15.2 to 1.1.0

- lib/theme_settings_object_validator.rb
What does this change do?
1. Reduce an additional loop through all the properties
2. Extract the validation of child objects into a dedicate method
> DEV: Refactor `ThemeSettingsObjectValidator#validate`

- plugins/chat/assets/stylesheets/common/chat-message-separator.scss
- plugins/chat/assets/stylesheets/desktop/chat-composer-uploads.scss
- plugins/chat/assets/stylesheets/mobile/chat-composer.scss
1. keep send icon active when keyboard is hidden (mobile)
2. keep composer insert button at bottom
⬇️ 
4. equal separator padding
⬇️
> UX: chat > general fixes

- app/assets/javascripts/discourse/config/deprecation-workflow.js
We'll unsilence once we've published a clear upgrade path.
> DEV: Silence header upgrade deprecations for now

- plugins/chat/spec/system/update_last_read_spec.rb
> DEV: attempts to make last spec non flakey

- app/services/post_alerter.rb
Explanation is in code a bit.. plugin customizations need this moved up.
> DEV: Move DiscourseEvent trigger in PostAlerter#push_notification

- app/serializers/found_user_with_status_serializer.rb
A followup to b3a1199493a5974353449e2b3f1b30d9eabbff59.
> DEV: Deprecate FoundUserWithStatusSerializer

- lib/stylesheet/manager.rb
> DEV: Prefer defer_get_set over get/set on DistributedCache

- app/services/post_alerter.rb
- plugins/chat/app/jobs/regular/chat/notify_watching.rb
- plugins/chat/spec/jobs/regular/chat/notify_watching_spec.rb
- spec/services/post_alerter_spec.rb
> DEV: Add push notification filtering to MessageBus alerts

- app/models/incoming_email.rb
- db/migrate/20240304030429_topic_id_on_incoming_email_index.rb
This table may grow to be large, and an index on this column improves performance for SELECT queries.
> DEV: add topic_id index to incoming_emails table

- plugins/chat/spec/system/update_last_read_spec.rb
> DEV: skip flakey last read spec

- plugins/chat/spec/system/reply_to_message/smoke_spec.rb
> DEV: quit session asap

- app/assets/javascripts/discourse/app/components/glimmer-header/icons.gjs
- app/assets/javascripts/discourse/app/lib/dag.js
- app/assets/javascripts/discourse/app/lib/plugin-api.gjs
- app/assets/javascripts/discourse/app/lib/plugin-api.js
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/tests/unit/lib/dag-test.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
- plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
> FEATURE: Introduce APIs for manipulating header icons

- app/assets/javascripts/admin/addon/components/modal/penalize-user.js
- app/assets/javascripts/discourse/tests/acceptance/flag-post-test.js
- config/locales/server.en.yml
- config/site_settings.yml
> FEATURE: site setting to include post in penalty messages

- app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
- app/assets/stylesheets/common/modal/modal-overrides.scss
- config/locales/client.en.yml
- Add cancel button
- Add loading spinner
- Add toast
> DEV: More bulk select modal enhancements

- spec/system/page_objects/pages/search.rb
- spec/system/search_spec.rb
Follow up to: https://github.com/discourse/discourse/pull/25504
> DEV: Add system test for soft loading topic search results

- plugins/chat/assets/stylesheets/common/chat-message-creator.scss
> UX: fix fontsize and weight for prioritize username setting

- script/bulk_import/base.rb
- script/bulk_import/generic_bulk.rb
* FEATURE: Import into `category_users` table
* FIX: Failed to import `user_options` unless `timezone` was set
* FIX: Prevent reusing original `id` from intermediate DB in `user_fields`
* FEATURE: Order posts by `post_nuber` if available
* FEATURE: Allow `[mention]` placeholder to reference users by"id" or "name" (username)
* FEATURE: Support `[quote]` placeholders in posts
* FEATURE: Support `[link]` placeholders in posts
* FEATURE: Support all kinds of permalinks and remove support for `old_relative_url`
* PERF: Speed up pre-cooking by removing DB lookups
> DEV: Improve generic import script

- spec/system/page_objects/components/select_kit.rb
> DEV: Added `has_option_value` test to SelectKit system spec component

- plugins/chat/spec/system/reply_to_message/smoke_spec.rb
> DEV: rely on default session in smoke spec

- app/assets/stylesheets/common/components/more-topics.scss
> UX: left align suggested topics header and footer text

- app/assets/javascripts/discourse/app/components/glimmer-header/home-logo.gjs
> DEV: Update home logo click action location

- app/assets/javascripts/discourse-markdown-it/src/engine.js
- app/assets/javascripts/discourse/app/instance-initializers/video-placeholder.js
- app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js
- app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js
- app/assets/stylesheets/common/base/onebox.scss
- app/models/post.rb
- lib/pretty_text.rb
- spec/system/composer_uploads_spec.rb
- **FIX: Video playback on iOS (#25513)**
- **FEATURE: Auto generate and display video preview image (#25633)**
- **FIX: Add a boarder around the video placeholder play button (#25727)**
- **FIX: Set the video background to be black (#25744)**
- **UX: Tweak play button css (#25754)**
- **UX: Fix the video spinner css (#25770)**
> DEV: Video placeholder fixes

- .github/workflows/release-notes.yml
> DEV: Fix input definition for release-notes workflow

- .github/workflows/release-notes.yml
> DEV: Improve output of release-notes task to include start/end info

- app/assets/javascripts/discourse/app/components/glimmer-header.gjs
- spec/system/header_spec.rb
- spec/system/page_objects/pages/header.rb
- spec/system/page_objects/pages/search.rb
> FIX: In topic search for glimmer header

- app/assets/javascripts/discourse/app/adapters/topic-list.js
- app/assets/javascripts/discourse/app/controllers/user-activity-bookmarks.js
- app/assets/javascripts/discourse/app/models/topic-list.js
- app/assets/javascripts/discourse/app/models/topic.js
- app/assets/javascripts/discourse/app/routes/user-activity-bookmarks.js
- app/assets/javascripts/discourse/app/services/route-scroll-manager.js
- app/assets/javascripts/discourse/app/services/store.js
- app/assets/javascripts/discourse/tests/acceptance/homepage-test.js
> DEV: Add model transformation hooks in more locations

- app/assets/stylesheets/common/components/buttons.scss
- app/assets/stylesheets/common/foundation/variables.scss
Found the updated hex from the logo on their homepage, and apparently if the button isn't blue they want us to use black and white! https://developers.facebook.com/docs/facebook-login/userexperience/#buttondesign
> UX: update Facebook blue hex, add comment about button color

- app/assets/javascripts/discourse/app/components/search-menu.hbs
- app/assets/javascripts/discourse/app/components/search-menu.js
- app/assets/javascripts/discourse/app/components/search-menu/advanced-button.hbs
- app/assets/javascripts/discourse/tests/acceptance/search-test.js
- app/assets/stylesheets/common/base/search-menu.scss
https://github.com/discourse/discourse/assets/50783505/91d9c7e1-615f-4618-81fb-f77a7155145e
https://github.com/discourse/discourse/assets/50783505/d9bcf343-df6a-46de-b5a7-e68775765992
> DEV: Close search menu after advanced search is clicked

- app/assets/javascripts/discourse-widget-hbs/lib/widget-hbs-compiler.js
> DEV: Fix glimmer node deprecations

- app/assets/javascripts/discourse/app/components/glimmer-header/hamburger-dropdown-wrapper.gjs
> FIX: Don't prevent opening regular links in 🍔wrapper

- app/assets/javascripts/discourse/app/components/glimmer-header/topic/info.gjs
> FIX: Correct pm icon link in glimmer header

- app/assets/javascripts/discourse/app/components/glimmer-header/hamburger-dropdown-wrapper.gjs
- app/assets/javascripts/discourse/app/components/glimmer-header/user-menu-wrapper.gjs
- app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
- app/assets/javascripts/discourse/app/components/site-header.js
- app/assets/javascripts/discourse/app/widgets/header.js
`classList` doesn't have a `direction` property
> FIX: Correctly detect RTL

- app/assets/javascripts/discourse/app/components/user-menu/menu.js
- app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
> FIX: Close user menu on navigation

- config/locales/server.en.yml
> DEV: Update the description for `include_in_discourse_discover`

- app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
> DEV: Fix build due to 3a4f4abdc9d6a1dbbd1535726bbf5931a5c37e1c

- lib/tasks/compatibility.rake
- spec/tasks/compatibility_spec.rb
> DEV: Introduce rake task to validate discourse-compatibility file

- app/assets/javascripts/discourse/app/routes/build-private-messages-route.js
> FIX: Hide suggestion to send PMs when PMs are disabled for user

- app/assets/javascripts/discourse/app/components/glimmer-header/user-dropdown/notifications.gjs
Followup to f2ac9e4c12e8f5adcf31d7550bca554fde90998c
> UX: Update glimmer header with new dnd icon

- app/assets/javascripts/discourse/config/deprecation-workflow.js
https://meta.discourse.org/t/296544
> DEV: Unsilence header-related deprecations

- app/serializers/found_user_with_status_serializer.rb
This is a follow-up to https://github.com/discourse/discourse/pull/25883. Somehow I forgot to address this [comment](https://github.com/discourse/discourse/pull/25883#discussion_r1503234622) before merging that PR.
> DEV: correct deprection versions of FoundUserWithStatusSerializer

- app/assets/javascripts/discourse/app/lib/d-popover.js
> DEV: Add discourse prefix to d-popover deprecations

- spec/requests/categories_controller_spec.rb
> DEV: Regression test for categories N+1

- app/assets/javascripts/discourse/app/components/post-text-selection.gjs
> UX: do not close post text selection on scroll

- plugins/chat/test/javascripts/unit/services/chat-channel-info-route-origin-manager-test.js
channnel -> channel
and use `assert.true()/assert.false()`
> DEV: Fix typos in a chat service tests

- app/assets/javascripts/discourse/app/components/search-menu/results.hbs
https://github.com/discourse/discourse/assets/50783505/17d2f1d8-3cff-41b7-824a-c5bd1ef673d5
> FIX: "Flash" when loading search results

- app/assets/javascripts/discourse/tests/index.html
- app/assets/stylesheets/qunit-custom.scss
- app/views/qunit/theme.html.erb
Fixes a semi-recent regression and adds dark color scheme css vars so the rendered app content in tests is dark too.
> DEV: Fix dark mode in QUnit

- app/assets/javascripts/discourse/app/widgets/header.js
> DEV: Support new header button/icon ordering APIs on widget header

- app/assets/javascripts/discourse/app/lib/plugin-api.gjs
> DEV: Fix toolbar API deprecation message

- app/assets/javascripts/discourse/app/static/wizard/components/wizard-field.gjs
> DEV: add a plugin outlet below wizard extra description

- app/assets/javascripts/discourse-common/addon/lib/icon-library.js
- app/assets/javascripts/discourse/app/components/sidebar/common/all-categories-section-link.hbs
- app/assets/javascripts/discourse/app/components/user-menu/menu.js
- app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.hbs
- app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/my-posts-section-link.js
- app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
> DEV: Add icon aliases

- app/assets/stylesheets/common/admin/schema_field.scss
> UX: Improve layout of theme objects setting editor

- app/models/category.rb
- spec/requests/categories_controller_spec.rb
> FIX: Set has_children correctly in Category.preload_user_fields!

- app/jobs/regular/notify_reviewable.rb
backport for: https://github.com/discourse/discourse/pull/26330
> PERF: only allow one reviewable notification at a time

- spec/lib/pretty_text_spec.rb
> DEV: Add a watched-words/mini_racer perf regression spec

- app/assets/javascripts/discourse/app/components/actions-summary.gjs
- app/assets/javascripts/discourse/app/components/small-user-list.gjs
- app/assets/javascripts/discourse/app/widgets/actions-summary.js
- app/assets/javascripts/discourse/app/widgets/post-menu.js
- app/assets/stylesheets/common/base/topic-post.scss
> DEV: Convert actions-summary to a component

- app/models/category_list.rb
> DEV: Reduce duplication

- .github/workflows/tests.yml
- app/assets/javascripts/discourse/testem.js
> DEV: Switch to Chromium in CI

- app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
- app/assets/javascripts/discourse/app/lib/plugin-api.gjs
- app/assets/javascripts/select-kit/addon/components/bulk-select-topics-dropdown.js
Adds a plugin api for the bulk actions dropdown.
> DEV: Bulk Actions Dropdown Plugin API

- lib/svg_sprite.rb
> UX: Add Threads fab icon

- spec/system/page_objects/components/dialog.rb
> DEV: Adds click_ok method on system spec dialog component

- app/assets/javascripts/discourse/app/lib/download-calendar.js
This part of the commit has been mistakenly forgotten from https://github.com/discourse/discourse/commit/bddc41b7adda5879df93a0e0f8f6cafa2d4b40f5
> FIX: calendar options part 2

- app/models/user_action.rb
> DEV: Add missing belongs_to to UserAction model

- app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
- app/assets/javascripts/discourse/app/raw-templates/topic-list-header-column.hbr
- app/assets/javascripts/select-kit/addon/components/bulk-select-topics-dropdown.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/site_settings.yml
- Setting is no longer hidden
- descriptions have been moved to the modal
- Removed ... from one of the dropdown titles
> DEV: Various bulk-select dropdown tweaks

- app/assets/javascripts/discourse/app/controllers/topic.js
- lib/presence_channel.rb
- script/import_scripts/phpbb3/settings.yml
- spec/requests/users_controller_spec.rb
> chore: remove repetitive words

- app/assets/javascripts/discourse/app/lib/form-template-validation.js
- config/locales/client.en.yml
- spec/system/composer/template_validation_spec.rb
Our translation files use the snake case convention so let us keep it that way.
> DEV: Fix case inconsistency in translation file

- config/locales/client.en.yml
> UX: tweaks enable defer setting copy

- config/locales/client.en.yml
> UX: changes defer copy to mark unread

- .github/workflows/tests.yml
- app/assets/javascripts/discourse/testem.js
- app/assets/javascripts/discourse/tests/acceptance/search-test.js
- lib/tasks/qunit.rake
> DEV: Restore qunit 'tap' reporter, but collapse per-test output

- app/assets/javascripts/discourse/app/routes/new-topic.js
The "new topic" route can open the composer with a category preselected. This commit ensures that the category is loaded before the composer is opened.
> FIX: Load category before opening composer

- lib/version.rb
> DEV: Add a note about the version bump rake tasks

- app/assets/javascripts/discourse/app/components/search-menu/results.hbs
- app/assets/javascripts/discourse/app/components/search-menu/results.js
- app/assets/javascripts/discourse/app/components/search-menu/results/types.hbs
- app/assets/javascripts/discourse/app/components/search-menu/results/types.js
- app/assets/javascripts/discourse/app/widgets/header.js
- app/assets/javascripts/discourse/tests/acceptance/search-test.js
- spec/system/search_spec.rb
This logic wasn't fully ported to the new search menu implementation.
> FIX: Log search result clicks in header search menu

- spec/system/user_tips_spec.rb
> DEV: Fix flakey user tips spec

- app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.hbs
- app/assets/javascripts/discourse/app/components/user-tip-container.gjs
- Adjusts placement
- Closes the tip when the user clicks on a link in the tip description
> DEV: Fix issues with "admin guide" tip

- config/locales/client.en.yml
> UX: better copy for reminder set

- app/assets/javascripts/discourse/app/instance-initializers/click-interceptor.js
- app/assets/javascripts/discourse/app/lib/intercept-click.js
> DEV: De-jQ click-interceptor

- app/assets/stylesheets/common/base/menu-panel.scss
> UX: Fix user menu ellipsis color

- app/assets/javascripts/discourse-common/addon/lib/icon-library.js
- app/assets/javascripts/discourse/app/lib/notification-types-manager.js
- app/assets/javascripts/discourse/app/lib/notification-types/linked-consolidated.js
- app/assets/javascripts/discourse/tests/fixtures/concerns/notification-types.js
- app/assets/javascripts/discourse/tests/unit/lib/notification-types/linked-consolidated-test.js
- app/models/notification.rb
- app/services/notifications/consolidation_planner.rb
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/site_settings.yml
- spec/requests/api/schemas/json/site_response.json
- spec/services/notifications/consolidation_planner_spec.rb
Just like we have for consolidating likes this adds similar
functionality for consolidating links.
> FEATURE: Consolidate link notifications

- plugins/chat/spec/system/move_message_to_channel_spec.rb
> DEV: Fix flaky test when moving threads

- app/assets/javascripts/admin/addon/models/web-hook.js
- app/assets/javascripts/discourse/app/services/store.js
- app/assets/javascripts/discourse/tests/acceptance/admin-webhooks-test.js
- app/controllers/admin/web_hooks_controller.rb
- app/serializers/admin_web_hook_serializer.rb
> DEV: Remove Category.findById from admin web hooks

- app/assets/javascripts/discourse/app/components/topic-timeline/back-button.hbs
"[en.Go back to your last unread post]" ain't it 😉
> FIX: Broken timeline back button title

- app/assets/javascripts/discourse/app/components/bookmark-menu.gjs
- spec/system/bookmarks_spec.rb
This fixes a timing issue where, if a user (or the CI) was
on a slow network connection, clicking one of the bookmark
menu options would cause an error because we hadn't yet received
the response from the server after creating the bookmark.
It should be very smooth most of the times because (paraphrasing j.jaffeux):
a) Most likely when user clicks it’s already saved
b) If it’s not saved when user clicks, it should already be almost done so
the perceived wait when click the reminder option should be rather short
> FIX: Wait for bookmark save before allowing menu button click

- app/assets/javascripts/discourse/app/instance-initializers/message-bus.js
Previously it was split across multiple functions, and had multiple logic branches. This commit consolidates it into a single `mbAjax` function
> DEV: Consolidate message-bus ajax implementation

- app/assets/javascripts/discourse/app/raw-templates/post/poster-avatar.hbr
> DEV: Remove an unused hbr template

- app/assets/javascripts/discourse/app/lib/fabricators.js
I will add new default properties as needed in the future, but for now this is enough to have an entry point.
> DEV: minimum fabricators for post/topic

- plugins/footnote/assets/javascripts/initializers/inline-footnotes.js
- plugins/footnote/test/javascripts/acceptance/footnote-test.js
Also: fixes typos, updates tests, and moves the tooltip element into document.body
> FEATURE: Allow dismissing tooltips by clicking their button

- app/assets/javascripts/discourse/app/components/header.gjs
> DEV: Don't leak the topic model through `minimized` arg

- app/assets/javascripts/discourse/app/components/sidebar/filter.gjs
The most important change being the replacement of `Input` component with an `<input>` element.
> DEV: Clean up sidebar/filter.gjs

- app/assets/javascripts/discourse/app/instance-initializers/auth-complete.js
> DEV: Allow auth errors to render HTML

- app/services/theme_settings_migrations_runner.rb
- spec/services/theme_settings_migrations_runner_spec.rb
This commit adds a `getCategoryIdByName` helper function to the context in
which theme migrations are ran in. The purpose of this commit is to
allow themes which may have stored category names in theme settings to
migrate to objects typed theme settings which supports properties of
categories typed which stores the category ids in the value of the
property.
> DEV: Add `getCategoryIdByName` helper function to theme migrations

- app/models/user.rb
- spec/jobs/enable_bootstrap_mode_spec.rb
We already skipping the admin welcome message for the first admin user. We should also skip the moderator message.
> DEV: don't send moderator welcome message to first admin.

- app/assets/javascripts/discourse/app/components/subcategories-with-featured-topics.hbs
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/tests/fixtures/discovery-fixtures.js
> FIX: Use serialized subcategories in subcategory-with-featured-topics

- app/assets/javascripts/select-kit/addon/components/user-notifications-dropdown.js
The icon has been changed from "user" to "bell" to make this level more clear.
> UX: changes normal level icon for user-notifications

- app/assets/javascripts/select-kit/addon/components/user-notifications-dropdown.js
- config/locales/client.en.yml
- changes mute icon to bell-slash
- changed mute text
- changed ignore text
> UX:minor tweaks to user notifications dropdown

- app/assets/javascripts/admin/addon/models/web-hook.js
- app/assets/javascripts/discourse/tests/acceptance/admin-webhooks-test.js
> FIX: Selecting categories for new admin webhooks

- app/assets/javascripts/admin/addon/components/cancel-link.js
- app/assets/javascripts/discourse/app/components/cancel-link.hbs
- app/assets/javascripts/discourse/app/components/cancel-link.js
- app/assets/javascripts/discourse/app/templates/preferences-email.hbs
- app/assets/javascripts/discourse/app/templates/preferences-second-factor.hbs
No need for this small component (and its unused and empty admin component twin)
> DEV: Inline cancel-link code

- app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
- app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
- app/serializers/current_user_serializer.rb
- config/site_settings.yml
- spec/system/admin_sidebar_navigation_spec.rb
Enable a new sidebar for moderators with limited links.
> FEATURE: new admin sidebar for moderators

- app/assets/javascripts/discourse/app/components/d-modal.gjs
We were disabling on setup, but if the modal was not closed correctly we wouldn't re-enable body scroll on destroy of the body. This should ensure it's always correctly cleared. This also avoids a `document.querySelector` which is always preferable.
> FIX: correctly enable/disable body scroll on modal

- lib/middleware/request_tracker.rb
> DEV: Log original exception/backtrace for RequestTracker errors

- plugins/chat/assets/javascripts/discourse/components/chat-thread-title-prompt.js
- plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
Followup: write a test for this
> FIX: correctly check the user id of the original message

- lib/search.rb
- spec/lib/search_spec.rb
> FIX: Do not show hidden posts in search results

- app/assets/javascripts/discourse/app/components/topic-admin-menu.gjs
> FIX: Do not show empty list in the topic admin menu

- plugins/chat/assets/stylesheets/common/chat-user-threads.scss
> FIX: prevents long URL to overflow thread title

- app/assets/javascripts/float-kit/addon/lib/update-position.js
Implements this custom placement strategy: https://floating-ui.com/docs/offset#creating-custom-placements
> DEV: Add `placement: center` option to float-kit

- lib/discourse_tagging.rb
- spec/lib/discourse_tagging_spec.rb
> FIX: Handle tags with underscores correctly

- plugins/chat/lib/chat/engine.rb
> DEV: Eager load chat's scheduled jobs in development mode

- spec/system/page_objects/components/dialog.rb
Some dialogs are dangerous...we need to accommodate that too.
> DEV: Add confirm_danger to Dialog page object

- app/assets/stylesheets/common/base/topic-admin-menu.scss
> FIX: Select posts menu styles

- app/assets/javascripts/discourse/app/components/modal/download-calendar.js
- app/assets/javascripts/discourse/app/lib/download-calendar.js
- app/assets/javascripts/discourse/tests/unit/lib/download-calendar-test.js
> FIX: adds support for location and details in ICS calendar

- app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.gjs
- spec/system/editing_sidebar_categories_navigation_spec.rb
> DEV: Make edit sidebar categories modal load more results incrementally

- plugins/poll/assets/javascripts/lib/discourse-markdown/poll.js
- plugins/poll/spec/lib/pretty_text_spec.rb
Polls should work when "nested" inside a quote or a details block.
Internal ref - t/89085
> FIX: nested polls

- lib/read_only_mixin.rb
- spec/requests/application_controller_spec.rb
> FIX: Serialization of staff_writes_only

- docs/ADMIN-QUICK-START-GUIDE.md
- Use a single checklist at the top
- Link to appropriate settings where appropriate
- Encourage people to invite others earlier
- Encourage iteration prior to launch
- Move most external links to bottom "Learn More" section
> UX: Update getting started guide

- script/bench.rb
This commit updates `script/bench.rb` to only support Unicorn as the web
server. We don't intend to run Puma in production anytime soon so it is
pointless for us to maintain Puma related code.
> DEV: Drop puma from `script/bench.rb`, default to Unicorn

- app/assets/javascripts/admin/addon/routes/admin-backups.js
- app/assets/javascripts/discourse/app/controllers/user.js
- app/assets/javascripts/discourse/app/models/category.js
- app/assets/javascripts/discourse/app/models/post-stream.js
- app/assets/javascripts/discourse/app/models/post.js
- app/assets/javascripts/discourse/app/models/topic-tracking-state.js
- app/assets/javascripts/discourse/app/models/topic.js
- app/assets/javascripts/discourse/app/models/user-action.js
- app/assets/javascripts/discourse/app/models/user-draft.js
- app/assets/javascripts/discourse/app/models/user.js
- app/assets/javascripts/discourse/app/routes/discovery.js
- app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
- app/assets/javascripts/discourse/tests/unit/models/post-stream-test.js
- app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js
> DEV: Use current-user service wherever possible

- app/assets/javascripts/discourse/app/templates/wizard/step.gjs
- spec/system/wizard_spec.rb
Reverts discourse/discourse#26873
> Revert "FEATURE: revert redirect from wizard to guide"

- app/assets/javascripts/discourse/app/models/category.js
> FIX: inject current user service in category model

- lib/onebox/helpers.rb
- spec/lib/onebox/helpers_spec.rb
In 95a82d608d6377faf68a0e2c5d9640b043557852, we lowered the default for
`Onebox.options.max_download_kb` from 10mb to 2mb for security hardening
purposes. However, this resulted in multiple bug reports where seemingly
nomral URLs stopped being oneboxed. It turns out that lowering
`Onebox.options.max_download_kb` resulted in `Onebox::Helpers::DownloadTooLarge` being raised
more often for more URLs  in `Onebox::Helpers.fetch_response` which
`Onebox::Helpers.fetch_html_doc` relies on. When
`Onebox::Helpers::DownloadTooLarge` is raised in
`Onebox::Helpers.fetch_response`, we throw away whatever response body
which we have already downloaded at that point. This is not ideal
because Nokogiri can parse incomplete HTML documents and there is a
really high chance that the incomplete HTML document …
> FIX: Attempt to onebox even if response body exceeds `max_download_kb`

- app/assets/stylesheets/desktop/discourse.scss
- app/assets/stylesheets/desktop/header.scss
570px -> `mobile-extra-large` (550px)
> UX: Use breakpoint CSS variable instead of arbitrary 570px

- app/assets/javascripts/discourse/app/components/sidebar/section.js
- app/assets/javascripts/discourse/app/components/sidebar/toggle-all-sections.gjs
- app/assets/javascripts/discourse/app/services/sidebar-state.js
> DEV: Simplify sidebar's `collapsedSections`

- app/assets/javascripts/discourse/app/services/presence.js
> DEV: Check lifetime props in the Presence service

- app/assets/javascripts/discourse/app/mixins/load-more.js
- app/assets/javascripts/discourse/app/mixins/scrolling.js
- app/assets/javascripts/discourse/tests/setup-tests.js
> DEV: Remove unused `screenNotFull` code

- app/assets/javascripts/discourse/app/components/header/user-dropdown/notifications.gjs
> FIX: Incorrect user menu title/alt

- app/assets/javascripts/discourse/app/components/header/user-dropdown/notifications.gjs
> DEV: Add plugin outlets on the user-dropdown/notifications component

- app/assets/javascripts/discourse/app/components/sidebar/switch-panel-buttons.gjs
- plugins/chat/assets/javascripts/discourse/initializers/chat-sidebar.js
- plugins/chat/assets/javascripts/discourse/routes/chat.js
- plugins/chat/assets/javascripts/discourse/services/chat-state-manager.js
- plugins/chat/spec/system/separate_sidebar_mode_spec.rb
> FIX: Sidebar mode switching on subfolder

- plugins/chat/assets/stylesheets/common/chat-message-images.scss
> DEV: Remove legacy styles for LazyYT

- lib/tasks/version_bump.rake
> DEV: Use the correct open command in the version bump rake task

- plugins/chat/db/migrate/20240409093348_add_show_thread_title_prompts_to_user_options.rb
- plugins/chat/db/migrate/20240516145911_update_user_options_for_thread_title_prompts.rb
- plugins/chat/db/post_migrate/20240516145911_update_user_options_for_thread_title_prompts.rb
> DEV: update thread title prompt migration

- app/assets/javascripts/discourse/app/components/header/home-logo.gjs
- app/assets/javascripts/discourse/app/components/header/topic/info.gjs
* Add `header-topic-info__before` and `header-topic-info__after` outlets
> DEV: Add new plugin outlets in the `header/topic/info` component

- spec/system/bookmarks_spec.rb
Not much value in keeping this around
> DEV: Delete bookmark slow connection flaky

- app/jobs/regular/bulk_invite.rb
- config/locales/server.en.yml
- spec/jobs/bulk_invite_spec.rb
```
[2024-05-17 08:49:54 -0600] Invalid User Field 'backend name' for 'foobarbing@gmail.com'
[2024-05-17 08:49:54 -0600] Invalid Email 'test
[2024-05-17 08:49:54 -0600] Invalid Email 'this@$@**.com
```
> DEV: Update bulk-invite logs and PM template

- .licensed.yml
> DEV: Add mutex_m to reviewed gems

- app/assets/javascripts/discourse/app/components/topic-list/topic-list-header.gjs
> DEV: Add missing `tr` wrapper to glimmer topic-list-header

- plugins/chat/spec/system/chat_new_message_spec.rb
> DEV: Fix flaky spec when creating a chat message from params

- app/assets/javascripts/discourse/app/components/sidebar/toggle-all-sections.gjs
- app/assets/stylesheets/common/base/sidebar.scss
> UX: Change admin toggle all icon

- app/assets/javascripts/discourse/app/components/header/user-dropdown.gjs
> DEV: Add the `user-dropdown-button__before` and `user-dropdown-button__after` plugin outlets

- app/assets/javascripts/discourse/app/components/topic-list/list.gjs
- spec/system/topic_list/glimmer_spec.rb
> DEV: Fix glimmer suggested topic item badges

- app/assets/javascripts/discourse/app/lib/desktop-notifications.js
https://github.com/discourse/discourse/pull/27127
> DEV: review follow up

- plugins/chat/app/controllers/chat/api/channel_messages_controller.rb
- plugins/chat/app/services/chat/trash_message.rb
- plugins/chat/app/services/chat/trash_messages.rb
- plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs
- plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/modal/delete-messages-confirm.gjs
- plugins/chat/assets/javascripts/discourse/components/chat/selection-manager.gjs
- plugins/chat/assets/javascripts/discourse/services/chat-api.js
- plugins/chat/config/locales/client.en.yml
- plugins/chat/config/routes.rb
- plugins/chat/spec/services/chat/trash_messages_spec.rb
- plugins/chat/spec/system/deleted_message_spec.rb
- plugins/chat/spec/system/page_objects/chat/components/selection_management.rb
> FEATURE: Allow to bulk delete chat messages

- config/locales/server.en.yml
> DEV: Update Discover URL

- app/assets/javascripts/discourse/tests/integration/components/home-logo-test.gjs
- app/assets/javascripts/discourse/tests/integration/components/widgets/home-logo-test.gjs
> DEV: Fix home-logo test flakes

- spec/system/editing_sidebar_categories_navigation_spec.rb
- spec/system/user_tips_spec.rb
> DEV: Fix a flakey test, skip another one

- app/models/post_action_type.rb
When the database is disabled, flags cannot be loaded. In that case, we should fallback to static FlagSetting.
> FIX: don't load database flag when database is disabled

- app/models/post.rb
- spec/models/post_spec.rb
This commit updates `Post#each_upload_url` to reject URLs that do not
have a host which matches `Discourse.current_hostname` but follows the
`/uploads/short-url` uploads URL format. This situation most commonly
happen when users copy upload URL link between different Discourse
sites.
> FIX: `Post#each_upload_url` yielding external URLs

- spec/support/omniauth_helpers.rb
- spec/system/login_spec.rb
- spec/system/page_objects/modals/login.rb
- spec/system/page_objects/modals/signup.rb
- spec/system/signup_spec.rb
- spec/system/social_authentication_spec.rb
> DEV: More system specs for signup/login

- lib/onebox/engine/twitter_status_onebox.rb
- lib/onebox/helpers.rb
> FIX: Add onebox support for x.com

- spec/models/flag_spec.rb
> FIX: change around to after in flag spec

- app/controllers/topic_view_stats_controller.rb
- app/models/topic.rb
- app/models/topic_view_item.rb
- app/models/topic_view_stat.rb
- config/locales/server.en.yml
- config/routes.rb
- db/migrate/20240527015009_add_topic_view_stats.rb
- spec/models/topic_view_item_spec.rb
- spec/requests/topic_view_stats_controller_spec.rb
This gives us daily fidelity of topic view stats
New table stores a row per topic viewed per day tracking
anonymous and logged on views
> FEATURE: topic_view_stats table with daily fidelity

- app/assets/javascripts/discourse/app/templates/topic.hbs
> DEV: linting

- spec/models/color_scheme_spec.rb
We were adding the custom scheme as a symbol, but trying to delete the string. Which would result in the symbol to not be removed.
This was causing errors in others test:
```
Error encountered while proccessing /admin/color_schemes.json  I18n::MissingTranslationData: Translation missing: en.color_schemes.baseschemewithnohighlightcolor
```
Reproducible with (probably possible to have a simpler repro):
```
bundle exec rspec --order random:27167 spec/integration/invalid_request_spec.rb spec/integration/spam_rules_spec.rb spec/jobs/bulk_invite_spec.rb spec/jobs/change_display_name_spec.rb spec/jobs/cleanup_imap_sync_log_spec.rb spec/jobs/download_backup_email_spec.rb spec/jobs/fix_primary_emails_for_staged_users_spec.rb spec/jobs/fix_s3_etags_spec.rb spec/jobs/pending_users_reminder_spec.rb …
```
> DEV: correctly delete custom scheme

- app/assets/javascripts/discourse/app/components/plugin-outlet.hbs
- app/assets/javascripts/discourse/app/components/topic-list/topic-link.gjs
- app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs
- app/assets/javascripts/discourse/app/components/topic-list/unread-indicator.gjs
- app/assets/javascripts/discourse/app/components/topic-post-badges.gjs
…and `plugin-outlet` that list items use extensively.
> DEV: Remove extra whitespace from glimmer topic list items

- app/assets/javascripts/select-kit/addon/components/bulk-select-bookmarks-dropdown.js
- app/models/bookmark.rb
- spec/lib/bookmarks_bulk_action_spec.rb
I also changed it so that we clear the selection after performing an action
> FIX: Bulk clear reminders when the reminder is expired

- app/assets/javascripts/discourse/app/components/modal/edit-topic-timer.hbs
- app/assets/javascripts/discourse/app/components/modal/edit-topic-timer.js
- app/assets/javascripts/discourse/app/components/topic-timer-info.js
> DEV: Work around topic-timer data flow issues

- plugins/discourse-narrative-bot/plugin.rb
- plugins/discourse-narrative-bot/spec/discourse_narrative_bot/new_user_narrative_spec.rb
> FIX: Allow triggering Discobot when bookmarking the entire topic

- app/models/about.rb
- spec/models/about_spec.rb
> DEV: Plugin modifier application for About admins

- app/assets/javascripts/discourse/app/components/render-glimmer-container.gjs
- app/assets/javascripts/discourse/tests/integration/helpers/raw-test.gjs
> DEV: Avoid extra whitespace in rawRenderGlimmer

- app/assets/javascripts/discourse/app/adapters/email-template.js
- app/assets/javascripts/discourse/app/adapters/group.js
- app/assets/javascripts/discourse/app/adapters/list-tag.js
- app/assets/javascripts/discourse/app/adapters/notification.js
- app/assets/javascripts/discourse/app/adapters/post-reply-history.js
- app/assets/javascripts/discourse/app/adapters/post-reply.js
- app/assets/javascripts/discourse/app/adapters/post.js
- app/assets/javascripts/discourse/app/adapters/reviewable-settings.js
- app/assets/javascripts/discourse/app/adapters/reviewable-topic.js
- app/assets/javascripts/discourse/app/adapters/tag-info.js
- app/assets/javascripts/discourse/app/adapters/tag-notification.js
- app/assets/javascripts/discourse/app/adapters/tag.js
- app/assets/javascripts/discourse/app/adapters/topic-list.js
- app/assets/javascripts/discourse/app/adapters/topic.js
> DEV: Convert adapters to native class syntax

- app/assets/javascripts/discourse/app/helpers/route-action.js
- app/assets/javascripts/discourse/app/helpers/topic-status-icons.js
> DEV: Convert helpers to native class syntax

- spec/system/login_spec.rb
> DEV: Attempt to fix flaky spec logging in on mobile

- lib/signal_trap_logger_spec.rb
Follow-up to 23c38cbf1189d90384c28654d11ab4a65191ed03
> DEV: Add rspec tests for `SignalTrapLogger`

- spec/support/system_helpers.rb
I suspect it's not useful anymore, if it ever was, and might cause more harm than good.
> DEV: attempts to remove using_session patch

- app/assets/javascripts/discourse/app/lib/url.js
> DEV: Convert DiscourseURL to native class syntax

- app/assets/javascripts/discourse/app/models/user-posts-stream.js
This is the final model in Discourse core to be converted
> DEV: Convert user-posts-stream to native class syntax

- app/assets/javascripts/discourse/app/routes/discourse.js
> DEV: Update action syntax for `routes/discourse.js`

- app/assets/javascripts/discourse/app/routes/application.js
> DEV: Update action syntax for routes/application.js

- app/assets/javascripts/discourse/app/routes/application.js
This reverts commit 0b10e335aedb06cb8a1b09549076175546f55b75.
I realised that some of these actions are overridden in themes/plugins, so this is going to cause problems (especially because modifyClass doesn't currently work well with the `@action` decorator)
> Revert "DEV: Update action syntax for routes/application.js (#27282)"

- lib/email/message_builder.rb
> DEV: Pass recipient email address to message_builder modifiers

- app/assets/javascripts/discourse/app/lib/sidebar/custom-sections.js
- app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
- app/assets/javascripts/float-kit/addon/lib/d-tooltip-instance.js
- app/assets/javascripts/float-kit/addon/services/toasts.js
- docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
- spec/system/admin_dashboard_new_features_spec.rb
- spec/system/navigation_menu_state_integration_spec.rb
> DEV: Fix typos and formatting

- app/assets/javascripts/discourse/app/services/presence.js
This may or may not fix flakes in `Unit | Service | presence` tests
> DEV: Check lifecycle props in Presence service

- spec/rails_helper.rb
On Github Actions, system tests which uses `Capybara#using_session` are
failing intermittently with the error "Socket::ResolutionError: getaddrinfo: Temporary failure in name resolution"
when `Selenium::WebDriver::Platform.localhost` tries to resolve
`localhost`.
Too much time has been spent trying to figure out why so we are giving
up here and just retrying the resolution of `localhost` on Github
Actions.
> DEV: Monkey patch `Selenium::WebDriver::Platform.localhost` to retry

- script/bulk_import/generic_bulk.rb
Add support for properly anonymizing:
- email
- date_of_birth
- location
- website
- bio
> DEV: Improve user generic bulk importer anonymization

- app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
> DEV: Fix incorrect hbs syntax in tests

- yarn.lock
(and do the yarn deduplication dance)
> DEV: Update browserslist

- app/assets/javascripts/discourse/app/controllers/password-reset.js
- spec/system/login_spec.rb
> FIX: password reset with security key

- app/assets/javascripts/admin/addon/components/modal/watched-word-test.js
- app/assets/javascripts/discourse-common/addon/utils/watched-words.js
- app/assets/javascripts/discourse-markdown-it/src/features/emoji.js
- app/assets/javascripts/discourse-markdown-it/src/features/watched-words.js
- app/assets/javascripts/pretty-text/addon/censored-words.js
- lib/pretty_text.rb
Inline the helper functions, avoid creating and then immediately destructuring arrays, use complete strings instead of string interpolation, Map instead of a pojo.
> PERF: Avoid excessive object creation in watched words

- spec/rails_helper.rb
If we don't increment attempts, we will retry forever.
> DEV: Increment attempts for ce91767b90bc6e19b6e8f2a4bb88f07b0ca7355a

- plugins/chat/spec/system/chat_new_message_spec.rb
The order of chat direct message groups can sometimes place usernames in an unexpected order, perhaps due to being alphanumeric (ie. bruce10 before bruce9), so one way to fix the spec is testing all combinations of usernames and accepting them no matter what order they are in.
> DEV: new chat from url flaky test fix

- plugins/chat/assets/javascripts/discourse/services/chat-channel-composer.js
This mirrors `ChatThreadComposer.blur`
> FIX: Check for textarea presence

- app/assets/javascripts/float-kit/addon/services/menu.js
- app/assets/javascripts/float-kit/addon/services/tooltip.js
- plugins/chat/test/javascripts/acceptance/chat-channel-reactions-test.js
> FIX: Don't modify `FloatKitInstance`s arrays unless needed

- plugins/chat/assets/javascripts/discourse/components/chat-message-reaction.gjs
* remove an unused service injection (and sort the rest)
* remove unused prop
* inline an arg check
* remove an unnecessary `?.` operator
* sort element attributes
> DEV: Clean up chat-message-reaction

- app/assets/javascripts/float-kit/addon/services/menu.js
- app/assets/javascripts/float-kit/addon/services/tooltip.js
* use `TrackedSet` instead of `@tracked []`
* correct return type annotations
* move code to outside Promise blocks where possible
* fix an outdated comment
> DEV: Minor refactor of tooltip and menu services

- spec/requests/categories_controller_spec.rb
> DEV: Add test to ensure /categories/search doesn't return secret categories

- app/models/application_request.rb
Adds `28_days` request stats alongside `30_days`, `7_days`.
> FEATURE: Capture 28 day interval request stats

- docs/ADMIN-QUICK-START-GUIDE.md
- Remove image
- Move “if you need to get back here” blurb below main checklist
- Note that each checklist item is a section in the doc
- Add nudge to create a topic in the “Discuss ideas” section
- Move “please join meta” blurb into email configuration section
- Fix a typo and remove some trailing whitespace
> Update getting started guide

- app/assets/javascripts/discourse/app/components/group-card-contents.hbs
- app/assets/javascripts/discourse/app/components/group-card-contents.js
- app/assets/javascripts/discourse/app/components/user-card-contents.hbs
- app/assets/javascripts/discourse/app/components/user-card-contents.js
- app/assets/javascripts/discourse/app/mixins/card-contents-base.js
- app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
> DEV: Minor cleanup of user-card code

- Gemfile.lock
> DEV: Update Gemfile.lock to include darwin-24

- app/assets/javascripts/discourse/app/components/group-card-contents.js
- app/assets/javascripts/discourse/app/components/user-card-contents.js
- app/assets/javascripts/discourse/app/mixins/card-contents-base.js
* remove `boundCardClickHandler`
* remove jQuery usage
* explicitly pass `event` into `_positionCard()`
* move `_positionCard()` calls into the mixin
* inline variables
* remove `!target` check
* merge nested `if`s
* remove unnecessary `return`
* update the `_showCallback` comment
* move computed props below basic props
* `let` -> `const`
> DEV: Further refactor of card-contents-base

- lib/auth/default_current_user_provider.rb
- spec/requests/api/rate_limits_spec.rb
> DEV: Don't enforce per ip rate limits for admin api requests

- spec/support/fake_logger.rb
> DEV: Make parameters optional to all FakeLogger methods

- app/assets/javascripts/discourse-common/addon/lib/popular-themes.js
Replace previews for 'Discourse' based ones
> UX: Add new preview links to Popular Themes

- config/site_settings.yml
- lib/onebox/engine/spotify_onebox.rb
- spec/fixtures/onebox/spotify.response
- spec/lib/onebox/engine/spotify_onebox_spec.rb
Without cookies for a Spotify account
With cookies for a Spotify account
> FEATURE: Support Spotify Onebox

- app/assets/javascripts/discourse/app/components/header/contents.gjs
> DEV: Add plugin outlets before and after the header content

- app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
> DEV: Enable admin notice for the Glimmer header warnings

- app/assets/javascripts/discourse/app/components/edit-topic-timer-form.hbs
- app/assets/javascripts/discourse/app/components/edit-topic-timer-form.js
- app/assets/javascripts/discourse/app/components/relative-time-picker.gjs
- app/assets/javascripts/discourse/tests/acceptance/topic-edit-timer-test.js
> FIX: Correctly update edit-topic-timer interval values

- app/assets/javascripts/discourse/tests/acceptance/about-test.js
- app/assets/javascripts/discourse/tests/acceptance/badges-test.js
- app/assets/javascripts/discourse/tests/acceptance/composer-form-template-test.js
- app/assets/javascripts/discourse/tests/acceptance/encoded-category-test.js
- app/assets/javascripts/discourse/tests/acceptance/invite-accept-test.js
- app/assets/javascripts/discourse/tests/acceptance/preferences-test.js
- app/assets/javascripts/discourse/tests/acceptance/search-full-test.js
- app/assets/javascripts/discourse/tests/integration/components/float-kit/d-tooltip-test.js
- plugins/chat/test/javascripts/components/chat-emoji-picker-test.js
- plugins/poll/test/javascripts/acceptance/poll-pie-chart-test.js
(and fix ~~one~~ two test bugs)
> DEV: Convert some tests to qunit-dom

- plugins/chat/assets/javascripts/discourse/components/chat-footer.gjs
- plugins/chat/assets/stylesheets/common/chat-footer.scss
- plugins/chat/assets/stylesheets/mobile/chat-footer.scss
Revert the application of the new nav underline for the chat footer
> UX: revert chat footer changes partially

- app/assets/javascripts/discourse/app/components/topic-list/topic-list-header-column.gjs
- spec/fabricators/topic_fabricator.rb
- spec/system/topic_list/glimmer_spec.rb
> FIX: Display new-new selector on glimmer topic list

- spec/fabricators/topic_fabricator.rb
- spec/requests/list_controller_spec.rb
- spec/system/new_topic_list_spec.rb
- spec/system/topic_list/glimmer_spec.rb
```rb
Fabricate(:new_reply_topic, count: 1, current_user:)
```
and
```rb
Fabricate(:read_topic, current_user:)
```
> DEV: Add/use two topic fabricators

- app/jobs/scheduled/aggregate_web_hooks_events.rb
- app/jobs/scheduled/purge_old_web_hook_events_daily_aggregate.rb
- app/models/web_hook.rb
- app/models/web_hook_events_daily_aggregate.rb
- config/locales/server.en.yml
- config/site_settings.yml
- db/migrate/20240619123052_create_web_hook_events_daily_aggregates.rb
- spec/models/web_hook_events_daily_aggregate_spec.rb
Add WebHookEventsDailyAggregate model to store daily aggregates of web hook events. 
Add AggregateWebHooksEvents job to aggregate web hook events daily. 
Add spec for WebHookEventsDailyAggregate model.
-  https://github.com/discourse/discourse/pull/27573
> FEATURE: Add WebHookEventsDailyAggregate

- app/assets/javascripts/discourse/app/components/parent-category-row.hbs
- app/assets/javascripts/discourse/app/models/category.js
> DEV: Indicate whether categories are missing on categories page

- app/assets/javascripts/discourse/app/components/topic-list-item.js
- app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs
- app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
- spec/fabricators/topic_fabricator.rb
- spec/system/page_objects/components/topic_list.rb
- spec/system/topic_list/glimmer_spec.rb
> FIX: Correctly highlight new topic-list-items in glimmer

- app/assets/javascripts/discourse/tests/integration/components/plugin-outlet-test.gjs
qunit-dom, reformat hbs blocks, use `<template>` where possible
> DEV: Update plugin-outlet tests

- app/assets/javascripts/discourse/app/instance-initializers/register-media-optimization-upload-processor.js
- app/controllers/admin/emojis_controller.rb
- app/jobs/regular/sync_acls_for_uploads.rb
- config/locales/server.en.yml
- lib/backup_restore/s3_backup_store.rb
- lib/tasks/uploads.rake
- plugins/chat/app/controllers/chat/api/direct_messages_controller.rb
- plugins/chat/assets/javascripts/discourse/services/chat.js
- plugins/chat/config/routes.rb
- spec/system/bookmarks_spec.rb
- spec/system/composer_uploads_spec.rb
- spec/system/page_objects/pages/admin_site_settings.rb
I am changing many of these to notes or resolving them as is,
most of these I have not actively worked on in years so someone
else can work on them when we get to these areas again.
> DEV: Resolve TODO comments for martin-brennan

- app/controllers/admin/themes_controller.rb
- app/controllers/admin/web_hooks_controller.rb
- app/controllers/topics_controller.rb
- app/controllers/users_controller.rb
- app/jobs/regular/export_user_archive.rb
- app/serializers/admin_web_hook_serializer.rb
- app/serializers/site_serializer.rb
- app/serializers/theme_serializer.rb
- app/serializers/topic_view_bookmark_serializer.rb
- app/serializers/topic_view_serializer.rb
- app/serializers/web_hook_event_type_serializer.rb
- app/views/exceptions/not_found.html.erb
- lib/freedom_patches/active_record_disable_serialization.rb
- plugins/chat/spec/plugin_helper.rb
- spec/lib/topic_query_spec.rb
- spec/requests/admin/themes_controller_spec.rb
- spec/requests/api/notifications_spec.rb
- spec/requests/api/posts_spec.rb
- spec/serializers/site_serializer_spec.rb
> DEV: Block accidental serialization of entire AR models

- app/models/theme.rb
- spec/lib/stylesheet/manager_spec.rb
Backporting changes from PR #27626 to stable branch.
> PERF: eager load field changes

- Gemfile.lock
> DEV: Bump rails_failover 2.1.1

- app/assets/javascripts/discourse/app/components/modal/create-account.js
> DEV: Remove jquery from create-account modal

- lib/git_utils.rb
`String#present?` is a method defined by Rails on the `String` class but
this class is used before Rails has been loaded.
> DEV: Fix unicorn not booting due to 8e10878

- spec/system/private_message_map_spec.rb
- spec/system/topic_map_spec.rb
Followup 527f02e99fee782f53e206f739fb4f12d63b6d2a,
don't have time to investigate now, will look next week
> DEV: Comment flaky specs

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/initializers/101-lograge.rb
- config/unicorn.conf.rb
- lib/discourse.rb
- lib/discourse_logstash_logger.rb
- lib/version.rb
This reverts commit 8e10878e1a37a608b0e1705bf9d0a06a295b8a63.
Something is broken on a friday so reverting first before I pick this up
again next Monday.
> Revert "DEV: Redo `DiscourseLogstashLogger` to not rely on `logstash-logger` (#27663)"

- plugins/chat/spec/system/message_thread_indicator_spec.rb
> DEV: skip flaky system chat spec

- app/assets/javascripts/discourse/app/components/sidebar/api-section.gjs
- app/assets/javascripts/discourse/app/components/sidebar/api-sections.gjs
- app/assets/javascripts/discourse/app/components/sidebar/back-to-forum.gjs
- app/assets/javascripts/discourse/app/components/sidebar/filter-no-results.gjs
- app/assets/javascripts/discourse/app/components/sidebar/footer.gjs
- app/assets/javascripts/discourse/app/components/sidebar/panel-header.gjs
- app/assets/javascripts/discourse/app/components/sidebar/section-header.gjs
- app/assets/javascripts/discourse/app/components/sidebar/section.gjs
- app/assets/javascripts/discourse/app/components/sidebar/toggle-all-sections.gjs
- app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
- app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-panel.js
- app/assets/javascripts/discourse/app/lib/sidebar/helpers.js
- app/assets/javascripts/discourse/app/services/sidebar-state.js
- app/assets/stylesheets/common/base/menu-panel.scss
- app/assets/stylesheets/common/base/sidebar.scss
- config/locales/client.en.yml
- spec/system/admin_sidebar_navigation_spec.rb
- spec/system/page_objects/components/navigation_menu/sidebar.rb
- spec/system/viewing_sidebar_spec.rb
This PR untangles the admin sidebar from the sidebar code in core.
It's still a draft, so I didn't add tests for now. 
Most of the changes should be covered by existing tests, and since I needed to change the APi slightly I wanted a pre-review first, before writing the tests that are needed.
> DEV: Untangle the admin sidebar from the sidebar code

- app/assets/javascripts/admin/addon/routes/admin-backups-index.js
- app/assets/javascripts/admin/addon/routes/admin-backups.js
- app/assets/javascripts/admin/addon/routes/admin-customize-themes-show-schema.js
- app/assets/javascripts/admin/addon/routes/admin-emojis.js
- app/assets/javascripts/admin/addon/routes/admin-plugins-show-settings.js
- app/assets/javascripts/admin/addon/routes/admin-plugins-show.js
- app/assets/javascripts/admin/addon/routes/admin-plugins.js
- app/assets/javascripts/admin/addon/routes/admin-search-logs-index.js
- app/assets/javascripts/admin/addon/routes/admin-search-logs-term.js
- app/assets/javascripts/admin/addon/routes/admin-site-text-edit.js
> DEV: Use `async/await` in admin route `model` fns

- plugins/poll/test/javascripts/component/poll-results-pie-test.js
Example of flakiness: https://github.com/discourse/discourse/actions/runs/9831645793/job/27139325323
> DEV: Skip flaky polls acceptance test
