discourse/discourse

plugins/chat/assets/stylesheets/common/chat-navbar.scss
plugins/chat/assets/stylesheets/common/chat-side-panel.scss

Fixes alignment issues within the drawer mode and chat sidebar panel on desktop.
Before:
After:
Before:
After:

UX: fix chat title margin on drawer and side panel

---

app/assets/javascripts/discourse/app/components/emoji-picker.js
app/assets/javascripts/discourse/tests/acceptance/emoji-test.js

Should open the emoji picker. But it wasn't 😅
The `handleOutsideClick` event was listening too early and would catch the click on the "more..." option in the autocomplete as a click outside the emoji picker and would immediately close it 🤦
The fix was to defer registering to this event.

FIX: clicking "more..." in emoji autocomplete

---

app/assets/javascripts/discourse/app/components/powered-by-discourse.gjs
app/assets/javascripts/discourse/app/controllers/application.js
app/assets/javascripts/discourse/app/templates/application.hbs
app/assets/stylesheets/common/components/_index.scss
app/assets/stylesheets/common/components/powered-by-discourse.scss
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
spec/system/powered_by_discourse_spec.rb

This adds a new site setting `enable_powered_by_discourse`, default false. 
When enabled, this will show a "Powered by Discourse" link to discourse.org at the bottom of most pages (admin, invites, full-page chat, login-required, and no-ember pages being the exceptions).
https://github.com/discourse/discourse/assets/1681963/9e771b44-bacf-446d-939f-5887143a693a

FEATURE: optionally show "Powered by Discourse" link to discourse.org

---

lib/search/grouped_search_results.rb

Since we are introducing new ways to search in Discourse, like the AI semantic search using embeddings, posts can be part of a search result list without having any search data.
Since the code path already handles this, we only need to add a safety check when accessing the post_search_data.

FIX: Handle nil post_search_data for search result

---

app/assets/javascripts/discourse-markdown-it/src/features/bbcode-block.js
app/assets/javascripts/discourse/tests/unit/lib/pretty-text-test.js

> [code]
> line1
> line2
> [/code]
would render as
| line1
| > line2
instead of the correct
| line1
| line2
That was due to the `bbcode-block` code using a `slice` to get the content of a block and not taking into account it being nested in a quote block for example.
The fix was to get the content using the `getLines` utils method.
Context: https://meta.discourse.org/t/markdown-bbcode-code-quote-bug/299047

FIX: support [code] in blockquotes

---

lib/content_security_policy/builder.rb
spec/lib/content_security_policy/builder_spec.rb
spec/lib/content_security_policy_spec.rb
spec/requests/application_controller_spec.rb

FIX: correctly strip unneeded csp directives under strict-dynamic

---

app/assets/javascripts/discourse/app/lib/download-calendar.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/unit/lib/download-calendar-test.js

This will now be used for google calendars to pre-fill the associated fields in: https://calendar.google.com/calendar/u/0/r/eventedit
Used in: https://github.com/discourse/discourse-calendar/pull/549

DEV: adds details/location options to downloadCalendar

---

app/models/api_key_scope.rb
config/locales/client.en.yml
spec/requests/admin/api_controller_spec.rb

This commit adds API scopes for reading, modifying, and deleting post
revisions.

DEV: Add API scopes for post revisions

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/field.gjs
app/assets/javascripts/discourse/tests/fixtures/theme-setting-schema-data.js
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/schema_field.scss
app/serializers/theme_settings_serializer.rb
spec/fixtures/theme_locales/objects_settings/en.yaml
spec/fixtures/theme_settings/objects_settings.yaml
spec/serializers/theme_settings_serializer_spec.rb
spec/system/admin_editing_objects_typed_theme_setting_spec.rb
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

When editing a objects typed theme setting, the input fields which are
rendered should include a description so that the user knows the purpose
of the field which they are changing.
This change adds support for adding description to each property in the
schema for an object by following a given convention in the locale file.
For a schema like this:
```
objects_setting:
type: objects
schema:
name: section
properties:
name:
type: string
required: true
links:
type: objects
schema:
name: link
properties:
name:
type: string
required: true
validations:
max_length: 20
url:
type: string
```
Description for each property in the object can be added like so:
```
en:
theme_metadata:
settings:
objects_setting:
description: <description> for the setting
schema:
properties:
name: <description for the …
```

DEV: Support description for properties in objects schema

---

app/models/user_api_key_scope.rb
spec/requests/notifications_controller_spec.rb

The `/notifications/totals` route is a stripped down version of `notifications#index`. This just allows the mobile app to use this new route.
Followup to https://github.com/discourse/discourse/pull/26106

DEV: Allow user api key scope for notifications#totals

---

app/services/problem_check/missing_mailgun_api_key.rb
spec/services/problem_check/missing_mailgun_api_key_spec.rb

This check was never used before. As part of the `ProblemCheck` migration this is now in use, which revealed a bug caused by an incorrect assumption about the shape of `ActionMailer::Base.smtp_settings`. This PR fixes that bug.

FIX: Amend broken Mailgun API key check

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/templates/customize-themes-show-schema.hbs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/customize_themes_show_schema.scss
app/assets/stylesheets/common/admin/schema_theme_setting_editor.scss
config/locales/client.en.yml
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

This is a first pass at styling the editor for creating/editing/updating
an objects typed theme setting. Only the desktop view is being
considered at the current moment.
The objects typed theme setting is still behind a feature flag at this moment so there is no need for us to get the styling perfect. The purpose of this PR is to get us to a state which we can quickly iterate with a designer on.

UX: First pass styling experimental objects typed setting editor

---

app/controllers/application_controller.rb
config/discourse_defaults.conf
config/site_settings.yml
spec/requests/application_controller_spec.rb

In https://web.dev/articles/preconnect-and-dns-prefetch, it describes
how hinting to the browser to preconnect to domains which we will
eventually use the connection for can help improve the time it takes to
load a page.
We are putting this behind an experimental flag so that we can test and
profile this in a production environment.
Introduce a hidden experimental `experimental_preconnect_link_header`
site setting which when enabled will add the `preconnect` and
`dns-prefetch` resource hints to the response headers for full page load
requests.

EXPERIMENTAL: preconnect and dns-prefetch resource hints for CDN domains

---

app/controllers/application_controller.rb
spec/requests/application_controller_spec.rb

Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link, the
syntax for multiple links is something like
```
Link: <https://one.example.com>; rel="preconnect", <https://two.example.com>; rel="preconnect", <https://three.example.com>; rel="preconnect"
```
There should be no trailing `;` before the `,`.

DEV: Fix syntax for Link entity header for `experimental_preconnect_link_header`

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

According to https://web.dev/articles/preload-critical-assets,
> By preloading a certain resource, you are telling the browser that you would like to fetch it sooner than the browser would otherwise discover it because you are certain that it is important for the current page.
The preload resource hint is meant to tell the browser to fetch
resources that it would not discover upfront or early. However, we are
not using it the right way because we are literally adding the resource
hint right before a `<script>` tag which means the browser would have
discovered the resource even without the resource hint.
This commit removes the preload resource hint which are added right
before script tags since the optimization here is highly questionable at the expense of making 
our initial DOM larger.

PERF: Remove unnecessary `<link rel="preload">`

---

app/assets/javascripts/discourse/app/models/user.js

Adds `@tracked` to the relevant property on the User model so that it is autotracked correctly via the function call `glimmer-header/user-dropdown/notifications#isInDoNotDisturb` -> `models/user#isInDoNotDisturb`.

FIX: Ensure dnd icon is updated immediately in glimmer header

---

app/models/private_message_topic_tracking_state.rb
app/models/user_action.rb
spec/lib/post_creator_spec.rb
spec/models/private_message_topic_tracking_state_spec.rb
spec/models/user_action_spec.rb

We never use that information and this also fixes an issue with the BCC plugin which ends up triggering a rate-limit because we were publishing a "NEW_PRIVATE_MESSAGE" to the user sending the BCC for every recipients 💥
Internal - t/118283

PERF: avoid publishing user actions to the user who did the action

---

plugins/chat/assets/stylesheets/common/chat-message-info.scss

UX: chat > fix lock icon in original message link

---

app/models/theme.rb
app/models/theme_field.rb

This is a follow up to e2da72b76c7f49c2c3a159ce48051c4050f3dc3e.
According to https://web.dev/articles/preload-critical-assets,
> By preloading a certain resource, you are telling the browser that you would like to fetch it sooner than the browser would otherwise discover it because you are certain that it is important for the current page.
The preload resource hint is meant to tell the browser to fetch
resources that it would not discover upfront or early. However, we are
not using it the right way because we are literally adding the resource
hint right before a `<script>` tag which means the browser would have
discovered the resource even without the resource hint.
What does this change do?
This commit removes the preload resource hint which are added right
before …

PERF: Remove unnecessary <link rel="preload"> for theme javascript

---

app/assets/javascripts/discourse/tests/integration/components/select-kit/mini-tag-chooser-test.js
app/assets/javascripts/select-kit/addon/components/mini-tag-chooser.js
app/assets/javascripts/select-kit/addon/components/select-kit.js
lib/version.rb

Currently when `max_tags_per_topic` is zero, it fails silently. 
This change highlights the limit below the tag picker, and also prevents search when max is 0. It continues to allow users to remove existing tags if the max is changed to 0.
I considered removing the tag picker when the value is 0 and there are no existing tags, but it becomes non-obvious to the user why the tag picker is gone. So showing the red 'error' provides a better clue. Language-wise it sounds a bit funny, but after thinking a bit, I think it works alright.
Related: https://meta.discourse.org/t/max-tags-per-topic-failing-silently/142241
Some screenshots

FIX: Show max tag error and prevent search

---

spec/rails_helper.rb

Google does not yet publish binaries for chrome and chromedriver for
`linux/arm64`. In 484954ec4c5c585c16fb6e7c2a8d45bac49d6964, we attempted
to add support for running system tests on `linux/arm64` by switching to
Firefox but our system tests seem to make lots of assumptions about
running on chromium based browsers so there are some tests that don't work in Firefox.
This commit works around the lack of chrome and chromedriver binaries by
doing the following:
1. Adds a `DISCOURSE_SYSTEM_TEST_CHROMIUM` ENV variable which when set to
`1` will allow us to run system tests using a chromium binary. Chromium
binaries for `linux/arm64` are available and since Chrome is Chromium based, all of our 
system tests "should pass" even when running against a Chromium binary. I don't expect 
this to be …

DEV: Support running system tests using chromium and custom chromedriver

---

app/assets/javascripts/discourse/app/components/scrolling-post-stream.js

Related: https://github.com/discourse/discourse/pull/25034
We were noticing a similar layout shift on mobile when ?page=N. It turns out there is an additional 100px worth of elements added after loading which didn't seem to be the case on desktop, so the `top` needs to be recalculated each time we attempt to scroll.
Before:
https://github.com/discourse/discourse/assets/1555215/f89aa082-d7f3-4726-b99d-a58d5f0a03b9
After:
https://github.com/discourse/discourse/assets/1555215/8d13fd15-a932-4982-9456-5fb5c72c862b
(Github seems to be weirding out on video attachments, they used to work)
t/278973

FIX: Prevent content layout shift on mobile when ?page=N

---

app/assets/javascripts/discourse/app/components/post-text-selection.gjs

This commit now ensures we will properly attempt to refresh the toolbar position after a scroll and consider it as a selection change.
Tangential to this fix we improved the positioning on mobile to better account for the native menu position and avoid a situation where the toolbar is always behind the native menu and can't be used.
No test because mobile + scroll is very hard to test reliably.

FIX: refreshes post toolbar on topic scroll

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/javascripts/discourse/tests/acceptance/mobile-pan-test.js

FIX: Regressed scroll-lock after mobile menu close

---

app/assets/javascripts/select-kit/addon/components/multi-select.hbs
app/assets/javascripts/select-kit/addon/components/single-select.hbs

Prior to this fix, if you were following this series of events:
- type something in a select-kit filter with async search
- query starts
- type something again
- first query finished with no results
- second query starts
- :boom: we would show a no content found for a split second
- second query finishes
- we display a list of results

FIX: wait for the end of search requests

---

app/controllers/categories_controller.rb
spec/requests/categories_controller_spec.rb

Follow up to commit a90b88af5618b99496ab14d8c6264785484e1f84.

PERF: Fix N+1 when loading categories with custom fields

---

app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js

Previously we were only running the `condition` function once, and then overwriting it with a static boolean value. Future changes to composer attributes would not affect button visibility.
This commit fixes the issue and adds an acceptance test for the behavior.

FIX: Ensure custom composer button 'condition' is run correctly

---

app/assets/javascripts/discourse/app/components/glimmer-header/dropdown.gjs
app/assets/javascripts/discourse/app/components/glimmer-header/user-dropdown.gjs
app/assets/javascripts/discourse/app/widgets/header.js

Those apply only to `a` elements

DEV: Remove href/auto-route attrs from buttons

---

app/assets/javascripts/admin/addon/routes/admin-revamp.js
app/assets/javascripts/admin/addon/routes/admin.js
app/assets/javascripts/admin/addon/services/admin-sidebar-state-manager.js
plugins/chat/assets/javascripts/discourse/services/chat-state-manager.js
plugins/chat/spec/system/admin_sidebar_navigation_spec.rb

This commit fixes an issue where the following happens:
1. You open /admin as a member of the admin_sidebar_enabled_groups
1. You then click the chat icon in the header when you prefer to have
drawer open, or if you just minimise chat into drawer after it opens
fullscreen
1. You lose the admin sidebar panel, and are reset instead to the main
panel
Also included is a bit of refactoring to make it so the forcing of
admin sidebar state is in one place.

FIX: Do not lose admin sidebar when opening chat drawer

---

plugins/discourse-local-dates/assets/javascripts/lib/discourse-markdown/discourse-local-dates.js
plugins/discourse-local-dates/spec/integration/local_dates_spec.rb

In this PR we introduced 3 new timezones to UX - IST, KST and JST
https://github.com/discourse/discourse/pull/20114
However, the same has to be done in PrettyText so cooked posts respect those timezones.

FIX: missing IST KST and JST timezones in cooked posts

---

app/models/admin_dashboard_data.rb
app/models/problem_check.rb
app/services/problem_check/sidekiq_check.rb
spec/models/admin_dashboard_data_spec.rb
spec/services/problem_check/sidekiq_check_spec.rb

In #26122 we promoted all problem checks defined as class methods on `AdminDashboardData` to their own first-class `ProblemCheck` instances.
This PR continues that by promoting problem checks that are implemented as blocks as well. This includes updating a couple plugins that have problem checks. (See below.)
**Do not merge until these plugins have had their problem checks promoted.**

DEV: Promote block problem checks to ProblemCheck

---

lib/pretty_text.rb
spec/lib/pretty_text_spec.rb

```
<a class="mention" href="/u/test1">bsam</a>
```
Is not a mention of the user sam. We expect an @ in front always.

FIX: remove "fake" mentions from extract_mentions

---

plugins/chat/config/locales/client.en.yml

When adding the new "illegal" flag option, we missed adding the translation to the chat plugin, so when flagging a chat message (rather than a post) you'd see `[en.chat.flags.illegal]`. This PR fixes that.

FIX: Add missing chat message illegal flag text

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
app/assets/stylesheets/common/admin/schema_theme_setting_editor.scss

Continue from https://github.com/discourse/discourse/pull/25673.
This feature adds new buttons for schema theme settings that add/remove objects from lists. Screenshot:

FEATURE: Buttons to add and remove objects for schema theme settings

---

plugins/chat/plugin.rb
plugins/chat/spec/plugin_spec.rb

When the current user disables chat from within user preferences, the chat button still appears when clicking another user’s profile picture to open the user card. This is also the case when the current user has chat enabled but the target user has disabled chat.
- when a user disables chat in preferences, the chat button should not be displayed when opening a user card or visiting profiles of other users.
- when chat is enabled in preferences but another user disables chat, the chat button should not appear on their user card or profile
/t/124129

FIX: hide chat btn from user card when chat disabled

---

app/models/concerns/has_custom_fields.rb
plugins/chat/app/services/chat/list_channel_messages.rb
plugins/chat/spec/services/chat/list_channel_messages_spec.rb
spec/lib/concern/has_custom_fields_spec.rb

We were incorrectly using `return` in a block which was causing exceptions at runtime. These exceptions were not causing much issues as they are in defer block.
While working on writing a test for this specific case, I noticed that our `upsert_custom_fields` function was using rails `update_all` which is not updating the `updated_at` timestamp. This commit also fixes it and adds a test for it.

FIX: do not use return in block

---

lib/discourse_connect_base.rb

For some identity providers, 10 minutes isn't much time for a user to complete authentication/registration on the identity provider. Increasing the default to 30 minutes should help in those situations. The nonce is still tied to a single browser session, so there is no material impact on security.

FEATURE: Increase default DiscourseConnect session length

---

app/assets/stylesheets/common/font-variables.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/mobile/discourse.scss

Previously we had an iOS-specific sizing rule which would increase inputs to `1.07em`, which would bring them over the 16px 'zoom on focus' threshold in some (but technically, not all) situations.
This commit does two things:
1. Updates the sizing rule from `1.07em` to `max(1em, 16px)`. Essentially: use the cascaded font size, unless it is smaller than 16px
2. Applies that sizing rule on all platforms. This will make Discourse design/theming more consistent across different devices

UX: Make input sizing consistent across all browsers

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/templates/customize-themes-show-schema.hbs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
app/assets/stylesheets/common/admin/customize_themes_show_schema.scss
app/assets/stylesheets/common/admin/schema_field.scss
app/assets/stylesheets/common/admin/schema_theme_setting_editor.scss
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

Some initial style adjustments to make this fit the full page layout. 
This also changes the list markup a little, which is why a bunch of tests needed some adjustment. Having nested `ul` within `li`, rather than making everything a sibling `li` can help distinguish that these are sublists. 
Before:
After:

UX: adjust objects editor styles for full page layout

---

spec/requests/categories_controller_spec.rb

The test registers a category custom field to preload but doesn't remove
it at the end of the test causing a state leak which can result in other
tests failing.

DEV: Fix state leak in test causing flaky tests

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

If an object doesn't have any child objects for a particular property
and we try to add one through the editor, an error will be raised.
```
Cannot read properties of undefined (reading 'push')
at SchemaThemeSettingEditor.addItem (editor.js:190:1)
```

FIX: Error encountered when adding child object in object setting editor

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/field-input-description.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/field.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/boolean.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/category.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/enum.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/float.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/group.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/integer.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/string.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/tag.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
app/assets/stylesheets/common/admin/schema_field.scss
config/locales/client.en.yml
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

In our schema, we support the `min_length` and `max_length` validation
rules like so:
```
some_objects_setting
type: objects
schema:
name: some_object
properties:
title:
type: string
validations:
min_length: 1
max_length: 10
```
While the validations used to validate the objects on the server side,
we should also add client side validation for better UX.

DEV: Add validation message to string fields in theme object editor

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/integer.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
config/locales/client.en.yml

This is a continuation of 8de869630fa51b4b2453a11cce316fc2da229a45.
In our schema, we support the `min` and `max` validation
rules like so:
```
some_objects_setting
type: objects
schema:
name: some_object
properties:
id:
type: integer
validations:
min: 5
max: 10
```
While the validations used to validate the objects on the server side,
we should also add client side validation for better UX.

DEV: Add validation message to integer fields in theme object editor

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/number-field.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/float.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/integer.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

This is a continuation of a30d73f255879f3e4cc0edbb9de358c03f3aed94
In our schema, we support the `min` and `max` validation
rules like so:
```
some_objects_setting
type: objects
schema:
name: some_object
properties:
id:
type: float
validations:
min: 5.5
max: 10.5
```
While the validations used to validate the objects on the server side,
we should also add client side validation for better UX.
Since the integer and float input fields share very very similar logic
in the component. This commit pulls the common logic into
`admin/components/schema-theme-setting/number-field.gjs` which
`admin/components/schema-theme-setting/types/integer.gjs` and `admin/components/schema-theme-setting/types/float.gjs`
will inherit from.

DEV: Add validation message to float fields in theme object editor

---

app/models/sitemap.rb

We were using `OFFSET`/`LIMIT` to query topics without an 'ORDER'. Without an explicit order, postgres makes no guarantees about which rows will be returned for each query. This commit adds `ORDER BY id ASC` so that our sitemaps behave consistently.

FIX: Ensure sitemaps include all topics with no duplicates

---

app/models/theme.rb
spec/models/theme_spec.rb

This PR exposes a normalized repository URL and how many users are using a given theme.

DEV: Expose extra data from themes

---

app/models/topic_list.rb
lib/topic_view.rb

When categories are loaded by the frontend, the parent category is looked up by ID and the `parentCategory` is set with the result. If the categories returned are not in order, the parent category may miss.

FIX: Serialize parent categories first

---

app/assets/javascripts/discourse/app/controllers/exception.js
app/assets/javascripts/discourse/app/lib/url.js
app/assets/javascripts/discourse/app/mixins/card-contents-base.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/user.js
config/locales/client.en.yml
spec/system/user_page/hide_from_public_spec.rb

Previously, we had an instant redirect back to the homepage, and clicking avatars would do nothing. This made things feel 'broken' for anon when 'hide_user_profiles_from_public' was enabled.
This commit does a few things to resolve this:
1. Improve our 'exception' system for routes so that developers can deliberately trigger it without an ajax error
2. Improve 'exception' system so that the browser URL bar is updated correctly, and the 'back' button works as expected
3. Replace the redirect-to-home with an 'access denied' error page, with specific copy for 'You must log in to view user profiles'
4. Update user-card logic to display this new page instead of doing nothing on click

DEV: Improve UX when user profiles are hidden from public

---

app/assets/stylesheets/common/font-variables.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/mobile/discourse.scss

This reverts commit d0d4a363d4801a274caad50ffa509fc64740f238. This causes issues for people that have specified explicit font sizes in their browser - reverting while we investigate. https://meta.discourse.org/t/300374

Revert "UX: Make input sizing consistent across all browsers (#26159)"

---

app/assets/stylesheets/common/base/activation.scss

The sidebar is already hidden here, but the toggle isn't. This hides it.
Eventually we'll probably have a service that can handle this so it's not only CSS. 
Before:
After:

UX: hide sidebar toggle on account created route

---

app/models/category_list.rb
spec/models/category_list_spec.rb

When "lazy load categories" is enabled and parent_category_id was set, the query fetching categories contained a contradiction filtering both by parent_category_id and parent_category_id = NULL.

FIX: Load subcategories through CategoryList

---

app/assets/stylesheets/common/components/powered-by-discourse.scss

"Powered by Discourse" looks out of place here:

UX: hide "powered by" from account activation page

---

app/assets/javascripts/discourse/app/templates/user.hbs
app/assets/stylesheets/common/base/discourse.scss

We have two skip links on this page, one to skip the site nav, and another to skip the profile nav. They should not use the same ID, which is against HTML spec 
https://meta.discourse.org/t/300012

FIX: two skip links should not have the same ID

---

lib/guardian.rb
lib/guardian/post_guardian.rb
spec/lib/guardian/post_guardian_spec.rb
spec/lib/guardian_spec.rb

Followup 3094f32ff5c7dec5be7ff4f01e6a855987f8d778,
this fixes an issue with the logic in this commit where
we were returning false if any of the conditionals here
were false, regardless of the type of `obj`, where we should
have only done this if `obj` was a `PostAction`, which lead
us to return false in cases where we were checking if the
user could edit their own post as anon.

FIX: Anon users could not edit their own posts

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/group.gjs
app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

Prior to this change, the group selector was using the `<GroupChooser>`
component which is a `<MultiSelectComponent>` and is not ideal in our
situation when we only allow a single group to be selected.
The other problem is that we are doing an async load of the groups when
it is already loaded and available in the `Site` service.

UX: Improve group selector in theme objects editor

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js

We are still making improvements to the admin sidebar and
various parts of the admin section. For now, to make the
transition easier, we are moving this link to the top of the
sidebar so it's clear that admins can still get to all settings
if they need to.

UX: Move "All Site Settings" link to top of admin sidebar

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/category.gjs
app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

Prior to this change, the category selector was not clearable and did
not allow a none value. This is incorrect as the category selector
should be clearable and should allow a none value when the property is
not required.

UX: Improve category selector in theme objects editor

---

app/assets/javascripts/discourse/app/components/d-button.gjs
app/assets/javascripts/discourse/app/components/glimmer-header/dropdown.gjs
app/assets/javascripts/discourse/app/widgets/header.js
plugins/chat/assets/javascripts/discourse/components/chat/header/icon.gjs

- Converts all header buttons to use `<DButton`
- Updates `<DButton` to render `<a href=` tags when `@href` is passed (previously it was rendering a `<button`, and then using JS to route when clicked)

UX: Ensure all header buttons are consistently sized

---

app/assets/javascripts/discourse/app/components/topic-map.gjs
app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs

The topic map expansion button correctly has `aria-controls` but there's no corresponding ID. 
This updates the ID to correspond with its purpose. I considered duplicating the class name as the ID and adding a comment... but I think this naming convention achieves a similar goal.

A11Y: topic map aria-controls needs an ID 

---

app/assets/javascripts/discourse-markdown-it/src/features/image-controls.js
config/locales/client.en.yml

This adds a title attribute to provide some more detail while hovering these controls:
Suggested in https://meta.discourse.org/t/100-75-50-next-to-images-in-preview-window/299883

UX: add title attribute to composer preview image controls

---

app/assets/javascripts/discourse/app/widgets/post.js

This isn't navigating somewhere else, but shows/hides content, so `role="button"` would be appropriate here. The mobile behavior functions as an anchor link rather than expanding content, so that will remain unchanged.

A11Y: Add button role to the reply-to-tab anchor on desktop

---

app/assets/stylesheets/common/base/not-found.scss
app/views/exceptions/not_found.html.erb

* Associates the input label with the input using `for`
* Drops `H2`, which can't shouldn't be within a label tag
* Removes the `p` which was used for spacing rather than any semantic meaning

A11Y: improve markup of 404 page search form

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/javascripts/discourse/app/components/modal/bookmark.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/login.hbs
app/assets/javascripts/discourse/app/components/modal/login/footer.hbs
app/assets/javascripts/discourse/app/instance-initializers/mobile-keyboard.js
app/assets/javascripts/discourse/app/lib/body-scroll-lock.js
app/assets/javascripts/discourse/app/modifiers/swipe.js
app/assets/javascripts/discourse/app/services/modal.js
app/assets/javascripts/discourse/tests/integration/components/d-modal-test.gjs
app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/components/bookmark-modal.scss
app/assets/stylesheets/mobile/login-modal.scss
app/assets/stylesheets/mobile/modal-overrides.scss
app/assets/stylesheets/mobile/modal.scss
spec/system/page_objects/components/navigation_menu/base.rb

This commit mainly improves two things:
- slide up/down animation of the modals on mobile, also allowing swipe down to close the modal
- a new `<:headerPrimaryAction>` block for `d-modal` which when present will move the cancel button to the left of the modal title, and this primary action to the right of the title
Note this commit also took this opportunity to convert `d-modal` to gjs.
A modal with the new header primary action:
A modal with without primary action:
A video of the animation:
[Kapture 2024-03-20 at 18.38.12.webm](https://github.com/discourse/discourse/assets/339945/b2496eba-6cc2-4f98-8672-20676088bc7b)

UX: improves modal on mobile

---

app/jobs/regular/notify_reviewable.rb

This job may notify hundreds of mods and take quite a while to run.

PERF: only allow one reviewable notification at a time

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/stylesheets/common/base/modal.scss
plugins/chat/spec/system/page_objects/chat/chat_channel.rb
spec/system/page_objects/components/navigation_menu/base.rb

The fading should now be function of the swipe position. We should also correctly instantly remove the fading when closing the modal.
[Kapture 2024-03-22 at 19.23.23.webm](https://github.com/discourse/discourse/assets/339945/e1a52522-a8f8-4ad0-bde1-e09ad019a51b)

UI: better modal backdrop opacity fading

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/tags.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
config/locales/client.en.yml

When a property of `type: tags` is required, we should be displaying the
"at least 1 tag is required" validation error message when there are no
tags selected in the `TagChooser` compoment. However, we were passing
`this.min` as the `count` attribute when generating the translation
string which is incorrect as `this.min` is not always set.

FIX: Broken translation in tags input field objects setting editor

---

app/assets/stylesheets/common/components/hashtag.scss
app/assets/stylesheets/common/foundation/mixins.scss

Works around a webkit bug (?) and makes more sense for elements that are mostly text and displayed _inline_ with text content.
Before / After
The recent webkit bug/behavior of unstable inline-block layout:
Tested on Chromium and in macOS Safari, with 3 different text sizes in the Interface settings

UX: Convert `mention` style to inline

---

lib/tasks/assets.rake

We were previously using the `EMBER_ENV=production` environment variable, which appears to produce the same output. But, some parts of ember-cli don't seem to support it, which leads to a confusing 'Environment: development' being printed on the console.
This commit adds `-prod` by default, which is the more common way to invoke ember-cli for production builds.

DEV: Use `-prod` flag when building production assets

---

.github/workflows/tests.yml
app/assets/javascripts/discourse/testem.js

This PR switches to using Chromium in our CI jobs instead of Chrome.

DEV: Switch to Chromium in CI

---

lib/discourse_ip_info.rb

Per https://dev.maxmind.com/geoip/release-notes/2024#presigned-urls-for-database-downloads 
MaxMind users who download databases should make sure that their HTTP client follows redirects and there are no proxy or firewall settings that would block requests to the host we are redirecting to.
See https://meta.discourse.org/t/fail-to-download-maxmind-db-with-valid-key-can-download-the-db-from-inside-containerr/300590/4 and https://meta.discourse.org/t/maxmind-r2-presigned-urls/298941/2

Allow redirect when downloading maxmind database

---

docs/ADMIN-QUICK-START-GUIDE.md

I fixed some links in the admin getting started guide, and changed the way internal links to categories are handled so they will work in other language locales besides US english.

fixed links in admin getting started guide

---

spec/fabricators/user_fabricator.rb
spec/lib/cooked_post_processor_spec.rb
spec/lib/guardian/topic_guardian_spec.rb
spec/lib/guardian_spec.rb
spec/lib/post_action_creator_spec.rb
spec/lib/post_creator_spec.rb
spec/lib/post_destroyer_spec.rb
spec/lib/post_revisor_spec.rb
spec/lib/topic_creator_spec.rb
spec/models/group_spec.rb
spec/models/post_mover_spec.rb
spec/requests/topics_controller_spec.rb
spec/requests/users_controller_spec.rb
spec/serializers/topic_view_details_serializer_spec.rb
spec/serializers/topic_view_serializer_spec.rb
spec/services/user_destroyer_spec.rb
spec/system/flagging_post_spec.rb

Make admins TL4 by default in tests, foregoing the need to call `refresh_auto_groups` on them.

DEV: Make all admins TL4 in tests

---

.github/workflows/tests.yml

The output is too verbose and prevents us from quickly identifying tests
failures. Now that our tests are way more stable and less flaky, we can
drop the documentation format since we do not need it for debugging
purposes that often anymore

DEV: Drop documentation format on CI

---

app/assets/stylesheets/common/admin/schema_field.scss

UX: Fix position of characters count on objects setting input field

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/models/theme-settings.js
app/assets/javascripts/admin/addon/routes/admin-customize-themes-show-schema.js
app/controllers/admin/themes_controller.rb
app/serializers/theme_objects_setting_metadata_serializer.rb
app/serializers/theme_serializer.rb
app/serializers/theme_settings_serializer.rb
config/routes.rb
spec/requests/admin/themes_controller_spec.rb
spec/serializers/theme_objects_setting_metadata_serializer_spec.rb
spec/serializers/theme_settings_serializer_spec.rb
spec/system/admin_editing_objects_typed_theme_setting_spec.rb
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

Previously, we were preloading the necessary metadata for
`adminCustomizeThemes.show.schema` route in the
`adminCustomizeThemes.show` route. This is wasteful because we're
loading data upfront when the objects setting editor may not be used.
This change also lays the ground work for a future commit where we need
to be shipping down additional metadata which may further add to the
payload.

DEV: Load theme objects typed setting metadata when routing to editor

---

spec/rails_helper.rb

This allows plugins to also easily read fixture
files for tests, rather than having to do stuff
like this:
```
File.open(File.join(__dir__, "../../../fixtures/100x100.jpg"))
```

DEV: Add plugin_file_from_fixtures helper

---

.github/workflows/tests.yml
lib/tasks/qunit.rake

This is so the CI output on GitHub actions isn't showing
tons and tons of unnecessary log data every time you want
to see the important thing, which is the actual test failure.

DEV: Change QUnit reporters to dot

---

spec/generator/site_setting_move_to_groups_migrations_generator_spec.rb
spec/generator/site_setting_rename_migrations_generator_spec.rb
spec/migrations/update_category_setting_approval_values_spec.rb

(plus fix the typo in the filename)

DEV: Silence the output of migration specs

---

lib/letter_avatar.rb

To generate letter avatars, we’re currently using the ImageMagick suite and we’re using the Helvetica font family. However, that font isn’t shipped anymore in the latest stable version of Debian (Bookworm). Instead it seems to have been replaced by the Nimbus font. The rendering is extremely similar (not to say it’s the same thing) so it shouldn’t be noticeable.
That change is necessary for us to upgrade our docker images to Debian Bookworm.

DEV: Use Nimbus font instead of Helvetica

---

app/assets/javascripts/discourse/app/components/modal/download-calendar.js

Prior to this fix the options were not passed down when the user had no default calendar.
No test as it's mostly an interaction between discourse-calendar and core which is hard to test.

FIX: correctly pass down calendar options

---

app/views/topics/show.html.erb
config/locales/server.en.yml
lib/topic_view.rb
spec/requests/topics_controller_spec.rb
spec/views/topics/show.html.erb_spec.rb

When crawlers visit a post-specific URL like `/t/-/{topic-id}/{post-number}`, we use the canonical to direct them to the appropriate crawler-optimised paginated view (e.g. `?page=3`).
However, analysis of google results shows that the post-specific URLs are still being included in the index. Google doesn't tell us exactly why this is happening. However, as a general rule, 'A large portion of the duplicate page's content should be present on the canonical version'.
In our previous implementation, this wasn't 100% true all the time. That's because a request for a post-specific URL would include posts 'surrounding' that post, and won't exactly conform to the page boundaries which are used in the canonical version of the page. Essentially: in some cases, the content of the post-specific pages …

FEATURE: Simplify crawler content for non-canonical post URLs

---

lib/topic_view.rb
spec/lib/topic_view_spec.rb

At the moment, all topic `?page=` views are served with exactly identical page titles. If you search for something which is mentioned many times in the same Discourse topic, this makes for some very hard-to-understand search results! All the result titles are exactly the same, with no indication of why there are multiple results showing.
This commit adds a `- Page #` suffix to the titles in this situation. This lines up with our existing strategy for topic-list pagination.

FEATURE: Add page number to page titles for crawlers

---

config/site_settings.yml

This user-agent is sent when URLs are inspected via the UI of Google's search console. It makes sense for us to serve it the same content as other bots, including GoogleBot.

DEV: Add Google-InspectionTool as a crawler user agent

---

app/assets/javascripts/admin/addon/components/embeddable-host.hbs
app/assets/javascripts/admin/addon/components/embeddable-host.js

The rest object doesn't need the whole serialized category.

DEV: Set category on embeddable-host component instead of rest object

---

lib/middleware/request_tracker.rb

It's best to always set a content-type header and one was missing here.

FIX: Add content-type header to rate limiter error

---

app/models/user.rb
plugins/chat/app/services/chat/search_chatable.rb
plugins/chat/spec/services/chat/search_chatable_spec.rb
spec/models/user_spec.rb

This enables the following in Discourse AI
```ruby
plugin.register_modifier(:chat_allowed_bot_user_ids) do |user_ids, guardian|
if guardian.user
mentionables = AiPersona.mentionables(user: guardian.user)
allowed_bot_ids = mentionables.map { |mentionable| mentionable[:user_id] }
user_ids.concat(allowed_bot_ids)
end
user_ids
end
```
some bots that are id < 0 need to be discoverable in search otherwise people can not talk to them.

FEATURE: allow re-scoping chat user search via a plugin

---

config/initializers/100-session_store.rb

Warning is getting tiring on local and I have https://l.discourse working just fine (tm)

DEV: allow developers to use HTTPS if they wish

---

lib/tasks/maxminddb.rake

We want to know when nothing was downloaded because stuff has been
cached on disk

DEV: Improve output of `maxminddb:refresh`

---

app/models/post.rb
db/migrate/20240327000440_replace_post_reply_index.rb

post_number is a sequence per topic, so it doesn't make sense to have an index on only reply_to_post_number without also including the topic_id.

PERF: Replace posts reply_to_post_number index

---

app/models/problem_check.rb
app/models/problem_check_tracker.rb

This was originally introduced in https://github.com/discourse/discourse/pull/26071, but that PR was closed, because the requirements changed. This PR lifts only the relevant parts, since they are a prerequisite for the new admin notice system.

DEV: Add the ability for problem checks to specify "max blips"

---

.github/workflows/tests.yml

We run on different runners depending on the scenario. We should use the
right number of parallel jobs for bundle install based on the number of
CPU cores the runner has.

DEV: Use the right number of cores for bundle install in tests workflow

---

lib/plugin/instance.rb
spec/rails_helper.rb

Followup 0bbca318f27089567d43f103cbfb18fa01eff15e,
rather than making developers provide the plugin path
name (which may not always be the same depending on
dir names and git cloning etc) we can infer the plugin
dir from the caller in plugin_file_from_fixtures

DEV: Use caller for plugin_file_from_fixtures

---

app/assets/javascripts/discourse/app/components/sidebar/admin-header.gjs
app/assets/javascripts/discourse/app/components/sidebar/api-section.hbs
app/assets/javascripts/discourse/app/components/sidebar/api-sections.hbs
app/assets/javascripts/discourse/app/components/sidebar/back-to-forum.gjs
app/assets/javascripts/discourse/app/components/sidebar/section.hbs
app/assets/javascripts/discourse/app/components/sidebar/section.js
app/assets/javascripts/discourse/app/components/sidebar/toggle-all-sections.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-section.js
app/assets/javascripts/discourse/app/services/sidebar-state.js
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/sidebar.scss
config/locales/client.en.yml
plugins/chat/spec/system/admin_sidebar_navigation_spec.rb
spec/system/admin_sidebar_navigation_spec.rb
spec/system/page_objects/components/navigation_menu/sidebar.rb

By default, admin sections should be collapsed.
In addition, a button to expand/collapse all sections has been added.
https://github.com/discourse/discourse/assets/72780/c8dd400c-f970-4ab7-b89b-883fe8cc7624

FEATURE: the ability to expand/collapse all admin sections

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/stylesheets/common/admin/schema_field.scss
app/assets/stylesheets/common/admin/schema_theme_setting_editor.scss
app/assets/stylesheets/common/select-kit/select-kit.scss

This adds collapsible headings to child lists, and adjusts the layout to utilize the available space. 
Before:
After:

UX: add collabsible headings to theme objects editor, adjust styles

---

plugins/chat/app/services/chat/create_direct_message_channel.rb
plugins/chat/spec/services/chat/create_direct_message_channel_spec.rb

When the site setting for `chat_max_direct_message_users` is set to 1, it is expected that users can have a 1:1 chat with other users. However, since the current user is counting as 1 user it makes starting a new chat impossible.
This change hands this validation off to `DirectMessageChannel::MaxUsersExcessPolicy` which handles the count correctly by filtering out the current user.

FIX: allow direct message when max dm users set to 1

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
config/discourse_defaults.conf
config/site_settings.yml
spec/helpers/application_helper_spec.rb
spec/requests/application_controller_spec.rb

This commit removes the 'experimental_preconnect_link_header' site setting, and the 'preload_link_header' global setting, and introduces two new global settings: early_hint_header_mode and early_hint_header_name.
We don't actually send 103 Early Hint responses from Discourse. However, upstream proxies can be configured to cache a response header from the app and use that to send an Early Hint response to future clients.
- `early_hint_header_mode` specifies the mode for the early hint header. Can be nil (disabled), "preconnect" (lists just CDN domains) or "preload" (lists all assets).
- `early_hint_header_name` specifies which header name to use for the early hint. Defaults to "Link", but can be changed to support different proxy mechanisms.

DEV: Consolidate experimental 'Link' header implementations

---

plugins/chat/assets/javascripts/discourse/connectors/above-site-header/chat-body-class.gjs
plugins/chat/spec/system/page_objects/chat/chat.rb
plugins/chat/spec/system/visit_channel_spec.rb

This class should help makes tests more reliable by ensuring we are in a known state.

DEV: adds a has-preloaded-chat-channels body-class

---

lib/topic_creator.rb
spec/lib/topic_creator_spec.rb

The `TopicCreator` class has a `skip_validations` option that can force-create a topic without performing permission checks or validation rules. However, at the moment it doesn't skip validations that are related to tags, so topics that are created by the system or by some scrip can still fail if they use tags. This PR makes the `TopicCreator` class skip all tags-related checks if the `skip_validations` is specified.
Internal topic: t/124280.

FIX: Skip tags-related validations when `skip_validations` option is present

---

config/locales/server.en.yml
lib/discourse_tagging.rb

When a topic fails to be created due to the user not having permission to add tags to the topic, the error message that you get is `There was an error tagging the topic` which is very generic and doesn't explain where/what the problem is. This PR adds a clearer error message for this scenario.

DEV: Better error message when user is not allowed to user tags

---

.github/workflows/tests.yml

The version of Chromium we have in our images (120) is relatively unstable and our system specs break regularly.
This PR makes sure Chrome is used instead for system specs.

DEV: Use Chrome in system specs

---

app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-collection.hbs
app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-collection.js

This will prevent any scrolling issues with sk when on mobile, especially on iOS and in modals.
Prior to this fix, scrolling could sometimes stop working in dropdowns.

DEV: applies body-scroll-lock on select-kit

---

app/assets/javascripts/admin/addon/components/site-settings/category-list.gjs
app/assets/javascripts/admin/addon/components/site-settings/file-size-restriction.gjs
app/assets/javascripts/admin/addon/components/site-settings/file-types-list.gjs

Descriptions for the `category-list`, `file-size-restriction` and `file-types-list` site/theme settings aren't rendered due to a bug that was introduced when those components were migrated to Glimmer components. This PR fixes the bug which is that arguments passed to .gjs components should be accessed as `@argument` and not `this.arugment` inside the `<template>` tag.

FIX: Descriptions not showing for some site setting types

---

app/assets/javascripts/discourse/app/lib/body-scroll-lock.js

Applying `overflow: hidden` was not playing well with sticky elements (like the header for example). It appears that we don't really need this to achieve our goal so Im removing this part of body scroll lock for now.

FIX: prevents body scroll to hide sticky elements

---

app/assets/javascripts/select-kit/addon/components/select-kit.js
app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-collection.js
app/assets/stylesheets/common/base/discourse.scss

- uses footer-nav height and safe-area-inset-bottom as bottom padding
- body scroll lock select-kit only when inside a modal

FIX: tweaks of select-kit on mobile

---

Gemfile.lock

This reverts commit 260b2a7450f75646f7c659ef41fa004ae51ec54d.
I believe this is causing errors: `SMTP-AUTH requested but missing user name`

Revert "Build(deps): Bump net-smtp from 0.4.0.1 to 0.5.0 (#26381)"

---

Gemfile.lock
config/environments/production.rb

FIX: Don't set smtp authentication type when there's no user or password

---

app/models/category_list.rb

The previous implementation of the method generated the query to find the relevant topics and iterated over the results processing them.
This behavior made difficult reusing or changing the query logic in classes extending CategoryList.
This commit extracts the query logic into another method called `all_relevant_topics` which can be reused or overwritten in descendant classes.
The commit does not add specs because no behavior was changed. The refactor only extracted the logic into another method. The existing tests cover the changes.

DEV: Extract the query code from CategoryList.find_relevant_topics into a separate method

---

.github/workflows/tests.yml

Bundle cache should be keyed on ruby version as well as the debian
release name. Changes to the debian release can affect the way gems are
installed since gems may link to different versions of binaries.
Dependent on https://github.com/discourse/discourse_docker/pull/789

DEV: Update actions cache keys for bundler and app cache

---

app/models/global_setting.rb
config/environments/production.rb
spec/integration/smtp_spec.rb

This is a follow up to 897be75941eb95b89e885e4b447ddf0c75eb81ff.
When updating `net-smtp` from `0.4.x` to `0.5.x`, our test suite passed
but the error `ArgumentError: SMTP-AUTH requested but missing user name`
was being thrown in production leading to emails being failed to send
out via SMTP.
This commit adds a test to ensure that our production SMTP settings will
at least attemp to connect to an SMTP server.

DEV: Add a test to ensure that our SMTP settings are correct

---

.github/workflows/tests.yml

This is a follow up to 69c132723ff7cf1c338709ac658b919c9f984125 which
wasn't right and broke our bundler github actions cache key

DEV: Update actions cache keys for bundler cache take 2

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/field.gjs
spec/fixtures/theme_locales/objects_settings/en.yaml
spec/requests/admin/themes_controller_spec.rb
spec/serializers/theme_objects_setting_metadata_serializer_spec.rb
spec/system/admin_editing_objects_typed_theme_setting_spec.rb
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

In cdba86459877987f52def4bcfeba5c7bef7de407, we added support for adding
a description which will be displayed under the input of each property
on the client side.
Currently this convention in the locale file is followed:
```
en:
theme_metadata:
settings:
objects_setting:
description: <description> for the setting
schema:
properties:
name: <description for the name property>
links:
name: <description for the name property in link>
url: <description for the url property in link>
```
Since we now want to allow the label to be translated as well, we will
be changing the convention to the following:
```
en:
theme_metadata:
settings:
objects_setting:
description: <description> for the setting
schema:
properties:
name:
label: <label for the name property>
description: <description for the name …
```

DEV: Support translations for property labels in objects schema editor

---

config/site_settings.yml

It's not really intentional to have regular admins change
this in all but pathological cases. It deletes all notifications
over this threshold for users without warning. If admins
really want to turn this on, they can do it via the app.yml file

FIX: Hide footgun max_notifications_per_user site setting

---

app/models/problem_check.rb
lib/discourse_plugin_registry.rb
lib/plugin/instance.rb
spec/jobs/run_problem_check_spec.rb
spec/jobs/run_problem_checks_spec.rb
spec/models/problem_check_spec.rb

Previously the problem check registry simply looked at the subclasses of `ProblemCheck`. This was causing some confusion in environments where eager loading is not enabled, as the registry would appear empty as a result of the classes never being referenced (and thus never loaded.)
This PR changes the approach to a more explicit one. I followed other implementations (bookmarkable and hashtag autocomplete.) As a bonus, this now has a neat plugin entry point as well.

DEV: Make problem check registration more explicit

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/editor/child-tree-node.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/editor/child-tree.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/editor/tree-node.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/editor/tree.gjs

Prior to this change, the `SchemaThemeSetting::Editor#tree` was creating a
new `Tree` instance which holds instances of `Node`. Both classes
consisted of tracked properties. The problem with this approach is that
when any tracked properties is updated, Ember will revaluate
`SchemaThemeSetting::Editor#tree` and because that method always return
a new instance of `Tree`, it causes the whole navigation tree to
rerender just because one tracked property changed.
This rerendering of the whole navigation tree every time made it hard to
implement simple features like hiding a section in
9baa820d53757aec36e4cb86efab8d0bb3f264c0. Instead of being able to just
declare a tracked property to hide/show a section, we end up with a more
complicated solution.
This commit rewrites …

DEV: Rewrite `SchemaThemeSetting::Editor` to avoid rerendering problems

---

app/assets/javascripts/discourse/app/controllers/application.js

The computed property wasn't updating as expected on route change, but using a getter works!

FIX: use getter for `showPoweredBy`

---

app/assets/javascripts/admin/addon/components/embeddable-host.hbs
app/assets/javascripts/admin/addon/components/embeddable-host.js
app/assets/javascripts/select-kit/addon/components/category-chooser.js

... rather than just the category id.
In order for the user to have selected a category, the category must have been loaded and it's useful for the category chooser to provide this fetched category so that it doesn't need to be refetched.
In the future, it would be better to store the categories that the chooser knows about in local component state, so that the category doesn't need to be fetched from the id map, but this, at least, puts the API in place.

DEV: Make CategoryChooser optionally provide the category

---

app/assets/stylesheets/common/base/topic-post.scss

Follow-up to https://github.com/discourse/discourse/pull/26337
This needs to wrap for the case of many users:
Before:
After:

UX: wrap `small-user-list-content` for many users case

---

app/assets/javascripts/discourse/app/controllers/application.js
app/assets/javascripts/discourse/app/helpers/hide-application-sidebar.js
app/assets/javascripts/discourse/app/mixins/disable-sidebar.js
app/assets/javascripts/discourse/app/routes/invites-show.js
app/assets/javascripts/discourse/app/routes/second-factor-auth.js
app/assets/javascripts/discourse/app/routes/wizard.js
app/assets/javascripts/discourse/app/services/sidebar-state.js
app/assets/javascripts/discourse/app/templates/invites/show.hbs
app/assets/javascripts/discourse/app/templates/second-factor-auth.hbs
app/assets/javascripts/discourse/app/templates/wizard.gjs

There are often circumstances where a theme or plugin would want to disable the sidebar. This can be a route (wizard, invite) or a particular theme/layout. This PR adds the ability to disable the sidebar from an Ember component. 
Usage is straightforward, add: 
```
{{hide-application-sidebar}}
```
to a template. The sidebar will be hidden as long as that component is rendered. Once it is removed from rendering, the sidebar will be displayed (as long as no other `hide-application-footer` instances are present). Works very similarly to the `{{hide-application-footer}}` helper.

DEV: Add `{{hide-application-sidebar}}` helper

---

config/locales/server.en.yml

The personal message enabled groups site setting is overridden by the group interaction settings for specifying who is allowed to write to groups. This was not clearly explained in the description here and I think I fixed it!

update desc of personal message enabled groups setting

---

config/locales/server.en.yml

improved description of  `allow_anonymous_likes` setting so it no longer refers to not-logged-in-users

Improved description of `allow_anonymous_likes`

---

app/jobs/regular/bulk_invite.rb
config/site_settings.yml
spec/jobs/bulk_invite_spec.rb

This adds a hidden site setting of `skip_email_bulk_invites`
If set to `true`, the `BulkInvite` job will pass the value to `Invite`, meaning the generated invite wont trigger an email notification being sent to the newly invited user.
(This is useful if you want to manage the sending of the invite emails outside of Discourse.)

DEV: Add skip_email_bulk_invites hidden site setting

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/field.gjs
app/assets/stylesheets/common/admin/schema_field.scss

this makes some minor adjustments to get the new schema editor workable on small mobile devices 
Before:
After:

UX: minor theme schema editor adjustments for mobile

---

app/assets/stylesheets/common/base/code_highlighting.scss

Code within `em` or `strong` wasn't getting a background or color change:
This fixes it.

UX: highlight code in `em` and `strong` blocks

---

Gemfile
Gemfile.lock

This gem is failing to install cleanly on macOS and the following
workaround is required:
`bundle config build.gc_tracer
--with-cflags=\"-Wno-incompatible-pointer-types\"`
Instead of requiring this workaround, we have decided to drop `gc_tracer`
because it isn't a gem that is used anymore.

DEV: Drop gc_tracer gem

---

Gemfile
Gemfile.lock

This gem was added close to 10 years ago to speed up the generation of
RSS feeds. However, RSS feeds generation do not even call `String#to_xs`
anymore and the `fast_xs` gem does not install on macOS without using
the following workaround:
`bundle config build.fast_xs
--with-cflags=\"-Wno-incompatible-pointer-types\"`
Therefore, we have decided to drop the gem.

DEV: Drop fast_xs gem

---

lib/theme_settings_object_validator.rb
spec/lib/theme_settings_object_validator_spec.rb

For a schema like this:
```
schema = {
name: "section",
properties: {
category_property: {
type: "categories",
required: true,
},
},
}
```
When the value of the property is set to an empty array, we are not
raising an error which we should because the property is marked as
required.

FIX: Error not being raised for required typed categories property

---

plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs
plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/spec/system/chat_channel_spec.rb

The expected behavior when receiving a message is the following:
- if user is at the bottom of the screen, scroll and append message
- if user is not at the bottom of the screen, don't scroll, show arrow and don't append message

FIX: messages list shouldn't scroll on new message

---

app/assets/stylesheets/common/admin/schema_field.scss
app/assets/stylesheets/common/admin/schema_theme_setting_editor.scss

This improves some styles for small screens...
Before:
After:

UX: minor style adjustments for schema objects editor

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

In e05628c0793567b581ca04cbae801a7d4a6e55ca we omitted the HTML view for logged in users but that view is used when printing.
This restore the HTML view when printing a topic page.

FIX: print view wasn't working

---

app/assets/stylesheets/common/base/header.scss

I think this may have broken when the home-logo-wrapper-outlet was introduced? the additional wrapper means we need a little more CSS. 
Before:
After:

UX: fix overflow of long site text site names in the header

---

app/assets/javascripts/discourse/app/components/sidebar/filter.gjs
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js

Allow the sidebar filter to be cleared by hitting ESC.
Demo
https://github.com/discourse/discourse/assets/72780/769794f9-98fa-400a-9326-6c463ed3196c

FEATURE: clear sidebar admin filter with ESC

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/categories.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/groups.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/models.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/tags.gjs

The field components to select categories, groups and tags had quite a
bit of logic duplicated between them. This commit refactors the logic
to remove most of the duplication so that we can introduce changes
without having to make the changes in multiple places.

DEV: Refactor Discourse models based field components to reduce duplication

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

When adding a new object, we want to switch to the input fields of the
new object instead of just appending the new object to the list of
objects as we believe this is a better UX flow.

UX: Switch to new object when adding object in theme objects setting editor

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/models.gjs
app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

In the categories, groups and tags selectors, we were showing a
validation error message when a property that is not required but
has a min validation is empty. In this case, we should not be displaying
the min validation error message because the property is allowed to be
empty.

UX: Fix required validation error shown for not required properties

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/models.gjs
app/assets/stylesheets/common/admin/schema_theme_setting_editor.scss
app/controllers/admin/themes_controller.rb
spec/requests/admin/themes_controller_spec.rb
spec/system/admin_editing_objects_typed_theme_setting_spec.rb
spec/system/page_objects/pages/admin_objects_theme_setting_editor.rb

Before this change, the validation error message shown to the user when
saving a theme objects setting is very cryptic. This commit changes the
validation error messages to be displayed on top of the editor instead.
Note that I don't think this way of displaying is the ideal state we
want to get to but given the time we have this will do for now.
https://github.com/discourse/discourse/assets/4335742/4ffa2517-02b8-4e75-9d60-34ecc08b94d8
https://github.com/discourse/discourse/assets/4335742/66e56036-bee4-4476-99ff-1e295f703664

UX: Improve validation error message when saving theme objects setting

---

lib/tasks/maxminddb.rake

We currently support `GlobalSetting.refresh_maxmind_db_during_precompile_days` which
should cache the maxmind databases on disk for the configured number of
days before it downloads the databases from maxmind again via the API.
This was previously added to help us avoid hitting the API rate limit from maxmind.
However, there is a bug in the `copy_maxmind` method of the Rake task when we copied the latest
downloaded database to the cache directory. In particular, `FileUtils.cp` was called with
`preserve: true` which would preserve the modified time of the file
being copied. This is problematic because downloading the database from
maxmind on 2 April 2024 can give us a file with an mtime of 29 March
2024. If `GlobalSetting.refresh_maxmind_db_during_precompile_days` is
set to `2` for …

FIX: `maxmind:refresh` does not respect `refresh_maxmind_db_during_precompile_days`

---

config/discourse_defaults.conf
lib/discourse_ip_info.rb
lib/discourse_ip_info_spec.rb

This allows downloading the MaxMind databases from a mirror in cases
where downloading directly from MaxMind's API endpoint is problematic
due to API limits.

DEV: Introduce `maxmind_mirror_url` GlobalSetting

---

plugins/chat/assets/javascripts/discourse/components/chat-composer.hbs
plugins/chat/assets/javascripts/discourse/components/chat-composer.js

We need to scroll lock textareas when the keyboard is visible, otherwise they might become unusable if another element is body scroll locked on the page (eg: channels messages).
Note this commit is also slightly simplifying the code.

FIX: body scroll lock textarea

---

app/views/topics/show.html.erb
spec/requests/topics_controller_spec.rb

Followup to 3329484e2d64951956981bde9bff662d6ad8b412

FIX: Restore author on non-first-post crawler views

---

app/controllers/admin/plugins_controller.rb
spec/requests/admin/plugins_controller_spec.rb

Plugins that are hidden or disabled aren't shown in the plugins list at `/admin/plugins` because they cannot be changed. However, the `#show` route doesn't check for the plugin's state and responds with 200 and the plugin's info even if the plugin is hidden or disabled. This PR makes the `#show` route respond with 404 if the plugin is hidden or disabled.

FIX: Don't allow access to plugin page if plugin is not visible

---

app/controllers/topics_controller.rb
spec/requests/topics_controller_spec.rb

This PR creates an extension point for plugins to add query parameters to an array, to not be scrubbed when the topics controller redirects to the most "proper" topic URL. We have all sorts of topic urls supported, but topics controller redirects to the standard version. In the redirect we scrub query params. A customer wants a specific param retained and this allows for the addition!

DEV: Modifier to add params to TopicsController redirect

---

spec/requests/api/schemas/json/site_basic_info_response.json
spec/requests/api/site_spec.rb

Add the /site/basic-info.json endpoint to the api docs.
See: https://meta.discourse.org/t/302109

DEV: Document basic-info endpoint

---

app/assets/javascripts/discourse/app/raw-views/topic-bulk-select-dropdown.gjs
app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/mobile/topic-list.scss
config/locales/client.en.yml

This fixes a CSS issue on mobile that was hiding labels, and cleans up styles slightly:
Before:
After:

UX: adjustments for experimental bulk select menu

---

plugins/chat/spec/system/document_title_spec.rb

`expect(page.title).to starts_with("...")` does not rely on capybara
waiters. This commit switches us to use `have_title` instead which will
rely on Capybara waiters.

DEV: Fix flaky system test

---

app/assets/javascripts/discourse/app/lib/site-setting-filter.js
app/assets/javascripts/discourse/tests/fixtures/site-settings.js
app/models/user.rb
config/locales/server.en.yml
lib/site_setting_extension.rb
spec/models/user_spec.rb
spec/system/admin_site_setting_search_spec.rb

When a user is manually deactivated, they should not be deleted by our background job that purges inactive users.
In addition, site settings keywords should accept an array of keywords.

FEATURE: ignore manually deactivated users when purging

---

app/assets/javascripts/admin/addon/adapters/theme.js
app/assets/javascripts/admin/addon/models/theme.js
app/assets/javascripts/discourse/tests/unit/models/theme-test.js

Instead of dealing with a generic object for `Theme#settings`, we want
to always be dealing with `ThemeSettings` objects. Previously, we
converted the generic objects to `ThemeSettings` objects in the theme's
adapter `afterFindAll` function. This is not correct because updating
or saving the theme individually reverted the `Theme#settings` back to an
array of generic object.
To fix this problem, the proper way with our REST models is to overwrite
the static `munge` method and create `ThemeSettings` instances there.

FIX: Ensure `Theme#settings` are instances of `ThemeSettings`

---

app/assets/javascripts/discourse/app/components/composer-editor.hbs
app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/package.json
yarn.lock

We've been having some performance issues with diffhtml and are trying out this newer & smaller library called morphlex.
No tests were changed since this should be a drop-in replacement (at least behaviour-wise).

DEV: replace diffhtml with morphlex

---

.github/workflows/tests.yml
lib/turbo_tests/documentation_formatter.rb
lib/turbo_tests/reporter.rb
lib/turbo_tests/runner.rb

DEV: Restore RSpec 'documentation' output, but collapse in CI

---

app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/app/models/composer.js
app/assets/javascripts/discourse/app/models/user-drafts-stream.js
app/assets/javascripts/discourse/app/routes/about.js
app/assets/javascripts/discourse/app/services/composer.js
plugins/chat/assets/javascripts/discourse/components/chat/modal/create-channel.js

Category.findById uses a Map to look up categories by ID which makes it
faster and preferable over Site.categories.find.

DEV: Use Category.findById instead of Array.find

---

app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/app/models/category-list.js
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/app/models/site.js
app/assets/javascripts/discourse/app/models/topic.js
app/assets/javascripts/discourse/tests/acceptance/d-styles-test.js
app/assets/javascripts/discourse/tests/acceptance/hashtag-css-generator-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
app/assets/javascripts/discourse/tests/integration/components/reorder-categories-test.gjs
app/assets/javascripts/discourse/tests/unit/models/category-test.js
app/assets/javascripts/discourse/tests/unit/models/site-test.js
plugins/chat/test/javascripts/acceptance/hashtag-css-generator-test.js

Some of the properties, like 'categoriesById', 'parentCategory' and 'subcategories', were updated manually when categories were loaded. This was not ideal because it required a lot of code to keep the objects in sync and some of the properties were not updated correctly.

DEV: Make category object more Ember friendly

---

app/assets/javascripts/discourse/app/components/header/home-logo.gjs
app/assets/javascripts/discourse/app/widgets/home-logo-wrapper-outlet.js

FIX: add home-logo outlet args to non glimmer version

---

app/models/user_summary.rb
lib/post_creator.rb
spec/models/user_summary_spec.rb

This PR improves the performance of the `most_replied_to_users` method on the `UserSummary` model.
```ruby
post_query
.joins(
"JOIN posts replies ON posts.topic_id = replies.topic_id AND posts.reply_to_post_number = replies.post_number",
)
.where("replies.user_id <> ?", @user.id)
.group("replies.user_id")
.order("COUNT(*) DESC")
.limit(MAX_SUMMARY_RESULTS)
.pluck("replies.user_id, COUNT(*)")
.each { |r| replied_users[r[0]] = r[1] }
```
```ruby
post_query
.joins(
"JOIN posts replies ON posts.topic_id = replies.topic_id AND replies.reply_to_post_number = posts.post_number",
)
.where("replies.user_id <> posts.user_id")
.group("replies.user_id")
.order("COUNT(*) DESC")
.limit(MAX_SUMMARY_RESULTS)
.pluck("replies.user_id, COUNT(*)")
.each { |r| replied_users[r[0]] = r[1] }
```
```ruby …
```

PERF: Improve performance of `most_replied_to_users`

---

config/locales/server.en.yml

To remove the Getting Started button manually, you have to disable bootstrap mode by setting bootstrap_mode_min_users to 0. I clarified this in the description for the setting.

updated bootstrap site setting to refer to getting started button

---

docs/ADMIN-QUICK-START-GUIDE.md

The "upgrade"page has been renamed to "update". See for context: https://meta.discourse.org/t/new-change-upgrade-page-is-now-the-update-page/302276?u=tobiaseigen

renamed upgrade to update

---

app/controllers/admin/themes_controller.rb
app/models/theme_setting.rb
config/site_settings.yml
db/migrate/20240404034232_remove_experimental_objects_type_for_theme_settings.rb
spec/lib/theme_settings_manager/objects_spec.rb
spec/models/theme_field_spec.rb
spec/models/theme_setting_spec.rb
spec/requests/admin/themes_controller_spec.rb
spec/serializers/theme_objects_setting_metadata_serializer_spec.rb
spec/serializers/theme_settings_serializer_spec.rb
spec/system/admin_editing_objects_typed_theme_setting_spec.rb

Objects type for theme settings is no longer considered experimental so
we are dropping the site setting.

DEV: Remove `experimental_objects_type_for_theme_settings` site setting

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

Prior to this change, the input fields were not displaying when adding
an object to a objects typed theme setting which has a default value of
`[]`. This is because the `fields` getter was not being recomputed.

FIX: Input fields not displaying when adding a object to empty setting

---

app/assets/javascripts/discourse/app/components/composer-editor.hbs
app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-form-template-test.js

The Composer service's `openNewTopic` action allows us to open the composer with certain topic properties pre-filled/selected. Currently, it supports setting properties such as `title`, `body`, `category` and `tags`.
This PR is intended to add support for form templates to `openNewTopic`.

DEV: Add form template support for composer's `openNewTopic` action

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Using around_action means `add_early_hint_header` is in the stack for every request, and gets included in the backtrace of any errors.
We can manage with an after_action instead, which avoids adding to the stack depth (and avoids people blaming me for unrelated application errors 😉)

DEV: early hints around_action -> after_action

---

app/assets/javascripts/discourse/app/lib/url.js
app/assets/javascripts/discourse/tests/unit/lib/click-track-test.js
app/assets/javascripts/discourse/tests/unit/lib/url-test.js

Simplify the implementation and make it return `true` for prefix-less relative urls, like `docs`

DEV: Redo `DiscourseURL.isInternal()`

---

app/assets/javascripts/discourse/app/components/d-editor.js
plugins/discourse-details/spec/system/preview_spec.rb
spec/system/page_objects/components/composer.rb

when morphing is enabled, `<details>` elements in the preview will be kept open 🤩
https://github.com/discourse/discourse/assets/362783/9ab56ac3-cbe7-4a94-b6b7-7f96e88df672
https://github.com/discourse/discourse/assets/362783/638e7a38-42be-4226-a3c4-56946546ca6a

FIX: keep details open in preview

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/enum.gjs
app/assets/javascripts/discourse/tests/fixtures/theme-setting-schema-data.js
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

For a `typed: objects` theme setting with an enum property, we are
adding a `default` key for `type: enum` fields which will be used
as the default value on the client side.
```
some_objects_setting:
type: objects
schema:
name: field
properties:
enum_field:
type: enum
default: awesome
choices:
- nice
- cool
- awesome
```

UX: Allow a default value to be specified for enum properties

---

config/site_settings.yml

I left out a few setting types that are not used much
(e.g. value_list) for now, we may remove them.

DEV: Added docs for additional site setting types

---

app/assets/javascripts/discourse/app/routes/about.js
app/models/about.rb
app/serializers/about_serializer.rb
spec/models/about_spec.rb

Load a basic category object instead of just the category ID. This makes the about page self contained (it does not require additional category info from the `Site` object).

FIX: Load category info for about page

---

app/assets/javascripts/discourse/app/raw-views/topic-status.js

Building on the modernization efforts of PR #26342, this PR applies similar updates to topic property access in the topic-status raw view, shifting from Ember's .get to direct property access.

FIX: update topic property access in raw topic-status view

---

Gemfile
Gemfile.lock
plugins/automation/plugin.rb

Moving the automation plugin dependencies to core allows us to receive automatic notifications about new releases for those gems.
Internal topic: t/112693/54.

DEV: Move automation dependencies to core's Gemfile

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/select-kit/addon/components/toolbar-popup-menu-options.js
plugins/discourse-presence/test/javascripts/acceptance/discourse-presence-test.js

The only functionality changes from this PR are some new `appEvent` triggers. That is for toolbar button clicks in the editor, and an appEvent for when the composer is opened, where the model is passed. 
**[app/assets/javascripts/discourse/app/components/d-editor.js](https://github.com/discourse/discourse/compare/d-editor-events?expand=1#diff-ac61e3b4a6e7c249e8b139b17417b7f7af20d61cf96476a7d2db09d2aabe54eb) changes** 
I renamed some variables to better represent the actual meaning (example: button -> buttonAttrs, as the variable name `button` then couldn't be used to represent the _actual button_ that is passed into `action`. The reason for all the edits in this file was to wrap the action call in a new function so that an appEvent could be consistently triggered without having to add the …

DEV: Add appEvents for composer / DEditor toolbar events

---

app/models/topic_embed.rb
spec/models/topic_embed_spec.rb

This modifier allows a plugin to change the arguments used when creating a new topic for an imported article.
For example: let's say you want to prepend "Imported: " to the title of every imported topic. You could use this modifier like so:
```ruby
plugin.register_modifier(:topic_embed_import_create_args) do |args|
args[:title] = "Imported: #{args[:title]}"
args
end
```
In this example, the modifier is prepending "Imported: " to the `title` in the `create_args` hash. This modified title would then be used when the new topic is created.

DEV: Add `topic_embed_import_create_args` plugin modifier

---

app/assets/javascripts/discourse/app/lib/load-faker.js
app/assets/javascripts/discourse/package.json
app/assets/javascripts/discourse/tests/acceptance/about-test.js
app/assets/javascripts/discourse/tests/loader-shims.js
plugins/styleguide/assets/javascripts/discourse/components/sections/organisms/modal.js
plugins/styleguide/assets/javascripts/discourse/routes/styleguide.js
plugins/styleguide/assets/javascripts/discourse/services/styleguide.js
yarn.lock

Available as a normal synchronous module in tests
Available as an async import in core, or via the `loadFaker` helper in themes/plugins (which cannot use async import directly)

DEV: Introduce faker.js for use in tests & styleguide

---

app/assets/javascripts/discourse-common/addon/utils/multi-cache.js
app/assets/javascripts/discourse/app/components/modal/history.js
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/app/models/group.js

We want to use asyncFindByIds, because, if the category doesn't exist locally, it allows us to fetch it.

DEV: Replace Category.findById with Category.asyncFindByIds in easy cases

---

app/assets/stylesheets/common/components/hashtag.scss
app/assets/stylesheets/common/foundation/mixins.scss

…to prevent them from overlapping/touching when placed on consecutive lines of text
Before/After
(screenshot taken with Text Size set to "Smaller")

UX: Tweak the mention padding

---

app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
app/assets/stylesheets/common/modal/modal-overrides.scss
app/controllers/topics_controller.rb
config/locales/client.en.yml
lib/topics_bulk_action.rb
spec/system/page_objects/components/topic_list_header.rb
spec/system/topic_bulk_select_spec.rb

This will allow you to type a single message when bulk closing topics
that will be applied to every topic, that way they all have the same
message.

FEATURE: Add message to bulk close topics

---

plugins/chat/assets/stylesheets/common/chat-message.scss

Improves the readability of a deleted chat message

UX: chat > deleted msg styling

---

config/site_settings.yml
db/migrate/20240327043323_disable_admin_sidebar_for_existing_sites.rb
db/migrate/20240327043323_set_admin_sidebar_enabled_groups.rb

By default, enable the new admin sidebar.
In addition, migration was created for old sites to keep the old admin panel.

FEATURE: enable new admin sidebar by default

---

lib/discourse_ip_info.rb
lib/discourse_ip_info_spec.rb

This commit changes `DiscourseIpInfo.mmdb_download` to use `File.join`
instead of `URI.join` when `GlobalSetting.maxmind_mirror_url` has been
configured. This is necessary because `URI.join` does not work the way I
expect it to work when I implemented it previously.
`URI.join("http://www.example.com/mirror", "test.tar.gz")` results in
`http://www.example.com/test.tar.gz` instead of our expected
`http://www.exmaple.com/mirror/test.tar.gz`. For our simple use case
here, `File.join` is sufficient.

FIX: `DiscourseIpInfo.mmdb_download` incorrectly joining URLs

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-default-toast-test.js
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/discourse/tests/unit/services/toasts-test.js
app/assets/javascripts/float-kit/addon/components/d-default-toast.gjs
app/assets/javascripts/float-kit/addon/components/d-menu.gjs
app/assets/javascripts/float-kit/addon/components/d-toast.gjs
app/assets/javascripts/float-kit/addon/lib/constants.js
app/assets/javascripts/float-kit/addon/lib/d-toast-instance.js
app/assets/javascripts/float-kit/addon/services/toasts.js
app/assets/stylesheets/common/components/bookmark-menu.scss
app/assets/stylesheets/common/float-kit/d-default-toast.scss
app/assets/stylesheets/common/float-kit/d-menu.scss
app/assets/stylesheets/mobile.scss
app/assets/stylesheets/mobile/components/_index.scss
app/assets/stylesheets/mobile/components/bookmark-menu.scss
app/assets/stylesheets/mobile/float-kit/_index.scss
app/assets/stylesheets/mobile/float-kit/d-menu-mobile.scss
app/assets/stylesheets/mobile/float-kit/d-menu.scss
spec/system/bookmarks_spec.rb

The colours for the icons in edit/delete are off, due to the strange .scss overrules. Pretty please investigate

UX: shows the bookmark menu as a modal on mobile

---

plugins/checklist/assets/javascripts/discourse/initializers/checklist.js
plugins/checklist/assets/javascripts/lib/discourse-markdown/checklist.js
plugins/checklist/assets/stylesheets/checklist.scss
plugins/checklist/test/javascripts/lib/checklist-test.js
plugins/discourse-local-dates/assets/javascripts/lib/discourse-markdown/discourse-local-dates.js

Exclude image URLs with empty alt text from checklist state changes. 
Adds a condition to skip `[]` preceded by `!`, preventing images from being misinterpreted as empty checklist items.
Internal - t/124499

FIX: checklist weren't working if there was an image URL

---

app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/javascripts/float-kit/addon/lib/d-toast-instance.js

The bug was due to the fact that the `<DModal />` is displayed inside a if block, when the condition was false to close the menu, the modal was just hidden without calling callbacks. The fix ensures we are correctly calling `modal.close()` before in this case.

FIX: prevents mobile DMenu modal to lock scroll

---

app/assets/javascripts/discourse/app/models/post.js
app/models/post_revision.rb
app/serializers/post_revision_serializer.rb

When lazy load categories is enabled, categories should be loaded with post revisions because the categories may not be preloaded on the client side.

FIX: Load categories with post revisions

---

plugins/chat/assets/javascripts/discourse/services/chat-channel-composer.js
plugins/chat/assets/javascripts/discourse/services/chat-thread-composer.js

Prior to this fix we would autofocus the chat input when editing a message. This was causing rendering issues (the body would scroll towards the top, leaving a large blank space between content and keyboard), especially on iOS, due to the fact that's it's not a trusted event and won't show the keyboard. Given it's not opening the keyboard anyways there's not reason to autofocus the keyboard.

FIX: do not autofocus input on edit in mobile

---

app/assets/javascripts/discourse/app/lib/load-faker.js
app/assets/javascripts/discourse/tests/setup-tests.js

Load synchronously in setup-tests

---

config/locales/client.en.yml
config/locales/server.en.yml

It's mostly fine to use the plural form instead of writing something like "topic(s)" when one or more topics could be meant, but the actual count is not known.
This also removes some unused strings from the locale files.

DEV: Reduce the usage of "(s)" in strings

---

app/assets/stylesheets/common/base/personal-message.scss
app/assets/stylesheets/common/foundation/base.scss

As discussed internally with the design team, we're adding a very minor 2px border-radius on elements such as inputs and buttons. Simultaneously, we're removing explicit legacy large border-radius from core.

UX: new default border radius

---

plugins/automation/admin/assets/javascripts/admin/components/placeholders-list.gjs
plugins/automation/config/locales/client.en.yml
plugins/automation/config/locales/server.en.yml
plugins/automation/lib/discourse_automation/scripts.rb
plugins/automation/lib/discourse_automation/scripts/topic.rb
plugins/automation/plugin.rb
plugins/automation/spec/scripts/topic_spec.rb

This PR adds a new automation script for creating topics. It's very similar to the existing 'create a post' automation, except that it posts new topics in a specific category and with optional tags.
Screenshot:

FEATURE: Add 'Create topic' automation script

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/types/enum.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs
lib/theme_settings_object_validator.rb
spec/lib/theme_settings_object_validator_spec.rb

This commit changes enum typed theme objects property to be optional.
Previously, an enum typed property is always required but we have found
that this might not be ideal so we want to change it.

DEV: Allow enum typed theme objects property to be optional

---

app/assets/javascripts/discourse/app/components/modal/bookmark.js
spec/system/bookmarks_spec.rb
spec/system/page_objects/pages/topic.rb

When choosing the "Custom..." option in the new bookmark
menu and then choosing a date + time in the modal for the
reminder, the bookmark icon on the post was not updating to
show the one with the clock to indicate the reminder.
This was just a data syncing issue between BookmarkFormData
and what the modal sets. Ideally all this would be refactored
because the data flow is messy...but hard to find time for
that right now.
Followup 67a8080e338aa62afbd02efc98178b4a67751775

FIX: Bookmark clock icon not showing

---

app/assets/javascripts/discourse/app/lib/cookie.js

Chrome's default is already Lax, so this change is a no-op there.
Firefox will soon be follow them, and has started warning about cookies with no samesite attribute. That's the motivation for this commit.

DEV: Set `samesite=lax` on cookies set by client-side

---

plugins/checklist/assets/stylesheets/checklist.scss

1. Fixes alignment of checkboxes in posts (they now sit higher on the text line and toggling no longer results in a content shift)
2. Removes unused styles
Before / After

UX: Tweak the checklist plugin css

---

app/assets/javascripts/discourse/app/templates/users.hbs
config/locales/client.en.yml

Admins and mods
Not admins or mods

UX: Display JIT when user list is empty

---

plugins/checklist/assets/stylesheets/checklist.scss

regressed in 6cf7447cb90b0ca632747d56ca2f5f0eed06d15c
Before / Bugged / After

FIX: Nested list checkboxes css

---

app/assets/javascripts/discourse/app/lib/user-status-message.js
app/assets/stylesheets/common/components/user-status-message.scss

FIX: Add the ident to fix user status styling in posts

---

app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/components/header/hamburger-dropdown-wrapper.gjs
app/assets/javascripts/discourse/app/components/header/user-dropdown/user-status-bubble.gjs
app/assets/javascripts/discourse/app/controllers/application.js
app/assets/javascripts/discourse/app/instance-initializers/narrow-desktop.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/modifiers/close-on-click-outside.js
app/assets/javascripts/discourse/app/services/header.js
app/assets/javascripts/discourse/app/templates/application.hbs
app/assets/javascripts/discourse/tests/acceptance/do-not-disturb-test.js
app/assets/javascripts/discourse/tests/acceptance/edit-notification-click-test.js
app/assets/javascripts/discourse/tests/acceptance/header-api-test.gjs
app/assets/javascripts/discourse/tests/acceptance/mobile-pan-test.js
app/assets/javascripts/discourse/tests/acceptance/search-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-user-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-narrow-desktop-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-test.js
app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
app/assets/javascripts/discourse/tests/acceptance/user-status-test.js
app/assets/javascripts/pretty-text/addon/emoji.js
app/models/user.rb
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/site_settings.yml
spec/system/header_spec.rb

This will automatically enable the glimmer header when all installed themes/plugins are ready. This replaces the old group-based site setting.
In 'auto' mode, we check for calls to deprecated APIs (e.g. decorateWidget) which affect the old header. If any are present, we stick to the old header implementation and print a message to the console alongside the normal deprecation messages.
To override this automatic behavior, a new `glimmer_header_mode` site setting can be set to 'disabled' or 'enabled'.
This change also means that our test suite is running with the glimmer header. This unveiled a couple of small issues (e.g. some incorrect `aria-*` and `alt` text) which are now fixed. A number of selectors had to be updated to ensure the tests were clicking the actual `<button>` elements …

DEV: Introduce default 'auto' mode for glimmer header

---

app/jobs/regular/enable_bootstrap_mode.rb
app/jobs/scheduled/disable_bootstrap_mode.rb
spec/jobs/disable_bootstrap_mode_spec.rb
spec/jobs/enable_bootstrap_mode_spec.rb
spec/requests/api/notifications_spec.rb
spec/requests/categories_controller_spec.rb

Previously, when the new site was created and after the first admin login, no one will receive notifications to review the user approval queue since only the moderators would receive the PMs about it. Also, this PR will change the "pending_users_reminder_delay_minutes" site setting to 5 minutes while the site is in bootstrap mode.

UX: make first admin a moderator to review user approvals.

---

plugins/chat/app/models/chat/message.rb
plugins/chat/assets/javascripts/lib/discourse-markdown/chat-html-block.js
plugins/chat/assets/javascripts/lib/discourse-markdown/chat-html-inline.js
plugins/chat/spec/lib/chat/pretty_text_spec.rb

This commit adds two custom markdown rules:
- chat-html-block
- chat-html-inline
For now it only allows `<kbd>` for inline and `<details>` for block.

DEV: allows chat to render specific html tags

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/types/categories.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-theme-setting/editor-test.gjs

This commit changes the identifier displayed in the navigation tree of
the theme objects editor from the generic "category 1" to "<category
name>, <category 2 name>" when a property of typed categories is set as
the identifier.
Example:
For the following theme objects schema:
```
some_setting:
type: objects
default: []
schema:
name: <some scheme name>
identifier: list_of_categories
properties:
list_of_categories:
type: categories
```
If the `list_of_categories` property's value has been set to `category
1` and `category 2`, the navigation tree will display `category 1,
category 2` as the text to represent the object in the navigation tree.
https://github.com/discourse/discourse/assets/4335742/39781b04-c44e-4b19-9dfe-073209999dd4

UX: Improve the identifier for categories typed prop in theme objects editor

---

lib/tasks/import.rake
script/bulk_import/generic_bulk.rb

This SQL tries to insert as much data as possible into the `user_stats` table by either calculating or by approximating stats based on existing. It also fixes an error in the calculation of `reply_count`which mistakenly contained all posts, not just replies.
This change also disables some steps in the `import:ensure_consistency` rake task by setting the `SKIP_USER_STATS` env variable. Otherwise, the rake task will overwrite the calculated data in the `user_stats` table with inaccurate data. I'm not changing or removing the logic from the rake task yet because other bulk import scripts seem to depend on it.

DEV: Import script should insert more data into `user_stats` table

---

plugins/chat/app/models/chat/mention.rb
plugins/chat/db/post_migrate/20240408140000_drop_notification_id_from_chat_mentions.rb

We ignore this column since fbd24fa6.

DEV: Drop chat_mention.notification_id column

---

plugins/chat/app/models/chat/mention.rb
plugins/chat/db/post_migrate/20240410130000_drop_user_id_from_chat_mentions.rb

This column is ignored since 62f423da.

DEV: Drop user_id from chat_mentions

---

app/assets/javascripts/discourse/app/lib/notification-types/linked-consolidated.js
app/assets/javascripts/discourse/app/models/user-action.js
app/assets/javascripts/discourse/app/routes/app-route-map.js
app/assets/javascripts/discourse/app/routes/user-notifications-links.js
app/assets/javascripts/discourse/app/templates/user/notifications.hbs
app/assets/javascripts/discourse/tests/unit/lib/notification-types/linked-consolidated-test.js
app/models/user_action.rb
app/services/user_action_manager.rb
config/locales/client.en.yml

This change creates a new user notifications page for showing your posts
that have been linked to.
This page is also needed for consolidated link notifications so that
when you click on the notification it will take you to this new page
showing you the link notifications from a specific user.
Follow up to: 72ac675e4ed498d4a961470358b7f807fa7f4a36

FEATURE: User Notifications Links Page

---

plugins/poll/plugin.rb
plugins/poll/spec/lib/polls_updater_spec.rb

When `poll_enabled` is `true` (default is `true`), and a user attempts to update a post, the update **always** goes through the `PollsUpdater` even though the user has never created a poll, nor is removing an existing poll.
This is a problem because the PollUpdater includes a `post.save_custom_fields`, and it errors out, hiding the real problem when a user attempts to save a post that is invalid.
This PR prevents the PollUpdater from getting invoked if there are no polls at all getting created or already created.
Here's the erroneous message which is shown when there are no polls involved
```
activerecord (7.0.8.1) lib/active_record/validations.rb:80:in `raise_validation_error'
app/models/concerns/has_custom_fields.rb:286:in `save_custom_fields'
plugins/poll/lib/polls_updater.rb:110:in …
```

DEV: Do not attempt to update polls if there are no polls before and after edit

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-default-toast-test.js
app/assets/javascripts/float-kit/addon/lib/constants.js

This change disables the toast notification progress bar by default. It can be enabled for a specific toast by setting `autoClose: true` (it is true by default) and also `showProgressBar: true`.

DEV: set toast progress bar to false by default

---

app/assets/stylesheets/common/float-kit/d-toasts.scss

This change prevents toast notifications from blocking the header and user navigation on both desktop and mobile.
Mobile (after change):
Desktop (after change):

UX: prevent toasts from covering header

---

plugins/chat/assets/javascripts/discourse/components/chat-message-actions-mobile.gjs

Prior to this fix we were calling the action before closing the menu which could cause various callbacks, like the enable body scroll one, to not be called as some actions will do: `chat.activeMessage = null;` causing the message actions menu to be instantly destroyed.

FIX: ensures reply is unlocking body scroll

---

app/assets/stylesheets/common/base/sidebar-section-link.scss
plugins/chat/assets/stylesheets/common/chat-channel-name.scss
plugins/chat/assets/stylesheets/common/chat-message-info.scss
plugins/chat/assets/stylesheets/common/sidebar-extensions.scss

Before / After
Sidebar
Sidebar
Sidebar user status
Header
Message

UX: Emoji alignment fixes, followup to #26491

---

app/assets/javascripts/discourse/app/components/bread-crumbs.js
app/controllers/categories_controller.rb

The breadcrumbs were updated everytime there were changes to the categories which was not efficient and caused unnecessary rerendering of the CategoryDrop elements when "lazy load categories" is enabled.
This commit also ensures that all category fields are serialized for ancestors too for the categories#search endpoint.

FIX: Update category breadcrumbs more reliably

---

app/mailers/user_notifications.rb
spec/mailers/user_notifications_spec.rb

See https://meta.discourse.org/t/invalid-user-timezone-jams-up-their-mail/303306
This ensures that "account silenced" and "account suspended" emails don't fail to send if the user has an invalid timezone.

FIX: Ensure invalid timezone does not block critical emails

---

app/assets/javascripts/discourse/app/controllers/group.js
app/assets/javascripts/discourse/app/templates/group.hbs
spec/system/groups/group_spec.rb
spec/system/page_objects/pages/group.rb

The issue was that we were returning the transition as a result to the `then`. The fix was just to add `{ }`  for this to not be interpreted as an implicit return.

FIX: deleting a groups was throwing an error

---

app/models/post.rb
app/models/upload_reference.rb
spec/integration/secure_uploads_spec.rb
spec/lib/post_revisor_spec.rb
spec/models/post_spec.rb

This reverts commit cdc8e9de1b8d269b7d1704b210462276042a8a38.
It's made things worse internally and on meta.

Revert "FIX: Post uploads setting access_control_post_id unnecessarily (#26627)"

---

app/assets/javascripts/discourse/app/controllers/topic.js
spec/system/composer/discard_draft_spec.rb
spec/system/page_objects/components/composer.rb
spec/system/page_objects/modals/discard_draft.rb
spec/system/page_objects/pages/topic.rb

This commit will now change two behaviors:
- If composer is already opened on a specific post and we click on edit again for the same post, we will do nothing and not show the discard draft modal
- if composer is shrinked and we click on edit for the same currently edited post, we will just open the composer and not show the discard draft modal

FIX: prevents showing discard modal on re-edit

---

app/services/user_merger.rb
config/locales/server.en.yml
spec/fabricators/user_associated_account_fabricator.rb
spec/services/user_merger_spec.rb

When merging users from /admin/users/:user_id, we currently don't merge user_associated_accounts. Sometimes this could lock users out of their accounts if local_logins are disabled, and the secondary email is tied to the main account.
This PR ensures user_associated_accounts are merged, and on conflict
- keeps the target_user's associated account
- sets user_id: nil for the source_user's conflicted user_associated_account

FEATURE: Merge user associated accounts

---

app/assets/javascripts/discourse/app/controllers/topic.js
app/assets/javascripts/discourse/app/services/composer.js

Prior to this fix we were manually expanding the composer but not setting the correct height. This commit adds a new `unshrink` function on the composer service to correctly set the state and the height on the composer model.

FIX: correctly unshrink composer when re-editing post

---

plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/config/locales/client.en.yml
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/user_updated.rb
plugins/automation/plugin.rb
plugins/automation/spec/models/automation_spec.rb
plugins/automation/spec/triggers/user_updated_spec.rb

This PR adds a new option to the `user_updated` trigger of the automation plugin to only trigger an automation for new users that join after the automation is enabled.
Screenshot:

FEATURE: Add 'New users only' option to user_updated trigger

---

app/assets/javascripts/discourse/app/components/choose-topic.hbs
app/assets/javascripts/discourse/app/components/topic-category.hbs
app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/select-kit/addon/components/topic-row.hbs

We want to remove uses of Category.findById. This change pushes the fetching up the chain of responsibility.

DEV: Always pass ancestors to category-link

---

app/assets/javascripts/discourse/app/widgets/render-glimmer.js

Decorators in object literals are non-standard, and we're working to remove them.

DEV: Avoid using `@tracked` as a decorator in RenderGlimmer object literal

---

app/controllers/categories_controller.rb
spec/requests/categories_controller_spec.rb
spec/system/editing_sidebar_categories_navigation_spec.rb

Full text search does not return ideal results for category dropdown. Usually, in category dropdowns we want to search for categories as we type. For example, while typing "theme", the dropdown should show intermediary results for "t", "th", "the", "them" and finally "theme". For some of these substrings (like "the"), full text search does not return any results, which leads to an unpleasant user experience.

FIX: Use ILIKE for searching categories

---

app/assets/javascripts/discourse/app/routes/user-activity-bookmarks.js
app/models/user_bookmark_list.rb
app/serializers/user_bookmark_list_serializer.rb
app/services/post_bookmarkable.rb
app/services/topic_bookmarkable.rb
spec/serializers/user_bookmark_list_serializer_spec.rb

This is necessary when "lazy load categories" feature is enabled to make sure the categories are rendered for topics and posts.

FIX: Serialize categories for bookmarks

---

app/assets/javascripts/discourse/app/lib/search.js

This 'category' variable isn't a serialized category - at least when doing a category/tag search.

FIX: Don't put non-category in Site.categories

---

app/assets/stylesheets/common/base/header.scss

This doesn't change anything in 99.9% of cases - by default d-header has only one child element `.wrap`.
There are only two themes that I'm aware of that add another child:
1. discourse-categories-navbar - which I'm currently updating to use the new header APIs, and where the column layout makes more sense
2. a private theme, which was recently updated to use those APIs and that works around the current layout by applying `flex-wrap: wrap` to d-header (I'll remove that override as it conflicts with this change)

DEV: Apply `flex-direction: column` on `.d-header`

---

app/assets/javascripts/discourse/app/services/composer.js

Currently when you minimize the composer, the `--composer-height` value is set to `40px` — when reopening a draft, this value isn't reset, so the resumed composer is quite short. This resets the `--composer-height` to the last known height. 
Before:
https://github.com/discourse/discourse/assets/1681963/e19eb854-d08f-4bf4-8cb1-d72efbffe539
After:
https://github.com/discourse/discourse/assets/1681963/4560dbae-fdad-4c69-90e1-549642ccafc7

UX: when reopening collapsed composer, reset height

---

app/assets/javascripts/admin/addon/components/site-settings/group-list.hbs
app/assets/javascripts/discourse/tests/integration/components/group-list-setting-test.js
app/assets/javascripts/select-kit/addon/components/multi-select.hbs
app/assets/javascripts/select-kit/addon/components/selected-choice.hbs
app/assets/javascripts/select-kit/addon/components/selected-choice.js
app/assets/stylesheets/common/select-kit/multi-select.scss
app/services/site_settings_task.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
lib/guardian.rb
lib/site_setting_extension.rb
spec/lib/guardian_spec.rb
spec/lib/site_setting_extension_spec.rb
spec/requests/admin/site_settings_controller_spec.rb

Automatically add `moderators` and `admins` auto groups to specific site settings.
In the new group-based permissions systems, we just want to check the user’s groups since it more accurately reflects reality
Demo
Affected settings:
- tag_topic_allowed_groups
- create_tag_allowed_groups
- send_email_messages_allowed_groups
- personal_message_enabled_groups
- here_mention_allowed_groups
- approve_unless_allowed_groups
- approve_new_topics_unless_allowed_groups
- skip_review_media_groups
- email_in_allowed_groups
- create_topic_allowed_groups
- edit_wiki_post_allowed_groups
- edit_post_allowed_groups
- self_wiki_allowed_groups
- flag_post_allowed_groups
- post_links_allowed_groups
- embedded_media_post_allowed_groups
- profile_background_allowed_groups
- user_card_background_allowed_groups …

FEATURE: mandatory fields for group site setting

---

app/models/user.rb
spec/models/user_spec.rb

In a previous PR, we skipped users deactivated by admins from being automatically purged - https://github.com/discourse/discourse/pull/26478.
However, users deactivated by `discourse-auto-deactivate` plugin are deactivated by the system user. Those users should not be purged as well.
https://github.com/discourse/discourse-auto-deactivate/blob/main/plugin.rb#L62

FIX: don't purge users who were deactivated by the system

---

app/mailers/user_notifications.rb
lib/email/message_builder.rb
lib/email/sender.rb
spec/lib/email/sender_spec.rb
spec/mailers/user_notifications_spec.rb

For e-mails, secure uploads redacts all secure images, and later uses the access control post to re-attached allowed ones. We pass the ID of this post through the `X-Discourse-Post-Id` header. As the name suggests, this assumes there's only ever one access control post. This is not true for activity summary e-mails, as they summarize across posts.
Add a new header, `X-Discourse-Post-Ids`, which is used the same way as the old header, but also works for the case where an e-mail is associated with multiple posts.

FIX: Correctly re-attach allowed images in activity summary e-mail

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.js
app/assets/javascripts/discourse/app/lib/topic-bookmark-manager.js
app/assets/javascripts/discourse/app/widgets/bookmark-menu.js
app/assets/javascripts/float-kit/addon/components/d-menu.gjs
spec/system/bookmarks_spec.rb
spec/system/page_objects/pages/topic.rb

Followup to 67a8080e338aa62afbd02efc98178b4a67751775
This commit makes it so the topic footer button for bookmarks
uses the new BookmarkMenu component, and makes some tweaks to
that component to allow for a label and CSS class options.
Also introduces a TopicBookmarkManager to manage the saving/editing/
deleting of the topic level bookmarks and the reactivity that happens
in the topic UI afterward.
Next commit should rip out old bookmark associated code in the
topic controller as it will no longer be needed.

FEATURE: Use new bookmark menu in topic footer buttons

---

lib/svg_sprite.rb

they are used since https://github.com/discourse/discourse/pull/26047 and were causing warnings

DEV: Add missing svg icons to the svg_sprite list

---

plugins/chat/app/views/user_notifications/chat_summary.html.erb

Reported here: https://meta.discourse.org/t/chat-email-notification-uses-hard-coded-text-color-in-title-but-not-in-background/304299
Since this section uses `@header_bgcolor` for the background, the text should dynamically update with `@header_color` to avoid situations where the text matches the background

UX: update to variable text color for variable background

---

app/assets/javascripts/admin/addon/components/admin-site-settings-filter-controls.gjs
app/assets/javascripts/admin/addon/routes/admin-users-list-show.js
app/assets/javascripts/discourse/app/components/sidebar/filter-no-results.gjs
config/locales/client.en.yml
spec/system/admin_sidebar_navigation_spec.rb

When the user sees no results in their admin sidebar query,
we are adding two additional links:
* "Search site settings" - Navigates to the site settings page
with the filter prefilled in the search
* "Admin user list" - Navigates to the user list with the filter
prefilled in the username search
This will bridge the gap until we have a full admin-wide search.

FEATURE: Show additional filter links in admin sidebar for no results

---

app/assets/stylesheets/common/base/user.scss

UX: Keep input headings consistently bold

---

Gemfile
Gemfile.lock

Ok.
There was an initializer introduced in discourse/discourse#11088
```
Rack::MiniProfiler.counter_method(Redis::Client, :call) { 'redis' }
```
This now throws an error
```
gems/rack-mini-profiler-3.3.1/lib/mini_profiler/profiling_methods.rb:87:
in alias_method': undefined method call' for class `Redis::Client'
```
The error states that the method `def call` is no longer defined for `Redis::Client`. Which is accurate since that method was dropped in 5.0 via https://github.com/redis/redis-rb/commit/349ddb1daeed0ef1ee6e8a521238705ced010f27 ( redis/redis-rb#1120 )
This change ensures a known redis api
Other options are to change the interface used by discourse and `gem "redis", "> 5.0"`
/via https://github.com/MiniProfiler/rack-mini-profiler/issues/610
I currently do not use discourse, so …

Peg redis client to 4.0

---

app/models/post_timing.rb
app/models/topic_user.rb
spec/models/post_timing_spec.rb
spec/models/topic_user_spec.rb
spec/requests/topics_controller_spec.rb

This ensures we only ever store correct post and topic timing when the client
notifies.
Previous to this change we would blindly trust the client.
Additionally this has error correction code that will correct the last seen
post number when you visit a topic with incorrect timings.

FIX: disable storing invalid post and topic timing when sent from client

---

plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/lib/discourse_automation/triggers/point_in_time.rb
plugins/automation/lib/discourse_automation/triggers/recurring.rb
plugins/automation/spec/triggers/point_in_time_spec.rb
plugins/automation/spec/triggers/recurring_spec.rb

Prior to this fix, any change to an automation would reset `pending_automations`, now we only do it if any value related to recurrence (start_date, interval, frequency, execute_at...) has been changed.
It means that any trigger creating `pending_automations` now needs to manage them in the `on_update` callback.

FIX: resets pending automations only if necessary

---

app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show.js
app/assets/javascripts/admin/addon/routes/admin-customize-themes-show.js
app/controllers/admin/themes_controller.rb
spec/system/admin_customize_themes_spec.rb

Before, the theme translations picker value was set to the site's default locale, which mismatches from the user's locale.
This commit changes the picker value to the user locale.
relates to https://meta.discourse.org/t/locale-mismatch-at-theme-translations/302879
<details>
<summary>Before</summary>
_You can see in the left-right corner that the picker is not consistent_
</details>
<details>
<summary>Now</summary>
</details>
> [!NOTE]
> Is there a better way to get the user's locale session? I used ruby [I18n.locale](https://github.com/discourse/discourse/blob/a45b2b1124e71a1d9fd8af2b53f69efdf5dba2af/app/assets/javascripts/admin/addon/routes/admin-customize-themes-show.js#L44) for [consistency](https://stackoverflow.com/questions/673905/how-can-i-determine-a-users-locale-within-the-browser …

FIX: Locale mismatch at theme translations picker

---

app/services/email_settings_validator.rb
lib/tasks/emails.rake

net-smtp 0.5.0 bails when authentication is set without username/password
followup-to: 7b8d60dc, 897be759

FIX: in EmailSettingsValidator, unset smtp authentication when there's no user and password

---

plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs

Prior to this fix, the debounced update last read call, might be cancelled when exiting the channel. We now ensure we make one last attempt at updating last read state when exiting a channel.
Note this commit also attempts to optimise the fold detection by starting from bottom and stopping on first hit.

FIX: ensures last read is updated on exit

---

plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs

This is reverting part of https://github.com/discourse/discourse/commit/08ff0bac297dede8144f83a0b0aa3fc530943bcf to only have the call on exit channel. This was causing incorrect unread update. I will refactor this in another commit.

FIX: messages are already reversed

---

app/assets/stylesheets/common/base/topic-summary.scss
app/assets/stylesheets/desktop/topic-post.scss
app/assets/stylesheets/mobile/topic-post.scss

There's some left margin on the top replies button to distance it from the AI summary button, but this creates a misalignment when the AI summary is disabled. 
Switching to flex gap here means the space will only be applied when both buttons are present. 
Before
After

UX: use flex gap to space topic map summary buttons

---

app/assets/javascripts/discourse/app/components/topic-list-item.js
app/assets/stylesheets/common/base/_topic-list.scss

Previously, we had two styles for selected/focused topic in the topic list. This was most noticeable when using the bulk select feature:
focus state (when returning to the list from a topic, the topic is marked as focused)
selected (when using keyboard navigation)
This change makes it so that both states look like the second screenshot. It's more consistent, and avoids the selected line hugging the text.

UX: Fix styling for focused row

---

app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.hbs
app/assets/javascripts/discourse/app/components/bootstrap-mode-notice.js
app/assets/javascripts/discourse/app/templates/wizard/step.gjs
app/models/user.rb
config/locales/client.en.yml
db/migrate/20240422015830_remove_admin_guide_tooltip_from_seen_popups.rb
docs/ADMIN-QUICK-START-GUIDE.md
spec/requests/api/schemas/json/site_response.json
spec/system/page_objects/pages/wizard.rb
spec/system/user_tips_spec.rb
spec/system/wizard_spec.rb

After the wizard is completed, the admin should be redirected to the admin guide topic.
Also tooltip from "Getting started" button was removed.
https://github.com/discourse/discourse/assets/72780/acb4705c-bd06-40fc-912f-73315bc183c8

FEATURE: after wizard admin is redirected to the guide page

---

app/assets/javascripts/discourse/app/lib/highlight-syntax.js
app/assets/javascripts/discourse/tests/integration/components/highlighted-code-test.js

Meta: https://meta.discourse.org/t/automatic-code-highlighting-broken-in-fullscreen-code-view/304879
This PR fixes the code highlighting not applied in the fullscreen modal.
A `lang-auto` classname name is added to the  `<code>` element when no language is provided.
The library highlight.js can then guess the language.
If found,  `lang-auto` is removed, and a `language-<name>` class name is added (from the library).
After clicking on fullscreen, the current element classnames are used in the modal template (see [here](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/lib/codeblock-buttons.js#L171-L176)).
Because no `lang-<name>` class name exists, the `lang` variable is always _undefined_, resulting in the highlighting being skipped.
The …

FIX: Automatic code highlighting not applied in fullscreen modal

---

app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs

All the other buttons here have this class, and without it styling may vary in undesired ways.

UX: bookmark button in topic footer should have btn-default class

---

config/site_settings.yml

This commit adds the most common AI bot crawlers seen
on our hosting (claudebot, gptbot, anthropic-ai, brightbot)
to our `slow_down_crawler_user_agents` and `crawler_user_agents`
site settings by default.
This means these AI bots will be rate limited by default instead
of site admins having to remember to do it for themselves.

FEATURE: Rate limit common AI bots crawlers by default

---

app/assets/javascripts/admin/addon/services/admin-sidebar-state-manager.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
spec/system/admin_sidebar_navigation_spec.rb

Include themes and component keywords to make the filter more accurate.
https://github.com/discourse/discourse/assets/72780/4f4d4ff7-c2fe-4169-9f2b-f140e03c62c8

FEATURE: include themes and components keywords to the admin sidebar

---

config/routes.rb
spec/requests/admin/themes_controller_spec.rb

This commit fixes a bug where the server returns a 404 response code if
a user visits the URL to edit a objects type theme setting directly.

FIX: 404 when visiting theme setting objects editor for theme component

---

app/controllers/application_controller.rb
config/initializers/200-first_middlewares.rb
lib/middleware/discourse_public_exceptions.rb
lib/read_only_mixin.rb
spec/rails_helper.rb
spec/system/bootstrap_error_pages_spec.rb
spec/system/content_security_policy_spec.rb

- Run the CSP-nonce-related middlewares on the generated response
- Fix the readonly mode checking to avoid empty strings being passed (the `check_readonly_mode` before_action will not execute in the case of these re-dispatched exceptions)
- Move the BlockRequestsMiddleware cookie-setting to the middleware, so that it is included even for unusual HTML responses like these exceptions

FIX: Improve handling of 'PublicExceptions' when bootstrap_error_pages enabled

---

app/assets/javascripts/discourse/app/templates/topic.hbs

Using this for an experimental component, `this.model.postStream.loadingFilter` can be used to show/hide the outlet's content when the topic is loading

DEV: add topic-area-bottom plugin outlet

---

app/assets/javascripts/discourse/app/controllers/email-login.js
app/assets/javascripts/discourse/app/routes/email-login.js
app/assets/javascripts/discourse/tests/acceptance/modal/login/login-with-email-and-2fa-test.js

The `secondFactorMethod` property is defined as a `@discourseComputed` which means it can't be overridden. Yet, we do override it in `app/assets/javascripts/discourse/app/components/security-key-form.js` and `app/assets/javascripts/discourse/app/components/second-factor-form.js` by doing `this.set("secondFactorMethod", ...)`.
This commit sets a default property `secondFactorMethod` on the `email-login` controller after the model has been loaded. Given this property is no longer computed, it can be set again at other places.
Followups:
- Ideally we would follow DDAU pattern but this is quite a significant refactor.
- The test I added is very limited, ideally we should start writing system specs for this, but it means having to deal with the email, it's a significant work.

FIX: prevents error due to property override

---

app/assets/javascripts/float-kit/addon/lib/constants.js

`<DMenu @inline={{true}} ...>...</DMenu>` will render the body relative to the trigger instead of rendering it in a portal.

DEV: supports inline for d-menu

---

app/controllers/admin/api_controller.rb
app/serializers/basic_api_key_serializer.rb

For better performances when listing all the API keys.
Loading all the "api key scopes" is slow and not required when showing the list of all the api keys.

PERF: introduce a basic api key serializer

---

app/assets/javascripts/admin/addon/components/modal/uploaded-image-list.hbs
app/assets/javascripts/admin/addon/components/modal/uploaded-image-list.js
app/assets/stylesheets/common/base/user.scss
app/controllers/admin/site_settings_controller.rb
spec/requests/admin/site_settings_controller_spec.rb

Fixes two issues:
- frontend was reloading the page when clicking-to-remove avatar
- backend wasn't allowing resetting the setting by deleting all avatars

FIX: Allow deleting avatars from the selectable avatars setting

---

lib/tasks/themes.rake

This is essential for us to determine which site is encountering an
error while updating remote themes. We are also including the theme's id
because themes can have the same name.

DEV: Add site's DB name in `themes:update` rake task when printing error

---

app/assets/javascripts/discourse/app/instance-initializers/message-bus.js
app/assets/javascripts/discourse/app/instance-initializers/page-tracking.js
app/assets/javascripts/discourse/scripts/pageview.js
app/controllers/pageview_controller.rb
app/models/application_request.rb
app/models/concerns/reports/consolidated_page_views_browser_detection.rb
app/models/report.rb
app/views/exceptions/not_found.html.erb
app/views/layouts/no_ember.html.erb
app/views/layouts/publish.html.erb
config/initializers/004-message_bus.rb
config/locales/server.en.yml
config/routes.rb
lib/middleware/request_tracker.rb
spec/lib/middleware/request_tracker_spec.rb
spec/system/request_tracker_spec.rb

Our 'page_view_crawler' / 'page_view_anon' metrics are based purely on the User Agent sent by clients. This means that 'badly behaved' bots which are imitating real user agents are counted towards 'anon' page views.
This commit introduces a new method of tracking visitors. When an initial HTML request is made, we assume it is a 'non-browser' request (i.e. a bot). Then, once the JS application has booted, we notify the server to count it as a 'browser' request. This reliance on a JavaScript-capable browser matches up more closely to dedicated analytics systems like Google Analytics.
Existing data collection and graphs are unchanged. Data collected via the new technique is available in a new 'experimental' report.

FEATURE: Add experimental tracking of 'real browser' pageviews

---

plugins/chat/app/models/chat/message.rb
plugins/chat/app/models/chat/thread.rb
plugins/chat/app/serializers/chat/in_reply_to_serializer.rb
plugins/chat/app/serializers/chat/message_serializer.rb
plugins/chat/app/serializers/chat/thread_original_message_serializer.rb
plugins/chat/app/serializers/chat/thread_preview_serializer.rb
plugins/chat/app/services/chat/create_message.rb
plugins/chat/app/services/chat/update_message.rb
plugins/chat/db/migrate/20240422042830_add_excerpt_to_chat_messages.rb
plugins/chat/spec/integration/outgoing_web_hooks_spec.rb
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/spec/plugin_helper.rb
plugins/chat/spec/serializer/chat/chat_message_serializer_spec.rb
plugins/chat/spec/serializer/chat/in_reply_to_serializer_spec.rb
plugins/chat/spec/services/chat/create_message_spec.rb
plugins/chat/spec/services/chat/update_message_spec.rb
plugins/chat/spec/system/chat/composer/channel_spec.rb
plugins/chat/spec/system/chat_channel_spec.rb
plugins/chat/spec/system/chat_composer_draft_spec.rb
plugins/chat/spec/system/reply_to_message/smoke_spec.rb

This change moves the chat message excerpt into a new database column (string) on the chat_messages table.
As part of this change, we will now set the excerpt within the `Chat::CreateMessage` service, and update it within the `Chat::UpdateMessage` service.

PERF: Reduce overhead from chat message excerpt

---

lib/theme_settings_manager.rb
lib/theme_settings_manager/objects.rb
spec/services/theme_settings_migrations_runner_spec.rb

This PR fixes a bug in theme settings migrations where values of `objects` typed theme settings aren't passed to migrations even when there are overriding values for those settings. What causes this bug is that, when creating the hash that contains all the overridden settings and will be passed to migrations, the values of `objects` typed settings are incorrectly retrieved from the `value` column (which is always nil for `objects` type) instead of `json_value`. `objects` settings are different from all other types in that they store their values in the `json_value` column and they need to be special-cased when retrieving their values.

FIX: Pass values of `objects` typed settings to theme migrations

---

app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/tests/fixtures/site-fixtures.js
app/assets/javascripts/select-kit/addon/components/category-row.gjs
app/assets/javascripts/select-kit/addon/components/category-selector.js
app/controllers/categories_controller.rb
app/models/category.rb
app/serializers/basic_category_serializer.rb
spec/requests/api/schemas/json/category_create_response.json
spec/requests/api/schemas/json/category_list_response.json
spec/requests/api/schemas/json/category_update_response.json
spec/requests/api/schemas/json/site_response.json
spec/requests/categories_controller_spec.rb

Selecting the +subcategories option does not work sometimes when "lazy load categories" is enabled because the subcategories may not be fetched. This ensures that subcategories are loaded by requesting them before being used.

FIX: Fetch categories for "+subcategories" option

---

plugins/chat/app/models/chat/channel.rb
plugins/chat/db/post_migrate/20240425133407_drop_chat_channels_last_message_sent_at.rb

chat_channels - last_message_sent_at
This column has been marked as ignored for a year.

DEV: drop ignored columns

---

plugins/checklist/assets/javascripts/discourse/initializers/checklist.js

This fixes the UX when clicking a checklist item to toggle its state.
**Before**
**After**

UX: loading spinner when clicking an item

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

e05628c0 introduced an optimization to remove basic-HTML content for authenticated users. The assumption is that, if they were able to log in, they must have a JS capable browser and do not need the basic HTML.
However, there are use-cases where an API-key is used to crawl a private site, or private categories of a public site. This commit re-enables those use cases by keeping the basic-html in place for crawler/bot user agents.

FIX: Include HTML content for authenticated users with crawler UA

---

plugins/chat/app/models/chat/null_message.rb
plugins/chat/app/serializers/chat/thread_original_message_serializer.rb
plugins/chat/app/serializers/chat/thread_preview_serializer.rb
plugins/chat/spec/models/chat/null_message_spec.rb
plugins/chat/spec/system/message_thread_indicator_spec.rb
plugins/chat/spec/system/thread_list/full_page_spec.rb

Follow up to #26712 to account for older threads that don't have a persisted excerpt, as this was previously generated on every page load.
This change allows us to build the excerpt on the fly when none exists, fixing the issue of missing message excerpts for thread previews (within channel) and thread lists (on mobile/desktop).

FIX: build chat message excerpt for thread preview

---

app/assets/javascripts/discourse/app/components/time-shortcut-picker.hbs
spec/system/bookmarks_spec.rb
spec/system/page_objects/modals/bookmark.rb

A change in relative picker was causing a serie of events which ultimately would cause the whole list of time options to be reset and re-rendered which would cause a new instance of the picker to be created, causing a reset.
The fix is using id in the each loop to help ember identify that it doesn’t have to re-render a specific component.

FIX: relative picker was being reset on change

---

plugins/chat/app/services/chat/publisher.rb
plugins/chat/assets/javascripts/discourse/components/user-threads/index.gjs
plugins/chat/assets/javascripts/discourse/models/chat-thread-preview.js
plugins/chat/assets/javascripts/discourse/services/chat-subscriptions-manager.js
plugins/chat/spec/system/reply_to_message/smoke_spec.rb
plugins/chat/spec/system/user_threads_spec.rb

That could cause flakeyness in specs depending in which timing message bus would arrive and it's not necessary as it should be update with `handleThreadOriginalMessageUpdate`.

FIX: do not increment reply count manually

---

lib/plugin/instance.rb
lib/topics_filter.rb
spec/lib/topics_filter_spec.rb

Those can be used in the /filter routes.

DEV: add support for adding custom status filter

---

plugins/automation/lib/discourse_automation/triggers/recurring.rb
plugins/automation/spec/triggers/recurring_spec.rb

This case is not supposed to happen but it seems safer to ensure this case will recreate pending automations.

FIX: ensures we don't exit without pending automations

---

plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs
plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/assets/javascripts/discourse/helpers/first-visible-message-id.js
plugins/chat/assets/javascripts/discourse/modifiers/chat/scrollable-list.js
plugins/chat/spec/system/update_last_read_spec.rb

In a recent commit we moved the computation of last read id into the scroll events, however, we disable scroll events when scroll happens through a new received messages, meaning that we wouldn't update last read in this case even if we should when you are at the bottom of the channel.
This commit now synchronously check the first visible message on `updateLastRead` which should ensure it's always correct.
Few tests have been added to test this behavior, and the visibility check has been extracted to a helper.

FIX: ensures last read is updated on new message

---

app/assets/javascripts/discourse/app/helpers/concat-class.js
app/assets/javascripts/discourse/tests/integration/helpers/concat-class-test.js

RFC
It'd be useful in cases like:
```gjs
get flagNames() {
return this.flags?.map((flag) => flag && `flag-${flag.name}`);
// w/o this change you'd have to handle it here:
// return this.flags?.map((flag) => flag && `flag-${flag.name}`).filter(Boolean).join(" ");
}
<template>
<span class={{concatClass "gadget" this.flagNames}}>
{{! …or here: }}
<span class={{concatClass "gadget" (concatClass this.flagNames)}}>
```
(also: replaces ember's `compact()` with `filter(Boolean)`)

DEV: Add support for arrays to concatClass

---

config/discourse_defaults.conf

Test coverage is omitted because I only changed a comment. The correct procedure is clearly to _prepend_ `DISCOURSE_` to the setting name, as shown in the example. Appending would result in nonsensical environment variable names like `DB_HOSTDISCOURSE_`.

fix: confusing comment

---

spec/system/admin_customize_themes_spec.rb

Because spec is searching for "5", we need to be sure that "Cool theme 5" is created.

DEV: fix flaky admin_customize_themes spec

---

app/models/concerns/reports/consolidated_page_views_browser_detection.rb

In the "Consolidated Pageviews with Browser Detection (Experimental)"
report we used the same color for "Known Crawler" and "Other pageviews"
which makes the report confusing to look at, this commit makes them
different.

UX: Fix report color duplication

---

spec/lib/search_spec.rb

We should not be clearing **all** the advanced search filters and orders, because some are required by the application.

DEV: fix the fix for flakey test 😓

---

app/assets/stylesheets/common/admin/admin_revamp.scss

Make admin sidebar headings bold.
Admin screenshot
Original sidebar headers are untouched

UX: admin sidebar headings are bold

---

lib/email/receiver.rb
spec/lib/email/receiver_spec.rb

This is a follow up of https://github.com/discourse/discourse/commit/5fcb7c262ddfff0a8f0a08d0a8eb90a942122721
It was missing the case where secure uploads is enabled, which creates a copy of the upload no matter what. Thus creating a new Upload record even if the sha is already present in the table.
So this checks for the original_sha1 of the uploads as well when checking for duplicates.

FIX: prevent duplicate attachments in incoming emails - take 2

---

app/services/theme_settings_migrations_runner.rb
lib/theme_settings_object_validator.rb
lib/url_helper.rb
spec/lib/theme_settings_object_validator_spec.rb
spec/lib/url_helper_spec.rb
spec/services/theme_settings_migrations_runner_spec.rb

This commit adds a `isValidUrl` helper function to the context in
which theme migrations are ran in. This helper function is to make it
easier for theme developers to check if a string is a valid URL or path
when writing theme migrations. This can be helpful in cases when
migrating a string based setting to `type: objects` which contain `type:
string` properties with URL validations enabled.
This commit also introduces the `UrlHelper.is_valid_url?` method
which actually checks that the URL string is of the valid format instead of
only checking if the URL string is parsable which is what `UrlHelper.relaxed_parse` does
and is not sufficient for our needs.

DEV: Add `isValidUrl` helper function to theme migrations

---

app/assets/javascripts/discourse/app/components/user-menu/icon-avatar.gjs

Update avatars to 48x48 resolution from 24x24. This improves image quality without changing their display size, which remains fixed at 2em x 2em due to CSS settings.

UX: Use larger avatar size for user menu

---

plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/plugin.rb
plugins/automation/spec/integration/infinite_loop_protection_spec.rb
plugins/automation/spec/models/automation_spec.rb

It's currently possible to setup multiple automation rules that trigger each other resulting in an infinite loop. To prevent that, this PR adds a global "circuit breaker" that prevents all automations from triggering while an automation rule is executing.
Internal topic: t/124365.

FIX: Prevent infinite loop of automations triggering each other

---

db/migrate/20240430185434_fix_watched_words_without_action.rb

This defaults the action to
- Censor if there are no "replacement"
- Replace if there's a "replacement"
It also fixes the `WatchedWordGroups` action to the action of one of their `WatchedWords`
We unfortunately don't have enough data to restore to correct action, so use the one that is the least disruptive.
Follow up to https://github.com/discourse/discourse/commit/e7d0083dbe4ffe84a8d6645cde248d6a2beac155 which fixes an issue introduced in https://github.com/discourse/discourse/commit/143f06f2c600bc9aa94c4d64ca84cd9a06b75b9e.

FIX: Watched Words (+ Groups) with missing action

---

plugins/automation/app/jobs/scheduled/discourse_automation_tracker.rb
plugins/automation/spec/jobs/discourse_automation_tracker_spec.rb

Recurring automations are triggered by a scheduled job that runs every minute and checks for due automations, runs them and then marks as them as completed (by deleting the `PendingAutomation` record). However, the job is currently subject to a race condition where a recurring automation can be executed more than once at its due date if it takes more than a minute to finish.
This PR adds a mutex around the code that triggers the recurring automation so that no concurrent executions can happen for a single automation.
Meta topic: https://meta.discourse.org/t/daily-summary-9pm-utc/291850/119?u=osama.

FIX: Prevent race condition in recurring automations

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/components/d-float-body.gjs
app/assets/javascripts/float-kit/addon/lib/constants.js

(to be used by the glimmer replacement of topic-entrance component)

DEV: Add `autofocus` option to d-menu

---

plugins/chat/app/serializers/chat/in_reply_to_serializer.rb
plugins/chat/spec/serializer/chat/in_reply_to_serializer_spec.rb

This was missed from #26765, this fixes an issue of missing excerpts for older messages when threads are disabled for a chat channel and a user has already replied to an older message. We previously addressed this for new message replies but this is a separate case when the reply has been sent.

FIX: add excerpt fallback for chat message replies

---

app/controllers/categories_controller.rb
spec/requests/categories_controller_spec.rb

Otherwise, the results don't make sense if the number of categories is more than the limit provided.

FIX: Order categories in SQL for Categories#search

---

app/assets/javascripts/discourse/app/widgets/after-header-panel-outlet.js
app/assets/javascripts/discourse/app/widgets/header-contents.js

DEV: Backport `after-header-panel` plugin outlet to widget header

---

app/services/category_hashtag_data_source.rb

Instead of `LIKE`, use either `starts_with` or `position`. This way the term isn't interpreted as a pattern.

DEV: Use safer SQL functions for string queries in CategoryHashTagDataSource

---

spec/system/admin_sidebar_navigation_spec.rb

`within` is the devil, let's try this fix to
followup 79cccaf61fe5ab23f0305464919d03edeab33023
and prevent `Selenium::WebDriver::Error::StaleElementReferenceError`

DEV: Fix admin sidebar filter flaky

---

plugins/chat/app/models/chat/message.rb
plugins/chat/app/services/chat/create_message.rb
plugins/chat/app/services/chat/update_message.rb
plugins/chat/lib/chat_sdk/message.rb
plugins/chat/spec/lib/chat_sdk/message_spec.rb
plugins/chat/spec/services/chat/create_message_spec.rb
plugins/chat/spec/services/chat/update_message_spec.rb

The TextCleaner step has been moved from chat message’s validation to create_message/update_message services. It allows us to easily tweak part of its behavior depending on the needs.
For example we will now disable strip_whitespaces by default when streaming messages as we want to keep newlines and spaces at the end of the message.

DEV: allows to disable strip_whitespaces in messages

---

app/assets/javascripts/discourse/ember-cli-build.js
app/assets/javascripts/ember-cli-progress-ci/index.js
lib/tasks/assets.rake

- Use 'cheap-source-map' webpack config on low-memory machines
This results in worse quality sourcemaps in browser dev tools, but it significantly reduces memory use in our webpack build. In approximate local testing it drops from 1100mb to 590mb. This should make the rebuild process on low-memory machines much faster and less likely to trigger OOM errors.
In development, and on higher-memory machines, the higher-quality 'source-map' option is maintained.
- Disable Webpack's built-in `minimize` feature. Embroider already applies Terser after the webpack build is complete. There is no need to double-minimize the output.
- Update ember-cli-progress-ci to print to stderr instead of stdout. For some reason, pups (used by discourse_docker) buffers the stdout of commands and only prints when …

PERF: Improve production JS build in low-memory environments

---

plugins/chat/lib/chat/engine.rb

Followup to e949684fc54e629035b8883dabd9ef2916251da1, ref https://github.com/discourse/discourse-plugin-skeleton/pull/47

DEV: Update chat scheduled job loading to match skeleton

---

app/controllers/groups_controller.rb

... so that special characters in 'term' aren't interpreted by ILIKE.

DEV: Use safer SQL function for string queries when searching groups

---

app/assets/javascripts/discourse/app/controllers/application.js
app/assets/javascripts/discourse/app/lib/after-frame-paint.js
app/assets/javascripts/discourse/app/templates/application.hbs
app/assets/javascripts/discourse/public/assets/scripts/discourse-boot.js
app/assets/javascripts/discourse/public/assets/scripts/start-app.js
app/assets/javascripts/discourse/tests/test-boot-ember-cli.js

- Rename `discourse-booted` to 'discourse-init' (because 'booted' makes it sound like boot was finished. When in fact, it was just starting)
- Introduce `discourse-paint`, which is fired after the Ember application has been painted to the screen by the browser. This happens slightly after DOMContentLoaded
- Add a `performance.measure` call to link those two marks, so they're easily visible in performance traces
Also removes an ember boot-order workaround which is no longer required.

DEV: Improve built-in browser performance marks/measurements

---

app/models/theme.rb
app/models/theme_settings_migration.rb
app/services/theme_settings_migrations_runner.rb
spec/models/theme_spec.rb
spec/support/helpers.rb
spec/support/system_helpers.rb

This commit introduces the `run_theme_migration` spec helper to allow
theme developers to write RSpec tests for theme migrations. For example,
this allows the following RSpec test to be written in themes:
```
RSpec.describe "0003-migrate-small-links-setting migration" do
let!(:theme) { upload_theme_component }
it "should set target property to `_blank` if previous target component is not valid or empty" do
theme.theme_settings.create!(
name: "small_links",
theme: theme,
data_type: ThemeSetting.types[:string],
value: "some text, #|some text 2, #, invalid target",
)
run_theme_migration(theme, "0003-migrate-small-links-setting")
expect(theme.settings[:small_links].value).to eq(
[
{ "text" => "some text", "url" => "#", "target" => "_blank" },
{ "text" => "some text 2", "url" => "#", "target" …
```

DEV: Introduce `run_theme_migration` spec helper in test environment

---

app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.js
app/assets/javascripts/discourse/app/instance-initializers/topic-footer-buttons.js

Followup 2d2329095c38dd754f2d4ecfea1774509d25ee04
Previous to the above commit, in PMs the bookmark button
was icon-only and did not show a label. This restores the
same functionality.

FIX: Do not show bookmark button label in PM topic footer

---

plugins/chat/app/queries/chat/messages_query.rb
plugins/chat/app/services/chat/list_channel_thread_messages.rb
plugins/chat/lib/chat_sdk/thread.rb
plugins/chat/spec/lib/chat_sdk/thread_spec.rb
plugins/chat/spec/queries/chat/messages_query_spec.rb
plugins/chat/spec/services/chat/list_channel_thread_messages_spec.rb

This commit introduces several enhancements to the ChatSDK module, aiming to improve the functionality and usability of chat thread interactions. Here's what has been changed and added:
1. **New Method: `first_messages`:**
- Added a method to retrieve the first set of messages from a specified chat thread.
- This method is particularly useful for fetching initial messages when entering a chat thread.
- Parameters include `thread_id`, `guardian`, and an optional `page_size` which defaults to 10.
- Usage example added to demonstrate fetching the first 15 messages from a thread.
2. **New Method: `last_messages`:**
- Added a method to retrieve the last set of messages from a specified chat thread.
- This method supports reverse pagination, where the user may want to see the most recent …

DEV: adds first_messages/last_messages to thread SDK

---

app/assets/stylesheets/common/base/_index.scss
app/assets/stylesheets/common/base/popup-menu.scss

Were removed in 8dd883d but some plugins rely on them. Let's restore them for now and address cleaning up once plugins/themes no longer use them.
Should fix https://meta.discourse.org/t/see-who-voted-display-issue/306641

FIX: Restore legacy popup menu SCSS

---

app/models/category.rb
app/models/directory_column.rb
app/models/email_token.rb
app/models/embeddable_host.rb
app/models/group.rb
app/models/invite.rb
app/models/post.rb
app/models/tag.rb
app/models/topic.rb
app/models/topic_user.rb
app/models/user_api_key.rb
app/models/user_option.rb
app/models/user_profile.rb
app/models/user_stat.rb

The columns have already been dropped in
beea8215d71a71f0bcd54c0a7376342bea9bcc38.

DEV: Remove unused `ignored_columns` from ActiveRecord models

---

config/routes.rb
spec/requests/admin/themes_controller_spec.rb

In this PR separate route for components was introduced https://github.com/discourse/discourse/pull/26644
However, the route to edit components was missed and it was 404 when reloaded.
Meta: https://meta.discourse.org/t/missing-admin-theme-component-edit-route/306560

FIX: missing route for edit components

---

app/services/theme_settings_migrations_runner.rb
spec/services/theme_settings_migrations_runner_spec.rb

This commit makes the `getCategoryIdByName` theme settings migration helper case insensitive so that the helper is easier to use.

FIX: Make `getCategoryIdByName` theme migration helper case insensitive

---

app/assets/javascripts/discourse/app/templates/wizard/step.gjs
spec/system/wizard_spec.rb

In this PR we started redirecting to the guide page after the wizard - https://github.com/discourse/discourse/pull/26696
The guide will require rebrand and until it is ready, we should redirect to `/latest`

FEATURE: revert redirect from wizard to guide

---

app/models/draft.rb
db/post_migrate/20240506035024_clear_orphaned_draft_upload_references.rb
spec/models/draft_spec.rb

In #22851 we added a dependent strategy for deleting upload references when a draft is destroyed. This, however, didn't catch all cases, because we still have some code that issues `DELETE drafts` queries directly to the database. Specifically in the weekly cleanup job handled by `Draft#cleanup!`.
This PR fixes that by turning the raw query into an ActiveRecord `#destroy_all`, which will invoke the dependent strategy that ultimately deletes the upload references. It also includes a post migration to clear orphaned upload references that are already in the database.
I don't think we need the optimization here for a couple of reasons:
1. The method is called from a background job, so won't block any requests.
2. When checking for drafts matching the query on meta, I find 1 record.
3. A few …

DEV: Delete upload references on draft cleanup

---

app/jobs/regular/user_email.rb
app/jobs/scheduled/enqueue_digest_emails.rb
app/mailers/user_notifications.rb
spec/jobs/user_email_spec.rb

instead of "last emailed" so that people getting email notifications (from a watched topic for example) also get the activity summaries.
Context - https://meta.discourse.org/t/activity-summary-not-sent-if-other-emails-are-sent/293040
Internal Ref - t//125582

FIX: send activity summaries based on "last seen"

---

plugins/chat/assets/javascripts/discourse/lib/extract-current-topic-info.js
plugins/chat/spec/system/send_message_spec.rb

This case had not been tested end to end as `Discourse.track_events` was not working when wrapping `send_message`. Because of this lack of end to end test, a regression has been created when renaming the expected context properties. This commit fixes the regression and write a slightly convulted, but effective end to end test.

FIX: correctly pass topic/posts context

---

plugins/chat/app/services/chat/create_message.rb
plugins/chat/spec/requests/chat/api/messages_controller_spec.rb
plugins/chat/spec/services/chat/create_message_spec.rb

There's no point checking if a user can join a channel if they are already part of it. This case was frequent when using `enforce_membership: true` for custom bots for example.

FIX: an existing member of a channel is allowed to join

---

app/models/category.rb
spec/models/category_spec.rb

If there's ever a circular reference in categories, don't go into an infinite loop when generating the category slug.
Instead, keep track of parent ids, and bail out as soon as we're encountering one more than once.

FIX: ensure no infinite category loop

---

app/controllers/sidebar_sections_controller.rb
app/models/site.rb
app/models/user.rb
app/serializers/current_user_serializer.rb
app/serializers/site_serializer.rb
spec/serializers/current_user_serializer_spec.rb
spec/serializers/site_serializer_spec.rb

Otherwise embedded objects don't get passed to the root.

DEV: Use has_many and ArraySerializer for SidebarSectionsSerializer

---

app/assets/javascripts/discourse/app/components/d-button.gjs

Previously, if you supplied your own content to DButton it would still add the character:
```hbs
<DButton>my text</DButton>
```
```html
<button>&#8203; my text</button>
```

DEV: Don't add 0-width char if there's no icon in d-button

---

plugins/chat/assets/stylesheets/common/chat-message-info.scss

Avoiding this:
By hiding the user-count in the link as its not important anyway.
And fixing link overflow:

UX: hide user count in original message link

---

plugins/chat/assets/javascripts/discourse/components/chat/modal/thread-settings.gjs
plugins/chat/test/javascripts/components/thread-settings-test.gjs

There's no point in showing a CTA to users who can't act on it.

FIX: only show discourse-ai CTA to admins

---

app/models/category.rb
app/models/directory_column.rb
app/models/email_token.rb
app/models/embeddable_host.rb
app/models/group.rb
app/models/invite.rb
app/models/post.rb
app/models/tag.rb
app/models/topic.rb
app/models/topic_user.rb
app/models/user_api_key.rb
app/models/user_option.rb
app/models/user_profile.rb
app/models/user_stat.rb
lib/migration/safe_migrate.rb

Ignored columns can only be dropped when its associated post-deploy
migration has been promoted to a regular migration. This is so because
Discourse doesn't rely on a schema file system to setup a brand new
database and thus the column information will be loaded by the
application first before the post-deploy migration runs.

DEV: Improve code comment about when ignored columns can be removed

---

lib/tasks/uploads.rake

When running `rake uploads:regenerate_missing_optimized`, a `Discourse::InvalidAccess` will be raised if an SVG file is being processed as `OptimizedImage.prepend_decoder!` doesn't support the svg extension. This commit simply copies the original SVG file as the thumbnail, just like currently `OptimizedImage.create_for` does.

FIX: ignore SVGs when regenerating missing optimized images

---

plugins/chat/app/controllers/chat/api/channel_messages_controller.rb
plugins/chat/app/controllers/chat/api/channels_messages_streaming_controller.rb
plugins/chat/app/services/chat/create_message.rb
plugins/chat/app/services/chat/stop_message_streaming.rb
plugins/chat/app/services/chat/update_message.rb
plugins/chat/lib/chat_sdk/message.rb
plugins/chat/spec/lib/chat_sdk/message_spec.rb
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/spec/requests/chat/api/channel_messages_controller_spec.rb
plugins/chat/spec/requests/chat/api/channel_threads_controller_spec.rb
plugins/chat/spec/requests/chat/api/channels_messages_streaming_controller_spec.rb
plugins/chat/spec/requests/chat/api/messages_controller_spec.rb
plugins/chat/spec/services/chat/create_message_spec.rb
plugins/chat/spec/services/chat/stop_message_streaming_spec.rb
plugins/chat/spec/services/chat/update_message_spec.rb

Prior to this commit, only system users had this pass.
Another significant change of the PR, is to make membership of a channel the angular stone of the permission check to create/update/stop streaming a message. The idea being, if you are a member of a channel already we don't need to check if you can join it, if you are already a member of this channel.
We also have `Chat::AutoRemove::HandleCategoryUpdated` which will deal with permissions change so it's simpler and less prone to error to consider the membership as the only source of truth.

FIX: allows bots to create/update/stream messages

---

app/assets/javascripts/discourse/app/components/sidebar/more-section-links.hbs
app/assets/javascripts/discourse/app/components/sidebar/more-section-links.js
app/assets/javascripts/discourse/app/components/sidebar/section-link-button.hbs
app/assets/javascripts/discourse/app/widgets/header.js
app/assets/javascripts/discourse/app/widgets/sidebar-toggle.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-community-section-test.js
app/assets/stylesheets/common/base/sidebar-more-section-links.scss
app/assets/stylesheets/common/base/sidebar-section-link.scss
spec/system/homepage_spec.rb
spec/system/page_objects/components/navigation_menu/sidebar.rb

Often when styling `.btn` in themes, some styles get applied in undesirable places, like the sidebar:
All caps and centering:
Wrong padding/color on more button:
This PR moves these "non-button buttons" to use `<button>` rather than `<Dbutton>` — this means that they no longer automatically get `.btn`, `.btn-default`, etc classes. 
When we style `.btn` in a theme, it's intended to change the appearance of all buttons that look like buttons. These are technically buttons, but aren't meant to have a button appearance. 
This means in a theme someone might:
1. Style `.btn` to attempt to cover all buttons 
2. Realize this also applied to buttons that don't look like buttons
3. Re-style the specific exceptions to override their added `.btn` style from step 1
This change avoids step 2 and 3. It …

DEV: Remove default button classes from sidebar buttons

---

app/assets/javascripts/discourse/app/lib/fabricators.js

Faker could generate usernames like `D'angelo` and that doesn’t work out nicely for our tests. Using domain names seems safer.

FIX: prevents flakey due to usernames with quotes

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/javascripts/discourse/app/components/site-header.js
app/assets/javascripts/discourse/app/lib/swipe-events.js
app/assets/javascripts/discourse/app/modifiers/swipe.js
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-toast-test.gjs
app/assets/javascripts/discourse/tests/modifiers/swipe-test.gjs
app/assets/javascripts/float-kit/addon/components/d-default-toast.gjs
app/assets/javascripts/float-kit/addon/components/d-toast.gjs
app/assets/javascripts/float-kit/addon/modifiers/auto-close-toast.js

This commit also:
- uses the swipe modifier in the glimmer-site-header component
- changes closing condition for d-modal and toast from distance to velocity
- cancels toast auto close on touch

DEV: uses swipe-events lib for swipe modifier

---

lib/validators/post_validator.rb
lib/validators/stripped_length_validator.rb
plugins/poll/lib/poll.rb
spec/lib/validators/post_validator_spec.rb

Whenever a post already failed "lightweight" validations, we skip all the expensive validations (that cooks the post or run SQL queries) so that we reply as soon as possible.
Also skip validating polls when there's no "[/poll]" in the raw.
Internal ref - t/115890

PERF: bail out of expensive post validations

---

app/assets/stylesheets/common/components/keyboard_shortcuts.scss

The keyboard navigation should not use the `--danger` colour variable to highlight. Instead, it should use the navigational `--quaternary` variable.
[https://meta.discourse.org/t/error-color-on-focus/306915/6](https://meta.discourse.org/t/error-color-on-focus/306915/6)

UX: use quaternary colour for keyboard navigation

---

app/assets/javascripts/discourse/app/lib/dag.js
app/assets/javascripts/discourse/tests/unit/lib/dag-test.js

The `dag-map` library inserts vertexes for keys that are used as reference points in the graph.
We need to compare that with the items on the raw data to ensure that keys that were deliberately
deleted are not included again among the returned results from `dag.resolve`.

DEV: Prevent removed keys from being resolved in the DAG

---

spec/system/topic_bulk_select_spec.rb

For some reason this test is showing up as flaky. It has something to do
with `have_read_post`:
https://github.com/discourse/discourse/blob/main/spec/system/page_objects/components/topic_view.rb#L10
In an effort to not just increase the wait time for `page.has_css?`
let's make these little tweaks and see if it makes any sort of
difference.

DEV: Adjust flaky bulk select spec

---

config/locales/server.en.yml
lib/wizard/builder.rb
spec/lib/wizard/wizard_builder_spec.rb

This keeps coming up in user testing as something
we want to get rid of. The `navigation_menu` setting
has been set to sidebar by default for some time now,
and we are rolling out admin sidebar widely. It just
doesn't make sense to let people turn this off in
the first step of the wizard -- we _want_ people to
use the sidebar.

FEATURE: Remove "Enable Sidebar" step from setup wizard

---

spec/system/page_objects/components/navigation_menu/base.rb

This commits updates
`PageObjects::Components::NavigationMenu::Base#click_edit_tags_button`
to wait for `.sidebar-tags-form` to be present before returning. This is
essential because the client side app has to load the tags from the
server when the modal is open. If we don't wait for all the tags to be
loaded, it makes it hard to reason about the state of the UI when
interacting with the modal. In the case of "allows a user to deselect all tags in the modal which will display the site's top tags" which
was flaky, the system test was interacting with the UI when the tags are
still loading.

DEV: Fix a flaky system test for editing sidebar navigation tags

---

.github/workflows/tests.yml
app/assets/javascripts/discourse/ember-cli-build.js

This seems to save ~7s in core build time. I also tried disabling sourcemaps completely, but it didn't bring any additional benefit.

DEV: Enable 'cheap source maps' in GitHub CI

---

app/assets/javascripts/admin/index.js
app/assets/javascripts/dialog-holder/index.js
app/assets/javascripts/discourse-common/index.js
app/assets/javascripts/discourse-plugins/index.js
app/assets/javascripts/discourse/app/app.js
app/assets/javascripts/discourse/ember-cli-build.js
app/assets/javascripts/discourse/tests/setup-tests.js
app/assets/javascripts/float-kit/index.js
app/assets/javascripts/pretty-text/index.js
app/assets/javascripts/select-kit/index.js
app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/theme-transpiler/transpiler.js
app/models/theme.rb
lib/discourse_js_processor.rb
patches/decorator-transforms+2.0.0.patch
spec/lib/discourse_js_processor_spec.rb
spec/lib/theme_javascript_compiler_spec.rb

decorator-transforms (https://github.com/ef4/decorator-transforms) is a modern replacement for babel's plugin-proposal-decorators. It provides a decorator implementation using modern browser features, without needing to enable babel's full suite of class feature transformations. This improves the developer experience and performance.
In local testing with Google's 'tachometer' tool, this reduces Discourse's 'init-to-render' time by around 3-4% (230ms -> 222ms).
It reduces our initial gzip'd JS payloads by 3.2% (2.43MB -> 2.35MB), or 7.5% (14.5MB -> 13.4MB) uncompressed.

DEV: `@babel/plugin-proposal-decorators` -> `decorator-transforms`

---

app/assets/javascripts/discourse/app/components/topic-admin-menu.gjs

Adds a divider only if we are staff or have extra buttons.

FIX: incorrect divider in topic admin menu

---

plugins/chat/assets/javascripts/discourse/initializers/chat-user-menu.js
plugins/chat/spec/system/user_menu_notifications/sidebar_spec.rb

We were missing two `getURL` calls.
The test is now written for subfolder but it's good enough. If it's working for subfolder, it's working for non subfolders, the opposite being false.

FIX: ensures chat notifications links work with subfolder

---

lib/middleware/request_tracker.rb
spec/lib/middleware/request_tracker_spec.rb

This can happen for various reasons including rate limiting and middleware bugs. This should resolve the warning we're seeing in the logs
```
RequestTracker.get_data failed : NoMethodError : undefined method `[]' for nil:NilClass
```

FIX: Ensure RequestTracker handles bubbled exceptions correctly

---

app/assets/javascripts/discourse/app/widgets/embedded-post.js
app/assets/stylesheets/desktop/topic-post.scss
app/assets/stylesheets/mobile/topic-post.scss
config/locales/client.en.yml

This PR merges the [design experiment](https://meta.discourse.org/t/embedded-replies-feedback/290538) based on the [Custom embedded replies component](https://meta.discourse.org/t/custom-embedded-replies/272670) created by [Don](https://meta.discourse.org/u/don/summary)
<div align="center">
<h3>Before / After</h3>
</div>

UX: Merge the redesign experiment for embedded replies

---

app/assets/javascripts/discourse/app/models/user.js

Fixes a bug I stumbled upon in dev env:
```
Error: Assertion Failed: You attempted to update <discourse@model:user::ember337>.status to "[object Object]", but it is being tracked by a tracking context, such as a template, computed property, or observer. In order to make sure the context updates properly, you must invalidate the property when updating it. You can mark the property as `@tracked`, or use `@ember/object#set` to do this.
```

FIX: Track `User.status` property

---

config/locales/server.en.yml

On new sites, /top has no topics, which is a poor experience for new users.

UX: link to /latest in welcome topic template

---

app/assets/stylesheets/common/admin/plugins.scss

This adds `admin-plugin-config-area__empty-list`,
allows us to standardize on CTA styling for empty lists.

UX: Add CSS for admin plugin empty list CTA

---

config/site_settings.yml

UX: enable_powered_by_discourse site setting default is true

---

app/assets/javascripts/float-kit/addon/components/d-menu.gjs
app/assets/javascripts/float-kit/addon/components/d-tooltip.gjs

* `menuInstance` cached getter -> prop
* `next()` and a `trigger` check -> gone
* `allowedProperties` action -> getter
* `keys` -> `entries`

DEV: Minor refactor of d-menu/d-tooltip

---

plugins/chat/lib/chat/guardian_extensions.rb
plugins/chat/spec/lib/chat/guardian_extensions_spec.rb
plugins/chat/spec/serializer/chat/direct_message_serializer_spec.rb

Bots should be allowed to chat regardless of their groups, just like staff. It makes configuring bots to work in chat much easier.

DEV: bots are always allowed to chat

---

app/assets/javascripts/discourse/app/components/powered-by-discourse.gjs

Opening the Discourse Powered-by link in a new tab doesn't take away from focus in the forum, avoids back button issues.

FIX: Open Powered-by link in new tab

---

app/assets/javascripts/discourse/app/components/topic-admin-menu.gjs

Prior to this fix we were making the action and then closing the d-menu which in this case would be a modal and close the modal opened by the action.

FIX: close d-menu before action in topic menu

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/javascripts/discourse/app/modifiers/swipe.js

Cases like the glimmer-site-header are complex because the swiped area is not the moved target, for now it's simpler to not apply the body scroll lock automatically.
A new property is now available on the swipe modifier: `{{swipe @lockBody=false}}`
Note I tried to have tests for this modifier in the past, but it was very inconsistent on CI causing lots of flakeys, this is why there are no tests for now. I might try to write them again using system specs.

FIX: allows to disable body scroll lock on swipe modifier

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs

It's a temporary solution while I work a better solution. The problem here is quite tricky. We are showing a modal from a modal. But if we close the previous modal, before the second one is show it means we destroy the menu holding the first modal which prevents showing the second modal.
One possible solution would be to refactor d-modal’s show function. At the moment if you await on show it will await until closed and not when the modal has been inserted to the DOM. It means we don't have a clean moment to close the d-menu.
The second issue it that even though it's possible to have multiple modals on screen, the close modal assumes only one active modal at a time.

FIX: disables the modal on mobile bookmark-menu

---

app/assets/javascripts/discourse/app/lib/homepage-router-overrides.js
app/assets/javascripts/discourse/tests/acceptance/homepage-test.js

Seems like an accident that the homepage route will always strip all query params from the URL.. This fixes that :)
Backport of 4f75cee6d2e1184159c0c13983e26fe357d0d2f4

FIX: Don't unnecessarily scrub query params from homepage (stable)

---

plugins/automation/lib/discourse_automation/triggers/recurring.rb
plugins/automation/spec/triggers/recurring_spec.rb

Some combinations of `start_date` and frequency/interval values can cause a recurring automation rule to either trigger before its `start_date` or never trigger. Example repros:
1. Configure a recurring automation with **hourly** recurrence and a `start_date` several days ahead. What this will do is make the automation start running hourly immediately even though the `start_date` is several days ahead.
2. Configure a recurring automation with a **weekly** recurrence and a `start_date` several weeks ahead. This will result in the automation never triggering even after the `start_date`.
These 2 scenarios share the same cause which is that the automation plugin doesn't use the `start_date` as the date for the first run and instead uses the frequency/interval values from the current time to …

FIX: Preveint recurring automations from running before `start_date`

---

app/models/single_sign_on_record.rb
db/migrate/20240510073417_increase_external_avatar_url_limit.rb

😮‍💨 
In some cases, e.g. /307494, a google avatar URL can exceed 1000 characters. 
This PR allows users with such lengthy avatar URLs to log in.

DEV: Increase external avatar url limit

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/services/menu.js

Usage:
```javascript
this.menu.getByIdentifier("foo");
```

DEV: allows to get a menu by its identifier

---

app/controllers/admin/watched_words_controller.rb
app/services/staff_action_logger.rb
config/locales/client.en.yml
spec/requests/admin/watched_words_controller_spec.rb

The watched word group's create, update and delete action logs were missing the translations. This PR will add those strings and will use the group key instead of watched word key where needed.

FIX: add missing translations for staff action logs.

---

app/models/post_custom_field.rb
app/models/topic_custom_field.rb
app/models/user_custom_field.rb
plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/db/post_migrate/20240507112651_switch_topic_automation_custom_fields_to_json.rb
plugins/automation/db/post_migrate/20240507112751_switch_user_automation_custom_fields_to_json.rb
plugins/automation/db/post_migrate/20240507112851_switch_topic_automation_triggered_ids_custom_fields_to_json.rb
plugins/automation/db/post_migrate/20240507112951_drop_automation_ids_custom_field_indexes.rb
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/post_extension.rb
plugins/automation/lib/discourse_automation/scripts/auto_responder.rb
plugins/automation/lib/discourse_automation/triggers/topic.rb
plugins/automation/plugin.rb
plugins/automation/spec/integration/core_ext_spec.rb
plugins/automation/spec/models/automation_spec.rb
plugins/automation/spec/triggers/topic_spec.rb
plugins/automation/spec/triggers/user_updated_spec.rb

The automation plugin has 4 custom field types that are array typed. However, array typed custom fields are deprecated and should be migrated to JSON type.
This PR migrates all four custom fields to JSON and fixes a couple of bugs that are related to the 4 custom fields. I will leave details of the bugs in comments to the relevant lines.

DEV: Move array type custom fields to JSON type in automation

---

app/assets/javascripts/discourse/app/routes/about.js
app/assets/javascripts/discourse/tests/fixtures/about.js
app/models/about.rb
app/serializers/about_serializer.rb

It used to embed the objects which could lead to duplicated objects when the same user or category was used multiple times (user was admin, moderator and category or category was parent for multiple categories).

DEV: Embed IDs in serializer for about page

---

app/assets/javascripts/discourse/app/components/sidebar/api-panels.gjs
app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js
app/assets/stylesheets/common/admin/admin_revamp.scss

Recently a bug was introduced when the admin sidebar section was made bold.
When the admin sidebar is disabled, we display the original sidebar in the admin panel. In that case, an incorrect CSS rule is executed.
```CSS
.admin-area .sidebar-wrapper {
background-color: var(--d-sidebar-admin-background);
.sidebar-section-header-text {
font-weight: bold;
}
}
```
Bug in this PR: https://github.com/discourse/discourse/pull/26801
To solve it, a custom CSS class with a panel key was added which will allow granular customisations.
The demo that admin sidebar has still bold headers
The demo that the original sidebar is ok

FIX: bold sidebar header when admin sidebar is disabled

---

Gemfile
Gemfile.lock

The following warning is being printed when running Discourse with Ruby
3.3
`warning: /usr/local/lib/ruby/3.3.0/csv.rb was loaded from the standard
library, but will no longer be part of the default gems since Ruby
3.4.0. Add csv to your Gemfile or gemspec.`

DEV: Add `csv` to Gemfile to resolve Ruby 3.3 deprecation warning

---

app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
config/routes.rb
lib/read_only_mixin.rb
spec/requests/categories_controller_spec.rb

This commit changes request method for "categories/search" from GET to POST to make sure that long filters can be passed to the server. For example, category selectors with many categories are setting the full list of selected category IDs to ensure these are filtered out from the list of choices. This can result in a long URL that exceeds the maximum length.

FIX: Change request method for categories/search

---

config/site_settings.yml

Per https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers
> GoogleOther is the generic crawler that may be used by various product teams for fetching publicly accessible content from sites. For example, it may be used for one-off crawls for internal research and development.
This commit will ensure it's served the crawler view, and included in crawler metrics

Add GoogleOther crawler user agent

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/services/menu.js

Prior to this fix all menus with empty identifier or groupIdentifier would be considered to be part of the same identifiers/groupIdentifiers and would auto close any existing d-menu with no identifier/groupIdentifier when opened.

FIX: do not auto close on empty identifiers

---

app/assets/javascripts/discourse/app/components/topic-admin-menu.gjs
app/assets/stylesheets/common/topic-timeline.scss

Fixes this theme component mismatch issue and also adds some missing button classes
Before: 
After:

UX: topic admin button should match height of siblings

---

app/assets/javascripts/discourse/app/widgets/header.js

Some of the old (pre-dag) header logic was accidently re-introduced as part of 9bcbfbba43b876ae92cb90d6d619be7b1154c119 (presumably by mistake while resolving a merge conflict). This causes sites on the old header implementation to end up with duplicate user menu icons.

FIX: Remove duplicate user menu for old header implementation

---

app/mailers/user_notifications.rb
app/models/notification.rb
lib/email/message_builder.rb
spec/lib/email/message_builder_spec.rb

(also add notification_type to email_opts so plugins can access it)

add modifiers to message_builder so plugins can customize subject/body/html

---

app/assets/stylesheets/common/components/keyboard_shortcuts.scss

In a topic item list, the row currently selected by the <kbd>j</kbd>/<kbd>k</kbd> keyboard shortcuts is indicated by a style applied to the [`td:first-child` of selected rows](https://github.com/discourse/discourse/blob/ce2388e40b44a10a7b1577b689c9d5042c0c6dbe/app/assets/stylesheets/common/components/keyboard_shortcuts.scss#L6), but the "above-topic-list-item" plugin outlet allows for inserting elements as the first child of those rows. If the inserted element is not a `<tr>` element, then there's no element matching the CSS selector and thus no way to tell what row is currently selected to navigate from.
For example, the Clickable Topic plugin inserts a [hidden `<div>`](https://github.com/discourse/discourse-clickable-topic/blob/611e3462f7d742c22b833f48c25a4130ddddd558/javascripts/discour …

FIX: show selected topic with above-topic-list-item

---

plugins/discourse-lazy-videos/lib/lazy-videos/lazy_youtube.rb

Fix overflowing youtube video thumbnail in chat

UX: add missing class for oneboxing youtube video

---

app/assets/javascripts/discourse/app/components/topic-admin-menu.gjs
app/assets/stylesheets/wcag.scss

A few things:
* The change in 47cabdc caused the `btn-default` class to be applied to the dropdown, switching this to `@triggerClass` fixes it 
* It seems the btn-default styles can be simplified a little bit because we're applying the button classes better than we used to 4 years ago
* Add the new `.btn-transparent` class to the btn-danger rule exception 
Before:
After:

A11Y: fix topic admin menu button colors for WCAG colors

---

app/assets/javascripts/admin/addon/components/admin-watched-word.hbs
app/assets/javascripts/admin/addon/components/admin-watched-word.js
app/assets/javascripts/admin/addon/components/watched-word-form.hbs
app/assets/javascripts/admin/addon/components/watched-word-form.js
app/assets/javascripts/admin/addon/models/watched-word.js
app/assets/javascripts/discourse-markdown-it/src/features/watched-words.js
app/controllers/admin/watched_words_controller.rb
app/models/watched_word.rb
app/serializers/watched_word_serializer.rb
app/services/word_watcher.rb
config/locales/client.en.yml
config/locales/server.en.yml
db/migrate/20240506125839_add_html_to_watched_words.rb

This adds support for Watched Words to allow replacement with HTML content rather than always replacing with text.
Can be useful when automatically replacing with the `<abbr>` tag for example.
Discussion - https://meta.discourse.org/t/replace-text-with-more-than-just-links/305672

FEATURE: add HTML replacements

---

app/assets/javascripts/discourse/app/raw-views/topic-list-header-column.js
app/assets/javascripts/discourse/app/routes/build-private-messages-group-route.js
app/assets/javascripts/discourse/app/routes/build-private-messages-route.js
app/assets/javascripts/discourse/app/routes/build-topic-route.js
app/assets/javascripts/discourse/app/routes/group-activity-topics.js
app/assets/javascripts/discourse/app/routes/user-activity-read.js
app/assets/javascripts/discourse/app/routes/user-activity-topics.js
app/assets/javascripts/discourse/app/services/store.js

Sorting a topics list in user activities wasn't working because the query parameters weren't passed to `findFiltered()` that does the request to the server.
Made the `sortIcon` more resilient to "input" by always converting the value to a string and checking against `"true"`.
Moved `cleanNullQueryParams()` inside `findFiltered` so we're always removing `null` query parameters.
Internal ref - t/127068

FIX: sorting user topics lists

---

app/assets/javascripts/discourse/app/templates/users.hbs
app/assets/javascripts/discourse/tests/acceptance/users-test.js
config/locales/client.en.yml

This PR adds a different message to the users directory (`/u`) that's shown when there are no results for the search term instead of showing the one for when there are no users on the site yet.
When there's a search term:
When there isn't a search term:
Internal topic: t/126076.

UX: Use a different JIT message when there are no search results in the users directory

---

lib/onebox/engine/twitter_status_onebox.rb
spec/fixtures/onebox/twitterstatus_noclient.response
spec/lib/onebox/engine/twitter_status_onebox_spec.rb

There is an error ("no implicit conversion of Array into Integer") if some meta tags are missing. At some point the twitter HTML changed and Murphy's law kicked in. This fixes the error and uses meta tags that exist.

FIX: avoid error from missing twitter meta tags

---

.licensed.yml
Gemfile
Gemfile.lock

Resolves the following deprecation warnings when running Discourse on
Ruby 3.3
```
warning: /Users/tgxworld/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.1 to add mutex_m into its gemspec.
warning: /Users/tgxworld/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/drb.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add drb to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.1 to add drb into its gemspec.
```

DEV: Add `mutex_m` and `drb` to Gemfile to remove deprecation warning

---

app/models/user.rb
spec/models/user_spec.rb

The users directory is updated on a daily cadence. However, when a site is new and doesn't have many users, it can be confusing that a user who has just joined doesn't show up in the users until a day after they join. To eliminate this confusion, this PR triggers a refresh for the users directory as soon as as a user joins, if the site is in bootstrap mode. The reason for the conditional trigger is that refreshing the users directory is an expensive operation and doing it often on a large site with many users could lead to performance problems.
Internal topic: t/126076.

FIX: Create directory items for new users when in bootstrap mode

---

lib/topics_filter.rb

This commit optimises the database query generated by
`TopicsFilter#filter_categories` when the `-category:*` query string is used to exclude topics 
from certain categories.
Previously, the `TopicsFilter#filter_categories` method will add the `topics.category_id NOT IN
(<category ids to be excluded>)` filter to the resulting query. However,
we noticed that the performance of the query degrades as the number of
rows in the `topics` table grow and when the number of category ids to be
excluded is large.
Sample of query we ran on a large database in production to demonstrate
the improvement:
Before:
```
SELECT topics.id FROM topics WHERE topics.category_id NOT IN (83, 136, 149, 143, 153, 165, 161, 123, 155, 163, 144, 134, 69, 135, 158, 141, 151, 160, 131, 133, 89, 104, 150, 147, 132, 145, …
```

PERF: Optimise query for excluding topics in certain categories in TopicsFilter

---

config/site_settings.yml

[Meta](https://meta.discourse.org/t/configure-linkedin-openid-connect-login-for-discourse/305366/3)
The LinkedIn OIDC client secret used to look something like:
```
sHyUiKxnLJKBE1Do
```
but now they are generating secrets that look like:
```
WPL_AP0.UIM1fMSfJMdLtHm0.agwMyzJw1xoAcEJ0==
```
This updates the regular expression used for validation to reflect this.

DEV: Update LinkedIn OIDC client secret validation format

---

app/jobs/regular/user_email.rb
app/jobs/scheduled/enqueue_digest_emails.rb
app/mailers/user_notifications.rb
spec/jobs/user_email_spec.rb

Reverts discourse/discourse#26879
We're getting reports of emails getting sent too often. Doing a revert here while we investigate the issue.

FIX: Revert "FIX: send activity summaries based on "last seen""

---

plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/spec/system/bookmark_message_spec.rb
plugins/chat/spec/system/page_objects/chat/chat_thread.rb

Whenever you get a bookmark notification, a mention notification, or click on a bookmark on a message in a long thread, we should ensure we always highlight and show the proper message.
Before this fix, we would correctly load the thread, but would always start at the bottom.
Internal ref. t/128103

FIX: deep linking to a message in a thread

---

lib/version.rb

Version bump for stable: v3.2.2

---

lib/version.rb

Version bumps for main: v3.3.0.beta2, v3.3.0.beta3-dev

---

yarn.lock

This will bring in the latest version of json5, thereby satisfying security scanners. Given that this was only used in a build pipeline with trusted inputs, Discourse was not vulnerable to CVE-2022-46175, so this is just a housekeeping commit.

DEV: Bump `find-babel-config` indirect dependency & yarn-deduplicate

---

lib/discourse_ip_info_spec.rb
lib/final_destination.rb
spec/lib/final_destination_spec.rb

This commit updates `FinalDestination#get` to not forward
`Authorization` header on redirects since HTTP clients I tested like
`curl` and `wget` does not do it.
This commit also fixes a recent problem in `DiscourseIpInfo.mmdb_download`
where we will fail to download the databases when both `GlobalSetting.maxmind_account_id` and
`GlobalSetting.maxmind_license_key` has been set. The failure is due to
the bug above where the redirected URL given by MaxMind does not accept
an `Authorization` header.

FIX: `FinalDestination#get` forwarding `Authorization` header on redirects

---

lib/discourse_ip_info.rb

Per https://dev.maxmind.com/geoip/release-notes/2024#presigned-urls-for-database-downloads 
MaxMind users who download databases should make sure that their HTTP client follows redirects and there are no proxy or firewall settings that would block requests to the host we are redirecting to.

FIX: Allow redirect when downloading maxmind database (#26333)

---

plugins/automation/plugin.rb
plugins/automation/spec/lib/triggerable_spec.rb

Previously active automation id was set globally, even though multiple threads could be running an automation leading to tracking falling apart in sidekiq.

FIX: thread safety for active automation tracking

---

lib/site_setting_extension.rb
spec/lib/site_setting_extension_spec.rb

Following on from eea74e0e32f704f0756202c3f3ae801bcc8ac8bb,
this commit adds the automatic _map splitting shorthand
for emoji_list, tag_list site settings.

DEV: Add more _map extensions for list site settings

---

plugins/chat/app/models/chat/message.rb
plugins/chat/spec/requests/chat/api/messages_controller_spec.rb
plugins/chat/spec/system/user_menu_notifications/sidebar_spec.rb

When you reply to a chat message, we [always create a thread][1]. But when the channel we're in doesn't have threading enabled, the reply is _technically_ not a thread.
This changes the `in_thread?` method to check for both the presence of a `thread_id` and to ensure that the channel has `threading_enabled`.
Internal ref - t/128103/3
[1]: https://github.com/discourse/discourse/blob/e6e3eaf472a0112aca882811267a260c4cc73a89/plugins/chat/app/services/chat/create_message.rb#L110-L115

FIX: chat replies are not always in a thread

---

app/services/group_message.rb
app/views/about/index.html.erb
spec/requests/about_controller_spec.rb
spec/services/group_message_spec.rb

When "unicode_usernames" is enabled, calling the "user_path" helper with a username containing some non ASCII character will break due to the route constraint we have on username.
This fixes the issue by always encoding the username before passing it to the "user_path" helper.
Internal ref - t/127547

FIX: crawler view with unicode usernames

---

script/bulk_import/base.rb
script/bulk_import/generic_bulk.rb

Currently, only one topic allowed user can be imported. This change introduces support for importing multiple topic-allowed users.
It also introduces a new step to support imports of  topic allowed groups.

FEATURE: Extend PM recipient bulk imports

---

app/jobs/regular/emit_web_hook_event.rb
spec/jobs/emit_web_hook_event_spec.rb

This allows for webhook event headers to be modified. The payload and webhook event instance are passed to the modifier so that the new/modified headers can be based off data in the payload/event type.

DEV: Add modifier for webhook event header generation

---

app/controllers/topics_controller.rb
app/models/topic.rb
app/models/topic_converter.rb
spec/jobs/publish_topic_to_category_spec.rb
spec/requests/topics_controller_spec.rb

When converting a PM to a public topic (and vice versa), if there was a validation error (like a topic already used, or a tag required or not allowed) the error message wasn't bubbled up nor shown to the user.
This fix ensures we properly stop the conversion whenever a validation error happens and bubble up the errors back to the user so they can be informed.
Internal ref - t/128795

FIX: display validation errors when converting topics

---

spec/support/omniauth_helpers.rb
spec/system/login_spec.rb
spec/system/page_objects/modals/login.rb
spec/system/page_objects/modals/signup.rb
spec/system/signup_spec.rb
spec/system/social_authentication_spec.rb

DEV: Full system specs coverage for signup/login

---

app/models/topic.rb
lib/post_revisor.rb
spec/lib/post_creator_spec.rb
spec/models/topic_spec.rb

Whenever one creates, updates, or deletes a post, we should keep the `topic.word_count` counter in sync.
Context - https://meta.discourse.org/t/-/308062

FIX: keep topic.word_count in sync

---

app/assets/javascripts/discourse/app/components/header/home-logo.gjs
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/widgets/home-logo.js
app/assets/javascripts/discourse/tests/integration/components/home-logo-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/home-logo-test.gjs
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md

The `registerHomeLogoHrefCallback` API allows setting a callback function that specifies the URL used in the home logo.

DEV: Add the `registerHomeLogoHrefCallback` plugin API

---

plugins/chat/assets/javascripts/discourse/controllers/preferences-chat.js

The translations of the labels of some of the chat preferences dropdowns were not customizable via the "site texts" feature.
This was because they were declared outside of a Controller class and were thus not taking into account the customization through "site texts".
Internal ref - t/128859

FIX: customize chat dropdown labels

---

app/assets/javascripts/admin/addon/templates/customize-colors-show.hbs

This regressed in https://github.com/discourse/discourse/pull/26644

FIX: Broken link to theme in customize colors page

---

app/controllers/groups_controller.rb
app/models/group.rb
spec/requests/groups_controller_spec.rb

In https://github.com/discourse/discourse/commit/07ecbb5a3b980115e6b8dfc127b8e336997a2ea8 we ensure the mentions in a group's activity page worked properly but we missed adding proper support for infinite loading.
The client is using the `before` parameter instead of the `before_post_id` to do the pagination.
This adds support for `before` as well as some tests to ensure it doesn't regress.
I also added tests to the group's activity posts as well since those were missing.
Finally I deleted some unused code (`group.messages_for`) which is not used anymore.
Context - https://meta.discourse.org/t/-/308044/9

FIX: group activity's mentions infinite loading

---

plugins/chat/assets/javascripts/discourse/components/user-threads/preview.gjs
plugins/chat/spec/system/page_objects/chat/user_threads.rb
plugins/chat/spec/system/user_threads_spec.rb

... wasn't properly escaped so it would show html entities (like `&#39;` instead of the apostrophe `'`).
I checked all the other places we show an excerpt and this was the only one that was missing the call to `htmlSafe` -> `replaceEmoji`.
Internal ref - t/128877

FIX: My Thread's last reply excerpt on mobile

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/stylesheets/mobile/modal.scss

- removes `will-change: auto;` which is a performance hack which should be avoided and is probably causing more harm than good here
- lowers swipe velocity to 0.4 to ensure the modal can be dismissed with the thumb
- uses JS CSS animate API to animate the backdrop opacity
- uses the height of the modal container to have more precise values when computing backdrop opacity
- animate the modal container instead of the wrapper
- removes a useless template-lint-disable directive
- simplify the closing animation
- various small code tweaks to limit indirection

FIX: mobile modal tweaks

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js

This commit fixes an issue where `I18n.lookup` was being used to
check if a link had a valid I18n key when the `addAdminSidebarSectionLink`
plugin API was used. However this was imperfect -- usually when we do
`I18n.t`, we fall back to the default locale (`en`), but if
`I18n.lookup` is used we do not do this, so we were removing the link
needlessly.
This issue was identified via the plugin API's use in https://github.com/discourse/docker_manager
c.f. https://meta.discourse.org/t/new-admin-sidebar-wheres-the-update-discourse-button/308213/15?u=martin

FIX: Take into account language fallbacks for admin sidebar plugin links

---

plugins/chat/assets/javascripts/discourse/lib/extract-current-topic-info.js

Prior to this fix we were using `topic.current_post_number` which is coming from the server side and represents the initial topic scroll position when initial rendered to the end user. However this value is not dynamic and is not updated when the user scroll, `topic.currentPost` is the dynamic equivalent.
No test as there are very low chances a test like this one based on scroll position, will be reliable over time.

FIX: ensures topic info is dynamic with scroll

---

lib/auth/auth_provider.rb
lib/plugin/instance.rb
spec/lib/plugin/instance_spec.rb
spec/requests/omniauth_callbacks_controller_spec.rb

`AuthProvider#enabled_setting=`, used primarily by plugins, has been deprecated since version 2.9, in favour of `Authenticator#enabled?`. This PR confirms we are seeing no more usage and removes the method.

DEV: Remove deprecated AuthProvider#enabled_setting=

---

app/assets/javascripts/discourse/app/lib/tracked-tools.js
app/assets/javascripts/discourse/tests/unit/lib/tracked-tools-test.gjs

Same as `@tracked`, but skips notifying consumers if the value is unchanged. This introduces some performance overhead, so should only be used where excessive downstream re-evaluations are a problem.
This is loosely based on `@dedupeTracked` in the `tracked-toolbox` package, but without the added complexity of a customizable 'comparator'. Implementing ourselves also avoids the need for pulling in the entire package, which contains some tools which we don't want, or which are now implemented in Ember/Glimmer (e.g. `@cached`).

DEV: Introduce `@dedupeTracked`

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/javascripts/discourse/app/helpers/element.gjs

Returns a wrapper component with the given tagname, or an empty wrapper for an empty string. Similar to the reference implementation of RFC389, with higher-performance shortcuts for common elements.

DEV: Introduce `element` helper

---

plugins/chat/assets/javascripts/discourse/controllers/preferences-chat.js
plugins/chat/assets/javascripts/discourse/services/chat-audio-manager.js

Debouncing the audio was causing the audio to be lost sometimes, somewhat randomly. It's not supposed to be necessary.
The commit also refactors the code to async/await.

FIX: improves chat audio notification reliability

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs

The bookmarks toasty last a bit too long (3s), taking up space and attention on screen.
This commit halves the time to 1.5s, which is sufficient to read a 1-word toasty.

UX: shorten duration of bookmark toasties

---

.github/workflows/tests.yml
lib/tasks/themes.rake

This commit adds a step in our tests workflow on Github actions to update the themes to
use the compatible version when not running aginast the `main` branch.
This is to ensure that we are not running
the tests for themes against an incompatible version of Discourse.

DEV: Pull compatible themes in tests workflow

---

.github/workflows/tests.yml

`discourse-ai` has custom gems which need to be bumped in order to be
compatible with Ruby 3.3. However, its version is pinned so we can't
pull in the commits in which upgrades the gems to be compatible with
Ruby 3.3. Just avoid running the specs on `stable` branch for now until
we release a new stable.

DEV: Don't run `discourse-ai` plugin specs when running against stable

---

app/controllers/post_action_users_controller.rb
app/models/user_action.rb
lib/guardian.rb
spec/lib/guardian_spec.rb
spec/models/user_action_spec.rb
spec/requests/post_action_users_controller_spec.rb

In https://github.com/discourse/discourse-reactions/commit/04c4742f938825f86694bf53627c8cb32d10fe17, we mark the plugin as compatible with `stable` to pull in a security fix with the plugin. However, the plugin was never really compatible with stable because the tests for the plugins were broken.
This PR backports the changes made to core which the `discourse-reaction` plugins needs in order for the latest commit of the plugin to be compatible with stable.

Backport fixes required for `discourse-reactions` plugin

---

app/assets/javascripts/discourse/app/components/modal/convert-to-public-topic.js
spec/system/page_objects/pages/topic.rb
spec/system/topic_admin_menu_spec.rb

Follow up to https://github.com/discourse/discourse/commit/e04ac5e2d8fed5badf984ae4aece69b45a05bdcd which missed showing the error messages in the "convert to public" modal 🤦‍♂️
It was instead showing a generic error message, which wasn't helpful.

FIX: shows errors when converting to public is impossible

---

app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.gjs
app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/modal.gjs
app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/tags-modal.gjs

1. async/await
2. TrackedSet
3. don't rely on ember array methods
4. list used props
5. move stuff out of constructors
6. don't use ember's Input component
7. convert a function to a class method (to avoid passing in a class prop)
8. add missing `@tracked`
9. remove tracking from props that don't need it (not used in templates)

DEV: Clean up sidebar modals

---

app/assets/stylesheets/common/base/search-menu.scss

The search context uses similar styles to our buttons, but has a slightly too dark background:
Before:
After:

UX: search context box too dark

---

app/assets/stylesheets/common/base/topic-post.scss

Most of our `DButton` buttons use `display: flex;` by default... so whitespace is collapsed. 
In `DButton` we have an intentional space character added to increase the icon-only button height to match button heights with text (the text adds a couple px of height).
So the use of `DButton` in the post controls, which are not currently flex buttons, means that we end up with an extra whitespace: 
This switches the post actions to `inline-flex` instead of `inline-block` to hide this space without requiring additional edits to the way the button is populated:

UX: switch post action buttons to inline-flex to avoid extra whitespace

---

app/assets/javascripts/discourse/app/helpers/element.gjs

…so it uses the more performant glimmer/template-only component wrapper instead of falling back to an ember component wrapper. see the `element` helper PR for more details.

DEV: Add `td` to the `element` helper list

---

app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/desktop/topic-list.scss
app/assets/stylesheets/desktop/topic-post.scss
app/assets/stylesheets/mobile/topic-list.scss
app/assets/stylesheets/mobile/topic-post.scss

This is a follow-up to https://github.com/discourse/discourse/commit/5c09792f79f40b057f5da9a38de71b3ec2d2241d
Since the font size is now 1px larger by default, we now have some places where the font size has increased, but spacing has not. This means the layout is slightly more cramped where px spacing was used. 
By switching these to em values, these spaces will now increase slightly along with font size. I've also increased the line spacing of post text from 1.4 to 1.5, because despite already being a proportionate unit-less value, often increasing text size requires disproportionately larger line height adjustments for readability.
There are more cases of this throughout the app, but this covers some of the primary issues with the topic list and posts.

UX: update px spacing to em for proportionality

---

plugins/chat/assets/javascripts/discourse/services/chat-audio-manager.js
plugins/chat/assets/javascripts/discourse/services/chat-channel-notification-sound.js
plugins/chat/assets/javascripts/discourse/services/chat-subscriptions-manager.js
plugins/chat/test/javascripts/unit/services/chat-channel-notification-sound-test.js

Prior to this change, only mentions would get a notification and a sound. This change will not create a notification for this case, but will play a sound. This is still respecting notification settings, not playing the sound when you are viewing the channel or not following it.

FIX: play audio sound on message in non group DMs

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs

DEV: Deprecate the `user-dropdown` header widget

---

app/controllers/posts_controller.rb
spec/requests/posts_controller_spec.rb

Note this may have performance issues in some cases, will need to be monitored
Previous to this change we were bracketing on 50 id windows. They may end up
having zero posts we are searching for leading to posts.rss and .json returning
no results.

FIX: paginating posts should allow for deletions and PMs

---

app/assets/javascripts/discourse/app/lib/desktop-notifications.js
plugins/chat/assets/javascripts/discourse/services/chat-channel-notification-sound.js
plugins/chat/test/javascripts/unit/services/chat-channel-notification-sound-test.js

This commit reuses the existing codepath in desktop-notifications and make it available to use to chat.
primaryTab was too hard to test if not impossible in this service test, however isIdle and disabled notifications are correctly tested.

FIX: correctly check for disabled notifications, tab and is idle

---

app/assets/javascripts/discourse/app/components/modal/history.hbs
app/assets/javascripts/discourse/app/components/modal/history.js
app/assets/javascripts/discourse/app/components/modal/history/revision.hbs
app/assets/javascripts/discourse/app/components/modal/history/revisions.hbs
app/serializers/post_revision_serializer.rb
spec/serializers/post_revision_serializer_spec.rb

- FIX: properly scope category changes to what the current user can see
- UX: previous category is now highlighted in "red", new category is highlighted in "green"
- PERF: no need to serialize the categories
- FIX: properly track wiki
- FIX: properly track post_type (aka. Staff Color)
- FIX: properly track making a topic a PM
- FIX: never show the category changes when a topic is made a PM
- PERF: post_revision serializer is now more leaner (never includes title changes when post_number > 1, never includes user changes if there aren't any)
- UX: always sort the tags by name
Context - https://meta.discourse.org/t/-/304696

FIX: various revision history modal quirks

---

.gitignore

VS Code is configured to automatically excludes files and directories from the `.gitignore` but the trailing slash was not working as expected.
The plugins that had a trailing slash in the .gitignore weren't allow-listed properly in VS Code.
There are no tests since it's only affecting how VS Code shows/hides directories.

DEV: git ignored directories should not have trailing slashes

---

plugins/chat/assets/stylesheets/common/chat-message-text.scss

Given this is currently buggy and  we have the cancel button Im not sure this is actually necessary. I feel like it's adding a lot of noise of low value.
For now at least, it's better without it.

UX: removes blinking indicator while streaming message

---

lib/pretty_text.rb
plugins/discourse-details/plugin.rb
plugins/discourse-details/spec/components/pretty_text_spec.rb
spec/lib/pretty_text_spec.rb

This fixes the `PrettyText.make_all_links_absolute` to better handle subfolder.
In subfolder, when given the cooked version of a post, links to mentions includes the `Discourse.base_path` prefix. Adding the `Discourse.base_url` was doubling the `Discourse.base_path`.
The issue was hidden behind the specs which was stubbing `Discourse.base_url` instead of relying on `Discourse.base_path`.
This fixes both the "algorithm" used in `PrettyText.make_all_links_absolute` to better handle this case and correct the specs to properly handle subfolder cases.
There are lots of changes in the specs due to a refactoring to use squiggly heredoc strings for easier reading and less escaping.

FIX: subfolder absolute links in summaries

---

app/assets/javascripts/deprecation-silencer/index.js

e.g. `unexpectedly found "! no whitespace ~" when slicing source, but expected " no whitespace "`
See: https://github.com/emberjs/ember.js/issues/19392

DEV: Silence whitespace-eating-comment warnings

---

plugins/chat/app/models/chat/user_chat_channel_membership.rb
plugins/chat/assets/javascripts/discourse/components/chat/header/icon/unread-indicator.gjs
plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb
plugins/chat/spec/system/message_thread_indicator_spec.rb

When a user had the chat option "Show activity indicator in header" set to "all new messages", and they would get a reply to a thread they're part of, the chat icon in the header would not show the unread bubble indicator.
In order to fix this, the `ChatHeaderIconUnreadIndicator` component will now `showUnreadIndicator` whenever there is either one unread public channel or there are unread threads.
I only added a system spec for this very specific path because I don't want to slow down the whole suite to test for all the various combination of the `chat_header_indicator_preference` values.
Internal ref - t/128874

FIX: chat activity indicator wasn't working for threads

---

app/controllers/groups_controller.rb
config/locales/server.en.yml
spec/requests/groups_controller_spec.rb

Slight alteration on group request messaging per [this meta post](https://meta.discourse.org/t/better-flow-for-group-membership-requests/64412/23?).
Instead of creating two separate Topics when a user (1) requests to join a group and (2) gets accepted in, this makes the acceptance message into a Post under the origin group request Topic.

UX: Group membership PMs thread

---

plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js
plugins/chat/spec/system/single_thread_spec.rb

Prior to this fix we wouldn't intercept it, and we also wouldn't handle it, which in result would cause us to handle as a full page interaction and open the full page chat even if you were in drawer mode.

FIX: correctly handles near-message-with-thread route in drawer

---

app/assets/javascripts/discourse/app/lib/desktop-notifications.js

When users come back to a tab we should consider they are not idle anymore.

UX: reset idle on tab focus

---

plugins/chat/assets/javascripts/discourse/routes/chat-channel-thread.js

activeChannel is something we should use less and less as it could not exist, in this case we have the channel right here in the function so there's no reason to reach for `this.chat.activeChannel`.
The origin of this commit is a bug which seems to happen with subfolders where `activeChannel` was null at this point, don't have yet the reason for this, but I'm confident that should fix the error.

FIX: set active thread on correct channel

---

app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs
app/assets/javascripts/admin/addon/models/admin-plugin.js
app/assets/javascripts/discourse/tests/integration/components/admin-plugins-list-item-test.js
app/serializers/admin_plugin_serializer.rb
config/locales/client.en.yml
spec/serializers/admin_plugin_serializer_spec.rb

For plugins with only an "enabled" site setting, it doesn't
make sense to take them to the site settings page, since the
toggle switch in the list can be used to change enabled/disabled.
This will not be the case for plugins that have their own custom
config page (like Automation), but we will deal with this when
we actually overhaul this plugin to use the new show page.

UX: Disable plugin list settings button for some plugins

---

app/assets/stylesheets/common/base/topic-post.scss

UX: add ellipsis to usernames in topic post map (PMs)

---

plugins/chat/app/models/chat/message.rb
plugins/chat/spec/models/chat/message_spec.rb

A message is in a thread if:
- it has a `thread_id`
- it is in `threading_enabled` channel OR the associated thread is marked as `force`

FIX: correct in_thread? message logic

---

app/assets/javascripts/discourse/app/models/user.js
app/assets/javascripts/discourse/tests/acceptance/personal-message-test.js
app/assets/javascripts/discourse/tests/unit/models/user-test.js

Before this fix when generating a pm path leading to a group messages inbox we would blindly take the first group of the pm, however, it's possible our current user doesn't have access to this group.
This commit will now try to find the first group the user has access to, and generate a path to this group’s inbox.

FIX: correctly generate pm path on user

---

app/assets/javascripts/admin/addon/components/admin-user-field-item.hbs
app/assets/javascripts/admin/addon/components/admin-user-field-item.js
app/assets/stylesheets/common/admin/customize.scss
app/controllers/admin/user_fields_controller.rb
app/models/user_field.rb
app/serializers/user_field_serializer.rb
config/locales/client.en.yml
db/migrate/20240520060901_add_requirement_to_user_fields.rb
spec/fabricators/user_field_fabricator.rb
spec/models/user_field_spec.rb
spec/requests/admin/user_fields_controller_spec.rb
spec/requests/users_controller_spec.rb
spec/system/admin_user_fields_spec.rb
spec/system/page_objects/modals/signup.rb
spec/system/page_objects/pages/admin_user_fields.rb
spec/system/signup_spec.rb

We're planning to implement a feature that allows adding required fields for existing users. This PR does some preparatory refactoring to make that possible. There should be no changes to existing behaviour. Just a small update to the admin UI.
The change includes:
- Migrate `UserField#required` boolean to `UserField#requirement` enum (including data migration) to support new value.
- Deprecate old column.
- Implement new admin user fields UI for existing options (optional and on signup.)
- Add system specs for signing up when there are required user fields.
The change does not include:
- Adding the new (for all users) option. This will be done in subsequent PRs.

FEATURE: Allow adding required fields for existing users - Part 1

---

app/assets/stylesheets/common/components/user-info.scss

Adds vertical spacing between follower/following list.
Before:
After:

UX: add space to following list

---

app/assets/javascripts/discourse/app/components/reviewable-item.js
app/models/reviewable_flagged_post.rb
config/locales/server.en.yml
spec/models/reviewable_flagged_post_spec.rb
spec/system/reviewables_spec.rb

adds agree and edit - an alias for agree and keep -- but with a client action to edit the post in the composer before the flag is agreed with.

FEATURE: add agree and edit

---

app/jobs/scheduled/auto_queue_handler.rb

Large batches of reviewables may require paginated queries.

DEV: replace .each with .find_each for paginated queries

---

app/serializers/post_serializer.rb
spec/models/flag_spec.rb

After flags were moved to the database, with each save they are changing available PostActionTypes. Therefore, flag specs should clear the state before and after each example not just before.
In addition, we need to clear `nil` counts for dynamically created flags from serializer.

FIX: flaky post action counts specs

---

app/jobs/scheduled/ensure_s3_uploads_existence.rb
lib/s3_helper.rb
lib/s3_inventory.rb
spec/jobs/ensure_s3_uploads_existence_spec.rb
spec/lib/s3_inventory_spec.rb

This commit updates `S3Inventory#files` to ignore S3 inventory files
which have a `last_modified` timestamp which are not at least 2 days
older than `BackupMetadata.last_restore_date` timestamp.
This check was previously only in `Jobs::EnsureS3UploadsExistence` but
`S3Inventory` can also be used via Rake tasks so this protection needs
to be in `S3Inventory` and not in the scheduled job.

FIX: `S3Inventory` to ignore files older than last backup restore date

---

spec/lib/guardian/flag_guardian_spec.rb

Flag guardian spec needs to clean state after evaluation. Each created flag is adding PostActionType.

FIX: flaky user_merger_spec.rb

---

app/assets/javascripts/discourse/app/lib/desktop-notifications.js
plugins/chat/assets/javascripts/discourse/initializers/chat-audio.js
plugins/chat/assets/javascripts/discourse/services/chat-audio-manager.js
plugins/chat/assets/javascripts/discourse/services/chat-channel-notification-sound.js
plugins/chat/assets/javascripts/discourse/services/chat-subscriptions-manager.js
plugins/chat/test/javascripts/unit/services/chat-channel-notification-sound-test.js

We consider that you should always receive a notification sound when someone speaks directly with you in chat.
This commit also refactors the way we play audio in chat to make it simpler and throttle it to 3 seconds.
We also added a safeguard to ensure we won't play sounds for old messages, this case can happen when message bus is catching up the backlog (eg: in an inactive tab for example).

UX: reduces idle time to 0 on chat

---

script/bulk_import/base.rb
script/bulk_import/generic_bulk.rb

* user_profiles - `location`
* users - `date_of_birth`
* topics - `pinned_at`, `pinned_until`, `pinned_globally`
This also includes changes to correctly import PMs. Currently PM topics are skipped because of a check in `import_users` step which requires `category_id` to be present.

DEV: Add support for various fields in generic bulk importer

---

app/models/user_email.rb
config/environments/test.rb
config/locales/server.en.yml
db/migrate/20150728210202_migrate_old_moderator_posts.rb
lib/archetype.rb
lib/freedom_patches/translate_accelerator.rb
plugins/automation/spec/requests/admin_discourse_automation_automations_spec.rb
plugins/automation/spec/serializers/automation_serializer_spec.rb
plugins/automation/spec/system/smoke_test_spec.rb
plugins/automation/spec/triggers/stalled_wiki_spec.rb
plugins/discourse-narrative-bot/spec/discourse_narrative_bot/track_selector_spec.rb
spec/jobs/check_translation_overrides_spec.rb
spec/jobs/regular/bulk_user_title_update_spec.rb
spec/lib/archetype_spec.rb
spec/lib/freedom_patches/translate_accelerator_spec.rb
spec/lib/js_locale_helper_spec.rb
spec/lib/plugin/instance_spec.rb
spec/lib/site_setting_extension_spec.rb
spec/models/incoming_links_report_spec.rb
spec/models/translation_override_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/requests/admin/site_texts_controller_spec.rb
spec/requests/extra_locales_controller_spec.rb
spec/requests/users_controller_spec.rb
spec/script/import_scripts/base_spec.rb
spec/services/badge_granter_spec.rb
spec/services/problem_check/translation_overrides_spec.rb
spec/support/i18n_helpers.rb

This configuration makes it so that a missing translation will raise an error during test execution. Better discover there than after deploy.

DEV: Catch missing translations during test runs

---

app/jobs/regular/emit_web_hook_event.rb
app/services/web_hook_emitter.rb
spec/requests/admin/web_hooks_controller_spec.rb

I added this modifier a bit ago in this commits https://github.com/discourse/discourse/commit/9264479c277467f9d82934e68448c39e878d736c
The issue is that when re-driving a failed webhook event, the headers are not modified again. Moving the modifier into the `WebHookEmitter` is nice b/c it allows for modifying headers on re-deliver. This adds to spec to make sure this case does work (redelivery) and ensures that modified headers are saved into the DB.

DEV: Move webhook event header modifier for redelivery-recalucation

---

plugins/chat/assets/javascripts/discourse/services/chat-channel-notification-sound.js
plugins/chat/test/javascripts/unit/services/chat-channel-notification-sound-test.js

Prior to this fix we were limiting this to 1:1 channels.

UX: also plays notification sounds in group channels

---

app/assets/javascripts/discourse/app/components/post-text-selection.gjs
app/assets/javascripts/discourse/app/lib/utilities.js
spec/system/post_selection_fast_edit_spec.rb

When selected some text inside a post, we offer the ability to "fast edit" the selected text without opening the composer.
However, there are certain cases where this isn't working quite a expected, due to the fact that we have some text in the "cooked" version of the post that isn't literally in the "raw" version of the post.
This ensures that whenever someone selects the within
- a quote
- a onebox
- an encrypted message
- a "cooked" date
we directly show the composer instead of showing the fast edit modal and then leaving the user with an invisible error.
Internal ref. t/128400

FIX: bypass fast edit when selected text isn't editable

---

plugins/chat/assets/javascripts/discourse/services/chat-notification-manager.js

The `onNotification` signature is:
```
onNotification(data, siteSettings, user, appEvents)
```
And we were not passing `appEvents`.
Also explicitly inject `currentUser` in `chat-notification-manager` service.

FIX: missing appEvents param for onNotification

---

app/models/user.rb
plugins/discourse-narrative-bot/plugin.rb

The `User#saw_notification_id` has been deprecated and replaced with `User#bump_last_seen_notification!`. It was marked for removal in 3.0.
According to both logs and a code search in public- and private GitHub organizations, there is only one remaining call site. This PR updates it one and removes the method.

DEV: Remove deprecated User#saw_notification_id method

---

app/assets/javascripts/discourse/app/lib/hashtag-autocomplete.js
spec/system/page_objects/components/topic_list_header.rb

Introduced in
https://github.com/discourse/discourse/commit/c7860173c1683fcbe33600d29b5294c0bb228253,
they are no longer necessary once https://github.com/discourse/discourse-encrypt/pull/317
is merged

DEV: Remove hashtag deprecations

---

config/unicorn.conf.rb
lib/freedom_patches/unicorn_http_server_patch.rb

This commit adds a `DISCOURSE_DUMP_BACKTRACES_ON_UNICORN_WORKER_TIMEOUT`
environment that will allow us to dump all backtraces for all threads of
a Unicorn worker 2 seconds before it times out. In development,
backtraces are dumped to `STDOUT` and in production we will dump it to
`unicorn.stdout.log`.
We want to dump all the backtraces to make it easier to identify the
cause of a Unicorn worker timing out.

DEV: Add `DISCOURSE_DUMP_BACKTRACES_ON_UNICORN_WORKER_TIMEOUT` env

---

lib/seed_data/topics.rb
spec/lib/seed_data/topics_spec.rb

Replacing the text of seeded topics doesn't require categories to exist, so this change removes that requirement for updates.

FIX: "Replace Text" didn't list "Welcome Topic" when "General" category is missing

---

app/models/post_timing.rb
app/models/topic_user.rb

This commit splits out the updating of `TopicUser#last_read_post_number` in `TopicUser.ensure_consistency!` to a new
`TopicUser.update_last_read_post_number` method which `PostTiming.pretend_read` will now call instead. Previously, `PostTiming.pretend_read` calls `TopicUser.ensure_consistency!` which in turn calls `TopicUser.update_post_action_cache` but that is unnecessary for `PostTiming.pretend_read` since `PostTiming.pretend_read` does not affect the `TopicUser#liked` or `TopicUser.bookmarked` columns which `TopicUser.update_post_action_cache` updates. As the query in `TopicUser.update_post_action_cache` can be expensive, we should avoid calling it when it isn't necessary.
One such scenario where it is unnecessary is when we are closing a topic.

PERF: `PostTiming.pretend_read` to not update `TopicUser` cache columns

---

spec/lib/plugin/instance_spec.rb

After flags are replaced, we need to bring the state back to the original. Otherwise, it causes flaky specs.

DEV: clean after replacing flags spec

---

app/controllers/application_controller.rb
lib/middleware/request_tracker.rb
spec/lib/middleware/request_tracker_spec.rb
spec/requests/application_controller_spec.rb

This PR moves the logic for crawler rate limits out of the application controller and into the request tracker middleware. The reason for this move is to apply rate limits to all crawler requests instead of just the requests that make it to the application controller. Some requests are served early from the middleware stack without reaching the Rails app for performance reasons (e.g. `AnonymousCache`) which results in crawlers getting 200 responses even though they've reached their limits and should be getting 429 responses.
Internal topic: t/128810.

FIX: Apply crawler rate limits to cached requests

---

plugins/chat/assets/stylesheets/common/chat-channel-members.scss

Fix for 
https://meta.discourse.org/t/very-long-real-names-overflow-the-member-list-for-chat-and-the-usercard/300264
Now:

UX: add text-overflow for channel members list

---

app/mailers/user_notifications.rb
spec/mailers/user_notifications_spec.rb

In https://github.com/discourse/discourse/commit/958437e7ddce6e015725522d25c3f8327ff4064a we ensured that the email summaries are properly sent based on 'digest_attempted_at' for people who barely/never visit the forum.
This fixed the "frequency" of the email summaries but introduced a bug where the digest would be sent even though there wasn't anything new since for some users.
The logic we use to compute the threshold date for the content to be included in the digest was
```ruby
@since = opts[:since] || user.last_seen_at || user.user_stat&.digest_attempted_at || 1.month.ago
```
It was working as expected for users who were never seen but for users who had connected at least once, we would use their "last_seen_at" date as the "threshold date" for the content to be sent in a summary 😬 …

FIX: correctly compute the window for email summaries

---

spec/rails_helper.rb
spec/system/email_change_spec.rb
spec/system/user_page/user_preferences_security_spec.rb

We are seeing a weird resolution error on Github actions with the
following backtrace:
```
Failure/Error:
visit File.join(
GlobalSetting.relative_url_root || "",
"/session/#{user.encoded_username}/become.json?redirect=false",
)
Socket::ResolutionError:
getaddrinfo: Temporary failure in name resolution
```
Switch to use `127.0.0.1` instead of forcing a name resolution.

DEV: Use `127.0.0.1` instead of `localhost` as Capybara's server host

---

app/assets/javascripts/discourse/app/controllers/application.js
spec/system/navigation_menu_state_integration_spec.rb

When navigation_menu is set to header dropdown, we are
still forcing admin sidebar by checking if the user is an
admin route (c.f. 9bcbfbba43b876ae92cb90d6d619be7b1154c119).
However in the initial commit the route check had the
false premise that all admin routes started with `admin.`;
there are others that don't. We need to force admin sidebar
on all routes starting with `admin` (no `.`).
c.f. https://meta.discourse.org/t/feedback-on-admin-sidebar-when-header-dropdown-navigation-selected/309490/3?u=martin

FIX: Admin sidebar disappeared on some routes for header dropdown

---

plugins/chat/plugin.rb

Chat messages are following normal post flags. 
This newly registered `:needs_review` score type is not used anymore

DEV: remove obsolete needs_review score type

---

spec/rails_helper.rb
spec/system/email_change_spec.rb
spec/system/user_page/user_preferences_security_spec.rb

This reverts commit 998b50fdf4b83383c9b8cbebdf606477f2a799a2.
Ended up making system tests even more unstable

Revert "DEV: Use `127.0.0.1` instead of `localhost` as Capybara's server host (#27215)"

---

lib/email/message_id_service.rb
spec/fixtures/emails/old_destination.eml
spec/lib/email/processor_spec.rb
spec/lib/email/receiver_spec.rb
spec/lib/imap/sync_spec.rb
spec/lib/message_id_service_spec.rb

Introduced back in 2022 in
https://github.com/discourse/discourse/commit/e3d495850d928150f569c7139f97bf5e9887ad1f,
our new more specific message-id format for inbound and
outbound emails has now been in use for a very long time,
we can remove the support for the old formats:
topic/:topic_id/:post_id.:random@:host
topic/:topic_id@:host
topic/:topic_id.:random@:host

DEV: Remove old TODOs for deprecated email Message-ID formats

---

app/controllers/embed_controller.rb

For some reason, despite iframe also indicating a
```
<meta name="robots" content="noindex">
```
.. Google is still indexing the embed/comment URLs. This causes links like http://\<site>/embed/comments\?topic_id\=6366 to be indexed instead of the topic.
This PR adds it explicitly in the header.

DEV: Also noindex embedded comments

---

app/assets/javascripts/discourse/app/modifiers/sticky-avatars.js

Previously, avatars would be 'sticky' when:
1. The post was longer than the viewport
OR
2. You were scrolling up
The difference in behavior based on scroll direction doesn't 'feel' quite right. This commit makes the behavior consistent, so sticky avatar logic is applied to all posts regardless of scroll direction.

UX: Make sticky avatars behavior consistent

---

app/assets/javascripts/discourse/app/lib/after-frame-paint.js

We need to register a waiter so that `settled()` will wait for `runAfterFramePaint()` callbacks to be run before proceeding.

DEV: Allow afterFramePaint to be used in tests

---

app/assets/javascripts/discourse/app/lib/after-frame-paint.js

This reverts commit 63b7b598cb9cd93e90e447fea24f2f517c2592c5.
Causing issues in production builds

Revert "DEV: Allow afterFramePaint to be used in tests (#27226)"

---

app/assets/javascripts/discourse/app/components/discourse-topic.js
app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/header/auth-buttons.gjs
app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/routes/topic-from-params.js
app/assets/javascripts/discourse/app/services/header.js

We currently have a tracked value of `topic` in the header service that we utilize across the app for determining the presence of a topic.
A simple example is: If you are in a topic, and scroll down the page, we need to communicate to the header that a topic is present and we change the styling of the header. 
The issue with this logic is that when entering a topic (and you are at the top of the page), we **haven't** set the topic on the header service yet. We only set the topic when you have scrolled down on the page (set by `app/components/discourse-topic.js`) 
This is unhelpful behavior when you are utilizing a plugin outlet that is receiving the `topic` from the header: 
https://github.com/discourse/discourse/blob/17add599e3cf7323ee8639286e6ab1876ef90474/app/assets/javascripts/discours …

DEV: Update how we determine the presence of a topic in the header

---

plugins/spoiler-alert/assets/javascripts/initializers/spoiler-alert.js
plugins/spoiler-alert/test/javascripts/unit/lib/to-markdown-test.js

Was "removing" (rather not re-applying) the `[spoiler]` BBCode because we were testing the **whole** class of the `span`/`div` was `spoiled` but we added another class and thus broke this functionnality.
In order to fix this issue, the test to determine whether a `span`/`div` is a spoiler, now uses a regular expression to check whether the `class` **contains** the word `spoiled`.
Also slightly improved the `toMarkdown` of the block version of a spoiler to add newlines after the opening `[spoiler]` tag and before the closing `[/spoiler]` tag.
Reference - https://meta.discourse.org/t/quoting-spoiler-text-doesnt-include-spoiler-tags-in-the-quote/170145

FIX: quoting a spoiler

---

app/assets/javascripts/discourse/app/components/discourse-topic.js
app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/header/auth-buttons.gjs
app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/routes/topic-from-params.js
app/assets/javascripts/discourse/app/services/header.js

This reverts commit caa29ec97351f1443f7be9560187116f045b820b. (#27138)
The reverted commit introduced an issue where`header.topic` is not being cleared when leaving the topic to another route.
Unfortunately, just setting it to `null` on the route's `deactivate` method causes the `Header::Info` component to crash.
Reverting it for now until we can review the commit and tests to avoid introducing more bugs.

Revert "DEV: Update how we determine the presence of a topic in the header (#27138)"

---

config/unicorn.conf.rb

This commit updates various spots in `config/unicorn.conf.rb` which were
doing `STDERR.puts` to either use `server.logger` which is unicorn's
logger or `Rails.logger` which is Rails' logger. The reason we want to
do so is because `STDERR.puts` doesn't format the logs properly and is a
problem especially when custom loggers with structured formatting is
enabled.
Also we are missing critical logging information like timestamp when we simply use `STDERR.puts`. A logger usually attaches the timestamp when it logs the message.

DEV: Use existing loggers for stuff we log in `config/unicorn.conf.rb`

---

app/assets/javascripts/discourse/app/components/deferred-render.gjs
app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.gjs

Rendering sidebar sections is costly due to 1. the popper and 2. the number of sections that may be displayed.
This PR introduces a `DeferredRender` which allows us to split the time to paint both.
Before:
https://github.com/discourse/discourse/assets/1555215/1eee16c9-8439-426a-8dec-47d6ac229962
After:
https://github.com/discourse/discourse/assets/1555215/c872aee9-9875-4de5-9812-5d8759baa32c

DEV: Delay rendering sidebar sections after sidebar is shown

---

config/unicorn.conf.rb
lib/demon/sidekiq.rb

This commit updates all Sidekiq signal handling event logs to go through
Unicorn's logger instead of logging to STDOUT. Going through a proper logger
means the log messages are logged in the format which the logger has configured.
This means we get proper timestamp for the log messages.

DEV: Use Unicorn logger to log Sidekiq signal handling events

---

app/assets/javascripts/admin/addon/components/admin-plugin-filtered-site-settings.gjs
app/assets/javascripts/admin/addon/components/admin-site-settings-filter-controls.gjs
app/assets/javascripts/admin/addon/controllers/admin-plugins-show-settings.js

When typing slowly in the admin setting filter input,
we were losing characters after the debounce. This commit
changes to use native <input /> instead of the ember
<Input /> component similar to the change in
bfd6a7b86c094ea41617bcb3477353baf08b50a9
c.f https://meta.discourse.org/t/settings-filter-loses-some-of-the-letters-you-entered/305201

FIX: Admin setting search debounce losing characters

---

lib/discourse.rb

Just logging the error message is useless if we don't know where the
error message is raised from.

DEV: Log backtrace along with the error

---

plugins/chat/assets/javascripts/discourse/components/chat-footer.gjs
plugins/chat/assets/javascripts/discourse/components/chat/footer/unread-indicator.gjs
plugins/chat/assets/stylesheets/common/base-common.scss
plugins/chat/assets/stylesheets/common/chat-footer.scss
plugins/chat/assets/stylesheets/mobile/chat-footer.scss
plugins/chat/spec/system/chat_footer_spec.rb

A few follup changes after changing to the chat footer split for drawer:
* Fixing a bug that stretched the unread indicator on mobile
* Minor style changes in hover/focus behaviour for chat drawer
* Repositioning of unread indicator so it has more space at the top of the footer
* Using the `c-unread-indicator` mixin

UX: Chat footer unread indicator

---

script/discourse

Adds the “s3_uploads” option (default: false) to the discourse backup script, which temporarily forces the inclusion of S3 uploads in the backup.
Also removed all unnecessary “require” statements as loading Rails is sufficient.
The rest of the changes were made by the linter.
_No tests since there aren't any for this small CLI that ends up using already tested code._

FEATURE: Add “s3_uploads” option to “discourse backup” script

---

plugins/chat/assets/javascripts/discourse/components/chat/modal/delete-channel.gjs

Under some circumstances, the TextField component could trigger a `Assertion Failed: You attempted to update attrs on ..., but it had already been used previously in the same computation...` error, causing the Ember app to crash.

DEV: Prevent possible Ember rendering error on Chat::DeleteChannel modal

---

app/assets/javascripts/discourse/app/components/modal/reorder-categories.hbs
app/assets/javascripts/discourse/app/components/modal/reorder-categories.js
app/assets/javascripts/select-kit/addon/components/categories-admin-dropdown.js
app/assets/stylesheets/common/base/reorder-categories.scss

This modal wasn't trapping focus for keyboard a11y, so `focusAfterOnChange: false,` fixes that. 
I've also fixed the layout and added a highlight on move to make changes a little more apparent. 
Before:
After:
https://github.com/discourse/discourse/assets/1681963/7cc327f3-83b2-4a7c-859a-3b9ed5e95472

UX: minor categories reorder fixes

---

config/locales/server.en.yml

The new admin sidebar navigation is the new default, so no longer considered experimental. Though still actively being improved at the moment!

Removed EXPERIMENTAL from new admin sidebar setting desc

---

app/models/upload.rb
lib/s3_inventory.rb
lib/tasks/uploads.rake
spec/lib/s3_inventory_spec.rb
spec/models/upload_spec.rb

This commit introduces the following changes which allows a site administrator to mark `Upload` records with the `s3_file_missing` verification status which will result in the `Upload` record being ignored when `Discourse.store.list_missing_uploads` is ran on a site where S3 uploads are enabled and `SiteSetting.enable_s3_inventory` is set to `true`.
1. Introduce `s3_file_missing` to `Upload.verification_statuses`
2. Introduce `Upload.mark_invalid_s3_uploads_as_missing` which updates `Upload#verification_status` of all `Upload` records from `invalid_etag` to `s3_file_missing`.
3. Introduce `rake uploads:mark_invalid_s3_uploads_as_missing` Rake task which allows a site administrator to change `Upload` records with `invalid_etag` verification status to the `s3_file_missing` …

DEV: Allow site administrators to mark S3 uploads with a missing status

---

app/controllers/users_controller.rb

The `UsersController#modify_user_params` method is deprecated and replaced with a plugin modifier (`users_controller_update_user_params`). It is marked for removal in 3.2. This PR removes it.

DEV: Remove deprecated UsersController#modify_user_params method

---

app/assets/javascripts/discourse/app/components/sidebar/filter.gjs
app/assets/stylesheets/common/base/sidebar.scss
config/locales/client.en.yml

This adds a small indicator of the Ctrl+/ shortcut that
exists for the admin sidebar filter, since it's not very
obvious that you can do that. This should help people
who are struggling with the long list of links -- it's
much faster to use the keyboard and search for what
you are looking for.

UX: Show shortcut for admin sidebar filter

---

plugins/chat/app/controllers/chat/api/channel_thread_messages_controller.rb
plugins/chat/app/services/chat/list_channel_thread_messages.rb
plugins/chat/lib/chat_sdk/thread.rb
plugins/chat/spec/requests/chat/api/channel_thread_messages_controller_spec.rb
plugins/chat/spec/services/chat/list_channel_thread_messages_spec.rb

Before this fix we could only list messages of a thread if it was part of a `threading_enabled` channel or if the thread was set to `force`.
Due to our design of also using a thread id when this is just a chain of replies so we can switch from threading enabled to disabled at any time, we will allow `Chat:: ListChannelThreadMessages` to list the messages of any thread, the only important requirements are:
- having a thread id
- being able to access this thread
To allow this, this commit simply removes the check on `threading_enabled` or `force.

FIX: allows listing messages of any thread

---

app/assets/stylesheets/common/components/badges.scss

Follow-up to 5c09792
This needs a slight adjustment, otherwise badge splits are slightly off for subcategories 
Get your 🔎 out 😜 
Before:
After:

UX: adjust category badge size for new default font-size

---

app/assets/stylesheets/common/base/topic-post.scss

UX: contain background for deleted small actions

---

app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/search-menu.scss

Also removing a little bit of dead `.hamburger-panel` css
Before:
After:

UX: keep recent search items on same line as icon

---

app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/search-menu.scss

This was making the hamburger menu un-scrollable on mobile.

REVERT: UX: keep recent search items on same line as icon (#27264)

---

plugins/chat/assets/stylesheets/common/chat-transcript.scss

Code can cause the transcripts to be too wide, this allows the container to shrink to fit. 
Before:
After:

UX: constrain width of chat transcripts in posts

---

app/assets/javascripts/discourse/app/components/bulk-select-topics-dropdown.gjs
spec/system/page_objects/components/topic_list_header.rb
spec/system/topic_bulk_select_spec.rb

Prior to this fix we were opening a modal before closing the `DMenu` modal, given `DModal` expects only one modal at a time it was closing the latest modal and instantly closing the one we just opened.

FIX: ensures bulk-select is correctly working on mobile

---

app/assets/javascripts/discourse/app/controllers/user-private-messages.js

The issue was simple, we were just not returning the helper in the `user-private-messages` controller which was preventing any action to happen.
Follow up: we should write specs for this toggle.
Internal: t/-/128853

FIX: ensures bulk-select on messages page is working

---

spec/rails_helper.rb

We have been seeing flaky socket resolution errors on CI and need more
debugging information to figure out why

DEV: puts debugging information when CI encounters resolution errors

---

app/models/category.rb
app/models/permalink.rb
app/models/tag.rb
app/models/user.rb
spec/models/permalink_spec.rb

* REFACTOR: All kinds of permalinks should return relative URLs
Mixing relative and absolute URLs is unnecessary and confusing.
* FIX: Permalinks with external URL didn't work with subfolders
* FIX: Store special characters in permalink URL as encoded characters 
see https://meta.discourse.org/t/permalink-not-working-with-cyrilics-symbols/301130

Improve permalinks

---

app/assets/javascripts/discourse/app/components/header/topic/info.gjs

FIX: Restore cmd+click ability in topic-info

---

plugins/chat/assets/stylesheets/common/chat-message-images.scss

TikTok embeds are vertical and not resizable. We need to allow them to have a greater height than other embeds. This is still under the experimental site setting `lazy_tiktok_enabled`, which is disabled by default.

FIX: Lazy TikTok embeds height in chat

---

app/assets/javascripts/discourse/app/components/sidebar/api-section.gjs
app/assets/javascripts/discourse/app/components/sidebar/filter.gjs
app/assets/javascripts/discourse/app/components/sidebar/section.gjs
app/assets/javascripts/discourse/app/services/sidebar-state.js
spec/system/admin_sidebar_navigation_spec.rb

Even when the admin sidebar sections are collapsed, they should expand while filtering. When the filter is removed, sections should go back to the previous state.
In addition, trim whitespace from the filter section.
https://github.com/discourse/discourse/assets/72780/c4b1a649-f335-4bca-afb2-edcd40531c40

FEATURE: expand the admin sidebar when filtering

---

app/assets/stylesheets/common/base/search-menu.scss

Trying to normalize some things here:
* Fix missing space between category and tag
* Fix category names smaller than tags
* Fix general group alignment
* I made this more consistent by giving groups without flair some padding and a background color on the icon 
Before|After

UX: improve search result consistency

---

app/controllers/session_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/models/user_password.rb
app/services/user_password_expirer.rb
config/locales/server.en.yml
db/migrate/20240603234529_create_user_passwords.rb
lib/validators/password_validator.rb
spec/fabricators/user_password_fabricator.rb
spec/lib/validators/password_validator_spec.rb
spec/models/user_password_spec.rb
spec/requests/session_controller_spec.rb
spec/services/user_password_expirer_spec.rb
spec/system/login_spec.rb

This commit adds the ability for site administrators to mark users'
passwords as expired. Note that this commit does not add any client side
interface to mark a user's password as expired.
The following changes are introduced in this commit:
1. Adds a `user_passwords` table and `UserPassword` model. While the
`user_passwords` table is currently used to only store expired
passwords, it will be used in the future to store a user's current
password as well.
2. Adds a `UserPasswordExpirer.expire_user_password` method which can
be used from the Rails console to mark a user's password as expired.
3. Updates `SessionsController#create` to check that the user's current
password has not been marked as expired after confirming the
password. If the password is determined to be expired based on the …

FEATURE: Allow site admin to mark a user's password as expired

---

app/assets/javascripts/discourse/app/components/modal/login.hbs
app/assets/javascripts/discourse/app/components/modal/login.js
app/controllers/session_controller.rb
config/locales/client.en.yml
config/locales/server.en.yml
spec/requests/session_controller_spec.rb
spec/system/login_spec.rb

This makes it more obvious what's happening, and makes it much less likely that users will send repeated reset emails (and thereby hit the rate limit)
Followup to e97ef7e9af60788f5761f6989ea2b70edaa3b79d

UX: Use regular reset-password flow for expired passwords

---

.github/workflows/tests.yml
lib/tasks/themes.rake

Previously "themes frontend" CI job would:
1. pull compatible versions of themes that happened to be in the base image
2. clone all official themes (overriding the compatible versions from 1.)
3. run tests

DEV: Fix the order of operations in themes-frontend

---

.github/workflows/tests.yml
lib/tasks/themes.rake

Previously "themes frontend" CI job would:
1. pull compatible versions of themes that happened to be in the base image
2. clone all official themes (overriding the compatible versions from 1.)
3. run tests

DEV: Fix the order of operations in themes-frontend (stable)

---

app/assets/stylesheets/common/base/history.scss

UX: add space between revision avatar and username

---

app/assets/javascripts/admin/addon/components/secret-value-list.js
app/assets/javascripts/admin/addon/components/simple-list.js
app/assets/javascripts/admin/addon/components/site-text-summary.js
app/assets/javascripts/admin/addon/components/value-list.js
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/app/models/user-posts-stream.js

Fixes a deprecation warning introduced in a64f021f4984a7120a4a3fd95932df150c2dcfd1 and removes all uses of `@on` in native classes. (those are unnecessary)

DEV: Remove uses of `@on` from native classes

---

app/assets/stylesheets/common/components/user-stream-item.scss

excerpt content is mostly rendered inline to be shorter, so the large emojis in posts (within tables and other elements) don't really work 
before:
after:

UX: fix only-emoji size in user-stream excerpts

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
spec/system/admin_sidebar_navigation_spec.rb

Before, users link was in the community section.

UX: move users link to the top of the admin sidebar

---

app/assets/javascripts/discourse/app/mixins/password-validation.js
app/assets/javascripts/discourse/tests/acceptance/password-reset-test.js
app/assets/javascripts/discourse/tests/unit/components/create-account-test.js
config/locales/client.en.yml

Followup 0434112aa71fc091583d8356a84fbf958f7228fb,
when I introduced the pluralisation for the
password.too_short message I didn't change the
key name to `count`, which is necessary.

FIX: Pluralisation for short password count

---

app/services/user_password_expirer.rb
spec/services/user_password_expirer_spec.rb

This commit updates the `UserPasswordExpirer.expire_user_password`
method to update `UserPassword#password_expired_at` when an existing
`UserPassword` record exists with the same `password_salt`,
`password_hash` and `password_algorithm`. This is to prevent the unique
validation error on `UserPassword#user_id` and
`UserPassword#password_hash` from being raised when the method is called
twice for a user that has not changed its password.

DEV: Avoid unique validation in `UserPasswordExpirer.expire_user_password`

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-tooltip-test.js
app/assets/javascripts/discourse/tests/integration/components/user-info-test.js

Followup to 26198fb32817c6df336ea20e6d234f0f58d663da
also removes superfluous whitespace

DEV: Fix invalid hbs syntax in tests

---

lib/plugin_gem.rb

> Platform names with a *-linux suffix are aliases for *-linux-gnu
Should fix the ffi upgrade issue

DEV: Search for `-gnu` gem variants

---

.github/workflows/tests.yml

script/get_github_workflow_run_job_id.rb would fail on forks anyway

DEV: Run flake check only on discourse/discourse

---

app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/templates/password-reset.hbs
spec/system/login_spec.rb

The current password reset on 2FA accounts is not showing when the OTP is invalid before you actually submit your password.
Repro:
- add TOTP to a user account
- log out
- start password reset process
- enter wrong TOTP code when asked
- :boom: you see the password input when you should have seen an error and stay on the OTP input step

FIX: ensures invalid OTP blocks submit

---

spec/services/reorder_flag_spec.rb
spec/services/toggle_flag_spec.rb
spec/system/admin_flags_spec.rb

When flags are modified, we always need to reset the state to the original values.

DEV: flaky flags specs

---

db/fixtures/003_flags.rb
db/migrate/20240606003822_reorder_flags.rb
spec/models/flag_spec.rb
spec/services/reorder_flag_spec.rb
spec/system/admin_flags_spec.rb

The mistake was made when flags were moved to the database. The `notify_moderators` (something else) flag should be the last position on the list.
This commit contains 3 changes:
- update fixtures order;
- remove position and enable from fixtures (they can be overridden by admin and we don't want seed to restore them);
- migration to fix data if the order was not changed by admin.

FIX: move something else flag to the bottom

---

app/assets/javascripts/discourse/app/components/modal/login.hbs
app/assets/javascripts/discourse/app/components/modal/login/local-login-form.hbs
app/assets/javascripts/discourse/app/components/second-factor-form.hbs
app/assets/javascripts/discourse/app/components/second-factor-form.js
app/assets/javascripts/discourse/app/components/security-key-form.js
app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/routes/password-reset.js
app/assets/javascripts/discourse/app/templates/email-login.hbs
app/assets/javascripts/discourse/app/templates/password-reset.hbs
app/controllers/session_controller.rb
spec/requests/session_controller_spec.rb
spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb
spec/system/login_spec.rb
spec/system/page_objects/pages/user_reset_password.rb
spec/system/user_page/user_preferences_security_spec.rb

This commit fixes a problem where the user will not be able to reset
their password when they only have security keys and backup codes
configured.
This commit also makes the following changes/fixes:
1. Splits password reset system tests to
`spec/system/forgot_password_spec.rb` instead of missing the system
tests in `spec/system/login_spec.rb` which is mainly used to test
the login flow.
2. Fixes a UX issue where the `Use backup codes` or `Use authenticator
app` text is shown on the reset password form when the user does
not have either backup codes or an authenticator app configured.

FIX: User can't reset password with backup codes when only security key is enabled

---

plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/members.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/settings.gjs
plugins/chat/assets/javascripts/discourse/components/chat/modal/edit-channel-name.gjs
plugins/chat/assets/javascripts/discourse/components/chat/routes/channel-info-nav.gjs
plugins/chat/assets/javascripts/discourse/components/chat/routes/channel-info.gjs
plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js
plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js
plugins/chat/assets/stylesheets/desktop/chat-index-drawer.scss
plugins/chat/spec/system/drawer_spec.rb
plugins/chat/spec/system/page_objects/chat_drawer/chat_drawer.rb

This change allows chat drawer users to edit channel settings and members without leaving drawer mode. If a channel is open within chat drawer and the user clicks the Channel name, it will load channel settings within the drawer.
Previously we forced users into opening chat settings in fullscreen mode which wasn't ideal.
Chat Drawer with Settings:
Chat Drawer with Members:

FEATURE: load chat channel settings within drawer

---

app/assets/javascripts/admin/addon/components/admin-config-area-card.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/contact-information.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/general-settings.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/your-organization.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/about.gjs
app/assets/stylesheets/common/admin/admin_config_area.scss
config/locales/client.en.yml

This PR introduces the initial UI for the admin config area for the /about page. The UI isn't wired yet and doesn't do anything yet, but we're going to iterate on it in future PRs.
Screenshot:

DEV: Initial UI for admin config area for /about

---

app/assets/javascripts/discourse/app/lib/tracked-tools.js
app/assets/javascripts/discourse/tests/unit/lib/tracked-tools-test.gjs

For cases where you'd be using a TrackedSet to render something and then modifying that set throughout the same render cycle. (specifically it will be used in #27365)

DEV: Implement `DeferredTrackedSet`

---

app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.js
app/assets/javascripts/discourse/app/helpers/age-with-tooltip.js
app/assets/javascripts/discourse/app/lib/formatter.js

The redundant dates in title are not useful, we should describe the button functionality instead.
Before:
After:

UX: improve topic timeline date titles

---

app/assets/javascripts/discourse/app/components/discovery/topics.hbs
app/assets/stylesheets/desktop/topic-list.scss

Solves this issue by adding a class to `.contents` when the education footer message is present: https://meta.discourse.org/t/new-or-unread-topics-banners-cover-text-at-new-unread/301669
Before:
After:
Mobile's new/unread banner shifts content down to accommodate, so there's no change there.

UX: create space for new topics banner on /new, /unread

---

spec/services/toggle_flag_spec.rb

Because the flag was not reloaded and contained old values, `update! `was not triggered and didn't clean flags to the original state.

FIX: flaky specs related to flags

---

plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js

This change prevents explicitly declaring each route that should be intercepted for chat drawer mode.
In theory all chat drawer routes should be intercepted from the main chat routes file and therefore we would only need to add new drawer routes directly within `chat-drawer-router.js`.

DEV: prevent duplication of chat drawer routes

---

app/controllers/admin/users_controller.rb

In some admin user controller extensions, `@user` is used to derive certain values.
The `grant_admin` method requires `@user` as well, so we are adding it here. This is tested in the plugin that it is used in. (see below)

DEV: Also fetch user when granting admin

---

app/controllers/admin/users_controller.rb

Related: https://github.com/discourse/discourse/pull/27382
> In some admin user controller extensions, @user is used to derive certain values.
>
> The grant_admin method requires @user as well, so we are adding it here. This is tested in the plugin that it is used in. (see below)

DEV: Also fetch user when granting admin (stable)

---

plugins/automation/spec/requests/admin_discourse_automation_automations_spec.rb
plugins/automation/spec/serializers/automation_serializer_spec.rb

When adding custom translations for tests using `I18n.backend.store_translations`,
we need to remove the custom translations at the end of each test to
prevent the custom translations from leaking to other tests.

DEV: Clean up state to prevent flaky tests

---

spec/rails_helper.rb

This is a follow up to 9ff0805a1de5695982b0dd5464e6786764fd94b3. We
noticed that `localhost` can fail to resolve in other spots of the app
and not just in selenium-webdriver.
From the failing tests we have seen, the `getaddrinfo: Temporary failure in name resolution` error is only
seen from within the `Capybara.using_session` block. This commit aims to
ensure that `localhost` can be resolve after the new session is started.

DEV: Monkey patch `Capybara.using_session` to resolve `localhost` in CI

---

spec/support/fake_s3.rb

When running ` rspec spec/services/external_upload_manager_spec.rb`
in the development environment, tests were failing with the following
error:
```
NameError:
uninitialized constant FakeS3::Aws
```

DEV: Fix missing require in `spec/support/fake_s3`

---

lib/plugin/metadata.rb

Removes BCC, Shared Edits, and Linkedin-auth from the official plugin list. 
Also corrects some alphabetising

Remove non-official plugins

---

plugins/chat/assets/javascripts/discourse/components/chat/routes/channel-info-settings.gjs
plugins/chat/assets/stylesheets/common/chat-drawer.scss

Now that we can access the settings page in desktop drawer, there was an adjustment needed to keep the button at the bottom, which looks better for short pages:
VS

UX: make chat drawer settings page full height

---

app/serializers/hidden_profile_serializer.rb
plugins/chat/plugin.rb
plugins/chat/spec/requests/core_ext/users_controller_spec.rb
spec/requests/users_controller_spec.rb

Allows displaying the Chat/Message buttons on the user's profile even when the user has their public profile hidden
<div align=center>
</div>

UX: Show message and chat buttons on hidden profiles

---

lib/html_to_markdown.rb
spec/lib/html_to_markdown_spec.rb

This PR contains multiple commits to make the changes easier to understand.
* **DEV: Add `additional_allowed_tags` to `HtmlToMarkdown`**
Import script often use subclasses of `HtmlToMarkdown` and might need to allow additional tags that can be used within the custom class.
* **FEATURE: Use basic HTML table if it can't be converted to Markdown**
Previously, `HtmlToMarkdown` always converted HTML tables into Markdown tables. That lead to some badly formatted Markdown tables, e.g. when the table contained `rowspan` or `colspan`. This solves the issue by using very basic HTML tables in those cases.
* **FIX: `HtmlToMarkdown` didn't support `tfoot` in tables**
* **FIX: `HtmlToMarkdown` didn't keep text from within `<center>` tag**
It should ignore the `<center>` tag, but keep the text from …

Improve `HtmlToMarkdown`

---

plugins/chat/assets/javascripts/discourse/routes/admin-plugins-chat.js
plugins/chat/plugin.rb
plugins/chat/spec/plugin_spec.rb
plugins/chat/spec/requests/chat/admin/incoming_webhooks_controller_spec.rb

In 4e7a75a7ece3205ce9f3f188b5e016bf75a869c0, we moved to a single admin plugin page and added a few fields to the "plugin serializer" but we already had a proper route with the correct serializers to properly load channels.
This fixes it by removing the "add_to_serializer" calls and changed the calls to "/admin/plugins/chat.json" to the proper "/admin/plugins/chat/hooks.json" route.
Meta - https://meta.discourse.org/t/names-are-missing-from-list-when-creating-new-chat-channel-webhooks/308481

FIX: correctly load channels in chat webhooks

---

app/assets/javascripts/discourse/app/components/header/home-logo-contents.gjs
app/assets/javascripts/discourse/app/components/header/home-logo.gjs

This PR extracts the content of the `HomeLogo` to a standalone component. This enables us to utilize the `home-logo-contents` plugin outlet to render an alternative version of the logo using the new component to reuse the rendering logic, but using alternative properties. For example:
```js
const logoSmallUrl = settings.theme_uploads["theme-alternative-logo-small"];
const logoUrl = settings.theme_uploads["theme-alternative-logo"];
const mobileLogoUrl = settings.theme_uploads["theme-alternative-logo"];
api.renderInOutlet("home-logo-contents", <template>
<HomeLogoContents
@logoSmallUrl={{logoSmallUrl}}
@logoUrl={{logoUrl}}
@minimized={{@outletArgs.minimized}}
@mobileLogoUrl={{mobileLogoUrl}}
@showMobileLogo={{@outletArgs.showMobileLogo}}
@title={{@outletArgs.title}}
/>
</template>);
```
The …

DEV: Extract the contents of the home logo to a component

---

plugins/discourse-local-dates/assets/stylesheets/common/discourse-local-dates.scss

surprised this hasn't come up sooner 
before:
after:

UX: allow cooked local-dates to wrap

---

app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
app/services/topic_status_updater.rb
lib/topics_bulk_action.rb

We were using `autoclose` as the topic status update
when silently closing topics using the bulk
actions (introduced in https://github.com/discourse/discourse/commit/0464ddcd9b377d8249d8a3c15cfe91d7a8e97bfc).
However, this resulted in a message like this showing in
the topic as a small moderator post:
> This topic was automatically closed after X days.
This is not accurate, the topic was bulk closed by someone.
Instead, we can use `closed` as the status, and a more accurate
> Closed on DATE
message is used. `TopicStatusUpdater` needed an additional
option to keep the same "fake read" behaviour as autoclose
so we can keep the same functionality for silently closing
topics in bulk actions.

FIX: Message for bulk closing topics silently

---

lib/demon/sidekiq.rb

We are seeing the following error in our logs when Sidekiq is sent a
`USR1` signal in production when logrotate happens:
```
log writing failed. stream closed in another thread
Error encountered while starting Sidekiq: can't be called from trap context\n/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/unicorn-6.1.0/lib/unicorn/util.rb:71:in `reopen'
```
I'm not quite sure where the error is triggered from so I'm improving
the way we log errors.

DEV: Log error encountered when reopening sidekiq logs

---

spec/rails_helper.rb

This commit tries another work around for the `Socket::ResolutionError: getaddrinfo: Temporary failure in name resolution`
error we are seeing on CI.
The problem with the previous workaround is that `Capybara.using_session` will attempt to resolve `localhost`
before yielding the block which means our retry code is not hit.
This problem may be related to https://bugs.ruby-lang.org/issues/20172
which hints at us potentially not being able to spin up threads on CI so
I'm adding a debugging statement when stuff fails.

DEV: Try another workaround for `getaddrinfo: Temporary failure in name resolution`

---

app/assets/javascripts/discourse/app/components/group-card-contents.js
app/assets/javascripts/discourse/app/components/search-result-entry.js
app/assets/javascripts/discourse/app/components/topic-list/featured-topic.gjs
app/assets/javascripts/discourse/app/components/user-card-contents.js
app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/controllers/topic.js
app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js

It was added when removing `{{action}}` modifiers from the app, but we already had `wantsNewWindow` so use that instead.

DEV: Remove `modKeysPressed`

---

lib/http_user_agent_encoder.rb
lib/middleware/anonymous_cache.rb
lib/middleware/request_tracker.rb
spec/lib/middleware/anonymous_cache_spec.rb
spec/lib/middleware/request_tracker_spec.rb

Meta: https://meta.discourse.org/t/encoding-conversion-error-from-ascii-8bit-to-utf-8-in-logs/308603/2
Crawler requests for non-UTF-8 user agents that contain invalid bytes generate an exception at two places.
See [`get_data()`](https://github.com/discourse/discourse/blob/main/lib/middleware/request_tracker.rb#L158-L193) function:
* On `encode("utf-8")` that results either in the following error depending on the incoming encoding
* `InvalidByteSequenceError`
* `UndefinedConversionError`
* On matching user-agent with invalid byte results to `ArgumentError`.
_Called from `helper.is_crawler` and `helper.is_mobile`, part of the `AnonymousCache::Helper` class._
This PR does the following:
* Handles `encode()` exceptions by relying on `undef` and `invalid` params to replace the faulty bytes …

FIX: Crawler requests exceptions for non UTF-8 user agents with invalid bytes

---

app/assets/stylesheets/common/modal/login-modal.scss

Before: 
After: 
Before:
After (social logins are hidden by scroll, but better than a broken form for now):

UX: improve login modal on very narrow screens in desktop mode

---

.github/workflows/tests.yml

script/get_github_workflow_run_job_id.rb would fail on forks anyway

DEV: Run flake check only on discourse/discourse (stable)

---

app/assets/stylesheets/common/select-kit/category-drop.scss
app/assets/stylesheets/common/select-kit/tag-drop.scss

This commits add a border + text colour when a tag or category breadcrumb has been selected to indicate the filter is active.

UX: add active highlight for breadcrumb navigation

---

app/assets/javascripts/discourse/tests/integration/components/select-kit/tag-drop-test.js
app/assets/javascripts/select-kit/addon/components/tag-drop.js
config/locales/client.en.yml

This matches the category dropdown updates done as part of category scaling work 
before:
after:
for consistency with category dropdown,

UX: update "all tags" to "remove filter" for tag breadcrumb dropdown

---

app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/javascripts/float-kit/addon/lib/d-tooltip-instance.js

Previously it would leave a thin line hanging (that was an empty `#user-card` element)

FIX: Properly close user-card after page transition

---

spec/lib/discourse_ip_info_spec.rb

This is a follow-up to 781a5f60eae93eade4ee62bf63e537c94090a51e

DEV: Fix broken `discourse_ip_info_spec`

---

app/controllers/admin/web_hooks_controller.rb
spec/requests/admin/web_hooks_controller_spec.rb

After working on the [Webhook events filter by Status](https://github.com/discourse/discourse/pull/27332), I noticed that the 'Delivered' and 'Failed' options do not take the status param when loading more than fifty Webhook events. It causes to load all Webhook events regardless of its status after the first load.  
This PR is adding webhook events status for the filter to the param when loading more than fifty Webhook events.

FIX: fix Webhook events filter 'loadMore' not taking params

---

lib/discourse_logstash_logger.rb

Logging events happen all the time. No need for us to keep running code
to fetch the hostname when it doesn't change between deploys.

PERF: Cache `hostname` in `DiscourseLogstashLogger`

---

lib/search.rb
spec/lib/search_spec.rb

This introduces the syntax of
`category:a,b,c` which will search across multiple categories.
Previously there was no way to allow search across a wide selection of
categories.

FEATURE: align with /filter and allow multiple category search

---

app/models/user_field.rb
db/migrate/20240612063735_add_field_type_enum_to_user_fields.rb

Currently this column is a text column, but by right should only take on one of the values text, confirm, dropdown, multiselect. We can convert this to an ActiveRecord enum instead.
This PR adds a new integer column (`field_type_enum`) and populates it based on the existing text column (`field_type`) and adds an alias to replace the latter with the former.
In the next PR we can drop the text column and rename the integer column to replace it.

DEV: Change UserField#field_type to an ActiveRecord enum - Part 1

---

app/models/user_field.rb
db/post_migrate/20240612073116_swap_field_type_with_field_type_enum_on_user_fields.rb

Follow up to: #27444. In that PR we added a new integer column for `UserField#field_type` and populated the data based on the old text field.
In this PR we drop the old text column and swap in the new integer (enum) column.

DEV: Change UserField#field_type to an ActiveRecord enum - Part 2

---

app/models/theme_setting.rb
spec/models/theme_setting_spec.rb

FIX: Use the proper i18n argument name

---

app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/javascripts/float-kit/addon/lib/d-tooltip-instance.js

This reverts commit 1ecfc397d36536795824d5b46d7687a5f76778f4.

Revert "FIX: Properly close user-card after page transition (#27423)"

---

lib/email/sender.rb
spec/lib/email/sender_spec.rb

In #26642 we introduced a change that re-attaches securely uploaded images in the digest e-mail. However, this change assumed that the `type` argument to the `Email::Sender` constructor would be a symbol, but when it is coming from the `UserEmail` job it is a string. This PR fixes that.

FIX: Email::Sender expects type to be a string

---

config/discourse_defaults.conf
config/initializers/100-sidekiq.rb
lib/sidekiq_long_running_job_logger.rb
spec/lib/sidekiq_long_running_job_logger_spec.rb

This commits introduces the `sidekiq_report_long_running_jobs_minutes`
global setting which allows a site administrator to log a warning in the
Rails log when a Sidekiq job has been running for too long.
The warning is logged with the backtrace of the thread that is
processing the Sidekiq job to make it easier to figure out what a
sidekiq job is stuck on.

DEV: Add ability to log a warning when Sidekiq job runs for too long

---

lib/tasks/admin.rake
lib/tasks/users.rake

While doing some work on the `discourse-k8s-operator` charm, functionality that I would expect to be covered in the rake tasks is not present. Notably, to create a non-admin user, we must interface with the `admin:create` task, and select specific parameters to ensure that a user is created with the correct permission level. This seems unintuitive.
This PR aims to resolve this by creating a small number of rake tasks with clearly confined behaviour, that I believe should exist already. These new rake tasks also depend on arguments being passed to the function rather that relying on `stdin` - which I find to be more deterministic for developers.

Additional rake tasks to cover expected functionality

---

app/services/service/base.rb
lib/steps_inspector.rb
spec/lib/steps_inspector_spec.rb

Now, when calling `StepsInspector#error` on a contract failure, the output will contain the parameters provided to the contract.

DEV: Show parameters on a service contract failure

---

plugins/chat/app/services/chat/lookup_user_threads.rb
plugins/chat/spec/services/chat/lookup_user_threads_spec.rb
plugins/chat/spec/system/chat_footer_spec.rb

We should show threads from muted channels in the My Threads area so that users can easily access their followed threads.
- When a user is following a thread in a muted channel, it should still be visible in My Threads.
- Activity in followed threads for muted channels should not generate an activity indicator (e.g. blue notification dot) on My Threads.

FEATURE: show my threads from muted chat channels

---

plugins/chat/assets/javascripts/discourse/models/chat-channel.js
plugins/chat/assets/javascripts/discourse/models/chat-direct-message.js
plugins/chat/assets/javascripts/discourse/models/chat-message-reaction.js
plugins/chat/assets/javascripts/discourse/models/chat-message.js
plugins/chat/assets/javascripts/discourse/models/chat-thread-preview.js
plugins/chat/assets/javascripts/discourse/models/chat-tracking-state.js
plugins/chat/assets/javascripts/discourse/models/user-chat-channel-membership.js
plugins/chat/assets/javascripts/discourse/models/user-chat-thread-membership.js

* remove default prop values where they're being set in constructor
* replace some `||` operators in constructors with `??` so the fallback boolean values are actually used

DEV: Minor refactor of chat models

---

lib/topics_filter.rb
spec/lib/topics_filter_spec.rb
spec/requests/list_controller_spec.rb

As mentioned in [this](https://meta.discourse.org/t/discourse-custom-topic-lists/311186/9?u=grubba) meta topic
It would be nice to have `tag_group` in the `/filter` feature. This PR addresses that.
From what I understand, `tag_group` is an alias for a specific list of `tags`:
`tag_group` -> `tag1,tag2,tag3`

FEATURE: Add tag_group option in `/filter`

---

app/assets/stylesheets/common/select-kit/tag-drop.scss

this keeps the tag name `--primary-high` to match the category dropdowns (and tag names in general)
Before:
After:

UX: make tag filter color consistent with category filters

---

app/assets/javascripts/discourse/tests/integration/components/select-kit/tag-drop-test.js
app/assets/javascripts/select-kit/addon/components/category-drop.js
app/assets/javascripts/select-kit/addon/components/tag-drop.js
config/locales/client.en.yml

This updates "all subcategories" to "remove filter" to match the categories and tags dropdowns.
Before:
After:
This also reorders the "remove fiter" option from the tag dropdown so it appears first for consistency with other filters:
Before:
After:

UX: replace "all subcategories" with "remove filter", reorder tag dropdown

---

app/controllers/admin/site_settings_controller.rb
app/services/site_setting_update_existing_users.rb
app/services/update_site_setting.rb
config/locales/server.en.yml
lib/site_setting_extension.rb
spec/requests/admin/site_settings_controller_spec.rb
spec/services/update_site_setting_spec.rb

This PR adds ability to fetch a subset of site settings from the `/admin/site_settings` endpoint so that it can be used in all places where the client app needs access to a subset of the site settings.
Additionally, this PR also introduces a new service class called `UpdateSiteSetting` that encapsulates all the logic that surrounds updating a site setting so that it can be used to update site setting(s) anywhere in the backend. This service comes in handy with, for example, the controller for the flags admin config area which may need to update some site settings related to flags.
Internal topic: t/130713.

DEV: Allow fetching specific site settings and introduce a service for updating site settings

---

app/assets/javascripts/discourse/app/lib/class-prepend.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/discourse/tests/unit/lib/class-prepend-test.js
app/assets/javascripts/discourse/tests/unit/lib/plugin-api-test.js

This allows modifyClass to be used like this:
```
api.modifyClass(
"model:topic",
(Superclass) =>
class extends Superclass {
static someStaticMethod() {
return `${super.someStaticMethod()} modified`;
}
someFunction() {
return `${super.someFunction()} modified`;
}
get someGetter() {
return `${super.someGetter} modified`;
}
}
);
```
One limitation, which is the same as the old object-literal syntax, is that native class fields and constructors cannot be modified.
`@tracked` properties can be overriden, because the decorator turns them into getters/setters.

DEV: Introduce callback-based native class syntax for modifyClass

---

lib/validators/form_template_yaml_validator.rb
spec/lib/validators/form_template_yaml_validator_spec.rb

We weren't restricting the `a` `href` protocols on the form template field description, this PR fixes it.

FIX: restrict a href protocols on form template description

---

app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.gjs
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
app/controllers/categories_controller.rb
app/models/category.rb
config/locales/client.en.yml
config/routes.rb
spec/models/category_spec.rb
spec/requests/categories_controller_spec.rb
spec/system/editing_sidebar_categories_navigation_spec.rb

* Load search results in displayed order so that when more categories are loaded, they appear at the end,

FIX: Make edit categories sidebar modal work more intuitively

---

app/assets/javascripts/select-kit/addon/components/category-drop.js
app/assets/stylesheets/common/select-kit/category-drop.scss

"No subcategories" is technically a user-changed filter, so we should highlight it as well. 
Before:
After: 
This gets us consistent with "no tags" too:

UX: highlight "no subcategories" as active dropdown option

---

plugins/chat/assets/stylesheets/mobile/chat-thread.scss

This fixes an issue where sticky dates within threads on mobile weren't getting the `is-pinned` class from this intersection observer: https://github.com/discourse/discourse/blob/2014f1a0b7139ad4d488e1a15316877c861a1747/plugins/chat/assets/javascripts/discourse/components/chat-message-separator.gjs#L13
The issue seems to be this additional padding pushing the date down and preventing the intersection from happening. 
I can't really find a reason for the padding, removing it makes the thread layout spacing more consistent with the main chat channel anyway. 
Before:
After:

UX: remove padding to fix mobile date pinning in chat threads

---

app/assets/stylesheets/common/base/d-image-grid.scss
app/assets/stylesheets/common/d-editor.scss

This makes it so the image resize/alt-text controls in the composer editor are always visible on desktop, instead of relying on hover (they're already always visible in the mobile preview).
This makes the controls more discoverable, and if we position them over the image, it means we end up with a preview that has spacing much closer to the cooked result. 
We planned on doing this long ago, but lost sight of it: https://meta.discourse.org/t/make-it-more-obvious-an-image-is-resizable-when-uploading-an-image/132030
Before:
After:
and cooked spacing...
Preview before:
Preview after:
Actual spacing in cooked post: 
For tiny images... more of the image is obscured this way, but there's a slight transparency so it's still somewhat visible: 
Before:
After:
Other states like grid and editing:

UX: always show image preview controls, improve spacing

---

lib/discourse_logstash_logger.rb

This is a duplicate of the `host` field which means we are bloating the
logs unnecessarily.
Just remove without depreciation for now but we are open to properly
depreciating it if others depend on this field.

DEV: Remove `hostname` from `DiscourseLogstashLogger` output

---

app/assets/javascripts/discourse/app/components/reviewable-item.js
app/models/reviewable.rb
spec/models/reviewable_spec.rb
spec/requests/reviewables_controller_spec.rb

Followup 783c935dcb7f114c206da4fe9c46c91ca5c687f3
Some admins were finding that the limit introduced above was
too short especially when sending an email to rejected users.
This commit bumps the limit from 500 to 2000 and also fixes
an issue where the friendly error message was not shown in
the browser.
c.f. https://meta.discourse.org/t/500-character-reject-reason-is-too-small-a-limit/291884

FIX: Bump reject_reason limit for reviewables to 2000 characters

---

config/initializers/002-rails_failover.rb
config/initializers/100-logster.rb
config/initializers/100-quiet_logger.rb
config/initializers/100-silence_logger.rb
config/initializers/101-lograge.rb
config/initializers/102-truncate-logs.rb
lib/discourse.rb
spec/support/fake_logger.rb

`Rails.logger.chained` was provided by Logster before Rails 7.1 introduced their broadcast logger. Now all the loggers are added to `Rails.logger.broadcasts`.
Some code in our initializers was still using `chained` instead of `broadcasts`.

FIX: Remove references to `Rails.logger.chained`

---

app/assets/javascripts/discourse/app/components/bookmark-list.hbs

Should fix this issue: 
We don't need to use a `<th>` here, a regular `<td>` element is fine. And we don't need to add `role="rowheader"` to the TD element either, that is only useful when the layout of the table uses flex or grid, but in this case we don't use either.

UX: Fix user bookmark list keyboard focus state

---

config/initializers/100-quiet_logger.rb
config/initializers/100-silence_logger.rb

A followup to f595d599dd361b7fb39fb3c82cbc11d19d518c19

FIX: Set `override_level` on Logster loggers

---

app/assets/stylesheets/common/base/lightbox.scss

Reported here: https://meta.discourse.org/t/lightboxed-images-do-not-have-vertical-align-set-misaligning-them-with-naked-img-s/312553/1
Since images have `vertical-align: middle`, the lightbox wrapper needs it for aligning with sibling images (without lightboxes) in posts. 
Before: 
After:

UX: vertical alignment for lighbox-wrapper

---

app/assets/stylesheets/common/d-editor.scss

This follow-up to https://github.com/discourse/discourse/commit/0a99407bfb363a28ae1a419cc5e4c16346b784f8, ensures that very short images always have space for the image controls by applying a min-height to the image wrapper. 
Before:
After:

UX: add min-height to preview image wrapper to give controls space

---

spec/system/composer_uploads_spec.rb

There's already a `before { sign_in }` in this spec file

DEV: Remove repeated `sign_in` calls

---

app/models/reviewable_user.rb
spec/requests/reviewables_controller_spec.rb

Followup 6b872c4c5382e5e58c14d55bc92b8da5ba158ce1
Even though we were showing a validation error for a reject
reason that was too long, we were still sending an email and
doing other operations on the user which we are rejecting.
This commit fixes this by validating the reviewable model
before attempting to do anything else after the reason is set.

FIX: Rejection email sent even if reject reason too long

---

app/models/topic_embed.rb
spec/models/topic_embed_spec.rb

For Topic Embeds, we would prefer `<article>` to be the main article in a topic, rather than a table cell `<td>` with potentially a lot of data. However, in an example URL like [here](https://documentation.sailpoint.com/cam/help/cloud_access_management/config_aws.html#policy-requirements), the table cell (the very large code snippet) is seen as the Topic Embed's article due to the determined content weight by the [Readability](https://github.com/cantino/ruby-readability) library we use.
In the newly released 0.7.1 https://github.com/cantino/ruby-readability/pull/94, the library has a new option to exclude the library's default `<td>` element into content weighting. This is more in line with the [original library](https://code.google.com/archive/p/arc90labs-readability/) where they only …

FIX: Disallow table cells to be weighted so actual articles can be main content

---

app/controllers/application_controller.rb
config/site_settings.yml
spec/requests/application_controller_spec.rb

Some tooling may rely on an `unsafe-none` cross origin opener policy to work. This change adds a hidden site setting that can be used to list referrers where we add this header instead of the default one configured in `cross_origin_opener_policy_header`.

FEATURE: Add hidden site setting to list 'unsafe-none' COOP referrers

---

spec/lib/email/sender_spec.rb

The test that checks that securely uploaded images are re-attached to the digest e-mail wasn't rendering the actual digest e-mail template. This change fixes that.

DEV: Ensure digest e-mail secure image test uses actual digest e-mail

---

app/controllers/application_controller.rb
spec/requests/application_controller_spec.rb

Follow-up to #27510. I hadn't had coffee yet, and my "host extraction" was incredibly primitive. This fixes that.
Update test cases based on [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer):

DEV: More robust referrer host parsing

---

lib/pretty_text.rb
spec/lib/pretty_text_spec.rb

When a post is cooked the links are extracted and `TopicLink` instances are created for each of them. These links are used in various places, including the topic view, user summary page, etc.
In previous commit 48e5d1a, hotlinked images from Oneboxes have been ignored from the texts, but hotlinked images turned into Lightboxes were still extracted.

FIX: Do not extract links for hotlinked images

---

lib/plugin/metadata.rb

…from the official plugins list. It's archived now.

DEV: Remove discourse-moderator-attention

---

lib/email/sender.rb
spec/lib/email/sender_spec.rb

We recently fixed a problem where secure upload images weren't re-attached when sending the activity summary e-mail.
This fix contained a bug that would lead to n copies of the e-mail body being included, n being the number of duplicates. This is because `#fix_parts_after_attachments!` was called once per attachment, and adding more parts to the multipart e-mail.
This PR fixes that by:
1. Adding a failing test case for the above.
2. Moving the looping over multiple posts into `#fix_parts_after_attachments!` itself.

FIX: Avoid duplicating e-mail body in summary e-mail

---

app/controllers/application_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
spec/requests/application_controller_spec.rb
spec/requests/omniauth_callbacks_controller_spec.rb

In this PR we introduced `enforce_second_factor_on_external_auth` setting https://github.com/discourse/discourse/pull/27506
When it is set to false and the user is authenticated via OAuth, then we should not enforce the 2fa configuration.

FIX: do not force configure 2FA when OAuth and not enforced

---

app/models/user_field.rb
db/migrate/20240620024938_add_back_field_type_enum_to_user_fields.rb
db/post_migrate/20240612073116_swap_field_type_with_field_type_enum_on_user_fields.rb

We previously migrated `field_type` from a string to an `integer` backed enum. Part of this involved renaming a column in a post migration, swapping out `field_type:string` for `field_type:integer`. This borks the ActiveRecord cache since the application is already running. Rebooting fixes it, but we want to avoid having this happen in the first place.
All instances are now in one of two states:
1. Migrations have been run, and there is a `field_type:integer`. (Affected by the cache poisoning.)
2. Migrations have not been run, and there is a `field_type:string`. (Not yet affected.)
The desired state is:
We have a `field_type:any` (ignored) and a `field_type_enum:integer` backing the enum.
For instances where migrations have already been run, we want to:
1. Create …

FIX: Prevent field type migration from poisoning AR cache

---

app/assets/javascripts/discourse/app/routes/discovery-filter.js
spec/system/filtering_topics_spec.rb

Previously filter route was not setting topic list, this meant that
keyboard navigation using "G" "J" was not functioning.
This amends it by ensuring the list is set after looking up the model.

FEATURE: enable list keyboard shortcuts on filter route

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
config/routes.rb
lib/homepage_constraint.rb
lib/homepage_helper.rb
lib/theme_resolver.rb
spec/lib/homepage_helper_spec.rb

This ensures that the theme id is resolved as early as possible in the request cycle. This is necessary for the custom homepage to skip preloading the wrong data.

DEV: Extract theme resolution to a helper

---

app/assets/stylesheets/common/admin/admin_report.scss
app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/base/groups.scss
app/assets/stylesheets/common/base/header.scss
app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/base/new-user.scss
app/assets/stylesheets/common/components/buttons.scss
app/assets/stylesheets/common/components/navs.scss
app/assets/stylesheets/common/d-editor.scss
app/assets/stylesheets/common/foundation/base.scss
app/assets/stylesheets/wizard.scss
plugins/chat/assets/stylesheets/common/chat-message-actions.scss

* Create new var: `--d-button-transition: background none, color none;`
* Replace properties on regular button or similar with new variable
* Change currentColor property to inherit for d-icon on buttons
* Remove superfluous transitions on random elements where possible

UX: Remove or replace button transitions with variable

---

app/serializers/post_revision_serializer.rb
spec/serializers/post_revision_serializer_spec.rb

In some instances, the `modifications` of `tags` hasn't been properly serialized as a Ruby array but rather as a string (I've seen `""`, `"[]"`, and `"[\"\"]"`).
This generates an error when we try to `filter_tags` and remove `hidden_tags` (which is an array) from `tags` which might be a string.
Internal ref - t/131126
I wasn't able to figure out the root cause of this so I reverted the behavior that was introduced ~6 years ago in f2c060bdf2a309fd4ba884b529367df66837a6d7

FIX: post revision serializer when tags is a string

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js

This commit introduces behaviour similar to sites
like GitHub, Notion, and others where, if you
are already typing a list and press enter in the composer,
we continue the list on the next line.
Then, if you press enter again on the next line with
an empty list item, we remove that item on that last line.
This works with the following list types:
```
* star bullet
- dash bullet
* [] star and dash bullet with checkbox
1. numbered
```
This also works if you are in the middle of a list, and
with indented sub-lists.
With the numbered lists, we continue with the next number
in the sequence, and if you start a new line in the middle
of the list, we renumber the rest of the list.
<video src="https://github.com/discourse/discourse/assets/920448/932662d5-b67c-4f32-a193-dcdbb7d89caa" />

FEATURE: Smarter list editing in DEditor

---

app/assets/stylesheets/common/foundation/variables.scss
plugins/chat/assets/stylesheets/common/chat-drawer.scss

Adds a new z-index value for the drawer 
Before:
After:

UX: fix chat drawer z-index

---

app/assets/stylesheets/common/admin/flags.scss

**What changed?**
Removed tertiary color styling from names that are not clickable

UX: Remove tertiary color from non-link elements

---

app/assets/stylesheets/mobile/menu-panel.scss
app/assets/stylesheets/mobile/sidebar.scss

UX: Increase spacing mobile menus

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
lib/homepage_constraint.rb
lib/homepage_helper.rb
spec/system/homepage_spec.rb

Fixes a small regression in https://github.com/discourse/discourse/pull/27426, following that PR, using the modifier in a theme component regressed. 
This also adds a test to prevent this from happening again in the future.

FIX: Regression in custom homepage modifier used in theme components

---

.github/workflows/tests.yml

Running in parallel seems to cause (unexplained so far) timeouts

DEV: Do not run theme QUnit in parallel

---

app/assets/javascripts/discourse/app/components/d-breadcrumbs-item.gjs

…to avoid re-evaulation right before destroying.
With `DeferredTrackedSet` we delay both adding and removing elements from the set. That means when you're transitioning between routes, and breadcrumbs change, both old and new breadcrumbs are rendered (briefly, in a first render pass)
And since the arguments for the old breadcrumbs can be (and often are) destroyed - it would blow up the renderer. By caching the template it will reuse it in that first pass.
---
No test because I couldn't figure out a synthetic test setup where you have breadcrumbs in a deeply nested route and where you navigate from that route to one of the parent routes.

FIX: Cache breadcrumb-item template

---

app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs
app/assets/stylesheets/common/admin/plugins.scss
spec/system/admin_plugins_list_spec.rb

* Removed the link from the title, so the settings can only be accessed via the settings button on the right
* Added an icon to the "Learn more" link to indicate that it opens a new window
* Made various styling adjustments

UX: Remove the link from the title; add external icon; style adjustment

---

app/controllers/application_controller.rb
spec/requests/omniauth_callbacks_controller_spec.rb

Followup to 0e1102b3326ace878c357301e108154051d37c31
Minor followup, makes the condition check against the
boolean val, see the difference here:
```ruby
!SiteSetting.enforce_second_factor_on_external_auth && "true"
=> "true"
```
vs:
```ruby
!SiteSetting.enforce_second_factor_on_external_auth && "true" == "true"
=> true
```

DEV: Check for "true" in oauth check for 2FA

---

app/assets/javascripts/admin/addon/controllers/admin-site-text-index.js
app/assets/javascripts/admin/addon/routes/admin-site-text-index.js
app/assets/javascripts/admin/addon/templates/site-text-index.hbs
app/controllers/admin/site_texts_controller.rb
config/locales/client.en.yml
config/site_settings.yml
lib/freedom_patches/translate_accelerator.rb
spec/requests/admin/site_texts_controller_spec.rb

Adds a checkbox to filter untranslated text strings in the admin UI, behind a hidden and default `false` site setting `admin_allow_filter_untranslated_text`.

FEATURE: add Untranslated filter to admin text customization

---

app/assets/stylesheets/common/base/header.scss

Personal messages don't have categories, so this information should be moved to the earlier grid column so it aligns properly. 
Before:
After:

UX: improve alignment of extra PM info in header

---

config/locales/server.en.yml

Replaced the term "staff" with "moderators" on the FAQ page.

UX: Use 'moderators' instead of 'staff'

---

lib/email/sender.rb
spec/lib/email/sender_spec.rb

Followup 96a0781bc181fdc4bda856bfb90b03ce55e342cf
When sending emails where secure uploads is enabled
and secure_uploads_allow_embed_images_in_emails is
true, we attach the images to the email, and we
do some munging with the final email so the structure
of the MIME parts looks like this:
```
multipart/mixed
multipart/alternative
text/plain
text/html
image/jpeg
image/jpeg
image/png
```
However, we were not specifying the `boundary` of the
`multipart/mixed` main content-type of the email, so
sometimes the email would come through appearing to
have an empty body with the entire thing attached as
one attachment, and some mail parsers considered the
entire email as the "epilogue" and/or "preamble".
This commit fixes the issue by specifying the boundary
in the content-type header per …

FIX: Missing multipart/mixed boundary on emails

---

app/assets/javascripts/discourse/app/components/header/user-dropdown/user-status-bubble.gjs
app/assets/javascripts/discourse/tests/acceptance/user-status-test.js

We didn't escape the "user status" before inserting in in the title of the "user status badge" next to the current user avatar.
This only affects the current user.
Internal ref - t/130332

FIX: properly escape user status's title

---

plugins/chat/app/serializers/chat/chatable_user_serializer.rb
plugins/chat/spec/serializer/chat/chatable_user_serializer_spec.rb

As an admin, I am unable to create personal chats with other users.
However, according to the site settings, staff members should always have the ability to create personal chats.
1. Set `chat allowed groups` to TL0 & `direct message enabled groups` to moderators
2. As an admin, attempt to create a personal chat with a TL1 user.
This issue is related to PR https://github.com/discourse/discourse/pull/26010 
https://github.com/discourse/discourse/blob/df373d90fe9460b49aaa771e138aebf3f768c803/plugins/chat/app/serializers/chat/chatable_user_serializer.rb#L8
When a user attempts to create a personal chat, we should not verify whether the target user has the ability to create personal chats. Instead, as specified in the site settings, we should verify whether the **current user** has the …

Fix: allow staff and `direct message enabled groups` to create personal chats

---

app/serializers/user_card_serializer.rb
plugins/chat/plugin.rb
plugins/chat/spec/requests/core_ext/users_controller_spec.rb
spec/serializers/user_card_serializer_spec.rb

We specifically checked against this before, but it's more consistent to show the buttons since the functionality is already allowed

UX: Show chat and message buttons on your own profile

---

app/controllers/static_controller.rb

This is a follow-up to https://github.com/discourse/discourse/pull/27451. These changes are still under the hidden setting `experimental_rename_faq_to_guidelines`

UX: Redirect /faq, /rules, /conduct to /guidelines

---

app/assets/stylesheets/common/d-editor.scss

This is a follow-up to https://github.com/discourse/discourse/commit/0a99407bfb363a28ae1a419cc5e4c16346b784f8
Overlaying the image proved to be annoying in cases where you want to see text in an image, so let's move back to controls below the image. 
Before:
After:

UX: move composer image controls below image

---

app/assets/javascripts/admin/addon/templates/flags-index.hbs
app/assets/javascripts/admin/addon/templates/flags-index.hbs ./config

When I attempt to clone this repository on Windows, I encounter the following error: 
The error message indicates an invalid path: `flags-index.hbs ./config`.
I found this file: 
https://github.com/discourse/discourse/blob/0d6bd5207d21de97c864d181b51b8ac41f20beb0/app/assets/javascripts/admin/addon/templates/flags-index.hbs%20./config
The filename contains a space and a dot, which does not seem to be a valid filename.
I suspect the correct filename should be `flags-index.hbs`.

FIX: invalid path

---

app/assets/javascripts/discourse/app/components/category-list-item.js
app/assets/javascripts/discourse/app/components/category-unread.js
app/assets/javascripts/discourse/app/components/parent-category-row.hbs
app/assets/javascripts/discourse/tests/integration/components/select-kit/category-selector-test.js
app/assets/stylesheets/desktop/category-list.scss
config/locales/client.en.yml

Minor follow-up to https://github.com/discourse/discourse/commit/0d6bd5207d21de97c864d181b51b8ac41f20beb0 for lazy-load categories. 
This improves the layout and alignment of the subcategories, their new/unread badges, makes the `+N subcategories` message styled more like the subcategories, and also makes it link to the full subcategories route. 
Before:
After:

UX: improve categories page subcategory layout

---

spec/system/user_page/user_preferences_profile_spec.rb

The auto-generated username has a sequence number after it that may be different from the hard-coded one. Use `user.username` instead.

DEV: Fix flaky system spec with hardcoded username

---

lefthook.yml

Often when the pre-commit hook is run and reports a problem, I want to follow up by running the auto-correct command of the respective linter, but that means I need to remember what to run. "Let's see. Did prettier need a double-dash before write or not?"
This change adds a `lefthook run fix-staged` command that runs linter auto-corrects on any staged files.

DEV: Add Lefthook command to auto-correct staged files

---

lib/email/sender.rb
spec/lib/email/sender_spec.rb

That can be used by plugins to control whether attachments should be sent.
Internal ref - t/132149

FEATURE: new 'should_add_email_attachments' plugin modifier

---

plugins/automation/admin/assets/javascripts/admin/templates/admin-plugins-discourse-automation-edit.hbs
plugins/automation/admin/assets/javascripts/admin/templates/components/form-error.hbs
plugins/automation/app/controllers/discourse_automation/admin_scriptables_controller.rb
plugins/automation/app/serializers/discourse_automation/automation_serializer.rb
plugins/automation/spec/system/error_spec.rb
plugins/automation/spec/system/smoke_test_spec.rb

A previous refactor has prevented errors to show correctly. The guilt of the issue is that we were not calling the error variable correctly in the templates.
This commit also adds a spec for this case, and removes the need for `I18n.backend.store_translations` in specs so we don't have to write too much boilerplate each time we write a spec.

FIX: correctly show validation errors in automation

---

app/models/topic_embed.rb
spec/models/topic_embed_spec.rb

This PR addresses an issue in the topic embedding importer where the import method fails when tags are passed as strings. The change ensures that the tags are correctly processed whether they are passed as strings or objects.

FIX: Topic embedding importer should accept string tags

---

app/assets/javascripts/discourse/app/routes/preferences-second-factor.js
app/assets/javascripts/discourse/tests/acceptance/enforce-second-factor-test.js
app/controllers/application_controller.rb
app/controllers/session_controller.rb
app/serializers/current_user_serializer.rb
lib/auth.rb

If the `enforce_second_factor_on_external_auth` setting
is disabled and a user logs in with an OAuth method,
they don't automatically get redirected to /preferences/second-factor
on login. However, they can get there manually, and once there
they cannot leave.
This commit fixes the issue and allows them to leave
and also does some refactors to indicate to the client
what login method is used as a followup to
0e1102b3326ace878c357301e108154051d37c31

FIX: Do not capture OAuth user on 2FA page

---

spec/requests/api/posts_spec.rb
spec/requests/api/private_messages_spec.rb
spec/requests/api/schemas/json/admin_user_response.json
spec/requests/api/schemas/json/category_topics_response.json
spec/requests/api/schemas/json/post_replies_response.json
spec/requests/api/schemas/json/post_show_response.json
spec/requests/api/schemas/json/post_update_response.json
spec/requests/api/schemas/json/topic_create_response.json
spec/requests/api/schemas/json/topic_show_response.json
spec/requests/api/schemas/json/user_get_response.json
spec/requests/api/tags_spec.rb
spec/requests/api/topics_spec.rb
spec/requests/api/users_spec.rb

The API docs currently report the types of several ID values as (possibly null) strings when in reality they are (possibly null) values. I found this to be the case for the `primary_group_id`, `flair_group_id`, and `uploaded_avatar_id` attributes of the `User` model; the `reviewable_id` attribute of the `ReviewableScore` model, and the `category_id` attribute of the `TopicTimer` model. 
Pry output for reference:
```rb
[1] pry(main)> User.type_for_attribute("primary_group_id").type
=> :integer
[2] pry(main)> User.type_for_attribute("flair_group_id").type
=> :integer
[3] pry(main)> User.type_for_attribute("uploaded_avatar_id").type
=> :integer
[4] pry(main)> ReviewableScore.type_for_attribute("reviewable_id").type
=> :integer
[5] pry(main)> TopicTimer.type_for_attribute("category_id").type …
```

FIX: update id types in API docs to integers

---

app/assets/javascripts/discourse/app/components/search-menu/results/initial-options.js
spec/system/page_objects/pages/search.rb
spec/system/user_page/user_page_search_spec.rb

When visiting a user profile, and then opening the search, there's an option to filter down by posts made by that user.
When clicking that option, it used to pre-fill the "search bar" with "@<username>" to filter down the search.
This restore this behaviour and add a system spec to ensure it doesn't regress.
Context - https://meta.discourse.org/t/in-posts-by-search-option-does-not-work-when-clicked/312916

FIX: "in posts by" user search

---

plugins/chat/lib/chat/user_notifications_extension.rb
plugins/chat/spec/mailers/user_notifications_spec.rb

The chat summary email currently contains mentions that are not relevant to the current user, by limiting by the target user id or when using `@all` we can restrict to showing only the relevant channel mentions.
/t/132240

FIX: only show relevent chat channel mentions in summary email

---

lib/search.rb
spec/lib/search_spec.rb

When using the full page search and filtering down to a specific topic, the sort order was overwritten to by by "post_number".
This was confusing because we allow different type of sort order in the full search page.
This fixes it by only sorting by post_number when there's no "global" sort order defined.
Since the "new topic map" uses the search endpoint behind the scene, this also fixes the "most likes" popup.
Context - https://meta.discourse.org/t/searching-order-seems-to-be-broken-when-searching-in-topic/312303

FIX: topic search order

---

app/assets/javascripts/discourse/app/components/header/topic/info.gjs
app/assets/stylesheets/common/base/header.scss

This fixes this featured link header misalignment...
before:
after:
and also eliminates some extra space created by an empty `topic-header-participants` div

UX: fix featured link alignment, hide participants wrapper outside of PMs

---

lib/discourse_ip_info.rb

If mmdb database fails to download a bootstrap fails. This is a trivial fix for that problem. A more elegant solution might check whether the dataabase was downloaded and provide a helpful error message.

FIX: rescue mmdb download failure

---

app/controllers/permalinks_controller.rb
spec/requests/permalinks_controller_spec.rb

Currently, redirecting to an external URL through a permalink doesn’t work because Rails raises a
`ActionController::Redirecting::UnsafeRedirectError` error.
This wasn’t the case before we upgraded to Rails 7.0.
This PR fixes the issue by using `allow_other_host: true` on the redirect.

FIX: Don’t raise an error on permalinks with external URL

---

app/controllers/list_controller.rb
spec/requests/list_controller_spec.rb

When bad data is provided in the URI for redirecting to a category, Rails raises an `ActionController::Redirecting::UnsafeRedirectError` error, leading to a 500 error.
This PR catches the exception to render a 404 instead.

FIX: Render a 404 error on a bad redirect in list controller

---

app/assets/javascripts/discourse/tests/unit/lib/sanitizer-test.js
app/assets/javascripts/pretty-text/addon/sanitizer.js

This improves the way we sanitize `iframe` and correctly strips them from the "raw" before cooking it.
Otherwise, we would show an empty iframe box.
Internal ref - t/131430

FIX: better iframe sanitization
