plugins/chat/assets/stylesheets/common/core-extensions.scss

Small follow-up on #27600: when you are an admin, the buttons are not in the correct order.
<div align=center>
<h4>Before</h4>
<h4>After</h4>
</div>

FIX: User controls buttons order for admins

---

app/assets/javascripts/discourse/app/components/calendar-date-time-input.js

When choosing a date range in some timezones, the displayed date in the calendar will render one day off when switching between the "from date" and the "to date".
<div align=center>
</div>
This is due to some inconsistencies with the default `Date` object in Javascript. For instance:
```javascript
new Date("2015-10-21")
// => Tue Oct 20 2015 21:00:00 GMT-0300 (Argentina Standard Time) // Wrong date
new Date("2015/10/21")
// => Wed Oct 21 2015 00:00:00 GMT-0300 (Argentina Standard Time) // Correct date
```
[Pikaday](https://github.com/Pikaday/Pikaday) uses a `Date` object to parse the string, so using the format `YYYY/MM/DD` solves the issue.
Note that this is strictly visual, the actual selected dates are correct.

FIX: `CalendarDateTimeInput` renders the wrong day

---

app/assets/javascripts/discourse/app/routes/new-category.js
spec/system/new_category_spec.rb
spec/system/page_objects/pages/category.rb

While creating a new category if the user didn't specify a value for `minimum_required_tags` input but clicked it then it returned the "PG::NotNullViolation: null value in column 'minimum_required_tags'" error.

FIX: should not raise error when minimum_required_tags value not defined for category.

---

config/locales/server.en.yml
config/site_settings.yml

This has been around for a long time now and was mentioned
in https://meta.discourse.org/t/a-new-era-for-file-uploads-in-discourse/210469,
there is no need to hide it, self-hosters are free to enable
this.

DEV: Unhide enable_direct_s3_uploads setting

---

plugins/chat/lib/chat/user_notifications_extension.rb
plugins/chat/spec/mailers/user_notifications_spec.rb

Follow up to #27631 to account for group mentions in channels.
We only want to show mentions for groups that are currently mentionable and those that the current user belongs to.

FIX: show group based notifications in chat summary email

---

app/assets/stylesheets/common/components/user-card.scss

Before:
After:
also works when name is prioritized

UX: truncate too-long names in usercard

---

app/assets/stylesheets/common/base/tagging.scss

In cases of long tags and narrow screens, the tag bullet can be hidden by flex-shrink... this prevents that from happening.
Before:
After:

UX: prevent the tag bullet from shrinking

---

plugins/discourse-lazy-videos/assets/stylesheets/lazy-videos.scss

This is a dupe of https://github.com/discourse/discourse-lazy-videos/pull/15, I didn't realize this plugin was added to core. 
The height set here: https://github.com/discourse/discourse/blob/94044591881cd11b71b2b98652e771ab0027fa71/app/assets/stylesheets/common/base/onebox.scss#L920 can sometimes override the height set by the plugin, so this more specific class selector ensures that can't happen.

UX: fix height of lazy youtube embeds

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js

Followup 30fdd7738ec942126bb055c9a6a8d69ddffba2da,
The issue with keyup is that it happens too late. maybeContinueList
itself runs in about 1 or 2 ms. But we show the linebreak in the
textarea on keydown and we handle it in keyup, which causes the “lag”.
The fix here is “hacking” itsatrap and textarea behavior to allow us to handle
it right away after the linebreak is inserted.
Full credit to Joffrey Jaffeux for this fix, I am making him
"co-author" below.
BEFORE
https://github.com/discourse/discourse/assets/920448/7f25750e-81c6-4e00-aa37-44e19a96bb4f
AFTER
https://github.com/discourse/discourse/assets/920448/2ed15f38-e3f3-48ea-b0e4-b7644cf5236a
Co-authored-by: Joffrey JAFFEUX <j.jaffeux@gmail.com>

FIX: Small delay when auto-adding list item in composer

---

app/models/theme.rb
spec/lib/stylesheet/manager_spec.rb

- This PR aims to fix a N+1 issue found in Theme model causing some performance problems. To prevent it, we are now including javascript_cache and upload relationships.

PERF: Eager load field causing N+1 issue

---

app/serializers/user_card_serializer.rb
spec/serializers/user_card_serializer_spec.rb

I thought this was necessary, but it is not, and it overwrites the setting `personal_message_enabled_groups`

FIX: Hide message button for current user if can't message

---

app/controllers/session_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
spec/requests/omniauth_callbacks_controller_spec.rb

By default, secure sessions expire after 1 hour.
For OAuth authentication it should expire at the same time when the authentication cookie expires - `SiteSetting.maximum_session_age.hours`.
It is possible that the forum will not have persistent sessions, based on `persistent_sessions` site setting. In that case, with next username and password authentication we need to reset information about OAuth.
Bug introduced in this PR - https://github.com/discourse/discourse/pull/27547

FIX: increase secure session for OAuth expiration time

---

app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js

Firefox is having a lot of inconsistent issues with this
feature introduced in 30fdd7738ec942126bb055c9a6a8d69ddffba2da,
disabling it there for now until further investigation can
be done.

DEV: Disable smart lists for now on Firefox

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js

Adds warnings for:
- `discourse.plugin-outlet-tag-name`
- `discourse.plugin-outlet-parent-view`
Also updates the ID list to be strings rather than regex (so that `.` is not treated as a wildcard).

DEV: Add admin warnings for plugin-outlet deprecations

---

lib/tasks/posts.rake

When doing mass rebaking, this task will print progress, speed and
expected time to completion (ETC) on a loop. It is meant for rebakes
that take several hours or days.
It will calculate a 10m moving average over the past 6 hours, and print
ETC accordingly.
It also shows Sidekiq stats in case Sidekiq jobs for rebaking were
enqueued separately, instead of using the rebake_posts tasks in this
file (which are 100% synchronous and do not touch Sidekiq at all).
NOTE: only the currently unbaked count at task start time is considered;
this is useful in live communities with lots of traffic, where new posts
might otherwise change the goal posts continuously.
Tests were not added because the task is strictly read-only, informative
and not mission critical. Not worth the complexity to unit test …

UX: Add a rake task to monitor progress for long rebakes

---

app/serializers/flag_serializer.rb
spec/system/admin_flags_spec.rb

FlagSerializer is used in this PR
https://github.com/discourse/discourse/pull/27484 but was not staged.
The original system spec didn't catch it because the record was created and before the error was displayed we redirected to a topic page to check available flags.

FIX: missing flag serializer

---

app/assets/javascripts/admin/addon/components/admin-flag-item.gjs
spec/system/admin_flags_spec.rb

Before checking if flags were reordered on the topic page, we need to ensure that the reorder action was finished. 
To achieve it "saving" CSS is added and removed when AJAX call is completed.

DEV: flaky reorder flags specs

---

app/assets/javascripts/discourse/app/instance-initializers/post-decorations.js
plugins/footnote/assets/javascripts/initializers/inline-footnotes.js
plugins/footnote/assets/stylesheets/footnotes.scss

meta topic: https://meta.discourse.org/t/inline-footnotes-doesnt-work-in-the-table-at-fullscreen/313445
after:

FIX: Inline footnotes doesn’t work in the table at fullscreen

---

lib/auth/managed_authenticator.rb
spec/lib/auth/managed_authenticator_spec.rb

Currently seeing an influx of `Job exception: url` due to `Jobs::DownloadAvatarFromUrl`
`return unless user && url` doesn't return if `url = ""`, so this fix ensures that a `""` won't pass through.

FIX: Do not schedule avatar download if image is ""

---

app/models/topic_embed.rb
spec/models/topic_embed_spec.rb

When a topic embed is run with either no tags argument or a nil tag argument this should not affect any existing tags.
Only update topic tags when tags argument is explicitly empty.
See also:
https://meta.discourse.org/t/rss-polling-plugin-removes-tags-added-manually/311811

FIX: topic embed blank tags or passed with nil do not blank out existing topic tags

---

app/models/report.rb
spec/models/report_spec.rb

Followup 2f2da7274732cba30d03b6c5c3a4194652cb6783
When the "Consolidated Pageviews with Browser Detection (Experimental)"
report was introduced, we started counting the original
"page_view_logged_in" and "page_view_anon" ApplicationRequest
data as "Other Pageviews", subtracting
"page_view_anon_browser" and "page_view_logged_in_browser" from
this number.
However we unknowingly automatically started counting these
browser-based page views, which are a subset of the total
"page_view_logged_in" and "page_view_anon" counts, in the
original "Pageviews" report, leading to double counting
which meant that when you looked at the data for each
report side-by-side the data didn't add up.
This commit fixes the issue by not counting the "browser"
pageviews in the Pageviews report, and making the code …

FIX: Discrepency between admin page view reports

---

spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/uppy_image_uploader.rb

There's currently a race condition in the following spec:
https://github.com/discourse/discourse/blob/65be7a7880ba0dc1a5cb403956fabd83aaa738d6/spec/system/admin_about_config_area_spec.rb#L70-L95
where the form can be saved before the image uploader field has finished uploading the selected image and causing the assertion at line 94 to fail with the following error:
```
Failure/Error: expect(SiteSetting.about_banner_image.sha1).to eq(Upload.generate_digest(image_file))
NoMethodError:
undefined method `sha1' for nil
[Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_admin_about_config_area_page_the_general_settings_card_can_saves_its_fields_to_their_corresponding_site_settings_312.png
http://localhost:31338/assets/vendor.js …
```

DEV: Fix flaky spec for the /about admin config area

---

app/assets/javascripts/discourse/app/components/topic-list/topic-link.gjs
app/assets/javascripts/discourse/app/helpers/topic-link.js

Both internal and customer accessibility audits have flagged this as an issue.

A11Y: topic list links should not be headings

---

app/controllers/users_controller.rb
config/locales/server.en.yml
config/site_settings.yml
spec/requests/users_controller_spec.rb

When user changes password, add an option to delete their associated accounts (google, facebook, etc).

FEATURE: add option to delete user associated account on password reset

---

app/models/upload.rb
spec/models/badge_spec.rb
spec/models/upload_spec.rb

Badges can have their associated image uploads deleted. When this happens, any user who has that badge will have their profile page error out.
When deleting an upload that's associated with a badge, nullify the foreign key ID on the badge. This makes the existing safeguard work correctly.

FIX: Don't error out when loading a badge with a deleted image

---

app/models/user.rb
spec/fabricators/invite_fabricator.rb
spec/models/invite_redeemer_spec.rb
spec/models/user_spec.rb
spec/system/user_invites_spec.rb

If an existing user (John) accepts an invite created by Kenny to a group, John may be seen as invited by Kenny, despite already having an account on the site.
This PR removes the bug by excluding invites that determine the `invited_by` after the user's creation date. The delay buffer in the query accounts for invites that also create the user at the same time.

FIX: Don't show that an existing user is invited_by another user

---

app/models/user.rb
spec/models/invite_spec.rb

When tag preference in group and site settings are both used with the same default notification level it will break new users' signups because it tries to create duplicate records in the tag_users table which can’t happen because we have a unique index set.

FIX: should not raise error when both group & site tag preferences are same

---

app/assets/javascripts/discourse/app/components/modal/spreadsheet-editor.gjs
app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js

Currently, when you use the table builder to edit an existing table, the table builder does not observe the `text-align` property of the original table. 
This results in the original table alignment being lost after editing and reset to no alignment.
This PR fixed this bug.
Related meta topic: https://meta.discourse.org/t/table-builder-editor-eradicates-column-alignment-specification/299577

FIX: Make the table builder respect table alignment specifications

---

app/controllers/users_controller.rb
spec/requests/users_controller_spec.rb

There are a few things at play here
1. Crawled links to user profiles e.g. `This is a post that mentions meta.discourse.org/u/derpina`
1. robots.txt
1. `SiteSetting.hide_user_profiles_from_public`
Our robots.txt includes `Disallow: /u`, which is [probably not a good idea](https://developers.google.com/search/docs/crawling-indexing/block-indexing), since (for instance) Google will not be able to see a `noindex` on /u because we've blocked it via robots.
Secondly, `SiteSetting.hide_user_profiles_from_public` raises a `Forbidden`, which disallows our `after_action: add no index header` from triggering.
This PR makes sure that the no index header gets added via `before_action` instead. We may consider removing /u from https://github.com/discourse/discourse/blob/2900cbefe10930173d4b29a8d2b69e85 …

FIX: Always noindex /u routes

---

app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs

set `highlight` to `false` regardless of the animation finishing

FIX: Correctly unhighlight glimmer topic list items

---

app/assets/stylesheets/mobile/float-kit/d-menu.scss
plugins/chat/assets/javascripts/discourse/components/chat-message-actions-mobile.gjs
plugins/chat/assets/stylesheets/mobile/chat-message-actions.scss

Bringing the message popup menu more in line with other menus by:
* increasing vertical spacing
* decreasing horizontal space
* removing the lines inbetween items
(screenshots not 1-1 with reality due to devtools)

UX: Chat mobile menu styling update

---

plugins/poll/assets/javascripts/discourse/components/poll-results-standard.gjs
plugins/poll/test/javascripts/component/poll-results-standard-test.js

In transferring widget code to Glimmer, some logic was missed.
* FIX: do not attempt to show voter list on private poll results
* FIX: avoid attempting to enrich results with undefined voters
relates to recent merge #27204
@ZogStriP

FIX: Poll: do not attempt to show voter list on private polls

---

app/assets/stylesheets/common/base/discourse.scss

FIX: Use the correct color scheme for default inputs

---

app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/tests/fixtures/md-table.js
app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js

The old implementation used unnecessary `\r\n` and caused the table generator to incorrectly add extra empty lines. This commit replaces it with `\n`, fixing the bug.
before:
after:
Note: This PR was tested on Windows. I am not sure if it will work on other platforms (Linux, Mac), but it is likely to work.
Related meta topic: https://meta.discourse.org/t/creating-a-table-sometimes-insert-empty-lines-between-rows-breaking-the-table/270658

FIX: Uses `\n` for line breaks in table builder

---

lib/turbo_tests/runner.rb

Fixes the following deprecation warning:
> DEPRECATION WARNING: The `check_pending!` method is deprecated in favor of `check_all_pending!`. The new implementation will loop through all available database configurations and find pending migrations. The prior implementation did not permit this.

DEV: `check_pending` -> `check_all_pending!`

---

Gemfile
Gemfile.lock
config/environments/development.rb
config/initializers/101-lograge.rb
config/unicorn.conf.rb
lib/discourse.rb
lib/discourse_logstash_logger.rb
lib/git_utils.rb
lib/version.rb
spec/lib/discourse_logstash_logger_spec.rb

This commit rewrites `DiscourseLogstashLogger` to not be an instance
of `LogstashLogger`. The reason we don't want it to be an instance of
`LogstashLogger` is because we want the new logger to be chained to
Logster's logger which can then pass down useful information like the
request's env and error backtraces which Logster has already gathered.
Note that this commit does not bother to maintain backwards
compatibility and drops the `LOGSTASH_URI` and `UNICORN_LOGSTASH_URI`
ENV variables which were previously used to configure the destination in
which `logstash-logger` would send the logs to. Instead, we introduce
the `ENABLE_LOGSTASH_LOGGER` ENV variable to replace both ENV and remove
the need for the log paths to be specified. Note that the previous
feature was considered experimental as …

DEV: Redo `DiscourseLogstashLogger` to not rely on `logstash-logger`

---

app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js

The original table builder does not escape `|`, which causes syntax like `![image|50x50](url)` to be recognized as two different cells. This PR fixes this issue.
Before: https://d11a6trkgmumsb.cloudfront.net/original/4X/0/9/5/09570ed7865ea704722528520d074378accf534c.mp4
After:
Related meta topic: https://meta.discourse.org/t/table-editor-breaks-embedded-images/314831

FIX: Make table builder escape `|`

---

plugins/poll/test/javascripts/acceptance/poll-pie-chart-test.js
plugins/poll/test/javascripts/component/poll-results-standard-test.js

The skipped tests have become flaky after
e3b6be15b88a9b61b409ec3f266ba7b076efb1d7, skip those tests for now while
we sort things out.
Evidence of the test being flaky: https://github.com/discourse/discourse/actions/runs/9802263684/job/27066725334

DEV: Skip flaky poll QUnit acceptance tests

---

app/assets/javascripts/admin/addon/models/admin-plugin.js
app/assets/javascripts/discourse-common/addon/lib/case-converter.js
app/assets/javascripts/discourse-markdown-it/src/features/bbcode-block.js
app/assets/javascripts/discourse/app/lib/user-search.js
app/assets/javascripts/discourse/tests/unit/lib/case-converter-test.js
lib/pretty_text.rb

The AdminPlugin JS model uses a similar pattern to chat models,
where it is a plain JS class manually converting provided
snake_case attributes from the serializer to JS camelCase.
However this doesn't work when it comes to using `add_to_serializer`
in plugins since core does not know about these new attributes.
Instead, we can use a JS function to convert snake_case to camelCase
and use that when initializing AdminPlugin. This commit also moves
similar functions to a new case-converter.js file in
discourse-common/lib.

DEV: Add case-converter common lib and use with AdminPlugin

---

lib/discourse_logstash_logger.rb
spec/lib/discourse_logstash_logger_spec.rb

This is a very partial revert of a change introduced in 8e10878e1a37a608b0e1705bf9d0a06a295b8a63
In our official Docker image, running git commands results in the
following error:
```
fatal: detected dubious ownership in repository at '/var/www/discourse'
To add an exception for this directory, call:
git config --global --add safe.directory /var/www/discourse
```

DEV: Remove `git_version` from `DiscourseLogstashLogger` log event

---

plugins/poll/assets/javascripts/discourse/components/poll-info.gjs
plugins/poll/test/javascripts/component/poll-info-test.js

See: https://meta.discourse.org/t/polls-causing-issues/315088?u=merefield
This critical issue began with a simple typo (`I18n` versus `i18n` in template - note this is now more of a risk in `.gjs` files), but needed a little extra work to ensure correct rich formatting of all Component labels were fully implemented.
@nattsw @ZogStriP

FIX: Poll: critical display issue when results are only shown upon vote

---

app/assets/javascripts/discourse/app/controllers/preferences/profile.js
spec/system/page_objects/pages/user_preferences_profile.rb
spec/system/user_page/user_preferences_profile_spec.rb

When editing your bio in your user profile and then saving it, it would be removed from the profile header section.
This was broken for over 7 years since ae68795d8206a6a796d7d65e63bd2af3509be704 was merged 😅
Context - https://meta.discourse.org/t/after-saving-changes-to-profile-expanding-full-profile-only-shows-half/314118

FIX: show cooked bio in user profile

---

app/assets/javascripts/discourse/app/templates/mobile/components/parent-category-row.hbs
app/assets/javascripts/discourse/app/templates/mobile/components/subcategories-with-featured-topics.hbs
app/assets/javascripts/discourse/tests/acceptance/categories-test.js

The featured topics have not been rendered correctly since 2190c9b and it has been fixed for desktop recently in commit d2a52c3. This commit implements similar changes that initialize Category and Topic object instances from the serialized data.

FIX: Show featured topics for categories on mobile

---

plugins/poll/assets/stylesheets/common/poll.scss

Long option text was not wrapping nicely as new Glimmer based options are buttons where, by default, text wraps centre aligned.  This PR resolves the issue.
The issue affects both mobile and desktop.
becomes:
@ZogStriP

FIX: Poll: option text wrapping behaviour styling improvement

---

app/controllers/search_controller.rb
app/models/search_log.rb
db/migrate/20240705153533_add_user_agent_to_search_logs.rb
lib/search.rb
spec/models/search_log_spec.rb

Add a new column - `user_agent` - to the `SearchLog` table. 
This column can be null as we are only allowing a the user-agent string to have a max length of 2000 characters. In the case the user-agent string surpasses the max characters allowed, we simply nullify the value, and save/write the log as normal.

DEV: Add `user_agent` to `search_logs`

---

plugins/poll/assets/javascripts/discourse/components/poll-options.gjs
plugins/poll/assets/javascripts/discourse/components/poll-results-standard.gjs
plugins/poll/test/javascripts/component/poll-options-test.js

Relates to recent Glimmer migration of Poll plugin. #27204 
See discussion: 
* https://meta.discourse.org/t/polls-causing-issues/315088/6?u=merefield
* https://meta.discourse.org/t/polls-with-markup-show-html-tags/315253?u=merefield
Images and rich text styling were being blocked in options html.
@ZogStriP

FIX: Poll: allow safe html in options, not just text

---

app/assets/javascripts/admin/addon/models/admin-plugin.js
app/assets/javascripts/discourse/tests/unit/models/admin-plugin-test.js

For example, https://github.com/discourse/docker_manager

UX: plugins may have underscore in the name

---

plugins/poll/assets/javascripts/discourse/components/poll-info.gjs

Reference to string poll.results.close.title should be "closed" instead of "close"
Very small typo in I18n string name:  https://github.com/discourse/discourse/blob/6022cc2af883323449092f3ad128b96c68fae9a3/plugins/poll/config/locales/client.en.yml#L21

FIX: typo in poll "closed"

---

config/initializers/101-lograge.rb

This commit monkey patches `Rails::Rack::Logger` to not log reqeust
information like `Started GET "/service-worker.js" for 127.0.0.1 at 2024-07-05 15:28:12 +0800`
when lograge is enabled. This was previously excluded by a monkey patch
in the `lograge` gem but that monkey patch has since broke and the gem
is unmaintained.

DEV: Remove noise from `Rails::Rack::Logger` after Rails 7.1 upgrade

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/serializers/current_user_serializer.rb
config/site_settings.yml
spec/system/admin_flags_spec.rb

Adds experimental_flags_admin_page_enabled_groups (default "")
to remove the Moderation Flags link from the admin sidebar for now,
there are still a few bugfixes that need to be done before we
are comfortable with turning this on more widely. This is
a _temporary_ flag, we will be removing this once the feature
is more stable.

DEV: Hide admin Moderation Flags UI behind feature flag for now

---

app/models/search_log.rb
spec/models/search_log_spec.rb

This is a follow up to 005f623c42b0e18392cc0ad29432961b3df7dccb where
we want to truncate the user agent string instead of nulling out the
column when the user agent string is too low. By truncating, we still
get to retain information that can still be useful.

DEV: Truncate user agent string when it is too long instead of null

---

app/controllers/topics_controller.rb

Followup to 527f02e99fee782f53e206f739fb4f12d63b6d2a,
I had to introduce defer_track_visit_v2 because discourse-docs
relied on defer_track_visit. Now that discourse-docs
is using the new method as of
discourse/discourse-docs@0d9365571ba8fed69302f0351b3ccc924d6773c1,
we can rename it in core. Then we will need one more PR
in both core and docs to remove usage of the "v2" method.

DEV: Renaming TopicsController defer track visit

---

plugins/poll/assets/javascripts/discourse/components/poll-results-pie.gjs
plugins/poll/test/javascripts/acceptance/poll-pie-chart-test.js
plugins/poll/test/javascripts/component/poll-results-pie-test.js
plugins/poll/test/javascripts/component/poll-results-standard-test.js

`afterUpdate` from chart.js is not integrated with the runloop and component lifecycle, as a result we have no guarantee on when it will happen. The easiest change we can do for now is ensuring we actually have the DOM we expect to have, and if not, we exit early.

DEV: Check for poll element presence

---

app/assets/javascripts/discourse/app/lib/ember-events.js
app/assets/javascripts/discourse/tests/test-boot-ember-cli.js

`import Ember from "Ember"` will be deprecated in an upcoming version of Ember

DEV: Drop `Ember` 'barrel file' import

---

app/assets/javascripts/admin/addon/components/admin-plugin-config-page.gjs
app/assets/javascripts/admin/addon/templates/plugins-index.hbs
app/assets/javascripts/admin/addon/templates/plugins-show-settings.hbs
app/assets/javascripts/discourse/app/components/d-breadcrumbs-item.gjs
app/assets/javascripts/discourse/tests/integration/components/d-breadcrumbs-test.gjs

Example:
```hbs
<DBreadcrumbItem
@path="/admin/plugins/{{@plugin.name}}"
@label={{@plugin.nameTitleized}}
/>
```
Using `@path` instead of `@route`+`@model` combo makes it impossible to pass temporarily unresolvable routes.
This fixes a bug with navigating from a model-based route to a parent route.

DEV: Simplify breadcrumbs by using `path` arg

---

app/assets/stylesheets/common/modal/login-modal.scss

Fixes this issue with long translations:
After:
Truncating here isn't *ideal* but at least prevents the layout from breaking. Perhaps in this specific instance a shorter translation could also be possible for Spanish.

UX: add max-width to social auth section

---

app/assets/javascripts/discourse/app/raw-templates/mobile/list/topic-list-item.hbr

On the topic list and mobile view, this adds a missing space before the featured link.
Before:
After:

UX: Insert a space before the featured link on mobile topic list view

---

app/assets/javascripts/discourse/app/mixins/card-contents-base.js
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/components/user-card.scss
plugins/chat/assets/stylesheets/desktop/base-desktop.scss

This fixes a minor bug and prepares usercards to be scalable at any browser zoom level or viewport width to improve accessibility. 
**Minor bug fix:** 
The default `max-width` on `dMenu` instances is set to `400px`, but the user card is wider. The card overflows the container so this usually doesn't matter on large screens... but on small screens it means the card is improperly positioned and causes horizontal overflow.
This is because it's positioned based on the smaller max-width rather than the real dimensions. 
Before: 
After:
**Scalability:** 
On smaller screens the usercard is just too wide to fit (we have a separate stylesheet for mobile devices)... at the moment it doesn't scale below its default width, but this gets it headed in that direction. With the max-width removed from the …

UX: fix card positioning, allow shrink-to-fit

---

config/initializers/101-lograge.rb
config/site_settings.yml
db/migrate/20240709015048_remove_logging_provider_site_setting.rb

This site setting has always been experimental and hidden since it was
added 7 years ago. Drop it to simplify the way we enable logging in a
logstash friendly way.
Also dropping `ENABLE_LOGRAGE` env in favor of just `ENABLE_LOGSTASH_LOGGER`. There is almost no use case where we only want lograge to be enabled.

DEV: Drop `logging_provider` site setting

---

spec/system/admin_site_setting_requires_confirmation_spec.rb
spec/system/page_objects/pages/admin_site_settings.rb

Waiting for the dialog to close was not enough,
need to wait for the overridden indicator to
show on the site setting.

DEV: Fix flaky admin confirmation spec

---

config/site_settings.yml
lib/file_store/s3_store.rb
lib/s3_inventory.rb
spec/lib/s3_inventory_spec.rb

This commit adds a hidden `s3_inventory_bucket_region` site setting to
specify the region of the `s3_inventory_bucket` when the `S3Inventory`
class initializes an instance of the `S3Helper`. By default, the
`S3Helper` class uses the value of the `s3_region` site setting but the
region of the `s3_inventory_bucket` is not always the same as the
`s3_region` configured.

DEV: Add hidden `s3_inventory_bucket_region` site setting

---

app/models/concerns/reports/topic_view_stats.rb
app/models/report.rb
config/locales/server.en.yml
spec/fabricators/topic_view_stat_fabricator.rb
spec/models/report_spec.rb

Adds a report to show the top 100 most viewed topics in a date range,
combining logged in and anonymous views. Can be filtered by category.
This is a followup to 527f02e99fee782f53e206f739fb4f12d63b6d2a
and d1191b7f5fbe9e8ea1b645d5a61c79fa93693c0c. We are also going to
be able to see this data in a new topic map, but this admin report
helps to see an overview across the forum for a date range.

FEATURE: Topic view stats report

---

app/views/topics/show.html.erb
spec/requests/topics_controller_spec.rb

When a crawler visits a topic that has a deleted author, it would error because the `show.html.erb` view was expecting a user to be always present.
This ensure we don't render the "author" meta data when the author of the topic has been deleted.
Internal ref t/132508

FIX: deleted topic author in crawler view

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js

DEV: Add `d-button-action-string` deprecation to admin warnings

---

spec/fabricators/redelivering_webhook_event_fabricator.rb
spec/jobs/redeliver_web_hook_events_spec.rb

It is a PR to add a test for checking redeliver_web_hook_events job not to delete webhook event in process.

DEV: Specs for redeliver_web_hook_events job

---

app/controllers/application_controller.rb
config/site_settings.yml
db/migrate/20240709010639_remove_cross_origin_unsafe_none_referrers_setting.rb
spec/requests/application_controller_spec.rb

Followup 3ff7ce78e782c7d28c8b5a1a3f40a1de897d89a1
Basing this setting on referrer was too brittle --
the referrer header can easily be ommitted or changed.
Instead, for the small amount of use cases that this
site setting serves, we can use a group-based setting
instead, changing it to `cross_origin_opener_unsafe_none_groups`
instead.

FEATURE: Use group based setting for unsafe-none COOP

---

app/assets/javascripts/discourse/app/components/group-activity-filter.gjs
app/assets/javascripts/discourse/app/components/group-activity-filter.hbs
app/assets/javascripts/discourse/app/components/group-activity-filter.js

DEV: migrates group-activity-filter to gjs

---

plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs
plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/config/locales/client.en.yml
plugins/chat/spec/system/message_errors_spec.rb
plugins/chat/spec/system/page_objects/chat/chat_channel.rb
plugins/chat/spec/system/page_objects/chat/chat_thread.rb
plugins/chat/spec/system/page_objects/chat/components/composer.rb

Prior to this fix we would show the message after a round trip to the server. If you had a too long message error, at this point your input would be empty and we would show an error in chat. It's important to have this sever side safety net, but we can have a better UX by showing an error on the frontend before sending the message, that way you can correct your message before sending it and not lose it.

FIX: show too long message error on client

---

app/assets/javascripts/discourse/app/components/sidebar/anonymous/custom-sections.gjs
app/assets/javascripts/discourse/app/components/sidebar/common/custom-sections.gjs
app/assets/javascripts/discourse/app/components/sidebar/section.gjs
app/assets/javascripts/discourse/app/components/sidebar/user/custom-sections.gjs
app/assets/javascripts/discourse/app/lib/sidebar/section.js
app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js
spec/system/custom_sidebar_sections_spec.rb
spec/system/page_objects/components/navigation_menu/base.rb

Handles the cases where the sections titles are Unicode only strings, allowing them to be expanded separately if the Unicode string contains letters.
Also prevents a sidebar section with the header hidden to be displayed collapsed.

DEV: Improve sidebar section expansion handling

---

lib/discourse_logstash_logger.rb
spec/lib/discourse_logstash_logger_spec.rb

This commit updates `DiscourseLogstashlogger` to add the
`exception_class` and `exception_message` field to the log line when the
`progname` of the log message is `web-exception` which is Logster's
logging of exceptions during a web request.
The `exception_class` and `exception_message` fields allows consumers of
the logs to easily group logs together.
1. Run `RAILS_DISABLE_ACTIVERECORD_LOGS=1 ENABLE_LOGSTASH_LOGGER=1 bin/rails s`
2. Run `tail -f log/development.log | grep "exception_field"`
3. Go to `application_controller` and just trigger a syntax error in one of the `before_action`
4. See that the error log line contains the `exception_class` and `exception_message`fields

DEV: Add exception class and message fields to `DiscourseLogstashLogger`

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js

We prefer not to use these Ember array extensions anymore

DEV: Remove findBy usage in admin-sidebar

---

lib/discourse_logstash_logger.rb
spec/lib/discourse_logstash_logger_spec.rb

This reverts commit bb0daa33cd93eeffb230689d1daacd737f61b2e7.
This commit was not causing the problems we thought it was.

Revert "DEV: Remove `git_version` from `DiscourseLogstashLogger` log event (#27730)"

---

lib/discourse_logstash_logger.rb
spec/lib/discourse_logstash_logger_spec.rb

This is the second take of af2bd4cc5097501ff0f11f497b8d6f6984cea9ae to
account for messages which contains newlines.

DEV: Add exception class/message to `DiscourseLogstashLogger` take 2

---

app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/preferences-profile.js
app/assets/javascripts/discourse/app/routes/preferences-second-factor.js
app/assets/javascripts/discourse/app/services/restricted-routing.js

When a user action is required and enforced, such as filling up newly added required fields or adding a 2FA method, we disable routing on the client-side. However, this could be bypassed by first loading an always allowed page, such as `/faq` and then client-side routing away from there.
1. Move the logic for checking if routing is restricted and if a given path is allowed into a service.
2. Hoist the `willTransition` hook into the application router and use the newly created service to check whether to abort transitions or not.

FIX: Disallow all client-side routing when action is required

---

app/assets/javascripts/discourse/app/services/header.js
app/assets/javascripts/discourse/tests/unit/services/header-test.js

Followup 0434112aa71fc091583d8356a84fbf958f7228fb,
we introduced HideApplicationHeaderButtons there
but didn't validate the buttons passed to it. With this
commit we do, and send an error to the browser console
if an invalid one is used.

DEV: Make sure header hidden buttons are valid

---

lib/discourse_logstash_logger.rb
spec/lib/discourse_logstash_logger_spec.rb

This commit updates `DiscourseLogstashLogger#add_with_opts` to avoid
logging messages that matches regexp patterns configured in
`Logster.store.ignore`. Those error logs are mostly triggered by clients
and do not serve any useful purpose.

DEV: Apply `Logster.store.ignore` to `DiscourseLogstashLogger` as well

---

app/assets/javascripts/discourse/app/templates/review-index.hbs

On the review page, once you select a category to filter by, while you can still change the category, you can not clear it.
Pass the "clearable" select-kit option through.
**Before:**
**After:**

FIX: Make category filter in review page clearable

---

app/models/draft_sequence.rb
db/migrate/20240705134114_clear_orphaned_draft_upload_references2.rb
spec/models/draft_sequence_spec.rb

Drafts used to be deleted instead of being destroyed. The callbacks that clean up the upload references were not being called. As a result, the upload references were not cleaned up and uploads were not deleted either. This has been partially fixed in 9655bf3e.

FIX: Destroy Drafts when increasing sequences

---

config/locales/server.en.yml
lib/email/receiver.rb
spec/lib/email/receiver_spec.rb

This change how we present attachments from incoming emails to now be "hidden" in a "[details]" so they don't "hang" at the end of the post.
This is especially useful when using Discourse as a support tool where email is the main communication channel. For various reasons, images are often duplicated by email user agents, and hiding them behind the details block help keep the conversation focused on the isssue at hand.
Internal ref t/122333

FEATURE: email attachments in a details

---

config/locales/server.en.yml
spec/integrity/i18n_spec.rb

Before Rails 7.1, the `config.i18n.raise_on_missing_translations` option was raising only in controllers and views, now it’s anywhere in the app.
It means it raises each time `#description` is called for a setting that is missing a proper description (and we have a ton of them). Most of the time it’s fine, as those are usually settings that aren’t shown to the user.
We can’t just let the code blow up every time there’s a setting with a missing description, that’s why it’s currently returning an empty string when the translation is missing.
However, this silently broke our I18n integrity spec that was relying on the old “Translation missing” message to detect missing translations.
This PR addresses this issue by checking the description isn’t an empty string. It caught a missing …

DEV: Fix the I18n integrity spec

---

app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs

This only affected one test. And in that case, when changing a value in JS, it is perfectly normal to make the developer write a manual `await settled()` before asserting the state of the DOM.
Also adds `assert.async()` to the test so that we can be sure the callback was triggered.

DEV: Remove unneeded `next()`

---

app/assets/javascripts/discourse/app/components/navigation-item.hbs

this concerns the latest/top/categories nav:
"page" is a more specific value than "true", and indicates that this is the currently active page 
"true" is more appropriate for an active state that doesn't necessarily correspond with a page change, like the currently selected state in a list

A11Y: aria-current="page" is more appropriate for navigation bar links

---

app/assets/javascripts/discourse/app/templates/user/notifications.hbs

Changing the copy to `replies` to be consistent with other places.

UX: user page copy change responses -> replies

---

app/assets/javascripts/discourse/app/components/topic-entrance.hbs
app/assets/javascripts/discourse/app/components/topic-entrance.js
app/assets/javascripts/discourse/app/components/topic-list/topic-entrance.gjs
app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.js
config/locales/client.en.yml

For the topic entrance menu, when clicking reply counts on topic lists
* includes date in aria-label
* includes title that says "jump to first/last post"
This makes the information consistent between both experiences, previously the date was omitted from the aria-label (which only said "jump to first/last post") and the title describing the functionality wasn't present in the menu itself (just the visible dates)

A11Y: improve topic entrance aria-label, title

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/desktop/menu-panel.scss

Made some adjustments for both drop-down and slide-in modes, as you can remain in drop-down mode if you open the panel and then zoom (slide-in mode activates when you zoom first, then open the panel) 
before
after
before
after

A11Y: improve notification panel layout for high zoom levels

---

app/assets/javascripts/select-kit/addon/components/notifications-button.js

This commit adds the missing title for notifications-button. In the past, it was automatically fallbacked to the button's key.
Related meta topic: https://meta.discourse.org/t/tracking-toggle-text-on-hover-sometimes-not-translated/315727
before: 
after:

UX: Add missing title to notifications-button

---

plugins/poll/assets/javascripts/discourse/components/poll-buttons-dropdown.gjs
plugins/poll/test/javascripts/component/poll-buttons-dropdown-test.js

relates to #27204 
see: https://meta.discourse.org/t/what-is-the-gear-button-under-the-poll-for/315477/2
During migration of Poll plugin from widget basis to glimmer, some functionality was inadvertently dropped:
* A single button should appear instead of the dropdown menu when there is only one valid "poll admin" action
* No button should appear when there are no valid "poll admin" actions for current user
This PR restores the original behaviour and adds test coverage (that didn't exist prior to migration, partly why it wasn't caught earlier)

FIX: Poll: visibility of gear button

---

app/assets/javascripts/discourse/app/templates/preferences/profile.hbs

Remove `span` tags around plugin outlets in profile preferences as they cannot contain block elements.

UX: Remove PluginOutlet spans

---

app/services/email_settings_validator.rb
spec/services/email_settings_validator_spec.rb

Both office365 and outlook SMTP servers need LOGIN
SMTP authentication instead of PLAIN (which is what
we are using by default). This commit uses that
unconditionally for these servers, and also makes
sure to use STARTTLS for them too.
Also extends the `read_timeout` for testing SMTP
email settings, since some servers (like outlook) add
artificial error delays.

FIX: Office365/Outlook auth method for group SMTP

---

lib/discourse_logstash_logger.rb
lib/sidekiq_logster_reporter.rb
spec/lib/discourse_logstash_logger_spec.rb

This commit improves the logging of Sidekiq errors when
`ENABLE_LOGSTASH_LOGGER` is set to 1. Prior to this change, we would
only log the message and the backtrace. After this change, useful
information like `job.class`, `job.opts`, `job.problem_db`,
`exception.class` and `exception.message` are included in the log line
as well.
This change is hard to cover with automated tests completely so some manual testing is required. To test this change locally, follow the steps below: 
1. Update `app/jobs/scheduled/about_stats.rb` to the code below:
```
module Jobs
class AboutStats < ::Jobs::Scheduled
every 10.seconds
def execute(args)
raise "boom"
About.refresh_stats
end
end
end
```
3. Run `UNICORN_SIDEKIQS=1 RAILS_DISABLE_ACTIVERECORD_LOGS=1 ENABLE_LOGSTASH_LOGGER=1 bin/rails s`
4. Run `tail -f …

DEV: Improve logging of Sidekiq errors when logstash logger is enabled

---

app/models/reviewable.rb
lib/discourse_plugin_registry.rb
lib/plugin/instance.rb
spec/lib/plugin/instance_spec.rb

Currently, when a plugin registers a new reviewable type or extends a list method (through `register_reviewble_type` and `extend_list_method` respectively), the new array is statically computed and always returns the same value. It will continue to return the same value even if the plugin is disabled (it can be a problem in a multisite env too).
To address this issue, this PR changes how `extend_list_method` works. It’s now using `DiscoursePluginRegistry.define_filtered_register` to create a register on the fly and store the extra values from various plugins. It then combines the original values with the ones from the registry. The registry is already aware of disabled plugins, so when a plugin is disabled, its registered values won’t be returned.

FIX: Don’t list values from disabled plugins

---

app/assets/javascripts/admin/addon/components/ace-editor.js

- set in constructor so they're guaranteed to be present, even if async-import hasn't finished yet
- ensure they're all cleaned up properly
- combine two cleanup methods into one

DEV: Cleanup ace-editor event listeners

---

app/assets/javascripts/discourse/app/components/empty-state.gjs
app/assets/javascripts/discourse/app/components/empty-state.hbs
app/assets/javascripts/discourse/app/components/empty-state.js

Technically there was a wrapping div here, but that shouldn't be necessary.

DEV: migrates empty-state to gjs

---

app/controllers/application_controller.rb
config/routes.rb
spec/requests/posts_controller_spec.rb

Our global error handler for `ActiveRecord::RecordInvalid` only handles JSON requests. This causes multiple errors on the backend that are not properly exposed to the user.
My change assumes that the default format will be JSON, as this is what our FE expects.
Alternatively, we could explicitly add the JSON format to the request, but I think handling this at the BE is a better solution.

FIX: Allow error handling for formats besides JSON

---

script/bulk_import/generic_bulk.rb

Currently, quotes imported via generic bulk import script do not include references to the quoted post. This change includes both topic and post attributes in a quote BBCode if the placeholder metadata includes a `post_id`

DEV: Include post and topic attributes in imported quotes

---

app/models/tag.rb
app/serializers/detailed_tag_serializer.rb

The 'permissions' field is used by the composer and the category chooser to render the category.

FIX: Include permissions in the tag serializer

---

app/assets/javascripts/discourse/app/components/desktop-notification-config.gjs

This localization string is missing a wrapping `span` for cleaner styling. Text should not be unwrapped if siblings exist within the same parent, in this case `DButton`.

UX: Wrap text in span

---

app/assets/javascripts/admin/addon/components/site-settings/integer.gjs
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.js

Followup db993cf8fd6b24b967509bbd4b35014e0b6e3749
Since in the above commit we converted integer site settings
to actual integers then set that as the new `buffered.value`,
the overridden indicator technically thinks the value has changed,
even if the user sets it back to the default:
```
overridden: propertyNotEqual("setting.default", "buffered.value"),
```
We can fix this by converting the parsed integer back to a string
before setting the buffered setting value.

FIX: Integer settings wrongly showing overridden from default

---

plugins/chat/app/services/chat/create_message.rb
plugins/chat/db/migrate/20240711153837_add_created_by_sdk_to_chat_messages.rb
plugins/chat/db/post_migrate/20240711154622_update_chat_messages_created_by_sdk.rb
plugins/chat/lib/chat/mailer.rb
plugins/chat/lib/chat_sdk/message.rb
plugins/chat/spec/components/chat/mailer_spec.rb
plugins/chat/spec/lib/chat_sdk/message_spec.rb

This change allows us to distinguish between regular user generated chat messages and those created via the Chat SDK.
A new `created_by_sdk` boolean column is added to the Chat Messages table. When this is value is true, we will not include the message in the user summary email that is sent to users.

FEATURE: prevent chat emails for messages created via SDK

---

plugins/chat/app/services/chat/create_message.rb

A change made in #27875 added a new step to the create message service, however the step should have been placed before saving the message.

FIX: update order of chat message service steps

---

app/assets/javascripts/discourse/app/app.js

This needs to run before any component files are `import`'d. In traditional resolver-based tests, this was working previously because component files would only be loaded 'at runtime'. However, in gjs-based tests (e.g. those introduced in the formkit PR), component files are imported before the application is booted.

DEV: Ensure implicit injections shim is run early

---

app/assets/stylesheets/common/base/user.scss

Fixes minor issue caused by https://github.com/discourse/discourse/pull/25576
Before:
After:

UX: fix top-list spacing on user summary

---

app/assets/javascripts/discourse/lib/babel-plugin-safari-class-fields-bugfix.js

This tightens things up to reduce the number of initializers which need to be wrapped in an IIFE.
Mirrors the changes made in https://github.com/babel/babel/pull/16569

DEV: Improve safari-class-fields-bugfix transform

---

app/assets/javascripts/discourse/app/components/modal/spreadsheet-editor.gjs
spec/system/table_builder_spec.rb

The old table builder would fill empty headers with default values A~Z when editing. This commit makes table-builder respect the old empty headers.
This is due to a behavior of jspreadsheet that cannot be turned off (see https://bossanova.uk/jspreadsheet/v4/docs/getting-started#Header-titles ). We have to pass in a value that cannot be implicitly converted to false in the JavaScript sense. In this case, we pass in a space, which is the same as the empty string in the visual sense.
before: 
The table-builder will fill the empty header with the default values ​​of A~Z and save it.
after:
Allows an empty header (strictly speaking, it is a space `" "`)
related meta topic: https://meta.discourse.org/t/editing-a-table-with-empty-headers-fills-them-in-with-the-default-text-column-a-column-b/26847 …

FIX: Don't let table-build automatically fill empty headers with default values

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
app/assets/javascripts/discourse/app/components/flag-action-type.js
app/assets/javascripts/discourse/app/components/modal/flag.js
app/assets/javascripts/discourse/app/models/post-action-type.js
app/assets/javascripts/discourse/tests/fixtures/site-fixtures.js
app/assets/javascripts/discourse/tests/helpers/site.js
app/assets/stylesheets/common/admin/flags.scss
app/models/concerns/reports/moderators_activity.rb
app/models/flag.rb
app/models/post.rb
app/models/post_action_type.rb
app/models/user.rb
app/serializers/flag_serializer.rb
app/serializers/post_action_type_serializer.rb
app/services/flags/create_flag.rb
app/services/flags/update_flag.rb
config/locales/client.en.yml
db/fixtures/003_flags.rb
db/post_migrate/20240703232446_rename_flags_custom_type_to_require_message.rb
lib/badge_queries.rb
lib/flag_settings.rb
lib/guardian/post_guardian.rb
lib/post_action_creator.rb
lib/post_revisor.rb
spec/lib/flag_settings_spec.rb
spec/models/post_action_spec.rb
spec/requests/api/schemas/json/site_response.json
spec/services/flags/create_flag_spec.rb
spec/services/flags/update_flag_spec.rb

Allow admin to create custom flag which requires an additional message.
I decided to rename the old `custom_flag` into `require_message` as it is more descriptive.

FEATURE: custom flag can require additional message

---

spec/system/admin_flags_spec.rb

Because of the global flag cache, those specs should not run in parallel. We need to execute them sequentially.

DEV: unparallel flags system spec

---

app/controllers/users_controller.rb
spec/requests/users_controller_spec.rb

We have recently added a new option to add user fields required for existing users. This is in contrast to requiring fields only on sign-up.
This revealed an existing problem. Consider the following:
1. User A signs up.
2. Admin adds a new user field required on sign-up. (Should not apply to User A since they already signed up.)
3. User A tries to update their profile.
**Expected behaviour:**
No problem.
**Actual behaviour:**
User A receives an error saying they didn't fill up all required fields.
When updating profile, we only check that required fields that are "for all users" are filled. Additionally, we check that fields that were required on sign-up and have previously been filled are not blanked out.

FIX: Don't require fields required on sign-up when updating fields

---

app/views/topics/show.html.erb

We're seeing a new glaring error on Google Search Console where we are getting warned the following:
The reason for this is because we report post replies as a "CommentAction". In a recent change by Google Search Console, they've required that we nest another "Comment" (post) in each post that has >1 "CommentActions" (reply). 
"Replies" in non-crawler view makes a request when clicked to get all replies, however this does not make sense in the crawler view where we load everything per post number. 
So the solution here is to exclude the reply number so we can avoid having to nest all replies in a post.
Meta: https://meta.discourse.org/t/missing-comment-field-in-comment/313624

FIX: Exclude reply count on posts due to required Comment nesting

---

app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/sidebar.scss

We lost these by mistake in fed90558188a03690010feb7239c0945808f384e,
this reinstates them.

FIX: Bold admin sidebar headings

---

app/controllers/static_controller.rb
spec/requests/static_controller_spec.rb

This commit updates `StaticController#enter` to not redirect to invalid
paths when the `redirect` param is set. Instead it should redirect to `/` when the
`redirect` param is invalid.

FIX: `StaticController#enter` should not redirect to invalid paths

---

plugins/chat/spec/services/chat/update_message_spec.rb

This is consistently failing on image build.

DEV: Temporarily skip failing test on CI

---

app/assets/stylesheets/common/base/user.scss

Follow-up to https://github.com/discourse/discourse/pull/27877, this needed an additional fix for `prioritize username in ux` being disabled
Before:
After:

UX: fix name & username width on profile summary

---

app/services/email_settings_exception_handler.rb
config/locales/server.en.yml
spec/requests/groups_controller_spec.rb
spec/services/email_settings_exception_handler_spec.rb
spec/services/problem_check/group_email_credentials_spec.rb

Originally in 964da218173db007fefe6357e96292f5545c513e
we hid the SMTPAuthenticationError message except in
very specific cases. However this message often contains
helpful information from the mail provider, for example
here is a response from Office365:
> 535 5.7.139 Authentication unsuccessful, user is locked by your
organization's security defaults policy. Contact your administrator.
So, we will show the error message in the modal UI instead
of supressing it with a generic message to be more helpful.

FIX: Show the SMTP authentication error for group UI

---

lib/topic_query.rb
lib/topic_query_params.rb
spec/requests/list_controller_spec.rb

This commit updates `TopicQuery.validators` to cover all of the
public options listed in `TopicQuery.public_valid_options`. This is done
to fix the app returning a 500 response code when an invalid value, such
as a hash, is passed as a query param when accessing the various topic
list routes.

FIX: Return 400 response codes when topic list query params are invalid

---

app/mailers/group_smtp_mailer.rb
app/services/email_settings_validator.rb
lib/smtp_provider_overrides.rb
spec/mailers/group_smtp_mailer_spec.rb

Followup 7b627dc14b934430f62a59fbcf09b0595ee94567
In this other commit, I changed the email settings validator
to always use the `login` authentication method for
office365 and outlook, but I didn't change the actual
group SMTP mailer to do this.
This commit fixes that issue and does some minor refactoring.

FIX: Use login SMTP auth for office365 in group mailer

---

config/locales/plurals.rb

Hungarian actually has a plural form (See: https://meta.discourse.org/t/issue-with-pluralized-count-translation-override/316019/8)
In a past commit we introduced an external JS library to describe the plural form of the language. (https://github.com/discourse/discourse/commit/301713ef9631e52975781b60b8b4c4a0d75530cf) 
https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse-i18n/src/index.js#L7
```javascript
import * as Cardinals from "make-plural/cardinals";
```
But this JS library actually has a slightly different pluralization definition than what we use in the backend (`plurals.rb`). ruby-i18n incorrectly assumes that Hungarian does not have plural forms. This resulted in singular text being used on the front end for Hungarian, but admins were unable to find …

FIX: Add plural definitions for Hungarian

---

app/controllers/topics_controller.rb
app/models/user_history.rb
app/services/staff_action_logger.rb
config/locales/client.en.yml
spec/requests/topics_controller_spec.rb

Previously, we did not log any topic slow mode changes. This allowed some malicious (or just careless) TL4 users to delete slow modes created by moderators at will. Administrators could not see who changed the slow mode unless they had SQL knowledge and used Data Explorer.
This commit enables logging who turns slow mode on, off, or changes it.
Related meta topic: https://meta.discourse.org/t/why-is-there-no-record-of-who-added-or-removed-slow-mode/316354

FEATURE: Log topic slow mode changes

---

app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/header/hamburger-dropdown-wrapper.gjs
app/assets/javascripts/discourse/app/components/header/search-menu-wrapper.gjs
app/assets/javascripts/discourse/app/components/header/user-dropdown.gjs
app/assets/javascripts/discourse/app/components/header/user-menu-wrapper.gjs
app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.gjs
spec/system/header_spec.rb

When navigating the header menus with a keyboard, as focus leaves the menu, it should automatically close. When closing, focus should return to the menu trigger. 
This listens for `focusout` on `.panel-body` and ensures that it's a keyboard event and not a click to trigger the menu to close on `focusout`. 
The search menu already refocuses the menu button on close, so I've added it to the hamburger menu and user menu as well. 
I also move focus to the first link when the hamburger dropdown is opened, and add an ID for the user menu button. 
https://github.com/user-attachments/assets/32f8a55b-2ea4-4dda-ae28-008f703ba881

A11Y: Close header dropdown menus on focusout

---

app/assets/javascripts/discourse/app/components/group-card-contents.hbs
app/assets/javascripts/discourse/app/components/user-card-contents.hbs
app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
app/assets/stylesheets/common/components/user-card.scss
app/assets/stylesheets/desktop/components/user-card.scss
app/assets/stylesheets/mobile/components/user-card.scss

This removes the headings (h1, h2, h3) from the user and group cards, headings don't make sense in this context because they don't contribute to the overall document structure and can interfere with screenreader navigation. 
Visual styles here shouldn't change...
Before:
After: 
I did fix a couple of related issues while I was at it... 
* in the "before" you can see how "cheers" from a plugin wraps to the next line too early, this will no longer be the case
* the group cards were attempting to use some custom properties like `--avatar-width` but these were only scoped to the user card, so I added the group-card class there to remedy that 
* `h3.user-status` was hanging out without a parent selector, so it was destined to cause class name collisions... I moved it to be scoped within …

A11Y: remove heading tags from usercards

---

app/assets/stylesheets/desktop/components/more-topics.scss

This also removes a now redundant style
Before:
After:

UX: fix padding on suggested/related toggle in PMs

---

app/assets/stylesheets/common/base/topic-post.scss

The quote menu can overflow, especially on smaller screens/mobile and in languages with longer words
This commit addresses the issue by:
* letting the menu wrap if needed
* on smaller screens, switch to a stacked view

UX: fix overflowing quote bar

---

app/assets/stylesheets/common/components/more-topics.scss
app/assets/stylesheets/desktop/components/more-topics.scss

This positioning can also be applied to mobile, so I've moved it from /desktop to /common 
This fixes this minor mobile alignment issue...
before:
after:

UX: spacing fix for related topics on mobile

---

app/assets/stylesheets/common/components/badges.scss
app/assets/stylesheets/common/select-kit/select-kit.scss

this allows long names to truncate, if needed — `min-width: 0` needs to be applied to all the flex descendants until you reach the final text node
Before:
After:

UX: allow category names in select-kit to truncate if needed

---

app/models/web_hook_event_type.rb
spec/models/web_hook_event_type_spec.rb
spec/models/web_hook_spec.rb

Related: https://github.com/discourse/discourse-topic-voting/pull/196. Ideally to be merged around the same time.

DEV: Update webhook site setting for topic voting

---

plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js

Removes a hardcoded whitespace from rendered dates in the composer preview and posts 
Before:
After:

UX: remove whitespace from rendered localdate

---

lib/discourse_plugin_registry.rb
lib/plugin/instance.rb
lib/topics_filter.rb
spec/lib/topics_filter_spec.rb

Currently there is no way to add a custom filter to the experimental `/filter` endpoint. While you can implement a custom `status:` there is no way to include the user's input in a custom query. 
This PR adds the ability to implement a custom filter. eg. `CUSTOM_FILTER:foo`
- Add `add_filter_custom_filter` for extension
- Add specs

DEV: Support adding a custom filter on `/filter`

---

app/assets/stylesheets/common/form-kit/_control-menu.scss

The recent formkit css had an unintended bleed into every `fk-d-menu`.

UX: remove formkit css bleeding into every dropdown

---

config/site_settings.yml

We are removing support for IMAP, hiding these site
settings is the first step.
c.f. https://meta.discourse.org/t/imap-support-for-group-inboxes/160588/39

DEV: Hide IMAP site settings

---

app/models/flag.rb

Before migration is run flags code is evaluated. It is causing error:
```
NoMethodError: undefined method `require_message' for an instance of Flag (NoMethodError)
Did you mean?  require_dependency
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/attribute_methods.rb:489:in `method_missing'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/var/www/discourse/app/models/post_action_type.rb:64:in `reject'
```
The solution is to temporarily fall back to old column name - custom_type

FIX: fallback to custom type for flags

---

app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/form-test.gjs

This is a convenience for when you have multiple properties to set in form kit.
```
// before
set("foo", 1);
set("bar", 2);
//after
setProperties({foo: 1, bar: 2});
```

DEV: supports setProperties

---

app/assets/javascripts/discourse/app/components/header.gjs

Follow-up to https://github.com/discourse/discourse/commit/0d4492c7b743c0eb609e24663b52c85fe1e4d03f
When triggering a modal within a dropdown using keyboard nav, an error would occur: 
> Uncaught Error: Assertion Failed: You attempted to update `hamburgerVisible` on `<Header:ember767>`, but it had already been used previously in the same computation. Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
Using `schedule("afterRender")` defers this update and avoids the issue

FIX: avoid updating `hamburgerVisible` in the same computation

---

app/assets/javascripts/discourse/app/components/header.gjs

Follow-up to https://github.com/discourse/discourse/commit/6344e3f9379d048fef2c486423dcd4d2a7a6f443
This avoids the issue entirely by not triggering close when a modal is opened from a header dropdown... this also fixes an issue where focus was being removed from the modal due to the refocusing done in `closeCurrentMenu`

DEV: follow-up to avoid using schedule when opening modal from dropdown

---

app/assets/javascripts/discourse/app/components/plugin-outlet.js

We'd implemented the deprecation by overriding `get parentView`, and storing the real value on `_parentView`. Unfortunately that meant people could access `_parentView` directly, thereby bypassing the deprecation message.
This commit moves the internal storage to a private field, which cannot be accessed from outside the class. A deprecated getter for `_parentView` is introduced to avoid immediate breakage for any code using this workaround.

DEV: Ensure plugin outlet `parentView` deprecation cannot be avoided

---

app/assets/javascripts/discourse/app/services/modal.js
spec/system/custom_sidebar_sections_spec.rb

On modal `show()` this sets `triggerElement` to the `document.activeElement`, so that on `close()` it can be focused 
> Keyboard users should always be returned to where they were before they opened the dialog.
> https://accessibility.huit.harvard.edu/technique-accessible-modal-dialogs
this avoids forcing a keyboard nav user to have to start over with navigating the page when a modal is closed

A11Y: attempt to refocus modal trigger on modal close

---

app/assets/javascripts/admin/addon/components/admin-site-settings-filter-controls.gjs
app/assets/stylesheets/common/admin/admin_base.scss

On mobile, when the settings category list is expanded, the page content gets pushed to the right.
This PR fixes:
- Prevents the page content from being pushed to the right when the settings category list is expanded
- Adds visual separation between the settings category list and the page content
- Displays a close icon when the menu is open

UX: Fix page content overflow when the setting category list is expanded on mobile

---

lib/s3_inventory.rb
spec/lib/s3_inventory_spec.rb

This commit ensures that we reset the `missing_s3_uploads` status count
if there are no inventory files which are at least 2 days older than the
site's restored date.
Otherwise, a site with missing uploads but was subsequntly restored will
be continue to report missing uploads for 2 days.

DEV: Restore `missing_s3_uploads` stats count if site was restored

---

app/assets/javascripts/discourse/app/form-kit/lib/validation-parser.js
app/assets/javascripts/discourse/app/form-kit/lib/validator.js
app/assets/javascripts/discourse/tests/unit/lib/form-kit/validation-parser-test.js
app/assets/javascripts/discourse/tests/unit/lib/form-kit/validator-test.js
config/locales/client.en.yml

Usage:
```
@validation="integer"
```
This commit also adds a default for rules. By default a rule will now be `ruleName: {}`, this avoids all the boilerplate in validation-parser.js.

DEV: adds an integer validation rule to form-kit

---

plugins/chat/spec/system/chat_message/channel_spec.rb
plugins/chat/spec/system/chat_message/thread_spec.rb
plugins/chat/spec/system/transcript_spec.rb
spec/system/page_objects/cdp.rb
spec/system/post_menu_spec.rb
spec/system/post_selection_copy_quote_spec.rb

Retry clipboard copy tests until success. Moving this `try_until_sucecss` into a helper method so it doesn't have to be littered everywhere.
Inspiration from https://github.com/discourse/discourse-ai/blame/ef4b3559cd2b200e319da00bdf26a3e04ca7998a/spec/system/ai_bot/share_spec.rb#L59-L62 thanks to @davidtaylorhq

DEV: Try until success for clipboard copies

---

app/assets/javascripts/discourse/app/components/sidebar/section-header.gjs
app/assets/javascripts/discourse/app/components/sidebar/section.gjs

This is weird but the following line is not actually using the event we think it should be using, so we're making sure DButton passes in the correct one.
https://github.com/discourse/discourse/blob/278ae6e5fd1f79481ea30af7d0466cb5d7911f27/app/assets/javascripts/discourse/app/components/sidebar/section.gjs#L82

DEV: Forward the actual event into the sidebar header

---

app/models/topic_user.rb
spec/models/topic_user_spec.rb

A plugin needs to know when the user first enters a topic, and this is the correct spot. Add event and adjust tests to ensure the event is trigger only when it should be.

DEV: Publish DiscourseEvent in TopicUser.track_visit for first visit

---

plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js
plugins/chat/assets/javascripts/discourse/services/chat-state-manager.js

This is a performance optimisation to prevent the same route to keep reloading the same endpoint.
No tests as it's not changing behavior and is also quite complex to test efficiently.

FIX: do not reload identical route in drawer

---

lib/topics_filter.rb
spec/lib/topics_filter_spec.rb

When tags contain an underscore we should allow filtering in the same way, previously due to the regex those with underscores were not being found when filtering.
/t/-/133637

FIX: experimental topics filter should allow tags with underscore

---

app/models/post_action_type.rb
app/serializers/site_serializer.rb
spec/models/post_action_type_spec.rb

Flags are stored in the memory of the process and a fragment cache is not necessary.

FIX: drop fragment cache for flags

---

app/assets/javascripts/discourse/app/components/d-button.gjs
app/assets/javascripts/discourse/app/lib/after-frame-paint.js
app/assets/javascripts/discourse/app/mixins/card-contents-base.js
spec/system/homepage_spec.rb

Currently, user actions can trigger functions that render changes to the screen within the same cycle (e.g. pressing the reply button will cause the login modal to pop up), potentially impacting performance and causing some jank on slower devices.
This change inserts `runAfterFramePaint` where certain actions are triggered. Below are some screenshots indicating an improved INP for some of the buttons affected on controls with the highest INPs. The two places where this is added help with several actions, e.g. user + group cards, generic button action usage.
(Note: **Interaction to Next Paint**)
Before ---> After
Before ---> After

DEV: Defer button actions with layout change to the next frame paint

---

app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/services/restricted-routing.js
spec/system/user_page/user_preferences_profile_spec.rb

If a user has a required action, e.g. adding a 2FA method or filling in new required fields, we disable client-side routing except to allowed pages.
This led to a situation where a user might navigate away from e.g. the profile page to look at the new ToS, and then being "stuck" due to not knowing how to get back to accept the new terms.
This PR makes it so that if you click any restricted link, instead of doing nothing we transition the user back to the page where they can take the required action.

DEV: Redirect to actionable page if routing is restricted

---

app/controllers/admin/emojis_controller.rb
app/models/custom_emoji.rb
app/models/user_history.rb
app/services/staff_action_logger.rb
config/locales/client.en.yml
db/migrate/20240722025822_add_user_id_to_custom_emojis.rb
spec/requests/admin/emojis_controller_spec.rb

We didn't provide any logs for CustomEmoji before, nor did we record the person who added any emoji in the database. As a result, the staff had no way to trace back who added a certain emoji.
This commit adds a new column `user_id` to `custom_emojis` to record the creator of an emoji. At the same time, a log is added for staff logs to record who added or deleted a custom emoji.
Staff actions log:
Data Explorer:

FEATURE: Add creator and logging for CustomEmoji

---

config/locales/client.en.yml

Most people will not know what an integer is,
refer to this as a whole number for the human-readable
error message.

UX: Change copy for FormKit "not an integer" error

---

spec/system/topic_map_spec.rb

Followup https://github.com/discourse/discourse/commit/72fd509fd482351807488c7b590995b422ed1c92
Also skips the like counter part of this
spec which is flaky

DEV: Skip flaky topic map

---

app/models/post_action_type.rb
app/serializers/post_serializer.rb
app/serializers/site_serializer.rb
lib/guardian/post_guardian.rb
lib/topic_view.rb
spec/models/post_action_type_spec.rb
spec/requests/topics_controller_spec.rb

Memoizing all_flags on PostActionType was a mistake. This commit brings back the cache on the serialize level - reverts https://github.com/discourse/discourse/pull/28001

FIX: stop memoize PostActionTypes

---

app/assets/javascripts/discourse/app/components/ace-editor.js

Add `@submit` hook to AceEditor to handle "save and run" in Data Explorer
I need to respond to ctrl+enter in AceEditor in Data Explorer and was hoping to introduce a hook for `@submit` in core so that I could simply write code like this
```handlebars
<AceEditor
@save={{this.save}}
@submit={{this.saveAndRun}}
/>
```

DEV: add @submit hook for ace editor

---

app/helpers/embed_helper.rb

Previously, the time format for embedded comments was hardcoded. This commit changes it to the time format defined in I18n.
Related meta topic: https://meta.discourse.org/t/embed-dates-are-not-localized/27997/
before: 
after

UX: Use localized time format in embedded comments

---

app/models/tag_group.rb

In a plugin we were trying to test the tag_groups controller for permission handling... it was weird how the param of `:full` or `:readonly` was passing from the controller down to this method in the diff and the permission type was `nil` at the end of it... Reason was the hash we are looking into has symbol keys and we are checking
* If value is an integer, return it
* If value is **anything else** lookup the key/value pair.... but the keys are symbols...
So this adds a .to_sym :)

DEV: Improve TagGroup.resolve_permissions method arg type handling

---

lib/text_sentinel.rb
spec/lib/text_sentinel_spec.rb

This improves the `TextSentinel` so that we don't consider CJK text as being uppercase and thus failing the validator.
It also optimizes the entropy computation by using native ruby `.bytes` to get all the bytes from the text.
It also tweaks the `seems_pronounceable?` and `seems_unpretentious?` check to use the `\p{Alnum}` unicode regexp group to account for non-latin languages.
Reference - https://meta.discourse.org/t/body-seems-unclear-error-when-users-are-typing-in-chinese/88715
Inspired by https://github.com/discourse/discourse/pull/27900

FIX: Allow all caps within CJK text

---

app/assets/javascripts/discourse/app/routes/user-private-messages.js

The composer automatically prompting when you visit your messages is unexpected behavior. For ease of use, the composer should only prompt if the user intentionally wants to open a draft or start a new topic.

UX: Remove automatic composer prompt when draft exists

---

lib/discourse_logstash_logger.rb
spec/lib/discourse_logstash_logger_spec.rb

This ensures that elasticsearch doesn't parse it as an object. There are
too many combination of job opts so we don't want elasticsearch to be
parsing and indexing this field as an object.

DEV: Log sidekiq job opts as string instead of hash

---

app/services/flags/create_flag.rb
app/services/flags/update_flag.rb
spec/services/flags/create_flag_spec.rb

There is a bug with chat type flags - "An error occurred: Applies to is not included in the list"
Flag.valid_applies_to_types is a set of core types and types registered by plugins `Set.new(DEFAULT_VALID_APPLIES_TO | DiscoursePluginRegistry.flag_applies_to_types)`
Using lamba should ensure that valid values are calculated dynamically.

FIX: flag valid type inclusion should be lambda

---

app/assets/javascripts/admin/addon/routes/admin-backups.js

Followup dd3046327684ce98f0c3a7430f5d22fd35f1d9ca
We missed the explicit `return` when we changed to
async/await, so the model ends up being null on admin
backups.
This means we also have no tests for the backup UI, that
will be fixed in a subsequent PR.

FIX: Missing model return in admin-backups route

---

app/models/user_history.rb
app/services/staff_action_logger.rb
config/locales/client.en.yml
db/migrate/20240723030506_add_post_id_index_to_user_histories.rb
lib/post_destroyer.rb
spec/requests/posts_controller_spec.rb
spec/requests/topics_controller_spec.rb

When soft deleteing a topic or post, we will log some details in the staff log, including the raw content of the post. Before this commit, we will not clear the information in these records. Therefore, after permanently deleting the post, `UserHistory` still retains copy of the permanently deleted post. This is an unexpected behaviour and may raise some potential legal issues.
This commit adds a behavior that when a post is permanently deleted, the details column of the `UserHistory` associated with the post will be overwritten to "(permanently deleted)". At the same time, for permanent deletion, a new `action_id` is introduced to distinguish it from soft deletion.
Related meta topic: https://meta.discourse.org/t/introduce-a-way-to-also-permanently-delete-the-sensitive-info-from-the-staff- …

FEATURE: Clean up previously logged information after permanently deleting posts

---

app/controllers/topics_controller.rb

Fixed using next instead. It was causing this kind of errors:
```
Job exception: unexpected return
/var/www/discourse/app/controllers/topics_controller.rb:1304:in `block in defer_topic_view'
/var/www/discourse/lib/scheduler/defer.rb:115:in `block in do_work'
rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:49:in `with_connection'
rails_multisite-6.0.0/lib/rails_multisite/connection_management.rb:21:in `with_connection'
/var/www/discourse/lib/scheduler/defer.rb:109:in `do_work'
/var/www/discourse/lib/scheduler/defer.rb:97:in `block (2 levels) in start_thread'
```

FIX: return is invalid inside a block

---

plugins/chat/assets/stylesheets/desktop/chat-index-full-page.scss

Changing the sidebar bg colour of full-page chat mode without sidebar enabled, to be consistent with the other sidebar-esk variations.

UX: change sidebar background to secondary

---

app/assets/javascripts/discourse/app/components/topic-title.gjs
app/assets/javascripts/discourse/app/routes/topic-from-params.js
app/assets/javascripts/discourse/app/services/header.js
spec/system/header_spec.rb

- Ensure main title is set as 'not visible' when removed from DOM
- `deactivate` -> `willTransition` to ensure proper behavior when navigating between multiple topics
Followup to bdec564d1417c51ef6958784fdd6375fd05da4fc

FIX: Improve topic/header integration when navigating away

---

lib/text_sentinel.rb

by scanning the text for the first word that is bigger than `max_word_length` instead of extracting (segmenting) all the words, computing their size, and comparing the maximum with `max_word_length`.
Idea from @mentalstring in https://meta.discourse.org/t/body-seems-unclear-error-when-users-are-typing-in-chinese/88715/14

PERF: improves TextSentinel's seems_unpretentious check

---

config/initializers/100-onebox_options.rb
config/site_settings.yml
lib/final_destination.rb
lib/onebox/helpers.rb
spec/lib/onebox/helpers_spec.rb
spec/lib/oneboxer_spec.rb

Previously, we can't change the user agent name dynamically for onebox requests. In this commit, a new hidden site setting `onebox_user_agent` is created to override the default user agent value specified in the [initializer](https://github.com/discourse/discourse/blob/c333e9d6e6a6a0407133eb2d5087605897048f95/config/initializers/100-onebox_options.rb#L15).

FEATURE: use new site setting for onebox custom user agent.

---

app/controllers/application_controller.rb
app/controllers/session_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/models/user_auth_token.rb
db/migrate/20240724021732_add_login_method_to_user_auth_tokens.rb
lib/auth/default_current_user_provider.rb
spec/requests/application_controller_spec.rb
spec/requests/omniauth_callbacks_controller_spec.rb
spec/requests/session_controller_spec.rb

Previously in these 2 PRs, we introduced a new site setting `SiteSetting.enforce_second_factor_on_external_auth`.
https://github.com/discourse/discourse/pull/27547
https://github.com/discourse/discourse/pull/27674
When disabled, it should enforce 2FA for local login with username and password and skip the requirement when authenticating with oauth2.
We stored information about the login method in a secure session but it is not reliable. Therefore, information about the login method is moved to the database.

FIX: store information about the login method in the database.

---

app/assets/javascripts/discourse/app/components/footer-nav.gjs

This commit is a minor optimisation to only start showing the footer nav once one of these conditions is valid:
- discourse is in the context of discourse hub
- user can go back
- user can go forward
No tests as it's a lot of stuff related to routing and discourse hub which would be hard to test. Although we could try writing a system spec in the feature for this whole footer-nav behavior.

UX: do not show footer nav if no actions

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/radio-group/radio.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/radio-test.gjs
app/assets/stylesheets/common/form-kit/_control-radio.scss
plugins/styleguide/assets/javascripts/discourse/components/sections/atoms/05-forms.hbs

Usage:
```
<Form as |form|>
<form.Field @name="foo" @title="Foo" as |field|>
<field.RadioGroup as |RadioGroup|>
<RadioGroup.Radio @value="one" as |radio|>
<radio.Title>One title</radio.Title>
<radio.Description>One description</radio.Description>
</RadioGroup.Radio>
</field.RadioGroup>
</form.Field>
</Form>
```

DEV: adds a way to set a title/description to a radio

---

app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs

Changes the location of the plugin outlet added in https://github.com/discourse/discourse/commit/d54e47f37312bdbfaafe2979f2bbfe2b54c4388c

DEV: update the plugin outlet to be available just after name and badge

---

app/assets/javascripts/discourse/ember-cli-build.js

Disabling webpack minimize is a bug we are working to resolve as we
have to consider self-hosters that deploy on low cost hardware
and reenabling this for them drastically increases the build time.
For now, add a  `DISCOURSE_WEBPACK_MINIMIZE` env to allow sites to opt
back in.

DEV: Add `DISCOURSE_WEBPACK_MINIMIZE` to reenable webpack minimize.

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs

We don't show this when editing on desktop,
so no need to show on mobile (also the label
is wrong)
Old
New

UX: Remove bookmark menu title on mobile

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/serializers/current_user_serializer.rb
config/site_settings.yml
db/migrate/20240725042522_remove_experimental_flags_admin_page_site_setting.rb
spec/system/admin_flags_spec.rb

The page was hidden behind a feature flag in this PR https://github.com/discourse/discourse/pull/27756
It is now in a shippable state.

DEV: show admin moderation flags UI

---

app/jobs/onceoff/onceoff.rb
spec/integrity/onceoff_integrity_spec.rb

We are investigating a memory leak in Sidekiq and saw the following line
when comparing heap dumps over time.
`Allocated IMEMO 14775 objects of size 591000/7389528 (in bytes) at:
/var/www/discourse/app/jobs/onceoff/onceoff.rb:36`
That line in question was doing a `.select { |klass| klass < self  }` on
`ObjectSpace.each_object(Class)`. This for some reason is allocating a
whole bunch of `IMEMO` objects which are instruction sequence objects.
Instead of diving deeper into why this might be leaking, we can just
save our time by switching to an implementation that is more efficient
and does not require looping through a ton of objects.

PERF: Avoid using `ObjectSpace.each_object` in  `Jobs::Onceoff.enqueue_all`

---

app/jobs/onceoff/onceoff.rb

In development, classes are lazy loaded so `Jobs::Onceoff.onceoff_job_klasses`
may not have been set. This is not a problem in production cause stuff
is eager loaded.
Follow-up to f4d06f195d583794313943e73b1b31d28151b85c

FIX: Fix `Jobs::Onceoff.enqueue_all` undefined method for nilClass error

---

app/controllers/topics_controller.rb

Performing a bulk action on many topics can exceed the 30 seconds timeout that Unicorn workers have which results in the request failing and the operation getting aborted. To get around this 30 seconds timeout, we can push the operation into a background thread using the rack `hijack` API.
Internal topic: t/133779.

FIX: Perform topics bulk action in a background thread

---

app/assets/javascripts/discourse/ember-cli-build.js
app/assets/javascripts/discourse/package.json
yarn.lock

In an attempt to improve build performance, 9db5eafb mistakenly removed minimization for some of our JS assets, leading to a significant increase in the size of some files.
This commit restores minimization to those files. To avoid regressing on the build time improvements, this commit switches to using the `webpack-terser-plugin`'s "swcMinify" option. On an entry-level 1CPU/1GB-ram/2GB-swap DO droplet, this commit increases build time from ~16 minutes to ~18 minutes.

PERF: Restore minimization of all JS assets

---

Gemfile.lock
lib/js_locale_helper.rb
spec/lib/js_locale_helper_spec.rb

We can get translations with invalid plural keys from Crowdin or from custom overrides. Currently, this will raise an error and the locales won’t be outputted at all.
This PR addresses this issue by using the new `strict: false` option of our `messageformat-wrapper` gem, allowing to generate locales even if there are invalid plural keys present.

FIX: Allow invalid plural keys in MF translations

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/post-test.js
app/assets/stylesheets/common/components/topic-map.scss
config/locales/client.en.yml

If there's enough space, it renders the extra content inline. This is meant for the summary button from the Discourse AI plugin. Summary locales are still in core, so I updated those too.

UX: Allow adding content inline to the topic map

---

app/assets/javascripts/discourse/app/templates/topic.hbs

Without this, the browser may anchor to the bottom topic map when loading posts, causing the post stream to scroll to the bottom.

FIX: Render the bottom topic map only if all posts are loaded

---

config/locales/client.en.yml

If only one badge has not been awarded, the rest of the string doesn’t make sense:
> Due to the large number of unmatched entries, only the first 100 are shown:
As we are going to show only 1 anyways.

FIX: better copy for one entry

---

app/assets/stylesheets/common/base/modal.scss

Regressed in https://github.com/discourse/discourse/pull/28047
Should fix issue reported in https://meta.discourse.org/t/broken-password-confirmation-box-on-registration/318386

FIX: Restore missing modal scss

---

package.json
yarn.lock

This reverts commit 5dca68dc1dc6dc0662cc6a187e59ad11e862daef.
Pending https://github.com/evilmartians/lefthook/issues/783
Meta: https://meta.discourse.org/t/132947/3

Revert "Build(deps-dev): Bump lefthook from 1.7.5 to 1.7.7 (#28068)"

---

app/assets/javascripts/discourse/tests/acceptance/user-tips-test.js
spec/system/user_tips_spec.rb

When we show user tips, we immediately send an AJAX request to mark the tiup as seen. This is done in the background. However, when system tests are run, sometimes that request is not completed before the test ends. This causes the test to be flakey.
One way to fix this is to force the system test run to wait for the AJAX request to complete. However, this is not ideal because it makes the test suite slower on each run.
Instead, this commit removes the flakey assertion and adds an alternative assertion in the frontend tests that ensures the background request is sent when the user tip is shown.

DEV: Fix flakey user tips test

---

app/assets/javascripts/discourse/app/templates/preferences/security.hbs

<s>Remove empty `href` attributes</s> and wrap labels with `span`s
I see the `href` attributes were added to bypass `Interaction added to non-interactive element  no-invalid-interactive`, so we can just add the `span`s

UX: Fix button syntax in preferences

---

app/controllers/admin/site_texts_controller.rb
app/models/translation_override.rb
spec/lib/js_locale_helper_spec.rb
spec/models/translation_override_spec.rb

Currently, when adding translation overrides, values aren’t validated for MF strings. This results in being able to add invalid plural keys or even strings containing invalid syntax.
This PR addresses this issue by compiling the string when saving an override if the key is detected as an MF one.
If there’s an error from the compiler, it’s added to the model errors, which in turn is displayed to the user in the admin UI, helping them to understand what went wrong.
----

FIX: Validate MF strings when adding overrides

---

plugins/chat/spec/services/chat/update_message_spec.rb

The message grace edit window (10 seconds) was too short after freezing time, possibly causing the test to fail occasionally if the record is not updated within 5 seconds.

DEV: fix chat message grace edit period flaky

---

lib/i18n/locale_file_checker.rb
spec/lib/js_locale_helper_spec.rb

This PR fixes the `i18n:check` rake task which has been broken by the `MessageFormat` upgrade.
It also adds a spec to ensure we generate valid MF code for all our available locales.

DEV: Ensure MF locales are checked properly

---

app/assets/javascripts/discourse/ember-cli-build.js

By default, the swc minifier seems to unwrap 'unneeded' IIFE. That means it was undoing the 'bugfix' transformation we have for class fields in Safari 15. Disabling the 'inline' and 'reduce_funcs' options seems to stop this behavior.

FIX: Adjust swc minify options for Safari 15 support

---

app/assets/javascripts/discourse/app/components/navigation-bar.hbs
app/assets/stylesheets/mobile/topic-list.scss

In anticipation of the bigger rework of the navigation, this commit does a first touch-up to the area on mobile by restyling the navigation dropdown to feel lighter

UX: restyle main nav on mobile

---

app/assets/javascripts/admin/addon/components/admin-config-area-card.gjs
app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
app/assets/javascripts/admin/addon/templates/dashboard-new-features.hbs
app/assets/javascripts/admin/addon/templates/whats-new.hbs
app/assets/stylesheets/common/admin/dashboard.scss
app/assets/stylesheets/mobile/dashboard.scss
config/locales/client.en.yml
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/pages/admin_dashboard_new_features.rb

Display new features grouped by month and show additional information about the version.
Desktop
Mobile

UX: group admin new features by month

---

app/jobs/scheduled/check_translation_overrides.rb
app/models/translation_override.rb
lib/i18n/i18n_interpolation_keys_finder.rb
spec/lib/js_locale_helper_spec.rb

The old implementation did not filter out deprecated translations, causing these translations to incorrectly override the new locale in the frontend.
This commit fills in the forgotten where clause, filtering only the up-to-date part.
Related meta topic: https://meta.discourse.org/t/outdated-translation-replacement-causing-missing-translation/314352

FIX: Ensure JsLocaleHelper to not output deprecated translations

---

config/locales/client.en.yml

We have some MF strings that are outputting HTML tags (typically links) and their attributes are using single quotes. The problem is that with the current implementation of MessageFormat, single quotes act as an escaping mechanism for special characters like `{`. This then prevents from interpolating some variables in the strings.
This PR addresses that issue by using double quotes instead, restoring the expected behavior.

FIX: Don't escape MF variables in HTML links

---

script/db_timestamps_mover.rb

https://github.com/discourse/discourse-topic-voting/pull/196
Some tables in that plugin are read-only, so the script fails when trying to update rows in those tables. Add them to the ignore list.

FIX: db_timestamps_mover errors from discourse-voting plugin

---

app/assets/javascripts/discourse/app/components/site-header.js
app/assets/javascripts/discourse/app/routes/topic-from-params.js
app/assets/javascripts/discourse/app/services/header.js

In this case, there is no 'nearPost' param in the URL. Instead, the server preloads a post-stream with whichever page of posts is requested. We can check for that situation using `postStream.firstPostPresent`.
Also updates the widget-header version to fetch a value from the service on initial render, instead of relying on the observer triggering.
Followup to bdec564d1417c51ef6958784fdd6375fd05da4fc

UX: Avoid header topic-info flicker when using `?page=` params

---

app/controllers/admin/email_templates_controller.rb
lib/email_templates_finder.rb
lib/tasks/list_email_templates_strings.rake
spec/requests/admin/email_templates_controller_spec.rb

We have a dedicated admin page (`/admin/customize/email_templates`) that lets admins customize all emails that Discourse sends to users. The way this page works is that it lists all translations strings that are used for emails, and the list of translation strings is currently hardcoded and hasn't been updated in years. We've had a number of new emails that Discourse sends, so we should add those templates to the list to let admins easily customize those templates.
Meta topic: https://meta.discourse.org/t/3-2-x-still-ignores-some-custom-email-templates/308203.

FIX: Add new/missing email templates to the email templates editor

---

lib/discourse_ip_info.rb
spec/lib/discourse_ip_info_spec.rb

Since switching to Maxmind permalinks to download the databases in
7079698cdfb6f0cd73cdfd305b15350634fcd56a, we have received multiple
reports about rebuilds failing as `maxminddb:refresh` runs during
the rebuilds and failing to download the databases cases the rebuilds to
fail.
Downloading Maxmind databases should not sit in the critical rebuild
path but since we are close to the Discourse 3.3 release, we have opted
to just rescue all errors encountered when downloading the databases.
In the near future after the Discourse 3.3 release, we will be looking
at moving the downloading of maxmind databases out of the rebuild path.

FIX: Rescue and warn when error is encountered in `DiscourseIpInfo.mmdb_download`

---

app/assets/javascripts/discourse/app/lib/sidebar/common/community-section/section.js
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js

`addCommunitySectionLink` API function accepts secondary argument to determine if the link should be added to the primary or secondary (more) section. There was a bug and all links were always mounted in the secondary section.

FIX: addCommunitySectionLink secondary argument

---

app/assets/javascripts/admin/addon/routes/admin-config-about.js
app/controllers/admin/config/site_settings_controller.rb
app/controllers/admin/site_settings_controller.rb
config/routes.rb
spec/requests/admin/config/site_settings_controller_spec.rb
spec/requests/admin/site_settings_controller_spec.rb

Followup 4aea12fdcb21216a528451c0f8803e02dff24998
In certain config areas (like About) we want to be able
to fetch specific site settings by name. In this case,
sometimes we need to be able to fetch hidden settings,
in cases where a config area is still experimental.
Splitting out a different endpoint for this purpose
allows us to be stricter with what we return for config
areas without affecting the main site settings UI, revealing
hidden settings before they are ready.

DEV: Move config area site setting fetch into new controller

---

lib/cache.rb
spec/lib/cache_spec.rb

When using `Discourse.cache.fetch` with an expiry, there's a potential for a race condition due to how we read the data from redis.
The code used to be
```ruby
raw = redis.get(key) if !force
entry = read_entry(key) if raw
return entry if raw && !(entry == :__corrupt_cache__)
```
with `read_entry` defined as follow
```ruby
def read_entry(key)
if data = redis.get(key)
Marshal.load(data)
end
rescue => e
:__corrupt_cache__
end
```
If the value at "key" expired in redis between `raw = redis.get` and `entry = read_entry`, the `entry` variable would be `nil` despite `raw` having a value.
We would then proceed to return `entry` (which is `nil`) thinking it had a value, when it didn't.
The first `redis.get` can be skipped altogether and we can rely only on `read_entry` to read the data from redis. …

FIX: race condition in Discourse.cache.fetch

---

plugins/poll/assets/javascripts/discourse/components/poll-voters-ranked-choice.gjs
plugins/poll/assets/javascripts/discourse/components/poll-voters.gjs

Glimmer migration may have dropped support for clickable (User Card invoking) and titled avatars in Poll results.  This PR restores this functionality.
@davidtaylorhq

FIX: Poll: Clickable, hoverable avatars

---

app/controllers/topics_controller.rb

Similar to https://github.com/discourse/discourse/pull/28061, merging topics with many posts can exceed the 30 seconds timeout that Unicorn workers are limited to, so we should move the operation into a background thread to get around this limit.
Internal topic: t/133710.

FIX: Perform topics merge in a background thread

---

app/serializers/post_action_type_serializer.rb
app/serializers/topic_flag_type_serializer.rb
spec/serializers/post_action_type_serializer_spec.rb

Currently, descriptions for flag types aren’t interpolated, returning `%{base_path}` in their string, for example. This breaks the navigation on the sites.
The behavior changed probably because of an upgrade of Ruby, as two hashes were passed to `I18n.t` (`vars` and `default`) without using the splat operator.

FIX: Return properly interpolated translations for flag types

---

lib/tasks/assets.rake
lib/tasks/maxminddb.rake

We have been seeing `ZLib::BufError` when running the `assets:precompile` rake
task.
```
I, [2024-07-30T05:19:58.807019 #1059]  INFO -- : Writing /var/www/discourse/public/assets/scripts/discourse-test-listen-boot-9b14a0fc65c689577e6a428dcfd680205516fe211700a71c7adb5cbcf4df2cc5.js
rake aborted!
Zlib::BufError: buffer error (Zlib::BufError)
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/sprockets-3.7.3/lib/sprockets/cache/file_store.rb:100:in `<<'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/sprockets-3.7.3/lib/sprockets/cache/file_store.rb:100:in `set'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/sprockets-3.7.3/lib/sprockets/cache.rb:212:in `set'
```
The hypothesis here is that some thread unsafe issue is causing the
problem since we download the Maxmind databases in a thread …

FIX: Move downloading of Maxmind databases to after `assets:precompile`

---

app/models/reviewable_queued_post.rb
lib/post_creator.rb
spec/lib/post_creator_spec.rb

When `SiteSetting.review_every_post` is true and the category `require_topic_approval` system creates two reviewable items.
1. Firstly, because the category needs approval, the `ReviewableQueuePost` record is created - at this stage, no `Topic` is created.
2. Admin is approving the `Review`. The `Topic` and first `Post` are created.
3. Because `review_every_post` is true `queue_for_review_if_possible` callback is evaluated and `ReviewablePost` is created.
4. Then `ReviewableQueuePost` is linked to the newly generated topic and post.
At the beginning, we were thinking about hooking to those guards:
```ruby
def self.queue_for_review_if_possible(post, created_or_edited_by)
return unless SiteSetting.review_every_post
return if post.post_type != Post.types[:regular] || …
```

FIX: double reviewable items bug

---

app/controllers/topics_controller.rb
app/models/topic.rb
spec/models/topic_spec.rb
spec/requests/topics_controller_spec.rb

When creating a shared draft, we're recording topic view stats on the draft and then pass those on when the draft is published, conflating the actual view count.
Don't register topic views if the topic is a shared draft.

FIX: Don't count draft views towards topic view stats

---

app/assets/javascripts/discourse/app/components/composer-container.hbs

Use “show preview” instead of “preview” as the `aria-label` for toggling the preview on, and add the `title` attribute with “hide preview” for toggling the preview off.

UX: Hide/show preview button title attribute fix

---

spec/rails_helper.rb

Sometimes the backtrace is quite big for failing specs, this env var
(RSPEC_EXCLUDE_NOISE_IN_BACKTRACE) can be set to
1 to remove backtrace from anything but spec or application code in
rspec. This makes it easier to see where the actual failure is
coming from, most of the time all the gem paths are noise.

DEV: Add RSPEC_EXCLUDE_NOISE_IN_BACKTRACE for rspec

---

app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
config/locales/client.en.yml
spec/system/admin_badges_spec.rb

[A previous commit](https://github.com/discourse/discourse/commit/2ca06ba2360c200b2be8e0718fcc04c64ca14935) mistakenly assumed system badges couldn't be disabled.

FIX: system badges can be disabled

---

app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
config/locales/client.en.yml
spec/system/admin_badges_spec.rb

A previous commit mistakenly assumed system badges couldn't be disabled.

FIX: system badges can be disabled (#28169)

---

app/assets/javascripts/admin/addon/mixins/period-computation.js
app/assets/javascripts/admin/addon/mixins/setting-component.js
app/assets/javascripts/admin/addon/mixins/setting-object.js

Ember's legacy mixin system does not support native-class syntax, so we have to use the non-decorator syntaxes for `action()` and `computed()`.
Eventually, we will need to refactor things to remove these mixins... but today is not that day.

DEV: Remove object-property-decorators from admin mixins

---

lib/pretty_text.rb
spec/lib/pretty_text_spec.rb

Skip trying to find a thumbnail if the video src cannot be found.
Bug report: https://meta.discourse.org/t/317423

FIX: Video thumbnails for missing videos

---

app/assets/javascripts/admin/addon/controllers/admin-badges/show.js
app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/image.gjs
app/serializers/admin_badge_serializer.rb
spec/requests/api/schemas/json/badge_create_response.json
spec/requests/api/schemas/json/badge_list_response.json
spec/requests/api/schemas/json/badge_update_response.json
spec/system/admin_badges_spec.rb
spec/system/page_objects/admin_badges.rb
spec/system/page_objects/components/form_kit.rb

In the formkit conversion in 2ca06ba2360c200b2be8e0718fcc04c64ca14935
we missed setting a type for the UppyImageUploader for badges. Also,
we were not passing down the `image_url` as form data, so when we used
`data.image` for that field the badge was not updating in the UI after
page loads and the image URL was not loading for preview.

FIX: Badge image uploader

---

app/assets/javascripts/discourse/app/models/user.js

Note this had no behavior impact, as the computed property was correct.

DEV: typo in variable name

---

app/assets/javascripts/discourse/app/models/user.js

[Following a refactor](https://github.com/discourse/discourse/commit/061e79297fb986a2c2d08558416126992d3e1e39#diff-bd99ef6b155af0dab90541be2ed856f3521f78adef81e378f528d1c9e74615fc) we forgot to return the value.

FIX: correct return isForever value

---

app/assets/javascripts/discourse/app/controllers/full-page-search.js

DEV: Resolve `observes` deprecation in full-page-search

---

app/assets/javascripts/theme-transpiler/build.js
lib/discourse_js_processor.rb
lib/tasks/assets.rake
spec/tasks/assets_precompile_spec.rb

We were writing theme-transpiler JS files to the filesystem on a per-process basis, and then immediately reading them back in. Plus, there was no cleanup mechanism, so the tmp directory would grow indefinitely.
This commit refactors things so that the `build.js` script outputs the theme-transpiler source to stdout. That way, we can read it directly into the process, and then into mini-racer, without needing to go via the filesystem. No cleanup required!
In production, the theme-transpiler is still cached in a file during `assets:precompile`

DEV: Stop storing theme-transpiler on filesystem in development

---

plugins/poll/assets/javascripts/discourse/components/poll-option-ranked-choice-dropdown.gjs
plugins/poll/assets/javascripts/discourse/components/poll-options.gjs
plugins/poll/assets/javascripts/discourse/components/poll-results-standard.gjs
plugins/poll/assets/javascripts/discourse/components/poll.gjs
plugins/poll/assets/javascripts/discourse/widgets/discourse-poll.js
plugins/poll/lib/ranked_choice.rb
plugins/poll/test/javascripts/component/poll-test.js

Fixes issue with polls not being fully updated by remote vote contributions in (semi-) real-time.
This was down to too great a focus on tracking local state and not accommodating a more data down approach with responsive getters. 
This is now implemented.
I've tried hard to minimise the changes whilst making sure the paradigm is properly followed through.

FIX: update voter information upon remote change

---

app/assets/javascripts/discourse/app/models/user.js
app/assets/javascripts/discourse/app/services/notifications.js

To achieve this, a new notifications service is set up with an `isInDoNotDisturb` tracked property. While a user is in do-not-disturb mode, it runs a regular timer until do-not-disturb is over.

FIX: Update do-not-disturb icon in real-time on glimmer header

---

app/assets/javascripts/discourse/app/lib/desktop-notifications.js
app/assets/javascripts/discourse/app/services/desktop-notifications.js
app/jobs/regular/send_push_notification.rb
app/services/post_alerter.rb
app/services/push_notification_pusher.rb
plugins/chat/app/jobs/regular/chat/notify_watching.rb
spec/jobs/send_push_notification_spec.rb

This change is mainly a refactor of the desktop notifications service to improve readability and have standardised values for tracking state for current user in regards to the Notification API and Push API.
Also improves readability when handling push notification jobs, especially in scenarios where the `push_notification_time_window_mins` site setting is set to `0`, which will allow sending push notifications instantly.

DEV: refactor live notifications setting in user preferences

---

plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js

This commits adds a `redirect` function to the `chat-drawer-router` which allows us to redirect the drawer to a different component based on custom logic defined in the `redirect` function.
Usage: 
```javascript
{
chat: {
name: ChatDrawerRoutesChannels,
redirect: (context) => {
if (context.currentUser) {
return "/something";
}
}
}
}
```

FIX: make the check better for drawer router

---

app/models/problem_check.rb
app/services/problem_check/inline_problem_check.rb
spec/services/problem_check_spec.rb

We support a low-level construct called "inline checks", which you can use to register a problem ad-hoc from within application code.
Problems registered by inline checks never show up in the admin dashboard, this is because when loading the dashboard, we run all realtime checks and look for problems. Because of an oversight, we considered inline checks to be "realtime", causing them to be run and clear their problem status.
Don't consider inline checks to be realtime, to prevent them from running when loading the admin dashboard.

FIX: Don't clear inline problems when loading admin dashboard

---

app/assets/javascripts/discourse-i18n/src/index.js
app/assets/javascripts/discourse/app/components/topic-map/topic-views-chart.gjs
app/assets/javascripts/discourse/app/components/topic-map/topic-views.gjs
app/assets/javascripts/discourse/tests/unit/lib/i18n-test.js

We're using the default browser locale instead of Discourse's locale on the new topic map views when formatting the date.
This PR introduces a simple conversion from our standard locale format to a BCP 47 language tag and passes it to `toLocaleDateString` – similar to [how we did it](https://github.com/discourse/discourse-calendar/blob/908ad614bc412f831f929ca726a4bda0b9ccaab6/assets/javascripts/discourse/initializers/discourse-calendar.js#L133) when passing a locale to `discourse-calendar`'s `FullCalendar` instance.

UX: respect current locale on topic map views date format

---

plugins/automation/lib/discourse_automation/stalled_topic_finder.rb
plugins/automation/spec/lib/discourse_automation/stalled_topic_finder_spec.rb

Prior to this fix the query in stalled_topic_finder would assume that tags/categories would be nil or an array of ids. However it can be an empty array, in this case the query will not return results.

FIX: ensures tags/categories are present

---

app/controllers/test_requests_controller.rb
config/initializers/200-first_middlewares.rb
config/routes.rb
lib/freedom_patches/net_http.rb
lib/middleware/processing_request.rb
spec/integrity/middleware_order_spec.rb
spec/requests/net_http_timeout_spec.rb

This commit patches `Net::HTTP` to reduce the default timeouts of 60
seconds when we are processing a request. There are certain routes in
Discourse which makes external requests and if the proper timeouts are
not set, we risk having the Unicorn master process force restarting the
Unicorn workers once the `30` seconds timeout is reached. This can
potentially become a vector for DoS attacks and this commit is aimed at
reducing the risk here.

FIX: Set sane default for `Net::HTTP` when processing a request

---

lib/backup_restore.rb

ActiveRecord::Base.connection_pool.db_config.configuration_hash has the username in `user`, not `username`.

FIX: backup_restore.rb wants db user from user, not username

---

app/assets/javascripts/admin/addon/components/admin-config-areas/flags.gjs
app/assets/javascripts/admin/addon/components/admin-config-header.gjs
app/models/flag.rb
config/site_settings.yml
lib/guardian/flag_guardian.rb
spec/lib/guardian/flag_guardian_spec.rb
spec/system/admin_flags_spec.rb
spec/system/page_objects/pages/admin_flags.rb

Admin can create up to 50 custom flags. It is limited for performance reasons.
When the limit is reached "Add button" is disabled and the backend is protected by the guardian.

FIX: limit the number of custom flags to 50

---

app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs

A recent change in FormKit has changed the syntax of this specific component. It's also better to use `<CheckboxGroup />` for this use case too.
Im mixed on writing tests for labels, it's a lot of tests to write for a rather low value.
This commit also slightly tweaks the width of the icon picker, from medium to small.

FIX: use CheckboxGroup for admin badges form

---

app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs

During our refactoring of admin badges we decided to link to:
`adminSiteText.edit locale=locale`
Instead of:
`adminSiteText q=key`
After feedback from the community we are reverting this change.

UX: link edit text to search in badges form

---

app/models/post_action_type.rb
spec/models/post_action_type_spec.rb

Following a recent refactor, some methods from `FlagSettings` have been renamed (`custom_types` -> `additional_message_types`). The `PostActionType` model was using `custom_types` but when the renaming was done, it was renamed to `with_additional_message` instead of `additional_message_types`, which under the right circumstances will raise an error.

FIX: Return additional message types properly

---

app/assets/stylesheets/common/components/user-stream-item.scss

UX: break long words to prevent overflow in activity stream

---

app/assets/stylesheets/common/base/modal.scss

Before (extra margin before "our community guidelines"): 
After:

UX: remove extra margin from flag description links

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/lib/search.js
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md

- Added `addLogSearchLinkClickedCallbacks` which allows plugins/TCs to register a callback when a search link is clicked and before a search log is created

DEV: Add `addLogSearchLinkClickedCallbacks` to plugin API

---

app/assets/stylesheets/common/base/user.scss
app/assets/stylesheets/desktop/user.scss
app/assets/stylesheets/mobile/user.scss
plugins/chat/assets/stylesheets/common/core-extensions.scss

Fixes this overflow issue by allowing buttons to wrap...
after:
This also: 
* simplifies styles by moving the container to flex in /common and removing margins for gap
* removes some now-redundant select-kit classes (the select-kit header has the .btn class now) 
* removes some desktop/mobile redundancies 
* removes some styles due to plugin outlet changes
* adds `:empty` handling for a state where the chat button isn't rendered, but its container is

UX: fix user profile button wrap, clean up styles

---

app/assets/stylesheets/mobile/components/user-card.scss

This fixes an issue where long usernames would wrap under the avatar for mobile user cards.
Before:
After:
– Awesomerob

UX: fix issue with long usernames wrapping in mobile user cards

---

app/jobs/base.rb

This information is helpful in debugging memory spikes when Sidekiq
processes jobs.
We have 0 test coverage here and I'm just adding two simple and new fields. Shall not invest my time into figuring how to test this.
To test this locally:
1. Run `tail -f log/sidekiq.log`
1. Run `UNICORN_SIDEKIQS=1 DISCOURSE_LOG_SIDEKIQ=1 bin/rails s`
1. Check that `live_slots_start` and `live_slots_finish` fields are present.

FEATURE: Add `live_slots_(start|finish)` for Sidekiq perf logging

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/stylesheets/common/base/about.scss
app/models/about.rb
app/serializers/about_serializer.rb
config/locales/client.en.yml
lib/discourse.rb
lib/svg_sprite.rb
spec/system/about_page_spec.rb
spec/system/page_objects/components/about_page_site_activity.rb
spec/system/page_objects/components/about_page_site_activity_item.rb
spec/system/page_objects/pages/about.rb

This PR continues on work laid out by https://github.com/discourse/discourse/pull/27996 to redesign the /about page. In this PR, we add the site age and a section on the right hand side to show site activities/statistics.
Screenshot:

DEV: Add site age and site activities section to the redesigned about page

---

app/assets/javascripts/discourse/app/lib/class-prepend.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/discourse/tests/unit/lib/class-prepend-test.js
app/assets/javascripts/discourse/tests/unit/lib/plugin-api-test.js

This resolves issues when a mix of callback-based modifications and Ember-reopen-based modifications are used on the same target. In summary:
- Fixes `pluginId` exception logic for callback-based modifications
- Moves `pluginId` storage to a WeakMap so it doesn't pollute the target's descriptors
- When applying a legacy modifyClass, we will temporarily rollback any modern callback-based modifications. This means all of Ember's reopen calls apply to un-prepended classes, and then we add our modern prepends on top.
- Calls `.proto()` on CoreObject descendants before prepending, to ensure that pending Ember mixins have been applied

DEV: Fixes for `modifyClass`

---

app/controllers/list_controller.rb
spec/requests/list_controller_spec.rb

Currently, when a badly named category slug is provided, it can lead to an infinite redirect.
This patch addresses the issue by properly unescaping `request.fullpath` so the path is successfully rewritten and the redirect happens as expected.

FIX: Unescape URI properly when redirecting to a category

---

app/assets/javascripts/discourse-common/addon/deprecation-workflow.js
app/assets/javascripts/discourse-common/addon/lib/deprecated.js
app/assets/javascripts/discourse/app/app.js
app/assets/javascripts/discourse/app/deprecation-workflow.js
app/assets/javascripts/discourse/app/initializers/deprecation-error-mode.js
app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
app/assets/javascripts/discourse/package.json
app/assets/javascripts/discourse/tests/helpers/deprecation-counter.js
app/assets/javascripts/discourse/tests/helpers/raise-on-deprecation.js
app/assets/javascripts/ember-production-deprecations/vendor/ember-production-deprecations/deprecate-shim.js
lib/pretty_text.rb
yarn.lock

From dependabot PR:
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/ember-cli/ember-cli-deprecation-workflow/releases">ember-cli-deprecation-workflow's releases</a>.</em></p>
<blockquote>
<h2>v3.0.1-ember-cli-deprecation-workflow</h2>
<h2>Release (2024-07-11)</h2>
<p>ember-cli-deprecation-workflow 3.0.1 (patch)</p>
<h4>:house: Internal</h4>
<ul>
<li><code>ember-cli-deprecation-workflow</code>
<ul>
<li><a href="https://redirect.github.com/ember-cli/ember-cli-deprecation-workflow/pull/192">#192</a> fix repository link in package.json (<a href="https://github.com/mansona"><code>@​mansona</code></a>)</li>
<li><a href="https://redirect.github.com/ember-cli/ember-cli-deprecation-workflow/pull/191">#191</a> update release plan workflow (<a …

DEV: Update ember-cli-deprecation-workflow from 2.2.0 to 3.0.1

---

app/assets/javascripts/admin/addon/components/admin-flag-item.gjs
spec/system/page_objects/pages/admin_flags.rb

Those are the steps to move the flag:
1. open menu;
2. click move up - `saving` CSS class is added;
3. request to backend;
4. `saving` CSS class is removed.
To check if the action was finished we are using this method:
```ruby
def move_up(key)
open_flag_menu(key)
find(".admin-flag-item__move-up").click
has_saved_flag?(key)
self
end
def has_saved_flag?(key)
has_css?(".admin-flag-item.#{key}.saving")
has_no_css?(".admin-flag-item.#{key}.saving")
end
```
However, sometimes specs were failing with `expected to find CSS ".admin-flag-item.spam.saving" but there were no matches`
I think that the problem is with those 2 lines:
```ruby
find(".admin-flag-item__move-up").click
has_closed_flag_menu?
```
If the save action is very fast, then the `saving` class is removed before the first check. …

FIX: flaky flags specs when moving up or down

---

Gemfile.lock
config/initializers/100-sidekiq.rb
lib/mini_scheduler_long_running_job_logger.rb
spec/lib/mini_scheduler_long_running_job_logger_spec.rb

This commit adds a `MiniSchedulerLongRunningJobLogger` class which will
poll every 60 seconds for mini_scheduler jobs which are stuck. When it
detects that a job is stuck, it will log a warning message with the
current backtrace of the thread that is executing the job.
Note that for scheduled jobs which are executed at a frequency of less
than 30 minutes, we will log when the job has been executing for 30
minutes.
For scheduled jobs executed at a frequency of less than 2 hours, we will
log when the job has been executing for a duration greater than its
specified frequency.
For scheduled jobs executed at a frequency greater than 2 hours, we will
log as long as the job has been executing for more than 2 hours.

DEV: Log a warning message when a MiniScheduler scheduled job is stuck

---

app/controllers/list_controller.rb
spec/requests/list_controller_spec.rb

Currently, in the list controller, when encountering an unsafe redirect error, a 404 is rendered. The problem is that it’s done in a way that it also logs a fatal error (because a `Discourse::NotFound` exception was raised inside a `rescue_from` block).
This PR addresses that issue by simply rendering a 404 without raising any error.

FIX: Don’t log an error when rendering a 404

---

spec/system/page_objects/components/tooltips.rb
spec/system/user_tips_spec.rb

Usage:
```ruby
tooltip = PageObjects::Components::Tooltips.new(identifier)
expect(tooltip).to be_present(text: "Welcome")
expect(tooltip).to be_not_present(text: "Welcome")
tooltip.find(".my-button").click
```

DEV: adds a tooltip system spec component

---

app/assets/javascripts/admin/addon/components/modal/reseed.hbs
app/assets/javascripts/admin/addon/templates/site-settings.hbs
app/assets/javascripts/discourse/app/components/categories-boxes-with-topics.hbs
app/assets/javascripts/discourse/app/components/categories-boxes.hbs
app/assets/javascripts/discourse/app/components/category-name-fields.hbs
app/assets/javascripts/discourse/app/components/category-title-link.hbs
app/assets/javascripts/discourse/app/components/edit-category-general.js
app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/lib/sidebar/user/categories-section/category-section-link.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/app/routes/build-category-route.js
app/assets/javascripts/discourse/app/routes/tag-show.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/image-previews/logo-small.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/-homepage-preview.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
app/assets/javascripts/discourse/tests/acceptance/transformers/category-description-text-test.js
app/assets/javascripts/discourse/tests/acceptance/transformers/category-display-name-test.js
app/assets/javascripts/discourse/tests/integration/helpers/category-badge-test.js
app/assets/javascripts/select-kit/addon/components/category-drop.js
app/assets/javascripts/select-kit/addon/components/category-row.gjs

This commit adds two new getters to the category model:
- `displayName`
- `descriptionText`
These getters are used instead of `name` and `description_text` where appropriate.
On top of this two transformers have been added to allow plugins to alter these getters:
```javascript
api.registerValueTransformer(
"category-display-name",
({ value, context }) =>
value + "-" + context.category.id + "-transformed"
);
```
```javascript
api.registerValueTransformer(
"category-description-text",
({ value, context }) =>
value + "-" + context.category.id + "-transformed"
);
```

DEV: allows to alter category name/description

---

plugins/discourse-narrative-bot/plugin.rb
plugins/discourse-narrative-bot/spec/system/user_spec.rb
plugins/discourse-narrative-bot/spec/user_spec.rb

Should fix https://meta.discourse.org/t/skip-tips-option-in-user-tip-should-not-delete-welcome-message/303420

UX: Do not delete narrative bot PM when skipping user tips

---

app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/modal/modal-overrides.scss
config/locales/client.en.yml

Modal headings are enormous at the moment (on desktop), this makes them smaller and reduces the line height slightly. I also shortened the flag modal title specifically because it can communicate a similar sentiment on one line... 
before: 
after:

UX: smaller modal headings, shorter flag mdoal title

---

app/assets/javascripts/admin/addon/templates/site-settings.hbs

These were accidentally included in the refactoring of c197daa04c3114184cbd3ec2f1cfade1b5701793

FIX: Site setting category titles

---

app/assets/javascripts/discourse/app/controllers/preferences/interface.js
app/assets/javascripts/discourse/tests/acceptance/assets-version-test.js
app/assets/javascripts/discourse/tests/acceptance/tags-test.js
app/assets/javascripts/discourse/tests/acceptance/topic-discovery-test.js
app/assets/javascripts/discourse/tests/acceptance/topic-discovery-tracked-test.js
app/assets/javascripts/discourse/tests/fixtures/site-fixtures.js
app/assets/javascripts/discourse/tests/helpers/site.js
app/models/user_option.rb
config/locales/server.en.yml
config/site_settings.yml
spec/system/homepage_spec.rb
spec/system/page_objects/components/select_kit.rb
spec/system/user_page/user_preferences_interface_spec.rb

This change only applies to instances that have not modified the `top_menu` site setting.

FEATURE: "Hot" replacing "Top" as default in the top menu

---

plugins/chat/assets/javascripts/discourse/components/chat-drawer.hbs
plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js

This outlet is rendered before the content of the drawer. The `currentRouteName` is accessible in `outletArgs`.
Example:
```gjs
export default class Test extends Component {
<template>
{{#if (eq @outletArgs.currentRouteName "chat.browse")}}
the browse page
{{/if}}
</template>
}
```

DEV: adds chat-drawer-before-content plugin outlet

---

plugins/chat/assets/javascripts/discourse/components/channels-list-direct.gjs

It should be below channels, not above.

DEV: correctly position below-direct-chat-channels

---

app/assets/javascripts/admin/addon/components/admin-flag-item.gjs
spec/system/page_objects/pages/admin_flags.rb

Very similar to move up/down flag problem fixed here -  https://github.com/discourse/discourse/pull/28272
Those are the steps to toggle the flag:
1. click toggle - `saving` CSS class is added;
2. request to backend;
3. `saving` CSS class is removed.
And check if the flag was toggle was:
```ruby
def has_saved_flag?(key)
has_css?(".admin-flag-item.#{key}.saving")
has_no_css?(".admin-flag-item.#{key}.saving")
end
```
If the save action is very fast, then the saving class is removed before the first check.
Therefore I decided to invert it, and once action is finished add `saved` CSS class.
Then we can have a quick positive check:
```ruby
def has_saved_flag?(key)
has_css?(".admin-flag-item.#{key}.saved")
end
```

DEV: flaky toggle flag spec

---

app/assets/javascripts/discourse/app/components/modal/keyboard-shortcuts-help.hbs
app/assets/stylesheets/common/components/keyboard_shortcuts.scss

No visual changes here... this just switches the headings to be sequential. The modal heading is an H1 so "jump to" "navigation" etc should be H2.

A11Y: do not skip heading levels in keyboard shortcut modal

---

app/assets/javascripts/discourse/app/components/global-notice.js
spec/system/ember_deprecation_spec.rb

In development, Ember raises an error when previously-used values are updated during a render. This is to avoid 'backtracking', where parts of templates have to be re-rendered multiple times. In general, this kind of pattern should be avoided, and Ember's warning helps us do that.
However, for the deprecation warning banner, it is quite reasonable for some rendering to trigger a deprecation, and thereby require the global-notice to be re-rendered. We can use our `DeferredTrackedSet` to achieve that. Its `.add` method will delay adding an item to the Set until after the current render has completed.

DEV: Ensure deprecation warning banner works in development builds

---

plugins/chat/assets/javascripts/discourse/controllers/chat.js

This deleted `if` statement was added to avoid a double CTA when no DMs were present and public channels disabled. The check was wrong, and ended up causing no channel list to be rendered :(
OLD:
NEW:

UX: Add sidebar DM list back when public channels are disabled

---

app/assets/javascripts/discourse-common/addon/resolver.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs

This message indicates broken behavior, so it should be an error rather than a warning.
An early-return is added, so that we don't even attempt to make the modification. This will make the behavior consistent, and easier to understand.
Also updates the normalization logic to use the resolver's own logic. This will handle all sorts of normalization in addition to our deprecations.

DEV: Promote modifyClass warning to error

---

app/assets/javascripts/discourse/app/components/latest-topic-list-item.hbs

This is for the avatars in the latest/top topic list on the /categories page:
This ensures the link has a properly accessible label, screenreaders will read "username's profile, latest poster, link"

A11Y: add aria-label to avatar link on categories page

---

app/assets/javascripts/discourse/app/lib/sidebar/common/community-section/everything-section-link.js
app/assets/javascripts/discourse/tests/fixtures/site-fixtures.js
app/assets/javascripts/discourse/tests/fixtures/site-settings.js
app/assets/javascripts/discourse/tests/helpers/site.js

Hot, Unseen, and My Posts (posted) are filters of the "all topics" feed so should highlight the sidebar link similar to new/unread/latest
before:
after:

UX: set "topics" link in sidebar as active for hot, unseen, and my posts filters

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/code.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/composer.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/textarea.gjs

e.g.
```
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://deprecations.emberjs.com/v1.x/#toc_binding-style-attributes. Style affected: \"height: 60px\"
```

DEV: Fix unsafe binding warnings

---

app/assets/javascripts/discourse/app/components/about-page-user.gjs
app/assets/javascripts/discourse/app/components/about-page-users.gjs
app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/javascripts/discourse/app/components/legacy-about-page-users.gjs
app/assets/javascripts/discourse/app/templates/about.hbs
app/assets/stylesheets/common/base/about.scss
config/locales/client.en.yml
spec/system/about_page_spec.rb
spec/system/page_objects/components/about_page_users_list.rb
spec/system/page_objects/pages/about.rb

This PR continues on work laid out by https://github.com/discourse/discourse/pull/27996 to redesign the /about page. In this PR, we add sections for showing the site admins and moderators. Screenshot:
The lists of admins and moderators display the 10 most recently seen admins/moderators, with a button to display the rest of admins or moderators. Admins or moderators that have not logged in to the site in the last year will not be shown. Clicking on an admin's or moderator's name/avatar will show their user card.

DEV: Add admins and moderators sections to the redesigned /about page

---

plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/spec/triggers/topic_tags_changed_spec.rb

Before, it was sending the old tags and the current tags in the topic. 
Now, it sends the removed and added tags in the topic.

FEATURE: Change tags sent in topic_tags_changed trigger in automation plugin

---

plugins/poll/assets/stylesheets/common/poll.scss

the background color here would noticeably clash with post highlights 
before:
after:

UX: remove poll button bg color to avoid highlight issue

---

plugins/poll/assets/javascripts/discourse/components/poll-options.gjs

This is a follow-up to: https://github.com/discourse/discourse/pull/27204
Before the refactor, we needed tabindex for keyboard nav because the poll choices were list items. Now that the list items contain buttons, they get a tab order automatically, making tabindex cause a redundant selection.

A11Y: remove redundant tabindex=0 from polls

---

app/models/stat.rb
lib/statistics.rb
plugins/chat/spec/lib/statistics_spec.rb
spec/lib/discourse_hub_spec.rb
spec/lib/plugin/instance_spec.rb
spec/lib/statistics_spec.rb
spec/requests/site_controller_spec.rb

Adds a new statistics (hidden from the UI, but available via the API) that tracks daily participating users.
A user is considered as "participating" if they have
- Reacted to a post
- Replied to a topic
- Created a new topic
- Created a new PM
- Sent a chat message
- Reacted to a chat message
Internal ref - t/131013

FEATURE: participating users statistics

---

app/controllers/admin/config/flags_controller.rb
app/jobs/regular/export_user_archive.rb
app/models/flag.rb
app/models/post.rb
app/models/post_action.rb
app/models/post_action_type.rb
app/models/reviewable_flagged_post.rb
app/models/reviewable_score.rb
app/models/translation_override.rb
app/models/user.rb
app/serializers/flag_serializer.rb
app/serializers/post_action_type_serializer.rb
app/serializers/post_serializer.rb
app/serializers/site_serializer.rb
config/initializers/004-message_bus.rb
db/fixtures/003_flags.rb
db/fixtures/003_post_action_types.rb
lib/guardian/post_guardian.rb
lib/post_action_creator.rb
lib/post_action_destroyer.rb
lib/post_action_type_view.rb
lib/post_destroyer.rb
lib/topic_view.rb
spec/lib/post_action_type_view_spec.rb
spec/models/flag_spec.rb
spec/models/post_action_type_spec.rb
spec/multisite/flags_spec.rb
spec/requests/api/schemas/json/site_response.json
spec/serializers/flag_serializer_spec.rb

Before, all flags were static. Therefore, they were stored in class variables and serialized by SiteSerializer. Recently, we added an option for admins to add their own flags or disable existing flags. Therefore, the class variable had to be dropped because it was unsafe for a multisite environment. However, it started causing performance problems. 
When a new Flag system is used, instead of using PostActionType, we can serialize Flags and use fragment cache for performance reasons. 
At the same time, we are still supporting deprecated `replace_flags` API call. When it is used, we fall back to the old solution and the admin cannot add custom flags. In a couple of months, we will be able to drop that API function and clean that code properly. However, because it may still be used, redis …

FIX: serialize Flags instead of PostActionType

---

db/fixtures/003_post_action_types.rb

Hardcode IDs because seed in multisite environment is run concurrently which can cause performance problems.
Same as Flags https://github.com/discourse/discourse/blob/main/db/fixtures/003_flags.rb
This seed will be dropped in the foreseeable future so no need to extract those IDs.

FIX: not hit Redis cache in seeds

---

app/models/flag.rb
db/fixtures/003_flags.rb

When flags are seeded, we don't need to reset the cache for each record.
We should instead create all flags and reset the cache at the very end.

PERF: skip reset flag callbacks on seed

---

app/assets/javascripts/discourse/app/modifiers/sticky-avatars.js

This margin hack appears to have only been needed when old topic map existed.
Now that the new topic map is there it leads to a weird blank space at the end of topics.

FIX: stop injecting uneeded margin

---

db/fixtures/003_flags.rb

Avoid reaching Redis cache while running migrations

PERF: no redis calls when running migrations

---

plugins/poll/assets/javascripts/discourse/components/poll.gjs
plugins/poll/test/javascripts/acceptance/poll-results-test.js

initially, the list of voters shown on the poll results has a limit of 25 per option.
If the actual number of voters is longer, a button is presented to allow the user to load another page of voters if they so choose. 
This calls a method to retrieve the extra voter information.
a bug existed such that the local tracked object was not correctly updated for ranked choice voters as there are two attributes per option, one which tells the interface if new data is currently loading, and the other contains the list of voters. 
so instead of updating the entire option key with the voters list, we must update the voters attribute only.
a small but critical change.
The PR includes a significant new test which will add coverage over and above this issue.

FIX: poll ranked choice voter list corrupting on expand

---

plugins/poll/assets/javascripts/discourse/components/poll-options.gjs
plugins/poll/assets/javascripts/discourse/components/poll-results-standard.gjs
plugins/poll/assets/javascripts/discourse/components/poll.gjs
plugins/poll/test/javascripts/component/poll-test.js

See: https://meta.discourse.org/t/cant-edit-topic-with-poll-bug-occurs/320845?u=merefield
When the Poll is set to "results ON_CLOSE", vote numbers for each option are only streamed to the browser when the vote is Closed.  It is therefore not possible to render the Results.
The current issue is that when you refresh the page, for those that have voted the default view is results.  For this type of poll this should NOT happen.  The Results view in this mode should not be possible to see until closure, even for the Author.
Because the votes are not yet serialised when this kind of poll remains open, an attempt to display results causes a JavaScript exception and in any case does not make logical sense.
So the fix here is making sure the default view, for Polls that have results on close, is …

FIX: poll when config is on_close only show results when poll is closed

---

app/models/post_action_type.rb
db/fixtures/003_post_action_types.rb

Reload is too expensive in a multisite environment. A proper way to expire cache is coming with the next PR.

PERF: do not expire cache when PostActionType is seed

---

app/jobs/regular/push_notification.rb
app/services/post_alerter.rb
spec/jobs/push_notification_spec.rb
spec/services/post_alerter_spec.rb

This change ensures native push notifications respect the site setting for `push_notification_time_window_mins `. Previously only web push notifications would account for the delay, now we can bring more consistency between Discourse in browser vs Hub, by applying the same delay strategy to both forms of push notifications.

FEATURE: add delay to mobile push notifications

---

plugins/chat/assets/stylesheets/common/base-common.scss

Few px alignment for the chat timestamp:

UX: remove baseline alignment from chat timestamp

---

app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js

This commit forces the textarea to check if the list is inside a codefence and won't continue the list if it's the case.
Example:
---
Some text
\```
\- Item <- pressing enter at this position won't create a new list item
---
Note this commit also uses the message param of qunit assertions to make them more explicit. It has no impact on behavior.

FIX: do not continue list inside codefence

---

spec/integrity/having_multiple_tagged_loggers_spec.rb

When upgrading to Rails 7.1, we had some problems because we were using several tagged loggers at the same time. They were all added to the main broadcast logger shipped with Rails, but the Rails 7.1 codebase contains a bug making a request being run as many times as there are tagged loggers.
The fix was to use the code from the Rails 7.2 codebase.
This PR adds a small spec to ensure the behavior will stay the proper one in the future.

DEV: Add spec to ensure app works with multiple tagged loggers

---

app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.js

Use `on` modifier instead, and set proper href attributes on links

DEV: Replace onClick props in topic-timeline container

---

app/assets/stylesheets/common/admin/dashboard.scss

FIX: Set overflow-x to auto to prevent scroll bar from always showing

---

app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/discourse/tests/integration/helpers/category-link-test.js

`defaultCategoryLinkRenderer` is using a fake category object which doesn’t have access to the functions and getters of category model.
This had been incorrectly set in https://github.com/discourse/discourse/commit/c197daa04c3114184cbd3ec2f1cfade1b5701793
As we don't get a real category object, we have to call the transformers manually and also pass the fake category object as context, this is not ideal as people might try to access properties in the transformer which are not available on the category object given they will be different based on the context. Hopefully one day this helper and all the chain can be refactored to use a real category model.
This commit also adds tests for these two properties in the category-link helper.

FIX: access correct name and description

---

plugins/chat/app/services/chat/auto_remove/handle_category_updated.rb

This commit seeks to reduce the memory footprint of `Chat::AutoRemove::HandleCategoryUpdated.call`
by optimizing the
`Chat::AutoRemove::HandleCategoryUpdated#remove_users_without_channel_permission` method which was
loading all the ActiveRecord users objects into memory at once. This
change updates the method call to load the ActiveRecord user objects in
batches instead.

PERF: Reduce memory footprint of `Chat::AutoRemove::HandleCategoryUpdated`

---

config/unicorn.conf.rb
lib/demon/base.rb
lib/discourse.rb

This commit updates `Demon::Base#start` to call `Discourse.before_fork`
before forking. According to the docs in `mini_racer`, we need to
"Dispose manually of all MiniRacer::Context objects prior to forking".
This commit is motivated by a segmentation fault which we are seeing in
production when killing a daemon process. Backtrace of the core dump
includes traces of `mini_racer` so we think this is the cause. Note that
we are not 100% sure if this will fix the issue.

FIX: Ensure we dispose of MiniRacer::Context before forking daemons

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/general-settings.gjs
app/assets/javascripts/discourse/app/components/about-page.gjs
spec/system/about_page_spec.rb
spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/uppy_image_uploader.rb
spec/system/page_objects/pages/about.rb

This PR fixes a bug in the redesigned about page where if there's no banner image configured for the page, the top of the page where the banner goes is occupied with large white space.
Before:
After:
Additionally, this PR also fixes a related bug in the admin config area for the /about page where it's not possible to remove the uploaded banner image.

FIX: Don't show blank space when there's no banner image

---

app/assets/javascripts/discourse/app/form-kit/lib/validator.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/input-number-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/input-text-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs

0 is falsy in JavaScript, so the original code would treat 0 as if it were not input. This unique exception was added to prevent 0 from being treated as empty input.
Screenshot before:

FIX: FormKit: Allow 0 in required number input

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/stylesheets/common/base/about.scss
app/assets/stylesheets/common/base/faqs.scss
spec/system/about_page_spec.rb

This PR tweaks the new /about page so that it can display 3 columns of users when there's space.
Before:
After:

UX: Tweak styling for the new /about page

---

app/serializers/wizard_field_choice_serializer.rb

If your wizard step has a dash in it, e.g. `foo-bar`, the wrong i18n key will be inferred for selects. This PR ensures the key is `underscore`d.

DEV: Generate correct i18n keys for wizard radio choices

---

app/assets/javascripts/discourse/app/static/wizard/components/wizard-field.gjs

We changed the design of the member access wizard step to use toggle groups instead of switches. To support existing designs for notices, we need another plugin outlet.
Here's a demo of the new plugin outlet in use. It's used to render the notice at the bottom:

DEV: Add plugin outlet for below wizard field

---

app/assets/javascripts/discourse/app/components/sidebar/section-link.gjs

When browsing through a sidebar with this feature enabled (i.e. admin, or docs), it's weird to have the scroll jump around when you click an item. This commit adds a check, so that we only `scrollIntoView` for items which are not already in the viewport.
Followup to b7cce1a0dcae18b3b8e4ed3bb06db43b5b71180d

UX: Only `scrollIntoView` if sidebar items are not already visible

---

app/assets/javascripts/discourse/app/initializers/freeze-valid-transformers.js

plugins/themes need to use `withPluginApi` to register transformers, and that only works after `discourse-bootstrap` has been run

DEV: Fix ordering of `freeze-valid-transformers`

---

app/serializers/reviewable_score_serializer.rb
spec/serializers/reviewable_score_serializer_spec.rb

After this change, a reason won't exclusively be a translation key anymore, but now, it can display a custom reason as well. We will escape HTML elements as a precaution. The string can come from a 3rd party and shouldn't be trusted.

FEATURE: Allow completely custom score reasons.

---

app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.gjs

This outlet is in the same place in sidebar mode, so we need it here to support the same customizations in dropdown mode as well.

DEV: add before-sidebar-sections outlet to dropdown mode too

---

app/assets/javascripts/discourse/app/static/wizard/components/wizard-field.gjs

We changed the design of the member access wizard step to use toggle groups instead of switches. To support existing designs for notices, we need another plugin outlet.
Merged in `main` [here](https://github.com/discourse/discourse/pull/28371). This is a backport to `stable`.

DEV: Add plugin outlet for below wizard field (stable)

---

plugins/chat/lib/chat/notifier.rb

This change delays the notify watching job to allow time for message to be marked as seen within chat.
Without a slight delay the job fires straight away and often means that messages are seen on screen but the user also receives a notification due to `Chat::Notifier.user_has_seen_message?` returning false.
I've omited a test since the change doesn't introduce new changes aside from delaying the job.

FIX: delay chat notify watching job

---

app/assets/javascripts/discourse/app/lib/desktop-notifications.js

Desktop chat notification sounds have stopped working on most desktop browsers.
This is due to Notifications API being disabled when Push Notifications are supported in the browser, which means that we never iterate on the `desktopNotificationHandlers` and trigger the callback since we return early.
I haven't added tests in this PR as this is fairy complex to test based on device type and audio playback.

FIX: allow chat sound when notifications are disabled

---

app/assets/javascripts/discourse-markdown-it/src/features/image-controls.js
app/assets/javascripts/discourse/tests/acceptance/composer-image-preview-test.js

When adding a video/image/audio to a post, we check the token content for dimensions. If dimensions are found, we assume the content can be resized and give it image controls in the composer preview. 
The problem is that we check the entire token, including filename, for dimensions. This means if a video has dimensions in its filename, we show broken controls: 
This PR updates the `hasMetadata` function so it checks the area dedicated to dimensions specifically, which comes after the `|` in markdown. 
Now images get the controls, and videos with dimensions in their filename do not:

UX: do not check for dimensions in video filename

---

plugins/chat/app/services/chat/action/calculate_memberships_for_removal.rb
plugins/chat/app/services/chat/auto_remove/handle_category_updated.rb
plugins/chat/app/services/chat/auto_remove/handle_destroyed_group.rb
plugins/chat/app/services/chat/auto_remove/handle_user_removed_from_group.rb

This is a follow up to ed11ee9d057160e5c1b0d1a86c9e94582d8fafd0.
In `Chat::AutoRemove::HandleCategoryUpdated`, we are currently loading
the related users record in batches and then handing it off to
`Chat::Action::CalculateMembershipsForRemoval.call`. However, we are
still seeing memory spike as a result of this.
This commit eliminates the allocation of `User` ActiveRecord objects until
absolutely necessary. `Chat::Action::CalculateMembershipsForRemoval.call` has been
updated to accept an ActiveRecord relation instead which allows us to
avoid the ActiveRecord allocations.

PERF: Reduce memory footprint of `Chat::AutoRemove::HandleCategoryUpdated.call`

---

app/assets/javascripts/discourse/app/components/sidebar/section-link-button.gjs

The `section-link` component gets a data attribute with the link name, like `data-list-item-name="My cool link"` — the `section-link-button` component is missing this. 
I've added it here to make these easier to target with CSS individually.

DEV: give sidebar link buttons a data-list-item-name

---

app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
app/assets/javascripts/admin/addon/controllers/admin-dashboard-new-features.js
app/assets/javascripts/admin/addon/controllers/admin-dashboard.js
app/assets/javascripts/admin/addon/models/admin-dashboard.js
app/assets/javascripts/admin/addon/routes/admin-dashboard-new-features.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/dashboard.hbs
app/assets/javascripts/discourse/app/lib/notification-types/new-features.js
app/assets/javascripts/discourse/tests/acceptance/dashboard-test.js
app/assets/javascripts/discourse/tests/fixtures/dashboard-whats-new.js
app/controllers/admin/dashboard_controller.rb
spec/requests/admin/dashboard_controller_spec.rb
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/pages/admin_new_features.rb

We used to show New Features in a tab on the dashboard,
but this could get pushed down the page especially on
our hosting. In https://github.com/discourse/discourse/commit/043117ca1389b8d7b564a7cfb9d98aeb86403ea7
we made a separate What's New page, so this commit removes
the dashboard tab and changes the admin notification to
send the admin to /admin/whats-new instead of the dashboard
tab.

FEATURE: Always show full page "New Features" to admins

---

plugins/chat/app/services/chat/auto_remove/handle_category_updated.rb

This is a follow-up to 671f40ce07ebda14e4655cb85ce4794b859023f0 and
ed11ee9d057160e5c1b0d1a86c9e94582d8fafd0.
While the optimisations in the previous commits were sound, it did not
resolve the memory bloat we were seeing. It turns out that in a [Service object](https://github.com/discourse/discourse/blob/931485b7c10dd61407697228c6a7fdc70c4f192d/app/services/service/base.rb#L3) we call
[.blank?](https://github.com/discourse/discourse/blob/931485b7c10dd61407697228c6a7fdc70c4f192d/app/services/service/base.rb#L142) on the model's result if the model has not been marked
optional. The problem with this is that if the model returns an
ActiveRecord relation, calling `.blank?` on the relation basically loads
everything into memory.
Therefore, this commit removes `users` as a model in the  since …

PERF: Reduce mem allocation of `Chat::AutoRemove::HandleCategoryUpdated`

---

plugins/chat/app/jobs/scheduled/chat/auto_join_users.rb
plugins/chat/spec/jobs/scheduled/auto_join_users_spec.rb

- Only ever auto join 10k users to channels (ordered by last seen)
- Join users to all channels at once, instead of batching and splitting

PERF: automatically join users to channels more efficiently

---

spec/lib/backup_restore/local_backup_store_spec.rb
spec/rails_helper.rb
spec/support/backups_helpers.rb

This has been split out from https://github.com/discourse/discourse/pull/28051
so we can use this same code in plugin specs before merging the core PR,
adds some helpers for creating local backup temp files
and cleaning them up.

DEV: Add backup helpers for specs

---

app/assets/javascripts/discourse/app/templates/user.hbs

Move it into the preceding `dl` element and remove the `div` wrapper.
The two plugins that use this outlet:
* d-follow - actually jumps through hacky hoops to get its elements into that `dl` anyway
* d-gamification - would look better if its element was in that `dl`

DEV: Move user-profile-secondary outlet

---

app/assets/javascripts/discourse/app/lib/highlight-syntax.js

Long code is considered 1000 characters atm. 10000+ characters would take seconds due to how highlightjs will consider every installed lang before choosing the best candidate.

FIX: bypass highlighths for long code in auto mode

---

app/assets/javascripts/discourse/app/templates/user/badges.hbs

Omits the "0/0 badges marked as favorite" notice when max favorites badge is 0.

UX: omit fav badges count if max is 0

---

app/assets/javascripts/discourse/app/helpers/route-action.js

`routeAction` is testing at runtime that a route exists when in debug mode. However in the case of components tested in isolation there's no existing route which was causing an exception, this commit prevents this check in this case as it's irrelevant.

DEV: prevents route action to crash in tests

---

app/assets/javascripts/discourse/app/components/sidebar/footer.gjs

`routeAction` is an old and bad pattern we don't want to have in the codebase anymore.

DEV: removes route action usage from sidebar footer

---

app/assets/javascripts/admin/addon/routes/admin-whats-new.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/app/models/user.js
app/assets/stylesheets/common/admin/sidebar.scss
app/serializers/current_user_serializer.rb
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/components/navigation_menu/base.rb

This commit adds a blue dot next to the "What's New"
link in the admin sidebar if the user has not seen the
new features yet, as a followup to 3e5976f8436255185de556ae165d9d849ac8fb3a
which removed the tab on the dashboard that had this same
functionality.
When the admin visits the "What's New" page they count
as having seen all the features straight away. This could
be something we want to change, but for now this keeps the
same functionality.

FEATURE: Unseen feature indicator in admin sidebar

---

lib/guardian.rb

In development mode and when a developer's email is configured as part
of `Rails.configuration.developer_emails`, the user can be trusted and
should not be required to be an admin user.

DEV: Update `Guardian#is_developer` to only require admin for Developer

---

plugins/poll/assets/javascripts/discourse/components/poll.gjs
plugins/poll/test/javascripts/acceptance/poll-results-test.js

An additional follow-up change on top of #28315 (which is still a valid improvement)  is required as currently expanded voter lists are almost immediately overwritten by incoming data on the message bus and post stream and effectively cancels the expansion leading to an uncomfortable user experience.  This was unfortunately not picked up during unit testing nor by manual testing because in dev the refresh cycle is so long.
So to prevent this and allow a user time to examine the expanded voter list, this change renders incoming updates for voter user lists disabled as soon as any option's voters list is expanded.  This only impacts big polls with > 25 voters on an option,
I believe this is a reasonable compromise and it still allows polls with fewer than 26 votes on an option to continue …

FIX: make poll voter list expansion persistent

---

app/assets/javascripts/discourse/app/controllers/full-page-search.js

The `SortOrders` were cached before translation overrides were applied on the client.

FIX: Translation overrides didn't work for search orders

---

app/assets/javascripts/discourse/app/instance-initializers/localization.js

There's no need to keep them around. This might just bloat memory if there are lots of translation overrides.

PERF: Delete `I18n._overrides` after they have been applied

---

lib/tasks/assets.rake
package.json

This was previously relying on a globally-installed terser, which comes from a time before Discourse had proper JS dependency management

DEV: Use `yarn`-installed terser in assets.rake

---

app/serializers/post_serializer.rb
lib/topic_view.rb
spec/lib/topic_view_spec.rb
spec/serializers/post_serializer_spec.rb

This commit fixes two codepaths which where incorrectly working with capitalized usernames as we were doing a mix of username_lower and non lower username.
Also adds two specs for these cases.

FIX: broken mentioned users with capitalized usernames

---

app/assets/javascripts/admin/addon/components/admin-backups-actions.gjs
app/assets/javascripts/admin/addon/components/admin-filtered-site-settings.gjs
app/assets/javascripts/admin/addon/components/admin-page-action-button.gjs
app/assets/javascripts/admin/addon/components/admin-page-header.gjs
app/assets/javascripts/admin/addon/components/admin-page-subheader.gjs
app/assets/javascripts/admin/addon/components/admin-plugin-config-metadata.gjs
app/assets/javascripts/admin/addon/components/version-checks.hbs
app/assets/javascripts/admin/addon/controllers/admin-backups-index.js
app/assets/javascripts/admin/addon/controllers/admin-backups-settings.js
app/assets/javascripts/admin/addon/controllers/admin-backups.js
app/assets/javascripts/admin/addon/routes/admin-backups-settings.js
app/assets/javascripts/admin/addon/routes/admin-backups.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/backups-index.hbs
app/assets/javascripts/admin/addon/templates/backups-logs.hbs
app/assets/javascripts/admin/addon/templates/backups-settings.hbs
app/assets/javascripts/admin/addon/templates/backups.hbs
app/assets/javascripts/admin/addon/templates/dashboard.hbs
app/assets/javascripts/admin/addon/templates/plugins-show-settings.hbs
app/assets/javascripts/discourse/app/components/uppy-backup-uploader.hbs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/admin_config_area.scss
app/assets/stylesheets/common/admin/admin_page_header.scss
app/assets/stylesheets/common/admin/backups.scss
app/assets/stylesheets/common/admin/dashboard.scss
config/locales/client.en.yml
config/routes.rb
spec/system/admin_backups_spec.rb
spec/system/page_objects/admin_backups.rb
spec/system/page_objects/pages/admin_site_settings.rb

This commit converts the Backups page in the admin interface
to follow our new admin interface guidelines, it looks like this now:
As part of this work, I've also made `AdminPageHeader` and `AdminPageSubheader`
components that can be reused on any admin page for consistency, that handle
the title and action buttons and also breadcrumbs.
Also renamed `AdminPluginFilteredSiteSettings` to `AdminFilteredSiteSettings` since
it can be used generally to show a subset of filtered site settings, not only
settings for a plugin. Not sure if it's ideal to have to define a new route for this
for every config area, but not sure how else to do it right now.

UX: Apply admin interface guidelines to Backups page

---

spec/lib/backup_restore/local_backup_store_spec.rb
spec/rails_helper.rb
spec/support/backups_helpers.rb

This has been split out from https://github.com/discourse/discourse/pull/28051 so we can use this same code in plugin specs before merging the core PR, adds some helpers for creating local backup temp files and cleaning them up.

DEV: Add backup helpers for specs (#28394)

---

.github/workflows/tests.yml

QUnit tests are failing in different ways on Chromium in Debian bookworm. We have no interest in figuring out why as it is not a good use of our time and the long term plan is to switch to Chrome for Testing anyway.

DEV: Switch back to Chrome for running QUnit tests

---

config/site_settings.yml
spec/services/post_alerter_spec.rb

Currently the push_notification_time_window_mins is set to 10
minutes by default. We want to change this to 1 minute, which is the
delay it has been set to on meta and our internal site already for over
a year now.
This conforms to the expectation users have that notifications are
delivered close to immediately.

FEATURE: Change default for push_notification_time_window_mins

---

app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/form-test.gjs

This commit adds the addError method to From's onRegisterApi to allow parent components to add errors to a field.

DEV: add addError method to FormKit onRegisterApi

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/discourse/tests/integration/components/about-page-test.gjs
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
lib/plugin/instance.rb
plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
plugins/chat/config/locales/client.en.yml
plugins/chat/plugin.rb
plugins/chat/spec/system/about_page_site_acitivity_spec.rb
spec/system/page_objects/components/about_page_site_activity.rb
spec/system/page_objects/components/about_page_site_activity_item.rb

This PR introduces a new frontend API to add custom items to the "Site activity" section in the new /about page. The new API is called `addAboutPageActivity` and it works along side the `register_stat` serve-side API which serializes the data that the frontend API consumes. More details of how the two APIs work together is in the JSDoc comment above the API function definition.
Internal topic: t/128545/9.

DEV: Allow custom site activity items in the new /about page

---

app/models/problem_check.rb
spec/services/problem_check_spec.rb

We need a way to disable certain checks programatically, e.g. on Discourse hosting. This PR adds a configuration option for this, and makes it so that disabled checks aren't run as part of `#run_all`.

DEV: Allow disabling problem checks programatically

---

app/models/problem_check.rb
spec/services/problem_check_spec.rb

We need a way to disable certain checks programatically, e.g. on Discourse hosting. This PR adds a configuration option for this, and makes it so that disabled checks aren't run as part of #run_all.
Backport of: #28440

DEV: Allow disabling problem checks programatically (stable)

---

bin/ember-cli

`bin/ember-cli -u` buffers the output of ember-cli, which means progress is not shown clearly. This commit uses `TERM=dumb` to put ember-cli into a more simple mode, which outputs progress on separate lines. Also adds a `[ember-cli]` prefix to all output.

DEV: Show ember-cli build progress when using `bin/ember-cli -u`

---

app/assets/javascripts/discourse/app/components/discovery/topics.hbs

This is an important wrapper for CSS customizations, and currently there is no clean way to select it. This adds a class so we select that spannnnn

DEV: Add class to span wrapping `after-topic-list` plugin outlet

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/javascripts/discourse/app/controllers/about.js
app/assets/javascripts/discourse/app/templates/about.hbs
app/assets/stylesheets/common/base/about.scss
app/models/application_request.rb
app/models/stat.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
lib/statistics.rb
spec/lib/statistics_spec.rb
spec/system/about_page_spec.rb
spec/system/page_objects/components/about_page_site_activity.rb
spec/system/page_objects/components/about_page_site_activity_item.rb

This PR implements 2 new metrics/stats in the /about page for the _estimated_ numbers of unique visitors from the EU and the rest of the world. This new feature is currently off by default, but it can be enabled by turning on the hidden `display_eu_visitor_stats` site settings via the rails console.
There are a number of assumptions that we're making here in order to estimate the number of unique visitors, specifically:
1. we're assuming that the average of page views per anonymous visitor is similar to the average number of page views that a logged-in visitor makes, and
2. we're assuming that the ratio of logged in visitors from the EU is similar to the ratio of anonymous visitors from the EU
Discourse keeps track of the number of both logged-in and anonymous page views, and also the …

FEATURE: Add estimated number of global and EU visitors to the about page

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
app/assets/javascripts/discourse/app/components/topic-map/topic-views.gjs

This is never really 0, because if you can see the 0... you're number 1!
before:
after:

UX: view count in topic map should always be at least 1

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/contact-information.gjs

A copy-and-paste error resulted in using the wrong subtitle for the "Site contact name" field in the admin config area for the /about page.

FIX: Use correct subtitle for Site contact name field

---

app/assets/javascripts/admin/addon/controllers/admin-backups-index.js
app/assets/javascripts/admin/addon/templates/backups-index.hbs
config/locales/client.en.yml

Followup 14465960893981e8aba49f2cc0620944f2abea53
The link to inform admins that restore is disabled
was not correct. This fixes it and also changes it
to go to /admin/backups/settings

UX: Fix restore info link on admin backups page

---

app/controllers/stylesheets_controller.rb

In some situations, the filesystem cache will be read and persisted to the database. If the file being read is still being written, then that can lead to empty/partial caches being stored in the database.
This commit ensures that cannot happen by switching to our `atomic_write_file` helper (which writes to a temp file, and then does an atomic `mv` operation to move it to the destination)

FIX: Write stylesheet cache atomically

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/general-settings.gjs

Specifying the type is required for the uploader to work on sites that use S3 uploads.

FIX: Specify `@type` for the image uploader in the about config area

---

app/assets/javascripts/discourse-common/addon/lib/raw-handlebars-helpers.js
app/assets/javascripts/discourse/tests/integration/helpers/raw-test.gjs

Regressed 3.5 years ago in e80332a2bcc5b9c56e4fd2937ecbc3b3dfff941c :P

FIX: Lost outer context in `#each` block in hbr

---

app/assets/stylesheets/common/foundation/mixins.scss

Some of the after colors feel similar (bot vs wide mention) but these color palettes intentionally use very similar colors so there aren't a lot of alternatives 
Before:
After:

UX: improve mention colors for dark color schemes

---

app/assets/javascripts/discourse/app/templates/activate-account.gjs
spec/system/signup_spec.rb

The user activation flow is currently broken within subfolder installs because `fetch`ing `/session/hp` will 404.
This PR changes it to use `ajax` instead (which already handles subfolders) and makes the "continue" flow take the user to the subfolder landing page.

FIX: subfolder account activation

---

app/assets/javascripts/discourse/app/models/nav-item.js

This would cause the infamous error:
```
index.js:118 Uncaught (in promise)
Error: Assertion Failed: You attempted to update `href` on `<ExtraNavItem:ember384>`, but it had already been used previously in the same computation.
```
Moreover, set didnt seem necessary here.

FIX: ensures href is not set two times

---

app/assets/javascripts/select-kit/addon/components/multi-select.js
app/assets/javascripts/select-kit/addon/components/select-kit.js
app/assets/javascripts/select-kit/addon/components/single-select.js
app/assets/javascripts/select-kit/addon/mixins/plugin-api.js

This lays the groundwork for converting SelectKit subclasses to native class syntax. This commit is designed to be entirely backwards-compatible, so it should not affect any existing subclasses.
Of interest:
- Any properties which are designed to be overridden by subclasses are implemented using a local `@protoProp` decorator. That means they are applied to the prototype, so that they can be overridden in subclasses by both legacy `.extend()` prototype extensions, and by modern native-class fields.
- New class decorators are introduced: `@selectKitOptions` and `@pluginApiIdentifiers`. These are native class versions of the legacy `concatenatedProperties` system. This follows the pattern Ember has introduced for `@className`, `@classNameBindings`, etc.

DEV: Convert select-kit base classes to native class syntax

---

plugins/chat/app/services/chat/search_chatable.rb

When you use the "chat search", we return 4 types of results : users, groups, category channels, and direct message channels.
When the search returns users, there's no point in showing 1:1 direct message channels with those users.
This changes the `channel.reject` condition to do _just_ that.
Internal ref - t/136079

FIX: skip 1:1s when chat search returns users

---

app/assets/javascripts/discourse/app/components/about-page.gjs

In the new /about page, when there's no extended description provided by the admin, the "About" heading above the description should not be displayed.

FIX: Hide heading when there's no custom description

---

lib/theme_store/git_importer.rb

Previously, we were silently failing when a theme hit SSRF protection, or the `git clone` command failed for some reason. This commit updates them to be exceptions, so they provide more useful error messages

DEV: Replace silent theme-install fails with exceptions

---

lib/auth/default_current_user_provider.rb
spec/lib/auth/default_current_user_provider_spec.rb

What did this fix?
===============
Previously, we only triggered this event in the `user.logged_out` method. This resulted in the event being triggered only when the user was logged out by the administrator or the site had log_out_strict mode enabled. This bug affected customers who managed user status via webhooks.
meta topic: https://meta.discourse.org/t/user-log-out-event-not-triggered-in-webhooks/249464

FIX: Trigger user_logged_out event when the user logs out

---

app/assets/javascripts/select-kit/addon/components/select-kit.js

Followup to 3e3c051164c4c32962d0a725b201784bb9a1f6a1

DEV: fixup select-kit pluginApiIdentifiers typo

---

plugins/chat/assets/javascripts/discourse/components/chat-drawer.hbs
plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
plugins/chat/spec/system/drawer_spec.rb

To achieve this, the code is now using bodyClass instead of relying on the addChatDrawerStateCallback`.

FIX: adds chat-draw-expanded class to body

---

app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js
spec/system/composer_uploads_spec.rb

If we don't get a `videoWidth` back for a video don't try and generate a
thumbnail for it.
Also as part of this change I switched getImageData, the function
throwing the error, to use video.videoWidth instead of canvas.width
because it's very likely we were setting canvas.width too early before
the width could be read. Now that we are reading the value inside of the
setTimeout hopefully we will actually have a width. Just incase we don't
detect a width we will now exit early instead of throwing an error.
We only need to check for `0` and not null because the value is an
integer and will always return a 0 if it can't be read. https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoWidth
See https://meta.discourse.org/t/322363

FIX: Videos not uploading due to thumbnail generation error

---

app/assets/stylesheets/common/form-kit/_control-textarea.scss

This existing rule needed an important because of the mixin upstream 
Before:
After:

UX: fix textarea height on mobile

---

app/assets/javascripts/discourse/app/components/header/topic/info.gjs

We should match the style in the undocked title:
Before:
After:
I've also covered this for sub-subcategories

UX: don't use split subcategory color in docked header

---

app/assets/stylesheets/common/software-update-prompt.scss

avoids this space issue by setting the top offset to 0 on relevant pages

UX: adjust software update banner for headerless pages

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/discourse/tests/acceptance/table-builder-test.js
app/assets/javascripts/select-kit/addon/components/dropdown-select-box/dropdown-select-box-row.hbs
app/assets/javascripts/select-kit/addon/components/toolbar-popup-menu-options.js
app/assets/stylesheets/common/select-kit/toolbar-popup-menu-options.scss
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
plugins/discourse-presence/test/javascripts/acceptance/discourse-presence-test.js
spec/system/table_builder_spec.rb

Previous to this change there is no clean way to apply keyboard shortcuts
to things such as "add poll" and other hidden options in the toolbar
This allows shortcuts to be specified similar to how they are on the toolbar

 FEATURE: allow plugins to specify keyboard shortcuts for hidden toolbar items

---

.github/workflows/tests.yml

We cannot just key on `runner.os` the number of CPU cores matter as
well. Therefore, we need to key on `runner.name` instead since each
runner has its own unique OS and CPU cores. Technically, two different
runner with different names can have the same `os` and `cpu cores` but
we don't have that problem now.

DEV: Update `app-cache` cache key for tests workflow

---

app/controllers/topics_controller.rb
app/serializers/suggested_topics_mixin.rb
lib/topic_view.rb
spec/requests/topics_controller_spec.rb
spec/serializers/topic_view_serializer_spec.rb

This commit improves `TopicsController#show` to not load suggested and
related topics unless it is the last page of the topic's view.
Previously, we avoided loading suggested and related topics by the use
of conditionals in the `TopicViewSerializer` to avoid calling
`TopicView#suggested_topics` and `TopicView#related_topics`. However,
this pattern is not reliable as the methods can still be called from
other spots in the code base. Instead, we ensure that
`TopicView#include_suggested` and `TopicView#include_related` is set
correctly on the instance of `TopicView` which ensures that for the
given instance, `TopicView#suggested_topics` and
`TopicView#related_topics` will be a noop.

PERF: Ensure suggested topics is only loaded on last page of topic view

---

.github/workflows/tests.yml

This allows to maximize the CPU cores when the tests workflow is ran on
a larger runner.

DEV: Avoid hardcoding PARALLEL_TEST_PROCESSORS in tests workflow

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/tests/integration/components/d-editor-test.js

This function was available in textarea manipulation mixin, but not exposed as other functions like addText, applySurround, ...

DEV: adds support for replaceText in toolbarEvent

---

app/assets/javascripts/discourse/app/components/auth-token-dropdown.js
app/assets/javascripts/discourse/app/components/bookmark-actions-dropdown.js
app/assets/javascripts/discourse/app/components/bulk-group-member-dropdown.js
app/assets/javascripts/discourse/app/components/email-dropdown.js
app/assets/javascripts/discourse/app/components/group-member-dropdown.js
app/assets/javascripts/discourse/app/components/security-key-dropdown.js
app/assets/javascripts/discourse/app/components/tags-admin-dropdown.js
app/assets/javascripts/discourse/app/components/token-based-auth-dropdown.js
app/assets/javascripts/discourse/app/components/two-factor-backup-dropdown.js
app/assets/javascripts/discourse/app/components/user-nav/messages-dropdown.js
app/assets/javascripts/discourse/app/components/user-preferences/passkey-options-dropdown.js
plugins/chat/assets/javascripts/discourse/components/chat-channel-chooser.js
plugins/chat/assets/javascripts/discourse/components/chat-thread-tracking-dropdown.js
plugins/chat/assets/javascripts/select-kit/addons/components/thread-notifications-button.js

This covers all select-kit subclasses in core and core plugins
Followup to https://github.com/discourse/discourse/pull/28489

DEV: Convert select-kit subclasses to native class syntax

---

app/assets/javascripts/admin/addon/controllers/admin-badges/show.js
app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
spec/system/admin_badges_spec.rb
spec/system/page_objects/admin_badges.rb

This change is preventing the "is dirty check" from happening when clicking delete on this form. This was not good UX and was also causing bugs by leaving the form in a unexpected state.

FIX: correctly reset form before destroying it

---

plugins/automation/lib/discourse_automation/scripts/topic.rb
plugins/automation/spec/scripts/topic_spec.rb

Create a topic can fail in many different ways and we don't want this to impact the rest of the application, the call will now be wrapped in a begin/rescue block and log an error if it fails.

FIX: prevents creating post from impacting the app

---

app/assets/javascripts/discourse/app/components/navigation-bar.gjs
app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/discourse/tests/integration/components/widgets/post-test.js
app/assets/javascripts/float-kit/addon/components/d-menu.gjs
app/assets/stylesheets/common/components/topic-map.scss
app/assets/stylesheets/common/float-kit/d-menu.scss
app/assets/stylesheets/mobile/components/_index.scss
app/assets/stylesheets/mobile/components/dropdown-menu.scss
app/assets/stylesheets/mobile/components/topic-map.scss
app/assets/stylesheets/mobile/float-kit/d-menu.scss
app/assets/stylesheets/mobile/list-controls.scss
app/assets/stylesheets/mobile/modal.scss

Now that DMenu is getting more use, it's important to make an effort to be consistent in its design.
This commit is a first step:
* li-elements use the same spacing
* by default, any direct `a-tag` or `button` gets the same padding: `.75em .1rem `
* Why: The default use case for DMenuMobile is to show a menu, consisting of either links or buttons that should be spaced evenly.   
* Any other element used within the DMenu component should apply the same padding manually
* EMs for block spacing to adjust with fonts, to maintain an relative spacing; REMs are used for inline spacing, to ensure vertical alignment across different fonts used
* container padding is consistent
* no inline-padding, to facilitate side-to-side hover effects 
It was necessary to change some topic-map CSS to implement …

UX: centralise DMenu mobile styling + fixes

---

app/assets/javascripts/admin/addon/controllers/admin-badges/show.js
app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/image.gjs
app/serializers/admin_badge_serializer.rb
spec/requests/api/schemas/json/badge_create_response.json
spec/requests/api/schemas/json/badge_list_response.json
spec/requests/api/schemas/json/badge_update_response.json
spec/system/admin_badges_spec.rb
spec/system/page_objects/admin_badges.rb
spec/system/page_objects/components/form_kit.rb

In the formkit conversion in 2ca06ba2360c200b2be8e0718fcc04c64ca14935 we missed setting a type for the UppyImageUploader for badges. Also, we were not passing down the `image_url` as form data, so when we used `data.image` for that field the badge was not updating in the UI after page loads and the image URL was not loading for preview.

FIX: Badge image uploader (#28188)

---

app/assets/javascripts/discourse/app/components/tag-info.js
app/assets/javascripts/discourse/tests/acceptance/tags-test.js
spec/system/page_objects/pages/tag.rb
spec/system/tag_view_spec.rb

If you’re viewing a tag and you switch to a different tag via the sidebar or the tags dropdown, after expanding the info section of the tag page via the wrench button, the info section keeps showing the previous tag's details instead of the new one.
This happens because the tag info section makes an ajax request to load the tag's details, and this request is made inside the `didInsertElement` hook which is only fired once when the component is rendered. To fix this, we need to set the result from the ajax request to null and add a `didUpdateAttrs` hook to trigger another request to load the info of the new tag.
Internal topic: t/134809.

FIX: Refresh the edit tag section when navigating to another tag

---

app/assets/javascripts/discourse/app/mixins/composer-video-thumbnail-uppy.js
spec/system/composer_uploads_spec.rb

If there is a codec issue or something trying to process a video file
for thumbnail generation, uploads could hang indefinitely. This fix
ensures that we continue the upload process even if we encounter an
error trying to generate a thumbnail for it.

FIX: Video uploads sometimes hang indefinitely

---

app/models/bookmark.rb
lib/bookmark_reminder_notification_handler.rb
lib/bookmarks_bulk_action.rb
spec/lib/bookmark_reminder_notification_handler_spec.rb
spec/lib/bookmarks_bulk_action_spec.rb

Followup 76c56c82845b4fce63c6f1cdf4ac3935bf1747e7
The change introduced above made it so the expired
bookmark reminders were cleared when using the bulk
action menu for bookmarks. However this also affected
clearing reminders for bookmarks when sending notifications.
When clearing bookmark reminders after sending notifications,
we take into account the auto delete preference:
* never          - The bookmark `reminder_at` date should not be cleared,
and the bookmark is kept.
* clear_reminder - The bookmark `reminder_at` date is cleared and
the bookmark is kept
The `never` option made it so "expired" bookmark reminder show
on the user's bookmark list.
This commit fixes the change from the other commit and only
forces clearing of `reminder_at` if using the bookmark bulk
action service.

FIX: Bookmark reminder was clearing incorrectly

---

db/migrate/20240820123404_copy_notifications_id_indexes.rb
db/migrate/20240820123406_drop_old_notification_id_indexes.rb

Follow up to 799a45a291e9f2bd94278f565e58874458768079

DEV: Fix bigint notifications id migration to deal with public schema

---

app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js

Replacing value in the composer will not maintain history, this migrates
us to the new pattern used throughout this file

FIX: when replacing text in composer maintain history

---

spec/system/page_objects/components/composer.rb

Covers the use case of doing this in composer:
```javascript
page.execute_script("document.querySelector('.d-editor-input').setSelectionRange(6, 12);")
```

DEV: Add select_range to composer page object

---

app/assets/javascripts/discourse/app/instance-initializers/subscribe-user-notifications.js
plugins/chat/assets/javascripts/discourse/services/chat-notification-manager.js

Small follow up to #28385 to prevent attempting to create desktop notifications (and notification handlers) on mobile.
We shouldn't attempt to process any desktop notification tasks when not on mobile. This change fixes an issue where chat desktop sounds would be played on mobile hub.
There is no test coverage for JS Notifications API and since it requires browser and system level permissions by the user I've omitted adding tests for now due to complexity.

FIX: prevent desktop notification callbacks on mobile

---

app/models/user.rb
spec/models/user_spec.rb

This check was checking the wrong scope, causing problems in certain edge conditions, for example:
1. Admin adds an "on signup" field that isn't editable after signup.
2. Admin adds a "for all users" field.
3. User goes and fills up the "for all users" field from 2.
4. User is now stuck on the required fields page without any fields showing.
We only consider "for all users" fields when asking if required custom fields are filled in.

FIX: Fix incorrect check for required custom fields

---

app/assets/javascripts/admin/addon/components/admin-watched-word.gjs
app/assets/javascripts/discourse/tests/acceptance/admin-watched-words-test.js

This was a recent error due to a mistake in https://github.com/discourse/discourse/commit/eccfc946f164983055a72fc4a60898499f645d58
This commit also adds a test which would have caught this.

FIX: prevents exception when showing replacements

---

app/assets/javascripts/discourse/app/controllers/group-requests.js
app/assets/javascripts/discourse/tests/acceptance/group-requests-test.js

In GroupRequestsController, request_count is incorrectly written as user_count, which causes group member requests to be loaded infinitely when user_count is greater than request_count.
meta topic link: https://meta.discourse.org/t/bug-with-group-requests/315353/

FIX: Prevent group requests from loading infinitely

---

app/models/topic_hot_score.rb
spec/models/topic_hot_scores_spec.rb

Prior this fix a topic created in the future could generate this exception:
```
Job exception: ERROR:  a negative number raised to a non-integer power yields a complex result
```
This fix and spec should ensure we don't consider topics in the future as the rest of the `update_scores` function is doing at other places.

FIX: prevents topic hot scope error on future topics

---

app/serializers/flag_serializer.rb
spec/serializers/flag_serializer_spec.rb

Currently, `FlagSerializer#short_description` properly provides `base_path` to its translations, but `FlagSerializer#description` does not. This breaks the link to guidelines when flagging a post, for example.
This PR provides `base_path` for `FlagSerializer#description` too.

FIX: Return properly interpolated translations for flags

---

app/models/directory_item.rb
app/models/user.rb
spec/models/user_spec.rb
spec/requests/users_controller_spec.rb

Follow-up to https://github.com/discourse/discourse/pull/27020
The previous PR added an `after_create` callback that triggers a refresh for the user directory whenever a `User` record is created. Theoretically, this approach should work, however, there's a gotcha in practice, because during a real user registration, when the `User` record is created in the database, it's not marked as active until the user verifies their email address and the user directory excludes inactive users, so the initial directory refresh triggered by the `after_create` callback becomes pointless.
To make a new user appear in the user directory immediately after sign up, we need to trigger a refresh via an `after_save` callback when they verify their email address and become active.

FIX: Add users to user directory on account activation

---

app/assets/javascripts/admin/package.json
app/assets/javascripts/discourse-common/package.json
app/assets/javascripts/discourse/package.json
app/assets/javascripts/select-kit/package.json
yarn.lock

A follow-up to dd1abf91ef2176f0a9edf54c31870c573fda4a72.
Because `ember-cli-deprecation-workflow` relied on `@ember/string` 3.1.1, that was the effective version used in the app.
Turns out there's a compatiblity issue with 4.0.0. Let's lock it to 3.x so we can easily update deprecation-workflow and then we can look into the ember/string issue.

DEV: "Downgrade" `@ember/string` from 4.x to 3.x

---

app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js

Prior to this fix using:
- `replaceText(...)`
- `selectText(..., ..., { scroll: true})`
Wouldn't have the expected behaviour as the scroll from selectText will attempt to save the scroll position and restore it AFTER the replacement happened. This commit allows scroll to be a Boolean or a Number, when a number, it will be used to restore the scrollTop position.
I tried to write tests for this specific behavior but couldn't reproduce the issue in tests.

FIX: allows selectText to take a scroll position as opt

---

app/assets/javascripts/admin/addon/controllers/admin-badges/show.js
app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/app/form-kit/lib/fk-form-data.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/form-test.gjs

In FormKit you can add error on an existing field existing in the DOM, but you can also set an arbitrary error on a virtual field not existing in the DOM.
When revalidating existing data, we are only resetting real fields. This commit adds `removeError(name)` to allow you to manually manage virtual fields. `removeError` is available in the same helpers where `addError` is available.

FIX: allows to manually remove error for virtual fields

---

app/assets/javascripts/discourse/app/controllers/topic.js
spec/system/topic_page_spec.rb

Given we are a single-page-app, we hijack the browser's default behavior for keyboard shortcuts like End because on long topics (20+ posts) we need to load the last post before really reaching the end of the page.
However, when the last post is already rendered, the End shortcut currently does nothing, it takes the user to the start of the last post. If that post is too long, the user will have to scroll down manually.
This change ensures that if the last post of a topic is already rendered (whether it is in the viewport or not), pressing End will take the user to the very bottom of the page.
Note for the reviewer: the test added here is for the general case, it is too hard to test the case where the last post is already rendered, that isn't covered here.

FIX: Respect the End key when last post is already rendered

---

app/assets/javascripts/select-kit/addon/components/toolbar-popup-menu-options.js

On windows + are shown between keys, not on mac. The fix was to wrap the whole shortcut in `translateModKey`.

FIX: correctly shortcut format on mac

---

app/assets/javascripts/admin/addon/components/admin-config-areas/flags-settings.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/flags.gjs
app/assets/javascripts/admin/addon/controllers/admin-config-flags-settings.js
app/assets/javascripts/admin/addon/controllers/admin-config-flags.js
app/assets/javascripts/admin/addon/routes/admin-config-flags-edit.js
app/assets/javascripts/admin/addon/routes/admin-config-flags-settings.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-flags-settings.hbs
app/assets/javascripts/admin/addon/templates/config-flags.hbs
app/assets/stylesheets/common/admin/settings.scss
config/locales/client.en.yml
spec/system/admin_flags_spec.rb
spec/system/page_objects/components/admin-header.rb
spec/system/page_objects/pages/admin_flags.rb

Add settings tab to flags moderation page.

UX: flag settings tab to follow UI guidelines

---

spec/system/admin_site_texts_spec.rb

Followup a16faa27cd0088361c1a486a68c98e731ab57878
I18n and translation overrides were not reset
between specs which led to the wrong text being
searched for in assertions

DEV: Fix flaky site text spec

---

spec/system/user_page/user_preferences_profile_spec.rb

To test the restricted routing when filling up required fields, we fill up the field and then navigate to the root path and checking that we're not redirected.
This is somewhat flaky, and the screenshot shows we are back at the profile page, without any prompt to fill up fields.
My hypothesis is in cases where the backend is "slow" to respond, we're navigating away from the page before the request finishes (which will redirect back to the profile page.)
This PR adds an expectation after saving, to wait until the unrestricted profile page is rendered, before navigating away.

DEV: Fix flaky profile spec by waiting for request to finish

---

app/assets/javascripts/discourse/app/components/modal/history.js
app/assets/javascripts/discourse/tests/acceptance/history-test.js
app/controllers/posts_controller.rb
spec/requests/posts_controller_spec.rb

Showing or hiding the revision on a post will update the clients through MessageBus. If, for some reason, the post does not get updated, attempting to fetch a hidden or nonexistent revision will yield the proper error and refresh the post to hide the revision button.

FIX: Endless loading post history

---

spec/support/service_matchers.rb

This is a follow-up of d749227e87bfc5df96a5b2fbace7601a83351633.
This PR checks if the key `not_found` is present on the result object instead of calling `#blank?` on the model, as it can trigger an `ActiveRecord` relation.

DEV: Fix RSpec service matchers when a model is not found

---

lib/version.rb

Version bump for stable: v3.3.1

---

app/assets/stylesheets/common/components/topic-map.scss

UX: fix spacing in topic map views menu

---

config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
lib/post_revisor.rb
spec/lib/post_revisor_spec.rb

Reverts discourse/discourse#28321
it turns out this was not solved _yet_
this relates to this: https://github.com/discourse/discourse-chat-integration/pull/214 as well

Fix: revert removal of create_post_for_category_and_tag_changes setting"

---

app/assets/javascripts/discourse/app/components/composer-editor.js

DEV: Fix an `on` import deprecation

---

app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/select-kit/addon/components/toolbar-popup-menu-options.js

We were applying it separately on each part of the shortcut when it needs to be applied once on the whole shortcut.

FIX: correctly apply translate mod key

---

spec/lib/guardian/flag_guardian_spec.rb
spec/serializers/flag_serializer_spec.rb

Because of caching, whenever flags are created, they have to be destroyed to not modify the state.

FIX: Flaky flags spec

---

app/assets/javascripts/discourse/app/components/ace-editor.gjs
app/assets/javascripts/discourse/tests/integration/components/ace-editor-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/code-test.gjs

Why all the manual setting of `width` and `height`? Without it all ace editors were 0x0, invisible.
Why didn't it affect the tests before? ace-editor tests only confirms that there is an element, theme-settings-editor tests were effectively unit tests before 7317b5a, fk-code test avoids interacting with ace.

DEV: Await for ace render in tests

---

app/assets/javascripts/discourse/app/components/edit-category-tab.js
app/assets/javascripts/discourse/app/components/group-post.js

I mistakenly replaced these with `@equal`, thinking the behavior was the same. It's not. `@propertyEqual` compares two properties, while `@equal` compares a single property with a constant.

FIX: Restore `propertyEqual` following native-class conversions

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/checkbox.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/checkboxes.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/dropdown.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/image-previews/generic.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/image-previews/logo-small.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/image-previews/logo.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/image.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/-homepage-preview.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/-preview-base.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/index.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/text.js

DEV: Convert wizard components to native class syntax

---

app/assets/javascripts/discourse/app/controllers/user-activity-bookmarks.js
app/assets/javascripts/discourse/app/templates/user/bookmarks.hbs
spec/system/page_objects/pages/user_activity_bookmarks.rb
spec/system/user_activity_bookmarks_spec.rb

We were not updating `searchTerm` when changing the input which was making us always send an empty q parameter.
This commit is also adding tests for:
- initial url with q param
- filtering the bookmarks through the input

FIX: correctly filter user bookmarks

---

app/services/user_activator.rb
app/services/user_authenticator.rb
spec/services/user_authenticator_spec.rb

In this PR we introduced a new setting `enforce_second_factor_on_external_auth` which disables enforce 2FA when the user is authenticated with an external provider.
https://github.com/discourse/discourse/pull/27506
However, with the first registration with an external provider, we authenticate the user right after activation. In that case, we need to also keep information that the user was authenticated with an external OAuth provider to potentially skip 2FA (when  `enforce_second_factor_on_external_auth` is false).

FIX: do not enforce 2fa when an account is created with OAuth

---

.github/workflows/tests.yml

This regressed in b83a2a34a4cb303b5b4936a325d93e1c63f5d214 because the
Github actions docs doesn't make it clear that `runner.name` is actually
the runner's name plus some unique string appended at the end. Why they
would do that is beyond me.
This is an example cache key without this fix: `ubuntu-22.04-8core_402c36492b1a- 3823af50517f70be1da4e4be845b1eb7dbf5816d06d185c7e3a26f1f67471a83- d93984824c3f1b6961dfd9538cb8cde3024d3c18c7a5e7dd62c8312291eaf3ff- 7a3af9a582fe31b60784143841031476cd4a50960f16e060adfddd69c201efd7- true`. See how `_402c36492b1a` is appended to `ubuntu-22.04-8core`.

DEV: Fix app-cache regression in tests workflow

---

.github/workflows/tests.yml

This is a follow-up to 8adc484804f67672cbed82dcdf4f2615e8831af9

DEV: Fix app-cache key not considering number of parallel database

---

app/assets/stylesheets/common/modal/login-modal.scss

The class `login-right-side` is more reliable since it's in the template itself instead of being injected.

FIX: Use `.login-right-side` instead of `.has-alt-auth`

---

config/routes.rb

The name `/theme-qunit` comes from the days when we served the main qunit tests at `/qunit`. Nowadays, with ember-cli, the core tests are on `/tests`, so `/theme-tests` makes more sense, and might be what people think to try.
Changing the name would be a fairly large refactor. But we can add a redirect very easily.

DEV: Redirect `/theme-tests` to `/theme-qunit`

---

app/jobs/base.rb

Introduce a new log line for Sidekiq jobs that consume more than `DISCOURSE_LIVE_SLOTS_SIDEKIQ_LIMIT` live slots. This is useful to track down jobs that may leak memory.
This is enabled only when Sidekiq's job instrumenter is enabled (set `DISCOURSE_LOG_SIDEKIQ` to `1`).

DEV: Log live slots of Sidekiq jobs

---

app/views/layouts/ember_cli.html.erb

This was throwing the "Discourse does not support compiling scss/sass files via Sprockets" error if the file was not cached

DEV: Stop using sprockets for 'use ember cli' stylesheet

---

app/models/about.rb
app/models/concerns/stats_cacheable.rb
spec/models/about_spec.rb

Prior to this fix we were calling `fetch_stats` which is never checking if we have a cache entry. This call is making a lot of SQL calls, so it's better to use the cache.
This commit also adds a spec and a way to clear the cache of a model using `stats_cacheable`.

FIX: ensure About#stats uses the cache

---

lib/tasks/docker.rake

`ember exam` points all browsers at a single ember-cli server process. With very high parallelism, we've started seeing `ChunkLoadError` exceptions, which may indicate the server being overloaded. Capping to 8 browsers to avoid that.

DEV: Cap qunit concurrency at 8 browsers

---

plugins/automation/spec/triggers/topic_tags_changed_spec.rb

The following test is flakey. We don't care about the order because we check if the tags are being sent.
```
Failure/Error: measurement = Benchmark.measure { example.run }
expected: ["tag4", "tag5"]
got: ["tag5", "tag4"]
(compared using ==)
```

FIX: change `eq` to `match_array` in `topic_tags_changed_spec.rb` to solve flaky test

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-message-emoji-picker.gjs
plugins/chat/assets/javascripts/discourse/components/chat-emoji-picker.js

Removes chat-specific changes from dfc947a97dd37d5ec58e1c971a9a2285429dd98d, and adds `preventScroll: true` to prevent timing issues between the emoji picker being brought into the viewport and being focussed.

FIX: Chat emoji picker positioning

---

app/models/external_upload_stub.rb
lib/external_upload_helpers.rb
spec/jobs/clean_up_uploads_spec.rb

* Do not delete created external upload stubs for 2 days
instead of 1 hour if enable_upload_debug_mode is true,
this aids with server-side debugging.
* If using an API call, return the detailed error message
if enable_upload_debug_mode is true. In this case the user
is not using the UI, so a more detailed message is appropriate.
* Add a prefix to log messages in ExternalUploadHelpers, to
make it easier to find these in logster.

DEV: Improve external upload debugging

---

app/assets/javascripts/discourse/app/components/login-buttons.js

This adds a `multiple` class when there is more than one login method. This is needed in a plugin for styling.

DEV: Add 'multiple' class to login-buttons when there are multiple btns

---

config/initializers/006-mini_profiler.rb

FIX: Mini-profiler CSP nonce when in report-only mode

---

app/assets/javascripts/discourse/ember-cli-build.js

This will avoid warnings: "The code generator has deoptimised the styling of {path} as it exceeds the max of 500KB."
Should also provide a tiny improvement in build times

DEV: Skip babel for ace-builds and json-editor

---

app/assets/javascripts/discourse/app/instance-initializers/banner.js
app/assets/javascripts/discourse/app/instance-initializers/live-development.js
app/assets/javascripts/discourse/app/instance-initializers/logout.js
app/assets/javascripts/discourse/app/instance-initializers/read-only.js
app/assets/javascripts/discourse/app/instance-initializers/subscribe-user-notifications.js
plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js

We're working to remove all decorators from object-literal-properties. This commit refactors all initializers which were using these decorators into classes, where decorators are allowed. Also adds cleanup logic to the local-dates initializer, which was previously missing.

DEV: Refactor complex initializers into classes

---

app/assets/javascripts/admin/addon/components/modal/edit-badge-groupings.hbs
app/assets/javascripts/admin/addon/routes/admin-badges.js
app/assets/javascripts/admin/addon/routes/admin-badges/show.js
app/assets/javascripts/admin/addon/templates/admin-badges.hbs
spec/system/admin_badges_grouping_modal_spec.rb
spec/system/page_objects/admin_badges.rb
spec/system/page_objects/admin_badges_groupings.rb

A previous refactor has moved this function in the controller instead of the route making it inaccessible to the modal.
This commit is fixing this and also adding a spec.

FIX: correctly pass updateGroupings to the modal

---

app/assets/javascripts/discourse/app/form-kit/lib/validator.js
app/assets/javascripts/discourse/tests/unit/lib/form-kit/validator-test.js

Prior to this fix `0` would be required as non-existing and would raise the required error.

FIX: ensures default required validator handles 0

---

plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/spec/fabricators/user_global_notice_fabricator.rb
plugins/automation/spec/lib/discourse_automation/event_handlers_spec.rb

Prior to this fix we could exit early if tags was `[]` as `tags && (tags & post.topic.tags.map(&:name)).empty?` would have returned true. This commit ensures it's not the case anymore and adds a test for it.

FIX: ensures global notices are destroyed on post created

---

app/assets/javascripts/admin/addon/components/admin-config-areas/flags-settings.gjs
app/controllers/admin/config/site_settings_controller.rb
app/models/site_setting.rb
config/site_settings.yml
lib/site_setting_extension.rb
plugins/chat/config/settings.yml
spec/lib/site_setting_extension_spec.rb
spec/requests/admin/config/site_settings_controller_spec.rb
spec/system/admin_flags_spec.rb

A new setting attribute is used to define areas (separated by `|`).
In addition, endpoint `/admin/config/site_settings.json` accepts new `filter_area` data.

DEV: the ability to define setting areas

---

app/assets/stylesheets/common/base/about.scss
app/assets/stylesheets/common/base/faqs.scss

UX: Adjustments for the about page banner image

---

app/assets/javascripts/discourse/app/components/navigation-item.js
app/assets/javascripts/discourse/tests/integration/components/navigation-bar-test.gjs

Originally, we assumed that the href passed to the NavigationItem must not have URLParams, and roughly appended URLParams such as `?order=created` to the end. This will result in something like `/latest?state=my_votes?order=created` (note the double question mark here), for example the discourse-topic-voting plugin
This commit modifies the logic for appending URLParams to the end, ensuring that the original URL parameters are preserved.
meta topic: https://meta.discourse.org/t/-/324436

FIX: Keep the original URLParams in navigation item

---

lib/search.rb
spec/lib/search_spec.rb

Currently, when the default locale is Japanese, the search for a topic using its URL, path or ID doesn’t work as expected. It will either return wrong results or no result at all.
The problem lies with how we process the provided terms in Japanese mode. For example, if `http://localhost/t/-/55` is provided, currently this will result in `http localhost t 5 5` to be searched for.
This PR addresses the issue by checking whether the provided term needs segmenting. If the provided term is a number, or a path or a full URL, then it doesn’t need segmenting. When that happens, we skip the processing we normally apply for Japanese, making the search return the expected results.

FIX: Return proper results when searching for a topic in Japanese

---

app/models/group.rb
config/locales/server.en.yml
config/site_settings.yml
lib/has_errors.rb
lib/topic_creator.rb
spec/lib/topic_creator_spec.rb
spec/models/group_spec.rb

This commit introduces a new hidden site setting: `group_pm_user_limit`, default to `1000` which will raise an error when attempting to create a PM target a large group.

FIX: prevents PM to large groups

---

app/assets/javascripts/discourse/app/components/about-page.gjs

The old /about page has 3 plugin outlets: one after the description, one after the admins list, and one after the mods list. These outlets translate cleanly to the new /about page, so we should add them to it to make plugins/themes compatible with the new page.

DEV: Add `PluginOutlet`s from the old /about page to the new one

---

package.json
pnpm-lock.yaml

Workaround for https://github.com/dependabot/dependabot-core/issues/10124

DEV: Use blob URL to install discourse/squoosh fork

---

app/assets/javascripts/discourse/app/components/modal/login.js
app/controllers/session_controller.rb
spec/requests/session_controller_spec.rb

FIX: Passkey login when Discourse used as SSO provider

---

lib/tasks/plugin.rake

The recorded runtime log was specified when running the plugin specs, but it failed to match the entries from the runtime log and the passed as command line arguments because the runtime log entries were not prefixed with `./`.

DEV: Use recorded runtime log for plugin specs

---

app/assets/javascripts/discourse/app/components/topic-navigation.js

Reported here: https://meta.discourse.org/t/timeline-bug-on-mobile-video-attached/323633
This regards the expanded timeline on mobile. When the timeline is dragged and the post changes, the timeline doesn't fully auto-close
What seems to happen, is that the postId is passed in from the topic controller like this:
`this.appEvents.trigger("topic:jump-to-post", postId);`
and in topic-navigation, the id is mistakenly used as the delay... so in cases like Meta where post ids are high the delay is very long (20+ minutes) and the expanded timeline appears stuck open
this avoids the issue by setting up a separate postId param

FIX: don't use post ID as timeline collapse delay

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/components/form-template-field/wrapper.gjs

Avoid the flashing red bar when loading a form template.
The ajax call to retrieve the form template yaml and then load it into fields could be made sooner, but that can be handled separately.

UX: avoid flashing error when loading form template

---

app/assets/javascripts/discourse/app/components/card-contents-base.js
app/assets/javascripts/discourse/app/components/group-card-contents.js
app/assets/javascripts/discourse/app/components/user-card-contents.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js

This allows us to convert it to native class syntax
Mixins are essentially deprecated, and will not be receiving native class syntax support. In this case, there is no real need for it to be a mixin, so a base class makes sense.

DEV: Convert card-contents-base from mixin to base class

---

.github/workflows/tests.yml

Base image no longer ships with Chromium so no need to remove it

DEV: Remove redundant step in tests workflow

---

app/models/web_hook.rb
app/models/web_hook_event_type.rb
config/locales/client.en.yml
db/fixtures/007_web_hook_event_types.rb

'Post approved by category experts' is moved to the post category:

DEV: Approved Post Webhook Event Category Update

---

plugins/chat/app/models/chat/direct_message.rb
plugins/chat/assets/javascripts/discourse/components/chat/composer/channel.js
plugins/chat/config/locales/client.en.yml
plugins/chat/spec/models/chat/direct_message_spec.rb
plugins/chat/test/javascripts/components/chat-composer-placeholder-test.js

This change improves the formatting of chat group names by doing the following:
- removes system users from the usernames in DM channel title
- simplifies the placeholder text for the chat composer to be "Chat in group"
- shows up to 7 usernames in full, if more then it shows 6 + N others

UX: Update Chat Group Name and Placeholder

---

lefthook.yml

On pre-commit, various people were getting an error like this:
> ERR_PNPM_NO_SCRIPT Missing script: ember-template-lint
This was because in our lefthook config we were doing
`pnpm run ember-template-lint` rather than the correct
`pnpm ember-template-lint`

DEV: pnpm ember-template-lint should not use run command

---

plugins/chat/assets/stylesheets/common/core-extensions.scss

Removes unused CSS that was a temporary fix for a new notification type that was later reverted.

DEV: remove CSS for consolidated DM notifications

---

app/assets/javascripts/discourse/app/controllers/about.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/templates/about.hbs
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
lib/plugin/instance.rb
plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js
plugins/chat/plugin.rb

We need to start printing deprecation notices when the `show_in_ui` argument is used because it works only for the old about page which will be removed soon. For the new about page, we've introduced a new API `addAboutPageActivity` which is more flexible than a true/false argument on the server side.
Internal topic: t/136551.

DEV: Deprecate `show_in_ui` argument of the `register_stat` API

---

config/site_settings.yml

This hidden setting will allow us to roll out changes
to pageview UIs and reporting in a controlled way.

DEV: Introduce legacy pageviews flag

---

app/assets/stylesheets/common/base/faqs.scss

Static pages such as /about, /faqs, /tos etc. currently overflow horizontally on some Android devices (reproducible on Samsung Galaxy A11). It seems like the `width: 100%` property on `.body-page` is what causing the problem, and removing it doesn't seem to break anything on the various devices that I've tested (desktop, iOS, Android).
Before:
After:

FIX: Don't let static pages overflow on some devices

---

plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/topic_tags_changed.rb
plugins/automation/spec/triggers/topic_tags_changed_spec.rb

`topic_tags_changed` trigger now fills the {{topic_url}} and {{topic_title}} placeholders. `topic_url` is the relative URL.

DEV: adds topic_url/topic_title placeholders

---

plugins/automation/app/controllers/discourse_automation/admin_automations_controller.rb
plugins/automation/spec/system/new_automation_spec.rb
plugins/automation/spec/system/page_objects/discourse_automation/new_automation.rb

This commit ensure we are properly showing an error to the end user and not just a vague 500.

FIX: creating an automation without script should error

---

plugins/chat/assets/javascripts/discourse/components/channel-name/index.gjs
plugins/chat/assets/javascripts/discourse/components/channel-title/index.gjs
plugins/chat/assets/javascripts/discourse/components/chat-channel-metadata.gjs
plugins/chat/assets/javascripts/discourse/components/chat-channel-row.gjs
plugins/chat/assets/javascripts/discourse/components/chat/message-creator/channel.gjs
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js
plugins/chat/assets/stylesheets/common/chat-channel-name.scss
plugins/chat/assets/stylesheets/common/chat-channel-row.scss
plugins/chat/assets/stylesheets/common/chat-message-creator.scss
plugins/chat/spec/system/channel_settings_page_spec.rb
plugins/chat/test/javascripts/components/channel-name-test.gjs
plugins/chat/test/javascripts/components/chat-channel-metadata-test.js

This change increases the visibility of unread channels to make them stand out more in drawer mode (desktop).
When a channel is unread:
- it floats to the top;
- when multiple channels are unread, they are sorted alphabetically (equal to how it’s done on mobile)
- the unread indicator blue dot moves to directly right of the channel name
With unread messages:
With mentions or urgent messages:

UX: chat drawer increase unread channel visibility

---

plugins/chat/assets/stylesheets/common/chat-channel-name.scss

Fixes a small spacing bug with emoji in channel titles, this is a recent regression from #28731
With unread indicator:

UX: fix spacing of emoji in chat channel title

---

plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel-threads.gjs

Chat toggle relies on using a `height: auto` to collapse drawer, however in channel threads we should be only displaying threads when drawer is expanded. Displaying threads conditionally based on drawer toggle status fixes this.

FIX: toggle chat drawer on channel thread list

---

plugins/automation/config/locales/client.en.yml
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/post_created_edited.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb
plugins/chat/plugin.rb
plugins/chat/spec/plugin_spec.rb

On top of this the following changes have also been made:
- adds a new `original_post_only` option, to trigger only on OP
- adds a new `restricted_tags` option, to trigger only when these tags are present
- adds `topic_url` and `topic_title` placeholders to the trigger

DEV: adds post_created_edited suport to chat

---

plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js

Reverts chat channel sorting changes made in #28731 due to desktop sidebar.

UX: update chat channel sorting

---

docs/ADMIN-QUICK-START-GUIDE.md

This PR adds links to the checklist in the new quick start guide an admin will see when launching Discourse for the first time.

UX: Add links to getting started check list

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/your-organization.gjs

Updated to an info alert for clarity, as the message is informational, not critical.

UX: Change organization alert type from error to info

---

Gemfile
Gemfile.lock

New version disable concurrent GC sweeping in V8 it was a culprit for
segfaults we saw in production

DEV: another attempt upgrading mini_racer

---

app/assets/javascripts/admin/addon/components/admin-config-areas/about.gjs
app/assets/javascripts/admin/addon/templates/config-about.hbs

This commit updates the about config page to use the `AdminPageHeader` component, and includes the breadcrumbs.

UX: Apply the admin page header component

---

Gemfile
Gemfile.lock

This reverts commit 5c0c053b111c55207dad954afd312a26ff67e176.
This still segfaults, but not as frequently as before, we will keep this
for a few more hours and then revert

Revert "DEV: another attempt upgrading mini_racer (#28763)"

---

app/controllers/groups_controller.rb
app/jobs/scheduled/run_problem_checks.rb
app/models/admin_dashboard_data.rb
spec/jobs/run_problem_check_spec.rb
spec/models/admin_dashboard_data_spec.rb

We're now using the new, database-backed problem check system. This PR removes parts of the old, Redis-backed system that is now defunct.

DEV: Remove old problem check system - Part 1

---

app/assets/javascripts/discourse/app/components/about-page.gjs
config/locales/client.en.yml
spec/system/about_page_spec.rb
spec/system/page_objects/pages/about.rb

This PR adds a link to the top of the new /about page, shown to admins only, to allow them to easily navigate to `/admin/config/about` where they can edit the /about page.
Screenshot:
Internal topic: t/137546.

FEATURE: Add 'Edit this page' link at the top of the new /about page

---

Gemfile
Gemfile.lock

Now that we’re using Rails 7.1, we don’t need to have the `mutex_m` and `drb` gems explicitly listed in our Gemfile.

DEV: Remove unneeded dependencies

---

app/assets/javascripts/discourse/app/components/about-page.gjs
spec/system/about_page_spec.rb
spec/system/page_objects/pages/about.rb

This PR adds the footer that currently exists on the old /about page to the new one.

FIX: Add traffic info footer to the new /about page

---

plugins/automation/admin/assets/javascripts/admin/components/automation-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-groups-field.gjs
plugins/automation/app/models/discourse_automation/field.rb
plugins/automation/config/locales/client.en.yml
plugins/automation/db/migrate/20240906091215_update_fields_for_post_created_edited_trigger.rb
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/post_created_edited.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb
plugins/automation/test/javascripts/integration/components/da-groups-field-test.js

To achieve it, this commit does the following:
- create a new `groups field, ideally we would have reused the existing group field, but many automations now have the expectation that this field will return a group id and not an array of group ids, which makes it a dangerous change
- alter the code in `post_created_edited` to use this new groups field and change the logic to use an array
- migrate the existing group fields post_created_edited automations to change name from `restricted_group` to `restricted_groups`, the component from `group` to `groups` and the metadata from `{"value": integer}` to `{"value": [integer]}`

FIX: supports groups field in post_created_edited

---

lib/plugin/instance.rb
spec/lib/plugin/instance_spec.rb

This was added 10 years ago, but currently there's not a single use in our public and private plugins and no reference in third-party plugins on github

DEV: Remove `register_color_scheme` api

---

lib/search.rb
spec/lib/search_spec.rb

DEV: Forces custom search filter matchers to be case insensitive

---

app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.gjs

This adds a below-sidebar-sections plugin outlet to the dropdown version of the sidebar, to match the outlet in the default sidebar (in sidebar.hbs)

DEV: add below-sidebar-sections to sidebar dropdown mode

---

plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js

This makes local-dates compatible with the fa6 upgrade in https://github.com/discourse/discourse/pull/28778

DEV: Use icon-rendering API for local-dates

---

plugins/chat/assets/javascripts/discourse/components/chat-thread-tracking-dropdown.js

The bell dropdown here:
gets the `.btn-default` class from select-kit, but it's not styled like a default button like this:
so that class only serves to get in the way of theming and should be removed — fortunately that's what `customStyle` does

UX: remove btn-default class from chat thread tracking dropdown

---

Gemfile
Gemfile.lock

The latest node 22.7.0 based release of mini_racer disabled
Maglev (https://v8.dev/blog/maglev) based optimisations
From previous segfaults it appears the failures happened in the maglev code
paths.
Node release of v8 lags latest release of v8 so, whatever is happening, may
be resolved in latest.

DEV: update mini_racer to latest

---

docs/ADMIN-QUICK-START-GUIDE.md

Followup e7d80cf762c8b8a1aa14260a6e3df046dc2fee80,
a slash was missing for the wizard link

UX: Fix wizard link in getting started guide

---

db/fixtures/003_flags.rb

There was a bug report on meta that after deployment, some topics were not loaded properly for 24 hours - https://meta.discourse.org/t/endless-spinner-on-some-posts/323031/17
In this PR we moved the `like` post action type to the database - https://github.com/discourse/discourse/pull/28362
However, flags are cached for performance reasons https://github.com/discourse/discourse/blob/main/app/serializers/site_serializer.rb#L113
After seed, we should ensure that the cache is reset so the site has access to all post-action types.

FIX: reset cache after flags are seed

---

lib/svg_sprite.rb

I think this is a typo in the font awesome documentation, they list `shield-blank` but it should be either `shield` or `shield-halved` in the FA6 renames 
follow-up to 7d8974d

FIX: replace shield-blank with shield-halved for Font Awesome

---

lib/file_store/to_s3_migration.rb

Previously we were opening the file handles, then putting them in a queue for upload. If that queue grows too large, we can hit a maximum open files limit.
This commit opens the file handle 'just in time', so the maximum number of open handles is equal to the upload concurrency (20).

FIX: Open file handles 'just in time' during s3 migration

---

app/assets/javascripts/admin/addon/templates/config-flags.hbs

Docs are published now at https://meta.discourse.org/t/moderation-flags/325589

UX: Add learn more URL for admin flags page

---

app/assets/javascripts/admin/addon/components/admin-report.js
app/assets/javascripts/admin/addon/controllers/admin-reports-show.js

Followup 14b436923c5b582cea454b69441a28e16f2f191e
On the standalone Site Traffic report page, we also need
to hide the 'other' and 'crawler' pageviews by default
like we do on the admin dashboard.

UX: Hide 'other' and 'crawler' site traffic on report page

---

app/assets/stylesheets/mobile/float-kit/d-menu.scss

On occasion the focus-visible style is activated when opening the list-control menu on mobile. This commit prevents this style from being visible. While it's important to adhere to accessibility guidelines, the focus state on a touch device is of minor importance, since traditionally no keyboard navigation is being used.

UX: prevent a focus-visible outline on mobile

---

plugins/chat/assets/javascripts/discourse/services/chat-notification-manager.js

On occasion we get an error popup on desktop due to the channel not being found.
This change means that we only check the cached channels in ChatChannelsManager for the matching channel id, but we skip doing manual lookup which results in ajax popup when it fails.

FIX: prevent chat channel not found ajax error

---

Gemfile.lock

The update introduced a small regression in d-data-explorer that was handled in https://github.com/discourse/discourse-data-explorer/pull/326

DEV: Update test-prof from 1.4.1 to 1.4.2

---

app/models/about.rb
config/locales/server.en.yml
config/site_settings.yml
spec/models/about_spec.rb

This PR adds a new `about_page_hidden_groups` setting to exclude members of specific groups from the admin and moderator lists on the /about page.
Internal topic: t/137717.

FEATURE: Add setting to exclude groups from /about page

---

plugins/poll/app/models/poll.rb
plugins/poll/app/models/poll_option.rb
plugins/poll/app/serializers/poll_option_serializer.rb
plugins/poll/app/serializers/poll_serializer.rb
plugins/poll/plugin.rb
plugins/poll/spec/models/poll_spec.rb
plugins/poll/spec/requests/topics_controller_spec.rb

These fields are often used when serializing topics which may contain multiple polls. On average, serializing a poll took 2+N queries where N is the number of options. This change reduces the number of queries to 3, one for each field (Poll#voters_count, PollOption#voters_count and Poll#has_voted?).

PERF: Preload voters_count and has_voted

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/stylesheets/common/base/about.scss

**What's changed:**
- Updated the banner to be fully responsive. Now it scales properly and keeps its aspect ratio, so it looks good on any screen
- Used object-fit: cover; to make sure the image covers the entire container, even if it's not ideally sized
- The banner container now adjusts its height based on its width, so it stays proportional no matter the device
- Not related to banner image, but removed icons preceding “Our Admins” and “Our Moderators”
**Why?**
This makes sure the banner images look great everywhere, whether they're wide, narrow, short, or tall. It helps maintain a consistent look and feel across different screens.
**Testing:**
- Check various screen sizes to ensure everything scales nicely
- Verify that images fit the container without major distortion

UX: Update banner to handle image with aspect ratio scaling

---

plugins/automation/config/settings.yml
plugins/automation/lib/discourse_automation/triggers/recurring.rb

We're seeing a problem where some recurring automations end up in a state where they don't have any `pending_automations` records scheduled which effectively makes the recurring automation dead. We need to add some debugging to figure out what might be causing this problem.
Internal topic: t/138045.

DEV: Add debug logging for automation recurring trigger

---

spec/system/page_objects/pages/about.rb

CSS selectors were changed in https://github.com/discourse/discourse/commit/995931b6ec83ffbb2787eae16b9c232e3cdca09a so we need to update system specs as well.

DEV: Fix the build on github

---

lib/tasks/assets.rake

We were running into errors running `ember build` on machines with high
CPU counts. It was then noted that `thread-loader`, which embroider uses, defaults to spinning
up x workers where x is number of physical CPU cores - 1. That is
probably too much so we set out to find out an optimal count to set for
the `JOBS` env which embroider uses to set the number of
`thread-loader` workers.
I first built an image using the following Dockerfile.
```
FROM discourse/base:release
RUN cd /var/www/discourse && sudo -EH -u discourse bundle exec rake plugin:install_all_official
RUN cd /var/www/discourse && sudo -EH -u discourse bundle exec rake assets:precompile:prereqs
```
I then ran the following command on my M3 Max Macbook Pro that has 14
phyisal CPU cores.
```
for j in 1 2 4 8 14; do echo …
```

DEV: Cap number of `thread-loader` workers in `assets:precompile:build`

---

spec/models/report_spec.rb

The Report model spec was directly adding methods
to the Report class, which was causing errors in the admin reports controller because it would look for a translation of the report name (e.g. report_timeout_test) like so `I18n.t("reports.#{type}.title")`, then get an error because the translation did not exist.
This is fixed by using `Report.stubs` instead, which is cleaned up after every test.

DEV: Fix report flakys

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
app/models/flag.rb
config/locales/client.en.yml
spec/lib/post_action_type_view_spec.rb
spec/models/flag_spec.rb
spec/models/post_action_spec.rb
spec/system/admin_flags_spec.rb

Currently, when the custom flag has the same name as the system flag (which is disabled) then it is not displayed. To fix the problem, `custom_` prefix as `name_key` is used to distinguish between the system and the custom flag.
I considered writing a migration to fix existing custom flags name key. However, at the end of migration I would need to run rails code to reset cache `Flag.reset_flag_settings!`. I decided to skip that step as it is a very edge case. If someone has the same flag name as the system flag, then all they have to do is edit the flag and click save.
In addition, I made 2 small fixes:
- edit flag title was missing translation;
- flag form UI was not showing that description is the required field.

FIX: use a custom prefix for custom flags

---

lib/mini_sql_multisite_connection.rb
plugins/poll/spec/requests/topics_controller_spec.rb
spec/support/helpers.rb

`track_sql_queries` only returned queries that were executed by
ActiveRecord. All queries executed through DB.exec, DB.query and others
were not returned.

DEV: Track SQL queries from MiniSql

---

lib/topic_view.rb
spec/requests/topics_controller_spec.rb

The user option 'hide_profile_and_presence' is necessary to figure out
if the user status has to be displayed or not. In order to avoid N+1s
generated by `include_status?` method, both `user_status` and
`user_option` relations have to be included.

PERF: Preload user options when status is enabled

---

lib/tasks/qunit.rake

that is: randomize the order in which theme test suites are scheduled

DEV: Run theme tests in random order

---

.github/workflows/tests.yml

This seems to mitigate the flaky timeouts we've been seeing recently, while not affecting the speed in any meaningful way.

DEV: Change qunit_parallel to 2 for frontend themes

---

Gemfile

Added in 7c3a29c, broke Dependabot parsing.

DEV: Remove dynamic inclusions from Gemfile

---

package.json

For people with corepack enabled, this causes problems when trying to `yarn install` in plugin directories.
Perhaps that can be improved in future by adding `packageManager` config in each plugin's own `package.json`, but that won't happen overnight. Removing the config for now to stop the bleeding.

DEV: Remove corepack config for now

---

.github/pull_request_template.md

So that it fits better in the Github UI.

DEV: Shorter PR draft template

---

app/assets/javascripts/discourse/app/components/navigation-bar.gjs
app/assets/stylesheets/mobile/list-controls.scss

This commit fixes the double li-element present in the list-control DMenu, introduced by #28324

UX: fix double li-element in mobile list control

---

app/models/report.rb
spec/lib/plugin/instance_spec.rb

Followup 0323b366f3023843468d1024135bbb1c7c6f0483
This was happening because another spec was adding a
report using the plugin API, but there was nothing
resetting that, so later in the reports controller
when we did Report.singleton_methods, we ended up
with another report with no translation, causing another
error.

DEV: Fix another report flaky

---

spec/system/page_objects/components/form_kit.rb

Adds support for `input-date` field when calling
`fill_in` on a FormKit field. Capybara supports passing
a Date object to `fill_in(with: value)` for date inputs,
so there is nothing fancy that needs to be done to support this.

FIX: Support date field in FormKit page object

---

app/assets/stylesheets/common/admin/admin_report.scss

Followup 5a8e7c5f29b21fe3465dd0db48026075e6c4b274
The admin report results need to be side by side
with the filter for the report, which sits on the
right. The previous commit made it stacked.

UX: Fix admin report filter stacking

---

app/assets/javascripts/discourse/app/components/reviewable-item.hbs
app/assets/javascripts/discourse/app/components/reviewable-item.js
app/assets/stylesheets/common/base/reviewables.scss

Previously for reviewables that could be claimed, we positioned
the "you can claim / you must claim" message and button underneath
the "Is there something wrong with this post?" message but _before_
the reviewable action buttons like Yes/No/Ignore. This was a confusing
flow.
This commit fixes the issue, and also makes it so if claiming is
required and the reviewable has not been claimed, we don't show
the "Is there something wrong with this post?" which was showing
with no buttons.
**Optional claiming**
**Required claiming**

UX: Fix confusing "claim reviewable" positioning

---

.pnpmfile.cjs

DEV: Automatically add `--ignore-workspace` when pnpm used in plugins

---

config/locales/client.en.yml

made sidebar links to "security settings" and "spam settings" unambiguous.

updated sidebar links to security settings and spam settings

---

lib/statistics.rb
spec/lib/statistics_spec.rb

The user directory (`/u`) excludes inactive and silenced users from the list, so for the sake parity, it makes sense to also exclude those users from the /about page stats.
Internal topic: t/70928.

FIX: Exclude inactive and silenced users from /about page stats

---

spec/system/admin_flags_spec.rb

Recently `custom_` prefix was added for flags https://github.com/discourse/discourse/pull/28839
When we wait to ensure that `Tasteless` flag is deleted, we need to use new prefix as well.

FIX: flaky system admin flags specs

---

.github/workflows/labeler.yml
.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/release-notes.yml
.github/workflows/stale-pr-closer.yml
.github/workflows/tests.yml

The self-hosted Github runners have been provisioned, and we can switch to using them for evaluation.
To prefer Github-hosted runners, you can safely revert this commit.
See: t/123181.

DEV: update runners to debian-12

---

app/models/user.rb
app/models/user_search.rb
config/site_settings.yml
db/migrate/20240912061702_drop_user_search_similar_results_site_setting.rb
db/migrate/20240912061806_drop_trgm_indexes_on_users.rb
spec/models/user_search_spec.rb

In 14cf8eacf1a679c08ea7df93aff17949d1a9c4df, we added the
`user_search_similar_results` site setting which when enabled will use
trigram matching for similarity search in `UserSearch`. However, we
noted that adding the `index_users_on_username_lower_trgm` index is
causing the PG planner to not use the `index_users_on_username_lower`
index when the `=` operator is used against the `username_lower` column.
Based on the PG mailing list discussion where support for the `=`
operator in gist_trgm_ops was being considered, it stated that "I also have checked that btree_gist is preferred over pg_trgm gist
index for equality search." This is however quite different from reality
on our own PG clusters where the btree index is not preferred leading to
significantly slower queries when the `=` …

PERF: Drop `user_search_similar_results` site setting

---

plugins/chat/assets/stylesheets/common/chat-composer.scss
plugins/chat/assets/stylesheets/mobile/chat-composer.scss

The chat composer focus state on mobile and desktop had diverted. This commit updates the desktop focus state to fall in line. It's  less harsh than before and no longer relies on box-shadow, which doesn't work well in dark mode anyway. Additionally, it incorporates the `tertiary` colour, which is used elsewhere too to indicate focus.
| <img width="756" alt="CleanShot 2024-09-13 at 14 15 26@2x" src="https://github.com/user-attachments/assets/2eac76bd-e31e-4d01-92d2-dd8be2294807"> | <img width="756" alt="CleanShot 2024-09-13 at 14 14 29@2x" src="https://github.com/user-attachments/assets/92b80cc5-80b5-4b00-aade-f860dd7e8b5c"> | 
| <img width="756" alt="CleanShot 2024-09-13 at 14 15 09@2x" src="https://github.com/user-attachments/assets/ddbbf7d5-cccb-45 …

UX: update stying of chat composer focused state

---

.github/workflows/labeler.yml
.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/release-notes.yml
.github/workflows/stale-pr-closer.yml
.github/workflows/tests.yml

docker.io rate limits _should_ be addressed now. Switch back to
`debian-12` runners.
This is now a conditional within the `tests` workflow as we evaluate the
migration.
This reverts commit a99e2c62e64e5d61fd99ef97b58657cde389a3b2.

Reapply "DEV: update runners to debian-12"

---

app/models/directory_item.rb
db/post_migrate/20240912210450_delete_anonymous_users_from_directory_items.rb
spec/models/directory_item_spec.rb

Anonymous users are "shadow" users created when an existing real user desires to post anonymously. This feature is off by default, but it can be enabled via the `allow_anonymous_posting` site setting. Those shadow users shouldn't be included in the users directory (`/u`).

FIX: Remove anonymous users from users directory

---

app/assets/javascripts/discourse/app/templates/group/manage/tags.hbs
app/models/group_tag_notification_default.rb
spec/models/group_spec.rb

An error will pop up when switching the default tag notification state for a group. This also happened if you attempted to set the same tag to two notification levels at a time. The UI no longer allows this

FIX: Error when moving the group default notification state

---

Gemfile
Gemfile.lock

This is attempt 4 or 5. This time we compiled libv8-node using clang vs gcc.
The working theory is that something may be off with the gcc compile.

DEV: attempt a mini_racer upgrade

---

Gemfile
Gemfile.lock

This reverts commit dc8620a491b83a6ef942f1ab4451f2807c5ebbe5.
Still segfaulting - missing artifact for ARM darwin

Revert "DEV: attempt a mini_racer upgrade (#28924)"

---

app/controllers/topics_controller.rb
lib/guardian/topic_guardian.rb
spec/lib/guardian_spec.rb

In TopicController, in addition to ensure_can_move_posts!, we also checked if the topic is private message in this line:
```ruby
raise Discourse::InvalidAccess if params[:archetype] == "private_message" && !guardian.is_staff?
```
However, this was not present in `guardian.can_move_posts?`. As a result, the frontend topic view got an incorrect serialized result, thinking that TL4 could move the private message post. In fact, once they tried to move it, they got the `InvalidAccess` error message.
This commit fixes that TL4 will no longer sees the "move to" option in the "select post" panel for a private message.
ref=/t/133860
Screenshot:

FIX: Don't show move topic for private messages for TL4

---

app/assets/javascripts/discourse/app/components/ace-editor.gjs
app/assets/javascripts/discourse/app/instance-initializers/hashtag-css-generator.js
app/assets/javascripts/discourse/app/instance-initializers/webview-background.js

1. `MediaQueryList.addListener` is deprecated in favor of `addEventListener`
2. `HTMLStyleElement.type` is deprecated with no replacement

DEV: Fix some js deprecations

---

.github/workflows/tests.yml

Seeing errors like the following which is normally due to us running
too many processes.
```
not ok 292 Firefox - [undefined ms] - error
---
message: >
Error: Browser timeout exceeded: 10s
Error while executing test: Acceptance: Uppy Composer Attachment - Multiple Upload Errors: should show a consolidated message for multiple failed uploads
Stderr:
*** You are running in headless mode.
Stdout:
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: No GPUs detected via PCI
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
```

DEV: Reduce number of parallel processes for frontend tests

---

plugins/chat/assets/stylesheets/common/chat-composer-dropdown.scss

Mini follow up for https://github.com/discourse/discourse/pull/28900

UX: small colour change to chat composer insert button

---

app/models/user.rb
spec/models/user_spec.rb

Back port of #28541 to stable.
This check was checking the wrong scope, causing problems in certain edge conditions, for example:
1. Admin adds an "on signup" field that isn't editable after signup.
2. Admin adds a "for all users" field.
3. User goes and fills up the "for all users" field from 2.
4. User is now stuck on the required fields page without any fields showing.
With this change, we only consider "for all users" fields when asking if required custom fields are filled in.

FIX: Fix incorrect check for required custom fields (stable)

---

app/assets/javascripts/admin/addon/components/admin-notice.gjs
app/assets/javascripts/admin/addon/components/dashboard-problems.gjs
app/assets/javascripts/admin/addon/controllers/admin-dashboard.js
app/assets/javascripts/admin/addon/templates/dashboard.hbs
app/assets/javascripts/discourse/tests/acceptance/dashboard-test.js
app/assets/stylesheets/common/admin/dashboard.scss
app/controllers/admin/admin_notices_controller.rb
app/models/problem_check_tracker.rb
app/serializers/admin_notice_serializer.rb
app/services/admin_notices/dismiss.rb
config/locales/client.en.yml
config/routes.rb
spec/fabricators/admin_notice_fabricator.rb
spec/models/problem_check_tracker_spec.rb
spec/services/admin_notices/dismiss_spec.rb
spec/system/admin_notices_spec.rb
spec/system/page_objects/pages/admin_dashboard.rb

This is a new feature that lets admins dismiss notices from the dashboard. This helps with self-service in cases where a notice is "stuck", while we work on provisions to prevent "sticking" in the first place.
**Screen capture:**
**Mobile layout:**
In terms of implementation, there's been some refactoring of the templates. In particular, the extraction of an `AdminNotice` component, and shifting of problem check related logic from `admin-dashboard.js` to `dashboard-problems.gjs`.
There's a lot of room for extension that is not part of this PR. An obvious issue here is if you dismiss a notice created by a real-time problem check, it will likely have been added back when you reload the dashboard.
Future improvements include:
- Ability to "snooze" notices.
- Ability to declare which notices …

FEATURE: Add ability to dismiss admin notices

---

app/models/translation_override.rb
db/post_migrate/20240711123755_drop_compiled_js_from_translation_overrides.rb

DEV: Drop unused column `translation_overrides.compiled_js`

---

app/assets/javascripts/discourse-common/addon/lib/raw-handlebars-helpers.js
app/assets/javascripts/discourse/tests/integration/helpers/raw-test.gjs

There is a risk of overriding and then deleting a prop for the context in case of a naming clash between localName and that prop, e.g.
```js
class Test {
item = "foo";
items = [1, 2];
}
const template = `
{{#each items as |item|}}
{{item}}
{{/each}}
`;
const compiledTemplate = compile(template);
const object = new Test();
// object.item === "foo"
const output = compiledTemplate(object, RUNTIME_OPTIONS);
// object.item === undefined
```
…but I think we can accept this risk and just be careful.`#each` isn't widely used in hbr anyway (as proven by the other long-standing and recently fixed bug) and hbr is on its way out anyway.

FIX: Support getters in hbr `#each` context

---

app/assets/stylesheets/common/base/topic-post.scss

Prior to this fix copy/pasting a text with mentions containing user status would paste the emoji name.

FIX: prevents user status selection in mentions

---

plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/spec/models/automation_spec.rb

Updates from 30 to 100 the maximum length of the name of an automation.
And adds tests for validating the maximum length of the name of an automation.

FEATURE: increasing name length in automation

---

docs/ADMIN-QUICK-START-GUIDE.md

This fixes one broken link, and updates the wording for a couple more.

Updating documentation links in admin quick start guide

---

app/jobs/scheduled/run_problem_checks.rb
app/models/problem_check_tracker.rb
spec/jobs/run_problem_checks_spec.rb
spec/models/problem_check_tracker_spec.rb

When running checks, we look to the existing problem check trackers and try to grab their `ProblemCheck` classes.
In some cases this is no longer in the problem check repository, e.g. when the check was part of a plugin that has been uninstalled.
In the case where the check was scheduled, this would lead to an error in one of the jobs.
This fix has two parts:
1. If a problem check tracker can't find it's `ProblemCheck` class, it destroys itself and any admin notices associated with it. It then returns `nil`.
2. The job that selects which checks to run now accounts for the fact that the `ProblemCheck` class could be `nil`, and filters it out of the run.
Bonus:
- Scheduled checks now honour the `enabled = false` configuration, same as realtime checks.

FIX: Appropriately handle uninstalled problem checks

---

.github/workflows/tests.yml

Cache for now but eventually we will remove the cache in https://github.com/discourse/discourse/pull/28897. That PR will take a much longer time to ship though and is more risky.

DEV: Cache minio binaries cause downloading them is slow

---

db/migrate/20240912061806_drop_trgm_indexes_on_users.rb

This avoids locking the index's table

PERF: Update migration to drop index concurrently.

---

plugins/poll/app/models/poll.rb
plugins/poll/lib/poll.rb
plugins/poll/plugin.rb
plugins/poll/spec/requests/topics_controller_spec.rb

Topics with multiple polls will generate N+1 queries to load the IDs of the users who voted and the details of these users.

PERF: Cache serialized voters at topic view level

---

app/assets/javascripts/discourse/ember-cli-build.js
app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

In our test suite, we sometimes see ChunkLoadErrors. This plugin should cause those failed requests to be retried seamlessly. It'll also help clients with flaky internet connections in production.

DEV: Introduce webpack-retry-chunk-load-plugin

---

plugins/chat/app/models/chat/direct_message.rb
plugins/chat/spec/models/chat/direct_message_spec.rb
plugins/chat/spec/system/sidebar_navigation_menu_spec.rb

Makes usernames in Chat Direct Message channels consistent with other areas of the app by removing the alias.
Before:
After:

UX: remove alias from chat direct message channel titles

---

app/assets/javascripts/discourse/app/raw-templates/mobile/list/topic-list-item.hbr

We've already got the sibling outlet `topic-list-before-columns` here, so this adds the after equivalent too (using this in a theme component refactor)

DEV: add topic-list-after-columns outlet to mobile

---

Gemfile
Gemfile.lock

This reverts commit 68e017c3243da54ae6171d49b12dcfc80be57132.
Still seeing faults ... we had 1 segfault in 7 hours.

Revert "DEV: attempt another upgrade on mini_racer (#28951)"

---

plugins/discourse-narrative-bot/spec/system/user_spec.rb

We are seeing the following error on CI:
```
Errno::EADDRNOTAVAIL:
Failed to open TCP connection to localhost:31337 (Cannot assign requested address - connect(2) for "localhost" port 31337)
```
This is because the job being enqueued makes a HTTP request to the Rails
server but Capybara doesn't start the Rails server until a session is
actually required. Therefore, we need to enqueue the job after we are
sure that a session has been started.

DEV: Fix failing system tests

---

lib/file_store/base_store.rb

At a point we split `FileStore#download` into two methods, one which returns `nil` (`#download`) and one which raises an exception (`#download!`) if there's a download error.
When we did this we added a deprecation warning to the `#download` method.
It has now been over a year and I have checked all relevant internal cases, so I think it's about time we remove this warning.

DEV: Remove FileStore#download deprecation warning

---

lib/search.rb
spec/lib/search_spec.rb

Currently, when certain search terms are provided, this can lead to `Search.need_segmenting?` raising an error because it makes `URI#path` to return `nil` instead of a string.
This PR forces a cast to string so it won’t raise anymore.

FIX: Don’t raise on some search terms

---

lib/service/base.rb
plugins/chat/app/services/chat/search_chatable.rb
spec/lib/service_spec.rb

With the current implementation, a service step can be written as:
```ruby
def my_step(a_default_value: 2)
…
end
```
That’s a pattern we want to avoid, as default values (if needed) should be probably defined in a contract.
This PR makes a service raise an exception if a default value is encountered.

DEV: Disallow default params in service steps

---

app/services/user_action_manager.rb
spec/lib/post_destroyer_spec.rb

Permanently deleting posts that no longer have a user associated was not working as expected because of UserAction.log which expected user_id to be present.

FIX: permanent delete of posts by deleted users

---

app/assets/javascripts/admin/addon/controllers/admin-user-index.js
app/assets/javascripts/admin/addon/models/admin-user.js
app/assets/javascripts/admin/addon/templates/user-index.hbs
app/controllers/admin/users_controller.rb
app/models/user_history.rb
app/services/staff_action_logger.rb
config/locales/client.en.yml
config/routes.rb
lib/guardian/user_guardian.rb
spec/requests/admin/users_controller_spec.rb

This commit introduces a feature that allows an admin to delete a user's associated account. After deletion, a log will be recorded in staff actions.
ref=t/136675
Log:

FEAT: Allow admin delete user's associated accounts

---

config/nginx.global.conf

This was added 11 years ago and I don't see us using this anywhere.

DEV: Remove unused file

---

app/assets/javascripts/admin/addon/components/admin-plugin-config-page.gjs
app/assets/javascripts/admin/addon/models/admin-plugin.js
plugins/chat/assets/javascripts/discourse/initializers/chat-admin-plugin-configuration-nav.js

In 61c1d35f17468b3666c966839da911d9f96dad19 I added a
PluginOutlet to AdminPluginConfigPage. This was intended to be
used as a way to render actions buttons inside the header of
a plugin that has a custom admin UI page. This worked, but
since the outlet was generically named, as soon as one plugin
used it the button would show on all plugins.
This fixes the immediate issue by naming the outlet based
on the plugin, then having each plugin specify their own
outlet to render into. There may be a nicer way to do this,
but for now this stops the bleeding.

FIX: Unscoped plugin config page actions outlet

---

app/assets/javascripts/discourse/app/components/reviewable-item.js
spec/fabricators/reviewable_fabricator.rb
spec/system/reviewables_spec.rb

After #28603, the options "agree and suspend" and "agree and silence" in the review queue weren't working. This was happening because the `optionalService`, when used as a decorator, needs a name argument to work properly. We were also lacking tests for this.
Provide a name to the `optionalService` decorator, which fixes the issue, and add a system test to prevent regressions.

FIX: Fix broken client-side review actions

---

app/assets/javascripts/admin/addon/components/admin-filtered-site-settings.gjs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/plugins.scss
app/assets/stylesheets/common/admin/site-settings.scss

* Fixes big gap at the left of the plugins list.
* Fixes plugin settings list padding, the yellow overridden
dot was cut off on mobile.
* Also increased settings filter input size and settings
sidebar button margin.
Before
After

UX: Minor admin mobile fixes

---

config/locales/server.en.yml

https://meta.discourse.org/t/regression-iframe-embedding-broken-with-allowed-src-domain/327852/13
The `allowed_iframes` isn't a list of simple domain names; it requires a full or partial URL with `https://` at the beginning and a trailing slash at the end.

Proper description of the `allowed_iframes` setting

---

app/models/reviewable_queued_post.rb

this adds a missing button label when a category moderator can delete their own queued post, reported here: https://meta.discourse.org/t/review-queue-displays-translation-missing-button/327651
Before:
After:

UX: Add label for delete own post button in review queue

---

plugins/automation/app/controllers/discourse_automation/admin_automations_controller.rb
plugins/automation/spec/requests/admin_discourse_automation_automations_spec.rb

When trying to create a new automation based on a scriptable that has "force_triggerable" enable, it would break because of a typo in the code.
This fixes the typo and add a spec to ensure this code path is tested.

FIX: create an automation with forced_triggerable enabled

---

app/assets/stylesheets/common/components/user-stream-item.scss

In some cases the category badge could overflow the page and create horizontal scroll, this fixes it! 
before:
after:

UX: prevent user stream title from overflowing page

---

lib/guardian/category_guardian.rb
lib/guardian/topic_guardian.rb
spec/lib/guardian/topic_guardian_spec.rb

Previously admins could still click on topics when `suppress_secured_categories_from_admin` was set
This change improves the block so admins without permission will not be allowed to click through till they add themselves to appropriate groups
Keep in mind this setting is a quality of life setting and not a SECURITY
setting, admins have an infinite way of bypassing visiblity limits

FEATURE: improve the suppression for admins when required

---

script/bulk_import/generic_bulk.rb

This prevented users from editing imported posts when they contained polls.

FIX: Import script didn't set `public` attribute of polls

---

app/assets/javascripts/discourse/app/instance-initializers/sharing-sources.js
config/locales/client.en.yml

change icon/wording/url of share link to reflect twitter's rebranding.
before:
after:
(there are no tests per se in core for validating share links wording/icons)

UX: change twitter share link to X

---

app/assets/javascripts/discourse/app/widgets/button.js
app/assets/javascripts/discourse/app/widgets/post-menu.js

When this "link copied!" text appears, it should be read by screen readers — adding `aria-live="polite"` to the button accomplishes this

A11Y: announce "link copied!" confirmation for screen readers

---

lib/svg_sprite.rb

This PR is a follow up to https://github.com/discourse/discourse/pull/29056 where it adds `fab-x-twitter` icon to the SVG sprite so it will be available for users. No tests as we have no testing for adding specific icons to the sprite.

DEV: Add missing x icon to `svg_sprite.rb`

---

lib/redis_snapshot.rb

My theory is that there were nil entries (that we were filtering out) that then changed and we weren't resetting them properly.
(the failure no longer repro'd in 30 CI runs in this PR)

DEV: Attempt to fix `about` model flakes

---

spec/system/bookmarks_spec.rb

I think the check for the bookmark icon is too optimistic,
so the DB might not be updated by the time we check. Using
try_until_success should fix this, we also don't have a
toast to check against via AJAX success, by design.

DEV: Try fix bookmark flaky

---

app/serializers/user_serializer.rb
spec/serializers/user_serializer_spec.rb

Only current user should see passkey metadata.

DEV: Do not include passkey metadata needlessly

---

plugins/chat/assets/stylesheets/common/index.scss
plugins/chat/assets/stylesheets/desktop/chat-side-panel.scss
plugins/chat/assets/stylesheets/desktop/index.scss
plugins/chat/assets/stylesheets/mobile/chat-footer.scss
plugins/chat/assets/stylesheets/mobile/chat-index.scss
plugins/chat/assets/stylesheets/mobile/chat-side-panel.scss
plugins/chat/assets/stylesheets/mobile/index.scss

Chat sidepanel css was being applied on mobile too, causing mild spacing issues, while it serves no purpose as we never show a sidepanel.
This commit:
* scopes css to desktop
* removes unnecessary `grid-template-row` property
* tweaks grid layout for footer on mobile
* tweaks styling to make sure last item is perceived as last item

UX: chat index mini refactor

---

lib/js_locale_helper.rb
spec/lib/js_locale_helper_spec.rb

Currently, when the MessageFormat compiler fails on some translations, we just have the raw output from the compiler in the logs and that’s not always very helpful.
Now, when there is an error, we iterate over the translation keys and try to compile them one by one. When we detect one that is failing, it’s added to a list that is now outputted in the logs. That way, it’s easier to know which keys are not properly translated, and the problems can be addressed quicker.

DEV: Output failing MF keys when compilation fails

---

plugins/chat/assets/stylesheets/common/chat-index.scss
plugins/chat/assets/stylesheets/mobile/chat-index.scss

Minor followup to #29082
Before
After

UX: Improve bottom padding to chat index on mobile

---

app/assets/javascripts/discourse/app/raw-templates/list/posters-column.hbr

This adds an aria-label to the link, which is useful due to `alt=""` on the avatar itself (the blank alt is intentional, because the avatar is decorative). 
This means screenreaders will read the link's purpose in absence of having visible content within it.

A11Y: add aria-label to user profile link in topic list

---

lib/tasks/assets.rake

Remove emoji.clear cache calls as data.js.es6.erb hasn't existed in a while. Emoji data is now compiled separately via javascript rake tasks. Would like confirmation but this call seems generally unnecessary here and I'd like to revisit removing this.
skip precompiling of css if db and redis are skipped.
I'm fairly sure in this way we'll be able to run `SKIP_DB_AND_REDIS=1 bundle exec rake assets:precompile` and it'll be able to build most assets, no db connection required.
`asset:compile:css` would be the only asset task missing after the above call, and it is very quick to do relative to the rest of the build.

DEV: update compile steps

---

app/models/global_setting.rb
spec/models/global_setting_spec.rb

Allows for `SKIP_DB_AND_REDIS` env var to be used without a secret key setup in global setting env.
Currently if secret key is unset, this results in errors such as the following despite `SKIP_DB_AND_REDIS` being set:
```
Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
/Users/jwong/discourse/app/models/global_setting.rb:41:in `safe_secret_key_base'
/Users/jwong/discourse/config/initializers/100-secret_token.rb:6:in `<main>'
/Users/jwong/discourse/config/environment.rb:7:in `<main>'
...
```

FIX: skips caching a generated secret key base token if `skip_redis` is true.

---

lib/version.rb

Version bumps for main: v3.4.0.beta2, v3.4.0.beta3-dev

---

lib/version.rb

Version bump for stable: v3.3.2

---

app/services/admin_notices/dismiss.rb
spec/services/admin_notices/dismiss_spec.rb

If you have the admin dashboard open, and one of the admin notices listed has already been dismissed (e.g. in another tab, or by another admin) we would show an ugly "FAILED" modal.
Make the admin dismiss endpoint idempotent. If the admin notice is already destroyed, then respond with 200. This will also correctly remove it from the list in the front-end.

FIX: Support idempotent admin notice dismissal

---

app/assets/javascripts/admin/addon/components/admin-notice.gjs
spec/system/admin_notices_spec.rb

Dismissing admin notices is an admin-only action. This is enforced on the back-end both by a routing constraint and a policy in the relevant service.
However, we still unconditionally display the "Dismiss" button to anyone with access to the admin dashboard. When clicked, it results in a 404 modal (due to the routing constraint.)
Only render the dismiss button for admins.

FIX: Only render admin notice dismiss button for admins

---

plugins/chat/spec/system/page_objects/chat/chat_thread.rb

`PageObjects::Pages::ChatThread#has_no_loading_skeleton?` was broken
because `.chat-thread__messages` is no longer a valid class.
Flaked in https://github.com/discourse/discourse/actions/runs/11205370509/job/31144816341?pr=29091

DEV: Fix flaky chat system tests

---

.github/workflows/tests.yml

Plugins are expected to always be compatible against the main `branch`
so we can skip the `plugin:pull_compatible_all rake task.

DEV: Skip `plugin:pull_compatible_all` when running against `main`

---

plugins/poll/lib/poll.rb

This can happen when other plugins, for example discourse-rainbow, are installed and add columns with same names.

FIX: Use full column name to prevent ambiguous query

---

app/assets/javascripts/admin/addon/components/admin-flag-item.gjs
app/models/post_action_type.rb
spec/system/admin_flags_spec.rb
spec/system/page_objects/pages/admin_flag_form.rb
spec/system/page_objects/pages/admin_flags.rb

Because of unreliability, the spec was temporarily disabled. However, it is ensuring that the custom flags system is working correctly. Therefore it would be great to enable it again.
I made a few fixes to try to mitigate this situation:
- Reduced amount of Redis calls;
- When deleting, ensure that the modal is closed before checking the result;
- Moved duplicated name tests to a separate block;
- Increased wait time to 3 times the default because I noticed that sometimes it gets stuck for a moment. Most of the time it is fast, but sometimes when I run tests in a loop 50 times I see slowness.

FIX: flaky flags system spec

---

plugins/discourse-details/assets/javascripts/lib/discourse-markdown/details.js
plugins/discourse-details/spec/components/pretty_text_spec.rb

Supporting `open` allows to show a `details` block open by default.
Usage:
```
[details open]
my visible content
[/details]
```

FIX: allows to use open attribute with details

---

spec/system/login_spec.rb

The `/wizard` route redirects to one of the steps. If that happens fast enough, the assertion on `/wizard` will fail.
This commit fixes that by using a regular expression. I chose this because the spec, as it is worded, should only be concerned with the fact that it is redirected to the wizard, not which step.

DEV: Fix flaky login wizard redirect spec

---

app/assets/stylesheets/common/base/sidebar-section-link.scss
app/assets/stylesheets/common/base/sidebar-section.scss
app/assets/stylesheets/common/base/sidebar.scss
plugins/chat/assets/stylesheets/common/chat-user-threads.scss
plugins/chat/spec/system/sidebar_navigation_menu_spec.rb

Moved the sidebar styling from design experiments into core, focussing on:
* increased spacing
* deemphasizing titles
* section separation

UX: new sidebar styling

---

script/bulk_import/base.rb
script/bulk_import/generic_bulk.rb

This first iteration implements bulk import for:
* direct_messages
* chat_channels
* user_chat_channel_memberships
* chat_threads
* user_chat_thread_memberships
* chat_messages
* chat_reactions
* chat_mentions

DEV: Generic bulk chat import support

---

plugins/automation/lib/discourse_automation/scriptable.rb
plugins/automation/spec/lib/scriptable_spec.rb
plugins/chat/plugin.rb
plugins/chat/spec/plugin_spec.rb

The script `send_chat_message` when used with the `post_created_edited` trigger now accepts `{{post_quote}}` as placeholder for the value of `message`.
This is made possible by a new method in `utils`. Usage:
```ruby
placeholders["foo"] = utils.build_quote(post)
```

FIX: adds post_quote as placeholder

---

app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/tests/acceptance/modal/login/login-test.js

Mobile app can capture event and launch a separate login flow. Should help resolve issues with passkeys (which aren't available in webviews) and non-local login methods.

DEV: Add app webview event when triggering login

---

config/routes.rb

This route was added for parity, it is not used. Adding it is causing internal test runs to fail with: 
```
ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
```
Locally I can repro this, but only after resetting the test env's DB. We could probably also fix this by setting 
```
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
```
but I am not sure if that has other side effects. Right now opting to remove the route, it's not essential anyway. (But odd it triggers this issue in the test env?)

DEV: Fix build by removing custom route that triggers error

---

app/assets/javascripts/discourse/app/controllers/groups-index.js
app/assets/javascripts/discourse/app/routes/groups-index.js
app/assets/javascripts/discourse/app/templates/groups/index.hbs

This update better adheres to Ember standards by moving the data fetching from the controller to the route. 
Loading the data in controller was causing some minor issues, like the loading slider not appearing on route transition.

DEV: move groups data loading from controller to route

---

spec/models/global_setting_spec.rb

`GlobalSetting.skip_redis` sets a class instance variable so we need
to reset it.
Follow-up to 7d441e378285fa37431ab49a001fc57eb75bb469

DEV: Fix state leak in spec

---

app/models/topic_view_item.rb

`Date.today` relies on the system's timezone instead of
`Rails.configuration.time_zone`. This can cause tests to fail when we
assert against the date of a record. Just use `Time.zone.today` instead
so that we always follow `Rails.configuration.time_zone`.

DEV: Fix flaky request tracker system spec

---

plugins/automation/config/locales/client.en.yml
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/topic_tags_changed.rb
plugins/automation/spec/triggers/topic_tags_changed_spec.rb

continuation of https://github.com/discourse/discourse-chat-integration/pull/223

FEATURE: add `trigger_with_pms` option to `topic tags changed` automation trigger

---

plugins/chat/assets/javascripts/discourse/lib/init-sidebar-state.js
plugins/chat/assets/javascripts/discourse/services/chat-state-manager.js

This PR fixes an issue where the following happens:
1. The user opens a page where an alternative sidebar panel is displayed like /admin or other page where a plugin is displaying an alternative sidebar like the `docs-categories` plugin
2. Clicking the chat icon in the header and opening the drawer, or if you just minimize chat into drawer after it opens full-screen
3. The alternative sidebar panel is lost and reverted to the main panel.
There are no additional tests added because this use case should already be covered by the test for the admin sidebar in:
https://github.com/discourse/discourse/blob/53f9c81790ca232b8dbfa9b04b7f0863cf0d16c2/plugins/chat/spec/system/admin_sidebar_navigation_spec.rb#L63-L79

FIX: Don't override other sidebar panels when opening/closing the chat drawer

---

app/jobs/base.rb
config/unicorn.conf.rb
lib/demon/sidekiq.rb
lib/discourse.rb

In our production environment, we have been seeing Sidekiq processes
getting stuck randomly when a USR1 signal is sent to the Unicorn master
process. We have not been able to identify the root cause of why the
Sidekiq process gets stuck. We however noticed that when the Unicorn
master process receives a USR1 signal, it will reopen the logs for the
Unicorn master process first before sending a USR1 signal for the
Unicorn worker processes to reopen the logs. We figured that we should
do the same for the Sidekiq process as well when a USR1 signal.
In this commit, we introduce an arbitrary delay of 1 second before we
the Sidekiq process reopens its log files so as to allow enough time for the Unicorn
master to finish reopening it logs first.
We also do not send reopen logs for the Sidekiq …

FIX: Unicorn master and Sidekiq reopening logs at the same time

---

app/assets/javascripts/admin/addon/components/admin-page-subheader.gjs
app/assets/stylesheets/common/admin/admin_page_header.scss

Since the AdminPageHeader is H1, it is more semantically
correct to progress to H2 after it rather than skipping
a level to H3

UX: Change AdminPageSubheader to H2

---

plugins/chat/assets/stylesheets/common/chat-channel-name.scss

Due to a change in #28731, the chat channel label on the index pages was being flexed, presumably to better align with emojis included in the names. This conflicts with `text-overflow:ellipsis` so I've removed flex. The lesser of 2 evils is a mildly misaligned emoji.
The other solution would involve separating these two elements, so label has its own wrapper element
```
<div class="chat-channel-name">
<div class="chat-channel-name__label">
{{replaceEmoji this.channelTitle}}
```
but thats not easily done.

UX: fix missing text overflow ellipsis in chat index pages

---

app/assets/javascripts/discourse/tests/helpers/form-kit-assertions.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/input-number-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/form-test.gjs

This commit simply ensures the API is similar for fields and form.

DEV: uses hasNoErrors for field as used on form

---

spec/integration/smtp_spec.rb

We some times get the following failure on Github CI:
```
expected StandardError with message matching /some.host/, got #<Socket::ResolutionError: getaddrinfo: Temporary failure in name resolution> with backtrace:
```

DEV: Attempt to fix a flaky spec

---

plugins/chat/assets/javascripts/discourse/components/channel-name/index.gjs
plugins/chat/assets/stylesheets/common/chat-channel-name.scss

Followup for #29150 
Recent indicator position changes and flex moving around caused some issues.  
This should hopefully fix everything:
* indicator moved outside of the `chat-channel-name__label`
* flex applied to `chat-channel-name` when inside a `chat-channel-row__info`

UX: chat index flex issues

---

app/assets/javascripts/discourse/app/templates/badges/show.hbs
app/assets/javascripts/discourse/app/widgets/poster-name.js

- This PR adds an outlet wrapper for the badge title and extracts a function outside the `html` method for poster-widget to help customize the badge title for posters. Nothing was changed in terms of functionality.

DEV: Add helpers to customize poster title

---

app/models/top_topic.rb
spec/models/top_topic_spec.rb

I'm working on a private plugin which adjusts TopTopic records after they have been calculated. This event will trigger once a period is calculated for plugins to listen for.

DEV: Publish DiscourseEvent after top topic period is calculated

---

script/bulk_import/base.rb
script/bulk_import/generic_bulk.rb

The current implementation adds a "note" for chat messages with empty messages, however chat messages with only uploads  are allowed. This change allows such messages to be imported.

FIX: Imports of upload-only chat messages

---

plugins/chat/app/controllers/chat/api/channels_controller.rb
plugins/chat/app/models/chat/direct_message_channel.rb
plugins/chat/assets/javascripts/discourse/components/chat/routes/channel-info-settings.gjs
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js
plugins/chat/lib/chat/guardian_extensions.rb
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/lib/chat/guardian_extensions_spec.rb
plugins/chat/spec/models/chat/direct_message_channel_spec.rb
plugins/chat/spec/system/channel_settings_page_spec.rb

Support threads in DMs and group chats so members can keep their conversations organized.
This change adds a new toggle switch for threads within the Chat Channel Settings screen. For new direct message channels threading is enabled by default.
We have made a decision to exclude direct message threads from the My Threads screen for now.
How the settings screen looks in chat drawer:
And the chat view looks with threads:

FEATURE: enable threading in chat DM channels

---

app/jobs/regular/notify_category_change.rb
spec/jobs/notify_category_change_spec.rb

Fixes: [Email notifications don’t get sent on category change for mailing list mode users](https://meta.discourse.org/t/email-notifications-dont-get-sent-on-category-change-for-mailing-list-mode-users/308096)
Previously, when category was changed, emails for mailing list subscribers were never triggered. It turns out this case was [never accounted for](https://meta.discourse.org/t/email-notifications-dont-get-sent-on-category-change-for-mailing-list-mode-users/308096/3). This PR triggers email notification for mailing list subscribers as well

FIX: Notify mailing list subscribers on category change

---

config/locales/server.en.yml

Added a link to https://meta.discourse.org/t/configuring-incoming-email-to-create-new-topics-or-group-messages/62977 to the `forwarded emails behaviour` setting description, to help admins learn how email forwarding works.

Add link to meta to forwarded emails behaviour desc

---

lib/plugin/metadata.rb

Adding `discourse-hcaptcha` to the plugin metadata list as part of making it an official plugin

DEV: Add discourse-hcaptcha plugin to the metadata list of official plugins

---

db/migrate/20241011054348_fix_unique_constraint_on_problem_check_trackers.rb

By default, when checking uniqueness on a tuple for the purposes of enforcing a unique index, PostgreSQL considers `NULL`s to be distinct values. Because of this we could incorrectly have multiple entries with `{ identifier: "rails_env", target: nil }` created due to race conditions. This would then cause errors at runtime.
Drop the existing index and recreate it with the `NULLS NOT DISTINCT` option.
The `problem_check_trackers` table is constrained by the number of problem check Ruby classes in the codebase, and will be in the range of 10-100.

DEV: Fix problem check tracker unique index not respecting NULLs

---

plugins/chat/assets/javascripts/discourse/components/chat/navbar/threads-list-button.gjs

Changing the thread button from using `btn-flat` to the new `btn-transparent` so it's consistent with the other buttons.
https://github.com/user-attachments/assets/5d47b386-eab8-4bbe-9b0d-56a73a1d3dd4
https://github.com/user-attachments/assets/215faf41-68b4-41fe-a6c9-23af3ff8e0bd

UX: change thread button in chat nav to use btn-transparent

---

app/assets/javascripts/discourse/app/components/header/user-dropdown/notifications.gjs
app/assets/javascripts/discourse/app/components/suggested-topics.hbs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs

Currently the topic timeline tip appears before the suggested topics one only due to a small implementation detail in the latter.
This ensures that tips appear in the expected order when more than one of these components is rendered at the same time.

DEV: Set priorities on user tips

---

plugins/chat/lib/chat/guardian_extensions.rb
plugins/chat/spec/requests/chat/api/channel_threads_controller_spec.rb

When chat channels are deleted, some users may be able to click the thread before it gets removed from the UI. This leads to a serverside error (a 500 error causing unwanted log noise) as chat_channel will be `nil` due to the `deleted_at` constraint on `Chat::LookupThread`.
We can use the safe navigational operator to prevent calling `chatable` when the channel is not found. This allows our failed policy to work correctly and raise `Discourse::InvalidAccess` (giving a 403 response code).

FIX: trashed channel thread view bug

---

app/assets/javascripts/discourse/app/helpers/theme-i18n.js
app/assets/javascripts/discourse/app/helpers/theme-setting.js

theme-setting and theme-i18n are not needed in `.gjs` files. This commit adds more helpful error messages to direct developers to the modern alternatives.

DEV: Improve error messages for legacy theme helpers in gjs

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs
app/assets/stylesheets/common/form-kit/_field.scss

Prior to this fix the format class was only applied to the child control, but in case of full we also need to ensure the parent wrapping field is also taking 100% width otherwise we are at risk of having a field of the width of its content.

FIX: applies full class to field

---

plugins/chat/app/services/chat/trash_messages.rb
plugins/chat/assets/javascripts/discourse/components/chat/selection-manager.gjs

50 is pretty restrictive, let's do 200 for now

UX: Bump up chat delete messages limit

---

app/models/notification.rb
app/models/shelved_notification.rb
app/models/user.rb
app/models/user_badge.rb
db/post_migrate/20240829140226_drop_old_notification_id_columns.rb
plugins/chat/app/models/chat/mention_notification.rb
plugins/chat/db/post_migrate/20240829140227_drop_chat_mention_notifications_old_id_column.rb

The `id` column of `notifications` table and `notification_id` columns of `shelved_notifications` and `user_badges` tables have been migrated to bigint in previous commits (for example, 799a45a).
In order to run the migrations with zero downtime, the data had to be copied to new columns and swapped, but the old columns have been kept to allow for rollback.

DEV: Drop old notification id columns

---

.github/workflows/tests.yml

This reverts commit 387f2c52e65ef48ea734fbfdfa34f2e28d3493fb.
Merging fails if there are no artifacts matching the pattern. Reverting while we work out a path forward

Revert "DEV: Fix github workflow yaml syntax (#29217)"

---

app/controllers/categories_controller.rb

The `index` and `categories_and_topics` methods have a lot of common
code that use `CategoryList` and `TopicQuery`. This commit refactors the
shared code into `fetch_category_list` and `fetch_topic_list`.

DEV: Refactor categories controller to reuse code

---

spec/rails_helper.rb
spec/support/system_helpers.rb

- Uses a temporary, clean, per-test-process directory for minio data
- Runs a separate minio instance for each test process
- Unskips minio-based tests in CI

DEV: Improve isolation and concurrency for minio-based upload specs

---

lib/plugin/metadata.rb

This plugin is prone to causing flaky test runs, and is in the process of being deprecated

DEV: Remove discourse-encrypt from core CI suite

---

plugins/chat/assets/javascripts/discourse/components/chat/message/info.gjs
plugins/chat/assets/javascripts/discourse/helpers/format-chat-date.js
plugins/chat/config/locales/client.en.yml

In certain locales like English (GB), If a user posted 2 subsequent messages, the first would have a date displayed in 24 hour format, while the second message would be shown in 12 hour format (when hovering the message).
This change forces both messages to display in 12 hour format, the first message showing the am/pm, and the second showing the smaller version without am/pm:

UX: consistent chat message date format

---

lib/promotion.rb
spec/lib/promotion_spec.rb

The Promotion class is in charge of checking the requirements for each trust level and promoting users. Currently, there is no way to customize the trust level requirements without doing a monkey patch on the Promotion class.
**Problem**
We are doing customer work that requires trust level requirements customization, to avoid monkey patches, these 2 modifiers are added.

DEV: Add PluginRegistry modifiers to #review and #recalculate

---

plugins/chat/lib/chat_sdk/message.rb

Currently, `ChatSDK.create` restricts what parameters can be provided to the underlying service. This prevents the `discourse-ai` plugin from using it in one of its specs (https://github.com/discourse/discourse-ai/blob/main/spec/lib/modules/ai_bot/playground_spec.rb#L436).
This patch allows extra parameters to be provided.

DEV: Allow `ChatSDK.create` to take extra parameters

---

app/assets/javascripts/discourse/app/components/search-menu/results/assistant.hbs

Add plugin outlets for each assistant result type - User, Tag and Categories, Groups, etc. This gives us the ability to add content for each _type_ of search suggestion: 
I would have preferred to add a single plugin outlet at the top of the template and pass `this.suggestionType` and `@results`, but that would then require that we carry over a ton of core logic to plugins to calculate which _type_ is being rendered, and it would get unnecessarily messy quick. So instead I opted to create a plugin outlet for each _type_.

DEV: Add `SearchMenu::Results::Assistant` plugin outlets

---

config/locales/client.en.yml
plugins/chat/assets/javascripts/discourse/helpers/format-chat-date.js
plugins/chat/config/locales/client.en.yml

This change moves the date/time formats to core locales, so that they can be used outside of the plugin.

DEV: move chat time formats to core locales

---

plugins/chat/assets/javascripts/discourse/components/chat-composer-uploads.js
plugins/chat/spec/system/uploads_spec.rb

Chat was using a private function which has now been made public.
This commit also adds a test for this codepath.

FIX: _uploadDropTargetOptions is now public

---

app/assets/javascripts/admin/addon/components/admin-user-field-item.hbs

When converting the user custom fields admin form in #29070, I accidentally removed the plugin outlet `after-admin-user-fields`. This is used by the `discourse-authentication-validations` plugin, which is now broken on `main` core.
Regardless of what we do, the outlet arguments have to change, because it is no longer a `bufferedProperty`, and we need to pass the `form` for plugins to use the FormKit components.
This commit adds back the plugin outlet in core.
A PR for fixing the plugin is incoming.

FIX: Add back user custom field plugin outlet that was accidentally removed

---

app/assets/stylesheets/common/base/sidebar-section.scss
app/assets/stylesheets/desktop/components/_index.scss
app/assets/stylesheets/desktop/components/sidebar/sidebar-section.scss

Followup of #29119 to address tablet styling, mentioned in https://meta.discourse.org/t/new-sidebar-design-on-tablets/330162
* Add missing dividers between sections
* mini alignment tweak for desktop/tablet for section-header
| ![CleanShot 2024-10-17 at 14 18 50@2x](https://github.com/user-attachments/assets/57bf81b4-8937-4323-810a-949a011f207e) | ![CleanShot 2024-10-17 at 14 16 22@2x](https://github.com/user-attachments/assets/115aaa25-87c0-486b-b956-adcb5dd8da6d) |

UX: fix sidebar styling on tablet

---

plugins/chat/spec/lib/chat/channel_fetcher_spec.rb
plugins/chat/spec/lib/chat/guardian_extensions_spec.rb
plugins/chat/spec/lib/chat/message_bookmarkable_spec.rb
plugins/chat/spec/lib/chat_sdk/message_spec.rb
plugins/chat/spec/requests/chat/api/channels_messages_flags_controller_spec.rb
plugins/chat/spec/requests/core_ext/bookmarks_controller_spec.rb
plugins/chat/spec/requests/core_ext/notifications_controller_spec.rb
plugins/chat/spec/requests/core_ext/users_controller_spec.rb
plugins/chat/spec/services/auto_remove/handle_user_removed_from_group_spec.rb
plugins/chat/spec/services/chat/create_message_spec.rb
plugins/chat/spec/services/chat/invite_users_to_channel_spec.rb
plugins/chat/spec/services/chat/stop_message_streaming_spec.rb
plugins/chat/spec/services/chat/update_user_channel_last_read_spec.rb
plugins/chat/spec/services/chat/update_user_thread_last_read_spec.rb

This is extracted from https://github.com/discourse/discourse/pull/29129.
In some chat specs, we provide an array as a value for group lists like `chat_allowed_groups`, which is wrong. This results in a value like `"1|2|[3]"` instead of `"1|2|3"`.

DEV: Don’t provide an array to site settings group lists in specs

---

app/assets/javascripts/discourse/app/mixins/uppy-upload.js
plugins/chat/assets/javascripts/discourse/components/chat-composer-uploads.js

This API change was unintentionally introduced in 06d32a8a894480673dce31241d81f7aeee50d04e
Partially reverts 23d90ecb26c666e83fd0ec1c19d2f6399f0fd2a7, but keeps the new specs.

DEV: Fix regression in uppy-mixin

---

plugins/chat/app/models/chat/channel.rb
plugins/chat/app/models/chat/direct_message_channel.rb
plugins/chat/app/services/chat/leave_channel.rb
plugins/chat/spec/models/chat/category_channel_spec.rb
plugins/chat/spec/models/chat/direct_message_channel_spec.rb

Extracted from https://github.com/discourse/discourse/pull/29129.

DEV: Extract leave logic to the `Chat::Channel` models

---

spec/system/custom_sidebar_sections_spec.rb
spec/system/page_objects/components/navigation_menu/base.rb

Technically we don't show the edit custom section button on mobile, but the button is present so I just fixed it so the finder works on mobile. We should probably remove this test or find a way to make the button visible on mobile.
Also used `mobile: true` instead of manual url.

DEV: fix flakey spec in sidebar

---

app/assets/javascripts/discourse/app/models/post-stream.js
app/assets/javascripts/discourse/app/models/post.js
app/models/remote_theme.rb
app/models/theme.rb
app/models/theme_modifier_set.rb
app/models/theme_setting.rb
app/serializers/post_stream_serializer_mixin.rb
db/migrate/20241011033602_add_post_badges_to_theme_modifiers.rb
lib/topic_view.rb
spec/models/remote_theme_spec.rb
spec/requests/topics_controller_spec.rb

This change allows theme to define modifiers that can be changed by site operator. 
New syntax is:
```
{
...
"modifiers": {
"modifier_name": {
"type": "setting",
"value": "setting_name"
}
}
}
```
This also introduces a new theme modifier for `serialize_post_user_badges`. Name of badge must match the name of the badge in the badges table.

FEATURE: theme_modifiers can depend on theme settings (add serialize_post_user_badges)

---

config/site_settings.yml

Follow-up to [fd57a64](https://github.com/discourse/discourse/commit/fd57a641744efca6f8ccc8ea530a5615cb7edf5d) that fixed iOS issues with this feature.

FEATURE: Enable image optimization on iOS >= 18

---

lib/active_support_type_extensions/array.rb
plugins/chat/app/services/chat/auto_remove/handle_chat_allowed_groups_change.rb
spec/lib/active_support_type_extensions/array_spec.rb

This PR improves the custom `array` type available in contracts. It’s now able to split strings on `|` on top of `,`, and to be more consistent, it also tries to cast the resulting items to integers.
---
Extracted from https://github.com/discourse/discourse/pull/29129

DEV: Improve `array` type in service contracts

---

app/assets/javascripts/discourse/app/components/discovery/categories-display.gjs
app/models/category_list.rb

The subcategories page was not paginated and it was using the subcategory style from the category settings. The same page style should be used for categories and subcategories page.
Categories page (both before and after):
Subcategories page (before - not using set desktop style):
Subcategories page (after - using set desktop style, same as categories page):

FIX: Make subcategories page more like categories

---

app/assets/javascripts/admin/addon/controllers/admin-badges/show.js
app/assets/javascripts/discourse/app/form-kit/components/fk/control/select/option.gjs
spec/system/admin_badges_spec.rb

This commit is fixing the path which sets a default value to trigger. We were doing `if (!this.model.trigger)` but `this.model.trigger` can have `0` as value, which would trigger this codepath and this codepath was setting the first value of badgeTriggers as a default value for trigger.

FIX: do not override trigger when equals 0

---

app/assets/stylesheets/common/font-variables.scss

Using the max() function will ensure the font-size is always 16px at minimum, and switches to 1em if that's larger than 16px.
This to prevent reported zooming when the text size setting is smaller or smallest.
https://meta.discourse.org/t/reply-button-not-visible-when-composing-on-ios/322220/2

UX: ensure ios font size is always min 16px with max() fn

---

lib/cooked_post_processor.rb
spec/lib/cooked_post_processor_spec.rb
spec/lib/email/sender_spec.rb

We want to allow lightboxing of smaller images, even if they are below the minimum size for image thumbnail generation.
This change sets a minimum threshold of 100 x 100 pixels for triggering the lightbox.

FIX: show lightbox for small images

---

app/controllers/categories_controller.rb
spec/requests/categories_controller_spec.rb

We're expecting the `page` param to be something that neatly coerces into an integer. If we receive something like a nested parameter, this will blow up. (I'm sure there are other examples as well.)
This commit falls back to a `page` value of `1` if the coercion fails.

FIX: Don't error out on nested categories index page param

---

app/controllers/topics_controller.rb
spec/requests/topics_controller_spec.rb

We're expecting the ID param to be something that neatly coerces into an ID. If we receive something like a nested parameter, this will blow up. (We already handle the case of arrays.)
This commit raises an `InvalidParameters` exception in the case of a nested ID.

FIX: Don't error out on nested topic show id param

---

app/services/flags/create_flag.rb
app/services/flags/destroy_flag.rb
app/services/flags/reorder_flag.rb
app/services/flags/toggle_flag.rb
app/services/flags/update_flag.rb
spec/services/flags/create_flag_spec.rb
spec/services/flags/destroy_flag_spec.rb
spec/services/flags/reorder_flag_spec.rb
spec/services/flags/toggle_flag_spec.rb
spec/services/flags/update_flag_spec.rb

Extracted from https://github.com/discourse/discourse/pull/29129.
This PR makes the code more compliant with the [upcoming service docs best practices](https://github.com/discourse/discourse-developer-docs/pull/5).

DEV: Refactor flag related services a bit
