Gemfile
Gemfile.lock
config/environments/development.rb
config/initializers/101-lograge.rb
config/unicorn.conf.rb
lib/discourse.rb
lib/discourse_logstash_logger.rb
lib/version.rb
spec/lib/discourse_logstash_logger_spec.rb

This reverts commit 92d7d24d0ffbf3e224af19eda2b24df740df056b.

DEV: Redo `DiscourseLogstashLogger` to not rely on `logstash-logger` take 2

---

script/discourse

DEV: Add force option to discourse remap command

---

config/initializers/101-lograge.rb

This commit updates the `101-lograge` initializer to unsubscribe from
log events logged by `ActionView::LogSubscriber`. This is what the `lograge`
gem has been doing but its implementation is not compatible with Rails
7.1 and we started getting noise in our logs when lograge is enabled.
1. Run `RAILS_DISABLE_ACTIVERECORD_LOGS=1 ENABLE_LOGRAGE=1 ENABLE_LOGSTASH_LOGGER=1 bin/rails s`
2. Run `tail -f log/development.log | grep "Rendering"`
3. Run `curl http://localhost:3000/latest`
4. Ensure that tail doesn't show any logs.

DEV: Unsubscribe from ActionView log events when lograge is enabled.

---

lib/plugin/instance.rb

DEV: Fix deprecation typo

---

app/assets/javascripts/discourse/app/components/generated-invite-link.gjs
app/assets/javascripts/discourse/app/components/generated-invite-link.hbs
app/assets/javascripts/discourse/app/components/generated-invite-link.js

DEV: migrate generated-invite-link to gjs

---

app/assets/javascripts/discourse/app/controllers/topic.js

FIX: Scroll to top shortcut regressed in b757275

---

app/controllers/topics_controller.rb

Followup b46e1fe2aa89c47fed9c86aa3337d84d29e95c53

DEV: Remove old defer_track_visit_v2 method

---

lib/tasks/docker.rake

This commit updates the `docker:test` rake task to run core and plugin
QUnit tests in parallel using half the number of available CPU
processors to speed up time it takes to run the tests on hardware with
more CPU cores.
Before this commit, core QUnit tests ran by the `docker:test` rake task was capped at 3 parallel
processes while plugin QUnit tests was not ran in parallel.

PERF: Update `docker:test` to run QUnit with more cores if available

---

app/assets/javascripts/discourse/package.json
yarn.lock

DEV: Fix a missing dependency to `@messageformat/core`

---

package.json
yarn.lock

* Remove `@messageformat/core` from the root package.json
* Run `yarn && npx yarn-deduplicate && yarn`

DEV: Clean up package.json/yarn.lock

---

app/assets/javascripts/discourse/app/components/modal/json-schema-editor.hbs
app/assets/javascripts/discourse/app/components/modal/json-schema-editor.js
app/assets/javascripts/discourse/tests/unit/components/json-schema-editor-test.gjs

Followup to ce3d91f422f2618edad62ac63c58062067f7011b

DEV: Add simple test for json-schema-editor and remove extra `await`

---

.licensed.yml

…and sort both lists alphabetically
(unlocks #27781)

DEV: Add `logger` to default gems list

---

plugins/chat/spec/system/uploads_spec.rb

DEV: wait a bit for chat message to persist

---

app/assets/javascripts/discourse/app/components/user-summary-section.gjs
app/assets/javascripts/discourse/app/components/user-summary-section.hbs
app/assets/javascripts/discourse/app/components/user-summary-section.js

DEV: migrates user-summary-section to gjs

---

app/assets/javascripts/discourse/app/components/render-glimmer-container.gjs

DEV: Remove extra whitespace from render-glimmer-container

---

app/assets/javascripts/discourse/app/components/topic-list/activity-column.gjs
app/assets/javascripts/discourse/app/components/topic-list/posts-count-column.gjs
app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs

DEV: Add missing outlet args to glimmer topic list components

---

app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common/foundation/color_transformations.scss

UX: modernize the header drop shadow

---

app/assets/javascripts/discourse/app/components/disabled-icon.hbs
app/assets/javascripts/discourse/app/components/disabled-icon.js

DEV: removes unused disabled-icon

---

app/assets/javascripts/discourse/app/components/text-overflow.hbs
app/assets/javascripts/discourse/app/components/text-overflow.js

DEV: removes unused text-overflow

---

app/assets/javascripts/discourse/app/components/discourse-topic.js
app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/header/auth-buttons.gjs
app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/components/header/topic/featured-link.gjs
app/assets/javascripts/discourse/app/routes/topic-from-params.js
app/assets/javascripts/discourse/app/services/header.js

Follow up on https://github.com/discourse/discourse/pull/27138 and https://github.com/discourse/discourse/pull/27234

DEV: Disambiguate how the topic info is handled in the header service

---

config/routes.rb
spec/requests/posts_controller_spec.rb

This PR aims to update the stable branch with changes from PR #27811

Backport changes from PR #27811

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
app/assets/javascripts/discourse/app/components/flag-action-type.js
app/assets/javascripts/discourse/app/components/modal/flag.js
app/assets/javascripts/discourse/app/models/post-action-type.js
app/assets/javascripts/discourse/tests/fixtures/site-fixtures.js
app/assets/javascripts/discourse/tests/helpers/site.js
app/assets/stylesheets/common/admin/flags.scss
app/models/concerns/reports/moderators_activity.rb
app/models/flag.rb
app/models/post.rb
app/models/post_action_type.rb
app/models/user.rb
app/serializers/flag_serializer.rb
app/serializers/post_action_type_serializer.rb
app/services/flags/create_flag.rb
app/services/flags/update_flag.rb
config/locales/client.en.yml
db/fixtures/003_flags.rb
db/post_migrate/20240703232446_rename_flags_custom_type_to_require_message.rb
lib/badge_queries.rb
lib/flag_settings.rb
lib/guardian/post_guardian.rb
lib/post_action_creator.rb
lib/post_revisor.rb
spec/lib/flag_settings_spec.rb
spec/models/post_action_spec.rb
spec/requests/api/schemas/json/site_response.json
spec/services/flags/create_flag_spec.rb
spec/services/flags/update_flag_spec.rb

Reverts discourse/discourse#27706

Revert "FEATURE: custom flag can require additional message"

---

plugins/chat/spec/system/uploads_spec.rb

DEV: skip flaky spec in CI

---

app/assets/javascripts/discourse/app/services/restricted-routing.js

FIX: 2fa check error for anon users

---

app/assets/javascripts/discourse/app/form-kit/components/fk/collection.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/password.gjs
app/assets/stylesheets/common/form-kit/_collection.scss
app/assets/stylesheets/common/form-kit/_control-input.scss
app/assets/stylesheets/common/form-kit/_control-password.scss
app/assets/stylesheets/common/form-kit/_index.scss
app/assets/stylesheets/common/form-kit/_row.scss

- removes unused css code
- improves password control sizing
- adds more spacing between collection items
- correct a typo in collection class

DEV: various form-kit tweaks

---

app/assets/javascripts/discourse/app/components/d-navigation.hbs

DEV: Add `after-breadcrumbs` plugin outlet

---

db/migrate/20240714231226_duplicate_flags_custom_type_to_require_message.rb

Drop read-only as it is causing problems with seed fu

DEV: drop readonly from flags custom type

---

app/models/flag.rb

Reverts discourse/discourse#27961

Revert "FIX: fallback to custom type for flags"

---

plugins/checklist/assets/javascripts/discourse/initializers/checklist.js

e.g. due to a permissions/network issue

UX: Show error when checkbox change fails

---

app/assets/javascripts/admin/addon/templates/dashboard.hbs
app/assets/stylesheets/common/admin/dashboard.scss

This fixes the nav overflow issue when viewing on mobile.

UX: fix dashboard tabbed nav overflow

---

app/assets/javascripts/discourse/app/components/sidebar/api-sections.gjs

DEV: Prevent error filtering the sidebar items when the section text is empty

---

app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs

DEV: add plugin outlets to the admin plugins list

---

spec/system/admin_sidebar_navigation_spec.rb
spec/system/homepage_spec.rb
spec/system/page_objects/components/select_kit.rb
spec/system/signup_spec.rb

This adds some more assertions in system tests at certain instances during the test to minimise flakiness.

DEV: Allow system tests to assert on values at the correct time

---

app/models/topic.rb

PERF: Shortcircuit Topic.similar_to if max_similar_results is 0

---

config/locales/client.en.yml

We don't need this extra description, whole number
should be enough

UX: FormKit error message followup

---

app/assets/javascripts/discourse/app/components/topic-map/index.gjs
app/assets/javascripts/discourse/app/controllers/topic.js

FIX: Ensure topic stream is loaded before rendering the map

---

config/locales/client.en.yml

FIX: missing ? in plural translation

---

app/models/remote_theme.rb
app/models/theme.rb

DEV: Don't try to update child themes in tests

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/contact-information.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/general-settings.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/your-organization.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/custom.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/custom-test.gjs
app/assets/stylesheets/common/form-kit/_container.scss
app/assets/stylesheets/common/form-kit/_control-custom.scss
app/assets/stylesheets/common/form-kit/_index.scss
config/locales/client.en.yml
spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/admin_about_config_area_contact_information_card.rb
spec/system/page_objects/components/admin_about_config_area_general_settings_card.rb
spec/system/page_objects/components/admin_about_config_area_your_organization_card.rb
spec/system/page_objects/components/form_kit.rb

DEV: Migrate about config area to Form Kit

---

app/assets/stylesheets/common/components/topic-map.scss

FIX: Topic map styling for PMs

---

spec/models/translation_override_spec.rb

DEV: Fix flaky spec related to translation overrides

---

app/assets/javascripts/discourse/app/lib/flag-targets/flag.js

this.flagCreatedEvent call needed () to work

---

app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs
spec/system/topic_list/glimmer_spec.rb

FIX: Bulk (glimmer) topic selection on mobile

---

lib/search.rb

unaccent isn't marked as a pure function, so it gets evaluated per row instead of once.

PERF: Don't use unaccent on string literals

---

app/models/translation_override.rb
lib/i18n/i18n_interpolation_keys_finder.rb
spec/lib/js_locale_helper_spec.rb

This is a small followup of https://github.com/discourse/discourse/pull/28037.

DEV: Refactor translation overrides a bit

---

app/assets/javascripts/discourse/app/components/bookmark-list.hbs
app/assets/javascripts/discourse/app/components/user-stream-item.hbs

Adding these plugin outlets to better mirror `topic-list-item`

DEV: Add `user-stream-item-above` and `bookmark-list-before-link` plugin outlets

---

app/assets/javascripts/admin/addon/controllers/admin-site-text-edit.js

DEV: `controllers/admin-site-text-edit` to native class syntax

---

app/assets/javascripts/admin/addon/components/admin-user-field-item.js

This was the last classic class in the `admin/` section 🎉

DEV: Convert `components/admin-user-field-item` to native class

---

lib/plugin/instance.rb
spec/lib/plugin/instance_spec.rb

DEV: Add plugin API to perform actions when the plugin is turned on/off

---

app/assets/javascripts/discourse/app/components/discovery-topics-list.js
app/assets/javascripts/discourse/app/components/discovery/topics.hbs
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/lib/transformer.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/tests/unit/lib/value-transformer-test.js
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md

Follow up on https://github.com/discourse/discourse/pull/27090 to add behavior transformers, which allows overriding code that generate side effects, actions, etc.

DEV: Add behavior transformers

---

app/assets/javascripts/discourse/app/controllers/about.js
app/assets/javascripts/discourse/app/controllers/account-created-edit-email.js
app/assets/javascripts/discourse/app/controllers/account-created-index.js
app/assets/javascripts/discourse/app/controllers/application.js
app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/app/controllers/email-login.js
app/assets/javascripts/discourse/app/controllers/exception.js
app/assets/javascripts/discourse/app/controllers/full-page-search.js

DEV: Convert core controllers to native class syntax (batch 1)

---

app/assets/javascripts/discourse/app/controllers/group-activity-posts.js
app/assets/javascripts/discourse/app/controllers/group-activity-topics.js
app/assets/javascripts/discourse/app/controllers/group-activity.js
app/assets/javascripts/discourse/app/controllers/group-index.js
app/assets/javascripts/discourse/app/controllers/group-manage-categories.js
app/assets/javascripts/discourse/app/controllers/group-manage-logs.js
app/assets/javascripts/discourse/app/controllers/group-manage-profile.js
app/assets/javascripts/discourse/app/controllers/group-manage-tags.js
app/assets/javascripts/discourse/app/controllers/group-manage.js
app/assets/javascripts/discourse/app/controllers/group-messages.js
app/assets/javascripts/discourse/app/controllers/group-permissions.js
app/assets/javascripts/discourse/app/controllers/group-requests.js
app/assets/javascripts/discourse/app/controllers/group.js
app/assets/javascripts/discourse/app/controllers/groups-index.js
app/assets/javascripts/discourse/app/controllers/groups-new.js

DEV: Convert core controllers to native class syntax (batch 2)

---

app/assets/javascripts/discourse/app/components/header/home-logo.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/acceptance/transformers/home-logo-image-url-test.js

DEV: Introduce `home-logo-image-url` value transformer

---

config/locales/server.en.yml
config/site_settings.yml
db/migrate/20240731190511_update_invalid_allowed_iframe_values.rb
lib/validators/allowed_iframes_validator.rb
spec/lib/oneboxer_spec.rb

- Adds a validator for the allowed iframes site setting
- Adds a migration to update any values that don't pass the validator
Follow up to: 188cb58daa833839c54c266ce22db150a3f3a210

DEV: Add validation for allowed iframes setting

---

plugins/poll/lib/ranked_choice.rb
plugins/poll/spec/lib/ranked_choice_spec.rb

FIX: poll ranked choice result algo majority check

---

lib/post_revisor.rb
plugins/automation/config/locales/client.en.yml
plugins/automation/config/locales/server.en.yml
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers.rb
plugins/automation/lib/discourse_automation/triggers/topic_tags_changed.rb
plugins/automation/plugin.rb
plugins/automation/spec/triggers/topic_tags_changed_spec.rb

Adding a trigger for when topic tags change.

FEATURE: Added trigger for topic tags changed

---

app/assets/javascripts/discourse/app/lib/transformer.js
app/assets/javascripts/discourse/tests/unit/lib/transformer-test.js
config/locales/client.en.yml

DEV: Catch transformer errors

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/services/header.js
config/locales/server.en.yml
config/site_settings.yml

https://meta.discourse.org/t/316549

DEV: Enable glimmer header by default

---

app/assets/javascripts/select-kit/addon/components/tag-row.hbs

DEV: add description parameter to discourse-tag component

---

app/models/flag.rb
app/models/post_action_type.rb
app/models/reviewable_score.rb
spec/models/flag_spec.rb
spec/multisite/flags_spec.rb

This fixes an N1 in topics when loading all flags
and also makes the cache multisite-safe, followup
to fb7cc2d3754d23e4c30fa2794eb7ac84ffdc667e

FIX: Cache all flags multisite-safe

---

app/assets/javascripts/discourse/app/controllers/user-activity-bookmarks.js
app/assets/javascripts/discourse/app/controllers/user-activity.js
app/assets/javascripts/discourse/app/controllers/user-badges.js
app/assets/javascripts/discourse/app/controllers/user-invited-show.js
app/assets/javascripts/discourse/app/controllers/user-invited.js
app/assets/javascripts/discourse/app/controllers/user-summary.js
app/assets/javascripts/discourse/app/controllers/user.js
app/assets/javascripts/discourse/app/controllers/users.js

DEV: Convert core controllers to native class syntax (batch 4)

---

Gemfile
Gemfile.lock
spec/lib/cache_spec.rb
spec/rails_helper.rb

This is a small followup of #28124.

DEV: Use rspec mocks to properly verify a race condition

---

app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/controllers/preferences.js
app/assets/javascripts/discourse/app/controllers/review-index.js
app/assets/javascripts/discourse/app/controllers/review-settings.js
app/assets/javascripts/discourse/app/controllers/second-factor-auth.js
app/assets/javascripts/discourse/app/controllers/tag-groups-edit.js
app/assets/javascripts/discourse/app/controllers/tag-groups-new.js
app/assets/javascripts/discourse/app/controllers/tag-groups.js
app/assets/javascripts/discourse/app/controllers/tags-index.js
app/assets/javascripts/discourse/app/controllers/topic.js

DEV: Convert core controllers to native class syntax (batch 3)

---

app/assets/javascripts/discourse/app/components/sidebar/api-panels.gjs
app/assets/javascripts/discourse/app/components/sidebar/api-section.gjs
app/assets/javascripts/discourse/app/components/sidebar/api-sections.gjs
app/assets/javascripts/discourse/app/components/sidebar/section-link.gjs
app/assets/javascripts/discourse/app/components/sidebar/section.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-panel.js
app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-section-link.js
app/assets/javascripts/discourse/app/services/sidebar-state.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js

DEV: Auto expand active sections and scroll active link into view

---

app/assets/javascripts/discourse/tests/acceptance/transformers/header-notifications-avatar-size-test.js
app/assets/javascripts/discourse/tests/acceptance/transformers/home-logo-href-test.js

This commit adds tests for:
- header-notifications-avatar-size
- home-logo-href

DEV: adds tests for transformers

---

plugins/chat/spec/system/admin_sidebar_navigation_spec.rb
plugins/chat/spec/system/chat_channel_spec.rb
plugins/chat/spec/system/navigation_spec.rb
plugins/chat/spec/system/page_objects/chat_drawer/chat_drawer.rb
plugins/chat/spec/system/separate_sidebar_mode_spec.rb
spec/support/system_helpers.rb
spec/system/homepage_spec.rb
spec/system/page_objects/components/logo.rb
spec/system/page_objects/pages/search.rb
spec/system/request_tracker_spec.rb
spec/system/scroll_manager_service_spec.rb
spec/system/search_spec.rb
spec/system/user_page/user_preferences_profile_spec.rb

Usage:
```ruby
click_logo # globally accessible
PageObjects::Components::Logo.click
PageObjects::Components::Logo.hover
```

DEV: adds logo page component

---

app/models/search_log.rb
app/models/user.rb
spec/models/search_log_spec.rb

DEV: Add `search_log` modifier to prevent search log logging

---

lib/guardian.rb
spec/lib/guardian_spec.rb

DEV: Add `guardian` modifier to prevent sending PM

---

app/models/user.rb
spec/models/user_spec.rb

DEV: Add `user` modifier to prevent updating ip_address

---

app/assets/javascripts/admin/addon/components/resumable-upload.hbs
app/assets/javascripts/admin/addon/components/resumable-upload.js

DEV: Remove an unused component

---

app/assets/javascripts/admin/addon/templates/admin-badges/show.hbs

This was not using CheckboxGroup and the I18n key was incorrect.

FIX: correctly render sql checkboxes

---

app/assets/javascripts/admin/addon/components/admin-watched-word.hbs
app/assets/javascripts/discourse/app/components/expand-post.hbs
app/assets/javascripts/discourse/app/components/software-update-prompt.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/components/user-status-picker.hbs
plugins/poll/assets/javascripts/discourse/components/poll-option-ranked-choice.gjs
plugins/poll/assets/javascripts/discourse/components/poll-options.gjs

DEV: Use `on` modifier (or `@action` param)

---

app/assets/javascripts/admin/addon/components/admin-watched-word.hbs
app/assets/javascripts/discourse/app/components/expand-post.hbs
app/assets/javascripts/discourse/app/components/software-update-prompt.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/components/user-status-picker.hbs
plugins/poll/assets/javascripts/discourse/components/poll-option-ranked-choice.gjs
plugins/poll/assets/javascripts/discourse/components/poll-options.gjs

This reverts commit e3e5710b3d0c81217628bf913d888eab800e6435.

Revert "DEV: Use `on` modifier (or `@action` param) (#28323)"

---

Gemfile.lock

This pulls in https://github.com/rubyjs/mini_racer/commit/87ef545a272c1573423f9af08a8e96eb57f4dede

DEV: Update mini_racer

---

app/assets/javascripts/discourse/app/lib/transformer.js

DEV: Accept new transformer names after resetting to a new test

---

app/assets/stylesheets/common/base/menu-panel.scss

UX: Style reviewables in the user menu when avatars are enabled

---

app/controllers/uploads_controller.rb
app/models/upload.rb
config/site_settings.yml
lib/validators/upload_validator.rb
spec/requests/uploads_controller_spec.rb

This adds `system_user_max_attachment_size_kb` to the server.

FEATURE: add `system_user_max_attachment_size_kb` site setting

---

config/initializers/000-development_reload_warnings.rb

The Listen gem watches recursively, which has a cost per-file on Linux (via rb-inotify). This commit skips a bunch of unnecessary directories to reduce the startup cost.

DEV: Skip unnecessary work when booting dev server on linux

---

app/assets/stylesheets/common/base/about.scss

UX: Improve mobile view for the new /about page

---

app/assets/javascripts/admin/addon/components/webhook-status.gjs
app/assets/javascripts/admin/addon/components/webhook-status.hbs
app/assets/javascripts/discourse/app/lib/fabricators.js
app/assets/javascripts/discourse/tests/integration/components/webhook-status-test.gjs

This commit also adds a test for this component.

DEV: migrates webhook-status to gjs

---

spec/lib/guardian_spec.rb

Follow up to e1c4cf2566172b4461119f2c145764b978809100

DEV: Add tests for `Guardian#is_developer?`

---

Gemfile.lock

This pulls in https://github.com/rubyjs/mini_racer/commit/87ef545a272c1573423f9af08a8e96eb57f4dede

DEV: Update mini_racer (#28363)

---

config/site_settings.yml
spec/system/topic_map_spec.rb

UX: Show topic map in topics without replies by default

---

app/assets/javascripts/admin/addon/templates/whats-new.hbs
config/locales/client.en.yml

UX: Apply new admin UI guidelines to What's New

---

app/assets/javascripts/discourse/app/components/anonymous-topic-footer-buttons.js
app/assets/javascripts/discourse/app/components/avatar-flair.js
app/assets/javascripts/discourse/app/components/avatar-uploader.js
app/assets/javascripts/discourse/app/components/badge-title.js
app/assets/javascripts/discourse/app/components/basic-topic-list.js
app/assets/javascripts/discourse/app/components/bookmark-list.js
app/assets/javascripts/discourse/app/components/bread-crumbs.js
app/assets/javascripts/discourse/app/components/categories-and-latest-topics.js
app/assets/javascripts/discourse/app/components/categories-and-top-topics.js
app/assets/javascripts/discourse/app/components/categories-boxes-topic.js
app/assets/javascripts/discourse/app/components/categories-boxes-with-topics.js
app/assets/javascripts/discourse/app/components/categories-boxes.js
app/assets/javascripts/discourse/app/components/categories-only.js
app/assets/javascripts/discourse/app/components/categories-topic-list.js
app/assets/javascripts/discourse/app/components/categories-with-featured-topics.js
app/assets/javascripts/discourse/app/components/modal/create-invite.js
app/assets/javascripts/discourse/app/components/modal/share-topic.js
app/assets/javascripts/discourse/app/components/user-fields/base.js

DEV: Convert core components to native class syntax (batch 1)

---

app/assets/javascripts/discourse/app/lib/fabricators.js

DEV: adds tag to core fabricators

---

.github/workflows/tests.yml

DEV: Update GitHub Actions runners to ubuntu 22.04

---

plugins/chat/app/services/chat/auto_remove/handle_category_updated.rb

Now that `ActiveRecord` relations are properly handled in a `model` step, putting this step back will allow the service to stops its execution if there are no users to be removed without calling the pretty big SQL query contained in the `CalculateMembershipsForRemoval` action.

DEV: Put back the `model` step in HandleCategoryUpdated service

---

lib/tasks/themes.rake

DEV: Add env to `themes:install:archive` to allow skipping child themes

---

lib/tasks/themes.rake

Followup to a69f3a0880154bf0cbbdf573e527e79b3cd571f8

DEV: fixup themes:install:archive flag

---

app/assets/javascripts/discourse/app/lib/fabricators.js

DEV: adds more fields to topic fabricator

---

app/assets/javascripts/discourse/app/mapping-router.js

DEV: Convert mapping-router to native class syntax

---

.github/workflows/tests.yml

DEV: Don't hardcode number of parallel processes for QUnit

---

.github/workflows/tests.yml

The `--profile 50` option will print the top 50 slowest tests

DEV: Profile RSpec tests in tests workflow

---

app/assets/stylesheets/common/components/topic-map.scss
app/assets/stylesheets/common/float-kit/d-menu.scss

* due to wrong scoping some topic map styling was bleeding into the general DMenu component
* added overflow property to DMenu

UX: DMenu fixes

---

config/site_settings.yml

Follow-up to https://github.com/discourse/discourse/pull/28382.

DEV: Unhide the `display_eu_visitor_stats` setting

---

spec/system/private_message_map_spec.rb

DEV: Skip failing system test on CI

---

app/models/notification.rb
app/models/shelved_notification.rb

Follow-up to ec8ba5a0b9ff8dbefae74d6ec4f08dc13e418c6b

DEV: Fix annotations

---

plugins/poll/assets/javascripts/discourse/components/poll-options.gjs
plugins/poll/assets/javascripts/discourse/components/poll.gjs
plugins/poll/config/locales/client.en.yml
plugins/poll/test/javascripts/component/poll-options-test.js

This commit will add `highest priority` to first choice and `lowest priority` to the last choice to make it more explicit to the user.

UX: explain choices priorities

---

app/assets/javascripts/discourse/app/mixins/card-contents-base.js
app/assets/stylesheets/common/components/user-card.scss
app/assets/stylesheets/mobile/components/user-card.scss
plugins/chat/assets/stylesheets/desktop/base-desktop.scss

DEV: changes identifier from card to usercard

---

plugins/chat/assets/javascripts/discourse/initializers/chat-sidebar.js
plugins/chat/assets/javascripts/discourse/services/chat.js

UX: highlight the chat channel/DM only when chat is expanded

---

app/assets/javascripts/discourse/app/components/category-list-item.js
app/assets/javascripts/discourse/app/components/category-name-fields.js
app/assets/javascripts/discourse/app/components/category-permission-row.js
app/assets/javascripts/discourse/app/components/category-read-only-banner.js
app/assets/javascripts/discourse/app/components/category-title-before.js
app/assets/javascripts/discourse/app/components/category-title-link.js
app/assets/javascripts/discourse/app/components/category-unread.js
app/assets/javascripts/discourse/app/components/choose-message.js
app/assets/javascripts/discourse/app/components/color-picker-choice.js
app/assets/javascripts/discourse/app/components/color-picker.js
app/assets/javascripts/discourse/app/components/composer-action-title.js
app/assets/javascripts/discourse/app/components/composer-body.js
app/assets/javascripts/discourse/app/components/composer-editor.hbs
app/assets/javascripts/discourse/app/components/composer-editor.js
app/assets/javascripts/discourse/app/components/composer-message.js
app/assets/javascripts/discourse/app/components/composer-title.js
app/assets/javascripts/discourse/app/components/composer-toggles.js
app/assets/javascripts/discourse/app/components/composer-user-selector.js
app/assets/javascripts/discourse/app/components/conditional-loading-section.js
app/assets/javascripts/discourse/app/components/connector-container.js
app/assets/javascripts/discourse/app/components/copy-button.js
app/assets/javascripts/discourse/app/components/create-invite-uploader.js
app/assets/javascripts/discourse/app/components/create-topic-button.js
app/assets/javascripts/discourse/app/components/custom-html.js

DEV: Convert core components to native class syntax (batch 2)

---

app/assets/javascripts/discourse/app/components/d-document.js
app/assets/javascripts/discourse/app/components/d-editor.hbs
app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/components/d-navigation.js
app/assets/javascripts/discourse/app/components/d-textarea.js
app/assets/javascripts/discourse/app/components/date-input.js
app/assets/javascripts/discourse/app/components/date-picker-future.js
app/assets/javascripts/discourse/app/components/date-picker-past.js
app/assets/javascripts/discourse/app/components/date-picker.js
app/assets/javascripts/discourse/app/components/date-time-input-range.js
app/assets/javascripts/discourse/app/components/date-time-input.js
app/assets/javascripts/discourse/app/components/directory-item.js
app/assets/javascripts/discourse/app/components/directory-table.js
app/assets/javascripts/discourse/app/components/discourse-banner.js
app/assets/javascripts/discourse/app/components/discourse-linked-text.js
app/assets/javascripts/discourse/app/components/discourse-root.js
app/assets/javascripts/discourse/app/components/discourse-tag-bound.js
app/assets/javascripts/discourse/app/components/discourse-topic.js
app/assets/javascripts/discourse/app/components/discovery-topics-list.js

DEV: Convert core components to native class syntax (batch 3)

---

app/controllers/tags_controller.rb
spec/requests/tags_controller_spec.rb

This had no effect in the app, but it was resulting in errors in the logs.

DEV: Ignore invalid tag parameter in TagsController

---

app/assets/javascripts/discourse/app/components/ace-editor.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-theme-settings-editor-test.gjs

Convert them to proper integration tests.

DEV: Update theme-settings-editor tests

---

app/assets/javascripts/discourse/app/components/featured-topic.js
app/assets/javascripts/discourse/app/components/flag-action-type.hbs
app/assets/javascripts/discourse/app/components/flag-action-type.js
app/assets/javascripts/discourse/app/components/flag-selection.js
app/assets/javascripts/discourse/app/components/flat-button.js
app/assets/javascripts/discourse/app/components/footer-message.js
app/assets/javascripts/discourse/app/components/future-date-input.js
app/assets/javascripts/discourse/app/components/global-notice.js
app/assets/javascripts/discourse/app/components/google-search.js
app/assets/javascripts/discourse/app/components/group-card-contents.js
app/assets/javascripts/discourse/app/components/group-flair-inputs.js
app/assets/javascripts/discourse/app/components/group-imap-email-settings.js
app/assets/javascripts/discourse/app/components/group-manage-email-settings.js
app/assets/javascripts/discourse/app/components/group-manage-logs-filter.js
app/assets/javascripts/discourse/app/components/group-manage-logs-row.js
app/assets/javascripts/discourse/app/components/group-manage-save-button.js
app/assets/javascripts/discourse/app/components/group-member.js
app/assets/javascripts/discourse/app/components/group-membership-button.js
app/assets/javascripts/discourse/app/components/group-navigation.js
app/assets/javascripts/discourse/app/components/group-post.js
app/assets/javascripts/discourse/app/components/group-selector.js
app/assets/javascripts/discourse/app/components/groups-form-interaction-fields.js
app/assets/javascripts/discourse/app/components/groups-form-membership-fields.js
app/assets/javascripts/discourse/app/components/groups-form-profile-fields.js

DEV: Convert core components to native class syntax (batch 5)

---

plugins/poll/assets/javascripts/discourse/components/poll-results-ranked-choice.gjs

FIX: poll ensure ranked choice results can handle options with rich text and links

---

app/assets/javascripts/discourse/app/components/table-header-toggle.js
app/assets/javascripts/discourse/app/components/tag-drop-link.js
app/assets/javascripts/discourse/app/components/tag-groups-form.hbs
app/assets/javascripts/discourse/app/components/tag-groups-form.js
app/assets/javascripts/discourse/app/components/tag-info.js
app/assets/javascripts/discourse/app/components/tag-list.js
app/assets/javascripts/discourse/app/components/tap-tile-grid.js
app/assets/javascripts/discourse/app/components/tap-tile.js
app/assets/javascripts/discourse/app/components/text-field.js
app/assets/javascripts/discourse/app/components/time-input.js
app/assets/javascripts/discourse/app/components/time-shortcut-picker.js
app/assets/javascripts/discourse/app/components/top-period-buttons.js
app/assets/javascripts/discourse/app/components/topic-category.js
app/assets/javascripts/discourse/app/components/topic-entrance.js
app/assets/javascripts/discourse/app/components/topic-footer-buttons.js
app/assets/javascripts/discourse/app/components/topic-list-item.js
app/assets/javascripts/discourse/app/components/topic-list.js
app/assets/javascripts/discourse/app/components/topic-navigation-popup.js
app/assets/javascripts/discourse/app/components/topic-navigation.js
app/assets/javascripts/discourse/app/components/topic-progress.js
app/assets/javascripts/discourse/app/components/topic-timer-info.js

DEV: Convert core components to native class syntax (batch 8)

---

app/assets/javascripts/discourse/app/components/uppy-backup-uploader.js
app/assets/javascripts/discourse/app/components/uppy-image-uploader.js
app/assets/javascripts/discourse/app/components/user-avatar-flair.js
app/assets/javascripts/discourse/app/components/user-card-contents.hbs
app/assets/javascripts/discourse/app/components/user-card-contents.js
app/assets/javascripts/discourse/app/components/user-flag-percentage.js
app/assets/javascripts/discourse/app/components/user-info.js
app/assets/javascripts/discourse/app/components/user-link.js
app/assets/javascripts/discourse/app/components/user-notification-schedule-day.js
app/assets/javascripts/discourse/app/components/user-notification-schedule.js
app/assets/javascripts/discourse/app/components/user-profile-avatar.js
app/assets/javascripts/discourse/app/components/user-stream-item.js
app/assets/javascripts/discourse/app/components/user-stream.js
app/assets/javascripts/discourse/app/components/user-summary-category-search.js
app/assets/javascripts/discourse/app/components/user-summary-topic.js
app/assets/javascripts/discourse/app/components/user-summary-topics-list.js
app/assets/javascripts/discourse/app/components/user-summary-user.js
app/assets/javascripts/discourse/app/components/user-summary-users-list.js

DEV: Convert core components to native class syntax (batch 9)

---

app/assets/javascripts/discourse/app/raw-views/list/new-list-header-controls.js
app/assets/javascripts/discourse/app/raw-views/list/post-count-or-badges.js
app/assets/javascripts/discourse/app/raw-views/list/posts-count-column.js
app/assets/javascripts/discourse/app/raw-views/list/visited-line.js
app/assets/javascripts/discourse/app/raw-views/topic-list-header-column.js
app/assets/javascripts/discourse/app/raw-views/topic-status.js

DEV: Convert raw-views to native class syntax

---

app/assets/javascripts/discourse/app/lib/eyeline.js
app/assets/javascripts/discourse/app/lib/posts-with-placeholders.js

DEV: Convert eyeline & posts-with-placeholders to native class syntax

---

app/assets/javascripts/discourse/app/controllers/badges/index.js
app/assets/javascripts/discourse/app/controllers/badges/show.js
app/assets/javascripts/discourse/app/controllers/preferences/account.js
app/assets/javascripts/discourse/app/controllers/preferences/email.js
app/assets/javascripts/discourse/app/controllers/preferences/emails.js
app/assets/javascripts/discourse/app/controllers/preferences/interface.js
app/assets/javascripts/discourse/app/controllers/preferences/notifications.js
app/assets/javascripts/discourse/app/controllers/preferences/profile.js
app/assets/javascripts/discourse/app/controllers/preferences/second-factor.js
app/assets/javascripts/discourse/app/controllers/preferences/security.js
app/assets/javascripts/discourse/app/controllers/preferences/tags.js
app/assets/javascripts/discourse/app/controllers/preferences/users.js

DEV: Convert badge & preferences controllers to native class syntax

---

app/assets/javascripts/discourse-common/addon/lib/helpers.js

DEV: Update `registerUnbound()` to native class syntax

---

plugins/automation/config/locales/client.en.yml
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/post_created_edited.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb

FEATURE: Post created/edited trigger can skip posts created via email

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-chooser-header.js
plugins/chat/assets/javascripts/discourse/components/chat-channel-chooser-row.js
plugins/chat/assets/javascripts/discourse/components/chat-composer-uploads.js
plugins/chat/assets/javascripts/discourse/components/chat-drawer.js
plugins/chat/assets/javascripts/discourse/components/chat-to-topic-selector.js
plugins/chat/assets/javascripts/discourse/components/collapser.js
plugins/discourse-local-dates/assets/javascripts/discourse/components/modal/local-dates-create.js
plugins/discourse-presence/assets/javascripts/discourse/components/composer-presence-display.js
plugins/discourse-presence/assets/javascripts/discourse/components/topic-presence-display.js
plugins/styleguide/assets/javascripts/discourse/components/styleguide-icons.js
plugins/styleguide/assets/javascripts/discourse/components/styleguide-markdown.js
plugins/styleguide/assets/javascripts/discourse/components/styleguide-section.js

DEV: Update remaining core plugin components to native-class syntax

---

app/assets/stylesheets/common/components/user-card.scss

UX: change usercard selector to new identifier

---

app/assets/javascripts/discourse/app/templates/invites/show.hbs

You can't select these nicely since there are no classes! This helps :)

DEV: Add container with classname to invited-by invite section

---

spec/jobs/reviewable_priorities_spec.rb
spec/lib/stylesheet/manager_spec.rb

This might be faster because the  smaller chunks of the test may run in parallel.

DEV: Split slow test in multiple smaller tests

---

spec/lib/homepage_helper_spec.rb

DEV: uses context blocks

---

config/locales/server.en.yml
config/site_settings.yml

DEV: Unhide the experimental_redesigned_about_page_groups setting

---

lib/migration/column_dropper.rb

DEV: Raise an exception if trying to set a readonly column with default

---

app/models/web_hook_event_type.rb
db/fixtures/007_web_hook_event_types.rb
spec/models/web_hook_event_type_spec.rb

This PR is adding a Category Experts WebHook event type.

FEATURE: Added Category Experts approved WebHook Event

---

config/initializers/100-logster.rb
lib/freedom_patches/rails_multisite.rb

PERF: Don't do initialization for every DB if RAILS_DB is set

---

app/assets/javascripts/admin/package.json
app/assets/javascripts/custom-proxy/package.json
app/assets/javascripts/deprecation-silencer/package.json
app/assets/javascripts/dialog-holder/package.json
app/assets/javascripts/discourse-common/package.json
app/assets/javascripts/discourse-hbr/package.json
app/assets/javascripts/discourse-i18n/package.json
app/assets/javascripts/discourse-markdown-it/package.json
app/assets/javascripts/discourse-plugins/package.json
app/assets/javascripts/discourse-widget-hbs/package.json
app/assets/javascripts/discourse/package.json
app/assets/javascripts/float-kit/package.json
app/assets/javascripts/pretty-text/package.json
app/assets/javascripts/select-kit/package.json
app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/truth-helpers/package.json
package.json

DEV: Reformat package.json files

---

config/locales/client.en.yml

DEV: Change recommended banner dimensions to 1100x300

---

plugins/chat/plugin.rb
plugins/chat/spec/plugin_spec.rb

This will allow admins to use this script and trigger together.

DEV: send_chat_message supports topic_tags_changed

---

.github/workflows/tests.yml
lib/tasks/docker.rake
lib/tasks/plugin.rake
lib/tasks/qunit.rake
lib/tasks/themes.rake

whatever was using that value is long gone

DEV: Drop qunit timeout args

---

lib/content_security_policy.rb
lib/content_security_policy/extension.rb

DEV: Remove `unsafe_eval` from test/theme-test CSP

---

app/assets/javascripts/discourse/tests/acceptance/admin-email-preview-test.js

DEV: Try to make admin email-preview test resilent

---

config/locales/client.en.yml

This PR is for changing text for the approved post webhook event.

DEV: Changed text for approved post webhook event

---

Gemfile
Gemfile.lock

This reverts commit c2b49bd095508e4c8fff05791bc23af14060b95b.
Still segfaulting

Revert "DEV: update mini_racer to latest (#28796)"

---

app/assets/javascripts/discourse/app/components/scroll-tracker.js

FIX: Remove breaking super call in scroll-tracker component

---

app/models/web_hook.rb
app/models/web_hook_event_type.rb
config/locales/client.en.yml
db/fixtures/007_web_hook_event_types.rb
spec/models/web_hook_event_type_spec.rb

This PR is adding a Category Experts unapproved WebHook event type.

FEATURE: Added Category Experts unapproved post WebHook Event

---

plugins/poll/assets/javascripts/discourse/components/poll.gjs
plugins/poll/assets/stylesheets/common/poll.scss

A test would have been nice, but it would require a lot of fixtures (more than 25 users) or new system specs, will try to add in a followup.

FIX: Poll voters list wasn't expanding properly

---

app/assets/javascripts/discourse/app/lib/model-transformers.js

FIX: Errors may be null-ish

---

lib/tasks/assets.rake

This fixes a mistake I introduced in
b652f66378590e43ae49fc8f58070c13ac846ab3. I wanted to cap it at 2 not 4.

DEV: `JOBS` should be cap at 2 in `assets:precompile:build`

---

lib/tasks/assets.rake

We were running into errors running `ember build` on machines with high CPU counts. It was then noted that `thread-loader`, which embroider uses, defaults to spinning up x workers where x is number of physical CPU cores - 1. That is probably too much so we set out to find out an optimial count to set for the `JOBS` env which embroider will use to set the number of `thread-loader` workers.
I first built an image using the following Dockerfile.
```
FROM discourse/base:release
RUN cd /var/www/discourse && sudo -EH -u discourse bundle exec rake plugin:install_all_official
RUN cd /var/www/discourse && sudo -EH -u discourse bundle exec rake assets:precompile:prereqs
```
I then ran the following command on my M3 Max Macbook Pro that has 14 phyisal CPU cores.
```
for j in 1 2 4 8 14; do echo …
```

DEV: Cap number of `thread-loader` workers in `assets:precompile:build`

---

app/assets/javascripts/admin/addon/components/admin-page-header.gjs
app/assets/javascripts/admin/addon/components/admin-page-subheader.gjs
app/assets/javascripts/admin/addon/templates/admin-badges.hbs
app/assets/javascripts/discourse/app/components/nav-item.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-page-header-test.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-page-subheader-test.gjs

These components will be used in many places and are quite
independent, adding component tests is sensible.

DEV: Add component tests for admin page header components

---

app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/discourse/tests/integration/component-templates-test.gjs

DEV: Avoid extra after-test cleanup

---

package.json
patches/licensee@11.1.0.patch
pnpm-lock.yaml

DEV: Update licensee to 11.1.0

---

app/assets/javascripts/admin/addon/templates/api-keys.hbs
app/assets/javascripts/admin/addon/templates/web-hooks.hbs

Adding these plugin outlets so that the admin pages for api keys and
webhooks can be customized.

DEV: Add plugin api for customizing api key and webhook pages

---

.github/pull_request_template.md

Added information:
- We expected the pr to have a title that is descriptive of the changes
- Good commit messages and prefixes
- If the pull request had UX/UI changes to include screenshots
- If changing flaky tests to include the reason for the change

DEV: update pull request template with more details of what is expected in a PR

---

app/assets/stylesheets/common/admin/badges.scss

FIX: Align bulk award button with the other header action buttons

---

app/assets/javascripts/discourse/app/components/admin-post-menu.gjs
plugins/poll/assets/javascripts/discourse/components/poll.gjs

FIX: Incorrect titles in two components

---

app/assets/javascripts/admin/package.json
app/assets/javascripts/discourse-common/addon/resolver.js
app/assets/javascripts/discourse-common/package.json
app/assets/javascripts/discourse-widget-hbs/package.json
app/assets/javascripts/float-kit/package.json
app/assets/javascripts/pretty-text/package.json
app/assets/javascripts/select-kit/package.json
pnpm-lock.yaml

See: https://github.com/ember-cli/ember-resolver/releases/tag/v13.0.0

DEV: Update ember-resolver to 13.0.0

---

app/assets/javascripts/admin/addon/templates/admin-badges.hbs
config/locales/client.en.yml

FIX: Regression in short description in admin badges page

---

plugins/chat/assets/javascripts/discourse/services/chat-emoji-reaction-store.js
plugins/chat/test/javascripts/unit/lib/chat-emoji-reaction-store-test.js

DEV: Add a missing service injection

---

plugins/chat/test/javascripts/unit/lib/get-reaction-text-test.js

DEV: Remove duplicated tests

---

.github/workflows/labeler.yml
.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/release-notes.yml
.github/workflows/stale-pr-closer.yml
.github/workflows/tests.yml

Need to address rate limits from docker.io
This reverts commit 6ba0dcdb0e578efee2cd4df10a30d362f3b447cd.

Revert "DEV: update runners to debian-12"

---

app/models/single_sign_on_record.rb
db/migrate/20240912212253_increase_external_avatar_url_limit_to2000.rb

We recently increased it to 1500 but that was not enough: https://github.com/discourse/discourse/commit/113e6fd274d84fadb324e2e27888ea52704fb215

DEV: Increases external avatar url limit

---

spec/system/admin_flags_spec.rb

See internal ticket t/134603/59

DEV: Skip flakey admin flags test

---

config/locales/server.en.yml
docs/ADMIN-QUICK-START-GUIDE.md

Links to https://meta.discourse.org/t/understanding-and-managing-bootstrap-mode/322876
in site settings and getting started guide.

UX: Add link to bootstrap mode docs

---

.github/workflows/tests.yml

Follow-up to 92f7b3e789e14e772fd6607a7ce3a637124d4a81

DEV: Use hosted runners on main branch for tests workflow

---

.github/workflows/tests.yml
bin/turbo_rspec

DEV: Fix incorrect `github.ref` value in tests workflow

---

.github/workflows/tests.yml

DEV: Only run `check-flaky-spec-report when enabled in tests workflow`

---

.github/workflows/tests.yml

DEV: Switch to our own hosted runners for tests workflow everywhere

---

plugins/chat/spec/system/list_channels/drawer_spec.rb
plugins/chat/spec/system/page_objects/chat/components/channels_index.rb
plugins/chat/spec/system/page_objects/chat_drawer/chat_drawer.rb

Adds a spec for chat channels lists in desktop drawer mode.

DEV: add spec for chat drawer channel lists

---

app/assets/javascripts/discourse/app/components/categories-boxes.hbs

- Add an outlet wrapper for overwriting categories boxes in plugins / themes

DEV: add outlet wrapper for categories boxes

---

app/assets/javascripts/discourse/app/components/category-name-fields.hbs

- Introduce category name field wrapper outlet

DEV: add outlet wrapper for category name field

---

app/assets/javascripts/discourse/app/components/categories-only.hbs

- Add a outlet wrapper to categories only and format file

DEV: Add outlet wrapper to categories only component

---

config/nginx.sample.conf

DEV: Remove unused lines

---

app/assets/javascripts/discourse/app/templates/user/badges.hbs

- Add outlet to overwrite badges template

DEV: Add outlet wrapper for badges template

---

app/assets/javascripts/discourse/app/components/topic-list/topic-cell.gjs
app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs

DEV: Extract TopicCell component

---

app/assets/javascripts/discourse/app/templates/user/badges.hbs

- Add 2 extra arguments to the outlet

DEV: Add aditional args to plugin outlet

---

plugins/chat/assets/javascripts/lib/discourse-markdown/chat-html-inline.js
plugins/chat/assets/stylesheets/common/chat-message.scss
plugins/chat/spec/system/chat/composer/channel_spec.rb
plugins/chat/spec/system/chat_channel_spec.rb
plugins/chat/spec/system/reply_to_message/full_page_spec.rb
plugins/chat/test/javascripts/components/chat-message-test.js

This brings feature parity with posts where you can use this tag.

FEATURE: supports mark tag in chat messages

---

Gemfile
Gemfile.lock

This time the compile disables strict aliasing to see if it resolves the issue

DEV: attempt another upgrade on mini_racer

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/contact-information.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/general-settings.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/your-organization.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/radio-group.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/meta.gjs
app/assets/javascripts/discourse/tests/helpers/form-kit-assertions.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/custom-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs
app/assets/stylesheets/common/form-kit/_field.scss
plugins/styleguide/assets/javascripts/discourse/components/sections/atoms/05-forms.hbs

Description should be above the field and that makes subtitle useless.

DEV: replaces subtitle by description

---

Gemfile
Gemfile.lock

This is attempt 5 at upgrading mini racer, fixes some edge conditions in
mini_racer that can lead to segfaults.

DEV: upgrade mini_racer

---

app/controllers/admin/config/flags_controller.rb
app/services/flags/create_flag.rb
app/services/flags/update_flag.rb
config/locales/server.en.yml
spec/services/flags/create_flag_spec.rb
spec/services/flags/update_flag_spec.rb
spec/system/admin_flags_spec.rb

Validation to ensure that the custom flag name is unique.

FIX: custom flag name should be unique

---

.github/workflows/labeler.yml
.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/release-notes.yml
.github/workflows/stale-pr-closer.yml
.github/workflows/tests.yml

Our self hosted runners does not work for forked repositories.

DEV: Only enable our self hosted runners on the discourse/discourse repo

---

Gemfile
Gemfile.lock

This reverts commit 042bfeac66185c7b13bec37814767bb825bca66a.
as expected still segfaulting

Revert "DEV: upgrade mini_racer (#29023)"

---

lib/discourse.rb
spec/lib/discourse_spec.rb

... to control whether readonly mode expires or not.

DEV: Add expires flag to enable_readonly

---

docs/INSTALL-email.md

https://www.brevo.com/pricing/
https://meta.discourse.org/t/wrong-information-of-brevo-that-discourse-recommend/327242

update brevo free pricing

---

app/assets/javascripts/discourse/app/components/reviewable-item.js
app/assets/javascripts/discourse/app/components/topic-timeline.js
app/assets/javascripts/discourse/app/controllers/user.js
app/assets/javascripts/discourse/app/lib/optional-service.js
app/assets/javascripts/discourse/tests/unit/utils/optional-service-test.js
plugins/chat/assets/javascripts/discourse/components/chat-message.gjs

DEV: Fix optionalService in decorator form

---

spec/requests/site_controller_spec.rb
spec/serializers/about_serializer_spec.rb

DEV: Resolve stat registration flaky tests

---

app/assets/javascripts/discourse/app/widgets/decorator-helper.js

DEV: Update `helper.renderGlimmer` example to gjs

---

Gemfile.lock

Backport selenium devtools

---

plugins/chat/assets/stylesheets/common/chat-index.scss

UX: add padding bottom to chat index list

---

app/assets/javascripts/discourse/app/static/wizard/components/wizard-step.gjs

DEV: Use the i18n helper in wizard

---

app/assets/javascripts/select-kit/addon/components/category-notifications-button.js

DEV: Fix `ember/no-incorrect-computed-macros` lint

---

app/assets/javascripts/discourse/app/components/topic-list/topic-cell.gjs
app/assets/javascripts/discourse/app/components/topic-list/unread-indicator.gjs

Moves related code from topic-cell to the component. Also fixes a couple autotracking cases in topic-cell.

DEV: Refactor UnreadIndicator

---

app/assets/javascripts/discourse/app/components/plugin-connector.js
app/assets/javascripts/discourse/app/lib/plugin-connectors.js

DEV: Fix `ember/no-arrow-function-computed-properties` lint

---

app/assets/javascripts/discourse/app/widgets/hooks.js

See: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/jquery-ember-run.md

DEV: Fix `ember/jquery-ember-run` lint

---

app/assets/javascripts/discourse/app/components/category-list-item.js
app/assets/javascripts/discourse/app/controllers/user-private-messages-group.js
app/assets/javascripts/discourse/app/controllers/user-private-messages-user.js
app/assets/javascripts/discourse/app/controllers/user-topics-list.js
app/assets/javascripts/discourse/app/models/nav-item.js
app/assets/javascripts/discourse/app/models/topic-tracking-state.js
app/assets/javascripts/discourse/app/routes/build-private-messages-group-route.js
app/assets/javascripts/discourse/app/services/pm-topic-tracking-state.js
app/assets/javascripts/discourse/tests/acceptance/user-private-messages-test.js
app/assets/javascripts/discourse/tests/unit/models/nav-item-test.js

DEV: Update internal tracking in pm/topic tracking state

---

app/assets/javascripts/discourse/package.json
app/assets/javascripts/theme-transpiler/package.json
package.json
patches/decorator-transforms@2.2.2.patch
pnpm-lock.yaml

DEV: Update decorator-transform to 2.2.2

---

lib/suggested_topics_builder.rb
spec/lib/suggested_topics_builder_spec.rb

DEV: Add modifier to SuggestedTopicsBuilder#add_results

---

db/post_migrate/20240910090759_make_password_columns_from_users_read_only.rb

We are getting a lock timeout but I can't tell which statement so break
it up.

DEV: Break up PG query in `MakePasswordColumnsFromUsersReadOnly`

---

spec/jobs/notify_category_change_spec.rb

DEV: Fix linting in notify_category_change_spec

---

spec/rails_helper.rb

In  ed6c9d154591b620e3347a417173b373f4738be7, we started flushing
Redis's database at the end of each test. However, we had something like
this:
```
config.after(:each, type: :system) { teardown system test stuff }
config.after(:each) { # flush redis }
```
When stuff was defined in this order, flushing redis was called before
the teardown of system test. Instead we have to switch the order around
which is what this commit does.

DEV: Fix not flushing Redis properly for system test.

---

app/assets/javascripts/admin/addon/controllers/admin-email-advanced-test.js

DEV: Ignore an upcoming eslint rule

---

spec/rails_helper.rb

DEV: Make BIGINT values more readable in tests env

---

lib/js_locale_helper.rb
spec/lib/js_locale_helper_spec.rb

This reverts commit aedfb12eda0fb4aed3fb9cd282b46740c15a1dbb.

Revert "DEV: Output failing MF keys when compilation fails"

---

plugins/discourse-local-dates/test/javascripts/helpers/freeze-time.js
plugins/discourse-local-dates/test/javascripts/unit/discourse-local-dates-test.js
plugins/discourse-local-dates/test/javascripts/unit/local-date-builder-test.js

DEV: Extract a test helper in local-dates

---

.github/workflows/tests.yml

I think the tests works with the new base image now. Will revert if it
doesn't.

DEV: Start running discourse-ai tests for stable again.

---

.github/workflows/tests.yml

DEV: Update upload-artifact to v4

---

.github/workflows/tests.yml

Followup to ec75c442db6c4817d702cfdf8279a22bbfcaea86

DEV: Fix github workflow yaml syntax

---

plugins/discourse-presence/assets/javascripts/discourse/components/composer-presence-display.hbs
plugins/discourse-presence/assets/javascripts/discourse/components/composer-presence-display.js
plugins/discourse-presence/assets/javascripts/discourse/components/topic-presence-display.hbs
plugins/discourse-presence/assets/javascripts/discourse/components/topic-presence-display.js

Glimmerify the `discourse-presence` plugin to help @chapoi refactor the topic footer on 📱 mobile.
No tests were changed since the behavior is identical.

DEV: glimmerify discourse-presence

---

app/assets/javascripts/discourse/app/lib/uppy/upload-debugging.js

DEV: Correct link in uppy-debugging warning message

---

config/initializers/000-development_reload_warnings.rb

DEV: Make the dev watcher ignore node_modules

---

config/site_settings.yml

This reverts commit 2ee63e41642868a0ea59a439decfb33fc5c1bae2.

Revert "FEATURE: Enable image optimization on iOS >= 18 (#29257)"

---

spec/requests/svg_sprite_controller_spec.rb

We only care that there are other results, not that there are a specific amount.

DEV: make the build less flaky

---

app/assets/javascripts/discourse/app/components/create-invite-uploader.hbs
app/assets/javascripts/discourse/app/components/create-invite-uploader.js

DEV: Update create-invite-uploader uppy usage

---

app/assets/javascripts/admin/addon/components/watched-word-uploader.hbs
app/assets/javascripts/admin/addon/components/watched-word-uploader.js
app/assets/javascripts/admin/addon/templates/watched-words-action.hbs
app/assets/javascripts/discourse/tests/integration/components/watched-word-uploader-test.js

DEV: Update watched-word-uploader uppy usage

---

plugins/chat/app/services/chat/add_users_to_channel.rb
plugins/chat/app/services/chat/auto_remove/handle_category_updated.rb
plugins/chat/app/services/chat/auto_remove/handle_destroyed_group.rb
plugins/chat/app/services/chat/auto_remove/handle_user_removed_from_group.rb
plugins/chat/app/services/chat/flag_message.rb
plugins/chat/app/services/chat/list_channel_messages.rb
plugins/chat/app/services/chat/search_chatable.rb
plugins/chat/app/services/chat/update_channel.rb
plugins/chat/app/services/chat/update_channel_status.rb
plugins/chat/spec/requests/chat/api/channel_messages_controller_spec.rb
plugins/chat/spec/services/auto_remove/handle_category_updated_spec.rb
plugins/chat/spec/services/auto_remove/handle_destroyed_group_spec.rb
plugins/chat/spec/services/chat/create_direct_message_channel_spec.rb
plugins/chat/spec/services/chat/create_thread_spec.rb
plugins/chat/spec/services/chat/flag_message_spec.rb
plugins/chat/spec/services/chat/invite_users_to_channel_spec.rb
plugins/chat/spec/services/chat/search_chatable_spec.rb
plugins/chat/spec/services/chat/stop_message_streaming_spec.rb
plugins/chat/spec/services/chat/trash_message_spec.rb
plugins/chat/spec/services/chat/trash_messages_spec.rb
plugins/chat/spec/services/chat/update_channel_status_spec.rb
plugins/chat/spec/services/chat/update_thread_notification_settings_spec.rb
plugins/chat/spec/services/chat/update_thread_spec.rb
plugins/chat/spec/services/chat/upsert_draft_spec.rb

Extracted from https://github.com/discourse/discourse/pull/29129.
This patch makes the code more compliant with the [upcoming service docs best practices](https://github.com/discourse/discourse-developer-docs/pull/5).

DEV: Refactor some services from chat

---

app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/admin_table.scss

This PR sets the stage for making the table layout in the admin area more responsive on mobile. You won’t see any visual changes yet since the new classes still need to be applied.
Internal: /t/133258

UX: improve layout for admin tables in mobile

---

app/assets/javascripts/discourse/app/lib/debounce.js

DEV: Deprecate the unused version of debounce

---

app/assets/javascripts/discourse/app/components/avatar-uploader.hbs
app/assets/javascripts/discourse/app/components/avatar-uploader.js

DEV: Update avatar-uploader uppy usage

---

app/assets/javascripts/admin/addon/components/emoji-uploader.hbs
app/assets/javascripts/admin/addon/components/emoji-uploader.js
app/assets/javascripts/admin/addon/templates/emojis.hbs

Also moves this component to the admin bundle. It is only used in the admin panel, and has dependencies on admin-specific i18n strings.

DEV: Update emoji-uploader uppy usage

---

app/assets/javascripts/discourse/app/components/header/user-dropdown/notifications.gjs
app/assets/javascripts/discourse/app/components/suggested-topics.hbs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/widgets/post-user-tip-shim.js

…and spread out existing priorities
A follow up to a3ea288

DEV: Add priority to post menu user-tip

---

plugins/chat/spec/system/chat_channel_spec.rb

DEV: More specs for chat excerpts

---

app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js
plugins/chat/assets/javascripts/discourse/components/chat-composer-uploads.hbs
plugins/chat/assets/javascripts/discourse/components/chat-composer-uploads.js

DEV: Update chat-composer-uploads uppy usage

---

app/models/theme_modifier_set.rb

FIX: Invalid `raise` syntax

---

app/assets/javascripts/discourse/app/components/uppy-image-uploader.hbs
app/assets/javascripts/discourse/app/components/uppy-image-uploader.js

DEV: Update uppy-image-uploader uppy mixin usage

---

plugins/automation/spec/system/admin_plugins_list_spec.rb
spec/system/page_objects/components/d_toggle_switch.rb

DEV: Avoid a hacky workaround in d-toggle-switch specs

---

app/assets/javascripts/discourse/app/components/topic-list/topic-list-header-column.gjs
app/assets/javascripts/discourse/app/raw-templates/topic-list-header-column.hbr

Using this to add some text to the table heading, like so:

DEV: add "topic-list-heading-bottom" plugin outlet

---

app/assets/javascripts/discourse/app/components/form-template-field/upload.gjs

DEV: Update form-template-field/upload uppy usage

---

plugins/automation/spec/system/admin_plugins_list_spec.rb
plugins/automation/spec/system/error_spec.rb
plugins/automation/spec/system/new_automation_spec.rb
plugins/automation/spec/system/smoke_test_spec.rb
spec/lib/backup_restore/shared_examples_for_backup_store.rb
spec/models/post_action_spec.rb
spec/models/topic_user_spec.rb
spec/models/user_avatar_spec.rb
spec/requests/users_controller_spec.rb
spec/services/user/silence_spec.rb
spec/services/user/suspend_spec.rb
spec/system/admin_user_fields_spec.rb
spec/system/admin_watched_words_spec.rb
spec/system/navigation_menu_state_integration_spec.rb
spec/system/post_menu_spec.rb

namely `js: true`, requiring `rails_helper`, and default `freeze_time` args

DEV: Remove extraneous spec code

---

app/assets/javascripts/discourse/app/components/d-modal.gjs

Revert https://github.com/discourse/discourse/pull/29391 for IOS

FIX: Enable scroll events in modals for IOS

---

lib/tasks/annotate.rake

relates to [Add annotation checks to plugins](https://github.com/discourse/.github/pull/156)
You can use this rake task like this:
```sh
rake annotate:clean:plugins
```
to annotate all plugins
or 
```sh
rake annotate:clean:plugins\[plugin-name\] 
```
for a specific one.

DEV: add rake task to annotate plugins in clean DB

---

app/assets/javascripts/discourse/app/mixins/uppy-upload.js

DEV: Deprecate uppy-upload-mixin

---

.github/dependabot.yml
package.json

- Remove pnpm peerdep exception. We're now up-to-date, and the issue is resolved
- Configure Dependabot to group future updates

DEV: Tweak uppy dependency config

---

app/assets/javascripts/discourse/tests/integration/components/d-button-test.js
app/assets/javascripts/discourse/tests/unit/lib/ember-action-modifer-test.js
app/assets/javascripts/discourse/tests/unit/lib/plugin-api-test.js
app/assets/javascripts/discourse/tests/unit/mixins/singleton-test.js
app/assets/javascripts/discourse/tests/unit/utils/decorators-test.js
app/assets/javascripts/discourse/tests/unit/utils/optional-service-test.js

In preparation for https://github.com/discourse/discourse/pull/28610

DEV: Update tests to remove/ignore classic-class uses

---

app/assets/javascripts/discourse/app/components/emoji-picker.js

DEV: Update emoji-picker.js to native class syntax

---

app/assets/javascripts/discourse/tests/unit/lib/plugin-api-test.js

DEV: Remove final object-literal decorator from plugin-api-test

---

plugins/discourse-presence/assets/javascripts/discourse/components/composer-presence-display.gjs
plugins/discourse-presence/assets/javascripts/discourse/components/topic-presence-display.gjs

DEV: Use `helperFn` in d-presence

---

app/assets/javascripts/discourse/tests/acceptance/user-test.js

Looks like the test was previously asserting the broken behaviour 🤦‍♂️

DEV: Correct test following 7af72804

---

app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs
app/assets/javascripts/discourse/app/components/topic-timeline.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs
app/assets/javascripts/discourse/app/components/topic-timeline/container.js
app/assets/javascripts/discourse/app/templates/topic.hbs
app/assets/javascripts/discourse/tests/integration/components/select-kit/topic-notifications-button-test.gjs
app/assets/javascripts/select-kit/addon/components/topic-notifications-button.gjs
plugins/styleguide/assets/javascripts/discourse/components/sections/molecules/topic-notifications.hbs

DEV: Simplify TopicNotificationsButton

---

spec/system/page_objects/modals/base.rb
spec/system/page_objects/modals/signup.rb
spec/system/page_objects/pages/signup.rb
spec/system/signup_spec.rb

These cause a lot of other flaky tests

DEV: Revert flaky specs fix attempts 

---

app/assets/javascripts/discourse/app/components/parent-category-row-optimized.hbs
app/assets/javascripts/discourse/app/templates/mobile/components/parent-category-row-optimized.hbs
app/assets/stylesheets/common/base/category-list.scss
app/assets/stylesheets/mobile/topic-list.scss

This applies only to the optimized category page style.
Desktop:
Mobile:

FEATURE: Add links to subcategories page on category page

---

app/assets/javascripts/discourse/app/components/local-login-form.hbs
app/assets/javascripts/discourse/app/components/local-login-form.js
app/assets/javascripts/discourse/app/components/login-page-cta.gjs
app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/templates/activate-account.gjs
app/assets/javascripts/discourse/app/templates/login.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/stylesheets/common/base/activation.scss
app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/common/modal/login-modal.scss
app/assets/stylesheets/desktop/invite-signup.scss
app/assets/stylesheets/desktop/login-signup-page.scss
app/assets/stylesheets/mobile/login-signup-page.scss

This PR adds more improvements to the signup/login forms. The main ones are:
- Validations for email and password will appear for the first time only after the input loses focus.
- Form inputs will scroll into view when they gain focus.
- Borders around the content on the account-created/activation pages are removed.
- Plugin outlets are hidden for fullpage login/signup.
- A plain background is used in the fullpage forms.
- The Font size of the login/signup CTA on mobile is bigger.
- Alerts are closer to the form in fullpage.

UX: More improvements to login/signup forms

---

app/assets/javascripts/admin/addon/helpers/human-size.js
app/assets/javascripts/discourse-common/addon/lib/helpers.js

DEV: Deprecate `htmlHelper`

---

app/assets/javascripts/discourse/app/models/composer.js

DEV: Add back-compat to recently converted computed props

---

app/assets/javascripts/discourse/tests/acceptance/sidebar-plugin-api-test.js

DEV: Update sidebar plugin api tests

---

migrations/.gitignore
migrations/bin/cli
migrations/config/upload.yml.sample
migrations/db/uploads_db_schema/100-base-schema.sql
migrations/lib/cli/upload_command.rb
migrations/lib/migrations.rb
migrations/lib/settings_parser.rb
migrations/lib/uploader/site_settings.rb
migrations/lib/uploader/tasks/base.rb
migrations/lib/uploader/tasks/fixer.rb
migrations/lib/uploader/tasks/optimizer.rb
migrations/lib/uploader/tasks/uploader.rb
migrations/lib/uploader/uploads.rb

This change ports the existing uploads importer script at `script/bulk_import/uploads_importer.rb` to the new migrations tooling framework, with focus on modularity and reusability. This first pass splits up the various upload import tasks and leverages new migration framework features where possible. 
Existing progress/status tracking, queuing, and threading implementations have mostly been copied over as-is, with the goal of developing a standardized framework-level implementation similar to `migrations/lib/common/extended_progress_bar.rb` and `migrations/lib/common/fork_manager.rb` later
The most important changes include adding a sample configuration file, defining database schemas, implementing CLI commands, and creating several classes for handling settings, site configurations, and …

DEV:  Refactor `uploads_importer` script

---

plugins/chat/app/models/chat/channel.rb
plugins/chat/app/models/chat/channel_custom_field.rb
plugins/chat/app/models/chat/message.rb
plugins/chat/app/models/chat/message_custom_field.rb
plugins/chat/app/models/chat/thread.rb
plugins/chat/app/models/chat/thread_custom_field.rb
plugins/chat/db/migrate/20241031050638_add_custom_fields_to_chat.rb
plugins/chat/spec/models/chat/channel_spec.rb
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/spec/models/chat/thread_spec.rb

This allows various extensions to store extra information the 3 most popular
chat entities
Useful for certain plugins and migrations

FEATURE: add custom fields to chat (channel/message/thread)

---

config/site_settings.yml

This has a number of known bugs, and we're unsure whether we'll be continuing development on it
(internal t/108372)

DEV: Hide composer diffhtml/morphlex setting

---

app/assets/javascripts/discourse/app/components/topic-status.gjs

DEV: restore topic argument for after-topic-status outlet

---

plugins/checklist/test/javascripts/lib/checklist-test.js

DEV: Update checklist tests

---

app/assets/javascripts/discourse/tests/integration/components/avatar-uploader-test.gjs
app/assets/javascripts/discourse/tests/unit/lib/lightbox/helpers/set-carousel-scroll-position-test.js
app/assets/javascripts/discourse/tests/unit/models/user-test.js
app/assets/javascripts/discourse/tests/unit/services/lightbox-test.js

with `verifySteps`, `expect(0)`, or by removing it

DEV: Replace `ok(true)` assertions

---

app/assets/javascripts/discourse/app/templates/login.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/stylesheets/common/base/login-signup-page.scss

PERF: Replace slow `:has` selectors with body classes

---

lib/site_setting_extension.rb

This makes membership checks more efficient

DEV: use Sets for setting lists.

---

app/assets/javascripts/admin/addon/routes/admin-customize-colors-show.js
app/assets/javascripts/admin/addon/routes/admin-customize-colors.js
app/assets/javascripts/admin/addon/routes/admin-customize-form-templates-edit.js
app/assets/javascripts/admin/addon/routes/admin-customize-form-templates-index.js
app/assets/javascripts/admin/addon/routes/admin-email-incomings.js
app/assets/javascripts/admin/addon/routes/admin-permalinks.js
app/assets/javascripts/admin/addon/routes/admin-user-badges.js
app/assets/javascripts/discourse/app/routes/badges-show.js
app/assets/javascripts/discourse/app/routes/group.js
app/assets/javascripts/discourse/app/routes/groups-new.js
app/assets/javascripts/discourse/app/routes/password-reset.js
app/assets/javascripts/discourse/app/routes/preferences-profile.js
app/assets/javascripts/discourse/app/routes/user-private-messages-user.js
app/assets/javascripts/discourse/app/routes/user-private-messages.js

and call super instead of manually setting model

DEV: Remove unnecessary setupController methods

---

app/assets/javascripts/discourse/app/routes/build-group-messages-route.js
app/assets/javascripts/discourse/app/routes/build-private-messages-group-route.js
app/assets/javascripts/discourse/app/routes/build-private-messages-route.js
app/assets/javascripts/discourse/app/routes/user-activity-drafts.js
app/assets/javascripts/discourse/app/routes/user-activity-pending.js
app/assets/javascripts/discourse/app/routes/user-activity-read.js
app/assets/javascripts/discourse/app/routes/user-activity-topics.js

DEV: Convert some simple model methods to async/await

---

app/assets/javascripts/discourse/app/components/composer-action-title.hbs

Add missing role attribute for accessibility

UX: add missing role attribute

---

app/assets/javascripts/discourse/app/components/modal/discard-draft.gjs

Adding missing role attribute for accessibility.

UX: add heading role to close composer dialog

---

app/assets/javascripts/theme-transpiler/package.json
package.json
patches/content-tag@2.0.3.patch
pnpm-lock.yaml

DEV: Update content-tag to 2.0.3

---

.eslintrc.cjs
app/assets/javascripts/discourse/tests/unit/lib/computed-test.js
app/assets/javascripts/discourse/tests/unit/utils/decorators-test.js

DEV: Enable `ember/no-classic-classes` eslint rule

---

config/locales/server.en.yml

relates to https://github.com/discourse/discourse/pull/29602

UX: update `create_post_for_category_and_tag_changes` to include that it needs whispers enabled to work

---

plugins/chat/app/controllers/chat/api/channel_threads_controller.rb
plugins/chat/app/services/chat/create_thread.rb
plugins/chat/spec/requests/chat/api/channel_threads_controller_spec.rb
plugins/chat/spec/services/chat/create_thread_spec.rb

Follow best practices from our docs.

DEV: Refactor the `Chat::CreateThread` service a bit

---

spec/system/discovery_category_spec.rb

Follow up to commit 948e283e0f0654a7bd1d48554623afc84beb03f4.

DEV: Add system spec for categories page

---

app/models/upload.rb
lib/s3_inventory.rb
spec/lib/s3_inventory_spec.rb

A "bad upload" in this context is a upload with a mismatched URL. This may happen if a site is moved.

FEATURE: Mark bad uploads with :invalid_url

---

app/assets/javascripts/discourse/app/lib/debounce.js
app/controllers/application_controller.rb
app/controllers/user_api_key_clients_controller.rb
app/controllers/user_api_keys_controller.rb
app/models/user_api_key.rb
app/models/user_api_key_client.rb
app/serializers/user_serializer.rb
app/services/post_alerter.rb
config/routes.rb
db/migrate/20240729084803_create_user_api_key_clients.rb
lib/auth/default_current_user_provider.rb
spec/fabricators/user_api_key_fabricator.rb
spec/lib/auth/default_current_user_provider_spec.rb
spec/requests/application_controller_spec.rb
spec/requests/notifications_controller_spec.rb
spec/requests/user_api_key_clients_controller_spec.rb
spec/requests/user_api_keys_controller_spec.rb
spec/services/post_alerter_spec.rb

See further https://meta.discourse.org/t/feasibility-of-allowing-a-user-api-key-client-to-register-a-valid-auth-redirect/312901

Add dedicated user_api_key_clients table to allow for 1:many use cases

---

app/assets/javascripts/discourse/tests/acceptance/composer-messages-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
app/assets/javascripts/discourse/tests/integration/components/widgets/render-glimmer-test.js
plugins/chat/test/javascripts/components/channel-icon-test.gjs
plugins/chat/test/javascripts/components/channel-name-test.gjs
plugins/chat/test/javascripts/components/chat-channel-card-test.js
plugins/chat/test/javascripts/components/chat-channel-preview-card-test.js
plugins/chat/test/javascripts/components/chat-composer-dropdown-test.js
plugins/chat/test/javascripts/components/chat-composer-upload-test.js
plugins/chat/test/javascripts/components/chat-emoji-avatar-test.js
plugins/chat/test/javascripts/components/chat-message-avatar-test.js
plugins/chat/test/javascripts/components/chat-message-info-test.js
plugins/chat/test/javascripts/components/chat-message-reaction-test.js
plugins/chat/test/javascripts/components/chat-message-test.js
plugins/chat/test/javascripts/components/chat-message-text-test.js
plugins/chat/test/javascripts/components/chat-upload-test.js
plugins/chat/test/javascripts/components/collapser-test.js
plugins/chat/test/javascripts/components/dc-filter-input-test.js
plugins/chat/test/javascripts/integration/components/user-menu/chat-notifications-list-test.js
plugins/poll/test/javascripts/acceptance/poll-builder-enabled-test.js

DEV: Convert `assert.true(exists())` to qunit-dom

---

app/assets/javascripts/discourse/app/instance-initializers/webview-background.js

This regressed in https://github.com/discourse/discourse/pull/28912

DEV: Fix updating header background in webview

---

app/assets/javascripts/discourse/tests/acceptance/emoji-test.js
app/assets/javascripts/discourse/tests/acceptance/group-manage-logs-test.js
app/assets/javascripts/discourse/tests/acceptance/hashtag-autocomplete-test.js
app/assets/javascripts/discourse/tests/acceptance/user-preferences-account-test.js
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.js
app/assets/javascripts/discourse/tests/integration/components/widgets/widget-test.js
plugins/chat/test/javascripts/components/chat-notices-test.js

DEV: Use selectors instead of `query()` where possible

---

.github/workflows/tests.yml

v3 is going to be EOL on Nov 14.

DEV: Upload tests workflow to use actions/upload-artifact@v4

---

config/locales/server.en.yml

Fixes: https://meta.discourse.org/t/update-or-remove-highlight-js-demo-link/304538

UX: fix link to Highlight JS demo

---

script/import_scripts/vbulletin3.rb

DEV: Fix ruby linting

---

app/assets/javascripts/discourse/app/routes/invites-show.js
app/controllers/invites_controller.rb
config/routes.rb
spec/system/signup_spec.rb

FIX: Correctly load the invites model when using full page logins

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/checkbox.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/code.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/composer.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/icon.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/input.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/menu.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/password.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/question.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/radio-group.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/radio-group/radio.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/select.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/textarea.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/toggle.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/meta.gjs
app/assets/javascripts/discourse/tests/helpers/form-kit-assertions.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/checkbox-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/code-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/composer-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/icon-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/image-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/input-text-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/menu-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/radio-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/select-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/textarea-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/toggle-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs

Disabled was set on field init which was preventing it to be dynamic.

FIX: correctly makes @disabled dynamic

---

plugins/chat/lib/discourse_dev/category_channel.rb
plugins/chat/lib/tasks/chat.rake

Those populate rake tasks weren't working anymore. Guess they aren't used that much.

DEV: fix chat:*:populate rake tasks

---

app/assets/javascripts/select-kit/addon/components/select-kit.js

The absolute strategy was causing issues on modals.

FIX: uses fixed strategy on ipad

---

.devcontainer/devcontainer.json
.devcontainer/scripts/start.rb
.vscode/extensions.json
.vscode/tasks.json.sample
app/assets/javascripts/custom-proxy/index.js
bin/ember-cli
spec/support/system_helpers.rb

- Uses a more appropriate image, with immutable tag (so update prompts work correctly)
- Updates port forwarding
- Improves mount setup (inc. persistant PG/Redis when rebuilding)
- Fixes ember-cli live reload
- Automatically configures VSCode & extensions

DEV: Overhaul devcontainer configuration

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs

This allows consumers to get intellisense completions on the `api.` argument of their callback

DEV: Improve JSDoc for withPluginApi

---

app/assets/javascripts/custom-proxy/index.js

Followup to fd5ef6896d16385eeadefae1d7558cd3a2cb2a4e

DEV: Fix duplicate port on livereload

---

config/locales/client.en.yml

To follow admin UI guidelines:

UX: Update CTA button label to 'Add Emoji' for clarity

---

app/assets/javascripts/discourse/tests/addons/truth-helpers/integration/helpers/includes-test.js
app/assets/javascripts/discourse/tests/integration/component-templates-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/category-link-test.js
app/assets/javascripts/discourse/tests/integration/helpers/concat-class-test.js

DEV: Use `test`-provided `assert` object

---

app/assets/javascripts/admin/addon/components/admin-flag-item.gjs
app/assets/javascripts/admin/addon/components/themes-grid-card.gjs
app/assets/javascripts/discourse/app/components/bookmark-menu.gjs
app/assets/javascripts/discourse/app/components/category-permission-row.gjs
app/assets/javascripts/discourse/app/components/dialog-messages/confirm-session.gjs
app/assets/javascripts/discourse/app/components/directory-item-user-field-value.gjs
app/assets/javascripts/discourse/app/components/post/menu.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/edit.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/like.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/replies.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/reply.gjs
app/assets/javascripts/discourse/app/components/signup-progress-bar.gjs
app/assets/javascripts/discourse/app/lib/offset-calculator.js
app/assets/javascripts/discourse/app/models/composer.js
app/assets/javascripts/discourse/app/services/composer.js
package.json
pnpm-lock.yaml

DEV: Bump `@discourse/lint-configs` and apply fixes

---

migrations/bin/cli
migrations/db/intermediate_db_schema/002-log_entries.sql
migrations/lib/cli/convert_command.rb
migrations/lib/cli/import_command.rb
migrations/lib/cli/upload_command.rb
migrations/lib/database.rb
migrations/lib/database/connection.rb
migrations/lib/database/intermediate_db.rb
migrations/lib/database/intermediate_db/log_entry.rb
migrations/lib/database/migrator.rb
migrations/lib/database/prepared_statement_cache.rb
migrations/lib/migrations.rb
migrations/spec/lib/database_spec.rb

DEV: Store details log entries in converter as JSON

---

app/jobs/regular/push_notification.rb
spec/jobs/push_notification_spec.rb

Follow up to commit 429cf656e78ae1858c29a446cccd386542ae2867.

DEV: Fix undefined variable

---

app/assets/stylesheets/common/base/code_highlighting.scss
app/assets/stylesheets/common/base/topic-post.scss

Further edits to allow non hljs wrapped codeblocks to render similarly

UX: Codeblocks edits

---

app/assets/javascripts/discourse/app/components/header/topic/info.gjs

No test as it's complicated to have a very simple test for this and I don't want to write a system spec for such a very specific thing.

FIX: makes tags reactive with docked header

---

app/assets/stylesheets/common/base/code_highlighting.scss
app/assets/stylesheets/common/base/topic-post.scss

This reverts commit 667a09b159ff2b348108cc6db54302da93dcebbd. Had side effects for inline code.

Revert "UX: Codeblocks edits (#29893)"

---

app/jobs/scheduled/tl3_promotions.rb
spec/jobs/tl3_promotions_spec.rb

Added tl3_custom_promotions modifier to allow the use of custom TL3 logic

DEV: Add tl3_custom_promotions plugin modifier to tl3_promotions.rb

---

app/jobs/base.rb

This was used to track jobs that may leak memory, but proved to be too noisy and not very useful.

DEV: Drop DISCOURSE_LIVE_SLOTS_SIDEKIQ_LIMIT

---

plugins/poll/test/javascripts/component/poll-test.js

DEV: lint poll test

---

app/assets/javascripts/discourse/tests/acceptance/admin-user-index-test.js
app/assets/javascripts/discourse/tests/acceptance/category-new-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-image-preview-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-uploads-uppy-test.js
app/assets/javascripts/discourse/tests/acceptance/header-api-test.gjs
app/assets/javascripts/discourse/tests/acceptance/lightbox-test.js
app/assets/javascripts/discourse/tests/acceptance/post-history-test.js
app/assets/javascripts/discourse/tests/acceptance/review-test.js
app/assets/javascripts/discourse/tests/acceptance/second-factor-auth-test.js
app/assets/javascripts/discourse/tests/acceptance/topic-user-status-test.js
app/assets/javascripts/discourse/tests/acceptance/user-activity-all-test.js
app/assets/javascripts/discourse/tests/acceptance/user-activity-likes-test.js
app/assets/javascripts/discourse/tests/acceptance/user-activity-replies-test.js
app/assets/javascripts/discourse/tests/acceptance/user-activity-topic-test.js
app/assets/javascripts/discourse/tests/acceptance/user-preferences-account-user-status-test.js
app/assets/javascripts/discourse/tests/acceptance/user-profile-summary-test.js
app/assets/javascripts/discourse/tests/acceptance/user-status-test.js
app/assets/javascripts/discourse/tests/integration/components/date-time-input-range-test.js
app/assets/javascripts/discourse/tests/unit/lib/dag-test.js

There will eventually be lint for this.

DEV: Updates all `assert.equal` to qunit-dom or strictEqual

---

app/assets/javascripts/admin/addon/templates/backups-index.hbs
app/assets/javascripts/admin/addon/templates/permalinks-index.hbs
app/assets/stylesheets/common/admin/admin_table.scss
app/assets/stylesheets/common/admin/api.scss
app/assets/stylesheets/common/admin/backups.scss
app/assets/stylesheets/common/admin/customize.scss
app/assets/stylesheets/common/admin/flags.scss
app/assets/stylesheets/common/admin/plugins.scss

DEV: refactor SCSS structure for admin table styling

---

lib/scheduler/defer.rb

DEV: Verify DB connection before trying to clear active connections

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs

- Add a plugin outlet for most liked replies

DEV:Add plugin outlet for liked posts

---

app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/theme-transpiler/transpiler.js
package.json
patches/content-tag@3.0.0.patch
pnpm-lock.yaml

DEV: Update content-tag to 3.0.0

---

config/initializers/101-lograge.rb
lib/method_profiler.rb

DEV: Log number of live slots used by requests

---

plugins/spoiler-alert/test/javascripts/unit/lib/to-markdown-test.js

DEV: Remove a use of discourseModule

---

Gemfile.lock

Context - https://meta.discourse.org/t/email-trimming-improvement-no-trimming-in-code-blocks/320159

DEV: bump email_reply_trimmer version to 0.2.0

---

app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/discourse/tests/unit/lib/url-test.js
app/assets/javascripts/discourse/tests/unit/services/document-title-test.js
app/assets/javascripts/discourse/tests/unit/services/user-tips-test.js
plugins/chat/test/javascripts/unit/utility/plugin-api-test.js

DEV: Make the `logIn` helper replace current-user service

---

app/assets/javascripts/discourse/app/templates/about.hbs

Required for removing template overrides from theme.

FEATURE: pass faqOverridden to about-wrapper plugin outlet

---

app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-image-preview-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/discourse/tests/acceptance/search-test.js
app/assets/javascripts/discourse/tests/acceptance/share-topic-test.js
app/assets/javascripts/discourse/tests/acceptance/topic-test.js

DEV: Use new qunit-dom's includesValue/doesNotIncludeValue

---

app/assets/javascripts/discourse/app/components/search-result-entry.hbs
app/assets/javascripts/discourse/app/templates/user/activity.hbs

Adding plugin wrappers as part of our move to officially deprecate (and then remove) template overrides

DEV: Add plugin wrappers required to fix template overrides

---

app/assets/javascripts/admin/addon/templates/users-list-show.hbs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/admin_filter.scss

UX: Add admin filter row styling

---

app/assets/javascripts/discourse/app/models/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-edit-conflict-test.js
app/controllers/drafts_controller.rb
app/controllers/posts_controller.rb
app/controllers/topics_controller.rb
spec/requests/drafts_controller_spec.rb
spec/requests/posts_controller_spec.rb
spec/requests/topics_controller_spec.rb

FIX: better edit conflict handling

---

app/assets/javascripts/discourse/app/services/history-store.js

DEV: Make history-store work in non-accceptance tests

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

DEV: Add posts_moved DiscourseEvent in PostMover

---

spec/rails_helper.rb

Followup:
* https://github.com/discourse/discourse/pull/28160
* https://github.com/discourse/discourse/pull/25921
In the previous PRs we added 2 environent variables
to control backtrace output for errors in rspec,
`RSPEC_EXCLUDE_NOISE_IN_BACKTRACE`, and
`RSPEC_EXCLUDE_GEMS_IN_BACKTRACE`
These largely do the same thing, and we want to enable
that behaviour by default.
This commit consolidates them into one env var,
`DISCOURSE_INCLUDE_GEMS_IN_RSPEC_BACKTRACE`, which is
disabled by default, meaning gem backtraces will not
be shown in rspec backtraces by default.
Also for the request spec use case with `RspecErrorTracker`,
we now show an indicator of how many lines were hidden from
the backtrace e.g. "...(21 framework line(s) excluded)",
and for this and the normal rspec backtrace exclusion …

DEV: Improve rspec gem backtrace exclusion ENV vars

---

spec/requests/api/schemas/json/user_create_request.json

Since the example specifies json use a json formatted example instead of
form-data.
https://meta.discourse.org/t/161413/5

DEV: Update create user w/ custom fields api docs

---

app/assets/javascripts/admin/addon/templates/user-badges.hbs
app/assets/javascripts/discourse/app/components/categories-boxes.hbs
app/assets/javascripts/discourse/app/components/small-user-list.gjs
app/assets/javascripts/discourse/app/components/user-card-contents.hbs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/app/lib/user-list-attrs.js
app/assets/javascripts/discourse/app/templates/user/badges.hbs
app/assets/javascripts/discourse/app/widgets/post-menu.js

- Backporting commits from main to stable.

DEV: backport outlet wrappers

---

app/assets/javascripts/admin/addon/templates/dashboard_general.hbs

Followup 9c4c17ad3fc80f79e8046b522efa4c769c76130d

UX: Minor fix to admin what's new link

---

db/migrate/20241206121401_delete_categories_only_optimized_site_setting.rb

This category style has been removed in f1700ca5.

DEV: Remove references to categories_only_optimized

---

app/jobs/base.rb

In `Jobs::Base::JobInstrumenter.raw_log`, we were creating an instance
of `Queue` and then pushing messages to the queue before popping it off
the queue in a thread. However, this complexity is not necessary when
we can just write directly to the logger without much overhead. This is
how all logging is done in other parts of the app as well.

DEV: Remove unnecessary thread in `Jobs::Base::JobInstrumenter`

---

app/jobs/base.rb

This reverts commit 1670ffe82dbfa46f33df94312a8649ab8117d19b.

Revert "DEV: Remove unnecessary thread in `Jobs::Base::JobInstrumenter` (#30179)"

---

app/assets/javascripts/discourse/app/controllers/review-index.js
app/assets/javascripts/discourse/app/routes/review-index.js
app/assets/javascripts/discourse/app/templates/review-index.hbs
app/controllers/reviewables_controller.rb
app/models/reviewable.rb
config/locales/client.en.yml
spec/requests/reviewables_controller_spec.rb

Previous to this change there was no way to find all the flags
a user raised.
New filter allows you to find all the flags raised by a user.

FEATURE: add support for "Flagged By" filter in reviewable

---

app/jobs/base.rb
spec/jobs/jobs_base_spec.rb

This bug was introduced in eeb01ea0de56319c9c700b88995d27e16607d49f

DEV: Fix broken sidekiq logging due to eeb01ea0de5

---

.gitignore

to ignore any .devenv and .direnv files and directories
More documentations on
- https://devenv.sh
- https://direnv.net

DEV: update .gitignore

---

app/assets/javascripts/discourse-i18n/src/index.js

Followup to e5a2ed596cc4e8470d073714fadb635b8c329923

DEV: Fixup verbose localization method name

---

lib/tasks/s3.rake

In my local setup (with Minio), this uploads the assets to S3 ~40% faster.

DEV: Upload assets to S3 in parallel

---

lib/tasks/s3.rake

Now that we run the `upload` method in different threads, we need to
synchronize writes to `STDOUT` which we can do so by using a `Logger`.
Follow-up to 49e835395966fbddb9ad2988961d8375e501151f

DEV: Use a `Logger` for `s3:upload_assets`

---

app/assets/javascripts/discourse/app/components/header/topic/info.gjs

UX: add header-categories-wrapper outlet

---

app/assets/stylesheets/common/base/topic.scss

UX: fix PM title editing layout

---

app/assets/javascripts/discourse/app/components/user-fields/confirm.hbs
app/assets/javascripts/discourse/app/mixins/user-fields-validation.js
app/assets/javascripts/discourse/tests/acceptance/create-account-user-fields-test.js
config/locales/client.en.yml

FIX: Show validation error on confirmation user fields

---

.licensed.yml

Unblocks some dependabot updates

DEV: Add io-console to default gems list

---

plugins/chat/spec/lib/chat/duplicate_message_validator_spec.rb

while we figure out if we want to keep the feature or replace it with a simpler version.
Internal ref - t/144221

DEV: skip flaky chat specs

---

plugins/chat/lib/chat/channel_fetcher.rb
plugins/chat/spec/lib/chat/channel_fetcher_spec.rb

When fetching DM channels, we would fetch all the user's DM channels, and limit the number of DM channels we display on the client-side using the `DIRECT_MESSAGE_CHANNELS_LIMIT`.
This is obviously not scalable as users are having more and more discussions with other users.
This commit ensures we always limit the number of DM channels we send to the client.
It adds the `MAX_DM_CHANNEL_RESULTS` in `ChannelFetcher` and uses it to limit the records returned by the server. This value should always be lower than `DIRECT_MESSAGE_CHANNELS_LIMIT` on the client-side, so that when the user has more "unread DMs" they still show up on the client as they "catch up".
While adding a spec, I also updated the spec that ensures we have a limit on public channels to use `stub_const` to temporarily lower the …

FIX: add server-side limit for DM channels

---

app/assets/stylesheets/common/base/sidebar-section-link.scss

This PR adds back muted & active styles to chat channel links.

UX: fix active and muted channels

---

spec/requests/session_controller_spec.rb
spec/requests/users_controller_spec.rb

These controller tests are passing locally and in CI, but are failing the build when run in parallel.
I managed to recreate the failures by running the entire suite with turbo_spec and the right seed locally. After these changes, the parallel suite passes locally as well. 🤞

DEV: Fix controller tests failing in parallel suite only

---

app/assets/stylesheets/desktop/login-signup-page.scss

This PR corrects code as well as makes the disclaimer font size smaller.

UX: Adjust disclaimer font size

---

app/assets/stylesheets/common/base/login.scss

UX: fix password mask on password reset

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/lib/transform-post.js
app/assets/javascripts/discourse/tests/unit/models/post-test.js
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md

DEV: Deprecate `api.includePostAttributes` in favor of `api.addTrackedPostProperties`

---

config/unicorn.conf.rb
lib/demon/base.rb
lib/demon/email_sync.rb
lib/demon/sidekiq.rb
spec/lib/demon/email_sync_spec.rb

This is a follow-up to 9812407f76e6925d28983084f373e9869f5bdc7f

DEV: Fix undefined method `check_email_sync_heartbeat` in unicorn conf

---

app/assets/javascripts/discourse/tests/helpers/notifications-tracking-assertions.js

DEV: fixes typo in notifications-tracking assertions

---

app/assets/javascripts/admin/addon/templates/logs.hbs
app/assets/javascripts/discourse/app/lib/lightbox.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/tests/acceptance/lightbox-test.js
app/controllers/admin/screened_emails_controller.rb
app/controllers/invites_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users_controller.rb
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/nginx.sample.conf
lib/guardian.rb
spec/integration/github_omniauth_spec.rb
spec/integration/twitter_omniauth_spec.rb
spec/requests/admin/screened_emails_controller_spec.rb
spec/requests/export_csv_controller_spec.rb
spec/requests/invites_controller_spec.rb
spec/requests/session_controller_spec.rb
spec/requests/users_controller_spec.rb
spec/system/admin_sidebar_navigation_spec.rb

SECURITY: Fixes for main

---

app/assets/javascripts/admin/addon/templates/logs.hbs
app/assets/javascripts/discourse/app/lib/lightbox.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/tests/acceptance/lightbox-test.js
app/controllers/admin/screened_emails_controller.rb
app/controllers/invites_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users_controller.rb
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/nginx.sample.conf
lib/guardian.rb
spec/integration/github_omniauth_spec.rb
spec/integration/twitter_omniauth_spec.rb
spec/requests/admin/screened_emails_controller_spec.rb
spec/requests/export_csv_controller_spec.rb
spec/requests/invites_controller_spec.rb
spec/requests/session_controller_spec.rb
spec/requests/users_controller_spec.rb
spec/system/admin_sidebar_navigation_spec.rb

SECURITY: Fixes for stable

---

app/assets/javascripts/discourse/app/components/basic-topic-list.hbs
app/assets/javascripts/discourse/app/components/basic-topic-list.js
app/assets/javascripts/discourse/app/components/categories-topic-list.hbs
app/assets/javascripts/discourse/app/components/discovery/topics.hbs
app/assets/javascripts/discourse/app/components/new-list-header-controls-wrapper.gjs
app/assets/javascripts/discourse/app/components/parent-category-row.hbs
app/assets/javascripts/discourse/app/models/site.js
app/assets/javascripts/discourse/app/models/user.js
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/site_settings.yml
plugins/styleguide/assets/javascripts/discourse/components/sections/molecules/topic-list-item.hbs
spec/system/topic_list/glimmer_spec.rb

This replaces the previous group-based site setting

DEV: Introduce new 'glimmer topic list mode' site setting

---

spec/system/admin_sidebar_navigation_spec.rb

DEV: Fix flakey spec

---

app/assets/javascripts/discourse/app/components/conditional-loading-spinner.gjs

DEV: Allow adding classes to ConditionalLoadingSpinner

---

app/assets/javascripts/discourse/app/components/modal/history.js
app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js
plugins/chat/assets/javascripts/discourse/services/chat-drafts-manager.js
plugins/chat/assets/javascripts/discourse/services/chat-guardian.js

DEV: Remove unnecessary optional chaining operators

---

app/assets/javascripts/discourse/app/components/category-title-before.gjs
app/assets/javascripts/discourse/app/components/category-title-before.hbs
app/assets/javascripts/discourse/app/components/category-title-before.js

DEV: Convert CategoryTitleBefore to gjs

---

app/assets/javascripts/discourse-common/addon/lib/object.js
app/assets/javascripts/discourse/app/lib/formatter.js
app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
app/assets/javascripts/discourse/app/models/group.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
plugins/chat/assets/javascripts/discourse/components/chat-channel.gjs
plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/assets/javascripts/discourse/lib/fabricators.js
plugins/poll/assets/javascripts/discourse/components/poll.gjs

DEV: Use object spread instead of Object.assign

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-unread-indicator.gjs

DEV: no services are used in this component

---

plugins/chat/spec/system/visit_channel_spec.rb

DEV: correct test to visit category channel and not DM

---

plugins/chat/spec/system/list_channels/drawer_spec.rb

DEV: waits for mark_read! to be applied

---

plugins/chat/assets/stylesheets/desktop/base-desktop.scss

UX: Remove chat hover effect from github status badge

---

app/helpers/common_helper.rb
app/views/layouts/application.html.erb
app/views/layouts/publish.html.erb
config/locales/server.en.yml
config/site_settings.yml

https://experienceleague.adobe.com/en/docs/experience-platform/tags/home
https://experienceleague.adobe.com/en/docs/platform-learn/implement-in-websites/configure-tags/add-embed-code

FEATURE: support adobe analytics tags tracking

---

app/controllers/user_api_key_clients_controller.rb
config/site_settings.yml
spec/requests/user_api_key_clients_controller_spec.rb

See further https://meta.discourse.org/t/issues-with-linked-actors/343469

Add user api key client rate limit settings

---

app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs

This PR updates the `DashboardNewFeatureItem` component to make it easier to customize with CSS. The changes improve flexibility and simplify styling. Existing functionality remains unaffected.
What’s changed
* Adjusted the component structure to provide better control for CSS manipulation

DEV: Refactor DashboardNewFeatureItem to simplify styling

---

app/assets/stylesheets/common/base/directory.scss

Followup to #30499, fixes CSS for older browsers.

DEV: User page layout backwards compatibility

---

plugins/automation/spec/system/page_objects/discourse_automation/automation.rb

This shouldn't be necessary and is already causing flakyness today.

DEV: do not check for loading state

---

config/locales/server.en.yml

https://meta.discourse.org/t/344065/10

UX: tweak suppress_secured_categories_from_admin setting description

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js

DEV: use isFocused dom helper

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

- Add `topic-list-item-expand-pinned` value transformer

DEV: Add `topic-list-item-expand-pinned` value transformer

---

app/assets/javascripts/discourse/app/templates/full-page-search.hbs

This PR adds PluginOutlets on `full-page-search-above-search-header` and `full-page-search-filters`.

DEV: Add PluginOutlet on full-page-search-above-search-header and filters

---

app/assets/javascripts/discourse/app/components/subcategories-with-featured-topics.hbs

This adds plugin outlets for mobile and desktop views of the subcategories with featured topics list.

DEV: Add subcategories with featured topics list plugin outlet

---

spec/requests/topics_controller_spec.rb

DEV: Clean up topics_controller_spec

---

.github/workflows/tests.yml

The previous conditionals was just more complex and harder to
understand.

DEV: Simplify `if` conditional for flaky test report steps

---

plugins/chat/plugin.rb

DEV: Fix build

---

lib/site_settings/deprecated_settings.rb

Scheduled to be removed ~3 years ago, there is a migration in place already

DEV: Remove an old deprecated setting

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js

DEV: Enable the Glimmer post menu admin notices

---

app/assets/javascripts/discourse/app/controllers/full-page-search.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/app/templates/full-page-search.hbs
app/assets/javascripts/discourse/tests/unit/controllers/full-page-search-test.js

DEV: Add behavior transformer for full page search loadMore

---

app/assets/javascripts/discourse/app/models/site.js

DEV: Silence "glimmer topic list" success message in tests

---

plugins/chat/test/javascripts/components/chat-user-card-button-test.js

DEV: Resolve this-property-fallback deprecation in chat test

---

app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

DEV: Remove now unused `bootstrap` dependency

---

.github/workflows/check-pr-body.yml

Followup to c6da8e335637cd7be3f258a311509469e452c2ee

DEV: Update dependabot commit-message splitting

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs

DEV: Move topic-list-item-class transformer to a getter

---

README.md

We forgot to update it last year :blush:

DEV: Update copyright year in README

---

app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs

We already have after-panel-body outlet and I will need this one for `*********-******`.

DEV: before-panel-body outlet

---

app/assets/javascripts/discourse/app/components/composer-body.js
app/assets/javascripts/discourse/app/instance-initializers/sniff-capabilities.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/stylesheets/common/base/compose.scss

Followup to 07e5f89.
See report https://meta.discourse.org/t/-/346876

DEV: Improve composer positioning on tablets

---

app/assets/javascripts/discourse/app/templates/full-page-search.hbs

We had no container, this allows folks to customize the styling :)

DEV: Wrap full page search 'no results' container in div

---

app/assets/javascripts/discourse/app/lib/icon-library.js

This will be displayed in the warning banner

DEV: Add URL to fa6 deprecation

---

config/locales/client.en.yml

@discourse-translator-bot keep_translations

DEV: Fix typo priviledges -> privileges

---

app/assets/javascripts/discourse/app/instance-initializers/component-templates.js

New topic-list should not be auto-enabled in this case

DEV: Detect overrides of topic-list and topic-list-item templates

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/javascripts/discourse/app/components/header/hamburger-dropdown-wrapper.gjs
app/assets/javascripts/discourse/app/components/sidebar/anonymous/sections.gjs
app/assets/javascripts/discourse/app/components/sidebar/common/custom-section.gjs
app/assets/javascripts/discourse/app/components/sidebar/common/custom-sections.gjs
app/assets/javascripts/discourse/app/components/sidebar/hamburger-dropdown.gjs
app/assets/javascripts/discourse/app/components/sidebar/more-section-link.gjs
app/assets/javascripts/discourse/app/components/sidebar/more-section-links.gjs
app/assets/javascripts/discourse/app/components/sidebar/section-link-button.gjs
app/assets/javascripts/discourse/app/components/sidebar/sections.gjs
app/assets/javascripts/discourse/app/components/sidebar/user/sections.gjs
app/assets/javascripts/discourse/app/services/modal.js
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js
app/assets/javascripts/discourse/tests/acceptance/enforce-second-factor-test.js
app/assets/javascripts/discourse/tests/acceptance/meta-tag-updater-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-community-section-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-community-section-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-test.js
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/stylesheets/common/base/sidebar-more-section-links.scss
app/assets/stylesheets/common/base/sidebar-section.scss
app/assets/stylesheets/common/components/dropdown-menu.scss
app/assets/stylesheets/desktop/menu-panel.scss
app/assets/stylesheets/mobile/float-kit/d-menu.scss
spec/system/page_objects/components/navigation_menu/sidebar.rb
spec/system/viewing_sidebar_spec.rb

UX: replaces custom more menu by d-menu

---

app/assets/stylesheets/common/base/topic-post.scss

This fixes a bit of jitteriness on mobile, noticeable mostly when going from the topic list to a post that has a table.

UX: Remove table editor transition effect

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs

Followup to 4933cfd46cf2b30600da9a72bb82d02c19ead8a3

UX: Extend Safari scrolling fix to work in iPad PWA

---

app/assets/stylesheets/mobile/topic-post.scss

Expected empty line before rule `rule-empty-line-before`

FIX: lint issue follow-up to a3359ac

---

.licensed.yml
Gemfile.lock

Dependabot PR: https://github.com/discourse/discourse/pull/30909

DEV: Update irb to 1.15.0

---

Gemfile.lock

Brings in more Inter font changes
c.f. https://github.com/discourse/discourse-fonts/commit/12124ea1443c60052f41b4b1b1f6ffa6ce058c5a

DEV: Bump discourse-fonts

---

app/assets/stylesheets/common/base/compose.scss
app/assets/stylesheets/common/components/footer-nav.scss

See https://meta.discourse.org/t/minimized-composer-reply-control-issues/348337

UX: Fix minimized composer position on iOS PWA and app

---

app/assets/javascripts/discourse/app/instance-initializers/auth-complete.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js
app/assets/javascripts/discourse/app/services/login.js
app/assets/javascripts/discourse/app/templates/login.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
spec/system/social_authentication_spec.rb

This reverts commit 13f86c99eaa1eae781ad8c869fcea515436eade8.
It had issues with login-required sites. I will re-merge it with a fix soon.

FIX: Revert "Automatic auth flow with full page login/signup"

---

lib/tasks/uploads.rake

This commit updates the `uploads:disable_secure_uploads` to be more
memory efficient by loading records in batches instead.

PERF: Optimize `uploads:disable_secure_uploads` to load in batches

---

lib/topic_query.rb
spec/lib/topic_query_spec.rb

So it matches the behavior of latest and new.

FIX: remove muted topics/tags/categories from top and hot topics lists

---

lib/service/base.rb
spec/lib/service/runner_spec.rb

That allows services to wrap steps within a Distributed lock (mutex).

DEV: new `lock` step for services

---

.github/workflows/dependabot-pnpm-dedupe.yml

DEV: Fix the dedupe workflow

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

https://meta.discourse.org/t/346415/7

DEV: Add topic-list-item-style valueTransformer

---

README.md

Update README.md description and screenshots

---

Gemfile
Gemfile.lock

There are reports of high CPU usage, so we will revert for now

DEV: revert mini_racer upgrade

---

app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/lib/username-validation-helper.js
app/assets/javascripts/discourse/app/templates/signup.hbs

This PR refactors the use of the UsernameValidation mixin to a helper class for the SignupController component. We'll extend this to the CreateAccount modal and InvitesShowController in follow-up PRs.

DEV: refactor username validation mixin to helper class

---

app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/common/table-builder/table-edit-decorator.scss
app/assets/stylesheets/wizard.scss
plugins/chat/assets/stylesheets/mixins/chat-reaction.scss
plugins/footnote/assets/stylesheets/footnotes.scss
stylelint.config.mjs

…and cases that didn't take webkit into account at all.

UX: Fix user-select regressions

---

app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/staff_logs.scss
app/assets/stylesheets/common/base/json_schema.scss
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/user.scss
stylelint.config.mjs

(to be merged after the release)

DEV: Fix `declaration-block-no-shorthand-property-overrides`

---

plugins/chat/assets/stylesheets/common/chat-message-info.scss

UX: Update bot-indicator styling

---

docs/INSTALL-cloud.md

Reverts discourse/discourse#31089

Revert "Update INSTALL-cloud.md"

---

app/assets/javascripts/discourse/app/components/topic-map/index.gjs

For @pmusaraj 
Ref: https://meta.discourse.org/t/re-federation-support-for-discourse/251640/342?u=angus

DEV: Add `topic-map` plugin outlet wrapper

---

app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js
app/assets/javascripts/discourse/app/services/login.js
app/assets/javascripts/discourse/app/templates/login.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/javascripts/discourse/tests/acceptance/login-required-test.js
config/site_settings.yml
spec/system/social_authentication_spec.rb

This adds back the fixes from https://github.com/discourse/discourse/pull/30928 that were reverted by https://github.com/discourse/discourse/pull/30960.

FIX: Automatic auth flow with full page login/signup V3

---

Gemfile
Gemfile.lock

This brings us extremely close to latest

DEV: update mini_racer to node 23.6.1

---

app/serializers/topic_list_item_serializer.rb
spec/serializers/topic_list_item_serializer_spec.rb

Will be used in this feature: https://github.com/discourse/discourse-topic-cards/pull/36

FEATURE: add first_post_id to TopicListItemSerializer

---

app/assets/javascripts/select-kit/addon/components/user-notifications-dropdown.js

Modify the component UserNotificationDropdown to receive a function that will be called after an user is ignored.

DEV: Add optional callback in notification dropdown action

---

lib/service/base.rb
spec/lib/service_spec.rb

A previous refactor of the `Service::Base::Step` class introduced a non thread-safe behavior. `#call` mutates instance variables at runtime, and since a step instance is the same for any given service class, this can sometimes lead to `context` being the wrong one for the running service.
This PR makes use of [`Concurrent::ThreadLocalVar`](https://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/ThreadLocalVar.html) to fix the issue.

DEV: Make Ruby services thread-safe

---

app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/customize.scss
app/assets/stylesheets/common/admin/settings.scss

See: https://sass-lang.com/d/mixed-decls
```diff
- WARNING: 253 deprecations encountered while compiling scss.
+ WARNING: 242 deprecations encountered while compiling scss.
```

DEV: Fix `mixed-decls` sass deprecation

---

app/assets/stylesheets/common/components/powered-by-discourse.scss

similar to: 63d376c7a9542709ec748aad32e76f304da29f4f

UX: Hide powered-by on admin invite page

---

script/bulk_import/generic_bulk.rb

`reaction_users_count` should be calculated in the import script instead of the converter.

FIX: Calculate `reaction_users_count` in the bulk import script

---

app/assets/javascripts/discourse/app/components/modal/history/revision.hbs
app/assets/javascripts/discourse/app/components/modal/history/revision.js
app/serializers/post_revision_serializer.rb

FIX: Post revision respects 'prioritize_full_name_in_ux' setting

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/components/topic-list/item/topic-cell.gjs

Requested on Meta, seems reasonable: https://meta.discourse.org/t/modify-topicexcerpt-template/352136

DEV: include expandPinned in topic-list-main-link-bottom outlet

---

lib/tasks/uploads.rake

This is a follow up to a9eefd1b4849573452581c113cfcbdd4420fb3c2.
This rake task is quite annoying to test so I don't think the time trying to figure out how to test it is worth it. This does not sit in a critical path anyway so I think the lack of tests here is OK.

FIX: Correct errors in `uploads:sync_s3_acls` rake task

---

app/assets/javascripts/discourse/app/components/parent-category-row.hbs

Description
We need to add these plugin modifiers as part of changes made to remove template overrides

DEV: Update/add plugin outlets to ParentCategoryRow to remove template overrides

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/stylesheets/common/base/_topic-list.scss

This PR adds a class to the topic list item that clarifies when a topic has an excerpt being rendered.

DEV: Clarify class when excerpt is present

---

app/assets/javascripts/discourse/app/controllers/invites-show.js

This replaces the password validation mixin with a helper class in the invites-show controller class.

DEV: replace passwordValidation mixin in InvitesShowController

---

app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/d-editor.scss
app/assets/stylesheets/common/select-kit/select-kit.scss

afaict it doesn't do anything since iOS 13?

DEV: Remove no-op `-webkit-overflow-scrolling`

---

app/assets/javascripts/admin/addon/routes/admin-config-flags-index.js
app/assets/javascripts/admin/addon/templates/config-flags.hbs

Followup e26a1175d7c33746bddbc858ad89e68cc14beefe

UX: Fix flags config page translations

---

app/controllers/webhooks_controller.rb
spec/requests/webhooks_controller_spec.rb

When an email is sent by sendgrid to an email address with an invalid
host, the webhook payload does not contain the "status" field:
```
[
{
"bounce_classification": "Unclassified",
"email": "noemail@this.does.not.exist.tld",
"event": "bounce",
"reason": "unable to get mx info: failed to get IPs from PTR record: lookup <nil>: unrecognized address",
"sg_event_id": "Ym91bmNlLTQtNTA0ODUxOTUtZXVvMmlLeGRTYXlQRjRZRTQtLUk3QS0w",
"sg_message_id": "euo2iKxdSayPF4YE4--I7A.recvd-5f54b5d587-pczjm-1-67BADEEA-6.0",
"smtp-id": "<870b3a2a-160c-4fc8-bc9a-bd0d5b943b81@forum.umbraco.com>",
"timestamp": 1740300320,
"tls": 0,
"type": "blocked"
}
]
```
When the `status` field is missing, it results in a `NoMethodError (undefined method `[]' for nil:NilClass)`
error in the controller method. In this commit, we …

FIX: No method error in `WebhooksController#sendgrid`

---

app/assets/javascripts/discourse/app/lib/composer/composer-position.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js

Add `correct-scroll-position` behavior transformer

DEV: Add `correct-scroll-position` behavior transformer

---

app/models/user_summary.rb
spec/requests/users_controller_spec.rb

Ref - https://meta.discourse.org/t/-/353878

FIX: exclude links from hidden posts in user summary

---

app/assets/javascripts/discourse/app/mixins/password-validation.js

This reverts commit fbe5a9c71096dde8d7d59a0b2bec932b22c38a05.
I missed one area outside of core where this mixin is being used.

FIX: Revert "DEV: delete PasswordValidation mixin (#31520)"

---

Gemfile.lock

See https://bundler.io/blog/2024/12/19/bundler-v2-6.html.

DEV: Enable Bundler checksums

---

app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/base/new-user.scss

UX: Evenly distribute nav-space for drop-downs & buttons

---

app/assets/javascripts/discourse/app/services/interface-color.js

This PR adds app event triggers when the interface color is changed or set back to default/auto.

DEV: Add app event triggers for interface color changes

---

app/assets/javascripts/discourse/app/components/user-summary-topic.hbs

- Add an outlet wrapper for user summary topic

DEV:add outlet wrapper for user summary topic

---

app/assets/javascripts/discourse/app/components/notifications-tracking.gjs
app/assets/stylesheets/common/components/notifications-tracking.scss

A follow up to c95c3c4311a7af461e23f18a2aad6f6e68414560

UX: Fix notifications tracking buttons styling

---

Gemfile
Gemfile.lock

Only notable changes is that we added
internal support for TimeWithZone which
was absent from previous release
We also improved error messages for T_OBJECT

DEV: bump to major release of mini_racer

---

app/assets/javascripts/admin/addon/components/admin-config-area-card-section.gjs
app/assets/stylesheets/admin/admin_config_area.scss

* Added a subtle left border to the indented field to improve visual hierarchy
* Updated the caret to align with other expandable elements for consistency

UX: Add left border to indented field and update caret for consistency

---

app/assets/javascripts/discourse/tests/integration/components/badge-button-test.gjs
app/assets/javascripts/discourse/tests/integration/components/badge-title-test.gjs
app/assets/javascripts/discourse/tests/integration/components/d-button-test.gjs
app/assets/javascripts/discourse/tests/integration/components/d-toggle-switch-test.gjs
app/assets/javascripts/discourse/tests/integration/components/date-time-input-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-template-field/checkbox-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-template-field/input-test.gjs
app/assets/javascripts/discourse/tests/integration/components/topic-participant-test.gjs
app/assets/javascripts/discourse/tests/integration/components/user-menu/menu-item-test.gjs
app/assets/javascripts/discourse/tests/integration/components/user-status-message-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/actions-summary-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/avatar-flair-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/post-cooked-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/post-links-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/poster-name-test.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/small-user-list-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/body-class-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/category-badge-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/concat-class-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/emoji-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/html-safe-test.gjs
app/assets/javascripts/discourse/tests/integration/helpers/slice-test.gjs

still lots to update but it's a start

DEV: Reduce the use of self/set in tests

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

- Add the behavior transformer `topic-list-item-click` to allow the customization for the click behavior on the topic list item.

DEV: Add a new behavior transformer to topic list item click

---

app/assets/javascripts/discourse/app/components/search-menu.js

For plugins/themes to be able to hook into after search result review is rendered

DEV: Add `SearchMenu` `search_result_view` app event

---

app/assets/javascripts/admin/addon/components/admin-config-area-card-section.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-config-area-card-section-test.gjs
app/assets/stylesheets/admin/admin_config_area.scss
spec/system/page_objects/components/admin_branding_logo_form.rb

Demo
https://github.com/user-attachments/assets/17e2b6d9-ba49-4312-85d9-6ff2ccad2290

UX: card section toggle

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

- Add the behavior transformer `topic-list-item-click` to allow the customization for the click behavior on the topic list item.

DEV: backporting to stable - add behavior transformer to topic list item click 

---

app/assets/javascripts/discourse/app/components/bulk-select-toggle.gjs

This PR adds a body class when bulk select is enabled

DEV: Add body class when bulk select is enabled

---

app/assets/javascripts/discourse/app/components/bulk-select-toggle.gjs
app/assets/javascripts/discourse/app/components/topic-list/list.gjs

Followup to 41eb83a40185e43feb964288a5ebc5a903f05e13

DEV: Move bulk-select-enabled from body to topic-list element

---

.devcontainer/devcontainer.json

Includes a node upgrade, which is required for latest prettier

DEV: Bump devcontainer image

---

config/nginx.sample.conf

- **Revert "FIX: Simplify nginx config change (#30383)"**
- **FIX: Set the Host header in the nginx.conf upstream block**

reapply refactor

---

app/assets/stylesheets/mobile/float-kit/d-menu.scss

Followup to 95922fe96b94df0e0887c71edd8e224b97446965

DEV: Fix stylelint violations

---

config/application.rb

DEV: Remove the symlinking message

---

app/controllers/users/omniauth_callbacks_controller.rb
lib/auth/result.rb

DEV: Add code comments around oauth `user-api-key/new` handling

---

app/assets/javascripts/discourse/app/components/composer/toggle-switch.gjs
config/locales/client.en.yml

UX: add title and aria-label to md/rich editor toggle

---

spec/system/forgot_password_spec.rb

The test is being tracked internally to be fixed by us

DEV: Skip system tests that have been flaky

---

plugins/discourse-presence/assets/stylesheets/presence.scss

UX: Remove bg color on presence indicator

---

app/assets/javascripts/discourse/app/components/post-list/item/details.gjs

- Backporting change from main to stable

DEV:pass post as an argument for additional member info

---

app/assets/javascripts/discourse/app/components/uppy-image-uploader.gjs
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/d-editor.scss
app/assets/stylesheets/common/float-kit/d-menu.scss

This PR:
- removes unnecessary css related to user status & DND
- removes border radius from buttons in d-menu 
- sets border radius for composer toolbar buttons

UX: Refactor, removal, cleanup

---

app/assets/stylesheets/desktop/components/header-search.scss

UX: header search adjustments

---

spec/system/admin_sidebar_navigation_spec.rb

Instances of test flake: 
1. https://github.com/discourse/discourse/actions/runs/13911507249/job/38926557337
2. https://github.com/discourse/discourse/actions/runs/13902570393/job/38897729522

DEV: Skip another flaky test on CI

---

app/assets/javascripts/discourse/app/components/post/menu.gjs
app/assets/javascripts/discourse/app/components/post/menu/button-config.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/unit/components/post-menu-test.gjs

- backport of #31734 to stable branch

DEV: Add APIs in the post menu to handle collapsed buttons (#31734)

---

plugins/automation/admin/assets/javascripts/admin/components/fields/da-choices-field.gjs
plugins/automation/app/models/discourse_automation/field.rb
plugins/automation/config/locales/client.en.yml
plugins/automation/db/post_migrate/20250319052218_rename_post_automation_fields.rb
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/post_created_edited.rb
plugins/automation/spec/models/field_spec.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb

1. **Multiselect Support for Choice Fields**
- Added a `multiselect` option to the choices field component
- Updated Field model to accept arrays as values for choices fields
2. **Post Content Feature Filtering**
- Added ability to filter posts based on content features:
- Posts with images
- Posts with links
- Posts with code blocks
- Posts with uploads
3. **Improved Group Filtering**
- Renamed `restricted_user_group` to `restricted_groups` to allow filtering by multiple groups
- Added `excluded_groups` to replace `ignore_group_members` which was complex for end users
- Renamed `restricted_groups` to `restricted_inbox_groups` for more specific PM filtering and clarity.
4. **Public Topics Filter**
- Added a "Public Topics" filter option that excludes all secure categories

FEATURE: enhance post created edited trigger in automation

---

app/assets/javascripts/discourse/app/instance-initializers/safari-15-deprecation.js
config/locales/client.en.yml

Ref https://meta.discourse.org/t/safari-15/358131

FEATURE: Introduce warning banner for Safari 15 deprecation

---

app/assets/javascripts/discourse/app/components/uppy-image-uploader.gjs
app/assets/stylesheets/common/base/upload.scss

[image-upload2.webm](https://github.com/user-attachments/assets/a57798a0-d5de-4879-ae6b-6dccea6e45ff)

UX: Show upload progress percentage for better feedback

---

plugins/automation/admin/assets/javascripts/admin/components/automation-list.gjs
plugins/automation/spec/system/smoke_test_spec.rb

We had some legacy code due to previous controller based automation

FIX: destroy automation not working

---

app/assets/javascripts/discourse/app/templates/login.hbs

- Add these params directly to stable since main refactored the template

DEV:add parameters to outlet args

---

app/controllers/users/omniauth_callbacks_controller.rb

- Move the change added in [this commit ](https://github.com/discourse/discourse/commit/df412608c8fa1ff396b02751590025ad7015484e)to stable

DEV:port split method from main to stable

---

app/models/concerns/category_hashtag.rb
lib/middleware/discourse_public_exceptions.rb
lib/svg_sprite.rb
lib/tasks/plugin.rake
lib/topics_filter.rb
plugins/automation/lib/discourse_automation/scriptable.rb

DEV: Fix `Lint/ShadowingOuterLocalVariable`

---

app/assets/stylesheets/admin/admin_report.scss

UI: storage stats content overflow

---

app/assets/javascripts/discourse/app/templates/login.gjs

DEV: Add outlet args to new login template

---

lib/plugin/instance.rb

Follow-up to af03873d37decf8dba4278fc38bfcde7747a79f4

DEV: Improvements to plugin API docs

---

app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/lib/viewport.scss

Usage:
```scss
@use "lib/viewport";
@include viewport.from(sm) {
...
}
@include viewport.until(lg) {
...
}
@include viewport.between(sm, lg) {
...
}
```
Values are inclusive on the lower bound, and exclusive on the upper bound.

DEV: Introduce new breakpoints

---

config/locales/server.en.yml
config/site_settings.yml

We are ready to start rolling this out to more
people and announce it on Meta.

UX: Make admin search setting visible

---

app/assets/javascripts/discourse/app/components/modal/create-account.gjs
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/lib/username-validation-helper.js

This aligns closer to how we are passing data through to the UserFieldsHelperClass https://github.com/discourse/discourse/pull/31670, and reduces coupling with the component itself.

DEV: refactor username validation helper class to take explicit args

---

app/assets/javascripts/discourse/ember-cli-build.js

Hopefully this will resolve some flaky qunit runs

DEV: Retry chunk loading from all chunks

---

app/assets/javascripts/discourse/app/initializers/discourse-bootstrap.js
app/assets/javascripts/discourse/ember-cli-build.js
app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

Bugfix is now released in ember

DEV: Drop backburner freedom patch

---

app/assets/stylesheets/admin/customize.scss
plugins/chat/assets/javascripts/discourse/components/chat/message-creator/new-group.gjs

This PR adjusts / fixes:
- theme/component page header buttons
- cmd+k chat modal cancel button

UX: Button fixes

---

app/assets/javascripts/discourse/app/components/modal/create-account.gjs
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/lib/password-validation-helper.js

This aligns closer to how we are passing data through to such helper classes (for example, the UserFieldsHelperClass https://github.com/discourse/discourse/pull/31670) and reduces coupling with the component itself.

DEV: refactor password validation helper class to take explicit args

---

app/assets/javascripts/discourse-markdown-it/src/index.js
app/assets/javascripts/discourse/app/components/reviewable-flagged-post.gjs
app/assets/javascripts/discourse/app/components/reviewable-post.gjs
app/assets/javascripts/discourse/app/components/reviewable-queued-post.gjs
app/assets/javascripts/discourse/app/components/reviewable-topic-link.gjs
app/assets/javascripts/discourse/app/lib/highlight-html.js
app/assets/javascripts/discourse/app/lib/highlight-watched-words.js
app/assets/javascripts/discourse/tests/unit/lib/highlight-watched-words-test.js
app/serializers/reviewable_score_serializer.rb
spec/serializers/reviewable_score_serializer_spec.rb

This change highlights watched words found in any reviewable posts.
- Have posts added to the review queue by triggering watched words.
- Check for edge cases that might cause the words to not be highlighted correctly.

FEATURE: Highlight watched words found in reviewables.

---

app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show.js
app/assets/javascripts/admin/addon/templates/customize-themes-show.gjs
spec/system/admin_customize_themes_spec.rb

Ensure that translations are loaded before checking input value.

FIX: flaky admin_customize_themes_spec

---

Gemfile.lock
app/assets/javascripts/pretty-text/addon/emoji/data.js

https://github.com/discourse/discourse-emojis/commit/d575425413019bf4d303cfd12d41f98f9bf332fe

DEV: discourse-emojis 1.0.39

---

spec/system/composer/prosemirror_editor_spec.rb

Example of a failure is here
https://github.com/discourse/discourse/actions/runs/14345676579/job/40214833933

DEV: Skip prosemirror flaky

---

script/bulk_import/generic_bulk.rb

Ensure `last_read_post_number` is set to the latest post for imported topic users with a `watching` notification level, even if they haven't engaged with the topic

FIX: Set last_read_post_number for imported watching topic users

---

app/assets/stylesheets/common/base/login-signup-page.scss

This PR removes Z index from labels on login input. It is no longer necessary.

UX: Remove z-index

---

app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/common/rich-editor/rich-editor.scss

This PR adds a border radius the prose mirror select node

UX: Border radius prose-mirror select node

---

app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/desktop/topic-post.scss

This PR uses a mixin for introducing border radius into quotes.

UX: Use mixin for quote border radius

---

app/assets/stylesheets/common/base/topic-post.scss

This PR adds the quote border styles to the right sheet in order to apply on mobile.

UX: Quick mobile fix for quote styles

---

script/assemble_ember_build.rb

This restores the fix in ae2bc240af434168aeebe73d550b1c979ca3a29b

PERF: Set `JOBS=1` for low memory build environment

---

app/assets/stylesheets/common/components/d-multi-select.scss

Fixes:
```
132 │ ┌   @keyframes pulse {
133 │ │     50% {
134 │ │       opacity: 0.5;
135 │ │     }
136 │ │   }
│ └─── nested rule
... │
141 │     animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
│     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
```

DEV: Fix scss deprecation warning

---

app/assets/javascripts/discourse/app/controllers/preferences/security.js
app/assets/javascripts/discourse/app/templates/preferences/security.gjs
app/assets/javascripts/discourse/tests/acceptance/user-preferences-security-test.js
config/locales/client.en.yml
spec/system/user_page/user_preferences_security_spec.rb

Simplified the language around remove password to be more clear, swapped out the button for a link.

DEV: Update verbiage around remove password modal, swap button for a link

---

app/assets/stylesheets/common/components/welcome-banner.scss
app/assets/stylesheets/desktop/components/header-search.scss
app/assets/stylesheets/mobile/topic-list.scss

The issues are easier to see when border-radius has been set.

UX: Header search tweaks

---

app/assets/stylesheets/common/base/header.scss

Follow-up to a0eeb83, this fixes the mixed declarations error

FIX: remove mixed declarations from header.scs

---

spec/requests/form_templates_controller_spec.rb

This reverts commit 4cd7ca677f69a18ab680c4b0ecac4a0d583d533b.

DEV: Revert "FIX: Flaky test for FormTemplatesController (#32351)"

---

app/assets/stylesheets/common/components/welcome-banner.scss

A fix for previous PR stylint eror

DEV: stylint fix

---

app/assets/stylesheets/common/select-kit/select-kit.scss
plugins/chat/assets/javascripts/discourse/components/chat-message-actions-desktop.gjs
plugins/chat/assets/stylesheets/common/chat-message-actions.scss

This PR adjusts some visual bugs occurring in the chat messages container

UX: Chat more message actions adjustments

---

app/assets/javascripts/discourse/app/templates/user.gjs
app/assets/javascripts/discourse/app/templates/user/collapsed-info.gjs

- Add before-user-profile-bio plugin outlet 
- Convert collapsed content into a component  (`CollapseInfo`) and pass any necessary arguments

DEV: add `before-user-profile-bio` plugin outlet and componentize `CollapseInfo`

---

app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/foundation/mixins.scss
plugins/chat/assets/stylesheets/common/chat-transcript.scss

This PR removes border radius from chat transcripts and blockquotes.

UX: Border radius removal

---

app/assets/stylesheets/common/base/compose.scss

Quick fix to error caused by previous PR.

UX: Fix content from not showing above composer

---

app/assets/stylesheets/common/rich-editor/rich-editor.scss

UX: rich editor placeholder edge case

---

app/assets/stylesheets/admin/admin_config_area.scss

UX: Better differentiation for dark-mode

---

lib/turbo_tests/runner.rb

This information is generally useful to know and it simple for us to
instrument.

DEV: Report runtime duration of each parallel test process

---

app/assets/stylesheets/common/base/search-menu.scss

UX: adjust search blurb text

---

app/assets/javascripts/discourse/tests/unit/lib/site-setting-matcher-test.js

These should have been part of #32461, but the file wasn't staged. 🙏

DEV: Add unit tests for SiteSettingMatcher

---

spec/requests/api/users_spec.rb

A user on meta was asking about this endpoint so we should add it to the
api docs.
See: https://meta.discourse.org/t/363641

DEV: Add /admin/users.json to the api docs

---

script/bulk_import/generic_bulk.rb

Extend the `import_site_settings` import step to enable the `migrated_site` flag if possible.
It also includes an escape hatch via the `SKIP_MIGRATED_SITE_FLAG_UPDATE` flag for cases where you really don't want to toggle it on.

DEV: Enable migrated_site flag during bulk imports

---

app/assets/javascripts/discourse/app/components/post.gjs
app/assets/javascripts/discourse/app/components/post/avatar.gjs
app/assets/javascripts/discourse/app/components/scrolling-post-stream.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/models/post.js
app/assets/javascripts/discourse/app/templates/topic.gjs
app/assets/javascripts/discourse/app/widgets/post-stream.js
app/assets/javascripts/discourse/app/widgets/post.js

This pull request introduces various enhancements and refactoring to the Glimmer Post Stream codebase, focusing on the integration and usage of `PluginOutlet` components, improved handling of post attributes, and the introduction of new properties and methods. Key changes include:
1. **`PluginOutlet` Integration**:
- Added `PluginOutlet` components across multiple files, such as `post.gjs`, `post/avatar.gjs`, and `post-stream.js`, to allow plugins to extend the functionality of posts, avatars, and metadata more effectively.
- Introduced `postOutletArgs` to pass structured arguments, enabling better customization and extensibility for plugins.
- Added PluginOutlet usage in `post/avatar.gjs` for avatar-related customizations.
2. **Refactored Post Attributes**:
- Enhanced handling of post …

DEV: Customization enhancements for the Glimmer Post Stream

---

lib/stylesheet/watcher.rb

A followup to https://github.com/discourse/discourse/pull/31416

DEV: Add a missing path to the stylesheet watcher

---

app/assets/stylesheets/common/select-kit/dropdown-select-box.scss
app/assets/stylesheets/common/select-kit/select-kit.scss

This PR scopes the float-in and float-up animations to DMenu only. It removes all previous changes to these two select kit stylesheets.

DEV: Remove select kit animation

---

app/assets/stylesheets/admin/settings.scss

This improves the new image uploader controls layout — this matches the layout the uploader uses in other contexts (user profile, logo config area) 
Before:
After:

UX: improve image uploader setting control layout

---

app/assets/javascripts/discourse/app/services/capabilities.js

This will allow us to have perfect consistency with CSS-based touch detection

DEV: Use media query for `capabilities.touch`

---

app/assets/javascripts/discourse/app/components/search-menu/results.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/recent-searches.gjs
app/assets/stylesheets/common/base/header.scss
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/common/components/welcome-banner.scss
app/assets/stylesheets/common/foundation/variables.scss
app/assets/stylesheets/desktop/components/header-search.scss
config/locales/client.en.yml

* change spacing to use consistent values
* change font weight and colours for search results
* updated copy for mobile to reflect the removal of the search icon (using native keyboard CTA now)
* results are full-width, in line with other dropdowns; noticable in hover effects
* trying to make sure all search results items are of equal height, were possible
* fixing missing `in-this-topic` context button
**Ignore the silly emoji in the screenshots on mobile – different problem, alrdy fixed on main**
| ![CleanShot 2025-04-23 at 12 11 19@2x](https://github.com/user-attachments/assets/324cf155-9832-4580-8d62-d49436813477) | ![CleanShot 2025-04-23 at 12 22 23@2x](https://github.com/user-attachments/assets/db9860a4-7e37-418f-85e9-9d68d5a5ab72) |
| …

UX: search CSS refactor + fixes

---

app/assets/stylesheets/common/base/search-menu.scss

FIX: header search mobile z-index issue

---

app/controllers/session_controller.rb
spec/requests/session_controller_spec.rb

In development mode, when 'DISCOURSE_DEV_ALLOW_ANON_TO_IMPERSONATE' is enabled, and going to /session/:username/become, we will now show an error message when trying to impersonate an inactive user.
This was not obvious why trying to impersonate a user wasn't working locally because I would hit the URL and be redirected back to the index without any error and without being logged in.

DEV: better error message when "becoming" an inactive user

---

app/assets/stylesheets/common/d-editor.scss

UX: minor style adjustments for experimental translation feature

---

spec/support/shared_examples/core_features.rb

This reverts eff31e0d42c535ee115317f5b63ff70d90097911.
While it passes our build, it breaks too many custom themes and plugins.

Revert "DEV: Speed up "having working core features" shared example by ~30%"

---

app/assets/stylesheets/admin/search.scss

UX: improve admin search focus states

---

.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/tests.yml

We have 8 and 16 cores runner now but 16 core runners are not quite
ready for prime time yet.

DEV: Update labels for our self hosted runners

---

app/assets/javascripts/discourse/app/components/modal/flag.gjs

This PR adds an appEvents trigger for 'flag:created'.

DEV: Add appEvents trigger for flag:created

---

plugins/chat/spec/system/user_chat_preferences_spec.rb

Im not convinced this will fix the flakyness, but this is better anyways.

DEV: attempts to use capybara choose

---

plugins/chat/spec/system/transcript_spec.rb

Attempts to not use within to make this spec less flaky.

DEV: flaky spec

---

app/models/theme.rb
app/models/theme_field.rb

https://meta.discourse.org/t/366482

DEV: Deprecate inline script tags for templates & initializers

---

app/assets/stylesheets/common/components/more-topics.scss
app/assets/stylesheets/desktop/components/more-topics.scss
app/assets/stylesheets/mobile/components/more-topics.scss

Trying to stabilize these styles, applied padding to match th elements, adjusted for border, removed unique hover/active styles
Before (desktop/mobile):
After:

UX: fix alignment of more topics nav pills

---

app/assets/stylesheets/common/components/user-card.scss

UX: fix overflow name in usercard

---

app/assets/stylesheets/admin/site-settings.scss

This PR slightly updates the unsaved changes popup in the admin panel.
| desktop | mobile | 
|--|--|
| ![CleanShot 2025-05-21 at 16 18 18@2x](https://github.com/user-attachments/assets/923468a5-49a3-431c-823f-b5e2b67b0585)| ![CleanShot 2025-05-21 at 16 20 30@2x](https://github.com/user-attachments/assets/297f7804-2fe0-431b-9091-4d914618481b)|
| desktop | mobile | 
|--|--|
| ![CleanShot 2025-05-21 at 16 18 32@2x](https://github.com/user-attachments/assets/d471aef4-df89-450c-ab3f-d11781959cf8) | ![CleanShot 2025-05-21 at 16 19 33@2x](https://github.com/user-attachments/assets/6db7f98f-93a5-4aeb-8e43-167da445fddd) |

UX: Update unsaved changes popup

---

app/assets/javascripts/discourse/app/controllers/topic.js
app/assets/javascripts/discourse/app/templates/topic.gjs
app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
app/assets/javascripts/discourse/tests/acceptance/topic-test.js
app/assets/stylesheets/common/base/topic.scss

Reverts discourse/discourse#32339
Will remove these changes in place of upcoming work we are doing in https://github.com/discourse/discourse/pull/32846

Revert "UX: Refactor the edit topic title UI"

---

app/assets/javascripts/discourse/tests/acceptance/composer-test.js

This is a follow up to 6da091a2b1aa4940fdfb6c42ed0c59fea17ab7e3

DEV: Improve tests for composer by checking for visibility

---

app/assets/stylesheets/common/base/menu-panel.scss

UX: Fix positioning of loading spinner

---

app/assets/javascripts/discourse/app/templates/signup.gjs
spec/system/social_authentication_spec.rb

UX: Improve intermediate state in social signup flow

---

app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/components/navs.scss
app/assets/stylesheets/common/foundation/mixins.scss

This PR changes the nav pill hover to match more closely with the active state.
**New**
**Old**

UX: Remove background from nav pill hover

---

config/site_settings.yml

Moving three site settings from <kbd>Navigation</kbd> to <kbd>Interface & layout</kbd>.

DEV: Move some site settings from Navigation to Interface

---

app/assets/javascripts/discourse/app/helpers/with-event-value.js

…to support `target.checked` cases

DEV: Add a path argument to `withEventValue`

---

spec/system/about_page_spec.rb

Adding tests for about page extra groups ordering.

DEV: Add tests for about page extra group ordering

---

config/locales/client.en.yml

This updates and adds short, human-friendly descriptions for commonly used color variables in the color palette UI. Mostly cleaned up the wording to make things easier to scan, so admins can quickly tell what each color is used for.
Internal: /t/154624

UX: Improve color descriptions

---

app/assets/stylesheets/admin/admin_base.scss
app/assets/stylesheets/common/foundation/base.scss

Previously they were only in the admin CSS bundle

DEV: Make `--space-#` variables available everywhere

---

app/assets/stylesheets/admin/customize.scss

UX: Scale down the theme title edit size

---

lib/onebox/engine/amazon_onebox.rb
lib/onebox/templates/amazon.mustache
spec/fixtures/onebox/amazon-og.response
spec/lib/onebox/engine/amazon_onebox_spec.rb

Fixes `&amp;` in onebox title and replaces with `&`.

FIX: correctly unescape title for amazon oneboxes

---

app/assets/stylesheets/common/base/onebox.scss

This PR changes the styling of oneboxes.
| New | Old |
|--|--|
|![CleanShot 2025-06-02 at 14 57 26@2x](https://github.com/user-attachments/assets/d2cf6b91-fb63-471e-8711-e9be2f6a285d)|![CleanShot 2025-06-02 at 14 58 03@2x](https://github.com/user-attachments/assets/b7eaa01d-041a-403d-84ec-c782e2aaa014)|

UX: Onebox changes

---

spec/system/search_shortcut_variation_spec.rb

Examples where the tests fail on reruns:
* https://github.com/discourse/discourse/actions/runs/15453248780/job/43500099718
* https://github.com/discourse/discourse/actions/runs/15457672316/job/43512812178?pr=33084

DEV: Skip flaky system tests

---

app/assets/stylesheets/admin/site-settings.scss

UX: Add z-index to the admin save all banner

---

app/helpers/application_helper.rb
app/models/theme.rb
app/models/theme_field.rb
app/views/layouts/application.html.erb
spec/models/theme_field_spec.rb

This reverts commit 33dc48b0daa0f6f75e6c0533edbe3f5df991c694.

Revert "DEV: Switch to `type="module"` for translation files (#33107)"

---

app/assets/javascripts/discourse/app/lib/discourse-template-map.js

Followup to d5ddaf05ee7dd03b14ec51564fca654a663aef3a

DEV: Correctly warn about inter-theme/plugin template clashes

---

migrations/lib/importer/shared_data.rb

Currently, the first two rows returned by `DiscourseDB#query_array` are silently dropped during the column size check in `DiscourseDB#load_mapping`. This happens because the rows object, while an enumerator, isn't fully compliant, it doesn't rewind during introspection. As a result, calls like `#first`, `#peek`, or `#any?` advance the iterator.
Ideally, we’d fix this by updating the `query_array` enumeration implementation. However, customizing the enumerator to be fully compliant would likely introduce unnecessary perf overhead for all use cases. So, this fix works around that limitation by building the map a little differently.

FIX: Stop silently dropping first two rows during `load_mapping`

---

app/assets/javascripts/discourse/app/components/modal/flag.gjs

This PR modifies `flag:created` appEvent trigger to pass `opts.message`.

DEV: Modify flag:created appEvent trigger

---

app/assets/stylesheets/common/base/menu-panel.scss

This border radius should not have been set to large.

UX: fix-border-radius

---

spec/system/post_stream_spec.rb

Reorganized the post reply and edit test to mitigate flakiness

DEV: Refactor flakey post stream spec

---

app/assets/javascripts/discourse/app/components/post-text-selection-toolbar.gjs
app/assets/javascripts/discourse/app/components/post-text-selection.gjs
app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/float-kit/addon/components/d-inline-float.gjs
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/mobile/topic-post.scss
spec/support/system_helpers.rb

This reverts commit 876dbe66299a7f0d3df71ae9064890a79d228321.

Revert "FIX: improves text selection of posts (#33143)"

---

app/assets/javascripts/float-kit/addon/lib/constants.js
app/assets/javascripts/float-kit/addon/modifiers/apply-floating-ui.js

Usage:
```gjs
<DMenu @updateOnScroll={{false}} />
```
https://floating-ui.com/docs/autoUpdate#ancestorscroll
No test as it's hard to test a scrolling behavior.

DEV: allows to disable ancestorScroll on float-kit

---

plugins/automation/admin/assets/javascripts/admin/components/fields/da-categories-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-choices-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-groups-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-tags-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-trust-levels-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-users-field.gjs
plugins/automation/test/javascripts/integration/components/da-categories-field-test.gjs
plugins/automation/test/javascripts/integration/components/da-choices-field-test.gjs
plugins/automation/test/javascripts/integration/components/da-groups-field-test.gjs
plugins/automation/test/javascripts/integration/components/da-tags-field-test.gjs
plugins/automation/test/javascripts/integration/components/da-trust-levels-field-test.gjs
plugins/automation/test/javascripts/integration/components/da-users-field-test.gjs

This is a follow-up to https://github.com/discourse/discourse/commit/299d28cb739e1a0b3ca41355269d93b4cf334d19 to apply it to more fields.

FIX: ensures empty fields don't store an empty array

---

app/assets/javascripts/discourse/app/templates/exception.gjs
app/assets/javascripts/discourse/app/templates/preferences-email.gjs

As part of removing template overrides from plugins and themes we need to introduce these pluginOutlets.

DEV: Add PluginOutlets to preferences-email and exception templates to remove template overrides

---

app/assets/javascripts/discourse/app/components/discovery/topics.gjs
app/assets/stylesheets/desktop/topic-list.scss

Followup 30b0e38877af703606042cf1a2997a9a06582c32

DEV: Remove old CSS class for empty topic filter

---

themes/horizon/common/common.scss
themes/horizon/javascripts/discourse/components/card/topic-activity-column.gjs
themes/horizon/javascripts/discourse/components/card/topic-replies-column.gjs
themes/horizon/javascripts/discourse/components/card/topic-status-column.gjs
themes/horizon/scss/categories-view.scss
themes/horizon/scss/hiddenstuff.scss
themes/horizon/scss/main.scss
themes/horizon/scss/topic-cards.scss
themes/horizon/spec/system/horizon_high_level_spec.rb
themes/horizon/spec/system/page_objects/components/user_color_palette_selector.rb
themes/horizon/spec/system/user_color_palette_selector_spec.rb

Keep Horizon up to date with the latest changes, so cutover
isn't as big.
https://github.com/discourse/horizon/compare/2bcd04d4f458c0672794cc9f09f2f7bad5fcccb1...c6000c996fe3b3693601c1c1ea18c770a5570d6a

DEV: Horizon sync for 2025-06-23

---

app/assets/javascripts/discourse/app/components/d-page-action-button.gjs

DEV: implement missing icons

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/database/intermediate_db/user_email.rb
migrations/lib/importer/steps/user_emails.rb
migrations/lib/importer/steps/users.rb

The import script will merge the users based on email

DEV: Allow multiple users to have the same email in IntermediateDB

---

app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js

DEV: Fix flaky AdminSearchDataSource tests

---

app/assets/javascripts/discourse/app/controllers/full-page-search.js
config/locales/client.en.yml
spec/system/page_objects/pages/search.rb
spec/system/search_spec.rb

FIX: add missing last read sort order to full page search

---

spec/requests/admin/config/site_settings_controller_spec.rb
spec/system/admin_flags_spec.rb

Follow-up to 40256ecc1c583f41346321654536feed6cd21f27

DEV: Fix broken test

---

app/assets/stylesheets/common/components/keyboard_shortcuts.scss

UX: Remove unnecessary border

---

app/assets/javascripts/discourse/app/components/topic-list/new-list-header-controls.gjs
app/assets/javascripts/discourse/app/models/nav-item.js
config/locales/client.en.yml

Adds some title labels and tweaks the main New tab title
label for the new new view.

UX: Title label adjustments for new new view

---

app/assets/stylesheets/common/base/topic.scss

This corrects a class target to be correct.

DEV: fix-patch

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/category_users.rb
migrations/lib/database/intermediate_db/category_user.rb
migrations/lib/importer/steps/category_users.rb
migrations/spec/lib/database/intermediate_db/category_user_spec.rb

This adds converter(Discourse-only, for now) and importer steps for `category_users`

DEV: Add `category_users` converter and importer steps

---

lib/system_themes_manager.rb
spec/lib/system_themes_manager_spec.rb

Ensure that the system themes are always enabled.

FIX: enforce system themes to be enabled

---

app/views/user_notifications/digest.html.erb
app/views/user_notifications/digest.text.erb
app/views/user_notifications/digest/_custom_header.erb
app/views/user_notifications/digest/_footer.html.erb
app/views/user_notifications/digest/_footer.text.erb
app/views/user_notifications/digest/_header.html.erb
app/views/user_notifications/digest/_header.text.erb
app/views/user_notifications/digest/_other_new_topics.text.erb
app/views/user_notifications/digest/_popular_posts.text.erb
app/views/user_notifications/digest/_popular_topics.text.erb

Adds partials for digest.text.erb and some comments for clarity.

DEV: Breaks up core digest.text.erb for readability

---

.github/workflows/tests.yml
app/assets/javascripts/discourse/tests/test-boot-ember-cli.js
lib/tasks/themes.rake

DEV: Run qunit tests and system specs for bundled themes

---

Gemfile
Gemfile.lock

let's see what shakes out in the next dependabot run

DEV: Unlock gem versions

---

Gemfile
Gemfile.lock

Adds high performance redis driver, see: https://github.com/redis-rb/redis-client
It is automatically configured.

PERF: switch redis driver to hiredis

---

plugins/discourse-ai/lib/embeddings/vector.rb
plugins/discourse-ai/lib/sentiment/post_classification.rb

Reduce concurrent generation of embeddings
Correct error reporting
Use Discourse ThreadPool

PERF: reduce embedding concurrent generation

---

app/assets/javascripts/discourse/app/components/sub-category-item.gjs

Added a new PluginOutlet around the SubCategoryItem template to allow us to customise the content from a theme.

DEV: Add sub-category-item plugin outlet

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/category_custom_fields.rb
migrations/lib/database/intermediate_db/category_custom_field.rb
migrations/lib/importer/steps/category_custom_fields.rb
migrations/spec/lib/database/intermediate_db/category_custom_field_spec.rb

This adds converter(Discourse-only, for now) and importer steps for `category_custom_fields`

DEV: Add `custom_category_fields` converter and importer steps

---

script/bulk_import/uploads_importer.rb

This change makes it easier to review failed uploads, especially downloadable ones, by standardizing `skip_reason` and adding a `skip_details` column to the uploads DB's `uploads` table for extended failure information.

FIX: Store context for failed uploads

---

app/assets/javascripts/discourse/app/lib/uppy/composer-upload.js
spec/system/composer_uploads_spec.rb

German translations will add a space before `...` which would trip our regex here.

FIX: ensures auto grid works in german

---

app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show-index.js

UX: Include JS in theme UI 'edited fields' list

---

app/assets/javascripts/discourse/app/components/user-menu/items-list.gjs
app/assets/javascripts/discourse/app/components/user-menu/menu.gjs
app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.gjs
app/assets/stylesheets/common/base/menu-panel.scss
themes/horizon/scss/header.scss

This PR:
- adds classname to the UL containing list of items in user menu
- removes bold font from profile buttons
- adjusts colors of icons & text on hover

UX: Multiple fixes addressing user menu panel

---

plugins/discourse-ai/assets/javascripts/discourse/components/ai-bot-conversations.gjs
plugins/discourse-ai/assets/javascripts/discourse/components/ai-persona-llm-selector.gjs
plugins/discourse-ai/assets/javascripts/discourse/controllers/discourse-ai-bot-conversations.gjs
plugins/discourse-ai/assets/javascripts/discourse/templates/discourse-ai-bot-conversations.gjs
plugins/discourse-ai/lib/ai_bot/entry_point.rb
plugins/discourse-ai/spec/system/ai_bot/homepage_spec.rb
spec/system/page_objects/components/select_kit.rb

1. FIX: persona selector should not show personas when PMs are disabled to persona
2. FEATURE: add support for llm and persona query params for ai home page

FEATURE: improvements to ai conversation page

---

app/assets/javascripts/discourse/tests/helpers/component-test.js
app/assets/javascripts/discourse/tests/integration/components/welcome-banner-test.gjs
plugins/discourse-calendar/test/javascripts/integration/components/upcoming-events-list-test.gjs

Also make some improvements to the component test helper
to allow stubbing the router service and also allowing for
anon users, since some components it is important to test
both of these paths.

DEV: Add initial component tests for WelcomeBanner

---

themes/horizon/javascripts/discourse/components/sidebar-new-topic-button.gjs
themes/horizon/spec/system/sidebar_topic_button_spec.rb

Removes unused helper for sidebar new topic button component

DEV: fix linting for unused helper

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/group_users.rb
migrations/lib/database/intermediate_db/group_user.rb
migrations/lib/database/intermediate_db/user_option.rb
migrations/lib/importer/steps/group_users.rb
migrations/spec/lib/database/intermediate_db/group_user_spec.rb

This adds converter(Discourse-only, for now) and importer steps for `group_users`

DEV: Add `group_users` converter and importer steps

---

app/assets/javascripts/discourse/app/models/post-stream.js
app/assets/javascripts/discourse/app/services/store.js

This reverts commit 38f75179669e5776b9a984d8b0dc10fc69c9eff4.

Revert "DEV: Reduce unnecessary UI updates when posts change (#33864)"

---

app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common/base/category-list.scss
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/base/header.scss
app/assets/stylesheets/common/base/sidebar-section-link.scss
app/assets/stylesheets/common/base/sidebar.scss
app/assets/stylesheets/common/base/user-badges.scss
app/assets/stylesheets/common/foundation/base.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/desktop/topic-list.scss

This pr adds:
- link color variable
- badge card background variable
- category boxes background color & border radius fix
- mention background color variable
- topic list / category list specific page padding
- uses `--d-hover` for table header hover
- header icon cleanup

DEV: Misc variable additions

---

script/assemble_ember_build.rb

Followup to fcaa068b8744fd106d4015ba5bedb935dc8ba228
Meta announcement: https://meta.discourse.org/t/376700

FEATURE: Fetch pre-build JS assets by default

---

app/assets/javascripts/discourse/app/components/discovery/filter-navigation-menu.gjs

Since we don't have native floatkit/dmenu functionality (yet) to
make the menu stick to the width of the element, this is a
stopgap solution to make sure the menu stays the same width
as the filter input whether resizing the window or hiding/showing
the menu.

UX: Resize dmenu width for filter on window resize

---

app/assets/javascripts/theme-transpiler/rollup-virtual-imports.js
app/models/theme.rb
spec/lib/theme_javascript_compiler_spec.rb

Followup to aa2fb29fa6cd5297bef37d0dc5312854f24c43af

FIX: JS/HBS connectors in themes

---

plugins/chat/app/controllers/chat/api/channel_thread_messages_controller.rb
plugins/chat/app/services/chat/list_channel_messages.rb
plugins/chat/app/services/chat/list_channel_thread_messages.rb
plugins/chat/app/services/chat/thread/policy/message_existence.rb
plugins/chat/lib/discourse_dev/thread.rb
plugins/chat/spec/requests/chat/api/channel_thread_messages_controller_spec.rb
plugins/chat/spec/services/chat/list_channel_messages_spec.rb
plugins/chat/spec/services/chat/list_channel_thread_messages_spec.rb
plugins/chat/spec/services/chat/thread/policy/message_existence_spec.rb

- Introduce a `max_page_size` option, allowing different behavior between controllers and SDK.
- Improve the contract (validations & helper method).
- Use `model` where possible.
- Extract message existence logic to a dedicated policy, allowing easier testing.
- Refactor specs to follow current guidelines/best practices.

DEV: Refactor `Chat::ListChannelThreadMessages` a bit

---

app/assets/stylesheets/common/components/more-topics.scss
app/assets/stylesheets/desktop/topic-list.scss
plugins/styleguide/assets/javascripts/discourse/components/sections/organisms/more-topics.gjs
plugins/styleguide/assets/javascripts/discourse/lib/dummy-data.js

A follow up to 911488bac12b13e332002e8bcd21b0fb6d1553b1

UX: Fix more-topics in the posters column case

---

plugins/discourse-assign/test/javascripts/acceptance/assigned-topic-test.js
plugins/discourse-assign/test/javascripts/acceptance/user-assignments-list-test.js
plugins/discourse-assign/test/javascripts/acceptance/user-private-messages-assigned-test.js

adds a missing cloneJSON, updates two tests to use only qunit-dom

DEV: Clean up d-assign tests

---

app/assets/stylesheets/common/base/_topic-list.scss

This PR corrects an incorrectly removed style. Visited topics on category topic lists will now show the correct styling of visited topics.

UX: Visited styles on categories topic list

---

themes/horizon/scss/main.scss

|Before|After|
|--|--|
|<img width="916" height="1676" alt="CleanShot 2025-08-11 at 17 00 48@2x" src="https://github.com/user-attachments/assets/81253a24-66f5-48ee-a5f9-c6509d144c31" />|<img width="902" height="1668" alt="CleanShot 2025-08-11 at 17 01 13@2x" src="https://github.com/user-attachments/assets/82926045-80cc-474f-928f-253cba2e10be" />|

FIX: Update small screen styles

---

spec/system/composer/prosemirror_editor_spec.rb

DEV: Skip a flaky system test for now

---

app/assets/stylesheets/common/base/search-menu.scss

|Before|After|
|--|--|
|<img width="1228" height="280" alt="CleanShot 2025-08-12 at 10 51 45@2x" src="https://github.com/user-attachments/assets/b7692866-b399-4316-8ba7-c12c4110cde8" />|<img width="1276" height="320" alt="CleanShot 2025-08-12 at 10 51 24@2x" src="https://github.com/user-attachments/assets/3574924d-6fb5-4f76-a569-6d6d369d014c" />|

UX: Correct missing padding

---

.github/instructions/copilot.instructions.md
bin/lint
lefthook.yml

- Align lefthook linting with linting CI does
- Call lefthook from bin/lint to handle linting (centralizes implementation)

DEV: align bin/lint to use lefthook

---

app/assets/javascripts/discourse/app/lib/quote.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/unit/lib/build-quote-test.js

DEV: Add a transformer for build quote

---

app/models/concerns/reports/associated_accounts_by_provider.rb
app/models/report.rb
config/locales/server.en.yml
spec/models/concerns/reports/associated_accounts_by_provider_spec.rb
spec/queries/reports/list_query_spec.rb

UX: Add admin report for associated accounts by login provider

---

plugins/discourse-ai/assets/javascripts/discourse/lib/ai-helper-suggestions.js
plugins/discourse-assign/assets/javascripts/discourse/components/topic-level-assign-menu.js
plugins/discourse-assign/assets/javascripts/discourse/initializers/extend-for-assigns.js
plugins/discourse-templates/assets/javascripts/discourse/services/d-templates.js

moving forward this will be an auto-fixable eslint rule

DEV: Update deprecated imports

---

app/models/color_scheme.rb
db/fixtures/600_themes.rb
spec/lib/stylesheet/manager_spec.rb
spec/serializers/site_serializer_spec.rb

UX: Don't make seeded palettes user-selectable

---

docs/ADMIN-QUICK-START-GUIDE.md

These were using invalid emoji code

fix emojis

---

app/assets/javascripts/discourse/app/components/discovery/filter-navigation-menu.gjs
app/assets/javascripts/discourse/app/lib/filter-suggestions.js
app/assets/javascripts/discourse/tests/unit/lib/filter-suggestions-test.js
config/locales/server.en.yml
lib/topics_filter.rb
spec/lib/topics_filter_spec.rb

Adds: 
users:sam,jane (filter by sam or jane)
users:sam+jane (filter by sam AND jane on same topic) 
group:a,b
group:a+b (ditto) 
No mix and match for users. 
Also add order:hot which was missing

FEATURE: user and group filters

---

script/import_scripts/base.rb
script/import_scripts/fluxbb.rb

Please see each individual commit for details.

Some fixes and updates for the FluxBB importer

---

app/assets/javascripts/discourse/app/loader-shims.js

in preparation for ember 6 upgrade

DEV: Add more ember/glimmer import shims

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/006-tag_synonyms.sql
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/tags.rb
migrations/lib/database/connection.rb
migrations/lib/database/intermediate_db/tag.rb
migrations/lib/database/intermediate_db/tag_synonym.rb
migrations/lib/importer/mapping_type.rb
migrations/lib/importer/steps/base/tags.rb
migrations/lib/importer/steps/tag_synonyms.rb
migrations/lib/importer/steps/tags.rb
migrations/spec/lib/database/intermediate_db/tag_spec.rb
migrations/spec/lib/database/intermediate_db/tag_synonym_spec.rb

This adds converter(Discourse-only, for now) and importer steps for tags

DEV: Add support for converting and importing `tags`

---

app/assets/javascripts/discourse/app/components/composer-editor.gjs
app/assets/javascripts/discourse/app/components/form-template-field/wrapper.gjs
app/assets/javascripts/discourse/app/lib/uppy/composer-upload.js
spec/system/admin_customize_form_templates_spec.rb
spec/system/composer/category_templates_spec.rb
spec/system/page_objects/pages/form_template.rb

- **FIX: form templates broke preview modal in admin section**
- **FIX: if topic templates are enabled uploads would break**

FIX: sites with form templates had broken uploads 

---

app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/common/components/buttons.scss
themes/horizon/common/color_definitions.scss

This PR uses primary button styles on the Discourse ID social auth button.

UX: Primary button styles on Discourse ID social button

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/badge_groupings.rb
migrations/lib/database/intermediate_db/badge_grouping.rb
migrations/lib/importer/mapping_type.rb
migrations/lib/importer/steps/badge_groupings.rb
migrations/spec/lib/database/intermediate_db/badge_grouping_spec.rb

This adds converter(Discourse-only, for now) and importer steps for `badge_groupings`

DEV: Add support for converting and importing `badge_groupings`

---

app/assets/javascripts/discourse/app/templates/preferences/account.gjs
app/assets/javascripts/discourse/app/templates/signup.gjs

Adding plugin outlets after signup and preferences fields to display extra instructions and additional markup in customizations.

DEV: Add plugin outlets after signup and preferences fields

---

app/assets/javascripts/discourse/app/components/post/meta-data/reply-to-tab.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/app/lib/user-menu/notification-item.js
app/assets/javascripts/discourse/app/templates/preferences/emails.gjs
app/assets/javascripts/discourse/tests/acceptance/notifications-test.js

- Backporting 3 changes from main to stable. Changes are associated with [this](https://github.com/discourse/discourse/pull/34492), [this](https://github.com/discourse/discourse/pull/34528) and [this](https://github.com/discourse/discourse/pull/34550/files) PRs.

Backport transformers to stable

---

app/assets/javascripts/admin/addon/components/site-setting.gjs
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.gjs

FIX: Don't show setting save/cancel buttons when selecting the current value

---

themes/horizon/common/common.scss
themes/horizon/scss/categories-view.scss
themes/horizon/scss/compatibility.scss
themes/horizon/scss/mobile-stuff.scss
themes/horizon/scss/topic.scss

Small CSS fixes for compatibility with popular components.

UX: Horizon compatibility fixes

---

app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/components/welcome-banner.gjs
config/site_settings.yml
spec/system/welcome_banner_spec.rb

Add a `const ALL_PAGES_EXCLUDED_ROUTES`. It lists the route names where elements are not supposed to be visible.

DEV: adds const ALL_PAGES_EXCLUDED_ROUTES

---

app/assets/javascripts/discourse/app/components/composer-container.gjs
app/assets/javascripts/discourse/tests/acceptance/assets-version-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/stylesheets/common/base/compose.scss
spec/system/page_objects/components/composer.rb

| Before | Now |
| <img width="2208" height="1220" alt="CleanShot 2025-08-29 at 18 19 35@2x" src="https://github.com/user-attachments/assets/3b42a44d-f67b-4333-8526-5b6724cb1d01" />  | <img width="2208" height="1224" alt="CleanShot 2025-08-29 at 18 17 44@2x" src="https://github.com/user-attachments/assets/671124f2-5ec8-4d32-86bb-d9aa9db24553" /> |
| <img width="706" height="1486" alt="CleanShot 2025-08-29 at 18 19 12@2x" src="https://github.com/user-attachments/assets/98860e44-b968-49ff-97bd-7a7abdc8e682" /> | <img width="706" height="1486" alt="CleanShot 2025-08-29 at 18 18 05@2x" src="https://github.com/user-attachments/assets/f76061cc-ea65-4762-a557-6b5d898663ec" />   |

UX: composer discard button styling + position

---

app/assets/stylesheets/common/base/sidebar.scss
app/assets/stylesheets/common/modal/modal-overrides.scss

| Current | Fix |
| <img width="684" height="754" alt="CleanShot 2025-09-01 at 13 42 06@2x" src="https://github.com/user-attachments/assets/507dbb85-abc7-493e-930a-44f461e24c23" /> | <img width="684" height="754" alt="CleanShot 2025-09-01 at 13 41 48@2x" src="https://github.com/user-attachments/assets/0f82cddc-1917-4abd-a79d-9dcc98834026" /> |

UX: layout adjustment for sidebar customisation modal on mobile

---

plugins/discourse-data-explorer/assets/javascripts/discourse/controllers/group-reports-show.js
plugins/discourse-data-explorer/assets/javascripts/discourse/routes/group-reports-show.js
plugins/discourse-data-explorer/assets/javascripts/discourse/templates/group-reports-show.gjs
plugins/discourse-data-explorer/test/javascripts/acceptance/run-query-test.js

Follow-up to 19acdbe3d92db752b8dffcb5d59a3b5204ac4c1e

FEATURE: Add run query param to group data explorer reports

---

themes/horizon/scss/topic-cards.scss

UX: Horizon > bring back unread number

---

plugins/discourse-lazy-videos/spec/lib/discourse_lazy_videos/crawler_post_end_spec.rb

Remnant from https://github.com/discourse/discourse/pull/34678

DEV: Remove remnant puts

---

plugins/discourse-ai/app/controllers/discourse_ai/admin/ai_llms_controller.rb
plugins/discourse-ai/assets/javascripts/discourse/components/ai-llm-editor-form.gjs
plugins/discourse-ai/config/locales/client.en.yml
plugins/discourse-ai/config/locales/server.en.yml
plugins/discourse-ai/spec/requests/admin/ai_llms_controller_spec.rb

FIX: LLM config must be valid before running a test

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
spec/system/ember_deprecation_spec.rb

- Enhance deprecation handling by tracking IDs in a set to prevent duplicate notices for the same issue. 
- Update deprecation message IDs to dynamically generate unique DOM identifiers. 
- Adjust the system specs to validate multiple deprecation messages and ensure accurate coverage.
This ensures that multiple critical warning notices are displayed for admins when necessary.

DEV: Improve critical deprecation warnings

---

app/assets/javascripts/admin/addon/components/schema-setting/editor.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-schema-setting/editor-test.gjs
config/locales/client.en.yml

This gives the ability to re-order items in a site setting `type: objects` form.
Topic: /t/162725

FEATURE: Ability to re-order objects in site setting type objects form

---

spec/requests/api/invites_spec.rb
spec/requests/api/schemas/json/invite_create_request.json
spec/requests/api/schemas/json/invite_create_response.json

This commit converts the api docs spec for the invite endpoint to use the new
json schema file format.

DEV: Update api docs spec for invite enpoint

---

plugins/discourse-ai/config/locales/client.en.yml

The toast shown needs copy update. 🥲

UX: Update copy

---

migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/database/intermediate_db/user_field.rb

Support newly added column on the `user_fields` core table

DEV: Sync IntermediateDB to support `user_fields.show_on_signup`

---

app/assets/javascripts/discourse/app/lib/transformer/registry.js
plugins/discourse-user-notes/assets/javascripts/discourse/components/modal/user-notes.gjs
plugins/discourse-user-notes/assets/javascripts/discourse/components/user-note.gjs
plugins/discourse-user-notes/assets/javascripts/discourse/initializers/enable-user-notes.gjs

- Adds a transformer to allow subtitle addition to the user notes form
- Adds plugin outlet to allow customization of each note in the modal form
- Rename a handler placement to place the avatar under the correct outlet

DEV: Update user note to allow customization

---

spec/requests/application_controller_spec.rb

Follow-up to a3e5a316740dea89836fe66c6b32c0a0a1692426 made 8 years ago

DEV: Add missing test case to `ApplicationController`

---

app/assets/javascripts/admin/addon/components/admin-logo-form.gjs
app/assets/javascripts/admin/addon/components/simple-list.gjs
app/assets/javascripts/discourse/tests/integration/components/simple-list-test.gjs

no more `@ember/-internals/metal` 😄 …in this component 😅

DEV: Convert `SimpleList` to glimmer

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/user_field_values.rb
migrations/lib/database/intermediate_db/user_custom_field.rb
migrations/lib/database/intermediate_db/user_field_value.rb
migrations/lib/importer/steps/user_custom_fields.rb
migrations/lib/importer/steps/user_field_values.rb

First pass at converting and importing user customer fields linked to user fields
Depends on https://github.com/discourse/discourse/pull/34739

DEV: Add support for converting and importing linked `user_custom_fields`

---

app/assets/javascripts/discourse/app/models/site.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-test.js
config/locales/server.en.yml
config/site_settings.yml
plugins/chat/spec/system/sidebars_spec.rb
spec/system/user_page/user_preferences_navigation_spec.rb
spec/system/viewing_sidebar_mobile_spec.rb

https://meta.discourse.org/t/367810

UX: Enable 'viewport based mobile mode' by default

---

config/locales/server.en.yml

```
Filter topics by in personal lists
```
to
```
Filter topics in personal lists
```
Thanks to ghpijffers on crowdin.

UX: Update strings for filter

---

app/assets/javascripts/discourse/app/components/topic-footer-buttons.gjs

Followup to 813b49473005bc21a649394a8719f3ff9b5fdce4

FIX: Topic footer dropdown/anonymousOnly null handling

---

spec/support/system_helpers.rb
spec/system/admin_color_palette_config_area_spec.rb

There are two parts to get this right:
- wait for the element
- wait for the element to have the color we expect
This should correctly handle this.

DEV: more resilient get_rgb_color

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/topic_allowed_users.rb
migrations/lib/database/intermediate_db/topic_allowed_user.rb
migrations/lib/importer/steps/topic_allowed_users.rb

This adds converter(Discourse-only, for now) and importer steps for `topic_allowed_users`

DEV: Add support for converting and importing `topic_allowed_users`

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/converters/discourse/steps/topic_users.rb
migrations/lib/database/intermediate_db/topic_user.rb
migrations/lib/importer/steps/topic_users.rb

This adds converter(Discourse-only, for now) and importer steps for `topic_users`

DEV: Add support for converting and importing `topic_users`

---

app/assets/javascripts/discourse/app/components/login-buttons.gjs
app/assets/javascripts/discourse/app/models/login-method.js
app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/mobile/login-signup-page.scss
config/locales/client.en.yml
lib/svg_sprite.rb

https://github.com/user-attachments/assets/e8a90b2a-100d-4b8e-87c3-a617a3b9be7c

UX: Add "works with" explanation for Discourse ID logins

---

migrations/lib/importer/executor.rb

Executing [PRAGMA OPTIMIZE](https://www.sqlite.org/pragma.html#pragma_optimize) ensures that the SQLite query optimizer has all the data it needs

DEV: Optimize IntermediateDB before running importer

---

plugins/discourse-ai/assets/javascripts/discourse/components/ai-feature-card.gjs

FIX: Don't link seeded LLMs on the features page

---

app/assets/javascripts/discourse/app/components/d-multi-select.gjs

Before this change, every update to the `searchTerm` tracked property would create a new promise in the `data` function. The issue was that once the debounce delay completed, only the most recent promise would be handled, leaving the other promises in a limbo state. This is problematic because we pass these promises to TrackedAsyncData, which registers a test waiter in the test environment. If promises are never settled, the test waiters will never complete, causing tests to hang indefinitely.

DEV: Fix `DMultiSelect` component creating one promise per input event

---

migrations/lib/common/topological_sorter.rb
migrations/lib/importer/step.rb
migrations/spec/lib/common/topological_sorter_spec.rb

This will be useful for steps like `site_settings` which need to run at the beginning.

DEV: Add priority handling and error management in `TopologicalSorter`

---

app/assets/javascripts/discourse/app/lib/public-js-versions.js
app/assets/javascripts/discourse/tests/unit/lib/load-script-test.js
lib/tasks/javascript.rake

- Remove broken uglifier require. It wasn't used anyway
- Remove entries for JS bundles which are now loaded via webpack/node_modules

DEV: Fix and run `javascript:update`

---

spec/system/category_localizations_spec.rb

Follow-up to 8a468904afaf0e355062c50d6adf351e8a8f749d

DEV: Fix flaky system test in category_localizations_spec.rb

---

app/views/layouts/_head.html.erb
config/locales/server.en.yml
config/site_settings.yml
spec/requests/application_controller_spec.rb

FEATURE: Introduce 'google_site_verification_token' site setting
