app/serializers/upload_serializer.rb
app/serializers/upload_thumbnail_serializer.rb
plugins/chat/plugin.rb
spec/requests/api/schemas/json/upload_create_response.json

Since [block accidental serialization of AR models](https://github.com/discourse/discourse/pull/27668) we are getting a 500 error in some cases with thumbnails. We can fix this by serializing the thumbnail, previously we just returned a raw `OptimizedImage` object.
Since thumbnails should probably be attached to the serializer in core, we no longer need to use `add_to_serializer` within the chat plugin to use thumbnails within chat message uploads.

DEV: serialize image upload thumbnail

---

app/assets/javascripts/discourse/app/components/create-invite-uploader.js

This component will soon be updated to remove the mixin entirely (and add a regression test for it). But for now, this is a quick fix to get it working again.

FIX: create-invite-uploader following uppy-upload mixin changes

---

app/models/topic_hot_score.rb
spec/models/topic_hot_scores_spec.rb

Handy for `discourse-ai` to inmediately generate summaries of these topics.

DEV: Trigger an event after updating topic hot scores

---

spec/services/flags/destroy_flag_spec.rb
spec/services/flags/toggle_flag_spec.rb
spec/services/flags/update_flag_spec.rb

Creating or updating flags generates global side effects. Sometimes it seems the state can leak from the flag specs.
This is probably related to the use of `fab!`. This PR replaces those calls with standard `let`s. While the overall performances of these tests will be a little less good, their state should not leak anymore.

DEV: Fix flaky specs related to flag services

---

app/controllers/svg_sprite_controller.rb
lib/svg_sprite.rb
spec/requests/svg_sprite_controller_spec.rb

instead of the first 200 which would "hide" some icons from the list when picking an icon for a badge or a sidebar link.
Internal ref - t/119652

FIX: bump the number of svg icons we return to first 500

---

app/models/user_password.rb
spec/models/user_password_spec.rb

Follow up to https://github.com/discourse/discourse/pull/28746.
I missed out trying to logging out and logging again with the new password after the test scenario I did in the original PR:
> Expire password via UserPasswordExpirer in console and attempt login which triggers the same flow as Step 3.
Currently, doing a logout/login would still trigger the password expired UI since setting the password never nulls out `password_expired_at`. 
I've added some tests, and did a manual test of the above-described flow to ensure the fix works. Any time we set a new password, it's expected that it would null out the `password_expired_at` timestamp.

FIX: setting new password should reset password_expired_at

---

app/models/top_topic.rb
spec/models/top_topic_spec.rb

We're expecting the period param to be something that neatly coerces into a symbol. If we receive something like a nested parameter, this will blow up.
This commit raises an InvalidParameters exception in the case of a non-stringy period parameter.

FIX: Don't error out on nested top topic period param

---

app/models/problem_check.rb
app/models/problem_check_tracker.rb
db/migrate/20241018031851_add_default_value_to_problem_check_trackers_target.rb
spec/models/problem_check_tracker_spec.rb

In #29169 we added a `NULLS NOT DISTINCT` option to the unique index on `problem_check_trackers`. This is to enforce uniqueness even when the `target` is `NULL`. (Postgres considers all `NULL`s to be distinct by default.)
However, this only works in PG15. In PG13 it does nothing.
This commit adds a default dummy string value `__NULL__` to `target`. Since it's a string, PG13 will be able to correctly identify duplicate records.
Adding a default value will lock the table and can cause issues on large tables, but the `problem_check_trackers` table is constrained by the number of problem check classes, and is in the ballpark of 10-100 rows.

FIX: Make problem check tracker unique constraint work on PG13

---

app/assets/javascripts/admin/addon/components/admin-user-field-item.js
spec/system/admin_user_fields_spec.rb

When adding or updating a custom user field to apply to all users (retroactively) we want to alert the admin that this will force all existing users to fill up the field before they are able to access the forum again.
However, we currently show this prompt when making changes only to other attributes on the custom field, i.e. the requirement hasn't changed.
This commit fixes that.

DEV: Don't ask admin to re-confirm 'for all users' when requirement didn't change

---

app/models/user.rb
config/site_settings.yml
spec/lib/user_name_suggester_spec.rb
spec/models/discourse_connect_spec.rb
spec/models/user_spec.rb

We're seeing errors in logs due to some sites setting the `reserved_usernames` setting to `nil`. This is causing multiple use cases upstream of `User#reserved_username?` to error out.
This commit changes from using the raw `#reserved_usernames` to using the `#reserved_usernames_map` helper which exists on list-type site settings. It returns an empty array if the raw value is `nil` or empty string.

FIX: Don't error out on empty reserved_usernames setting

---

app/controllers/session_controller.rb
app/controllers/users_controller.rb
spec/requests/session_controller_spec.rb
spec/requests/users_controller_spec.rb

When staff only mode is enabled - Discourse.enable_readonly_mode(Discourse::STAFF_WRITES_ONLY_MODE_KEY)
Staff members couldn't reset their password via the "forgot password" link.
This fixes it.
Internal ref. t/133990

FIX: staff only mode blocks admin password resets

---

app/assets/javascripts/discourse/app/services/restricted-routing.js
app/controllers/application_controller.rb
spec/system/user_page/user_preferences_profile_spec.rb

When a user is missing required fields, they are required to fill those up before continuing to interact with the forum. This applies to admins as well.
We keep a whitelist of paths that can still be visited in this mode: FAQ, About, 2FA setup, and any admin route for admins.
We concluded that admins should still be able to enable safe mode even with missing required fields. Since plugins etc. can potentially mess with the ability to fill those up.

DEV: Allow enabling safe-mode even when missing required fields

---

Gemfile
Gemfile.lock
lib/tasks/themes.rake

- Add concurrency when running on multisite clusters (default 10, configurable via THEME_UPDATE_CONCURRENCY env)
- Add a version cache for the duration of the rake task. This avoids duplicating work when many sites in the cluster have the same theme installed, and it is already up-to-date
- Updates output to be more concurrent friendly (all `puts`, no `print`)

PERF: Optimize themes:update task

---

app/assets/javascripts/discourse/app/components/pick-files-button.hbs
app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js
app/assets/javascripts/discourse/app/mixins/uppy-upload.js

These tweaks will help adoption of the non-mixin-based uppy patterns.
- Add `type:`  to default arguments list
- Update pick-files-button to support explicit element registration
- Make `cancelSingleUpload` a public API, and add `cancelAllUploads`
- Remove `isDestroyed` logic - it doesn't do anything outside a component
- Add `@bind` to `setup()`

DEV: UppyUpload improvements

---

.github/workflows/tests.yml

The aim of the flaky-tests-rerun system is to reduce the amount of time developers have to spend manually restarting CI jobs. That means that, to get the benefit, we need to run it for PRs as well as on `main`.
Our internal reporting system only looks at the data from runs on `main`, so that it's not polluted by legitimately failing tests in PRs.

DEV: Use flaky-test-retry in PRs as well

---

.github/workflows/tests.yml

The env needs to be '1', not 'true'

DEV: Correct flaky env from deb425f3

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
app/serializers/flag_serializer.rb
app/services/flags/create_flag.rb
app/services/flags/update_flag.rb
config/locales/client.en.yml
spec/requests/api/schemas/json/site_response.json
spec/services/flags/create_flag_spec.rb
spec/services/flags/update_flag_spec.rb

Allow admins to specify if the flag should be `auto_action_type`. If yes, then when an admin flags a post,  it is automatically actioned.
Meta: https://meta.discourse.org/t/allow-creation-of-custom-flags-which-auto-hide-content-similar-to-spam-and-inapproriate/329894

FEATURE: auto_action_type field for flags

---

app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
app/assets/stylesheets/common/admin/dashboard.scss
app/controllers/admin/dashboard_controller.rb
app/services/experiments/toggle.rb
config/locales/client.en.yml
config/routes.rb
lib/discourse_updates.rb
spec/lib/discourse_updates_spec.rb
spec/multisite/jobs_spec.rb
spec/services/experiments/toggle_spec.rb
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/pages/admin_new_features.rb

Toggle the button to enable the experimental site setting from "What's new" announcement.
The toggle button is displayed when the site setting exists and is boolean.
The feature item is displayed when the potentially required plugin is enabled.

FEATURE: allow admins to enable announced experimental features

---

app/controllers/admin/reports_controller.rb
app/models/concerns/reports/consolidated_page_views.rb
app/models/report.rb
config/locales/server.en.yml
spec/requests/admin/reports_controller_spec.rb

This commit brings back some reports hidden or changed
by the commit in 14b436923c5b582cea454b69441a28e16f2f191e if
the site setting `use_legacy_pageviews` is false.
* Unhide the old “Consolidated Pageviews” report and rename it
to “Legacy Consolidated Pageviews”
* Add a legacy_page_view_total_reqs report called “Legacy Pageviews”,
which calculates pageviews in the same way the old page_view_total_reqs
report did.
This will allow admins to better compare old and new pageview
stats which are based on browser detection if they have switched
over to _not_ use legacy pageviews.
**use_legacy_pageviews is false**
**use_legacy_pageviews is true**

FEATURE: Revive legacy pageview reports

---

app/assets/javascripts/float-kit/addon/components/d-menu.gjs
app/assets/stylesheets/mobile/float-kit/d-menu.scss
app/assets/stylesheets/mobile/list-controls.scss
app/assets/stylesheets/mobile/modal.scss

To prevent the DMenu on mobile to be too minimal, we're adding a minimum height of 45% viewport.
In addition, we're implementing a small grip element to highlight the pulldown/swipedown functionality that is already implemented, to close the menu.

UX: DMenu modal add grip and min-height

---

app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/desktop/modal.scss

follow-up fix to 4cb46ecb0fd41c183daeca4153cecf4487027cb5
this new css var was unintentionally un-setting max-height, so I'm including that max-height as the fallback for when the var is unset — also slightly clearer comment (indicating that it's been added unset: without a corresponding `--modal-max-height: x;` definition) 
before (too tall):
after (falls back to 80vh):

UX: fallback max-height for modal style

---

spec/services/flags/create_flag_spec.rb
spec/services/flags/destroy_flag_spec.rb
spec/services/flags/reorder_flag_spec.rb
spec/services/flags/toggle_flag_spec.rb
spec/services/flags/update_flag_spec.rb

The bug was introduced here https://github.com/discourse/discourse/pull/29258
It is very important for flags to reset to their original state because they are cached and shared between specs.

FIX: flaky flags spec after refactoring

---

db/migrate/20241022022326_remove_nulls_not_distinct_from_problem_check_trackers.rb

We added `NULLS NOT DISTINCT` to a unique index on `problem_check_trackers`.
This option is only available in PG15+. It does not in itself break PG13, but restoring a PG15+ backup to PG13 currently errors out. It seems this is an operation that's more common than we first thought.
This commit fixes that by removing the `NULLS NOT DISTINCT`.
We already have another, backwards-compatible approach to do the same thing in place, so this shouldn't change existing behaviour.

DEV: Remove NULLS NOT DISTINCT from problem check trackers

---

plugins/footnote/assets/stylesheets/footnotes.scss

Missing box-sizing property interfered with correct positioning, which caused horizontal scrolling.

UX: fix footnote causing horizontal scroll on narrow screens

---

app/models/problem_check_tracker.rb

As part of #29272 we made a unique index work on PG13 by introducing a dummy string to represent "NULL".
We missed one spot, leading to a potential for duplicate admin notices for problems without a target.
This fixes that.

FIX: Avoid duplicate problem admin notices

---

spec/services/flags/create_flag_spec.rb
spec/services/flags/destroy_flag_spec.rb
spec/services/flags/reorder_flag_spec.rb
spec/services/flags/toggle_flag_spec.rb
spec/services/flags/update_flag_spec.rb

Followup to https://github.com/discourse/discourse/pull/29325.
This PR adds comments to tell why we need to destroy created flags in specs once the examples have run.

DEV: Add comments in flags specs

---

app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/templates/login.hbs
spec/system/login_spec.rb

This restores the login-required page when the `experimental_full_page_login` and `login_required` settings are enabled

FIX: Bring back the login-required page for fullpage login

---

app/controllers/admin/config/flags_controller.rb
app/controllers/admin/site_settings_controller.rb
app/controllers/admin/users_controller.rb
app/services/experiments/toggle.rb
lib/service/runner.rb
plugins/chat/app/controllers/chat/api/channel_messages_controller.rb
plugins/chat/app/controllers/chat/api/channel_thread_messages_controller.rb
plugins/chat/app/controllers/chat/api/channel_threads_controller.rb
plugins/chat/app/controllers/chat/api/channel_threads_current_user_notifications_settings_controller.rb
plugins/chat/app/controllers/chat/api/channel_threads_current_user_title_prompt_seen_controller.rb
plugins/chat/app/controllers/chat/api/channels_controller.rb
plugins/chat/app/controllers/chat/api/channels_current_user_membership_follows_controller.rb
plugins/chat/app/controllers/chat/api/channels_read_controller.rb
plugins/chat/app/controllers/chat/api/channels_status_controller.rb
plugins/chat/app/controllers/chat/api/chatables_controller.rb
plugins/chat/app/controllers/chat/api/current_user_channels_controller.rb
plugins/chat/app/controllers/chat/api/current_user_threads_controller.rb
plugins/chat/app/controllers/chat/api/direct_messages_controller.rb
plugins/chat/app/jobs/regular/chat/auto_join_channel_batch.rb
plugins/chat/lib/chat_sdk/channel.rb
plugins/chat/lib/chat_sdk/message.rb
plugins/chat/lib/chat_sdk/thread.rb
plugins/chat/spec/plugin_helper.rb
plugins/chat/spec/requests/chat/api/current_user_threads_spec.rb
spec/lib/service/runner_spec.rb

Currently, when calling a service with its block form, a `#result` method is automatically created on the caller object. Even if it never clashed so far, this could happen.
This PR removes that method, and instead uses a more classical way of doing things: the result object is now provided as an argument to the main block. This means if we need to access the result object in an outcome block, it will be done like this from now on:
```ruby
MyService.call(params) do |result|
on_success do
do_something(result)
end
end
```
In the same vein, this PR introduces the ability to match keys from the result object in the outcome blocks, like we already do with step definitions in a service. For example:
```ruby
on_success do |model:, contract:|
do_something(model, contract)
end
```
Instead of …

DEV: Stop injecting a service result object in the caller object

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/javascripts/discourse/app/controllers/about.js
app/assets/javascripts/discourse/app/templates/about.hbs
app/assets/javascripts/discourse/tests/integration/components/about-page-test.gjs
config/locales/server.en.yml

The visitor stats on the /about page were previously showing as `NaN` immediately after enabling the `display_eu_visitor_stats` site setting because the stats for the /about page are cached and updated once every 30 minutes in a sidekiq job. The `NaN` would go away upon the next run of the relevant sidekiq job, but it's not good UX to display a cryptic `NaN` until the job runs. So, this PR ensures that the visitor stats is not displayed at all until the visitor stats is calculated and available.
Internal topic: t/128480.

FIX: Prevent 'NaN' display by hiding visitor stats on /about until they're ready

---

app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs
app/assets/javascripts/select-kit/addon/components/topic-notifications-button.gjs

Moves the user-tip from the topic-timeline notifications button to the one at the bottom of the topic page.
Three reasons:
1. new users are more likely to use the button that has the full text (and description) rather than the icon-only one
2. we hide the timeline button when scrolled all the way to the bottom of the page, and then the tip doesn't seems to be attached to anything
3. we might be removing the timeline button altogether in the near future

UX: Move "watching topic" user-tip to the other button

---

app/assets/javascripts/admin/addon/templates/config-about.hbs
config/locales/client.en.yml

This PR changes the description for the about config page so it contains a link to the /about page itself for easy access when editing the page.

UX: Add link to /about in the about config page

---

app/assets/javascripts/discourse/app/components/d-editor.hbs
app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/lib/textarea-text-manipulation.js
app/assets/javascripts/discourse/app/mixins/textarea-text-manipulation.js
plugins/chat/assets/javascripts/discourse/lib/textarea-interactor.js

Refactor of the `TextareaTextManipulation` from a Mixin to a native class
`discourse-templates` needs a [follow-up](https://github.com/discourse/discourse-templates/pull/84) to work&pass tests
Ultimately (ie after this first PR) the intent is to move all `DEditor` actions that rely on a `textarea` to be part of the `TextareaTextManipulation` class (or other separate abstraction).

DEV: refactor textarea text manipulation mixin

---

app/assets/javascripts/discourse/app/services/user-tips.js
app/assets/javascripts/discourse/tests/acceptance/user-tips-test.js
app/assets/javascripts/discourse/tests/integration/components/user-tip-test.gjs
spec/system/user_tips_spec.rb

…or a tip with the highest priority.
This regressed in 597ef1119536693ef0bc7fe799ff485047f9f6f7 where we got rid of `next()` calls, so we'd render the first tip we encounter.
The commit also adds a test and updates existing ones.

FIX: Show the last rendered user-tip

---

app/assets/javascripts/discourse/app/components/sidebar/footer.gjs

Reported here: https://meta.discourse.org/t/a11y-certain-buttons-remain-unlabeled/332053
These buttons lack accessible text, so they need aria labels

A11Y: add aria-labels to sidebar footer buttons

---

app/assets/javascripts/admin/addon/components/site-setting.hbs
config/locales/client.en.yml

Reported here: https://meta.discourse.org/t/a11y-certain-buttons-remain-unlabeled/332053
Currently the ok, cancel, and unmask buttons all lack accessible label because they're icon-only, this adds appropriate aria-labels

A11Y: Label site setting buttons

---

db/post_migrate/20241023041126_clear_duplicate_admin_notices.rb

In #29272 we added a backwards-compatible way to prevent duplicate **problem check trackers**. However, there was a mistake in the PR that would instead create duplicate **admin notices**. As a result, a number of admins now have multiple copies of the same admin notice in their dashboard.
The root cause was fixed in #29329, preventing new duplicates.
This PR is here to clean up notices that were already created.
Admin notices are meant to be ephemeral. Instead of going through hoops to delete duplicates and update the remaining notices' unstructured field with the correct `target`, it is a lot less error-prone to delete all notices and let the problem check system re-create them.
The real-time checks run every time the dashboard is loaded, so they will appear to never have been deleted. …

DEV: Clear duplicate admin problem notices

---

app/assets/javascripts/admin/addon/components/site-settings/compact-list.hbs
app/assets/javascripts/discourse/tests/integration/components/compact-list-test.js
app/assets/javascripts/select-kit/addon/components/selected-choice.js

In this PR we introduced mandatory fields for `group-list` https://github.com/discourse/discourse/pull/26612
The same solution should apply to `compact-list`.
Demo

FEATURE: mandatory fields for compact-list

---

app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
app/assets/stylesheets/common/admin/dashboard.scss
lib/discourse_updates.rb
spec/lib/discourse_updates_spec.rb

Bug introduced in this PR https://github.com/discourse/discourse/pull/29244
When the experiment toggle button was introduced, new features did not look right when the toggle button was not available.
In addition, the plugin name can be an empty string. In that case, information about new features should be displayed.
Before
After

FIX: visual regression for new features

---

app/models/user.rb
db/post_migrate/20241011080517_drop_password_columns_from_users.rb

Follows up on https://github.com/discourse/discourse/pull/28746 to drop password-related columns from the users table. These are now in the table user_passwords.

DEV: drop password-related columns from users table

---

app/assets/javascripts/discourse/app/components/user-tip.gjs
app/assets/javascripts/discourse/app/helpers/helper-fn.js

We were using a modifier purely for its lifecycle hooks - not to modify an element. This commit switches to using a helper, which provides a similar lifecycle, but without needing to be attached to an element.

DEV: Refactor user-tip to avoid unneeded wrapper element

---

app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.hbs
app/assets/javascripts/discourse/app/components/search-menu/results/assistant.hbs

When rendering the initial search options, we re-use the `AssistantItem` component. 
`AssistantItem` requires that you pass in the required params to define what _type_ of component it will be - category, tag, tag intersection, user, etc. This flexibility is nice, as we can just loop through all `@results` and pass in params, without having to predefine what _type_ of result it is. 
It is is not very good when it comes to seperating the html strucutre of each unique _type_. This is an example of the initial search results: 
You can see that both categories **and** tags are being rendered. The HTML strcuture looks like so: 
```html
<ul class="search-menu-assistant">
<li class="search-menu-assistant-item">
<a class="search-link" href="#"> CATEGORY </a>
</li>
<li …
```

DEV: Add `typeClass` to search `AssistantItem`

---

plugins/automation/admin/assets/javascripts/admin/controllers/admin-plugins-discourse-automation-edit.js
plugins/automation/admin/assets/javascripts/admin/controllers/admin-plugins-discourse-automation-new.js
plugins/automation/admin/assets/javascripts/admin/routes/admin-plugins-discourse-automation-index.js
plugins/automation/admin/assets/javascripts/admin/routes/admin-plugins-discourse-automation-new.js
plugins/automation/admin/assets/javascripts/admin/templates/admin-plugins-discourse-automation-edit.hbs
plugins/automation/admin/assets/javascripts/admin/templates/admin-plugins-discourse-automation-index.hbs
plugins/automation/admin/assets/javascripts/admin/templates/admin-plugins-discourse-automation-new.hbs
plugins/automation/admin/assets/javascripts/admin/utils/automation-placeholder.js
plugins/automation/app/controllers/discourse_automation/admin_automations_controller.rb
plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/assets/stylesheets/common/discourse-automation.scss
plugins/automation/config/locales/client.en.yml
plugins/automation/config/locales/server.en.yml
plugins/automation/db/migrate/20241016174732_remove_name_requirement_from_automations.rb
plugins/automation/spec/models/automation_spec.rb
plugins/automation/spec/system/error_spec.rb
plugins/automation/spec/system/new_automation_spec.rb
plugins/automation/spec/system/smoke_test_spec.rb

This simplifies the workflow of creating automations and gives scripts and their descriptions more space. It also removes the "blank" state before any scripts are created and instead shows the grid of scripts to get started. 
If you don't have an automation created yet, we'll present you with a grid of script options for browsing. 
This is also filterable:
When you select a script, you get the edit form:
and when you already have scripts, nothing has changed... when you click "create" from here, you're presented with the grid of script options again.

UX: simplify and shorten new script flow for automations

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
config/locales/client.en.yml

Simplified wording for `auto_action_type` flags.

FIX: reword auto action type field for flags

---

app/assets/javascripts/discourse/app/components/d-toggle-switch.gjs

move the template to the bottom, inline `checked`, remove unnecessary `template-lint-disable`

DEV: Clean up d-toggle-switch

---

bin/docker/boot_dev

When attempting to [set up the Docker development environment](https://meta.discourse.org/t/install-discourse-for-development-using-docker/102009), I was seeing the following error when running `d/boot_dev --init`:
```
ActiveRecord::NoDatabaseError: We could not find your database: discourse_development. Available database configurations can be found in config/database.yml. (ActiveRecord::NoDatabaseError)
```
Running `db:create` before the `db:migrate` fixed this issue for me. It appears to be safe to run `db:create` even if the database already exists, running `d/rake db:create` locally shows an info message at the database already exists, but doesn't exit with an error.
If you already have a Docker dev environment setup, you will need to run `docker stop discourse_dev && docker rm …

DEV: Create the DB before migration in the Docker environment

---

app/assets/javascripts/discourse/app/components/categories-only-optimized.hbs
app/assets/javascripts/discourse/app/components/categories-only-optimized.js
app/assets/javascripts/discourse/app/components/discovery/categories-display.gjs
app/assets/javascripts/discourse/app/components/parent-category-row-optimized.hbs
app/assets/javascripts/discourse/app/components/parent-category-row-optimized.js
app/assets/javascripts/discourse/app/templates/mobile/components/categories-only-optimized.hbs
app/assets/javascripts/discourse/app/templates/mobile/components/parent-category-row-optimized.hbs
app/assets/stylesheets/mobile/topic-list.scss
app/models/category_list.rb
app/models/category_page_style.rb
config/locales/client.en.yml
spec/requests/categories_controller_spec.rb

The new style is called `categories_only_optimized` and it is designed to show only the parent categories, without any subcategories. It also implements pagination, so on first load it loads only the first 25 categories and the rest as the user scrolls to the bottom of the page.
This works best for communities with many categories (over a thousand). Communities with too many categories might still have issues in other areas.
Mobile:
Desktop:

FEATURE: Introduce an optimized style for category page

---

app/assets/javascripts/discourse/app/lib/class-prepend.js
app/assets/javascripts/discourse/tests/unit/lib/class-prepend-test.js

DEV: Allow parent method to be called using `super.` in `modifyClass`

---

app/assets/javascripts/discourse/app/components/d-modal.gjs

This causes some issues with different devices. We want to test the side effects of removing this.

FIX: Remove scroll events for mobile modals

---

app/controllers/categories_controller.rb
spec/requests/categories_controller_spec.rb

This endpoint used to be a GET request, but was changed to POST to allow larger payloads.
Follow up to commit ebc1763aa5c5224b42ef79680a5d1839ebbd5a85.

FIX: Skip CSRF check for POST /categories/search

---

app/models/web_hook.rb
app/models/web_hook_event_type.rb
config/locales/client.en.yml
db/fixtures/007_web_hook_event_types.rb
db/migrate/20241024093027_remove_category_experts_web_hook_event_types.rb
spec/models/web_hook_event_type_spec.rb

When creating webhooks on a site without the Discourse Category Experts plugin installed, the `category_experts_unapproved_event` and `category_experts_approved_event` webhook events are getting automatically added to webhooks without a way to disable them.
The `category_experts_unapproved_event` and `category_experts_approved_event` webhook events are associated with the Discourse Category Experts plugin so I am moving these webhook events into the Category Experts plugin.
[Here is the PR](https://github.com/discourse/discourse-category-experts/pull/167) that adds the webhook events into the Category Experts plugin.
This PR deletes Category Experts plugin specific webhook event types added into core:
* [Added Category Experts approved WebHook …

 DEV: Delete plugin specific webhook event types

---

app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-collection.hbs
app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-collection.js
app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/components/add-pm-participants.scss
app/assets/stylesheets/mobile/modal-overrides.scss

https://github.com/discourse/discourse/pull/26784 adds the scroll lock in the modal which renders this second scroll lock for SK component redundant. Having it there in fact causes issues on iPads, where it isn't necessary. The modal scroll lock is limited to mobile devices only: 
https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/components/d-modal.gjs#L46-L49

FIX: remove redundant body scroll lock

---

db/migrate/20120427154330_create_vestal_versions.rb
db/migrate/20120924182000_add_hstore_extension.rb
db/migrate/20130127213646_remove_trust_levels.rb
db/migrate/20131014203951_backfill_post_upload_reverse_index.rb
db/migrate/20131210181901_migrate_word_counts.rb
db/migrate/20140929204155_migrate_tos_setting.rb
db/migrate/20141014191645_fix_tos_name.rb
db/migrate/20150709021818_add_like_count_to_post_menu.rb
db/migrate/20150728210202_migrate_old_moderator_posts.rb
db/migrate/20150729150523_migrate_auto_close_posts.rb
db/migrate/20150731225331_migrate_old_moved_posts.rb
db/migrate/20150822141540_fix_migrated_hosts.rb
db/migrate/20160407160756_remove_user_firsts.rb
db/migrate/20160627104436_use_https_name_change_in_site_settings.rb
db/migrate/20161202034856_add_uploads_to_categories.rb
db/migrate/20180521190040_allow_null_ip_topic_link_click.rb
db/migrate/20190123171817_drop_queued_posts.rb
db/migrate/20190402142223_disable_invite_only_sso.rb
db/migrate/20190503180839_remove_like_count_from_post_menu.rb
db/migrate/20190508141824_drop_claimed_by_id.rb
db/migrate/20190908234054_migrate_post_edit_time_limit.rb
db/migrate/20191025005204_amend_oauth2_user_info_index.rb
db/migrate/20200429095035_migrate_image_url_to_image_upload_id.rb
db/migrate/20210127140730_undo_add_processed_to_notifications.rb
db/migrate/20230224225129_backfill_svg_sprites.rb
db/migrate/20230308042434_backfill_auto_bump_cooldown_days_category_setting.rb
db/post_migrate/20240612073116_swap_field_type_with_field_type_enum_on_user_fields.rb
db/post_migrate/20240912210450_delete_anonymous_users_from_directory_items.rb
db/post_migrate/20241023041126_clear_duplicate_admin_notices.rb

We are adding the Rails/ReversibleMigrationMethodDefinition cop to `rubocop-discourse`, this change resolves existing errors under this rule.
All migrations before the last irreversible migration will now raise irreversible migration error as well on `down`.

DEV: resolve Rails/ReversibleMigrationMethodDefinition errors

---

app/assets/javascripts/discourse/app/lib/textarea-text-manipulation.js

Using execCommand to replace the entire contents of the textarea is very slow for larger posts (it seems the browser does a reflow after every 'virtual keypress').
This commit updates the `maybeContinueList()` function to be more surgical when removing the bullet. Now it only selects & removes the characters which actually need to be deleted
Similar to a7cd2207048bfac3e76fafdf47e259cd1b391352

PERF: Update `maybeContinueList` to avoid replacing the entire post

---

app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md
spec/system/keyboard_shortcuts_spec.rb

Add `disableDefaultKeyboardShortcuts` function to the plugin API to allow for disabling [default bindings](https://github.com/discourse/discourse/blob/e4941278b2055285d0e83330732ffb63f285b86e/app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js#L49). 
This function is used to disable a "default" keyboard shortcut. You can pass an array of shortcut bindings as strings to disable them.
**Please note that this function must be called from a pre-initializer.**
Example:
```js
api.disableDefaultKeyboardShortcuts(['command+f', 'shift+c']);
```
- Added system spec, displaying intended behavior

DEV: Add `disableDefaultKeyboardShortcuts` plugin API to disable default keyboard shortcuts

---

app/models/reviewable_queued_post.rb
spec/models/reviewable_queued_post_spec.rb
spec/system/reviewables_spec.rb

Followup 9762e6575841889d50275cb6026e4482d8091857
When we added the Revise... option for posts/new topics
in the review queue, which sends a PM to the user, we used
`SystemMessage.create_from_system_user`, which always sends
the PM from the system user. However, this makes it so if the
user replies to the PM, which they are encouraged to do,
no one will see it unless they actively monitor the system inbox.
This commit changes it so `SystemMessage.create` is used,
which uses the `site_contact_username` and `site_contact_group`
site settings as participants in the sent PM. Then, when the
user replies, it will send to that inbox instead.
If `site_contact_username` is blank, the system user is used.

FIX: Use site contact user + group for Revise... review action

---

Gemfile.lock

Running a local dev environment on an Intel Mac with MacOS 15 causes `Gemfile.lock` to be updated with the latest Darwin kernel version number every time `bundle install` is run.
This PR adds `x86_64-darwin-23` and `x86_64-darwin-24` to the `PLATFORMS` section, to avoid this.

DEV: Update Gemfile.lock for MacOS 15 on x86

---

app/assets/stylesheets/common/components/user-card.scss
app/assets/stylesheets/desktop/components/user-card.scss

follow-up to https://github.com/discourse/discourse/commit/74bb520877161bc04cd11a338949c85c5ab9db80
that commit applies focus on usercards in more situations, but sometimes this can create an undesirable focus ring on mobile 
this PR removes the ring from mobile, where typically other assistive technologies are used instead of keyboard nav
before:
after:

UX: limit user-card username focus ring to desktop

---

plugins/poll/assets/stylesheets/common/poll.scss

Extending @merefield's PR a bit (https://github.com/discourse/discourse/pull/28593) 
This gives the ranked choice polls a distinctive preview style, rather than the default radio buttons. This more closely mimics the button styles in the live post: 
The live poll: 
Preview before: 
Preview after:

UX: Give ranked choice polls distinctive bullets in preview

---

app/assets/javascripts/admin/addon/components/admin-config-area-card.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/about.gjs
config/locales/client.en.yml

Follow up to #29387. 
Changes:
* added a `description` to the config area card component
* updated strings

UX: Add description config area card

---

app/controllers/admin/config/site_settings_controller.rb
lib/discourse_plugin_registry.rb
lib/plugin/instance.rb
lib/site_setting_extension.rb
spec/lib/site_setting_extension_spec.rb

In this PR, we defined the ability to group site settings by area - https://github.com/discourse/discourse/pull/28570
Plugins should be able to register in their own areas.

DEV: allow the plugin to register valid site setting areas

---

app/assets/javascripts/discourse/app/components/d-editor.js

A common pattern in the industry for bypassing smart lists is detection of
the shift key.
This information is not available in the "beforeinput" event but it always
fires afer keydown, so we track if shift is pressed on keydown.

FEATURE: do not insert smart list if SHIFT+Enter is pressed

---

app/assets/stylesheets/desktop/post-action-feedback.scss

The z-index of the copy link effect on desktop was too high, making it appear from behind composer and drawer in certain screen layouts. It only needs to be higher than the timelime.

UX: lower copy link z-index

---

app/assets/javascripts/discourse/app/components/topic-list/topic-cell.gjs
app/assets/javascripts/discourse/app/components/topic-list/topic-list-item.gjs

- Fixes the topic focus style for Glimmer components.
During work on [PR #29420](https://github.com/discourse/discourse/pull/29420), I noticed that the topic focus feature is broken for Glimmer components. This PR attempts to address this issue. 
My initial approach duplicates events to achieve the fix, I think the current approach can be polished further by reusing the `<TopicCell>` component for a more streamlined implementation.
BEFORE:
https://github.com/user-attachments/assets/d4b7a0f0-44de-41e1-960e-76489accbca1
AFTER:
https://github.com/user-attachments/assets/1689d5f8-0692-44ef-8a56-cbd66a91ce93

FIX: Missing glimmer topic list focus actions on mobile

---

app/assets/javascripts/discourse/app/components/reviewable-item.hbs

The block form of `{{#component` is not supported by Glint tooling. They recommend using this `{{#let`-based syntax to achieve the same result

DEV: Update dynamic component hbs syntax

---

app/assets/javascripts/discourse/app/components/topic-timeline/container.hbs

UX: Remove the admin menu button from expanded mobile timeline

---

lib/service/base.rb
lib/service/contract_base.rb
plugins/chat/app/services/chat/create_message.rb
plugins/chat/app/services/chat/search_chatable.rb
plugins/chat/app/services/chat/update_message.rb

We decided to make contracts immutable once their validations have run. Indeed, it doesn’t make a lot of sense to modify a contract value outside the contract itself.
If processing is needed, then it should happen inside the contract itself.

DEV: Make service contracts immutable

---

plugins/chat/assets/stylesheets/common/chat-channel-members.scss

Improves layout of channel members list with user status emojis.
Before:
After:

UX: fix emoji spacing in chat members user status

---

bin/unicorn

Our sprockets-based locale pipeline correctly `depends_on` client.*.yml files which already exist. But sprockets does not provide a way to watch for the creation of new files matching a certain path. This commit works around that limitation by adding the set of client.*.yml files to our global cache-clearing logic

DEV: clear asset cache when plugins add/remove client.*.yml files

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs

Moved the BackButton component outside the admin-config-area wrapper to address layout issues.

UX: Move BackButton outside admin-config-area to prevent unintended wrapping

---

app/assets/stylesheets/mobile/reviewables.scss

The "No" button for flagged posts was a different
size on mobile
Before:
After:

UX: Fix No button on review queue on mobile

---

docs/ADMIN-QUICK-START-GUIDE.md

Added the missing word 'done' in the 'Adjust other customizations' section of the guide.

FIX: Missing word 'done' in admin quick start guide

---

config/locales/server.en.yml

When the must_approve_users setting is enabled, the "arrive at topic" invite option is not shown. They have to wait for approval and are sent an email when they are allowed it, and then arrrive on the site home page upon login.

edited description of must_approve_users

---

jsconfig.json
script/build_jsconfig.rb

Check *.hbs, but skip 'standalone' template. This gives us working glint in colocated templates, without a ton of errors from the standalone templates which Glint can't map to the relevant component/controller

DEV: Configure glint hbs checking

---

app/controllers/user_badges_controller.rb

- There was no change in the functionality introduced by this PR. I split up how to get the grant opts so a plugin could pass more opts when a badge is granted.

DEV:refactor user badges create to get grant opts from method

---

app/models/report.rb
spec/models/report_spec.rb

Followup bd4e8422fe46f5eff63fdc073f480ec948b0e1f8
In the previous commit, we introduced the `page_view_legacy_total_reqs`
report. However this was not tested properly, and due to a typo
the report returned no data.
This commit fixes the issue and adds a spec to catch this.

FIX: Blank "Legacy Pageviews" report showed no data

---

app/assets/javascripts/admin/addon/components/admin-config-area-cards/about/general-settings.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/about.gjs
app/assets/javascripts/admin/addon/routes/admin-config-about.js
app/controllers/admin/config/about_controller.rb
config/locales/client.en.yml
spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/admin_about_config_area_general_settings_card.rb

This PR adds a new "Community title" field to the about config page. This field controls the `short_site_description` setting, which is shown in the browser tab for key pages such categories pages and topic lists.
Screenshot:
Internal topic: t/140812.

FEATURE: Add 'Community title' field to about config page

---

script/bulk_import/base.rb
script/bulk_import/generic_bulk.rb

This pull request implements bulk import for `topic_voting_votes`.
**Key Changes:**
- Implemented bulk import functionality specifically for `topic_voting_votes`.
- Updated the method name from `import_votes` to `import_post_voting_votes` for improved clarity and maintainability.
**Additional Context:**
- Ensured compatibility with existing Discourse infrastructure.
- No UX/UI changes were made, so no screenshots are included.
Please review and let me know if there are any questions or further improvements needed.

DEV: Add import support for Topic Voting plugin

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/sidebar.scss
app/assets/stylesheets/desktop/menu-panel.scss
plugins/chat/assets/stylesheets/common/base-common.scss
plugins/chat/assets/stylesheets/common/chat-composer.scss
plugins/chat/assets/stylesheets/common/chat-height-mixin.scss
plugins/chat/assets/stylesheets/desktop/chat-index-full-page.scss

This introduces a new CSS var, `--main-outlet-offset` alongside the existing `--header-offset`. 
- `--header-offset` remains as before, giving in CSS the header's offset from the top of the viewpoint
- `--main-outlet-offset` includes `--header-offset` plus any elements that are above the main outlet and below the header, for example, elements in the `below-header` outlet
This fixes issues with the sidebar overflowing on sites with some theme components. And incompatibilities between said theme components and chat. 
Before/After (notice the missing bottom of chat and sidebar in the before screenshot)

DEV: Refactor header offset calculations

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/stylesheets/common/base/header.scss
app/assets/stylesheets/common/components/footer-nav.scss
spec/system/header_spec.rb

Docking is a leftover from older header code, it looks like it is no longer used in the app. This helper was registering a scroll event listener to check if the header should be docked or not. Initially, a "docked" class was added to the body element. This class persisted through the lifecycle of the app and the scroll event was doing no useful work.
Some older themes may still use it in CSS, that will cause a regression, from a quick look at existing code, the surface area should be small (2-3 themes). It's worth removing the event listener for performance reasons. We could possibly add the class "docked" statically to the body element, but it's redundant. It's best to clean up the relevant CSS in themes, where applicable.

DEV: Remove body docked class and its scroll event listener

---

config/locales/server.en.yml

This has been unused since 709fa24558ec7da797b334d0076613494e9bf408.

DEV: Remove unused translation string

---

config/site_settings.yml

This setting is not ready for use, we should hide it from the UI.

DEV: Hide experimental lightbox setting

---

app/assets/javascripts/discourse/app/components/topic-list/topic-link.gjs
app/assets/javascripts/discourse/app/helpers/topic-link.js

This reverts commit 72a53894592cf07bb206a949f703193a486b654c.
Despite advice from a customer's accessibility team, we've had a couple users mention that labeling these as headings is actually helpful. 
https://meta.discourse.org/t/a11y-topic-lists-do-not-have-headings-for-each-topic/332050
Maybe this can be an optional feature at some point, but until we have better accessibility controls and options this seems like the best path to take.

REVERT:  "A11Y: topic list links should not be headings (#27700)"

---

app/models/topic.rb
spec/models/topic_spec.rb

When using the `digest_suppress_tags` site setting to list some tags that should be removed from the digests, if there was a topic that had one suppressed tag and other regular tag(s), it would be duplicated in the summaries.
https://meta.discourse.org/t/multiple-repeated-summary-mail-entries/296539
Thanks to @scossar for [figuring it out](https://meta.discourse.org/t/multiple-repeated-summary-mail-entries/296539/30).

FIX: duplicate topics in digests / summaries

---

config/locales/client.en.yml

Per https://meta.discourse.org/t/formatting-text-in-discourse-documentation-and-uis/324637

UX: Use correct case for "Add Flag" button

---

app/models/translation_override.rb
spec/models/translation_override_spec.rb

Some of our translations are HTML and have `target='_blank'`
included, we should allow the same when sanitizing input for
translation overrides.

FIX: Allow `target` attribute in translation overrides

---

app/assets/javascripts/service-worker.js.erb

Follow up to #29388 - when there are no clients in focus, we should take the first visible client as the primary tab.
Example with chat desktop sounds:
You have 2 Discourse tabs open, but then switch to another app (ie. <kbd>cmd</kbd> + <kbd>tab</kbd>). Now the Discourse tab is still visible but not in focus, therefore if a chat message is received it won't play the sound despite being recently active.
With this change the user can switch between apps and we still attempt to play the sound in the visible tab, even when the browser is not in focus.

DEV: allow non focused tab to be primary tab in service worker

---

db/migrate/20241025045928_add_invites_link_to_sidebar.rb

Meta topic: https://meta.discourse.org/t/stumped-about-launcher-rebuild-app-error-process-pid-2096/333876?u=osama.
Follow up to https://github.com/discourse/discourse/pull/29448.
The migration that adds the invite link to the sidebar determines the position of the link by looking up the max position that a primary link has and inserts the invite link at the max position plus 1. This approach works fine for most sites, however, sites that have deleted all primary links from the sidebar will fail because the max position will be `nil` which blows up the migration.
This PR addresses this edge case by falling back to looking up the min position of secondary links,    or to zero if there're also no secondary links, and then inserts the invite link at the min position minus 1.

FIX: Account for sidebars with no primary links when adding invite link

---

app/assets/javascripts/discourse/app/lib/transformer.js
app/assets/javascripts/discourse/tests/unit/lib/transformer-test.js

This PR introduces a new method to apply value transformers, which mutate the value instead of returning it.
This is useful when we need to apply a transformer over an object that has internal state that is mutated using methods.
Using the new `applyMutableValueTranformer` it is not necessary that the registered transformers return the value at the end of the transformer in order for the transformer chain to be processed.
This improves the readability of the code of these transformers and prevent subtle bugs on more complex logics with multiple returns.
Example:
- before:
```js
const transformerRegistered = api.registerValueTransformer(
"post-menu-buttons",
({ value: dag }) => {
dag.replace(POST_MENU_LIKE_BUTTON_KEY, ReactionsActionButton);
return dag;
}
);
```
- after:
```js
const …
```

DEV: Added value transformers that mutate the value instead of returning it

---

app/models/web_hook_event_type.rb
config/locales/client.en.yml

This group will not show up unless a plugin registers a WebHookEventType under the `:custom` group, so this is an invisible change.

DEV: Add 'custom' WebHook event type group

---

app/models/topic.rb

This commit fixes an undesirable geometric query resource usage introduced in  b908abe35a0121e7df69ab3bbced259b6a2b7104
I have been unable to figure out a way of testing this usefully (as I fear it would require creating several thousands of objects), but existing tests pass and a manual test with ~400k topics succeeds after the fix, while it would hang indefinitely and/or consume all disk space before the fix.
I have reported the initial problem and my findings in https://meta.discourse.org/t/topic-reset-all-highest-exhausts-all-available-disk-space/333837

FIX: Prevents Topic.reset_all_highest from consuming all resources

---

plugins/automation/app/controllers/discourse_automation/admin_automations_controller.rb
plugins/automation/app/services/discourse_automation/destroy_automation.rb
plugins/automation/config/locales/client.en.yml
plugins/automation/config/routes.rb
plugins/automation/spec/requests/admin_discourse_automation_automations_spec.rb
plugins/automation/spec/services/destroy_automation_spec.rb

A UserHistory entry will now be created when an automation is destroyed. This is visible in /admin/logs/staff_action_logs.
This commit also creates a service `DestroyAutomation` to hold all the destroy automation logic.

UX: logs when an automation is destroyed

---

plugins/chat/app/models/chat/channel.rb
plugins/chat/app/serializers/chat/channel_serializer.rb
plugins/chat/app/services/chat/create_category_channel.rb
plugins/chat/app/services/chat/create_direct_message_channel.rb
plugins/chat/app/services/chat/update_channel.rb
plugins/chat/assets/javascripts/discourse/components/channel-icon/index.gjs
plugins/chat/assets/javascripts/discourse/initializers/chat-sidebar.js
plugins/chat/assets/javascripts/discourse/models/chat-channel.js
plugins/chat/assets/stylesheets/common/chat-channel-icon.scss
plugins/chat/db/migrate/20241104053309_add_icon_upload_id_to_chat_channel.rb
plugins/chat/lib/chat/channel_fetcher.rb
plugins/chat/spec/services/chat/create_category_channel_spec.rb
plugins/chat/spec/services/chat/create_direct_message_channel_spec.rb
plugins/chat/spec/services/chat/update_channel_spec.rb

There's no UI for it at the moment but when creating a channel or updating it, it's now possible to pass `icon_upload_id` as param. This will be available on the channel as `icon_upload_url`.

DEV: sets an icon_upload_id on a channel

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs

We already had a data-attribute, but a class feels more natural in this case.

DEV: adds is-disabled modifier to form field container

---

app/assets/stylesheets/common/base/topic.scss

This fixes the icon alignment, and shrinks the input to avoid overflow on narrow screens 
Before:
After:

UX: align PM icon when editing title, allow shrink-to-fit

---

app/assets/javascripts/discourse/app/components/modal/download-calendar.hbs
app/assets/javascripts/discourse/app/lib/download-calendar.js
plugins/discourse-local-dates/test/javascripts/acceptance/download-calendar-test.js

Allows anonymous users to download the calendar file. Before, they were given the option, but it would fail silently with a `TypeError: Cannot read properties of null (reading 'user_option')`.

FIX: allow anon users to download calendar

---

app/assets/stylesheets/common/base/personal-message.scss

This margin no longer appears necessary... 
before:
after:

UX: remove extra margin from PM small actions

---

app/assets/javascripts/discourse-common/addon/lib/discourse-template-map.js
app/assets/javascripts/discourse/app/instance-initializers/component-templates.js
app/assets/javascripts/discourse/tests/integration/component-templates-test.gjs
app/assets/javascripts/discourse/tests/unit/ember/resolver-test.js

Template overrides have been advised against for a long time, and are increasingly hard to maintain as Discourse's development accelerates. This commit officially deprecates this customization method, which will be removed in the not-too-distant future (likely in the first half of 2025).

DEV: Deprecate template overrides

---

spec/support/system_helpers.rb
spec/system/s3_secure_uploads_spec.rb
spec/system/s3_uploads_spec.rb

It's annoying to have to do both of these every
time you write an S3 system spec, let's just do them
in one call instead.

DEV: Combine S3 system spec helpers into one

---

config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml

This will allow admins to easily see all the experiments
in one place. In the future, we would like a full Experiments
config page with descriptions and screenshots, but this will
do for now.
This also removes the manual labelling of experiments
in site setting descriptions, which was inconsistent.

DEV: Move all experimental settings into new setting category

---

plugins/chat/plugin.rb
plugins/chat/spec/plugin_spec.rb

In the case where:
* Secure uploads were enabled
* Allow unsecure chat uploads was enabled
* For a site with login required enabled
When a chat upload was created, it was being marked as secure. Since
there is no provision for secure uploads in chat, this would lead to
broken uploads/images shown in the channel.
We can use the "public types" functionality of secure uploads to make
sure we never mark chat uploads as secure, and we can revisit this
whenever we get around to allowing secure uploads in chat.

FIX: Chat uploads over-secured in some situations

---

app/assets/javascripts/discourse/app/components/topic-list/topic-list-header-column.gjs

this failed a test in https://github.com/discourse/discourse/pull/28934 so seems to have _some_ test coverage

FIX: Incorrect reference in TopicListHeaderColumn

---

spec/system/page_objects/components/form_kit.rb

DEV: Add support for image fields in FormKit PageObject

---

app/assets/javascripts/discourse/app/components/d-virtual-height.gjs

In some cases, on Safari iOS, we would recompute the "--composer-vh" variable due to a minimal change in the viewport. This ends up triggering a loop where setting this variable triggers another viewport resize event, which triggers another change of the variable...
In order to fix (patch?) this issue, we now have a 1px leeway when checking the difference between the previous and new viewport.
This is unfortunately very hard to test.
Internal ref - t/141088

FIX: weird slow auto scrolling on iOS

---

app/assets/javascripts/discourse/app/lib/codeblock-buttons.js

This PR changes the buttons inside of code blocks to use the `btn-flat` class.
**After**
**Before**

UX: Migrate to `btn-flat`

---

app/assets/javascripts/admin/addon/components/modal/reseed.hbs
spec/system/admin_site_texts_spec.rb
spec/system/page_objects/pages/admin_site_texts.rb

Bug introduced in this PR https://github.com/discourse/discourse/pull/23232
The previous modal was using `category.name`
https://github.com/discourse/discourse/pull/23232/files#diff-bfae353a2f3457780e5c281b6a165261cfe552dd9dd791f3859e52d60e22be7fL20
Demo

FIX: correctly display category name in replace text modal

---

config/site_settings.yml
spec/lib/search_spec.rb
spec/models/discourse_connect_spec.rb

The `normalize_emails` setting makes it so that only canonical e-mails are considered for validation purposes. This means disallowing "plus addressing". For example, with this enabled, `bob@discourse.org` and `bob+foo@discourse.org` are considered the same address, and you can only sign up with one of them.
Currently this is disabled by default, leading to a lot of spam sign-ups. It's healthier to consider this an opt-out setting.

DEV: Enable the normalize_emails site setting by default

---

app/assets/javascripts/admin/addon/routes/admin-config-about.js
app/models/site_setting.rb
config/site_settings.yml

This PR switches the route for the about config page to retrieve the list of site settings that control the /about page by their area instead of their individual names.
Internal topic: t/136384.

DEV: Fetch settings by area name instead of individual settings

---

app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/image-test.gjs
app/assets/javascripts/discourse/tests/integration/components/uppy-image-uploader-test.js
app/controllers/uploads_controller.rb
spec/requests/uploads_controller_spec.rb

Prior to Uppy, the `uploads#create` endpoint used to receive a `type` param that indicated the purpose/target of the upload, such as `avatar`, `site_setting` and so on. With the introduction of Uppy, the `type` param became the MIME type of the file being uploaded, and the purpose/target of the upload became a new param called `upload_type`, however the backend could still use the `type` param (which now contains MIME type) as the purpose/target of the upload if `upload_type` is absent.
We technically don't need to send the MIME type over the network, but it seems like it's done by Uppy and we have no control over the `type` param that Uppy includes:
https://github.com/discourse/discourse/blob/758de8167bb79712fda01af0b35c2699c147b09e/app/assets/javascripts/discourse/app/lib/uppy/uppy-uploa …

FIX: Pass upload type correctly to uploads#create

---

config/initializers/100-flags.rb
db/fixtures/003_flags.rb

After data seed, we should reset Redis cache to ensure that the correct flags are cached.
However, `db:create` is skipping Redis 
https://github.com/discourse/discourse/blob/main/lib/tasks/db.rake#L39
And uses `ActiveSupport::Cache::MemoryStore.new`
https://github.com/discourse/discourse/blob/e2292d4c5914875ad0e303770c56db7cc96847e3/lib/discourse.rb#L523
Therefore, the reset flags cache was moved to initializers and evaluated only when the cache is Redis and Flags table already exists.
Meta: https://meta.discourse.org/t/development-install-fails-when-running-bin-rails-db-migrate/332754

FIX: setup with db:create db:migrate

---

app/assets/stylesheets/common/modal/modal-overrides.scss

This commits adds breakpoints for mobile & tablet to stretch the content and show visible overflow respectively
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/40eef2bc-a1c8-440c-a39d-d392e651275d) | ![DiscoToc test topic - General - Yes](https://github.com/user-attachments/assets/e9180bf9-3051-4444-9d46-6db0745b093a) |
| ![Open Discourse Meta](https://github.com/user-attachments/assets/3b65bda9-8dc4-44b3-a648-d8184fb90134) | ![CleanShot 2024-11-06 at 11 35 34@2x](https://github.com/user-attachments/assets/20c128bc-ccac-4e2c-86d5-d69327bcb849) |

UX: fix visibility of grant badge modal dropdowns

---

app/assets/javascripts/admin/addon/templates/admin-badges/award.hbs
app/assets/stylesheets/common/admin/badges.scss

I was skimming through existing pages to get a feel for the admin UI guidelines. I noticed that this part was missing its margin. On some further investigation, it seems that a single CSS selector, `.award-badge` was being used both for the section and for the button in the header, so I decided to 1) separate the two and 2) add in the missing margin.
**Before:**
**After:**

DEV: Untangle award badge admin CSS

---

app/serializers/post_revision_serializer.rb
spec/serializers/post_revision_serializer_spec.rb

Currently, if an association is added as a tracked field in `PostRevisor`, the `PostRevisionSerializer` class will try to serialize it somehow. This will raise an error as ActiveRecord collection proxies can't be serialized.
This patch addresses this issue by skipping any association tracked by the `PostRevisor` class.

FIX: Don’t try to serialize associations in `PostRevisionSerializer`

---

lib/post_revisor.rb
spec/lib/post_revisor_spec.rb

It currently can leak private tags/categories, to address this we are moving to whispers.

FIX: Change `create_post_for_category_and_tag_changes` setting to use whispers instead of small actions

---

plugins/chat/db/migrate/20241029192512_alter_chat_ids_to_bigint.rb
plugins/chat/spec/plugin_helper.rb

The primary key is usually a bigint column, but the foreign key columns are usually of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.
This was using a temporary plugin / test API to make tests pass. After more careful consideration, we concluded that it is safe to alter the tables directly.
Even for larger communities, with more than 1M chat messages, the slowest `ALTER` query runs in about 15 seconds, which well under the 30 seconds query timeout limit. As a result, chat messages will be delayed for a few seconds, but the system will remain operational.

DEV: Fix mismatched column types

---

app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/tests/acceptance/composer-editor-mentions-test.js

When replying to a topic, the @-mention `userSearch` needs the `topicId` and the `categoryId` so they can trigger immediately, with sane suggestions.
This was broken when the mentions were [moved](https://github.com/discourse/discourse/pull/29411) from `ComposerEditor` to `DEditor`.

FIX: pass topic+category to @-mention user search

---

lib/cooked_processor_mixin.rb

Follow-up to 7d8974d
This icon was renamed, and won't auto-remap when referenced like this

UX: replace broken link SVG with new Font Awesome 6 name

---

app/models/site_setting.rb
lib/s3_helper.rb
spec/lib/backup_restore/s3_backup_store_spec.rb
spec/lib/backup_restore/shared_examples_for_backup_store.rb
spec/lib/s3_helper_spec.rb
spec/models/optimized_image_spec.rb
spec/requests/admin/backups_controller_spec.rb
spec/requests/uploads_controller_spec.rb
spec/support/system_helpers.rb
spec/support/uploads_helpers.rb

When we added direct S3 uploads to Discourse, which use
presigned URLs, we never took into account the dualstack
endpoints for IPv6 on S3.
This commit fixes the issue by using the dualstack endpoints
for presigned URLs and requests, which are used in the
get-presigned-put and batch-presign-urls endpoints used when
directly uploading to S3.
It also makes regular S3 requests for `put` and so on use
dualstack URLs. It doesn't seem like there is a downside to
doing this, but a bunch of specs needed to be updated to reflect this.

FIX: Use dualstack S3 endpoint for direct uploads

---

app/assets/javascripts/admin/addon/templates/api-keys-index.hbs
app/assets/stylesheets/common/admin/api.scss

UX: Apply admin table classes for consistent mobile styling on the API keys page

---

plugins/chat/assets/stylesheets/mobile/chat-footer.scss

This commit is a revert of https://github.com/discourse/discourse/commit/c91bd3ca07ebcb99a379861f9f17f948cc8ab491

UX: do not hide topic composer in mobile chat

---

app/assets/javascripts/discourse/app/components/time-shortcut-picker.hbs

These icons are not contributing to any clarity or user understanding, and instead can even cause confusion by the chevron being a usual indicator of a toggle, which is not the case here. Tomorrow is also not traditionally a cog, and some icons are being used double. In general, when an icon doesn't contribute to clarity, it's just noise.
This commit removes them from the tiles used for these duration or time indicators.
| ![CleanShot 2024-11-07 at 14 40 11@2x](https://github.com/user-attachments/assets/74318bf9-0c93-4193-84b0-844ccc5e09ad) | ![CleanShot 2024-11-07 at 14 34 45@2x](https://github.com/user-attachments/assets/570b7ec3-2309-4e05-bcdf-ca78d61f6da2) |
| ![CleanShot 2024-11-07 at 14 39 …

UX: remove icons indicating time in userstatus, bookmarks, topic timer

---

plugins/chat/app/models/chat/message.rb
plugins/chat/assets/javascripts/discourse/components/chat-message.gjs
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/test/javascripts/components/chat-message-test.js

The markdown it rule "heading" will only be used when the message is done by a bot, which means an id < 0.
This commit also adds a `is-bot` css class on messages made by a bot, for finer control.

DEV: only supports headings in messages for bots

---

app/assets/javascripts/discourse/app/services/composer.js
spec/system/composer/discard_draft_spec.rb

"Resume editing" would do nothing when going through the `/new-message` flow.
This seems to be broken since [this commit](https://github.com/discourse/discourse/commit/b0f6d074be2be452092c3062dde703d969c97110). which moved `this._setModel` calls around – the same we're doing now, but to different places: the first one needs to happen after the `draft.data` has been set , while the second needs to happen before the `this.open` call.

FIX: resume editing when through /new-message

---

plugins/chat/assets/javascripts/discourse/services/chat-thread-pane.js
plugins/chat/spec/system/chat/composer/shortcuts/thread_spec.rb

`chatThreadPane.isOpened` was returning `false` when it should return `true` due to an incorrect matching on the route.
Note that visiting a thread will focus the composer and the first escape will blur the input, only the second will close the panel.

FIX: ensures thread panel closes on escape

---

plugins/chat/app/serializers/chat/channel_serializer.rb
plugins/chat/assets/javascripts/discourse/models/chat-channel.js
plugins/chat/assets/javascripts/discourse/routes/chat-channel-decorator.js
plugins/chat/spec/serializer/chat/channel_serializer_spec.rb
plugins/chat/spec/system/chat_channel_spec.rb

Before this fix we would render the emoji as text, eg: `:cat:`
Example with the fix:

FIX: correctly render unicode in channel page title

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
spec/system/topic_map_spec.rb

We want to make summaries shown through the AI plugin a little easier to reach at the bottom of the topic, so lowering the threshold on the topic map's appearance should help initially.

UX: lower min_post_count to show bottom topic map

---

app/models/site_setting.rb
spec/models/site_setting_spec.rb
spec/support/system_helpers.rb

Followup 0568d36133081e52f25f05585c1a568c3b828d79
S3 itself and other S3-compatible providers do not
allow using an S3 custom endpoint and dualstack at
the same time, so this commit fixes that by not using
dualstack when the endpoint is present.
c.f. https://meta.discourse.org/t/rebuild-issue-cannot-set-dual-stack-in-combination-with-a-custom-endpoint/334902

FIX: S3 custom endpoint incompatible with dualstack

---

plugins/chat/assets/stylesheets/common/chat-height-mixin.scss

Prior to this fix a collapsed composer (40px height) would appear above the chat channel as the height of the channel would be too high.

FIX: correctly account for composer height in PWA

---

app/assets/javascripts/discourse/app/components/modal/create-invite.gjs
app/assets/javascripts/discourse/tests/helpers/form-kit-helper.js
app/assets/javascripts/discourse/tests/integration/components/create-invite-test.gjs
config/locales/client.en.yml
spec/system/create_invite_spec.rb
spec/system/page_objects/modals/create_invite.rb

Follow-up to https://github.com/discourse/discourse/pull/28974
In the linked PR, as part of simplifying the invite modal, we removed the option to skip sending an email when creating an invite restricted to a specific address. This has caused confusion about whether an email will be sent by Discourse or not, so we're adding back the option to create a restricted invite without emailing.
Screenshot:
Internal topic: t/134023/48.

FIX: Add back the option to create invite without emailing

---

app/models/upload.rb
lib/s3_inventory.rb
spec/lib/s3_inventory_spec.rb

This reverts commit 5a00a041f1a9a00fb31b18956769262af6f11037.
Implementation is currently not correct. Multiple uploads can share the
same etag but have different paths in the S3 bucket.

Revert "FEATURE: Mark bad uploads with :invalid_url (#29640)"

---

plugins/chat/app/models/chat/message.rb
plugins/chat/spec/models/chat/message_spec.rb

This change will only prevent a cooked message with `[grid]` to show `[grid]`, instead the content will be wrapped in `div class="d-image-grid"`. This is only enabled on messages made by bot, as regular users could use grid but have no reason to use it ATM, so it's ok to consider it as non supported markup for now. It will also not apply the decoration which shouldn't change the behavior more than just removing grid markup from the message.

DEV: cook grid bbcode in chat

---

plugins/chat/app/models/chat/message.rb
plugins/chat/spec/models/chat/message_spec.rb

Writing `\*test\*` will now correctly cook `*test*`, and not `<em>test</em>`.

FIX: supports escape sequence in chat

---

app/assets/javascripts/discourse/app/components/bulk-select-topics-dropdown.gjs
app/assets/stylesheets/common/base/modal.scss
config/locales/client.en.yml
spec/system/page_objects/modals/topic_bulk_actions.rb
spec/system/topic_bulk_select_spec.rb

When performing bulk dismissal in Unread and New views, the dismiss button stays at the top of the UI. Because of this we want to provide the dismiss action also in the "sticky" menu that's always in view, even when scrolling a long list of topics.

FEATURE: Add more bulk dismiss buttons with confirmation

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-unread-indicator.gjs
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/system/list_channels/drawer_spec.rb
plugins/chat/spec/system/page_objects/chat/components/channels_index.rb
plugins/chat/spec/system/page_objects/chat_drawer/chat_drawer.rb

Adds channels with unread threads (watching/tracking) to the sorting logic for both public and direct message channels.
Previously channels with unread threads could easily be missed as we didn't bump them to the top when new thread replies were created.
We are also adding a blue unread badge next to DM channels when there is an unread thread, as previously they weren't appearing as unread within the DMs tab (they only showed within the My Threads section).
In DMs, watched threads (and messages/mentions) are urgent and appear in green, regular (tracked) threads are blue:
In public channels unread messages and unread threads are blue, and watched threads (and mentions) in green:
Note: for watched threads we currently show the urgent count on the My Threads tab. We could also include …

UX: update chat channel sorting to include unread threads

---

.pnpmfile.cjs

Adding it to the end means it may get passed to some other tool (e.g. `pnpm eslint` would end up as `pnpm eslint --ignore-workspace`, but we want `pnpm --ignore-workspace eslint`)

DEV: Add --ignore-workspace immediately after 'pnpm' in arguments

---

app/assets/javascripts/discourse/app/components/flat-button.js

Overriding computed properties with arguments is no longer supported by Ember, so we need to rename this computed property and add fallback logic manually.
This fixes the styleguide 'buttons' page. Ref https://meta.discourse.org/t/styleguide-bugs/335211?u=david

DEV: Fix passing translatedTitle as argument to flat-button

---

plugins/styleguide/assets/javascripts/discourse/lib/dummy-data.js

The base `transformedPost` in dummy-data was missing the topic object.

FIX: broken post in styleguide

---

config/initializers/100-flags.rb

Bug introduced here: https://github.com/discourse/discourse/pull/29609
It was checking if `flags` table existed before resetting the cache. However, `require_message` flag was added in further migration:
https://github.com/discourse/discourse/blob/main/db/migrate/20240714231226_duplicate_flags_custom_type_to_require_message.rb#L5
When the admin tried to update Discourse which already has `flags` table but no `require_message` column, it was causing the error.
Therefore, we should ensure that all migrations are finished before resetting flags cache.
Meta: https://meta.discourse.org/t/update-failing-column-require-message-does-not-exist/335030

FIX: migrations must be finished to reset flags cache

---

plugins/chat/test/javascripts/components/chat-message-collapser-test.js

https://github.com/mainmatter/qunit-dom/blob/master/API.md#isvisible will return true if offsetWidth or offsetHeight are zero which could happen in this case as the test could run before the image has loaded. By forcing a minimum height in the test we ensure it will be consistent.

FIX: flakey due to 0 width/height images

---

config/site_settings.yml
spec/lib/search_spec.rb
spec/models/discourse_connect_spec.rb

This reverts commit 7d9d98422c8c68db5b6f64e08428ea5a2b30f4f2.
Reverting for now because this can cause issues on SSO setups

Revert "DEV: Enable the normalize_emails site setting by default (#29587)"

---

app/assets/javascripts/admin/addon/controllers/admin-config-flags.js
app/models/user_history.rb
spec/system/admin_staff_action_logs_spec.rb
spec/system/page_objects/pages/admin_staff_action_logs.rb

Flag actions must be added to `staff_actions` method to be filterable.

FIX: filterable staff logs for flags

---

spec/system/page_objects/pages/topic.rb

Wait for the flag button to arrive before clicking it.

FIX: flaky system flags spec

---

app/models/moved_post.rb
app/models/post.rb
app/models/post_mover.rb
app/models/topic.rb
db/migrate/20241108154026_create_moved_posts.rb
spec/fabricators/moved_post_fabricator.rb
spec/models/moved_post_spec.rb
spec/models/post_mover_spec.rb

This is a very simple change, which creates a permanent table in the DB, rather than generating a temporary table when moving posts. This change is about capturing data and any usage will appear in a follow-up.
I did include a new column `created_new_topic` in the new table, so that it can be easily audited without having to compare destination topic created_at with moved_post records.

DEV: Create permanent version of `moved_posts` table from PostMover class

---

script/import_scripts/vbulletin3.rb

Import script for vBulletin 3. It is based on the existing `vbulletin.rb` script which was made for vBulletin 4.
Besides various bug fixes for vBulletin 3 this script also contains significant improvements to the BBcode to markdown conversion. It properly associates attachments with post. Polls are converted. vBulletin forum permission and forum moderators groups are converted as much as possible. Private forums for certain groups will still be private after the import. Custom user groups are imports and joinable public or private groups. Deep links can be converted to internal links in posts. Link rot to threads, posts, and categories are prevented as much as possible. It restores the original forum in a similar state in Discourse with ordered categories and nesting up to 3 levels deep. …

DEV: vBulletin 3 import script

---

plugins/automation/spec/scripts/topic_spec.rb
plugins/automation/spec/scripts/user_group_membership_through_badge_spec.rb
plugins/automation/spec/scripts/zapier_webhook_spec.rb
plugins/chat/spec/lib/chat/channel_archive_service_spec.rb
spec/lib/discourse_hub_spec.rb
spec/lib/discourse_ip_info_spec.rb
spec/lib/discourse_spec.rb
spec/lib/email/processor_spec.rb
spec/lib/middleware/discourse_public_exceptions_spec.rb
spec/lib/middleware/request_tracker_spec.rb
spec/lib/mini_scheduler_long_running_job_logger_spec.rb
spec/lib/sidekiq_long_running_job_logger_spec.rb
spec/models/report_spec.rb
spec/rails_helper.rb
spec/requests/application_controller_spec.rb
spec/requests/csp_reports_controller_spec.rb
spec/services/user_stat_count_updater_spec.rb

Instead of replacing the Rails logger in specs, we can instead use `#broadcast_to` which has been introduced in Rails 7.

DEV: Don’t replace Rails logger in specs

---

plugins/automation/spec/system/error_spec.rb
plugins/automation/spec/system/page_objects/discourse_automation/automation.rb

This page object also attempts to make the update automation more resilient as we are seeing flakey specs on this codepath. The solution for now is to ensure we have the sequence: click button/button is loading/ button has finished loading.

DEV: adds a page object for automation page

---

lib/tasks/uploads.rake

If the upload has existed before, we should allow the upload to be
created even if the upload's size is too big.
There are no tests for this rake task and it is quite complicated to write tests for a rake task like this. Please give me a pass 😉

DEV: Fix `uploads:fix_missing_s3` rake task when file is too big

---

app/assets/javascripts/discourse/app/components/uppy-image-uploader.js
app/assets/javascripts/discourse/tests/integration/components/uppy-image-uploader-test.js
app/assets/stylesheets/common/admin/admin_emojis.scss
app/assets/stylesheets/common/base/upload.scss

`UppyImageUploader` used to support this but this has been broken.
This commit:
- Adds back the target drop options to enable the feature
- Applies the css to every elements and not just the one for admin emojis, also fixes the style as it was flashing and preventing it to work. For now we just change the color of the image icon.
- Adds a test to ensure we don't regress.

FIX: correctly supports dropping image

---

spec/rails_helper.rb
spec/support/system_helpers.rb

These URLs allow the state of a headless browser to be viewed and debugged using any other browser, without needing to restart the test with `SELENIUM_HEADLESS=0`.
Also adds a 'resuming test...' indicator when you end the pause.
New output of pause_test:
When visiting those URLs, this is what the inspector looks like:

DEV: Add remote debugging URLs to system spec helper

---

app/controllers/uploads_controller.rb
spec/requests/uploads_controller_spec.rb

Follow up to https://github.com/discourse/discourse/pull/29600
Prior to the linked PR, the `uploads#create` endpoint had a `upload_type` and `type` param that acted as aliases for each other and raised an error if both of them were missing. In the linked PR, we removed the `type` param and always required the `upload_type` param which break API consumers that only included `type` in their requests.
This PR adds back the `type` param temporarily and introduces a deprecation message for it so that API consumers are made aware of the eventual removal of the `type` param.

FIX: Restore and deprecate the `:type` param of `uploads#create`

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
app/assets/javascripts/discourse/app/controllers/topic.js
spec/system/topic_map_spec.rb

This reduces the post count threshold for the bottom topic map to 3. 
Including a word count minimum and filtering out small posts will help ensure that in cases where there's not much content people won't be seeing two topic maps at the same time.

UX: reduce bottom topic map threshold, with protections

---

app/assets/javascripts/custom-proxy/index.js

When running a development environment behind a proxy (e.g. when using a cloud development environment, or a service like ngrok), the ember-cli port & protocol may not match the one in the browser. `livereload.js` knows how to auto-configure itself based on the current browser environment... but Ember CLI overrides that autoconfiguration with some hard-coded values.
The intention there is to allow running the livereload server on a different port to the ember-cli web proxy. We don't need that functionality.
This commit stops loading `ember-cli-live-reload.js`, and instead loads `_lr/livereload.js` directly.

DEV: Simplify livereload configuration for better proxy compatibility

---

plugins/chat/app/jobs/regular/chat/auto_join_channel_batch.rb

The job was removed in 6dfe2fbe16a4096ff342ec8b626ac62a19eaa180 as part of a performance-related refactor.
The issue was that job was already enqueued in sidekiq and now that the file has been deleted, it's generating a lot of `uninitialized constant Jobs::Chat::AutoJoinChannelBatch` errors.
Restoring this file will help clear the sidekiq queue. We'll remove the job in a few months.
Internal ref - t/141563

DEV: restore AutoJoinChannelBatch job as a no-op to clear queue

---

plugins/chat/app/queries/chat/channel_unreads_query.rb
plugins/chat/app/queries/chat/thread_unreads_query.rb
plugins/chat/assets/javascripts/discourse/components/chat-channel-unread-indicator.gjs
plugins/chat/assets/javascripts/discourse/components/thread-unread-indicator/index.gjs
plugins/chat/spec/queries/chat/channel_unreads_query_spec.rb
plugins/chat/spec/queries/chat/thread_unreads_query_spec.rb

Previously we only counted mentions that were made within channels, however for threads this was never implemented. 
This change adds a thread count to the `ThreadUnreadsQuery`, which is used for channel thread lists and the user thread list. We are also expanding channel mentions count to include mentions within threads.
This means that we can have a more consistent urgent badge across chat, in places such as channel lists and the chat header.
Chat mention within a public channel thread on mobile:

FEATURE: add mention count to threads

---

app/assets/javascripts/discourse/app/controllers/discovery/list.js
spec/system/category_topics_spec.rb
spec/system/dismissing_new_spec.rb

When a parent category shows topics from subcategories, dismissing should dismiss posts in both parent and subcategories.
See meta t/335195 for the original report.

FIX: Dismiss unread posts in subcategories

---

plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/spec/system/bookmark_message_spec.rb
spec/system/page_objects/components/user_menu.rb

When using chat in drawer mode, after you've clicked on a chat bookmark in the user menu, clicking any other chat bookmark would "do nothing".
In 8b18fd155679fa9b9d6e660ac74130cb79daabdc we added an optimization to prevent the same route from being reloaded, but it ended up breaking the bookmarks.
This commit reverts the changed made the above commit and adds a system specs that ensure we can click two chat bookmarks in the user menu when using chat in drawer mode.
Internal ref - t/134362

FIX: chat bookmarks in drawer mode

---

app/assets/javascripts/discourse/app/components/search-menu/results/random-quick-tip.hbs
app/assets/stylesheets/common/base/search-menu.scss

This updates these clickable search tips to buttons, rather than interactive spans — this allows them to be tabbable and more accessible by default. I've also added the description as a `aria-describedby` so they get read as well.  
Appearance and functionality otherwise hasn't changed.

A11Y: update clickable search dropdown tips to be buttons

---

app/models/site_setting.rb
spec/models/site_setting_spec.rb

Followup 0568d36133081e52f25f05585c1a568c3b828d79
Followup 97cf069a061e350edfc5310266e80e58532a39a4
Due to the S3 dualstack endpoint change, sites with
S3 backups configured but _not_ S3 uploads were erroring,
with admins unable to access the backups page. This
commit fixes the error by not enabling S3 dualstack
endpoints if S3 uploads have not been enabled, backups
don't need to use them.
c.f. https://meta.discourse.org/t/unable-to-backup-or-navigate-to-backups/335899

FIX: Admin backups erroring because of S3 dualstack

---

app/models/theme_field.rb
lib/scheduler/defer.rb
spec/integration/activerecord_preventing_writes_spec.rb
spec/rails_helper.rb

Firstly, we need to understand that ActiveRecord can be
connected to a role which prevent writes and this happens in Discourse when a
replica database has been setup for failover purposes. When a role
prevent writes from happening, ActiveRecord will raise the
`ActiveRecord::ReadOnlyError` if a write query is attempted.
Secondly, theme fields are baked at runtime within GET requests. The
baking process involves writing the baked value to the
`ThemeField#baked_value` column in the database.
If we combine the two points above, we can see how the writing of the
baked value to the database will trigger a `ActiveRecord::ReadOnlyError`
in a GET request when the database is connected to a role preventing
writes. However, failing to bake a theme is not the end of the world and
should not cause GET …

FIX: Rescue `ActiveRecord::ReadOnlyError` when baking theme field

---

.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/settings.json.sample

DEV: Update vscode config to use ruby-lsp for syntax_tree formatting

---

app/assets/javascripts/discourse/app/components/fullname-input.gjs
app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/templates/invites/show.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/common/modal/login-modal.scss

Using the site setting `full_name_required` changes the order of the fields in the signup form. Previously, this was done with CSS, which caused issues with tab navigation. This PR fixes that by rearranging the elements in the template. 
It also makes the field descriptions always visible, instead of only when the input was focused, and adds the auto-scroll feature for the invites page as well

FIX: Signup fields tab order and descriptions

---

app/assets/stylesheets/common/admin/sidebar.scss

The section header text does not stand out enough with the background color. This PR improves the text color for better visibility.

UX: Increase admin section header contrast

---

app/assets/javascripts/select-kit/addon/components/category-row.gjs

Descendants can gain focus (category badge) and that makes aria-hidden incorrect as a result.

FIX: removes aria-hidden on category-status

---

app/serializers/user_serializer.rb
spec/serializers/user_serializer_spec.rb

As part of [this fix](https://github.com/discourse/discourse/pull/27664) we changed which groups are serialized for a user, in order to fix a bug in the default group selector under user preferences.
However, we should only change this when serializing the current user. This change combines the old code-path and the new based on who is serializing.

FIX: Don't include secret membership groups when serializing other users

---

app/assets/javascripts/discourse/app/components/modal/discard-draft.gjs
app/assets/javascripts/discourse/tests/acceptance/composer-test.js

Reference: https://meta.discourse.org/t/bug-unable-to-close-modal-using-keyboard-esc-or-clicking-modal-overlay/335849

A11Y: Allow dismissing the discard drafts modal via keyboard

---

app/assets/javascripts/discourse/app/components/header/user-dropdown/notifications.gjs
app/assets/stylesheets/common/base/discourse.scss
config/locales/client.en.yml

This PR:
- changes the way we show a border around the dnd icon, preventing alignment at different zoom amounts.
- adds a localized string on hover to show what the icon means

UX: Add title & adjust dnd image

---

app/assets/stylesheets/common/admin/admin_table.scss

This PR: 
* Vertically align the content within each table cell to the center
* Updated the `.overview` class to be applied specifically to `td` elements, giving better control over cell-specific styling and preventing any unintended styling on entire rows

UX: Make cells middle aligned; apply overview class directly to td elements

---

app/assets/javascripts/select-kit/addon/components/category-row.gjs
app/assets/javascripts/select-kit/addon/components/none-category-row.js

There were two problems here:
- category link shouldn't output a link or we will get focus on it
- category row itself should not be focusable
The purpose of this dropdown is to navigate from one dropdown to another and to use arrow keys and enter to navigate inside.

FIX: ensures category row is not focusable

---

app/assets/javascripts/admin/addon/components/admin-config-area-empty-list.gjs
app/assets/javascripts/admin/addon/templates/permalinks-index.hbs
app/assets/stylesheets/common/admin/admin_config_area.scss
app/assets/stylesheets/common/admin/customize.scss
app/assets/stylesheets/common/admin/plugins.scss
config/locales/client.en.yml

This component can be used as a placeholder on
admin pages where the table has no data as per
the admin UI guidelines.

UX: Add AdminConfigAreaEmptyList component

---

app/assets/javascripts/admin/addon/components/admin-config-areas/emojis-settings.gjs

Because of an oversight in a previous PR, the breadcrumb link when visiting Admin > Emoji > Settings was broken. The correct path is `customize`, not `config`.

FIX: Amend broken settings link in emoji admin breadcrumbs

---

lib/service/base.rb
lib/service/runner.rb
lib/service/steps_inspector.rb
spec/lib/service/runner_spec.rb
spec/lib/service/steps_inspector_spec.rb
spec/support/service_matchers.rb

This PR adds a new step to services named `try`.
It’s useful to rescue exceptions that some steps could raise. That way, if an exception is caught, the service will stop its execution and can be inspected like with any other steps.
Just wrap the steps that can raise with a `try` block:
```ruby
try do
step :step_that_can_raise
step :another_step_that_can_raise
end
```
By default, `try` will catch any exception inheriting from `StandardError`, but we can specify what exceptions to catch:
```ruby
try(ArgumentError, RuntimeError) do
step :will_raise
end
```
An outcome matcher has been added: `on_exceptions`. By default, it will be executed for any exception caught by the `try` step. Here also, we can specify what exceptions to catch:
```ruby
on_exceptions(ArgumentError, RuntimeError) do …
```

DEV: Add a `try` step to services

---

app/assets/javascripts/discourse-i18n/src/index.js

Soon, we intend to consolidate all js/gjs translation calls to this new function. See https://github.com/discourse/lint-configs/pull/67 and https://github.com/discourse/discourse/pull/29804

DEV: add `i18n` named export to "discourse-i18n"

---

script/bulk_import/generic_bulk.rb

Forgot to update the table during these changes - https://github.com/discourse/discourse/pull/29442

Fix the import votes for posts table to the new 'post_voting_votes' table

---

plugins/chat/assets/stylesheets/common/chat-composer.scss

In some rare cases, this was causing the input to be invisible, for example when `--main-outlet-offset` was a high number. The change here means the input will have a slightly different max height, but since here we are limiting this to 25% of the viewport height, it should be fine.
It's also not necessary to include the `chat-header-offset`, it ends up being only a few pixels' difference (since, again, the value is divided by 4).
Before / after desktop
Before / after mobile with keyboard visible

FIX: Simplify max-height calculation for chat composer 

---

spec/rails_helper.rb

This spec helper was introduced as a temporary solution to the problem of mismatched types between primary key and foreign key columns. All plugins have been migrated and the only remaining use of this helper is in core Discourse.

DEV: Remove migrate_column_to_bigint spec helper

---

app/assets/javascripts/discourse/app/components/topic-list.js
app/assets/javascripts/discourse/app/components/topic-list/topic-list-header-column.gjs
app/assets/javascripts/discourse/app/raw-templates/topic-list-header-column.hbr
app/assets/stylesheets/common/base/discourse.scss

This converts these sortable headers to buttons instead of spans, allowing us to drop the tabindex and button roles. This also improves the visual styling so the chevron is included within the button
Before:
After:

A11Y: convert sortable topic list headers to proper buttons

---

app/assets/javascripts/discourse/app/components/uppy-image-uploader.hbs
app/assets/javascripts/discourse/app/components/uppy-image-uploader.js
spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/uppy_image_uploader.rb

This makes it possible to navigate to this button with the keyboard (technically a label triggering an invisible file input) and triggers the input on enter or space 
previously you could not navigate to this button with the keyboard at all

A11Y: make the uppy image uploader keyboard navigable

---

migrations/bin/cli
migrations/lib/cli/convert_command.rb
migrations/lib/cli/import_command.rb
migrations/lib/cli/upload_command.rb
migrations/lib/migrations.rb

The previous approach of splitting Thor commands into multiple files caused problems when the same method name was used in multiple commands.
This also loads the Rails environment only for commands that need it. That speeds up the CLI boot for most commands or when the help should be shown. That's also why we can't use `Rails.root` in the CLI.

FIX: migrations-tooling CLI didn't work anymore

---

spec/rails_helper.rb
spec/services/site_settings_spec.rb
spec/services/themes_spec.rb
spec/support/helpers.rb
spec/tasks/assets_precompile_spec.rb
spec/tasks/compatibility_spec.rb
spec/tasks/hashtags_spec.rb
spec/tasks/incoming_emails_spec.rb
spec/tasks/posts_spec.rb
spec/tasks/redis_spec.rb
spec/tasks/themes_spec.rb
spec/tasks/topics_spec.rb
spec/tasks/uploads_spec.rb
spec/tasks/users_spec.rb
spec/tasks/version_bump_spec.rb

Don't load rake files over and over again when running specs.

DEV: Fix constant redefinition warnings when running specs

---

plugins/chat/lib/chat_sdk/message.rb
plugins/chat/spec/lib/chat_sdk/message_spec.rb

Blocks have been added in https://github.com/discourse/discourse/commit/582de0ffe3a892db6db74b3d73ef105966534f13 but were not yet supported in the SDK.
Usage:
```ruby
ChatSDK::Message.create(
raw: "hello world",
blocks: [
{
type: "actions",
elements: [
{ value: "foo", type: "button", text: { text: "How can I install themes?", type: "plain_text" } }
]
}
],
guardian: guardian,
channel_id: channel.id,
)
```

DEV: supports blocks in chat message sdk

---

plugins/chat/app/services/chat/auto_leave_channels.rb
plugins/chat/spec/integration/auto_channel_user_removal_spec.rb
plugins/chat/spec/services/chat/auto_leave_channels_spec.rb

This optimizes a hot path when users are being removed from one or more groups since we use the `on(:user_removed_from_group)` event to call the `Chat::AutoLeaveChannels` with a `user_id` parameter. In such case, we don't need to clear the membership of all users, just that one user.
DEBUG: Also added a "-- event = <event>" comment on top of the SQL queries used by the "AutoLeaveChannels" so they show up in the logs and hopefully facilitate any performance issues that might arise in the future.

PERF: optimize chat user membership cleanup when removing a single user

---

plugins/chat/app/serializers/chat/message_interaction_serializer.rb
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/serializer/chat/message_interaction_serializer_spec.rb
plugins/chat/spec/serializer/chat/message_interaction_spec.rb
plugins/chat/spec/support/api/schemas/message_interaction.json

Prior to this fix it would cause an error as we need to pass the user to get the title of the channel.
This commit also adds a test for message interaction serializer.

FIX: serializes interaction for direct messages

---

lib/tasks/profile.rake
script/bench.rb

Following a recent commit (cb4b8146a30cd94b04db1b662fbebdb8021a7771), the benchmark script wasn’t working anymore (and the related rake task).
This PR fixes it. It also adds some information about Ruby YJIT being enabled or not.

DEV: Fix benchmark script

---

config/locales/server.en.yml

changed "reading hand" to "reading and"

Update server.en.yml to fix typo in tl1 description

---

config/locales/client.en.yml

Updated "Edit link options" link on the invite popup so it now reads "Edit link options or send by email". This will help folks find the legacy send invite by email UI. We are still wanting to move away from that and encourage site members to grab an invite link and send it themselves using email, chat app, social media etc.

Update client.en.yml to improve link text on invite popup

---

db/migrate/20241120182858_add_index_to_chat_messages_on_chat_channel_id.rb

Commit c2a733a95a422837d517a991de04f8462119cc5e was applied to an
existing migration that possibly had already run. Due to this some
discourse instances might not have the correct index.
This change removes the original migration and creates a new one so that
it will actually be applied.
This is the missing index that some sites might not have:
```
Missing Index | CREATE INDEX
index_chat_messages_on_chat_channel_id_and_id ON public.chat_messages
USING btree (chat_channel_id, id) WHERE (deleted_at IS NOT NULL)
```

DEV: Re-apply chat index migration

---

app/assets/javascripts/discourse/app/components/modal/create-invite.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

This allows a theme to do:
```js
withPluginApi("1.32.0", (api) => {
api.registerValueTransformer(
"invite-simple-mode-topic",
({ value, context }) => {
if (context.invite.isCustomInvite) {
return INVITE_LANDING_TOPIC_ID;
}
}
);
});
```
which will populate a landing topic in the invite modal's "simple mode" (this mode below)

FEATURE: add transformer to pass topic ID to simple invite generation

---

app/assets/javascripts/discourse/app/raw-templates/topic-list-header.hbr

Adding an order value here ensures the column header gets the `posters` class — currently it has no unique class to target with CSS.
This has already been done in the glimmer topic list, because @CvX is wonderful and smart. 
https://github.com/discourse/discourse/blob/a914d3230bd53950677324ecc328d6c7a98167aa/app/assets/javascripts/discourse/app/components/topic-list/topic-list-header.gjs#L48

DEV: add order to posters column so it gets a classname

---

app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common/base/code_highlighting.scss
app/assets/stylesheets/common/foundation/color_transformations.scss

This PR merges the [experimental styling changes](https://meta.discourse.org/t/improved-code-block-sizing-color-scheme/333946/26) for codeblocks into core.

UX: Codeblocks experiment merge

---

spec/system/topic_bulk_select_spec.rb

This commit is going to try using the `have_read_post` page object from
`topic_view` instead of the page object for `topic` because it's
implementation has a longer wait time as it uses the ENV variable for
wait time: `Capybara.default_max_wait_time * 2`.
If this works out we should probably remove the duplicated
`have_read_post` page object so that we have a single implementation.

DEV: Fix flaky test with bulk select closing topics

---

app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/invite-section-link.js

This PR updates the sidebar's Invite button to use the intended text for its title attribute.

DEV: Update sidebar invite button to use correct title attribute text

---

app/jobs/regular/push_notification.rb
spec/jobs/push_notification_spec.rb

Sometimes `Jobs::PushNotification` gets stuck, probably because of the network call. This commit replaces `Excon` with `FinalDestination::HTTP` which is safer.

FIX: Use FinalDestination::HTTP to push notifications

---

app/assets/javascripts/discourse/app/components/search-menu.hbs
app/assets/javascripts/discourse/app/components/search-menu.js
app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.js
app/assets/javascripts/discourse/app/components/search-menu/results/assistant.hbs
app/assets/javascripts/discourse/tests/acceptance/search-test.js

Prior to this fix the menu would not close if a child was in focus, and the search suggestions had a special implementation to handle this. The fix now relies on trapping the keydown escape event on the top dip of the search menu.

FIX: correctly closes search menu on escape

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

While it is ok to have the check for if the person can delete a topic, for this feature some times you might want some more flexibility.
Instead of relying on patching this class and method, it would be better to have a modifier that can decide if the topic should be deleted after the merge.

FEATURE: Add modifier to delete after merge

---

app/assets/javascripts/discourse/app/components/composer-container.hbs
app/assets/javascripts/discourse/app/components/composer-editor.hbs
app/assets/javascripts/discourse/app/components/composer-editor.js
app/assets/javascripts/discourse/app/components/d-editor.hbs
app/assets/javascripts/discourse/app/components/d-editor.js
app/assets/javascripts/discourse/app/lib/uppy/composer-upload.js
app/assets/javascripts/discourse/tests/integration/components/composer-editor-test.gjs
app/assets/stylesheets/common/base/compose.scss

Most of it is removing the `ComposerContainer > ComposerEditor` indirect references to the `composer` service, so `ComposerEditor` now deals with the service directly.
There are still some monkey patches in customizations to adjust before considering merging this.

DEV: refactor `composer` references on composer-container/-editor

---

app/assets/javascripts/discourse/app/components/discovery/filter-navigation.hbs
app/assets/javascripts/discourse/app/components/discovery/filter-navigation.js
app/assets/javascripts/discourse/app/controllers/discovery/filter.js
app/assets/javascripts/discourse/app/templates/discovery/filter.hbs
app/assets/stylesheets/common/components/topic-query-filter.scss
spec/system/filtering_topics_spec.rb

- Add bulk actions component on /filter page for both desktop & mobile view.
- Add system specs to assert bulk actions to be available on /filter page.
- Only users with `canManageTopic` set as true can use bulk action.
Desktop:
https://github.com/user-attachments/assets/3bb5e7b2-3b81-47e2-8189-5d6ce5faca50
Mobile:
https://github.com/user-attachments/assets/aff6e23e-d528-4f2c-a13b-4ccb08f28653
- Manually tested with both ember & experimental glimmer components.
- With Glimmer components there was an issue with missing focus action on topic-link component. Attempted fix in PR

FEATURE: Add Bulk actions to /filter page

---

app/assets/javascripts/discourse/app/lib/fabricators.js
plugins/chat/assets/javascripts/discourse/components/chat/direct-message-button.gjs
plugins/chat/test/javascripts/components/chat-user-card-button-test.js

when the user isn't able to receive DMs (either because they've disabled it or because they're suspended for example).
Internal ref - t/142198

FIX: hide chat button in user card

---

app/assets/javascripts/discourse/app/initializers/deprecation-this-property-fallback-handler.js

A followup to 019ba099c84f2e2e4fa0053588707acd2e728376

DEV: Fix theme name in `this` deprecation notices

---

app/assets/javascripts/discourse-common/addon/lib/raw-templates.js
app/assets/javascripts/discourse/app/components/topic-list-item.js
app/assets/javascripts/discourse/app/components/topic-list.js
app/assets/javascripts/discourse/app/instance-initializers/hbr-topic-list-overrides.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs

1. `addRawTemplate` is called too early for deprecation handlers to process its deprecation call, so toggle the hbr flag directly
2. move the deprecation handler to an initializer so that other (non-template) calls are always handled
3. mvoe the debug logging to the handler

DEV: Improve hbr topic list detection

---

config/site_settings.yml

The `/filter` route is now default available, no other UI changes are included.

DEV: Enable `experimental_topics_filter` by default

---

app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common/base/code_highlighting.scss
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/foundation/base.scss
app/assets/stylesheets/common/foundation/color_transformations.scss

This PR addresses a couple issues:
- lines up inline codeblocks with web standard styling
- adds a darker bg for inline codeblock for better readability

UX: Multiple codeblocks fixes

---

app/assets/javascripts/admin/addon/components/admin-permalink-form.gjs
app/controllers/admin/permalinks_controller.rb
app/models/permalink.rb
spec/models/category_spec.rb
spec/models/permalink_spec.rb
spec/requests/admin/permalinks_controller_spec.rb
spec/requests/application_controller_spec.rb
spec/requests/categories_controller_spec.rb
spec/requests/permalinks_controller_spec.rb

This moves the logic of setting the correct permalink values back into the controller. And it replaces the validation with a simpler one, that always works, even when the model is loaded from the DB.
Follow-up to https://github.com/discourse/discourse/pull/29634 which broke import scripts and lots of documentation on Meta.

FIX: `Permalink.create` didn't work as expected anymore

---

lib/topic_view.rb
spec/lib/topic_view_spec.rb

I also refactored some existing modifier tests for TopicView that I didn't like. Now they're grouped together and follow a very similar pattern.

DEV: Apply modifier for topic_view link_counts

---

app/assets/javascripts/discourse/app/components/composer-toggles.js
plugins/chat/assets/javascripts/discourse/components/chat-drawer.hbs
plugins/chat/assets/javascripts/discourse/components/chat/navbar/back-button.gjs
plugins/chat/assets/javascripts/discourse/components/chat/navbar/channel-title.gjs
plugins/chat/assets/stylesheets/common/chat-drawer.scss
plugins/chat/assets/stylesheets/common/chat-navbar.scss

- Clicking the channel title of a collapsed drawer will only open the drawer, and not open settings
- Remove the back button when the drawer is collapsed
- Uses same icon for toggling on chat that composer

UX: improved collapsed drawer state/interactions

---

app/models/discourse_connect.rb
app/models/user_email.rb
spec/models/discourse_connect_spec.rb

We recently tried to default the `normalize_emails` site setting to `true` to avoid spam. What this does is it considers e-mails the same regardless of plus addressing, e.g. `bob+1@mail.com == bob+2@mail.com`. This caused some problems for SSO users.
This PR makes it so that DiscourseConnect never normalizes e-mails.

DEV: Ignore normalize_emails when using SSO

---

plugins/chat/assets/javascripts/discourse/components/chat/navbar/channel-title.gjs

There's already a test for this behavior and the CI is currently broken because of it.

FIX: correctly link to settings in full page

---

lib/upload_security.rb
spec/system/admin_about_config_area_spec.rb

Uploads that are linked to site settings shouldn't be flagged as secure in login-required sites that enable secure uploads. However, in order for site setting uploads to not be marked secured, the frontend uploader has to include 2 params in the upload request: `for_site_setting: true` and `type: "site_setting"`.
Since these 2 params are semantically identical, we want the `type: "site_setting"` param alone to make the upload correctly treated as a site setting upload. To achieve that, we need to include the `site_setting` type in the public types list because the `for_site_setting` param has the same effect — it marks the upload as a public type.
https://github.com/discourse/discourse/blob/b138eaf9e58d3207009b5efb9d5ffe37300877e3/lib/upload_security.rb#L128-L131
Meta topic (private): …

FIX: Don't secure the banner image for /about

---

app/assets/javascripts/admin/addon/components/bulk-user-delete-confirmation.gjs
app/assets/javascripts/admin/addon/controllers/admin-users-list-show.js
app/assets/javascripts/admin/addon/routes/admin-users-list-show.js
app/assets/javascripts/admin/addon/templates/users-list-show.hbs
app/assets/javascripts/discourse/app/components/responsive-table.hbs
app/assets/javascripts/discourse/tests/acceptance/admin-users-list-test.js
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/admin_bulk_users_delete_modal.scss
app/assets/stylesheets/common/admin/users.scss
app/controllers/admin/users_controller.rb
app/serializers/admin_user_list_serializer.rb
app/serializers/admin_user_serializer.rb
app/services/user/bulk_destroy.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/routes.rb
spec/requests/admin/users_controller_spec.rb
spec/serializers/admin_user_list_serializer_spec.rb
spec/system/admin_users_list_spec.rb
spec/system/page_objects/components/d_menu.rb
spec/system/page_objects/modals/bulk_user_delete_confirmation.rb
spec/system/page_objects/pages/admin_users.rb

This PR introduces a new feature that allows staff to bulk select and delete users directly from the users list at `/admin/users/list`. The main use-case for this feature is make deleting spammers easier when a site is under a large spam attack.
Screenshot:
Internal topic: t/140321.

FEATURE: Add bulk destroy to admin users list

---

lib/db_helper.rb
spec/lib/db_helper_spec.rb

This is a follow-up to the `remap` [refactor](https://github.com/discourse/discourse/commit/9b0cfa99c5277daccef24ef6e3b79597de1470a1). Similar to `remap`, the entire `regex_replace` operation fails if the new content exceeds the column’s max length.
This change introduces an optional mode, controlled by the new `skip_max_length_violations` param to skip records eligible for `regex_replace`  where the new content violates the max column length constraint.
It also includes updates to the exception message raised when `regex_replace` fails to include more details

DEV: Gracefully handle `regex_replace` max column length violations

---

app/controllers/uploads_controller.rb
spec/requests/uploads_controller_spec.rb

Previously, the secure-upload redirection logic would fail for extension-less files. This commit updates it to work, and adds a spec for the behavior.
Extension-less file uploads are not allowed by default, so this is a very niche situation.

FIX: Extension-less secure uploads

---

app/assets/javascripts/discourse/app/lib/transformer.js
app/assets/javascripts/discourse/tests/unit/lib/transformer-test.js

This unlocks the ability to use that function directly in templates:
```hbs
{{applyValueTransformer
"foo-bar"
@defaultValue
(hash arg1=@arg1 arg2=@arg2)
}}
```

DEV: Allow ember hash as a context in applyValueTransformer

---

plugins/styleguide/assets/javascripts/discourse/components/sections/molecules/tooltips.js

Tooltips have different triggers / untriggers by device type (mobile / desktop) and this PR provides the correct options in the styleguide based on device type.

FIX: `Tooltip` styleguide triggers not rendering options

---

lib/email/receiver.rb
spec/fixtures/emails/email_to_group_email_username_3.eml
spec/lib/email/receiver_spec.rb

This fix handles the case where an In-Reply-To mail header
can contain multiple Message-IDs. We use this header to
try look up an EmailLog record to find the post to reply
to in the group email inbox flow.
Since the case where multiple In-Reply-To Message-IDs is
rare (we've only seen a couple of instances of this causing
errors in the wild), we are just going to use the first one
in the array.
Also, Discourse does not support replying to multiple posts
at once, so it doesn't really make sense to use multiple
In-Reply-To Message-IDs anyway.

FIX: Handle multiple In-Reply-To Message-ID in group inbox

---

app/serializers/remote_theme_serializer.rb
spec/fabricators/theme_fabricator.rb
spec/serializers/remote_theme_serializer_spec.rb

At the top of the theme show page we have a link
to the theme About and License, which are supposed
to be URLs. However some themes have left placeholder
text in these metadata fields, which leads to a wonky
experience.
Instead, we can just not serialize these fields if they
are not valid URLs, then they will not show as links
in the UI.

FIX: Hide broken theme about/license URLs

---

app/models/reviewable_flagged_post.rb
spec/models/reviewable_flagged_post_spec.rb

We ran into an edge case where it was possible for a
ReviewableFlaggedPost to end up in a state where it was hidden
and the topic was already deleted. This meant that the Ignore
action bundle for the reviewable ended up empty, with no associated
actions.
This commit fixes the server-side issue where this was ending up
empty. A further commit will aim to make the client more resilient
to these issues by gracefully failing if a reviewable action bundle
is detected with no associated actions.

FIX: Empty post reviewable ignore bundle causing client errors

---

app/assets/javascripts/float-kit/addon/components/d-menu.gjs
app/assets/javascripts/float-kit/addon/components/d-tooltip.gjs

This fix will ensure we correctly play the close/destroy sequence in this situation.

FIX: correctly destroy menu/tooltip when removed from dom

---

app/assets/javascripts/discourse/app/templates/topic.hbs

This PR removes the duplicate html ID inserted on the anonymous footer button container as `the anonymous-topic-footer-buttons.js` file defines this ID already.
https://github.com/discourse/discourse/blob/c91dcd0447d4e5bda8be6e9fcfb9c37aae3ea1d0/app/assets/javascripts/discourse/app/components/anonymous-topic-footer-buttons.js#L8

FIX: Remove duplicate id

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

This option will allow the api user to specify if the original topic should be `frozen`(locked and posts not deleted neither moved)
With this option when moving topic posts your posts will be `copied` to the new topic and the original topic will be kept there.

FEATURE: Add `freeze_original` option to `PostMover`

---

app/assets/stylesheets/desktop/topic-post.scss

Broadly reported here and reproduced internally as well: https://meta.discourse.org/t/scroll-jumping-in-this-meta-site-while-viewing-threads/324800
Firefox in some situations seems to have very jumpy scroll. This is most notable in long topics while scrolling with a Macbook touchpad (perhaps the smoothing exacerbates it)... it seems to be a Firefox-specific performance issue with `position: sticky;` avatars. 
Disabling overflow anchor on these elements seems to have some positive impact (and there are no downsides since these images don't impact page height), so let's give it a try.

UX: attempt to reduce jumpy topic scroll in Firefox

---

app/assets/javascripts/discourse/app/routes/discovery-filter.js
config/locales/client.en.yml

This PR removes the `replace: true` option in the query param for the `/filter` route. This allows for the history to be preserved with each subsequent search as well as when we link to the filter route from another page.
Initially we had simply `replace: true` because on the `/filter` route we want to perform multiple filters without worrying about polluting the browser history. However, preserving the history is genuinely useful and we do so in other areas of the app with similar functionality such as the full page search.
No tests added as this is difficult to test browser back without having the browser refresh tests and make tests incomplete.
https://github.com/user-attachments/assets/a6765922-fc53-4b55-97a6-ad942e5cd4a5
https://github.com/user-attachments/assets/79e1f4f2-1604-4509-a8 …

FIX: Preserve history when routing to `/filter` route

---

config/locales/server.en.yml

The PR updates the regular badge description by removing "access a private lounge area," since the lounge category is no longer a default feature. For reference, see [this topic](https://meta.discourse.org/t/lounge-category-still-part-of-default-regular-badge-description/286061) reporting the issue.

UX: Remove lounge category from badge description

---

app/assets/javascripts/discourse/app/components/d-button.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/app/helpers/plugin-outlet.gjs
app/assets/javascripts/discourse/app/raw-views/topic-bulk-select-dropdown.gjs
app/assets/javascripts/select-kit/addon/components/topic-notifications-button.gjs

Using Ember's `<template>` dynamically is not supported. For every invocation, glimmer-vm has to run one-time setup, and will cache the result indefinitely. This leads to significant memory leaks, and eventual OOM errors.
This commit updates a handful of cases. We'll be following up with the more complex ones, and a linting rule to avoid re-introducing the problem in future.

PERF: Reduce use of dynamic `<template>` invocations

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

relates to this https://github.com/discourse/discourse/pull/29940
The issue was that it was shifting from the first post number rather than from the last:
```rb
[3, 4] -> shift_post_numbers -> ActiveRecord::RecordNotUnique:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_posts_on_topic_id_and_post_number"
DETAIL:  Key (topic_id, post_number)=(233, 4) already exists.
```
_before: the error is that the one in position 3 should not go to positon 4 because there were someone there already_
```rb
[4, 3] -> shift_post_numbers -> [5, 4]
```
_after fix, reversing the array_

FIX: Solve flaky tests in PostMover

---

app/assets/javascripts/admin/addon/components/admin-config-area-empty-list.gjs
app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
app/assets/javascripts/admin/addon/controllers/admin-whats-new.js
app/assets/javascripts/admin/addon/templates/whats-new.hbs
app/controllers/admin/dashboard_controller.rb
config/locales/client.en.yml
lib/discourse_updates.rb
spec/lib/discourse_updates_spec.rb
spec/requests/admin/dashboard_controller_spec.rb

Sometimes changes to "What's new?" feed items are made or the feed items are
removed altogether, and the polling interval to check for new features is 1 day.
This is quite long, so this commit introduces a "Check for updates"
button for admins to click on the "What's new?" page which will bust
the cache for the feed and check again at the new features endpoint.
This is limited to 5 times per minute to avoid rapid sending of
requests.

FEATURE: Allow admins to force refresh "What's new?"

---

config/site_settings.yml

This setting is not experimental anymore, and hasn't been
for a while.
Docs at https://meta.discourse.org/t/user-status/240335 will
be updated.

DEV: Move enable_user_status out of experimental category

---

plugins/chat/assets/stylesheets/common/chat-navbar.scss
plugins/chat/assets/stylesheets/desktop/chat-side-panel.scss

The min-width on the thread side panel was a bit too lenient at 150px. This commit implements a more graceful approach by setting it to a min-width of 33vw if possible, with a fallback to 350px minimum. This ensures better usability and decreases the risk of the title wrapping oddly. Additionally, the title is now working with `overflow-wrap: anywhere` to accommodate too long words where needed.

UX: update minwidth to chat sidepanel + better title word-break fn

---

app/models/reviewable.rb
app/models/reviewable_flagged_post.rb
app/models/reviewable_post.rb
app/models/reviewable_queued_post.rb
app/models/reviewable_user.rb
db/migrate/20241127034553_add_potentially_illegal_to_reviewables.rb
lib/post_action_creator.rb
spec/models/reviewable_flagged_post_spec.rb

We already add the "delete user" and "delete and block user" options to the drop-down for potential spam, but we should do this for potentially illegal posts as well.
This is entirely based on the implementation for the potential spam one, including caching the status on the reviewable record.
Also note that just as for potential spam, the user must be "deletable" for the option to appear.
I also took the liberty to move the options in the drop-down to what I think is a more intuitive place. (Between delete post and suspend/silence user.)
I have decided not to back-fill existing reviewables for now, for a couple reasons: 1) the potentially huge number of reviewables (high risk) and the ephemeral nature of reviewables (low reward), but we can reconsider if we think this is important …

DEV: Add "delete user" options to illegal flag review

---

app/assets/javascripts/discourse/app/components/emoji-picker.hbs

The use-case is for an upcoming TC that alters the emoji picker, among other things.

DEV: Add `emoji-picker-footer` plugin outlet

---

app/controllers/static_controller.rb
spec/requests/static_controller_spec.rb

Previously, we were doing a blank match validation here with: 
```
!redirect_location.match(login_path)
```
That means that any `redirect` parameter containing `/login` would be discarded. This causes a bug, for example `redirect=https://loginsite.test.com/about` would be discarded even though it is valid on a site with `base_url=https://loginsite.test.com`. 
The fix here moves the check a bit later and scopes it down to paths starting with `/login`.

FIX: Do not discard redirects containing "/login"

---

plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/spec/triggers/topic_tags_changed_spec.rb

The check for when a rule had multiple tags was exclusive; you had to have all the tags to trigger the automation. Now, it's inclusive; you can trigger the automation if you have any of the tags.

FIX: `TopicTagsChanged` trigger not working with multiple tags

---

app/controllers/groups_controller.rb
spec/requests/groups_controller_spec.rb

This adds a `skip_email` param for inviting users to the forum by email, when you don't want the actual email to be sent.

FEATURE: Allow add group member endpoint to skip invite emails

---

app/serializers/web_hook_post_serializer.rb
lib/post_destroyer.rb
spec/models/web_hook_spec.rb

- Generate webhook data after posts are destroyed
- Don't count user_deleted posts
See further:
- https://meta.discourse.org/t/discrepancies-in-webhook-topic-posts-count/292741
- https://meta.discourse.org/t/should-comments-webhook-update-count-after-deleting-posts-comments/336621/

FIX: topic post counts for webhook post_destroyed event

---

app/assets/javascripts/admin/addon/components/admin-config-areas/emojis-list.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/user-fields-list.gjs
app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
app/assets/javascripts/admin/addon/templates/permalinks-index.hbs

FIX: Missing translations for empty config area

---

lib/scheduler/defer.rb
spec/lib/scheduler/defer_spec.rb

Spec was flaky cause work could still be in pipeline after the defer
length is 0. Our length denotes the backlog, not the in progress
count.
This adds a mechanism for gracefully stopping the queue and avoids
wait_for callse

DEV: fix flaky spec

---

app/assets/javascripts/admin/addon/components/admin-config-area-empty-list.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/emojis-list.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/user-fields-list.gjs
app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
app/assets/javascripts/admin/addon/templates/permalinks-index.hbs

Followup ccc8e37dde6dd16de1f1103d60065c1b5afcbc6e
The fix above was good, but I would prefer to give
the option of untranslated vs translated label like
I have for other admin components for consistency.

DEV: Consistent AdminConfigAreaEmptyList options

---

plugins/chat/assets/stylesheets/desktop/chat-channel.scss
plugins/chat/assets/stylesheets/desktop/index.scss

This commit will hide the channel when the side panel is present and the width of the viewport is less than 1000px. This is especially useful when you want to focus reading a thread on a small screen.
This change only impacts desktops.

UI: hides channel with visible panel on narrow screen

---

config/database.yml

In our CI env, sometimes, we see problems regarding getting a connection from the pool. As it’s currently set to 1, increasing it a bit should fix that kind of issues.

DEV: Increase pool connections to 2 in test environment

---

README.md

Replace Boing Boing with HomeExchange forum. Also updated mobile preview image to replace Codecademy with OpenAI.
Before:
After:

Update customer image in README.md

---

plugins/chat/lib/chat/mailer.rb

Using CTEs and DISTINCT ON to:
- Pre-filter active users with correct preferences
- Get only first unread message per channel
- Eliminate redundant joins and message scanning
This reduces the query execution time by limiting message scanning and joins to only relevant users and messages.
Internal ref t/142836 & t/139517

PERF: Optimize query for finding users with unread chat messages

---

lib/scheduler/defer.rb

Checking if a connection is available is probably not enough, when the connection is available, we should still verify it’s not stale.

DEV: Try fixing flaky spec related to Scheduler::Defer

---

app/assets/javascripts/discourse/app/components/fullname-input.gjs
app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/javascripts/discourse/tests/acceptance/create-account-test.js
config/locales/server.en.yml
config/site_settings.yml

Follow-up https://github.com/discourse/discourse/pull/29959 to to enhance localization. Instead of using text directly from the site settings, the site settings now toggle descriptions on or off. You can use the text replacement feature to customize the content.

FIX: Localization for custom signup form descriptions

---

app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/stylesheets/common/base/personal-message.scss
app/assets/stylesheets/common/base/topic-post.scss

Animating the background-color property like this is not compositable for the browser, which means the animation is not smooth, and can contribute to the Cumulative Layout Shift web vital.
For now, we're removing this, and may consider re-introducing an alternative version in future based on user feedback.

UX: Drop post-background highlighting on navigation

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/models/post.js
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/discourse/tests/unit/models/post-test.js
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md

This PR ensures that tracked properties added to the post model are correctly synced when using `post.updateFromPost`.
It also introduces a plugin API to allow plugins to register new tracked properties in the post model without needing to modify the class

DEV: Ensure `post.updateFromPost` syncs tracked properties

---

app/assets/javascripts/discourse/app/models/post.js
app/assets/javascripts/discourse/tests/unit/models/post-test.js

This PR addresses an issue where the `like button` would not be updated properly when reloading a post that lost the only like it had received.

FIX: Reset likeAction when updating a cached post from JSON data

---

app/controllers/application_controller.rb
spec/requests/application_controller_spec.rb

This prevents requests that are routed to controllers that share the same name under different namespaces from getting identical value for the `X-Discourse-Route` response header.

DEV: Include controller namespace in X-Discourse-Route

---

app/assets/javascripts/discourse/app/components/page-loading-slider.gjs
app/assets/javascripts/discourse/app/services/loading-slider.js

- Use `requestAnimationFrame` when transitioning from `ready` -> `loading`. The previous `next()` implementation was unreliable, particularly in Safari, and would cause the loading slider to jump backwards instead of forwards
- Double the minimum transition time to 200ms. This avoids the rolling average being skewed too much by routes which load quickly without network access.

UX: Improve loading-slider behavior

---

app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js

We're now using QUnit's `module` directly in core and all plugins/themes.

DEV: Deprecate `discourseModule`

---

plugins/chat/assets/javascripts/discourse/components/chat-thread-heading.gjs
plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/browse.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel-thread.gjs
plugins/chat/assets/javascripts/discourse/components/chat/navbar/index.gjs
plugins/chat/assets/javascripts/discourse/components/chat/navbar/title.gjs
plugins/chat/assets/javascripts/discourse/components/chat/thread/header.gjs
plugins/chat/assets/stylesheets/common/chat-navbar.scss
plugins/chat/assets/stylesheets/common/chat-thread-heading.scss
plugins/chat/assets/stylesheets/common/index.scss
plugins/chat/assets/stylesheets/mobile/chat-navbar.scss
plugins/chat/test/javascripts/components/chat-thread-heading-test.gjs

We were using a complex logic to make it change size based on scroll position but this was imperfect and not visually pleasing. Also the title had been made a button which was causing the ellipsis to not work correctly, and I would prefer to not mix page knowledge (thread) with title component so I made this click logic directly in the chat-thread component.

UI: simplify chat thread title

---

plugins/chat/assets/javascripts/discourse/components/chat/thread/header.gjs

When the current user can't modify the thread title we shouldn't show it as a clickable area.

FIX: do not show as clickable the thread header

---

plugins/chat/assets/javascripts/discourse/components/chat/modal/thread-settings.gjs

This will ensure AI generated titles don't appear as out of range in the UI and also allow users to set longer titles. The limit in DB was already 100 so it's just a simple frontend change.

FIX: increase chat thread title limit

---

plugins/chat/assets/stylesheets/common/chat-thread-heading.scss

FIX: word break long continuous thread titles

---

lib/email/styles.rb
spec/lib/email/styles_spec.rb

Shortens multiple CSS style definitions in emails to the last given one.
https://meta.discourse.org/t/resolve-final-styles-in-email-notifications/310219

FIX: deduplicate css in mails

---

app/assets/javascripts/discourse/tests/helpers/component-test.js

Similar to [discourseModule](https://github.com/discourse/discourse/pull/30000) it's unused now

DEV: Deprecate `componentTest`

---

lib/discourse_diff.rb

When serializing the `body_changes` in the `PostRevisionSerializer`, we create two diffs: one for the `cooked` and another one for the `raw` version of the post.
Inside `DiscourseDiff`, we generate both `html` and `markdown` diffs when we only need the `html` diffs for the `cooked` version of the post and the `markdown` diff for the `raw` version of the post.
This solves the issue repored in https://meta.discourse.org/t/server-error-accessing-topic-revisions-on-a-specific-topic/339185 where some revisions would return 500 because of a `ArgumentError : Attributes per element limit exceeded` exception when trying to generate the `html` diff on a very large `raw`.

PERF: only diff HTML / Markdown when needed

---

lib/email/styles.rb
spec/integration/email_style_spec.rb
spec/lib/email/sender_spec.rb
spec/lib/email/styles_spec.rb

In order to limit issues with duplicate inline CSS definitions, this will now deduplicate inline CSS styles with the "last-to-be-defined-wins" strategy.
Also removes unecessary whitespaces in inline styles.
Context - https://meta.discourse.org/t/resolve-final-styles-in-email-notifications/310219
Follow-up to #30003

FIX: deduplicate inline styles in emails

---

app/assets/javascripts/admin/addon/routes/admin-user-index.js
app/assets/javascripts/admin/addon/templates/users-list-show.hbs
app/assets/javascripts/admin/addon/templates/users-list.hbs
app/assets/javascripts/discourse/tests/acceptance/admin-users-list-test.js
app/assets/stylesheets/common/admin/admin_base.scss
config/locales/client.en.yml
spec/system/admin_user_spec.rb
spec/system/admin_users_list_spec.rb
spec/system/page_objects/pages/admin_users.rb

Conversion of `/admin/users` page to follow admin UX guidelines.
In addition, add the username to the title on the user admin page.

UX: admins users page follows admin ux guideline

---

config/site_settings.yml

We are hiding this site setting because we no longer
support the old horizontal admin nav, and this setting
will be going away soon.

DEV: Hide admin_sidebar_enabled_groups

---

lib/backup_restore/restorer.rb

There is no point creating a message for the system user since it is a
non-human user.
There are no existing tests for the `BackupRestore::Restorer` class since it is hard to write an automated test for the whole restore process. Therefore, there are no tests for this change and I think it is fine since the impact of this change regressing is low.

DEV: Avoid creating system message when system user initiates restore

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/stylesheets/desktop/modal.scss

Uses the `htmlClass` to automagically set the `modal-open` class to `<html>` so that we can do `overflow: hidden` and prevent the "background" behind the modal from scrolling while the modal is open.
Internal ref - t/142760

UX: disable scrolling when modal is open on desktop

---

app/assets/javascripts/discourse/app/controllers/topic.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
spec/system/composer/discard_draft_spec.rb
spec/system/page_objects/components/composer.rb

BEFORE: if you click the "reply" button on a post and then decided that you want to "edit" the same post, clicking the "edit" button would do nothing. Clicking "edit" on another post works, but editing the same post would appear broken.
AFTER: if you click the "edit" button, it will properly load the content of the post you're trying to edit. No matter which one it is.
This was somewhat tricky to track down as the system specs seemed to contradict the qunit tests until I realized that the qunit tests were only testing the edit on the 1st post and the system specs were testing on replies.
I improved the qunit tests to test both editing OP and a reply and (hopefully) made the system specs a little bit clearer.
This is a follow up to bbe62d88d2554189e15f407736b1f7a01968c631.

FIX: editing post while replying

---

app/assets/stylesheets/mobile/login-signup-page.scss

This change allows the form to resize when the virtual keyboard is shown on mobile devices.
Otherwise, the keyboard would appear on top of the inputs. I was only able to reproduce the issue on a production site, on Android, in Chromium-based browsers.

FIX: Virtual keyboard for fullpage login/signup

---

app/assets/stylesheets/common/base/code_highlighting.scss

This PR adjusts codeblocks nested in link tags to convey they are links.
**Before**
**After**

FIX: adjust codeblock link styling

---

lib/onebox/engine/github_pull_request_onebox.rb
lib/onebox/engine/github_repo_onebox.rb
lib/onebox/mixins/github_body.rb

We were already stripping comments from GitHub issue/PR oneboxes, but the regex was not correctly matching multiline comments.

UX: Strip multiline comments in github oneboxes

---

app/assets/javascripts/discourse/app/components/category-list-item.js
app/assets/javascripts/discourse/app/components/parent-category-row.hbs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

Added 3 plugin outlets:
- `category-list-above-category-section` (above `td.category`)
- `category-list-above-topics-section` (above `td.topics`)
- `category-list-below-topics-section` (below `td.topics`)

FEATURE: Add plugin outlets to parent category row for desktop

---

config/nginx.sample.conf

This fixes a typo that was introduced in baa5389a237525514708a17dfa3c6b7012828dcb

DEV: Allow webp images to be served directly by nginx

---

plugins/chat/assets/stylesheets/common/chat-navbar.scss
plugins/chat/assets/stylesheets/desktop/chat-navbar.scss
plugins/chat/assets/stylesheets/desktop/index.scss
plugins/chat/assets/stylesheets/mobile/chat-navbar.scss

The main bug this commit is fixing is lack of spacing on the title "channels" when visiting the chat homepage on mobile.

FIX: attempt to simplify chat navbar spacing

---

db/migrate/20241127072350_remap_fa5_icon_names_to_fa6.rb
spec/migrations/remap_fa5_icon_names_to_fa6_spec.rb

The current migration would lead to us removing from the `svg_icon_subset` site setting any updated icon names with fab/far prefixes, leaving only the prefix. The migration for the other tables done directly in SQL is fine as we directly search for FA5 icon names before applying the remapping logic (I've added more example rows in the spec to verify this).

FIX: font awesome remapping migration should not drop unmapped names from svg_icon_subset

---

app/assets/javascripts/discourse/app/widgets/poster-name.js

Followup to 2513339955ebdfa457a5d6126716091110045e37

UX: Only add `user-badge-buttons` wrapper when badges exist

---

app/assets/javascripts/discourse/app/services/history-store.js

async/await doesn't play well with transitions (to be investigated… later)

FIX: Stick to then/finally in history-store

---

plugins/chat/assets/stylesheets/mobile/chat-navbar.scss

Minor alignment adjustment for text titles (this doesn't impact channel titles which are aligned correctly)
Before:
After:

UX: adjust mobile chat text title alignment

---

config/site_settings.yml

Followup 56df077931e42749ea254a9df32154a8aa13bddc
This removes info, support, and community as mandatory values for the reserved_usernames site setting. These could arguably be useful for admins generally. The rest can stay as-is as they are much more likely to be
confusing to members.
c.f. https://meta.discourse.org/t/default-reserved-usernames-can-not-be-deleted/336020

FIX: Remove some mandatory_values for reserved_usernames

---

app/models/emoji.rb
spec/lib/plugin/instance_spec.rb

Recent problems with custom emojis having `+` and `-` symbols in their names have surfaced, this addresses the issue.

FIX: Sanitization issue when replacing default emoji with custom emojis that contains `+` or `-` symbols

---

lib/onebox/templates/githubcommit.mustache
lib/onebox/templates/githubissue.mustache
lib/onebox/templates/githubpullrequest.mustache

Github oneboxes have an avatar next to the username text, and the alt for the avatar is the username. For screenreaders this is redundant information. 
If we're not providing a description of the avatar content (which github doesn't provide), then setting the alt attribute as the username results in the username being read twice... once for the image, and again for the actual text. 
So in this case, since the username is already provided, the image is decorative. Setting a blank alt attribute means screenreaders can skip it. 
This also fixes a broken image state, where if the image fails to load the alt text breaks the layout:
This conveniently fixes it

A11Y: remove redundant alt text from github oneboxes

---

script/discourse

This change allows backup CLI user to explicitly  exclude uploads from the generated backup

FEATURE: Add `--sql-only` option to discourse backup

---

app/controllers/admin/site_settings_controller.rb
app/services/site_setting/update.rb
config/locales/server.en.yml
spec/requests/admin/site_settings_controller_spec.rb
spec/services/site_setting/update_spec.rb

Previously when attempting to edit a globally shadowed setting, the
error message was not very helpful, it said "You are not allowed to
change hidden settings". This commit changes the error message to
reflect the actual problem, which is that the setting is shadowed by
a global setting via ENV var.

UX: Improve error when trying to edit globally shadowed setting

---

app/models/post.rb
lib/post_destroyer.rb
spec/lib/post_destroyer_spec.rb
spec/models/post_spec.rb

Currently, only system flags are translated. When we send a message to the user that their post was deleted because of a custom flag, we should default to the custom flag name.
Before: 
After:
Meta: https://meta.discourse.org/t/modify-add-site-text-associated-with-custom-moderation-flags/335942

FIX: update flag reason message with default value

---

spec/rails_helper.rb

Followup aca6c462a6af0eab53c7ea5820f2a9c65c5a88c7
Remove the warning message if DISCOURSE_INCLUDE_GEMS_IN_RSPEC_BACKTRACE
is not set for now while we decide whether we want to include
this or not, it's a little in-your-face.

DEV: Remove backtrace warning

---

plugins/discourse-presence/plugin.rb
plugins/discourse-presence/spec/integration/presence_spec.rb

In 0993273 we introduced the `whisper_allowed_group_ids` to allow whispers to more users than "staff".
The presence plugin hadn't been updated to account for this change.
Extracted from #30067

FIX: whisper's presence channels

---

app/assets/javascripts/discourse/app/lib/utilities.js

This replaces the video container / thumbnail with a proper "<video>" element when quoting a video.
It's not the best UX, especially when "morphing" is disabled.
Needs more work.
Internal ref - t/143321

FIX: unable to quote video

---

app/assets/javascripts/discourse-markdown-it/src/engine.js
app/assets/javascripts/discourse/app/lib/utilities.js

Follow up to f294f984cf64236a63e9ed21df3c8782e046c90f
All that was needed was a little fix to our markdown engine to use the "image src" as the "video src" when the "data video src" was not defined.
That way we can use the regular image markdown with the "|video" option (?).

FIX: properly quote videos

---

app/assets/javascripts/float-kit/addon/components/d-menu.gjs

`DMenu` is using in-element, which means the content is detached from the trigger, and pressing tab from the trigger is not going to jump into the content. This commit catches the tab event and attempts to focus the first focusable element of the content.

FIX: ensures tabbing from trigger focus content

---

app/assets/stylesheets/common/components/topic-map.scss

this moves padding to the parent container to avoid a situation where padding can be missing when a child div isn't rendered
Before:
After:

UX: fix topic map padding in low-content situations

---

lib/plugin/metadata.rb

Encrypt's tests are known to be flaky, and now seem to be impacting the poll plugin specs somehow. The plugin is end-of-life, with almost no users, so let's skip it on stable CI.

DEV: Skip encrypt on stable CI

---

app/assets/javascripts/discourse/app/templates/topic.hbs
app/assets/stylesheets/common/base/topic.scss
app/assets/stylesheets/desktop/topic.scss

This increases the flexibility of the layout of the inline title editing to avoid some awkward layout situations. 
I also added wrapping divs around the plugin outlets associated with each input, this makes the layout much easier to manage when they're used to add additional elements... 
On wide screens, not much should change:
Before, when tags would wrap the category input would stretch
After, instead the tag input will wrap if needed
Eventually tags will need to wrap again, but better if they do only when they have a full row:

UX: refactor title editing CSS to improve layout

---

app/models/reviewable.rb
lib/reviewable/actions.rb
spec/models/reviewable_spec.rb

Followup c7e471d35a0d394899eda5af26de64511e199cc6
It is currently possible to add a bundle (which is a collection
of actions used for a dropdown on the client) for a reviewable
via actions.add_bundle and then never add any actions to it.
This causes the client to explode, as seen in the referenced
commit, because of the way our store expects to resolve objects
referenced by ID that are passed down by the serializer, which
then causes Ember to have an unrecoverable render error.
Fixing this on the serializer level is not really possible because
of all the ActiveModel::Serializer magic that serializes
objects by ID reference when doing things like has_many.
`Reviewable#actions_for` is a better place to do this anyway,
because this is the main location where the bundles and actions
are built …

FIX: Discard empty bundles for reviewables

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-metadata.gjs
plugins/chat/assets/javascripts/discourse/models/chat-channel.js
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js
plugins/chat/spec/system/list_channels/drawer_spec.rb

This change sorts unread channels in descending order based on last message date, so channels with the latest activity will always appear at the top. It also adds some improvements for sorting channels with unread threads, now when multiple channels have unread threads, they will be sorted by last thread reply date to ensure more active channels rise to the top.
For DM channels, the order is now:
- Urgent (green badge) - unread messages, mentions and unread watched threads (most recent activity at top)
- Unread (blue badge) - unread tracked threads (most recent thread reply at top)
- Everything else (most recent message at top)

FIX: improve chat channel sorting for DMs

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-row.gjs

Channels with unread threads should have a font weight of bold to match unread channels.
Before:
After:

UX: make channel name bold for unread threads

---

app/assets/javascripts/admin/addon/templates/api-keys-index.hbs
app/assets/stylesheets/common/admin/admin_table.scss
app/assets/stylesheets/common/admin/api.scss
config/locales/client.en.yml

This PR makes the following updates:
* Removed the revoked icon
* Added a dedicated column for revoked status as a badge

UX: Move revoked API key status to dedicated column

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/select.gjs
app/assets/javascripts/discourse/tests/integration/components/create-invite-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/select-test.gjs
config/locales/client.en.yml

This commit will now show a "Select..." option when no value selected and a "Unselect" option when a value is selected, as the first row. It ensures that people don't think a value is selected when it's actually just the html select showing the first available option.

DEV: adds default option to form-kit select

---

app/assets/javascripts/discourse/app/components/user-profile-avatar.hbs

**Description** 
Adding plugin wrapper to user-profile-avatar as part of our move to officially deprecate (and then remove) template overrides

DEV: Add plugin wrapper to avoid template override in plugins

---

app/assets/javascripts/discourse/app/models/composer.js
app/assets/javascripts/discourse/app/models/topic.js
app/assets/javascripts/discourse/tests/unit/models/topic-test.js

This PR fixes an error that would be thrown in some edge cases where the composer is opened for a post instance without an associated topic model already loaded.
An example of such edge cases would be, a plugin trying to edit a post outside of the topic view.
This was causing an error that would prevent the composer from being opened.

DEV: Fix open composer without post topic loaded

---

app/models/moved_post.rb
app/models/post_mover.rb
db/migrate/20241205162117_add_columns_to_moved_posts.rb
spec/models/post_mover_spec.rb

Follow-up from this PR - https://github.com/discourse/discourse/commit/9b8af0ea9fdd8e82e8c1dc4fedcc754bff8830c9
Adds helpful data into `MovedPost` records for later lookup. ALSO fixes notifications for `freeze_original` to point to the newly created post, not the moved post.

DEV: Add user_id and post_user_id to MovedPost records

---

app/assets/javascripts/admin/addon/templates/dashboard_general.hbs

We want to point to our dedicated /admin/whats-new
page which is more focused and has better screenshots
and so on.

UX: Change "What's new in Discourse?" link

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/components/topic-list/list.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

These will enable https://github.com/discourse/discourse-topic-thumbnails/pull/60

DEV: Update transformers in topic-list/item

---

config/locales/server.en.yml
config/site_settings.yml
db/migrate/20241206002425_drop_experimental_topics_filter_site_setting.rb

This is a follow-up to e6fdfcdcd25d4bf7f009079cace41d0e9ffe4791 which
did not remove the site setting from `config/site_settings.yml` and drop
the site setting value from the database.

DEV: Drop `experimental_topics_filter` site setting take 2

---

app/assets/stylesheets/common/base/personal-message.scss

This needs some more work, but makes the layout less broken for now 
Before:
After:

UX: fix PM topic map layout

---

plugins/chat/assets/javascripts/discourse/components/chat-channel-row.gjs

Follow up to #30127.
Normally when viewing a channel with tracked threads, we dismiss the blue dot next to the channel name even though the thread has not been read yet.
This change applies the same criteria to determine if we should bold the channel name.
When we have unread threads but haven't opened the channel yet (looks correct):
We open the channel but don't open the thread:
After hitting the back button or channels tab the channel name is still bolded but blue dot removed:

UX: fix channel name style for unread threads

---

app/assets/javascripts/discourse/app/templates/group.hbs
app/assets/javascripts/discourse/tests/acceptance/group-manage-membership-test.js

Follow up to #28630 which added the tooltip on automatic group.
It was missing a check to ensure the current user is an admin, since only admins can manage automatic groups.
Reported in https://meta.discourse.org/t/324215 by @moin-Jana
Closes #30154

UX: only show automatic group tooltip to admins

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

Currently when copy an OP to another topic, the link is to the topic that _wasn't_ moved. The notification should instead be to the new topic the OP was moved to -- we have duplicate logic already for this but first post creation get special treatment, and this applies the same treatment.

FIX: freeze_original for moved_post notifications for OP moves, link to destination topic

---

plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js

Some users are seeing consistent "Error 5" crashes in chrome when saving/deleting bookmarks on chat messages.
When crash logging is enabled, the message is:
`[33466:259:1206/122312.195048:ERROR:ax_object.cc(3400)] Check failed: !NeedsToUpdateCachedValues(). Stale values: "Group" axid#7543 <svg#discourse-emojis> needsToUpdateCachedValues/disallowed isIgnored inUserAgentShadowRoot:<use> isInert needsToUpdateChildren hasDirtyDescendants`
This seems to be influenced by a few factors, including the re-render of the bookmarks button, the adjacent 'reactions' button, and also the opening/closing of the modal.
Adding this `activeElement.blur` seems to avoid the issue in my manual testing. Hopefully, this can be dropped after future chrome releases.
Internal topic: t/143485

DEV: Add workaround for chrome crash

---

app/views/users/admin_login.html.erb

The submit button here (/u/admin-login) is a weird case at the moment, it's an input with button classes added.
This can cause the button to pickup styles of both a button and an input in a theme, which is undesirable. Better to be a button. 
Tested to verify that it still submits properly and generates an email.

DEV: admin-login submit should be a button, not an input

---

plugins/chat/assets/stylesheets/desktop/chat-side-panel.scss

It's been set to this value as a workaround for long thread titles, but we now have standalone thread titles in the thread body which makes this not needed. People had troubles understanding why they couldn't resize more the thread panel.

FIX: lower thread panel min-width

---

app/assets/javascripts/discourse/app/models/post.js
spec/system/post_menu_spec.rb

This commit fixes an issue where the recover button would not be displayed for a user delete post.

FIX: Recover user deleted post

---

app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
app/assets/javascripts/admin/addon/components/themes-grid-card.gjs
app/assets/javascripts/admin/addon/components/version-checks.hbs
app/assets/javascripts/admin/addon/templates/user-index.hbs
app/assets/javascripts/discourse/app/components/post/menu/buttons/read.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/show-more.gjs
app/assets/javascripts/discourse/tests/unit/lib/icon-library-test.js
plugins/chat/admin/assets/javascripts/admin/components/admin-chat-incoming-webhooks-list.gjs
plugins/poll/plugin.rb

This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update more deprecated Font Awesome icon names

---

app/assets/javascripts/admin/addon/components/themes-grid-card.gjs
app/assets/stylesheets/common/components/theme-card.scss

This PR updates deprecated Font Awesome icon names in the ThemesGridCard component and associated styling. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: update deprecated icon names in themes-grid-card

---

app/assets/javascripts/admin/addon/templates/users-list.hbs
spec/system/admin_users_list_spec.rb
spec/system/page_objects/pages/admin_users.rb

Omission and instead of `permlinks`, `users` title should be used.
Screenshot

FIX: correct breadcrumb for admin users page

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
spec/system/admin_sidebar_navigation_spec.rb

This is so the link is more visible, instead of being
buried in the Account section.

UX: Move "What's new?" link in admin sidebar to root section

---

lib/discourse_logstash_logger.rb

We already have a `GIT_VERSION` constant in `DiscourseLogstashLogger` so
we can just use that.

PERF: Don't execute a `git` command each time we log a log line

---

lib/guardian/user_guardian.rb
plugins/chat/spec/system/user_profile_spec.rb
spec/lib/guardian/user_guardian_spec.rb
spec/requests/list_controller_spec.rb
spec/requests/posts_controller_spec.rb
spec/requests/user_actions_controller_spec.rb
spec/requests/user_badges_controller_spec.rb
spec/requests/users_controller_spec.rb
spec/serializers/user_serializer_spec.rb

We've seen in some communities abuse of user profile where bios and other fields are used in malicious ways, such as malware distribution. A common pattern between all the abuse cases we've seen is that the malicious actors tend to have 0 posts and have a low trust level.
To eliminate this abuse vector, or at least make it much less effective, we're making the following changes to user profiles:
1. Anonymous, TL0 and TL1 users cannot see any user profiles for users with 0 posts except for staff users
2. Anonymous and TL0 users can only see profiles of TL1 users and above
Users can always see their own profile, and they can still hide their profiles via the "Hide my public profile" preference. Staff can always see any user's profile.
Internal topic: t/142853.

FEATURE: Restrict profile visibility of low-trust users

---

app/assets/javascripts/admin/addon/components/bulk-user-delete-confirmation.gjs
app/controllers/admin/users_controller.rb
app/services/user/bulk_destroy.rb
config/locales/client.en.yml
spec/requests/admin/users_controller_spec.rb
spec/system/admin_users_list_spec.rb
spec/system/page_objects/modals/bulk_user_delete_confirmation.rb

This PR adds an option for blocking the IP and email addresses when bulk-deleting users.
Internal topic: t/140321/11.

FEATURE: Add an option to block IPs and emails to bulk user delete

---

plugins/chat/assets/javascripts/discourse/components/channels-list-public.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channels.gjs
plugins/chat/assets/javascripts/discourse/components/chat/routes/channels.gjs
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js
plugins/chat/spec/system/list_channels/sidebar_spec.rb

This change creates a shallow copy of the public message channels so we don't change the original array while sorting.
Without this change the `publicMessageChannels` getter cache gets invalidated and cached again with the sorted channels array instead, which causes a bug where the sidebar channel list sorting order is updated by activity when user interacts with the chat drawer.
Note: sidebar is the only place that we don't sort chat channels by activity, and it directly loads the channels by calling `chatChannelsManager.publicMessageChannels`.
Internal ref: /t/-/143486

FIX: chat channel sort order consistency in sidebar

---

plugins/discourse-presence/assets/javascripts/discourse/components/composer-presence-display.gjs
plugins/discourse-presence/assets/javascripts/discourse/components/topic-presence-display.gjs

Since 3e7f0867ea044ffd3e957946e1996736d4a19df8, I started seeing some specs fail due to the following error
```plain
Error occurred while rendering: top-level application > discourse-root > topic > discourse-topic > topic-navigation > plugin-outlet > plugin-connector > topic-presence-display
/assets/plugins/discourse-presence.js - Uncaught TypeError: Cannot destructure property 'whisperer' of 'this.currentUser' as it is null.
```
For some reasons I can't fanthom, the presence components seem to be rendered even though they're using outlets that are only rendered when a user is signed in... 🤷‍♂️
Lost too much time trying to reproduce so I ended up adding this `if (!this.currentUser) { return; }` condition to both "presence display" component to (hopefully) fix these flakes.

DEV: attempt to fix some system spec flakes

---

app/controllers/drafts_controller.rb
spec/requests/drafts_controller_spec.rb

In 806e37aaec549069a599fd31edc16c5cdcd0774e, I improved the conflict handling when editing a post to account for title and tags.
This fixes an edge cases when a topic has a hidden tag the current editor can't see. When they submit their edit, we automatically add the hidden tags before checking with the tags stored in the database.
Reported in https://meta.discourse.org/t/341375

FIX: correctly handle hidden tags when checking for edit conflicts

---

lib/middleware/anonymous_cache.rb

We identify and deny blocked crawlers here in anonymous_cache.
Separating the notion of the crawler identifier here lets plugins perform an
override if they perform more advanced detection.

DEV: add the notion of a 'crawler identifier' in anonymous_cache

---

app/assets/javascripts/discourse/app/components/navigation-bar.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

Adds `navigation-bar-dropdown-mode` and `navigation-bar-dropdown-icon` value transformer for use here: https://github.com/discourse/discourse-compact-nav/pull/19

DEV: add transformers to navigation bar for theme dev

---

config/unicorn.conf.rb

In 6cafe59c76fd2e1151f2b8483402a6984ccd901b, we added a monkey patch to
`Unicorn::HtppServer#murder_lazy_workers` to log a message and send a
`USR2` signal to the Unicorn worker process when the Unicorn worker
process is 2 seconds away from being timed out by the Unicorn master
process. However, we ended up logging multiple messages and sending
multiple USR2 signal during the 2 seconds before the Unicorn worker
process hits the time out.
To overcome this problem, we will now set an instance variable on the
`Unicorn::Worker` instance and use it to ensure that the log message is
only logged once and USR2 signal to the Unicorn worker process is only
sent one as well.
This change has to be tested manually. To replicate the problem, follow the steps below:
1. Run `UNICORN_TIMEOUT=5 …

DEV: Fix duplicated logging of unicorn worker backtraces

---

script/db_timestamps_mover.rb

The three tables listed have been dropped and no longer need to be ignored: https://github.com/discourse/discourse-topic-voting/commit/6d52b8cfa8b3e2920aa3f12fc52673b88f53f776

DEV: Remove ignored tables that have been dropped

---

app/assets/stylesheets/common/admin/dashboard.scss

This PR resolves an issue where the "Experimental" badge would break onto a new line when the title was too long, causing the badge text to separate from the icon. The fix ensures the badge text and icon remain aligned, even with longer titles.

FIX: Prevent experimental badge from splitting onto new lines with long titles

---

app/jobs/base.rb
lib/discourse.rb
spec/jobs/jobs_base_spec.rb

This reverts commit 766ff723f8c216b2bf59053dba302b82e1d34d4b and reintroduces 1670ffe82dbfa46f33df94312a8649ab8117d19b.
Ensure that we create the sidekiq log file first before opening it for
logging. This avoids any issue of the log file not being present when we
initialize an instance of the `Logger`.

DEV: Remove unnecessary thread in `Jobs::Base::JobInstrumenter` take 2

---

app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
config/locales/client.en.yml

Makes it so the result of toggling a new feature
feed item is clearer.

UX: Copy for feature feed toggle

---

app/assets/javascripts/discourse/app/components/fast-edit.gjs
app/assets/javascripts/discourse/app/components/post-text-selection.gjs
app/assets/javascripts/discourse/tests/acceptance/fast-edit-test.js
spec/system/post_selection_fast_edit_spec.rb

When a post containing an apostrophe (') is being cooked, the apostrophe is being converted to the "typographic" version (’) (because we enable markdown-it's **typographer** mode by default in Discourse)
When you select text that contains such apostrophe and then try to save your fast edit, it fails miserably without any error.
That's because when you select text from the DOM, it uses the cooked version which has the typographic apostrophe.
When you save your fast edit, we fetch the raw version of the post, which has the "regular" apostrophe. Thus doing `raw.replace(selectedText, editedText)` doesn't work because `raw` has the regular apostrophe but `selectedText` has the typographic apostrophe.
Since it's somewhat complicated to handle all typographic characters, we would basically have …

FIX: fast edit with a typographic character

---

app/assets/javascripts/discourse/app/lib/safari-hacks.js

Ensures composer does not go out of view after adding an upload.
Internal ticket 143769

FIX: Composer position on DiscourseHub iOS

---

app/assets/javascripts/discourse-i18n/src/index.js

We now extensively reference the `{ i18n }` named export of the `discourse-i18n` package, instead of calling `I18n.t` directly. That means that mutations of `I18n.t` no longer have any impact on most of the app.
This commit updates the verbose localisation logic to be switched by a boolean instead of a method mutation.

DEV: make verbose localization work without mutating I18n.t

---

spec/fabricators/user_fabricator.rb
spec/requests/directory_items_controller_spec.rb

The directory items controller specs that have a search param were not
matching how things worked in production. In a non-test environment the
UserSearch class depends on the `user_search_data` table being
populated, so the tests I corrected now use this table as well to match
reality.
Also added a new test to match the 20 user limit for search results that
currently exists. This 20 user limit is on the line between a bug and a
feature but it is how it is currently working so we should document
that. We have plans to increase this limit and it has been documented
here: https://meta.discourse.org/t/296485
This PR is a no-op and only changes the tests.
Co-authored-by: brrusselburg <25828824+brrusselburg@users.noreply.github.com>

DEV: Fix specs for directory items controller

---

lib/tasks/s3.rake

This is because Sprocket's manifest already contains the source maps.
The easy and safe fix here is to just use a `Set` to prevent
duplications.

FIX: `s3:upload_assets` uploaded some source maps twice

---

lib/tasks/assets.rake

The `max_compress?` logic is totally broken at least when used for
brotli compression because we are only seeing 4 assets subjected to the
max compression level in production. Instead of fixing the broken logic,
we should just drop this unnecessary complexity cause things are easier
to reason about when we only have one compression level to deal with
across all assets.

DEV: Remove max compression level for brotli in assets.rake

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

This is a follow-up to #30176.
When moving multiple first posts to an existing topic whilst preserving chronological ordering, the second move can trigger a PostgreSQL error:
```
PG::UniqueViolation:
ERROR:  duplicate key value violates unique constraint "post_timings_unique"
DETAIL:  Key (topic_id, post_number, user_id)=(1278, 2, 2261) already exists.
```
Additionally, if you move from the same topic to a newer destination: it will fail with this error:
```
PG::CardinalityViolation:
ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```
Both of these issues can be fixed using the same approach as in #30176: ensuring we only copy post timings for the specific …

FIX: When moving first posts between topics, ensure only relevant timings are moved

---

app/assets/stylesheets/common/base/sidebar.scss

reported here: https://meta.discourse.org/t/minor-visual-issue-when-theres-a-vertical-scrollbar-in-the-admin-sidebar/341822
Before:
After:

UX: fix admin sidebar header width

---

app/assets/stylesheets/common/admin/admin_config_area.scss
app/assets/stylesheets/common/admin/site-settings.scss

This was fixed previously but must have regressed, we
are showing a darker grey background around the
"Only show overridden" checkbox for our Settings tab
in config pages.
**Before**
**After**

FIX: Background color for settings overriden filter

---

lib/db_helper.rb
spec/lib/db_helper_spec.rb

The new name may be too long for the bookmarks.name column and raise an exception. This changes allows the remapper to truncate the new value to fit (truncates to 100 characters).

FIX: Truncate bookmarks.name when remapping

---

lib/excerpt_parser.rb
spec/lib/excerpt_parser_spec.rb
spec/lib/pretty_text_spec.rb

It doesn't make much sense to have the content of a `<details>` in an excerpt so I replaced them with "▶ summary" instead.
That way, they can't be (ab)used in user cards for example.
Reference - https://meta.discourse.org/t/335094

FIX: proper details / summary excerpt

---

plugins/discourse-narrative-bot/config/locales/server.en.yml
plugins/discourse-narrative-bot/lib/discourse_narrative_bot/new_user_narrative.rb
plugins/discourse-narrative-bot/spec/discourse_narrative_bot/new_user_narrative_spec.rb

Group names are translated, so the slug changes depending on the default locale. This could break the link to the staff group.

FIX: Link to group didn't work in locales other than English

---

app/assets/javascripts/discourse/app/components/topic-timeline/container.gjs
app/assets/stylesheets/common/base/topic-footer.scss
app/assets/stylesheets/mobile/topic-footer.scss

Follow up of https://github.com/discourse/discourse/pull/30132
* the timeline on mobile turned out too small => increased in size
* same for the buttons: increased size and spacing
* use a different layout for the buttons, to make the reply button stand out more
* fix a scoping issue with the timeline on desktop
* fix the missing timeline tracking button on desktop
* fix (some) button height issues

UX: increase button sizes and timeline size

---

app/assets/javascripts/discourse-common/addon/deprecation-workflow.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/widgets/post.js
app/assets/javascripts/discourse/tests/acceptance/keyboard-shortcuts-test.js
app/serializers/current_user_serializer.rb
config/site_settings.yml
db/migrate/20241211030039_remove_glimmer_post_menu_groups_setting.rb

This commit starts the rollout of the Glimmer post menu:
- default to `auto`: after the upgrade, it will be enabled on all discourse instances that do not have incompatible customizations
- unsilence the deprecation messages in the console
- removes the setting `glimmer_post_menu_groups` as it's no longer in the test phase

Switch the glimmer post menu to auto and unsilence deprecations

---

app/assets/javascripts/discourse/app/components/d-stat-tiles.gjs
app/assets/javascripts/discourse/tests/integration/components/d-stat-tiles-test.gjs
app/assets/stylesheets/common/components/_index.scss
app/assets/stylesheets/common/components/d-stat-tiles.scss

Introduces a new component used to show a grid of stats
on any page, mostly used for dashboards and config pages.
This component yields a hash with a `Tile` component property,
and the caller can loop through their stats and display them
using this component.
Each stat needs a `@label` and a `@value` at minimum, but can
also pass in a `@tooltip` and a `@url`.
Here is an example, but note the title and the white box around
the stats is a separate component, `<AdminConfigAreaCard />`,
which may be ported to core eventually.

UX: Introduce <DStatTiles /> component

---

lib/tasks/s3.rake

We can't delete the file from disk as some of the assets are still
served by the app instead of going through the S3 bucket. It is a bug we
need to fix but it also means this ENV is unsafe now. Just drop the env
until we ensure all assets requested by the app are requested from the
S3 bucket directly.
I tried out the ENV on my own test site and it broke it.

DEV: Remove line of code that does not work

---

lib/service/base.rb
plugins/chat/app/services/chat/create_message.rb
plugins/chat/app/services/chat/update_channel.rb
spec/lib/service_spec.rb

Currently, there are two ways (kind of) for accessing `params` inside a service:
- when there is no contract, or it hasn’t been reached yet, `params` is just the hash that was provided to the service. To access a key, you have to use the bracket notation `params[:my_key]`.
- when there is a contract, and it has been executed successfully, `params` now references the contract and the attributes are accessible using methods (`params.my_key`).
This PR unifies how `params` exposes its attributes. Now, even if there is no contract at all in a service, `params` will expose its attributes through methods, that way things are more consistent.
This PR also makes sure there is always a `params` object available even when no `params` key is provided to the service (this allows a contract to fail …

DEV: Unify params access in services

---

app/helpers/application_helper.rb
app/views/layouts/_head.html.erb
app/views/layouts/finish_installation.html.erb
spec/helpers/application_helper_spec.rb

Adds the `color-scheme` meta tag to the `_head` partial and removes it from the finish installation template to prevent it from being added twice.

UX: add color-scheme meta tag to _head

---

app/assets/javascripts/discourse/app/form-kit/components/fk/collection.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field-data.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/object.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/collection-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/object-test.gjs
app/assets/stylesheets/common/form-kit/_collection.scss
app/assets/stylesheets/common/form-kit/_index.scss
app/assets/stylesheets/common/form-kit/_object.scss

Collections were an existing concept in FormKit but didn't allow nesting. You can now do infinite nesting:
```gjs
<Form
@data={{hash
foo=(array
(hash bar=(array (hash baz=1))) (hash bar=(array (hash baz=2)))
)
}}
as |form|
>
<form.Collection @name="foo" as |parent parentIndex|>
<parent.Collection @name="bar" as |child childIndex|>
<child.Field @name="baz" @title="Baz" as |field|>
<field.Input />
</child.Field>
</parent.Collection>
</form.Collection>
</Form>
```
On top of this a new component has been added: `Object`. It allows you to represent objects in your form data. Collections are basically handling arrays, and Objects are objects.
This is useful if you form data has this shape for example:
```javascript
{ foo: { bar: 1, baz: 2 } }
```
This can now be mapped in your form using this …

DEV: adds support for nested collections and objects

---

app/assets/javascripts/discourse/app/controllers/user.js
app/assets/javascripts/discourse/tests/acceptance/user-profile-summary-test.js

When viewing your own user profile, we offer the ability to expand / collapse your user info.
By default, the info are collapsed and the button to toggle it only worked once. Meaning you could expand the info but not collapse it back.
This fixes the issue by using `toggleProperty()` instead of directly `set()`-ing a value.
Also added an acceptance test to ensure it doesn't regress.
Was reported in https://meta.discourse.org/t/342254

FIX: expanding / collapsing own user info panel

---

app/assets/javascripts/discourse/config/environment.js
app/assets/javascripts/discourse/tests/test-boot-ember-cli.js

This feature writes a stack trace as part of the message. That means it is not sourcemapped by the browser, and you have further to scroll to find the real backtrace.
In the past we avoided this feature with our production 'deprecation shim', but that was removed as part of our Ember 5.12 upgrade.
Before:
After:

DEV: Disable Ember's LOG_STACKTRACE_ON_DEPRECATION

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

With the new `freeze_original` option to PostMover, there are occasions where we want to grab the old post event handlers for this DiscourseEvent. This commit simply passes it as a third argument to the DiscourseEvent.

DEV: Pass in old post to post_moved DiscourseEvent

---

app/jobs/scheduled/ensure_db_consistency.rb
app/jobs/scheduled/periodical_updates.rb
app/models/user_avatar.rb
app/models/user_email.rb
spec/jobs/periodical_updates_spec.rb
spec/models/user_avatar_spec.rb
spec/models/user_email_spec.rb

This allows the periodical job that rebakes old posts to proceed even when user avatars have users that no longer exist or are related to users that are missing their primary email addresses. These type of avatars can lead to cases where the last_gravatar_download_attempt timestamp is set to nil since gravatars are dependent on the existence of an email address.
We tackle this problem in two ways:
1. We scope out inconsistent data for user avatars when doing the conditional check on whether to rebake old posts.
2. We clean the inconsistent data for UserEmail and UserAvatar during the EnsureDbConsistency job

DEV: ensure rebaking works even when some users have inconsistent data

---

lib/backup_restore/database_restorer.rb
lib/backup_restore/restorer.rb
script/discourse

This can be helpful if you need to fix problems in the DB before the DB gets migrated, as well as before uploads are restored.

FEATURE: Allow pausing of restore before DB migration and uploads are restored

---

app/models/theme.rb
lib/theme_javascript_compiler.rb
spec/lib/theme_javascript_compiler_spec.rb
spec/models/theme_field_spec.rb

Previously, theme hbr files were compiled to an IIFE, which would be executed before the app is booted. That is causing silenced deprecations to be printed, because the deprecation-workflow isn't set up when the IIFE is run.
This commit updates the theme compiler so that it matches the ember-cli-based raw-hbs compiler. Templates are output to normal modules, which will then be loaded by the existing `eager-load-raw-templates` initializer. This runs after the app has started booting.

DEV: Compile theme raw-hbr to modules

---

app/assets/javascripts/discourse/app/components/topic-list/list.gjs

Using the (array) helper creates an array instance, passes it to applyValueTransformer, which then allows themes/plugins to mutate it.
When the helper is re-computed, the **same array instance** is passed to the transformers again. Any elements added in the last run are still there.
This commit moves applyValueTransformer to a getter, so that it's run with a brand new array each time.

DEV: Move topic-list-class transformer to getter

---

app/assets/javascripts/discourse/app/components/topic-list/unread-indicator.gjs
app/assets/javascripts/discourse/tests/integration/components/topic-list-item-test.gjs

FIX: Correctly display group unread indicator in gjs

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
config/locales/client.en.yml
spec/system/admin_sidebar_navigation_spec.rb

Add groups link to the admin and moderator sidebar for easy access.
Currently, the admin needs to go to `users` first.

UX: display groups link when disabled group directory

---

app/models/user_custom_field.rb
spec/models/user_custom_field_spec.rb

The addition of the `.where("user_custom_fields.name ~ ?", '^user_field_\\d+$')` clause prevents the error below from occurring, when a user_field is not named with the required integer suffix.
```
ERROR:
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type integer: "invalid"
```

FIX: Searchable user fields do not always have an integer name

---

app/assets/javascripts/discourse/app/components/reviewable-item.js
app/assets/javascripts/discourse/app/controllers/review-index.js
app/assets/javascripts/discourse/app/routes/review-index.js
app/assets/javascripts/discourse/app/templates/review-index.hbs
app/assets/stylesheets/common/base/reviewables.scss
app/controllers/reviewables_controller.rb
app/models/reviewable.rb
app/models/reviewable_score.rb
app/serializers/reviewable_flagged_post_serializer.rb
app/serializers/reviewable_score_type_serializer.rb
config/locales/client.en.yml
spec/requests/reviewables_controller_spec.rb

Add flag reason filter and improve handling of deleted content in review queue
This commit enhances the review queue with several key improvements:
1. Adds a new "Reason" filter to allow filtering flags by their score type
2. Improves UI for deleted content by:
- Adding visual indication for deleted posts (red background)
- Properly handling deleted content visibility for staff (category mods can not see deleted content)
3. Refactors reviewable score type handling for better code organization
4. Adds  tests for trashed topics/posts visibility
This change will help moderators more efficiently manage the review queue by
being able to focus on specific types of flags and better identify deleted
content.

FEATURE: Reason and deleted content support in the review queue

---

app/assets/javascripts/admin/addon/components/admin-config-area-card.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/about.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-config-area-card-test.gjs
app/assets/stylesheets/common/admin/admin_config_area.scss

Additional `collapsable` argument which makes area cards collapsible.

UX: the ability to collapse AdminConfigAreaCard

---

app/assets/javascripts/discourse/tests/acceptance/forgot-password-test.js
config/site_settings.yml
plugins/automation/spec/integration/core_ext_spec.rb
spec/integration/invite_only_registration_spec.rb
spec/lib/email_updater_spec.rb
spec/models/invite_spec.rb
spec/requests/api/users_spec.rb
spec/requests/users_controller_spec.rb
spec/requests/users_email_controller_spec.rb
spec/system/email_change_spec.rb
spec/system/login_spec.rb
spec/system/signup_spec.rb

We're changing the default of `hide_email_address_taken` to `true`. This is a trade-off we want to make, as it prevents account enumeration with minimal impact on legitimate users. If you forget you have an account and try to sign up again with the same e-mail you'll receive an e-mail letting you know.
**Before:**
**After:**

DEV: Change hide_email_address_taken default to true

---

config/application.rb

When adding new fonts to our discourse-fonts gem,
you may want to test these changes locally using the
`path` option of the gem line in bundler.
However we set a symlink for the fonts dir for public/fonts,
which does not get updated if the gem path changes. This
fix checks if the current symlink resolved path is equal to
the DiscourseFont gem path, and if not deletes + recreates it.

DEV: Delete symlink when DiscourseFont path changes

---

lib/topic_query.rb
spec/lib/topic_query_spec.rb

new_in_category was using `first` instead of `limit`
this meant it gets an array and that means that you can not operate on it easily in a modifier.
this ensures we always give the modifier a relation, with the notable exception of suggeted topics.

FIX: use relations for new_in_category

---

spec/requests/users_email_controller_spec.rb

This should be the last fallout from changing `hide_email_address_taken` default. 🤞

DEV: Fix flaky users_email_controller_spec test case

---

app/assets/javascripts/discourse/app/components/d-select.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/select.gjs
app/assets/javascripts/discourse/tests/integration/components/create-invite-test.gjs
app/assets/javascripts/discourse/tests/integration/components/d-select-test.gjs

When using FK select, we include a "None" option automatically. However, for required select fields, "None" isn't a valid option, so we exclude it instead.

DEV: Don't include blank option for required selects

---

app/assets/javascripts/admin/addon/components/webhook-status.gjs
app/assets/javascripts/admin/addon/templates/web-hooks-index.hbs
app/assets/javascripts/discourse/tests/integration/components/webhook-status-test.gjs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/admin_table.scss
app/assets/stylesheets/common/admin/api.scss

UX: Apply admin table to webhooks

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

When `freeze_original` option is passed to PostMover, and we are moving all posts there is an issue. We attempt to put the small_action right after the last moved post. The issue is when there is an existing small action after the last moved "real" post. We then try to put the moderator post at the same location of the existing small action, which causes an index conflict and the move fails.
This makes sure that we place the moderator post at the verrrrrry end of the topic :)

FIX: Correct moderator post position for full topic move with freeze_original

---

app/assets/javascripts/discourse/app/components/d-button.gjs

Followup to #28019, on iOS this delay means that we don't properly set focus on the composer.

DEV: Do not delay DButton actions on iOS

---

app/assets/javascripts/discourse/app/components/local-login-form.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/toggle-password-mask.hbs
app/assets/javascripts/discourse/app/templates/invites/show.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/stylesheets/common/base/login.scss

This PR moves away from "show" text, and toward an eye/eye slash icon button within the password input for password masking. This is to save space on login/signup forms.
**Before**
**After**

UX: move to icon for password masking

---

app/assets/javascripts/discourse/app/components/create-topic-button.hbs
app/assets/javascripts/discourse/app/components/create-topic-button.js
config/locales/client.en.yml

Originally reported here: https://meta.discourse.org/t/wrong-reason-for-not-allowing-topic-creation/286132
Currently, if you're not allowed to post because of the current tag filter... we say:
> You're not allowed to create topics in this category
Which is incorrect, this updates it so when `this.canCreateTopicOnTag === false` we show:
> You're not allowed to create topics with this tag
When the category prevents new topics: 
When the tag prevents new topics:

UX: show correct message when creating topics is disabled by a tag

---

app/assets/javascripts/discourse/app/components/signup-progress-bar.gjs
app/assets/stylesheets/common/components/signup-progress-bar.scss
app/assets/stylesheets/mobile/invite-signup.scss

This PR moves the signup progress UI to its mobile version for a minimal layout on all platforms.
**Before**
**After**

UX: move to minimal layout

---

config/site_settings.yml

Followup 1bb33d15f202e6f5e06770c4ae1524ac657cd6cf
Self-hosters still need access to this for now,
we will hide it on our own hosting.

DEV: Unhide admin_sidebar_enabled_groups

---

lib/service/base.rb
spec/lib/service_spec.rb

There’s currently a bug when using a dedicated class as a policy in services: if that class delegates its `#call` method (to an underlying strategy object, for example), then an error will be raised saying steps aren’t allowed to provide default parameters.
This should not happen, and this PR fixes that issue.

DEV: Fix policy classes delegating their `#call` method in services

---

config/nginx.sample.conf

extra-locales bundles have unique digests in their URLs, and include an indefinite cache-control header. Therefore we should include them in the heavily-cached group of URLs in NGINX.

PERF: Cache public extra-locales requests in nginx

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
spec/system/topic_list/glimmer_spec.rb

it's already handled by TopicStatus component (so one was undoing the other's toggle)

FIX: Unpinning topics in glimmer topic list

---

plugins/discourse-presence/assets/stylesheets/presence.scss

On a narrow viewport on desktop, the margins above and below the "replying..." indicator were missing.
Also added a **minimum height** so the layout doesn't shift when the indicator is added in the DOM.
**BEFORE**
**AFTER**
Internal - t/144612

UX: fix border around reply indicator

---

app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/common/components/buttons.scss

This pr correctly removes the powered by discourse content, along with balancing spacing on social login buttons, and cleans up the header for login / signup / invite pages.
| --- | --- |
| ![CleanShot 2024-12-17 at 15 40 28@2x](https://github.com/user-attachments/assets/9587e584-c0c8-4508-b175-a53b3db00ed8)|![CleanShot 2024-12-17 at 15 38 04@2x](https://github.com/user-attachments/assets/5cce8c95-8c77-41d5-8bea-f29544e68afb) |
| ![CleanShot 2024-12-17 at 15 39 53@2x](https://github.com/user-attachments/assets/d4eaff40-e6e6-4025-ae7b-e672d5816de8) | ![CleanShot 2024-12-17 at 15 38 33@2x](https://github.com/user-attachments/assets/7ca94951-4804-42dc-93bf-e45312ae3d49) |
| ![CleanShot 2024-12-17 at 15 41 04@2x](https://github.com/user-attachments/assets/ebb35af3-5adf-4458- …

UX: Improve balance on login & signup pages

---

app/models/post_mover.rb
spec/models/post_mover_spec.rb

This allows plugins to skip the "posted" notifications for watching users, when posts get moved. The specs are kind of wild looking, as this unit tests a private method. This is difficult to isolate otherwise, with lots of trickery needed to make sure that this actually works. 
I opted to unit test just this method instead.

DEV: Plugin modifier to skip enqueue PostCreator jobs on PostMove

---

app/assets/javascripts/discourse/app/lib/can-check-emails-helper.js

Bug introduced in https://github.com/discourse/discourse/pull/30315.
For staged user cards, we don't set `this.model`. The previous incarnation of this helper (as a mixin) handles this case via Ember computed properties which resolves "model.id" to a null value even if model is itself undefined. 
As admin user, from admin controls, filter for staged users in the users index, and click on the avatar icon to trigger the user card. Email should be visible.

FIX: CanCheckEmailsHelper should handle null this.model gracefully

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/components/d-menu.gjs

A previous refactor used an incorrect path. This commit also adds a simple test to ensure this identifier is present.

DEV: correctly applies identifier do DModal used in DMenu

---

app/assets/javascripts/discourse/app/components/notifications-tracking.gjs
app/assets/javascripts/discourse/tests/integration/components/notifications-tracking-test.gjs

We never want to show this caret on mobile.

DEV: removes caret from notifications-tracking on mobile

---

lib/version.rb

Version bumps for main: v3.4.0.beta3, v3.4.0.beta4-dev

---

lib/version.rb

Version bump for stable: v3.3.3

---

config/nginx.sample.conf

The security fix in 15b43a20 also introduced some unrelated refactoring to the file, which seems to be causing issues in some environments. This commit reverts the refactoring, and applies the security fix to each block individually.

FIX: Simplify nginx config change

---

Gemfile.lock
lib/scheduler/thread_pool.rb
spec/lib/scheduler/thread_pool_spec.rb

Following: https://github.com/ruby-concurrency/concurrent-ruby/issues/1075
Current implementation in Ruby Concurrent is not spinning down
threads
New implementation is simpler and as a bonus respects Discourse database conventions
so it is multisite safe
(discourse fonts is weird - not sure what is up with that)

FEATURE: ThreadPool implementation

---

lib/scheduler/thread_pool.rb
spec/lib/scheduler/thread_pool_spec.rb

1. When there were zero threads, it could take a very long time to process first job
2. Properly scale up thread queue depending on actual busy work
3. Align APIs with concurrent

FIX: handle more thread pool edge cases

---

app/assets/stylesheets/common/admin/admin_config_area.scss
app/assets/stylesheets/common/admin/site-settings.scss
config/locales/client.en.yml

Followup 203f93bcaffab1f493be70c2277ef11048f2017e
This commit makes sure the background for all the admin
site settings filters (including the filter input and
override checkbox) is consistent no matter what the theme,
as it currently changes based on theme.
Before
After

UX: Site setting filter background inconsistencies

---

app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

due to rustlang regression
See: https://github.com/discourse/discourse/pull/30288#issuecomment-2556373204

DEV: Downgrade highlightjs to 11.10.0

---

app/assets/javascripts/select-kit/addon/components/category-notifications-button.js

This file has been incorrectly removed in https://github.com/discourse/discourse/commit/41df7051883dca8404c38e151294058ec8525b83 while it's still being used by plugins (https://github.com/discourse/discourse-circles).

DEV: reintroduces category-notifications-button.js

---

app/assets/javascripts/discourse/app/lib/uppy-plugin-base.js

`this.siteSettings` was always undefined anyway

DEV: Remove unused `_consoleDebug`

---

app/models/notification.rb
spec/models/notification_spec.rb

without additional query, add the name of the originator of the notification (ie, the person who posted on a topic you're following) to the `/notifications.json` endpoint.
since this is just adding a property to the endpoint json payload, there should be very low regression risk.
NB: this would only be populated when a call to `populate_acting_user` is made. currently in the core codebase, this appears to only happen when `SiteSetting.show_user_menu_avatars` is true.
screenshot:

DEV: return full name in /notifications.json

---

app/assets/javascripts/discourse/app/lib/post-action-feedback.js
app/assets/stylesheets/common/post-action-feedback.scss
app/assets/stylesheets/desktop/post-action-feedback.scss

Reported here: https://meta.discourse.org/t/share-link-copy-confirmation-text-shifts-on-double-click/343484
This improves the transition for the copy success message — there was an issue where some elements would linger when a sibling button was clicked... I also noticed some transitions that weren't being applied and fixed those 
Before:
After:

UX: improve link copy status transition

---

plugins/chat/plugin.rb

> NOTE: I wasn't able to reproduce locally, so that's my best guess as to what happens based on the production error logs. It's also the reason why I haven't changed/added any tests...
Earlier today, we started seeing a growing number of errors in the `register_presence_channel_prefix("chat-reply")` handler of the chat plugin. It was all coming from a Discourse where they make a heavy use of chat channels. They create and **delete** category channels regularly.
If a user has a thread in one of the channels that just got deleted, the client application might not be aware (just yet), asks the server to be connected to the "presence" bus of that channel, and BOOOM.
The following [line](https://github.com/discourse/discourse/blob/fa0ad0306c06250f8af5f842d86b86f609fe02ea/plugins/chat/plugin.rb# …

FIX: better handle race condition when a channel is deleted

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/toggle.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/toggle-test.gjs

A previous refactoring has incorrectly changed a variable and the test was only testing toggling to true and not to false.

FIX: correclty allows to untoggle a fk toggle

---

app/assets/javascripts/discourse/app/components/sidebar/common/custom-section.gjs
app/assets/javascripts/discourse/app/lib/sidebar/common/community-section/section.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-anonymous-community-section-test.js
spec/serializers/site_serializer_spec.rb

When lurking on a Discourse as anonymous, if the sidebar is enabled, and a section contains only secondary links that are not visible to anonymous users, we should not display the "more..." button.
Otherwise it feels broken because clicking on it does nothing, since there are no "visible" links to be shown.
Internal ref t/144716
**BEFORE**
As an admin, I can see the "Admin" section
As an anon, I can't see the "Admin" section, so the "more..." menu is empty
**AFTER**
As an anon, I can't see the "Admin" section, so the "more..." menu is not displayed since it's the only link

FIX: more... should not show when there are not links

---

app/jobs/scheduled/ensure_db_consistency.rb
spec/jobs/ensure_db_consistency_spec.rb

Fix ensures all classes are rooted and there is a spec that will catch
failures next time

FIX: we introduced a Jobs::UserEmail which broke consistency checks

---

config/nginx.sample.conf

The security fix in 15b43a2 also introduced some unrelated refactoring to the file, which seems to be causing issues in some environments. This commit reverts the refactoring, and applies the security fix to each block individually.

FIX: Simplify nginx config change (#30383)

---

config/initializers/000-zeitwerk.rb
lib/middleware/request_tracker.rb
lib/plugin/instance.rb
lib/request_tracker/rate_limiters/base.rb
lib/request_tracker/rate_limiters/ip.rb
lib/request_tracker/rate_limiters/stack.rb
lib/request_tracker/rate_limiters/user.rb
spec/lib/middleware/request_tracker_spec.rb
spec/lib/plugin/instance_spec.rb
spec/multisite/request_tracker_spec.rb
spec/requests/api/rate_limits_spec.rb

This commit adds the `add_request_rate_limiter` plugin API which allows plugins to add custom rate limiters on top of the default rate limiters which requests by a user's id or the request's IP address.
Example to add a rate limiter that rate limits all requests from Googlebot under the same rate limit bucket:
```
add_request_rate_limiter(
identifier: :crawlers,
key: ->(_request) { "crawlers" },
activate_when: ->(request) { request.user_agent&.include?("Googlebot") },
)
```

DEV: API to register custom request rate limiting conditions

---

app/assets/stylesheets/common/base/topic-footer.scss
app/assets/stylesheets/mobile/topic-footer.scss

* fix double em font-size being applied, causing a misalignment in button height
* remove border-radius from topic-progress-wrapper

UX: fix misalignment + remove border-radius of topic progress element

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/assets/javascripts/discourse/tests/integration/components/about-page-test.gjs

This PR makes the `contact_url` in the /about page behave as an absolute URL instead of a relative one if it doesn't explicitly start with a slash or a protocol. This prevents situation where, e.g., `www.example.com` is specified in the setting and the contact URL anchor tag ends up with a `href` that navigates to `<site address>/www.example.com` instead of just `www.example.com`. We prevent this by adding 2 leading slashes `//` to `contact_url` which makes the `href` resolves to the specified `contact_url` using the same protocol as the current site's.
Internal topic: t/143907.

FIX: Treat contact_url setting as a domain by default on /about

---

app/assets/stylesheets/common/components/navs.scss

The nav rows in the category settings page had no indication when the route was active; despite having an arrow icon coded, which was invisible at all times.
This commit adds a background colour (`d-selected`) to the `.active` class.
| <img width="924" alt="CleanShot 2024-12-23 at 12 35 43@2x" src="https://github.com/user-attachments/assets/cfb55b75-2fbe-4d4a-9c68-893bef94e612" /> | <img width="924" alt="CleanShot 2024-12-23 at 12 35 29@2x" src="https://github.com/user-attachments/assets/19e840b0-d2d1-41ad-8b4f-78b0cb556334" /> |

UX: add highlight for active nav in category settings

---

app/controllers/posts_controller.rb
spec/requests/posts_controller_spec.rb

Admins and moderators can see a user's deleted posts via the `/u/:username/deleted-posts` route. Admins can always see any post on the site, but that's not always the case for moderators, e.g., they can't see all PMs. So, this route accounts for that and excludes posts that a moderator wouldn't be allowed to see if they were not deleted.
However, there's currently a problem with that logic where admins who also have moderation privileges, are treated the same way as moderators and prevented from seeing posts that pure moderators can't see. This PR fixes that problem and only applies the permission checks to moderators who don't have admin privileges.
Internal topic: t/143107.

FIX: All admins should be allowed to see deleted PM posts regardless of their mod status

---

config/locales/server.en.yml
config/site_settings.yml

This setting suppresses topics and PMs from the admin UI unless they are participants. This is not a security feature: admins can always access all content on the site if needed.

FEATURE: Unhide 'suppress_secured_categories_from_admin' setting

---

bin/rspec

When passing a `plugins/...` path to bin/rspec, it's reasonable to assume that the developer wants the tests to be run with plugins loaded. This commit automatically takes care of that.
If `LOAD_PLUGINS` is explicitly specified, then that value will always be used.
This mimics the logic we already have for database migrations in the `bin/rake` stub

DEV: Automatically set LOAD_PLUGINS for bin/rspec

---

plugins/chat/spec/system/chat_composer_draft_spec.rb
plugins/chat/spec/system/page_objects/chat/components/composer.rb
spec/system/page_objects/components/composer.rb

Checking for value of input directly is not waiting for value to be present.

DEV: uses capybara helper has_field

---

app/assets/javascripts/discourse/tests/unit/controllers/topic-test.js

…instead of `next()`/`assert.async()/done()`

DEV: Update a topic test to use `settled`

---

app/assets/javascripts/discourse/app/components/composer-editor.js
app/assets/javascripts/discourse/app/components/topic-progress.js
plugins/chat/assets/javascripts/discourse/services/chat-emoji-picker-manager.js

`discourseLater` automatically uses delay of 10ms in test environment

DEV: Don't use 0-delay for test-env discourseLater

---

plugins/chat/assets/stylesheets/desktop/base-desktop.scss

This PR removes the border-radius being applied to full screen chat channels. This was causing an odd visual bug on highlighted chat messages.
**Before**
**After (Fixed)**

UX: Remove rounded borders from full screen chat channel

---

app/jobs/regular/notify_moved_posts.rb
spec/jobs/notify_moved_posts_spec.rb

We currently query the `posts` table without an order when notifying users of moved posts. Generally the query will return the lowest post number post (b/c ID correlates with post_number in most cases) but not always. This adds an `order` to the post query in `notify_moved_posts` job.
Also I removed some if statement nesting with early returns / guard clauses.

FIX: Consistently notify lowest post number in post_moved notifications

---

plugins/chat/assets/stylesheets/common/chat-composer.scss

Chat had the following bug.
Paste the following content into chat composer:
```
a
b
```
It would render as (in safari only):
```
a
b
```
It seems this behavior occurs because of how Safari handles the white-space CSS property in conjunction with the `::placeholder` and `:placeholder-shown` pseudo-classes. Specifically when rendering multiline content in textareas where white-space: nowrap is applied to these pseudo-classes.
I couldn't find an exact source of this, but surely commenting this part of the code was making it work, it seems forcing `pre-wrap` is working.

DEV: fixes safari bug with content including linebreaks

---

app/assets/stylesheets/common/base/sidebar-section-link.scss

This PR adds a target for the non-chat active sidebar class, which is still using `active` as most other areas in Discourse. 
**This PR does not address:**
1) In chat sidebar we are using `sidebar-section-link--active` when the recommendation from the Discourse styleguide is to separate modifiers from their main target. IE. `sidebar-section-link --active`
https://github.com/discourse/discourse/blob/fef14c004cd1708b90ca29425090b0b06b159470/plugins/styleguide/assets/javascripts/discourse/components/sections/syntax/00-bem.hbs#L29-L65
2) I am not changing the other areas in core to use `--active` as this would likely cause lots of issues with existing themes

UX: Fix active class targeting for sidebar

---

app/jobs/regular/sync_acls_for_uploads.rb

This job is not mission critical and should not clog the default queue

DEV: Set `Jobs::SyncAclsForUploads` to low queue

---

app/jobs/regular/sync_acls_for_uploads.rb

I think the log messages were used for initial production trials but the
log messages are actually not very useful in the grand scheme of things.
If the timing of the job is important information, one can get it by
enabling Sidekiq logging and obtain the information from there. There is
no need for us to flood the logs with these messages.
Also the messages will contain at most 100 ids so it is just alot of
noise in general.

DEV: Remove log messages that are redundant

---

.github/workflows/tests.yml

On our own self hosted runners, pulling from github actions cache is quite slow and can take up to 20 seconds for the `bundler cache` step. Instead, we will now copy the gems from the `/var/www/discourse/vendor/bundle` folder in the `discourse/discourse_test:release` image which is built daily. This eliminates the need to pull from Github actions cache and also potentially reduces our costs of cache storage.
Note that `discourse/discourse_test:release` is pulled periodically on our self hosted runners so there is no impact on the time it takes to initialize the container.

DEV: Copy gems from Docker image in Github actions tests workflow

---

app/jobs/base.rb
spec/jobs/jobs_scheduled_spec.rb

This is useful for scheduled jobs that should be performed even when
`Discourse.readonly_mode?` is `true`.

DEV: Support a `perform_when_readonly` option for `Jobs::Scheduled`

---

.github/workflows/tests.yml

We are running on self hosted runners with more CPU and RAM so we should
be able to run one system test process per CPU core for more speedz.
This may lead to some instability in our system tests but it is hard to say unless we roll this change out. If it does lead to system tests being more unstable, we can easily roll back the change.

DEV: Run one system test process per CPU core

---

app/assets/stylesheets/common/base/login-signup-page.scss

This PR adds the before-header-panel-outlet to the list of outlets to be hidden on login pages.

UX: Hide before-header-panel-outlet on login page

---

.github/workflows/tests.yml

This commit updates the `tests` workflow to only support running on Discourse self hosted runners. Previously, we had to maintain a couple of conditional steps because we assumed that the `tests` workflow might not be run on Discourse hosted runners. However, we currently don't think the benefits outweigh the complexity it introduces hence this change.
With the change to always run on self hosted runners, we can also remove various Github actions caches which simplifies the `tests` workflow even more.

DEV: Simplify tests workflow 

---

plugins/chat/spec/system/thread_list/full_page_spec.rb

This spec was flaky, by not using a second session and rely on services instead, I hope to make it more stable.

DEV: simplify restore message spec

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/raw-views/topic-status.js

This will make the 'auto' glimmer-topic-list feature aware of these modifications, so that the new topic-list will not be enabled until they're resolved.

DEV: Add deprecations for topic-status raw-view modifications

---

lib/tasks/import.rake

After running the `import:ensure_consistency` rake task the post and topics counts where way off. 
When investigating, I found this six-year-old #TODO. 
It was an easy fix 👍

FIX: correct topics and posts count in import:ensure_consistency rake task

---

app/assets/javascripts/discourse/app/modifiers/swipe.js

`onDidCancelSwipe` event was calling itself instead of the callback (not an actual FIX because no user of this API has set a callback so far)

DEV: fix cancel swipe callback typo

---

app/assets/javascripts/discourse/app/components/post/menu.gjs
app/assets/stylesheets/common/base/topic-post.scss

This PR adds `showLogin` as an available action to the post menu buttons. They can use this action to show the login form when there is no user logged in.
It also adds a small CSS tweak to prevent the content from the post menu to being user selectable. This was causing small UX issues in touch devices.

DEV: Add showLogin action to post menu buttons and prevent text selection

---

app/assets/javascripts/discourse/app/components/fullname-input.gjs
app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/preferences/account.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/mixins/name-validation.js
app/assets/javascripts/discourse/app/templates/invites/show.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/javascripts/discourse/tests/acceptance/create-account-test.js
app/assets/javascripts/discourse/tests/acceptance/invite-accept-test.js
app/assets/javascripts/discourse/tests/fixtures/site-fixtures.js
app/models/full_name_requirement.rb
app/serializers/site_serializer.rb
app/services/user_anonymizer.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
db/migrate/20241224191732_change_full_name_required_setting.rb
lib/discourse_dev/config.rb
lib/tasks/admin.rake
lib/validators/user_full_name_validator.rb
spec/lib/validators/user_full_name_validator_spec.rb
spec/requests/api/schemas/json/site_response.json
spec/services/anonymous_shadow_creator_spec.rb
spec/services/user_anonymizer_spec.rb
spec/system/social_authentication_spec.rb

This PR replaces the `full_name_required` setting with a new `full_name_requirement` setting to allow more flexibility with the name field in the signup form. The new setting has 2 options, "Required at signuo" and "Optional at signup", which are equivalent to the true/false possibilities of the old setting, and a third option "Hidden at signup" that hides the name field from the signup form, making it effectively optional too.
New sites will have the "Hidden at signup" option as the default option, and existing site will continue to use the option that maps to their current configuration.
Internal topic: t/136746.

FEATURE: Add option to hide full name input at signup

---

config/locales/server.en.yml

Follow-up to https://github.com/discourse/discourse/pull/30471
We've merged a PR that requires an entry for all site settings in the keywords section in `server.en.yml`, and I merged my previous PR without rebasing my branch so I didn't catch the new failure.

DEV: Fix build

---

app/assets/javascripts/discourse/app/components/directory-item.hbs
app/assets/javascripts/discourse/app/components/directory-item.js
app/assets/javascripts/discourse/app/components/user-info.hbs
app/assets/stylesheets/common/base/directory.scss

This fix doesn't work in Safari 15.7, which we still support, because `subgrid` support was only added in iOS 16+. May need to add a CSS hack for iOS before 16 or accept that the layout of this page is broken for that browser version. (It has no other effects.)

A11Y: Fix screen reader access to user directory

---

app/assets/javascripts/admin/addon/mixins/setting-component.js
spec/system/admin_flags_spec.rb
spec/system/admin_site_setting_label_formatting_spec.rb

In order to make the many lists of settings more readable, this PR transforms setting names into Sentence Case, with a handful of special cases, too:
- Transforms common acronyms to upper case (eg, URL, TLD)
- Handles plural versions of common acronyms (eg, URLs, TLDs)
- Allows for words with weird casing (eg, GitHub, iOS)
Browser through the site settings, see if there are any that you think should look different.
Try the settings for popular plugins, make sure they're handled correctly.

UX: Add Sentence Casing for Setting Names

---

config/locales/server.en.yml
config/site_settings.yml
lib/guardian/user_guardian.rb
spec/lib/guardian/user_guardian_spec.rb

The profile hiding feature is particularly problematic on sites that are
private (invite only or must approve users) so it is unconditionally disabled.
Also certain sites may prefer to disable the anti spam feature, they can
opt out using `hide_new_user_profiles`

FEATURE: allow disabling of anti spam profile hiding feature

---

app/models/post_mover.rb

This PR reverts some of the behaviour changes of #29664, whilst maintaining the permanent record of moved posts that #29664 intended to add.
Prior to #29664, a new temp table was created every time posts were moved to a different topic. This allowed the rest of the queries within the post moving process to assume that they were always working with a fresh set of data. Unfortunately, changing this to a permanent table introduced a bunch of edge cases which proved challenging to entirely eliminate (see #30176, #30217, #30256, #30311).
To avoid an ongoing whack-a-mole situation, the best option is to switch the post moving section of the code back to a temporary table. However, given that the permanent table has a model set up for it, the more straightforward approach is to give the …

FIX: Switch back to using a temp table for moving posts.

---

app/controllers/email_controller.rb
lib/email/message_builder.rb
spec/lib/email/message_builder_spec.rb
spec/mailers/user_notifications_spec.rb

We were missing the "List-Unsubscribe-Post" header in emails we sent to allow Yahoo / GMail and others to automagically show a link to unsubscribe.
Internal ref - t/144713

FEATURE: add support for One-Click unsubscribe (RFC 8058)

---

lib/email/receiver.rb
spec/fixtures/emails/exchange_html_body.eml
spec/fixtures/emails/exchange_html_body_and_reply.eml
spec/fixtures/emails/exchange_html_reply.eml
spec/lib/email/receiver_spec.rb

When receiving emails sent with Exchange, we look for some markers to identify the body of the mail and the reply (aka. previous email).
For some reasons, those markers aren't 100% reliable and sometimes, only one of them is present.
The commit 20ba54d53630b57c25fa3f325b0f219581314936 introduced the bug because the `HTML_EXTRACTERS` regex for exchange looks for either `messageBodySection` or `messageReplySection` but we were only using the `reply` section. So if an email had only the `body` section, it would not be correctly extracted.
This commit handle the cases where either one of them is missing and use the other one as the actual "reply". When both are present, it correctly elides the "reply" section.

FIX: correctly extract body and/or reply from exchange emails

---

app/assets/javascripts/admin/addon/adapters/user-field.js
app/assets/javascripts/admin/addon/components/admin-config-areas/emojis-list.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/emojis-new.gjs
app/assets/javascripts/admin/addon/components/emoji-uploader.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/services/admin-emojis.js
app/assets/javascripts/admin/addon/templates/emojis-settings.hbs
app/assets/javascripts/admin/addon/templates/emojis.hbs
app/assets/javascripts/admin/addon/templates/permalinks-settings.hbs
app/assets/javascripts/admin/addon/templates/permalinks.hbs
app/assets/javascripts/admin/addon/templates/user-fields.hbs
app/assets/javascripts/discourse/tests/acceptance/admin-permalink-test.js
app/assets/javascripts/discourse/tests/integration/components/emoji-uploader-test.js
app/controllers/admin/emoji_controller.rb
config/routes.rb
docs/ADMIN-QUICK-START-GUIDE.md
plugins/automation/test/javascripts/integration/components/da-custom-field-test.js
spec/requests/admin/emojis_controller_spec.rb
spec/requests/admin/user_fields_controller_spec.rb
spec/system/page_objects/admin_emojis.rb
spec/system/page_objects/pages/admin_permalinks.rb
spec/system/page_objects/pages/admin_user_fields.rb

The customize routes add CSS classes that make these admin
config pages look different from the ones under /admin/config.
We want all config routes to be under /admin/config as well.
This commit moves the emoji, user fields, and permalinks pages
out of customize and into config, updating all references and
adding more rails routes as needed.
Also renames admin emojis route to emoji, emoji is singular and plural.

DEV: Move admin config pages out of /customize/ sub-route

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/image.js
spec/system/wizard_spec.rb

Followup 3135f472e2c4221a9348aec27514d3e2947bc9ab
Fixes an issue where the wizard branding step would
error if SiteSetting.logo was null, this did not come
up during testing because in our testing discourse-logo-sketch-small.png
is used for the logo settings.

FIX: Wizard branding step null logo

---

lib/hijack.rb
spec/lib/hijack_spec.rb
spec/requests/admin/reports_controller_spec.rb

Our bulk report endpoint uses `hijack`, which does not
use the current user's locale via the `with_resolved_locale`
method in `ApplicationController`. This is happening because
we are doing `around_action` to set the locale, then calling
the code in the block inside the action directly when we use
`hijack`.
We can fix this by capturing `I18n.locale` when starting the
hijack then using `I18n.with_locale` when evaluating the
block inside `hijack`, this way the translations will always
use the correct locale based on the current user.
c.f. https://meta.discourse.org/t/titles-on-graphs-in-community-health-dashboard-are-not-localized/302776/5

FIX: Reports did not respect user locale

---

app/assets/stylesheets/common/admin/admin_base.scss

This PR makes the secondary sidebar in the admin UI more consistent navigation experience:
* Added a coloured background for links on hover
* Replaced the bold text and line style with a distinct background highlight, ensuring it complements the admin sidebar while maintaining its own identity
* Bringing in arrow indicators to match the active navigation state in the category settings

UX: Add highlight for active nav in admin secondary sidebar

---

app/assets/javascripts/discourse/app/components/notifications-tracking.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/components/d-float-body.gjs
app/assets/javascripts/float-kit/addon/components/d-menu.gjs
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js

The trigger will now be refocused after closing the menu by default. This is very useful for tab behavior, otherwise after closing the menu, the body could be focused making it impossible to re-open the menu with Enter or just move up/down the flow.
If you want to disable this behavior:
```javascript
this.menuApi.close({focusTrigger: false});
```
This behavior is already disabled when closing after clicking outside. We don't want to risk interfering with the click of the user.

DEV: allows d-menu to refocus trigger

---

app/assets/javascripts/discourse/app/components/more-topics.gjs

There's no action you can do on the active tab of more topics so tabbing to it doesn't make sense.

UX: do not tab to an already active tab

---

app/assets/stylesheets/common/base/code_highlighting.scss

**Problem:** `<code>` inside headings (`<h1>`, `<h2>`, etc) have a fixed font-size. This reduces readability for larger headings due to the dramatic size difference in the same line.
**Solution:** `code` within heading elements set to `font-size: inherit`
Internal discussion reference: /t/-/145176

UX: inherit font-size for code in headings

---

app/assets/javascripts/admin/addon/controllers/admin-config-notifications-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-notifications.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-notifications-settings.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml
plugins/chat/config/settings.yml

Make the Notifications config page reached from the sidebar

UX: Admin setting page consistency - Notifications

---

app/assets/javascripts/admin/addon/models/report.js
config/locales/client.en.yml

Use i18n in the JS code instead of concatenating English
strings.
c.f. https://meta.discourse.org/t/titles-on-graphs-in-community-health-dashboard-are-not-localized/302776/8?u=martin

FIX: Dashboard report change tooltip was not translated

---

plugins/discourse-lazy-videos/lib/lazy-videos/lazy_youtube.rb

FIX: Fallback when embedding YouTube videos with lazy videos

---

spec/support/match_html_matcher.rb

HTML5 parser doesn't have those options

DEV: Remove invalid parsing options

---

app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/tests/acceptance/password-reset-test.js
spec/system/signup_spec.rb

FIX: Show error message when password is too common

---

app/models/user_api_key_client_scope.rb

@pmusaraj I think the issue with the AP plugin registering a client in production (e.g. on meta.discourse.org) is that dynamic calculation of the `UserApiKeyClientScope` inclusion list doesn't work in a production environment unless you use a lambda. The error I'm able to recreate in my own production environments is:
```
ActiveRecord::RecordInvalid (Validation failed: Name discourse-activity-pub:read is not a valid scope) app/controllers/user_api_key_clients_controller.rb:27
```
This error does not occur in development and test, and I'm not quite sure how to specifically test for this, however considering this same fix is used elsewhere, I think it's worth adding this and seeing if it fixes our issue in production.
Compare https://github.com/discourse/discourse/commit/e020888b0a30832697aa …

Use lambda to dynamically evaluate allowed user api key client scopes

---

app/assets/stylesheets/common/base/code_highlighting.scss

A follow-up to [UX: inherit font-size for code in headings #30536](https://github.com/discourse/discourse/pull/30536). Instead of defining new styling rules for code within headings, this changes the base `font-size` for code styling to use `em` units instead of `px`.
**Why 0.875em?**
Regular text is set to **1em**, or **16px**, so **0.875em** should be equal to **14px**. Therefore this change should have no discernable affect on regular code elements.
**Affect on inline code within headings**
Inline code within headings will have a size ratio consistent with code in regular paragraphs (slightly smaller than the surrounding text).
Internal discussion reference: /t/-/145176

UX: use em units for code font-size

---

lib/site_settings/deprecated_settings.rb
spec/fixtures/site_settings/deprecated_test.yml
spec/lib/search_spec.rb
spec/requests/admin/site_settings_controller_spec.rb

It was supposed to be removed ~3 years ago (there was [a migration](https://github.com/discourse/discourse/blob/b4f0a8748d5dbfbe97f526734ef537f52db2c660/db/migrate/20220126052157_change_segment_cjk_site_setting.rb) already)

DEV: Remove deprecated `search_tokenize_chinese_japanese_korean` setting

---

spec/fixtures/site_settings/deprecated_test.yml
spec/lib/site_settings/deprecated_settings_spec.rb
spec/models/trust_level_setting_spec.rb
spec/rails_helper.rb
spec/requests/admin/site_settings_controller_spec.rb

…and remove obsolete (and already-disabled) TL-migration related specs

DEV: Fix flaky deprecated setting specs

---

app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/serializers/site_serializer.rb
spec/serializers/site_serializer_spec.rb

Follow-up to https://github.com/discourse/discourse/pull/30471
When the `enable_names` setting is false and the `full_name_requirement` setting is set to `required_at_signup`, the name field in the signup form should effectively be not required (and hidden). However, that is not actually the case at the moment because the `name-validation.js` mixin only checks for the `full_name_requirement` setting when determining whether the name field should block a new signup.
This PR fixes the issue by making the `full_name_required_for_signup` and `full_name_visible_in_signup` site attributes check for the `enable_names` setting themselves. This spares any consumers of these properties from having to remember to include a check for the `enable_names` setting.

FIX: Allow signups when full names are disabled

---

app/assets/javascripts/discourse/app/services/capabilities.js

We already had isIpadOS, but for some themes and components
we really need to do different things if the user is on
a tablet, including Android tablets.
isTablet and isTabletScreen have been introduced to the
capabilities service.
isTablet is true if the screen size is a tablet, touch
is detected, or we have already detected iPad OS, or
the device matches tablet UAs
isTabletScreen checks both portrait and landscape dimensions
of 1280x600 which should cover most cases.

DEV: Add isTablet to capabilities service

---

.github/workflows/tests.yml

This reverts commit a78028e54e5c6eb8ba9f7e7e389d7d713e4ffbf3.
System tests started to become more unstable

Revert "DEV: Run one system test process per CPU core (#30484)"

---

config/initializers/000-development_reload_warnings.rb

`site_settings.yml` is read when the server starts, but isn't re-read if it changes. (Eg, adding a new setting, or changing the configuration of an existing setting.)
This change includes `site_settings.yml` as a file that requires a server restart when it changes. This behaviour obeys the `AUTO_RESTART` environment variable.

DEV: Restart unicorn when site_settings.yml changes.

---

app/assets/javascripts/discourse/app/components/discovery/categories-display.gjs
app/assets/javascripts/discourse/tests/acceptance/categories-test.js
app/controllers/categories_controller.rb
app/models/mobile_category_page_style.rb
config/locales/server.en.yml
config/site_settings.yml

Variation of [this PR](https://github.com/discourse/discourse/pull/30470) to add a new setting altogether for mobile `mobile_category_page_style` (screenshots are same both PRs).
Internal discussion: /t/-/144253

FEATURE: add new setting to select view for category page on mobile

---

app/assets/javascripts/admin/addon/controllers/admin-dashboard.js

The `problemsTimestamp` on the admin dashboard was always
forcing the "en" locale for some reason, we can remove the locale
entirely because we already set the locale for moment.js using
I18n on the server-side.
c.f. https://meta.discourse.org/t/last-check-date-not-localized-in-admin-dashboard/345483

FIX: Dashboard last checked date was always English

---

app/assets/javascripts/admin/addon/controllers/admin-config-trust-levels-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-trust-levels.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-trust-levels-settings.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb

Make the trust levels config page reached from the sidebar

UX: Admin setting page consistency - Trust levels

---

app/assets/javascripts/admin/addon/controllers/admin-config-legal-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-legal.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-legal-settings.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml

Make the Legal config page reached from the sidebar

UX: Admin setting page consistency - Legal

---

.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/release-notes.yml
.github/workflows/stale-pr-closer.yml

Our self hosted runners are limited in quantity so we should preserve
them for workflows that actually require the additional resources
instead of tying them up on workflows that do not benefit from the
additional resources.

DEV: Use github hosted runners for simple workflows

---

app/assets/javascripts/admin/addon/controllers/admin-config-search-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-search.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-search-settings.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb

Make the Search config page reached from the sidebar

UX: Admin setting page consistency - Search

---

config/initializers/000-development_reload_warnings.rb

This is a follow-up to #30565.
Aside from `site_settings.yml`, all plugin `config/settings.yml` files are only read when the server starts, and aren't re-read if they change.
This change expands the matcher added in #30565 to match any `settings.yml` file as requiring a server restart when it changes. Unfortunately, the `Listen.to(only: ...)` filter only matches against filenames (as opposed to full paths) so we can't add a matcher against `plugins/.*/config/settings.yml` to make it explicit.

DEV: Restart unicorn when any settings.yml changes.

---

app/assets/javascripts/admin/addon/controllers/admin-config-fonts-settings.js
app/assets/javascripts/admin/addon/controllers/admin-config-navigation-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-navigation.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-navigation-settings.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml
plugins/chat/config/settings.yml

This PR creates a basic config page that only contains navigation-related settings, to replace the setting filtered view linked to from "Navigation" in the admin sidebar.
Check that there aren't any other settings missing from this view.

UX: Admin setting page consistency - Navigation

---

plugins/chat/app/models/chat/message.rb
plugins/chat/app/queries/chat/channel_unreads_query.rb
plugins/chat/app/queries/chat/thread_unreads_query.rb
plugins/chat/assets/javascripts/discourse/components/chat-channel-unread-indicator.gjs
plugins/chat/assets/javascripts/discourse/components/chat/header/icon/unread-indicator.gjs
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/spec/queries/chat/channel_unreads_query_spec.rb

For mentions within threads, the mentioned user can experience a stuck notification. This is due to thread memberships only being created for users who interact with a thread. Without the membership we cannot track if the message containing the mention was read by the user.
The solution to this explored in this PR is:
- auto add memberships for mentioned users (only direct mentions for performance reasons)
- update channel/thread unread queries to check notification read status AND thread membership last read message id when counting mentions
Previously the mention count would remain until the user notification (containing the mention) was read. However this only happens if the user clicks the notification or clicks dismiss all notifications.
When a user navigated to the thread without …

FIX: stuck notification for mentions within threads

---

app/assets/javascripts/admin/addon/components/ip-lookup.gjs
app/assets/stylesheets/common/admin/admin_base.scss

Before:
After:
With more than 0 it's red to associate with the delete button

UX: only show red count in IP lookup when greater than 0

---

app/assets/javascripts/discourse/app/widgets/post-small-action.js

Investigated here: https://meta.discourse.org/t/convert-to-topic-icon-missing/334309/8?u=awesomerobot
When a site is set to `login_required` the small action for converting a PM to a topic is `open_topic` rather than `public_topic` — and there's no icon defined for it. This adds one (the same as `public_topic`). 
Before:
After:

UX: add missing icon for `open_topic` small action

---

app/assets/javascripts/discourse/app/instance-initializers/post-decorations.js
app/assets/stylesheets/common/base/topic-post.scss

Reported here: https://meta.discourse.org/t/table-shadow-on-hover-shouldnt-appear-when-we-cant-edit-the-table/345421
Before... can't edit or expand, but has shadow on hover: 
After... no shadow on hover: 
...unless it's expandable: 
...or editable: 
I also noticed this issue: 
It appears that 
`...(props.label ? ["no-text"] : []),` 
was backwards and should be 
`...(props.label ? [] : ["no-text"]),`
which fixes that button so:

UX: improve table hover states, fix table button margin issue

---

app/assets/javascripts/discourse/app/components/topic-list-item.js

This provides an easier upgrade path for themes/plugins. Matches the strategy used for other new topic-list-related modifiers.

DEV: Support expand-pinned modifier in legacy topic-list

---

app/assets/stylesheets/mobile/topic-footer.scss

We need a little more CSS here to avoid this jitter issue: https://meta.discourse.org/t/infinite-loop-when-scrolling-in-chrome-on-android-in-landscape-mode/345635
When the progress bar attempts to dock, the layout shifts, causing it to undock and get stuck in a jittery dock/undock loop. This adjusts the layout to avoid the shift like we do on desktop. 
Before: 
After:

UX: adjust mobile to avoid progress bar jitter

---

app/assets/javascripts/admin/addon/models/report.js
config/locales/client.en.yml

Followup 8d5c4ecc3398611764a4459c0e92f0fb90edd90f
Implement review suggestions from https://github.com/discourse/discourse/pull/30541
after merge, and also fix other hardcoded strings on this
dashboard.

UX: More translations for admin dashboard

---

config/locales/client.en.yml
spec/system/admin_sidebar_navigation_spec.rb

Followup b3fa335c7db3b92530625cbe37db32427f567ebc
Changes these sidebar links to better reflect
what these pages contain:
* (Email) Server setup → Server setup & logs
* (Security) Staff action logs → Logs & screening

UX: Update email and security sidebar link copy

---

plugins/chat/lib/discourse_dev/message.rb
plugins/chat/lib/discourse_dev/reviewable_message.rb
plugins/chat/plugin.rb

Related to https://github.com/discourse/discourse/pull/30540
This also makes the chat plugin use the new plugin API for extending the `reviewables:populate` rake task.

DEV: Extend the reviewables:populate rake task in chat

---

.github/workflows/tests.yml

Use the `ubuntu-latest` runner which is free thus freeing up a
self hosted runner

DEV: Move `merge` job in tests workflow to different runner

---

app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
lib/discourse_updates.rb
spec/lib/discourse_updates_spec.rb
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/pages/admin_new_features.rb

Experimental "What's new?" feature feed items previously calculated
a boolean for experimentEnabled on the client based on the siteSettings
service, and this would control the initial state of the experiment
toggle.
However this requires the person who creates the site setting for the
experiment to remember to set it to `client: true`. This commit removes
that manual step by calculating whether the experiment is enabled
server-side, where we have access to all the site settings.

FIX: Calculate experiment_enabled on server for "What's new?"

---

app/assets/javascripts/admin/addon/controllers/admin-config-experimental-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-experimental.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-experimental-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/locales/server.en.yml
config/routes.rb

Make the Experimental config page reached from the sidebar

UX: Admin setting page consistency - Experimental

---

db/migrate/20241224191732_change_full_name_required_setting.rb

Followup 3187606d3402003437c2ccd6121a26f874939228
Fix full_name_requirement INSERT by adding ON CONFLICT DO NOTHING,
on sites that already have this setting this migration will fail.

FIX: ChangeFullNameRequiredSetting could fail if setting was already in DB

---

app/assets/javascripts/admin/addon/controllers/admin-config-spam-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-spam.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-spam-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb

This PR creates a basic config page that only contains security-related settings, to replace the "security" category view linked to from "Security settings" in the admin sidebar.

UX: Admin setting page consistency - Spam

---

app/assets/javascripts/admin/addon/controllers/admin-config-developer-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-developer.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-developer-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml

This PR creates a basic config page that only contains developer-related settings, to replace the "developer" category view linked to from "Developer" in the admin sidebar.

UX: Admin setting page consistency - Developer

---

.github/workflows/tests.yml

We don't care about flaky tests on the `stable` branch for now.

DEV: Only check for flaky test report on the `main` branch

---

app/assets/javascripts/admin/addon/controllers/admin-config-rate-limits-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-rate-limits.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-rate-limits-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb

This PR creates a basic config page that only contains rate limiting-related settings, to replace the "rate_limits" category view linked to from "Rate limits" in the admin sidebar.

UX: Admin setting page consistency - Rate Limits

---

app/assets/javascripts/admin/addon/controllers/admin-config-user-api-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-user-api.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-user-api-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb

This PR creates a basic config page that only contains user API-related settings, to replace the "user_api" category view linked to from "User API" in the admin sidebar.

UX: Admin setting page consistency - User API

---

app/assets/javascripts/admin/addon/controllers/admin-config-onebox-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-onebox.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-onebox-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml
config/routes.rb

This PR creates a basic config page that only contains Onebox-related settings, to replace the "onebox" category view linked to from "Onebox" in the admin sidebar.

UX: Admin setting page consistency - Onebox

---

plugins/chat/assets/javascripts/discourse/components/chat-composer-dropdown.gjs

When inserting anything from the chat composer dropdown, any popups opened aren't properly focussed.
This is due to the default behaviour of the dropdown menu closing, which tries to return the focus to the original triggering element. This would normally be the correct behaviour, but here we want the menu to close in the background, handing focus off to the popup, instead.
Check that popups are properly focussed when opened from the chat composer dropdown.

FIX: Ensure popups from the chat composer dropdown gain focus

---

script/bulk_import/base.rb
script/bulk_import/generic_bulk.rb

This pull request implements bulk import for discourse reactions plugin.
**Key Changes:**
- Implemented bulk import functionality discourse reactions plugin.
- Updated the Importing category permissions for the ability to change regular category permissions and not just for tags.
**Additional Context:**
- Ensured compatibility with existing Discourse infrastructure.
- No UX/UI changes were made, so no screenshots are included.
Please review and let me know if there are any questions or further improvements needed.

Adding Import Support for Discourse Reactions Plugin

---

plugins/chat/spec/system/chat_composer_spec.rb

This test is flaky, sometimes it fails with the hamburger menu blocking the click on the emoji, other times it just doesn't return the list of emojis when the search term is there.
Other similar emoji tests are skipped. Stopping the bleed, but we still need to figure out a more reliable testing strategy here.
Will revisit after #28277 is merged.
ref `/t/-/145212`

DEV: skip flaky chat composer emoji spec

---

app/models/site.rb
app/serializers/site_serializer.rb
spec/system/page_objects/modals/signup.rb
spec/system/page_objects/pages/signup.rb
spec/system/signup_spec.rb

Meta topic: https://meta.discourse.org/t/full-name-at-sign-up-went-missing/345662/17?u=osama
The preloaded `site` object for anons on login-required sites is a stripped down version of the full object with just a specific set of attributes and doesn't use the site serializer. This results in the `full_name_required_for_signup` and `full_name_visible_in_signup` attributes not making it to the client app when a login-required site is accessed by an anon, causing the name field in the signup form to not be rendered, even when it's required.
This PR includes those attributes in the stripped down version of the `site` object that's used for anons on login-required sites.

FIX: Name field should appear in the signup form for login-required sites

---

app/assets/javascripts/discourse/app/components/horizontal-overflow-nav.js

- Resolved an issue where the right arrow would remain visible after reaching the end of the scrollable content.
- Implemented a buffer to address minor inaccuracies in scroll calculations.
- Adjusted the logic so that arrows are only displayed when the content exceeds the container width.
[Kapture 2025-01-07 at 22.20.24.webm](https://github.com/user-attachments/assets/aab4eed6-51b0-4db2-9061-821f8241477e)
[Kapture 2025-01-07 at 22.17.26.webm](https://github.com/user-attachments/assets/2750f2a1-28e6-4ae2-880a-4dfab85ad65e)

FIX: Cleaned up horizontal nav scrolling so arrows show/hide properly

---

app/assets/javascripts/admin/addon/controllers/admin-users-list-show.js
app/assets/javascripts/admin/addon/templates/users-list-show.hbs
app/assets/stylesheets/common/admin/users.scss
app/controllers/admin/users_controller.rb
app/serializers/admin_user_list_serializer.rb
config/locales/client.en.yml
lib/admin_user_index_query.rb
spec/requests/admin/users_controller_spec.rb
spec/requests/api/users_spec.rb

This adds the Silence Reason column to silenced user lists. 
This feature helps combat large spam attacks cause you can quickly see 
why a user was silenced and then bulk act on all the silenced users
The backend is somewhat complex cause silence reason is not attached to user and just a row in the log making it a bit hard to join
I needed to make room for the column so I am dropping the topics viewed column from the suspended tab

FEATURE: show silence reason when viewing silenced users

---

plugins/chat/assets/javascripts/discourse/components/chat-composer-dropdown.gjs

Now that we correctly await for the modal to close, we dont need to special case and disable focusTrigger, the flow will now be:
- click an element of the menu
- wait for modal to close
- focus trigger
- trigger action, which will eventually open a modal and attempt to focus the first item

DEV: removes non needed special case

---

app/assets/javascripts/discourse/app/components/topic-list-item.js
app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/components/topic-title.gjs
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/acceptance/topic-test.js
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
docs/CHANGELOG-JAVASCRIPT-PLUGIN-API.md

This was deprecated more than a year ago, and we are not aware of any remaining uses in the ecosystem.

DEV: Drop deprecated `decorateTopicTitle` API

---

app/assets/javascripts/admin/addon/templates/users-list-show.hbs
app/assets/stylesheets/common/admin/users.scss

UX: Align silence reason header text with content alignment

---

app/assets/javascripts/admin/addon/components/admin-permalink-form.gjs
app/assets/javascripts/admin/addon/controllers/admin-permalinks-index.js
app/assets/javascripts/admin/addon/models/permalink.js
app/assets/javascripts/admin/addon/templates/permalinks-index.hbs
app/assets/javascripts/discourse/tests/acceptance/admin-permalink-test.js
spec/system/admin_permalinks_page_spec.rb
spec/system/page_objects/pages/admin_permalinks.rb

This PR attempts to implement a conditional rendering of the permalinks filter at `/admin/config/permalinks`. Currently, a filter is present when no permalinks have been created. This signals an awkward UX as there is nothing to actually filter.
I assumed I could just add an `{{#if this.model.length}}` statement to conditionally render this filter, but the model was always returning a *filtered* list, based on what was input into the filter input. It worked, except when the filter did not return any permalink results, because at that point the model's length is technically 0, due to no matches for the filter.
To correct this, I changed to model to return an object containing `allLinks` and `filteredLinks`. The filter is now conditionally able to be rendered based on the length of …

UX: Conditionally render permalinks filter

---

app/assets/javascripts/discourse/app/initializers/dev-tools.js

I'm not sure if this is a real-world consideration... but our `test/smoke-test.mjs` script runs chrome with `--disable-local-storage`, so it needs to work.

DEV: Gracefully handle missing localstorage in dev-tools initializer

---

lib/onebox/helpers.rb
lib/oneboxer.rb
spec/lib/oneboxer_spec.rb

Onebox embeds currently default to accepting any language response from the destination, which can have some surprising behaviour. For example the `curl` equivalent of what Onebox does:
```
% curl -si -H "Accept-Language: *" 'https://developer.android.com/studio' | grep location:
location: /studio?hl=hi
```
This PR uses the value of `SiteSetting.default_locale` to populate the `Accept-Language` header, falling back to English if that isn't available, then finally accepting whatever language the destination makes available.
Make sure you always get Onebox responses in the correct language: it should default to the `default_locale` language, then fall back to English, then fall back to whatever language is available.

FIX: Ensure Onebox requests ask for the correct language.

---

app/assets/javascripts/discourse/app/widgets/post-cooked.js
app/assets/javascripts/discourse/tests/acceptance/fast-edit-test.js
app/assets/stylesheets/common/base/topic-post.scss
spec/system/topic_page_spec.rb

On WebKit-based browsers, triple clicking on the last paragraph of a post won't stop at the end of the paragraph, leaking the selection into the following nodes until it finds a non-empty node.
This PR introduces a workaround to fix this behavior.

DEV: Fix triple click selection in WebKit derived browsers

---

app/assets/javascripts/admin/addon/components/site-settings/font-list.gjs
app/assets/javascripts/admin/addon/mixins/setting-component.js
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.js
config/site_settings.yml

#30055 added a nifty new `FontSelector` component, which creates a dropdown where each item is styled in the font that it corresponds to.
We can make use of this to style the `base_font` and `heading_font` site setting selectors, too.
Test that font selection works as expected.

UX: Use `FontSelector` for displaying font-related settings

---

app/models/reviewable_score.rb
spec/multisite/flags_spec.rb

Score types are dynamic because of custom flags. Therefore we cannot memorize them on class level as it is not multisite safe.

FIX: do not memoize score types

---

lib/inline_oneboxer.rb
lib/retrieve_title.rb
spec/lib/inline_oneboxer_spec.rb

Following on from #30637, we need to apply a similar fix to inline oneboxes, since they use a different code path to retrieve the onebox provider data.
This change ensures the `Accept-Language` header is sent by inline onebox requests, too.
Test that inline oneboxes appear in the expected language.

FIX: Inline oneboxes should obey the locale.

---

app/assets/stylesheets/mobile/topic-post.scss

Reported on [meta](https://meta.discourse.org/t/badges-in-posts-look-misaligned-on-mobile/346054).
Due to more explicit CSS flex arrangement on mobile devices, user badges were being shoved out of alignment. This PR nudges them back into line.
Test on additional mobile device sizes, check that user badges are correctly aligned.

FIX: Improve the user badge alignment on mobile devices.

---

lib/post_creator.rb

Previously we would enqueue sidekiq jobs like `PostProcessCooked` **before** triggering the `topic_created` and `post_created` DiscourseEvents. That means that, depending on the speed/availability of Sidekiq, PostProcessCooked might start running on another host before the DiscourseEvents have been executed.
This commit moves the event triggers before enqueue_jobs, so that ordering is guaranteed to be consistent, regardless of Sidekiq performance.

DEV: Ensure consistency in PostCreator hook order

---

.github/workflows/linting.yml

In 15a7a84d84bb97742263228c7cd043ab6deeae18, I changed the `linting`
workflow to run on `ubuntu-latest` because it is free and helps to free
up our self hosted runners for more important workflow jobs. However,
some devs rely on the `linting` workflow for feedback so we want to
provide this feedback as soon as we can. Therefore, we are putting the
`linting` workflow back on our faster self hosted runners.

DEV: Run `linting` workflow on our self hosted runners

---

app/assets/javascripts/discourse/app/components/emoji-picker/content.gjs
app/assets/javascripts/discourse/app/components/emoji-picker/index.gjs
app/assets/javascripts/discourse/app/components/user-status-picker.gjs
app/assets/javascripts/discourse/tests/integration/components/emoji-picker-test.js
app/assets/stylesheets/common/components/emoji-picker.scss

This pull request is doing the following changes:
- prevents clicking on a section to scroll the document body
- do not show favorites section if empty
- do not close the user-status modal on emoji selection
- giving its own context for user-status picker, that way if you frequently use same emojis for the picker they will always be in favorites

FIX: emoji picker followups

---

lib/discourse_dev/reviewable_queued_post.rb

Follow-up to https://github.com/discourse/discourse/pull/30540
There are many scenarios that can result in creating a `ReviewableQueuedPost` record, however in the original PR we only added once scenario to the populate rake task. This PR adds the remaining scenarios to the rake task.

DEV: Populate all subtypes of ReviewableQueuedPost

---

app/assets/stylesheets/common/base/sidebar-footer.scss
app/assets/stylesheets/common/base/sidebar-more-section-links.scss
app/assets/stylesheets/common/base/sidebar-section-link.scss
app/assets/stylesheets/common/base/sidebar-section.scss
app/assets/stylesheets/common/base/sidebar.scss
app/assets/stylesheets/desktop/components/sidebar/sidebar-section.scss

Originally I had wanted to make it possible to re-color the sidebar with CSS variables, but this has regressed a little. I've cleaned up the variables and made sure they're applied throughout. 
The default styles shouldn't change, but now we should be able to edit colors properly with variables. For example... some custom styles: 
```scss
:root {
--d-sidebar-background: #00A36C;
// must be rgb for gradient
--d-sidebar-footer-fade: rgba(0, 163, 108, 1);
--d-sidebar-header-color: var(--secondary);
--d-sidebar-header-icon-color: var(--secondary);
--d-sidebar-border-color: #00ca86;
--d-sidebar-link-color: var(--secondary);
--d-sidebar-link-icon-color: var(--secondary);
--d-sidebar-link-badge-color: var(--secondary); // example: new count
--d-sidebar-prefix-background: #00ca86; …
```

DEV: fix and improve sidebar CSS variables

---

app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js

If, for some reasons, navigating between posts using j/k keyboard shortcuts does not select any posts, there could be an infinite loop due to setting the `direction` to `0` and then using it do "iterate" over the arrays of available "articles".
Despite many attemps, I wasn't able to reproduce the issue reported in https://dev.discourse.org/t/145565 so this is somewhat of a shot in the dark.

FIX: lockup when navigating with j/k

---

lib/post_creator.rb
spec/lib/post_creator_spec.rb

Reference: https://meta.discourse.org/t/wp-discourse-embedded-comments-question/343494
I originally also wrote a db migration for this:
```SQL
execute "UPDATE topic_embeds SET embed_url = lower(rtrim(embed_url, '/'))"
execute "UPDATE topic_embeds SET embed_url = regexp_replace(embed_url, '\-\-+', '-', 'g')
execute "UPDATE topic_embeds SET embed_url = trim(embed_url)"
```
However, on reflection, I'm of two minds about whether to apply it. Interested in other thoughts on that. Here's my current thinking:
1. Un-normalised embed_urls become an issue for topics created via the PostCreator (e.g. via `discourse/wp-discourse`) in edge cases such as platform migrations (see linked discussion).
2. Other code or behaviour either in `discourse/discourse` or elsewhere may be currently relying on the …

Apply TopicEmbed url normalisation to embed urls inserted in the PostCreator

---

app/assets/stylesheets/common/base/sidebar-section-link.scss
app/assets/stylesheets/common/base/sidebar.scss
plugins/chat/assets/stylesheets/common/chat-user-threads.scss

This fixes a couple regressions from c398933, and covers a missed case
Before: 
After:

 UX: follow-up sidebar variable fixes for c398933 

---

app/assets/stylesheets/common/components/emoji-picker.scss

Following a change in https://github.com/discourse/discourse/commit/b1e40d04b9ccec66085619a0ecef376584292374 the width of the picker has been reduced in modals when it should have been reduced only when NOT in a modal.

FIX: correct emoji picker size in modal

---

app/assets/javascripts/admin/addon/components/admin-config-areas/api-keys-new.gjs
app/assets/stylesheets/common/admin/api.scss
config/locales/client.en.yml
spec/system/admin_api_keys_spec.rb
spec/system/page_objects/admin_api_keys.rb

In #30096 we converted the API keys UI to follow the new admin UI guidelines.
During this conversion, the step where you get a chance to copy the API key after creating, was lost due to a rebase mistake.
This re-introduces it:

FIX: Add back missing API key 'peek' step

---

plugins/chat/assets/javascripts/discourse/models/chat-channel.js

This PR updates the deprecated `archive` icon name. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: update deprecated icon name archive to box-archive in chat plugin

---

app/assets/javascripts/admin/addon/templates/site-text-index.hbs
app/assets/javascripts/admin/addon/templates/site-text.hbs
app/assets/stylesheets/common/admin/customize.scss
config/locales/client.en.yml

This adds the new admin UI header to the site texts page:

DEV: Add new admin UI header to site texts page

---

app/assets/javascripts/admin/addon/templates/api-keys.hbs
config/locales/client.en.yml

Addressing a couple minor inconsistencies on the admin API keys page.
1. Add missing "Admin" root breadcrumb.
2. De-titleize "API Keys" -> "API keys".

DEV: Add missing root breadcrumb to API keys page

---

app/assets/javascripts/admin/addon/templates/customize-colors-index.hbs
app/assets/javascripts/admin/addon/templates/customize-colors.hbs
app/assets/javascripts/admin/addon/templates/watched-words.hbs
app/assets/stylesheets/common/admin/customize.scss
config/locales/client.en.yml

Part of our admin UI consistency efforts, this is a stop-gap
until we can do a further UI review of these pages.

UX: Add DPageHeader to watched words and color palettes

---

app/assets/stylesheets/common/base/onebox.scss
lib/onebox/engine/github_blob_onebox.rb
lib/onebox/engine/gitlab_blob_onebox.rb
lib/onebox/mixins/git_blob_onebox.rb
lib/onebox/templates/githubblob.mustache
lib/onebox/templates/gitlabblob.mustache

Rearranges the info at the top of github/gitlab 'blob' oneboxes to make them easier to read
Before:
After:

UX: Improve git blob oneboxes

---

app/assets/javascripts/discourse/app/lib/body-scroll-lock.js
app/assets/javascripts/discourse/app/modifiers/swipe.js
plugins/chat/assets/javascripts/discourse/components/chat-composer.js
plugins/chat/assets/stylesheets/common/chat-channel.scss

This will have the following advantages:
- removes a very annoying bug which was making text selection super hard on iOS
- removes the flashing of header when transitioning from disable to enable body scroll lock

FIX: simplify body scroll lock on iOS

---

lib/tasks/reviewables.rake

This PR introduces a new rake task that can be used in situations where a community receives a large number of flags/reports and needs a quick way to handle all of those pending reports. Usage instructions are included in the rake task source code.
Internal topic: t/145475.

DEV: Add reviewables:mass-handle rake task

---

plugins/chat/assets/stylesheets/common/chat-message-actions.scss

This is a regression of https://github.com/discourse/discourse/pull/28277

FIX: removes blank spacing in message actions

---

config/application.rb

Having it in stdout means it pollutes the output of some scripts & rake tasks, which then gets piped to other tooling

DEV: Move 'symlinking fonts' message to STDERR

---

.github/workflows/check-pr-body.yml

We'd like to enable the "default commit message: pull request title and body" option for squash merges. That doesn't currently work well for dependabot PRs, because the PR body includes rich HTML.
Therefore, this commit introduces a new workflow which replaces any dependabot PR bodies with plaintext content from the commit message. The original rich content will be added in a comment.

DEV: Add workflow to replace dependabot PR bodies with plaintext

---

app/assets/javascripts/discourse/app/components/d-editor.js

The emoji picker was correctly showing in both cases, but when clicking we didn't have a valid range as the click makes us lose selection.
This commit uses the coordinates of the mouse on the click event to create a virtual element. We can't create the event target as the menu is disappearing after the click on more.
No tests as we already test it's showing, and testing position is complicated and often unreliable.

FIX: correctly position emoji picker when clicking more

---

.github/pull_request_template.md

We'd like to enable the "default commit message: pull request title and body" option for squash merges. That means we need PR bodies to be clean, and do not want HTML comments like this template to end up becoming part of the commit message body.

DEV: Remove pull_request_template

---

app/assets/javascripts/admin/addon/templates/api-keys.hbs

When converting the admin API keys page to the new admin UI guidelines we lost a plugin outlet. This adds that back.

FIX: Add back API keys plugin outlet lost in translation

---

app/assets/javascripts/admin/addon/components/ip-lookup.gjs
app/assets/javascripts/discourse/app/components/reviewable-item.hbs
app/assets/javascripts/discourse/app/components/reviewable-item.js

Moves the theme component https://github.com/discourse/discourse-review-ip-lookup into core, this allows looking
up a user's IP directly from the review queue and seeing if
there are other users with the same IP on the forum

FEATURE: Add IP Lookup to review queue

---

spec/multisite/distributed_cache_spec.rb

Distributed cache when namespace is false is not multisite safe as values are shared between sites. Distributed cache with namespace option (default) is multisite safe.
Improved specs to cover both cases.

DEV: Improve distributed cache multisite specs

---

plugins/chat/spec/system/chat_new_message_spec.rb

Ensures that visiting the route creates a new chat channel before checking the new redirected url is using the last channel.

DEV: fix flaky chat new message spec

---

app/assets/javascripts/discourse/app/components/tag-groups-form.hbs
app/assets/javascripts/discourse/app/components/tag-groups-form.js
app/assets/javascripts/discourse/app/models/tag-group.js
app/assets/javascripts/discourse/tests/acceptance/tag-groups-test.js
app/models/group.rb
app/models/tag_group.rb
app/serializers/tag_group_serializer.rb
config/locales/client.en.yml
spec/serializers/tag_group_serializer_spec.rb

The "Tag Groups Form" component was using group names to handle permissions. This works just fine when the default locale is "English" but breaks as soon as it's changed to a different locale.
The fix is to use the group id's for handling the permissions instead of the group name.
Reported in https://meta.discourse.org/t/221849

FIX: ensure GroupChooser works with localized group names

---

lib/email/receiver.rb
spec/lib/email/receiver_spec.rb

When we send an email notification to a user, we always include a link that will allow them unsubscribe to these emails.
If the user reply to the email notification, the link to unsubscribe might still be present in the final post (often in the elided part).
Since those links do not require authentication to unsubscribe a user (this is a feature, not a bug), we would like to avoid showing them to other users on Discourse.
(If such an email is forwarded elsewhere, then it's totally out of our control.)
This commmit ensures we always strip those unsubscribe links from any incoming email to avoid making it easier to unsubscribe another user.
Since the format we use for those links might be similar to the ones used by other applications, the regular expression used to match those links uses …

FIX: strip unsubscribe links in incoming emails

---

plugins/chat/lib/chat/duplicate_message_validator.rb
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/lib/chat/duplicate_message_validator_spec.rb
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/spec/plugin_helper.rb
plugins/chat/spec/requests/chat/api/channels_archives_controller_spec.rb
plugins/chat/spec/requests/chat/api/channels_status_controller_spec.rb
plugins/chat/spec/services/chat/update_message_spec.rb
plugins/chat/spec/system/message_notifications_mobile_spec.rb
plugins/chat/spec/system/page_objects/chat/chat_channel.rb
plugins/chat/spec/system/page_objects/chat/chat_thread.rb

And change the "formula" to check for duplicate messages to
- no duplicate check in 1:1 DMs
- only duplicate check in group DMs / channels, for posts made by the same user, in the past 10 seconds
Internal ref - t/144262

FIX: remove complicated 'chat_duplicate_message_sensitivity' site setting

---

app/jobs/regular/run_problem_check.rb
spec/jobs/run_problem_check_spec.rb

(…and remove extraneous `stringify_keys` - enqueue already does `deep_stringify_keys`)
The warning in question:
```
Deprecation notice: Jobs::RunProblemCheck was enqueued with argument values which do not cleanly serialize to/from JSON. This means that the job will be run with slightly different values than the ones supplied to `enqueue`. Argument values should be strings, booleans, numbers, or nil (or arrays/hashes of those value types). (deprecated since Discourse 2.9) (removal in Discourse 3.0)
```

DEV: Fix job serialization warnings

---

app/assets/javascripts/discourse/app/components/modal/create-invite.gjs

- Fixed an issue where the invite link in the sidebar remained highlighted after the invite popup was closed.
- Included the link inside the modal in the tabbing order by adding tabindex="0" (previously excluded due to the absence of an href).
- Resolved a bug where pressing Enter on the focused link incorrectly triggered the "Create Link" button instead of performing the intended action.
Internal topic: /t/141364

FIX: Improve sidebar invite link highlight persisting, link tabbing and activation behavior

---

app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/components/buttons.scss

From https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible:
> The :focus-visible pseudo-class applies while an element matches the [:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) pseudo-class and the UA ([User Agent](https://developer.mozilla.org/en-US/docs/Glossary/User_agent)) determines via heuristics that the focus should be made evident on the element. (Many browsers show a "focus ring" by default in this case.)
This change switches buttons over to `:focus-visible` which shouldn't change much, except for situations where focus state may linger in cases when it's not desired, like the tracking button here for example: 
When using `focus-visible` the `focus` state is no longer visible after a tap, but the focus state will still appear when using keyboard …

UX: Switch button focus state to focus-visible

---

app/assets/javascripts/discourse/app/components/topic-drafts-dropdown.gjs
config/locales/client.en.yml

Adds a placeholder title for drafts that don't have a saved title.
Before:
After:

UX: add placeholder title for drafts

---

script/bulk_import/base.rb

Adding fix to avoid loading reactions indexes when plugin is not installed

FIX: Avoid loading reactions index when plugin is not installed

---

app/assets/javascripts/discourse/app/controllers/user-activity.js
app/assets/javascripts/discourse/app/mixins/viewing-action-type.js
app/assets/javascripts/discourse/app/routes/user-activity-stream.js
app/assets/javascripts/discourse/app/routes/user-badges.js
app/assets/javascripts/discourse/app/routes/user-notifications.js
app/assets/javascripts/discourse/app/routes/user-topic-list.js

This removes the viewing action type mixin. It was previously setting a property `userActionType` on the user controller but this property was actually removed since https://github.com/discourse/discourse/pull/4771 (Mar 2017) and doesn't seem referenced anywhere else. 
It also sets the same property on the user activity controller and this is a 1-liner so I've opted to duplicate that across the routes that need this.

DEV: remove viewingActionType mixin

---

app/assets/stylesheets/common/select-kit/email-group-user-chooser.scss

This PR addresses an issue where the dropdown container width was inconsistent, resizing based on its content. 
**Changes included:**
- Added a fixed width for the dropdown container.
- Adjusted margin spacing by applying it to the `.identifier` class instead of `.name`. This prevents awkward spacing when either contains a large number of characters.
Internal topic: /t/143862

FIX: Set fixed width for email group chooser dropdown to prevent resizing based on content

---

app/jobs/regular/export_csv_file.rb
spec/models/report_spec.rb

This Type column is a special ":post" column on the
Flag Status report, so it did not show by default in
the CSV export of that report. This adds it so the
type of flag e.g. illegal, off topic, innapropriate
is shown in the CSV output.

FIX: Add Type column to Flag Status CSV export

---

app/models/problem_check.rb
app/services/problem_check/admin_sidebar_deprecation.rb
config/locales/server.en.yml
spec/services/problem_check/admin_sidebar_deprecation_spec.rb

We want to avoid surprises when we make the new admin sidebar baseline, so in addition to announcements, we're also adding a problem check that informs you if you don't have it enabled for any group yet:

DEV: Add problem check informing about admin layout deprecation

---

app/assets/javascripts/admin/addon/templates/customize-themes.hbs
config/locales/client.en.yml

This PR updates the header of the admin Themes page to be more consistent with the rest of the admin UI.

UX: Use `DPageHeader` on the Themes page

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/radio.gjs
lib/wizard/builder.rb

This PR removes the flat icons from wizard step 2, as they are not used elsewhere in the wizard. Keeping the steps consistent with the existing style improves visual alignment and avoids unnecessary elements.

UX: Remove flat icons from wizard step two

---

app/assets/javascripts/admin/addon/templates/customize-themes.hbs
config/locales/client.en.yml

This PR updates the header of the admin Components page to be more consistent with the rest of the admin UI.
The Themes and Components pages share the same templates, so this change switches the header based on which tab is active.

UX: Use `DPageHeader` on the Components page

---

app/assets/javascripts/discourse/app/components/topic-drafts-dropdown.gjs
app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/common/components/drafts-dropdown-menu.scss

Adds a loading state to prevent multiple requests when clicking the drafts menu button.
We are also making a very slight adjustment to button spacing (needed for both desktop and mobile).

FIX: prevent multiple requests when clicking drafts trigger

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js

Our test suite now shows no deprecation counts from official themes/plugins for the FA6 upgrade, and we've done a few rounds of removing these in direct references & known settings, so it's time to enable the admin banner.

DEV: add FontAwesome 6 upgrade to deprecation warnings handler

---

app/assets/javascripts/discourse/app/controllers/topic.js

Reported here: https://meta.discourse.org/t/quoting-a-closed-topic-prefills-category-in-composer-that-should-be-off-limits/260009
Currently, if someone tries to quote a topic they don't have permission to reply to, we'll open a new topic composer with the quote so they can "continue the discussion". When doing this, we populate the current category, even if the user doesn't have permission to post in it. 
This is misleading, as when the user attempts to submit their topic they get an error because they lack the category permissions. 
This change checks the category permissions before populating it.

UX: check category permission before new topic quote

---

app/controllers/list_controller.rb
lib/topic_query.rb
spec/lib/topic_query_spec.rb
spec/requests/api/topics_spec.rb
spec/requests/list_controller_spec.rb

Internal discussion at `t/145686`.
This change allows controllers that construct TopicQuery parameters, to pass `per_page` into the `TopicQuery` constructor as an option. I can't see why this shouldn't be a public param, so long as we properly validate the value!

DEV: Add per_page as public param for TopicQuery

---

app/assets/stylesheets/common/base/history.scss

Reported here: https://meta.discourse.org/t/strike-through-text-is-not-rendered-in-diff/347101
`text-decoration: none` needs a few exceptions here to avoid stripping out styling that's present in posts 
before (strikethrough and underline stripped): 
after:

UX: show strikethrough, underline in post edit diff

---

app/assets/javascripts/discourse/app/templates/full-page-search.hbs

Another case of text node missing container with a selectable class.

DEV: Add div with className around Search no results header

---

app/assets/stylesheets/common/base/history.scss

This redundant `text-decoration: none` was getting in the way of showing a strikethrough on the deleted part of the diff
before ("new strike" at the bottom missing the strikethrough): 
after (strikethrough appears correctly):

UX: remove redundant `text-decoration: none`,  follow up to 912b002

---

app/assets/stylesheets/common/base/compose.scss

Not sure why, but it looks like this `z-index: -1` on the composer causes iOS to crash super quickly when pinch zooming . This change was introduced in 07e5f8907e2a8de27c42c2d6f5a02fc153212288 and is not strictly necessary, let's try removing.

FIX: Safari on iOS crashes when pinch-zooming

---

config/site_settings.yml
lib/site_settings/type_supervisor.rb

Both heading_font and body_font should not allow
additional user-defined values, these are lists with
predefined choices. The UI already prevents this
because the font selector dropdown is unique, but
we want to make sure the setting definition reflects
this too.

FIX: Do not allow_any on fonts site_settings

---

app/assets/javascripts/admin/addon/templates/admin.hbs
app/assets/javascripts/admin/addon/templates/site-settings.hbs
config/locales/client.en.yml

This PR updates the header of the admin Site Settings page to be more consistent with the rest of the admin UI.

UX: Use `DPageHeader` on the Site Settings page

---

app/assets/javascripts/admin/addon/components/email-styles-editor.hbs
app/assets/javascripts/admin/addon/templates/customize-email-style.hbs
app/assets/javascripts/discourse/app/components/nav-item.gjs
config/locales/client.en.yml

This PR updates the header of the admin Email Style page to be more consistent with the rest of the admin UI.
The HTML/CSS tabs have also been updated, which required an extra check being added to the `NavItem` component.

UX: Use `DPageHeader` on the Email Style page

---

app/assets/javascripts/discourse/app/components/topic-progress.hbs
app/assets/stylesheets/common/base/topic.scss
app/assets/stylesheets/mobile/topic.scss

UX: Adjust styling of Back button in topic progress

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/dropdown.gjs
app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/-homepage-preview.js
app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/-preview-base.js
app/assets/javascripts/discourse/tests/helpers/select-kit-helper.js
app/assets/javascripts/discourse/tests/integration/components/wizard-fields-dropdown-test.gjs
config/locales/client.en.yml
lib/wizard/builder.rb

* Do not offer "categories with latest" option anymore, it does
not look good with our default Sidebar selection
* Display a sensible item in the dropdown if the admin has not
chosen hot, latest, or category_boxes as the homepage style,
before it was broken. Now we show Custom with a little blurb
about whether topics or categories are shown, and what the landing
page is

UX: Wizard homepage dropdown improvements

---

lib/s3_inventory.rb
spec/fixtures/csv/s3_inventory.csv
spec/lib/s3_inventory_multisite_spec.rb
spec/lib/s3_inventory_spec.rb

The `key` provided in the S3 inventory file will esacpe any special
characters in the filename of the key so we need to unescape. Otherwise,
uploads with extensions that conatins special characters will fail to
match records which we insert into the temporary table based off the
s3 inventory file.

FIX: `S3Inventory#backfill_etags_and_list_missing` need to unescape key

---

app/models/topic.rb

We have the other side of this association wired up -- 
https://github.com/discourse/discourse/blob/da72ad4ecddffc837cd9ec82624f51bbc22c6fc4/app/models/topic_hot_score.rb#L4
This commit simply adds the association to `Topic` model so we can reference the hot score.

DEV: Add topic_hot_score association to topic.rb

---

app/assets/javascripts/admin/addon/templates/admin.hbs
app/assets/javascripts/admin/addon/templates/logs.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml

This PR updates the header of the admin Logs page to be more consistent with the rest of the admin UI.
The tabs to access the different sub-pages have also been updated.

UX: Use `DPageHeader` on the Logs page

---

app/assets/javascripts/admin/addon/templates/customize.hbs
app/assets/javascripts/admin/addon/templates/plugins.hbs
app/assets/javascripts/discourse/tests/acceptance/admin-plugins-test.js

Admin pages that are based off the customize or plugin templates were wrapped in the `admin-container` class, which has slightly different margins to the `admin-config-page` class, which is used on most admin pages.
This change ensures that all the admin pages have the same alignment.
Click between different admin pages, make sure the breadcrumb and heading all appear in the same location.

UX: Tweak plugin and customize-based admin page margins

---

lib/topic_creator.rb
spec/models/reviewable_queued_post_spec.rb

Followup 72c4709a5ab26f00e32b65d874b3a206d679181e
Previously we made a fix to allow skip validations when tagging
a topic via TopicCreator. However, this flow also skips a lot of
the more in-depth work on tags we do when creating a topic, like
processing tag synonyms. When approving reviewable queued posts,
we skip validations, so this would cause an issue where a topic
was approved and the tag synonyms weren't applied.
This commit changes the logic so we attempt the more complete
`DiscourseTagging.tag_topic_by_names` call first and if this fails
and skip validations is on, then we do `DiscourseTagging.add_or_create_tags_by_name`.
This at least gives a chance for the full workflow to work first.

FIX: Process tag synonyms when approving reviewable queued post

---

db/migrate/20250116024516_update_font_site_settings_type.rb

This PR is  a follow-up to #30636.
The previous change altered the `data_type` of the `base_font` and `heading_font` site settings, but didn't update the corresponding entries in the `site_settings` table to match.

FIX: Add a DB migration to update font site settings types

---

spec/rails_helper.rb
spec/system/admin_embeddable_hosts_spec.rb
spec/system/admin_flags_spec.rb
spec/system/page_objects/components/d_page_header.rb
spec/system/page_objects/pages/admin_backups.rb
spec/system/page_objects/pages/admin_base.rb
spec/system/page_objects/pages/admin_embedding.rb
spec/system/page_objects/pages/admin_emojis.rb
spec/system/page_objects/pages/admin_flags.rb
spec/system/page_objects/pages/admin_permalinks.rb
spec/system/page_objects/pages/admin_users.rb

This PR proposes a base page object for admin pages. Since we're standardizing using components, this makes writing tests easier by abstracting away details about selectors.
This initial version instantiates a `DPageHeader` page object and delegates tab related actions to it, but over time we can add more stuff here as we standardize more.
We should probably have the components auto-generate the class names as well in the future, to further reduce manual toil and risk for mistakes.

DEV: Add base admin page page object

---

config/locales/client.en.yml

In the new admin UI conventions, button labels and section headings should be sentence case, rather than title case.
This PR performs a sweep of all the fragments visible when using the sidebar layout.

DEV: Convert a bunch of admin UI translations to follow convention

---

docs/INSTALL-cloud.md
plugins/spoiler-alert/README.md

`git pull` statement is now redundant and not needed

UX: Removed a redundant git pull statement from the docs

---

plugins/chat/assets/javascripts/discourse/lib/chat-ios-hacks.js

The stacking context fix we use in chat to avoid: https://bugs.webkit.org/show_bug.cgi?id=262287 was causing this weird behavior in chat where the scroll event wouldn't fire when the finger is on text and not an empty area of the scrollable div.
This simplified implementation seems to work reliably and avoids the issue.

FIX: ensures scrolls work in chat when touch is on text

---

app/assets/javascripts/discourse/tests/acceptance/post-inline-mentions-test.js
app/assets/javascripts/discourse/tests/integration/components/d-stat-tiles-test.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-tooltip-test.js
app/assets/javascripts/discourse/tests/integration/components/user-info-test.js
app/assets/javascripts/discourse/tests/integration/components/user-status-message-test.js
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/javascripts/float-kit/addon/lib/d-tooltip-instance.js
app/assets/javascripts/float-kit/addon/lib/float-kit-instance.js
plugins/chat/test/javascripts/components/chat-channel-test.js

When tapping something on a touch-enabled device, `mouseMove` events are still fired, so floatkit would still be triggered even if configured for 'hover' only. For links, this would be particularly strange, because the tooltip would appear for a split-second, before the page navigation occured.
To avoid this problem, we can use the more-modern 'pointerMove' event, and check the `pointerType` to exclude 'touch'

DEV: Do not trigger floatkit 'hover' for touch events

---

app/assets/javascripts/discourse/app/lib/composer/composer-position.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js

In a theme or plugin, if you have a scrollable mobile composer, you may want to allow scrolling events on the composer editor.. this allows for it!

DEV: applyBehaviorTransformer for composer-position editTouchMove

---

app/assets/javascripts/deprecation-silencer/index.js

We managed to find a slightly different way to trigger the same Ember bug. This commit makes sure that's silenced as well.

DEV: Relax 'unexpectedly found' matcher in deprecation-silencer

---

app/assets/javascripts/discourse/app/components/flag-action-type.hbs
app/assets/javascripts/discourse/app/components/modal/anonymous-flag.gjs
app/assets/javascripts/discourse/app/components/modal/flag.js
app/assets/javascripts/discourse/app/components/post/menu/buttons/flag.gjs
app/assets/javascripts/discourse/app/routes/topic.js
app/assets/javascripts/discourse/app/widgets/post-menu.js
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
lib/guardian/post_guardian.rb
lib/site_settings/validations.rb
spec/lib/guardian_spec.rb
spec/lib/site_settings/validations_spec.rb
spec/requests/admin/config/site_settings_controller_spec.rb
spec/system/admin_flags_spec.rb
spec/system/flagging_post_spec.rb
spec/system/page_objects/modals/anonoymous_flag.rb
spec/system/page_objects/pages/topic.rb

The new site setting `allow_anonymous_and_tl0_to_flag_illegal` allows tl0 users to flag illegal content. In addition, anonymous users are instructed on how to flag illegal content by sending emails.
Also `email_address_to_report_illegal_content` setting is added. If not provided, then the site contact email is used.

FEATURE: setting allowing tl0/anonymous flag illegal content

---

app/assets/javascripts/discourse/app/components/user-status-message.gjs
app/assets/stylesheets/common/components/user-status-message.scss

Before: 
After: 
Short message layout stays mostly unchanged:

UX: improve the alignment of long status messages

---

app/assets/javascripts/discourse/ember-cli-build.js

This improves the developer experience, and also happens to workaround https://github.com/embroider-build/content-tag/issues/92 in our production builds.

DEV: Enable ember-template-imports sourcemaps

---

app/assets/javascripts/discourse/app/components/post/menu.gjs
app/assets/javascripts/discourse/tests/integration/components/widgets/post-test-with-glimmer-post-menu-test.js
spec/system/flagging_post_spec.rb

When only one option is available for the action menu, it should be automatically expanded for the glimmer component.
This is the default behaviour for the old post menu: https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/widgets/post-menu.js#L624

FIX: Expand the hidden post menu when one option is available.

---

app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/acceptance/transformers/home-logo-minimized-test.js

Similar to the `home-logo-href` and `home-logo-image-url` transformers, this PR adds a new `home-logo-minimized` transformer to allow plugins/themes to amend the default behavior of the header logo.
Internal topic: t/144688.

DEV: Add home-logo-minimized transformer

---

app/assets/javascripts/discourse/config/environment.js
app/helpers/application_helper.rb

1. Add comments
2. Remove obsolete options: `historySupportMiddleware` (x2), `exportApplicationGlobal` (x2), `_APPLICATION_TEMPLATE_WRAPPER`, `_JQUERY_INTEGRATION`
3. Remove unused sections (dev, prod) from the test-only config
4. Add commented-out debug options to the "main" config
5. Copy options between configs for parity: `_DEFAULT_ASYNC_OBSERVERS`, `LOG_ACTIVE_GENERATION`, `LOG_VIEW_LOOKUPS`

DEV: Clean up ember configuration

---

app/assets/javascripts/discourse/app/lib/url.js
app/assets/javascripts/discourse/tests/unit/lib/url-test.js

When trying to insert schemaless or relative links using the "insert hyperlink modal" in the composer, the resulting link would be wrongly prefixed with "https://"

FIX: relative links in the insert hyperlink modal

---

app/assets/javascripts/discourse/app/components/emoji-picker/index.gjs
app/assets/javascripts/discourse/app/components/user-status-picker.gjs
app/assets/javascripts/discourse/app/instance-initializers/enable-emoji.js
app/assets/javascripts/discourse/tests/acceptance/user-status-test.js
plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js

discourse-emojis is used in chat only for message actions to show a difference with the the other emojis so people don't think it's just the smiley emoji.

UX: makes smile the default emoji-picker icon

---

plugins/chat/assets/javascripts/discourse/components/chat-message-actions-desktop.gjs
plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js
plugins/chat/spec/system/react_to_message_spec.rb

This feature has been mistakenly removed in https://github.com/discourse/discourse/commit/6740a340cacb4605e9c5d6e0b536dc43ede14ca3

FIX: re-adds favorite reactions on mobile

---

app/assets/javascripts/discourse/config/environment.js
app/assets/javascripts/discourse/config/optional-features.json.js
app/helpers/application_helper.rb

A follow-up to 560c1875a54da2e3c539ce9bae4ddf72252b8993
1. `_DEFAULT_ASYNC_OBSERVERS` is already configured in optional-features
2. `no-implicit-route-model` defaults to `true` now (see: `pnpm ember feature:list`)

DEV: Remove more ember options

---

plugins/chat/config/locales/server.en.yml
plugins/chat/lib/chat/inline_onebox_handler.rb
plugins/chat/plugin.rb
plugins/chat/spec/lib/chat/inline_onebox_handler_spec.rb
plugins/chat/spec/plugin_spec.rb

Previously if you linked to a chat thread inline, our oneboxer
did not have special handling for this, so the link would end
up with the text "Chat #channel-name" which is not ideal for a
thread.
This commit makes it so the thread onebox is in the format
"Thread title - #channel-name" if the thread title exists,
otherwise we show "Thread in #channel-name"

FEATURE: Chat thread inline oneboxes

---

app/assets/javascripts/discourse/app/controllers/topic.js
app/models/topic.rb
lib/guardian/post_guardian.rb
spec/lib/guardian/post_guardian_spec.rb
spec/requests/posts_controller_spec.rb
spec/system/private_message_spec.rb

In a PM, if a user has made a post, and is later removed from the PM, they can still edit their own post. This can be done either if they happen to have a composer open in an active tab, or by just manually sending an HTTP request.
The post guardian is missing a basic check, `can_see_post_topic?` when we determine whether a user can edit a post or not. This basic check is already in place when we determine whether a user can see the post in the first place.
This PR adds in the missing check, so that if the user tries to edit their post after being removed, they'll receive a 403.
It also adds a MessageBus message scoped to the affected user and topic when they are removed from the PM, which will redirect them to their inbox. This helps avoid a stale tab where they are still in the PM which …

FIX: Don't allow editing own posts user can no longer see

---

app/assets/stylesheets/common/select-kit/dropdown-select-box.scss

Applied `white-space: nowrap` to ensure text remains on a single line.

FIX: Prevent wrapping of select box container by applying nowrap

---

app/assets/javascripts/discourse/app/controllers/preferences/profile.js

When the user selects “Use Current Timezone” on Profile -> Preferences -> Profile, a call is made to `moment.tz.guess()`.
https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/ states that, by default, previously cached responses from this function will be returned upon subsequent calls. If your physical location has changed, this may result in a cached value being returned, and thus the timezone seemingly not being updating.
By passing the `true` value to the function, the cache is bypassed, forcing an explicit recheck of the current timezone.

DEV: Ignore timezone cache when getting current timezone

---

app/assets/stylesheets/common/base/onebox.scss

Added  `minmax(0, 1fr)` to `grid-template-columns` to ensure the second column can shrink to fit within the container, avoiding overflow in smaller viewports or when the container width is limited.

FIX: Adjust grid-template-columns to prevent text overflow

---

Gemfile.lock

Pulls in this change https://github.com/discourse/discourse-fonts/commit/d09fff88677695c959e818633d8061d1574450c4

DEV: Bump discourse-fonts to 0.0.13

---

config/nginx.sample.conf

Add fonts to existing block, and remove unneeded 'include' directive.
Followup to 8dbbe53dcc09766f9ce90963326caa96a5f20a03

FIX: Update nginx `types` config

---

app/assets/javascripts/discourse/app/components/post/menu.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/show-more.gjs

ff815384 introduced a modifier which changes tracked state. If the conditions are correct, this can cause an infinite re-rendering loop. One example is [here](https://meta.discourse.org/t/346215/4), although there are other non-dev-tools things which could trigger this kind of loop. As a general rule, modifiers should not change tracked state.
This commit changes the approach to match the rest of the new-post-menu assumptions: instead of trying to modify `collapsed` at runtime, the rendering of individual buttons has the `>1` logic. That matches the existing logic [here](https://github.com/discourse/discourse/blob/89ff7d51e6/app/assets/javascripts/discourse/app/components/post/menu.gjs#L392C18-L394C6).

FIX: Avoid possible rendering infinite-loop in post-menu

---

app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs
app/assets/javascripts/discourse/app/components/user-menu/items-list.js

so it respects the user's input of opening it in another tab when CTRL/META/MIDDLE clicking it.

UX: convert "view all notification" to a link

---

app/assets/javascripts/discourse/app/instance-initializers/safari-viewport-setup.js
app/assets/stylesheets/common/font-variables.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/mobile/discourse.scss
app/assets/stylesheets/mobile/form-kit/_control-input.scss

By default, iOS safari will automatically zoom into focused inputs with font-sizes less than 16px. To avoid this, we had a CSS rule to ensure inputs always had a large font-size on iOS. This worked, but did lead to design inconsistencies.
Instead, we can set `user-scalable=no` on the viewport meta tag. Since iOS 10, this property doesn't actually stop users zooming. But it *does* still prevent the automatic zooming of inputs. So it solves our zoom problem, and allows us to remove the CSS font-size workaround.

UX: Replace `font-size-ios-input` workaround

---

app/assets/javascripts/discourse/app/lib/to-markdown.js
app/assets/javascripts/discourse/tests/unit/lib/to-markdown-test.js

This will properly extract the text used to generate mathjax expression (both inline and block display modes) as well as remove all the cruft that mathjax is adding in the DOM.
Internal ref - t/135307

FIX: supports quoting mathjax

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs

- Calculate the overscroll amount and subtract it from viewport-based measurements
- Only round at the end of calculations, to avoid sub-pixel rounding discrepancies
- Compensate for < 1px fluctuations which happen during scroll
Before:
https://github.com/user-attachments/assets/a1044405-9f4a-46b1-a3b1-bc5fff29bf45
After:
https://github.com/user-attachments/assets/212e4a32-aa97-4054-aba0-b7f1d993f007

UX: Improve sidebar positioning in Safari

---

app/assets/javascripts/discourse/app/components/d-editor.js

When clicking more in the emoji autocomplete menu, the picker would sometimes be hidden at the bottom of the page. It was easily reproducible in long topic pages when scrolled to the bottom.
This commit just marks the textarea as the trigger which is not a perfect position but is still a good fallback.

FIX: emoji picker position when clicking more

---

config/locales/server.en.yml
lib/user_name_suggester.rb
spec/lib/email/receiver_spec.rb
spec/lib/user_name_suggester_spec.rb

Previously this setting would only control values received in an 'email' field from an identity provider. This commit extends it, so that it also applies to email-like content in other fields. This provides improved protections against partial email addresses being leaked

FEATURE: Improve `use_email_for_username_and_name_suggestions`

---

app/assets/javascripts/discourse/app/lib/avatar-utils.js
app/assets/javascripts/discourse/tests/acceptance/mobile-discovery-test.js
app/assets/javascripts/discourse/tests/acceptance/topic-discovery-test.js
app/assets/javascripts/discourse/tests/unit/lib/avatar-utils-test.js
app/assets/javascripts/discourse/tests/unit/models/report-test.js
plugins/chat/spec/integration/post_chat_quote_spec.rb
plugins/chat/spec/models/chat/message_spec.rb
spec/jobs/change_display_name_spec.rb
spec/lib/pretty_text_spec.rb
spec/lib/quote_rewriter_spec.rb
spec/services/username_changer_spec.rb

Lazy loading images naturally causes a slight delay, because the browser only starts to load them after laying out the DOM and checking whether they're in the viewport. Plus, in Safari, re-rendering the DOM of a lazy-loaded image always causes a brief flicker, even if the image is already cached in the browser.
Lazy-loading is most beneficial on large one-off images which are often rendered outside the viewport. That's frequently the case for images which users share in topics. Avatars, on the other hand, are very small images, they're very often above-the-fold, and the same avatar often occurs many times on the same page.
Therefore, this commit removes `loading="lazy"` from avatars, which should improve avatar load times in all browsers, and stop the flicker in Safari.
---
Tapping logo …

UX: Remove `loading="lazy"` from avatars for improved UX

---

plugins/chat/assets/javascripts/discourse/components/chat-message-actions-desktop.gjs

Message action menu used to be much more intrusive and show during scroll, if your mouse was going over a menu during the scroll it would stop it. Now it shouldn't happen anymore and this hack seems un-necessary, moreover, it was causing a bug where it would close the emoji picker unexpectedly if you would scroll a little bit on the actions menu while the picker was opened.

FIX: removes mousewheel edge case on messages

---

app/assets/javascripts/discourse/app/instance-initializers/viewport-setup.js

c171e3dc works well in Safari, because the browser ignores the `user-scalable=no` directive. However, PWA/Hub do respect the directive, which means that it stopped pinch-zooming from working.
This commit updates the strategy for those environments so that the viewport is only locked briefly during a focusin event. The simpler strategy is maintained for the real safari browser.

UX: Only lock viewport scale during focusin events for iOS PWA/Hub

---

app/assets/stylesheets/mobile/topic-post.scss

This fixes an issue where topics could scroll horizontally on mobile: https://meta.discourse.org/t/topic-page-layout-issue/348262?u=pmusaraj
It seems some recent core change impacted the read state size/position 
This sets the size and position to more static values (not based on global font changes) to avoid the issue, and removes the horizontal scroll.

UX: set mobile read state indicator to static size to avoid overflow

---

plugins/chat/spec/system/chat_message_interaction_spec.rb

```
Checking for expected text of nil is confusing and/or pointless
since it will always match. Please specify a string or regexp instead.
plugins/chat/spec/system/chat_message_interaction_spec.rb:51
```

DEV: Fix a warning in a chat spec

---

app/assets/stylesheets/common/components/footer-nav.scss

This was inadvertantly removed in d88ee33eb622e52cec5f442dd6416e68c8f758e4
See https://meta.discourse.org/t/348262/4

FIX: Restore footer-nav backdrop-filter for iOS < 18

---

app/models/color_scheme.rb
app/models/theme.rb
app/models/theme_color_scheme.rb
db/migrate/20250121180125_create_theme_color_scheme.rb
spec/models/theme_spec.rb
spec/requests/admin/color_schemes_controller_spec.rb

Related to https://github.com/discourse/discourse/pull/30893
As part of the theme overhauling project, we're making each theme fully own/control its color palette which can be edited directly on the theme page. To make this possible, we need to introduce a special type of color palettes that are marked as "owned by a theme" in the database which aren't displayed in the admin color palettes page and can't be edited from it. This PR is the first step of this change; it adds a new join table to associate a color palette with a theme. For now, we're keeping the relationship one-to-one (hence the `UNIQUE` indexes), but we may later change it to one-to-many.
Internal topic: t/141648.

DEV: Introduce theme-owned color palettes

---

plugins/chat/assets/stylesheets/common/base-common.scss

Since this change https://github.com/discourse/discourse/commit/6c3a7f2a674253681ef419df02c8d15d71ecab83#diff-48126857aeb1748fb1eb2500ca69b832212061db59d93ed61dde9fd5dcddf0c7 we had various behaviours in different browsers as what should be at the top was ambiguous. This commit ensures the navbar is one layer above the content.

FIX: ensures chat navbar is on top of content

---

config/locales/client.en.yml

Reported here: https://meta.discourse.org/t/open-hamburger-menu-wording/348216
After adding the sidebar, we started calling related settings the "navigation menu" because it can either be the sidebar or the hamburger menu (dropdown) — this reflects that change in the keyboard shortcuts modal as well 
Before:
After:

UX: rename "hamburger menu" to "navigation menu" in keyboard help

---

script/import_scripts/base.rb

I take no credit for this fix. User154574 posted it and resolved my issue here:
https://meta.discourse.org/t/migrate-a-mailing-list-to-discourse-mbox-listserv-google-groups-etc/79773/240
Without adding this string mbox imports are currently broken with the error 
> /var/www/discourse/script/import_scripts/base.rb:447:in `strip!': **can't modify frozen String: "xxxxx-xxxxxxx@xxxxxxx.com" (****FrozenError****)**

Added duplication to name to prevent modification of frozen string exception

---

Gemfile
Gemfile.lock

Mini_racer was redesigned to keep all V8 vm integration on a dedicated thread.
Previous attempts at upgrades had lots of stack poisoning across V8 owned
and Ruby owned threads that were leading to segfaults.
We will monitor the new design in production to see how robust the new solution is.

DEV: update mini_racer

---

app/assets/stylesheets/common/foundation/base.scss

Inherit `font-variation-settings` and `font-feature-settings` if there are any, keeping consistency for `textarea`/`input`/`button`/`select` with any `html`-set CSS.

UX: inherit font-settings on form controls

---

app/assets/stylesheets/common/base/code_highlighting.scss

The solution in (https://github.com/discourse/discourse/pull/30547) using `em` units was causing readability problems for code blocks in mobile. This reverts to the previous solution (https://github.com/discourse/discourse/pull/30536) of using `font-size: inherit` for code within heading elements.
The downside is that the code in heading won't be slightly smaller than the other text like it is for inline code in paragraphs, but it seems worth it to avoid causing other size issues.

UX: Revert #30547 UX: use em units for code font-size

---

app/assets/stylesheets/common/base/search-menu.scss

FIX: Adjust search menu buttons alignment

---

app/assets/javascripts/discourse/app/components/header/topic/info.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/type/topic.hbs
app/assets/javascripts/discourse/app/components/topic-list/featured-topic.gjs
app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/components/topic-list/item/topic-cell.gjs
app/assets/javascripts/discourse/app/components/topic-list/latest-topic-list-item.gjs
app/assets/javascripts/discourse/app/components/topic-status.gjs

…so that plugins/themes can conditionally conditionally display their topic-status icon (e.g. just on the topic list, or everywhere but the header)

DEV: Add a `context` arg to after-topic-status outlet

---

Gemfile.lock

This applies some fixes to Inter which remove some features we set (like sso4)
from the core CSS.
It brings us closer to default.

DEV: update discourse-fonts

---

app/helpers/application_helper.rb
app/models/color_scheme.rb
app/models/color_scheme_color.rb
config/site_settings.yml
db/migrate/20250120115539_add_dark_hex_to_color_scheme_color.rb
lib/stylesheet/importer.rb
lib/stylesheet/manager.rb
lib/stylesheet/manager/builder.rb
spec/helpers/application_helper_spec.rb
spec/lib/stylesheet/manager_spec.rb

We're embarking on a project for overhauling the color palette and theme systems in Discourse. As part of this project, we're making each color palette include light and dark modes instead of the status quo of requiring 2 separate color palettes to implement light and dark modes.
This PR is a first step towards that goal; it adds a code path for generating and serving `color_definitions` stylesheets using the built-in dark variant of a color palette. All of this code path is behind a default-off site setting `use_overhauled_theme_color_palette`, so there's no change in behavior unless the setting is enabled.
Internal topic: t/141467.

DEV: Backend support for light/dark mode in color palettes

---

app/assets/javascripts/discourse/app/lib/textarea-text-manipulation.js

`replaceText` will replace some text, then call `selectText()` to restore the cursor position. However, selectText was asynchronous, so calling `replaceText()` multiple times in the same runloop iteration would cause the cursor to jump to an unexpected place. This likely explains some of the weird behavior we've seen with upload-markdown replacement

DEV: Ensure sequential `replaceText` calls work correctly

---

app/assets/javascripts/discourse/app/lib/sidebar/user/categories-section/category-section-link.js
app/assets/javascripts/discourse/app/lib/sidebar/user/tags-section/tag-section-link.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-categories-section-test.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-tags-section-test.js

Fixes issue reported in https://meta.discourse.org/t/sidebar-links-loose-active-state-on-the-hot-list-filter/348468

FIX: Keep active state in sidebar button for category/tag hot routes

---

app/assets/javascripts/discourse/app/lib/composer/composer-position.js

We stop propagating the `touchmove` event in the composer to ensure that the page doesn't scroll inadvertently. We should only do this if no text is selected, otherwise we block making changes to the text selection on the `textarea` element.

FIX: Allow `touchmove` in composer when there is a selection

---

app/assets/javascripts/discourse/app/components/composer-container.hbs
app/assets/stylesheets/common/base/sidebar.scss

This adds the class `composer-has-preview` to the HTML element when the composer is opened and the preview is visible. 
This allows us to adjust the sidebar height, so that the previewless composer can overlap the sidebar and better utilize the available space. 
Before:
After:

UX: add HTML class for composer preview to manage sidebar height

---

app/assets/javascripts/discourse/app/components/d-button.gjs

If a consumer is passing in their own string to `@translatedLabel`, then they should set it as `htmlSafe` themselves (if it is indeed safe)

DEV: Only mark translations as htmlSafe for DButton

---

app/controllers/export_csv_controller.rb
lib/guardian.rb

Follow-up to #30918.
This change moves the guardian check for whether an export has been generated too recently to the endpoint handler, since we only want this check to apply when generating an export.

FIX: Only apply the rate limit to user exports, not downloads

---

app/assets/javascripts/discourse/app/components/topic-label-content.gjs
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js

Because of https://github.com/discourse/discourse/commit/2b63830496f25a8a042d570df3f8d701bfb1f88b  `Which topic do you want to reply to rendering HTML` was rendering raw HTML.
Added `htmlSafe` for now.
I'll work on testing for this feature.

FIX: Which topic do you want to reply to rendering raw HTML
