app/assets/javascripts/admin/addon/components/admin-report.hbs
app/assets/javascripts/discourse/app/components/d-page-subheader.gjs
app/assets/stylesheets/common/admin/admin_report.scss
app/assets/stylesheets/common/admin/dashboard.scss

Heading link regression reported here: https://meta.discourse.org/t/admin-panel-reports-in-the-community-health-section-are-no-longer-clickable/347631
Also noticed some style regressions:
Before:
After:

UX: fix admin dashboard link and style regressions

---

app/assets/javascripts/admin/addon/components/admin-user-exports-table.gjs

Followup to #30918.
We need to check that the user export data exists before creating a model, since having an empty model will cause the UI to incorrectly think there's a user export to display.
This change shows the correct message, instead.

FIX: Show the correct message when no user export exists.

---

app/assets/javascripts/discourse/app/lib/icon-library.js
app/assets/javascripts/discourse/tests/unit/lib/icon-library-test.js
db/fixtures/006_badges.rb
lib/svg_sprite.rb

This PR raises an error on any deprecated icon names being converted by `icon-library.js`, which will result in any deprecated icons introduced in JS-land to fail qunit/system tests. 
We'll do the same for `svg_sprite.rb` once I've resolved pre-existing deprecated icons in core/plugins that's caught by the same exception logic.

DEV: raise error on deprecated icon name caught on JS in system and qunit tests

---

config/nginx.sample.conf

We are scrubbing the `Client-Ip` request header at the nginx proxy
because it is not a request header which we have decided to trust. Our
application should only use the `X-Fowarded-For` request header instead.
This change helps to resolve `ActionDispatch::RemoteIp::IpSpoofAttackError`
errors from being raised by the `ActionDispatch::RemoteIp` when
the request headers contains both `Client-Ip` and `X-Forwarded-For`.
At the time of writing, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
also states that "The HTTP X-Forwarded-For (XFF) request header is a de-facto standard header for identifying the originating IP address of a client connecting to a web server through a proxy server."

FIX: Scrub `Client-Ip` request header in nginx

---

app/assets/javascripts/discourse/app/templates/activate-account.gjs

Fixes Activate Account page's tada emoji that's currently broken (missing the base path) on subfolder installs.

FIX: broken tada emoji on subfolder account activation

---

lib/backup_restore/backuper.rb
spec/lib/backup_restore/backuper_spec.rb

This corrects an issue where very long titles on
website would cause the backup not to save
cause filename was too long

FIX: truncate extremely long site name titles

---

app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.js
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/mixins/username-validation.js
app/assets/javascripts/discourse/app/routes/invites-show.js
app/assets/javascripts/discourse/app/templates/invites/show.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs

_Splitting this out from https://github.com/discourse/discourse/pull/30919 to simplify review and isolate issues_
This will update properties that are used by the UsernameValidation mixin to autotracking and also updates the use of Input component in these templates to native inputs. This will help the refactor of the mixin to a helper class that uses the  modern Ember reactivity system.

DEV: refactor components dependent on UsernameValidation to use related tracked properties and native inputs

---

app/jobs/regular/backfill_badge.rb
app/models/user_badge.rb
app/models/user_stat.rb
spec/models/user_badge_spec.rb
spec/models/user_stat_spec.rb

This commit fixes an SQL syntax error in `UserBadge.update_featured_ranks!` when
the `user_ids` param is an empty array `[]`.
This was causing the `Jobs::BackfillBadge` job to raise the following
exceptions:
```
Job exception: ERROR:  syntax error at or near ")"
LINE 6:   AND user_id IN ()
```
This commit fixes the same error in `UserState.update_distinct_badge_count` as well
Follow-up to 3e4eac0fed05daedcdea50d6275e143469d55eda

FIX: Query syntax error in `UserBadge.update_featured_ranks!`

---

db/migrate/20250124062108_remap_deprecated_icon_names_for_seeded_badges.rb

This is a very narrowly scoped migration to update badges.icon for two deprecated names `smile` and `share-alt`. Following on from this PR that updated the Badge seed fixture used as part of site creation: https://github.com/discourse/discourse/pull/30942
The migration logic closely follows that of the [previous DB migrations](https://github.com/discourse/discourse/pull/30100) that updated all deprecated FA icon names, just that we reduce the mappings to only look for `smile` and `share-alt`.

DEV: add migration to remap from deprecated icon names for badges

---

.github/workflows/tests.yml

This could cause assets (e.g. fonts) to try and load from `www.example.com`, which led to an error. In the case of theme-qunit tests this actually caused the run to fail. Not entirely sure why... font failures shouldn't be catastrophic... but this is a good fix regardless.

DEV: Remove DISCOURSE_HOSTNAME from test workflow

---

app/assets/javascripts/discourse/app/components/topic-label-content.gjs
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/discourse/tests/fixtures/topic.js

https://github.com/discourse/discourse/pull/30962 lost the rendering of category in topic-label-content. This commit fixes it and adds a test to ensure we render category and tags.

FIX: ensures category is rendered

---

config/locales/client.en.yml

(credit: @moin-Jana for spotting this)
Fixes the english translation string for `admin.user.exports.started`, had an extra `collecting`.

DEV: fix typo in admin.user.exports.started translation string

---

app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-header.js

Double clicking on the INPUT for tag entry
was cause the INPUT to be selected but the
actual tag entry and lookup to be hidden
This adds special case handling

FIX: double click on tag INPUT breaking expected behavior

---

app/controllers/application_controller.rb
spec/requests/application_controller_spec.rb

fix an improper redirect when enforcing second factor under a subfolder install

FIX: enforce second factor with subfolders

---

app/assets/javascripts/discourse/app/components/bulk-select-toggle.gjs
app/assets/javascripts/discourse/app/components/notifications-tracking.gjs
app/assets/javascripts/discourse/app/components/topic-drafts-dropdown.gjs
app/assets/javascripts/discourse/app/components/user-menu/items-list.hbs

While updating a couple of themes I noticed some buttons were missing `.btn-default`, which resulted in some inconsistent button styling

DEV: add missing button classes

---

app/models/user.rb
spec/models/user_spec.rb

When suspending a user, we check for similar users by
IP address and show a number of and a list of them.
However we were checking this if the current user had a
NULL IP address, which found all other users with a NULL
IP. This doesn't make sense, this commit fixes the issue.
**Before**
**After**

FIX: NULL IP for similar users caused incorrect message

---

app/assets/javascripts/admin/addon/components/webhook-item.gjs
app/assets/javascripts/admin/addon/templates/web-hooks-show.hbs

This fixes two minor problems on the admin webhooks page.
- Wrong key used for edit button title in listing.
- Duplicated use of `i18n` leading to "en.Edit" in show page.

FIX: Minor i18n problems on admin webhooks pages

---

plugins/chat/assets/javascripts/discourse/components/chat-drawer.hbs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/browse.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel-info-members.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel-info-settings.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel-thread.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel-threads.gjs
plugins/chat/assets/javascripts/discourse/components/chat/drawer-routes/channel.gjs
plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js
plugins/chat/assets/javascripts/discourse/services/chat-subscriptions-manager.js

These changes allow to load model when loading a screen of the drawer, the underlying idea is to avoid having to rely on the global `activeChannel`, this essentially makes each screen responsible for it's data.
This change is also fixing a bug where clicking on a link routing to the same screen of the drawer you are already on, would display a blank drawer.

DEV: implements model/afterModel/deactivate in drawer router

---

app/assets/javascripts/admin/addon/components/site-settings/bool.gjs
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.js

Checkboxes rendered for `bool` site settings weren't being promptly updated when resetting a non-default site setting value to the default value, because `enabled` was only set on initialization.
This PR changes `enabled` to a getter so it can track when the dependent `args` update.

FIX: reset bool site setting not updating checkbox

---

plugins/chat/assets/javascripts/discourse/routes/chat-channel-thread.js
plugins/chat/assets/javascripts/discourse/routes/chat-channel-threads.js
plugins/chat/spec/system/navigation_spec.rb

The following case was bugged:
- visit a thread in full page chat
- click channel title
- click back button in channel navbar
- :boom: you would have a channel with limited width as if there was still the thread showing next to it, but it was empty

FIX: correctly closes panels in threads

---

app/assets/javascripts/discourse/app/components/card-contents-base.js
app/assets/stylesheets/common/components/user-card.scss

When the usercard is opened, we manually assign focus to the first link to capture focus, but this creates an undesirable focus ring for visitors not relying on focus indicators for navigation.
With this update, the focus is assigned to the container rather than the first link. This fulfills the goal of capturing focus within the user card, but hides the focus ring until navigation within the card begins. 
`tabindex="-1"` is necessary because this allows us to manually focus the container (normally unfocusable) while removing it from the tab order for subsequent navigation. 
Before:
After:
then on tab:

UX: hide user card focus until keyboard navigation begins

---

app/assets/stylesheets/common/base/sidebar-more-section-links.scss

Currently the vertical ellipsis is slightly darker than other sidebar icons
Before: 
After:

UX: sidebar "more" icon color fix

---

app/assets/stylesheets/wcag.scss

Reported here: https://meta.discourse.org/t/wcag-high-contrast-color-palettes-for-low-vision/168795/30
Before: 
After:

A11Y: fix color issue with delete topic button in WCAG palette 

---

app/serializers/reviewable_score_serializer.rb
config/locales/server.en.yml
config/site_settings.yml
db/migrate/20250119222805_fill_fast_typing_threshold_based_on_deprecated_setting.rb
lib/new_post_manager.rb
lib/site_settings/deprecated_settings.rb
plugins/poll/spec/controllers/posts_controller_spec.rb
spec/requests/posts_controller_spec.rb

Rename `min_first_post_typing_time` to `fast_typing_threshold` and provide admin 4 options:
- disabled
- low - 1 second
- standard - 3 seconds
- high - 5 seconds
Related PRs:
- https://github.com/discourse/discourse-zoom/pull/112

FEATURE: new `fast_typing_threshold` site setting

---

app/assets/javascripts/admin/addon/components/admin-plugin-config-area.gjs
app/assets/javascripts/admin/addon/components/admin-plugin-config-page.gjs
app/assets/javascripts/admin/addon/controllers/admin-plugins.js
app/assets/javascripts/admin/addon/services/admin-plugin-nav-manager.js
app/assets/javascripts/discourse/app/lib/admin-plugin-config-nav.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-plugin-config-area-test.js
plugins/chat/assets/javascripts/discourse/initializers/chat-admin-plugin-configuration-nav.js

We used this flag for experimenting with admin plugin sidebars. We have now settled on a tabbed layout, and this is no longer needed.
This PR simply ignores the flag in a backwards-compatible way, so we can discontinue usage in plugins and then remove the backwards-compatibility in core.

DEV: Remove plugin sidebar rendering fallback

---

app/controllers/admin/email_controller.rb
spec/requests/admin/email_controller_spec.rb

It seems from the original commit notes that this was only included as a query
optimisation, but doing so leads to confusion: https://meta.discourse.org/t/348688
Searching for outbound mail to an address should find that address regardless
of whether or not the mail type to search for is explicitly `group_smtp`.

FIX: always search email logs including the cc: addresses

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js

We are adding some old deprecations (deprecated since 2022 at least) to the admin warning banner.

DEV: add IDs of old deprecations to admin warning banner

---

app/controllers/topics_controller.rb

We have had reports of the topic post move endpoint
sometimes timing out, not necessarily with a large
number of posts, but between two topics that have a
large number of posts.
This buys us some time by `hijack`ing the controller,
which gives us 90 seconds instead of the Unicorn 30
seconds to do the work. At some point we may want to
do this in a background job.
c.f. https://meta.discourse.org/t/moving-posts-to-a-long-topic-fails/347984

FIX: Hijack controller for topic move posts

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs

This button in the topic map has our default button styling, but misses the btn-default class, making it inconsistent in themes

DEV: add missing class to top replies button

---

app/assets/javascripts/discourse-widget-hbs/package.json
app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

Cross-ref:
https://github.com/discourse/discourse/pull/31003, https://github.com/discourse/discourse/pull/31025, https://github.com/discourse/discourse/pull/31033

DEV: Lock `@glimmer/syntax` to 0.93.1

---

app/assets/javascripts/discourse/app/templates/group-index.hbs

This bulk-select button on group pages is styled like a default button, but lacks the `btn-default` class, making it inconsistent to style in themes

UX: add missing class to group bulk select button

---

app/controllers/search_controller.rb
spec/requests/search_controller_spec.rb

Previously, for a search query with `page=11` or higher, we were quietly returning the page 10 results. The frontend app isn't affected because it sets its own limit to 10 pages, but still, this response from the search endpoint does not make sense.
This change switches to returning a 400 error when the `page` parameter is above the allowed limit (a max of 10).

DEV: Add proper error response when searching with an invalid page param

---

app/assets/javascripts/admin/addon/components/admin-config-areas/emojis-list.gjs
app/assets/javascripts/admin/addon/components/admin-flag-item.gjs
app/assets/javascripts/admin/addon/components/admin-notice.gjs
app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs
app/assets/javascripts/admin/addon/components/admin-user-field-item.gjs
app/assets/javascripts/admin/addon/components/api-key-item.gjs
app/assets/javascripts/admin/addon/components/dashboard-period-selector.gjs
app/assets/javascripts/admin/addon/components/embeddable-host.gjs
app/assets/javascripts/admin/addon/components/emoji-value-list.hbs
app/assets/javascripts/admin/addon/components/ip-lookup.gjs
app/assets/javascripts/admin/addon/components/secret-value-list.hbs
app/assets/javascripts/admin/addon/components/simple-list.hbs
app/assets/javascripts/admin/addon/components/site-settings/file-types-list.gjs
app/assets/javascripts/admin/addon/components/value-list.hbs
app/assets/javascripts/admin/addon/components/webhook-item.gjs
app/assets/javascripts/admin/addon/templates/backups-index.hbs
app/assets/javascripts/admin/addon/templates/permalinks-index.hbs
app/assets/javascripts/admin/addon/templates/watched-words-action.hbs
app/assets/javascripts/discourse/app/components/badge-card.gjs
app/assets/javascripts/discourse/app/components/edit-category-tags.hbs
app/assets/javascripts/discourse/app/components/username-preference.gjs
app/assets/javascripts/discourse/app/templates/preferences/security.hbs
app/assets/stylesheets/common/admin/settings.scss
plugins/chat/admin/assets/javascripts/admin/components/admin-chat-incoming-webhooks-list.gjs
plugins/chat/assets/javascripts/discourse/components/browse-channels.gjs

All of these buttons use our default grey background styling, but aren't carrying the `btn-default` class, which makes them easier to target in themes. This PR adds the class.

DEV: add btn-default classes to buttons using default styling

---

app/models/problem_check_tracker.rb
spec/models/problem_check_tracker_spec.rb

We have many problem check trackers, and some of them
like `OutOfDateThemes` can have a message which has variable
data in it shown to admins. In this case, a list of themes
that need updating. Currently if you resolve one of these
out of date themes and refresh the list of problems, you
do not see any change.
This is happening because we are only updating the `details`
of the `ProblemCheckTracker` record, not the corresponding
`AdminNotice` record which is what is displayed to the admins
on their dashboard. This commit fixes the issue by updating the
details of the notice at the same time as the problem check
tracker details.

FIX: Update AdminNotice details when problem check tracker changes

---

plugins/chat/assets/stylesheets/mobile/chat-channel-row.scss

UX: Fix mobile chat DM row layout

---

lib/tasks/s3.rake

This reverts commit b9f8a77d9ba5222bbf55172092f0b235b92d1c85.
Reverting while we work on adding error handling. At the moment, failures are logged, but the process still exits with status=0.

Revert "DEV: Upload assets to S3 in parallel (#30210)"

---

app/assets/javascripts/discourse/app/form-kit/lib/validator.js
app/assets/javascripts/discourse/tests/unit/lib/form-kit/validator-test.js

When using the following validation: `length:5,10`, if the field had no value we would fail the validation which is incorrect. This commit ensures we return early in this case and don't fail anymore. If you want the same behavior you need to do: `required|length:5,10`

FIX: only validate length when value is set

---

app/assets/javascripts/discourse/app/routes/tag-show.js
spec/system/page_objects/pages/tag.rb
spec/system/tag_edit_spec.rb

Changing a tag name and reverting it to a previous tag name choice on
the same screen (meaning, without reloading the page) causes a 404
error.
Reproduction steps:
* Open an existing tag page https://your-discourse.com/tag/a
* Click the wrench, change the name and save
* Open edit again, revert the name to the original tag name
* 404 error
This was happening because of the way we find existing objects
in our store. Tags are using the name as the id/primary key
unlike other records in the UI. When we get the existing object
from the store we throw away the "new" ID, so we ended up with
the old tag ID on the existing object, which led to a 404. To
fix it we can just manually set the tag ID to what it is supposed
to be from params in the tag show route.
c.f. …

UX: Fix tag revert rename 404 error

---

Gemfile.lock

This brings in the change from ttf to woff2 fonts
for all our fonts.
This brings the total distributed size of our fonts down to 1.4MB (down
from 17MB) which is ~91% decrease, and most fonts are now only around
20KB max individually :slight_smile: The biggest reduction was Noto Sans
JP, which was in .otf format and ~4MB for each file.

DEV: Bump discourse-fonts

---

lib/promotion.rb
spec/models/group_user_spec.rb

The group has `grant_trust_level` setting which automatically updates the trust level when the user is added to the group.
Similarly, when the user is removed from the group, the trust level is recalculated.
There was a bug that when the trust level was downgraded, the user was not removed from automatic groups like for example `trust_level_3`.

FIX: Remove groups when promotion is recalculated.

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/styling-preview/-homepage-preview.js

Followup 83cc97994fa73c19832fa1dc0a2ec790e6f29064
Fixes issues after a refactor in the linked commit.
We now pass `font` as an object to the preview JS
functions, so to get the proper font for the canvas
we need to do `font.label`.
**Before**
**After**

FIX: Wizard preview fonts not loaded

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field-data.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs

Usage:
```javascript
// with a string
<Form as |form|>
<form.Field @name="foo" @title="Foo" @tooltip="text" as |field|>
<field.Input />
</form.Field>
</Form>
// with a DTooltip component
<Form as |form|>
<form.Field @name="foo" @title="Foo" @tooltip={{component DTooltip content="component"}} as |field|>
<field.Input />
</form.Field>
</Form>
```

DEV: supports tooltips in form kit

---

app/assets/javascripts/discourse/app/components/topic-progress.js
app/assets/stylesheets/common/base/topic.scss

We're seeing drops in CLS performance and the animation of this element may likely be the culprit. We can try removing and seeing if this is indeed the issue.

UX: remove animation for back button on mobile

---

app/assets/javascripts/discourse/app/components/scrolling-post-stream.js

This code was calling `elementFromPoint` on every scroll event. This is an expensive browser API, and also seems to trigger a premature 'paint' event during initial render. This seems to trigger cumulative-layout-shift metric problems, even though the shift was never actually visible onscreen.
This workaround was added more than 7 years ago, and it seems like `document.fullscreenElement` now correctly detects fullscreen youtube embeds. So we should be able to remove the `elementFromPoint` call without affecting any functionality.

PERF: Remove old fullscreen-detection code

---

db/migrate/20250130205841_fix_incorrect_fast_typing_threshold_setting.rb

Bug introduced in migration in this PR - https://github.com/discourse/discourse/pull/30865/files#diff-ca17f6d1353d626d1664a3d55fcc7aed3c6e4587a0269cb264aa2c25c3264013R14
When the old setting was `0` then the value `for fast_typing_threshold` should be `disabled` instead of `off`. Because of that mistake, new users cannot create a topic when the `min_first_post_typing_time` value was `0`.

FIX: change off to disabled for fast_typing_threshold setting

---

lib/stylesheet/manager.rb

Followup 23edfe7cc27cd56d5806c965ac52ed2b0394e8b8
When working on changes to any of the lib/stylesheet/*.rb
files, the color_definitions.scss and other stylesheet
caches can be annoyingly persistent.
This commit adds all of these lib files to the `max_file_mtime`
part of the `fs_asset_cachebuster` cache key, so if any of
them are changed then the cache will break, making development
a lot easier.

DEV: Include lib/stylesheet mtime in stylesheet cache

---

app/assets/javascripts/admin/addon/components/schema-theme-setting/editor.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/editor/tree-node.gjs
app/assets/javascripts/admin/addon/components/schema-theme-setting/editor/tree.gjs

1. use `constructor` instead of `didInsert`
2. remove non-existent `unregisterInputFieldObserver` arg usage
3. don't curry `@index` arg twice in `@onClick`
4. use `@bind`
5. use `concatClass`
6. `dIcon` -> `icon`

DEV: Clean up `TreeNode` component

---

app/assets/javascripts/admin/addon/components/admin-report-table.hbs
app/assets/javascripts/admin/addon/components/admin-report-table.js
app/assets/javascripts/admin/addon/controllers/admin-reports-show.js
app/assets/javascripts/admin/addon/models/report.js
app/assets/javascripts/discourse/tests/unit/models/report-test.js

This commit updates the display of totals and table
rows for reports in the admin interface. Currently
we show abbreviated numbers for totals e.g. 2.1M
which is not helpful when you need accurate data.
We are also not adding locale-specific number separators
so the row numbers are hard to read e.g. 246999 instead
of 246,999.
This commit fixes both issues to improve the UX of reports
without having to export them.
**Before (totals)**
**After (totals)**
**Before (rows)**
**After (rows)**

UX: Show full total numbers in admin reports

---

app/assets/javascripts/discourse/app/lib/utilities.js
lib/pretty_text.rb
lib/pretty_text/helpers.rb
spec/lib/pretty_text_spec.rb

This change ensures we use the base62 sha1 for videos when quoting
because this is what the composer is used to using. With a valid base62
sha1 the composer already knows how to fetch the placeholder image for
it.
Fallbacks have been created to continue to support the old way as well
as a fix for the old way so that the thumbnail continues to display when
quoting. These fallbacks are in place so that we don't have to rebake
all posts that contain videos. If we ever do that we may remove these
fallbacks.

FIX: Quoting videos can show a corrupted thumbnail

---

app/assets/javascripts/discourse/app/controllers/group-index.js
app/assets/javascripts/discourse/tests/acceptance/group-manage-membership-test.js

Adding/removing users from automatic groups should not be possible.
Bug introduced in this PR https://github.com/discourse/discourse/pull/30174
Before
After

FIX: Cannot manually add users to automatic groups

---

app/assets/javascripts/admin/addon/controllers/admin-config-localization-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-localization.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-localization-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/controllers/admin/config/site_settings_controller.rb
app/models/site_setting.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/routes.rb
config/site_settings.yml
plugins/discourse-local-dates/config/locales/server.en.yml
plugins/discourse-local-dates/config/settings.yml

This commit adds a new Localization config page for
admins, as a basic filtered site setting page similar
to Legal and Notifications. Included settings are:
* default locale
* allow user locale
* set locale from accept langauge header
* onebox locale
* display local time in user card
* discourse local dates enabled
* support mixed text direction
* unicode usernames
* allowed unicode username characters

FEATURE: Localization admin settings config page

---

app/jobs/regular/sync_acls_for_uploads.rb
lib/file_store/s3_store.rb

The optimization is not required because `find_each` fetches records in
batches of 1000 and no upload record will have more than 1000 optimized
images.

DEV: Remove `optimized_images_preloaded` kwarg from `FileStore::S3Store#update_upload_ACL`

---

app/assets/javascripts/discourse/app/lib/sidebar/base-community-section-link.js
app/assets/javascripts/discourse/app/lib/sidebar/common/community-section/section.js

Passing the owner allows section class to access services without having to pass each service instance one by one.

DEV: pass owner instead of services

---

lib/tasks/uploads.rake

This commit updates the `uploads:sync_s3_acls` rake task to accept a
`sync` argument that would run the rake task in a synchronous manner
so that the outcome of running the rake task can easily be determined.

DEV: Support synchronous mode for `uploads:sync_s3_acls` rake task

---

app/assets/javascripts/discourse/app/components/sidebar/switch-panel-buttons.gjs
app/assets/javascripts/discourse/app/lib/sidebar/custom-sections.js
plugins/chat/spec/system/separate_sidebar_mode_spec.rb

Previously the return to forum link would automatically take you to the forum homepage, however this was not intended functionality. We should attempt to take the user to their last viewed forum page.
This change fixes a bug in how we determined what the destination link should be.
Internal ref: /t/110508

FIX: switch panel back to forum last known url

---

lib/svg_sprite.rb

Meta: https://meta.discourse.org/t/the-icon-clock-is-missing-from-the-default-svg-subset/349823/3
This adds the missing `clock` icon to the default SVG subset.
The icon is used in the GitHub PR onebox and the user's activity pending posts tab.

DEV: Add missing clock icon to the svg_sprite list

---

app/assets/javascripts/discourse/app/routes/group.js

Prior to this change the tooltip would forever stay even after changing a group until you hard refresh the page.
No test as it's a very niche behavior and we have a todo to have multiple other improvements at this codepath.

FIX: reset the delete automatic group tooltip

---

app/assets/javascripts/discourse/app/controllers/preferences/interface.js
app/assets/javascripts/discourse/app/controllers/preferences/profile.js
app/assets/javascripts/discourse/app/templates/preferences/interface.hbs
app/assets/javascripts/discourse/app/templates/preferences/profile.hbs
app/assets/javascripts/discourse/tests/acceptance/user-preferences-profile-test.js
spec/system/page_objects/pages/user_preferences_profile.rb
spec/system/user_page/user_preferences_profile_spec.rb

This moves the "hide my public profile" checkbox from the /my/preferences/interface > other section into the top of the /my/preferences/profile section.
Internal ref - t/146570

UX: move "hide profile" checkbox to profile tab

---

lib/onebox/engine/github_pull_request_onebox.rb
spec/fixtures/onebox/githubpullrequest.response
spec/lib/onebox/engine/github_pull_request_onebox_spec.rb

Instead of displaying:
`discourse:main <- discourse:feature` or `discourse:main <- user:feature`
shows:
`main <- feature` or `main <- user:feature`

FEATURE: Remove unnecessary org names from PR oneboxes

---

plugins/chat/assets/stylesheets/common/chat-selection-manager.scss

UX: allow msg select buttons to wrap

---

app/assets/stylesheets/common/base/onebox.scss

Regressed possibly in https://github.com/discourse/discourse/pull/24198
Before / After

UX: Fix discourse topic onebox styling

---

lib/onebox/engine/hackernews_onebox.rb

This file has changed at some point to an svg instead
of a gif

FIX: Hacker News onebox favicon

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/composer.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/composer-test.gjs
app/assets/stylesheets/common/form-kit/_control-composer.scss

- `@height` was supported but not working correctly, this is now fixed and tested
- `@preview` was not supported, we would always hide the preview in form kit. You now have control over this, default `false`.

FIX: supports height/preview form-kit composer

---

app/assets/javascripts/discourse/app/components/post/menu/buttons/like.gjs
app/assets/javascripts/discourse/app/widgets/post-menu.js
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/components/buttons.scss
app/assets/stylesheets/desktop/topic-post.scss
app/assets/stylesheets/mobile/topic-post.scss

Related to https://meta.discourse.org/t/double-button-inconsistencies-post-menu/349845
This does some general clean up...
* **Moves shared mobile/desktop styles into /common** 
We had some mobile hover states for some reason, and desktop hover/focus states can be moved to common and gated with `.discourse-no-touch`... this means we're applying them on capabilities rather than device type
* **Adds some `-d-post-control-` variables to make theming easier** 
Theme authors can replace the variables without worrying about selector specificity 
* **Removes an overridden fade-out class from likes**
We were overriding the effect here anyway 
* **Fixes a janky hover transition effect on the like button**
This was being incorrectly inherited from another button
...and fixes some issues
* **Corrects …

UX: clean up post action menu styles, fix issues, add variables

---

app/assets/stylesheets/common/base/login.scss
app/assets/stylesheets/wizard.scss

support for the `system-ui` value is widely available now, so we can drop the device specific values: https://highperformancewebfonts.com/read/ditch-BlinkMacSystemFont-and-apple-system
https://caniuse.com/?search=system-ui

UX: update system font stack to system-ui

---

lib/tasks/db.rake

Rake allows env variables to specified in arguments, so we need to use the list of top_level_tasks which excludes those env
Followup to c8718a64dd7a26165efe91706ce5507e6999044a.

DEV: Tweak `db:create` re-exec

---

app/assets/stylesheets/common/base/topic-footer.scss

I'm not sure what the original intention was @ZogStriP, but it seems this causes a lot of overflow... 
Before: 
After:

UX: fix topic progress position when composer is open

---

app/assets/javascripts/discourse/app/components/topic-list/list.gjs
app/assets/javascripts/discourse/app/lib/transformer.js
app/assets/javascripts/discourse/tests/unit/lib/transformer-test.js

`topic-list-columns` expects consumers to mutate the DAG, not return a new one. This change means that themes/plugins do not need to remember to `return columns` when using the transformer.
Also removes the exception when someone returns a value to a mutable valueTransformer. This is essential for backward-compatibility.

DEV: Mark topic-list-columns transformer as mutable

---

app/assets/stylesheets/common/base/topic-footer.scss

Reported here: https://meta.discourse.org/t/topic-navigation-toggle-prevents-interactions-on-the-page-in-a-certain-area/350073
The purple wrapper shown here prevents elements underneath it from being clicked/tapped, this can sometimes interfere with post controls
The fix is to disable pointer events on the wrapping element, so clicks pass through. Then clicks are re-enabled on the child element.

UX: unblock clicking through progress bar wrapper

---

app/views/common/_discourse_splash.html.erb

That didn't render well (and was visible in dark themes only)

UX: Remove half-pixel border from loading dots

---

plugins/chat/assets/javascripts/discourse/services/chat-drawer-router.js
plugins/chat/spec/system/transcript_spec.rb

Due to a recent regression the selection management was failing in drawer mode for threads. We were not correctly setting the active thread.
This commit fixes the issue and adds a spec.

FIX: quote from thread in drawer mode

---

plugins/chat/lib/chat/mailer.rb
plugins/chat/spec/components/chat/mailer_spec.rb

due to an issue with LEFT JOIN, we were enqueue a "chat summary" email for every new messages in a channel, instead of for every new mentions 😬
This bloated the sidekiq queue with a lot of unecessary jobs as seen in
- https://meta.discourse.org/t/-/347197
- https://meta.discourse.org/t/-/346542
Thankfully, it wasn't sending those emails as the query for listing the unread mentions and dms was correct when generating the chat summary email.

FIX: chat was enqueueing too many "chat summary" emails

---

app/assets/stylesheets/common/components/topic-map.scss

Before (overflows, can't reach bottom): 
After (max-height clipped, can scroll contents):

UX: prevent topic map link menu from overflowing when there are many links

---

app/assets/stylesheets/common/components/buttons.scss

This PR adds the & line back to the transparent styling scss block. It was accidentally removed in this commit: https://github.com/discourse/discourse/pull/31138/files#diff-79939a573d667edf74bf255677d7cd3a87fe916be27b7b62c1fd48cbf9ce73f3

DEV: Add removed & back to transparent styling

---

Gemfile
Gemfile.lock

Previous upgrade had a runaway CPU issue due to
overly aggressive GC running.
MiniRacer was running V8 GC every 2 seconds.
New change fixes the parameter so it only issues a GC
if 2 seconds past since last MiniRacer eval.

DEV: upgrade mini_racer

---

app/assets/stylesheets/common/components/buttons.scss

This PR adds a couple more targets for transparent buttons.

UX: More selectors for transparent buttons

---

app/assets/javascripts/discourse/app/components/post-list/index.gjs
app/assets/javascripts/discourse/app/components/post-list/item/details.gjs
app/assets/javascripts/discourse/app/components/post-list/item/index.gjs
app/assets/javascripts/discourse/app/components/user-stream.gjs
app/assets/javascripts/discourse/tests/acceptance/user-drafts-stream-test.js
app/assets/stylesheets/common/components/user-stream-item.scss
app/assets/stylesheets/desktop/components/_index.scss
app/assets/stylesheets/desktop/components/user-stream-item.scss

Improves the layout for the drafts list page, including the addition of icons to represent the content type.
Internal ref: /t/129117

UX: improve drafts list

---

app/assets/javascripts/admin/addon/components/admin-config-areas/api-keys-new.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/webhooks-form.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/checkbox.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field-data.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/optional.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/tooltip.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/checkbox-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/layout/checkbox-group-test.gjs
app/assets/stylesheets/common/admin/admin_base.scss
app/assets/stylesheets/common/admin/api.scss
app/assets/stylesheets/common/form-kit/_index.scss
app/assets/stylesheets/common/form-kit/_tooltip.scss

Before this commit it was complicated to render a `Checkbox` outside of a `CheckboxGroup` as you would get no title, no description, no optional hint and not tooltip.
This commits makes all of this possible by adding a special case for checkboxes, and sharing code for tooltips and optional hint.
This commit also uses this opportunity to refactor part of the code to use curryComponent and reduce code duplication.

FIX: better standalone checkbox support

---

app/assets/javascripts/admin/package.json
app/assets/javascripts/custom-proxy/package.json
app/assets/javascripts/deprecation-silencer/package.json
app/assets/javascripts/dialog-holder/package.json
app/assets/javascripts/discourse-hbr/package.json
app/assets/javascripts/discourse-i18n/package.json
app/assets/javascripts/discourse-markdown-it/package.json
app/assets/javascripts/discourse-plugins/package.json
app/assets/javascripts/discourse-widget-hbs/package.json
app/assets/javascripts/discourse/package.json
app/assets/javascripts/float-kit/package.json
app/assets/javascripts/pretty-text/package.json
app/assets/javascripts/select-kit/package.json
app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/truth-helpers/package.json
package.json

pnpm 10 changed the lockfile syntax slightly, so we need to keep everyone using v9 until we handle the upgrade.

DEV: Pin pnpm to v9

---

app/assets/javascripts/discourse/app/lib/plugin-api.gjs

We'll be making this change more deeply soon. For now, this is the minimum change required to a this version-free syntax work under Discourse 3.4.0.

DEV: Make api version optional

---

app/assets/javascripts/discourse/app/lib/sidebar/common/community-section/section.js
app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/my-posts-section-link.js
app/assets/javascripts/discourse/tests/acceptance/sidebar-user-community-section-test.js
app/models/sidebar_url.rb
config/locales/client.en.yml
spec/models/sidebar_section_spec.rb
spec/system/drafts_dropdown_spec.rb
spec/system/editing_sidebar_community_section_spec.rb
spec/system/viewing_sidebar_spec.rb

While introducing the new drafts dropdown menu component, we also made some changes to how the sidebar link works for Drafts. However, after following user feedback and internal discussions we decided to revert back to the shared link approach that combines My Posts and My Drafts.

UX: restore shared sidebar link for posts and drafts

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/select.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/select-test.gjs

This option allows to force the presence of none when a value is selected.

DEV: adds includeNone param to form-kit select

---

config/nginx.sample.conf

The 'include' statements serve as extension outlets that are populated by discourse/discourse_docker.
This also includes some whitespace changes to make the file more consistent.

DEV: Add 'include' statements for outlets in nginx config

---

lib/version.rb

Version bump for stable: v3.3.4

---

lib/version.rb

Version bumps for main: v3.4.0.beta4, v3.5.0.beta1-dev

---

app/assets/stylesheets/common/base/topic-footer.scss

This is a follow-up to 71eb2f6cda9ad8a69ba1ae7d506440c3ff0bc9cb, we have outlets in this wrapper too — so best to re-enable pointer events on all immediate children of the disabled wrapper.

UX: ensure all children of `.with-topic-progress` are clickable

---

app/assets/stylesheets/wcag.scss

We had a little regression here: 
Before:
After: 
Upon closer inspection, a lot of the post control styles here are no longer necessary, as the contrast is fine without them:

A11Y: fix post control button contrast issue for WCAG colors

---

app/assets/javascripts/discourse/app/components/modal/change-owner.hbs
app/assets/stylesheets/mobile/modal-overrides.scss

These modals contain only a dropdown and have a very small height by default which doesn't give us enough space for the expanded dropdown. This commit adds two special cases to ensure we can correctly use the dropdowns.
Note I also removed label/form from change-owner modal as that seems totally unecessary.

FIX: correct mobile height of badge and ownership modals

---

app/assets/javascripts/discourse/app/lib/admin-plugin-config-nav.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs

In #31012 we deprecated this nav mode option when registering a plugin in a backwards compatible way.
We have now removed its use in all relevant plugins:
- [new-features-feed](https://github.com/discourse-org/discourse-new-features-feeds/blob/b51f054032bb0e66a9d80b58653c86d050565c42/assets/javascripts/discourse/initializers/discourse-new-features-feeds-admin-plugin-configuration-nav.js#L13)
- [ai](https://github.com/discourse/discourse-ai/blob/a7d032fa28ee4c2e19b2a7b36769e4ccdc656ec3/assets/javascripts/initializers/admin-plugin-configuration-nav.js#L13)
- [chat](https://github.com/discourse/discourse/blob/503f9b6f02ac5c4918d41611848c886b8755e5a0/plugins/chat/assets/javascripts/discourse/initializers/chat-admin-plugin-configuration-nav.js#L14)
- …

DEV: Remove deprecated plugin config nav mode option

---

app/assets/javascripts/discourse/app/controllers/review-index.js
app/assets/javascripts/discourse/app/routes/review-index.js
app/assets/javascripts/discourse/app/templates/review-index.hbs
app/assets/stylesheets/common/base/reviewables.scss
app/controllers/admin/unknown_reviewables_controller.rb
app/controllers/reviewables_controller.rb
app/models/reviewable.rb
config/locales/client.en.yml
config/routes.rb
spec/models/reviewable_spec.rb
spec/requests/admin/unknown_reviewables_controller_spec.rb
spec/system/page_objects/pages/review.rb
spec/system/reviewables_spec.rb

Plugins like for example AI or Akismet create reviewable items. When the plugin is disabled, then we cannot properly handle those items.
In that situation, we should display warnings about unhandled types. Instruct admin to reenable plugins. In addition, we should allow the admin to delete all pending reviews from disabled plugins.
Desktop:
Mobile:

FEATURE: Gracefully handle unhandled reviewables

---

app/assets/javascripts/admin/addon/controllers/admin-plugins-index.js
lib/plugin/instance.rb
plugins/chat/spec/requests/application_controller_spec.rb

In the current admin index page, all plugins show up as tabs. This includes plugins with auto-generated config routes.
This changes the tabs to include only plugins with custom UIs.
**Before:**
**After:**

DEV: Only include custom admin UIs in the plugins index tabs

---

app/assets/javascripts/discourse/app/components/create-topic-button.hbs
app/assets/javascripts/discourse/app/components/topic-drafts-dropdown.gjs
app/assets/stylesheets/desktop/components/drafts-dropdown-menu.scss
config/locales/client.en.yml
spec/system/drafts_dropdown_spec.rb
spec/system/page_objects/components/drafts_menu.rb

This change includes the following updates:
- Rename view all to view all drafts
- Remove view all link from drop-down when all drafts are displayed in the menu
- Different icon for draft topics and PMs (adds envelope for PMs)
- Disable drop-down when New Topic button is disabled (private categories etc)
- Improve drafts drop-down loading (no longer disables the trigger btn on click)
Disabled menu when the New Topic button is disabled:
Drafts menu open, showing new PM icon and also hides the view all link when all drafts are shown:
internal ref: /t/145786

UX: multiple drafts menu improvements

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-link.gjs
app/assets/stylesheets/common/components/topic-map.scss

Due to a change with how the link counter renders (as a pseudo element) the grid layout in the topic map link modal regressed slightly with long links 
before: 
after:

UX: fix wrapping of topic map links with counter

---

app/assets/stylesheets/common/base/topic-footer.scss

This is a follow-up to 71eb2f6cda9ad8a69ba1ae7d506440c3ff0bc9cb, we have outlets in this wrapper too — so best to re-enable pointer events on all immediate children of the disabled wrapper.

FIX: ensure all children of `.with-topic-progress` are clickable (#31176)

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/javascripts/float-kit/addon/lib/float-kit-instance.js

Stopping propagation when a `DMenu`'s trigger is clicked could prevent another floating UI element, e.g. the search menu in the header, from closing when clicking outside of it. We call `stopPropagation` on the event to allow more clicks within a `DMenu`'s trigger without it getting closed, so we shouldn't stop the event propagation if the `DMenu` hasn't been expanded yet.

FIX: Propagate pointerdown events on DMenu trigger when the menu isn't expanded

---

app/assets/javascripts/admin/addon/components/admin-report.gjs

Using length is not working on javascript objects and this would always be falsey.
```
const test = { foo: 1 };
test.length // undefined
```

FIX: correctly check for hasData in admin-report

---

app/assets/stylesheets/common/components/dropdown-menu.scss

When dropdown button text wraps onto multiple lines, it's centered. It should be left-aligned instead. 
Before: 
After:

UX: left-align dropdown menu button text

---

app/assets/stylesheets/desktop/modal.scss

Flex is causing odd wrapping for errors with multiple elements within.
Before: 
After:

UX: fix layout of invite modal errors

---

app/jobs/scheduled/clean_up_uploads.rb
spec/jobs/clean_up_uploads_spec.rb

Until now, we were excluding uploads with a not null
access_control_post_id from cleanup, because we were still
considering them "secure" even though they might have been
`secure: false`.
It's not necessary to keep these around, these are no more
important than regular uploads if they are not referenced
by anything.

FIX: Clean up not secure uploads with access_control_post_id

---

app/assets/javascripts/discourse/app/components/flag-action-type.hbs
app/assets/javascripts/discourse/app/components/flag-action-type.js
spec/system/flagging_post_spec.rb

Currently, the description is hidden when an additional reason field appears on the flag modal. It can contain important guidance and therefore should never be hidden.

FEATURE: show flag description along with additional reason

---

app/assets/javascripts/admin/addon/controllers/admin-plugins.js

Same as #31192, but for plugins that are not yet converted to the new show page. 🙏

FIX: Only include custom plugin config routes in tabs for old show page

---

config/locales/server.en.yml
config/site_settings.yml
lib/validators/post_validator.rb
lib/validators/stripped_length_validator.rb
spec/lib/validators/post_validator_spec.rb

Currently, the markdown for uploads is counted towards post minimum length requirements. This change introduces a site setting `prevent_uploads_only_posts` which can be flipped to exclude upload segments from the calculation.
**Note:**
We never do any stripping when checking against post maximum length requirements. I have not changed that as part of this PR.
**Caveat:**
When uploading a PDF or other non-media file, we generate something like this:
```
[filename.pdf|attachment](upload://hash.pdf) (806.1 KB)
```
That file size fragment is hard to match to the markdown part without a lot of false positives, and it is technically rendered as part of the raw text of the post, so for now that still counts towards the minimum length.

FEATURE: Allow excluding uploads from min post length requirement

---

app/assets/stylesheets/common/admin/plugins.scss

This PR fixes an issue where badges weren’t displaying correctly due to improper CSS targeting. 
/t/147165

FIX: Adjust badge selector for proper nesting in plugin list

---

app/jobs/regular/group_smtp_email.rb
spec/jobs/regular/group_smtp_email_spec.rb

Likely we want the group smtp email job to retry. Also added a check to see if we already have an email log entry for the message to avoid possible duplicates on retry.
Related previous commit: ed47b550266e1ab669c756b0ecb48d1685b08fee

DEV: Have group smtp email job retry

---

app/models/theme_modifier_set.rb
app/serializers/topic_list_item_serializer.rb
db/migrate/20250205174221_add_serialize_topic_op_likes_data_theme_modifier.rb
spec/serializers/topic_list_item_serializer_spec.rb

This PR adds two attributes (`op_can_like` & `op_liked`) to `TopicListItemSerializer`.
We've also added `serialize_topic_op_likes_data` theme modifier so that these two attributes are only added when a theme or component needs this data.

FEATURE: add first post likes data serializer

---

app/assets/javascripts/discourse/app/components/topic-admin-menu.gjs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs

While working with some themes, I noticed that all of these buttons don't have the `topic-footer-button` class, so it can't really be used effectively. The admin menu, bookmark button, and reply button were all missing it. This adds the class.

DEV: add `topic-footer-button` class to all topic footer buttons

---

app/assets/javascripts/discourse/app/controllers/preferences/interface.js
app/assets/javascripts/discourse/app/routes/preferences-interface.js
spec/system/page_objects/pages/user_preferences_interface.rb
spec/system/user_page/user_preferences_interface_spec.rb

This PR fixes a bug in the "Dark Mode" checkbox in the interface user preferences where the checkbox state doesn't appear in the disabled state if the user disables dark mode.
This happens because when rendering the checkbox, we check the relevant user options field within the controller's `init` method, but at that point in the controller's life cycle, the `user_option` object isn't available. What we should do instead is move this check to the route's `setupController` method where the `user_option` object is available and we can set the correct state on the controller.
https://meta.discourse.org/t/-/349976 (private topic)

FIX: Set the correct state of the dark mode checkbox user preference

---

app/assets/javascripts/discourse/app/components/composer-save-button.gjs

`disabled` -> `disable` to match:
https://github.com/discourse/discourse/blob/0e61565b2bb5aa24da060b701378b22dee056312/app/assets/javascripts/discourse/app/components/composer-container.hbs#L238

FIX: Correct typo in property name for save button component

---

app/serializers/admin_plugin_serializer.rb
lib/plugin/instance.rb
spec/lib/plugin/instance_spec.rb

Followup 503f9b6f02ac5c4918d41611848c886b8755e5a0
This previous commit introduced an autogenerated
settings route for every plugin with more than one
setting defined. Plugins with only one setting
only have enabled_site_settings defined, which are
handled using the toggle in the admin plugin list,
so we don't need a dedicated setting page for them.
However in production this introduced a performance
issue, since we were looking through SiteSetting.all_settings
for every plugin, which could be quite slow in some
cases especially on our hosting.
Instead, we already have all the plugin settings cached
inside `SiteSetting.plugins`. We can instead use this to
count how many settings the plugin has, then if there is > 1
for a plugin we use the settings route. This is a much faster lookup than …

PERF: Admin plugin preload settings routes

---

plugins/footnote/spec/system/admin_sidebar_navigation_spec.rb
spec/system/admin_sidebar_navigation_spec.rb

In a previous PR, I introduced this system spec that checks that a sidebar link is auto-generated for certain plugins.
This causes problems, because the core test suite can be run with plugins either enabled or disabled, causing flaky tests.
This fixes that by moving the test to the plugin's test suite, as suggested by @martin-brennan. 💌

DEV: Move a plugin related system spec to footnote plugin

---

lib/guardian/post_guardian.rb
spec/lib/guardian_spec.rb

When `suppress_secured_categories_from_admin` SiteSetting is enabled, it is expected that the admin will not be notified about PMs in which they are not participating - even when they watch the attributed tag.
Before it was only checking if the admin had access to a secured category assigned to a regular topic. PMs do not have categories so we need to ensure that admin in participating in that conversation.

FIX: do not notify admins about PMs when suppress is on

---

app/models/translation_override.rb
spec/jobs/check_translation_overrides_spec.rb
spec/models/translation_override_spec.rb

Translation overrides can be marked as "invalid interpolation keys" or "outdated" if the original translation is changed. We run a job every hour to check for this. We also have an admin problem check for it.
The problem is we don't refresh this status when an admin updates the override. So even if the invalid keys are removed, the override will still show up under the "invalid" filter.
There's a similar situation with the "outdated" status. The admin is shown a prompt which they can dismiss, which in turn updates the status, but updating the translation should also count as "addressing" it.
This PR runs a refresh on the override status when updating.

DEV: Refresh translation override status when updating

---

app/controllers/invites_controller.rb
spec/requests/invites_controller_spec.rb
spec/system/signup_spec.rb

6fd577d97d3923cec3d2458f45ebd2704703fd22 widened the scope of `use_email_for_username_and_name_suggestions` (default false) to include invites, which means that it fell back to a generic username like `user1`.
This commit makes it bail out earlier in this situation, so that no suggestion is attempted.

UX: Do not use generic username suggestions for invites

---

config/locales/server.en.yml
config/site_settings.yml
lib/middleware/omniauth_bypass_middleware.rb
spec/requests/omniauth_callbacks_controller_spec.rb

By default, when multiple login providers are enabled, Discourse requires user interaction before triggering an external auth flow. This is defense-in-depth against "Login CSRF" attacks.
This commit introduces a setting to control this behavior, so that it can be disabled when admins fully trust the downstream systems, and need an interaction-free login flow on a site with multiple login providers.
Default behavior remains unchanged.

FEATURE: Allow admins to opt-in to seamless redirects on `/auth/*`

---

app/assets/stylesheets/common/components/user-stream-item.scss
app/assets/stylesheets/desktop/components/user-stream-item.scss

Small alignment fix for user stream items on desktop, following changes made in #31122 
We currently have a combination of `post-list-item` and `user-stream-item` classes within these pages, so I've also applied some shared styles to these elements to provide a more consistent layout.

UX: user stream alignment fix for likes

---

app/assets/javascripts/discourse/app/components/post-action-description.gjs
app/assets/javascripts/discourse/app/components/user-stream.gjs
app/assets/javascripts/discourse/app/widgets/post-small-action.js

This change makes it possible to render the action code from small action posts (ie. close topic etc) without the relative date. This is applied in the user stream items to prevent duplication of dates.
Before:
After:
Internal ref: /t/129117/10

UX: omit date in user stream for small action posts

---

app/assets/javascripts/discourse/app/components/create-topic-button.hbs
app/assets/javascripts/discourse/app/components/d-navigation.js

Updates the create topic button to be icon only (mobile) due to screen space restrictions. The icon is also updated to make it easier to understand what the button does, even when there is no text.
On both desktop and mobile we used the full text button with the plus icon:
Desktop:
Mobile:
Internal ref: /t/145786

UX: use icon for create topic btn on mobile

---

app/assets/javascripts/discourse/app/lib/composer/composer-position.js

After you've selected and deselected text, `selection.rangeCount` will return `true` on future events. Checking for `selection.toString` is more robust.
Followup to f1bdd86a8c9bec03b962167c37963b1d11d0e5ea

DEV: Improve checking for selected text

---

app/controllers/posts_controller.rb

DEV: remove another deprecation notice when serializing args

---

spec/models/post_mover_spec.rb

arguments being passed to background jobs.

DEV: remove a deprecation notice regarding hard-to-serialize

---

lib/tasks/uploads.rake
spec/fabricators/draft_fabricator.rb
spec/tasks/uploads_spec.rb

This commit contains a couple of improvements for this
rake task.
* We no longer limit the uploads to only ones with Post
upload references, it doesn't matter what the secure uploads
are linked to, they should all be un-secured
* We now only get distinct uploads from the initial query,
multiple upload references on the same upload caused
double ups and confusing counts for the task
* We now also disable the secure_uploads_pm_only site
setting at the same time

FIX: Improvements for uploads:disable_secure_uploads task

---

lib/content_security_policy/builder.rb
spec/fixtures/plugins/csp_extension/plugin.rb
spec/lib/content_security_policy/builder_spec.rb
spec/lib/content_security_policy_spec.rb
spec/system/content_security_policy_spec.rb

[Security patch](https://github.com/rails/rails/commit/5558e72f22fc69c1c407b31ac5fb3b4ce087b542) (for this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2024-54133)) from rails actionpack was backported from [Rails 8.0.0.1](https://github.com/rails/rails/blob/v8.0.1/actionpack/CHANGELOG.md#rails-8001-december-10-2024) to previous stable versions including `7-1-stable` / `7-2-stable`.
Any previous version of Discourse upgrading to v3.4.0.beta3 and above would have observed their sites crashing if they had invalid sources in their CSP directive extensions.
This fix removes such invalid sources during our build of the CSP, and logs these at a warning level so devs are able to find out why their CSP sources were filtered out of the extendable directives.

FIX: invalid CSP directive sources should allow site to boot with valid CSP directives

---

.github/workflows/tests.yml
lib/plugin/metadata.rb

This repo was archived in March 2024 and is no longer supported.
Commit also fixes up the plugin-gem-symlinking logic to support removing plugins from the list

DEV: Drop d-crowd plugin from official list

---

app/assets/javascripts/discourse/app/components/group-navigation.gjs

This fixes the "all groups" link on mobile, follow-up to 50136ee
Before 
After

UX: fix horizontal group nav on mobile

---

lib/topic_publisher.rb

While it is possible derive a topic published event from category id changes in a `post_edited` or `before_post_publish_changes` event, there are use cases when a dedicated event is more apposite.

DEV: Add topic_published event

---

app/assets/javascripts/discourse/app/components/edit-category-settings.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js

This allows us to set custom values here, like "Voting" from the topic voting plugin: https://github.com/discourse/discourse-topic-voting/pull/232

DEV: add transformer for default category view setting

---

app/assets/javascripts/admin/addon/components/admin-site-settings-filter-controls.gjs
app/assets/javascripts/admin/addon/controllers/admin-site-settings.js
app/assets/javascripts/admin/addon/routes/admin-site-settings-index.js
app/assets/javascripts/admin/addon/templates/site-settings-category.hbs
app/assets/javascripts/admin/addon/templates/site-settings.hbs
app/assets/stylesheets/common/admin/site-settings.scss
config/locales/client.en.yml

This reverts commit 91e9c1c81343990d5ebbb3a3bb7c68ec4445d610.
After feedback, for now we are reverting this change. This is not
permanent, the settings sidebar will be removed again, after we:
* Visually group the settings the same way as the sidebar does
on All Settings
* Add more settings pages to the main admin sidebar to cover the ~250
settings not yet represented there

Revert "UX: Hide inner site settings sidebar if admin sidebar enabled (#31047)"

---

config/site_settings.yml

Adds a site setting confirmation to the following
settings, since they can be dangerous if changed
incorrectly:
* allowed_crawler_user_agents
* blocked_crawler_user_agents
* slow_down_crawler_user_agents

UX: Add confirmation to crawler settings

---

lib/content_security_policy/builder.rb
spec/fixtures/plugins/csp_extension/plugin.rb
spec/lib/content_security_policy/builder_spec.rb
spec/lib/content_security_policy_spec.rb
spec/system/content_security_policy_spec.rb

[Security patch](https://github.com/rails/rails/commit/5558e72f22fc69c1c407b31ac5fb3b4ce087b542) (for this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2024-54133)) from rails actionpack was backported from [Rails 8.0.0.1](https://github.com/rails/rails/blob/v8.0.1/actionpack/CHANGELOG.md#rails-8001-december-10-2024) to previous stable versions including `7-1-stable` / `7-2-stable`.
Any previous version of Discourse upgrading to v3.4.0.beta3 and above would have observed their sites crashing if they had invalid sources in their CSP directive extensions.
This fix removes such invalid sources during our build of the CSP, and logs these at a warning level so devs are able to find out why their CSP sources were filtered out of the extendable directives.

FIX: invalid CSP directive sources should allow site to boot with valid CSP directives (stable)

---

script/bulk_import/base.rb

Empty slugs for topics break Discourse. This makes sure that we always fall back to "topic" as default. And it also uses the configured slug generation method instead of always using ASCII.

DEV: Use correct method for creating slugs

---

app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.js
app/assets/javascripts/float-kit/addon/components/d-menu.gjs

This property allows to have a custom component for the DMenu trigger instead of using a `DButton` which comes with its own css class for example.
Example:
```gjs
const myComponent = <template><span ...attributes>test</span></template>;
<DMenu @triggerComponent={{myComponent}}>...</DMenu>
```
:warning: It's important to pass the attributes otherwise your custom trigger won't work.

DEV: supports triggerTag on DMenu

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs

With some customizations, this element may not be on the page. Instead of erroring, just continue on without the cloak.

FIX: JS error when .header-cloak isn't present

---

app/assets/javascripts/admin/addon/routes/admin-user-index.js
app/assets/javascripts/discourse/app/components/invite-panel.js
app/assets/javascripts/discourse/app/components/modal/create-invite.gjs
app/assets/javascripts/discourse/tests/acceptance/admin-user-index-test.js
app/serializers/site_serializer.rb
spec/requests/api/schemas/json/site_response.json
spec/serializers/site_serializer_spec.rb

In a few places throughout the app, when we render the `<GroupChooser />` component, we fetch the full groups list of the site from the `/groups/search` endpoint. This is wasteful because the full groups list is already included in the preloaded data that's sent to the client app on the initial page load, so we can just use this preloaded list for `<GroupChooser />` and we can avoid making an HTTP request.
Internal topic: t/147297.

FIX: Don't load all groups when rendering `<GroupChooser />`

---

app/assets/javascripts/discourse/app/components/sidebar/more-section-links.gjs
app/assets/javascripts/discourse/app/components/sidebar/more-section-trigger.gjs

This uses the new `triggerComponent` functionality to implement a button without the default `DButton` component classes, which helps themes avoid applying unintentional styling.

DEV: use custom trigger for sidebar more section

---

app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/mobile/discourse.scss

Reported here https://meta.discourse.org/t/do-auto-margins-still-need-to-be-unset-on-mobile/351503
This helps better handle some situations where we want to center content on large screens while using mobile view

UX: remove main-outlet-wrapper margin reset for mobile

---

app/serializers/user_export_serializer.rb
spec/serializers/user_export_serializer_spec.rb

If a user has an export that doesn't have a file it can cause their
profile page to not load.

FIX: User profile not loading with an empty export

---

app/assets/javascripts/discourse/tests/integration/components/select-kit/group-chooser-test.gjs
app/assets/javascripts/select-kit/addon/components/group-chooser.js

Follow-up to https://github.com/discourse/discourse/pull/31271
In the linked PR, we made `<GroupChooser />` use the site's preloaded list of groups instead of fetching the list from the servers every time the component is triggered. However, when a site has thousands of groups, the performance issue has shifted from the server to the browser — `<GroupChooser />` takes several seconds to render in the browser for a site with thousands of groups and the sites becomes completely unresponsive while the component is rendering.
This PR changes the `<GroupChooser />` so it limits the displayed groups to 100, with ability to filter the list to show more groups when there are more than 100 groups.

FIX: Limit displayed groups in `<GroupChooser />` to 100 groups

---

app/assets/javascripts/discourse/app/components/about-page.gjs
app/models/about.rb

This PR does some things to the about page:
- Hide the stat if there are 0 admins/moderators.
- Count admins and moderators separately, so a user who is both will add to both counts.
- A user who is both will still show up as a moderator, even if `admins` is hidden.

DEV: Separate admins and moderators on about page

---

app/assets/javascripts/discourse/app/components/search-menu/search-term.hbs
app/assets/javascripts/discourse/app/components/search-text-field.js
app/assets/javascripts/discourse/app/components/text-field.js
app/assets/javascripts/discourse/app/templates/full-page-search.hbs

Adds
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint
to the search inputs.
This hint is used for mobile devices to guide what label
is shown on the onscreen keyboard. By default `return` is
shown, now for search we will see `search`.
Also add `type="search"` to the full page search input for
further guidance.
Example below is from https://arnabsen.dev/quick-html-tips-enterkeyhint

UX: Add enter key hints for search

---

app/assets/stylesheets/common/base/edit-category.scss
app/assets/stylesheets/common/components/footer-nav.scss
app/assets/stylesheets/common/foundation/color_transformations.scss
app/assets/stylesheets/common/foundation/math.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/common/foundation/variables.scss
app/assets/stylesheets/mobile/compose.scss
app/assets/stylesheets/mobile/topic-post.scss
stylelint.config.mjs

The ignored lines are using functions that have replacements ,but those are not available on our sass version.

DEV: Fix `scss/no-global-function-names` stylelint rule

---

app/assets/javascripts/discourse/app/widgets/hooks.js
app/assets/javascripts/discourse/app/widgets/widget.js

This commit adds support these events in widgets.
Usage in a widget:
```javascript
pointerOver(event) {}
pointerOut(event) {}
```

DEV: supports pointerover and pointerout

---

app/assets/javascripts/discourse/app/controllers/topic.js
spec/system/keyboard_shortcuts_spec.rb

Currently when using the shortcuts to delete a post the UI would show you the confirmation modal even if you don't have the right to do it. This commit fixes the issue at the root in the `deletePostWithConfirmation` function.

FIX: do not show confirmation modal

---

app/assets/javascripts/discourse/app/components/search-menu/advanced-button.hbs

Noticed that this advanced search button unintentionally picks up some unwanted styles in themes: 
adding the btn-transparent class should help

DEV: add btn-transparent class to advanced search button

---

.github/workflows/dependabot-pnpm-dedupe.yml

It was missing branches for updated namespaced packages

DEV: Fix pnpm dedupe workflow branch matching

---

app/assets/javascripts/discourse/app/components/topic-footer-buttons.hbs

Adds a couple missing classes to this mobile-specific button:

DEV: add missing button classes to topic-footer-mobile-dropdown

---

spec/system/social_authentication_spec.rb

This is covered by the two specs above it:
"automatically redirects when going to /signup" and "automatically redirects when skipping the signup form"
(Plus, it doesn't do what it says on the label.)

DEV: Remove redundant system spec

---

app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js

Those still run `QUnit.testStart`/`QUnit.testDone` callbacks, and doing so with no actual test body leads to flaky behavior.

DEV: Don't run conditionally skipped tests

---

app/assets/javascripts/discourse/app/form-kit/components/fk/object.gjs

Ember workaround to ensure that a field with the same name is correctly destroyed/created when changing the params and then correctly calling registerField/unregisterFIeld.

FIX: ensures fields are correctly unregistered

---

app/assets/javascripts/discourse/app/components/modal/login.js
app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
spec/system/login_spec.rb

This fixes the destination of the auth process in the following scenarios:
- when landing on a PM or a topic as an anonymous user and then loggin in
- when landing on a public topic, hitting Reply or Like and then logging in

FIX: Keep user in same context after login

---

lib/validators/min_username_length_validator.rb
spec/lib/validators/max_username_length_validator_spec.rb
spec/lib/validators/min_username_length_validator_spec.rb

`@min_length_violation` was not defined and that made the range of values error to never be displayed.

FIX: Minimum username length should be validated

---

app/assets/stylesheets/common/base/edit-category.scss
app/assets/stylesheets/desktop/topic-list.scss
app/assets/stylesheets/mobile/topic-list.scss

UX: prevent long category names from overflowing on mobile topic list

---

app/assets/stylesheets/common/base/header.scss

We used to hide the bottom border of the header buttons when menu panels were open (so they'd appear connected), but this is no longer necessary... so all this vestigial CSS does is sometimes create a stray line like this:

UX: remove old menu border hack

---

app/assets/javascripts/discourse/app/components/modal/anonymous-flag.gjs
app/assets/javascripts/discourse/app/components/modal/flag.hbs
app/assets/javascripts/discourse/app/components/post/menu/buttons/flag.gjs
app/assets/javascripts/discourse/app/widgets/post-menu.js
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
db/migrate/20250212044021_rename_allow_all_users_to_flag_illegal_content_site_setting.rb
lib/guardian/post_guardian.rb
lib/site_settings/validations.rb
spec/lib/guardian_spec.rb
spec/lib/site_settings/validations_spec.rb
spec/requests/admin/config/site_settings_controller_spec.rb
spec/system/admin_flags_spec.rb
spec/system/flagging_post_spec.rb

Information about the process is displayed on top of the flag modal.
In addition `allow_tl0_and_anonymous_users_to_flag_illegal_content` site setting was renamed to `allow_all_users_to_flag_illegal_content` as it is more descriptive.

FEATURE: display process information on flag modal

---

app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
app/assets/stylesheets/common/admin/dashboard.scss
config/locales/client.en.yml
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/pages/admin_new_features.rb

This commit allows admins to filter the list of feature
feed items on the "What's new?" page to _only_ show experiments.
This is useful to both find existing experiments they may have
enabled, and to get a better overview of new ones they would
like to try.
This will eventually not be required when we build a dedicated
config page for experiments.

FEATURE: Allow showing only experiments on "What's new?"

---

app/assets/javascripts/discourse/app/components/post-list/item/index.gjs
app/assets/javascripts/discourse/app/components/user-stream.gjs
app/assets/javascripts/discourse/app/models/post.js
app/assets/javascripts/discourse/tests/acceptance/user-drafts-stream-test.js

- Remove JQuery
- Move decoration into `components/post-item`, instead of managing it from the top-level user-stream component
- Use new `DecoratedHtml` component

DEV: Refactor PostList cooked HTML rendering

---

app/assets/javascripts/discourse/app/components/composer-editor.js
app/assets/javascripts/discourse/app/components/composer-messages.js
app/assets/javascripts/discourse/app/components/d-editor.hbs
app/assets/javascripts/discourse/app/components/d-editor.js

- Switch to use new `<DecoratedHtml` component (including `renderGlimmer` support)
- Updates click handling to use `{{on` modifier instead of manual event listener setup/teardown

DEV: Refactor composer preview rendering

---

app/assets/javascripts/discourse/app/lib/formatter.js
app/assets/javascripts/discourse/tests/unit/lib/formatter-test.js

This changes makes relative date formats consistent for both tiny and medium formats.
Previously we were removing 12 hours from the date for medium format when it was more than 2520 minutes (42 hours) but not for tiny date formats.
Internal ref: /t/139852

FIX: relative date format consistency

---

app/assets/javascripts/discourse/app/services/composer.js

The current code was doing:
- initial value for `showPreview`
- setting another default value in `_setupPreview`
The fix is to move all the computation in one initial step when initializing the property.

FIX: prevents double set in the same computation

---

app/assets/javascripts/admin/addon/components/site-settings/upload.hbs
app/assets/javascripts/admin/addon/components/site-settings/upload.js
app/assets/javascripts/discourse/app/controllers/preferences/profile.js
app/assets/javascripts/discourse/app/templates/preferences/profile.hbs

Followup to 310cd513d88e3670c7008682ae4b35414084a17d. The `uploadDone` callback returns the whole upload object, so we need to extract the URL from it in these cases.

FIX: Image uploads in site-settings and profile

---

plugins/chat/assets/javascripts/discourse/components/chat-message-collapser.hbs
plugins/chat/assets/javascripts/discourse/components/chat-message-collapser.js
plugins/chat/assets/javascripts/discourse/components/chat-message-text.gjs
plugins/chat/assets/javascripts/discourse/components/chat-message.gjs
plugins/chat/assets/javascripts/discourse/initializers/chat-decorators.js
plugins/chat/assets/javascripts/discourse/lib/lightbox.js
plugins/chat/assets/stylesheets/common/base-common.scss

Uses the new `<DecoratedHtml` component, which takes care of the full decorate/render lifecycle. That means we can drop all the custom modifiers/debouncing which chat was doing. It also naturally adds support for `helper.renderGlimmer` in chat decorations.
This should resolve a number of subtle bugs related to chat message decorations.

DEV: Refactor chat HTML decorating

---

spec/serializers/about_serializer_spec.rb
spec/serializers/user_bookmark_list_serializer_spec.rb
spec/serializers/user_serializer_spec.rb

When running core specs with `LOAD_PLUGINS=1`, `DiscoursePluginRegistry.reset!` throws a warning. Using specific cleanup ensures that doesn't happen.

DEV: More targeted cleanup in plugin registry specs

---

app/assets/javascripts/discourse/app/lib/transformer.js

`consolePrefix()` is an expensive operation (it throws a synthetic error, then parses the backtrace), so we should only do it when absolutely necessary
On the topic-list page, this provides a 3-4% improvement in "init to render" times.

PERF: Defer `consolePrefix()` calculation for transformers

---

app/assets/javascripts/discourse/app/static/dev-tools/mobile-view/button.gjs
app/assets/javascripts/discourse/app/static/dev-tools/toolbar.gjs

Meta: https://meta.discourse.org/t/introducing-discourse-developer-toolbar/346215/15?u=arkshine
Followup https://github.com/discourse/discourse/commit/498481e5be21780c20e3646bd934eb9d7316a8f8
With David's approval, this PR adds a new button to toggle the mobile view.

DEV: Add mobile_view toggle to dev-tools toolbar

---

app/services/post_alerter.rb
spec/services/post_alerter_spec.rb

This sets the stage for being able to consolidate Like notifications using full names. It also is crucial to this [Reactions plugin PR](https://github.com/discourse/discourse/pull/31292).
The Like consolidation PR will come after these.

FIX: Adds further support for 'prioritize_full_name_in_ux' setting

---

app/services/badge_granter.rb
spec/services/badge_granter_spec.rb

When `revoke_ungranted_titles!` was invoked, the optional list of `user_ids` was not passed from the argument list of to the query. This resulted in an exception because the placeholder `:user_ids` existed in the query.

FIX: Ensure revoke_ungranted_titles! works with user_ids

---

app/assets/javascripts/discourse/app/lib/ajax.js

Before this, triggering two ajax requests close together would 'race' to create a csrf-token, and only one would succeed

DEV: Ensure only one csrftoken request is running simultaneously

---

app/assets/javascripts/discourse/app/components/topic-map/index.gjs
app/assets/stylesheets/common/components/topic-map.scss

The `toggle-summary` class is specific to our use in the AI plugin, so I've moved it there in https://github.com/discourse/discourse-ai/pull/1136... 
This wrapper was occupying some space even though it was empty in the PM topic map, so it's better to not have it. 
This also allows us to remove some sub-optimal CSS that was adding a gap based on content within it. Without the empty wrapper, we can always have the gap present.

DEV: remove empty outlet wrapper to prevent it from occupying layout space

---

plugins/chat/lib/chat/channel_fetcher.rb

Increases the number of chat channels loading to prevent missing notifications for channels beyond the current limit.

UX: increase limit in chat channel fetcher

---

app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/instance-initializers/auth-complete.js
app/assets/javascripts/discourse/app/lib/password-validation-helper.js
app/assets/javascripts/discourse/app/templates/signup.hbs

This introduces a helper class for password validation logic, and replaces the mixin in the signup controller class. All properties that impact password validation in that class are also converted to autotracked ones.

DEV: use PasswordValidationHelper instead of mixin for signup controller

---

plugins/chat/app/controllers/chat/api/channels_memberships_controller.rb
plugins/chat/app/models/chat/channel.rb
plugins/chat/app/models/chat/direct_message_channel.rb
plugins/chat/app/serializers/chat/channel_serializer.rb
plugins/chat/app/services/chat/remove_user_from_channel.rb
plugins/chat/assets/javascripts/discourse/components/chat/routes/channel-info-members.gjs
plugins/chat/assets/javascripts/discourse/models/chat-channel.js
plugins/chat/assets/javascripts/discourse/services/chat-api.js
plugins/chat/assets/stylesheets/common/chat-channel-members.scss
plugins/chat/config/locales/client.en.yml
plugins/chat/config/locales/server.en.yml
plugins/chat/config/routes.rb
plugins/chat/lib/chat/guardian_extensions.rb
plugins/chat/spec/requests/chat/api/channels_memberships_controller_spec.rb
plugins/chat/spec/services/chat/remove_user_from_channel_spec.rb
plugins/chat/spec/system/channel_members_page_spec.rb

This feature allows admins to remove users from channels. This is allowed for category channels and group DMs, but not one-on-one DMs, as that wouldn't make any sense. 😉 
This PR attempts to follow the existing structure as much as possible. The major moving parts are:
- A new back-end service for removing users from channels.
- A guardian extension checking the ability to do so. This is also propagated to the front-end.
- A new method in the front-end chat API.
- UI changes.
- Tests.
- When removing a member from a group DM, the header doesn't update to reflect this. This is a pre-existing issue. (It also doesn't update when adding members.) I have created a task to fix this separately.
- The terms `users` and `members` are mixed throughout the code base. I tried as best …

FEATURE: Allow admins to remove users from chat DMs

---

plugins/chat/assets/javascripts/discourse/components/chat-message-collapser.hbs
plugins/chat/assets/javascripts/discourse/components/chat-message-collapser.js

When a message is first sent, the original upload URL is used for a split-second before it's replaced by the optimised thumbnail. Using `didInsert` didn't re-run on any changes to the uploads. Switching to a proper modifier, and checking the length of the uploads array within it, will ensure that it is re-run whenever the uploads change.

FIX: Lightbox chat uploads immediately after optimize

---

app/assets/javascripts/discourse/app/controllers/password-reset.js
app/assets/javascripts/discourse/app/templates/password-reset.hbs

This replaces the password validation mixin with a helper class in the password-reset controller class. 
Also removes the redundant flag `passwordValidationVisible` that is already fully dependent on whether `passwordValidation` has a `reason`.

DEV: replace passwordValidation mixin in PasswordResetController

---

plugins/automation/app/jobs/scheduled/discourse_automation/tracker.rb

If Jobs::DiscourseAutomation::Tracker fails during execution of a pending automation, then the remaining automation were no longer executed.
Automation may fail for various reasons: a person has PMs disabled, rate limit is reached, etc.

FIX: Recover from failing automations

---

lib/tasks/db.rake

In this case, db:create is run as part of another command, so it's not in the argument list.
Followup to 30bea2563121308fce1bffb7b1e43c07e4a39839

DEV: Fixup `db:reset`

---

app/assets/javascripts/theme-transpiler/build.js
app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/theme-transpiler/postcss-variable-prefixer.js
app/assets/javascripts/theme-transpiler/postcss.js
app/assets/javascripts/theme-transpiler/transpiler.js
app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common.scss
lib/discourse_js_processor.rb
lib/stylesheet/compiler.rb
lib/stylesheet/manager.rb
pnpm-lock.yaml
spec/lib/stylesheet/compiler_spec.rb

Introduces PostCSS at the end of our CSS compilation pipeline. For now, just adds autoprefixer and light-dark polyfill.

DEV: Introduce postcss for autoprefix and `light-dark()` polyfill

---

app/assets/javascripts/theme-transpiler/build.js
app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/theme-transpiler/postcss-variable-prefixer.js
app/assets/javascripts/theme-transpiler/postcss.js
app/assets/javascripts/theme-transpiler/url-polyfill.js
lib/stylesheet/manager/builder.rb
pnpm-lock.yaml
spec/lib/stylesheet/compiler_spec.rb

Followup to 087e8e4bdb53f71930ec5c930c463c37dd2bd58d
- Fixes the variable-prefixer so it doesn't explode when the input is unparseable
- Add URL polyfills so that postcss can print its errors properly
- Catch postcss errors in the same way as sass errors

DEV: Improve postcss error handling

---

plugins/chat/assets/javascripts/discourse/components/chat-composer-dropdown.gjs

When making a double click on the [+] button next to the chat composer, the upload dialog will now be displayed.
No test as it's hard to test with capybara and is not an important behavior.

UX: triggers upload dialog on doubleclick

---

plugins/chat/assets/javascripts/discourse/components/chat/composer/thread.js
plugins/chat/spec/system/chat/composer/shortcuts/thread_spec.rb

Before this commit we were requiring two escapes:
- one to un-focus composer
- one to close panel

UX: close thread panel with a single escape

---

app/assets/javascripts/discourse/app/lib/autocomplete.js
app/assets/javascripts/pretty-text/addon/emoji.js
app/assets/javascripts/pretty-text/addon/emoji/data.js
lib/emoji/db.json
plugins/chat/assets/javascripts/discourse/components/chat-composer.js
plugins/chat/assets/javascripts/discourse/components/chat/composer/channel.js
plugins/chat/assets/javascripts/discourse/components/chat/composer/thread.js
plugins/chat/spec/system/chat_composer_spec.rb
plugins/chat/spec/system/page_objects/chat/chat_thread.rb

This change allows you to add a reaction to the most recent message, by sending a reaction message.
A reaction message can be formatted as `+{emoji}` (eg, `+❤️`), or as `+{emoji_code}` (eg, `+:heart:`).
https://github.com/user-attachments/assets/37d18353-2d23-43d6-ba5e-73c8b3ab8784
- Test that you can react normally to messages by typing the reaction.

FEATURE: Type reactions in chat

---

app/assets/javascripts/admin/addon/components/admin-theme-editor.js
app/assets/javascripts/admin/addon/models/theme.js
app/assets/javascripts/admin/addon/templates/customize-themes-edit.hbs
config/locales/client.en.yml
spec/system/admin_customize_themes_spec.rb

Previously, the only way to author js/hbs via the admin panel was to use `<script>` tags. This strategy is not pretty, and doesn't provide access to proper ES module imports or gjs `<template>` syntax.
Our recommendation for most themes is still that they should be authored using a proper IDE, the `discourse_theme` CLI, and version-controlled using git. However, we understand that this isn't a good fit for everyone, and that there's still a place for simple admin-panel-ui-authored themes.
This commit introduces a "JS" tab in the admin theme editor, which corresponds to a file named `discourse/api-initializers/theme-initializer.gjs` in the theme. This means that everyone will be able to move towards the more modern syntaxes, and away from the old `<script>` patterns.

FEATURE: Allow a gjs initializer to be authored in local themes

---

app/assets/javascripts/discourse/app/lib/textarea-text-manipulation.js

This issue has been impossible to repro locally so far, but we have reports of switching from one channel to another causing the sidebar to scroll to the bottom.
Looking at the trace of events, calling `blurAndFocus` is the last function call before it happens.

FIX: prevent sidebar scroll on chat composer focus

---

app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/base/modal.scss
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/components/footer-nav.scss
app/assets/stylesheets/common/foundation/mixins.scss
app/assets/stylesheets/common/table-builder/table-edit-decorator.scss
app/assets/stylesheets/vendor/normalize.scss
app/assets/stylesheets/wizard.scss
plugins/chat/assets/stylesheets/mixins/chat-reaction.scss
plugins/chat/assets/stylesheets/mobile/chat-message-actions.scss
plugins/chat/assets/stylesheets/mobile/chat-message.scss
plugins/footnote/assets/stylesheets/footnotes.scss

Now we have autoprefixer, we don't need to do this manually

DEV: Remove unneeded -webkit prefixes from css

---

app/controllers/extra_locales_controller.rb
config/nginx.sample.conf
spec/requests/extra_locales_controller_spec.rb

Code/translations for the admin panel and wizard are not considered sensitive, so there's no need for access control checks here. Once they're removed, we can cache in NGINX and the CDN, and thereby improve server and client-load performance.

PERF: Cache all extra-locale bundles and use CDN

---

app/serializers/topic_list_item_serializer.rb
spec/serializers/topic_list_item_serializer_spec.rb

This commit will allow plugin developers to enable/disable the topic op likes data in serializer.
Usage:
```
register_modifier(:serialize_topic_op_likes_data) { |enabled| true }
```

DEV: implements register_modifier(:serialize_topic_op_likes_data)

---

app/assets/javascripts/discourse/app/components/composer-editor.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/integration/components/composer-editor-test.gjs

This PR reverts the removal of the import quote toolbar button that happened in https://github.com/discourse/discourse/pull/30815.
It re-adds the previously existing implementation without changes.

FEATURE: revert/re-add import quote toolbar button

---

app/assets/javascripts/discourse/app/components/sidebar/api-sections.gjs

This has been a very hard to track and reproduce bug, but after a lot of profiling I detected that a scroll was showing in the trace just after a RemoveChild in div.sidebar-sections.
I suspect the performance of this is bad due to a difficulty to reconciliate object identity and using key seems to help here as I was not able to reproduce the bug after.

FIX: prevents sidebar to scroll when opening channel

---

app/assets/javascripts/discourse/app/components/emoji-picker/index.gjs
app/assets/javascripts/discourse/tests/acceptance/user-status-test.js

UX: Replace solid face-smile emoji picker icon with a regular one

---

plugins/chat/assets/javascripts/discourse/services/chat-drafts-manager.js
plugins/chat/assets/javascripts/discourse/services/chat.js

On chat setup we get the initial state of drafts for the current users, we need to add them to the drafts manager, but we don't need to store them again on the backend.
This commit adds a persist (boolean) parameter to the `ChatDraftsManager.add` service which when set to true will only add the draft on the frontend and not send it to the backend.
No test, as the behavior is already tested and unchanged, this is only a performance improvement.

DEV: allows to add a draft without persisting it

---

Gemfile
Gemfile.lock

that is now a built-in syntax_tree plugin

DEV: Remove an obsolete gem

---

lib/version.rb

Version bumps for main: v3.5.0.beta1, v3.5.0.beta2-dev

---

lib/version.rb

Version bump for stable: v3.4.1

---

plugins/chat/config/locales/server.en.yml
plugins/chat/db/migrate/20250220090521_add_last_unread_message_when_emailed_id_to_chat_thread_memberships.rb
plugins/chat/lib/chat/mailer.rb
plugins/chat/lib/chat/user_notifications_extension.rb
plugins/chat/spec/components/chat/mailer_spec.rb
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/mailers/user_notifications_spec.rb

Updates the chat summary email to account for:
- unread mentions in category channels (same as before)
- unread direct messages (now excluding threads)
- unread watched thread replies (for both channels and DM channels)
We have also reduced the window from 1 week down to 1 day for all 3 criteria. The DM unreads query is now properly selecting the first unread message within the window (rather than the first message regardless of read status).

FIX: delayed chat summary email

---

app/controllers/extra_locales_controller.rb

Followup to 1b5e4b6b0fef9811839490f2ee3b9f31d5fbed3b
When running through a CDN in a multisite environment, the site hostname needs to be included in the path or query or the URL so that the 'current db' can be set correctly by rails multisite. Without this, the response will assume the default site in the cluster.

FIX: Include hostname in extra-locales URLs

---

plugins/automation/config/locales/client.en.yml

Adds a description to highlight the need for sender to have correct permissions when sending PM. Without the correct permissions the PM is not sent and a message is added to the site logs.

UX: add automation script description for pm sender

---

app/assets/javascripts/discourse/tests/index.html
app/controllers/extra_locales_controller.rb
config/routes.rb
spec/requests/extra_locales_controller_spec.rb

CDNs are often configured to strip query params, which means that the `?v=` parameter wasn't reaching the Rails app, and therefore the cache-control header was not being set correctly. Having a 40 character sha1 digest in the **path** is the approach we take for other similar assets like stylesheets and theme-javascripts.
Also adds a spec for the fix in 573fbeef64f052decc47e740cbe01a3c298c20b5

PERF: Move extra-locale digest from query-param to path

---

app/assets/javascripts/discourse/app/components/backup-codes.gjs

Currently LF is used, making the backup codes indistinguishable for Windows users. Instead, use CRLF which is compatible for Windows as well as Linux and macOS fixes https://meta.discourse.org/t/downloaded-two-factor-backup-codes-are-not-separated-on-windows-only-lf-newline/331940

2FA Backup Code Download: Use CRLF for Windows-compatibility

---

app/assets/javascripts/discourse/tests/index.html
app/controllers/extra_locales_controller.rb
config/routes.rb
spec/requests/extra_locales_controller_spec.rb

Previously the rendered locale was based on the current session's locale. Now that we're routing requests via the CDN, we can't rely on the user's session, and should instead include the locale name in the URL. Also adds a `.js` suffix for parity with our other JS assets.

FIX: Include locale in extra-locales URLs

---

lib/site_setting_extension.rb
spec/jobs/disable_bootstrap_mode_spec.rb
spec/jobs/enable_bootstrap_mode_spec.rb
spec/lib/site_setting_extension_spec.rb
spec/requests/categories_controller_spec.rb

When using the rails console to change site settings log them to the
staff actions logs so that there is a record.

DEV: Log site setting changes from the rails console

---

lib/discourse.rb
spec/lib/discourse_spec.rb

…and remove `caller[0]`, we already have the stack

DEV: Add command to `execute_command` errors

---

app/controllers/admin/users_controller.rb
spec/requests/admin/users_controller_spec.rb

Small regression created in this PR https://github.com/discourse/discourse/pull/30635
The reason is included only when `include_silence_reason` option is included.

FIX: include silence_reason when admin sees user

---

app/assets/javascripts/admin/addon/components/color-palette-editor.gjs
app/assets/javascripts/discourse/tests/integration/components/color-palette-editor-test.gjs
app/assets/stylesheets/admin/admin_base.scss
app/assets/stylesheets/admin/color-palette-editor.scss
app/assets/stylesheets/common/base/discourse.scss
app/assets/stylesheets/common/components/color-input.scss
config/locales/client.en.yml
lib/svg_sprite.rb

As part of the theme/color palette overhaul project, we're redesigning the UI for the editing color palettes. This PR introduces a new `ColorPaletteEditor` component that encapsulates all the logic and interface for editing color palettes in the redesigned admin interface. This component isn't used anywhere at this moment, but it will be once we start introducing the rest of the redesigned interface.
Screenshot:

DEV: Introduce ColorPaletteEditor component

---

lib/auth/discord_authenticator.rb
spec/lib/auth/discord_authenticator_spec.rb

Previously we were applying the Discord username to both the name and the username fields in Discourse.
Supersedes https://github.com/discourse/discourse/pull/30994

DEV: Fix username/name mapping for Discord auth

---

lib/auth/auth_provider.rb

A number of attributes on `AuthProvider` are deprecated for and were marked for removal in 2.9.0.
This PR removes them.

DEV: Remove deprecated AuthProvider attributes

---

plugins/discourse-narrative-bot/config/locales/server.en.yml

In one of the discourse narrative bot tutorial steps, we show the user a few links and ask them to copy one and paste it in a reply to teach them about oneboxes. In order to prevent the links from getting oneboxed in the bot's post, we enclose them in `<>` which makes the links render as-is without oneboxing.
However, if an admin attempts to customize via site texts the tutorial step about onebox, the links enclosed in `<>` get removed completely from the step content because they're interpreted as HTML tags when the text override goes through sanitization (see [relevant code](https://github.com/discourse/discourse/blob/424da95128bd2e92c4d8e42baf65a947602e9c68/app/models/translation_override.rb#L73-L74)).
To prevent that, this PR changes the default content for the onebox step to use the …

FIX: Use `[]()` Markdown syntax for links instead of `<>` for narrative bot

---

plugins/chat/app/models/chat/incoming_webhook.rb
plugins/chat/config/routes.rb
plugins/chat/spec/requests/chat/incoming_webhooks_controller_spec.rb

This provides a slightly nicer-looking URL, and also helps when external systems have strict validations on the webhook URL.

FEATURE: Allow chat incoming webhooks to work without `.json` extension

---

lib/email/message_builder.rb

See https://meta.discourse.org/t/email-footer-says-visit-message-to-respond-to-no-names-after-to/354359 
There may be a deeper root issue somewhere further up the stack, but this change ensures we always use the `visit_link_to_respond` locale key when the PM is from `system`. Seems cleaner than copy that says `to respond to system`. 
Before
After

FIX: do not add `_pm` suffix to locale key when email is from system user

---

app/jobs/regular/update_username.rb

Always double check we are going to need to
rewrite a json object prior to doing the work
Pathological cases such a Null could end up
doing JSON rewrites on the  most of the notification
table

PERF: improve performance of username mover

---

app/assets/javascripts/discourse/app/components/modal/create-account.hbs
app/assets/javascripts/discourse/app/components/modal/create-account.js

This introduces a helper class for password validation logic, and replaces the mixin in the create-account modal component class. All properties that impact password validation in that class are also converted to autotracked properties and getters - the 1 remaining mixin here (UserFields) doesn't reference properties through `this.model` so no need to make changes in that mixin.

DEV: replace passwordValidation mixin in CreateAccount modal component

---

lib/onebox/engine/allowlisted_generic_onebox.rb
plugins/chat/assets/stylesheets/common/chat-onebox.scss
plugins/chat/spec/jobs/regular/chat/process_message_spec.rb
spec/fixtures/onebox/title_no_description.response
spec/lib/onebox/engine/allowlisted_generic_onebox_spec.rb
spec/lib/oneboxer_spec.rb

This behaviour was allowed in https://github.com/discourse/onebox/commit/cb82dce86afbfbf2db08b80d61134a7da25c6d68
but then inexplicably removed a few months later in
https://github.com/discourse/onebox/pull/448, but showing
title-only oneboxes is valid. The original Meta topic that
this was discussed in was https://meta.discourse.org/t/abc-news-not-oneboxing-due-to-missing-description/155933 .
This commit re-introduces allowing this behaviour to avoid the need for a plugin,
c.f. https://meta.discourse.org/t/allow-title-only-onebox/354306
For example <https://en-americas-support.nintendo.com/app/answers/detail/a_id/67660>:
This commit also unhides onebox descriptions in chat, it's not
clear why they were ever hidden in the first place:

FIX: Allow oneboxes with no description

---

plugins/automation/config/locales/client.en.yml
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/post_created_edited.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb

This commit allows admins to limit the post created/edited trigger execution to a specific post user group.
It's for example useful if you want to auto tag all the topics created by member of a specific group.

FEATURE: limits post created edited trigger to a group

---

app/assets/javascripts/truth-helpers/package.json

In modern embroider, `app-js` files need to be exported by the module.
We need to keep the separate `app/` directory because this v2 addon doesn't have a build step, and therefore the relative imports in the `src/helpers` files would break if loaded as-is into the app bundle.

DEV: Correct truth-helper exports

---

app/assets/javascripts/discourse/app/components/emoji-picker/content.gjs

With the emoji picker unified (https://github.com/discourse/discourse/pull/28277), there is no longer a footer, including the previous plugin outlet. 
This PR moves the plugin outlet at the top.
Usage example: [Emoji Fluff TC](https://meta.discourse.org/t/emoji-fluff/339163) 
Before: 
After:

DEV: Add emoji-picker-filter-container plugin outlet

---

.github/workflows/device-screenshots.yml

This is for continued experimentation in https://github.com/discourse/discourse/pull/31410,
GitHub does not react to the issue_comment event unless the workflow file is in main already,
see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
This workflow is a noop, it will be actually written/tested
in the linked PR

DEV: Adds empty device screenshot workflow file

---

lib/email/sender.rb
spec/lib/email/sender_spec.rb

When secure uploads are enabled, we need to send images that are rendered in the digest e-mail as attachments. Before this change, we would indiscriminately attach all images in the relevant topic's first post, whether they were rendered the e-mail body or not.
This change fixes that by only attaching images that are referenced in the e-mail body.

FIX: Don't attach images that aren't rendered in the digest e-mail

---

plugins/chat/app/jobs/regular/chat/notify_watching.rb
plugins/chat/app/models/chat/channel.rb
plugins/chat/app/models/chat/direct_message_channel.rb
plugins/chat/app/services/chat/leave_channel.rb
plugins/chat/app/services/chat/remove_user_from_channel.rb
plugins/chat/app/services/chat/unfollow_channel.rb
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/jobs/regular/chat/notify_watching_spec.rb
plugins/chat/spec/models/chat/category_channel_spec.rb
plugins/chat/spec/models/chat/direct_message_channel_spec.rb
plugins/chat/spec/requests/chat/api/channels_current_user_membership_controller_spec.rb
plugins/chat/spec/requests/chat/api/channels_current_user_membership_follows_controller_spec.rb

Followup b5147a4634f0fd5c98262f949a8c766bfd73d290
When we aliased `leave` to `remove` and renamed
the method in `DirectMessageChannel` in the previous
commit, this inadvertantly caused an error when
unfollowing group channels in the channel list.
When clicking the X in the channel list, we hit
ChannelsCurrentUserMembershipFollowsController for the
current user and the channel, which is supposed to only
unfollow the channel for all channel types including DMs.
Group DMs have a different Leave behaviour vs Unfollow.
Leaving the channel altogether is done from the channel
settings page, the "Leave channel" button, and that
deletes the user's membership and DM user record from that
channel.
So, we were trying to do the leave channel behaviour in the
unfollow channel controller, which was …

FIX: Error when leaving group DM channel

---

plugins/chat/app/models/chat/message.rb
plugins/chat/lib/chat/duplicate_message_validator.rb
plugins/chat/spec/lib/chat/duplicate_message_validator_spec.rb

This commit fixes an issue where if you tried to post
2 chat messages in quick succession which only contained
uploads (both `message` fields would be `""`), then we
would show the "You posted an identical message too recently."
error.
We should not do this for upload-only messages, they
are not identical messages.

FIX: Duplicate error for chat messages for upload-only messages

---

app/controllers/search_controller.rb
spec/requests/search_controller_spec.rb

This reverts commit 38de3d7bd1f503743c5d0237bc8a8d9d89effb8e. This changed seemed to be blocking our own AI helper as well if it has the “Search” tool.

Revert "DEV: Prevent crawlers from loading search results. (#31535)"

---

app/assets/javascripts/discourse/app/lib/password-validation-helper.js

Partial backport of https://github.com/discourse/discourse/commit/b8a4b11cbba2cd3ef7d294e25b4ca35130bbf5fb.
This adds the `password-validation-helper.js` class so that anything else depending on `stable` is able to use this class.

DEV: add password validation helper class

---

app/assets/javascripts/discourse/app/lib/utilities.js

Here we correctly focus a mid-stream post for screenreaders so they know where to start, but once focus is removed NVDA becomes unmoored and will jump back up the post stream to a previous post if someone tries to navigate with the arrow keys. 
Retaining the focus prevents this and shouldn't have any major side-effects. 
Tested using Chrome and NVDA

A11Y: retain focus on highlighted post to avoid scroll jump

---

app/models/email_token.rb

EmailToken.confirm is called in a number of contexts (hence the need for the `scope`) and this is sometimes needed in `user_confirmed_email` callbacks to distinguish those contexts.

DEV: add scope param to user_confirmed_email event

---

app/assets/javascripts/discourse/app/components/notifications-tracking.gjs

If we have a custom content for a `DMenu` trigger the `DButton` has no way to know there's text in this custom content so it will output the "no-text" class on the `DButton`. The correct way to fix this is to use our own `DButton` and the `@triggerComponent` so we can fully replace the behavior and set the correct classes.

DEV: correct class on trigger of notifications-tracking

---

app/controllers/posts_controller.rb
spec/requests/posts_controller_spec.rb

Add `posts_controller_create_user` modifier to modify which user is associated with the post creation.

DEV: Add `posts_controller_create_user` modifier

---

Gemfile
Gemfile.lock
lib/twitter_api.rb
spec/lib/twitter_api_spec.rb

We have a native dependency, Rinku, that's used only to make links in one place. We can get rid of this and use PrettyText instead.
This is almost a one-for-one replacement, but PrettyText adds `rel="noopener nofollow ugc"` to external links, which I suspect is actually what we want. It also wraps the result in a `<p>` tag, which we strip out for parity with Rinku.

DEV: Replace Rinku native gem with PrettyText

---

plugins/chat/app/models/chat/direct_message.rb
plugins/chat/spec/models/chat/direct_message_spec.rb

In #31366, we added the ability for admins to remove people from group chats. However, that only works as long as the admin is already in the group chat.
For forum-side group messages, admins can join any of them at will. This PR extends that same ability to chat for parity.

FEATURE: Allow admins to access group chats

---

app/controllers/test_requests_controller.rb
app/jobs/regular/emit_web_hook_event.rb
config/initializers/100-onebox_options.rb
config/routes.rb
lib/discourse.rb
lib/freedom_patches/net_http_header.rb
lib/onebox/engine/twitter_status_onebox.rb
lib/onebox/helpers.rb
spec/lib/discourse_spec.rb
spec/lib/onebox/helpers_spec.rb
spec/lib/oneboxer_spec.rb
spec/requests/admin/web_hooks_controller_spec.rb
spec/requests/net_http_header_spec.rb

This change monkey-patches `Net::HTTPHeader` to add a default `User-Agent` header to all requests that Discourse makes.
You can use a HTTP echo service to test that the header is being set correctly. For example:
```
% rails c
Loading development environment (Rails 7.2.2.1)
[1] pry(main)> JSON.parse(Net::HTTP.get(URI("https://echo.free.beeceptor.com")))
=> {"method"=>"GET",
"protocol"=>"https",
"host"=>"echo.free.beeceptor.com",
"path"=>"/",
"ip"=>"...",
"headers"=>
{"Host"=>"echo.free.beeceptor.com",
"User-Agent"=>"Discourse/3.5.0.beta2-dev-a6066732c67b1430655d1bdfe3c54ee271bc1569; +https://www.discourse.org/",
"Accept"=>"*/*",
"Accept-Encoding"=>"gzip;q=1.0,deflate;q=0.6,identity;q=0.3"},
"parsedQueryParams"=>{}}
```

DEV: Add a user agent to all HTTP requests that Discourse makes.

---

app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/desktop/components/header-search.scss

This change improves the alignment and placement of the search spinner and icons (ie. clear search / advanced search). Having a fixed width on desktop prevents the search field from changing width when the loading icon is toggled.
https://github.com/user-attachments/assets/99ff111c-73db-4a35-9110-f2e5e9da8bb8

UX: search dropdown layout improvements

---

app/assets/stylesheets/desktop/components/header-search.scss

Prevents deprecation warning of sass mixed declarations. We should move declarations above nested styles.
We get the following message from logs:
```
DEPRECATION WARNING [mixed-decls]: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
```
For more info see:
https://sass-lang.com/documentation/breaking-changes/mixed-decls/

DEV: prevent sass mixed declarations warning

---

spec/requests/api/schemas/json/user_create_request.json

The API docs is incorrect as the `active` param is only permitted when an admin API key
is used. This has always been the case since 429f27ec96c090d9054c498263f0cb635b665d99

DEV: Correct users create API docs

---

config/application.rb
lib/middleware/default_headers.rb
lib/middleware/discourse_public_exceptions.rb
spec/integrity/middleware_order_spec.rb
spec/requests/default_headers_spec.rb
spec/system/default_headers_spec.rb

In some error paths, headers that were set earlier can get overwritten (e.g. `Cross-Origin-Opener-Policy`) by middleware such as ActionDispatch::ShowExceptions.
This PR sets the `Cross-Origin-Opener-Policy` header to the value of the SiteSetting `cross_origin_opener_policy_header` if it's missing and if the response is for HTML. 
In future, this DefaultHeaders middleware can be used to set other default headers that relate to security or other purposes.

FIX: cross origin opener policy should apply to public error responses

---

app/assets/javascripts/discourse/app/components/edit-category-images.hbs
config/locales/client.en.yml

This adds a description to the category logo image fields that informs users of the recommended image aspect ratio and minimum size to upload.

UX: Add recommended image size for category logos

---

spec/lib/discourse_spec.rb

Followup to 8615fc6cbbd1085b37b5ec251e4acd39b16cb839
Stubbing things which are memoized means we'd need to clear the caches before & after the tests to be safe. Easier to just avoid the stubs altogether.

DEV: Resolve flaky user-agent spec

---

config/initializers/002-freedom_patches.rb
config/initializers/100-sidekiq.rb
db/post_migrate/20250227142351_migrate_sidekiq_jobs.rb
lib/discourse.rb
lib/freedom_patches/sidekiq.rb
lib/sidekiq_migration.rb

As we’re currently using a namespace for Sidekiq, in order to upgrade to the latest version, we need to drop it as it’s not supported anymore.
The recommended way is to use a different Redis DB for Sidekiq.
This PR uses a different config for Sidekiq and also takes care of migrating existing jobs (in queues and the retry and scheduled sets).

DEV: Migrate Sidekiq to a dedicated Redis DB

---

lib/site_setting_extension.rb
spec/lib/site_setting_extension_spec.rb

This change allows plugins to customize the description for site setting
logs that occur via site setting changes via the rails console.

DEV: Create plugin outlet for console site setting logging

---

app/assets/javascripts/theme-transpiler/transpiler.js

Miniracer seems to be inconsistent in how it serializes errors from JS, which caused flakiness in our specs. Throwing a simple string seems to circumvent this flakiness.

DEV: Resolve flaky terser spec

---

app/models/emoji.rb
spec/models/emoji_spec.rb

Before this commit doing: `Emoji.exists?(some_alias)` would return false. The only important thing in emoji is to never remove an emoji code which has been used by users but changing the name of an emoji and keeping old name as an alias should not break the application in any way, this commit should ensure this is true.

DEV: aliases should be considered as existing

---

app/assets/javascripts/discourse/app/components/modal/anonymous-flag.gjs
app/assets/javascripts/discourse/app/components/modal/flag.hbs

In this PR, information about the review process was added to the flag modal - https://github.com/discourse/discourse/pull/31300
Admins would like to use HTML tags to customise it even more.

UX: rich text for review_process_description

---

plugins/footnote/assets/stylesheets/footnotes.scss

1. remove the margin (it's displayed inline with text, so having a left margin didn't make sense)
2. use em unit in min-height
3. slighty tighten the button (inline padding 0.5em -> 0.4em) so it's more proportional

UX: Tweak footnote button styling

---

.github/workflows/linting.yml
lefthook.yml
lib/tasks/docker.rake

1. `--parallel` is the default
2. it runs in the current directory by default

DEV: Remove extraneous rubocop arguments

---

app/assets/javascripts/admin/addon/components/admin-branding-logo-form.gjs
app/assets/javascripts/admin/addon/components/admin-config-area-card-section.gjs
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-branding.gjs
app/assets/javascripts/admin/addon/templates/config-logo-settings.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/image.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-config-area-card-section-test.gjs
app/assets/stylesheets/admin/admin_config_area.scss
app/controllers/admin/config/branding_controller.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/routes.rb
config/site_settings.yml
db/migrate/20250217003916_x_summary_large_image_based_on_deprecated_setting.rb
lib/site_settings/deprecated_settings.rb
lib/site_settings/validations.rb
spec/lib/site_settings/validations_spec.rb
spec/system/admin_branding_spec.rb
spec/system/page_objects/components/admin_branding_logo_form.rb
spec/system/page_objects/pages/admin_branding.rb

Redesigned page to update site logos. `AdminBrandingLogoFormComponent` is attached to the old logos page and the new branding page. In the next steps, branding will replace the logos page.
A new `AdminConfigAreaCardSection` component was added hidden and less frequently used settings.
An image placeholder was also needed because many additional logos have a fallback to the site logo.
Finally, `twitter_summary_large_image` was renamed to `x_summary_large_image`.
Desktop
Mobile

FEATURE: rebranded admin logos settings

---

app/assets/javascripts/admin/addon/controllers/admin-reports-show.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js

This update adds a new value transformer to the `queryParams` property on the `AdminReportsShowController`. This is necessary so that plugins can add additional `queryParams` to the route and have it reflected when the route is transitioned.

DEV: Add value transformer for admin reports show query params

---

app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js

Admin sidebar links can have either a `href` or a
`route`, and the admin search was not handling
this properly. Also, we should always use `getURL()`
on the href in case the link is internal, for subfolder
sites.
This is hard to test right now, I plan on adding more extensive
links for admin-search-data-source in another PR.

FIX: Handle `href` admin sidebar links better

---

app/assets/javascripts/admin/addon/components/admin-config-areas/api-keys-new.gjs
app/assets/javascripts/discourse/app/lib/constants.js
app/models/api_key.rb
db/migrate/20250304054720_add_scope_mode_to_api_keys.rb
lib/tasks/javascript.rake
spec/models/api_key_spec.rb

Currently, after creating an API key, there is no way in the UI to see what scope the key has. To do this we need to first store the selected scope mode when creating a new key.
**In this PR we:**
- Convert `scope_mode` from a transient attribute to a database backed enum.
- Ship the possible values through the `javascript:update_constants` rake task instead of hard coding in front-end.
**In follow-up PRs we will:**
- Backfill existing API keys based on their associated `api_key_scopes` records.
- Start showing the scope mode in the UI.

DEV: Store selected API key scope mode in the database table

---

app/services/destroy_task.rb
config/locales/server.en.yml
lib/tasks/destroy.rake
spec/lib/tasks/destroy_rake_spec.rb
spec/services/destroy_task_spec.rb
spec/support/rake_context.rb

This PR adds a `destroy:posts` rake task that can be used to hard-delete a list of posts. Useful for dealing with large amounts of spam that has been soft deleted and needs to go.
**Notes:**
- Works on both non-deleted and soft-deleted posts. (We might want to change this to work on only soft-deleted posts?)
- Works exclusively on post IDs. We can't mix topic and post IDs as they might clash, and we have no way of resolving that ambiguity.
- Accepts either a rake-style array of IDs or, more conveniently, you can pipe the argument in through `STDIN`.
- Added a confirmation step since it's a fairly destructive operation.

DEV: Add rake task to bulk delete posts

---

Gemfile

This change allows updates to any 3.x version, while still restricting major updates to 4.x.

DEV: Relax Ruby version constraint to `~> 3.3`

---

app/assets/javascripts/discourse/app/components/small-user-list.gjs

Need to check length here so we're not exposing the component when there are no users, fixes: https://meta.discourse.org/t/expanding-topic-actions-displays-who-liked-the-posts-but-nobody-has-liked-it/355225
follow-up to https://github.com/discourse/discourse/commit/5312550bf98431fb6c52a1f99798638820819a42

FIX: only show small user list if users has length

---

app/assets/javascripts/admin/addon/controllers/admin-users-list-show.js
app/assets/javascripts/admin/addon/templates/user-index.hbs
app/assets/javascripts/admin/addon/templates/users-list-show.hbs
app/assets/javascripts/discourse/tests/acceptance/admin-users-list-test.js
app/assets/stylesheets/admin/users.scss
app/controllers/admin/users_controller.rb
app/serializers/admin_user_list_serializer.rb
spec/requests/admin/users_controller_spec.rb

Allow HTML tags in silence reason. Tags must be stripped for title attribute.
Before
After

UX: display html tags in silence reason

---

app/serializers/reviewable_score_serializer.rb
app/services/word_watcher.rb
spec/serializers/reviewable_score_serializer_spec.rb
spec/services/word_watcher_spec.rb

Follow-up to #31435.
This change ensures that queued posts that have ended up in the review queue due to matched a watched word display correctly.
It also improves the data checking to ensure that any other reviewables with watched words don't break the review queue, either.

FIX: Ensure queued posts with watched words are processed correctly.

---

lib/middleware/default_headers.rb
spec/requests/default_headers_spec.rb

Follow up from https://github.com/discourse/discourse/pull/31559.
We expect some standard headers to be added from `Rails.application.config.action_dispatch.default_headers` for responses, however these were found to be removed in some error paths. 
This PR adds those headers back if they aren't there, with the caveats that we don't add headers that are irrelevant for non-HTML responses, and neither do we add X-Frame-Options which is intentionally removed for embeddables.

DEV: ensure Rails application default headers are present in responses

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field.gjs

Calling `<field.Calendar>` will ultimately call `componentFor` which will mutate the type of the field. Problem is the way we use a hash to define all the available controls, would work correctly on first render, but because of the mutation in `componentFor` if something would trigger a re-render it would have to evaluate all the `componentFor` calls, and the last one would "win" (currently calendar), which would mean that a field rendered as custom would for example become calendar.
The easiest repro was:
```gjs
<Form as |form|>
<form.field as |field|>
{{log field}}
<field.Custom>
Hello world
</field.Custom>
</form.field>
</Form>
```
The fix for now is to mutate the value at the point where the component is actually rendered, in control-wrapper.
A possibly more correct longer term fix …

DEV: set field type in control wrapper

---

.github/workflows/tests.yml

In the `discourse/discourse_test:release` base image, the minio binaries
are already being installed and updated on a daily basis. There is also no
real need for us to have to run the latest minio binaries once it is
released. As such, we can drop the step in the `tests` workflow.

DEV: Remove installing minio binaries in tests workflow

---

db/migrate/20250212045125_add_type_source_to_reviewable.rb
db/post_migrate/20250305233449_populate_type_source_in_reviewable.rb

Follow-up to #31325.
When the upgrade process from 29a8c6ee498999f114f933d2de2b46989a407660 is run, there's a deployment race condition where old code can write a Reviewable to the database without a `type_source` (incorrectly defaulting it to 
"unknown").
This change adds a post-deploy migration script that populates any such Reviewables with the correct `type_source` value.

FIX: Ensure the reviewable.type_source migration is run post-deploy.

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs

This commit adds a PluginOutlet for activity number in mobile view, so I can override it with my theme component.
Why?
======
In this theme component https://meta.discourse.org/t/show-both-op-and-last-reply-on-mobile/267944, I need to add an avatar to the post time to indicate the last poster.
Without this outlet, I can't do this, having to rewrite the entire `item.gjs`, or use some vanilla JavaScript tricks to do it.

DEV: Add a PluginOutlet for mobile-view topic activity number

---

app/assets/stylesheets/admin/admin_config_area.scss

UX: remove padding in admin card section

---

config/locales/server.en.yml

Based on the discussion in https://github.com/discourse/discourse-social-share/pull/24#discussion_r1975633090 I think "fa-" is no longer needed in core either.

UX: Remove fa- prefix in svg_icon_subset setting description

---

plugins/chat/assets/javascripts/discourse/components/chat-composer.js
plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js

UX: removes per channel context of favorites emojis

---

lib/onebox/engine/youtube_onebox.rb
spec/lib/onebox/engine/youtube_onebox_spec.rb

Meta: https://meta.discourse.org/t/youtube-autoembeds-for-live-streams/350920
This PR supports YouTube live URLs, such as: `https://www.youtube.com/live/eJemwqO0SDw`.

FEATURE: Handle youtube live url format

---

app/assets/stylesheets/common/components/emoji-picker.scss

FIX: ensures emoji picker loader is centered

---

plugins/chat/assets/stylesheets/common/chat-replying-indicator.scss

We were using a zero width space added by CSS here, but have run into occasional encoding issues for some reason? a couple people have reported getting this instead of an empty space: 
I can't repro the issue, but we can avoid it by removing this space in CSS — setting the container height to `1em` along with `line-height: normal` should make it consistent with the height of the text within. 
In the blame it seems this static height on the container was added after the pseudo hack, and achieves the same goal when I test it across a Firefox/Chrome/Safari

DEV: replace zero width space character in chat typing indicator

---

lib/oneboxer.rb

Fixes the same issue that https://github.com/discourse/discourse/commit/e9387e238c75219a02ea07762f51d01f96f28f25
did for twitter.com, but for x.com. Since they redirect
on our first FinalDestination call with onebox, the request
fails even with `twitter_consumer_secret` and `twitter_consumer_key`
settings set.

FIX: Authenticated x.com oneboxes failing

---

app/controllers/tags_controller.rb
spec/requests/tags_controller_spec.rb

When a tag has a description defined, we should use that in the `<meta name="description"...` tag on the tagged topic list page. This matches the behaviour on the equivalent category pages.
Check that the description is being used correctly, and that the fallback text continues to function as expected.

FIX: If a tag has a description, use it for the meta description.

---

plugins/automation/app/models/discourse_automation/automation.rb

Logging creates impression that something is not working while everything is working as expected.

FIX: loop detection works as expected and does not need logging

---

package.json

Node 18 will soon be out of its support period, and many of our dependencies are now requiring node 22

DEV: Bump minimum node version to 22

---

plugins/chat/assets/javascripts/discourse/components/chat-thread.gjs
plugins/chat/assets/stylesheets/common/chat-channel-preview-card.scss
plugins/chat/spec/system/message_errors_spec.rb
plugins/chat/spec/system/visit_channel_spec.rb

Prevents channel non-members from seeing the composer in threads. Since they do not have the correct permissions to post within the channel, we should show the join channel CTA in place of the chat composer.
Internal ref: /t/146242

FIX: dont allow channel non-members to write messages in threads

---

app/assets/stylesheets/common/base/compose.scss
app/assets/stylesheets/common/base/topic-footer.scss

this adjusts the topic progress bar when the composer is open and the preview is hidden, so it properly aligns: 
Before:
After:

UX: adjust progress bar position when composer preview is hidden

---

app/assets/javascripts/discourse/app/lib/render-tags.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/acceptance/search-test.js
app/assets/javascripts/discourse/tests/acceptance/tags-test.js
app/assets/stylesheets/common/base/tagging.scss

We were using CSS to add commas between tags like this: 
but this is kind of a hacky way to add content and we've also ended up with a separate encoding issue side-effect
So this avoids that whole thing by adding the commas in the HTML properly — this also unlocks a bonus feature of using our value transformer system so it's easy to change the separator like this:
```js
import { apiInitializer } from "discourse/lib/api";
export default apiInitializer((api) => {
api.registerValueTransformer("tag-separator", ({ value, context }) => {
return "|"
});
});
```
to get:

FEATURE: customizable tag separator with value transformer in proper HTML

---

app/assets/stylesheets/common/base/tagging.scss

This is a follow-up to https://github.com/discourse/discourse/commit/55a3a4e69ed75b055fb4907ac5370cf1519276c6, the tag separator should be hidden for box/bullet tag styles

UX: hide tag separator for box/bullet styles

---

plugins/automation/config/locales/client.en.yml
plugins/automation/db/post_migrate/20250307031538_migrate_category_to_categories_post_created.rb
plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/lib/discourse_automation/triggers/post_created_edited.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb

- Allow deciding if we include or exclude sub categories
- Allow filtering to only look at PMs or Topics
- Allow selection of multiple categories
- Migrations to carry all data into new structure

FEATURE: improve post_created_edited automation triggers

---

app/controllers/tags_controller.rb
spec/requests/tags_controller_spec.rb

When a synonym page is visited, the user should be redirected to the parent tag.

FIX: redirect to parent tag when synonym page visited

---

plugins/discourse-narrative-bot/lib/discourse_narrative_bot/new_user_narrative.rb

`DistributedMutex` is eager loaded in production/test and autoloaded in
development.

DEV: Remove unnecessary `require`

---

app/assets/javascripts/discourse/app/components/topic-navigation.js
app/assets/javascripts/discourse/app/components/topic-timeline/container.gjs
app/assets/javascripts/discourse/app/services/composer.js

This updates the timeline behavior so that when the composer preview is closed, the full timeline is rendered. 
Before: 
After: 
When the preview is shown again, we recalculate and switch back to the timeline if needed

UX: show timeline when composer preview is hidden

---

db/post_migrate/20250304074934_backfill_api_key_scope_modes.rb
spec/fabricators/api_key_fabricator.rb
spec/fabricators/api_key_scope_fabricator.rb
spec/migrations/backfill_api_key_scope_modes_spec.rb

Follow-up to #31601. This will be used for display in the admin API keys UI.

DEV: Backfill API key scope modes

---

app/assets/javascripts/admin/addon/components/admin-config-areas/api-keys-list.hbs
app/assets/javascripts/admin/addon/components/api-key-item.gjs
app/assets/javascripts/discourse/tests/integration/components/admin-api-key-item-test.gjs
app/serializers/api_key_serializer.rb
app/serializers/basic_api_key_serializer.rb
config/locales/client.en.yml

**Note:** Do not merge before the backfill (#31606) is merged.
We're now storing the selected API key scope mode in the back-end, and can display it in the API key list.

UX: Show scope mode in API key list

---

app/services/inline_uploads.rb
spec/jobs/pull_hotlinked_images_spec.rb
spec/services/inline_uploads_spec.rb

Currently, when converting raw hotlinked image urls to image upload markdown, the `alt` attribute is left blank.
This change sets the `alt` to the original filename (which means it will also appear in the lightbox).
This adds more context and accessibility to the image and is consistent with how regular uploaded images default to use the filename.
For example:
`http://foo.bar/screenshot.jpg` becomes `![screenshot](upload://bEs9WFJErcB8y7m1Ye5JopTWeX3.jpeg)`

FIX: Use filename as alt for hotlinked image uploads

---

app/assets/stylesheets/common/float-kit/d-menu.scss
app/assets/stylesheets/mobile/float-kit/d-menu.scss

Buttons used in the dMenu mobile (touch device) variant should not:
* show states like hover, or focus
* should never have round borders because the component is full-width

UX: scope btn states to touch devices

---

spec/system/signup_spec.rb

- Remove `wait: 0` and base flow on site setting instead
- Ensure full-page-login has actually opened before running `go_back` - otherwise we'll end up going back to `about:blank`

DEV: Fix flaky signup spec

---

plugins/chat/spec/system/list_channels/drawer_spec.rb

The setup was happening after the page has loaded which could lead to inconsistent results.

DEV: attempts to fix flakey drawer spec

---

spec/system/email_change_spec.rb

This might not reduce the failures to zero but some screenshots of the failures clearly show we were still on the success message page.

DEV: more resilient email change spec

---

app/assets/javascripts/discourse/app/components/modal/login.js
app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/lib/url.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/tests/unit/lib/url-test.js

This should avoid unwanted early redirects from other routes (like the user api key routes).

FIX: Limit referrerUrl redirect to topic URLs

---

spec/integration/watched_words_spec.rb

This fixes a flaky test, where the generated flagged words would sometimes not be in alphabetical order.
This is the random seed that would previously fail:
```
bundle exec rspec --order random:48156 spec/integration/watched_words_spec.rb
```

FIX: When testing multiple flagged words, ensure test matches expected word order.

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/register-default.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/trailing-paragraph.js
app/assets/javascripts/discourse/tests/helpers/rich-editor-helper.gjs
spec/system/composer/prosemirror_editor_spec.rb

Adds a plugin to enforce an empty trailing paragraph.

FEATURE: add trailing-paragraph rich editor extension

---

app/assets/javascripts/discourse/app/lib/composer/rich-editor-extensions.js
app/assets/javascripts/discourse/app/static/prosemirror/components/prosemirror-editor.gjs
app/assets/javascripts/discourse/app/static/prosemirror/core/serializer.js
plugins/discourse-local-dates/assets/javascripts/initializers/discourse-local-dates.js
plugins/discourse-local-dates/assets/javascripts/lib/rich-editor-extension.js
plugins/discourse-local-dates/spec/system/rich_editor_extension_spec.rb
plugins/discourse-local-dates/test/javascripts/integration/rich-editor-extension-test.js

Adds `local_date` and `local_date_range` nodes, parsers, and serializers.

FEATURE: add local-dates (plugin) rich editor extension

---

plugins/checklist/assets/javascripts/discourse/initializers/checklist.js
plugins/checklist/assets/javascripts/lib/rich-editor-extension.js
plugins/checklist/assets/stylesheets/checklist.scss
plugins/checklist/test/javascripts/integration/rich-editor-extension-test.js

Adds a `check` node, parser, and serializer, and an input rule to convert when typing `[]`/`[ ]`/`[x]`

FEATURE: add check (plugin) rich editor extension

---

plugins/spoiler-alert/assets/javascripts/initializers/spoiler-alert.js
plugins/spoiler-alert/assets/javascripts/lib/rich-editor-extension.js
plugins/spoiler-alert/assets/stylesheets/discourse_spoiler_alert.scss
plugins/spoiler-alert/test/javascripts/integration/rich-editor-extension-test.js

Adds `spoiler` and `inline_spoiler` nodes, parsers, and serializers, and a click handler to toggle its blurriness in the editor.

FEATURE: add spoiler (plugin) rich editor extension

---

app/assets/javascripts/discourse/tests/helpers/rich-editor-helper.gjs
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/code-block-test.js
plugins/discourse-details/assets/javascripts/initializers/apply-details.js
plugins/discourse-details/assets/javascripts/lib/rich-editor-extension.js
plugins/discourse-details/assets/stylesheets/details.scss
plugins/discourse-details/test/javascripts/integration/prosemirror-editor/details-test.js

Adds `details` and `summary` nodes, parsers, and serializers, and a click handler to toggle the `open` attribute.

FEATURE: add details (plugin) rich editor extension

---

app/assets/javascripts/discourse/app/components/modal/create-account.gjs
app/assets/javascripts/discourse/app/controllers/invites-show.js
app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/lib/user-fields-validation-helper.js

This PR refactors the UserFieldsValidation mixin into a helper class.
* moved this.userFields to a tracked collection of TrackedUserFields stored on the helper class itself
* introduced `validationVisible` property to explicitly control when to display the validation result, we expect the helper to not display validation until form submission in the `SignupController` and `CreateAccount` components. 
* added backward compatibility to the plugin API `addCustomUserFieldValidationCallback` to ensure ex-Core instances of the mixin continues working till we remove them

DEV: replace UserFieldsValidation mixin with helper class

---

app/controllers/list_controller.rb

Some RSS readers require metadata to be present.

FIX: Add metadata to `/hot` RSS feed

---

app/assets/javascripts/admin/addon/components/admin-config-areas/color-palette.gjs
app/assets/javascripts/admin/addon/components/color-palette-editor.gjs
app/assets/javascripts/admin/addon/models/color-scheme-color.js
app/assets/javascripts/admin/addon/models/color-scheme.js
app/assets/javascripts/admin/addon/routes/admin-config-color-palettes-show.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-color-palettes-show.hbs
app/assets/javascripts/discourse/tests/integration/components/color-palette-editor-test.gjs
app/assets/stylesheets/admin/admin_base.scss
app/assets/stylesheets/admin/admin_config_color_palettes.scss
app/controllers/admin/color_schemes_controller.rb
app/controllers/admin/config/color_palettes_controller.rb
app/serializers/color_scheme_color_serializer.rb
app/services/color_scheme_revisor.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml
spec/system/admin_color_palettes_config_area_spec.rb
spec/system/page_objects/components/color_palette_editor.rb
spec/system/page_objects/components/form_kit.rb
spec/system/page_objects/pages/admin_color_palettes_config_area.rb

As part of the theme/color palette overhaul project, we're introducing a new admin page for editing color palettes. The new page is located at `/admin/config/colors/:id`. It's linked from anywhere, but it will be linked in the sidebar as we progress more in the overhaul project.
Screenshot:
Related PRs: https://github.com/discourse/discourse/pull/30893 https://github.com/discourse/discourse/pull/30915 https://github.com/discourse/discourse/pull/31328.
Internal topic: t/148628.

FEATURE: Introduce new color palettes config area

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
lib/auth/result.rb
spec/system/login_spec.rb

A new user joining a community via DiscourseHub and logging in via oauth goes through this process. This would break down for two reasons. 
Reason 1: in some cases, especially on Safari mobile, the redirect in the omniauth callback was happening too early. A new user may not be signed in yet by that point, which means the redirect to `/user-api-key/new` triggers a redirect to `/login` which ends up in a bit of an infinite loop. Not all browsers exhibited this behaviour, but Safari definitely did. 
Reason 2: `/user-api-key/new` is gated via group membership using the `user_api_key_allowed_groups` site setting. By default that is set to include `trust_level_0`, however, auto group assignment wasn't taking place for all user `create` events (only some that go through staged users).

FIX: Ensure auth completes correctly when going via `/user-api-key/new` for new users

---

plugins/chat/assets/javascripts/discourse/components/chat-composer.js

This was causing some confusion and now that we have the chat preference to send with enter or metakey+enter it's even more confusing.
If your setting is send on enter, you need to use shift+enter for a new line, even in codeblocks. If your setting is meta+enter you need to use enter in the codeblock for a new line, meta+enter will send as expected.

DEV: removes code block enter edge case

---

app/assets/javascripts/discourse/app/components/d-editor.js

There's no `textarea` with the rich editor, so being `undefined` it fails with a `TypeError: Cannot read properties of undefined (reading 'id')`.
This has the same behavior with the textarea editor but works much better (positioning closer to the caret) with the rich editor.

FIX: use virtualElementFromTextRange on emoji autocomplete more

---

lib/migration/safe_migrate.rb
spec/fixtures/db/migrate/create_index_concurrently_safe/20230309014016_create_index_concurrently.rb
spec/fixtures/db/migrate/create_index_concurrently_unsafe/20230309014015_create_index_concurrently.rb
spec/lib/migration/safe_migrate_spec.rb

This commit updates `Migration::SafeMigrate` to protect against unsafe
ways of adding a Postgres index concurrently.
Per postgres documentation:
If a problem arises while scanning the table, such as a deadlock or a uniqueness violation in a unique index,
the CREATE INDEX command will fail but leave behind an "invalid" index. This index will be ignored for querying
purposes because it might be incomplete; however it will still consume update overhead. The recommended recovery
method in such cases is to drop the index and try again to perform CREATE INDEX CONCURRENTLY .
Therefore, the simplest way for us to ensure that migrations that create
indexes concurrently are idempotent is to follow postgres'
recommendation of dropping the index first before trying to create the
index concurrently.

DEV: Add protection for migrations that creates index concurrently

---

app/assets/javascripts/discourse/app/static/prosemirror/core/inputrules.js
spec/system/composer/prosemirror_editor_spec.rb

Adds support to typing `---`, `___` or `***` to create a horizontal rule.
Converting when typing `---` is actually written here as an en-dash + `-`, because the typographer replacements extension turns `--` into an en-dash first.
`___` and `***` are only triggered after a whitespace, because they could also mean bold+italic.

FEATURE: add horizontal_rule rich editor input rule

---

app/assets/javascripts/discourse/app/components/composer-editor.hbs
app/assets/javascripts/discourse/app/components/composer/toggle-switch.gjs
app/assets/javascripts/discourse/app/components/d-editor.hbs
spec/system/composer/prosemirror_editor_spec.rb
spec/system/page_objects/components/composer.rb

When you are uploading, it just causes weird problems
when you switch between markdown/rich editors, and it's
not something we really want to support. This commit
disables the Composer::ToggleSwitch while uploading.

FIX: Disable composer editor switch when uploading

---

app/assets/javascripts/discourse/app/components/post-list/item/details.gjs

- The user information passed currently is very limited and in some cases we need more info.

DEV: pass post as an argument for additional member info

---

app/assets/javascripts/discourse/app/components/small-user-list.gjs

We made some changes to the `SmallUserList` widget in #31549. This accidentally broke at least one plugin (`discourse-topic-voting`) which uses it.
This fixes that by defaulting `isVisible` to `true` (old behaviour) when the argument is missing.
**Before:**
**After:**

FIX: Make SmallUserList change backwards compatible

---

plugins/chat/assets/javascripts/discourse/connectors/chat-composer-inline-buttons/emoji-picker.hbs

This was preventing favorites emojis to work correctly as it was using topic context. No tests for now as it's a very specific behavior hard to test with acceptance test and a system spec seems heavy for this.

FIX: ensures chat context is given to emoji picker

---

app/controllers/static_controller.rb
app/views/static/service-worker.js.erb
config/initializers/assets.rb
spec/requests/static_controller_spec.rb

The service worker isn't served via normal asset paths or the CDN. Instead, the ERB was being compiled by sprockets, fished out of the `public/` directory by the static_controller, and then the sprockets-specific stuff like `sourceMappingUrl` was being removed.
Instead, we can put the ERB under `views/static/`, and have it evaluate at runtime. There are only a couple of super-cheap interpolations, plus the route is cached in nginx, so there is no performance concern.
This takes us one step closer to removing sprockets.

DEV: Stop using sprockets to compile service-worker js

---

app/assets/javascripts/custom-proxy/index.js

Previously, I was getting this error in the JS console:
```
livereload.js:2232 Mixed Content: The page at 'https://DOMAIN/' was
loaded over HTTPS, but attempted to connect to the insecure WebSocket
endpoint 'ws://DOMAIN:443/_lr/livereload'. This request has been blocked;
this endpoint must be available over WSS.
````
Adding a `https: true` option seems to fix the problem when running the local server over an https proxy. (It'll be marked as `false` when the protocol isn't https.) 
This isn't just a warning, opening `/tests` is delayed about 10-20 seconds.

DEV: Fix livereload locally on https

---

app/assets/javascripts/discourse/app/models/topic-tracking-state.js
app/assets/javascripts/discourse/tests/unit/models/topic-tracking-state-test.js

When opening the sidebar on a site with thousands of categories, `getSubCategoryIds` is called repeatedly and the nested loops burn a lot of CPU time.
The `Category.descendants` logic is similar in efficiency, but crucially it is cached so it only needs to be calculated once per category. So this change should make a big difference to sidebar performance on sites with lots of categories.

PERF: Optimize topic-tracking-state subcategory calculation

---

app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/app/models/site.js

At the moment, every call to `Category.subcategories` causes an iteration through every single category. For sites with thousands of categories, this is incredibly expensive, and makes things like the category dropdown & sidebar rendering very slow.
To improve things, we can create a map of parent_category => [child categories] in a single iteration, cache it, and then use that when finding subcategories.
The `@computed` decorator ensures that this cache will be recalculated whenever the list of categories changes (e.g. when sideloading new categories in the experimental lazy-loaded-categories mode)

PERF: Optimize `Category.subcategories`

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/image.js
spec/system/composer/prosemirror_editor_spec.rb
spec/system/page_objects/cdp.rb

When copying images from cooked, we have a `data-base62-sha1` attribute instead of a `data-orig-src` that we were expecting.
This PR fixes it and adds a system test.

FIX: copy image from cooked to rich editor

---

app/assets/javascripts/discourse/app/static/prosemirror/lib/text-manipulation.js
spec/system/composer/prosemirror_editor_spec.rb

When a user typed `:emoji` using the autocomplete on the rich editor, but then used the "more" option to open the emoji picker and picked an emoji from there, we were leaving the dangling `:emoji` there and just added the emoji node after it.
We now check if there's a partial emoji exactly at the caret position, and replace it too.

UX: strip partial :emoji when adding emoji from picker

---

plugins/chat/app/serializers/chat/chatable_group_serializer.rb
plugins/chat/spec/serializer/chat/chatable_group_serializer_spec.rb

When creating a DM to a group in chat, we show
a count of users for that group if the number of
users exceeds SiteSetting.chat_max_direct_message_users.
However, we were also counting bot users here, we should
only be counting human users, this led to confusion because
the chat group count was different from the one on
e.g. /g/:group_name

FIX: Incorrect chat DM group user count

---

bin/rspec

Having to type `SELENIUM_HEADLESS=0` everytime is annoying and hard to
remember.

DEV: Support `--headful` to run system test in headful mode in bin/rspec

---

spec/system/email_change_spec.rb

The tests have been flaky on CI so just double the timeouts for now.
We will investigate further if it continues to flake with the doubled
timeout.

FIX: Double wait timeout for mail deliver in email_change_spec.rb

---

app/services/destroy_task.rb
lib/post_destroyer.rb
spec/services/destroy_task_spec.rb

This improves the new rake task to bulk delete posts based on feedback:
- Honour the `can_permanently_delete` site setting.
- Fix a warning about a scope order no being applied due to batching.
- Fix an issue where double delete would result in duplicate user histories.

DEV: Destroy posts rake task enhancements

---

spec/system/page_objects/components/select_kit.rb

The "Tag synonyms when visiting edit tag page allows an admin to create a new tag as synonym when tag does not exist" system
test was flaky with the following error:
```
Failure/Error: super
Capybara::ElementNotFound:
Unable to find css "#add-synonyms.is-expanded"
```
Backtrace points to the following location:
```
...
./spec/system/page_objects/components/select_kit.rb:30:in `expanded_component'
./spec/system/page_objects/components/select_kit.rb:88:in `search'
...
```
What I noticed is that
`PageObjects::Components::SelectKit#expanded_component` has already
found the expanded element when it calls `#expand`. Therefore, there is
no need for us to search for it again.

DEV: Fix flaky system tests due to select kit

---

app/controllers/posts_controller.rb
spec/requests/posts_controller_spec.rb

This was picked up by the `PostsController#replies supports pagination`
requests spec as it was flaky from time to time.
Example of failing run: https://github.com/discourse/discourse/actions/runs/13824916594/job/38677991883

FIX: Ensure ordering is enforced in `PostsController#replies`

---

plugins/checklist/assets/javascripts/lib/rich-editor-extension.js

Not supported on iOS Safari <= 16.3

FIX: replace positive lookbehind on checklist inputrule

---

app/assets/javascripts/discourse/app/controllers/composer.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-form-template-test.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/select-kit/addon/components/composer-actions.js
config/locales/client.en.yml

Now that we support multiple drafts, we can avoid the extra draft check within composer when creating a new topic or reply. For posts, we already autoload the existing draft into composer when the user tries to create a new reply, so there is no longer a need for the abandon draft dialog.
Drafts can still be deleted by closing the composer (using a different dialog) or manually via the User Drafts page.
This change also correctly sets the draft key within composer actions when switching from a post reply to a linked topic.
Internal ref: /t/148325

FIX: remove abandon draft dialog

---

app/assets/javascripts/discourse/app/models/category.js

Since d2409f2964e85a4cb134f119d1bdddce54156175, these calculations are now incredibly cheap, and the caches introduced by `@computed` become the bottleneck. On a site with 5k+ categories, removing these caches results in a 4x render time improvement for their homepage (~2s -> ~0.5s).
Technically, this means these properties will no longer be reactive for places that depend on them using computed property syntax. However, they are still reactive for modern code with autotracking. Given that the set of categories doesn't change after initial load, I think this is acceptable. If we do run into any issues, then we can update the related code to use autotracking.
Note: `@dependentKeyCompat` has similar perf overheads to `@computed`, so that's why I haven't used that for backward-compat.

PERF: Remove caches from Category.subcategories & Category.descendents

---

spec/system/admin_editing_objects_typed_theme_setting_spec.rb
spec/system/page_objects/components/ace_editor.rb
spec/system/page_objects/components/admin_theme_settings_editor.rb

Follow up to dd015af0b8e9528eaabd690299cde12a0fdbe7de

DEV: Rename `fill_input` -> `set_input` in `AceEditor` page object

---

app/assets/javascripts/discourse/app/components/d-navigation.hbs
app/assets/javascripts/discourse/app/components/d-navigation.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js

It's somewhat common for a theme to remove our topic list header: 
One issue with this is that it eliminates the bulk select button. 
Fortunately, we already have a solution for this on mobile... show it in the navigation-controls: 
This PR adds the `showBulkSelectInNavControls` value transformer — so we can optionally allow this on desktop as well: 
This provides an easy way to keep the bulk select controls without the topic list header. 
```js
api.registerValueTransformer("bulk-select-in-nav-controls", () => {
return true;
});
```

DEV: add value transformer to allow bulk select in nav controls

---

app/controllers/user_api_keys_controller.rb

See https://meta.discourse.org/t/user-api-keys-should-use-oaep-padding/354056 for context.

DEV: Add comment to clarify padding used in user-api-key encryption

---

plugins/chat/spec/system/chat_composer_draft_spec.rb

The test has been flaking in CI with the following message:
```
Failure/Error: measurement = Benchmark.measure { example.run }
expected: "draft"
got: ""
(compared using ==)
[Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_chat_composer_draft_when_loading_a_channel_with_a_draft_loads_the_draft_458.png
~~~~~ END JS LOGS ~~~~~
./plugins/chat/spec/system/chat_composer_draft_spec.rb:31:in `block (3 levels) in <main>'
```

DEV: Skip flaky test

---

spec/system/admin_customize_themes_spec.rb

Test is flaking in CI with:
```
Failure/Error: expect(theme_translations_settings_editor.get_input_value).to have_content("Bonjour!")
expected to find text "Bonjour!" in "Hello there!"
[Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_admin_customize_themes_when_editing_theme_translations_should_allow_admin_to_edit_and_save_the_theme_translations_from_other_languages_797.png
(no logs)
~~~~~ END JS LOGS ~~~~~
./spec/system/admin_customize_themes_spec.rb:158:in `block (3 levels) in <main>'
```

DEV: Skip a flaky test

---

app/models/remote_theme.rb
lib/compression/strategy.rb
lib/compression/tar.rb
lib/file_helper.rb
lib/theme_screenshots_handler.rb
spec/lib/theme_screenshots_handler_spec.rb
spec/models/remote_theme_spec.rb

Currently we allow for 2 theme screenshots to be specified,
with a lightweight spec to allow both a light and dark
version of the screenshot. However, we were not storing this
screenshot name anywhere, so we would not be able to use it
for light/dark switching.
This commit fixes that issue, and also does some general refactoring
around theme screenshots, and adds more tests.

FIX: Use theme screenshot names in theme fields

---

app/assets/javascripts/discourse/app/mixins/singleton.js
app/assets/javascripts/discourse/tests/unit/mixins/singleton-test.js

This reverts commit 992bdf173ad8ad25764c0a89132bc35df4c81f12.
This change was causing issues in a [third party plugin](https://meta.discourse.org/t/events-plugin): https://meta.discourse.org/t/events-plugin/69776/869
```
Uncaught Error: Could not find module `discourse/mixins/singleton` imported from `discourse/plugins/discourse-events/discourse/models/provider`
at loader.js:247:1
at h (loader.js:258:1)
at u.findDeps (loader.js:168:1)
at h (loader.js:262:1)
at u.findDeps (loader.js:168:1)
at h (loader.js:262:1)
at requireModule (loader.js:24:1)
at y (app.js:170:18)
at b (app.js:193:19)
at app.js:156:29
at g.start (app.js:167:1)
at HTMLDocument.<anonymous> (start-app.js:5:7)
at discourse-boot.js:13:12
at discourse-boot.js:1:1
```

Revert "DEV: remove singleton mixin (#31823)"

---

app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/common/base/header.scss
app/assets/stylesheets/common/base/tagging.scss
app/assets/stylesheets/common/select-kit/select-kit.scss

This reduces some duplicate color assignment to tags and rolls them up under a common css var
```css
:root {
--tag-text-color: var(--primary-high);
}
.extra-info-wrapper {
--tag-text-color: var(--header_primary-high);
}
```
This also makes the tag separator color consistent with the tag color, by setting it to `--tag-text-color`
Ultimately we have 3 tag text color states (this appeared to be consistent across all tag styles):
* Default: primary-high
* Header: header__primary-high
* Visited topic in the topic list: primary-medium

DEV: normalize tag text color assignment

---

app/controllers/custom_homepage_controller.rb
app/views/custom_homepage/index.erb
app/views/default/custom.html.erb
spec/requests/custom_homepage_controller_spec.rb

Fixes the custom homepage crawler output to include links to the site's top menu. 
This also provides a way to override that content via a plugin. Example usage in a `plugin.rb` file: 
```
register_html_builder("server:custom-homepage-crawler-view") do |c|
"<div>override</div>"
end
```

DEV: Fix custom homepage crawler display and override

---

app/assets/stylesheets/common/base/upload.scss

follow-up to https://github.com/discourse/discourse/commit/6d92165ae77bf78935b9b54a22e517ebc75701f9, rehides this: 
before:
after:

UX: re-hide hidden upload field

---

app/assets/javascripts/discourse/app/components/uppy-image-uploader.gjs
spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/uppy_image_uploader.rb

It is an old bug that preview is not working for newly uploaded images. To fix it, we need to initialize lightbox when image is rendered and not when component.
We have Qunit test when image is already available https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/tests/integration/components/uppy-image-uploader-test.gjs#L28
System test was added to ensure lightbox is working right after image is uploaded.
After fix
https://github.com/user-attachments/assets/1091cd55-b24b-4640-8e8f-a60c3426ff65

FIX: uploader lightbox preview for new images

---

spec/lib/topics_bulk_action_spec.rb
spec/system/dismissing_new_spec.rb

This commit removes a system test that has been flaky in Github's CI and
replaces it with a much simpler unit test that covers the fix introduced
in 48c8ed49d6eda40fbee0d926ea67a81f2851e641
Example of multiple flakes in CI:
1. https://github.com/discourse/discourse/actions/runs/13888933997/job/38857572872
2. https://github.com/discourse/discourse/actions/runs/13793587465/job/38579530997

DEV: Remove flaky system test and replace it with simpler unit test

---

lib/demon/base.rb

This commit updates the log level for certain log messages to the
approporiate level for the severity of the message being logged.

DEV: Correct log level when logging in `Demon::Base`

---

plugins/automation/spec/system/page_objects/discourse_automation/automation.rb

This commit updates `PageObjects::Pages::Automation#update` to check
that the button is not disabled before clicking the button.
Instances of flakiness:
1. https://github.com/discourse/discourse/actions/runs/13864294630/job/38801362996
2. https://github.com/discourse/discourse/actions/runs/13392214535/job/37402368070

DEV: Fix flaky automation system test

---

spec/system/page_objects/components/select_kit.rb

Before this commit,
`PageObjects::Components::SelectKit#expanded_component` might not expand
the component if `is_collapsed?` returns true which can return true if
the method was called before the select-kit component appears on the
screen. When that happens, we end up not expanding the `select-kit`
because we think it is collapsed when in fact the select-kit component
is not rendered yet. This lead to system test failures with errors like:
```
Capybara::ElementNotFound:
Unable to find css "#add-synonyms.is-expanded"
```
This commit updates `PageObjects::Components::SelectKit#is_collapsed?`
to check that the select-kit component has rendered first before
checking if the component is not expanded.
Instances of test flakiness due to this bug:
1. …

DEV: Make expanding select-kit more reliable in system tests

---

script/bulk_import/generic_bulk.rb

This change adds an import step to retroactively grant anniversary badges to users.

DEV: Grant all anniversary badges during imports

---

app/assets/javascripts/discourse/app/components/group-manage-save-button.gjs
app/assets/javascripts/discourse/app/controllers/groups-new.js
app/assets/javascripts/discourse/app/lib/constants.js
app/assets/javascripts/discourse/app/services/group-automatic-members-dialog.js
app/assets/javascripts/discourse/tests/acceptance/group-manage-email-settings-test.js
app/controllers/admin/groups_controller.rb
config/locales/client.en.yml
config/locales/server.en.yml
lib/tasks/javascript.rake
spec/requests/admin/groups_controller_spec.rb
spec/system/groups/group_spec.rb
spec/system/page_objects/pages/group_form.rb
spec/system/page_objects/pages/group_index.rb

When creating or editing a group, we are meant to show a dialog telling the admin how many members will be automatically added. This was broken:
Extract the dialog functionality into a service and use that in the create- and update pages.
When looking this number up, the operation needs to do `domains x users` RegEx comparisons in the database. This can be very slow for large number of domains and users. So this change also sets an upper limit for how many domains can be looked up using that endpoint to avoid DoS situations. If the user adds more than that, we show a generic dialog without a count instead.
I also changed the alert to a confirm, giving the admin a way out if they are doing something they didn't intend to.

FIX: Amend broken group automatic member dialog

---

config/locales/server.en.yml

The string introduced in https://github.com/discourse/discourse/pull/31854 included a count but was not pluralized. Even though the singular form may not be used in English, proper pluralization is necessary for other languages. Some languages have different plural forms depending on the number, so explicitly defining pluralization ensures accurate translations.

DEV: Pluralize email domain count string

---

app/assets/javascripts/admin/addon/components/color-palette-editor.gjs
app/assets/javascripts/discourse/tests/integration/components/color-palette-editor-test.gjs
app/assets/stylesheets/admin/color-palette-editor.scss
config/locales/client.en.yml

Follow-up to https://github.com/discourse/discourse/pull/31742
Adding a text input field to type in or paste color values can be useful when creating/editing a color palette with specific colors.
Screenshot:

FEATURE: Allow typing/pasting colors in palette editor

---

app/helpers/application_helper.rb
app/models/site_setting.rb
lib/site_settings/deprecated_settings.rb
spec/helpers/application_helper_spec.rb
spec/jobs/clean_up_uploads_spec.rb

In this PR x_summary_large_image was introduced but now updated in all places.
Also `min_first_post_typing_time` deprecation should not be removed.

FIX: twitter_summary_large_image is renamed to x

---

app/assets/javascripts/discourse/app/services/group-automatic-members-dialog.js
spec/system/groups/group_spec.rb
spec/system/page_objects/pages/group.rb

The change made in #31854 introduced a regression when editing groups, preventing saving when no auto membership e-mail domains are entered.
This change fixes that and adds a system test.

FIX: Updating a group without e-mail domains

---

app/assets/javascripts/admin/addon/templates/config-customize.hbs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
config/locales/client.en.yml

Moves the Themes & components I18n text to use the
admin > config structure, so the description shows
up properly in admin search

UX: Themes & components I18n adjustments

---

app/assets/stylesheets/common/components/d-page-header.scss

We have this rule in
https://meta.discourse.org/t/formatting-text-in-discourse-documentation-and-uis/324637:
> Do not use a period for the following:
>
> Tooltips, image captions, or other UI elements with only one sentence
However, this looks strange on some admin pages because we also show
a "Learn more..." link after the header description, which kind of
runs on into the link.
This commit adds a separator after the link to address this issue.
**Before**
**After**

UX: Add separator for "Learn more..." on admin pages

---

plugins/chat/spec/system/kick_user_from_channel_spec.rb

This commit removes a flaky system test without replacement given that
the test isn't really testing something in the critical path or
something that happens often.
Example of flakiness:
1. https://github.com/discourse/discourse/actions/runs/13901410315/job/38893877234
2. https://github.com/discourse/discourse/actions/runs/12362090310/job/34500684809

DEV: Remove flaky system test

---

app/assets/javascripts/discourse/app/components/modal/share-topic.gjs

Use of the buffer API within this component was removed back in https://github.com/discourse/discourse/pull/23940.

DEV: remove unnecessary use of buffered mixin in share-topic modal

---

app/models/group.rb
config/locales/server.en.yml
config/site_settings.yml
spec/models/group_spec.rb

We currently limit the number of characters in the bar-separated list of auto-membership e-mail domains. We want to make this configurable through site settings.
After this change, we limit the length of each individual domain, and enable the number of domains to be configured through a hidden site setting.
The original limit is there to prevent DoS, since a `TEXT` column can take up to 1Gb. With this new limit we're still at a maximum of around 10kb.

DEV: Make group auto e-mail domain limit configurable

---

lib/post_destroyer.rb
spec/lib/post_destroyer_spec.rb

When hard deleting a first post by passing `force_destroy: true` as an option to `PostDestroyer`, the post/topic is correctly deleted, and the staff record is created, but the app then errors out.
This only happens on sites with a `topic_destroyed` webhook setup.
After deleting the record, we pass the topic's ID to `TopicView`, which then raises an error because it can not load it from the DB.
`TopicView` supports being initialized with either an ID or an already instantiated record. Since we still have the record in memory after deleting, we can pass that to `TopicView`.

FIX: Don't error out after destroying first post with webhook configured

---

lib/demon/base.rb
lib/demon/sidekiq.rb

This commit changes the way Sidekiq is restarted when memory limit is exceeded. The HUP signal was replaced with TERM, as mentioned in the official documentation. The stopping timeout has also been increased to 30 seconds to account for the Sidekiq timeout (25 seconds) and another for it shutdown cleanly (5 more seconds).
See https://github.com/sidekiq/sidekiq/wiki/Deployment.

FIX: Safely restart Sidekiq when mem usage is high

---

app/assets/javascripts/discourse/app/controllers/confirm-new-email.js
app/assets/javascripts/discourse/app/controllers/confirm-old-email.js
spec/system/email_change_spec.rb

Both tests being unskipped here failed previosly with the following
error:
```
Failure/Error: expect(page).to have_current_path("/u/#{user.username}/preferences/account")
expected "/u/confirm-new-email/f42a416fcbca40d66788d65a8837ad49" to equal "/u/bruce306/preferences/account"
./spec/system/email_change_spec.rb:49:in `block (2 levels) in <main>'
```
The error indicates that the transition was not successful and I
suspect that it may be due to the use of the `/my` route prefix which
is just a nice to have and not necessary.

DEV: Attempt to fix flaky system tests around email confirmation

---

app/assets/javascripts/admin/addon/components/admin-config-areas/api-keys-new.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/collection.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/field-data.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/object.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/collection-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/object-test.gjs
app/assets/stylesheets/admin/api.scss
app/assets/stylesheets/common/form-kit/_collection.scss

Before this commit form-kit couldn't represent this shape of data: `[1,2,3]`, it could only represent: `[{value: 1}, {value: 2}]`.
The above data can now be expressed with this form:
```gjs
<Form @data={{hash foo=(array 1 2 3)}} as |form|>
<form.Collection @name="foo" as |collection|>
<collection.Field @title="time" as |field|>
<field.Input @type="number" />
</collection.Field>
</form.Collection>
</Form>
```

DEV: adds support for primitive collections in form-kit

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/link.js
spec/system/composer/prosemirror_editor_spec.rb

Fixes an incorrect logic on `transformPasted` that was causing a `TypeError: Cannot read properties of null (reading 'marks')` when only part of a paragraph was selected.
Adds tests

FIX: paste url on rich editor with partial paragraph selected

---

app/assets/javascripts/discourse/app/templates/discovery/list.gjs
app/models/category_list.rb
spec/models/category_list_spec.rb

Commit f1700ca58929bcbfad23565861d1d3084ae1b3f8 ensures that categories are loaded lazily, in pages, if the number of visible categories is over
1000. This affected the list of subcategories on the category page too.
The logic has been changed to only paginate if the number of categories that would have been returned is grater than 1000. For example, if there is a parent category filter, pagination will only be enforced if the number of subcategories is over 1000.

FIX: Force pagination only if more than 1000 subcategories

---

app/models/upload.rb
db/migrate/20250313000000_increase_uploads_origin_column_length.rb
lib/upload_creator.rb

The current limit is too small for the way Discourse currently stores a pre-signed S3 URL for each upload in the form of:
```
https://{bucketname}.s3.dualstack.{region}.amazonaws.com/original/1X/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2FYYYYMMDD%2F{region}%2Fs3%2Faws4_request&X-Amz-Date=YYYYMMDDTHHMMSSZ&X-Amz-Expires=xxxxxx&X-Amz-SignedHeaders=host&X-Amz-Security-Token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX …
```

FIX: Increase uploads.origin column length to 2048 to accommodate longer S3 pre-signed URLs for user uploads.

---

app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/components/header/icons.gjs
app/assets/javascripts/discourse/app/components/welcome-banner.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/integration/components/header-contents-test.gjs
app/assets/javascripts/discourse/tests/integration/components/header-icons-test.gjs
app/assets/javascripts/discourse/tests/integration/components/welcome-banner-test.gjs

We want to give some themes more control over
the default experience in core. To this end, this
commit adds value transformers for these
site settings:
* enable_welcome_banner
* search_experience
This way, themes can give a different value to
what has been set in core.
This can be potentially confusing, a follow up PR
may refactor this a bit so there is a more direct
correlation between the setting and the transformer
so we could show a warning in the site setting page
for example.

FIX: Add value transformers for welcome banner and search

---

app/assets/javascripts/discourse/app/lib/utilities.js

Ideally we would add support for color spaces like okclh to the app, or have some method for converting them to rgb automatically. But for now, this will stop the app crashing completely.

FIX: Stop non-rgb header background colors crashing DiscourseHub

---

app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/header/header-search.gjs
app/assets/javascripts/discourse/app/components/search-menu.gjs
app/assets/javascripts/discourse/app/components/search-menu/search-term.gjs
app/assets/javascripts/discourse/app/components/welcome-banner.gjs
app/assets/javascripts/discourse/app/services/search.js
app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/common/components/welcome-banner.scss
app/assets/stylesheets/desktop/components/header-search.scss
app/assets/stylesheets/mobile/components/welcome-banner.scss
spec/support/system_helpers.rb
spec/system/header_spec.rb
spec/system/page_objects/pages/header.rb
spec/system/page_objects/pages/search.rb
spec/system/search_shortcut_variation_spec.rb
spec/system/welcome_banner_spec.rb

Now we have the search input showing in a few
different configurations:
* Welcome banner
* Header field
* Header icon
And we can get to the search with both `/` and
`Ctrl+F` shortcuts. These configurations can
be used together, and we need to focus on the right
search input at the right time.
This commit fixes the shortcuts not working
or showing the wrong thing in some cases,
and adds a comprehensive system spec for all
the variants.

UX: Fix various search shortcut UX issues

---

spec/rails_helper.rb
spec/requests/application_controller_spec.rb
spec/requests/default_headers_spec.rb

Setting Rails.logger after the application has been initialized does not
seem to be safe anymore and can lead to flaky tests. This commit
disallows the reassignment of `Rails.logger` going forward and updates
the affected test.
Reassigning `Rails.logger` from within RSpec tests is causing tests which uses `Rails.logger.broadcast_to(FakeLogger.new)` to flake. Example: https://github.com/discourse/discourse/actions/runs/13951116847/job/39050616967
```
1) invalid requests handles NotFound with invalid json body
Failure/Error: expect(fake_logger.errors).to have_attributes(size: 1)
expected [] to have attributes {:size => 1} but had attributes {:size => 0}
Diff:
@@ -1 +1 @@
-:size => 1,
+:size => 0,
```

DEV: Disallow the use of `Rails.logger=` in RSpec tests

---

app/assets/javascripts/discourse/app/controllers/second-factor-auth.js
app/assets/javascripts/discourse/app/templates/second-factor-auth.gjs
spec/system/email_change_spec.rb

This commit updates the 2FA token submission page to disable the submit
button when the 2FA token is not valid and to also set the submit button
to be in the loading state after the submit button has been clicked.
The UX issues were discovered while I was investigating a flaky test
which has been unskipped in this commit as well. I am not sure if  this
will completely resolve the flakiness but we have to unskip it to know
if it continues to be flaky.

UX: Improve UX of 2FA token submission page

---

app/assets/javascripts/dialog-holder/addon/components/dialog-holder.gjs
app/assets/javascripts/dialog-holder/addon/services/dialog.js
app/assets/javascripts/discourse/tests/integration/components/dialog-holder-test.gjs

Accessing a component-rendered DOM element from a service is not ideal, and can lead to timing issues. We've attempted to work around this using `afterRender`, but it's still not ideal.
This commit moves the `A11YDialog` setup into a modifier. Now the service only stores state, and the component renders things based on that state. This is much more in line with Ember norms, and should be much more robust.
Test adjustments are because the dialog element is now only rendered on-demand, rather than being present in the DOM all the time. This brings dialog inline with our Modal system.

DEV: Move dialog DOM handling from service to component

---

app/assets/javascripts/admin/addon/components/site-setting.js
app/assets/javascripts/admin/addon/controllers/admin-customize-robots-txt.js
app/assets/javascripts/admin/addon/controllers/admin-email-templates-edit.js
app/assets/javascripts/admin/addon/controllers/admin-site-text-edit.js
app/assets/javascripts/admin/addon/mixins/setting-component.js
app/assets/javascripts/discourse/app/controllers/topic.js

Refactors the use of the buffered-content mixin to native getters on the dependent classes. 
This mixin previously provided a cached wrapper around an instance of BufferedProxy and added 2 convenience methods aliasing BufferedProxy methods.
* Use of the`@cached` decorator to maintain parity with the previous version of `this.buffered` to make sure we only refresh the buffered proxy if the dependent property changes. 
* _Not entirely sure if @cached + @dependentCompat is more performant than just using `@computed`_
* Use of the`@dependentCompat` decorator to ensure backwards compatibility of the getter with computed properties - we will leave refactoring of those somewhere down the road as that would greatly increase the scope of this PR
* `applyChanges` / `discardChanges` are the same as …

DEV: refactor usage of buffered-content mixin

---

app/assets/javascripts/discourse/app/controllers/user-activity-bookmarks.js
spec/system/page_objects/pages/user_activity_bookmarks.rb
spec/system/user_activity_bookmarks_spec.rb

Meta: https://meta.discourse.org/t/cant-erase-the-bookmark-search-input/357861/4
> When we fill in the bookmark search input and send the request, then we can’t delete the input’s content.
After removing the last character, the `searchTerm` getter is called. At this point, `_searchTerm` is empty.
However,  `this._searchTerm || this.q` will treat the empty string as _falsy_, and the `q` value is displayed instead.
It makes it impossible to clear the input.
To fix this, we check specifically on the initial state of `_searchTerm,` which is _undefined_, to include an empty string as a valid value.
Note: because of `@computed`, the issue is not triggered when the content is selected and deleted.

FIX: Bookmark search input can't be cleared with backspace with `?q=` present

---

spec/system/email_change_spec.rb

This commit removes an assertion for the redirect after 2FA
authentication is success message because the message is flashed briefly
before a route transition happens. A proper fix would require us to
redesign when/how the flash message which we can address in the future.

DEV: Remove assertion causing test to flake.

---

plugins/chat/app/services/chat/add_users_to_channel.rb
plugins/chat/assets/javascripts/discourse/components/chat/routes/channel-info-members.gjs
plugins/chat/spec/requests/chat/api/channels_memberships_controller_spec.rb
plugins/chat/spec/services/chat/add_users_to_channel_spec.rb
plugins/chat/spec/system/channel_members_page_spec.rb
plugins/chat/spec/system/page_objects/chat/chat.rb

This change allows more flexibility when starting a 1-1 direct message with another user. If there are no messages in the new DM channel then we should still allow them to add additional users.
Internal ref: /t/148525

FEATURE: allow adding members to new 1-1 DM channels

---

plugins/chat/app/validators/chat/allow_chat_in_anonymous_mode_validator.rb
plugins/chat/config/locales/server.en.yml
plugins/chat/config/settings.yml
plugins/chat/lib/chat/guardian_extensions.rb
plugins/chat/spec/lib/chat/guardian_extensions_spec.rb
plugins/chat/spec/validators/allow_chat_in_anonymous_mode_validator_spec.rb

Currently, anonymous/shadow users go through the same permission checks for chat as normal users do. This means that if a site has chat enabled for all users, anonymous users also get access to chat. This may be undesirable for some communities, so we're adding a new site setting `allow_chat_in_anonymous_mode` to block access to chat for anonymous users.
Internal topic: t/148088.

FEATURE: Add setting to prevent anonymous users from using chat

---

app/assets/javascripts/discourse/app/routes/user-activity-drafts.js
app/assets/javascripts/discourse/tests/acceptance/user-activity-drafts-test.js

When logged in and visiting another user's drafts page, we should redirect back to the current user drafts page.
For non auth users, we can redirect back to the forum `/latest` page.
Internal ref: /t/150250

FIX: redirect user activity drafts route

---

app/assets/javascripts/discourse/app/components/modal/history/revisions.gjs
app/assets/stylesheets/common/base/history.scss

follow-up to b4f9626984667133a2a1f656109d154214dbe47a
the previous commit removed an intentionally empty wrapper, which aligned the diff when there's only an addition
Before (tag aligned to the left, associated with the wrong version):
After (tag aligned right, associated with the new revision):

FIX: tag revisions need an empty wrapper

---

app/assets/javascripts/discourse/app/lib/lazy-load-images.js

Safari does not reload lazy images smoothly, which causes a lot of flickering in the composer preview while typing.

PERF: Skip lazy-loading images in composer preview

---

lib/site_icon_manager.rb
spec/lib/site_icon_manager_spec.rb

Currently, the light version of mobile logo falls back to the desktop version if the mobile version isn't set. It makes sense to have the same fallback rule for the dark version as well, i.e. if there's no dark mobile logo, use the dark desktop logo.
Internal topic: t/150316.

FIX: Make dark mobile logo fallback to dark desktop logo

---

app/assets/javascripts/admin/addon/templates/dashboard.hbs

This PR removes the span wrapper from the admin dashboard plugin outlet.

DEV: Remove span tag from outlet

---

app/assets/stylesheets/common/base/search-menu.scss

The search result panel didn't have the new-ish border-radius variable attached yet.

UX: Add missing border-radius variable

---

app/models/problem_check.rb
app/services/problem_check/group_email_credentials.rb
app/services/problem_check/problem.rb
spec/services/problem_check/group_email_credentials_spec.rb

We didn't have support in the `#problem` constructor for multiple targets, forcing developers to manually construct a `Problem` instance. This involves a lot of details and is error prone.
This PR supports passing an optional `target` argument to the constructor. This will be passed on to the `translation_data` method to generate the correct message as well.

DEV: Support target in problem check problem constructor

---

app/controllers/admin/email_templates_controller.rb
app/mailers/user_notifications.rb
app/models/reviewable_flagged_post.rb
config/locales/server.en.yml
spec/models/reviewable_flagged_post_spec.rb

When a user post is flag as spam and the moderator deletes the user, we should send email to the affected user.

FEATURE: send email to deleted user

---

lib/plugin/instance.rb
lib/topics_filter.rb
spec/lib/topics_filter_spec.rb

This adds the `guardian` argument to the `TopicsFilter` plugin callback so that plugin can guard their topics filter based on the current user.

DEV: Add `guardian` argument to `TopicsFilter` plugin callback

---

lib/second_factor/actions/discourse_connect_provider.rb
spec/lib/second_factor/actions/discourse_connect_provider_spec.rb
spec/requests/session_controller_spec.rb

The URLs returned by DiscourseConnect for the user's avatar, profile and card backgrounds were not always correctly handling CDN.
This make use of the `GlobalPath.full_cdn_url` helper method which has been battle-tested.
Ref - https://meta.discourse.org/t/-/356599

FIX: avatar, profile & card backgrounds url in DiscourseConnect

---

app/assets/stylesheets/common/base/new-user.scss
app/assets/stylesheets/common/components/horizontal-overflow-nav.scss

Concerns this little fading scroll affordance in the horizontal overflow nav: 
The parent container of the user nav has an optional `--d-content-background` variable applied, and adding this for the nav means that if a theme author uses `--d-content-background` the nav will match automatically. When `--d-content-background` is not set, we fall back to `--secondary` which is the default background. 
I also realized that we don't need RGB values here since we're simply fading from a solid color to transparent.

UX: improve nav fade css

---

app/assets/stylesheets/common/base/personal-message.scss

This applies the pm border radius (optional theme variable) to the pm topic map as well 
before:
after:

DEV: apply pm border radius to topic map

---

app/assets/stylesheets/common/base/modal.scss

These are *technically* buttons, but are much larger and have multi-line content, so if you apply a border-radius via `--d-button-border-radius` that tries to make rounded buttons... it doesn't work great here. 
A case where normal buttons are fine (6rem radius) 
but these big buttons have too much content to pull it off well, the same border radius is too extreme
the border radius variable we have for more general content areas (`--d-border-radius`) generally doesn't work with a fully round radius, so it should work better here most of the time:

UX: adjust border radius for reply-where buttons

---

app/assets/stylesheets/admin/customize.scss

Meta: https://meta.discourse.org/t/issue-with-custom-css-save-button-on-smaller-screens/358505
With the editor maximized, this PR adjusts the height by considering the new info banner (#31561) and the navbar with `Show advanced` enabled (even without banner, the height needed adjustments).
The info banner is forced to scroll to contain the height, especially on mobile.
Before:
After:

UX: Adjust code editor height when maximized

---

app/assets/javascripts/admin/addon/components/admin-config-areas/color-palette.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/submit.gjs
app/controllers/stylesheets_controller.rb
app/helpers/application_helper.rb
lib/stylesheet/manager.rb
spec/system/admin_color_palettes_config_area_spec.rb

When editing a color palette via the new page introduced in https://github.com/discourse/discourse/pull/31742, it should apply the color changes for the admin making the change automatically upon save.
Internal topic: t/148628/12.

UX: Apply changes live when editing currently active palette

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/bullet-list.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/ordered-list.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/register-default.js
spec/system/composer/prosemirror_editor_spec.rb

Tight lists are lists that look like this:
* Item 1
* Item 2
* Item 3
Loose lists look like this:
* Item 1
* Item 2
* Item 3
There is a place for the latter, but the former is more
common default behaviour for writing apps and widgets, so
we are overriding the prosemirror default to use tight lists.
Eventually we will have a shortcut or other special behaviour
to switch between the list styles.

FEATURE: Tight lists by default on rich composer

---

app/assets/javascripts/discourse/app/controllers/second-factor-auth.js
spec/system/email_change_spec.rb

This commit unskips 3 flaky system tests and gives up on asserting that
redirecting is done correctly. This is because we have invested
considerable effort into this and cannot figure it out. The redirect is
tested by the client side anyway so there is still some test coverage.

DEV: Unksip flaky changing email system tests

---

app/controllers/users/omniauth_callbacks_controller.rb

- This change separates the logic that handles 2fa flow, from the one that deals with the user after it is authenticated.

DEV: Split 2fa logic from account activation

---

app/assets/javascripts/discourse/app/form-kit/components/fk/field-data.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs

This allows more flexibility for custom behaviours.
Example usage:
```gjs
@action
onSet(value, { set, name }) {
set(name + ".0.baz", value * 2)
}
<form.Object @name="something" as |object|>
<object.Field @name="foo" @title="Foo" @onSet={{onSet}} as |field|>
<field.Input />
</object.Field>
</form.Object>
```

DEV: exposes parentName and name in onSet

---

app/assets/javascripts/discourse/app/templates/tags/index.gjs

This `.list-controls` wrapper on the tags index has no specific styles applied, and can easily pick up styles of the actual `.list-controls` container on topic lists when the class is used in themes... so it's more harmful than helpful (it's also not a list?).
Before:
After (no visual changes):

DEV: remove list-controls wrapper on tags index

---

spec/support/system_helpers.rb
spec/system/page_objects/pages/search.rb
spec/system/search_spec.rb

After clicking on the search icon, we should ensure that the
`.search-container` has been rendered before moving on. Also update assertions to properly rely on Capybara's autowait.
Example of flaky tests: https://github.com/discourse/discourse/actions/runs/14057379759/job/39359791607

DEV: Fix flaky search system tests

---

lib/version.rb

Version bumps for main: v3.5.0.beta2, v3.5.0.beta3-dev

---

lib/version.rb

Version bump for stable: v3.4.2

---

app/assets/javascripts/discourse/app/components/dialog-messages/confirm-session.gjs
spec/system/forgot_password_spec.rb
spec/system/page_objects/pages/user_preferences_security.rb

This commit adds a loading state to the confirm button in
`confirm-session` dialog.
This also unskips the flaky system tests in
`spec/system/forgot_password_spec.rb` as this change will allow us to
gather more information about why the test is flaky. The screenshots
which we have gathered when the test flakes does not allow us to know if
the button has been clicked or not before the test times out.

UX: Add loading state to button when confirming password

---

plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js

With header search we toggle the search icon when scrolling on topics, which can feel visually jarring when the search icon is in the middle.
Switching the position of the chat icon in the header reduces the impact of this.
Before:
After:
Internal ref: /t/150026/46

UX: reposition chat header icon

---

app/controllers/admin/config/about_controller.rb
app/controllers/admin/site_settings_controller.rb
app/services/site_setting/policy/settings_are_not_deprecated.rb
app/services/site_setting/update.rb
config/locales/server.en.yml
spec/requests/admin/site_settings_controller_spec.rb
spec/services/site_setting/update_spec.rb

This PR moves the logic that checks if a site setting we're trying to update has been deprecated from one of the controllers into a policy of the `SiteSetting::Update` service.
It also gives us the opportunity to shift the error message into a locale file.

DEV: Move setting deprecation check to SiteSetting::Update service

---

app/models/theme.rb
app/models/theme_field.rb
lib/plugin/instance.rb
lib/stylesheet/compiler.rb
lib/stylesheet/importer.rb
lib/stylesheet/manager/builder.rb
lib/theme_store/zip_exporter.rb
spec/lib/stylesheet/compiler_spec.rb
spec/lib/stylesheet/importer_spec.rb
spec/lib/stylesheet/manager_spec.rb
spec/models/theme_field_spec.rb

Previously we would prepend extra content to developer-authored files, which means adding `@use` in some files would throw an error because `@use` must be at the top of any compiled file.
Instead, we can ensure any developer-authored files are on the load path, and then `@import` them into the synthetic entrypoint.
Plugin color_definitions stylesheets are an edge case here, and will need to be handled separately (or... wait until we move to native css relative-color syntax, then we can drop color-definition stylesheets altogether)

DEV: Allow stylesheet entrypoints to use `@use`

---

lib/stylesheet/compiler.rb
lib/stylesheet/manager.rb
spec/fixtures/plugins/scss_plugin/assets/stylesheets/simple.css
spec/fixtures/plugins/scss_plugin/plugin.rb
spec/lib/stylesheet/compiler_spec.rb

b1924c35 switched our compiler to use `@import` internally for scss entrypoints. This logic also applied to `.css` files, but unfortunately sass doesn't do anything with `@import` of CSS files, so they'll be left intact all the way to the browser. Continue using the old concatenation approach for them in the compiler.
Followup to b1924c352487ab2c85ae50af45c5b3e098589014

FIX: Do not `@import` `.css` assets for plugins

---

plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js

The chat icon was repositioned in #31951 but we should also account for mobile, where it should appear before the hamburger icon.
Mobile/hub:
Mobile/hub:
Desktop:

FIX: update chat icon position on mobile

---

app/assets/stylesheets/common/base/compose.scss

Follow-up to bbea7c3b11054b8e7faeee85a0336ecc45b84890
This behavior should only be applied to mobile view, otherwise there are some scenarios (Android tablets) where the composer toolbar will become inaccessible.

UX: only check for toolbar-visible class in mobileView

---

app/assets/stylesheets/common/components/hashtag.scss

Improves alignment of emojis within hashtags.
Emojis:
Emojis:

UX: improve hashtag emoji alignment

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/javascripts/discourse/app/components/topic-list/item/topic-cell.gjs

This was accidentally reverted as part of the rebasing/merging of the gjs conversions in b29e0b6e1b6001890ce92f96448258550f80132b

FIX: Reapply 94ee3554

---

app/assets/javascripts/admin/addon/components/site-setting.gjs
app/assets/javascripts/admin/addon/mixins/setting-component.js

This change disables the save and undo buttons for site settings while the setting is being saved. This gives some visual indication that saving is underway, and prevents unnecessarily sending more than one request (which will be no-ops anyway.)
Here's a screen recording with a heavily throttled response time for demonstration purposes:

DEV: Disable site setting save/discard buttons while saving

---

spec/rails_helper.rb

When a Capybara helper times out after hitting `Capybara.default_max_wait_time`, we will now
dump the puma server threads backtraces. This information will help us
diagnose test failures due to requests not completing within `Capybara.default_max_wait_time`.
Example test failure output:
```
Failures:
1) User resetting password when desktop when user has multi-factor authentication configured when user has TOTP, security key and backup codes configured should allow a user to toggle from security key to TOTP and between TOTP and backup codes
Failure/Error: expect(page).to have_current_path("/u/#{user.username}/preferences/second-factor")
expected `#<Capybara::Session>.has_current_path?("/u/john/preferences/second-factor")` to be truthy, got false
[Screenshot Image]: …
```

DEV: Print puma threads backtraces when Capybara's helpers time out

---

app/assets/stylesheets/common/components/badges.scss
app/assets/stylesheets/common/components/hashtag.scss

Small alignment and sizing improvements for emojis/icons added to categories.
We are also fixing the private category locked icon to retain the grey color.
Private category lock color:
Emoji sizing was too big:
Private category lock color:
Emoji sizing now matches squares:
And here too:
And within the header:

UX: emoji styling adjustments

---

app/assets/stylesheets/common/base/header.scss

This is causing misalignment with displayed metadata such as category, tags, assigned,… We don't remember why it was added in the first place.

UX: removing baseline alignment from topic title wrapper

---

app/assets/javascripts/discourse/app/components/topic-list/item/topic-cell.gjs

DEV: Remove clearfix class from topic title link in topic lists

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/mobile/topic-list.scss

* Prevents tag separators (commas by default) from wrapping separately by using absolute positioning so they don't impact the width (thus a comma can't wrap on its own, because a tag can't influence the width) 
* Removes some whitespace creating extra space between categories and tags (to better match desktop) 
* Removes a redundant `flex-wrap: wrap` as `.discourse-tags` already carries this 
* Improves vertical alignment of commas (they were too high on mobile, which is avoided on desktop with baseline alignment in flex) 
* Fixes an issue where tag and separator color could be mismatched because of a too-broad color being applied to all links 
Before:
After:

UX: improve mobile topic list tag layout

---

app/assets/javascripts/admin/addon/templates/dashboard.gjs

This adds a title to the admin dashboard to match other admin pages.
Adds a description to the admin dashboard.
Adds a plugin outlet after the header
BEFORE:
AFTER:

UX: Admin Dashboard title

---

spec/rails_helper.rb
spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb

This is to provide diagnostic information for some flaky system tests
which we are currently investigating. The previous attempt in
6f92f42eb83fea61b2712aaaefcc124e4939365d only dumped threads that
contains the `puma` gem in the backtrace but that is not enough. Since I
am now printing all thread backtraces, I added the `dump_threads_on_failure` metadata
which will be used to determine if all the thread backtraces should be
printed out in the spec's failure output.

DEV: Dump all threads for some flaky system tests

---

plugins/chat/spec/system/chat_channel_spec.rb
plugins/chat/spec/system/page_objects/chat_drawer/chat_drawer.rb
spec/support/system_helpers.rb
spec/system/page_objects/components/logo.rb
spec/system/search_spec.rb

A system test in `system/search_spec.rb` was failing with the following
error frequently on CI:
```
Failure/Error: expect(search_page).to have_heading_text("Search")
expected `#<PageObjects::Pages::Search:0x00007fb9fcd3f028>.has_heading_text?("Search")` to be truthy, got false
[Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_search_when_using_full_page_search_on_mobile_works_and_clears_search_page_state_912.png
(no logs)
~~~~~ END JS LOGS ~~~~~
./spec/system/search_spec.rb:42:in `block (3 levels) in <main>'
./spec/rails_helper.rb:619:in `block (3 levels) in <top (required)>'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/benchmark-0.4.0/lib/benchmark.rb:304:in `measure'
./spec/rails_helper.rb:619:in `block (2 levels) in …
```

DEV: Attempt to fix flaky search system test

---

app/assets/javascripts/admin/addon/mixins/setting-component.js
app/assets/javascripts/discourse/app/lib/constants.js
app/controllers/admin/config/about_controller.rb
app/controllers/admin/config/branding_controller.rb
app/controllers/admin/site_settings_controller.rb
app/models/site_setting.rb
app/services/site_setting/policy/settings_are_configurable.rb
app/services/site_setting/policy/settings_are_not_deprecated.rb
app/services/site_setting/policy/settings_are_unshadowed_globally.rb
app/services/site_setting/policy/settings_are_visible.rb
app/services/site_setting/policy/values_are_valid.rb
app/services/site_setting/update.rb
lib/tasks/javascript.rake
spec/services/site_setting/update_spec.rb

Some site settings support backfilling if the user specified it. This works fine for singular site settings sent to the `SiteSettingsController#update` endpoint, but with bulk save we need to support this for a list of settings as well.
This change alters the params format for `SiteSetting::Update`.
**Old format:**
```rb
{ setting_name => setting_value, ... }
```
This does not support additional config options, such as the backfill opt-in.
**New format:**
```rb
[{ setting_name:, value:, backfill: }, ...]
```
It also moves the backfill logic into the service.
To structure the service internals, a local `Setting` struct is used, which can carry the extra flag as well as the resulting changeset, which can then be used to extract the old and new value in the backfill step.

DEV: Move backfill into SiteSetting::Update service

---

plugins/chat/spec/system/chat_new_message_spec.rb

We are not waiting for asynchronous operations to complete before executing our assertions.
Example test failure: https://github.com/discourse/discourse/actions/runs/14100970402/job/39496976787
```
Failure/Error: measurement = Benchmark.measure { example.run }
expected `Chat::Channel.count` to have changed by 1, but was changed by 0
[Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_chat_new_message_from_params_with_multiple_users_creates_a_dm_channel_when_none_exists_626.png
~~~~~ END JS LOGS ~~~~~
./plugins/chat/spec/system/chat_new_message_spec.rb:57:in `block (3 levels) in <main>'
./spec/rails_helper.rb:619:in `block (3 levels) in <top (required)>'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/benchmark-0.4.0/lib/benchmar …
```

DEV: Fix a flaky chat system test

---

spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb

I'm not sure what is causing the tests to be flaky so I need more
information to determine where the problem is. For now, I'm doubling the
wait time to rule out any server side problem.

DEV: Double default capybara wait time for certain flaky tests

---

spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb

The `using_wait_time` DSL did not work when used in the `around` context as the Capybara's session has not been initialized.
Follow-up to afde7cc1727a751e4d87be2ceee17f2d82edf89c

DEV: Double default capybara wait time for certain flaky tests take 2

---

config/site_settings.yml
lib/final_destination.rb
lib/onebox/engine/amazon_onebox.rb
lib/onebox/engine/html.rb
lib/onebox/helpers.rb
lib/oneboxer.rb
spec/lib/oneboxer_spec.rb

This is a hidden site setting which has never been publicized, and is not recommended for use. If we decide to add a feature like this in future as a visible site setting, it would need many more safeguards to prevent misuse.

DEV: Drop 'cache_onebox_response_body' feature

---

lib/email/styles.rb
spec/lib/email/styles_spec.rb

7d587937 introduced css property deduplication in emails to workaround bugs in some email clients. However, this didn't account for admin-supplied customizations which were overriding core rules using `!important`. This commit ensures that the deduplicator will always prioritise `!important` rules, just like a browser.

FIX: Prioritize !important CSS in emails

---

app/assets/javascripts/discourse/app/components/d-editor.gjs
app/assets/javascripts/discourse/app/static/prosemirror/components/prosemirror-editor.gjs
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/prosemirror-editor-test.gjs

When passing our ProsemirrorEditor component an initial value,
we were sometimes passing `null`, which causes the error in
the title of this commit. The fix here is to handle `null`
gracefully as string.
We originally found this on the category edit page, since
we have a `<DEditor />` in the form template form for the
category.

FIX: “Input data should be a string” error in ProseMirror

---

app/assets/javascripts/discourse/app/components/d-styles.gjs
app/assets/javascripts/discourse/app/components/edit-category-general.gjs
app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/app/helpers/category-variables.js
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/app/models/category.js
app/assets/javascripts/discourse/tests/acceptance/category-edit-test.js
app/assets/javascripts/discourse/tests/acceptance/category-new-test.js
app/assets/javascripts/discourse/tests/acceptance/transformers/text-color-test.js
config/locales/client.en.yml

This change removes the foreground color category setting to simplify the category creation and edit process for admins.
Instead we determine the highest contrasting color (either white or black) based on the background color.
Contrast algorithm is based on:
https://www.w3.org/TR/AERT/#color-contrast
We also implement the value transformer as part of this change, which allows overriding the category text color.
Internal ref: /t/147046

FEATURE: auto contrast text color for categories

---

app/assets/javascripts/discourse/app/models/rest.js

This property is used for the `isNew` and `isCreated` computed properties, which are then used in templates. To make that work correctly, we need to use `.set` or `@tracked`.

DEV: Add `@tracked` to RestModel `__state`

---

plugins/chat/assets/javascripts/discourse/initializers/chat-setup.js

Over the last few weeks, I have occasionally seen a deprecation warning on my smartphone. Unfortunately, there was no corresponding entry in /logs, and I never had the browser console available at the time.
I have now found the steps to reproduce the issue: the warning is triggered by the emoji selection button in the chat.
https://github.com/user-attachments/assets/fbda7ee2-6967-48af-aa00-d081466e6aea
The icon used in the button was 'smile' instead of 'face-smile'. With this fix, the warning no longer appears. 
Otherwise, the icon will be missing once https://github.com/discourse/discourse/pull/31866 is merged.

DEV: Fix FA icon deprecation 'smile' -> 'face-smile'

---

app/assets/javascripts/discourse/app/components/notifications-tracking.gjs
app/assets/javascripts/discourse/app/components/topic-notifications-tracking.gjs
app/assets/javascripts/discourse/app/components/topic-timeline/container.gjs
app/assets/javascripts/float-kit/addon/lib/d-menu-instance.js
app/assets/javascripts/select-kit/addon/components/topic-notifications-button.gjs
app/assets/stylesheets/common.scss
app/assets/stylesheets/common/components/notifications-tracking.scss

Before this fix a click on a d-menu trigger would fire a click on the parent element, which could have undesired consequences.
This also fixes two things:
- moves float-kit/form-kit css files higher in the chain, so it's easier to override
- increases the z-index of the notifications-tracking menu content or it would be behind the timeline control

FIX: prevents d-menu trigger/untrigger propagation

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control-wrapper.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/textarea.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/meta.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/field-test.gjs
app/assets/stylesheets/common/form-kit/_control-textarea.scss
app/assets/stylesheets/common/form-kit/_default-input-mixin.scss

This commit also ensures meta will resize with the textarea to avoid meta being badly positioned.
I couldn't easily write a test working on all platforms.

FIX: allows to resize textarea

---

app/assets/javascripts/discourse/app/static/prosemirror/core/inputrules.js
spec/system/composer/prosemirror_editor_spec.rb

iOS is automatically converting a double-hyphen (--) to an em-dash (–).
It may get in the way when we're trying to create an horizontal rule with a ---, so this PR adds the "em-dash + hyphen" case to our input rule regex.

UX: convert emdash+hyphen to a horizontal rule on rich editor

---

plugins/chat/app/models/chat/message.rb
plugins/chat/spec/models/chat/message_spec.rb
plugins/chat/spec/requests/chat/incoming_webhooks_controller_spec.rb

Especially with AI we have no exact control on the words and this could create and endless loop of errors.

DEV: skip watch word when message is created by bots

---

lib/email/styles.rb
spec/integration/email_style_spec.rb
spec/lib/email/sender_spec.rb
spec/lib/email/styles_spec.rb

These aren't technically needed in the output, since we inline all styles. However, there's no harm in including them, and having them visible will improve the developer experience when restyling emails.

DEV: Preserve ids/classes in emails

---

config/initializers/000-development_reload_warnings.rb

In a development environment, the server auto-restarter can't watch symlinked paths, which means that any symlinked plugins won't reload if their non-autoloaded files change.
This change does a simple resolve of the symlink for any symlinked plugins, and adds the real plugin path to those that it will auto-restart for.

DEV: Automatically reload dev when symlinked plugins change

---

lib/site_setting_extension.rb
spec/lib/site_setting_extension_spec.rb

Do not create UserHistory when new value is same as the old one. It is even more important now, when we have bulk save option.

FIX: create UserHistory only when setting changed

---

app/assets/javascripts/discourse/app/lib/icon-library.js
app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
app/assets/javascripts/discourse/tests/unit/lib/icon-library-test.js
lib/deprecated_icon_handler.rb
lib/discourse.rb
spec/lib/svg_sprite/svg_sprite_spec.rb

On 1st April, we'll start showing no icons if the icon name used is a deprecated one and therefore no longer part of the svg set.
We'll continue showing the messages with the correct icon name to aid correction of these names. 
Console logging will now be done at an error level for such icons.
We retain the behaviour of raising an error for such icons in plugins from svg_sprite.rb in test environments, but removed this from icon-library.js as it's harder to test the actual expected behaviour of returning the original icon now that it's not part of the deprecation workflow. (sinon.stub doesn't work well here for `isTesting` - the alternative would be to override the environment.js module with `proxyquire`) In any case, once we remove the mapping logic, we won't be raising errors in test …

DEV: show no icon if icon name is missing and log at error level

---

lib/stylesheet/compiler.rb

SASS deprecation warnings are quite noisy, especially when
running specs, here is an example:
```
Deprecation Warning [mixed-decls]: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
╷
52  │ ┌     @media screen and (max-width: 1048px) {
53  │ │       right: 0;
54  │ │     }
│ └─── nested rule
... │
56  │       background: var(--secondary);
│       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
╵
theme-entrypoint/desktop.scss 56:5         @import
/home/mb/repos/discourse/desktop.scss 3:9  root stylesheet
Deprecation …
```

DEV: Add env var to silence SASS deprecation warnings

---

spec/system/email_change_spec.rb

This is a follow up to 59edec46a3de105e720bd2c716ae34d636794044
Test is flaky and seems to require more time to complete on CI so we
double the max wait time for now to see if it reduces the test's
flakiness.

DEV: Double default capybara max wait time for certain tests take 3

---

app/assets/javascripts/discourse/app/components/d-editor.gjs
app/assets/stylesheets/common/d-editor.scss

- adds .d-editor-container--rich-editor-enabled to d-editor-container
- conditionally swaps textarea to monospace when siteSettings.rich_editor is enabled

FEATURE: when rich editor is enabled markdown is in monospace

---

lib/topics_bulk_action.rb
spec/lib/topics_bulk_action_spec.rb

When bulk removing tags, the tag topic count isn't updated. You have to wait for the daily "ensure consistency" job to run for it to update properly. This is causing downstream problems, like the inability to use the "remove unused tags" feature.
The counter updating is handled on destroy by the join table model `TopicTag`. But we are calling `#delete_all` to perform the bulk tag removal, which bypasses callbacks.
Change from `#delete_all` to `#destroy_all`, which invokes callbacks and updates the counters.

FIX: Update tag topic counts when bulk removing tags

---

app/assets/javascripts/discourse/app/components/edit-category-general.gjs

Some themes make use of the category background color even when using emojis or icons as the category style.
Therefore we should always allow the color selector to be visible when editing the category.
Internal ref: /t/150539

FIX: always allow edit category bg color

---

app/assets/javascripts/select-kit/addon/components/combo-box.js

Follow up fix to #31795 to prevent duplicate icons in category chooser.
This change prevents duplicate icons or icon and emoji combinations.
Relevant meta topic:
https://meta.discourse.org/t/duplicated-icon-in-composers-category-dropdown/359474

FIX: prevent duplicate category icons

---

spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb

When `Capybara.threadsafe` has been set to `true` as in our case, we
have to use `Capybara::Session#using_wait_time` instead of
`Capybara.using_wait_time`. The latter sets `default_max_wait_time` on
`Capybara.default_max_wait_time` while the former sets
`default_max_wait_time` on the session.

DEV: Use `Capybara::Session#using_wait_time` instead

---

config/site_settings.yml

When the feature was designed in 2020, it had two options: invite a single user or generate a link.
https://github.com/discourse/discourse/pull/9813
With simplified interface, it makes sense to allow to send a link to just 1 user.
Meta: https://meta.discourse.org/t/unable-to-restrict-invite-link-to-one-person/359872

FIX: invite_link_max_redemptions_limit min 1

---

plugins/chat/spec/system/thread_list/full_page_spec.rb

The system test relies on a MessageBus message being published and
received by the client. As we currently don't have a reliable way to
ensure that we run an assertion after the client has received all
MessageBus messages, we will just double the timeout for now.
Example of flaky test: https://github.com/discourse/discourse/actions/runs/14192287309/job/39759467138

DEV: Fix a flaky system test by doubling timeout

---

app/jobs/regular/backfill_badge.rb

Since 3e4eac0fed05daedcdea50d6275e143469d55eda, the daily `Jobs::BadgeGrant` scheduled job enqueues one `Jobs::BackfillBadge`
job per enabled badge. This can become problematic on large sites that
have alot of enabled badges as the long running queries executed by each
`Jobs::BackfillBadge` job may end up exhausting all available
database connections in a short span of time. To combat this, we are
limiting the `cluster_concurrency` of the `Jobs::BackfillBadge` job to
`1`.

PERF: Set `cluster_concurrency 1` for `Jobs::BackfillBadge`

---

Gemfile.lock
app/assets/stylesheets/common/d-editor.scss
app/assets/stylesheets/common/foundation/base.scss
lib/stylesheet/importer.rb

This change forces consistency around code font in Discourse once the new
rich-editor is enabled
- This means all code blocks in Discourse will render with this font
- Additionally the markdown mode composer will render with this font
Additionally we make 3 small adjustments:
1. We disable ligatures which conflict with typographer
2. We add support for custom ligature settings
3. We adjust down font size, cause 14px ends up matching visually with a 16px non monospace font, this change is already in place previously on posts
Example:

FEATURE: when rich-editor is enabled use Jetbrains Mono as code font

---

spec/support/helpers.rb

Some plugins are always enabled and don’t have a related site setting.
This PR takes this into account.

DEV: Fix the `enable_current_plugin` spec helper

---

app/assets/stylesheets/admin/admin_base.scss

This PR adjusts the bottom spacing in the site settings when scrolled to the bottom and the “Save all changes” banner is visible, ensuring that the setting controls and helper text are fully visible within the viewport.

UX: Adjust spacing to prevent last setting from being hidden behind save all banner

---

spec/system/email_change_spec.rb

Checking of the database state is still flaky on CI. Double the timeout
to give the server more time to process as a workaround.
Example of test flake: https://github.com/discourse/discourse/actions/runs/14216968060/job/39835831706

DEV: Double timeout in `spec/email_change_spec.rb`

---

app/assets/stylesheets/admin/settings.scss

UX: Adjust spacing between simple tags in the site settings preview

---

app/assets/javascripts/discourse/app/components/header/contents.gjs
spec/system/search_spec.rb

This change prevents rendering the search field on login and sign up pages.
Internal ref: /t/150011

FIX: hide search field on auth pages

---

app/assets/stylesheets/common/base/search.scss

Better alignment with the  `,` separator

UX: Align tag separator properly when viewing search in full-page mode

---

app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/components/hashtag.scss
app/assets/stylesheets/common/foundation/mixins.scss

Fixing hashtag text glued to the icon
And updated some related properties to using better units
| ![CleanShot 2025-04-01 at 14 25 32@2x](https://github.com/user-attachments/assets/818d763d-900d-4a68-9115-381173b0c0a3) | ![CleanShot 2025-04-01 at 14 15 37@2x](https://github.com/user-attachments/assets/abbe9167-6fa1-41ff-999d-e12a779f6a0e) |

UX: add flex to mention for consistent alignment and spacing

---

app/assets/javascripts/admin/addon/components/admin-site-settings-changes-banner.gjs
app/assets/javascripts/admin/addon/components/site-setting.gjs
app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show.js
app/assets/javascripts/admin/addon/mixins/setting-component.js
app/assets/javascripts/admin/addon/models/site-setting.js
app/assets/javascripts/admin/addon/models/theme-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-with-settings-route.js
app/assets/javascripts/admin/addon/routes/admin-site-settings.js
app/assets/javascripts/admin/addon/services/site-setting-change-tracker.js
app/assets/javascripts/discourse/tests/integration/components/compact-list-test.gjs
app/assets/javascripts/discourse/tests/integration/components/group-list-setting-test.gjs
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.gjs
config/locales/client.en.yml
spec/system/admin_site_setting_bulk_action_spec.rb
spec/system/admin_site_setting_category_bulk_action_spec.rb
spec/system/page_objects/pages/admin_site_settings.rb

This builds onto #32013 in two major ways:
1. Unsaved changes are now persisted when you browse categories inside "All site settings".
2. If you're about to navigate away (and lose edits) you will be prompted if you want to save or discard changes. (This applies to individual category site setting pages as well.
**All site settings:**
**Site setting category:**
The original problem is that we kept a lot of the state in the components themselves. Because of Ember's component lifecycle, these were destroyed when switching categories, losing the state.
Most of this change is shifting state and behaviour around between three actors:
- `SiteSettingChangeTracker` service.
- `SiteSettingComponent` component (and its `SettingComponent` mixin).
- `SiteSetting` model.
In particular:
- The relevant …

DEV: Preserve unsaved site settings

---

app/assets/javascripts/admin/addon/components/admin-site-settings-changes-banner.gjs
app/assets/stylesheets/admin/site-settings.scss

Elements with `position: fixed` are taken out of the rendering context, so we can't easily make the banner the width of the main container using CSS. We tried a CSS hack, but that doesn't scale to larger screens, and probably breaks in some themes.
This is a simple JavaScript implementation that matches the width of the main container.

UX: Proper width of unsaved site setting banner

---

app/assets/javascripts/admin/addon/controllers/admin-user-index.js
app/assets/javascripts/admin/addon/controllers/admin-users-list-show.js
app/assets/javascripts/discourse/app/controllers/preferences/account.js
app/assets/javascripts/discourse/app/controllers/preferences/security.js
app/assets/javascripts/discourse/app/controllers/user.js
app/assets/javascripts/discourse/app/lib/can-check-emails-helper.js

We only need the `model.id` input here, so this simplifies the arguments being passed into this helper.

DEV: refactor CanCheckEmailsHelper to directly take model id

---

app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/common/components/hashtag.scss
app/assets/stylesheets/common/foundation/mixins.scss
plugins/chat/spec/system/channel_members_page_spec.rb

Fixing hashtag text glued to the icon
And updated some related properties to using better units
| ![CleanShot 2025-04-01 at 14 25 32@2x](https://github.com/user-attachments/assets/818d763d-900d-4a68-9115-381173b0c0a3) | ![CleanShot 2025-04-01 at 14 15 37@2x](https://github.com/user-attachments/assets/abbe9167-6fa1-41ff-999d-e12a779f6a0e) |

UX: add flex to mentions mixin + update units

---

spec/system/admin_sidebar_navigation_spec.rb

Wait till all sections are expanded before checking expected links.

FIX: flaky admin_sidebar_navigation_spec

---

.github/workflows/tests.yml
spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb

There are flaky system tests that have been exhausting the 10 seconds
default max wait time which we have set previously on CI. However, I
have yet to be able to figure out why and lack the tools to be able to
figure out why. The hope here is that the upcoming playwright driver
will provide us with better tooling to debug such problems.
I've attempted to use `Capybara::Session#using_wait_time` by there is some race condition going on where the session's default max wait time is sometimes not set properly. I can't figure out why and have spent too much time trying to figure out why. Instead, I will just bump up the `default_max_wait_time` to `20`. This may the build take longer when there are test failures but it is a trade-off we will make right now.

DEV: Bump Capybara.default_max_wait_time to 20 on CI

---

app/models/user_option.rb
plugins/chat/assets/javascripts/discourse/controllers/preferences-chat.js
plugins/chat/assets/javascripts/discourse/initializers/chat-user-options.js
plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js
plugins/chat/assets/javascripts/discourse/templates/preferences/chat.gjs
plugins/chat/config/locales/client.en.yml
plugins/chat/db/migrate/20250307185912_add_chat_quick_reaction_preferences.rb
plugins/chat/lib/chat/user_option_extension.rb
plugins/chat/plugin.rb
plugins/chat/spec/models/user_option_spec.rb
plugins/chat/spec/serializer/current_user_serializer_spec.rb
plugins/chat/spec/serializer/user_serializer_spec.rb
plugins/chat/spec/system/page_objects/chat/chat_channel.rb
plugins/chat/spec/system/page_objects/pages/user_preferences_chat.rb
plugins/chat/spec/system/user_chat_preferences_spec.rb
plugins/chat/test/javascripts/unit/lib/chat-message-interactor-test.js

Adds a one-click chat reactions setting to the chat preferences page where members can determine what one-click reactions are shown in chat.
- Frequent: This will be the default setting. (Automatically set based on most used chat reactions)
- Custom: Members can choose up to three reactions they want to see in their one-click chat/DM reactions menu. Defaults are `:heart:`, `:+1:` , and `:smile:`.
This pull request is essentially the work of @dsims in https://github.com/discourse/discourse/pull/31761

FEATURE: One-click chat reaction settings

---

app/assets/javascripts/discourse/app/components/modal/bulk-topic-actions.gjs
app/assets/javascripts/discourse/app/controllers/group-messages.js
spec/system/topic_bulk_select_spec.rb

Bulk archiving group messages can be done from two places: a) from the user's view (`/u/ted/messages/group/swedes`) and b) from the group's view (`/g/swedes/messages/inbox`). Only the former is currently working. From the latter view, the action looks like a success, but is actually a no-op.
When using the group view, the `operation[group]` parameter is missing from the request.
Copy the logic of the user view for the group view to make sure the `group` parameter is included.

FIX: Archiving messages from group inbox

---

lib/tasks/assets.rake

Recent testing has shown that this config requires significantly less memory for a successful build, which should improve the situation for people running Discourse on low-memory servers.

PERF: Set `JOBS=1` for low-memory build environments

---

app/assets/javascripts/discourse/app/components/composer-editor.gjs
app/assets/javascripts/discourse/app/components/d-editor.gjs
app/assets/javascripts/discourse/app/lib/user-search.js
app/assets/javascripts/discourse/app/services/composer.js
app/controllers/users_controller.rb
app/models/user_search.rb
app/serializers/post_serializer.rb
spec/models/user_search_spec.rb
spec/requests/api/schemas/json/post_replies_response.json
spec/requests/users_controller_spec.rb

When replying to a post, the user who is getting the reply should be prioritized in the autocomplete
- Added in composer a getter for getting `.replyingToUser`
- Added in d-editor the reference to the user that is getting the reply(`this.composer.replyingToUser`)
- Passed along the reference to the user that is getting the reply to the user-search service as `replyingToUser`
- Controller `users_controller.rb` was modified to accept the `user_id` parameter and pass it to the `UserSearch` model
- The `UserSearch` model was modified to accept the `user_id` parameter and use it to prioritize the user that is getting the reply in the autocomplete on the first time you call the autocomplete service and while the username is included in the searched term
- Had to update the serializer to pass …

FEATURE: prioritize the user who is getting the reply in the autocomplete

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

I've considered some _very_ generic, like:
```rb
DiscoursePluginRegistry.apply_modifier(:"meta_data_content_for_#{property}", content, property, opts)
```
But, I think for now, we can use this one and rely on the plugin to do the filtering (`if property == :title`)

DEV: Add modifier for meta_data_content in ApplicationHelper

---

app/assets/javascripts/discourse/app/components/search-menu.gjs
app/assets/javascripts/discourse/app/components/search-menu/search-term.gjs
app/assets/javascripts/discourse/tests/integration/components/search-menu-test.gjs

Followup c4d971ea2c7677d893e0d6fdcec5d7d93d9c964e
There are some customizations still relying on #search-menu
for an ID, this provides a fallback to that ID if no
@searchInputId arg is provided while we work through the
customizations.

FIX: Fallback to #search-menu for search input

---

app/assets/javascripts/admin/addon/controllers/admin-analytics-settings.js
app/assets/javascripts/admin/addon/routes/admin-analytics.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/analytics-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml

This PR adds a dedicated page for Analytics and SEO related site settings:

DEV: Add Analytics and SEO admin config page

---

app/assets/stylesheets/admin/admin_config_area.scss

When running specs I noticed this mixed-decls Sass deprecation warning:
> Deprecation Warning [mixed-decls]: Sass's behavior for declarations that appear after nested
> rules will be changing to match the behavior specified by CSS in an upcoming
> version. To keep the existing behavior, move the declaration above the nested
> rule. To opt into the new behavior, wrap the declaration in & {}.
>
> More info: https://sass-lang.com/d/mixed-decls
This change address that issue.
Follow up to: 928f9175f05413289c45d3fd6424f62956ea0944

DEV: Fix mixed-decls Sass deprecation warning

---

app/assets/javascripts/admin/addon/controllers/admin-config-user-defaults-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-user-defaults-settings.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-user-defaults-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml
lib/svg_sprite.rb

This PR adds a dedicated admin config page for User defaults related site settings.

DEV: Add User defaults admin config page

---

app/assets/javascripts/admin/addon/controllers/admin-config-interface-settings.js
app/assets/javascripts/admin/addon/routes/admin-config-interface-settings.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-interface-settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml

This PR adds a dedicated admin settings page for Interface & layout related site settings:

DEV: Add Interface and layout admin config page

---

app/assets/javascripts/admin/addon/routes/admin-api-keys.js
app/assets/javascripts/admin/addon/routes/admin-badges.js
app/assets/javascripts/admin/addon/routes/admin-dashboard.js
app/assets/javascripts/admin/addon/routes/admin-email.js
app/assets/javascripts/admin/addon/routes/admin-logs.js
app/assets/javascripts/admin/addon/routes/admin-permalinks.js
app/assets/javascripts/admin/addon/routes/admin-reports.js
app/assets/javascripts/admin/addon/routes/admin-site-settings.js
app/assets/javascripts/admin/addon/routes/admin-site-text.js
app/assets/javascripts/admin/addon/routes/admin-users.js
app/assets/javascripts/admin/addon/routes/admin-watched-words.js
spec/system/admin_user_spec.rb

A number of admin config pages are missing a page title. This PR adds them in.
For example:

UX: Add missing admin config page titles

---

spec/system/page_objects/components/admin-branding-fonts-form.rb

Wait for state to be updated before submit fonts form to avoid random failures.
Form was submitted too quickly

FIX: flaky admin_branding_spec fonts section

---

app/assets/javascripts/discourse/app/components/edit-category-general.gjs
app/assets/javascripts/discourse/app/components/edit-category-settings.gjs
app/assets/javascripts/discourse/tests/acceptance/category-new-test.js

This PR fixes a bug where, if you're editing or creating a category, selecting a parent category for the category that's being edited/created causes the rest of the fields in the category edit/create form to be cleared out.
Internal topic: t/151232.

FIX: Selecting a parent category shouldn't clear other form fields

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/link.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/onebox.js
app/assets/javascripts/discourse/app/static/prosemirror/lib/plugin-utils.js
spec/system/composer/prosemirror_editor_spec.rb

Using markdown-it's linkify strategy, this plugin adds marks to regular text that happens to be identified as a URL, and removes marks from link-marked text that happens to not be a valid URL anymore.
Additionally, it changes the onebox handling to only act if we're not in the same word as the link to be oneboxed.

FEATURE: auto-link/unlink url-like words on rich editor when typing

---

app/assets/stylesheets/common/base/_topic-list.scss

This PR allows group participant tags to wrap in the topic list.

UX: Wrap participants in pm topic item

---

app/assets/javascripts/discourse-markdown-it/src/features/onebox.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/onebox.js
spec/system/composer/prosemirror_editor_spec.rb

Adjusts the rich editor onebox handling to ensure the full protocol URLs are passed to the inline/full onebox endpoints, but when they are resolved, we keep the original textual content as the stored URLs for the onebox nodes, because we need to keep them as-is when serializing them back to Markdown.
Additionally, it now re-uses the `isTopLevel` logic for inline oneboxes, so top level domains like `example.com` are not mistakenly inline oneboxed.

UX: improve onebox handling on rich editor

---

docs/INSTALL-email.md

mailgun no longer offers a 5k/3 month trial. it offers a 50k/30 day trial. the "Basic" level for $15/mo with 10k emails has no ability to trial it for any time.

DEV: Update mailgun pricing

---

app/assets/javascripts/discourse/app/static/prosemirror/core/keymap.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/code-block.js
app/assets/javascripts/discourse/app/static/prosemirror/lib/plugin-utils.js
spec/system/composer/prosemirror_editor_spec.rb

Adds to the Backspace keymap - a custom `backspaceUnset`, which will set the node as `paragraph` if it's at a block start and the node type in `BACKSPACE_UNSET_NODES`, currently for `heading` and `code_block`.
Removes a `code_block`-specific plugin that did exactly the same.
Adds to the Backspace keymap - `joinTextblockBackward`, which will take precedence over `joinBackward`, and make the backward joining closer to the expectation e.g. backspacing to a list won't create a new list item

UX: backspace rich editor keymap improvements

---

lib/deprecated_icon_handler.rb

The string was written as a JS one (using ``), but in Ruby this syntax tries to execute the string as a command on the host system.

DEV: Fix the error message from the deprecated icon handler

---

app/assets/javascripts/discourse/app/components/category-title-link.gjs
app/assets/stylesheets/common/base/category-list.scss

Adds support for category style headings (square, emojis and icons) to the all categories list.
With RTL support:
Internal ref: /t/150539

FIX: add category badge style to category list

---

app/assets/javascripts/dialog-holder/addon/services/dialog.js
app/assets/javascripts/discourse/app/components/user-preferences/user-passkeys.gjs
app/assets/javascripts/discourse/app/controllers/preferences/security.js
app/assets/javascripts/discourse/app/models/user.js
app/assets/javascripts/discourse/app/templates/preferences/security.gjs
app/assets/javascripts/discourse/tests/acceptance/user-preferences-security-test.js
app/controllers/users_controller.rb
app/models/user.rb
app/models/user_security_key.rb
app/serializers/user_serializer.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/routes.rb
spec/requests/users_controller_spec.rb
spec/system/user_page/user_preferences_security_spec.rb

Added button to remove password from account if user has a linked external account or passkey
The button only displays if the user has at least one associated account or a passkey set up. Uses the ConfirmSession dialog in addition to a warning about deleting the password.
Users can still reset their password via the Reset Password button (which will now display "Set Password" if they've removed it).
Also prevent user from removing their last remaining associated account or passkey if they have no password set.
Replaces PR #31489 from my personal repo, with some fixes for conflicts since then.

Added button to remove password from account

---

app/assets/stylesheets/common/rich-editor/rich-editor.scss

Respects the same styling from the preview for font-style and color for the ProseMirror editor when we're composing a whisper.

UX: whisper color and font-style on rich editor

---

app/assets/stylesheets/common/modal/login-modal.scss

This fixes a bug on Safari where, for some reason, it was leaking to affect the rich editor list item rendering. When typing, the current list item was breaking to a next line:
With this change, it doesn't happen anymore, and the more specific `svg` target will serve the same purpose as it's currently defined on `InputTip`.

FIX: safari bug on rich editor's list item

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/table.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/table-test.js
app/assets/stylesheets/common/base/emoji.scss

Adds the `md-table` to rich editor tables for consistency with cooked.
Keeps `only-emoji` with their regular size when they happen within a `li`.

UX: only-emoji consistency between rich editor and cooked

---

plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs

discourse presence can be disabled, given it's a plugin the `composerPresenceManager` service wouldn't be present anymore and would cause an error.
No test as it's testing the imbrication of multiple plugins and hard to test reliably.

DEV: ensures chat can work without discourse-presence

---

app/assets/javascripts/discourse/app/lib/transform-post.js
app/assets/javascripts/discourse/app/models/post-action-type.js
app/assets/javascripts/discourse/app/models/post.js
app/serializers/flag_serializer.rb
spec/requests/api/schemas/json/site_response.json
spec/system/flagging_post_spec.rb

Currently, this is the order of i18n translate function:
1. Translation in required language;
2. Optional `defaultValue` provided;
3. Fallback to forum default language.
When admin set language as English GB, translation was not correctly displayed as it went to step 2 and displayed `defaultValue` instead of correct translation from default language.
Before
After

FIX: incorrect flag message when en_GB language

---

app/assets/javascripts/admin/addon/controllers/admin-api-keys-settings.js
app/assets/javascripts/admin/addon/controllers/admin-api-keys.js
app/assets/javascripts/admin/addon/routes/admin-api-keys-index.js
app/assets/javascripts/admin/addon/routes/admin-api-keys-settings.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/api-keys.gjs
app/assets/javascripts/admin/addon/templates/api-keys/settings.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js

We used to have a `User API` admin page, which is just a page with the site settings. This PR moves that into a `Settings` tab under `API keys`:

DEV: Move User API admin settings into API keys page

---

app/assets/javascripts/admin/addon/controllers/admin-reports-dashboard-settings.js
app/assets/javascripts/admin/addon/controllers/admin-reports.js
app/assets/javascripts/admin/addon/routes/admin-reports-dashboard-settings.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/reports-dashboard-settings.gjs
app/assets/javascripts/admin/addon/templates/reports-index.gjs
app/assets/javascripts/admin/addon/templates/reports.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/site_settings.yml

This change adds a `Dashboard settings` tab to the `Reports` page:

DEV: Add Dashboard settings tab to Reports page

---

app/assets/javascripts/admin/addon/controllers/admin-config-content-categories-and-tags.js
app/assets/javascripts/admin/addon/controllers/admin-config-content-posts-and-topics.js
app/assets/javascripts/admin/addon/controllers/admin-config-content-sharing.js
app/assets/javascripts/admin/addon/controllers/admin-config-content-stats-and-thresholds.js
app/assets/javascripts/admin/addon/routes/admin-config-content-categories-and-tags.js
app/assets/javascripts/admin/addon/routes/admin-config-content-posts-and-topics.js
app/assets/javascripts/admin/addon/routes/admin-config-content-sharing.js
app/assets/javascripts/admin/addon/routes/admin-config-content-stats-and-thresholds.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-content-categories-and-tags.gjs
app/assets/javascripts/admin/addon/templates/config-content-posts-and-topics.gjs
app/assets/javascripts/admin/addon/templates/config-content-sharing.gjs
app/assets/javascripts/admin/addon/templates/config-content-stats-and-thresholds.gjs
app/assets/javascripts/admin/addon/templates/config-content.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/models/site_setting.rb
config/locales/client.en.yml
config/routes.rb
config/site_settings.yml
spec/system/admin_sidebar_navigation_spec.rb

This PR adds a dedicated page for Content related site settings. It has four different site setting tabs:

DEV: Add Content admin config page

---

app/assets/javascripts/discourse/app/components/header/contents.gjs
spec/system/search_spec.rb

Prevents rendering the search field on the invites page.
Internal ref: /t/150011

FIX: hide search field on invites page

---

lib/search.rb
spec/lib/search_spec.rb

Add new advanced search filters for post types
- `in:bot` or `in:bots`: Filters for posts made by bot users (user_id < 0)
- `in:human` or `in:humans`: Filters for posts made by human users (user_id >= 0)
- `in:whisper` or `in:whispers`: Filters for whisper posts (respects permissions)
- `in:regular`: Filters for regular posts only

FEATURE: allow searching for whispers and bots

---

plugins/automation/app/models/discourse_automation/stat.rb
plugins/automation/spec/models/stat_spec.rb

The previous code could attempt to log a `nil` `run_time` if the block would raise an exception. This commit adds two safeguards:
- rescue any exception to still compute `run_time`
- defaults to `0` if we still don't have any `run_time`

FIX: logs time even when automation raises

---

app/assets/javascripts/discourse/app/lib/hashtag-decorator.js

The style type data attribute is missing for cooked posts prior to #31795 which meant that older posts with category hashtags were not displaying correctly. We already have a default style type at the database level, but for hashtag styling it is handled based on stored markup at the point in time when the post was last cooked.
Simply rebuilding html solves this but a good workaround is to set a proper default when the data attr is missing.
Internal ref: /t/151514

FIX: category badge style missing data attr

---

app/assets/javascripts/discourse/app/components/composer-editor.gjs
app/assets/javascripts/discourse/app/components/d-editor.gjs
app/assets/javascripts/discourse/app/services/composer.js
spec/system/composer_spec.rb
spec/system/page_objects/components/composer.rb
spec/system/page_objects/components/post.rb

Added in https://github.com/discourse/discourse/pull/32086 this prioritization did not accounted for when the user was replying to the topic/OP.
Now when replying to the topic, the author will be prioritized in the list.
All other cases are the same as before.
Added testing for all cases and changed `replyingToUser` to `replyingToUserId` for clarity and consistency with API.

FIX: Prioritize the author when replying to topic

---

plugins/automation/admin/assets/javascripts/admin/components/fields/da-tags-field.gjs
plugins/automation/lib/discourse_automation/scriptable.rb
plugins/automation/lib/discourse_automation/scripts/auto_tag_topic.rb
plugins/automation/spec/scripts/auto_tag_topic_spec.rb
plugins/automation/spec/scripts/send_pms_spec.rb

Relaxed restrictions:
- Automation posts are not validated for similarity. This was causing error when PMs were created by regular user with same content and sent to different users.
- Don't create warning logs when PM target does not exist anymore. When for example spammer was deleted, delayed PM is not sent, but it is correct behaviour;
- Allow tags to be applied even if an automation user is not allowed to tag;
- Restricted category tags should be visible in configuration UI. Still, they will be applied only when specific topic belongs to correct category.

FIX: relax automation restrictions

---

app/assets/javascripts/admin/addon/controllers/admin-users-settings.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/routes/admin-users-settings.js
app/assets/javascripts/admin/addon/templates/users-settings.gjs
app/assets/javascripts/admin/addon/templates/users.gjs
app/models/site_setting.rb
config/routes.rb
config/site_settings.yml

This PR adds a `Settings` tab to the admin `Users` page, grouping relevant site settings:

DEV: Add Settings tab to admin Users page

---

lib/svg_sprite.rb

Changing the `CORE_SVG_SPRITES` constant to a method enables us to detect SVG files that are written to the vendor directory during plugin initialization (as done by the [FontAwesome pro plugin](https://github.com/discourse/discourse-fontawesome-pro/blob/79a8d39fb46d0f28543680a45acf988fd7b87194/plugin.rb#L31)) which happens after all the ruby classes/files are read and loaded into memory.
Internal topic: t/151476.

FIX: Move CORE_SVG_SPRITES constant to a method

---

app/controllers/admin/watched_words_controller.rb
spec/requests/admin/watched_words_controller_spec.rb

When a watched words CSV file is uploaded, we assume it's utf-8 encoded, but that's not always going to be the case. This change loads the CSV and converts it to utf-8 before processing it.

FIX: Ensure uploaded watched word CSVs are converted to utf-8.

---

app/assets/javascripts/discourse/app/controllers/tag/show.js
app/assets/javascripts/discourse/app/initializers/dynamic-route-builders.js
app/assets/javascripts/discourse/app/routes/build-category-route.js
app/assets/javascripts/discourse/app/routes/build-topic-route.js
app/assets/javascripts/discourse/app/routes/tag-show.js
spec/system/discovery_list_spec.rb

Sharing a controller seems to make query params behave more weirdly than normal. This change lets Ember create a separate controller instance for each route, even though they will still share the same class.

FIX: Ensure discovery queryParams do not persist invisibly

---

app/helpers/application_helper.rb
app/views/layouts/crawler.html.erb
spec/helpers/application_helper_spec.rb

In https://github.com/discourse/discourse/pull/32159 we overrode the `og:` and `twitter:` title and description but for some crawlers, we need to override the `title` and `description` meta tag as well.

FEATURE: add override for crawler title and description tags

---

app/services/push_notification_pusher.rb
spec/services/push_notification_pusher_spec.rb

Our service worker concatenates `baseUrl` with `url` coming from the payload:
https://github.com/discourse/discourse/blob/e8f4433872f075db6400ab53c94d8d117422b93b/app/views/static/service-worker.js.erb#L96
This PRs strips the base path before sending `url` to the push notification to avoid having a URL with the base path duplicated, causing a 404.

FIX: avoid double base path on push notification

---

plugins/discourse-details/assets/javascripts/lib/rich-editor-extension.js

Currently, all clicks on the `summary` node toggles the `details` `open` state.
With this change, only clicks on the caret ▶️  `::before` element will be used to toggle it.

UX: only toggle rich editor details on caret click

---

app/assets/javascripts/discourse/app/components/d-editor.gjs
spec/system/composer/prosemirror_editor_spec.rb
spec/system/page_objects/components/composer.rb

Adds a ctrl+m shortcut to d-editor to toggle between rich and markdown editor when the `rich_editor` site setting is enabled.

FEATURE: Ctrl+M to toggle between rich/markdown editor

---

app/assets/javascripts/discourse/app/components/composer/toggle-switch.gjs
app/assets/javascripts/discourse/app/lib/utilities.js
config/locales/client.en.yml

Followup 198dc813750d7a0de98cc94372dea1222b97743b
Indicate the shortcut in the tooltip for the rich/markdown
editor toggle, and also add the control translation for mac
in `translateModKey`

UX: Add tooltip for markdown toggle shortcut

---

app/assets/javascripts/admin/addon/controllers/admin-site-text-edit.js
app/assets/javascripts/discourse/tests/acceptance/admin-site-text-test.js

Repro steps:
1. Go to `/admin/customize/site_texts`
2. Click edit on any translation
3. Go back by clicking on "Back to search"
4. Click edit on another translation
5. Change the text field in any way
Expected results:
The disabled state on the "Save changes" button is removed and you're able to click it
Actual results:
The "Save changes" button remains disabled
This happens because the computed property for the button's disabled state doesn't get re-evaluated when navigating between translation strings because it doesn't include on the `siteText` property in its dependent properties, so changing the site text doesn't invalidate the old value for the disabled state and it always stays the same.
Meta topic: https://meta.discourse.org/t/i-cant-save-edit-on-site-texts/360990?u=osama

FIX: Refresh disabled state when switching between site texts

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/emoji.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/hashtag.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/mention.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/emoji-test.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/hashtag-test.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/mention-test.js
plugins/discourse-local-dates/assets/javascripts/lib/rich-editor-extension.js

On some cases during serialization (like with headings), the previous node is still "open" when it's the "turn" of the node we're serializing.
In this case, checking the boundaries before writing was getting the wrong state, because the `write` call uses `flushClose()`, which makes sure we have the newlines from closing the previous node.
This would create scenarios like (notice the space before each node below the heading)
```markdown
:tada:
@mention
#hashtag
```
This PR makes sure we call flushClose() before checking boundaries, and adds tests for that.

UX: avoid leading space when serializing some nodes from rich editor

---

app/assets/stylesheets/common/base/onebox.scss
app/assets/stylesheets/desktop/topic-post.scss
plugins/chat/assets/stylesheets/common/chat-transcript.scss

This PR causes oneboxes and quotes to inherit the border radius set by `var(--d-border-radius)`

UX: Onebox & quote border radius

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/html-block.js
app/assets/javascripts/discourse/app/static/prosemirror/lib/plugin-utils.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/html-block-test.js

When using a html block within the rich editor (currently only possible after parsing it from Markdown), it would get serialized with the default escape=true processing.
Additionally, html blocks are a continuous block, if a `\n\n` is seen during cooking the block is closed, so we make sure at most one continuous `\n` is seen in the html block node on the  ProseMirror doc.
EDIT: It turns out, it's not so simple. I'm merging this as is, but it's important to link the actual behavior to close a paragraph from markdown-it:
https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/lib/rules_block/html_block.mjs#L6-L17

UX: rich editor html_block without escaping and avoiding \n\n

---

app/assets/stylesheets/common/d-editor.scss
app/assets/stylesheets/common/rich-editor/rich-editor.scss

Adds the whisper styling to the Markdown editor as well, keeping it consistent with the preview and the rich editor.

UX: keep the whisper editor font/color style consistent between editors

---

app/assets/javascripts/discourse/app/static/prosemirror/lib/text-manipulation.js

Our `insertBlock` implementation was only taking the `firstChild` into consideration.
We didn't notice this before because there's only one use of this in core, quoting from a post, which has a single child.
This fix is necessary to support the `insert-block` call that the https://github.com/discourse/discourse-templates plugin makes when inserting a template.

FIX: rich editor insertBlock implementation

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/layouts/crawler.html.erb
spec/helpers/application_helper_spec.rb

Previously, there was only those helpers in `crawler.html.erb` as we added it in https://github.com/discourse/discourse/pull/32259
However, to keep it consistent, we need to add it in `application.html.erb` as well.

FIX: Add helpers for title and content for `application.html.erb` and `crawler.html.erb`

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/image.js
spec/system/composer/prosemirror_editor_spec.rb

New lines on `alt`/`title` embedded media are not allowed, causing an invalid serialized Markdown which is not supposed to contain new lines for these attributes.
This PR removes them during HTML parsing – we are not creating this new line scenario otherwise.

FIX: remove newline from rich editor's pasted img title/alt

---

plugins/footnote/assets/javascripts/lib/rich-editor-extension.js

Instead of using the matched string, this PR uses the actual sliced content from the ProseMirror document range as the content when creating the footnote node.

UX: keep content on rich editor footnote inputrule

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/image-previews/logo.js

`PreviewBase#drawPills` expects a `homepageStyle` option, but on the logo wizard page we weren't passing any.
Pass one of the possible values. I chose `hot` (because why not?)
**Before:**
_Note how the navigation isn't rendered._
**After:**

FIX: Wizard logo step JS error

---

app/assets/javascripts/admin/addon/components/admin-fonts-form.gjs
app/assets/javascripts/admin/addon/components/admin-logo-form.gjs
app/assets/javascripts/admin/addon/mixins/setting-component.js
app/assets/javascripts/admin/addon/services/site-setting-change-tracker.js
spec/system/admin_logo_and_fonts_spec.rb
spec/system/page_objects/components/admin_fonts_form.rb

It takes a moment to sync site settings. Therefore, it is better to pass new values to  `refreshPage` function.
Also, it was not working for some fonts like `JetBrains Mono`. SiteSetting key is `jet_brains_mono` but font family value should be `JetBrains Mono`.

FIX: bugs with refresh page after save fonts

---

app/assets/javascripts/discourse/app/static/prosemirror/lib/text-manipulation.js
app/assets/javascripts/discourse/tests/integration/components/d-editor-test.gjs

When we do replaceText in the ProseMirror TextManipulation lib,
we are creating a regex for the provided markdown. However this markdown
can have things like * (which is valid for a markdown list), which also
doubles as a regex symbol. We can escape the markdown provided to
the regex first to fix the issue.

FIX: Escape regex symbols when replaceText is called for ProseMirror

---

app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
app/assets/javascripts/float-kit/addon/components/d-default-toast.gjs
config/locales/client.en.yml
spec/system/search_shortcut_variation_spec.rb

This commit removes the Ctrl+F search shortcut, which hijacks the
browser search shortcut in Discourse. We are doing this because there
has been many years of complaints around this behaviour, and now that
we have the new header search it has become even more annoying.
We originally added this because we lazy load posts in a topic, and it
might not have been immediately clear to users that they are not searching
all the posts in the topic when pressing Ctrl+F. However, that was 10+ years
ago, most people are very familiar with lazy loading now, it doesn't make sense
to keep this additional hijack for this one topic use case.
Search is still accessible by pressing the `/` shortcut.

UX: Remove Ctrl+F search shortcut

---

app/assets/javascripts/discourse/app/templates/login.gjs

Adds a plugin outlet below the login buttons in the login-required splash screen.
Use case: adding a custom footer to the splash screen with links to tos and privacy policy.

Add a plugin outlet to the login splash screen

---

app/models/theme.rb
spec/models/theme_spec.rb

Theme/component description is fetched via the `locale_fields` and `theme_translation_overrides` associations on the `Theme` model. We're currently not preloading these associations when serializing themes/components, which causes an N+1 performance issue when accessing the themes/components listing pages.

PERF: Prevent N+1 queries when loading theme/component descriptions

---

app/assets/javascripts/admin/addon/components/admin-config-areas/components.gjs
app/assets/javascripts/discourse/app/lib/popular-themes.js
spec/system/admin_customize_components_config_area_spec.rb

When an installed component doesn't have a description in its locale files, we should fallback to the description that core has for the component if it's one of the popular components that core features.

UX: Use core description of popular components when there's no description

---

.github/workflows/tests.yml
.gitignore
app/assets/javascripts/discourse/ember-cli-build.js
lib/tasks/assets.rake
lib/tasks/qunit.rake
script/assemble_ember_build.rb

Building the Discourse JS app is very resource-intensive. This commit introduces an `assemble_ember_build` script which will check the existing content of the `dist/` directory and re-use the core build if possible. Plugins will always be rebuilt.
For now, this functionality is only useful for multi-stage (i.e. non-standard) Discourse deployments. But in future, this script may be extended to pull the contents of the `dist/` directory from a remote location.

PERF: Reuse existing core JS build where possible

---

spec/helpers/application_helper_spec.rb

State seems to be leaking into other specs. Minimal repro:
```
bin/rspec --order defined spec/helpers/application_helper_spec.rb:783 spec/lib/wizard/wizard_builder_spec.rb:38
```
```
Failures:
1) Wizard::Builder introduction should not prefill default site setting values
Failure/Error: expect(description_field.value).to eq("")
expected: ""
got: " - modified by plugin"
```

DEV: Skip meta_data_content specs

---

spec/helpers/application_helper_spec.rb

It was using `<<` that caused the SiteSetting to get modified
Updated the spec to use the same pattern as other modifiers and used `next` to return the correct value of the modifer

FIX: Fix meta data content modifier state leak

---

app/assets/javascripts/admin/addon/routes/admin.js
app/assets/javascripts/discourse/app/components/modal/keyboard-shortcuts-help.gjs
app/assets/javascripts/discourse/app/components/sidebar/filter.gjs
app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/serializers/current_user_serializer.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
db/migrate/20250416012407_remove_experimental_admin_search_enabled_groups_setting.rb
spec/system/admin_search_spec.rb
spec/system/admin_sidebar_navigation_spec.rb

This commit removes the experimental setting controlling
admin search and releases it for all admins. This search
can be triggered with Ctrl+/ or Cmd+/
For more information see https://meta.discourse.org/t/introducing-comprehensive-admin-search/360157

FEATURE: Release admin search for all sites

---

app/controllers/safe_mode_controller.rb
spec/requests/safe_mode_controller_spec.rb

The `/safe-mode` route doesn't really need to be indexed by search engines. Notably, it results in meta's safe-mode page appearing before safe mode documentation in Google.
This change adds the `X-Robots-Tag` header to the `/safe-mode` response, discouraging search engines from including the page in their index.

FIX: Set X-Robots-Tag header to prevent indexing of /safe-mode

---

config/nginx.sample.conf

This is already included in nginx's default set, and is currently causing this message to be printed:
> nginx: [warn] duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/conf.d/discourse.conf:4

DEV: Drop wasm type override in nginx config

---

spec/system/user_activity_posts_spec.rb

The test being fixed in this commit was flaking with the following
error:
```
Capybara::Ambiguous:
Ambiguous match, found 2 elements matching visible css ".stream-topic-title .title a[href*='/2']"
```
The regexp match on the `href` attribute has the potential to match
multiple elements if both urls contain the `/#{topic.id}` substring. For
example, both `/t/-/2/2` and `/t/-/1/2` will satisfy the regexp.

DEV: Resolve flaky test due to regexp match

---

plugins/chat/app/models/chat/reviewable_message.rb
plugins/chat/spec/models/chat/reviewable_chat_message_spec.rb

When a flagged chat message has already been deleted, we offer an option in the review queue to agree with the flag and keep the message deleted. However, this option is currently broken due to a missing implementation for the option.
Internal topic: t/152203.

FIX: Make the 'Keep Message Deleted' reviewable option work

---

config/initializers/100-sidekiq.rb
lib/sidekiq/discourse_event.rb
lib/sidekiq/pausable.rb
spec/lib/sidekiq/discourse_event_spec.rb

This commit adds a `:sidekiq_job_error` event which is
triggered when an error is encountered while running a Sidekiq job. The
intent of this change is to complement the `:sidekq_job_ran` event which
can be used with the `:sidekiq_job_error` event to calculate the error
rate for each job.

DEV: Add `:sidekiq_job_error` DiscourseEvent

---

app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/components/search-menu.gjs
app/assets/javascripts/discourse/app/components/search-menu/advanced-button.gjs
app/assets/javascripts/discourse/app/components/search-menu/clear-button.gjs
app/assets/javascripts/discourse/app/modifiers/delayed-destroy.js
app/assets/javascripts/discourse/tests/acceptance/search-mobile-test.js
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/desktop/components/header-search.scss

Follows up [my initial PR](https://github.com/discourse/discourse/pull/31711) on mobile search in header improvements.
1. added `4px` spacing between search input and cancel button
2. increased cancel button size (with padding) to match input height
3. decreased search panel padding by 1/2 from 16px to 8px
4. animation show/hide changed (from vertical to horizontal) and made it quicker (300ms->200ms)
5. set html unscrollable when search panel is open
1. changed `data-test-` value to be consistent with other element's attrs values
2. clear search action tag changed from `<a>` to `<DButton>`

UX: header search mobile support - follow up

---

app/assets/javascripts/discourse/app/components/emoji-picker/content.gjs

Previously this behavior was only on desktop.

UX: auto focus emoji picker input on mobile

---

app/assets/stylesheets/common/d-editor.scss

I think this is causing iOS to zoom in on the composer in some scenarios, and we don't want that:

UX: don't decrease composer monospace font on mobile

---

app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/common/components/welcome-banner.scss
app/assets/stylesheets/mobile/components/welcome-banner.scss

* Hides the welcome banner search in mobile, it's not necessary
since there is the header search
* Fix an issue where the positioning of the search input for
the header on mobile was affecting welcome banner search
* Make the welcome font a bit smaller and with less padding so
it takes up less room on mobile

UX: Welcome bannner and search tweaks for mobile

---

app/assets/javascripts/discourse/app/lib/uppy/composer-upload.js
spec/system/composer/prosemirror_editor_spec.rb
spec/system/page_objects/cdp.rb

Without the `useCapture` as `true` on this `ComposerUpload`'s `addEventListener`, if the clipboard contained both a Files array and a `text/html` item, the paste event would be captured by ProseMirror before being captured by the `ComposerUpload` setup and its `preventDefault` call.

FIX: pasting img on rich editor could be double-processed

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/hashtag.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/heading.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/mention.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/onebox.js
plugins/discourse-local-dates/assets/javascripts/lib/rich-editor-extension.js

We don't want "ghost" `content` within mention/hashtag, as they're already rendering their non-editable content on `toDOM`.
`atom: true` is not necessary for content-less nodes
Re-use existing heading node spec instead of re-creating.
A UX improvement from these changes is a better Cmd-Left/Home navigation when these nodes begin a paragraph and the caret is after them.

UX: prosemirror rich editor nodes cleanup / slightly better UX

---

app/assets/javascripts/admin/addon/services/admin-sidebar-state-manager.js
app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/components/header/hamburger-dropdown-wrapper.gjs
app/assets/javascripts/discourse/app/components/header/icons.gjs
app/assets/javascripts/discourse/app/components/header/sidebar-toggle.gjs
app/assets/javascripts/discourse/app/controllers/application.js
app/assets/javascripts/discourse/app/services/sidebar-state.js
spec/system/viewing_sidebar_spec.rb

This PR allows for other code to force the sidebar, but making the language not admin-specific. There is a general problem to solve of "how can I force the sidebar to appear, while keeping the hamburger menu in the header as-is". This problem is solved for admin interface, but the variable naming made it seem like the logic was directly tied to the admin UI.
It is easy with this change, to have another sidebar manager force the sidebar to be open for a route. Technically it was easy before, but it would look like you were doing awful hacks.

DEV: Refactor forcing admin sidebar logic in hamburger nav mode

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/link.js
spec/system/composer/prosemirror_editor_spec.rb

Avoid auto-linking URLs within code marks
Avoid auto-linking URLs when there's a `` ` `` just before the matched URL, assuming the user is about to type a closing `` ` `` to create a code mark instead.

UX: avoid auto-linking clash with code marks on rich editor

---

plugins/chat/spec/system/rich_editor_extension_transcript_spec.rb
spec/system/page_objects/cdp.rb

This is to try fix this error by sending the keys
on the element itself:
```
Failure/Error: page.send_keys([PLATFORM_KEY_MODIFIER, "v"])
Selenium::WebDriver::Error::StaleElementReferenceError:
stale element reference: stale element not found in the current frame
(Session info: chrome=135.0.7049.84); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
```

DEV: Try fix composer rich text transcript spec

---

app/assets/javascripts/discourse/app/components/create-topic-button.gjs
spec/system/drafts_dropdown_spec.rb
spec/system/page_objects/components/drafts_menu.rb

Reinstates the draft dropdown on private category pages.
Default theme:
Internal ref: /t/151641

FIX: enable drafts dropdown on private categories

---

app/assets/javascripts/admin/addon/routes/admin-customize-themes-show.js
app/assets/javascripts/admin/addon/routes/admin-dashboard.js
app/assets/javascripts/admin/addon/routes/admin-email-templates-edit.js
app/assets/javascripts/discourse/app/components/header.gjs
app/assets/javascripts/discourse/app/controllers/full-page-search.js
app/assets/javascripts/discourse/app/lib/scroll-top.js
plugins/chat/assets/javascripts/discourse/routes/chat.js

This was refactored from an actual Mixin some time back. This PR moves the function to the lib folder and keeps the same logic/interface otherwise.
We'll remove the mixin file once all non-core repos change to use the new file.

DEV: duplicate scroll-top util function to lib and replace current usage with new path

---

app/assets/javascripts/discourse/app/components/group-card.gjs
app/assets/javascripts/discourse/app/components/group-list.gjs
app/assets/javascripts/discourse/app/controllers/groups-index.js
app/assets/javascripts/discourse/app/templates/groups/index.gjs

We need to reuse some of the groups UI in the admin dashboard. This is currently a bit hairy because it's using the old controller + routes + template style design.
This PR extracts to components, `GroupCard`, and `GroupList`, and shifts the logic in there.
Below is a screenshot of a list with twelve cards:

DEV: Convert groups page to components

---

spec/requests/qunit_controller_spec.rb

This test file fails locally if `tmp/theme-transpiler.js` does not exists.
Since the test file stubs the production env, we have to ensure that
`DiscourseJsProcessor::Transpiler.build_production_theme_transpiler` is
run first to mirror the production environment where the theme
transpiler file is built as part of assets precompilation.
Example failure: https://github.com/discourse/discourse/actions/runs/14529161497/job/40766003075
To repro locally, run the following steps: 
1. In your Discourse directory, run `rm -rf tmp`
2. `rspec spec/requests/qunit_controller_spec.rb`

DEV: Fix broken `request/qunit_controller_spec.rb`

---

app/assets/stylesheets/common/base/discourse.scss

After some new changes in the header, the user-status' z-index caused issues
AFAICT there is no need for that z-index to begin with.

FIX: remove z-index from user-status in header

---

bin/turbo_rspec

The `--disable-system-tests` CLI arg does nothing

DEV: Remove broken CLI option in `bin/turbo_rspec`

---

app/assets/javascripts/admin/addon/controllers/admin-groups-index.js
app/assets/javascripts/admin/addon/controllers/admin-groups-settings.js
app/assets/javascripts/admin/addon/controllers/admin-groups.js
app/assets/javascripts/admin/addon/routes/admin-groups-index.js
app/assets/javascripts/admin/addon/routes/admin-groups-settings.js
app/assets/javascripts/admin/addon/routes/admin-groups.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/admin-groups-index.gjs
app/assets/javascripts/admin/addon/templates/admin-groups-settings.gjs
app/assets/javascripts/admin/addon/templates/admin-groups.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/controllers/admin/groups_controller.rb
config/routes.rb

Previously, clicking "Groups" on the admin dashboard would bring you to the public groups page. Historically, the public and admin actions have been mixed together on that page.
This is a bit of a frustrating experience when working on the admin dashboard, and also prevented us from adding a "Settings" tab for group-related site settings.
This PR adds an "admin groups" page, which is just an exact copy of the public groups index for now. This allows us to add the "Settings" tab, and lets us gradually work un disentangling the public- and admin parts of groups.
When you click a group, or click the button to create a new group, you are still brought to the public page of that group. We will work to disentangle these gradually.

DEV: Add dedicated admin groups page

---

.github/workflows/tests.yml
bin/turbo_rspec
lib/turbo_tests/runner.rb

This commit adds a new `--exclude-pattern` CLI option which supports
excluding files using unix style pattern matching.
This is to simplify a couple of situations:
1. Running `bin/turbo_rspec plugin/spec` but we want to exclude all
tests in the `plugin/spec/system` folder.
Example: `bin/turbo_rspec --exclude-pattern="*spec/system*"
plugin/spec`
2. Running `bin/turbo_rspec plugin/*/spec/system` but we want to exclude
tests for a particular plugin.
Example: `bin/turbo_rspec --exclude-pattern="plugins/chat/*"
plugin/*/spec/system`

DEV: Add `--exclude-pattern` to `bin/turbo_rspec`

---

app/assets/javascripts/discourse/app/form-kit/components/fk/collection.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/collection-test.gjs

This is particularly important for array of primitives, eg: `["a", "b", "c"]` where ember will struggle to know it's re-rendering the same object.
The previous code was mostly working by chance as calling index on something almost works for anything in javascript. But since we introduced array of primitives  in collections, we could now end up with an `undefined` value for the items of the collection, and calling `index` on `undefined` would raise an error.
This commit create a more general and explicit solution to this problem.

DEV: generate identifier for collections

---

app/assets/javascripts/discourse/app/components/topic-list/item/replies-cell.gjs
config/locales/client.en.yml

At the moment the reply count is labelled by the topic list's header column, which is good — but we don't actually describe what the link does, so it's a little ambiguous. 
This adds an aria-label to describe the behavior "jump to first post" so it will be read as:
"n replies, jump to first post" 
This provides better coverage for link-to-link navigation because it both describes the number and the function.

A11Y: add aria-label to reply count link in topic list

---

app/assets/stylesheets/common/base/_topic-list.scss

It seems there are some situations where we can get nested paragraph tags in category headings, and in these cases we end up with twice-as-large descriptions. Moving the font-size rule to the parent avoids this.
Before:
After:

UX: avoid nested paragraph tags causing extra large category descriptions

---

bin/turbo_rspec

The `--disable-system-tests` CLI arg does nothing

DEV: Remove broken CLI option in `bin/turbo_rspec` (#32388)

---

lib/trust_level.rb
spec/lib/promotion_spec.rb

Currently, trust level is calculated with this formula: `[granted_trust_level, previous_trust_level,  SiteSetting.default_trust_level].max`
When a user is invited, SiteSetting.default_invitee_trust_level should be respected in that calculation.

FIX: recalculate respects default invitee trust level

---

app/assets/javascripts/admin/addon/templates/backups-index.gjs
app/assets/javascripts/admin/addon/templates/backups.gjs
app/controllers/admin/backups_controller.rb
spec/requests/admin/backups_controller_spec.rb
spec/system/admin_backups_spec.rb
spec/system/page_objects/pages/admin_backups.rb

When backups are disabled, backup files and logs tabs should be hidden. Same for backup and read only button.
Demo
https://github.com/user-attachments/assets/7ce373cc-4fab-4f0f-89ef-d9fc7b889255
https://meta.discourse.org/t/disabling-backups-does-not-remove-item-from-admin-sidebar/36209

FIX: hide unnecessary tabs and buttons when backups disabled

---

.github/workflows/tests.yml
bin/turbo_rspec
lib/turbo_tests/runner.rb

This commit adds a new `--exclude-pattern` CLI option which supports excluding files using unix style pattern matching.
This is to simplify a couple of situations:
1. Running `bin/turbo_rspec plugin/spec` but we want to exclude all tests in the `plugin/spec/system` folder.
Example: `bin/turbo_rspec --exclude-pattern="*spec/system*" plugin/spec`
2. Running `bin/turbo_rspec plugin/*/spec/system` but we want to exclude tests for a particular plugin.
Example: `bin/turbo_rspec --exclude-pattern="plugins/chat/*" plugin/*/spec/system`

DEV: Add `--exclude-pattern` to `bin/turbo_rspec` (#32390)

---

app/controllers/admin/backups_controller.rb
spec/requests/admin/backups_controller_spec.rb

In this PR, we allowed to download backups even if backups are disabled:
https://github.com/discourse/discourse/pull/32396
This PR is fixing bug and allowing email action.

FIX: allow to email backup even if backups disabled

---

spec/models/user_spec.rb

For some reason, not on local, and not on PRs, but in the build pipeline, the precision of the timestamp changes during a database roundtrip, causing the build to fail.
This fixes the build.

DEV: Fix flaky User#silenced_till test

---

app/assets/javascripts/discourse/app/static/prosemirror/core/inputrules.js
app/assets/javascripts/discourse/app/static/prosemirror/extensions/link.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/link-test.js
spec/system/composer/prosemirror_editor_spec.rb

Adds support to creating an "autolink" by explicitly typing the `<https://link>`.
Changes linkification while typing to only act when `markup` is `linkify` (so, not a `[normal](link)` nor an `<autolink>`), and adds a test to make sure `<http://auto.links>` won't convert to a `linkify` while typing.
Avoids linkifying within code when pasting `text/html`.
Removes the `markup: "linkify"` when pasting a URL over a selection, as that will create a `[normal](link)` instead.
Fixes the case on Firefox when you're typing an `example.com` URL mid-paragraph and it stopped the link mark before the last letter, leaving an un-linked dangling `m`.
Also uses a `linkify.test()` call before `linkify.match()` for "best speed" as per https://markdown-it.github.io/linkify-it/doc/#LinkifyIt.prototype.match.

UX: improve input rules for rich editor autolink/linkify

---

app/assets/javascripts/discourse/app/components/header/home-logo-contents.gjs
app/assets/javascripts/discourse/tests/integration/components/home-logo-test.gjs
app/assets/stylesheets/common/base/header.scss

Without a site logo we render a the site name in the header as text, this is a nice fallback!
...but it's marked up as an H1, and having the same H1 on every page means it's not a meaningful page heading and can make headings fairly annoying to navigate using screenreaders and other assistive technologies 
This converts it to a div and ensures that it retains the bold styling previously applied by the heading tag. Font size is already handled by the ID, so there are no visual changes as a result.

A11Y: site-text-logo should not be an H1

---

spec/support/system_helpers.rb

We are seeing test timeouts on CI due to attempts to download the minio
binaries while the tests are running. Example backtrace:
```
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `wait_readable'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `rbuf_fill'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:164:in `read'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/net-http-0.6.0/lib/net/http/response.rb:723:in `read'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/net-http-0.6.0/lib/net/http/response.rb:631:in `read_chunked'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/net-http-0.6.0/lib/net/http/response.rb:595:in `block in read_body_0' …
```

DEV: Avoid installing minio binaries in CI

---

app/assets/javascripts/admin/addon/components/admin-config-areas/flags.gjs
app/assets/javascripts/admin/addon/components/admin-flags-form.gjs
app/assets/javascripts/admin/addon/templates/config-flags.gjs
app/assets/javascripts/discourse/app/components/d-page-action-button.gjs
app/assets/javascripts/discourse/tests/integration/components/d-page-header-test.gjs
spec/fabricators/flag_fabricator.rb
spec/services/flags/destroy_flag_spec.rb
spec/system/admin_flags_spec.rb
spec/system/page_objects/modals/flag.rb
spec/system/page_objects/pages/admin_flag_form.rb
spec/system/page_objects/pages/admin_flags.rb

This particular system test is taking a long time (~20 seconds) on CI
because it is doing many full page loads. This commit refactors the test
to be more efficient about the number of full page loads triggered by
the tests thus reducing the runtime by half.
One of the test is taking 28 seconds out of the 13 mins system tests run which is about 3.5% just for a single test.

DEV: Simplify "Admin Flags Page" system test to reduce runtime duration

---

spec/system/page_objects/pages/topic.rb

Visiting `/t/-/<topic_id>` results in an extra redirect request.

DEV: Avoid unnecessary redirect in system tests when visiting a topic

---

spec/system/login_spec.rb
spec/system/signup_spec.rb

This commit applies a similar optimisation as
d0d755ad8c478db45e3298df9de1cdabe59d9592.
Basically, the `full_page_login` site setting is going to be dropped
this week and these extra system tests we are running due to this site
setting is accounting for a significant percentage of the overall
runtime for core system tests.
The PR to remove the `full_page_login` site setting is at https://github.com/discourse/discourse/pull/32189 and scheduled to be merged by us on 29th April.

DEV: Reduce runtime of `spec/system/(login|signup)_spec.rb`

---

plugins/chat/assets/javascripts/discourse/modifiers/chat/resizable-node.js

The problem is mainly that we also have a css animation made from js which was setting a different width for the panel, so the `style.width = "auto"` was not overriding this part. This animation happens in a parent component after `didResizeContainer` is called, so it could be fine most of the times, but the simpler change is to ensure, panel resize, or window resize ends up in the same codepath so whatever the developer decides to do in `didResizeContainer` hook will be applied in both cases.
No test as it's fairly hard to test and would require a complex system spec setup.
It avoids this situation where the side panel is larger than viewport after window resize:

FIX: correctly reset panel when resizing window

---

Gemfile.lock
spec/support/system_helpers.rb

The binary is already preinstalled in the Docker image so we don't have to attempt to install it again.
Installing the minio binary is taking more than 45 seconds consistently causing the test to timeout: https://github.com/discourse/discourse/actions/runs/14638755310/job/41075932169

DEV: Don't attempt to install minio binary in CI

---

app/assets/javascripts/discourse/app/components/composer-body.js
app/assets/stylesheets/common/base/compose.scss
plugins/chat/assets/stylesheets/common/chat-height-mixin.scss

This PR will allow composer to hover over chat, as it does in the rest of the app.
FYI: on dragging there is sometimes a jitter hover effect of chat action messages, but this is an edge case and would be encountered very rarely
**After**
**Before**

UX: Do not let composer affect chat window height

---

lib/svg_sprite.rb
vendor/assets/svg-icons/discourse-additional.svg

Meta: https://meta.discourse.org/t/icon-missing-in-admin-panel-after-updating-discourse-today/363295
The `discourse-table` icon usage was introduced in https://github.com/discourse/discourse/commit/464726d973a267802bbe9c06653f11cfd9d0d93a.
However, the SVG doesn't exist in core, but instead in the [AI plugin](https://github.com/discourse/discourse-ai/blob/main/svg-icons/icons-sprite.svg?short_path=9d0511c).
The PR adds this SVG icon to the core.

UX: Add missing `discourse-table` SVG icon

---

app/assets/javascripts/discourse/app/components/categories-boxes-with-topics.gjs
app/assets/javascripts/discourse/app/components/categories-boxes.gjs

This was missed when adding category badges in #32109. Category title badges are now added when the site setting for `Desktop category page style` or `Mobile category page style` is set to either:
- Boxes with Subcategories
- Boxes with Featured Topics

FIX: add category title badges to boxed layout

---

spec/support/system_helpers.rb
spec/system/email_change_spec.rb
spec/system/forgot_password_spec.rb
spec/system/user_page/user_preferences_security_spec.rb

Instead of having each test go incur the overhead of having to go
through the actual user flow to register a security key, we can generate
the WebAuthn credentials on the server side and adds it to the virtual
authenticator.

DEV: Introduce `with_security_key` system test helper

---

app/assets/javascripts/discourse/app/components/category-title-link.gjs

Allows themes and components to opt out of category title badge styling when using the `CategoryTitleLink`.
Using `@unstyled` allows the previous text only category name that we had prior to #32109:
```
<CategoryTitleLink @category={{c}} @unstyled={{true}} />
```
_Note: we don't appear to have a test for this specific component and this change just allows us to use it in the same way it was previously (before adding badges). Maybe later we can go back and add additional tests._

DEV: make category title badges optional

---

.github/workflows/tests.yml

While the step to run plugin system tests has been set with a timeout of
30 minutes, the overall job timeout was only set to 20 minutes. As a
result, we are starting to see the plugin system tests job fail due to
the job exceeding the 20 minutes timeout.
Example of plugin system tests exceeding 20 minutes timeout: https://github.com/discourse/discourse/actions/runs/14665943355/job/41160611627

DEV: Bump tests workflow build job timeout for plugin system tests

---

.github/workflows/tests.yml

Merging the core annotation check into the core backend job reduces the
number of runners required per workflow from 15 to 14. Before this
change, the core annotations job occupies a runner for about 1 min
30 secs in order to spend 9 seconds running the core annotations check.

DEV: Stop running core annotations check as a standalone job

---

config/locales/server.en.yml
config/site_settings.yml

This will show the experimental rich_editor setting and admins
can turn it on for their site. It is still marked experimental
because there are some features missing, but it works well for
95% of cases.

UX: Unhide the rich_editor site setting

---

app/assets/javascripts/discourse/app/templates/full-page-search.gjs

This span renders even when the plugin outlet isn't being used, so it can get in the way. I did a quick search and don't see it targeted anywhere obvious (it would be difficult to do without a unique class anyway)

DEV: remove wrapping span from full-page-search-below-search-info outlet

---

app/assets/javascripts/discourse/app/lib/uppy/composer-upload.js
app/assets/stylesheets/common/rich-editor/rich-editor.scss

After adjusting an overflow on the rich editor placeholder, it started being cut on mobile, as the parent paragraph can be smaller than the area the placeholder takes.
This fixes it by returning the `position: relative` to the `.ProseMirror` editor, which also fixes some weird positioning errors for "fake" cursors (gap cursor, codemark cursor, drop cursor) and absolute-positioned elements that relied upon the editor being `position: relative`.
Before
After

UX: fix rich editor placeholder being cut on mobile

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/link.js
spec/system/composer/prosemirror_editor_spec.rb

Fixes an edge case when backspacing at the end of a link mark, the entire link was getting lost – the test may help understanding.
The main fix is making sure the `markup` attr falls back to `null` if it comes as empty `""` string from the markdown-it tokens.
I didn't investigate too far as this solved it for us, but for some reason the link mark was getting lost when text node after the mark was being merged with the text node with the mark containing the "" markup.
The rest of the changes are `DEV`. `isPlainURL` is not necessary anymore as we're tracking the markup to determine if it should be serialized as an `<https://auto.link>`.

FIX: rich editor link backspace edge case

---

app/controllers/categories_controller.rb
spec/requests/categories_controller_spec.rb

This is a bug introduced by me by thinking the lonely operator is redundant here. It is not. Sometimes the param keys are not sent, and when they aren't we should preserve the existing attribute value, not null it out.
This PR fixes that and also adds a regression test explaining why it's needed.

FIX: Don't null out category attributes if no param keys

---

app/assets/javascripts/discourse/app/models/user.js
app/assets/javascripts/discourse/tests/acceptance/banner-test.js

Meta: https://meta.discourse.org/t/clicking-x-to-close-welcome-banner-does-not-work-until-page-refresh/363222
The site banner is not hidden when a logged-in user clicks on the close button.
This PR adds `@tracked` to the User model  `dismissed_banner_key` property so it is autotracked correctly by `DiscourseBanner` [`visible` getter](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/components/discourse-banner.gjs#L34-L49).

FIX: Ensure site banner hides when user clicks on close button

---

lib/stylesheet/manager.rb

This is mainly used for the test environment where
`Discourse.current_hostname` and `GlobalSetting.relative_url_root` can
be stubbed.
We don't really need a test here since this doesn't really affect the production environment.

DEV: Account for relative url root in `Stylesheet::Manager` cache keys

---

app/assets/javascripts/admin/addon/lib/site-setting-filter.js
app/assets/javascripts/admin/addon/lib/site-setting-matcher.js

This change does a couple of things.
**Change in behaviour:**
- Matches on the site setting name and keywords now get a higher ranking in search results.
- When counting gaps for ranking fuzzy matches, we no consider the smallest number of gaps.
**Example:**
Filter: `abc`
Setting: `axabxc`
Previously this would have been counted as two gaps (`a__b_c`). It is now counted as one gap (`ab_c`).
**Code organization:**
- Extract a separate `SiteSettingMatcher` object for the matching logic.
- Flatten some conditionals to make control flow clearer.
- Higher weight now means higher in search results.

DEV: Improve site setting search ranking

---

app/assets/stylesheets/common/components/welcome-banner.scss

The css class selector `d-icon-search` refers to a deprecated icon name, this PR updates it to the correct name.

DEV: update styling class reference to d-icon-magnifying-glass

---

config/locales/client.en.yml

We don't do tag intersections when filtered to a category, so these can always be singular 
follow-up to https://github.com/discourse/discourse/commit/ca658a8bb093c82410927d1fa29e5ef1940260b7

A11Y: use singular tag in accessible category_tag string

---

app/helpers/common_helper.rb
config/locales/server.en.yml
config/site_settings.yml

Need the script to migrate existing settings to come together with this. 🙏

Revert "DEV: Remove the word tags from adobe_analytics_tags_url"

---

app/assets/javascripts/discourse/app/components/emoji-picker/content.gjs
app/assets/javascripts/discourse/tests/integration/components/emoji-picker-test.gjs

This will allow the CDN to be used for custom emojis.

DEV: correctly use emoji urlFor to render emojis

---

lib/discourse_tagging.rb
spec/lib/discourse_tagging_spec.rb
spec/support/helpers.rb

Allow creating a tag group with tags that are visible to everyone but can be used by admin only.

FIX: allow tags to be restricted to admin only

---

lib/version.rb

Version bumps for main: v3.5.0.beta3, v3.5.0.beta4-dev

---

lib/version.rb

Version bump for stable: v3.4.3

---

plugins/automation/lib/discourse_automation/event_handlers.rb

Instead of looking at post count that is cached, only ever look at the post_number
which is guaranteed to be correct

DEV: add extra safety around original post only implementation

---

app/assets/stylesheets/common/base/discourse.scss

Previously only mobile had body background, so that change made it cover the html backround (as seen on meta)

FIX: Background body regressed in #32517

---

app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
app/assets/javascripts/discourse/app/helpers/number.js
app/assets/javascripts/discourse/app/lib/formatter.js
app/assets/javascripts/discourse/tests/unit/lib/formatter-test.js
app/models/topic_link.rb

Meta: https://meta.discourse.org/t/suggestion-for-fixing-the-inaccurate-link-counter-value/359527
The link count in the topic map summary is limited to 50 on the backend. 
However, the frontend displays exactly 50, even when more links exist. 
This can be misleading as users might assume there are no additional links.
This PR updates the logic by fetching one extra link from the database and appending a `+` to the count when there are more than 50 links.
Before:
After:

UX: Append '+' to link count if above threshold in topic map

---

app/assets/javascripts/admin/addon/components/admin-search.gjs
app/assets/javascripts/admin/addon/components/modal/admin-search.gjs
app/assets/javascripts/admin/addon/services/admin-sidebar-state-manager.js
app/assets/javascripts/discourse/app/components/sidebar/panel-header.gjs
app/assets/javascripts/discourse/app/components/sidebar/search.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-panel.js
app/assets/javascripts/discourse/tests/acceptance/admin-site-settings-test.js
app/assets/stylesheets/admin/search.scss
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/sidebar.scss
config/locales/client.en.yml
spec/system/admin_search_spec.rb
spec/system/admin_sidebar_navigation_spec.rb
spec/system/page_objects/components/navigation_menu/sidebar.rb
spec/system/page_objects/modals/admin_search.rb

In this PR we hide search input.
https://github.com/discourse/discourse/pull/32485
However, search input is much more intuitive. Therefore, input was brought back and opens modal on click. In addition, search link was removed.
Demo:
https://github.com/user-attachments/assets/5b193fab-918e-4a4d-9fdd-97c92c534850
Mobile:

UX: display search input and open modal on click

---

.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/tests.yml

`github.ref_name` is
> The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, feature-branch-1.
> 
> For pull requests, the format is <pr_number>/merge.
Not sure why we use `github.run_number` when it is a unique number for
each run of a workflow. `github.head_ref` is only present on pull request events so it is blank when the workflow is ran on 
other branches.
By updating the key to `github.ref_name` + `github.job` we ensure that
only one workflow will be running for a given PR or branch.

DEV: Update workflow concurrency controls to use `github.ref_name`

---

app/assets/stylesheets/desktop.scss
app/assets/stylesheets/desktop/category-list.scss
app/assets/stylesheets/desktop/latest-topic-list.scss
app/assets/stylesheets/mobile.scss
app/controllers/bootstrap_controller.rb
app/models/theme.rb
app/views/common/_discourse_preload_stylesheet.html.erb
app/views/common/_discourse_stylesheet.html.erb
lib/stylesheet/importer.rb
lib/stylesheet/manager.rb
lib/stylesheet/manager/builder.rb
lib/stylesheet/manager/scss_checker.rb
spec/lib/discourse_spec.rb
spec/lib/scss_checker_spec.rb
spec/lib/stylesheet/compiler_spec.rb
spec/lib/stylesheet/manager_spec.rb
spec/models/theme_spec.rb
spec/requests/safe_mode_controller_spec.rb

Previously we were compiling core and theme CSS into two targets: Desktop and Mobile. The majority of both files was the 'common' css. This commit splits those common styles into their own targets so that there is less duplication. This should improve compilation times + cache reuse, as well as opening the door for experiments with media-query-based mobile-modes.
The only functional change is that we can no longer use `@extend` to copy 'common' rules in core to mobile/desktop. This is probably for the best. Duplication and/or mixins are a more native-css pattern for this.
Plugins already have a common / mobile / desktop pattern, so are unchanged by this commit.

DEV: Compile 'common' CSS into own asset

---

config/locales/client.en.yml

`Search everything` was a bit too big.
Before:
After:

FIX: shorten search everything to search

---

app/assets/javascripts/discourse/app/static/wizard/components/fields/image.gjs
docs/ADMIN-QUICK-START-GUIDE.md
spec/system/page_objects/pages/wizard.rb
spec/system/wizard_spec.rb

Bug introduced in this commit - https://github.com/discourse/discourse/commit/e41897a3066
`imagePreviews` already returns component classes.
I tried:
`return getOwner(this).resolveRegistration("component:${id}");` but in wizard `getOwner(this)` throws error.
In addition, links to logo page in admin guide were fixed.

FIX: wizard logo preview

---

app/assets/javascripts/discourse/app/components/discovery/layout.gjs

Even when these plugin outlets are unused we end up with empty spans in the layout, which can get in the way (especially for grid and flex layouts where empty containers are not collapsed). 
These are fairly hard to target without classes present anyway, they'd have to be picked up with `:has()` or something like `#main-outlet > span`. I did a quick spot check of themes/components that use these outlets in http://github.com/discourse and I didn't see any obvious cases where they were being targeted. 
In any cases where the removal does cause issue, the theme can be updated to target a container added by it, or a wrapping `span` can be added there.

DEV: remove wrapping spans from #main-outlet plugin outlets

---

app/assets/stylesheets/common/base/category-list.scss

UX: fix long category name overflow in category boxes

---

app/assets/stylesheets/common/base/login-signup-page.scss

These styles should generally apply to the invite page as well — fixes some inconsistencies, including this issue reported here: https://meta.discourse.org/t/user-fields-at-signup-visual-bug-when-invited-vs-regular-signup/364488
Before: 
After:

UX: apply signup page styles to invite page

---

app/controllers/topics_controller.rb
app/services/destroy_task.rb
app/services/group_message.rb
app/services/user_destroyer.rb
config/locales/server.en.yml
lib/imap/sync.rb
lib/post_destroyer.rb
lib/seed_data/topics.rb
spec/lib/imap/sync_spec.rb
spec/lib/post_destroyer_spec.rb
spec/models/post_spec.rb
spec/requests/reviewable_claimed_topics_controller_spec.rb
spec/requests/topics_controller_spec.rb
spec/serializers/topic_view_details_serializer_spec.rb
spec/serializers/web_hook_post_serializer_spec.rb
spec/services/username_changer_spec.rb
spec/system/topic_page_spec.rb

There are instances of posts being deleted by `system_user` where the context is left blank in the staff action logs, leading to confusion about why exactly they have been deleted.
This change deprecates using the `PostDestroyer` as `system_user` without providing a `context`, and adds a context to all call sites currently missing it in core. Plugins to be done after this is merged.

DEV: Don't allow context-free system post destruction

---

app/assets/javascripts/admin/addon/components/admin-config-areas/color-palette.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/color-palettes.gjs
app/assets/javascripts/admin/addon/components/modal/color-scheme-select-base.gjs
app/assets/javascripts/admin/addon/routes/admin-config-color-palettes-show.js
app/assets/javascripts/admin/addon/routes/admin-config-color-palettes.js
app/assets/javascripts/admin/addon/routes/admin-route-map.js
app/assets/javascripts/admin/addon/templates/config-color-palettes-show.gjs
app/assets/javascripts/admin/addon/templates/config-color-palettes.gjs
app/assets/stylesheets/admin/admin_config_color_palettes.scss
app/controllers/admin/config/color_palettes_controller.rb
config/routes.rb
spec/system/admin_color_palette_config_area_spec.rb
spec/system/admin_color_palettes_config_area_spec.rb
spec/system/page_objects/modals/create_color_palette.rb
spec/system/page_objects/pages/admin_color_palette_config_area.rb
spec/system/page_objects/pages/admin_color_palettes_config_area.rb

Follow-up to https://github.com/discourse/discourse/pull/31742
This PR adds a color palettes list to the new color palette edit page that was introduced in the linked PR to allow navigating between color palettes. It reuses the same UI that we already have in the legacy color palette UI (`/admin/customize/colors`), but we may redesign the page in the future.
Screenshot:

FEATURE: Add color palette list selection to new UI

---

app/assets/stylesheets/common/rich-editor/rich-editor.scss
plugins/footnote/assets/stylesheets/footnotes.scss

Moves `position: relative` from the editor itself to the scrollable container, to avoid the footnote sub-editor scrolling with the content. This also affects the gap cursor, which should scroll with the content, so it is now changed to `position: sticky`.
Fixes the z-index for the footnote sub-editor - it was being rendered behind code blocks.

UX: rich editor footnotes position

---

lib/version.rb

Version bumps for main: v3.5.0.beta4, v3.5.0.beta5-dev

---

docs/ADMIN-QUICK-START-GUIDE.md

The `/my/invited` page is kind of jarring to send a new admin to? 
Before, directs to `/my/invited`
After, `/new-invite` (opens the modal on the homepage)

UX: link to `/new-invite` in quick start guide

---

app/assets/stylesheets/common/rich-editor/rich-editor.scss

The `.ProseMirror-container` is scrollable, and it being `position: relative` cuts mentions/hashtags/etc autocompletes. Removing it _should_ be safe and `.d-editor-textarea-wrapper` (a name we should change eventually btw...) becomes the new anchor for absolute positioning.
Before
After

FIX: autocomplete being cut on rich editor

---

app/assets/javascripts/discourse/app/services/composer.js

The rich editor is loaded asynchronously, so when `allowPreview` starts as `true`, if we're opening the composer for the 1st time, ProseMirror dependencies will be loaded async and while the rich editor is fully loaded, the composer animates from having a preview to not having one, shrinking in width.
This changes the `allowPreview` to be default `false`, so the animation never happens – when the default composer editor is set to the Markdown editor, it'll instantly and synchronously set the tracked property, before any animation kicks in.

UX: composer starts with allowPreview default false

---

app/models/optimized_image.rb
db/migrate/20250505050610_optimized_image_format_index.rb
spec/models/optimized_image_spec.rb

Previous to this change when we used to specify format it could get an image
in the incorrect format.
Also... allows image magick to decode svg
---
There remains a bug where the crop / resize information is not stored in optimized images
this means that sometimes when asking for a cropped image you may get a resized one.

 FIX: key optimized images on format

---

app/assets/javascripts/admin/addon/routes/admin-badges/show.js
app/assets/javascripts/discourse/app/models/badge.js

In the `/admin/badges` view, badges are showing as enabled even when they are verifiably disabled in the database.
This is happening because the defaults (needed to render the "new badge" form) are overwriting the actual value.
Since the `enabled` default is only used for "new badge" form, move it to the route where the other "new badge" defaults are being set.

FIX: Badge not showing as disabled when it is

---

.github/workflows/licenses.yml
.github/workflows/linting.yml
.github/workflows/migration-tests.yml
.github/workflows/tests.yml

This reverts commit 427d4d2b53fcddf771e450ebaa3dbf5140c9fb7a.
This prevents us from knowing which commit broke the build. Revert for
now while we figure out a better solution.

Revert "DEV: Update workflow concurrency controls to use `github.ref_name` (#32524)"

---

app/assets/javascripts/discourse/app/lib/sidebar/admin-nav-map.js
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js

We have gradually moved the pages out of the `Account` section in the admin sidebar. This moves the last one, `Backups`, to the `Advanced` section, and entirely removes `Account`.

DEV: Move admin backups page to Advanced section

---

app/assets/javascripts/discourse/app/components/decorated-html.gjs
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
plugins/checklist/assets/javascripts/discourse/initializers/checklist.js

This PR adds a basic fallback to prevent errors for extensions accessing `helper.widget` when using `api.decorateCookedElement`.
The purpose of the fallback is provide access to `.widget.attrs`and `scheduleRerender()` which are common scenarios. 
Since the call to the callback happens only when rendering the auto mode of the Glimmer Post Stream can't detect the existence of these customizations. The PR also adds a deprecation notice in the console.
There are no additional tests because the existing ones should cover the existing functionality

DEV: add fallback for calling `helper.widget` decorating cooked content when using the Glimmer Post Stream

---

app/assets/javascripts/admin/addon/components/admin-search.gjs
app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/tests/fixtures/admin-search-fixtures.js
app/assets/javascripts/discourse/tests/integration/components/admin-search-test.gjs
app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js
app/assets/stylesheets/admin/search.scss

Instead of simple match keywords, search login was a bit enhanced by calculating score.
1. 20 points if item label starts with searched phrase. This is to prioritize `automation` when `auto` is typed;
2. 10 points for each exact word matches keywords. This is to prioritize `discourse-ai` when `ai` is typed;
3. 5 points if matches fallback to original phrase match.
In addition, stop showing loading sign when modal is opened.

FIX: improvements for admin search

---

app/assets/javascripts/discourse/tests/unit/lib/input-utils-test.js
app/assets/javascripts/select-kit/addon/components/multi-select.gjs
app/assets/javascripts/select-kit/addon/components/select-kit.js
app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-header.js
app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.gjs
app/assets/javascripts/select-kit/addon/components/single-select.gjs
app/assets/javascripts/select-kit/addon/lib/input-utils.js
app/assets/javascripts/select-kit/addon/mixins/utils.js

This PR replaces the set of methods related to validation and normalization of input values in the select-kit utils mixin with simple exported functions from a input-utils lib file. 
We maintain the `_normalize` method on the select-kit component because there are external repos dependent on that part of the interface.
We'll replace the remainder of the mixin with another utils lib file in a separate PR.

DEV: replace select-kit utils mixin methods with input-utils lib

---

app/models/user.rb

Chat is currently broken in local development if anonymous mode is enabled in site settings. This is happening after #32416. One of the `strict_loading` directives in `ChannelFetcher` is trickling down to an anonymous user check.
We don't need to enforce `strict_loading` on this 1-to-1 association that's only used in a few code paths, so mark it as `strict_loading: false` on the `User` model.
**Before:**
**After:**

FIX: Don't enforce strict loading on anon user main record

---

app/models/remote_theme.rb
config/site_settings.yml
db/migrate/20250507013646_remove_theme_download_screenshots_site_settings.rb
spec/models/remote_theme_spec.rb

Enable theme screenshots to everyone

DEV: remove theme_download_screenshots site setting

---

lib/pretty_text/helpers.rb
spec/lib/pretty_text/helpers_spec.rb

`hashtag_lookup` fails if called with a deleted user's ID. This change defaults to system user if the user does not exist.

FIX: Ensure `hashtag_lookup` falls back to system user if post user is deleted

---

spec/rails_helper.rb

It was not working locally and should just be less wasteful.

DEV: move file instead of rewriting it

---

app/assets/javascripts/discourse/app/components/decorated-html.gjs
app/assets/javascripts/discourse/app/lib/plugin-api.gjs
app/assets/javascripts/discourse/app/widgets/decorator-helper.js
app/assets/javascripts/discourse/app/widgets/post-stream.js
app/assets/javascripts/discourse/tests/integration/components/decorated-html-test.gjs
plugins/discourse-lazy-videos/assets/javascripts/initializers/lazy-videos.gjs

Modernizes the renderGlimmer API to use Glimmer components, replacing deprecated ember-cli-htmlbars templates. Adds deprecation warnings for invalid parameters and improves compatibility with the new Glimmer Post Stream API.

DEV: Refactor lazy-video initialization for Glimmer compatibility

---

app/assets/javascripts/discourse/app/components/d-navigation.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js

On mobile we remove the create topic button label:
and we don't have a great way to add it back (https://meta.discourse.org/t/new-topic-button-hidden-text/364902) 
this will allow the translation to be set for both mobile and desktop like this: 
```js
import { apiInitializer } from "discourse/lib/api";
export default apiInitializer((api) => {
api.registerValueTransformer("create-topic-label", ({ value, context }) => {
return context.defaultKey;
});
});
```
and also grants the flexibility to have a custom labels for mobile and desktop

DEV: add create-topic-label value transformer

---

app/assets/javascripts/discourse/app/components/user-fields/text.gjs
spec/system/signup_spec.rb

Reported in https://meta.discourse.org/t/signup-instructions-arent-showing-for-text-custom-user-fields/359935?u=rishabh

UX: Include custom text field description in signup form

---

bin/ember-cli

Users won't be able to use video locally but we think it's not necessary for now. This could also cause permissions errors on CI as deps require sudo to be installed.

DEV: remove deps

---

app/assets/stylesheets/common/base/login-signup-page.scss

UX: Do not reserve space for the tip message on the signup page

---

app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js

Add 20 points for matched pages to move them higher.
Before:
After:

FIX: prioritize pages over other categories in admin search

---

app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show.js
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes.rb

When a theme is deleted, we should redirect to new themes page.

FIX: redirect to new themes page after deletion

---

plugins/chat/lib/chat_sdk/thread.rb
plugins/chat/spec/lib/chat_sdk/thread_spec.rb

If a user was using invalid values for the contract we would return "Unexpected error", which is incorrect given we know the exact error. The user will now get the following exception: "Page size must be less than or equal to 50"

DEV: correctly returns contract error
