discourse/discourse

app/assets/javascripts/discourse/app/components/local-login-form.gjs

Reported here: https://meta.discourse.org/t/autofill-with-username-in-forgot-password-modal/365310
When `hide_email_address_taken` is enabled, we don't want to populate the username in the forgot email input, because we require an email address. This will remove username content that doesn't look like an email when that site setting is enabled.
Before (username populated when email required): 
After (username not populated, email is):

UX: don't always fill username for forgot password

---

app/assets/javascripts/discourse/app/components/post-list/index.gjs
app/assets/javascripts/discourse/app/controllers/group-activity-posts.js

As reported: https://meta.discourse.org/t/endless-spinning-on-user-activity-of-user-without-activity/365313
If a user has no posts, their post list will show a loading spinner indefinitely 
This is because if there are no posts we never set `canLoadMore` or `loading` to `false`
If we always check for new posts we avoid the issue.

DEV: Remove post length check to allow loading to end

---

app/assets/javascripts/admin/addon/services/admin-sidebar-state-manager.js

When we create a custom homepage using the `custom_homepage` modifier we can hide the sidebar using `{{hideApplicationSidebar}}` in the template — this forces the hamburger dropdown to appear in the header.
This creates an issue when navigating from the custom homepage to the admin area, because when the route transitions the hamburger menu isn't closed... and at this point, it cannot be closed at all. The `clickOutside` listener from the open menu is calling `toggleNavigation`, which is now the sidebar... so instead of closing the hamburger menu, it toggles the sidebar and prevents other elements from being clicked (because the `clickOuside` listener is only removed when the hamburger menu is destroyed).
This change ensures that when the admin sidebar is forced, the hamburger menu will …

UX: always close hamburger menu when navigating to admin

---

config/initializers/100-i18n.rb

When Translation Overrides are changed, a message is sent on the `/i18n-flush` channel to ensure all running unicorns flush their caches. This message is not received in a database-specific context, so running `ExtraLocalesController.clear_cache!` was only affecting the default site in a multisite cluster. This commit updates it to flush caches for all sites.

FIX: Purge ExtraLocalesController cache correctly for multisite

---

app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js

In this PR, test was removed
https://github.com/discourse/discourse/pull/32639
To be sure result are consistent, we need to define a data set which will confirm that the page is getting bonus points.

DEV: bring back admin search page priority test

---

config/site_settings.yml

We are merging the [add-groups-to-about](https://github.com/discourse/discourse-add-groups-to-about-component/) theme component into core. As per protocol, we'll use a hidden site setting to facilitate the switchover.

DEV: Add a flag to facilitate merging about groups into core

---

config/site_settings.yml

We just added this site setting to be used for switchover as we merge a theme component into core. However, as it wasn't marked `client: true`, the theme component cannot read it. 🤦

DEV: Expose show_additional_about_groups to client

---

lib/email_updater.rb
spec/lib/email_updater_spec.rb

Previously when changing back to the same email (ie. change to new email, then change back again) we can easily end up showing the incorrect old email.  Passing the incorrect old email causes an error as it can't be found:
```
@user.user_emails.find_by(email: old_email).update!(email: new_email)
```
This is because we only searched for a combination of `user_id` and `new_email` which can load an older change from the database. By using the current email address when finding / initializing the `EmailChangeRequest` we can prevent this issue as we will be creating a new entry rather than loading an outdated one.

FIX: ensure old email set correctly when updating email

---

app/assets/javascripts/discourse/app/components/post/meta-data/date.gjs
app/assets/javascripts/discourse/app/components/post/small-action.gjs
app/assets/javascripts/discourse/app/lib/post-cooked-html-decorators/mentions.gjs
app/assets/javascripts/discourse/app/lib/user-status-message.js
app/assets/javascripts/discourse/app/models/post-stream.js
app/assets/javascripts/discourse/tests/acceptance/post-inline-mentions-test.js
app/assets/javascripts/discourse/tests/integration/components/post/post-test.gjs
plugins/chat/test/javascripts/components/chat-channel-test.gjs

- When using the Glimmer Post Stream, ensure the status wrapper is only rendered for mentions of users with a status set.
This prevents an empty wrapper from adding a small blank space at the end of the mention.
- Ensures the post's user field in initialized with the `avatar_template` in the PostStream to prevent missing avatar on small actions
- Fix an issue where the path would be incorrectly linked on small actions 
- Fix an issue where the relative timestamp would be incorrectly displayed in wiki posts

DEV: Fix small issues in the Glimmer Post Stream

---

plugins/chat/assets/javascripts/discourse/modifiers/chat/on-long-press.js
plugins/chat/spec/system/page_objects/chat/chat_channel.rb
plugins/chat/spec/system/page_objects/chat/components/message.rb
plugins/chat/spec/system/page_objects/chat/components/messages.rb
plugins/chat/spec/system/react_to_message_spec.rb

These changes have been made for playwright as it was hard to test a long press event on playwright given `click` won't trigger `touchstart` even with `isMobile:true` and `hasTouch:true`. You have to use `tap`, but you don't have the `delay` option on tap, so you can't make it a long tap.
Sadly this code is apparently not working correctly on Android 15. This commit will revert the modifier to what it was before and is relying on native JS to trigger the fake long press in specs, which seems to work nicely.
This commit also attempts to centralize the actions on messages in page objects to avoid code duplication.

DEV: revert long press changes

---

app/assets/javascripts/discourse/app/lib/media-optimization-utils.js

Switches to using `URL.createObjectURL` for better support of very large images (30Mb+). Using blob URLs is more memory-efficient and on testing, handles a 90Mb file just fine (previously, it would fail and skip optimization).

DEV: Further optimize large image uploads on iOS

---

spec/support/shared_examples/core_features.rb
spec/system/composer_spec.rb
spec/system/page_objects/components/composer.rb
spec/system/page_objects/pages/search.rb
spec/system/page_objects/pages/topic.rb

Doing a full page load in system test is expensive and takes about 1
second on average. Since this shared example is being run across 70 official
plugins, the additional time to execute these full page loads adds up.
Therefore, we are trading off some readability here for CI runtime.
Before:
```
Randomized with seed 7202
..................
Finished in 21.26 seconds (files took 1.72 seconds to load)
18 examples, 0 failures
```
After:
```
Randomized with seed 7202
........
Finished in 14.28 seconds (files took 1.74 seconds to load)
8 examples, 0 failures
```

DEV: Speed up "having working core features" shared example by ~30%

---

spec/system/page_objects/pages/search.rb

If the field had the value: "tags:" we would end up with "tag1tags:"

DEV: ensures type_in_search appends

---

lib/discourse_plugin_registry.rb
spec/lib/freedom_patches/translate_accelerator_spec.rb

Running this spec locally I was getting an error:
```
1) translate accelerator plugins loads plural rules from plugins
Failure/Error: raise "Clearing modifiers during a plugin spec run will affect all future specs. Use unregister_modifier instead."
RuntimeError:
Clearing modifiers during a plugin spec run will affect all future specs. Use unregister_modifier instead.
```
On top of this, this spec was flakey, Im not sure this is going to fix flakyness, but this seems like a good first step.

DEV: adds unregister_locale

---

app/assets/javascripts/admin/addon/components/flag-user.gjs
app/assets/javascripts/admin/addon/templates/search-logs-term.gjs
app/assets/javascripts/discourse/app/components/featured-topic.gjs
app/assets/javascripts/discourse/app/components/group-manage-logs-row.gjs
app/assets/javascripts/discourse/app/components/mobile-category-topic.gjs
app/assets/javascripts/discourse/app/components/modal/history/revision.gjs
app/assets/javascripts/discourse/app/components/relative-date.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/blurb.gjs
app/assets/javascripts/discourse/app/components/topic-list/featured-topic.gjs
app/assets/javascripts/discourse/app/components/user-menu/profile-tab-content.gjs
app/assets/javascripts/discourse/app/components/user-preferences/user-api-keys.gjs
app/assets/javascripts/discourse/app/helpers/age-with-tooltip.js
app/assets/javascripts/discourse/app/helpers/bound-date.js
app/assets/javascripts/discourse/app/helpers/format-age.js
app/assets/javascripts/discourse/app/lib/formatter.js
app/assets/javascripts/discourse/app/templates/group-index.gjs
app/assets/javascripts/discourse/app/templates/group-requests.gjs
app/assets/javascripts/discourse/app/templates/user/collapsed-info.gjs
plugins/styleguide/assets/javascripts/discourse/components/sections/organisms/user-about.gjs

…and just leave `ageWithTooltip` helper (and `RelativeDate` component, replacing its implementation with that helper)
1. we don't need three helpers for the same thing
2. replacing the component impl might fix a bug with post timestamps in the glimmer post implementation 🤞

DEV: Deprecate boundDate and formatAge helpers

---

spec/system/composer/review_media_unless_trust_level_spec.rb

Attempts to look from the page instead of the d-editor-preview which might be recreated when updating the image.
This spec is often flaky atm with this error:
```
Failure/Error: super
Playwright::Error:
TypeError: Cannot read properties of null (reading 'namespaceURI')
at eval (eval at evaluate (:313:29), <anonymous>:17:12)
at UtilityScript.evaluate (<anonymous>:320:18)
at UtilityScript.<anonymous> (<anonymous>:1:44)
Call log:
```

DEV: flaky spec

---

app/assets/javascripts/admin/addon/routes/admin-customize-themes-show.js
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes.rb

When edit theme page is reloaded or visited directly, we should display new layout.

FIX: correct reload edit theme page

---

app/assets/javascripts/discourse/app/components/reviewable-bundled-action.gjs
app/assets/stylesheets/common/base/reviewables.scss
app/assets/stylesheets/common/components/buttons.scss
spec/system/reviewables_spec.rb

These reject/approve buttons were getting `btn-default` classes rather than `btn-danger` or `btn-success`, which meant the styles for the colors had to be applied separately to `.approve-post` and `.reject-post`. This also meant the styles needed an additional override in themes. 
Moving to our common button classes helps centralize the styles and avoids a manual override being needed in themes. 
Button appearance is the same before/after

DEV: clean up review queue button classes

---

app/assets/javascripts/discourse/app/components/header/user-dropdown.gjs
app/assets/javascripts/discourse/app/components/header/user-dropdown/notifications.gjs
config/locales/client.en.yml

We were using a vanilla `button` tag here, but can use `DButton` now, this helps us be more consistent with classes... we had a minor issue where class differences changed the active state between buttons here...
Before (hamburger and avatar forced active):
After (hamburger and avatar forced active): 
I also noticed we have a useless title attribute on the image here, the title should be on the button and the image doesn't need one. 
I've also cleaned up the titles:
* hamburger menu was previously just `menu` but we refer to this as `Navigation menu` generally, and that provides a lot more context 
* the notification menu was "Username's account" but more accurately it's "Notifications and account" (and I don't think we need the username present)

DEV: use DButton for user header avatar menu

---

config/initializers/000-development_reload_warnings.rb

Ignore any files/directories in '.devenv' like we do for those in 'node_modules' to 1) speed-up watching files and 2) prevent files from being watched multiples times (due to symlinks).
No specs since this is only a warning that is being shown in development when using devenv.
---
Here's an example of the 100s of warning you get when using devenv
```plain
** ERROR: directory is already being watched! **
Directory: /Users/zogstrip/Poetry/discourse/plugins/discourse-login-client/.devenv/profile
is already being watched through: /nix/store/jp4qhxc2f98nyq90kia200mrygl2ndcy-devenv-profile
MORE INFO: https://github.com/guard/listen/blob/master/README.md        
```

DEV: prevent files being watched warning when using devenv

---

config/site_settings.yml

This allows, in particular, for larger animated image uploads. Due to optimizing (clientside and serverside), the actual size of the uploaded (non-animated) image often ends up being smaller than the o riginal size. I.e. it may already be optimized before hitting this limit.

DEV: bump max_image_size_kb to 10MB

---

app/controllers/groups_controller.rb
app/models/group.rb
config/locales/server.en.yml
config/routes.rb
db/post_migrate/20250513161753_rename_by_id_group.rb
spec/models/group_spec.rb
spec/requests/api/groups_spec.rb
spec/requests/groups_controller_spec.rb

As part of a customer request, we have added the option to search groups by ID when doing API calls. However, in doing so we have decided to correct the confusion around the group's routes. Previously the route would look like `g/:id` while taking the `name` of the group as the param. For example, when getting a group the route would be like this:
```
GET /g/admins
```
This would make the code in the controller seem as if it was handling the group IDs instead of names. With these changes, this should be addressed.

FEATURE: Add the group show endpoint to search groups by id instead of only the slug name

---

app/assets/stylesheets/admin/admin_base.scss

While re-reviewing what I did in https://github.com/discourse/discourse/pull/32706,  I noticed that the import for customize_show_schema in `admin_base.scss` file was missing. Probably removed by mistake in the rebase.

UX: add missing import to admin_base.scss

---

app/assets/stylesheets/common/base/modal.scss

This PR causes modals to inherit the border radius set by `--d-border-radius`.

UX: Modal to inherit border radius

---

app/assets/stylesheets/admin/schema_setting_editor.scss

relates to https://github.com/discourse/discourse/pull/32707 and https://github.com/discourse/discourse/pull/32706
I've retested manually and all should be fine now.

FIX: wrong class in schema setting editor stylesheet file

---

spec/system/page_objects/modals/sidebar_edit_categories.rb

We were not correctly relying on capybara matchers leading to test
flakiness
```
ailure/Error: super
Capybara::Playwright::Node::StaleReferenceError:
Element is not attached to the DOM
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/capybara-playwright-driver-0.5.6/lib/capybara/playwright/node.rb:91:in `rescue in assert_element_not_stale'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/capybara-playwright-driver-0.5.6/lib/capybara/playwright/node.rb:81:in `assert_element_not_stale'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/capybara-playwright-driver-0.5.6/lib/capybara/playwright/node.rb:124:in `visible_text'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/capybara-3.40.0/lib/capybara/node/element.rb:60:in `block in text' …
```

DEV: Fix flaky system tests

---

spec/support/shared_examples/core_features.rb

This commit removes the assumption that the sidebar will always be
present as that may not always be the case in certain themes.

DEV: Improve core features spec

---

spec/support/shared_examples/core_features.rb

Follow-up to eff31e0d42c535ee115317f5b63ff70d90097911
This removes the assumption that the search dropdown is present across
all themes and plugins.

DEV: Fix full page search core features system test

---

app/assets/javascripts/admin/addon/components/ip-lookup.gjs
spec/system/admin_user_spec.rb

This has been broken in https://github.com/discourse/discourse/commit/b6aad28ccffc276153fe847621d282549c4aac78
We correctly access the users object and added a test to prevent future regressions.

FIX: ensure we can lookup identical ip addresses

---

app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/templates/signup.gjs
spec/system/page_objects/pages/signup.rb
spec/system/social_authentication_spec.rb

If user returns to the signup form with data from their social login, then we shouldn't show the right side column, because it is confusing to have buttons there that restart the social login flow. This PR makes it so we only show the signup form.
Internal ticket: /t/154184

UX: Focus on sign up form in social auth flow

---

config/site_settings.yml

Brings it in line with `max_image_size_kb`.

DEV: bump max attachment size to 10MB

---

app/controllers/groups_controller.rb
config/routes.rb

Reverted unintended changes to group routes made [here](https://github.com/discourse/discourse/pull/32442/files#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5)

DEV: Revert unintended changes to GroupsController #add_members and its corresponding route

---

lib/plugin/metadata.rb

This is a plugin that is no longer maintained.

DEV: Remove `discourse-logster-rate-limit-checker` from official plugins

---

Gemfile
Gemfile.lock

Because we use a custom `ContentSecurityPolicy` middleware, the latest versions (> 8.0.3) of Bullet error out on load:
<details><summary>Stacktrace</summary>
```
/Users/drenmi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.2.2.1/lib/action_dispatch/middleware/stack.rb:180:in `assert_index': No such middleware to insert before: ActionDispatch::ContentSecurityPolicy::Middleware (RuntimeError)
from /Users/drenmi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.2.2.1/lib/action_dispatch/middleware/stack.rb:107:in `insert'
from /Users/drenmi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/railties-7.2.2.1/lib/rails/configuration.rb:53:in `block in insert_before'
from /Users/drenmi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/railties-7.2.2.1/lib/rails/configuration.rb:9 …
```

FIX: Lock Bullet gem to a compatible version

---

app/assets/javascripts/admin/addon/components/admin-search.gjs
app/assets/javascripts/admin/addon/components/modal/admin-search.gjs
app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/tests/integration/components/admin-search-test.gjs
app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js
app/assets/stylesheets/admin/search.scss
app/assets/stylesheets/common/modal/modal-overrides.scss
config/locales/client.en.yml
plugins/chat/assets/javascripts/discourse/components/chat/modal/new-message.gjs
plugins/chat/assets/stylesheets/common/chat-modal-new-message.scss
spec/system/admin_search_spec.rb
spec/system/page_objects/modals/admin_search.rb

This simplifies the admin search and adds some basic accessibility
Simplification: 
* Removes the filters for now, both in the modal and full-screen 
* Removes the link to full-screen from the modal
* Simpler input placeholder text
* Positioned to sit higher on the page, similar to a command palette 
Accessibility: 
* Results (or lack of) announced for screenreaders after query 
Bonus: 
* Makes the modal input sticky on scroll 
* Combined some styles shared between this and the chat menu (modifier + k) under a `--quick-palette` class 
Before:
After:

UX: simplify admin search, make more accessible

---

app/assets/javascripts/admin/addon/components/bulk-user-delete-confirmation.gjs
app/assets/javascripts/admin/addon/components/ip-lookup.gjs
app/assets/javascripts/admin/addon/controllers/admin-users-list-show.js
app/assets/javascripts/admin/addon/models/admin-user.js
app/assets/javascripts/discourse/tests/acceptance/admin-users-list-test.js
app/assets/javascripts/discourse/tests/helpers/create-pretender.js
app/controllers/admin/users_controller.rb
spec/requests/admin/users_controller_spec.rb
spec/requests/api/schemas/json/admin_user_list_response.json

This change was unfortunately introduced in https://github.com/discourse/discourse/commit/b6aad28ccffc276153fe847621d282549c4aac78#diff-5c7ecbec34de2166b60c5381df93a4e8438a2dbb6dcb8af0203cff4462fbc64b to prevent a failing spec due to the lack of last message bus id.
This commit reverts the change associated to it which was causing the JSON response to be an object instead of an array.

DEV: revert admin users list change

---

app/controllers/static_controller.rb
spec/requests/static_controller_spec.rb
spec/system/login_spec.rb
spec/system/page_objects/pages/login.rb

Detects the `redirect` queryParam on the /login route. If the user is already logged in, navigates to that page. Otherwise, sets the "destination_url" cookie so that the user will be redirected after logging in. 
If the param doesn't start with a  single slash, ignore it and follow previous behavior (navigate to "/" or log in then navigate there. 
Respects subfolder configs.

Allow passing a redirect path to a param on the /login route

---

app/controllers/posts_controller.rb
spec/requests/posts_controller_spec.rb

a complement to the :post_destroyed event - customer needed an action to happen just once when the wrench icon was used to delete one or more posts ...

DEV: trigger single event when multiple posts are destroyed at once

---

app/assets/javascripts/discourse/app/components/search-menu.gjs
app/assets/stylesheets/common/base/search-menu.scss

This node has been incorrectly removed in https://github.com/discourse/discourse/commit/215a129b68de2b3b1615ed2d180f7af56b3baf55
Before:
After:

FIX: adds missing search-input-wrapper

---

app/assets/stylesheets/admin/search.scss

little follow-up to 264b9db18896d4125fa9a75898867bd127d80316 to make admin search match topic search hover/focus styles 
Before:
After:

UX: more consistent admin search hover/focus color

---

app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js

`?.close()` is an unsafe pattern
```
test = {}
test?.close()
￼VM363:1 Uncaught TypeError: test?.close is not a function
at <anonymous>:1:7
```

FIX: correctly guard for missing close method

---

.git-blame-ignore-revs

ca2dee5 was a reformatting commit that can be ignored in `git blame`.

DEV: Add ca2dee5 to .git-glame-ignore-revs

---

.github/workflows/tests.yml

This is the bottleneck for the `tests` workflow now so we are throwing
more cores at the job

DEV: Run plugin system tests job on 16 core runners

---

lib/stylesheet/compiler.rb

Fixing this everywhere will be a very large undertaking, so we're deferring it until there is a concrete timeline for it becoming an error in sass.
In the meantime, we'll be adding a stylelint rule to enforce ordering of declarations/nested-blocks/mixins, so that will go some way towards avoiding this deprecation.

DEV: Silence scss mixed-decls for themes/plugins

---

app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/desktop/topic-list.scss

This tightens up some topic list spacing — our line height for titles has been kind of on the large size, we've got too much space between wrapping metadata, and sometimes not enough space between the right of titles and avatars.
Generally headline line-height is recommended to be within 1.1 - 1.3, and we were at 1.4, this puts it at 1.2
Before:
After:

UX: improve spacing of text in topic list items

---

app/assets/javascripts/discourse/app/components/plugin-outlet.gjs
app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
app/assets/javascripts/discourse/tests/integration/components/plugin-outlet-test.gjs

This has been deprecated with an admin warning for some time

DEV: Drop deprecated `PluginOutlet` `@tagName` argument

---

app/assets/stylesheets/color_definitions.scss
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/common/float-kit/d-menu.scss
app/assets/stylesheets/common/float-kit/d-toasts.scss
app/assets/stylesheets/common/float-kit/d-tooltip.scss
app/assets/stylesheets/mobile/post-action-feedback.scss
app/assets/stylesheets/qunit-custom.scss

This eliminates menu panel container padding, which gets us a closer match to the recent search panel adjustments. I've also eliminated the menu-panel box-shadow variant — if we're not going to use it on the search panel we should consolidate and eliminate the variance.  
Before:
After:

UX: make the notification panel consistent with new search panel styles

---

app/assets/javascripts/admin/addon/services/admin-sidebar-state-manager.js

Reported here: https://meta.discourse.org/t/dashboard-freezes-until-sidebar-is-opened/366402
This is a follow-up to https://github.com/discourse/discourse/pull/32651, when navigating from the homepage to admin the hamburger gets force-hidden because we switch from the dropdown to the sidebar nav but the scrollLock was unintentionally left behind. 
This makes sure we're only messing with hamburger state when the sidebar is hidden (with ` {{hideApplicationSidebar}}`) and also removes the scroll lock when the hamburger is force-hidden.

FIX: check if sidebar hidden and remove scrollLock when hiding hamburger menu

---

app/assets/stylesheets/common/base/search-menu.scss

follow-up to https://github.com/discourse/discourse/commit/6169ac26830bd272dec199eb97cfe320cb6e6483
this fixes a spacing regression in the welcome banner search results
before:
after: 
before:
after:

UX: follow-up search fixes for welcome banner

---

spec/system/s3_uploads_spec.rb

The spec is randomly failing, but it's not due to the system spec. Sometimes the upload fails to work and we get an error from the service.

DEV: skips s3 multipart spec

---

spec/system/page_objects/pages/admin_site_texts.rb

A spec could potentially go so fast that it would attempt to fill in the input before we have gone through the various redirects resulting in an error.
```
Failure/Error: super
Playwright::Error:
TypeError: Cannot read properties of null (reading 'namespaceURI')
at eval (eval at evaluate (:313:29), <anonymous>:17:12)
at UtilityScript.evaluate (<anonymous>:320:18)
at UtilityScript.<anonymous> (<anonymous>:1:44)
Call log:
```
Now that we ensure that we have the current final state path we should avoid this error.

DEV: fix flaky in admin site texts

---

plugins/automation/spec/models/stat_spec.rb

I suspect that by having an integer and not a float sometimes the value we get is converted to 0.
This is the error we have atm:
```
Failure/Error: measurement = Benchmark.measure { example.run }
expected: 0.75
got: 0.0
(compared using ==)
```
This might not fix it, but it feels right to make this change.

FIX: attempts to fix flaky in stat spec

---

spec/system/composer/review_media_unless_trust_level_spec.rb

I suspect the within is doing a memoization of the preview at a moment where the emoji has not been rendered yet, when we render the emoji we might have a different instance of the preview in the within which doesn't have the emoji.
Im not super confident about this theory, but the within is useless here so it seems like a good thing to try first.
The error we have is:
```
Failure/Error: super
Playwright::Error:
TypeError: Cannot read properties of null (reading 'namespaceURI')
at eval (eval at evaluate (:313:29), <anonymous>:17:12)
at UtilityScript.evaluate (<anonymous>:320:18)
at UtilityScript.<anonymous> (<anonymous>:1:44)
Call log:
[Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_composer_using_review_media_does_not_flag_a_post_with_an_emoji_250. …
```

FIX: attempts to fix flaky in review media

---

plugins/chat/spec/system/thread_tracking/full_page_spec.rb

This test is about testing that we can set notification_level, which it does correctly. The rest of the spec was testing some undefined behavior which is flaky.

FIX: simplify test to remove flaky part

---

spec/system/admin_users_list_spec.rb

The proper fix was to apply what has been reverted in https://github.com/discourse/discourse/commit/7558e2c7cd66306bf3ac33e0854a855ad11a26d5 but we would have to break the API to apply this fix so I will just skip these specs for now.

FIX: skip flaky specs

---

app/controllers/admin/themes_controller.rb
app/models/theme.rb
app/serializers/basic_theme_serializer.rb
app/serializers/color_scheme_serializer.rb
app/serializers/theme_serializer.rb
spec/requests/admin/themes_controller_spec.rb

`strict_loading` was added to prevent it happening in the future. Few adjustments had to be made:
- include color_scheme and color_scheme_colors, also for parent and child themes;
- internal translations were using preload_fields, but it was too deep to correctly use preloaded tables. I had to pass `preloaded_locale_fields` manually;
- include theme in color_scheme.
Before:
After:

FIX: N+1 in admin themes page

---

app/assets/javascripts/admin/addon/components/admin-search.gjs

When we construct the admin search component, we fire off a call to get data from the back-end. When this is done, there's an async callback that re-does the search. This can result in confusing flickering of the results.
This was compounded by a separate issue that caused the data endpoint to be extremely slow if we had two specific plugins installed at the same time. That issue has already been resolved.
The first time we construct the component (and fetch the data) we initialize it with a flag to indicate that data is still loading. Until the data is loaded, we will show the regular loading spinner if the admin starts typing.
On Meta the endpoint takes ~600ms. That countdown starts when you click or use the shortcut, then you need to start typing as well, so this delay shouldn't be a …

FIX: Wait for data before showing admin search results

---

config/routes.rb

This avoids making unnecessary database queries when routing to paths that were positioned below this entry, e.g.
```
curl http://localhost:3000/form-templates
```

DEV: Move the catch-all route to the bottom

---

lib/plugin/instance.rb

The Rails asset pipeline isn't used for locale bundles any more. Plus, `assets.precompile` isn't used for anything since we switched to propshaft.

DEV: Remove precompile for locale js

---

app/assets/javascripts/discourse/app/components/plugin-outlet.gjs
app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
app/assets/javascripts/discourse/app/static/dev-tools/plugin-outlet-debug/args-table.gjs
app/assets/javascripts/discourse/tests/integration/components/plugin-outlet-test.gjs

Historically, plugin outlet arguments had to be accessed like `@outletArgs.foo` in templates, or `this.args.outletArgs.foo` in javascript. Following this commit, outletArgs will be passed to connectors at the top level, so they can be accessed like `@foo` in templates or `this.args.foo` in JS.
`@outletArgs` remains available for compatibility, and there are no plans to remove it.
For custom classic component connectors, these new arguments may clash with functions/fields defined on the component class. This rare case will be automatically detected, protected against, and a deprecation will be shown.

DEV: Make outletArgs available as regular arguments in PluginOutlet

---

app/assets/javascripts/discourse/app/components/plugin-outlet.gjs

A followup to 707a91243c35ea1693b80249e1c00fb5320f47cb

DEV: Remove accidental whitespace from PluginOutlet

---

spec/system/private_message_spec.rb

We should check the H1 is not present anymore only once we have confirmed we changed page.

FIX: ensures we have changed page first

---

app/assets/javascripts/discourse/tests/integration/components/plugin-outlet-test.gjs

Fixes for recent regressions:
- da6b82f7767cbeb038dfbebda92a4474626ff1e8
- 2a18834db1cb6b9c8f071eeab8554257336b2802
These tests should stop it happening for a third time 😅

DEV: Add test for plugin-outlet whitespace

---

plugins/automation/app/controllers/discourse_automation/admin_automations_controller.rb
plugins/automation/app/models/discourse_automation/automation.rb
plugins/automation/app/models/discourse_automation/field.rb
plugins/automation/app/serializers/discourse_automation/automation_serializer.rb
plugins/automation/config/locales/server.en.yml

- Add a safeguard until we implement pagination for the index, it ensures we won't try to load more than 500 automations ever.
- Includes the fields of the automation so we don't have an N+1 and also filter them in ruby land instead of doing two additional queries
- Ensures a field object in the field serializer is capable to find the loaded automation associated to it instead of trying to reload it
- Includes pending_automations to avoid an N+1

PERF: fixes N+1 for automation plugin

---

plugins/automation/admin/assets/javascripts/discourse/templates/admin-plugins/show/automation/edit.gjs

Technically we want to follow DDAU but most of our usage in the code base are just mutating `@checked`. This will eventually get converted to form-kit but in the meantime we can just remove this bit of code as it's doing two times the same thing and you could even end up in the situation where they both fight for what is the correct value.

DEV: removes unnecessary lines

---

spec/models/theme_field_spec.rb

This error sometimes includes a filepath in the middle, which has a random tmp/ prefix. To workaround this, we can just assert for the "Missed semicolon" part

DEV: Resolve flaky ThemeField spec

---

app/assets/javascripts/discourse/app/components/date-input.gjs
app/assets/javascripts/discourse/app/components/search-advanced-options.gjs
app/assets/stylesheets/common/components/date-input.scss

As seen in the advanced search filters... iOS doesn't show placeholders for the date input, so we have a CSS adjustment for this, but it doesn't clear when a value is present. 
This update adds a class when a value is present so the placeholder can be cleared. 
Before:
After:
Also fixed extra left margin by removing a class.

UX: improve mobile date picker slightly

---

app/controllers/list_controller.rb

These lines of code would output "Period - Site name" as the page title for the crawlier view only for Top routes. This is too specific and unnecessary, since the top route isn't highly prioritized for crawlers. Without this, the page title defaults to "Site name" for these routes. 
One major advantage of this change is that when the homepage is set to the Top route, the page title for crawlers on the homepage is now "Site name", which is a lot better.

DEV: Remove Top route title for crawlers

---

lib/site_settings/hidden_provider.rb
spec/lib/site_settings/hidden_provider_spec.rb

This might be useful to revert changes made by plugins when they're disabled for example.

DEV: support un-hiding site settings programmatically

---

app/assets/javascripts/admin/addon/components/modal/admin-search.gjs

Previously it was relying on the default Modal behavior, which is to close **after** the next route transition.

UX: Close admin search modal immediately when result is selected

---

app/assets/javascripts/admin/addon/components/admin-badges.gjs
app/assets/javascripts/discourse/app/components/nav-item.gjs

Some cases are more complex than the default behavior of `this.router.isActive(this.args.route)`, in this case you can give use `@currentWhen` on your `NavItem` component.
Example:
```gjs
get isItCurrent() {
return true;
}
<template>
<NavItem @i18nLabel="test" @currentWhen={{this.isItCurrent}} />
</template>
<template>
<NavItem @i18nLabel="test" @currentWhen="foo" />
</template>
<template>
<NavItem @i18nLabel="test" @currentWhen="foo.show foo.index" />
</template>
```
No test as I can't write a component test for this as it relies on the router.

DEV: allows to pass `@currentWhen` to `NavItem`

---

spec/models/site_spec.rb

```
rspec --seed 52075 spec/models/site_spec.rb spec/lib/freedom_patches/translate_accelerator_spec.rb
Randomized with seed 52075
....................................................F
Failures:
1) translate accelerator plugins loads plural rules from plugins
Failure/Error: self.locale_no_cache = value
I18n::InvalidLocale:
:foo is not a valid locale
```
This is because setting `I18n.config.available_locales` is equivalent to hard coding the
locales for the entire process. It should not be set so that `I18n` will
fallback to `backend.locales`.

DEV: Fix state leak in test

---

app/assets/javascripts/discourse/app/components/header/topic/participant.gjs
app/assets/javascripts/discourse/app/components/topic-map/topic-map-summary.gjs
app/assets/stylesheets/common/components/topic-map.scss

Header: 
* Allows optional avatar size for header participant component (for reuse elsewhere) 
Topic map:
* Adds a new `topic-map-participants-after` outlet
* Removes an `!important`

DEV: new topic map outlet and header participant flexibility

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/views/layouts/_noscript_header.html.erb
spec/requests/home_page_controller_spec.rb

In some cases, Google crawlers don't output the meta description but rather they output the first bit of text in the UI. Sometimes that is a mix of table headings, topic titles and excerpts, which don't reflect the site's mission. Adding the description to the homepage header might help.
Internal ticket t/154372

DEV: Add site description to crawler homepage view

---

config/locales/client.en.yml

We use ampersand to concatenate sidebar sections, e.g. <kbd>Login & authentication</kbd>, <kbd>Logs & screening</kbd>, etc.
This updates <kbd>Themes & components</kbd> to have the same.
**Before:**
**After:**

DEV: Use ampersand for themes and components admin section

---

plugins/chat/app/services/chat/trash_channel.rb
plugins/chat/spec/services/chat/trash_channel_spec.rb

Required for this PR: https://github.com/discourse/discourse-livestream/pull/55

FEATURE: trigger an event when chat channel is trashed

---

app/assets/javascripts/discourse/app/components/sidebar/filter-no-results.gjs
app/assets/javascripts/discourse/app/components/sidebar/filter.gjs
app/assets/javascripts/discourse/app/components/sidebar/panel-header.gjs
app/assets/javascripts/discourse/app/lib/sidebar/admin-sidebar.js
app/assets/javascripts/discourse/app/lib/sidebar/base-custom-sidebar-panel.js
app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/base/sidebar.scss
config/locales/client.en.yml
spec/system/admin_sidebar_navigation_spec.rb
spec/system/page_objects/components/filter.rb

In this PR, filter was removed and replaced by search.
https://github.com/discourse/discourse/pull/32485/
However, moderator should still be able to filter sidebar. Also, plugins like `doc-category` should have filterable sidebar.
Moderator:
https://github.com/user-attachments/assets/2604930f-c69a-4ac2-bdac-9ad94eead4bb
Doc category plugin
https://github.com/user-attachments/assets/9ad9f5b4-9d2c-4c2d-9005-e31822acfaab

FIX: bring back sidebar filter

---

app/assets/stylesheets/common/base/compose.scss

* Removed backgound from composer tips popup
* Added more spacing
* Made links the default link colour, so it's clear they are links.
* Applied `d-border-radius-large` var

UX: new styling for composer tips

---

app/models/emoji.rb
spec/models/emoji_spec.rb

This regressed because with recent emojis changes, the base name is now `trade_mark` and not `tm`. `tm` is just an alias emoji.

DEV: do not convert (tm) and (TM) to emoji

---

app/assets/javascripts/admin/addon/routes/admin-config-customize.js

We removed a duplicate translation key, but it was being used here. Update the title token to use the canonical one.

FIX: Themes and components page title

---

plugins/chat/app/services/chat/action/fetch_threads.rb
plugins/chat/app/services/chat/lookup_channel_threads.rb
plugins/chat/spec/services/actions/fetch_threads_spec.rb
plugins/chat/spec/services/chat/lookup_channel_threads_spec.rb

- use `model` where possible
- extract threads fetching logic to its own action
- refactor specs to follow current guidelines/best practices

DEV: Refactor Chat::LookupChannelThreads to follow best practices

---

lib/stylesheet/compiler.rb

Marking mixed-decls as silenced & fatal simultaneously is causing a warning "Ignoring setting to silence mixed-decls deprecation, since it has also been made fatal"
The intention is for it to be silenced for themes/plugins, but fatal for core.

DEV: Resolve mixed-decls misconfiguration

---

app/assets/javascripts/discourse/app/instance-initializers/component-templates.js
app/assets/javascripts/discourse/app/lib/deprecated.js
app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
app/assets/javascripts/discourse/tests/integration/component-templates-test.gjs

These changes are backported from `main`, so that stable users receive better feedback about this upcoming deprecation.
- Update Meta topic URLs
- Add theme/plugin identification to deprecation
- Enable admin warning banner
https://meta.discourse.org/t/355668

DEV: Improve template-override deprecations (stable)

---

app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js
app/assets/javascripts/discourse/app/services/login.js
app/assets/javascripts/discourse/app/templates/login.hbs
app/assets/javascripts/discourse/app/templates/signup.hbs
app/assets/javascripts/discourse/tests/acceptance/login-required-test.js
config/site_settings.yml
spec/system/social_authentication_spec.rb

Backported PR merge commit 42447770bf39e7bb7164b66c498b80827dff04d1 from main, resolved conflict with another backport. 
This fixes an issue where navigating to /login on a site with only one external auth method does not redirect to that auth provider but instead goes to a "Welcome back" landing page with a button to login.
Here's the message from that PR:
FIX: Automatic auth flow with full page login/signup V3 (#31072)
This adds back the fixes from
https://github.com/discourse/discourse/pull/30928 that were reverted by https://github.com/discourse/discourse/pull/30960.

FIX: Backport automatic auth flow fix for full page login/signup from main to stable

---

app/assets/stylesheets/common/base/compose.scss

Undoes the CSS nesting done inadvertently on https://github.com/discourse/discourse/pull/32843.
Everything below `.fullscreen-composer` shouldn't be nested within `.similar-topics`.

FIX: fullscreen composer regression

---

app/assets/javascripts/discourse/app/components/modal/login.js
app/assets/javascripts/discourse/app/controllers/login.js
app/assets/javascripts/discourse/app/routes/application.js
app/assets/javascripts/discourse/app/routes/login.js
app/controllers/static_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
lib/auth/result.rb
spec/requests/static_controller_spec.rb
spec/system/login_spec.rb
spec/system/page_objects/modals/login.rb
spec/system/page_objects/pages/login.rb

This backports to stable my changes to add a redirect queryParam to the /login route.
Pulled in a couple other commits that affect the login process and the same spec that I modified.
Had to add a commit cleaning up the modal login helper for login_spec.rb to pass here since the modal login was already removed in main.

DEV: backport login redirect param to stable

---

plugins/checklist/assets/javascripts/lib/rich-editor-extension.js

Removes the rich editor checklist input rule `undoable: false`, which is not needed.
Making it undoable allows a backspace to undo the input rule conversion, so we can go from a check to a `[]` again

UX: rich editor checklist undoable input rule

---

spec/support/diagnostics_helper.rb

Allow tracking of client ids published to message bus. 
Required for when you are targeting publishing at a single browser

DEV: track client ids published to message bus

---

app/assets/javascripts/discourse/app/components/d-styles.gjs
app/assets/javascripts/discourse/app/components/sidebar/footer.gjs
app/assets/javascripts/discourse/app/instance-initializers/mobile.js
app/assets/javascripts/discourse/app/lib/mobile.js
app/assets/javascripts/discourse/app/models/site.js
app/assets/javascripts/discourse/app/static/dev-tools/toolbar.gjs
app/assets/javascripts/discourse/tests/integration/components/d-modal-test.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-menu-test.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-toast-test.gjs
app/assets/javascripts/discourse/tests/integration/components/float-kit/d-tooltip-test.gjs
app/assets/javascripts/discourse/tests/integration/components/home-logo-test.gjs
app/assets/javascripts/discourse/tests/integration/components/navigation-bar-test.gjs
app/assets/javascripts/discourse/tests/integration/components/notifications-tracking-test.gjs
app/assets/javascripts/discourse/tests/unit/controllers/preferences-account-test.js
app/assets/javascripts/discourse/tests/unit/controllers/topic-test.js
app/helpers/application_helper.rb
app/views/common/_discourse_stylesheet.html.erb
config/locales/server.en.yml
config/site_settings.yml
plugins/chat/test/javascripts/components/chat-channel-leave-btn-test.gjs
plugins/chat/test/javascripts/components/chat-channel-row-test.gjs
plugins/chat/test/javascripts/components/chat-header-icon-test.gjs
plugins/chat/test/javascripts/unit/services/chat-state-manager-test.js
spec/system/mobile_mode_spec.rb

Introduces the viewport_based_mobile_mode experimental site setting. When enabled, user-agent-based mobile/desktop detection will be replaced with viewport-width logic. 'mobile mode' is enabled for any viewport less than our 'sm' breakpoint (40rem, or 640px at default font size).
When this mode is enabled, mobile/desktop toggle buttons are hidden, since they are non-functional.
Tests are also updated to use a consistent method for force-enabling the legacy mobile mode. All state is now stored in `lib/mobile`, and the `Site` model references that via a getter.

DEV: Introduce experimental viewport-based mobile mode

---

app/assets/javascripts/discourse/app/components/discovery/accessible-discovery-heading.gjs
app/assets/javascripts/discourse/tests/integration/components/accessible-discovery-heading-test.gjs
config/locales/client.en.yml
spec/system/discovery_h1_accessibility_spec.rb

Follow-up to ca658a8bb093c82410927d1fa29e5ef1940260b7
The original attempt at this wasn't flexible enough for some languages where adjectives may depend on context, so this requires more translation but allows for full context in each string
Discussed here: https://meta.discourse.org/t/translating-filter-in-headings-for-discovery-routes/363520

A11Y: Update accessible headings for more flexible translations

---

app/assets/javascripts/discourse/app/components/category-title-link.gjs
app/assets/javascripts/discourse/tests/integration/components/category-title-link-test.gjs

Related to [this issue on meta](https://meta.discourse.org/t/category-headers-missing-the-titles/361954).
Apparently a few customers with themes using the CategoryTitleLink component got hit with the category title not updating correctly when the category changed.
The component was importing `@ember/component` but not marking the category arg as tracked. Changed to `@glimmer/component` so the category arg is tracked, and cleaned up the rest of the component to match.

FIX: Fix category title link to update when category changes, add tests

---

app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js

This change updates the minimize button to always minimize the composer so we don’t inadvertently delete user input.
Internal ref: /t/129123

FEATURE: allow minimizing composer when no text

---

app/assets/javascripts/admin/addon/components/schema-setting/editor.gjs
app/assets/javascripts/discourse/tests/fixtures/theme-setting-schema-data.js
app/assets/javascripts/discourse/tests/integration/components/admin-schema-setting/editor-test.gjs

`label` and `description` did not work in `type: objects` in site settings; this PR fixes that.
In theme settings, it is still working as expected(added tests for it ).

FIX: fix label and description not working in type objects for site settings

---

app/assets/javascripts/discourse/app/components/flag-action-type.gjs

There is currently no selector on this `div` and I need a better selector than `strong` for a CSS customization in a private theme.

DEV: Add className to flag name in flagging modal

---

app/assets/stylesheets/common/foundation/base.scss

This PR adjusts the default border radius from `2px` to `4px`. It also increase `--d-border-radius-large` by setting it to be `2x` the default.

UX: Establish a larger default border radius

---

app/assets/stylesheets/common/base/sidebar-section-link.scss

Reported here: https://meta.discourse.org/t/dmenu-for-more-in-sidebar-selects-first-item-even-if-it-is-not-the-current-page/367344
focus-visible will make the focus state only appear when needed (like when navigating with your keyboard), rather than appearing on menu open

UX: switch sidebar focus to focus-visible

---

plugins/chat/assets/javascripts/discourse/lib/lightbox.js

Due to one of the side effects of `app/assets/javascripts/discourse/app/lib/body-scroll-lock.js` we are disabling touch actions on body which was impacting zooming of images in chat.
Im not sure we should keep this touch-action hack  in `app/assets/javascripts/discourse/app/lib/body-scroll-lock.js` but for now the simplest change is to just disable it when a chat image is lightboxed.

FIX: allows zooming of images in chat

---

app/assets/javascripts/admin/addon/components/themes-grid-card.gjs

Just a small update to make the theme install icon match the one we use for components.

UX: Match theme install icon with component icon

---

app/assets/stylesheets/common/base/menu-panel.scss
app/assets/stylesheets/common/components/welcome-banner.scss
app/assets/stylesheets/desktop/components/header-search.scss

Meta report: https://meta.discourse.org/t/search-in-header-gives-too-deep-results/362973
The general problem of our `menu-panel` is that it had no proper max-height set, which mean you have to scroll the page instead of the panel to see bottom results. In the new header-search setup however, scrolling the page makes the panel disappear, effectively locking you out.
This commit adds a best-estimate max-height on the parent level `menu-panel`, dependent on where the search is triggered from (header VS welcome banner)
| Old | New |
| ![CleanShot 2025-05-23 at 14 58 07@2x](https://github.com/user-attachments/assets/4a96d518-13d0-4f97-b472-5d1f56bbaa1a) | ![CleanShot 2025-05-23 at 14 59 30@2x](https://github.com/user-attachments/assets/9c8546d2-a780-49b3-80d0-95eab81eff94) …

UX: fix search results unreachable bottom results and more button

---

app/assets/javascripts/discourse/app/components/sidebar/back-to-forum.gjs

Search for last not admin URL only when user is in admin panel. When back to forum link is clicked from documentation plugin link should lead to homepage.
Meta: https://meta.discourse.org/t/doc-sub-category-back-to-forum-loop/367513/10
Specs: https://github.com/discourse/discourse-doc-categories/pull/40

FIX: back to forum button only from admin

---

lib/stylesheet/manager.rb
spec/lib/stylesheet/manager_spec.rb

Follow up to https://github.com/discourse/discourse/pull/32881
Stylesheet `<link>` tags for themes/components are aren't getting included/rendered in the HTML document due to a missing check in stylesheet manager. See https://meta.discourse.org/t/ui-layout-broken-for-rtl-language-after-latest-update/367434?u=osama.

FIX: Serve RTL CSS for themes and components

---

app/assets/javascripts/discourse/app/components/sidebar/back-to-forum.gjs
plugins/chat/spec/system/sidebar_navigation_menu_spec.rb

Similar fix to https://github.com/discourse/discourse/pull/32911
Meta: https://meta.discourse.org/t/doc-sub-category-back-to-forum-loop/367513/15

FIX: back to forum button should lead to forum and not chat

---

app/assets/javascripts/discourse/app/components/emoji-picker/content.gjs
app/assets/javascripts/discourse/app/services/emoji-store.js
app/assets/javascripts/discourse/tests/integration/components/emoji-picker-test.gjs
app/assets/javascripts/discourse/tests/unit/lib/pretty-text/emoji-test.js
app/assets/javascripts/discourse/tests/unit/services/emoji-store-test.js
app/assets/javascripts/pretty-text/addon/emoji.js
plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js
plugins/chat/test/javascripts/unit/lib/chat-message-interactor-test.js

This change polishes the emoji diversity rendering behaviour in the emoji pickers. When a user changes their diversity setting, that setting will now be applied to favourites, chat default reactions, and in the emoji picker section selectors.
If an emoji was previously stored with a skin tone in favourites or default reactions, the stored skin tone won't be overridden.

FEATURE: Improve emoji diversity rendering

---

app/controllers/tags_controller.rb
spec/requests/tags_controller_spec.rb

When tag synonym is tag itself, it should not redirect to prevent infinite loop.

FIX: avoid infinite loop when synonym tag is self

---

app/assets/javascripts/discourse/app/components/about-page-extra-groups.gjs
config/site_settings.yml

We are missing one of the options for ordering of extra groups on the about page. This setting uses the exact order the groups are selected in the settings.
**Sorting by creation date:**
**Sorting by order of setting:**

FIX: Add missing about group ordering option

---

config/locales/server.en.yml

Updates the composer educational tips copy for the following:
- new topic
- new reply
- dominating topic
- don't feed the trolls
How it looks with the updated text:
Internal ref: /t/150274

UX: update composer educational tips copy

---

app/models/topic.rb
config/locales/server.en.yml
config/site_settings.yml

Updates the composer similar topics tips to return a maximum of 3 topic results. We are phasing out the site setting in an effort to improve the UX in the composer.
We will handle the migration to remove the site setting value from the database in a follow up PR.
/t/150274

DEV: update composer similar topics limit

---

app/assets/stylesheets/common/components/theme-card.scss

Added `overflow-wrap: anywhere` to prevent long URLs from breaking the layout

UX: Handle long URLs in theme grid with overflow-wrap

---

app/assets/javascripts/discourse/app/components/composer-editor.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js

This adds an `applyValueTransformer` for the Composer textarea's placeholder text. Shocked there isn't one already!

DEV: Apply transformer for composer editor reply placeholder

---

plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/automation/spec/triggers/post_created_edited_spec.rb

- For `with_images`, ignore `<img>` tags representing emoji or a quote avatar
- For `with_links` and `with_uploads`, exclude tags starting with the letter "a" other than `<a>` (like `<aside>`)
- For `with_code`, the `<pre>` tag wasn't being detected because it was expecting an extra char before the ">"

FIX: Make post created/edited automation trigger regexes more specific

---

app/models/category.rb
db/migrate/20250528030212_add_locale_to_categories.rb

Previously we had omitted determining the locale of categories, as unlike posts, categories are usually single words and are usually only translated once.
Since there is no locale, a category called "Staff" would also have an English translation. With LLMs that perform poorly, we see that translating "Staff" to English may result in something entirely different (like "Personnelle" or "Personal").
Thus adding locale support to categories can mitigate this issue due to the uncertainty.

DEV: Add locale column to categories

---

app/assets/javascripts/discourse/app/lib/notification-types/group-mentioned.js
app/assets/javascripts/discourse/tests/unit/lib/notification-types/group-mentioned-test.js
app/mailers/user_notifications.rb
spec/fabricators/notification_fabricator.rb
spec/mailers/user_notifications_spec.rb
spec/system/page_objects/pages/user_notifications.rb
spec/system/user_page/user_notifications_spec.rb

This is part of a series of changes to allow customers to dsiplay users' names instead of the users' username. 
When a user belongs to a group that has been mentioned by another user. It shows the name of the user that mentioned the group.
**Before**
**After**
When a email is sent to the user when mentioned in a post 
**Before**
**After**

DEV: Added the ability to use users' names in group mention notifications and mentions shown in emails

---

app/assets/stylesheets/common/components/theme-card.scss

This PR aims to decrease spacing between content sections in theme-card UI
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/49e35808-a463-4723-97f2-61200977e965)|![image](https://github.com/user-attachments/assets/f5f36d96-96f2-4bf4-a756-f58b16dd53f7)|

UX: Decrease spacing between content sections in theme-card UI

---

migrations/lib/database/schema/table_writer.rb

Ensure last column definition before a composite primary key definition has a comma.

FIX: Composite primary key output

---

plugins/chat/assets/stylesheets/common/chat-scroll-to-bottom.scss

Im not exactly sure why it's not necessary anymore, but it's certainly the cause of an actual shift today.

FIX: removes shift which is not necessary anymore

---

app/assets/stylesheets/common/base/sidebar-section.scss
app/assets/stylesheets/common/base/sidebar.scss

This PR adds a small gap between the sidebar items. Currently, when hovering over an item, and a previous element is active, there is no gap between the two.
**Issue**
**Fix**

UX: add gap to sidebar items

---

plugins/discourse-local-dates/assets/javascripts/lib/discourse-markdown/discourse-local-dates.js
plugins/discourse-local-dates/config/locales/server.en.yml
plugins/discourse-local-dates/config/settings.yml
plugins/discourse-local-dates/db/migrate/20250529021721_add_utc_to_setting.rb
plugins/discourse-local-dates/spec/integration/local_dates_spec.rb
plugins/discourse-local-dates/spec/lib/pretty_text_spec.rb

1. Changes default email format to llll (eg: Tue, May 8, 2018 2:00 AM)
from 2018-05-08T00:00:00Z UTC which is not nice on the eyes
2. Adds `discourse_local_dates_email_timezone` which allows configuring
default timezone in emails
3. Improved help text on site settings (format / timezone)

FEATURE: allow customizing default timezone for email.

---

app/assets/stylesheets/common/base/compose.scss

Uses the same hack that the markdown editor (`textarea`) uses to avoid iOS shifting the mobile composer, when using the rich editor/ a content editable.

UX: fix mobile positioning for content editable (rich editor)

---

app/assets/stylesheets/common/base/header.scss

The border radius should not be present at the bottom of menu icons.

UX: Fix active menu item bottom border

---

plugins/discourse-details/assets/stylesheets/details.scss
plugins/discourse-details/test/javascripts/integration/prosemirror-editor/details-test.js

When we first introduced the `discourse-details` plugin, the `<details>` element was not supported in all browsers, so this `display: none`-based polyfill had to be used.
Nowadays, there is no need for this. And in fact, the `details[open] > summary:first-of-type ~ *` selector is showing as our most expensive CSS selector during repaints.
Removing this `display: none` also means that browser find-in-page will now be able to correctly find content inside `<details>` in discourse.

PERF: Remove `<details>` polyfill

---

plugins/discourse-presence/assets/stylesheets/presence.scss

The space reserved for presence was just slightly too short, which was causing a layout shift when the indicator appears, this fixes it.

UX: avoid presence layout shift

---

app/assets/stylesheets/common/base/onebox.scss

This reverts commit 1af8ef60ed0f9fe094994f4a503ad6a0e765e638. It caused multiple oneboxes to lose spacing between them. Reverting while we investigate.

Revert "UX: Merge onebox experiment into core (#33015)"

---

migrations/config/intermediate_db.yml
migrations/config/json_schemas/db_schema.json
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/database/intermediate_db/user.rb
migrations/lib/database/intermediate_db/user_email.rb
migrations/lib/database/schema/global_config.rb
migrations/lib/database/schema/loader.rb

By default, rails makes timestamp columns (`created_at` and `updated_at`) non-nullable, we also have some required core and plugins columns we wouldn't necessarily want to enforce in the intermediate DB schema. It'll be better to set the default values for these during import instead of enforcing these at the converter level.
This change adds support for globally modifying a column’s `nullable` state, defaulting all `created_at` columns to be `nullable` while allowing for  table level overrides.

DEV: Support `nullable` column property modification

---

db/migrate/20210215231312_fix_group_flair_avatar_upload_security_and_acls.rb
db/migrate/20210528003603_fix_badge_image_avatar_upload_security_and_acls.rb

Application code should not be used in migrations since we want
migrations to be idempotent. Since these migrations were added 4 years
ago, the application code is safe to be removed.
This will allow me to make changes to the `FileStore::S3Store#update_upload_ACL` method without having to worry about these migrations.

DEV: Remove application code from old migration

---

app/assets/javascripts/discourse/app/components/edit-category-general.gjs
app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/app/lib/constants.js
app/assets/javascripts/discourse/tests/acceptance/category-new-test.js
app/models/category.rb
config/locales/client.en.yml
lib/tasks/javascript.rake

Restores the category text/foreground color field that was removed in #32015.
We are also retaining the auto text color selection that was introduced and applying on background color change rather than when the form is saved. The text color algorithm has been changed from color brightness to use color difference instead, which appears to be more reliable.
Algorithm for color difference: https://www.w3.org/TR/AERT/#color-contrast
https://github.com/user-attachments/assets/4d668ea1-b7b9-48d5-8131-d596fc0382ee
Internal ref: /t/154650

FIX: restore category text color field

---

app/assets/javascripts/admin/addon/components/admin-badges-show.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/color-palette.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/components.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/user-fields-list.gjs
app/assets/javascripts/admin/addon/components/form-template/form.gjs
app/assets/javascripts/admin/addon/components/form-template/row-item.gjs
app/assets/javascripts/admin/addon/controllers/admin-customize-colors-show.js
app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show.js
app/assets/javascripts/admin/addon/controllers/admin-permalinks-index.js
app/assets/javascripts/admin/addon/services/admin-emojis.js
app/assets/javascripts/discourse/app/components/modal/sidebar-section-form.gjs
app/assets/javascripts/discourse/app/components/user-stream.gjs
app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/tests/acceptance/user-drafts-stream-test.js
config/locales/client.en.yml
spec/system/admin_badges_spec.rb
spec/system/admin_color_palette_config_area_spec.rb
spec/system/admin_customize_components_config_area_spec.rb
spec/system/admin_customize_emojis_spec.rb
spec/system/page_objects/modals/sidebar_section_form.rb
spec/system/page_objects/pages/admin_customize_themes.rb
spec/system/page_objects/pages/admin_permalinks.rb

More consistent format.
Before
After

UX: Update some delete confirmation dialogs

---

app/assets/javascripts/discourse/app/components/search-menu.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.gjs
app/assets/javascripts/discourse/tests/integration/components/search-menu-test.gjs

Uses a getter to reactively re-render the search context (eg. "in messages").
Also fixes an issue where although the in:messages suggestion appeared, it didn't work to add the PM context.

UX: make sure search context is kept when navigating

---

migrations/config/intermediate_db.yml
migrations/db/intermediate_db_schema/100-base-schema.sql
migrations/lib/database/intermediate_db/user.rb

Add a table-level override to require `created_at` on `users` table

DEV: Require `created_at` on `users`

---

migrations/lib/importer/copy_step.rb
migrations/lib/importer/discourse_db.rb

Currently, if a  batch "copy" of an import step results in all rows being skipped, the `after_commit_of_skipped_rows` callback is never triggered. This happens because the callback is nested inside a block that only runs when at least one row is inserted.
This change ensures the DB copy operation returns both inserted and skipped rows, allowing the caller to respond appropriately in either case.

FIX: Ensure `copy_data` callbacks run even when all rows are skipped

---

config/site_settings.yml

This setting didn't have an area. Putting it in <kbd>Interface & layout</kbd>.

DEV: Add enable_welcome_banner setting to Interface section

---

app/assets/javascripts/admin/addon/components/admin-badges-show.gjs
app/assets/javascripts/discourse/app/components/ace-editor.gjs
app/assets/javascripts/discourse/app/form-kit/components/fk/control/code.gjs
app/assets/javascripts/discourse/tests/integration/components/ace-editor-test.gjs
app/assets/stylesheets/common/components/_index.scss
app/assets/stylesheets/common/components/ace-editor.scss
app/assets/stylesheets/common/form-kit/_control-code.scss

This commit adds a `@resizable` argument to `<AceEditor />`
and sets it to true always for the FormKit code control.
This allows the user to vertically resize the editor inside
FormKit forms. Horizontal resizing is not allowed at this
time, it's more unpredictable for layout, and the vertical
resizing is mostly what's needed anyway.
Also changes the FormKit code control to use min-height of
250px so the inline style height takes precedence, before
it was a hardcoded !important height.

FEATURE: Add option to make <AceEditor /> resizable

---

app/assets/javascripts/discourse/app/components/search-menu/results/assistant-item.gjs
app/assets/stylesheets/common/base/search-menu.scss
app/assets/stylesheets/common/components/welcome-banner.scss

This gives the search input in the header dropdown consistent spacing by adding top padding to the results wrapper (always present), which avoids issues like this (too little space below while loading):
Also fixes this slight misalignment (`test in all topics and posts` has an extra space on the left):

UX: more consistent search menu spacing

---

app/assets/javascripts/discourse/app/components/modal/dismiss-new.gjs
app/assets/javascripts/discourse/app/controllers/discovery/list.js
app/assets/javascripts/discourse/tests/integration/components/dismiss-new-test.gjs
spec/system/dismissing_new_spec.rb
spec/system/page_objects/modals/dismiss_new.rb

Currently both boxes are always checked, even if you're filtered to new topics or new posts. 
You must have the site setting `Experimental new new view groups` set to your user's group to see this mode. 
This allows both options to appear, but only selects the current filter: 
Turns out this was already implemented, but `subset` was always undefined. This fixes the arg and adds a couple new specs to cover it. 
see /t/155039 for reference

FIX: when new new is enabled, filter dismiss modal to correct type

---

app/assets/javascripts/discourse/app/controllers/topic.js
app/assets/javascripts/discourse/app/templates/topic.gjs
app/assets/stylesheets/common/base/topic.scss

Changes of this commit:
- edit pencil will only show on hover on desktop
- clicking the topic title will display the topic edit UI
https://github.com/user-attachments/assets/58c55351-96ed-4f2d-8bd6-569310901cf0
/t/-/154792

UX: fast topic edit

---

app/assets/javascripts/discourse/app/static/prosemirror/lib/text-manipulation.js
plugins/discourse-details/spec/system/details_spec.rb
spec/system/page_objects/components/composer.rb

When hiding details if the user has currently a text selection we want to use it as the content of the details element.
/t/-/154716/30

FIX: uses text selection when using hide details

---

plugins/discourse-details/assets/javascripts/lib/rich-editor-extension.js
plugins/discourse-details/assets/stylesheets/details.scss

Improves the styles for the [details] caret pseudo-element on the rich editor.
Additionally, having `summary` have no `pointer-events` is important so Firefox doesn't mess with our caret positioning when clicking it.

UX: rich editor [details] caret hover and padding

---

Gemfile
Gemfile.lock

A few minor versions of Bullet were incompatible with Discourse because we use our own content security policy middleware.
This has now been fixed upstream and released in 8.0.7: https://github.com/flyerhzm/bullet/issues/747#issuecomment-2882882825

DEV: Update Bullet to latest version

---

app/assets/javascripts/admin/addon/components/admin-config-areas/components.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/themes.gjs
app/assets/javascripts/discourse/tests/acceptance/admin-install-theme-modal-test.js
app/assets/javascripts/discourse/tests/acceptance/themes-test.js
config/locales/client.en.yml
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes_config_area.rb

- Add subheader with install button to match the <kbd>Components</kbd> tab.
- Remove the "special" card with the install button from the end of the list.

UX: Add subheader to admin themes page

---

db/post_migrate/20250526063633_copy_add_groups_to_about_component_settings.rb
spec/migrations/copy_add_groups_to_about_component_settings_spec.rb

When "Add Groups to About" component is duplicated, choose the most recently updated settings for migration.

FIX: latest duplicated groups to about components

---

config/initializers/012-web_hook_events.rb
spec/initializers/web_hook_events_spec.rb

Currently, if you configure a webhook with reviewable events and apply categories/tags filtering, no webhook gets fired for reviewable events. This is because when we schedule the `EmitWebHookEvent` job, we don't pass to it the reviewable's category or tags, making it seem like the reviewable doesn't belong to the filtering category/tags that webhook specifies.
Internal topic: t/155369.

FIX: Respect category/tag filtering for reviewable webhooks

---

db/migrate/20250527101351_remove_max_similar_results_site_setting.rb

We phased out the site setting for `max_similar_results` in #32934 - this change is a follow up migration to delete the site setting from the database.

DEV: remove max similar results site setting

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/emoji.js
spec/system/composer/prosemirror_editor_spec.rb

When typing `:emoji:` or `:)` to create emoji nodes through ProseMirror inputrules, this PR changes the handler to enforce the use of the existing marks in the current caret position (if it's a link, bold, etc) so the newly created emoji is marked with the same marks(s).

UX: keep marks when using emoji input rules on rich editor

---

app/assets/javascripts/admin/addon/components/admin-config-areas/about.gjs
app/assets/javascripts/discourse/app/components/about-page.gjs
config/site_settings.yml
spec/system/about_page_spec.rb
spec/system/admin_about_config_area_spec.rb

When we ported over the about page extra groups theme component, we used a hidden site setting to control this as per MO.
We don't need this any more. We can simply rely on the presence of any configured groups to decide.

DEV: Have about page extra groups depend on groups selected

---

app/assets/javascripts/discourse/app/components/post-stream.gjs
app/assets/javascripts/discourse/app/lib/keyboard-shortcuts.js
app/assets/stylesheets/common/components/keyboard_shortcuts.scss

This commit fixes displaying the post highlighted when navigating using the keyboard. 
Ember was overriding the direct DOM manipulations, causing the browser outline to be displayed.

DEV: Fix post highlighting for keyboard navigation in the Glimmer Post Stream

---

config/initializers/009-omniauth.rb

In production, the enforce_hostname middleware overwrites the HTTP_HOST env using `Discourse.base_url_no_prefix`, which takes into account any configured protocol/hostname/post overrides.
That middleware is not used in development, so if we want omniauth to respect any host/port overrides, we need to configure the 'full host' directly.

DEV: Use canonical hostname for omniauth callbacks

---

app/models/theme.rb
app/models/theme_field.rb

Theme translations are very simple JS, and do not need to be run through the theme transpiler. This brings their format in-line with core/plugin translations.
Extracted from https://github.com/discourse/discourse/pull/33103

DEV: Simplify theme translation JS generation

---

app/models/theme.rb
app/models/theme_field.rb

Without this wrapper, `data` is defined in the global scope and clashes when there are multiple themes with translations.
Followup to 033cccdf17a56b43f9f243bb549abe0a41a0de63
We can remove the wrapper once we land https://github.com/discourse/discourse/pull/33107

FIX: Wrap theme translations in IIFE

---

lib/version.rb

Version bump for stable: v3.4.5

---

app/controllers/extra_locales_controller.rb
app/helpers/application_helper.rb
app/models/theme.rb
app/models/theme_field.rb
app/views/layouts/application.html.erb
spec/models/theme_field_spec.rb
spec/requests/extra_locales_controller_spec.rb

We will be moving towards `type="module"` for all of Discourse's JS
bundles in the near future. This commit makes a start by applying the
change to translation bundles.
This was previously merged, but the lack of `apply_cdn_headers` on the locales controller led to CORS errors on sites with CDNs.

DEV: Switch to `type="module"` for translation files

---

db/migrate/20250609115711_remove_composer_tips_site_settings.rb

In #33012 we phased out the site settings for:
- `disable_avatar_education_message`
- `sequential_replies_threshold`
- `warn_reviving_old_topic_age`
This change is a follow up migration to delete the site settings from the database.

DEV: remove redundant composer tips site settings

---

app/assets/javascripts/admin/addon/components/admin-config-areas/webhooks-form.gjs
app/assets/javascripts/admin/addon/models/web-hook.js

We had a regression where you can no longer update an existing webhook to have a blank secret field.
The problem is the blank field will return a value of `undefined`, which is ignored by the store when sending the request to the back-end.
This fixes that by using the nullish coalescing operator to replace `undefined` with an empty string.
**In action:**

FIX: Allow setting blank secret on an existing webhook

---

app/assets/javascripts/discourse/app/components/post/meta-data/language.gjs
app/assets/javascripts/discourse/app/lib/transform-post.js
app/assets/javascripts/discourse/app/widgets/post.js
app/assets/javascripts/discourse/tests/integration/components/post/post-test.gjs
app/serializers/post_serializer.rb
config/locales/client.en.yml
spec/serializers/post_serializer_spec.rb

We will not update localization on every edit for now. To compensate, the existing indicator will also add information if a translation might be outdated.
Related: https://github.com/discourse/discourse-ai/pull/1422
/t/156185

FEATURE: Indicate if a localization might be outdated based on version number

---

app/models/backup_file.rb
lib/backup_restore/backup_file_handler.rb
lib/backup_restore/restorer.rb
script/discourse
spec/lib/backup_restore/backup_file_handler_spec.rb
spec/lib/backup_restore/shared_context_for_backup_restore.rb

This commit introduces new features and utilities related to the backup
and restore system that make use of remote URLs:
- `discourse restore` accepts a URL to a backup file
- `discourse backup_url` generates a URL of a backup file (S3 only)
- `discourse import_backup_url` downloads a backup file from a URL to
the configured backup store
This can be used to move content between two Discourse instances by
backing up the entire site, copying the backup URL, importing or
restoring it on the other instance.

FEATURE: Add utilities for importing and exporting backups

---

app/assets/stylesheets/common/base/faqs.scss

Hard to take a screenshot, the "Log In" button having a right margin forced the rest of the block to be slightly misaligned. It's not visible on the default screen, but quite visible when adding other centre-aligned elements to the page.

UX: Properly center-align buttons in login-required screen

---

lib/post_action_creator.rb
spec/lib/post_action_creator_spec.rb

I need reviewables to be created for bot users in a private plugin. This allows me to do that.

DEV: Add Plugin modifier for reviewable creation (bot posts)

---

app/assets/javascripts/discourse/app/components/load-more.gjs
app/assets/javascripts/discourse/app/templates/users.gjs
app/assets/javascripts/discourse/tests/integration/components/load-more-test.gjs
app/assets/stylesheets/common/components/_index.scss
app/assets/stylesheets/common/components/load-more.scss

This commit adds an @enabled boolean to `<LoadMore />` to allow for
cases where the element is visible in the viewport but you don't want to
allow the `loadMore` behaviour. A use case for this is when our
controllers return some `canLoadMore` boolean. There is no use
attempting to load more from the server in this case, there will be
nothing else.
I also moved the CSS styles for the `<LoadMore />` component into
a new file.
This also fixes a bug in the users list shown here
https://meta.discourse.org/t/users-list-only-partial/368793

FIX: Add @enabled arg to <LoadMore /> component

---

app/assets/stylesheets/common/base/menu-panel.scss

Two applications of `--font-down-1` are making this icon *slightly* smaller if it is unread. This should not be the case.

FIX: Unread-icon-size

---

app/assets/javascripts/discourse/app/widgets/post-stream.js

Follow-up to 66564434330e52958cf3a4e90ca1b500b7f40f4c, to fix issue reported here: https://meta.discourse.org/t/super-long-line-in-topic-causing-page-to-be-sidescrolled-a-lot/369637
The addition of the class in the glimmer template resulted in double-classes in the post stream widget. Removing the small-action class fixes this in the widget post-stream without breaking the glimmer post-stream.
Before (note the timegap line going through the timeline):
After (widget):
After (glimmer):

UX: Remove duplicate class from time-gap in post-stream widget

---

app/assets/javascripts/discourse/app/components/post-text-selection-toolbar.gjs
app/assets/javascripts/discourse/app/components/post-text-selection.gjs
app/assets/javascripts/discourse/app/lib/utilities.js
app/assets/javascripts/discourse/tests/helpers/qunit-helpers.js
app/assets/javascripts/float-kit/addon/components/d-inline-float.gjs
app/assets/stylesheets/common/base/topic-post.scss
app/assets/stylesheets/mobile/topic-post.scss
spec/support/system_helpers.rb

This commit is applying different techniques to make selecting text of a post less error prone:
- ensure we only ever show the toolbar when the common ancestor of a range is cooked
- ensures the menu is not interfering with text selection
- do not compute the menu while selection is changing, only when pointer is released
The situation was very bad on android but it should also improve other situations.

FIX: improves text selection of posts

---

spec/system/search_shortcut_variation_spec.rb

We weren't checking for visibility enough before scrolling
I think

DEV: Try fix flaky search shortcut variation test

---

app/controllers/metadata_controller.rb
spec/requests/metadata_controller_spec.rb

Discourse has a fantastic feature whereby when installed as PWA (on Android or Windows), you can share content to that Discourse from other apps and browsers.
Currently when sharing a link to a Discourse PWA, it pre-populates a draft Topic body with the link.
Whilst this is really nice already, we can improve this further.  Currently, sharing a link to the body misses out on the auto-magic core feature of pasting a link in the title which simultaneously hydrates a title from the og tag and creates a one-box in the body.
This PR remedies this whilst carefully maintaining the current behaviour for text shares.
Documentation for the standard is here:
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Share_data_between_apps
Demo of this working change is implemented in …

FEATURE: sharing link to PWA renders url in title in new Topic to leverage core link expansion

---

app/assets/javascripts/discourse/app/templates/preferences.gjs
lib/svg_sprite.rb

We repeat the user icon here, making the icons kind of pointless.
This changes the account and profile icons to potentially be a little more useful. 
Before:
After:
Mentioned here: https://meta.discourse.org/t/ux-improvements-on-header-dropdown-notifications/370110

UX: make all preference icons unique

---

app/assets/javascripts/discourse/app/lib/user-menu/message-item.js
app/assets/stylesheets/common/base/menu-panel.scss

The messages in the message tab did not include a class to show whether it was read or unread.

UX: Add classes to read/unread user menu messages items 

---

app/serializers/admin_detailed_user_serializer.rb
lib/guardian/user_guardian.rb
spec/lib/guardian_spec.rb
spec/serializers/admin_detailed_user_serializer_spec.rb

There is a bug that when `SiteSetting.enable_names` is disabled, the admin can click the pencil next to the user and successfully update the name. However, the change is not saved as the action is blocked by the guardian.
Meta: https://meta.discourse.org/t/disabling-enable-names-makes-admin-act-strange/291912

FIX: Admin can edit the name even if enable_names is disabled

---

app/assets/javascripts/admin/addon/controllers/admin-site-settings-category.js
app/assets/javascripts/admin/addon/controllers/admin-site-settings.js
app/assets/javascripts/admin/addon/models/site-setting.js
app/assets/javascripts/admin/addon/routes/admin-site-settings-category.js
app/assets/javascripts/admin/addon/routes/admin-site-settings-index.js
app/assets/javascripts/admin/addon/routes/admin-site-settings.js
app/assets/javascripts/admin/addon/templates/site-settings-category.gjs
app/assets/javascripts/admin/addon/templates/site-settings.gjs

The filtering is currently being done in the controller. This leads to weird things where the filter loop might already be initiated and we get double filtering, as well as the issue that we can't abort like we could with a route transition.
- Cache the site settings fetched from the server in the route instance.
- Hook up the controller to the query params.
- Use the query params to filter the `model` in the route.

DEV: Change admin site settings filter to be route based

---

config/initializers/101-lograge.rb
lib/discourse_logstash_logger.rb

Before this change, we were relying on the `lograge`'s gem default
`log_level` of `info`. However, `lograge` should be following
`Rails.application.config.log_level` instead and this commits seeks to
correct that behaviour.

DEV: Fix lograg `logger` and `log_level` not following rails `log_level`

---

app/controllers/admin/config/customize_controller.rb
config/site_settings.yml
db/migrate/20250617064103_migrate_experimental_system_themes_site_setting_to_enum.rb
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes_config_area.rb

Before it was Boolean. 
The list is giving more control over which system themes should be displayed.

DEV: change experimental_system_themes setting to list

---

app/models/upload.rb
lib/file_store/s3_store.rb
lib/s3_helper.rb
spec/lib/file_store/s3_store_spec.rb
spec/models/upload_spec.rb

This commit is a follow-up to b02bc707dec12c607511d4a95c7d791f63131b49
where `Upload#update_secure_status` does not call `FileStore::S3Store#update_upload_access_control` if
`s3_use_acls` is disabled. This is no longer correct as an upload's
access control on S3 can now be based on tags if the `s3_enable_access_control_tags` site setting is
enabled.
To fix this, this commit removes the `s3_use_acls` check in `Upload#update_secure_status` and updates `FileStore::S3Store#default_s3_options`
to not set the `acl` option if the `s3_use_acls` site setting is disabled.

FIX: `Upload#update_secure_status` not updating s3 access control

---

lib/service/base.rb
lib/service/steps_inspector.rb

Currently when a model is not found, we raise an `ArgumentError` exception and that exception is stored in the resulting context object.
However, since we’re also storing unexpected exceptions, this default exception can pollute the context object when we need to inspect it or act on it.
This PR addresses that issue by raising a custom exception instead, and we then discard it from the context object.

DEV: Remove generic exception in model step in services

---

plugins/automation/app/models/discourse_automation/field.rb
plugins/automation/spec/requests/admin_discourse_automation_automations_spec.rb

The `on_update` callback of triggers is called with previous fields and new fields, values. However since a recent change: https://github.com/discourse/discourse/pull/32810 this relationship is cached and would cause previous fields to equal new fields. This commit ensures we are refreshing the relationship before calling the `on_update` callback.

FIX: correctly refreshes associated fields after update

---

lib/seed_data/categories.rb
spec/lib/seed_data/categories_spec.rb

This change adds some flair to the default seeded categories by adding emojis for new sites:
Internal ref: /t/156455

FEATURE: add emojis to seeded categories

---

app/assets/javascripts/discourse/app/components/post/avatar.gjs

This adds an outlet wrapper for post avatar flair to keep in line with the existing pattern we see with user card and profile avatar flair:
https://github.com/discourse/discourse/blob/8cc009ceebe55a6650cf424b003878279fe276c0/app/assets/javascripts/discourse/app/components/user-card-contents.gjs#L391-L399
https://github.com/discourse/discourse/blob/8cc009ceebe55a6650cf424b003878279fe276c0/app/assets/javascripts/discourse/app/components/user-profile-avatar.gjs#L21-L27

DEV: Add outlet wrapper for post avatar flair

---

app/controllers/session_controller.rb
lib/discourse.rb
spec/requests/session_controller_spec.rb

When we migrated to the full page /login, we added a nice feature that will automatically redirect a user to the idp if it's the only way they can log in, thus avoiding unecessary click.
But when logging out, we would redirect to the /login page which would start the /login process by automatically redirecting the user to the idp...
The fix is easy, redirect back to `/login-required` after logging out instead. This will show the "splash" screen that asks the user to either log in or sign up.
Note: I also removed the `Discourse::Utils::EMPTY_KEYWORDS` since it was its last occurence and I'm pretty sure we dropped support for Ruby 2 a while ago...
Internal ref - t/156834

FIX: prevent login loop when logging out when only one idp

---

app/assets/javascripts/discourse/app/lib/hashtag-decorator.js
plugins/chat/assets/javascripts/discourse/lib/hashtag-types/channel.js

When category lazy loading was disabled, chat channel CSS classes were not being inserted into the page markup. This meant that they would not be styled correctly in the markdown editor preview.

FIX: add channel hashtag color when lazy load is disabled

---

lib/service/base.rb
spec/lib/service/runner_spec.rb
spec/lib/service/steps_inspector_spec.rb

When fetching a model using the `model` step in a service, if that model is an `ActiveRecord` object, we check if it’s in a valid state. While this is useful when manipulating the model or when creating a new one, it’s not the case for a model we just pulled from the DB, as it should be valid.
In some cases, running the validations can be costly (it can lead to N+1 queries if the model validates associated items for example).
This PR introduces a small optimization by checking if the model has any pending changes on it, thus requiring validation. If that’s not the case, we just skip the validation part, as the model should be valid anyway.

DEV: Don’t check model validity when no changes have been made

---

app/assets/javascripts/discourse/app/controllers/preferences/account.js
app/assets/javascripts/discourse/app/templates/preferences/account.gjs
app/serializers/auth_provider_serializer.rb
lib/auth/auth_provider.rb
lib/auth/authenticator.rb
lib/auth/discord_authenticator.rb
lib/auth/discourse_id_authenticator.rb
lib/auth/facebook_authenticator.rb
lib/auth/github_authenticator.rb
lib/auth/google_oauth2_authenticator.rb
lib/auth/linkedin_oidc_authenticator.rb
lib/auth/twitter_authenticator.rb
spec/system/user_page/user_preferences_account_spec.rb

This adds a link for each authentication providers that are listed in /my/preferences/account in the "Associated Accounts" section.
This is particularly useful when Discourse is being used in the PWA or in the DiscourseMobile app where there's no browser bar available and the only way to visit the provider's website is to open a browser window.
That way, they can _just_ click the provider's name.
Internal ref - t/156255
---
**BEFORE**
**AFTER**

FEATURE: add link to "associated accounts" providers

---

app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/form-test.gjs

This commit ensures the form errors summary is visible on error.

UX: scroll to top of form on error

---

plugins/chat/assets/javascripts/discourse/components/chat-message-text.gjs
plugins/chat/assets/javascripts/discourse/initializers/chat-decorators.js
plugins/chat/spec/system/chat_message_onebox_spec.rb

Chat inline onebox links should open in a new tab with the help of chat decorators by appending the `target="_blank"` attribute. I suspect this may have been accidentally broken during a refactor in #31309 
The issue was that the element that we pass into the decorator has changed, meaning that the selector in the decorator would never find inline links in cooked messages.

FIX: chat message inline onebox url target

---

Gemfile.lock
spec/lib/backup_restore/s3_backup_store_spec.rb
spec/lib/s3_helper_spec.rb
spec/support/fake_s3.rb

In an upcoming pr #33092 that adds support for aws-sdk-mediaconvert it requires
that we bump aws-sdk-core to 3.225.0
```
+    aws-sdk-mediaconvert (1.160.0)
+      aws-sdk-core (~> 3, >= 3.225.0)
```
but in doing so there are apparently some api changes and it requires changes
in core to support the new version. I thought it would best to break out these
changes in a separate PR as to not muddy up the mediaconvert pr that is already
quite large.

DEV: Bump aws-sdk-core in prep for aws-sdk-mediaconvert

---

app/models/concerns/reports/trust_level_growth.rb
app/models/report.rb
spec/models/report_spec.rb

A previous refactor change colors from an array to hash and this specific report had not been updated.
This commit correctly uses named colors and improves the existing spec to ensure we check for colors.

FIX: ensures colors are set for tl-growth report

---

docs/ADMIN-QUICK-START-GUIDE.md

As reported in https://meta.discourse.org/t/self-hosted-discourse-instance-appending-7d-to-the-fqdn/371144, there was an extra "7D" in the URL which caused the link to break.

FIX: broken link in admin quick start guide

---

app/assets/stylesheets/common/components/empty-states.scss

Followup 30b0e38877af703606042cf1a2997a9a06582c32
Changes margin to padding for topic filter empty state to prevent the
"See X new or updated topics" banner from overlapping with the empty state
when there are no topics in the filter.
**BEFORE**
**AFTER**
**Mobile**

UX: Fix new/unread topic banner overlap with topic filter empty state

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/textarea.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/textarea-test.gjs

The FormKit textarea component was using `@field.value` as inner content, preventing dynamic updates to the `textarea` value through the form API.
This change moves the `textarea` value to being set in the `value` attribute, instead.
Confirm that the automated tests cover expected behaviour.

FIX: FormKit textarea value attribute binding

---

app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js
plugins/chat/assets/javascripts/discourse/initializers/chat-admin-plugin-configuration-nav.js
plugins/chat/config/locales/client.en.yml

Fixes an issue where the admin search results was showing
breadcrumbs with a double up of the parent label. For example,
we would show "Plugins > Plugins > AI > Usage" or
"Advanced > Advanced > Backups > Logs".
Also adds a missing translation for the chat incoming webhooks
page.

FIX: Admin search labels doubled up with parent label

---

lib/service/base.rb
plugins/chat/app/serializers/chat/messages_serializer.rb
plugins/chat/app/services/chat/channel/policy/message_existence.rb
plugins/chat/app/services/chat/list_channel_messages.rb
plugins/chat/app/services/chat/list_channel_thread_messages.rb
plugins/chat/spec/services/chat/channel/policy/message_existence_spec.rb
plugins/chat/spec/services/chat/list_channel_messages_spec.rb
plugins/chat/spec/services/chat/list_channel_thread_messages_spec.rb

- improve the contract a little.
- use `model` where possible.
- extract message existence logic to a dedicated policy, allowing easier
testing.
- remove unused code.
- refactor specs to follow current guidelines/best practices.

DEV: Refactor Chat::ListChannelMessages service a bit

---

app/assets/javascripts/discourse/app/services/composer.js
spec/system/content_localization_spec.rb
spec/system/page_objects/components/composer.rb

This PR relates to the locale setting in the composer and fixes 2 quirks:
- When replying to a post, the composer sets the locale of the new post in composer to the locale of the post being replied. This PR defaults the value to "none"
- When creating a new post, the composer sets the locale to the user's locale. However we are seeing the behaviour that users do not write in the locale they set their profile to. This PR defaults the value to "none"

FIX: Do not set locale when replying and also default to none

---

app/assets/stylesheets/common/base/sidebar-section-link.scss

Before:
After: 
To match the sizing with tags:

UX: consistent sizing for configure default nav links

---

app/models/user.rb
spec/models/user_spec.rb

All the way back in bc52bdfa1280ba08e6fb1931c26e18aa7fee9f7f we changed
the definition of new_user_posting_on_first_day? to return true if the
user was TL0 unconditionally. However this changes the logic of
the method, and essentially makes it "lie". Yes TL0 may be considered
a new user in other places, but in this method specifically we want
to check it's their "first day" of posting, not just that they are TL0.
The intent per these commits:
* 487c20959c874666db726d69c00abe139ba1aeab
* 5aa1272f05fc0de0b08577707d3370d10fafdd51
* 9834d1150300de26ffc35cb6af9a3ac91666e216
Was consider any user < TL2 who hadn't made their first post yet
as a new user posting on their first day. If they had made a post
>= 24 hours ago, they were no longer considered a new user posting
on their first day.
This …

FIX: Correct new_user_posting_on_first_day? logic

---

lib/site_settings/label_formatter.rb

Site settings with the acronym "ui" in them will now have it formatted as "UI".

DEV: Add "UI" as a humanizable acronym

---

app/assets/javascripts/discourse/app/widgets/post.js
app/serializers/post_serializer.rb
spec/serializers/post_serializer_spec.rb
spec/system/content_localization_spec.rb
spec/system/page_objects/components/composer.rb
spec/system/page_objects/components/post.rb

Previously, there was no way to edit post localizations, so the `post.raw` was always returning the localized value. With localization UI and endpoints now, we want to always return the original raw and the composer to reflect the original value.
https://github.com/discourse/discourse/pull/33184 will handle the decision to show the post edit composer or the post localization composer.

FIX: Return the post's raw when GET /post

---

app/assets/javascripts/admin/addon/components/site-setting.gjs
app/assets/javascripts/admin/addon/components/theme-setting-editor.js
app/assets/javascripts/admin/addon/components/theme-setting-relatives-selector.js
app/assets/javascripts/admin/addon/components/theme-translation.js
app/assets/javascripts/discourse-markdown-it/addon-main.cjs
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.gjs

Fixed the refs to the `setting` argument and refactored more of the component over to glimmer style

FIX: Hide secret admin fields by default

---

migrations/bin/cli
migrations/lib/cli/import_command.rb
migrations/lib/importer.rb
migrations/lib/importer/executor.rb

It deletes the MappingDB before executing the import. That's useful during development when you repeat the import multiple times.

DEV: Add `--reset` option to `import` command

---

lib/version.rb

Version bumps for main: v3.5.0.beta7, v3.5.0.beta8-dev

---

app/serializers/theme_settings_serializer.rb

Followup 5b236ccc0774e3b0f5e0b34c99c1c36d9ea9604e, a change here
made it so the theme setting name was no longer showing on the
UI, this commit fixes the issue by making sure it's sent from
the server in the same way as site setting humanized names.

FIX: Add humanized setting names for theme setting serializer

---

app/jobs/regular/sync_access_control_for_uploads.rb
lib/file_store/s3_store.rb
lib/tasks/uploads.rake
spec/lib/file_store/s3_store_spec.rb

The `uploads:sync_access_control` rake task should reset the access control
of all s3 objects linked to an upload record. This means that if the
`s3_use_acls` site setting has been disabled, the rake task should
remove the existing ACL that has been set previously.

DEV: Update `uploads:sync_access_control` rake task to remove ACLs

---

app/controllers/admin/config/flags_controller.rb
app/models/flag.rb
app/models/post_action.rb
app/models/reviewable_score.rb
app/serializers/flag_serializer.rb
app/serializers/site_serializer.rb
db/migrate/20250620025548_add_index_to_post_actions_on_post_action_type_id.rb
db/migrate/20250620033435_add_index_reviewable_scores_on_reviewable_score_type.rb
spec/models/flag_spec.rb
spec/serializers/flag_serializer_spec.rb

`SiteSerializer#post_action_types` and `SiteSerializer#topic_flag_types`
both call the `Flag.used_flag_ids` method which executes queries that
becomes very slow on sites with alot of records in either the `post_actions` or `reviewable_scores` table.
On the `post_actions` table, we execute `SELECT DISTINCT
post_action_type_id FROM post_actions`. On the `reviewable_scores`
table, we execute `SELECT DISTINCT reviewable_scope_type FROM
reviewable_scopes`. The problem with both queries is that it requires
the PG planner to scan through every single row in those tables.
For our use case, all we actually need is to check if a flag is being
referenced by a record in either the `post_actions` or
`reviewable_scores` tables. This commit updates the `Flag.used_flag_ids` to accept a `flag_ids` …

PERF: Avoid slow preloading in `SiteSerializer`

---

lib/search.rb
spec/lib/search_spec.rb

There exists a hidden `search_recent_regular_posts_offset_post_id` site
setting which is used to optimize the searching of recent posts through
the use of a partial index. However, we do not want this optimization to
apply when the `before` and `after` advanced search filters are used
since the partial index only contains the most recent posts 1 million
posts and the `before`/`after` filter may be searching for posts that falls outside of the 
most recent posts range.

FIX: Ignore recent posts offset in search when before/after filters are used

---

app/assets/javascripts/admin/addon/components/site-setting.gjs
app/assets/javascripts/discourse/tests/integration/components/site-setting-test.gjs

Previously it always had a slash through it. Now it has a slash if clicking it will hide the site setting, and no slash if clicking it will show the site setting.

DEV: Update eye icon behavior for secret site settings

---

plugins/chat/assets/javascripts/discourse/components/chat-upload.gjs

Turns out we do need the iOS check, not just the safari check.
Follow up to: #33199

FIX: Chat video thumbnails on iOS

---

app/jobs/regular/export_user_archive.rb

I'm extending this job in a plugin and need to be able to access an additional job arg in the `provide_results` method (see https://github.com/discourse/discourse/pull/33328)

DEV: Pass ExportUserArchive job args into provide_results method

---

app/assets/javascripts/admin/addon/components/admin-config-areas/components.gjs

Reported here: https://meta.discourse.org/t/components-list-not-showing-all-components-after-deleting-one/371784
Deleting a component reloads the component list, but doesn't maintain pagination if the admin loaded multiple pages of components... so you can end up with only a partial list after delete. 
This instead removes the component from the array without a reload, so it maintains the current list state.

UX: delete components without full reload to maintain pagination

---

app/assets/stylesheets/common/base/_topic-list.scss

These were a bit too large relative to tags and had some extra space...
Before:
After:

UX: minor adjustments to participant group badge

---

app/controllers/admin/themes_controller.rb
lib/guardian/user_guardian.rb
spec/requests/admin/themes_controller_spec.rb

This PR adds a new modifier that plugins can hook into to add further restriction to who install themes and components via the admin UI. It isn't possible to use this modifier to open up the theme installation permissions to more than core allows, e.g. this modifier can't be used to allow moderators to install themes on the site.
Internal topic: t/156924.

DEV: Add modifier for restricting theme creation endpoints

---

app/assets/javascripts/discourse/app/components/emoji-picker/content.gjs
app/assets/javascripts/discourse/tests/integration/components/emoji-picker-test.gjs

This change ensures that emoji search results have the appropriate skin tone applied, when a diversity option has been selected.
Check that the emoji selector uses the correct skin tone when a diversity option is set, and no skin tone when no diversity option is set.

FIX: Apply diversity preferences to emoji search results.

---

app/assets/javascripts/discourse/app/components/header/contents.gjs

This passes a couple additional args to the `header-content__before`. This is used by a private plugin, to append the sidebar hamburger back in a specific case.

DEV: Pass additional args to header-content__before PluginOutlet

---

lib/tasks/themes.rake
spec/tasks/themes_spec.rb

When the remote horizon color scheme is `user_selectable`, the system color scheme should be as well.

FIX: improve the merge horizons task

---

config/site_settings.yml

No tests are this is mostly a UX change which we don't expect to regress easily.

UX: Add `flag_post_allowed_groups` site setting to `flags` area

---

app/assets/javascripts/discourse/app/modifiers/grippie-drag-resize.js

Scopes a check introduced on https://github.com/discourse/discourse/pull/33046 to `mousedown` events, it was preventing touch events to be used to drag the grippie.
Reported on [meta.discourse.org](https://meta.discourse.org/t/composer-resizing-problems-while-using-a-tablet/370706).

UX: avoid suppressing non-click events when dragging the grippie

---

app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js
spec/system/edit_category_images_spec.rb
spec/system/page_objects/pages/category.rb

**Problem**
An error is showing up for staff members when trying to upload images and `SiteSetting.authorized_extensions = ""` and  `SiteSetting.authorized_extensions_for_staff != ""` because `this.currentUser` is not defined in the `UppyUploader` component

FIX: UppyUploader issues when authorized_extensions setting is blank but authorized_extensions_for_staff is not

---

app/assets/javascripts/discourse/app/lib/uppy/uppy-upload.js
spec/system/edit_category_images_spec.rb
spec/system/page_objects/pages/category.rb

**Problem**
An error is showing up for staff members when trying to upload images and `SiteSetting.authorized_extensions = ""` and `SiteSetting.authorized_extensions_for_staff != ""` because this.currentUser is not defined in the UppyUploader component
stable backport for #33423

[stable] FIX: UppyUploader issues when authorized_extensions setting is blank but authorized_extensions_for_staff is not

---

app/assets/javascripts/discourse/app/components/user-fields/dropdown.gjs
app/assets/javascripts/discourse/app/components/user-fields/multiselect.gjs
app/assets/javascripts/discourse/app/lib/user-fields-validation-helper.js
config/locales/client.en.yml
spec/fabricators/user_field_fabricator.rb
spec/system/signup_spec.rb

Dropdown and multiselect components lack `InputTip`, which makes them not show any reason when validation fails.
This commit also adds a new i18n message for select fields, after this commit, if a multiselect or dropdown custom field required has no option selected, it will display a `Please select a value for "XX" field` validation error when the Signup button is clicked.

FIX: Show tip for required selectable field on signup when not selected

---

app/assets/javascripts/admin/addon/templates/customize-themes-show-index.gjs
config/locales/client.en.yml
spec/system/admin_customize_themes_spec.rb
themes/horizon/javascripts/discourse/components/card/topic-activity-column.gjs
themes/horizon/javascripts/discourse/components/card/topic-status-column.gjs
themes/horizon/locales/en.yml

List of small changes for the system Horizon theme:
- Remove"Created by: system"
- Remove All Extra Files section
- Move translation to core
- Remove settings editor button
- Remove export button

UI: improvement for the admin system theme

---

app/assets/javascripts/discourse/app/components/reviewable-claimed-topic.gjs
spec/system/page_objects/pages/review.rb
spec/system/reviewables_spec.rb

`ReviewableClaimedTopic` has an `onClaim` arg, which is used by the calling components to locally mutate the value of `reviewable.claimed_by`.
This was being incorrectly mutated to a User model, when it in fact needs to match the `ReviewableClaimedTopicSerializer` output.
Claim and unclaim reviewables, confirm that:
- The UI updates correctly as soon as you perform the claim/unclaim (client side updates are correct).
- The UI is displayed correctly after reloading the page (server side updates are correct).

FIX: Ensure client-side reviewable claiming data is set correctly

---

app/assets/javascripts/discourse/app/components/reviewable-refresh/flag-reason.gjs
app/assets/javascripts/discourse/app/components/reviewable-refresh/item.gjs
app/assets/javascripts/discourse/tests/integration/components/reviewable-refresh/item-test.gjs
app/assets/stylesheets/common/base/_index.scss
app/assets/stylesheets/common/base/review.scss
config/locales/client.en.yml
spec/system/page_objects/pages/reviewable.rb
spec/system/viewing_reviewable_spec.rb

This commit adds a header with badges indicating why a reviewable was
created in the refreshed reviewable UI that is currently being hidden
behind the `reviewable_ui_refresh` site setting.
Mobile design will be considered in a future iteration.

DEV: Display flag reasons and count for reviewable in refreshed UI

---

app/assets/javascripts/discourse/app/components/post-text-selection.gjs

Prior to this fix you could select the text of a small action (after closing a topic with a message for example) and it would show the toolbar.
This commit will now ensure the common ancestor of the text range has no ".small-action" node as parent.
No test as it's currently very hard to test this behavior due to the debouncing delay causing the check for "no_css" to always be true, I need to re-think few parts of the toolbar to make it reliable. We also have other tests in the codebase which are currently not testing the reality for the same reason: spec/system/post_selection_copy_quote_spec.rb

FIX: ensures small actions don't trigger post toolbar

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/hashtag.js
app/assets/javascripts/discourse/tests/integration/components/prosemirror-editor/hashtag-test.js

Correctly renders emojis within hashtag text (ie. chat channel titles) in composer rich text mode.

FIX: render emojis in cooked hashtag text for composer rich text mode

---

app/assets/javascripts/discourse/app/components/post-text-selection.gjs

At this point cooked could be null and checking if it's inside a small action is useless and would generate an error which wouldn't break anything but is something we want to avoid.

FIX: ensures we have a cooked to work with

---

app/assets/stylesheets/common/base/discourse.scss

follow-up to https://github.com/discourse/discourse/commit/e4be2df16a86c29837ee082f0fb0e09ef0edc6a1
The switch to rem made these based on the document font size, but they should scale with the title font size 
Before:
After:

UX: fix title status icon size

---

app/assets/javascripts/discourse/app/templates/discovery/login-required.gjs

One can use it in a plugin to override the whole "login-required" template without having to replace all the different (and smaller) plugin outlets already available in that template.
Internal ref - t/154909

DEV: add login-required wrapper plugin outlet

---

app/assets/javascripts/discourse/app/components/post/meta-data/reply-to-tab.gjs
app/assets/javascripts/discourse/app/widgets/post.js

Adding an empty href to this link makes it keyboard accessible. You can now trigger it with the enter key. This also allows us to remove the tabindex. 
`event.preventDefault();` is neccessary because otherwise `href=""` was resulting in a page refresh, and another work around like `href="#"` was adding an entry to the browser history

A11Y: make in-reply-to keyboard accessible

---

plugins/chat/assets/stylesheets/common/chat-transcript.scss

This fixes an issue where the YouTube thumbnail was huge in a chat
transcript, like in this scenario:
* Share a link to a youtube video in channel A
* See it onebox at a reasonable size
* Grab a link to your message
* Share the link to your message in channel B (e.g. a DM to yourself)
* :x: See GIANT youtube image
This commit only fixes the issue visually though -- it does not apply
the LazyYoutube decorations that actually embed the video. We can do
this in a followup commit.
**Before**
**After**

UX: Shrink YouTube thumbnail in chat transcript

---

lib/guardian/user_guardian.rb
spec/lib/guardian/user_guardian_spec.rb

The site setting `hide_new_user_profiles` states:
> Hide trust level 1 or lower user profiles from the public and trust level 1 users until they post for the first time.
This implies that TL2 and above should be visible.
However, the actual logic encodes the assumption that TL2 have posted at some point. This fails to account for the fact that admins can manually upgrade a user without posts to a higher TL. This PR covers for that scenario.

FIX: Make hide_new_user_profiles work with manually upgraded users

---

app/assets/javascripts/discourse/app/templates/review-show.gjs
app/serializers/current_user_serializer.rb
spec/system/reviewables_spec.rb

This commit adds a `use_reviewable_ui_refresh` attribute to the
`CurrentUserSerializer` and updates the client side to use this
attribute as a feature flag to determine when the new reviewable UI
should be shown.

DEV: Add `CurrentUserSerializer#use_reviewable_ui_refresh` attribute

---

app/assets/javascripts/discourse/app/lib/load-full-calendar.js
app/assets/javascripts/discourse/app/static/full-calendar-bundle.js
app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

Usage:
```js
import loadFullCalendar from "discourse/lib/load-full-calendar";
const calendarModule = await loadFullCalendar();
const fullCalendar = new calendarModule.Calendar(...);
```
This will be used in discourse-calendar.

DEV: allows to load full calendar 6 as an async bundle

---

app/assets/javascripts/discourse/app/static/dev-tools/plugin-outlet-debug/args-table.gjs

- Use `String()` instead of `.toString()`
- Safe navigation on `constructor`
- Catch & log any other errors, to prevent rendering blowing up

DEV: Make outlet argument stringification more robust

---

app/assets/javascripts/discourse/app/components/composer-editor.gjs

Having a text selection can cause issues on iOS where the caret will show over any other element. The state is already stored in the toolbar state so we don't need to keep it actually selected.
No test as it's a very specific behavior and a whole system spec for this seems heavy.

FIX: clear selection on expand popup menu

---

app/assets/javascripts/discourse/app/components/reviewable-refresh/post.gjs
app/assets/stylesheets/common/base/review.scss

This commit makes a UX pass at the layout when displaying a reviewable
of `ReviewableFlaggedPost` type.

DEV: Improve layout of flagged post in new reviewable UI

---

app/controllers/invites_controller.rb
spec/requests/invites_controller_spec.rb

This PR adds an `invite_bulk_csv_custom_error` apply_modifier to the invite_controller's `upload_csv` method.
This change lets plugins to add custom error message when bulk invite is created.

DEV: Add apply_modifier to invite upload_csv

---

lib/backup_restore/backup_file_handler.rb
spec/lib/backup_restore/backup_file_handler_spec.rb

Moving parsing the URL to the constructor ensures that is_archive is correctly initialized. This allows .sql.gz backups to be restored.

FIX: Handle restore URLs ending with query params

---

config/locales/server.en.yml
config/site_settings.yml

Moves the `rich_editor` site setting from the experimental to the posting section, and updates its copy.

UX: move rich_editor setting from experimental to posting

---

app/assets/javascripts/admin/addon/components/admin-badges-show.gjs

This button has been broken for awhile and its text is not properly
translated. Given that there is already a top level button to manage
badge groupings, it makes more sense for us to drop this button than to
fix it.

DEV: Remove broken button in admin badge show template

---

app/assets/javascripts/admin/addon/components/admin-badges-show.gjs
spec/system/admin_badges_spec.rb

This is mostly a fix for the UI which incorrectly disables the badge
grouping field for system badges. However, nothing in the backend
suggests that the badge grouping for system badges is disallowed. This
is confirmed by the fact that `Badge.protected_system_fields` do not
list the `badge_grouping_id` column as protected.

FIX: Badge grouping for system badges should be editable

---

spec/fabricators/reviewable_fabricator.rb

For a reviewable of `ReviewableFlaggedPost` type, the reviewable's
`topic_id` should be set to the target post's `topic_id`.

DEV: Correct `reviewable_flagged_post` fabricator

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/calendar.gjs
app/assets/javascripts/discourse/app/form-kit/lib/validation-parser.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/calendar-test.gjs

I ran into an issue where the date was being set back 1 day. This is due to Midnight in Kansas being the past day in UTC. Check this out:
___
This change does a simple parsing of the date string, and extracts the year/month/days out, so that picking a date from any timezone will keep it at that date (the time is separate -- this is OK!)

FIX: Formkit calendar date setting back one day

---

app/assets/stylesheets/common/rich-editor/rich-editor.scss

Minor followup to d07443a721224b16d74eb52ba72fda50d562e6cb
Makes it so emojis do not have rounded borders in the RTE,
this affects the appearance of some of them (like floppy disk)
**Before**
**After**

UX: Do not round emoji img borders in RTE

---

app/assets/javascripts/discourse/app/static/prosemirror/components/image-node-view.gjs
app/assets/javascripts/discourse/app/static/prosemirror/extensions/image.js
app/assets/javascripts/discourse/app/static/prosemirror/lib/glimmer-node-view.js
spec/system/composer/prosemirror_editor_spec.rb

Adds a `![markdown](image)` input rule that uses the markdown parser to create an image node.
Supporting this format surfaced an issue with dimension-less images, so now the image node view uses the max width/height site settings in addition to the loaded image natural dimensions to determine what a 100% looks like – it's used for display, and also when a zoom-out button action is taken, so we calculate the next step % of the calculated dimensions.

FEATURE: image input rule when typing on rich editor

---

app/assets/javascripts/discourse/app/components/post-stream.gjs
app/assets/javascripts/discourse/app/modifiers/post-stream-viewport-tracker.js

This PR enhances the accuracy of post height calculations during cloaking and uncloaking in the Discourse post stream. The main improvements include:
- Capturing and restoring the full set of post styles (height, margin, etc.) instead of only the height, reducing rounding errors and visual glitches when posts are cloaked or uncloaked.
- Introducing a hysteresis mechanism to the uncloaking logic. This means posts now require a more significant and sustained intersection with the viewport before being uncloaked, preventing rapid toggling or flickering when a post is near the edge of the viewport.
- Refactoring the style application and visibility tracking logic to support these improvements and ensure smoother post rendering and scrolling performance.
There are no tests added because …

DEV: Add hysteresis to post-stream uncloaking to prevent layout shift flicker

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/image.js

Changes the regex to be a bit less strict and allow `)`s in the input rule.
For example, `![image](https://upload.wikimedia.org/wikipedia/commons/3/37/Terry_Pratchett\_(3x4_cropped).jpg)` is a valid markdown, but wouldn't get converted with the previous regex.

UX: allow parens on rich editor img input rule

---

app/assets/javascripts/discourse/app/components/reviewable-refresh/note-form.gjs
app/assets/stylesheets/common/base/review.scss

This is a general clean-up of the reviewable note form component, including these changes:
- Hands off the note validation to FormKit validation checks (thanks @jjaffeux and @lis2 for pointing these out).
- Removes the keyboard shortcut for form submission, in favour of putting it into FormKit (#33527)
- Removes the check that disables the submit button when no note content is entered.
I initially experimented with adding stripped down validation checks to all FormKit forms that would disable the submit button until all required fields were set, matching the previous behaviour of the note form. I got it working quite well, avoiding the potential performance issues of running all form validation checks on large forms whenever a value changed. However, I decided not to go ahead with it for …

DEV: Use FormKit APIs for reviewable note validation.

---

app/assets/javascripts/discourse/app/components/reviewable-refresh/topic-link.gjs
spec/system/page_objects/components/review/topic_link.rb
spec/system/page_objects/pages/review.rb
spec/system/viewing_reviewable_spec.rb

This commit fixes a problem in the new reviewable item template that uses the `reviewable-refresh/topic-link` component where a topic is always shown as deleted even if the topic is present.

DEV: Fix topic link component for reviewabled flagged post in new UI

---

app/assets/javascripts/discourse/app/components/language-switcher.gjs
spec/system/anon_language_switcher_spec.rb

While topics, posts, and titles had the language switched, controls were still in the old language. Force a full refresh.
Related: t/157985

DEV: Force full refresh from language switcher

---

app/assets/javascripts/discourse/app/form-kit/components/fk/control/textarea.gjs
app/assets/javascripts/discourse/tests/helpers/form-kit-helper.js
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/password-test.gjs
app/assets/javascripts/discourse/tests/integration/components/form-kit/controls/textarea-test.gjs

When a FormKit textarea is focussed, there's currently no way to submit the form using the keyboard without tabbing out of the textarea.
This change lets the form be submitted using the Ctrl/Cmd+Enter key combination, bringing consistency with the post and chat composers.

FEATURE: Allow Ctrl/Cmd+Enter to submit a form from a textarea

---

app/assets/stylesheets/color_definitions.scss

Followup 20f57aec12a5d2291c79a447d18eb3f164877c61
Adds missing --topic-timeline-border-color CSS var,
otherwise topic timeline vertical line is not shown. Fixes
this:

FIX: Missing topic timeline color var

---

app/assets/stylesheets/common/base/discourse.scss

Followup 20f57aec12a5d2291c79a447d18eb3f164877c61
Fixes header horizontal padding on mobile devices by
setting a value for `--d-header-padding-v` instead of 0.
Used the same value as `--d-wrap-padding-h` since that
is what it was previous to the referenced commit.
**Before**
**After**

FIX: Header horizontal padding on mobile

---

app/assets/javascripts/discourse/app/components/modal/avatar-selector.gjs
app/controllers/users_controller.rb
config/locales/server.en.yml
config/site_settings.yml
db/post_migrate/20250709051949_disable_gravatar_enabled_if_unconfigured.rb
spec/requests/users_controller_spec.rb
spec/system/page_objects/modals/avatar_selector.rb
spec/system/user_page/user_preferences_account_spec.rb

We want to add the ability to enable/disable users selecting Gravatar for their avatar.
This change adds a site setting to enable/disable the option (default to enabled.) This will prevent users from configuring Gravatars from that point on. It does not affect already configured avatars.
We're also taking this chance to hide some of the advanced settings from the UI.

DEV: Add a Gravatar enable/disable toggle

---

app/assets/stylesheets/common/toolbar-popup-menu-options.scss

Addressing some z-index issues with the first use of Dmenu within the composer:
* z-index need an adjustment on mobile/tablets
* z-index need an adjustment when in fullscreen on desktop
Also limiting the max height on desktop to 30vh to avoid it potentially scrolling of the page without a way to fix it by resizing composer height.
Meta report: https://meta.discourse.org/t/composer-more-menu-partly-hidden-behind-header-and-composer/372859

FIX: z-index issues with new DMenu in composer

---

app/assets/stylesheets/common/components/banner.scss

When a topic is pinned as a site banner, we include automatically generated anchor links from the post in the banner's content... but do not include the anchor functionality from the topic (topic seen below)
This means we end up with a 0 dimension link in the banner content, which is still reachable via keyboard and other forms of navigation. You can see the outlined link below:
This can be confusing if you're using a screenreader, and the anchor links don't serve much purpose when included in these banners. Hiding them with CSS avoids the issue.

A11Y: hide anchor links from global site banners

---

app/assets/javascripts/discourse/app/components/post/quoted-content.gjs
app/assets/javascripts/discourse/app/widgets/post-cooked.js

Concerns the quote controls: 
This improves the title so rather than "expand/collapse" for both states it represents the current action "expand" or "collapse". This is also added for aria-label. 
I've also added aria-label to the "go to the quoted post" arrow.

A11Y: add aria-label to quote expansion button, jump to post

---

app/assets/stylesheets/common/base/category-list.scss

These margins are not being applied, and then the top one is applied, it is useless.

UX: Remove category h3 margin

---

.github/workflows/labeler.yml

Seeing the following in https://github.com/discourse/discourse/actions/runs/16209614945/job/45767099809?pr=33577
```
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: HttpError: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
Error: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
```
Related: https://github.com/orgs/community/discussions/156181

DEV: Add extra permission to allow labeller to work in PRs

---

lib/onebox/templates/_layout.mustache
lib/onebox/templates/allowlistedgeneric.mustache
lib/onebox/templates/preview_error_onebox.mustache
lib/onebox/templates/threadsstatus.mustache
lib/onebox/templates/twitterstatus.mustache

Adding `alt=""` to tell screenreaders to skip these, we don't reliably have alt content available for onebox images and they tend to be decorative, so better to omit. 
We already do this in some oneboxes, so this covers some more cases including the generic.

A11Y: onebox avatars/images are decorative, so screenreaders can skip

---

app/assets/javascripts/discourse/app/components/date-input.gjs
app/assets/javascripts/discourse/app/components/search-advanced-options.gjs

The date control here doesn't have a label:
This adds the label, and also removes the headerAriaLabel from the before/after dropdown — the dropdown has a label applied elsewhere so this wasn't doing anything (tested with NVDA)

A11Y: add aria-label to advanced search date input

---

app/assets/stylesheets/common/base/list-controls.scss

Looks like this regressed in 20f57aec12a5d2291c79a447d18eb3f164877c61, this gets it fixed
Before:
After:

UX: make navigation container full-width again

---

app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/my-messages-section-link.js
spec/system/page_objects/components/navigation_menu/sidebar.rb
spec/system/viewing_sidebar_spec.rb

We were not correctly converting the key, it was outputting "my messages" instead of "my_messages".

FIX: correctly allow to translate my messages

---

app/assets/javascripts/discourse/app/components/user-card-contents.gjs
app/assets/javascripts/discourse/app/controllers/user.js
app/assets/javascripts/discourse/app/models/user.js
app/assets/javascripts/discourse/app/templates/user.gjs
app/assets/javascripts/discourse/tests/acceptance/user-card-test.js
app/assets/stylesheets/common/base/user.scss
app/assets/stylesheets/common/components/user-card.scss
app/controllers/users_controller.rb
app/models/user.rb
app/serializers/admin_user_list_serializer.rb
app/serializers/user_card_serializer.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
lib/guardian/user_guardian.rb
plugins/styleguide/assets/javascripts/discourse/components/sections/organisms/user-about.gjs
spec/lib/guardian_spec.rb
spec/models/user_spec.rb
spec/requests/users_controller_spec.rb
spec/system/page_objects/pages/user.rb
spec/system/user_page/staff_info_spec.rb

This commit make it easier for staff to see if a profile is silenced by aligning it with how suspended notices are shown.
- The number of times a profile has been silenced is shown in the staff counters banner at the top of the public user profiles.
- Clicking on the silenced note in the staff counters banner goes to a filtered view of the staff action logs for the user and the silenced action.
- The profile indicates if a user is silenced and shows the date they are silenced until. This looks exactly the same as how it currently displays for suspended users, with the added info of the date. This is also displayed on the user card, the same as suspended notices currently are.

FEATURE: Make it easier for staff to see if a profile is silenced

---

app/controllers/admin/color_schemes_controller.rb
app/controllers/admin/config/customize_controller.rb
app/controllers/admin/themes_controller.rb
app/models/color_scheme.rb
app/models/theme.rb
config/locales/server.en.yml
config/site_settings.yml
db/fixtures/600_themes.rb
db/migrate/20250714030525_remove_experimental_system_themes_site_setting.rb
spec/models/theme_spec.rb
spec/requests/admin/color_schemes_controller_spec.rb
spec/requests/admin/themes_controller_spec.rb
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes_config_area.rb

Reveal Foundation theme and stop creating a Default for new instances. Instead, the Foundation should be set as the default.

DEV: enable Foundation and stop Default

---

app/models/javascript_cache.rb
spec/requests/theme_javascripts_controller_spec.rb

It's possible for different source files to generate the same compiled output (e.g. if only a comment changes), so we should include the sourcemap content when calculating a digest.
Extracted from #33103

DEV: Include sourcemap when generating JavascriptCache digest

---

app/assets/stylesheets/common/base/compose.scss

1. The grippie shouldn't appear in full-screen mode, as reported here: https://meta.discourse.org/t/grip-not-hidden-in-composer-full-screen-mode/373303
2. Composer education popups are tool tall (post the change from c8482635230359c29e8ef7b405943eeed890c9ef): https://meta.discourse.org/t/your-topic-is-similar-to-pop-up-in-full-screen-composer/373304
Before:
After:

UX: minor fullscreen composer adjustments

---

app/assets/javascripts/discourse/app/components/search-menu.gjs
app/assets/javascripts/discourse/app/components/search-menu/results.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/type/topic.gjs
app/assets/javascripts/discourse/app/components/search-menu/results/types.gjs
app/assets/javascripts/discourse/app/components/search-result-entries.gjs
app/assets/javascripts/discourse/app/components/search-result-entry.gjs
app/assets/javascripts/discourse/app/controllers/full-page-search.js
app/assets/javascripts/discourse/app/templates/full-page-search.gjs
app/assets/javascripts/discourse/tests/integration/components/search-menu/results/type/topic-test.gjs
spec/system/search_spec.rb

Context: https://meta.discourse.org/t/missing-pm-icon-in-in-all-searches/365094
This ensures PMs are marked as such with the PM icon in searches where there might be other types of results.

FIX: include icon for private messages in non message filtered searches

---

app/controllers/users_controller.rb
spec/requests/users_controller_spec.rb

This changes allows the `/my/` prefix redirect to work when the name param contains uppercase letters.
`/my/messages/group/MyGroup` now redirects to `/u/username/messages/group/MyGroup`

FIX: my redirect case insensitive params

---

app/assets/javascripts/discourse/app/controllers/topic.js
app/assets/javascripts/discourse/tests/acceptance/composer-test.js
app/assets/javascripts/discourse/tests/acceptance/emoji-test.js
plugins/discourse-presence/test/javascripts/acceptance/discourse-presence-test.js

In the past we have always relied on automatically opening the composer and auto loading the existing draft when visiting a topic that has a draft post reply. This is fine to auto load the draft, but when the composer is closed and reopened on the same page then we have an issue.
The result is that the draft is then deleted because the draft key is set and the composer body is blank, since it has never been populated when clicking the reply to post button.
To solve this we can check for existing drafts when clicking the reply to post button, then load the draft into the composer.
_The challenging part of this change is that we have a number of tests that were relying on a false positive. Hence in the specs I have switched some tests to use a fixture that does not have drafts and in some …

FIX: load saved draft when clicking reply to post

---

config/locales/client.en.yml

When admin'ing an account, we have a very old "private topics" text — this should use the current term, "personal messages" 
Reported: https://meta.discourse.org/t/rename-private-topics-to-personal-message-topics/374264

UX: use correct name for PMs in user admin stats

---

app/models/topic.rb
spec/lib/topic_query_spec.rb

Currently visible on <https://meta.discourse.org/tag/chinese-translation> for `Developers`, we see an N+1 when loading /latest or any other topic lists due to `topic_localizations.find_by` which will hit the db.
This PR switches us to use `find` instead as the associations have been loaded already, and includes a test.

DEV: Prevent N+1s when topic list (e.g. /latest) has localized titles

---

app/assets/javascripts/discourse/app/lib/preload-store.js
app/assets/javascripts/discourse/app/models/login-method.js
app/assets/javascripts/discourse/tests/acceptance/create-account-test.js
app/assets/javascripts/discourse/tests/unit/lib/preload-store-test.js
lib/auth/discourse_id_authenticator.rb
spec/lib/auth/discourse_id_authenticator_spec.rb
spec/system/discourse_id_spec.rb

And forward them in "discourse id" so we can pre-fill the email field on the signup page.
Also added `PreloadStore.has("key")` so we can quickly check a key is present in the "preload store" without actually retrieving it.
Internal ref - t/154880

FEATURE: pass email to external auth on signup

---

lib/site_setting_extension.rb
spec/lib/site_settings/deprecated_settings_spec.rb

Followup 19af83d39e6c06cdc31df2c203623b47bef9c252
There was another edge case here, where this scenario happened:
* A site setting is deprecated _without_ an override
* This site setting is being shadowed by a global setting
* This would cause an argument error when getting the deprecated
setting value in SiteSetting.client_settings_json_uncached
An example of this setting was `external_system_avatars_enabled`.
The shadowed setting was blowing up because it was missing the
`scoped_to` argument that was added for themeable site settings
in the referenced commit.
This commit fixes the issue and adds a spec to cover this scenario,
followup commit will add stronger handling of shadowed global
settings for theme site settings...this is not allowed.

FIX: Error in shadowed global settings for deprecated settings

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
config/locales/client.en.yml
spec/system/ember_deprecation_spec.rb

- Make the message shorter
- Make it clearer that the theme/plugin code needs to be updated
- Add explicit 'learn more', because the linked ID was often missed
Before:
After:

DEV: Improve deprecation warning banner

---

plugins/discourse-assign/assets/javascripts/discourse/components/assign-button.gjs
plugins/discourse-assign/assets/javascripts/discourse/components/topic-level-assign-menu.js
plugins/discourse-assign/assets/javascripts/discourse/initializers/extend-for-assigns.js
plugins/discourse-assign/assets/javascripts/discourse/models/assignment.js
plugins/discourse-assign/assets/javascripts/discourse/models/topic.js
plugins/discourse-assign/assets/javascripts/discourse/services/task-actions.js
plugins/discourse-assign/test/javascripts/acceptance/assign-enabled-test.js
plugins/discourse-assign/test/javascripts/acceptance/edit-assignments-modal-test.js
plugins/discourse-assign/test/javascripts/acceptance/post-popup-menu-test.js
plugins/discourse-assign/test/javascripts/acceptance/topic-level-assign-menu-test.js

Replaced legacy assignment updates with `@tracked` properties for reactive state management in `Discourse Assign` plugin. Updated methods for modifying assignment-related properties (`assigned_to_user`, `assigned_to_group`, etc.) and ensured compatibility with Glimmer's reactive model.
Also, improved test coverage by parameterizing tests to run with `glimmer_post_stream_mode` both enabled and disabled, ensuring consistent behavior across configurations.

DEV: Enhance `discourse-assign` data tracking for components

---

app/assets/javascripts/theme-transpiler/transpiler.js
app/models/javascript_cache.rb
app/models/theme.rb
app/models/theme_field.rb
db/migrate/20250715094001_update_javascript_cache.rb
lib/discourse_js_processor.rb
spec/models/theme_field_spec.rb
spec/requests/admin/themes_controller_spec.rb

Previously, all script tags in a theme field would be combined into a single `.js` bundle along with the `text/discourse-plugin` modules. This led to some unexpected run order, and also makes it hard to implement the `type=module` change being developed in #33103.
This commit refactors things so that each raw script gets extracted into its own `.js` bundle, which is then placed in exactly the same place in the HTML.

DEV: Extract theme script tags into their own JS files

---

app/assets/javascripts/discourse/app/components/signup-cta.gjs
app/assets/javascripts/discourse/app/instance-initializers/signup-cta.js

No behaviour changes, just code refactoring.
The most important change is converting an `<a>` into a `<DButton>` in the signup-cta.gjs component.
I also renamed `neverShown` to `hideForever` to match the other `hideForSession` action.
---
This has been extracted from https://github.com/discourse/discourse/pull/33072

DEV: refactor signup-cta component & initializer

---

app/assets/javascripts/discourse/app/deprecation-workflow.js
config/site_settings.yml

This PR enables the Glimmer Post Stream automatically on compatible sites.
- Set the default value for `glimmer_post_stream_mode` to "auto"
- Unsilences the deprecation message in the console.

DEV: Enable the Glimmer Post Stream automatically

---

app/assets/javascripts/admin/addon/routes/admin-reports-show.js
spec/system/admin_reports_spec.rb

This commit redirects the new site traffic report URL to the legacy one on sites where `use_legacy_pageviews = true`.
- New URL: /admin/reports/site_traffic
- Legacy URL: /admin/reports/consolidated_page_views

FEATURE: Show legacy pageview report for sites using legacy pageviews

---

spec/system/welcome_banner_spec.rb

We needed to ensure `enable_user_locale` was true
otherwise updating the locale would have no effect

DEV: Fix welcome banner locale spec

---

config/locales/server.en.yml
config/site_settings.yml

Add the `composer` word to keywords and description, and
also put the setting in an appropriate area so it shows
up in `/admin/config/content/posts-and-topics`

UX: Make the `rich_editor` setting easier to find

---

plugins/discourse-calendar/app/models/discourse_post_event/event.rb
plugins/discourse-calendar/spec/models/discourse_post_event/event_spec.rb

Currently, there’s an edge case in the calendar plugin: when a recurring event (typically a daily one) ends on the next day, it can happen that we create a `event_date` record with no `starts_at` attribute.
This is because `Event#calculate_next_date` doesn’t check the result from `RRuleGenerator.generate`.
This PR addresses the issue simply by checking the value of `RRuleGenerator.generate` and returns early if the value is `nil`.

FIX: Don’t create empty event dates in calendar

---

app/controllers/application_controller.rb

fixes errors like:
```
Failed to handle exception in exception app middleware : NoMethodError : undefined method `ends_with?' for an instance of Integer
```

FIX: external_id param can be an integer

---

app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs
app/assets/javascripts/admin/addon/templates/plugins-index.gjs
app/assets/stylesheets/admin/admin_table.scss
app/assets/stylesheets/admin/plugins.scss
app/assets/stylesheets/common/base/alert.scss
config/locales/client.en.yml
plugins/checklist/plugin.rb
plugins/discourse-details/plugin.rb
plugins/discourse-lazy-videos/plugin.rb
plugins/discourse-local-dates/plugin.rb
plugins/discourse-narrative-bot/plugin.rb
plugins/discourse-presence/plugin.rb
plugins/poll/plugin.rb
plugins/styleguide/plugin.rb
plugins/styleguide/spec/integration/assets_spec.rb

Instead of listing the redundant commit hash, this now shows "preinstalled" for the relevant components and links to https://meta.discourse.org/t/bundling-more-popular-plugins-with-discourse-core/373574. This is accomplished by checking the URL of the plugin for `"/discourse/discourse/tree/main/plugins/"` which indicates it's part of the core Discourse repo. 
I've also removed the `hide_plugin` flag from existing preinstalled plugins. Now Discourse admins will have more clarity into what's included. 
I also made some minor layout adjustments: 
* Larger click area for "how to install a plugin" banner
* Moved "Learn more" into a separate line for consistent positioning
Before:
After:

UX: show all preinstalled plugins and label them as such

---

app/assets/javascripts/discourse/app/controllers/preferences/tracking.js
app/assets/javascripts/discourse/app/controllers/preferences/users.js

Reported here: https://meta.discourse.org/t/title-of-tracking-and-users-preferences-pages/372965
We were missing subpage titles for these user pref pages 
Before:
After:

UX: add missing subpage title to tracking and users prefs

---

app/models/post.rb
app/serializers/post_serializer.rb
spec/requests/topics_controller_spec.rb

`post_localizations` are preloaded, but using `find_by`, `exists?`, and `count` will hit the db.
Use alternatives instead that can make use of the loaded records.
The two records below in mini profiler shares the caller:

DEV: Prevent N+1 for localizations on topic show

---

app/models/remote_theme.rb
spec/models/remote_theme_spec.rb

This fixes an issue identified in specs where the theme site setting
cache was not being set correctly when importing themes, leading
to an incomplete list of settings being sent down to the client
via the `themeSiteSettingOverrides` preload store.
For example, a theme might have something like this:
```
496=>{:enable_welcome_banner=>false}}
```
Which is missing the `search_experience` theme site setting.
We can address this properly by refreshing the SiteSetting theme
site setting cache after importing themes, ensuring that all
properties are correctly set.

FIX: Make sure theme site setting cache is set on theme import

---

app/assets/stylesheets/common/base/compose.scss

UX: decrease font of discourse tags in composer popup

---

app/assets/stylesheets/common/base/compose.scss
themes/horizon/scss/chat.scss
themes/horizon/scss/composer.scss

* relocated the border-radius to core, so it follows the variable settings always, not just in Horizon
* changed the interaction-layout in Horizon for composer-chat where
* When opened, chat drawer will always be in front of composer, no matter which mode (markdown, RTE, peek)
* When minimised, chat drawer will always be behind the composer
* also changed the color of the chat-drawer when minimised, to stand out a bit more and to match the de-focussed grippie colour on composer.
* slight change in height of composer when minimised (40 -> 45px) to match height of chat drawer when minimised

UX: Horizon composer-chat interaction

---

spec/lib/email/processor_spec.rb

Modifying site settings outside of an example (or `before/after` blocks) results in corrupting those settings in the test database.
(the was issue introduced in e05ef50c709afb9b4777223e22881b695868d4c2)

DEV: Incorrect site setting modifications in specs

---

app/assets/javascripts/admin/addon/models/admin-user.js

When we introduced a dedicated admin page for e-mail logs under a new route, this link remained un-updated.

FIX: Broken admin user profile bounce score link

---

lib/guardian/post_guardian.rb
spec/lib/guardian/post_guardian_spec.rb

In #33587 we moved `PostGuardian` related tests from `guardian_spec` to `post_guardian_spec`. When doing so we also added stubs for missing tests.
This PR implements those missing tests.

DEV: Add test coverage for PostGuardian methods

---

app/assets/javascripts/discourse/app/controllers/user-invited-show.js
app/assets/javascripts/discourse/app/models/invite.js
app/assets/javascripts/discourse/app/templates/user-invited-show.gjs
app/controllers/invites_controller.rb
spec/requests/invites_controller_spec.rb
spec/system/page_objects/pages/user_invited_expired.rb
spec/system/user_page/user_invites_spec.rb

An existing codepath to bulk delete invites exists, but does not show up. This commit fixes it and also fixes the old code's bug.
Specifically,
- `destroy_all_expired` endpoint only acts on the `current_user` which is absolutely counter-intuitive, when a person visits another person’s profile and is able to see the button, clicking it would delete their own invites and not those of the profile they are visiting.
- In `UserInvitedShowController` the removedAll state is never set to the original state, which results in the link being displayed in the list when the new link expires, but the batch deletion cannot be displayed unless the page is refreshed. It is replaced by a toast.

FIX: Show bulk removal of expired invites 

---

plugins/chat/assets/stylesheets/common/core-extensions.scss

follow-up to 2d111e2a9a0a8dcc87691c7a4725597af8bc9a3f, we're showing all plugins now but chat was hidden via CSS

UX: show chat in plugin list

---

app/assets/javascripts/discourse/app/components/post/cooked-html.gjs
app/assets/javascripts/discourse/app/components/post/quoted-content.gjs
app/assets/javascripts/discourse/tests/acceptance/composer-actions-test.js
app/assets/stylesheets/common/base/topic-post.scss

This PR refactors the `PostCookedHtml` and `PostQuotedContent` components to enhance how quoted posts are rendered and decorated. It introduces a new `className` prop for customizing the class of cooked HTML, and ensures collapsed quote content is consistently decorated with appropriate styles and structure.
Key changes:
- Adds a `className` argument to `PostCookedHtml`, allowing quoted content to have a distinct class for easier styling.
- Updates `PostQuotedContent` to render collapsed and expanded quoted content through `PostCookedHtml`, ensuring consistent decoration and disabling selection barriers for quoted posts.
- Refines decorator application logic in `PostCookedHtml` to conditionally apply selection barriers.
- Improves CSS by targeting quoted content within blockquotes, …

DEV: Ensure the collapsed content of quoted posts is decorated

---

app/assets/javascripts/discourse/app/components/reviewable-refresh/flag-reason.gjs
app/assets/javascripts/discourse/app/components/reviewable-refresh/item.gjs
app/assets/javascripts/discourse/tests/integration/components/reviewable-refresh/flag-reason-test.gjs

This is a follow-up to #32506.
In this change:
- Add JSDocs for the component.
- Add integration tests for the component.
- Standardise on passing a single `@score` parameter to the component, rather than splitting out the parameters.
- Read the JSDocs. Do they make sense? Convey the reason for this component as well as its usage?
- Review the tests. Do they cover everything? Do they cover too much?

DEV: Add tests for the ReviewableFlagReason component.

---

plugins/checklist/assets/javascripts/discourse/initializers/checklist.js

Wraps the post widget lookup in `withSilencedDeprecations` to suppress noisy `post-stream-widget-overrides` warnings when the checklist plugin accesses the legacy post stream widget.
The deprecation warning was being triggered when incompatible extensions forced the use of the legacy widget post-stream, even though the code already properly handles the Glimmer Post Stream case. This change maintains the existing functionality while eliminating unnecessary console noise.

DEV: Silence `post-stream-widget-overrides` in the checklist plugin

---

plugins/chat/assets/javascripts/discourse/routes/chat-channels.js
plugins/chat/assets/javascripts/discourse/routes/chat-direct-messages.js

Hotfix to explicitly import `router` service.
This is follow-up change after https://github.com/discourse/discourse/pull/33539.

FIX: adds missing router service import (explicit)

---

plugins/discourse-calendar/app/services/discourse_post_event/chat_channel_sync.rb
plugins/discourse-calendar/spec/services/discourse_post_event/chat_channel_sync_spec.rb

We added few weeks ago the possibility to create a channel with the post event, however if the event name was not set we could create an event with no name. This change ensures we will use the topic title in this case, as we do for the event.
Channel name max length is using the topic title max length so that shouldn't be a problem.

FIX: default channel name to topic title

---

app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/my-messages-section-link.js
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/site_settings.yml
spec/system/viewing_sidebar_spec.rb

Followup 037670fe73cb208e9ed02d401d6e8ba80f0ae73a
This commit adds a experimental_sidebar_messages_count_enabled_groups
site setting feature flag to control the visibility of the messages count/
icon in the sidebar while we work out some kinks with the
functionality. By default this feature is disabled.

FEAUTRE: Hide messages count in sidebar with feature flag

---

plugins/discourse-post-voting/app/models/post_voting_comment.rb
plugins/discourse-post-voting/assets/javascripts/discourse/initializers/post-voting-edits.gjs
plugins/discourse-post-voting/config/locales/server.en.yml
plugins/discourse-post-voting/config/settings.yml
plugins/discourse-post-voting/spec/models/post_voting_comment_spec.rb
plugins/discourse-post-voting/spec/system/page_objects/pages/post_voting_topic.rb
plugins/discourse-post-voting/spec/system/post_voting_spec.rb

This commit introduces a post_voting_comment_enabled site setting to
control whether comments are allowed on posts.

FEATURE: Add site setting to allow comments to be disabled in discourse-post-voting plugin

---

app/assets/javascripts/discourse/app/controllers/login.js
app/controllers/session_controller.rb
spec/requests/session_controller_spec.rb

Looks like this cookie was introduced in c28843e87b about 10 years ago but I couldn't find any reasons why it's any different than the already existing and well-tested destination_url cookie.
This commit replaces the use of the 'sso_destination_url' cookie with the generic 'destination_url' cookie, mainly in order to reduce code complexity.
This was extracted from #33072

DEV: remove sso_destination_url and use destination_url cookie instead

---

plugins/discourse-ai/db/migrate/20241230153301_add_index_to_ai_topics_embeddings.rb

This updates the timestamp of the `AddIndexToAiTopicsEmbeddings`
migration to `20241230153301` so that it runs before all recent
migrations. This is required because the lack of this index is causing
core migrations to fail as queries against the `ai_topics_embeddings`
table are running for too long and causing lock timeouts to happen.
This is a follow-up to cc77e73cfdc381a2cdce18e9e1afa869c16dcd16

DEV: Update migration to add index to run first

---

lib/guardian/invite_guardian.rb

We check for membership in `invite_allowed_groups`, which has `admins` and `moderators` as a mandatory value, so it's redundant to check `is_staff?` as well.
I also unfurled this one long conditional into multiple guard clauses.
The refactoring is covered by existing tests in `invite_guardian_spec.rb`.

DEV: Remove now-redundant is_staff check in can_invite_to_forum

---

Gemfile
Gemfile.lock

Revert hiredis upgrade due to .info failing on some environments

DEV: revert hiredis upgrade

---

app/assets/stylesheets/common/foundation/mixins.scss

Not a perfect fix, but good enough for the very small usecase 
https://meta.discourse.org/t/wrong-text-color-when-hovering-buttons-on-the-404-page/343829

UX: fix hover effect for anon login btns on non-ember page

---

plugins/discourse-ai/lib/embeddings/strategies/truncation.rb

When collecting text for vectorizing a topic, we iterate over as many posts as possible within the context window, parsing their cooked attribute using Nokogiri. We noticed this method doesn't scale well when working with larger contexts.
Instead, we'll collect as much unparsed cooked text as we can, then parse it all in a single Nokogiri call.
I ran this a hundred times in a benchmark, and the perf gains are significant:
```
user     system total        real
prepare_target_text:           114.887620   3.731693 118.619313 (118.952465)
prepare_target_text_bis:        10.264950   0.186204  10.451154 ( 10.465957)
```
Tried running it 1k times, but the old method took too long.

PERF: Speed up embedding text preparation.

---

themes/horizon/scss/desktop-horizon-fixes.scss

This regressed at some point on its way into core. The controls were no longer sticky and unreachable on scroll. This makes them sticky again. 
Before:
After:

UX: fix bulk select in Horizon theme

---

lib/guardian.rb
spec/lib/guardian_spec.rb

The `personal_message_enabled_groups` setting now has `admins` and `moderators` as mandatory values, so we don't need to check for `is_staff?` as well.
Also removes a duplicated test case.

DEV: Remove now-redundant is_staff check

---

config/locales/client.en.yml

Admins resetting the theme site setting values are
resetting to the site setting default, not whatever
the theme had in about.json, because we do not store
this latter value in the database.

UX: Fix copy for theme site setting description

---

config/site_settings.yml

In all group based access site settings we use `admins` and `moderators` explicitly, except these two. This PR updates them to match the rest.

DEV: Replace staff auto-group in settings

---

app/models/post.rb
lib/post_destroyer.rb
spec/lib/post_destroyer_spec.rb

Necro-posting by spammers will bump the topic, and once you delete them, those topics will still sit in `/latest` without any benifit.
This commit implements automatic resetting of topic bump date when a post is deleted, so the topic will go to the correct place it belongs on `/latest` based on its last public post.

FEATURE: Reset bump date when deleting a post 

---

app/assets/javascripts/discourse/app/components/d-editor.gjs
app/assets/stylesheets/common/base/compose.scss
app/assets/stylesheets/common/d-editor.scss

To prevent the toolbar to wrap onto 2 lines and eat into the precious writing space on mobile, this commit aims to allow horizontal scrolling.
This is a very basic implementation; I'd like to follow-up later with fade-out and arrow-scrolling

UX: allow horizontal scrolling for the editor toolbar on mobile

---

plugins/discourse-assign/spec/system/assign_topic_spec.rb

fixes warnings, and now the spec does what it says it does

DEV: Fix a d-assign spec

---

themes/horizon/scss/desktop-horizon-fixes.scss

For some reason `display: block;` here was causing Safari to not always stick the bulk controls in the Horizon theme on scroll. Fortunately we don't need it and removing it seems to fix the issue. Follow-up to https://github.com/discourse/discourse/commit/4987ae6c495fd43b9015b23ddb5e05c6bafc13aa

FIX: Horizon bulk select sometimes not sticky in Safari

---

app/assets/javascripts/admin/addon/components/admin-filter-controls.gjs
app/assets/javascripts/admin/addon/components/admin-reports.gjs
app/assets/javascripts/admin/addon/controllers/admin-plugins-index.js
app/assets/javascripts/admin/addon/templates/plugins-index.gjs
app/assets/javascripts/discourse/tests/acceptance/admin-sidebar-section-test.js
app/assets/javascripts/discourse/tests/acceptance/dashboard-test.js
app/assets/stylesheets/admin/admin_base.scss
app/assets/stylesheets/admin/admin_filter_controls.scss
app/assets/stylesheets/admin/plugins.scss
config/locales/client.en.yml
spec/system/admin_filter_controls_spec.rb
spec/system/page_objects/components/admin_filter_controls.rb

This creates a reusable filter component for admin areas that includes a text filter and dropdown. 
The component accepts an array to filter, an array of searchable property names, and optional dropdown values. An additional option is available if you'd like the default dropdown value to be something other than "all." 
It looks like this: 
The dropdown is optional, without it: 
When there are no matching filters, it provides a reset button: 
I'll use this to replace occurrences of similar filters, we've added a couple to the AI plugin.

FEATURE: Add reusable AdminFilterControls component, apply to plugins and reports

---

app/assets/javascripts/admin/addon/components/modal/penalize-user.gjs
app/services/user/action/trigger_post_action.rb
app/services/user/silence.rb
app/services/user/suspend.rb
spec/services/user/action/trigger_post_action_spec.rb
spec/services/user/silence_spec.rb
spec/services/user/suspend_spec.rb
spec/system/admin_user_spec.rb
spec/system/page_objects/modals/penalize_user.rb

When the user was silenced or suspended by accepting a flag, and the action on the post was `Do Nothing`, it was throwing a silent error.
That was fixed, but in addition, ensured that errors are always displayed on the modal to inform the user that something went wrong.

FIX: bug when silence user and do nothing to post

---

app/assets/javascripts/admin/addon/models/admin-user.js
app/assets/javascripts/discourse/tests/acceptance/flag-post-test.js
spec/system/admin_user_spec.rb
spec/system/page_objects/modals/penalize_user.rb
spec/system/page_objects/pages/admin_user.rb

In this PR `silenced` became a computed property - https://github.com/discourse/discourse/pull/33537
When we silence the user, one of the serialised attributes is `silenced`. When we tried to assign it with `setProperties`, Ember was throwing an error. This was fixed by explicitly defining the arguments.
https://github.com/user-attachments/assets/e8126484-2980-4fd8-90a7-35594076e9d8

FIX: JS error when silencing and unsilencing the user

---

.github/dependabot.yml

The hope is that this will allow dependabot to handle lint-config bump.

DEV: Group lint deps in dependabot

---

app/assets/javascripts/discourse/app/components/create-topic-button.gjs
app/assets/javascripts/discourse/app/components/d-navigation.gjs
app/assets/javascripts/discourse/tests/acceptance/category-banner-test.js
app/assets/javascripts/discourse/tests/acceptance/tags-test.js
spec/system/composer/default_to_subcategory_spec.rb
spec/system/drafts_dropdown_spec.rb
themes/horizon/javascripts/discourse/components/sidebar-new-topic-button.gjs

When visiting a restricted category or tag where the current user does not have permission to create a topic, we should still allow the user to write a new topic under a different category or tag. This is especially important when using the **new topic** button from the sidebar.
When clicking the **new topic** button when the user does not have permission, the composer category defaults to:
1) Subcategory (if `SiteSetting.default_subcategory_on_read_only_category` is `true` and subcategory exists)
2) Default site category (if `SiteSetting.default_composer_category` has a category id value)
3) Default category chooser value of `Category...` prompting the user to select a category from the dropdown
Internal ref: /t/-/152613

FEATURE: create new topic while viewing restricted category or tag

---

plugins/discourse-topic-voting/assets/javascripts/discourse/components/vote-box.gjs
plugins/discourse-topic-voting/spec/system/page_objects/pages/topic.rb
plugins/discourse-topic-voting/spec/system/voting_spec.rb

This corrects a slight logic bug that was preventing the alert when the number of remaining votes was zero.

FIX: display alert when casting last remaining vote

---

Gemfile
Gemfile.lock

Upgrading Rack to version 3 will break Unicorn. When we don’t use Unicorn anymore, we’ll be able to upgrade to Rack 3.

DEV: Pin Rack to < 3

---

config/locales/client.en.yml

UX: Mention browser console in theme error banner

---

app/assets/javascripts/admin/addon/controllers/admin-customize-colors.js
app/assets/javascripts/admin/addon/lib/color-scheme-manager.js
app/assets/javascripts/admin/addon/templates/customize-colors.gjs
config/locales/client.en.yml

Follow-up to 8fea4eaaa5aa6c473dfed800b6c51c752ee68120
This fixes an issue where if a live preview wasn't being shown (due to preferences), the color palette wasn't being changed in the theme settings. It's now being applied correctly.
I've also simplified the color-scheme-manager so the logic for handling the default fallback palette is handled in the controller (and determines preview mode in the manager)
This also adds a warning for another case where live previewing isn't available: when the admin is in dark mode. 
This will hopefully be temporary while we simplify how dark mode works.

FIX: apply color palette change when preview is unavailable, warn for dark mode

---

lib/svg_sprite.rb

This icon is used in the rich editor. Normally it works fine because it's the default icon for the "Editor" badge. But if that icon was changed, or the badge was disabled, then the icon was unavailable.

FIX: Add `pen` icon to core icons list

---

app/assets/stylesheets/common/base/topic-footer.scss

Follow-up to e61f2e1b89a6bf02c7b555d5f3cdb88ff9d9f3c0, unintentionally added `flex-grow: 1` when using the shorthand, should only apply `flex-shrink: 0`
Before:
After:

FIX: don't grow topic footer button

---

spec/services/video_conversion/aws_media_convert_adapter_spec.rb

Looks like we need to use the TEST_ENV_NUMBER in the spec which appears to be a
common pattern in other specs.

DEV: Fix flakey spec with media convert

---

app/assets/javascripts/discourse/app/components/post-stream.gjs

Added a new `PluginOutlet` at the bottom of the `post-stream` to enable plugins to expand functionality.

DEV: Add `post-stream-bottom` plugin outlet to support extensions

---

lib/version.rb

Version bumps for main: v3.5.0.beta8, v3.5.0.beta9-dev

---

app/assets/javascripts/discourse/app/services/site-settings.js

Logging these on every page load is quite noisy. Best to keep the console as clear as possible, so that important messages are easier to identify.

DEV: Remove logging for themable site settings

---

app/models/post.rb
spec/models/post_spec.rb

This is a continuation of #33747, implements automatic resetting of topic bump date when a last reply is hidden, so the topic will go to the correct place  it belongs on /latest based on its last public post.

FEATURE: Reset bump date when hiding a post

---

config/site_settings.yml
lib/guardian/post_guardian.rb
lib/guardian/topic_guardian.rb
spec/lib/topic_view_spec.rb

Instead of doing both an `is_staff?` and a group access check, just add `admins` and `moderators` as mandatory values to the group access setting.

DEV: Remove now-redundant is_staff? guardian check

---

app/assets/javascripts/admin/addon/components/admin-plugins-list-item.gjs
app/assets/javascripts/admin/addon/templates/plugins-index.gjs
app/assets/stylesheets/admin/plugins.scss

The link we were using only applied to newly moved plugins, so wasn't the best fit for all of them. This unlinks it. 
I've also removed the plugin install banner and inlined it in the page description. The blue banner was kind of intense for a message that's always visible on the page. We need to retain the class there so it can be hidden for sites on our hosting. 
Before:
After:

UX: on plugin index, unlink preinstall, simplify install banner

---

app/assets/stylesheets/common/base/user-badges.scss
app/assets/stylesheets/common/base/user.scss
app/assets/stylesheets/common/components/user-stream-item.scss

Adds a few more uses of `--content-border-color` that were missed in https://github.com/discourse/discourse/commit/49a16671559656f93b7e117c692e6b60845b1ee4

UX: Content border variables 2

---

themes/horizon/scss/chat.scss

Because Horizon has a different drawer-composer interaction as default (#33677) this means that certain floating elements such as the `fk-d-menu[data-identifier="usercard"]` and the `chat-message-actions-container` need an adjusted z-index to remain visible.
Scoped to chat-drawer for safety.

UX: Horizon > chat-drawer z-index adjustments for popup content

---

config/locales/client.en.yml

Slightly longer, but clearer if you're new and don't know what the default theme's name is yet
Before:
After:

UX: clarify color palette activation button

---

app/assets/javascripts/admin/addon/models/report.js

When the y-axis value is 0 and the column type is percent, display 0% instead of replacing it with an em dash. Only show an em dash when the value is null or undefined.

UX: show 0% instead of em dash in percent-type report columns

---

app/assets/stylesheets/common/base/header.scss

We do not use border color to signify active state any longer. These styles are not necessary.

DEV: remove transparent pixels

---

app/assets/stylesheets/common/base/menu-panel.scss

A followup to #33795
1. the hover effect was broken in Safari (because it was trying to emulate a background by setting a box-shadow of a small child element)
2. in <= 400px height viewports elements were overlapping eachother and icons moved on hover
3. changing `--user-menu-border-width` had issues: at 0px and at >= 3px icons would move on hover, and increasing the value would make tabs overlap with the border

UX: Fix tabs in new notification panel

---

app/assets/javascripts/discourse/app/components/modal/upsert-hyperlink.gjs
spec/system/composer/prosemirror_editor_spec.rb
spec/system/page_objects/modals/upsert_hyperlink.rb

Using ENTER on the composer link modal was having unwanted consequences because of a misplaced preventDefault.

FIX: composer link modal ENTER event

---

app/models/post.rb
app/models/topic.rb
spec/models/post_spec.rb

This is a continuation of #33895, implements automatic resetting of topic bump date when a last reply is unhidden, so the topic will back to the correct place it belongs on /latest based on its last public post.

FEATURE: Reset bump date when unhiding a post

---

plugins/chat/spec/system/shortcuts/full_page_spec.rb

Ref: t/159511
There's a race condition in this test that could cause the composer value to not have been updated before the test tries to read the value.
The composer page object makes use of the `has_field?()` test, which will wait until the value has been updated properly.

DEV: Fix a flaky chat shortcut test

---

plugins/discourse-ai/lib/translation/base_candidates.rb
plugins/discourse-ai/lib/translation/category_candidates.rb
plugins/discourse-ai/lib/translation/post_candidates.rb
plugins/discourse-ai/lib/translation/topic_candidates.rb
plugins/discourse-ai/spec/lib/translation/category_candidates_spec.rb
plugins/discourse-ai/spec/lib/translation/post_candidates_spec.rb
plugins/discourse-ai/spec/lib/translation/topic_candidates_spec.rb

This PR fixes 2 things. 
1. If a `post` was written in `ja` (Japanese) and for some reason also had a `post_localization` that is `ja`, it becomes 200%
2. When getting completion progress for "English (US)", if there exists a "English (UK)" localization, we want to include that
3. Previously the completion count was also getting `post_localization` from posts that are not candidates. If the user switches `ai_translation_backfill_limit_to_public_content` from false to true, it would include previously localized PMs when it should not.
Follow up: https://github.com/discourse/discourse/pull/33927

FIX: Completion rate double-count and normalize

---

app/assets/stylesheets/common/base/onebox.scss

UX: Fix github repo oneboxes in chat (drawer)

---

app/assets/javascripts/discourse/app/services/element-classes.js
app/assets/javascripts/discourse/tests/integration/helpers/element-class-test.gjs
plugins/chat/assets/javascripts/discourse/components/chat-drawer.gjs
plugins/chat/assets/javascripts/discourse/routes/chat.js
plugins/chat/assets/javascripts/discourse/templates/chat.gjs
plugins/chat/spec/system/drawer_spec.rb

Also remove the `scrollTop()`, which is now handled by `services/route-scroll-manager`

DEV: Tidy html/body classes in chat

---

app/controllers/users_controller.rb
spec/requests/users_controller_spec.rb

If an anon Japanese user views Jane's summary page, then subsequently an anon German user views Jane's summary page, the German user will see topic titles in Japanese.
This PR prevents cache poisoning on the user summary page when content localization is enabled.

FIX: Extend cache key due to user locale

---

themes/horizon/scss/topic-cards.scss

The topic-cards on the messages page are laid out differently than on the main topiclist page and lack spacing. This causes the box-shadow on selected-highlight to be cutoff:
This commit uses an inset box-shadow to avoid that, on this page specifically:

UX: Horizon > messages page – change box-shadow to inset

---

app/assets/javascripts/discourse/app/services/element-classes.js

`Iterator.filter` only exists on Safari 18+. Need to convert to an array first

FIX: element-classes implementation on older browsers

---

plugins/discourse-ai/lib/embeddings/strategies/truncation.rb
plugins/discourse-ai/spec/lib/modules/embeddings/strategies/truncation_spec.rb

On a27e20c we made an emergency perf fix to speedup generating text from
a topic for embeddings generation.
This introduced some issues, like missing separators between posts,
including to line breaks per included post all at the top of the
generated text, and resulted in using a lot less content per topics,
as we count the cooked size before stripping all the HTML tags.
This commit helps alleviate by:
- removing the "\n\n" * quantity of posts at the top
- adding a space between posts
- generating text 3 times longer than the max allowed lenght, since
it's getting shrinked after it's built by the Nokogiri.text call.

FIX: Optimize shortcomings from topic truncation from a27e20c

---

app/assets/javascripts/discourse/app/components/card-contents-base.js
spec/system/page_objects/components/post.rb
spec/system/page_objects/components/user_card.rb
spec/system/user_card_spec.rb

Currently, clicking on a mention of user who has set a custom status causes the user card to fail to load. This happens because when the username is extracted from the mention `<a>` element, the space between the username and the status emoji is captured with the username and is sent to the server which fails to lookup the user due to the erroneously appended space.
To fix this, we should cleanup the captured username and remove surrounding spaces using `trim()`.

FIX: Mention with a status should open the user card

---

plugins/discourse-calendar/assets/javascripts/discourse/components/csv-uploader.gjs

CSV bulk invites need to be uploaded direct to the controller, otherwise
uploadUrl is not respected and upload never heads to the correct place

FIX: CSV bulk invites broken when S3 uploads enabled

---

config/site_settings.yml
lib/guardian/post_guardian.rb
plugins/discourse-calendar/spec/requests/events_controller_spec.rb
plugins/discourse-presence/plugin.rb
plugins/discourse-presence/spec/integration/presence_spec.rb

The `edit_all_post_groups` used to have TL4 as the default setting. This update:
1. Adds in `admins` and `moderators` as well as makes those mandatory values.
2. Gets rid of now-redundant `is_staff?` check.
3. Makes use of the magic `#edit_all_post_groups_map` method.
Test coverage is here:
- https://github.com/discourse/discourse/blob/main/spec/lib/guardian/post_guardian_spec.rb#L507-L544
- https://github.com/discourse/discourse/blob/main/spec/lib/guardian/post_guardian_spec.rb#L624-L642

DEV: Remove now-redundant is_staff guardian check

---

lib/guardian/topic_guardian.rb
spec/lib/guardian/topic_guardian_spec.rb
spec/lib/guardian_spec.rb

In a previous PR I had to work with `TopicGuardian#can_delete_topic?` and I had to whip out pen and paper to untangle the single conditional that governs it. Now that that task is done, I'm going back to it to clear it up.
Commit by commit:
1. Move the tests to `topic_guardian_spec.rb`.
2. Add missing test cases for trashed- and category topics.
3. Break the conditional into individual code paths using guard clauses.

DEV: Fix up TopicGuardian#can_delete_topic?

---

spec/lib/site_settings/deprecated_settings_spec.rb

See: t/158747
Some of the deprecated settings tests set our site settings to be global settings. When the settings are reloaded between tests (see `stub_deprecated_settings!()`), the setting loader (`SiteSettingExtension.setting()`) will check to see if there's a global setting that would override the site setting, and use that value from previous tests.
To fix this, we need to un-global the site setting after the test finishes.
`bin/rspec --order random:37535 spec/lib/site_settings/deprecated_settings_spec.rb`

DEV: Fix a flaky deprecated settings test

---

plugins/discourse-ai/spec/system/ai_helper/ai_composer_helper_spec.rb

There was a race condition in this test, where the mini tag chooser may not have had time to update after a tag was selected.
`bin/rspec --order random:49018 plugins/discourse-ai/spec/system/ai_helper/ai_composer_helper_spec.rb`

DEV: Fix a flaky AI composer helper test

---

app/assets/javascripts/discourse/app/components/composer/toolbar-buttons.gjs
app/assets/javascripts/discourse/app/components/toolbar-popup-menu-options.gjs
app/assets/javascripts/discourse/app/lib/composer/toolbar.js
config/locales/client.cs.yml
config/locales/client.de.yml
config/locales/client.en.yml
config/locales/client.he.yml
config/locales/client.pl_PL.yml
config/locales/client.ro.yml
config/locales/client.sk.yml
config/locales/client.uk.yml
config/locales/client.ur.yml
config/locales/client.zh_CN.yml

Adds a `title` attribute to the composer toolbar items that are used to trigger a dropdown menu.

A11Y: composer toolbar dropdown title

---

config/initializers/100-sidekiq.rb

By default, Sidekiq logs the `start` and `done` messages at the `info` log level
when a sidekiq job executes. These log messages are not necessary in
production and is bloating our log files. Even in other environments, I
don't see how the messages are useful so we are going to just disable
this.
See https://github.com/sidekiq/sidekiq/pull/6200

DEV: Configure `skip_default_job_logging` for Sidekiq

---

app/assets/javascripts/admin/addon/templates/email-logs-bounced.gjs
app/assets/javascripts/admin/addon/templates/email-logs-received.gjs
app/assets/javascripts/admin/addon/templates/email-logs-rejected.gjs
app/assets/javascripts/admin/addon/templates/email-logs-sent.gjs
app/assets/javascripts/admin/addon/templates/email-logs-skipped.gjs
app/assets/javascripts/discourse/app/components/horizontal-scroll-sync-wrapper.gjs
app/assets/javascripts/discourse/app/components/responsive-table.gjs
app/assets/stylesheets/admin/emails.scss
app/assets/stylesheets/common/base/directory.scss

This improves the admin email log overflow by: 
* allowing tables to horizontally scroll if needed
* ensuring `code` has pre-wrap to avoid very long lines
* making all links have overflow-wrap to avoid very long email address and link issues 
I've also removed some truncation CSS, because this is data we ideally need to see all of, even if it has to wrap. 
The horizontal scrolling is implemented by horizontal-scroll-sync-wrapper.gjs, this is a new component I pulled out of the existing responsive-table.gjs and updated. The component adds a top scrollbar to horiztonally overflowing areas and syncs it up with the bottom scrollbar to make scrolling a little easier. 
These templates are quite old and can use some more general improvements, but this gets them to a place where they aren't …

UX: better handling of admin email log overflow

---

spec/rails_helper.rb

In our serializers, we have a method `cache_fragment` that we use for caching chunks of JSON that are expensive to generate. We currently don't clear this cache between tests, which causes tests to become flaky since a cached fragment from one test can leak to another test and make it fail.

DEV: Clear serializers cache between tests

---

app/assets/stylesheets/common/base/directory.scss

Follow-up to 459a58f
Had an extra overflow style causing an issue with dropdowns, it's unnecessary because we have overflow handled on a descendant 
Before:
After:

FIX: remove unneeded overflow in horizontal-scroll-sync

---

script/bulk_import/base.rb

This change ensures the incoming category slug doesn't already exist

FIX: Ensure imported category slug is deduplicate

---

app/assets/javascripts/discourse/app/components/d-navigation.gjs
app/assets/javascripts/discourse/app/components/tag-info.gjs
app/assets/javascripts/discourse/app/models/user.js
app/assets/javascripts/discourse/tests/acceptance/tags-test.js
app/controllers/tags_controller.rb
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/site_settings.yml
lib/guardian/tag_guardian.rb
spec/lib/guardian/tag_guardian_spec.rb
spec/requests/tags_controller_spec.rb
spec/system/page_objects/pages/tag.rb
spec/system/tag_edit_spec.rb

Break down tag admin into more fine grained permissions using a new setting listing groups that can edit (but not create or delete) tags.
**Admin:**
**User in access group:**
**Regular user:**

FEATURE: Add new edit_tags_allowed_groups setting

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/quote.js
spec/system/composer/prosemirror_editor_spec.rb

Adds a `transformPasted` phase that enforces a trailing paragraph if (at the end of a text block AND single child AND child is a `[quote]`) so the cursor can be outside the pasted quote.
internal /t/149983

UX: add trailing paragraph when pasting a [quote] at the end of a text block

---

plugins/discourse-calendar/app/models/discourse_post_event/event.rb
plugins/discourse-calendar/assets/javascripts/discourse/initializers/discourse-calendar.js
plugins/discourse-calendar/config/locales/client.en.yml
plugins/discourse-calendar/test/javascripts/acceptance/notifications-test.js

When users were sent a notification when they were signed up to
an event with predefined attendance, the translation key was misssing,
since we originally needed to append `_html` to the key, but don't
anymore.
Handled this broken translation and used the eventName instead
of description in the notification, since the latter is not always
set and was not passed to I18n anyway.

FIX: Event notification translation for predefined attendance

---

app/assets/javascripts/discourse/app/static/prosemirror/components/prosemirror-editor.gjs
app/assets/javascripts/discourse/app/static/prosemirror/lib/text-manipulation.js

Our ProseMirror text-manipulation impl's `putCursorAtEnd` was not putting the cursor at the end of the document.
This change is important in particular for Quoting directly from a post selection, which was opening the composer but the cursor was not being correctly placed.

UX: [rte] properly put cursor at end when putCursorAtEnd is called

---

spec/system/composer/prosemirror_editor_spec.rb

See #33381, #34035
There appears to be a race condition where the editor tests are pasting an image, but then not ensuring that the image has been added to the DOM before trying to click on it.
Switching from using `sleep` to `expect` tells Capybara to wait until the appropriate DOM element exists.

DEV: Fix a handful of flaky Prosemirror editor tests

---

app/assets/javascripts/select-kit/addon/components/tags-intersection-chooser.js

When on a tag intersection like this: `/tags/intersection/foo/bar`
We have our tag selector:
When you remove all but one tag, we redirect to /tags, which isn't the best experience. This change will direct users to the single tag page `/tag/foo` instead.

UX: direct to single tag page from tag intersection when one tag remains

---

app/assets/stylesheets/common/base/topic-post.scss

Fix for meta report
https://meta.discourse.org/t/a-table-renders-outside-the-boundaries-of-the-post-comment/375689
Broken overflow gets replaced by horizontal scrolling within the table cells. Not ideal either, but better than before and not much alternatives afaik.
| Normal (before) | With fixed layout (after) |
| <img width="754" height="769" alt="CleanShot 2025-08-04 at 11 49 29" src="https://github.com/user-attachments/assets/68d040d6-2e0c-45a8-90da-0879d142f1ba" /> | <img width="789" height="751" alt="CleanShot 2025-08-04 at 11 56 09" src="https://github.com/user-attachments/assets/d1e2439b-0a5c-46ce-a282-e205e687f5a1" /> |

UX: make tables in blockquotes fixed to prevent overflow

---

plugins/discourse-ai/assets/javascripts/discourse/lib/ai-streamer/progress-handlers.js
plugins/discourse-ai/assets/javascripts/discourse/lib/ai-streamer/updaters/post-updater.js

In the glimmer post stream, mutating `post.cooked` will cause ember to re-render the HTML. That conflicts with d-ai's own morphlex-based diff streaming.
To avoid this, we can wait until all streaming has finished before setting the cooked property of the model.
Co-authored-by: Sérgio Saquetim <saquetim@discourse.org>

UX: Make AI streaming more efficient under glimmer post stream

---

app/assets/javascripts/discourse/app/components/post.gjs

- Add `prevPost` and `nextPost` to post outlet params
- Add `prevPost` to  `post-article-class` transformer
- Introduce `in-post-article` plugin outlet for adding extension points to the post within the `article` itself
- Introduce `post-links` plugin outlet that wraps `PostLinks` component (I chose to wrap here vs within the component to ensure that we render the outlet even if there is not post links)

DEV: Add and update `post` plugin outlets

---

lib/category_badge.rb
spec/requests/application_controller_spec.rb

Looks like the new styles weren't implemented here, this does it
Before:
After:

UX: fix category badges on 404 page and oneboxes

---

app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/discourse/tests/integration/helpers/category-link-test.gjs

The category-link helper isn't working in some cases, like the user summary: 
Before:
After:
It looks like we were using `category.styleType` instead of `category.style_type` — I've also added a fallback (to square) if for some reason `style_type` isn't defined and added some tests

FIX: update fallback style for category-link helper

---

app/assets/javascripts/admin/addon/models/user-field.js
app/assets/javascripts/discourse/app/components/user-field.gjs
app/assets/javascripts/discourse/app/components/user-fields/textarea.gjs
app/assets/stylesheets/common/base/login-signup-page.scss
app/assets/stylesheets/common/base/user.scss
app/models/user_field.rb
config/locales/client.en.yml
spec/requests/admin/user_fields_controller_spec.rb

Meta feature request https://meta.discourse.org/t/is-it-possible-to-have-a-multi-line-longer-text-field-in-the-signup-form/257642/7
This commit adds the option to use a textarea as a custom field:

DEV: add text area option to custom user fields

---

app/assets/javascripts/discourse/app/components/post/meta-data/edits-indicator.gjs
app/assets/javascripts/discourse/app/lib/transformer/registry.js
app/assets/javascripts/discourse/tests/integration/components/post/meta-data/edits-indicator-test.gjs

Introduced the `post-meta-data-edits-indicator-label` transformer to enable customization of post edits indicator labels. Added integration tests to validate customization and default behavior.

DEV: Add value transformer for post edits indicator labels

---

app/assets/javascripts/discourse/app/modifiers/d-autocomplete.js
config/locales/server.en.yml
config/site_settings.yml
plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs
plugins/chat/spec/system/chat_composer_spec.rb
plugins/chat/spec/system/hashtag_autocomplete_spec.rb

This PR ports the floatkit-based autocomplete system to chat composer under a site setting, providing consistent UX across both regular and chat composers.
* Adds floatkit_autocomplete_chat_composer setting (defaults to true)
* Adds `fixedTextareaPosition` option and `createVirtualElementAtTextarea` to DAutocompleteModifier to allow for positioning of the autocomplete menu relative to the whole textarea bounds instead of following the cursor - this is better for chat UI & aligns with current behaviour

DEV: use floatkit autocomplete for chat composer

---

app/assets/javascripts/discourse/app/lib/user-menu/bookmark-item.js
app/assets/javascripts/discourse/tests/acceptance/user-menu-test.js
app/assets/javascripts/discourse/tests/integration/components/user-menu/menu-item-test.gjs
app/models/topic.rb
app/serializers/basic_topic_serializer.rb
app/serializers/concerns/localized_fancy_topic_title_mixin.rb
app/serializers/notification_serializer.rb
app/serializers/topic_view_serializer.rb
app/serializers/user_post_topic_bookmark_base_serializer.rb
spec/models/topic_spec.rb
spec/requests/notifications_controller_spec.rb
spec/requests/users_controller_spec.rb

Localizes topic titles in these areas
- user notification
- bookmarks
This PR also updates the user notification bookmark list to use fancy title instead of title, similar to the other user notification tabs.

FEATURE: Localize topic titles in notifications and bookmarks

---

app/assets/stylesheets/common/base/discourse.scss
plugins/discourse-solved/assets/stylesheets/solutions.scss

For increased clarity when scanning the topic list
| <img width="678" height="243" alt="CleanShot 2025-08-05 at 09 57 01" src="https://github.com/user-attachments/assets/72e25e99-40a2-4b3b-94c8-6cdedb006fef" /> | <img width="678" height="243" alt="CleanShot 2025-08-05 at 09 56 41" src="https://github.com/user-attachments/assets/b31c1b87-8620-4db2-9c4e-b1f1be038f73" /> |

UX: use success colour for solved icon in topic list

---

app/assets/javascripts/discourse/app/components/categories-boxes.gjs
app/assets/stylesheets/common/base/category-list.scss

This PR adjusts the way we render subcategory image logos. It will only render its container if present. Right now, the container is rendered regardless and causes spacing issues.
|Before|After|
|-- | --|
|<img width="1950" height="1352" alt="CleanShot 2025-08-04 at 18 30 37@2x" src="https://github.com/user-attachments/assets/3d976a75-f12f-4dbb-9168-b18f016868ce" />|<img width="1940" height="1352" alt="CleanShot 2025-08-04 at 18 29 59@2x" src="https://github.com/user-attachments/assets/23c1b943-4a97-40f2-99be-b67d958b6267" />|

UX: subcategory image tweaks

---

themes/horizon/scss/categories-view.scss
themes/horizon/scss/sidebar.scss

This PR adjusts the sidebar border color due to recent changes to some variables in core.
|before|after|
|-- | --|
|<img width="552" height="706" alt="CleanShot 2025-08-05 at 08 53 43@2x" src="https://github.com/user-attachments/assets/0d87977d-3c8d-4f20-88de-9715825a4f1e" />|<img width="536" height="1322" alt="CleanShot 2025-08-05 at 08 50 12@2x" src="https://github.com/user-attachments/assets/db9d9004-b9cd-44ab-9203-3ab867f2bc0b" />|

UX: Sidebar changes & css cleanup

---

app/assets/stylesheets/admin/admin_base.scss

Meta request.
Makes sense to expose the buttons on touch-devices, otherwise it gets very tricky to use.
| <img width="1126" height="798" alt="CleanShot 2025-08-05 at 18 56 24@2x" src="https://github.com/user-attachments/assets/f81f9213-1e5a-4b6e-bb85-0922faa1016f" /> | <img width="1126" height="798" alt="CleanShot 2025-08-05 at 18 55 55@2x" src="https://github.com/user-attachments/assets/da167903-dbc6-41ea-8d56-208949d9227c" /> |

UX: expose shift buttons for lists on touch-devices

---

themes/horizon/scss/topic.scss

Follow-up to https://github.com/discourse/discourse/commit/7404e3f526fee93471a39a7f62cbb87bc76214ab, The new `grid-template-columns: auto 8em;` style is too specific and was overriding this on mobile, moving the query fixes it
Before: 
After:

UX: Horizon theme, fix d-toc class on smaller screens

---

plugins/discourse-ai/spec/lib/completions/cancel_manager_spec.rb

Note, if this does now work we may have to simply skip in CI
Concurrent tests depend on timing of background threads and if scheduler is overwhelmed stuff can take inconsistent amounts of time.

DEV: attempt to de-flake concurrent spec

---

app/assets/javascripts/discourse/app/components/discovery/filter-navigation-menu.gjs
app/assets/javascripts/discourse/tests/integration/components/discovery/filter-navigation-menu-test.gjs
app/assets/stylesheets/common/components/filter-navigation.scss

This PR:
- removes DButton from being needed in the filter-tip list
- simplifies some of the CSS as well.
- normalized the font sizes in the tip list
|before|after|
|--|--|
|<img width="1956" height="796" alt="CleanShot 2025-08-05 at 09 17 51@2x" src="https://github.com/user-attachments/assets/c4fca721-3c23-4535-93e2-9da5cf80b763" />|<img width="1976" height="924" alt="CleanShot 2025-08-05 at 09 17 17@2x" src="https://github.com/user-attachments/assets/03dcf528-bd75-42b4-a651-b5fa122eff43" />|

DEV: Markup refactor

---

spec/system/admin_customize_themes_spec.rb

Previously: #33997
See t/157993
The `hides unecessary sections and buttons for system themes` spec is still be flaky after the previous fix. It seems like the `system?` method was not being properly stubbed on the theme object we have in the spec, so now it stubs all Theme objects, so that the corresponding theme object created in the Playwright thread will also be stubbed.
I've also tweaked the `cannot edit js, upload files or delete system themes`, the test was wrong, I suspect it was only passing when the checks managed to all run before the page loaded.

DEV: Clean up a couple of flaky theme customization specs.

---

app/views/exceptions/_not_found_topics.html.erb

We were transforming emoji codes for 'popular' topics, but not 'recent' topics

UX: Render emojis consistently on 404 page

---

app/assets/javascripts/discourse/app/controllers/preferences/interface.js
app/assets/javascripts/discourse/app/initializers/discourse-bootstrap.js
app/assets/javascripts/discourse/app/lib/color-scheme-picker.js
app/assets/javascripts/discourse/app/templates/preferences/interface.gjs
app/assets/javascripts/discourse/tests/acceptance/user-preferences-interface-test.js
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb
spec/system/interface_color_selector_spec.rb
spec/system/page_objects/pages/user_preferences_interface.rb
spec/system/user_page/user_preferences_interface_spec.rb
themes/horizon/spec/system/user_color_palette_selector_spec.rb

Before the "theme default" option appeared conditionally, which caused confusion. For example, it was shown when the theme was using a color scheme that was not user-selectable. If the scheme was selectable, then a specific scheme like "Merigold" was preselected. If the theme changed default schemes, that change was not reflected on the user interface.
Therefore, it would be better to always have the "Theme default" option, which would have `-1` id. It means that the user's color scheme will always follow theme defaults.

FEATURE: theme default option in user interface

---

app/assets/javascripts/admin/addon/controllers/admin-logs-staff-action-logs.js
app/controllers/export_csv_controller.rb
app/jobs/regular/export_csv_file.rb
spec/jobs/export_csv_file_spec.rb
spec/system/admin_staff_action_logs_spec.rb

On the Admin > Logs & Screening page, the Export button never applied the current page's filters. For older websites, viewing large exported logs may cause lag.
This commit makes the Export button respect the current page's filters, reducing the size of exported staff action logs and improving consistency.

FEATURE: Make staff action logs export respect the filter

---

plugins/chat/app/services/chat/auto_join_channels.rb
plugins/chat/plugin.rb
plugins/chat/spec/services/chat/auto_join_channels_spec.rb

Currently, it can happen that the `Chat::AutoJoinChannels` service raises a `PG::UniqueViolation` error. This is probably due to a race condition. That exception is not rescued, leading to 500s.
This PR wraps the main step inside a `try` block and also inside a `lock` block.

FIX: Catch possible PG exception from `Chat::AutoJoinChannels`

---

app/assets/javascripts/admin/addon/controllers/admin-customize-colors.js

Follow-up to https://github.com/discourse/discourse/commit/7a9cf9356e486cf3eb6a2c2bf6cd6927a6ef59e4, `_initialUserColorSchemeId` no longer exists — we can simplify to only showing this warning if the admin isn't using the default theme

FIX: Update logic for displaying admin palette warning

---

app/assets/javascripts/discourse/app/instance-initializers/live-development.js
app/models/theme.rb
spec/models/theme_spec.rb

In production, reloading CSS files before loading new JS is risky, and can lead to surprising UI flickering/breakage. This commit updates theme CSS 'file-change' notifications to trigger a reload on next navigation, just like regular core updates.
In development mode, CSS will still be refreshed 'live'.
Also adds the 'common' target to the list of refreshed CSS bundles, which will improve the experience in development mode.

FIX: Make theme live-reload safer

---

migrations/lib/database/intermediate_db/user_option.rb

Regenerate intermediate DB schema to reflect newly added `user_options` column

DEV: Add new `user_options` column to intermediate DB schema

---

app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js

On "slow" computers and/or in production builds of the client-side application, the redirection to discourse connect (via window.location) might happen _after_ the login/signup route is done loading and the login/signup template is being shown.
Since when discourse connect is enabled, no other auth "provider" is allowed, we "flashed" a screen that indicated there was no "login method" configured.
In order to fix this, we rely on the "isRedirectingToExternalAuth" boolean and ensure it's set to "true" when discourse connect is enabled.
This is unfortunately ~~impossible~~ very hard to test as it depends on how fast the browser running the test is...
The only way I was able to reproduce this issue locally was to throttle both the CPU and network in Chrome's performance tab.
---
I also …

FIX: show loading spinner when redirecting to discourse connect

---

plugins/discourse-calendar/app/serializers/discourse_post_event/event_summary_serializer.rb
plugins/discourse-calendar/spec/requests/events_controller_spec.rb
plugins/discourse-calendar/spec/serializers/discourse_post_event/event_summary_serializer_spec.rb

If you have a lot of recurring events, and particularly when recurring every day we would generate data for each of these days for a year, which means ~365 entries, multiplied by your number of events, you would quickly end up with a very large json payload.
This commit ensures we never return more than 31 upcoming dates (31 to ensure we can show a full month of events in the month view).
This was a known issue and this fix is not a definitive solution as it comes with a massive limitation: when clicking next we won't be showing you future events. This is mostly an issue for daily events, as monthly event will still allow you to see about 3 years of events which should be enough for most cases.
The ideal solution is to load only the events (and dates) we show on the screen instead of …

PERF: limit the number of upcoming dates generated

---

plugins/discourse-ai/app/models/embedding_definition.rb
plugins/discourse-ai/lib/inference/gemini_embeddings.rb
plugins/discourse-ai/spec/lib/inference/gemini_embeddings_spec.rb
plugins/discourse-ai/spec/models/embedding_definition_spec.rb

Includes tests for passing dimensions to GeminiEmbeddings and verifies request payloads with and without embedding_config.

FEATURE: Add support for matryoshka in Gemini embeddings

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/html-block.js
plugins/poll/assets/javascripts/lib/rich-editor-extension.js

A `draggable: true` ProseMirror node ["can be dragged without being selected"](https://prosemirror.net/docs/ref/#model.NodeSpec.draggable), so it doesn't make sense for nodes that allow inner `content`, as it would break the drag-text selection.
We had `html_block` and `poll` in this situation.

UX: avoid prosemirror nodes w/ content and draggable:true

---

app/assets/javascripts/discourse/app/components/welcome-banner.gjs
app/assets/javascripts/discourse/tests/integration/components/welcome-banner-test.gjs
app/models/welcome_banner_page_visibility.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/site_settings.yml
spec/system/page_objects/components/welcome_banner.rb
spec/system/welcome_banner_spec.rb
themes/horizon/scss/welcome-banner.scss

Enhances customizability of the core welcome banner by adding an Interface setting: *page visibility* to the core welcome banner.
This allows us to replace [advanced search banner](https://meta.discourse.org/t/advanced-search-banner/122939).

UX: add welcome banner page visibility setting

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/quote.js
spec/system/composer/prosemirror_editor_spec.rb

Adds a `[quote*]` input rule – when matched, leverages the markdown parser to convert it to ProseMirror.

UX: add [quote] rich editor input rule

---

plugins/discourse-ai/lib/completions/endpoints/open_ai.rb

Follow up to d410df351ddfc7542b71e30b8c5e72597ec94a3f which used '|' instead of '||' as or operator.
Decided to move the condition inside a regexp used by 'starts_with?'

FIX: correct open ai endpoint call

---

plugins/footnote/assets/javascripts/lib/rich-editor-extension.js
plugins/footnote/spec/system/rich_editor_extension_spec.rb

Adds a `[^n]` input rule to trigger a footnote creation on rich editor.

UX: add [^n] rich editor footnote input rule

---

app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js

This ensure auth works on webviews that aren't DiscourseHub.

FIX: Do not exit early from login route in webviews

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/html-inline.js
spec/system/composer/prosemirror_editor_spec.rb

Fixes our `html_inline` node's `parseDOM` which was not correctly setting the `tag` attribute from the pasted HTML.

FIX: rich editor html_inline parseDOM not setting the tag attr

---

app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js
spec/system/discourse_connect_spec.rb

When an "anon" user visits a topic that is "private", they will get a page that is server-rendered and doesn't load the client-side app.
When they click the "login" button, it will redirect to the /login route which loads the app. The only way we can know where the user landed initially is via the "document.referrer".
The issue was that the code that checked the referrer was **after** the code that is doing the redirection to discourse connect.
By putting the code before doing the redirection to discourse connect, we are successfully redirected to the landing url after doing the discourse connect auth.
I've also added a system spec that test the happy path by starting the most basic discourse connect compliant sso server in the background.

FIX: redirect to 'private' topic when using discourse connect

---

app/assets/javascripts/discourse/app/static/prosemirror/extensions/quote.js
spec/system/composer/prosemirror_editor_spec.rb

Changes the `[quote]` node making it `isolating: false` (the default), meaning it will be easier to backspace-delete it or break out of it via a double-enter (among other things).

UX: make rich-editor [quote] non-isolating

---

app/assets/javascripts/discourse/app/static/prosemirror/core/keymap.js
spec/system/composer/prosemirror_editor_spec.rb

Supports an ENTER key mapping to add a hard break when triggered at the end of a line ending in two spaces.

UX: add hard break with double space+enter on rich editor

---

app/assets/javascripts/discourse/app/static/prosemirror/core/keymap.js
spec/system/composer/prosemirror_editor_spec.rb

https://github.com/discourse/discourse/commit/909d19ddb8bd7cc68baf07529152d60cab5c47e5 introduced a bug (`Uncaught TypeError: can't access property "endsWith", n.nodeBefore.text is undefined`) when hitting ENTER after non-text nodes.
This should fix it.

FIX: rich editor ENTER after non-text node

---

lib/final_destination.rb

FD was using a user agent that is many years old so it is being flagged as
an out of date browser

FIX: update final destination to use more recent user agent

---

app/assets/javascripts/discourse/app/components/user-nav/messages-dropdown.gjs
app/assets/javascripts/discourse/app/controllers/user-private-messages.js
app/assets/javascripts/discourse/app/lib/sidebar/user/community-section/my-messages-section-link.js
app/serializers/current_user_serializer.rb
config/locales/server.en.yml
config/site_settings.yml
db/migrate/20250808064354_remove_experimental_sidebar_messages_count_enabled_groups_site_setting.rb
spec/system/viewing_sidebar_spec.rb
spec/system/viewing_user_private_messages_spec.rb

Removes the temporary `experimental_sidebar_messages_count_enabled_groups` site setting.
Reverts #33774.

DEV: remove experimental_sidebar_messages_count_enabled_groups

---

app/models/concerns/reviewable_action_builder.rb
app/models/reviewable.rb
app/models/reviewable_flagged_post.rb
app/models/reviewable_post.rb
app/models/reviewable_queued_post.rb
app/models/reviewable_user.rb
config/locales/server.en.yml
lib/reviewable/actions.rb
spec/models/concerns/reviewable_action_builder_spec.rb

This is a step towards unifying how reviewable types are defined.
In this PR, we add a new `ReviewableActionBuilder` concern, which can be included by the various reviewable types to give them a standard helper for adding actions that can be performed on the reviewable.
The first feature for this concern takes the `build_action()` helper that some reviewables used, and makes it available to all reviewables. This is done in a backward compatible fashion, so it will work even whilst we transition to the new reviewable UI.

DEV: Unify reviewable action definition.

---

app/assets/javascripts/discourse/app/lib/user-search.js
app/assets/javascripts/discourse/tests/unit/lib/user-search-test.js
plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs
plugins/chat/spec/system/chat_composer_spec.rb

The current chat autocomplete pipeline can mutate the user object selected for autocomplete here:
https://github.com/discourse/discourse/blob/071e82140cf375e2875b87d1664ae596c19320dd/plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs#L485
Specifically this occurs when we attempt to create a record in the store service where it already exists, and the logic for fetching the right record there deletes some properties from the input object:
https://github.com/discourse/discourse/blob/216df43502e25fcb9a228bfc09f90548712d7f49/app/assets/javascripts/discourse/app/services/store.js#L426-L435
This mutates the object that is eventually used to replace the search term (and therefore causes an error as it is now missing all its properties except for `id`). This also pollutes the …

FIX: user autocomplete search cache pollution

---

app/assets/stylesheets/common/base/user-badges.scss

Reported on meta
https://meta.discourse.org/t/xxx-more-box-in-user-card-not-aligned/378031?mobile_view=1
This commit removes margin on `user-badge` class to avoid misalignment on the usercard.
Only other instance I think uses this element is the admin badge page:
Which also does not need that margin.

UX: remove margin on user badge

---

app/assets/javascripts/discourse/app/instance-initializers/auth-complete.js
app/assets/javascripts/discourse/app/routes/application.js

Unable to repro this using tests, but can confirm with a local repro, when the site is `login required`, the controller isn't present in the router's promise. In those cases, we should look it up.
We do the same for signups later in this file.

FIX: Showing errors during social auth in some edge cases

---

themes/horizon/scss/sidebar.scss

I believe updating the way the component is connected in https://github.com/discourse/discourse-sidebar-theme-toggle/commit/9f2217410c97b87c9f82d2114a6da60a1b195505 caused ordering to become inconsistent here... so I've got to do it manually 
This PR puts the theme selector first, and removes the redundant icon (in Horizon the paintbrush icon is used to swap the color palette) 
Before:
After:

UX: fix theme toggle component positioning in Horizon

---

app/assets/javascripts/discourse/app/controllers/preferences/interface.js
app/assets/javascripts/discourse/app/routes/preferences-interface.js
app/assets/javascripts/discourse/app/templates/preferences/interface.gjs
app/assets/javascripts/discourse/tests/acceptance/user-preferences-interface-test.js
app/assets/stylesheets/common/base/user.scss
app/models/theme.rb
config/locales/client.en.yml
spec/system/page_objects/pages/user_preferences_interface.rb
spec/system/user_page/user_preferences_interface_spec.rb

Improves the user interface preferences by:
- Removing the separate dark mode toggle in favor of a unified color mode selector
- Ensuring proper theme cache invalidation when dark color scheme changes
- Remove dim out dark/light mode based on system settings

FEATURE: remove dark mode checkbox 

---

app/models/remote_theme.rb
lib/site_setting_extension.rb
lib/site_settings/local_process_provider.rb
spec/lib/site_setting_extension_spec.rb
spec/support/helpers.rb

This commit fixes an issue in multi-process setups where the following
would happen:
1. Admin changes a theme site setting. The new value is stored in memory
in the process that made the change. For this example, changing
`enable_welcome_banner` from `true` to `false`
2. Another user visits the site and hits another process, which has the
old value of `enable_welcome_banner` still set to `true` in memory
3. The other user's value for `enable_welcome_banner` is cached in
the cache for theme site settings, which is shared across all
processes
The issue is fixed by doing the same thing as site settings: when the
new value is saved, we send a MessageBus message to all processes via
`SiteSettingExtension` which calls `refresh!` and reloads the in-memory
cache of theme site settings from the …

FIX: Theme site settings not reloading across processes

---

app/jobs/scheduled/schedule_backup.rb
config/locales/server.en.yml
config/site_settings.yml
db/post_migrate/20250812033430_replace_null_with_zero_in_backup_frequency.rb
script/bulk_import/vanilla.rb
script/bulk_import/vbulletin.rb
script/bulk_import/vbulletin5.rb
spec/lib/backup_restore/shared_examples_for_backup_store.rb

In #33558 we removed `automatic_backups_enabled` setting, and instead rely on `backup_frequency` being blank to disable.
There was a big oversight there with the site setting type system, which will coerce the value to an integer. It also makes it so you can't blank the value out in the UI.
This is a "fix forward" solution where instead of "set to blank to disable" we do "set to 0 to disable". This works along the grain of the site setting type system for a workable fix where we don't have to deal with the irreversible migration in the previous change.
We can potentially go and add in "nullable" to the type system at a later point.

FIX: Use a valid value for disabling backups using backup_frequency

---

config/initializers/000-goldiloader.rb

Early results of testing out goldiloader is promising so we want to
start enabling it by default in the test environment to help catch
potential problems early.

DEV: Enable goldiloader in tests environment

---

config/locales/client.en.yml

Updating wording of `user_selectable_unavailable_button_label` to be more clear and accurate.

UX: Improve wording of non-user-selectable option for colour palettes

---

plugins/discourse-ai/assets/stylesheets/modules/ai-helper/common/ai-helper.scss

|Before|After|
|--|--|
|<img width="446" height="128" alt="CleanShot 2025-08-12 at 13 31 53@2x" src="https://github.com/user-attachments/assets/cdcf7c76-d045-4241-9070-d56ee81e9625" />|<img width="536" height="128" alt="CleanShot 2025-08-12 at 13 31 28@2x" src="https://github.com/user-attachments/assets/88af457c-579e-42e7-a506-0c02b5141e25" />|

FIX: Border-radius should appear in the edit topic title input

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/stylesheets/common/base/modal.scss

This improves modal header padding in the case of mobile modals having a primary action
Before:
After:
Modals without primary actions look like (unchanged):

UX: improve header alignment in mobile modals

---

app/assets/javascripts/discourse/app/components/post/avatar.gjs

Refactors `post/avatar` logic to return the original user object directly when the `avatar_template` is unchanged, avoiding unnecessary use of proxies and improving efficiency.

DEV: Optimize `post/avatar` proxy logic for unchanged templates

---

app/controllers/topics_controller.rb
app/helpers/topics_helper.rb
lib/localization_attributes_replacer.rb
lib/topic_list_responder.rb
spec/lib/localization_attributes_replacer_spec.rb
spec/requests/topics_controller_spec.rb

Follow up to https://github.com/discourse/discourse/pull/34212
This PR affects the crawler view for topic view, e.g. \<site>/t/:slug/:id, and updates the title, subcategory (+parent category breadcrumb), post, if any of them are not in the site default locale, and have an equivalent localization.
| before | after |
|---|---|
| <img width="1264" height="831" alt="Screenshot 2025-08-12 at 7 09 50 PM" src="https://github.com/user-attachments/assets/677d4595-4d4a-482e-b948-c0043576348e" /> mixed mode | <img width="1264" height="831" alt="Screenshot 2025-08-12 at 7 11 35 PM" src="https://github.com/user-attachments/assets/552f16ca-ebf2-4bdd-a052-a3abb8174a29" /> site default locale |

FEATURE: Localize topic view in crawler view

---

lib/localization_attributes_replacer.rb
spec/lib/localization_attributes_replacer_spec.rb

Follow up https://github.com/discourse/discourse/pull/34253 - There's a bug now where deleted topics will fail attribute replacement.

FIX: Deleted topic causes an issue when replacing attributes

---

app/assets/stylesheets/admin/customize.scss

On mobile, the email appearance form isn't very useable
Due to a seemingly unnecessary flex being applied. I can't find another instance of `.admin-customise .admin-container`, so I think it's safe to remove it and it won't impact other places?

UX: remove flex from admin email appearance form layout

---

app/assets/javascripts/admin/addon/components/color-input.gjs
app/assets/javascripts/discourse/app/components/edit-category-general.gjs
app/assets/javascripts/discourse/app/controllers/edit-category-tabs.js
app/assets/javascripts/discourse/tests/integration/components/color-input-test.gjs

This change allows users to update category text color without autocompleting the input value. Instead we are using `onBlur` to allow the normalized hex value to be updated when the using submits or tabs/clicks out of the field.
We are also restoring the normalized hex back to the correct value - for example`f8f` becomes `ff88ff` if using only 3 digits. This was mistakenly changed in #34218 to improve auto complete in the edit category page but it affects the color pickers in other parts of the app too.

FIX: set category text color on field blur

---

app/assets/javascripts/discourse/app/components/welcome-banner.gjs
app/assets/stylesheets/common/components/welcome-banner.scss
app/assets/stylesheets/desktop/user.scss
config/locales/server.en.yml
config/site_settings.yml
spec/system/page_objects/components/welcome_banner.rb
spec/system/welcome_banner_spec.rb

Add a background image setting for a core welcome banner to the *Interface & layout* admin page.
Replaces [advanced search banner](https://meta.discourse.org/t/advanced-search-banner/122939).

UX: add background image setting for welcome banner

---

app/models/color_scheme.rb
app/serializers/color_scheme_serializer.rb
spec/serializers/color_scheme_serializer_spec.rb

The `selected` and `hover` colors are always positioned at the bottom of the colors list in the admin color palette edit page. We think these colors are more likely to be customized than many of the colors currently shown above them, so this PR moves them a few places up so they appear below the `header_primary` color.

UX: Move `selected` and `hover` colors up in the color palette UI

---

themes/horizon/scss/buttons.scss

Fixes a minor styling regression with the disabled new topic button in the sidebar
Before:
After:

UX: fix Horizon disabled new topic button

---

app/assets/javascripts/discourse/app/components/card-contents-base.js

Currently, avatars located within a `DMenu` when clicked bring you to the user's activity page.
This PR adds `#d-menu-portals` to the selectors list. It will allow user-avatars within `DMenu` to trigger user-card appearance on click.
Thanks @CvX for the how-to.
https://github.com/user-attachments/assets/e07edb5a-f479-4382-8568-3df12f09a675
https://github.com/user-attachments/assets/3d9de236-8978-4b62-92d8-8d9708fb0488

DEV: Allow avatars contained within DMenu to trigger user-card open

---

app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js

Expanded the `CRITICAL_DEPRECATIONS` list to include `discourse.post-stream-widget-overrides` and `discourse.widgets-end-of-life` enabling admin notices.

DEV: Add admin widget notices

---

app/models/user_auth_token.rb
spec/models/user_auth_token_spec.rb

Fixes: https://meta.discourse.org/t/clean-up-user-auth-token-logs/326397?u=jonaharagon1
Currently (since 2021 when this logging was [made unconditional](https://github.com/discourse/discourse/commit/8fb823c30f7fd3086f4370c2dc6e4e3737ae6acf)) all user IP addresses and user agent strings for all forum users are continuously logged and never cleared. Keeping unnecessary PII is a massive liability for us, so I hope this can be merged ASAP.
I observe (in my user archive download) this indefinite logging does not happen on Meta, presumably because you have _verbose_ logging enabled, but it does happen on virtually all Discourse-hosted and self-hosted sites, which indicates to me this is unintended behavior. I should not have to enable verbose logging to _decrease_ the amount of logging here, …

FIX: Automatically clean up user_auth_token_logs

---

app/serializers/color_scheme_serializer.rb
spec/serializers/color_scheme_serializer_spec.rb

The color scheme fabricator doesn't always user `color_0` and `color_1` for the names, which can make this spec fail.

DEV: Stabilize `ColorSchemeSerializer#colors` spec

---

app/assets/javascripts/discourse/app/components/d-editor.gjs
app/assets/javascripts/discourse/app/lib/search.js
app/assets/javascripts/discourse/app/lib/user-search.js
app/assets/javascripts/discourse/app/modifiers/d-autocomplete.js
config/locales/client.en.yml
plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs
plugins/discourse-ai/assets/javascripts/discourse/components/ai-bot-conversations.gjs

Related to https://github.com/discourse/discourse/pull/34208.
Previously, missing name properties for a selected user search result would fail silently which made it difficult to tell if something had gone wrong with the user autocomplete. 
This PR adds some error handling to make it more obvious that an error has occurred. I've opted for using `toasts` here since it's less intrusive compared to the `dialog` modal. ~~Also left out translation as it's not actually actionable by the user other than reporting it to us.~~ added it anyway ✨ 
https://github.com/user-attachments/assets/92f585d8-95bf-4c5b-a08a-698c1a527b79

DEV: raise error on missing name properties for user autocomplete results

---

app/assets/javascripts/discourse/app/components/discovery/filter-navigation.gjs

The toggle bulk select was not showing on horizon on the filter route.
This is happened for two reasons:
We use a value transformer to render bulk select in the nav controls instead of the table header in horizon. In the filter markup, the bulk select toggle was set to only show on mobile, due to typically it rendering in the table header.
|Before|After|
|--|--|
|<img width="2396" height="1580" alt="CleanShot 2025-08-11 at 18 00 18@2x" src="https://github.com/user-attachments/assets/c4269b79-cd7a-4266-b0af-02251a2e065a" />|<img width="2400" height="1584" alt="CleanShot 2025-08-11 at 18 00 04@2x" src="https://github.com/user-attachments/assets/98381ecc-7f7a-439e-a283-35a736f05c4d" />|

UX: Show bulk select on filter page when set to show in nav controls

---

plugins/discourse-ai/app/controllers/discourse_ai/admin/ai_artifacts_controller.rb
plugins/discourse-ai/app/serializers/ai_artifact_serializer.rb
plugins/discourse-ai/config/routes.rb
plugins/discourse-ai/spec/requests/admin/ai_artifacts_controller_spec.rb

- GET /admin/plugins/discourse-ai/ai-artifacts.json — list (paginated, per_page capped at 100)
- GET /admin/plugins/discourse-ai/ai-artifacts/:id.json — show
- POST /admin/plugins/discourse-ai/ai-artifacts.json — create
- PUT /admin/plugins/discourse-ai/ai-artifacts/:id.json — update
- DELETE /admin/plugins/discourse-ai/ai-artifacts/:id.json — destroy
Admin-only, JSON responses.

FEATURE: CRUD access for ai-artifacts (admin only)

---

app/assets/javascripts/discourse/app/components/composer-container.gjs
app/assets/javascripts/discourse/app/components/create-topic-button.gjs
app/assets/javascripts/discourse/app/components/d-navigation.gjs
app/assets/javascripts/discourse/app/controllers/discovery/list.js
app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/discourse/app/models/composer.js
app/assets/javascripts/discourse/app/services/composer.js
app/assets/javascripts/discourse/tests/acceptance/category-banner-test.js
app/assets/javascripts/discourse/tests/acceptance/tags-test.js
app/assets/javascripts/select-kit/addon/components/category-chooser.js
app/assets/javascripts/select-kit/addon/components/category-row.gjs
app/assets/stylesheets/common/select-kit/category-row.scss
config/locales/client.en.yml
spec/system/composer/default_to_subcategory_spec.rb
spec/system/drafts_dropdown_spec.rb
themes/horizon/javascripts/discourse/components/sidebar-new-topic-button.gjs
themes/horizon/spec/system/sidebar_topic_button_spec.rb

Most of this feature was already approved in #33495 but it was reverted temporarily due to users accidentally posting in the wrong category (due to the default composer category site setting).
This PR removes the default category from composer when the user doesn't have permission to post in the category (preventing accidental posts in the wrong category), and also inserts the read-only category into the category chooser with a read only badge, this way providing some information to the user when they find it in the dropdown.
The read only category in the drop down can't be selected via clicking or keyboard selection.

FEATURE: enable topic creation button for read only categories

---

lib/guardian/bookmark_guardian.rb
lib/guardian/post_guardian.rb
lib/guardian/tag_guardian.rb
lib/guardian/topic_guardian.rb
lib/guardian/user_guardian.rb
spec/lib/guardian/bookmark_guardian_spec.rb

1. Make consistent use of `is_me?`, `is_my_own?`, etc. since these are more robust and don't use the `user` accessor method (soon to be deprecated) directly.
2. Add missing test coverage for `BookmarkGuardian` methods.

DEV: Consistently use Guardian helper methods

---

app/assets/javascripts/admin/addon/controllers/admin-customize-themes-show-index.js
app/assets/javascripts/admin/addon/templates/customize-themes-show-index.gjs

Before this change, no icon is set for the button when the theme being
displayed is not a theme component. That made the UI inconsistent since
all the surrounding action buttons has an icon. Previously, a cube was
used for a theme component but we don't see how that makes sense
anymore.
Upon clicking the button, there is a confirmation dialog that indicates
to the user whether we are converting the curren theme to a component or
not.

UX: Use rotate icon for convert theme button

---

app/assets/stylesheets/common/base/sidebar-section-link.scss
plugins/chat/assets/stylesheets/common/chat-message.scss

Follow up of https://github.com/discourse/discourse/pull/33902
Fixes:
* User status in chat mentions needed a spacing
* Sidebar user status was misaligned

UX: user status emoji alignment in sidebar and chat mention

---

app/assets/stylesheets/embed.scss

The default use is an emoji that matches the surrounding font-size so it makes sense to set this globally to 1em and adjust in the instances it needs to be different (which is often already in place)

UX: set emoji size to 1em

---

app/assets/javascripts/discourse/app/components/discovery/layout.gjs

This PR adds `model` arg to "discovery-above" PluginOutlet.

DEV: Add arg to discovery-above PluginOutlet

---

app/assets/javascripts/admin/addon/components/dashboard-new-feature-item.gjs
app/assets/javascripts/admin/addon/components/dashboard-new-features.gjs
config/locales/client.en.yml
lib/discourse_updates.rb
spec/lib/discourse_updates_spec.rb
spec/system/admin_dashboard_new_features_spec.rb
spec/system/page_objects/pages/admin_new_features.rb

The experimental label will be uncouple from the site setting toggle switch. See internal ticket t/160076

DEV: Update "what's new" feed due to upstream changes

---

app/assets/javascripts/admin/addon/components/admin-section-landing-item.gjs
app/assets/stylesheets/admin/admin_base.scss
app/assets/stylesheets/admin/admin_report.scss
app/assets/stylesheets/admin/admin_section_landing_page.scss
app/assets/stylesheets/common/components/theme-card.scss
plugins/discourse-ai/assets/stylesheets/common/ai-features.scss
plugins/discourse-ai/assets/stylesheets/modules/ai-bot/common/ai-persona.scss
plugins/discourse-ai/assets/stylesheets/modules/llms/common/ai-llms-editor.scss

This resolves a number of cases where we were highlighting content on hover that isn't clickable. 
Common table example
Before:
After:
Reports are a case where the box *should* be clickable, so I kept the hover effect and made the box clickable via changes to `admin-section-landing-item`... 
Before: 
After (removed the blue because the headings aren't actually links anymore, the whole box is): 
In cases where these boxes have buttons, the inner title (if linked) and buttons are clickable, not the box...

UX: don't highlight admin content on hover if it isn't clickable

---

app/assets/stylesheets/common/base/topic.scss

This category dropdown can become a little too short at different font scales, this fixes it. 
Before: 
After:

UX: fix category dropdown size in title editor

---

app/assets/javascripts/admin/addon/components/color-palette-list-item.gjs
app/assets/javascripts/admin/addon/components/themes-grid-card.gjs
app/assets/stylesheets/common/components/theme-card.scss
config/locales/client.en.yml
spec/system/admin_color_palettes_features_spec.rb
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes_config_area.rb

Active is a confusing term to use for the default theme
and color palette in the admin UI.
This commit updates the copy for consistency
to use Default instead of Active to reflect the code
and the way people think about how this works generally.
**Before**
**After**

UX: Update copy from Active -> Default for themes + palettes

---

app/assets/javascripts/admin/addon/services/admin-search-data-source.js
app/assets/javascripts/discourse/tests/unit/services/admin-search-data-source-test.js
lib/site_settings/label_formatter.rb

In the admin search, links to site settings for plugins that
are not using the new show page for plugins were pointing to
the admin route for the plugin. This is not useful, because most
plugins do not show their site settings here.
Instead, we should link to the plugin category on the /admin/site_settings
route.
This was first noticed with this setting:

FIX: Incorrect site setting link for plugins in admin search

---

app/assets/stylesheets/color_definitions.scss

Follow-up to 30ee375ee6f147f874cb36182d0db0fa22afb39c
We improved contrast of the light mode handle, but this wasn't ideal in dark mode... this fixes it 
Before: 
After:

UX: fix timeline handle color in dark mode palettes

---

app/assets/javascripts/admin/addon/components/themes-grid.gjs
app/assets/javascripts/admin/addon/controllers/admin-customize-colors.js

Follows the same pattern as the color palette index, where we
sort the themes once, and then resort only when the themes array
from the model changes. This fixes the issue where if you installed
a new theme, it would not show up on the grid until you refreshed.

FIX: Allow themes index to resort when adding new themes

---

app/assets/javascripts/admin/addon/controllers/admin-customize-colors.js
app/assets/javascripts/admin/addon/routes/admin-customize-colors.js
app/assets/javascripts/admin/addon/templates/customize-colors.gjs
app/controllers/admin/config/color_palettes_controller.rb
app/models/color_scheme.rb
app/serializers/color_scheme_serializer.rb
spec/helpers/application_helper_spec.rb
spec/lib/stylesheet/manager_spec.rb
spec/requests/admin/config/color_palettes_controller_spec.rb
spec/requests/application_controller_spec.rb

Fixes https://meta.discourse.org/t/checkbox-in-color-palettes-user-selectable-yes-no-doesnt-work/378545?u=osama
This PR moves the sorting logic to server-side to avoid caching issues where the (sorted) palettes list, which was stored as a property on the controller, would need to be invalidated each time the user navigated to the palettes list page because changes to palettes could've been made between the last and new visits to the page. This PR also eliminates an AJAX request that the palettes list page makes to fetch the default theme by including the default theme in the same response that includes the color palettes list.

FIX: Refresh palettes list when navigating back to palettes list page

---

lib/version.rb

Version bumps for main: v3.5.0.beta9, v3.6.0.beta1-dev

---

app/assets/javascripts/admin/addon/components/admin-config-areas/components.gjs
app/assets/javascripts/admin/addon/components/admin-config-areas/themes.gjs
app/assets/javascripts/admin/addon/components/install-theme-item.gjs
app/assets/javascripts/admin/addon/components/modal/install-theme.gjs
app/assets/javascripts/admin/addon/templates/customize-themes-show.gjs
spec/system/admin_customize_components_config_area_spec.rb
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/components/admin_customize_theme_install_button.rb
spec/system/page_objects/modals/install_theme.rb
spec/system/page_objects/pages/admin_customize_components_config_area.rb
spec/system/page_objects/pages/admin_customize_themes_config_area.rb

Prior to this change, creating a new theme or theme component was causing the user to stay on the index route.

UX: Creating a new theme/component should redirect to theme edit route

---

migrations/lib/database/schema/table_writer.rb

Before:
```sql
CREATE TABLE muted_users
(
created_at    DATETIME,
muted_user_id NUMERIC  NOT NULL,
user_id       NUMERIC  NOT NULL
);
CREATE TABLE user_custom_fields
(
created_at           DATETIME,
field_id             NUMERIC,
is_multiselect_field BOOLEAN,
name                 TEXT     NOT NULL,
user_id              NUMERIC  NOT NULL,
value                TEXT
);
CREATE UNIQUE INDEX ucf_multiselect_by_field_id_index ON user_custom_fields (user_id, field_id, value) WHERE is_multiselect_field = TRUE AND field_id IS NOT NULL;
CREATE UNIQUE INDEX ucf_not_multiselect_by_field_id_index ON user_custom_fields (user_id, field_id) WHERE is_multiselect_field = FALSE AND field_id IS NOT NULL;
CREATE UNIQUE INDEX ucf_multiselect_by_name_index ON user_custom_fields (user_id, name, value) WHERE …
```

DEV: Remove redundant newlines in generated indexes

---

app/assets/javascripts/discourse/app/components/topic-list/item.gjs
themes/horizon/javascripts/discourse/initializers/topic-list-columns.gjs

This commit adds a new `auxclick` event handler to the topic list item,
which calls the same `click` handler.
The `auxclick` event is triggered by auxiliary mouse buttons, such as
the middle mouse button. This fixes an issue where using the middle mouse button
on a topic card in Horizon anywhere but the topic title would not open the topic
in a new tab.
Normal topic list click functionality remains unchanged.
c.f. https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event
The areas in red were "dead zones" for middle click:

FIX: Handle auxclick event on topic list

---

plugins/discourse-chat-integration/config/locales/client.en.yml
plugins/discourse-chat-integration/lib/discourse_chat_integration/provider/matrix/matrix_provider.rb
plugins/discourse-chat-integration/spec/lib/discourse_chat_integration/provider/matrix/matrix_provider_spec.rb

This PR relaxes the accepted format of Matrix room IDs in the Matrix chat provider. It allows the new room ID format in [Room v12](https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/msc4291/proposals/4291-room-ids-as-hashes.md) to be used in Discourse.
Reported here: https://meta.discourse.org/t/new-matrix-v12-rooms-not-supported-by-chat-integration/378675

FIX: Relax Matrix room ID validation

---

app/assets/javascripts/theme-transpiler/package.json
app/assets/javascripts/theme-transpiler/postcss.js
lib/stylesheet/manager.rb
package.json
pnpm-lock.yaml
spec/lib/stylesheet/compiler_spec.rb

We were already polyfilling `light-dark` for older browsers. However, that polyfill makes use of native CSS nesting, which is also unsupported by older browsers. This commit adds the `postcssNesting` transform to turn that nesting back into flat CSS.
This became a noticable problem since light-dark was added to a critical core stylesheet in 1ec69c3f2f32c48b68596d639e1e495dc031f4ed, which then caused the whole file to be a syntax error under Safari 16.

FIX: Support `light-dark` on older browsers

---

app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js
spec/system/discourse_connect_spec.rb

DiscourseConnect "required" auth_immediately to also be enabled to work properly but this was incorrect.
This fixes that assumption and add specs to cover all combination of
- login_required
- auth_immediately
- visiting /
- visiting /login
Internal ref - t/161485

FIX: DiscourseConnect and auth_immediately = false

---

app/assets/stylesheets/common/base/modal.scss
plugins/chat/assets/stylesheets/common/chat-message-creator.scss
plugins/chat/assets/stylesheets/common/chat-modal-new-message.scss

Moved some things around to fix the lack of bottom padding while searching for results:
🔽

UX: fix cmd-k bottom padding

---

app/assets/javascripts/admin/addon/components/admin-config-areas/color-palette.gjs
app/assets/javascripts/admin/addon/components/color-palette-editor.gjs
app/assets/javascripts/admin/addon/templates/customize-themes-show-colors.gjs
app/assets/javascripts/discourse/tests/integration/components/color-palette-editor-test.gjs
app/assets/stylesheets/admin/color-palette-editor.scss
spec/system/admin_color_palette_config_area_spec.rb
spec/system/admin_customize_themes_spec.rb
spec/system/page_objects/components/color_palette_editor.rb

We've decided that we aren't going to go forward with dual-mode color palettes, so we're removing the code for it for now.
Internal topic: t/161398.

DEV: Remove color mode tabs from palette editor

---

app/assets/javascripts/discourse/app/components/glimmer-site-header.gjs
app/assets/javascripts/discourse/app/components/impersonation-notice.gjs
app/assets/stylesheets/common/base/header.scss
app/controllers/admin/impersonate_controller.rb
app/jobs/scheduled/clear_expired_impersonations.rb
app/models/user.rb
app/models/user_auth_token.rb
app/models/user_history.rb
app/serializers/current_user_serializer.rb
app/services/staff_action_logger.rb
config/locales/client.en.yml
config/locales/server.en.yml
config/routes.rb
config/site_settings.yml
db/migrate/20250811070948_add_impersonated_user_fields_to_user_auth_token.rb
lib/auth/current_user_provider.rb
lib/auth/default_current_user_provider.rb
lib/current_user.rb
lib/impersonator_constraint.rb
spec/models/user_auth_token_spec.rb
spec/requests/admin/impersonate_controller_spec.rb
spec/system/impersonation_spec.rb

The current impersonation feature works by signing you in as the user you are impersonating. This has the side effect of invalidating your own session and forcing you to log out and in again.
In this experimental implementation you keep your existing session, but `DefaultCurrentUserProvider` returns the user being impersonated, allowing you to see the site from their perspective.
There are two immediate questions to ask here:
**What if the application code path is compromised?**
The new implementation uses the same code path as the old one (with `ImpersonateController#create` as an entry point), and (critically) is behind the same guardian check.
**What if the database is compromised?**
As an implementation detail, this has a new field `impersonated_user_id` on the `UserAuthToken`. This …

DEV: Allow impersonation without session swapping

---

app/assets/javascripts/discourse/app/instance-initializers/component-templates.js
app/assets/javascripts/discourse/app/services/deprecation-warning-handler.js
app/assets/javascripts/discourse/tests/integration/component-templates-test.gjs

Switches from Ember's deprecation to our own

DEV: Polyfill component-template-resolving for Ember 6

---

app/assets/javascripts/admin/addon/components/color-palette-list-item.gjs
app/assets/javascripts/admin/addon/components/themes-grid-card.gjs
app/assets/stylesheets/admin/color_palettes.scss
app/assets/stylesheets/common/components/theme-card.scss
config/locales/client.en.yml
spec/system/admin_color_palettes_features_spec.rb
spec/system/admin_customize_themes_config_area_spec.rb
spec/system/page_objects/pages/admin_customize_themes_config_area.rb

UX: Improve default badge positioning on admin themes/colors index

---

app/controllers/application_controller.rb
lib/middleware/crawler_hooks.rb
spec/lib/middleware/crawler_hooks_spec.rb

Follow up to comments in https://github.com/discourse/discourse/pull/34466. We apply a header to minimize duplication, and also promote the check earlier.

DEV: Check for setting prior to applying transformation on crawler view

---

app/assets/javascripts/discourse/app/lib/autocomplete/category-tag.js
app/assets/javascripts/discourse/app/lib/autocomplete/emoji.js
app/assets/javascripts/discourse/app/lib/autocomplete/group.js
app/assets/javascripts/discourse/app/lib/autocomplete/user.js
app/assets/stylesheets/common/components/autocomplete.scss

The current way we try to style text spans that are too long is to apply the custom style `ellipsis` on the `a` element that wraps around text spans for each autocomplete item. However, this is being positioned with `flex` which does not apply that styling well on child elements. 
We need to apply it directly on text spans and orient them with `inline`/`inline-block`. As some of these autocomplete items have more than 1 span element in the same line, we use a wrapper `.text-content` as the target selector for this `ellipsis` styling.
Older Autocomplete:
Floatkit Autocomplete:
https://github.com/user-attachments/assets/0a999d37-2486-4939-8def-f0716841a953

FIX: truncate long names for autocomplete results

---

app/assets/stylesheets/common/base/compose.scss

The preview is supposed to be fullscreen on mobile.

UX: remove height limit when showing preview on mobile composer

---

app/assets/javascripts/discourse/app/controllers/preferences/profile.js
spec/system/user_page/user_preferences_profile_spec.rb

When adding a new field required "for all users", and the field is of "confirmation" type, it does not show up:
This is happening because we're checking for fields using `isEmpty`, assuming the value will be `null` before it is filled up, but for confirmation type fields it is in fact cast to `false`.
`isEmpty(value)` -> `!value`
This PR also fixes an issue where we'd "unlock" the user in the front-end even if the call to update the required fields failed.

FIX: Required confirmations not showing up

---

plugins/footnote/assets/javascripts/api-initializers/inline-footnotes.gjs
plugins/footnote/assets/stylesheets/footnotes.scss

This avoids the spacing caused by line breaks.
Meta report:
https://meta.discourse.org/t/extra-spaces-around-footnote/380153

UX: add class to inline-footnote to display as inline-block

---

plugins/chat/app/controllers/chat/api/channel_messages_controller.rb
plugins/chat/app/services/chat/list_channel_messages.rb
plugins/chat/spec/requests/chat/api/channel_messages_controller_spec.rb
plugins/chat/spec/services/chat/list_channel_messages_spec.rb

We recently updated `Chat::ListChannelThreadMessages` to take an option so its `max_page_size` could be configured.
This behavior should be consistent between `Chat::ListChannelThreadMessages` and `Chat::ListChannelMessages` since they’re basically doing the same thing.
This PR updates the behavior of the `Chat::ListChannelMessages` service.

DEV: Unify `ListChannelMessages`/`ListChannelThreadMessages` behaviors

---

docs/INSTALL-cloud.md

This PR adds three individual changes to the self-hosting installation guide:
1. A note on DigitalOcean blocking SMTP ports
1. A preemptive bit of troubleshooting for SMTP port 465
1. A nice title!
**A note on DigitalOcean blocking SMTP ports**
DigitalOcean is recommended in the self-hosting guide, but they block SMTP ports in all droplets by default now. This change formally occurred in March/April 2025. You can have them unblocked, but it requires a support ticket. I added this information right below the recommendation on using DigitalOcean.
**A preemptive bit of troubleshooting for SMTP port 465**
I don’t have the ability to edit the email troubleshooting guide, but since the self-hosting guide has a few helpful tips on setting up your email properly, I felt this was appropriate to …

Add a few helpful tips to the installation guide

---

app/assets/javascripts/discourse/app/instance-initializers/message-bus.js

The message bus initialization code has a bug where `messageBus.baseUrl` is set twice:
1. First set from `siteSettings.long_polling_base_url`
2. Immediately overwritten with `getURL("/")`
This makes the `long_polling_base_url` site setting ineffective, preventing users from configuring a separate message server or CDN for long polling.
This PR fixes the issue by:
- Adding conditional logic to check if `long_polling_base_url` is configured with a non-default value
- Using the configured URL when available, otherwise falling back to `getURL("/")`
- Removing the duplicate assignment that was overwriting the setting
- Modified `app/assets/javascripts/discourse/app/initializers/message-bus.js`
- Added proper conditional check for `long_polling_base_url` setting
- Preserved the URL …

FIX: Respect long_polling_base_url setting for message bus configuration

---

Gemfile
config/initializers/000-goldiloader.rb

As things are going well with Goldiloader enabled, we can now enable it by default.

DEV: Enable Goldiloader by default

---

app/assets/stylesheets/common/base/topic.scss
app/assets/stylesheets/common/components/buttons.scss
plugins/discourse-solved/assets/javascripts/discourse/connectors/topic-navigation/no-answer.gjs

This commit aims to polish the popup a tiny bit by subduing the title size and close button, and making sure they play better together.
| Header | After |
| <img width="1956" height="1400" alt="CleanShot 2025-08-25 at 16 19 59@2x" src="https://github.com/user-attachments/assets/d2eeddaa-7c99-433f-b70c-ccca1fb0a5bd" /> | <img width="1956" height="1400" alt="CleanShot 2025-08-25 at 16 20 30@2x" src="https://github.com/user-attachments/assets/0c8614c1-96c3-4c24-a185-bc5b4570f31d" /> |

UX: restyling of the solved popup

---

app/controllers/metadata_controller.rb
app/services/discourse_id/register.rb
config/locales/server.en.yml
config/routes.rb
lib/tasks/admin.rake
spec/requests/metadata_controller_spec.rb
spec/services/discourse_id/register_spec.rb

Implements the challenge/response flow for Discourse ID registration:
- Add `.well-known/discourse-id-challenge` endpoint to serve challenge tokens
- Create DiscourseId::Register service for automated registration flow
- Handle challenge token storage in Redis with 10-minute expiration
- Include comprehensive test coverage for both endpoint and service

WIP: Add Discourse ID challenge endpoint and registration service

---

plugins/discourse-calendar/assets/javascripts/discourse/routes/upcoming-events-base-route.js
plugins/discourse-calendar/spec/system/upcoming_events_spec.rb

Prior to this fix we would generate a range which would be incorrect as we would use Monday as the end of the week.

FIX: correctly start weeks en Monday

---

plugins/discourse-calendar/assets/javascripts/discourse/components/upcoming-events-list.gjs
plugins/discourse-calendar/test/javascripts/integration/components/upcoming-events-list-test.gjs

Previously, the dates within a month could go out of order. We were using plain javascript objects here with the date (DD) as the key, but these are unordered, so `12` would often be listed after `03`. 
Switching to a map allows us to sort properly.

FIX: Correctly order events in upcoming events list

---

app/assets/javascripts/discourse/app/components/header.gjs

Add a warning comment in the `header.gjs` file to clarify that the order of `div.header-buttons` and the `<Icons />` component must not be modified. This ensures compatibility with existing themes and Theme Components leveraging the DAG plugin APIs.

DEV: Comment about the header components order

---

app/assets/javascripts/admin/addon/controllers/admin-user-index.js
config/locales/client.en.yml
spec/system/impersonation_spec.rb

I wanted to have a more specific error when there's an unexpected server error (5XX).
Turns out the existing error differentiation (between `not_found` and `invalid`) was not working, because the shape of `e` is not what the developer expected.
This PR fixes that and adds another message for unexpected errors.

DEV: Improve errors for failed impersonation

---

plugins/discourse-ai/lib/embeddings/semantic_search.rb

Fixes "related topics" so they are instant vs many seconds long

PERF: do not hydrate all candidates in big relation

---

app/assets/javascripts/admin/addon/components/admin-config-areas/color-palette.gjs
app/assets/stylesheets/admin/admin_config_color_palettes.scss

- Add `.admin-config-color-palettes__sections` wrapper with flex layout
- Apply consistent `var(--space-4)` gap between sections
- Adjust save card top margin for proper alignment
Before
After

UX: Improve color palette layout with proper spacing

---

app/controllers/admin/search_controller.rb
lib/site_setting_extension.rb
spec/requests/admin/search_controller_spec.rb

FIX: `Default Locale` site setting not included in admin search

---

plugins/discourse-data-explorer/app/controllers/discourse_data_explorer/query_controller.rb
plugins/discourse-data-explorer/config/routes.rb
plugins/discourse-data-explorer/plugin.rb
plugins/discourse-data-explorer/spec/integration/custom_api_key_scopes_spec.rb
plugins/discourse-data-explorer/spec/requests/query_controller_spec.rb

New GET endpoint at /data-explorer/queries/ID/run.json
Allows for simple execution of queries based on ID
Previous endpoint was POST and required group name, which makes it harder to use via API

DEV: new API endpoint for data explorer query running

---

spec/system/composer/drafts_spec.rb
spec/system/page_objects/components/toasts.rb

This spec was not testing the right thing, the draft
is not supposed to save if the topic title is too short,
but the way the expectations were written (checking the
float message) made it pass incorrectly.

DEV: Fix draft spec

---

plugins/chat/app/services/chat/search_chatable.rb
plugins/chat/spec/services/chat/search_chatable_spec.rb

This change prevents the user from starting a group chat with groups when the current user does not have permission to view the group's members.
The group is omitted from both the default list and results list when searching.
Internal ref: /t/-/145343

FIX: prevent group chat when cannot see group members

---

plugins/discourse-ai/assets/javascripts/discourse/components/ai-persona-llm-selector.gjs
plugins/discourse-ai/spec/system/ai_bot/ai_bot_helper_spec.rb

Currently we show the AI persona dropdown on the AI conversations page if there's only one option:
To simplify, we should only show it when more than one option are present: 
and it appears again with multiple options:

UX: only show AI persona dropdown with multiple options

---

plugins/chat/app/models/chat/message.rb
plugins/chat/spec/lib/chat/core_pretty_text_spec.rb

Chat is using custom rules so it means we are considered as using a "zero" preset and have to declare everything we use.

FIX: supports html entities in chat

---

lib/discourse_updates.rb
lib/git_utils.rb
spec/lib/discourse_updates_spec.rb

This allows using commit hashes in addition to Discourse versions to decide whether to show a feature in the "What's new?" feed or not.
The command `git cat-file -t` uses Git's index, and is `0.01s` with 60k commits. The results are also cached.
I considered a case where the version could be spoofed, e.g. using DNS poisoning, leading to a possible command injection.
I'm sanitizing the version to just `a-z` and `0-9`. No spaces, special characters, etc. To my understanding that is not sufficient to be used maliciously, but would love a second set of eyes. 👀

DEV: Allow specifying a new feature by a commit hash

---

app/assets/javascripts/discourse/app/models/login-method.js
app/serializers/auth_provider_serializer.rb
lib/auth/auth_provider.rb
spec/serializers/auth_provider_serializer_spec.rb
spec/system/user_page/user_preferences_account_spec.rb

Add capability to pass an icon setting into auth provider registration to override the default icon with a site setting.
Matches the pattern we use for the auth provider title and pretty name. 
With this, the SAML plugin can be updated to have a site setting to override the default "user" icon.

DEV: Add capability to pass an icon setting into auth provider registration

---

plugins/discourse-calendar/assets/javascripts/discourse/components/upcoming-events-calendar.gjs
plugins/discourse-calendar/spec/system/upcoming_events_spec.rb

Checking the title first allows us to ensure the current path should be in its final state.

DEV: more reliable calendar navigation specs

---

config/locales/client.en.yml

Followup b24a3d81edfe14f90975ad12ce28239f1189d6a7

FIX: Add missing translation for stop_impersonating

---

app/assets/javascripts/discourse/app/components/footer-nav.gjs
app/assets/stylesheets/mobile/login-signup-page.scss

In login/signup routes in particular, the footer nav blocks access to the main CTA. It's important to both remove it from those screens and add appropriate padding to the CTA wrapper.
Before (PWA on iOS)
After (PWA on iOS)

UX: Do not include PWA/mobile app footer nav on some routes

---

plugins/discourse-calendar/app/models/discourse_post_event/event.rb
plugins/discourse-calendar/app/serializers/discourse_post_event/basic_event_serializer.rb
plugins/discourse-calendar/app/serializers/discourse_post_event/event_serializer.rb
plugins/discourse-calendar/assets/javascripts/discourse/components/category-calendar.gjs
plugins/discourse-calendar/assets/javascripts/discourse/components/upcoming-events-calendar.gjs
plugins/discourse-calendar/assets/javascripts/discourse/models/discourse-post-event-event.js
plugins/discourse-calendar/spec/models/discourse_post_event/event_spec.rb
plugins/discourse-calendar/spec/serializers/discourse_post_event/event_serializer_spec.rb
plugins/discourse-calendar/spec/system/page_objects/discourse_calendar/upcoming_events.rb
plugins/discourse-calendar/spec/system/upcoming_events_spec.rb

rrule doesn't support duration so we have to ensure we can communicate the duration to the frontend.
We were also making a mistake for the end date of non recurring events.

FIX: ensures events have correct duration

---

app/assets/javascripts/discourse/app/controllers/preferences/security.js
app/assets/javascripts/discourse/app/templates/preferences/security.gjs
config/locales/client.en.yml
spec/system/user_page/user_preferences_security_spec.rb

By design, staged users can't receive reset password e-mails. From documentation:
> Forgot password will do nothing …when you attempt to send a password reset to a staged account
This PR just disables the button in the UI to avoid confusion.
I also took the liberty to add a text explanation when it is disabled, because I kind of anticipate the question.
**Non-staged user:**
**Staged user:**

DEV: Disable reset password button for staged users

---

plugins/discourse-ai/config/locales/client.en.yml
plugins/discourse-ai/lib/completions/dialects/chat_gpt.rb
plugins/discourse-ai/lib/completions/dialects/dialect.rb
plugins/discourse-ai/lib/completions/dialects/gemini.rb
plugins/discourse-ai/lib/completions/endpoints/base.rb
plugins/discourse-ai/lib/completions/endpoints/gemini.rb
plugins/discourse-ai/lib/completions/llm.rb
plugins/discourse-ai/lib/completions/prompt_messages_builder.rb
plugins/discourse-ai/spec/lib/completions/dialects/dialect_spec.rb
plugins/discourse-ai/spec/lib/completions/dialects/gemini_spec.rb
plugins/discourse-ai/spec/lib/completions/endpoints/gemini_spec.rb
plugins/discourse-ai/spec/lib/completions/prompt_messages_builder_spec.rb

Adds support for: https://blog.google/products/gemini/updated-image-editing-model/
This mode generates images natively, we updated the Gemini endpoint to support handling image output.
Additionally, there is a refinement to how we provide image context to models, we avoid very short descriptions and simply
inline images in the context, prior to this fix image generating models could get confused and start generating markdown blobs.
This takes care to properly omit images from context in model responses for anthropic and open ai in responses api.

FEATURE: add support for google image model

---

app/assets/stylesheets/mobile/topic-list.scss

Many solutions possible here. I could also just reserve some extra spacing, but I feel the z-index layer is a more elegant solution.
At the moment only an issue on Horizon, due to the absence of the table header there. But applying it globally because theres other setups without the that layout.
| Before | Now |
| <img width="832" height="502" alt="CleanShot 2025-08-28 at 13 24 12@2x" src="https://github.com/user-attachments/assets/b84b15b2-6163-4fc6-88de-378a58a4ffda" /> | <img width="832" height="502" alt="CleanShot 2025-08-28 at 13 24 40@2x" src="https://github.com/user-attachments/assets/35d4964a-ab02-425f-92bf-62ddd984e9af" /> |

UX: keep new nav underline visible

---

app/models/user.rb
app/models/user_field.rb
spec/models/user_spec.rb

A confirm field will always be a Boolean so there's no need to check for it. This was causing an error as we were trying to treat it as a string in the watched word code.
Example error:
```
NoMethodError (undefined method `gsub' for true)
app/services/word_watcher.rb:258:in `censor_text_with_regexp'
app/services/word_watcher.rb:146:in `block in censor_text'
app/services/word_watcher.rb:146:in `each'
app/services/word_watcher.rb:146:in `inject'
app/services/word_watcher.rb:146:in `censor_text'
app/models/user.rb:1612:in `block in apply_watched_words'
app/models/user.rb:1611:in `each'
app/models/user.rb:1611:in `apply_watched_words'
app/models/invite_redeemer.rb:156:in `create_user_from_invite'
app/models/invite_redeemer.rb:220:in `invited_user'
app/models/invite_redeemer.rb:277:in …
```

FIX: exclude confirm user field from watch word check

---

app/models/user.rb
app/models/user_field.rb
spec/models/user_spec.rb

This is a backport of #34646 to the stable branch.
If a user field doesn't allow user-editable text content, then there's no need to validate that the user field content passes the word watcher checks.

FIX: exclude non-text user fields from watch word check

---

config/initializers/100-sidekiq.rb

Set to `true` to skip not `false`...
Follow-up to 504233da6eb9b1cdb08797717c8e29c22b3d3660

DEV: Configure skip_default_job_logging for Sidekiq take 2

---

lib/action_dispatch/session/discourse_cookie_store.rb
spec/integration/discourse_cookie_store_spec.rb

This PR logs what’s in the cookie when there is an overflow, as it sometimes happens during auth workflows. This should help us better understand what’s happening.

DEV: Debug cookie overflows

---

plugins/discourse-ai/spec/lib/completions/cancel_manager_spec.rb

This spec is flaking a lot. Adding debug logs to try and identify whether this is a specific-specific problem, or something which may affect production too.

DEV: Debug timeout of `.join` on AI cancel_manager_spec

---

plugins/chat/app/services/chat/create_message.rb
plugins/chat/app/services/chat/update_message.rb
plugins/chat/spec/services/chat/create_message_spec.rb
plugins/chat/spec/services/chat/update_message_spec.rb
spec/fabricators/upload_fabricator.rb

When creating or updating a chat message, uploads attached to the message are filtered so as to only keep uploads created by the message creator using `Upload.user`. This field, however, only points to the _original_ user that created the upload, but since uploads are de-duplicated, other users might have also uploaded the file. This PR fixes this by looking at the `UserUpload`s instead (as suggested by @SamSaffron).
Reported here: https://meta.discourse.org/t/chat-upload-bug/379253

FIX: in chat messages, filter uploads by `UserUpload`, not by `Upload.user`

---

app/assets/javascripts/admin/package.json
app/assets/javascripts/dialog-holder/package.json
app/assets/javascripts/discourse-plugins/package.json
app/assets/javascripts/discourse-widget-hbs/package.json
app/assets/javascripts/discourse/package.json
app/assets/javascripts/float-kit/package.json
app/assets/javascripts/pretty-text/package.json
app/assets/javascripts/select-kit/package.json
pnpm-lock.yaml

Following the update to v5.100.0, changes to files under `app/static/*` are no longer reflected live in development mode.

DEV: Pin Webpack to 5.99.9

---

plugins/discourse-calendar/assets/javascripts/discourse/components/upcoming-events-list.gjs

Addresses two issues. On sites with many old events, we would not show the correct items because the query would return the older events first.
Adds `includeSubcategories` parameter to include events from subcategories in the list.
No tests for now, we might refactor this component very soon.

FIX: Include subcategories in upcoming events list, add `after` param

---

plugins/discourse-calendar/app/controllers/discourse_post_event/invitees_controller.rb
plugins/discourse-calendar/app/models/discourse_post_event/event.rb
plugins/discourse-calendar/app/models/discourse_post_event/invitee.rb
plugins/discourse-calendar/app/serializers/discourse_post_event/event_serializer.rb
plugins/discourse-calendar/app/serializers/discourse_post_event/event_stats_serializer.rb
plugins/discourse-calendar/assets/javascripts/discourse/components/discourse-post-event/status.gjs
plugins/discourse-calendar/assets/javascripts/discourse/components/modal/post-event-builder.gjs
plugins/discourse-calendar/assets/javascripts/discourse/lib/raw-event-helper.js
plugins/discourse-calendar/assets/javascripts/discourse/models/discourse-post-event-event.js
plugins/discourse-calendar/assets/javascripts/discourse/services/discourse-post-event-api.js
plugins/discourse-calendar/config/locales/client.en.yml
plugins/discourse-calendar/config/locales/server.en.yml
plugins/discourse-calendar/db/migrate/20250811120000_add_max_attendees_to_events.rb
plugins/discourse-calendar/jobs/regular/discourse_post_event/bulk_invite.rb
plugins/discourse-calendar/lib/discourse_post_event/event_parser.rb
plugins/discourse-calendar/spec/fabricators/invitee_fabricator.rb
plugins/discourse-calendar/spec/models/discourse_post_event/event_spec.rb
plugins/discourse-calendar/spec/requests/events_controller_spec.rb
plugins/discourse-calendar/spec/requests/invitees_controller_spec.rb
plugins/discourse-calendar/spec/serializers/discourse_post_event/event_serializer_spec.rb
plugins/discourse-calendar/spec/system/post_event_spec.rb

Allows to set the max attendees of an event. When an event is full you can only mark yourself as interested or not going. The going button will be disabled.
Maximum attendees can be defined in the post builder:

FEATURE: introduce max attendees for events

---

lib/git_utils.rb
lib/version.rb

There are two issues addressed by this PR:
1. We log an error to console when a git hash is passed to `Discourse#has_needed_version?`. This isn't correct. We should just return `false`.
2. We only check that the commit hash is in the repo, we don't check that it's actually an ancestor in the current tree. So you'd see the feature even if you're on a branch that doesn't have it.

FIX: New features git hash version tweaks

---

config/locales/client.en.yml

This fixes the wording when attempting to delete an admin user to say that only admins cannot be deleted, without mentioning moderators. This means the wording will now reflect the actual behaviour.

FIX: Correct user deletion wording

---

app/assets/javascripts/theme-transpiler/transpiler.js
app/models/theme.rb
lib/discourse_js_processor.rb
lib/ember_cli.rb
spec/lib/discourse_js_processor_spec.rb
spec/lib/ember_cli_spec.rb

During in-container updates, the old version of the application continues running while an update is applied. That means that it's possible for the `node_modules/ember-source` version to be different to the version currently loaded in the transpiler. That means it's theoretically possible for theme assets to be built with the old compiler, and then stored against the new version.
This commit removes that race condition by adding an `ember_version` method to the JS transpiler. This is guaranteed to give us an accurate version number for the template-compiler currently being used for themes.
This commit also bumps the BASE_COMPILER_VERSION to force a recompile on any sites affected by this race condition.

FIX: Ensure ember version in cache key is coupled to compiler

---

app/assets/javascripts/discourse/app/controllers/signup.js

In some rare instance the provider of the "authOptions" might not be set correctly. Instead of showing an string like "authenticated by [missing %{provider value}]" we show a generic "ok" message.
Internal ref - /t/154880/58

FIX: display a generic message when email is auth'ed without a provider

---

plugins/discourse-ai/app/controllers/discourse_ai/admin/ai_translations_controller.rb
plugins/discourse-ai/assets/javascripts/discourse/components/ai-translations.gjs
plugins/discourse-ai/config/locales/client.en.yml
plugins/discourse-ai/config/locales/server.en.yml
plugins/discourse-ai/spec/requests/admin/ai_translations_controller_spec.rb
plugins/discourse-ai/spec/system/admin_ai_translations_spec.rb

Follow up to https://github.com/discourse/discourse/pull/34643
- Pluralizes posts
- Shows the chart even if `ai_translation_backfill_hourly_rate` is zero, and indicates as such
- Appropriate paddings
- Hides labels if bar too short
| desk | mob |
|---|---|
| <img width="1264" height="831" alt="Screenshot 2025-09-02 at 2 18 25 PM" src="https://github.com/user-attachments/assets/e9462238-7ca4-4beb-a1ab-aa70b6d93036" /> | <img width="300" height="2796" alt="d loc_admin_plugins_discourse-ai_ai-translations_mobile_view=1(iPhone 14 Pro Max)" src="https://github.com/user-attachments/assets/4e5047f5-9185-426a-aabf-c992f9df4d04" /> |

UX: Some translation progress chart refinements

---

app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/discourse/tests/unit/lib/category-badge-test.js

When both parent and child categories had the same style type, the icon and emoji values would leak from the child to the parent when generating the category badge html. When processing categories recursively in this way we should unset these values to ensure they are taken from the ancestor category directly rather than from an option.

FIX: reset category styles for ancestor recursion

---

spec/system/signup_spec.rb

The test is flaky because the route which we are asserting for leads to
a redirect. If the assertion is called before the redirect, the test
passes. If the assertion is called after the redirect, the test fails.
Instead, we can just assert for the final state which we want to see. The intermediate route itself is not important.

DEV: Fix a flaky signup system test

---

app/assets/javascripts/discourse/app/components/create-topic-button.gjs
app/assets/javascripts/discourse/app/components/topic-drafts-dropdown.gjs
themes/horizon/javascripts/discourse/components/sidebar-new-topic-button.gjs
themes/horizon/scss/buttons.scss

The Horizon theme was overriding `btn-default` styles for the new topic button in the sidebar with custom CSS to achieve `btn-primary` styles. Ideally we should be able to swap out the class and rely on that! 
So here I
1. Convert CreateTopicButton to Glimmer component 
2. Add `@btnTypeClass` param - Allows parent components to specify the button type
(`btn-primary`, `btn-default`, etc.)
3. Separate concerns:
* `@btnClass` handles general class name needs (and existing use) 
* `@btnTypeClass` handles core visual style

UX: glimmerize CreateTopicButton, make btnType class variable for Horizon

---

spec/system/admin_about_config_area_spec.rb
spec/system/page_objects/components/form_kit.rb
spec/system/page_objects/components/uppy_image_uploader.rb

I don't see a good reason why we should be executing a script to submit
a form when we can just click the submit button.

DEV: Update `PageObjects::Components::FormKit#submit` to click submit

---

plugins/chat/spec/system/channel_members_page_spec.rb

When visiting a channel's members info route directly, the add member
button will always be shown because the logic to show the button assumes
that chat messages have been loaded. Skip for now while we figure out a
fix.

DEV: Skip a broken spec

---

plugins/discourse-assign/spec/system/assign_topic_spec.rb
plugins/spoiler-alert/spec/system/composer_spoiler_spec.rb

This test appears to be flaky. Specifically the last expect.
Follow up to: #34734

DEV: Skip flaky d-assign spec

---

plugins/poll/assets/stylesheets/common/poll.scss
plugins/poll/config/locales/client.en.yml
plugins/poll/config/locales/server.en.yml

"Editing" can be a little misleading, because we technically only allow adding/removing — if you edit an existing option the votes are reset. 
This shortens the text by removing the "dynamic poll" text (seems self-explanatory without naming it), and also specifies adding/removing
Before:
After: 
I also reduced padding to the poll info slightly to give text a little more space before wrapping.

UX: use more specific language for dynamic polls

---

app/assets/javascripts/discourse/app/components/bulk-select-toggle.gjs
app/assets/javascripts/discourse/app/components/d-navigation.gjs
app/assets/javascripts/discourse/app/components/notifications-tracking.gjs
config/locales/client.en.yml
themes/horizon/scss/hiddenstuff.scss

Some small polish.
**Before:**
**After:**

UX: Polish for topic list controls

---

plugins/chat/assets/javascripts/discourse/components/chat-message.gjs
plugins/chat/assets/javascripts/discourse/lib/chat-message-interactor.js
plugins/chat/spec/system/page_objects/chat/chat_channel.rb
plugins/chat/spec/system/react_to_message_spec.rb

Prior to this change we would have different context for quick reactions and for channels this commit just move everything into one context which is less surprising.

FIX: ensures quick reactions usage shows in frequently

---

plugins/chat/assets/javascripts/discourse/lib/chat-channel-subscription-manager.js
plugins/chat/assets/javascripts/discourse/lib/chat-threads-manager.js
plugins/chat/assets/javascripts/discourse/services/chat-channels-manager.js

Prior to this fix we would fetch thread data even if it was present in the bus data, that's already unnecessary work in a normal situation but that's even worse when a user is coming back to their computer as we will have to catchup multiple new threads at once.
Also ensures we correctly await fetching data from server when necessary.
No test as there are not behavior change.

PERF: do not fetch thread data when we have it

---

plugins/discourse-calendar/app/serializers/discourse_post_event/basic_event_serializer.rb
plugins/discourse-calendar/assets/javascripts/discourse/components/category-calendar.gjs
plugins/discourse-calendar/assets/javascripts/discourse/components/upcoming-events-calendar.gjs
plugins/discourse-calendar/spec/models/discourse_post_event/event_spec.rb
plugins/discourse-calendar/spec/system/upcoming_events_spec.rb
plugins/discourse-calendar/test/javascripts/acceptance/category-events-calendar-test.js

This was preventing the `map_events_to_color` site setting to work correctly given we couldn't match on tag slug as it was not present.
This commit adds system specs and removes the js test as it was misleading and incorrectly passing due to the fixture which couldn't catch the issue in the serializer.

FIX: ensures event serializer has tags info

---

app/assets/javascripts/discourse/app/controllers/user-private-messages-group.js
app/assets/javascripts/discourse/app/controllers/user-private-messages.js
app/assets/javascripts/discourse/app/templates/user-private-messages-group.gjs
app/assets/javascripts/discourse/app/templates/user/messages.gjs
app/assets/stylesheets/common/base/new-user.scss

This undoes an older refactor that introduced an empty div for use with `in-element` to improve the group inbox loading experience (https://github.com/discourse/discourse/pull/21930)
The empty span being always present isn't ideal, because this causes additional space to be included when the `gap` property is used to space elements within a flex or grid container. 
Large space caused by use of `gap` when empty div is present: 
Additionally, our loading experience is different than it used to be (compare to the videos in https://github.com/discourse/discourse/pull/21930... we no longer show the spinner) — *and* we hide the text for the dropdown button, so there's much less jankiness to avoid when the notification button is added: …

DEV: refactor `groupNotificationsButton` to no longer rely on empty div

---

app/assets/stylesheets/common/base/_topic-list.scss
app/assets/stylesheets/common/components/drafts-dropdown-menu.scss
themes/horizon/scss/mobile-stuff.scss

Concerns this section of the nav:
This switches the margin between buttons to `gap` which is more predictable and avoids situations where an extension might need to add its own margin, like this:
After this change:
Ideally shouldn't be merged until https://github.com/discourse/discourse/pull/34770 is, because the empty div removed in that PR causes too much space when `gap` is utilized

UX: remove margin from navigation-controls children in favor of gap

---

config/locales/server.en.yml

pipe delimited lists are not exposed in the UI, users always have proper controls, stop mentioning this in help text.

DEV: stop talking about pipe delimited lists in docs

---

app/assets/javascripts/discourse/app/static/prosemirror/core/keymap.js
spec/system/composer/prosemirror_editor_spec.rb

Fixes an issue where a hashtag is decorated in composer and we try to either:
- press return in middle of a paragraph to move the hashtag onto the next line
- press backspace at beginning of a paragraph containing emojis
In both scenarios the hashtag decoration was lost but the data attributes were retained (ie. `processed` was set to `true`). By setting `processed` to `false` we can force hashtags to be processed again after breaking into a new paragraph or when pressing backspace at the start of the line to combine two paragraphs.
Demo:
https://github.com/user-attachments/assets/755f8619-ed04-4b65-bdd3-e14c0c591583
Internal ref: /t/-/159535

FIX: reset hashtags when pressing return in composer

---

spec/requests/api/groups_spec.rb

Update rspec api doc test to follow new format and use the shared
success_ok_response.

DEV: API docs update for update group endpoint

---

plugins/discourse-ai/lib/translation/language_detector.rb
plugins/discourse-ai/lib/translation/post_locale_detector.rb
plugins/discourse-ai/spec/lib/translation/language_detector_spec.rb
plugins/discourse-ai/spec/lib/translation/post_locale_detector_spec.rb

Seeing many errors about
```
DiscourseAi::Completions::Endpoints::Gemini: status: 400 - body: {
"error": {
"code": 400,
"message": "* GenerateContentRequest.contents: contents is not specified\n",
"status": "INVALID_ARGUMENT"
}
}
```
This is triggered due to posts with images and no text.
The solution here is to set the locale to site default locale.

FIX: Do not send empty content when detecting language

---

plugins/chat/app/models/chat/direct_message_channel.rb
plugins/chat/spec/fabricators/chat_fabricator.rb
plugins/chat/spec/models/chat/direct_message_channel_spec.rb
plugins/chat/spec/services/chat/create_thread_spec.rb
plugins/chat/spec/system/channel_settings_page_spec.rb
plugins/chat/spec/system/chat_footer_spec.rb
plugins/chat/spec/system/list_channels/drawer_spec.rb
plugins/chat/spec/system/message_notifications_with_sidebar_spec.rb

Previously we introduced threads in Chat DMs in #29170 - however setting the default to false seems like a better fit.
This will take effect for all new DM chats initiated, existing chats are not changed but threads can still be turned off manually within each channel's settings.

FEATURE: disable chat DM threads by default

---

plugins/discourse-ai/config/locales/server.en.yml
plugins/discourse-ai/config/settings.yml
plugins/discourse-ai/lib/embeddings/schema.rb
plugins/discourse-ai/lib/embeddings/semantic_related.rb
plugins/discourse-ai/spec/lib/modules/embeddings/semantic_related_spec.rb

Introduces two new site settings to apply exponential age-based
penalties to semantic topic suggestions, similar to algorithms
used by Reddit/HN:
* ai_embeddings_semantic_related_age_penalty (default: 0.3)
Controls penalty strength. 0.0 = disabled, 0.3 = gentle bias
toward newer content, 1.0+ = strong recency preference
* ai_embeddings_semantic_related_age_time_scale (default: 365 days)
Controls time horizon. Use 365 for yearly scale, 90 for
quarterly scale, etc.
Formula: similarity_score / POWER(age_in_days / time_scale + 1, penalty)
This allows sites to de-prioritize older topics in suggestions
while maintaining configurability for forums with different
content lifecycles. Performance optimized with conditional
JOINs only when penalty > 0.

FEATURE: add configurable age penalty for semantic related topics

---

app/assets/javascripts/discourse/app/lib/autocomplete.js

We are deprecating this jquery-based autocomplete library, replaced by DAutocomplete modifier for text field usage and DMultiSelect for input selector usage.

DEV: add deprecation console warning to jquery autocomplete

---

plugins/discourse-calendar/app/controllers/discourse_post_event/events_controller.rb
plugins/discourse-calendar/app/models/discourse_post_event/event.rb
plugins/discourse-calendar/app/serializers/discourse_post_event/basic_event_serializer.rb
plugins/discourse-calendar/app/serializers/discourse_post_event/event_topic_serializer.rb
plugins/discourse-calendar/lib/discourse_post_event/event_finder.rb
plugins/discourse-calendar/spec/fabricators/event_fabricator.rb
plugins/discourse-calendar/spec/requests/events_controller_spec.rb

There was two issues:
- using the `TopicListItemSerializer` was fetching way more than we need and also expecting includes from other plugins (assign for example), switching to our own dedicated serializer seems a better choice here
- event dates were not preloaded
- fixed a spec which was supposed to track N+1 but was commented
I also improved our fabricator to limit the boilerplate needed.
We might need few more indices to improve perf event more here but going to merge this first.

PERF: removes N+1 when loading events list

---

plugins/discourse-calendar/assets/javascripts/discourse/pre-initializers/rich-editor-extension.js
plugins/discourse-calendar/test/javascripts/integration/components/rich-editor-extension-test.js

Prior to this fix events with a description wouldn't show in the composer when they contain a description. This was particularly problematic as saving the post in this state would remove the event.

FIX: supports description for post events in rich editor

---

app/assets/javascripts/discourse/app/controllers/application.js

Refactor `showSidebar` in `application.js` to use a tracked property, allowing dynamic updates and configurable overrides. This supports themes that rely on viewport properties to adjust the sidebar's visibility.
Testing should be covered by existing tests, e.g: https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/tests/acceptance/sidebar-narrow-desktop-test.js

DEV: Convert `showSidebar` to a tracked property with getter and setter

---

app/assets/stylesheets/common/components/user-card.scss
app/assets/stylesheets/mobile/components/user-card.scss

Follow up to https://github.com/discourse/discourse/commit/e48df443497142f5d064e2ea43048f4c86914ecb and 6a6ef122647e14d36f2a2be24431cdc1f19d46ed
Fixes a regression with centered user field text and the way badges wrap on mobile
Before
After

UX: mobile user card fixes

---

app/assets/stylesheets/common/base/discourse.scss
themes/horizon/scss/main.scss

This regressed recently. We need to make sure non-ember pages have a minimum left/right padding, otherwise content is hugging the device edges.
Before: 
After:

UX: Fix padding for no-ember pages

---

themes/horizon/javascripts/discourse/components/card/topic-activity-column.gjs
themes/horizon/test/acceptance/topic-activity-column-test.gjs

For these steps:
* In Horizon, create a topic.
* You’ll notice that the topic card has the OP name.
* Make an edit to the OP after the edit grace period.
You would see no username under the topic title. This is because
we were saying that if the topic bump date was after the last post
date, then we should never show any edit details.
However this didn't handle the common case of posting then editing
soon after.
Now in this commit, if the difference is < 1 day, we still show
the same username.
A proper fix would be to know the bumped_at_user then we can tell
if the user is the same as the last poster, but that is more complex
to do.

FIX: Horizon topic activity username sometimes blank

---

app/assets/javascripts/discourse/app/services/composer.js

This function is effectively now a no-op after https://github.com/discourse/discourse/pull/34867 which removes the ability to set up the jquery-based autocomplete library in composer. Floatkit autocomplete handles its own cancel & close functionality via its component lifecycle. 
This will be ok to merge once all calls to this function from supported plugins are removed.

DEV: remove composer service closeAutocomplete function

---

app/assets/javascripts/discourse/app/templates/review-index.gjs
app/assets/javascripts/discourse/app/templates/review-show.gjs
app/assets/javascripts/discourse/app/templates/review.gjs
app/assets/stylesheets/common/base/reviewables.scss
config/locales/client.en.yml

This PR adds the "Back to queue" link for the new review UI, while reserving the old header for the old UI index and show.
**Old review UI index:**
**Old review UI show:**
**New review UI index:**
**New review UI show:**

DEV: Show back to queue link in header on new review UI

---

themes/horizon/scss/nav-pills.scss

The clickable card layout used in the boxes+featured categories has a higher z-index, which conflicts with the sticky list-controls in Horizon. Hence the latter needs this increase.

UX: Horizon > increase z-index for list controls

---

app/assets/stylesheets/common/base/_topic-list.scss

Context:
https://meta.discourse.org/t/large-emojis-in-post-preview-of-bookmarks/296815
| BC | AC |
| <img width="2244" height="834" alt="CleanShot 2025-09-23 at 12 01 59@2x" src="https://github.com/user-attachments/assets/7edcff24-7e3d-400e-9345-51a7f6e5c9d6" /> | <img width="2244" height="834" alt="CleanShot 2025-09-23 at 12 02 20@2x" src="https://github.com/user-attachments/assets/215894f4-2cd6-4654-9c3e-d2d634603e60" /> |

UX: fix emoji size in post excerpts

---

app/assets/javascripts/discourse/app/components/post/menu/buttons/add-translation.gjs
app/assets/javascripts/discourse/tests/integration/components/post/menu/buttons/add-translation-test.gjs
spec/system/post_translation_spec.rb

The Add Translation post menu will now always be shown. Previously, it immediately opened the translation composer when there are 0 translations.

FIX: Always show the translation post menu

---

plugins/discourse-calendar/assets/javascripts/discourse/components/admin-holidays-list-item.gjs
plugins/discourse-calendar/assets/javascripts/discourse/components/admin-holidays-list.gjs
plugins/discourse-calendar/assets/javascripts/discourse/components/region-input.js
plugins/discourse-calendar/assets/javascripts/discourse/templates/admin-plugins/show/discourse-calendar-holidays.gjs
plugins/discourse-calendar/assets/stylesheets/common/discourse-calendar-holidays.scss
plugins/discourse-calendar/config/locales/client.en.yml
plugins/discourse-calendar/test/javascripts/acceptance/admin-holidays-test.js
plugins/discourse-calendar/test/javascripts/integration/components/admin-holidays-list-item-test.gjs

Followup a5730bfe2ff603ee892952e5dd94fe81f9fb164b
Apply admin table UI guidelines, and convert
AdminHolidaysListItem to a glimmer component.

UX: Use admin table classes for Calendar Holidays list

---

app/models/site.rb
spec/models/site_spec.rb

When the site setting `login_required` is enabled, the signup page should include links to the TOS and Privacy Policy.

FIX: Include TOS and Privacy Policy URLs in signup when login required

---

app/assets/stylesheets/common/base/topic-footer.scss

This PR adjusts some topic-timeline changes from https://github.com/discourse/discourse/pull/34886 which introduced a bug where the timeline moved to the bottom of the post stream before it should.
|Before|After|
|--|--|
|<img width="1982" height="1866" alt="CleanShot 2025-09-24 at 10 49 18@2x" src="https://github.com/user-attachments/assets/afd97830-4a84-4877-81e8-114e897ee329" />|<img width="1986" height="1862" alt="CleanShot 2025-09-24 at 10 48 42@2x" src="https://github.com/user-attachments/assets/faac2daf-1ccf-400e-99a1-112b21493b89" />|

UX: Timeline fix

---

app/assets/javascripts/discourse/app/components/bookmark-menu.gjs
app/assets/stylesheets/common/components/dropdown-menu.scss

The bookmark modal should not be using `btn-danger`, as these classes are reserved for buttons following a standard format ("normal buttons"). This can cause issues when a theme styles these classes, which then conflicts with the display in a list.
This commit removes the class and replaces it with a `--danger` modifier that can be used in any dropdown.
| BC | AC |
| <img width="734" height="326" alt="CleanShot 2025-09-23 at 20 59 03@2x" src="https://github.com/user-attachments/assets/bd771908-8de2-4cfd-a648-fa880d330a09" /> | <img width="598" height="316" alt="CleanShot 2025-09-23 at 21 05 35@2x" src="https://github.com/user-attachments/assets/aba3877c-1aba-4fb3-935d-a31ec99e5fb6" /> |

UX: replace btn-danger with modifier class for bookmark dropdown

---

app/assets/javascripts/discourse/app/components/post/small-action.gjs
app/assets/javascripts/discourse/tests/integration/components/post/small-action-test.gjs

Renamed `username` to `who` and updated the component to use `@args.post` consistently, improving the semantic clarity of the code. Adjusted related logic to reflect the new naming convention and fixed references accordingly.
Enhanced test coverage for custom components with new assertions verifying parameter bindings (e.g., `who`, `created_at`, `path`).
Backport from https://github.com/discourse/discourse/pull/34928

DEV: Change arguments provided to `PostSmallAction` custom components

---

app/assets/javascripts/discourse/app/deprecation-workflow.js
app/assets/javascripts/discourse/app/lib/search.js

Refactor `recentSearches` logic in `search.js` to replace the deprecated `without` with a `filter` function. Update deprecation workflow to log usages of the `discourse.native-array-extensions.without` method.

DEV: Replace `without` usage and update deprecation handling

---

plugins/chat/spec/system/page_objects/pages/user_preferences_chat.rb
spec/support/system_helpers.rb

Clicking save and then immediately refreshing can cause a race condition, because the refresh may cancel the ajax request which is performing the save.
Instead, we can wait for the built-in refresh, which will only be triggered after the save is completed successfully.

DEV: Resolve flaky chat preferences spec

---

app/assets/stylesheets/common/components/more-topics.scss

Noticed we're using some custom hover effect on these buttons, which we don't use with similar nav areas such as main nav or user page nav.
✅  <img width="1684" height="288" alt="CleanShot 2025-09-19 at 09 46 37@2x" src="https://github.com/user-attachments/assets/f6615210-411b-4f14-96a1-7119642dc2c1" />
✅  <img width="1060" height="210" alt="CleanShot 2025-09-19 at 09 46 56@2x" src="https://github.com/user-attachments/assets/933f4a9d-1e42-4b19-b69c-ece8114b46c0" />
❌ <img width="938" height="226" alt="CleanShot 2025-09-19 at 09 47 20@2x" src="https://github.com/user-attachments/assets/74ca8a0d-f82a-445d-a503-8f4082fa8417" />

UX: remove hover effect (not consistent)

---

app/assets/javascripts/discourse/app/deprecation-workflow.js
app/assets/javascripts/discourse/tests/unit/deprecation-workflow-test.js

Refine `shouldThrow` behavior by replacing `includeUnhandled` parameter with `includeUnsilenced` to improve clarity and semantics. Adjust logic to integrate unsilenced deprecations handling, ensuring more precise deprecation workflows.

DEV: Ensure unsilenced deprecations raise errors in core tests

---

plugins/discourse-assign/spec/plugin_spec.rb
plugins/discourse-calendar/spec/models/calendar_event_spec.rb
plugins/discourse-calendar/spec/serializers/discourse_post_event/post_serializer_spec.rb
plugins/discourse-policy/spec/serializers/post_serializer_spec.rb
plugins/discourse-reactions/spec/requests/custom_reactions_controller_spec.rb
plugins/discourse-solved/spec/integration/solved_spec.rb

…and remove a stray `puts` in a spec

DEV: Fix PostDestroyer deprecations in specs

---

plugins/discourse-ai/assets/stylesheets/modules/ai-bot/common/ai-discobot-discoveries.scss

| 📸 | before | after |
|----|---|---|
| narrow desktop |  <img width="786" height="967" alt="Screenshot 2025-09-26 at 4 53 36 PM" src="https://github.com/user-attachments/assets/639b4e01-6822-4599-9985-a75d82be05d6" /> | <img width="787" height="968" alt="Screenshot 2025-09-26 at 4 54 32 PM" src="https://github.com/user-attachments/assets/1c2d9c96-43a4-47ac-9a99-52a9f40023a9" /> |
| wide desktop | <img width="1075" height="1013" alt="Screenshot 2025-09-26 at 4 53 14 PM" src="https://github.com/user-attachments/assets/66c21999-9113-44a5-9369-9ea6c06a6159" /> | <img width="1075" height="1013" alt="Screenshot 2025-09-26 at 4 54 54 PM" src="https://github.com/user-attachments/assets/4adf580c-dd93-43ee-89bc-28a5a92f1f8a" /> |

UX: Use search padding for discoveries

---

app/assets/javascripts/admin/addon/routes/admin.js
app/assets/javascripts/discourse/app/components/header/contents.gjs
app/assets/javascripts/discourse/app/components/header/icons.gjs
app/assets/javascripts/discourse/app/components/welcome-banner.gjs
app/assets/javascripts/discourse/tests/acceptance/search-mobile-test.js
app/assets/javascripts/discourse/tests/acceptance/search-test.js
app/assets/javascripts/discourse/tests/integration/components/header-icons-test.gjs
spec/system/search_spec.rb

1. We are adding more pages that do not need a Welcome banner to be shown on:
- a sign up journey
2. Hides Header search on a `/search` page (avoids duplicate inputs)

FIX: escapes `account-created` routes on Welcome banner page visibility

---

app/assets/stylesheets/common/components/d-breadcrumbs.scss

We need to allow the breadcrumbs to wrap properly, to account for deep navigation layers on mobile
| BC | AC |
| <img width="668" height="842" alt="CleanShot 2025-09-26 at 08 17 42@2x" src="https://github.com/user-attachments/assets/e38400eb-b8a2-48f2-be69-089ad392d144" /> | <img width="668" height="842" alt="CleanShot 2025-09-26 at 08 17 59@2x" src="https://github.com/user-attachments/assets/b061f82a-433a-409e-903e-90b2fde35a39" /> |

UX: prevent icon and text wrapping in breadcrumb

---

themes/horizon/scss/hiddenstuff.scss

Fix for https://github.com/discourse/discourse/pull/34714
Which made the new-topic-button reappear on desktop.

UX: fix new topic btn reappearing in Horizon

---

app/services/discourse_id/register.rb
spec/services/discourse_id/register_spec.rb

This ensures the automated registration process for #discourse-id
correctly supports Discourse running in a subfolder by adding a "path"
value in the data sent.
Internal ref - t/161934/15
Related - https://github.com/discourse/discourse-login/pull/74

FIX: add support for subfolder in discourse-id registration

---

plugins/discourse-ai/assets/javascripts/discourse/components/ai-translations.gjs
plugins/discourse-ai/assets/stylesheets/modules/translation/common/admin-translations.scss

Adds variables for chart colors so we can support dark mode 
Before:
After:

UX: improve AI translations chart colors in dark mode

---

app/assets/javascripts/discourse/package.json
pnpm-lock.yaml

Follow-up to e81e3bebffcd89117a24b47fd2d8f128e44f3b4d, which missed the version in the nested package.

DEV: Fully revert `@swc/core` to 1.13.5

---

plugins/discourse-reactions/spec/system/page_objects/post_reactions_button.rb
plugins/discourse-reactions/spec/system/page_objects/post_reactions_list.rb
plugins/discourse-reactions/spec/system/reactions_post_spec.rb
spec/system/page_objects/components/base.rb

Covers default reactions, `discourse_reactions_experimental_allow_any_emoji`,
`discourse_reactions_enabled_reactions`, and interaction with the `emoji_deny_list` setting from core.

DEV: Add basic system spec for discourse-reaction on post

---

lib/version.rb

Version bumps for main: v3.6.0.beta1, v3.6.0.beta2-latest

---

lib/version.rb

Version bump for stable: v3.5.1

---

spec/rails_helper.rb

In the `SiteSettingExtension`, when calling `SiteSetting.send(:setting_name, value)`,
if the setting counts as a global one, we add it to the list of hidden
and shadowed site settings in memory. However, when using the
`global_setting` helper in specs, we were not cleaning up these
overrides after the spec finished, leading to potential flakiness
in tests that rely on the visibility of site settings.
The fix is to just remove the setting from the hidden and shadowed
list after the spec is done.

DEV: Properly clean up global setting overrides in specs

---

app/assets/javascripts/discourse/app/controllers/signup.js
app/assets/javascripts/discourse/app/routes/login.js
app/assets/javascripts/discourse/app/routes/signup.js
app/assets/javascripts/discourse/app/templates/login.gjs
app/assets/javascripts/discourse/app/templates/signup.gjs

Loading the controller and its template causes a request to `hp.json`, which can then trigger a race condition with `/session/csrf.json` if an external auth is in-progress. This commit updates the redirect behavior so that the the `beforeModel` hook never resolves, and therefore the transition remains in a pending state until the redirect updates `window.location`.
This also improves the UX, since there is no need for a flash of a loading spinner. Instead, the normal route transition animation will keep running until the redirect is complete.

DEV: Skip loading login/signup controller when redirecting

---

app/assets/javascripts/discourse/tests/integration/components/select-kit/single-select-test.gjs
app/assets/javascripts/select-kit/addon/components/select-kit/select-kit-row.gjs
app/assets/stylesheets/common/select-kit/select-kit.scss

If you row has `disabled` as property it will be used to disable the row.

DEV: adds support for disabled in select-kit

---

bin/turbo_rspec
lib/turbo_tests/flaky/failed_example.rb

1. Use relative paths instead of absolute. This will make the commands portable to other machines, and matches the out-the-box behavior of the regular rspec command
2. Strip out some 'infrastructure' ENV and params from the rerun_command, so that it's easier to copy/paste and run locally

DEV: Improve turbo_rspec and flaky-test output

---

app/assets/javascripts/admin/addon/components/admin-config-areas/components.gjs
app/assets/javascripts/admin/addon/components/themes-grid-card.gjs

These are needed for adding custom elements to the page and targeting specific themes with CSS in plugins.

DEV: Add plugin outlet to components config area and data-theme-id to themes grid

---

app/assets/stylesheets/common/base/topic-post.scss

This PR fixes a hover background effect on the like button when a double button is present showing a number of likes, along with the like action.
|before|after|
|--|--|
|<img width="1796" height="849" alt="CleanShot 2025-09-30 at 14 03 38@2x" src="https://github.com/user-attachments/assets/53d0d151-b438-403d-a1aa-0e7a0b1efd59" />|<img width="1963" height="1082" alt="CleanShot 2025-09-30 at 14 04 55@2x" src="https://github.com/user-attachments/assets/396fdfbc-32e1-4b78-87d4-6a57dd9f9e56" />|

UX: Fix hover effect on heart icon in double-like button

---

spec/system/admin_color_palette_config_area_spec.rb

This resolves the flaky spec we're seeing on `system/admin_color_palette_config_area_spec.rb:157`
`--bisect` minimal repro was:
```
bin/rspec './spec/system/admin_color_palette_config_area_spec.rb[1:9,1:12]' --tag ~type:multisite --order random:3906
```

DEV: Clear caches properly in admin_color_palette_config_area_spec

---

plugins/discourse-calendar/assets/javascripts/discourse/components/full-calendar.gjs
plugins/discourse-calendar/assets/stylesheets/common/full-calendar-ext.scss

We have limited space and removing the time in this case allows to have more space for the text of the event.

UX: hide time in month view on mobile

---

app/models/bookmark.rb
plugins/chat/spec/system/bookmark_message_spec.rb
spec/models/bookmark_spec.rb
spec/requests/users_controller_spec.rb

Prior to this fix a user could delete a chat bookmark but the notification reminder if it had already fired would still show in notifications.

FIX: notification reminder is deleted with bookmark

---

app/jobs/scheduled/run_problem_checks.rb
app/models/problem_check.rb
spec/jobs/run_problem_checks_spec.rb

Scheduled problem checks without trackers weren't being run. This is because we directly tried to look for trackers instead of going through the checks.

FIX: Run scheduled problem checks even when no tracker exists yet

---

plugins/chat/assets/javascripts/discourse/components/chat/header/icon.gjs
plugins/chat/spec/system/message_notifications_mobile_spec.rb
plugins/chat/spec/system/navigation_spec.rb
plugins/chat/spec/system/page_objects/chat/chat.rb
plugins/chat/spec/system/page_objects/chat/components/footer.rb
plugins/chat/test/javascripts/components/chat-header-icon-test.gjs

In order to reduce visual noise in mobile view, there is no need to show chat icon in header, once user has already chat open.
|Before|After|
|---|---|
|<img width="456" height="199" alt="Screenshot 2025-10-01 at 17 16 29" src="https://github.com/user-attachments/assets/6d124a79-4a0a-4edd-913a-43a0cfa05623" />|<img width="442" height="198" alt="Screenshot 2025-10-01 at 17 16 06" src="https://github.com/user-attachments/assets/052a2f78-574e-4d35-aff4-264f54f2fb15" />|

FIX: hides redundant chat icon on mobile chat routes

---

app/controllers/metadata_controller.rb
spec/requests/metadata_controller_spec.rb

Added subfolder support for #discourse-id automated registration in 874c875e02794aa but we were missing returning the "path" in the response from the "discourse_id_challenge".
This ensures we also return the "path" field in the challenge so it can properly be validatated by id.discourse.com.
Internal ref - t/161934/21

FIX: discourse_id_challenge response when using subfolder

---

app/services/video_conversion/aws_media_convert_adapter.rb
spec/services/video_conversion/aws_media_convert_adapter_spec.rb

When authenticating to aws mediaconvert we need to also allow the use of
`iam_profile` and not just assume `s3_access_key_id` and
`s3_secret_access_key` are being used.

FIX: Allow aws mediaconvert to use iam profile

---

app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.gjs
spec/system/editing_sidebar_categories_navigation_spec.rb
spec/system/page_objects/modals/sidebar_edit_categories.rb

Followup 9a9a0e5c1b39956b97b2188df7c79a07cf07b4ef
The "Show more" button in the sidebar categories modal was not working
when a root-level category had more than 5 subcategories (e.g., a
grandparent category with 6+ parent categories as children).
Root-level categories have `parent_category_id: undefined`, but the
`findPartialCategories` function was checking `categoriesById.has(id)`
before creating "Show more" buttons. Since `undefined` is never in the
categoriesById map, no button was created for root-level pagination.
The fix adds special handling for `undefined` parent IDs throughout the
component, treating root-level categories as a valid case for pagination.

FIX: Show more button now loads additional root-level subcategories

---

lib/auth/default_current_user_provider.rb
spec/lib/auth/default_current_user_provider_spec.rb

Before this change, impersonating a user would result in that user's `last_seen_at` being updated. This PR fixes that for the new impersonation feature gated behind the `experimental_impersonation` site setting.
The old impersonation feature that logs in as the impersonated user has a completely separate code path. If we decide to backport this change it will be in a separate PR.

FIX: Don't update last_seen_at when impersonating a user

---

app/assets/javascripts/discourse/app/controllers/preferences/security.js
app/assets/javascripts/discourse/app/routes/preferences/security.js
app/assets/javascripts/discourse/app/templates/preferences/security.gjs
app/assets/javascripts/discourse/tests/acceptance/user-preferences-security-test.js
app/controllers/users_controller.rb
app/models/user.rb
config/locales/client.en.yml
spec/requests/users_controller_spec.rb

We have this slightly awkward UX on the <kbd>Preferences</kbd> > <kbd>Security</kbd> page, where we offer to remove the password from an account if it has other means of signing in. You need to first click a cryptic <kbd>Show</kbd> button which may or may not lead you to the button you want. This button loads the associated accounts so we can evaluate whether to show the <kbd>Remove password</kbd> button or not.
This PR loads that data when entering the route, so that we can just show the button up-front. If removing password isn't possible, the button is disabled and shows an explainer underneath.
**Before:**
**After:**

UX: Show remove password button without suspense

---

lib/action_dispatch/session/discourse_cookie_store.rb
spec/integration/discourse_cookie_store_spec.rb

Reverts discourse/discourse#34639
We understood the main culprit for cookie overflows was storing `destination_url` in the session, so we don’t really need that debug code anymore.

Revert "DEV: Debug cookie overflows"

---

app/assets/javascripts/admin/addon/components/color-input.gjs
app/assets/javascripts/discourse/app/components/edit-category-general.gjs
app/assets/javascripts/discourse/app/controllers/edit-category/tabs.js
app/assets/javascripts/discourse/app/form-kit/components/fk/form.gjs
app/assets/javascripts/discourse/app/templates/edit-category/tabs.gjs
app/models/category.rb
config/locales/client.en.yml
spec/models/category_spec.rb
spec/system/edit_category_general_spec.rb
spec/system/page_objects/components/form_kit.rb
spec/system/page_objects/pages/category.rb

This PR reworks the validation and handling of color pickers in the category edit page so they're simpler and more predictable. In particular:
* It no longer attempts to "autocomplete" 3-digits hex values to the equivalent 6-digits format -- we now accept both 3 and 6 digits formats
* It no longer disables the save button if the input color value is invalid. The save button is always clickable, and if the admin attempts to save with an invalid color value, the form will display errors explaining which input is invalid and what's wrong with the color value
Internal topic: t/163062.

FIX: Allow saving category when color attributes are 3-digits hex

---

app/assets/javascripts/discourse/app/components/anonymous-topic-footer-buttons.gjs
app/assets/javascripts/discourse/app/components/topic-footer-buttons.gjs
app/assets/javascripts/discourse/app/lib/register-topic-footer-button.js
app/assets/javascripts/discourse/app/lib/register-topic-footer-dropdown.js

Some topic buttons or dropdown items are displayed conditionally based on the viewport width (e.g. via `site.mobileView`). Previously, the topic-footer-button API wasn't designed to support autotracking. Instead, it required plugins to pass a list of string-based keys, which it then attached to a computed property.
This commit updates it to be fully 'autotracking-native'. Old dependent keys are accessed internally via `.get()` to maintain backwards compatibility.
Now, dependencies on autotrackable property like `site.mobileView` will be reflected in real-time.

UX: Update topic-footer buttons automatically when viewport changes

---

app/assets/javascripts/admin/addon/components/schema-setting/types/tags.gjs

Allows for surfacing all tags by adding a `every_tag` option to the `tags` property. This value is then passed to the `everyTag` option on the `TagChooser` component
Demo:
```yml
type: objects
client: true
default: "[]"
schema:
name: "state"
properties:
tags:
type: tags
min: 2
every_tag: true
```
Defaults to `false` (current behavior)

DEV: Add `every_tag` option to tags schema-setting

---

app/assets/javascripts/admin/addon/components/simple-list.gjs

Found while working on a customization. Caused a floating integer in the admin settings.
Before:
After:

FIX: Removes debugging line

---

app/assets/javascripts/discourse/app/templates/preferences/security.gjs

Needed to implement additional/replacement instructions or functionality where the password change buttons usually live.

Add a plugin outlet after preferences > security password section

---

app/services/video_conversion/aws_media_convert_adapter.rb
spec/services/video_conversion/aws_media_convert_adapter_spec.rb

In the aws_media_convert_adapter we were referencing
`SiteSetting.s3_upload_bucket` but that can be empty on some instances,
so we need to use the `SiteSetting.Upload.s3_upload_bucket` version,
which should always have a value when using s3.
This follows a similar pattern we used previously for other s3 related
settings.

DEV: Favor Upload.s3_upload_bucket for mediaconvert

---

app/assets/stylesheets/common/base/lightbox.scss

When quoting an image it is easy to accidentally select the image caption as it appears on hovering the image. Because of this the caption text also appears underneath the image (within the quote).
Making the caption text unselectable when hovering the image solves this.

UX: make lightbox hover caption unselectable

---

app/assets/javascripts/discourse/app/components/post.gjs
app/assets/javascripts/discourse/app/components/post/menu.gjs
app/assets/javascripts/discourse/app/components/post/menu/buttons/replies.gjs

This prevents users from clicking multiple times and causing replies to be shown more than once while expansion is in progress.

FIX: Disable replies button until replies are loaded

---

config/application.rb
lib/freedom_patches/message_pack_extensions.rb

This PR uses MessagePack instead of JSON for serializing our cookies.
MessagePack is almost as fast as Marshal but without the security issues. It’s also able to serialize more objects than JSON (like Time, Symbol, etc.). As it’s a binary format, it takes less space than JSON, sometimes half less. Finally, MessagePack isn’t Ruby-specific and implementations exist in every existing language.
Regarding the cookies Discourse is using, we can see a small improvement on the `_forum_session` one when it’s almost empty (around 2%), but the more things are put into it, the more we’ll see savings. For the `_t` cookie, we’re saving around 20% for free.

DEV: Serialize cookies using MessagePack

---

Gemfile
Gemfile.lock

This significantly simplifies and speeds up using the ruby LSP in development, since a separate 'composed bundle' is no longer needed.

DEV: Add ruby-lsp to development gems

---

app/assets/javascripts/discourse/app/helpers/category-link.js
app/assets/javascripts/select-kit/addon/components/category-chooser.js

The badge in `CategoryChooser` is incorrectly showing the child category badge when displaying both parent and child as the selected option. This was already fixed for cases where the `ancestors` option is passed to `categoryBadgeHTML` in the category link helper.
Updating the option within CategoryChooser fixes this issue, but I have also added a fallback fix for any other components that still use the recursive option.
_Note: as part of #26638 the preferred approach was to pass `ancestors: category.predecessors` in place of `recursive: true`. That way reducing multiple calls to `Category.findById` at the component level when looping through category parents. We may want to completely remove the recursive option in the future but leaving it be for now._
The category emojis are working …

FIX: pass ancestor data to category badge helper

---

app/assets/javascripts/discourse/app/components/d-modal.gjs
app/assets/javascripts/discourse/app/components/modal/bookmark.gjs

Buttons can only have 1 declarative class, not a combination. 
| BC | AC |
| <img width="666" height="1214" alt="CleanShot 2025-10-03 at 07 24 22@2x" src="https://github.com/user-attachments/assets/448e4193-13a9-483c-80f7-6acc86e253d0" /> | <img width="666" height="1214" alt="CleanShot 2025-10-03 at 07 23 56@2x" src="https://github.com/user-attachments/assets/45c3abe5-a59f-4cf5-ad5e-19efb4721023" /> |

FIX: double declarative button class names

---

spec/rails_helper.rb
spec/support/discourse_connect_support_helpers.rb
spec/system/discourse_connect_provider_spec.rb
spec/system/discourse_connect_spec.rb

- Rename SSO -> DiscourseConnect. SSO is the general term for all external login methods. DiscourseConnect is the name for this protocol
- Allocate different IP for each parallel spec environment, so they don't clash. This will resolve some flaky specs we're seeing
- Only bind to localhost. No need to make this available from other machines

DEV: Improvements to DiscourseConnect spec helpers

---

app/assets/javascripts/discourse/app/lib/composer-video-thumbnail-uppy.js
app/assets/javascripts/discourse/app/lib/uppy/composer-upload.js

In the current version of DiscourseHub on iOS 26, video uploads are stalling.
This is because the video thumbnail generation code relies on video events
and it looks like iOS 26 webviews are not firing those events.
This may require a fix in DiscourseHub, but in the meantime, we need to
tighten the logic in thumbnail generation here.

DEV: Bypass video thumbnail generation if events don't fire

---

config/locales/server.en.yml

The settings text doesn't reflect reality, as wide rectangular logo isn't a requirement. A square one works just as well, and is recommended to optimise header space.

UX: update the copy in settings for the mobile logo

---

app/views/exceptions/not_found.html.erb

Removing the subtitle until we can make a better distinction between "page not found" and "no access" 404 pages.

UX: remove subtitle from 404 page

---

config/site_settings.yml

In our efforts to increase the signal-to-noise ratio and discoverability of site settings, we're hiding overly technical settings that few users override.

DEV: Hide overly technical image compression settings

---

plugins/discourse-subscriptions/assets/javascripts/discourse/connectors/user-main-nav/billing.gjs

This PR is a revised version from #35199 , aim at fixing a visual mismatch in buttons at user-menu.
Thanks to @tyb-talks for suggestions.

FIX: Fix an issue in user-menu-billing to align with other buttons

---

app/assets/javascripts/admin/addon/components/modal/penalize-user.gjs
spec/system/flagging_post_spec.rb

In a [previous refactor](https://github.com/discourse/discourse/pull/22960) we lost the functionality that creates a reviewable when a moderator immediately takes action on a post and chooses to either silence or suspend a user.
Fix the broken JavaScript reference and add a system test for regression safety.

FIX: Ensure a reviewable is created when directly taking action on user (stable)

---

lib/plugin/instance.rb
spec/lib/plugin/instance_spec.rb

The `discourse_owned?` method in `lib/plugin/instance.rb` was calling `.split` on `parsed_commit_url.path` without checking if the path could be nil. This caused a 500 error on `/admin/plugins` when any plugin had a commit URL that parsed successfully but returned a nil path (e.g., plugins without a git remote configured).
Added a nil check for `parsed_commit_url.path` to gracefully handle this edge case and prevent the crash. Also added a test case to verify the method returns false when the parsed URL has a nil path.

FIX: crash in Admin::PluginsController when plugin has nil commit URL path

---

app/serializers/category_badge_serializer.rb
spec/serializers/topic_list_serializer_spec.rb
spec/system/category_localizations_spec.rb

There's a bug now that translated category names get replaced. This applies to logged in users on sites where `SiteSetting.content_localization_enabled` and `SiteSetting.lazy_load_categories_groups` are enabled for the user.
The fix here has been checked for N+1s, and it was covered before in https://github.com/discourse/discourse/pull/34212/files#diff-a064afa7c610321917d3edfd0a462197d7cb3b76191552dfb770f3b9fb11db18.
See sidebar category name getting replaced:
https://github.com/user-attachments/assets/f8ac44a4-a134-44d0-8f07-b44d711eda32
Sidebar category name and visiting /latest does not get replaced.
https://github.com/user-attachments/assets/437ff0c9-65e2-4d65-873c-fc77da4a1a33

FIX: Navigating via topic filters should not untranslate a category name

---

spec/system/category_localizations_spec.rb

https://github.com/discourse/discourse/pull/35211 introduced some specs that require selecting parent category dropdown, but there are two dropdowns and spec is confoosed.

FIX: Spec ambiguity when selecting category dropdowns

---

plugins/discourse-ai/discourse_automation/llm_triage.rb
plugins/discourse-ai/lib/automation.rb
plugins/discourse-ai/spec/lib/discourse_automation/llm_triage_spec.rb

When a post is edited, avoid re-flagging it if there’s already a flag pending in the review queue. This prevents duplicate triage runs and reduces unnecessary processing.

FIX: Skip triage on edits when unhandled flags exist

---

plugins/discourse-calendar/app/controllers/discourse_post_event/events_controller.rb
plugins/discourse-calendar/app/views/discourse_post_event/events/index.ics.erb
plugins/discourse-calendar/config/routes.rb
plugins/discourse-calendar/lib/discourse_post_event/event_finder.rb
plugins/discourse-calendar/spec/lib/discourse_post_event/event_finder_spec.rb
plugins/discourse-calendar/spec/requests/events_controller_spec.rb

Reverts the removal of this from https://github.com/discourse/discourse-calendar/pull/231. This opens up the relative url `/discourse-post-event/events.ics` for access to an ical formatted response.
We also make available the `order` argument for this endpoint which defaults to ascending order if there is no value or invalid value passed. This maintains existing behaviour while allowing for users to specify that they want most recent events first.
Downloaded an ical file from the endpoint and imported into my local laptop's calendar.

DEV: add ical format response for discourse-post-events index route

---

app/services/video_conversion/aws_media_convert_adapter.rb
spec/services/video_conversion/aws_media_convert_adapter_spec.rb

When converting videos if there is an error we need some more details to
debug what is going on.

DEV: Add more logging to mediaconvert check_status

---

app/assets/javascripts/admin/addon/components/site-setting.gjs

Minor follow-up to 759fc04
This 👁️  button was missing the btn-default class, so it wasn't getting a border-radius
Before
After

UX: add missing button class to secret toggle

---

app/assets/javascripts/discourse/app/components/modal/bookmark.gjs

On mobile, the bookmark modal uses the DMenu setup, which has cancel/save actions in the header. So we should hide the footer actions.
| BC | AC |
| <img width="658" height="1142" alt="CleanShot 2025-10-03 at 13 10 04@2x" src="https://github.com/user-attachments/assets/2e886369-9f1f-4332-a00a-812dcaf6205e" /> | <img width="660" height="1142" alt="CleanShot 2025-10-03 at 13 09 09@2x" src="https://github.com/user-attachments/assets/50527750-9252-40d7-aed3-8dd65a9df77c" /> | 
Desktop stays the same:

UX: remove double actions buttons in bookmark modal on mobile

---

app/assets/stylesheets/common/base/new-user.scss

The inbox element was missing some styling, probably due to a conversion from selectkit to DMenu in https://github.com/discourse/discourse/pull/33889
This commit address the UX issue reported in https://meta.discourse.org/t/inbox-multi-word-styling-issue/384870

UX: user inbox styling fix

---

app/assets/javascripts/discourse/app/components/sidebar/edit-navigation-menu/categories-modal.gjs
app/assets/javascripts/discourse/app/lib/utilities.js
spec/system/editing_sidebar_categories_navigation_spec.rb

**Disclaimer: I used AI quite heavily to fix and describe the issue here, but I hopefully have simplified and explained things enough so it's not a huge chore to review.**
This commit fixes an issue where the category modal would not show
a "Show more" button in the scenario below:
* Grandparent category
* Parent category 1
* Child category 1-1
* Child category 1-2
* Child category 1-3
* Child category 1-4
* Child category 5-5
* [ Show more ]
* Parent category 2
* Parent category 3
* Parent category 4
* Parent category 5
* Child category 5-1
* Child category 5-2
* Child category 5-3
* Child category 5-4
* Child category 5-5
* [ Show more ]
* [ Show more ] <-- This button was missing
* (Not yet loaded) Parent category 6
In this case, we _knew_ that grandparent had more categories to load. …

FIX: Another category modal partial loading edge case

---

db/migrate/20251008050307_delete_post_localizations_with_links.rb
lib/cooked_post_processor.rb
lib/cooked_processor_mixin.rb
plugins/discourse-ai/lib/translation/localized_cooked_post_processor.rb
plugins/discourse-ai/lib/translation/post_localizer.rb
plugins/discourse-ai/spec/jobs/regular/detect_translate_post_spec.rb
plugins/discourse-ai/spec/lib/translation/post_localizer_spec.rb

This change ensures that oneboxes, lightboxes are correctly generated for localized posts.
The `PostLocalizer` was using `PrettyText.cook` directly, which does not perform all the necessary post-processing steps, such as onebox generation.
This commit introduces a new `LocalizedCookedPostProcessor` class that is responsible for post-processing the cooked HTML of translated posts. This new class reuses the `CookedProcessorMixin` to gain access to the `post_process_oneboxes` method. The `PostLocalizer` is updated to use this new processor, ensuring that oneboxes are correctly generated in the translated content.

FEATURE: Add oneboxes and lightboxes to localized posts

---

plugins/automation/admin/assets/javascripts/admin/components/fields/da-pms-field.gjs
plugins/automation/admin/assets/javascripts/admin/components/fields/da-post-field.gjs

These automation setups use a full-fledged editor where you can toggle between markdown and rich editing, but they don't have the logic that the composer comes with, that decides whether to display the preview or not, so it still (incorrectly) displays the preview when rich editor mode is selected.
This PR restricts the editor to just rich mode, and disables the preview.

DEV: Simplify automation post editors

---

app/assets/stylesheets/common/components/load-more.scss

Based on reports in https://meta.discourse.org/t/users-list-only-partial/368793/17, some users may have issues with the LoadMore sentinel not triggering the intersection observer to load more elements due to it's `0px` height. I've not been able to reproduce this consistently myself, but adding the `1px` height appears to resolve the issue. This is an invisible element so it should not cause any inconsistency visually other than possibly causing a marginally earlier load of more elements.
Credit to `cathys` on Meta Discourse for the fix.

FIX: add minimal load-more-sentinel height

---

spec/system/composer/category_templates_spec.rb

Not using capybara matchers leads to flaky tests

DEV: Fix system tests not relying on capybara matchers

---

plugins/automation/lib/discourse_automation/event_handlers.rb
plugins/discourse-ai/config/locales/client.en.yml
plugins/discourse-ai/discourse_automation/llm_tagger.rb
plugins/discourse-ai/spec/lib/automation/llm_tagger_spec.rb

I want to use the AI llm_tagger script on https://discover.discourse.com, but in order to do this the automation needs to be allowed to run on posts created by the system user. 
To accomplish this, I've added the ability for scripts to add a `allow_system_posts` setting. Existing scripts will still ignore system posts, but this allows script authors to add a setting to opt-in to processing them.

DEV: Allow AI tagging automation to tag system-created topics
